import type { VictoriaRow } from '../victoriaBundleShared';

type MovieSeriesSeed = {
  en: string;
  ru: string;
  uk: string;
  es: string;
  meaningRu: string;
  meaningUk: string;
  meaningEs: string;
  contextRu: string;
  contextUk: string;
  contextEs: string;
  exampleEn: string;
  exampleRu: string;
  exampleUk: string;
  exampleEs: string;
  level?: string;
};

const SEEDS: MovieSeriesSeed[] = [
  { en: "What's going on?", ru: 'что происходит?', uk: 'що відбувається?', es: '¿qué está pasando?', meaningRu: 'что происходит', meaningUk: 'що відбувається', meaningEs: 'qué está pasando', contextRu: 'когда герой не понимает ситуацию и просит быстро объяснить', contextUk: 'коли герой не розуміє ситуацію й просить швидко пояснити', contextEs: 'cuando alguien no entiende la situación y pide una explicación rápida', exampleEn: "What's going on? Why is everyone running?", exampleRu: 'Что происходит? Почему все бегут?', exampleUk: 'Що відбувається? Чому всі біжать?', exampleEs: '¿Qué está pasando? ¿Por qué todos corren?' },
  { en: 'You got this.', ru: 'ты справишься', uk: 'ти впораєшся', es: 'tú puedes', meaningRu: 'ты справишься', meaningUk: 'ти впораєшся', meaningEs: 'tú puedes con esto', contextRu: 'когда нужно поддержать человека перед сложным моментом', contextUk: 'коли треба підтримати людину перед складним моментом', contextEs: 'para animar a alguien antes de algo difícil', exampleEn: 'Take a breath. You got this.', exampleRu: 'Вдохни. Ты справишься.', exampleUk: 'Вдихни. Ти впораєшся.', exampleEs: 'Respira. Tú puedes.' },
  { en: "I'm out.", ru: 'я пас / я ухожу', uk: 'я пас / я йду', es: 'me voy / yo paso', meaningRu: 'я пас или я выхожу из ситуации', meaningUk: 'я пас або я виходжу із ситуації', meaningEs: 'me retiro o no participo', contextRu: 'когда герой отказывается участвовать или резко завершает разговор', contextUk: 'коли герой відмовляється брати участь або різко завершує розмову', contextEs: 'cuando alguien se niega a participar o termina la conversación', exampleEn: "If this is your plan, I'm out.", exampleRu: 'Если это твой план, я пас.', exampleUk: 'Якщо це твій план, я пас.', exampleEs: 'Si ese es tu plan, yo paso.' },
  { en: "Don't mess this up.", ru: 'не испорти это', uk: 'не зіпсуй це', es: 'no arruines esto', meaningRu: 'не испорти важный шанс или план', meaningUk: 'не зіпсуй важливий шанс або план', meaningEs: 'no arruines una oportunidad o un plan importante', contextRu: 'перед рискованной сценой, встречей или решающим действием', contextUk: 'перед ризикованою сценою, зустріччю або вирішальною дією', contextEs: 'antes de una escena, reunión o acción decisiva', exampleEn: "This is our only chance. Don't mess this up.", exampleRu: 'Это наш единственный шанс. Не испорти всё.', exampleUk: 'Це наш єдиний шанс. Не зіпсуй усе.', exampleEs: 'Es nuestra única oportunidad. No lo arruines.' },
  { en: "That's not the point.", ru: 'дело не в этом', uk: 'річ не в цьому', es: 'ese no es el punto', meaningRu: 'главная мысль в другом', meaningUk: 'головна думка в іншому', meaningEs: 'lo importante es otra cosa', contextRu: 'когда разговор уходит в сторону и нужно вернуть фокус', contextUk: 'коли розмова йде вбік і треба повернути фокус', contextEs: 'cuando la conversación se desvía y hay que volver al tema', exampleEn: "That's not the point. The point is that you lied.", exampleRu: 'Дело не в этом. Дело в том, что ты соврал.', exampleUk: 'Річ не в цьому. Річ у тому, що ти збрехав.', exampleEs: 'Ese no es el punto. El punto es que mentiste.' },
  { en: 'Are you kidding me?', ru: 'ты издеваешься?', uk: 'ти знущаєшся?', es: '¿me estás tomando el pelo?', meaningRu: 'ты серьёзно или это шутка', meaningUk: 'ти серйозно чи це жарт', meaningEs: 'si esto es serio o una broma', contextRu: 'для удивления, раздражения или неверия', contextUk: 'для здивування, роздратування або недовіри', contextEs: 'para mostrar sorpresa, molestia o incredulidad', exampleEn: 'Are you kidding me? We just fixed it.', exampleRu: 'Ты издеваешься? Мы только что это починили.', exampleUk: 'Ти знущаєшся? Ми щойно це полагодили.', exampleEs: '¿Me estás tomando el pelo? Acabamos de arreglarlo.' },
  { en: 'Give me a break.', ru: 'да ладно / хватит уже', uk: 'та годі / досить уже', es: 'dame un respiro / no fastidies', meaningRu: 'перестань давить, жаловаться или говорить ерунду', meaningUk: 'перестань тиснути, скаржитися або казати дурниці', meaningEs: 'deja de presionar, quejarte o decir tonterías', contextRu: 'когда герой устал от обвинений или абсурда', contextUk: 'коли герой втомився від звинувачень або абсурду', contextEs: 'cuando alguien se cansa de acusaciones o absurdos', exampleEn: 'Give me a break. I did everything I could.', exampleRu: 'Да ладно тебе. Я сделал всё, что мог.', exampleUk: 'Та годі. Я зробив усе, що міг.', exampleEs: 'Dame un respiro. Hice todo lo que pude.' },
  { en: 'I owe you one.', ru: 'я у тебя в долгу', uk: 'я тобі винен', es: 'te debo una', meaningRu: 'я благодарен и отплачу позже', meaningUk: 'я вдячний і віддячу пізніше', meaningEs: 'te agradezco esto y te lo devolveré', contextRu: 'после помощи, спасения или услуги', contextUk: 'після допомоги, порятунку або послуги', contextEs: 'después de recibir ayuda o un favor', exampleEn: 'Thanks for covering for me. I owe you one.', exampleRu: 'Спасибо, что прикрыл меня. Я у тебя в долгу.', exampleUk: 'Дякую, що прикрив мене. Я тобі винен.', exampleEs: 'Gracias por cubrirme. Te debo una.' },
  { en: 'We need to talk.', ru: 'нам нужно поговорить', uk: 'нам треба поговорити', es: 'tenemos que hablar', meaningRu: 'нужен серьёзный разговор', meaningUk: 'потрібна серйозна розмова', meaningEs: 'hace falta una conversación seria', contextRu: 'фраза перед важным признанием, конфликтом или решением', contextUk: 'фраза перед важливим зізнанням, конфліктом або рішенням', contextEs: 'antes de una confesión, conflicto o decisión importante', exampleEn: 'We need to talk. Not here.', exampleRu: 'Нам нужно поговорить. Не здесь.', exampleUk: 'Нам треба поговорити. Не тут.', exampleEs: 'Tenemos que hablar. No aquí.' },
  { en: "It's complicated.", ru: 'всё сложно', uk: 'усе складно', es: 'es complicado', meaningRu: 'ситуация непростая и требует объяснения', meaningUk: 'ситуація непроста й потребує пояснення', meaningEs: 'la situación no es simple y necesita explicación', contextRu: 'когда короткий ответ не передаёт всей истории', contextUk: 'коли коротка відповідь не передає всієї історії', contextEs: 'cuando una respuesta corta no cuenta toda la historia', exampleEn: "Are you two together? It's complicated.", exampleRu: 'Вы вместе? Всё сложно.', exampleUk: 'Ви разом? Усе складно.', exampleEs: '¿Están juntos? Es complicado.' },
  { en: 'Long story short.', ru: 'короче говоря', uk: 'коротше кажучи', es: 'en resumen', meaningRu: 'коротко пересказать длинную историю', meaningUk: 'коротко переказати довгу історію', meaningEs: 'resumir una historia larga', contextRu: 'когда герой пропускает детали и переходит к сути', contextUk: 'коли герой пропускає деталі й переходить до суті', contextEs: 'cuando alguien salta detalles y va al punto', exampleEn: 'Long story short, we lost the car.', exampleRu: 'Короче говоря, мы потеряли машину.', exampleUk: 'Коротше кажучи, ми загубили машину.', exampleEs: 'En resumen, perdimos el coche.' },
  { en: "For what it's worth.", ru: 'если это что-то значит', uk: 'якщо це щось значить', es: 'por si sirve de algo', meaningRu: 'мягко добавить мнение, поддержку или признание', meaningUk: 'мʼяко додати думку, підтримку або визнання', meaningEs: 'añadir una opinión, apoyo o confesión con suavidad', contextRu: 'когда говорящий не уверен, поможет ли его слова', contextUk: 'коли мовець не впевнений, чи допоможуть його слова', contextEs: 'cuando alguien no sabe si sus palabras ayudarán', exampleEn: "For what it's worth, I believe you.", exampleRu: 'Если это что-то значит, я тебе верю.', exampleUk: 'Якщо це щось значить, я тобі вірю.', exampleEs: 'Por si sirve de algo, te creo.' },
  { en: "I didn't see that coming.", ru: 'вот это поворот', uk: 'ось це поворот', es: 'no me lo esperaba', meaningRu: 'я не ожидал такого развития событий', meaningUk: 'я не очікував такого розвитку подій', meaningEs: 'no esperaba ese giro', contextRu: 'после неожиданного признания, поворота или финала', contextUk: 'після несподіваного зізнання, повороту або фіналу', contextEs: 'después de una confesión, giro o final inesperado', exampleEn: "He was the spy? I didn't see that coming.", exampleRu: 'Он был шпионом? Вот это поворот.', exampleUk: 'Він був шпигуном? Ось це поворот.', exampleEs: '¿Él era el espía? No me lo esperaba.' },
  { en: "Don't take it personally.", ru: 'не принимай на свой счёт', uk: 'не сприймай це на свій рахунок', es: 'no te lo tomes como algo personal', meaningRu: 'это не нападение на тебя лично', meaningUk: 'це не напад на тебе особисто', meaningEs: 'no es un ataque personal', contextRu: 'перед критикой, отказом или неприятной правдой', contextUk: 'перед критикою, відмовою або неприємною правдою', contextEs: 'antes de una crítica, rechazo o verdad incómoda', exampleEn: "Don't take it personally, but this plan won't work.", exampleRu: 'Не принимай на свой счёт, но этот план не сработает.', exampleUk: 'Не сприймай це на свій рахунок, але цей план не спрацює.', exampleEs: 'No te lo tomes como algo personal, pero este plan no funcionará.' },
  { en: "I'm just saying.", ru: 'я просто говорю', uk: 'я просто кажу', es: 'solo digo', meaningRu: 'я высказываю мысль без давления', meaningUk: 'я висловлюю думку без тиску', meaningEs: 'expreso una idea sin presionar', contextRu: 'после спорной фразы, чтобы смягчить тон', contextUk: 'після спірної фрази, щоб помʼякшити тон', contextEs: 'después de una frase discutible para suavizar el tono', exampleEn: "I'm just saying, maybe we should wait.", exampleRu: 'Я просто говорю: может, нам стоит подождать.', exampleUk: 'Я просто кажу: може, нам варто зачекати.', exampleEs: 'Solo digo que quizá deberíamos esperar.' },
  { en: 'That makes no sense.', ru: 'это не имеет смысла', uk: 'це не має сенсу', es: 'eso no tiene sentido', meaningRu: 'это нелогично или не сходится', meaningUk: 'це нелогічно або не сходиться', meaningEs: 'no es lógico o no encaja', contextRu: 'когда объяснение, план или улика не работают', contextUk: 'коли пояснення, план або доказ не працюють', contextEs: 'cuando una explicación, plan o pista no encaja', exampleEn: 'That makes no sense. He was with us all night.', exampleRu: 'Это не имеет смысла. Он был с нами всю ночь.', exampleUk: 'Це не має сенсу. Він був з нами всю ніч.', exampleEs: 'Eso no tiene sentido. Estuvo con nosotros toda la noche.' },
  { en: 'You crossed a line.', ru: 'ты перешёл черту', uk: 'ти перейшов межу', es: 'cruzaste una línea', meaningRu: 'ты сделал что-то недопустимое', meaningUk: 'ти зробив щось неприпустиме', meaningEs: 'hiciste algo inaceptable', contextRu: 'когда нарушены границы, доверие или правила', contextUk: 'коли порушено межі, довіру або правила', contextEs: 'cuando se rompen límites, confianza o reglas', exampleEn: 'You crossed a line when you read my messages.', exampleRu: 'Ты перешёл черту, когда прочитал мои сообщения.', exampleUk: 'Ти перейшов межу, коли прочитав мої повідомлення.', exampleEs: 'Cruzaste una línea al leer mis mensajes.' },
  { en: "I've got your back.", ru: 'я тебя прикрою', uk: 'я тебе прикрию', es: 'te cubro / estoy contigo', meaningRu: 'я поддержу и защищу тебя', meaningUk: 'я підтримаю й захищу тебе', meaningEs: 'te apoyaré y protegeré', contextRu: 'в сценах дружбы, команды или опасного плана', contextUk: 'у сценах дружби, команди або небезпечного плану', contextEs: 'en escenas de amistad, equipo o un plan peligroso', exampleEn: "Go in first. I've got your back.", exampleRu: 'Заходи первым. Я тебя прикрою.', exampleUk: 'Заходь першим. Я тебе прикрию.', exampleEs: 'Entra primero. Yo te cubro.' },
  { en: 'Stay out of this.', ru: 'не вмешивайся', uk: 'не втручайся', es: 'no te metas en esto', meaningRu: 'это не твоё дело или не твой конфликт', meaningUk: 'це не твоя справа або не твій конфлікт', meaningEs: 'esto no es asunto tuyo o no es tu conflicto', contextRu: 'когда герой отталкивает свидетеля, друга или союзника', contextUk: 'коли герой відштовхує свідка, друга або союзника', contextEs: 'cuando alguien aparta a un testigo, amigo o aliado', exampleEn: 'Stay out of this. It is between me and him.', exampleRu: 'Не вмешивайся. Это между мной и ним.', exampleUk: 'Не втручайся. Це між мною і ним.', exampleEs: 'No te metas en esto. Es entre él y yo.' },
  { en: "I'm working on it.", ru: 'я над этим работаю', uk: 'я над цим працюю', es: 'estoy en ello', meaningRu: 'я уже занимаюсь этой задачей или проблемой', meaningUk: 'я вже займаюся цим завданням або проблемою', meaningEs: 'ya estoy ocupándome de esa tarea o problema', contextRu: 'когда героя торопят, а решение ещё не готово', contextUk: 'коли героя кваплять, а рішення ще не готове', contextEs: 'cuando presionan a alguien y la solución aún no está lista', exampleEn: "Can you fix it? I'm working on it.", exampleRu: 'Можешь это починить? Я работаю над этим.', exampleUk: 'Можеш це полагодити? Я працюю над цим.', exampleEs: '¿Puedes arreglarlo? Estoy en ello.' },
  { en: "It's not over yet.", ru: 'это ещё не конец', uk: 'це ще не кінець', es: 'esto aún no ha terminado', meaningRu: 'история или борьба продолжается', meaningUk: 'історія або боротьба триває', meaningEs: 'la historia o la lucha continúa', contextRu: 'перед продолжением конфликта, матчем-реваншем или финальным шансом', contextUk: 'перед продовженням конфлікту, реваншем або фінальним шансом', contextEs: 'antes de continuar un conflicto, revancha o última oportunidad', exampleEn: "It's not over yet. We still have one move.", exampleRu: 'Это ещё не конец. У нас всё ещё есть один ход.', exampleUk: 'Це ще не кінець. У нас ще є один хід.', exampleEs: 'Esto aún no ha terminado. Nos queda una jugada.' },
  { en: 'Let me handle this.', ru: 'дай мне с этим разобраться', uk: 'дай мені з цим розібратися', es: 'déjame encargarme de esto', meaningRu: 'я возьму ситуацию под контроль', meaningUk: 'я візьму ситуацію під контроль', meaningEs: 'yo me encargaré de la situación', contextRu: 'когда герой просит доверить ему разговор, конфликт или задачу', contextUk: 'коли герой просить довірити йому розмову, конфлікт або завдання', contextEs: 'cuando alguien pide que le dejen resolver algo', exampleEn: 'Let me handle this. I know what to say.', exampleRu: 'Дай мне с этим разобраться. Я знаю, что сказать.', exampleUk: 'Дай мені з цим розібратися. Я знаю, що сказати.', exampleEs: 'Déjame encargarme de esto. Sé qué decir.' },
  { en: 'What do you want from me?', ru: 'чего ты от меня хочешь?', uk: 'чого ти від мене хочеш?', es: '¿qué quieres de mí?', meaningRu: 'я не понимаю твоих требований или давления', meaningUk: 'я не розумію твоїх вимог або тиску', meaningEs: 'no entiendo tus exigencias o tu presión', contextRu: 'в эмоциональном споре, когда герой загнан в угол', contextUk: 'в емоційній суперечці, коли героя загнали в кут', contextEs: 'en una discusión emocional cuando alguien se siente acorralado', exampleEn: 'What do you want from me? I told you the truth.', exampleRu: 'Чего ты от меня хочешь? Я сказал тебе правду.', exampleUk: 'Чого ти від мене хочеш? Я сказав тобі правду.', exampleEs: '¿Qué quieres de mí? Te dije la verdad.' },
  { en: 'I had no choice.', ru: 'у меня не было выбора', uk: 'у мене не було вибору', es: 'no tenía opción', meaningRu: 'другого выхода не было', meaningUk: 'іншого виходу не було', meaningEs: 'no había otra salida', contextRu: 'после сложного решения, предательства или жертвы', contextUk: 'після складного рішення, зради або жертви', contextEs: 'después de una decisión difícil, traición o sacrificio', exampleEn: 'I had no choice. They would have found you.', exampleRu: 'У меня не было выбора. Они бы нашли тебя.', exampleUk: 'У мене не було вибору. Вони б знайшли тебе.', exampleEs: 'No tenía opción. Te habrían encontrado.' },
  { en: 'This is on me.', ru: 'это моя вина / я беру это на себя', uk: 'це моя провина / я беру це на себе', es: 'esto es culpa mía / yo me hago responsable', meaningRu: 'я принимаю ответственность', meaningUk: 'я беру відповідальність', meaningEs: 'acepto la responsabilidad', contextRu: 'когда герой признаёт ошибку перед командой или близким человеком', contextUk: 'коли герой визнає помилку перед командою або близькою людиною', contextEs: 'cuando alguien admite un error ante el equipo o alguien cercano', exampleEn: 'This is on me. I should have checked.', exampleRu: 'Это моя вина. Мне нужно было проверить.', exampleUk: 'Це моя провина. Мені треба було перевірити.', exampleEs: 'Esto es culpa mía. Debí comprobarlo.' },
  { en: 'You have no idea.', ru: 'ты даже не представляешь', uk: 'ти навіть не уявляєш', es: 'no tienes ni idea', meaningRu: 'ты не понимаешь масштаб ситуации', meaningUk: 'ти не розумієш масштаб ситуації', meaningEs: 'no entiendes la magnitud de la situación', contextRu: 'для сильного эмоционального акцента перед объяснением', contextUk: 'для сильного емоційного акценту перед поясненням', contextEs: 'para dar énfasis emocional antes de explicar algo', exampleEn: 'You have no idea what I went through.', exampleRu: 'Ты даже не представляешь, через что я прошёл.', exampleUk: 'Ти навіть не уявляєш, через що я пройшов.', exampleEs: 'No tienes ni idea de lo que pasé.' },
  { en: "I'm done.", ru: 'с меня хватит', uk: 'з мене досить', es: 'ya terminé / ya basta', meaningRu: 'я больше не хочу продолжать', meaningUk: 'я більше не хочу продовжувати', meaningEs: 'ya no quiero seguir', contextRu: 'когда герой завершает спор, отношения или участие', contextUk: 'коли герой завершує суперечку, стосунки або участь', contextEs: 'cuando alguien termina una discusión, relación o participación', exampleEn: "I'm done. I can't do this anymore.", exampleRu: 'С меня хватит. Я больше не могу.', exampleUk: 'З мене досить. Я більше не можу.', exampleEs: 'Ya basta. No puedo seguir con esto.' },
  { en: "Don't push me.", ru: 'не дави на меня', uk: 'не тисни на мене', es: 'no me presiones', meaningRu: 'не заставляй меня реагировать жёстче', meaningUk: 'не змушуй мене реагувати жорсткіше', meaningEs: 'no me obligues a reaccionar con más dureza', contextRu: 'в напряжённой сцене перед конфликтом', contextUk: 'у напруженій сцені перед конфліктом', contextEs: 'en una escena tensa antes de un conflicto', exampleEn: "Don't push me. I said no.", exampleRu: 'Не дави на меня. Я сказал нет.', exampleUk: 'Не тисни на мене. Я сказав ні.', exampleEs: 'No me presiones. Dije que no.' },
  { en: 'I mean it.', ru: 'я серьёзно', uk: 'я серйозно', es: 'lo digo en serio', meaningRu: 'это не шутка и не пустые слова', meaningUk: 'це не жарт і не порожні слова', meaningEs: 'no es una broma ni palabras vacías', contextRu: 'после предупреждения, обещания или признания', contextUk: 'після попередження, обіцянки або зізнання', contextEs: 'después de una advertencia, promesa o confesión', exampleEn: 'Leave now. I mean it.', exampleRu: 'Уходи сейчас. Я серьёзно.', exampleUk: 'Йди зараз. Я серйозно.', exampleEs: 'Vete ahora. Lo digo en serio.' },
  { en: 'Back off.', ru: 'отвали / отойди', uk: 'відчепись / відійди', es: 'aléjate / déjame en paz', meaningRu: 'перестань приближаться или давить', meaningUk: 'перестань наближатися або тиснути', meaningEs: 'deja de acercarte o presionar', contextRu: 'короткая резкая фраза в конфликте или опасности', contextUk: 'коротка різка фраза в конфлікті або небезпеці', contextEs: 'frase corta y fuerte en conflicto o peligro', exampleEn: 'Back off. She said no.', exampleRu: 'Отойди. Она сказала нет.', exampleUk: 'Відійди. Вона сказала ні.', exampleEs: 'Aléjate. Ella dijo que no.' },
  { en: 'Is that supposed to be funny?', ru: 'это должно быть смешно?', uk: 'це мало бути смішно?', es: '¿se supone que eso es gracioso?', meaningRu: 'шутка прозвучала плохо или обидно', meaningUk: 'жарт прозвучав погано або образливо', meaningEs: 'la broma sonó mal u ofensiva', contextRu: 'когда герой холодно отвечает на неудачную шутку', contextUk: 'коли герой холодно відповідає на невдалий жарт', contextEs: 'cuando alguien responde fríamente a una broma mala', exampleEn: 'Is that supposed to be funny? Because it is not.', exampleRu: 'Это должно быть смешно? Потому что не смешно.', exampleUk: 'Це мало бути смішно? Бо не смішно.', exampleEs: '¿Se supone que eso es gracioso? Porque no lo es.' },
  { en: "I'll make it up to you.", ru: 'я заглажу вину', uk: 'я загладжу провину', es: 'te lo compensaré', meaningRu: 'я компенсирую ошибку или обиду', meaningUk: 'я компенсую помилку або образу', meaningEs: 'compensaré mi error o el daño', contextRu: 'после срыва планов, ошибки или обещания', contextUk: 'після зриву планів, помилки або обіцянки', contextEs: 'después de arruinar planes, cometer un error o fallar una promesa', exampleEn: "I'm sorry. I'll make it up to you.", exampleRu: 'Прости. Я заглажу вину.', exampleUk: 'Вибач. Я загладжу провину.', exampleEs: 'Lo siento. Te lo compensaré.' },
  { en: "You're better than this.", ru: 'ты выше этого', uk: 'ти вищий за це', es: 'eres mejor que esto', meaningRu: 'ты способен поступить достойнее', meaningUk: 'ти здатен вчинити гідніше', meaningEs: 'puedes actuar de una forma más digna', contextRu: 'когда герой удерживает другого от плохого поступка', contextUk: 'коли герой стримує іншого від поганого вчинку', contextEs: 'cuando alguien intenta impedir que otro haga algo malo', exampleEn: "Don't do it. You're better than this.", exampleRu: 'Не делай этого. Ты выше этого.', exampleUk: 'Не роби цього. Ти вищий за це.', exampleEs: 'No lo hagas. Eres mejor que esto.' },
  { en: 'I can explain.', ru: 'я могу объяснить', uk: 'я можу пояснити', es: 'puedo explicarlo', meaningRu: 'дай мне шанс объяснить ситуацию', meaningUk: 'дай мені шанс пояснити ситуацію', meaningEs: 'dame la oportunidad de explicar la situación', contextRu: 'после того, как героя застали в странной или плохой ситуации', contextUk: 'після того, як героя застали в дивній або поганій ситуації', contextEs: 'cuando alguien es descubierto en una situación rara o mala', exampleEn: 'Wait, I can explain.', exampleRu: 'Подожди, я могу объяснить.', exampleUk: 'Зачекай, я можу пояснити.', exampleEs: 'Espera, puedo explicarlo.' },
  { en: 'This changes everything.', ru: 'это всё меняет', uk: 'це все змінює', es: 'esto lo cambia todo', meaningRu: 'новая информация полностью меняет ситуацию', meaningUk: 'нова інформація повністю змінює ситуацію', meaningEs: 'la nueva información cambia toda la situación', contextRu: 'после важного открытия, улики или признания', contextUk: 'після важливого відкриття, доказу або зізнання', contextEs: 'después de un descubrimiento, pista o confesión importante', exampleEn: 'If he is alive, this changes everything.', exampleRu: 'Если он жив, это всё меняет.', exampleUk: 'Якщо він живий, це все змінює.', exampleEs: 'Si está vivo, esto lo cambia todo.' },
  { en: "We're running out of time.", ru: 'у нас заканчивается время', uk: 'у нас закінчується час', es: 'se nos acaba el tiempo', meaningRu: 'времени почти не осталось', meaningUk: 'часу майже не лишилося', meaningEs: 'queda muy poco tiempo', contextRu: 'в сценах дедлайна, погони, спасения или финального выбора', contextUk: 'у сценах дедлайну, погоні, порятунку або фінального вибору', contextEs: 'en escenas de plazo, persecución, rescate o decisión final', exampleEn: "We're running out of time. Move!", exampleRu: 'У нас заканчивается время. Быстрее!', exampleUk: 'У нас закінчується час. Швидше!', exampleEs: 'Se nos acaba el tiempo. ¡Muévete!' },
  { en: 'I need a minute.', ru: 'мне нужна минутка', uk: 'мені потрібна хвилина', es: 'necesito un minuto', meaningRu: 'мне нужно короткое время, чтобы прийти в себя или подумать', meaningUk: 'мені потрібен короткий час, щоб оговтатися або подумати', meaningEs: 'necesito un momento para calmarme o pensar', contextRu: 'после шока, новости или эмоционального удара', contextUk: 'після шоку, новини або емоційного удару', contextEs: 'después de un shock, noticia o golpe emocional', exampleEn: 'I need a minute. This is a lot.', exampleRu: 'Мне нужна минутка. Это слишком много.', exampleUk: 'Мені потрібна хвилина. Це забагато.', exampleEs: 'Necesito un minuto. Es demasiado.' },
  { en: "Don't play dumb.", ru: 'не притворяйся дураком', uk: 'не прикидайся дурнем', es: 'no te hagas el tonto', meaningRu: 'ты понимаешь, о чём речь', meaningUk: 'ти розумієш, про що йдеться', meaningEs: 'entiendes perfectamente de qué se habla', contextRu: 'когда герой подозревает ложь или уклонение', contextUk: 'коли герой підозрює брехню або ухиляння', contextEs: 'cuando alguien sospecha mentira o evasión', exampleEn: "Don't play dumb. You know where it is.", exampleRu: 'Не притворяйся дураком. Ты знаешь, где это.', exampleUk: 'Не прикидайся дурнем. Ти знаєш, де це.', exampleEs: 'No te hagas el tonto. Sabes dónde está.' },
  { en: 'I know what I saw.', ru: 'я знаю, что видел', uk: 'я знаю, що бачив', es: 'sé lo que vi', meaningRu: 'я уверен в своём свидетельстве', meaningUk: 'я впевнений у своєму свідченні', meaningEs: 'estoy seguro de lo que presencié', contextRu: 'когда другие сомневаются в герое или называют его слова невозможными', contextUk: 'коли інші сумніваються в герої або називають його слова неможливими', contextEs: 'cuando otros dudan de alguien o llaman imposible su relato', exampleEn: 'I know what I saw, and it was not human.', exampleRu: 'Я знаю, что видел, и это было не человек.', exampleUk: 'Я знаю, що бачив, і це була не людина.', exampleEs: 'Sé lo que vi, y no era humano.' },
  { en: "You can't be serious.", ru: 'ты не можешь говорить серьёзно', uk: 'ти не можеш казати це серйозно', es: 'no puedes hablar en serio', meaningRu: 'это звучит невероятно или абсурдно', meaningUk: 'це звучить неймовірно або абсурдно', meaningEs: 'suena increíble o absurdo', contextRu: 'реакция на рискованный план, признание или требование', contextUk: 'реакція на ризикований план, зізнання або вимогу', contextEs: 'reacción ante un plan, confesión o exigencia arriesgada', exampleEn: "You can't be serious. That is impossible.", exampleRu: 'Ты не можешь говорить серьёзно. Это невозможно.', exampleUk: 'Ти не можеш казати це серйозно. Це неможливо.', exampleEs: 'No puedes hablar en serio. Eso es imposible.' },
  { en: 'Let it go.', ru: 'отпусти / забудь', uk: 'відпусти / забудь', es: 'déjalo ir / olvídalo', meaningRu: 'перестань держаться за обиду, спор или прошлое', meaningUk: 'перестань триматися за образу, суперечку або минуле', meaningEs: 'deja de aferrarte a una ofensa, discusión o al pasado', contextRu: 'когда герой просит прекратить конфликт или obsession', contextUk: 'коли герой просить припинити конфлікт або навʼязливу думку', contextEs: 'cuando alguien pide dejar un conflicto u obsesión', exampleEn: 'Let it go. It was years ago.', exampleRu: 'Отпусти это. Это было много лет назад.', exampleUk: 'Відпусти це. Це було багато років тому.', exampleEs: 'Déjalo ir. Fue hace años.' },
  { en: "I'm not buying it.", ru: 'я в это не верю', uk: 'я в це не вірю', es: 'no me lo creo', meaningRu: 'твоя версия звучит неправдоподобно', meaningUk: 'твоя версія звучить неправдоподібно', meaningEs: 'tu versión no suena creíble', contextRu: 'когда герой не принимает объяснение или алиби', contextUk: 'коли герой не приймає пояснення або алібі', contextEs: 'cuando alguien no acepta una explicación o coartada', exampleEn: "Nice story, but I'm not buying it.", exampleRu: 'Хорошая история, но я в это не верю.', exampleUk: 'Гарна історія, але я в це не вірю.', exampleEs: 'Buena historia, pero no me la creo.' },
  { en: "It's worth a shot.", ru: 'стоит попробовать', uk: 'варто спробувати', es: 'vale la pena intentarlo', meaningRu: 'попытка имеет смысл, даже если успех не гарантирован', meaningUk: 'спроба має сенс, навіть якщо успіх не гарантований', meaningEs: 'vale la pena intentarlo aunque no esté garantizado', contextRu: 'перед рискованной, но разумной попыткой', contextUk: 'перед ризикованою, але розумною спробою', contextEs: 'antes de un intento arriesgado pero razonable', exampleEn: "It might fail, but it's worth a shot.", exampleRu: 'Может не сработать, но стоит попробовать.', exampleUk: 'Може не спрацювати, але варто спробувати.', exampleEs: 'Puede fallar, pero vale la pena intentarlo.' },
  { en: "What's the catch?", ru: 'в чём подвох?', uk: 'у чому підступ?', es: '¿cuál es la trampa?', meaningRu: 'какое скрытое условие или проблема', meaningUk: 'яка прихована умова або проблема', meaningEs: 'qué condición oculta o problema hay', contextRu: 'когда предложение звучит слишком хорошо', contextUk: 'коли пропозиція звучить надто добре', contextEs: 'cuando una oferta suena demasiado buena', exampleEn: 'Free tickets? What is the catch?', exampleRu: 'Бесплатные билеты? В чём подвох?', exampleUk: 'Безкоштовні квитки? У чому підступ?', exampleEs: '¿Entradas gratis? ¿Cuál es la trampa?' },
  { en: "I'll take my chances.", ru: 'я рискну', uk: 'я ризикну', es: 'me arriesgaré', meaningRu: 'я осознанно принимаю риск', meaningUk: 'я свідомо приймаю ризик', meaningEs: 'acepto el riesgo conscientemente', contextRu: 'когда герой выбирает опасный путь вместо ожидания', contextUk: 'коли герой обирає небезпечний шлях замість очікування', contextEs: 'cuando alguien elige un camino peligroso en vez de esperar', exampleEn: 'If that is the only way, I will take my chances.', exampleRu: 'Если это единственный путь, я рискну.', exampleUk: 'Якщо це єдиний шлях, я ризикну.', exampleEs: 'Si es la única forma, me arriesgaré.' },
  { en: 'Suit yourself.', ru: 'как хочешь', uk: 'як хочеш', es: 'como quieras', meaningRu: 'делай по-своему, я не буду спорить', meaningUk: 'роби по-своєму, я не сперечатимуся', meaningEs: 'hazlo a tu manera, no discutiré', contextRu: 'сухая реакция, когда герой перестаёт убеждать', contextUk: 'суха реакція, коли герой перестає переконувати', contextEs: 'respuesta seca cuando alguien deja de convencer', exampleEn: "Suit yourself. I'm leaving anyway.", exampleRu: 'Как хочешь. Я всё равно ухожу.', exampleUk: 'Як хочеш. Я все одно йду.', exampleEs: 'Como quieras. Yo me voy igual.' },
  { en: "Don't make this harder.", ru: 'не усложняй', uk: 'не ускладнюй', es: 'no hagas esto más difícil', meaningRu: 'не добавляй напряжение, драму или проблемы', meaningUk: 'не додавай напруги, драми або проблем', meaningEs: 'no añadas tensión, drama o problemas', contextRu: 'когда ситуация уже тяжёлая и эмоции мешают', contextUk: 'коли ситуація вже важка й емоції заважають', contextEs: 'cuando la situación ya es difícil y las emociones estorban', exampleEn: "Please don't make this harder than it has to be.", exampleRu: 'Пожалуйста, не усложняй больше, чем нужно.', exampleUk: 'Будь ласка, не ускладнюй більше, ніж треба.', exampleEs: 'Por favor, no lo hagas más difícil de lo necesario.' },
  { en: 'We had a deal.', ru: 'у нас была сделка', uk: 'у нас була угода', es: 'teníamos un trato', meaningRu: 'ты нарушил договорённость', meaningUk: 'ти порушив домовленість', meaningEs: 'rompiste el acuerdo', contextRu: 'когда один персонаж напоминает о соглашении', contextUk: 'коли один персонаж нагадує про угоду', contextEs: 'cuando alguien recuerda un acuerdo previo', exampleEn: 'We had a deal. You promised.', exampleRu: 'У нас была сделка. Ты обещал.', exampleUk: 'У нас була угода. Ти обіцяв.', exampleEs: 'Teníamos un trato. Lo prometiste.' },
  { en: "I'm not going anywhere.", ru: 'я никуда не уйду', uk: 'я нікуди не піду', es: 'no me voy a ninguna parte', meaningRu: 'я останусь рядом или не отступлю', meaningUk: 'я залишуся поруч або не відступлю', meaningEs: 'me quedaré o no me rendiré', contextRu: 'для поддержки, верности или упрямого сопротивления', contextUk: 'для підтримки, вірності або впертого опору', contextEs: 'para mostrar apoyo, lealtad o resistencia', exampleEn: "I'm not going anywhere. We face this together.", exampleRu: 'Я никуда не уйду. Мы встретим это вместе.', exampleUk: 'Я нікуди не піду. Ми зустрінемо це разом.', exampleEs: 'No me voy a ninguna parte. Lo enfrentamos juntos.' },
  { en: 'You were right.', ru: 'ты был прав', uk: 'ти мав рацію', es: 'tenías razón', meaningRu: 'я признаю, что твоя оценка была верной', meaningUk: 'я визнаю, що твоя оцінка була правильною', meaningEs: 'reconozco que tu evaluación era correcta', contextRu: 'после ошибки, открытия или запоздалого понимания', contextUk: 'після помилки, відкриття або запізнілого розуміння', contextEs: 'después de un error, descubrimiento o comprensión tardía', exampleEn: 'You were right. I should have listened.', exampleRu: 'Ты был прав. Мне нужно было послушать.', exampleUk: 'Ти мав рацію. Мені треба було послухати.', exampleEs: 'Tenías razón. Debí escucharte.' },
  { en: 'I messed up.', ru: 'я облажался', uk: 'я облажався', es: 'la arruiné / metí la pata', meaningRu: 'я совершил ошибку', meaningUk: 'я зробив помилку', meaningEs: 'cometí un error', contextRu: 'простое признание вины без долгих оправданий', contextUk: 'просте визнання провини без довгих виправдань', contextEs: 'admisión simple de culpa sin excusas largas', exampleEn: 'I messed up, and I am sorry.', exampleRu: 'Я облажался, и мне жаль.', exampleUk: 'Я облажався, і мені шкода.', exampleEs: 'Metí la pata, y lo siento.' },
  { en: "It won't happen again.", ru: 'это больше не повторится', uk: 'це більше не повториться', es: 'no volverá a pasar', meaningRu: 'я обещаю не повторять ошибку', meaningUk: 'я обіцяю не повторювати помилку', meaningEs: 'prometo no repetir el error', contextRu: 'после извинения, провала или предупреждения', contextUk: 'після вибачення, провалу або попередження', contextEs: 'después de una disculpa, fracaso o advertencia', exampleEn: "It won't happen again. You have my word.", exampleRu: 'Это больше не повторится. Даю слово.', exampleUk: 'Це більше не повториться. Даю слово.', exampleEs: 'No volverá a pasar. Te doy mi palabra.' },
  { en: 'I need you to trust me.', ru: 'мне нужно, чтобы ты мне доверял', uk: 'мені потрібно, щоб ти мені довіряв', es: 'necesito que confíes en mí', meaningRu: 'сейчас важно поверить мне без полной картины', meaningUk: 'зараз важливо повірити мені без повної картини', meaningEs: 'ahora necesito que me creas sin tener toda la información', contextRu: 'перед опасным планом, тайной или срочным решением', contextUk: 'перед небезпечним планом, таємницею або терміновим рішенням', contextEs: 'antes de un plan peligroso, secreto o decisión urgente', exampleEn: 'I need you to trust me and run.', exampleRu: 'Мне нужно, чтобы ты доверился мне и бежал.', exampleUk: 'Мені потрібно, щоб ти довірився мені й біг.', exampleEs: 'Necesito que confíes en mí y corras.' },
  { en: "You're hiding something.", ru: 'ты что-то скрываешь', uk: 'ти щось приховуєш', es: 'estás ocultando algo', meaningRu: 'я чувствую, что ты не говоришь всю правду', meaningUk: 'я відчуваю, що ти не кажеш усієї правди', meaningEs: 'siento que no dices toda la verdad', contextRu: 'в сценах подозрения, допроса или отношений', contextUk: 'у сценах підозри, допиту або стосунків', contextEs: 'en escenas de sospecha, interrogatorio o relaciones', exampleEn: "You're hiding something. I can see it.", exampleRu: 'Ты что-то скрываешь. Я это вижу.', exampleUk: 'Ти щось приховуєш. Я це бачу.', exampleEs: 'Estás ocultando algo. Lo noto.' },
  { en: 'This stays between us.', ru: 'это останется между нами', uk: 'це залишиться між нами', es: 'esto queda entre nosotros', meaningRu: 'это секрет, который нельзя раскрывать', meaningUk: 'це секрет, який не можна розкривати', meaningEs: 'es un secreto que no debe salir', contextRu: 'после признания, тайной сделки или опасной информации', contextUk: 'після зізнання, таємної угоди або небезпечної інформації', contextEs: 'después de una confesión, trato secreto o información peligrosa', exampleEn: 'This stays between us. No one else can know.', exampleRu: 'Это останется между нами. Никто больше не должен знать.', exampleUk: 'Це залишиться між нами. Ніхто більше не має знати.', exampleEs: 'Esto queda entre nosotros. Nadie más puede saberlo.' },
  { en: "I'll be right back.", ru: 'я сейчас вернусь', uk: 'я зараз повернуся', es: 'vuelvo enseguida', meaningRu: 'я уйду ненадолго и скоро вернусь', meaningUk: 'я піду ненадовго й скоро повернуся', meaningEs: 'me voy por poco tiempo y vuelvo pronto', contextRu: 'короткая бытовая фраза перед уходом из кадра или комнаты', contextUk: 'коротка побутова фраза перед виходом з кадру або кімнати', contextEs: 'frase cotidiana antes de salir de la escena o habitación', exampleEn: "Wait here. I'll be right back.", exampleRu: 'Жди здесь. Я сейчас вернусь.', exampleUk: 'Чекай тут. Я зараз повернуся.', exampleEs: 'Espera aquí. Vuelvo enseguida.' },
  { en: "Now we're talking.", ru: 'вот теперь другое дело', uk: 'ось тепер інша справа', es: 'ahora sí estamos hablando', meaningRu: 'теперь вариант стал интересным или правильным', meaningUk: 'тепер варіант став цікавим або правильним', meaningEs: 'ahora la opción se volvió interesante o correcta', contextRu: 'когда ситуация резко улучшилась', contextUk: 'коли ситуація різко покращилася', contextEs: 'cuando la situación mejora de golpe', exampleEn: 'You found the keys? Now we are talking.', exampleRu: 'Ты нашёл ключи? Вот теперь другое дело.', exampleUk: 'Ти знайшов ключі? Ось тепер інша справа.', exampleEs: '¿Encontraste las llaves? Ahora sí.' },
  { en: "Don't get me wrong.", ru: 'не пойми меня неправильно', uk: 'не зрозумій мене неправильно', es: 'no me malinterpretes', meaningRu: 'я хочу смягчить возможное недопонимание', meaningUk: 'я хочу помʼякшити можливе непорозуміння', meaningEs: 'quiero evitar que se entienda mal lo que digo', contextRu: 'перед честным мнением, критикой или осторожным признанием', contextUk: 'перед чесною думкою, критикою або обережним зізнанням', contextEs: 'antes de una opinión honesta, crítica o confesión cuidadosa', exampleEn: "Don't get me wrong, I like him. I just do not trust him.", exampleRu: 'Не пойми меня неправильно, он мне нравится. Я просто ему не доверяю.', exampleUk: 'Не зрозумій мене неправильно, він мені подобається. Я просто йому не довіряю.', exampleEs: 'No me malinterpretes, me cae bien. Simplemente no confío en él.' },
  { en: 'That was close.', ru: 'это было близко', uk: 'це було близько', es: 'estuvo cerca', meaningRu: 'опасность или провал почти случились', meaningUk: 'небезпека або провал майже сталися', meaningEs: 'el peligro o el fracaso casi ocurrió', contextRu: 'после спасения в последний момент', contextUk: 'після порятунку в останню мить', contextEs: 'después de salvarse en el último momento', exampleEn: 'That was close. We almost got caught.', exampleRu: 'Это было близко. Нас почти поймали.', exampleUk: 'Це було близько. Нас майже спіймали.', exampleEs: 'Estuvo cerca. Casi nos atrapan.' },
  { en: 'End of story.', ru: 'и точка', uk: 'і крапка', es: 'fin de la historia', meaningRu: 'обсуждение закончено', meaningUk: 'обговорення завершено', meaningEs: 'la discusión terminó', contextRu: 'жёсткая финальная точка в споре или решении', contextUk: 'жорстка фінальна крапка в суперечці або рішенні', contextEs: 'cierre firme de una discusión o decisión', exampleEn: 'You are not going alone. End of story.', exampleRu: 'Ты не пойдёшь один. И точка.', exampleUk: 'Ти не підеш сам. І крапка.', exampleEs: 'No irás solo. Fin de la historia.' },
  { en: 'Previously on...', ru: 'ранее в...', uk: 'раніше в...', es: 'anteriormente en...', meaningRu: 'краткое напоминание о прошлых событиях', meaningUk: 'коротке нагадування про попередні події', meaningEs: 'resumen breve de hechos anteriores', contextRu: 'в начале серии, обзора или пересказа', contextUk: 'на початку серії, огляду або переказу', contextEs: 'al inicio de un episodio, reseña o recapitulación', exampleEn: 'Previously on this show, the team split up.', exampleRu: 'Ранее в этом шоу команда разделилась.', exampleUk: 'Раніше в цьому шоу команда розділилася.', exampleEs: 'Anteriormente en esta serie, el equipo se separó.' },
  { en: 'No spoilers.', ru: 'без спойлеров', uk: 'без спойлерів', es: 'sin spoilers', meaningRu: 'не раскрывай важные детали сюжета', meaningUk: 'не розкривай важливі деталі сюжету', meaningEs: 'no reveles detalles importantes de la trama', contextRu: 'перед обсуждением фильма, серии или финала', contextUk: 'перед обговоренням фільму, серії або фіналу', contextEs: 'antes de hablar de una película, episodio o final', exampleEn: 'No spoilers. I have not seen the finale.', exampleRu: 'Без спойлеров. Я не видел финал.', exampleUk: 'Без спойлерів. Я не бачив фінал.', exampleEs: 'Sin spoilers. No he visto el final.' },
  { en: 'The trailer looks good.', ru: 'трейлер выглядит хорошо', uk: 'трейлер виглядає добре', es: 'el tráiler se ve bien', meaningRu: 'превью производит хорошее впечатление', meaningUk: 'превʼю справляє хороше враження', meaningEs: 'el avance causa buena impresión', contextRu: 'когда обсуждают новый фильм или сериал до выхода', contextUk: 'коли обговорюють новий фільм або серіал до виходу', contextEs: 'cuando se habla de una película o serie antes del estreno', exampleEn: 'The trailer looks good. I might watch it.', exampleRu: 'Трейлер выглядит хорошо. Возможно, посмотрю.', exampleUk: 'Трейлер виглядає добре. Можливо, подивлюся.', exampleEs: 'El tráiler se ve bien. Quizá la vea.' },
  { en: 'It is based on a true story.', ru: 'это основано на реальных событиях', uk: 'це засновано на реальних подіях', es: 'está basada en hechos reales', meaningRu: 'сюжет связан с реальными событиями', meaningUk: 'сюжет повʼязаний з реальними подіями', meaningEs: 'la trama se relaciona con hechos reales', contextRu: 'когда объясняют происхождение фильма или сериала', contextUk: 'коли пояснюють походження фільму або серіалу', contextEs: 'cuando se explica el origen de una película o serie', exampleEn: 'It is based on a true story, but they changed a lot.', exampleRu: 'Это основано на реальных событиях, но многое изменили.', exampleUk: 'Це засновано на реальних подіях, але багато змінили.', exampleEs: 'Está basada en hechos reales, pero cambiaron mucho.' },
  { en: 'The ending was rushed.', ru: 'финал был скомканным', uk: 'фінал був поспішним', es: 'el final fue apresurado', meaningRu: 'финал слишком быстро закрыл сюжетные линии', meaningUk: 'фінал надто швидко закрив сюжетні лінії', meaningEs: 'el final cerró la trama demasiado rápido', contextRu: 'после просмотра, когда концовка не успела раскрыться', contextUk: 'після перегляду, коли кінцівка не встигла розкритися', contextEs: 'después de ver algo cuando el cierre no tuvo tiempo', exampleEn: 'I liked the show, but the ending was rushed.', exampleRu: 'Мне понравился сериал, но финал был скомканным.', exampleUk: 'Мені сподобався серіал, але фінал був поспішним.', exampleEs: 'Me gustó la serie, pero el final fue apresurado.' },
  { en: 'The soundtrack is amazing.', ru: 'саундтрек потрясающий', uk: 'саундтрек неймовірний', es: 'la banda sonora es increíble', meaningRu: 'музыка в фильме или серии очень хорошая', meaningUk: 'музика у фільмі або серії дуже хороша', meaningEs: 'la música de la película o serie es muy buena', contextRu: 'когда обсуждают атмосферу и музыку', contextUk: 'коли обговорюють атмосферу й музику', contextEs: 'cuando se habla de atmósfera y música', exampleEn: 'The soundtrack is amazing. I saved every song.', exampleRu: 'Саундтрек потрясающий. Я сохранил все песни.', exampleUk: 'Саундтрек неймовірний. Я зберіг усі пісні.', exampleEs: 'La banda sonora es increíble. Guardé todas las canciones.' },
  { en: 'The acting feels natural.', ru: 'игра актёров кажется естественной', uk: 'гра акторів здається природною', es: 'la actuación se siente natural', meaningRu: 'актёры звучат и ведут себя правдоподобно', meaningUk: 'актори звучать і поводяться правдоподібно', meaningEs: 'los actores suenan y actúan de forma creíble', contextRu: 'в разговоре о качестве фильма или сериала', contextUk: 'у розмові про якість фільму або серіалу', contextEs: 'al comentar la calidad de una película o serie', exampleEn: 'The acting feels natural, even in quiet scenes.', exampleRu: 'Игра актёров кажется естественной даже в тихих сценах.', exampleUk: 'Гра акторів здається природною навіть у тихих сценах.', exampleEs: 'La actuación se siente natural incluso en escenas tranquilas.' },
  { en: 'The scene gave me chills.', ru: 'от этой сцены мурашки', uk: 'від цієї сцени мурахи', es: 'esa escena me dio escalofríos', meaningRu: 'сцена сильно впечатлила или напугала', meaningUk: 'сцена сильно вразила або налякала', meaningEs: 'la escena impresionó o asustó mucho', contextRu: 'после мощной эмоциональной или страшной сцены', contextUk: 'після сильної емоційної або страшної сцени', contextEs: 'después de una escena emocional o aterradora', exampleEn: 'The scene gave me chills. I still think about it.', exampleRu: 'От этой сцены мурашки. Я всё ещё о ней думаю.', exampleUk: 'Від цієї сцени мурахи. Я досі про неї думаю.', exampleEs: 'Esa escena me dio escalofríos. Aún pienso en ella.' },
  { en: 'This episode is filler.', ru: 'эта серия филлер', uk: 'ця серія філер', es: 'este episodio es de relleno', meaningRu: 'серия почти не двигает основной сюжет', meaningUk: 'серія майже не рухає основний сюжет', meaningEs: 'el episodio casi no avanza la trama principal', contextRu: 'когда серия ощущается необязательной', contextUk: 'коли серія здається необовʼязковою', contextEs: 'cuando un episodio parece prescindible', exampleEn: 'This episode is filler, but it is still fun.', exampleRu: 'Эта серия филлер, но всё равно весёлая.', exampleUk: 'Ця серія філер, але все одно весела.', exampleEs: 'Este episodio es de relleno, pero igual es divertido.' },
  { en: 'The villain stole the show.', ru: 'злодей затмил всех', uk: 'лиходій затьмарив усіх', es: 'el villano se robó la escena', meaningRu: 'злодей оказался самым ярким персонажем', meaningUk: 'лиходій виявився найяскравішим персонажем', meaningEs: 'el villano fue el personaje más llamativo', contextRu: 'после фильма, где антагонист особенно запомнился', contextUk: 'після фільму, де антагоніст особливо запамʼятався', contextEs: 'después de una película donde el antagonista destaca', exampleEn: 'The villain stole the show in every scene.', exampleRu: 'Злодей затмил всех в каждой сцене.', exampleUk: 'Лиходій затьмарив усіх у кожній сцені.', exampleEs: 'El villano se robó la escena cada vez.' },
  { en: 'There is a post-credit scene.', ru: 'есть сцена после титров', uk: 'є сцена після титрів', es: 'hay una escena postcréditos', meaningRu: 'после титров есть дополнительная сцена', meaningUk: 'після титрів є додаткова сцена', meaningEs: 'después de los créditos hay una escena extra', contextRu: 'когда предупреждают не уходить из зала слишком рано', contextUk: 'коли попереджають не виходити із залу надто рано', contextEs: 'cuando advierten que no hay que irse demasiado pronto', exampleEn: 'Do not leave yet. There is a post-credit scene.', exampleRu: 'Пока не уходи. Есть сцена после титров.', exampleUk: 'Поки не йди. Є сцена після титрів.', exampleEs: 'No te vayas todavía. Hay una escena postcréditos.' },
  { en: 'The pacing is slow.', ru: 'темп медленный', uk: 'темп повільний', es: 'el ritmo es lento', meaningRu: 'история развивается слишком медленно', meaningUk: 'історія розвивається надто повільно', meaningEs: 'la historia avanza demasiado despacio', contextRu: 'в обсуждении сериала, фильма или отдельной серии', contextUk: 'в обговоренні серіалу, фільму або окремої серії', contextEs: 'al hablar de una serie, película o episodio', exampleEn: 'The pacing is slow, but the atmosphere is great.', exampleRu: 'Темп медленный, но атмосфера отличная.', exampleUk: 'Темп повільний, але атмосфера чудова.', exampleEs: 'El ritmo es lento, pero la atmósfera es genial.' },
  { en: 'The dialogue is sharp.', ru: 'диалоги острые', uk: 'діалоги гострі', es: 'el diálogo es brillante', meaningRu: 'реплики умные, быстрые и выразительные', meaningUk: 'репліки розумні, швидкі й виразні', meaningEs: 'las líneas son inteligentes, rápidas y expresivas', contextRu: 'когда особенно нравятся разговорные сцены', contextUk: 'коли особливо подобаються розмовні сцени', contextEs: 'cuando destacan las escenas conversacionales', exampleEn: 'The dialogue is sharp and every joke lands.', exampleRu: 'Диалоги острые, и каждая шутка попадает.', exampleUk: 'Діалоги гострі, і кожен жарт влучає.', exampleEs: 'El diálogo es brillante y cada broma funciona.' },
  { en: 'That line became a meme.', ru: 'эта фраза стала мемом', uk: 'ця фраза стала мемом', es: 'esa frase se volvió meme', meaningRu: 'реплика стала популярной в интернете', meaningUk: 'репліка стала популярною в інтернеті', meaningEs: 'la frase se hizo popular en internet', contextRu: 'когда обсуждают культовую или вирусную реплику', contextUk: 'коли обговорюють культову або вірусну репліку', contextEs: 'al hablar de una línea icónica o viral', exampleEn: 'That line became a meme overnight.', exampleRu: 'Эта фраза стала мемом за одну ночь.', exampleUk: 'Ця фраза стала мемом за одну ніч.', exampleEs: 'Esa frase se volvió meme de la noche a la mañana.' },
  { en: 'The season finale is tonight.', ru: 'финал сезона сегодня вечером', uk: 'фінал сезону сьогодні ввечері', es: 'el final de temporada es esta noche', meaningRu: 'последняя серия сезона выходит сегодня', meaningUk: 'остання серія сезону виходить сьогодні', meaningEs: 'el último episodio de la temporada sale hoy', contextRu: 'когда говорят о расписании выхода сериала', contextUk: 'коли говорять про розклад виходу серіалу', contextEs: 'al hablar del calendario de una serie', exampleEn: 'The season finale is tonight. Do not spoil it.', exampleRu: 'Финал сезона сегодня вечером. Не спойлери.', exampleUk: 'Фінал сезону сьогодні ввечері. Не спойлери.', exampleEs: 'El final de temporada es esta noche. No hagas spoilers.' },
];

export const MOVIE_SERIES_CARDS: VictoriaRow[] = SEEDS.slice(0, 60).map((seed, index) => ({
  id: `official_movie_series_en_${String(index + 1).padStart(2, '0')}`,
  en: seed.en,
  ru: seed.ru,
  uk: seed.uk,
  es: seed.es,
  explanationRu: `${seed.en} = ${seed.meaningRu}. Употребляется в кино, сериалах и обычной живой речи, ${seed.contextRu}. Модель: готовая реплика, которую можно сказать целиком. Пример: ${seed.exampleEn} — ${seed.exampleRu}`,
  explanationUk: `${seed.en} = ${seed.meaningUk}. Уживається в кіно, серіалах і звичайній живій мові, ${seed.contextUk}. Модель: готова репліка, яку можна сказати цілком. Приклад: ${seed.exampleEn} — ${seed.exampleUk}`,
  explanationEs: `${seed.en} = ${seed.meaningEs}. Se usa en peliculas, series y habla cotidiana, ${seed.contextEs}. Patron: frase lista para decir completa. Ejemplo: ${seed.exampleEn} — ${seed.exampleEs}`,
  exampleEn: seed.exampleEn,
  exampleRu: seed.exampleRu,
  exampleUk: seed.exampleUk,
  exampleEs: seed.exampleEs,
  register: 'cinematic everyday',
  level: seed.level ?? 'A2-B1',
}));
