// AUTO-GENERATED by content/avatar-studio/scripts/publish_catalog.mjs — не править руками.
// Перегенерация: node content/avatar-studio/scripts/publish_catalog.mjs
export const AVATAR_25D_ASSETS: Record<string, number> = {
  'base/base_m': require('./catalog/base/base_m.png'),
  'base/base_f': require('./catalog/base/base_f.png'),
};
