// AUTO-GENERATED by content/avatar-studio/scripts/publish_catalog.mjs — не править руками.
// Перегенерация: node content/avatar-studio/scripts/publish_catalog.mjs
export const AVATAR_25D_ASSETS: Record<string, number> = {
  'base/base_m': require('./catalog/base/base_m.webp'),
  'base/base_f': require('./catalog/base/base_f.webp'),
  'hair/hair_pony_f': require('./portraits/hair/hair_pony_f.webp'),
  'portrait:hair/hair_pony_f': require('./portraits/hair/hair_pony_f.webp'),
  'hair/hair_halfup_f': require('./portraits/hair/hair_halfup_f.webp'),
  'portrait:hair/hair_halfup_f': require('./portraits/hair/hair_halfup_f.webp'),
  'hair/hair_messy_m': require('./portraits/hair/hair_messy_m.webp'),
  'portrait:hair/hair_messy_m': require('./portraits/hair/hair_messy_m.webp'),
};
