import type { LearningV2BankPhraseV1 } from "../phrase_bank_v1";

/**
 * Английский банк урока 12 — «Рассказать историю с частыми глаголами прошлого».
 *
 * зачем: неправильные глаголы обычно зубрят таблицей и не используют. Здесь взяты только восемь самых частых (went, saw, had, said, took, came, got, made) и сразу в связках с «and then» и «suddenly» — то, из чего состоит живой рассказ. Таблицы нет: глагол приходит внутри истории.
 */
export const EN_LESSON_12_PHRASES_V1: readonly LearningV2BankPhraseV1[] =
  Object.freeze([
    {
      id: "en-l12-01",
      text: "I went to the market this morning.",
      ru: "Утром ходил на рынок.",
      component: "использовать частые неправильные глаголы",
      function: "рассказать о походе за покупками",
      isChunk: true,
      rarestWordRank: 800,
      contexts: ["магазин", "разговор о дне"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-02",
      text: "We saw an old friend at the shop.",
      ru: "В магазине встретили старого знакомого.",
      component: "использовать частые неправильные глаголы",
      function: "рассказать о встрече",
      isChunk: true,
      rarestWordRank: 600,
      contexts: ["магазин", "разговор"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-03",
      text: "I had a headache all morning.",
      ru: "Всё утро болела голова.",
      component: "использовать частые неправильные глаголы",
      function: "рассказать о самочувствии",
      isChunk: true,
      rarestWordRank: 1560,
      contexts: ["здоровье", "аптека"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-04",
      text: "She said hello and then sat down.",
      ru: "Она поздоровалась и села.",
      component: "использовать частые неправильные глаголы",
      function: "описать чужое действие",
      isChunk: true,
      rarestWordRank: 300,
      contexts: ["встреча", "работа"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-05",
      text: "I took the wrong bus yesterday.",
      ru: "Вчера сел не на тот автобус.",
      component: "использовать частые неправильные глаголы",
      function: "рассказать о неловкой ситуации",
      isChunk: true,
      rarestWordRank: 1400,
      contexts: ["поездка", "город"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-06",
      text: "We went to the market and saw fresh fish.",
      ru: "Сходили на рынок и увидели свежую рыбу.",
      component: "использовать частые неправильные глаголы",
      function: "рассказать о покупках",
      isChunk: true,
      rarestWordRank: 1500,
      contexts: ["рынок", "еда"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-07",
      text: "She had a bad cold last week.",
      ru: "На прошлой неделе она сильно простыла.",
      component: "использовать частые неправильные глаголы",
      function: "рассказать о болезни близкого",
      isChunk: true,
      rarestWordRank: 1500,
      contexts: ["здоровье", "семья"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-08",
      text: "He got my letter yesterday.",
      ru: "Письмо он получил вчера.",
      component: "использовать частые неправильные глаголы",
      function: "рассказать о получении",
      isChunk: true,
      rarestWordRank: 900,
      contexts: ["почта", "работа"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-09",
      text: "We came home late and had tea.",
      ru: "Домой вернулись поздно и попили чаю.",
      component: "связать события",
      function: "описать вечер",
      isChunk: true,
      rarestWordRank: 700,
      contexts: ["семья", "вечер"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-10",
      text: "I got a letter and then called my son.",
      ru: "Получил письмо и сразу позвонил сыну.",
      component: "связать события",
      function: "описать последовательность",
      isChunk: true,
      rarestWordRank: 1200,
      contexts: ["семья", "почта"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-11",
      text: "I made breakfast and then went out.",
      ru: "Приготовил завтрак и вышел.",
      component: "связать события",
      function: "описать утро",
      isChunk: true,
      rarestWordRank: 1150,
      contexts: ["утро", "дом"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-12",
      text: "I saw the doctor and then went to the pharmacy.",
      ru: "Был у врача, а потом зашёл в аптеку.",
      component: "связать события",
      function: "описать визит к врачу",
      isChunk: true,
      rarestWordRank: 900,
      contexts: ["здоровье", "аптека"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-13",
      text: "He went home and then called his wife.",
      ru: "Он поехал домой и позвонил жене.",
      component: "связать события",
      function: "описать последовательность",
      isChunk: true,
      rarestWordRank: 800,
      contexts: ["семья", "работа"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-14",
      text: "I had lunch and then took a rest.",
      ru: "Пообедал и немного отдохнул.",
      component: "связать события",
      function: "описать дневной отдых",
      isChunk: true,
      rarestWordRank: 1550,
      contexts: ["дом", "здоровье"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-15",
      text: "I took my medicine and then had breakfast.",
      ru: "Принял лекарство и позавтракал.",
      component: "связать события",
      function: "описать утренний ритуал",
      isChunk: true,
      rarestWordRank: 1290,
      contexts: ["здоровье", "утро"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-16",
      text: "I said goodbye and then left the office.",
      ru: "Попрощался и ушёл из офиса.",
      component: "связать события",
      function: "описать конец рабочего дня",
      isChunk: true,
      rarestWordRank: 1200,
      contexts: ["работа", "вечер"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-17",
      text: "I took a taxi and then met my friend.",
      ru: "Взял такси и встретился с другом.",
      component: "связать события",
      function: "описать поездку на встречу",
      isChunk: true,
      rarestWordRank: 1150,
      contexts: ["поездка", "друзья"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-18",
      text: "I made a mistake and then fixed it.",
      ru: "Ошибся, но потом исправил.",
      component: "связать события",
      function: "рассказать о рабочей ситуации",
      isChunk: true,
      rarestWordRank: 1750,
      contexts: ["работа", "учёба"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-19",
      text: "Suddenly it started to rain.",
      ru: "Вдруг пошёл дождь.",
      component: "удержать интерес",
      function: "добавить неожиданность",
      isChunk: true,
      rarestWordRank: 1850,
      contexts: ["прогулка", "поездка"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-20",
      text: "Suddenly the phone rang.",
      ru: "Вдруг зазвонил телефон.",
      component: "удержать интерес",
      function: "добавить неожиданное событие",
      isChunk: true,
      rarestWordRank: 1600,
      contexts: ["дом", "работа"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-21",
      text: "Suddenly the lights went out.",
      ru: "И тут погас свет.",
      component: "удержать интерес",
      function: "добавить драматичный момент",
      isChunk: true,
      rarestWordRank: 1300,
      contexts: ["дом", "вечер"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l12-22",
      text: "And then something strange happened.",
      ru: "А дальше произошло странное.",
      component: "удержать интерес",
      function: "подвести к развязке",
      isChunk: true,
      rarestWordRank: 1450,
      contexts: ["рассказ", "разговор"],
      interactionModes: ["recognition", "production"],
    },
  ] as const);
