import type { LearningV2BankPhraseV1 } from "../phrase_bank_v1";

/**
 * Английский банк урока 5 — «Спросить человека о его привычках и работе».
 *
 * зачем: это урок про то, как НЕ дать разговору умереть. Классическая беда
 * новичка — он умеет ответить, но не умеет спросить в ответ и отреагировать,
 * поэтому диалог обрывается после второй реплики. Треть банка — короткие
 * реакции («Really?», «Me too»), которые дороже длинных правильных фраз.
 *
 * Правки черновика: «Я этого не знал» — мужской род; заменено на нейтральное
 * «Вот это новость». «Good for you!» убрано: по-русски «молодец» от незнакомца
 * звучит покровительственно, для 40+ это риск.
 */
export const EN_LESSON_05_PHRASES_V1: readonly LearningV2BankPhraseV1[] =
  Object.freeze([
    {
      id: "en-l5-01",
      text: "Do you like your job?",
      ru: "Вам нравится ваша работа?",
      component: "построить вопрос с do/does",
      function: "спросить об отношении к работе",
      isChunk: true,
      rarestWordRank: 1,
      contexts: ["разговор с коллегой", "знакомство на встрече"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-02",
      text: "Do you work near here?",
      ru: "Вы работаете поблизости?",
      component: "построить вопрос с do/does",
      function: "спросить о месте работы",
      isChunk: false,
      rarestWordRank: 620,
      contexts: ["разговор с соседом", "беседа в очереди"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-03",
      text: "Does he work with you?",
      ru: "Он ваш коллега?",
      component: "построить вопрос с do/does",
      function: "спросить о третьем лице",
      isChunk: false,
      rarestWordRank: 1,
      contexts: ["спрашивают про знакомого", "обсуждаете общего человека"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-04",
      text: "Do you cook at home?",
      ru: "Вы готовите дома?",
      component: "построить вопрос с do/does",
      function: "спросить о бытовой привычке",
      isChunk: false,
      rarestWordRank: 970,
      contexts: ["разговор о повседневной жизни", "обмен рецептами"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-05",
      text: "Does she live near you?",
      ru: "Она живёт рядом с вами?",
      component: "построить вопрос с do/does",
      function: "спросить о месте жительства другого",
      isChunk: false,
      rarestWordRank: 1,
      contexts: ["спрашивают про подругу", "разговор о соседях"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-06",
      text: "Do you walk every day?",
      ru: "Вы каждый день гуляете?",
      component: "построить вопрос с do/does",
      function: "спросить о ежедневной привычке",
      isChunk: false,
      rarestWordRank: 1,
      contexts: ["разговор о здоровье", "беседа в парке"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-07",
      text: "Do you enjoy it?",
      ru: "И вам это в радость?",
      component: "построить вопрос с do/does",
      function: "спросить об удовольствии от занятия",
      isChunk: true,
      rarestWordRank: 640,
      contexts: ["собеседник рассказал о хобби", "разговор о работе"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-08",
      text: "What do you do in the evenings?",
      ru: "Чем вы заняты по вечерам?",
      component: "построить вопрос с do/does",
      function: "спросить о привычном занятии",
      isChunk: true,
      rarestWordRank: 1,
      contexts: ["поддержание разговора", "узнаёте о распорядке"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-09",
      text: "Does that keep you busy?",
      ru: "Это отнимает много времени?",
      component: "построить вопрос с do/does",
      function: "спросить о занятости",
      isChunk: true,
      rarestWordRank: 610,
      contexts: ["собеседник упомянул дело", "разговор о новом занятии"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-10",
      text: "How often do you see them?",
      ru: "Как часто вы с ними видитесь?",
      component: "уточнить частоту",
      function: "спросить о частоте встреч",
      isChunk: true,
      rarestWordRank: 450,
      contexts: ["разговор о родственниках", "спрашивают про друзей"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-11",
      text: "How often do you cook?",
      ru: "Часто ли вы готовите?",
      component: "уточнить частоту",
      function: "уточнить частоту бытового действия",
      isChunk: true,
      rarestWordRank: 970,
      contexts: ["разговор о домашних делах", "обмен привычками"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-12",
      text: "How often do you travel?",
      ru: "Как часто вы куда-то ездите?",
      component: "уточнить частоту",
      function: "спросить о частоте поездок",
      isChunk: true,
      rarestWordRank: 730,
      contexts: ["разговор об отпуске", "обсуждение планов"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-13",
      text: "Every day, or just sometimes?",
      ru: "Каждый день или время от времени?",
      component: "уточнить частоту",
      function: "уточнить регулярность",
      isChunk: false,
      rarestWordRank: 620,
      contexts: ["ответ был неточным", "хотите узнать детали"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-14",
      text: "How many times a week?",
      ru: "Сколько раз в неделю?",
      component: "уточнить частоту",
      function: "спросить точное число",
      isChunk: true,
      rarestWordRank: 380,
      contexts: ["обсуждают занятия", "разговор о графике"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-15",
      text: "Once a week or twice?",
      ru: "Раз в неделю или два раза?",
      component: "уточнить частоту",
      function: "уточнить частоту через выбор",
      isChunk: false,
      rarestWordRank: 1050,
      contexts: ["уточняете расписание", "разговор о привычках"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-16",
      text: "Really? How interesting.",
      ru: "Правда? Как интересно.",
      component: "отреагировать на ответ",
      function: "показать интерес к ответу",
      isChunk: true,
      rarestWordRank: 460,
      contexts: ["собеседник рассказал о работе", "услышали новое"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-17",
      text: "Me too, actually.",
      ru: "Я, кстати, тоже.",
      component: "отреагировать на ответ",
      function: "показать общее увлечение",
      isChunk: true,
      rarestWordRank: 490,
      contexts: ["нашлось общее", "поддерживаете беседу"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-18",
      text: "That sounds like a lot.",
      ru: "Звучит внушительно.",
      component: "отреагировать на ответ",
      function: "отреагировать на большой объём",
      isChunk: true,
      rarestWordRank: 490,
      contexts: ["назвали большое число", "услышали про нагрузку"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-19",
      // Было «Я этого не знал» — мужской род. Стало нейтрально.
      text: "I didn't know that.",
      ru: "Вот это новость.",
      component: "отреагировать на ответ",
      function: "показать, что услышанное неожиданно",
      isChunk: true,
      rarestWordRank: 1,
      contexts: ["узнали новую деталь", "собеседник поделился фактом"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-20",
      text: "Wow, that's a lot of work.",
      ru: "Ого, сколько работы.",
      component: "отреагировать на ответ",
      function: "отреагировать удивлением",
      isChunk: true,
      rarestWordRank: 1,
      contexts: ["описали загруженный график", "узнали про большой проект"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-21",
      // Заменяет «Good for you!»: по-русски от незнакомца это звучит
      // покровительственно, а аудитории 40+ такое особенно неприятно.
      text: "That's great.",
      ru: "Это здорово.",
      component: "отреагировать на ответ",
      function: "одобрительно отреагировать",
      isChunk: true,
      rarestWordRank: 130,
      contexts: ["собеседник рассказал о хорошем", "поддерживаете разговор"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l5-22",
      // Добавлено: без встречного вопроса разговор снова упирается в тупик.
      text: "And how about you?",
      ru: "А у вас как с этим?",
      component: "отреагировать на ответ",
      function: "вернуть тему собеседнику",
      isChunk: true,
      rarestWordRank: 30,
      contexts: ["после ответа собеседника", "чтобы разговор шёл дальше"],
      interactionModes: ["recognition", "production"],
    },
  ] as const);
