import type { LearningV2BankPhraseV1 } from "../phrase_bank_v1";

/**
 * Английский банк урока 2 — «Спросить о человеке и коротко ответить».
 *
 * зачем: черновик агента исправлен на входе. Что поменялось:
 *  - «Nice to meet you too» агент положил в компонент «ответить да/нет» и сам
 *    признал натяжку в заметке. Фраза к тому же уже есть в уроке 1 (en-l1-21).
 *    Удалена: дубль между уроками хуже, чем на одну фразу меньше.
 *  - «Are you a student?» заменена: аудитория 40+/50+, а фраза уводит в
 *    студенческий контекст. Вместо неё «Are you here on business?» — то, что
 *    этот человек реально спросит и услышит.
 *  - «Yes, I am» / «No, I'm not» имели переводы «Да, это так» / «Нет, не так» —
 *    неестественно по-русски. Заменено на живое «Да» / «Нет, не я».
 */
export const EN_LESSON_02_PHRASES_V1: readonly LearningV2BankPhraseV1[] =
  Object.freeze([
    {
      id: "en-l2-01",
      text: "Are you from here?",
      ru: "Вы отсюда?",
      component: "задать вопрос с are you",
      function: "спросить о происхождении собеседника",
      isChunk: true,
      rarestWordRank: 40,
      contexts: ["знакомство в кафе", "разговор в очереди"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-02",
      text: "Are you married?",
      ru: "Вы в браке?",
      component: "задать вопрос с are you",
      function: "спросить о семейном положении",
      isChunk: true,
      rarestWordRank: 950,
      contexts: ["личный разговор со знакомым", "анкета в клинике"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-03",
      text: "Are you busy?",
      ru: "Вы заняты?",
      component: "задать вопрос с are you",
      function: "спросить, есть ли у собеседника время",
      isChunk: true,
      rarestWordRank: 410,
      contexts: ["перед просьбой", "перед приглашением на кофе"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-04",
      text: "Are you tired?",
      ru: "Вы устали?",
      component: "задать вопрос с are you",
      function: "спросить о самочувствии",
      isChunk: true,
      rarestWordRank: 600,
      contexts: ["после долгой дороги", "в конце рабочего дня"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-05",
      text: "Are you okay?",
      ru: "Вы в порядке?",
      component: "задать вопрос с are you",
      function: "проявить заботу",
      isChunk: true,
      rarestWordRank: 260,
      contexts: ["собеседник выглядит расстроенным", "после неловкости"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-06",
      text: "Are you new here?",
      ru: "Вы здесь недавно?",
      component: "задать вопрос с are you",
      function: "спросить, давно ли человек в этом месте",
      isChunk: true,
      rarestWordRank: 220,
      contexts: ["первый день на новом месте", "новый сосед"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-07",
      text: "Are you hungry?",
      ru: "Вы голодны?",
      component: "задать вопрос с are you",
      function: "спросить, хочет ли собеседник поесть",
      isChunk: true,
      rarestWordRank: 480,
      contexts: ["перед обедом", "в гостях"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-08",
      text: "Are you ready?",
      ru: "Вы готовы?",
      component: "задать вопрос с are you",
      function: "спросить о готовности к действию",
      isChunk: true,
      rarestWordRank: 300,
      contexts: ["перед выходом из дома", "перед началом встречи"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-09",
      // Заменяет «Are you a student?»: аудитория 40+, студенческий контекст ей чужой.
      text: "Are you here on business?",
      ru: "Вы здесь по работе?",
      component: "задать вопрос с are you",
      function: "спросить о цели приезда",
      isChunk: true,
      rarestWordRank: 180,
      contexts: ["разговор в отеле", "знакомство в самолёте"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-10",
      text: "Yes, I am.",
      ru: "Да, верно.",
      component: "ответить да/нет",
      function: "кратко подтвердить",
      isChunk: true,
      rarestWordRank: 1,
      contexts: ["ответ на любой вопрос с are you", "подтверждение по телефону"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-11",
      text: "No, I'm not.",
      ru: "Нет, не я.",
      component: "ответить да/нет",
      function: "кратко возразить",
      isChunk: true,
      rarestWordRank: 1,
      contexts: ["ответ на ошибочное предположение", "уточнение личности"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-12",
      text: "Yes, a little.",
      ru: "Да, немного.",
      component: "ответить да/нет",
      function: "смягчённое подтверждение",
      isChunk: true,
      rarestWordRank: 190,
      contexts: ["на вопрос про усталость", "на вопрос про знание языка"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-13",
      text: "Not really.",
      ru: "Не особо.",
      component: "ответить да/нет",
      function: "смягчённое отрицание",
      isChunk: true,
      rarestWordRank: 370,
      contexts: ["на вопрос про занятость", "на вопрос про голод"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-14",
      text: "I'm not sure.",
      ru: "Точно не скажу.",
      component: "ответить да/нет",
      function: "признать неуверенность вместо да/нет",
      isChunk: true,
      rarestWordRank: 150,
      contexts: ["когда нет чёткого ответа", "при сомнении"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-15",
      text: "Yes, of course.",
      ru: "Да, конечно.",
      component: "ответить да/нет",
      function: "уверенно подтвердить",
      isChunk: true,
      rarestWordRank: 95,
      contexts: ["на просьбу", "на прямой вопрос"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-16",
      text: "And you?",
      ru: "А вы?",
      component: "переспросить вежливо",
      function: "вернуть тот же вопрос собеседнику",
      isChunk: true,
      rarestWordRank: 1,
      contexts: ["после ответа о себе", "в лёгкой беседе"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-17",
      text: "What about you?",
      ru: "А как у вас?",
      component: "переспросить вежливо",
      function: "вернуть вопрос развёрнуто",
      isChunk: true,
      rarestWordRank: 30,
      contexts: ["после рассказа о себе", "при смене темы на собеседника"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-18",
      text: "Sorry?",
      ru: "Простите?",
      component: "переспросить вежливо",
      function: "переспросить, если не расслышал",
      isChunk: true,
      rarestWordRank: 330,
      contexts: ["в шумном месте", "при быстрой речи собеседника"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-19",
      text: "Sorry, what?",
      ru: "Простите, что вы сказали?",
      component: "переспросить вежливо",
      function: "переспросить неформально",
      isChunk: true,
      rarestWordRank: 330,
      contexts: ["среди знакомых", "в непринуждённой беседе"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-20",
      text: "Can you say that again?",
      ru: "Повторите, пожалуйста.",
      component: "переспросить вежливо",
      function: "попросить повторить фразу целиком",
      isChunk: true,
      rarestWordRank: 270,
      contexts: ["на встрече", "в разговоре по телефону"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-21",
      text: "I don't understand.",
      ru: "Я не понимаю.",
      component: "переспросить вежливо",
      function: "сообщить о непонимании",
      isChunk: true,
      rarestWordRank: 160,
      contexts: ["при незнакомом слове", "в сложном разговоре"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "en-l2-22",
      // Добавлено вместо удалённого дубля: без этой просьбы новичок тонет
      // в быстрой речи, а «I don't understand» разговор не спасает.
      text: "Can you speak slowly, please?",
      ru: "Говорите помедленнее, пожалуйста.",
      component: "переспросить вежливо",
      function: "попросить говорить медленнее",
      isChunk: true,
      rarestWordRank: 350,
      contexts: ["разговор с быстро говорящим собеседником", "звонок в службу"],
      interactionModes: ["recognition", "production"],
    },
  ] as const);
