import type { LearningV2BankPhraseV1 } from "../phrase_bank_v1";

/**
 * Испанский банк урока 6 — «Узнать нужную информацию».
 *
 * зачем: урок закрывает ловушку, на которой спотыкаются все: «¿Cuánto cuesta?» для одного предмета и «¿Cuánto cuestan?» для нескольких. Обе формы даны рядом, чтобы разница была видна, а не заучивалась случайно. Здесь же латиноамериканское «quedar» вместо «estar» для «находится».
 */
export const ES_LESSON_06_PHRASES_V1: readonly LearningV2BankPhraseV1[] =
  Object.freeze([
    {
      // estar — физическое местоположение.
      id: "es-l6-01",
      text: "¿Dónde está el baño?",
      ru: "Где туалет?",
      component: "спросить место",
      function: "спросить расположение",
      isChunk: true,
      rarestWordRank: 150,
      contexts: ["ресторан", "вокзал"],
      interactionModes: ["recognition", "production"],
    },
    {
      // quedar — частый латиноамериканский вариант для «находится».
      id: "es-l6-02",
      text: "¿Dónde queda la farmacia?",
      ru: "Где находится аптека?",
      component: "спросить место",
      function: "спросить дорогу к учреждению",
      isChunk: true,
      rarestWordRank: 1400,
      contexts: ["здоровье", "улица"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-03",
      text: "¿Dónde está la parada del bus?",
      ru: "Где автобусная остановка?",
      component: "спросить место",
      function: "вежливо спросить дорогу",
      isChunk: true,
      rarestWordRank: 900,
      contexts: ["улица", "поездка"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-04",
      text: "¿Dónde puedo comprar agua?",
      ru: "Где можно купить воду?",
      component: "спросить место",
      function: "спросить место покупки",
      isChunk: true,
      rarestWordRank: 250,
      contexts: ["магазин", "улица"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-05",
      text: "¿Está cerca de aquí?",
      ru: "Это близко отсюда?",
      component: "спросить место",
      function: "уточнить близость",
      isChunk: true,
      rarestWordRank: 300,
      contexts: ["улица", "поиск места"],
      interactionModes: ["recognition", "production"],
    },
    {
      // usted.
      id: "es-l6-06",
      text: "Disculpe, ¿dónde firmo?",
      ru: "Извините, где расписаться?",
      component: "спросить место",
      function: "спросить, где поставить подпись",
      isChunk: true,
      rarestWordRank: 2000,
      contexts: ["клиника", "оформление"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-07",
      text: "¿Cuándo abre la tienda?",
      ru: "Когда открывается магазин?",
      component: "спросить время",
      function: "спросить время открытия",
      isChunk: true,
      rarestWordRank: 600,
      contexts: ["магазин", "планы"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-08",
      text: "¿Cuándo llega el próximo tren?",
      ru: "Когда придёт следующий поезд?",
      component: "спросить время",
      function: "спросить время прибытия",
      isChunk: true,
      rarestWordRank: 1500,
      contexts: ["вокзал", "поездка"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-09",
      text: "¿A qué hora cierran?",
      ru: "Во сколько вы закрываетесь?",
      component: "спросить время",
      function: "спросить время закрытия",
      isChunk: true,
      rarestWordRank: 400,
      contexts: ["магазин", "ресторан"],
      interactionModes: ["recognition", "production"],
    },
    {
      // ser — назначенное событие, не estar.
      id: "es-l6-10",
      text: "¿Cuándo es la cita?",
      ru: "Когда назначен приём?",
      component: "спросить время",
      function: "спросить время встречи",
      isChunk: true,
      rarestWordRank: 800,
      contexts: ["клиника", "запись"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-11",
      text: "¿Hasta qué hora está abierto?",
      ru: "До скольки открыто?",
      component: "спросить время",
      function: "уточнить время работы",
      isChunk: true,
      rarestWordRank: 1600,
      contexts: ["магазин", "аптека"],
      interactionModes: ["recognition", "production"],
    },
    {
      // cuesta — единственное число.
      id: "es-l6-12",
      text: "¿Cuánto cuesta esto?",
      ru: "Сколько это стоит?",
      component: "спросить цену",
      function: "спросить цену одного товара",
      isChunk: true,
      rarestWordRank: 200,
      contexts: ["магазин", "рынок"],
      interactionModes: ["recognition", "production"],
    },
    {
      // cuestan — множественное число: частая ошибка новичков.
      id: "es-l6-13",
      text: "¿Cuánto cuestan las manzanas?",
      ru: "Почём яблоки?",
      component: "спросить цену",
      function: "спросить цену нескольких товаров",
      isChunk: true,
      rarestWordRank: 550,
      contexts: ["рынок", "магазин"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-14",
      text: "¿Cuánto es en total?",
      ru: "Сколько всего?",
      component: "спросить цену",
      function: "спросить итоговую сумму",
      isChunk: true,
      rarestWordRank: 700,
      contexts: ["касса", "ресторан"],
      interactionModes: ["recognition", "production"],
    },
    {
      // usted.
      id: "es-l6-15",
      text: "¿Tiene algo más barato?",
      ru: "Есть что-нибудь подешевле?",
      component: "спросить цену",
      function: "спросить о более дешёвом варианте",
      isChunk: true,
      rarestWordRank: 650,
      contexts: ["магазин", "рынок"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-16",
      text: "Es un poco caro.",
      ru: "Дороговато.",
      component: "спросить цену",
      function: "отреагировать на цену",
      isChunk: true,
      rarestWordRank: 450,
      contexts: ["магазин", "торг"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-17",
      text: "¿Cuánto cuesta la entrada?",
      ru: "Сколько стоит входной билет?",
      component: "спросить цену",
      function: "спросить цену билета",
      isChunk: true,
      rarestWordRank: 1000,
      contexts: ["музей", "мероприятие"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-18",
      text: "¿Por qué está cerrado hoy?",
      ru: "Почему сегодня закрыто?",
      component: "спросить причину",
      function: "спросить причину закрытия",
      isChunk: true,
      rarestWordRank: 900,
      contexts: ["магазин", "улица"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-19",
      text: "¿Por qué es tan caro?",
      ru: "Почему так дорого?",
      component: "спросить причину",
      function: "спросить причину цены",
      isChunk: true,
      rarestWordRank: 750,
      contexts: ["магазин", "ресторан"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-20",
      text: "¿Por qué no funciona?",
      ru: "Почему не работает?",
      component: "спросить причину",
      function: "спросить причину неисправности",
      isChunk: true,
      rarestWordRank: 1100,
      contexts: ["техника", "отель"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l6-21",
      text: "¿Por qué hay que esperar?",
      ru: "Почему нужно ждать?",
      component: "спросить причину",
      function: "спросить причину задержки",
      isChunk: true,
      rarestWordRank: 1700,
      contexts: ["клиника", "очередь"],
      interactionModes: ["recognition", "production"],
    },
    {
      // tú.
      id: "es-l6-22",
      text: "¿Por qué llegas tarde?",
      ru: "Почему ты опаздываешь?",
      component: "спросить причину",
      function: "спросить причину опоздания",
      isChunk: true,
      rarestWordRank: 1200,
      contexts: ["семья", "встреча"],
      interactionModes: ["recognition", "production"],
    },
  ] as const);
