import type { LearningV2BankPhraseV1 } from "../phrase_bank_v1";

/**
 * Испанский банк урока 5 — «Спросить человека о его привычках и работе».
 *
 * зачем: главное открытие урока: в испанском НЕТ вспомогательного do/does. Вопрос строится интонацией и порядком слов — «¿Trabajas aquí?». После английского это разгрузка, и её надо показать явно, а не прятать. Треть банка — короткие реакции: без них диалог обрывается после второй реплики.
 */
export const ES_LESSON_05_PHRASES_V1: readonly LearningV2BankPhraseV1[] =
  Object.freeze([
    {
      // В испанском нет do/does — только интонация и порядок слов.
      id: "es-l5-01",
      text: "¿Trabajas aquí?",
      ru: "Ты здесь работаешь?",
      component: "построить вопрос с do/does",
      function: "спросить о месте работы на «ты»",
      isChunk: true,
      rarestWordRank: 1100,
      contexts: ["работа", "знакомство"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-02",
      text: "¿Usted trabaja aquí?",
      ru: "Вы здесь работаете?",
      component: "построить вопрос с do/does",
      function: "спросить о месте работы на «вы»",
      isChunk: true,
      rarestWordRank: 1100,
      contexts: ["работа", "магазин"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-03",
      text: "¿Vives cerca?",
      ru: "Ты живёшь недалеко?",
      component: "построить вопрос с do/does",
      function: "спросить о месте жительства",
      isChunk: true,
      rarestWordRank: 900,
      contexts: ["знакомство", "соседи"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-04",
      text: "¿Tienes hijos?",
      ru: "У тебя есть дети?",
      component: "построить вопрос с do/does",
      function: "спросить о семье",
      isChunk: true,
      rarestWordRank: 400,
      contexts: ["семья", "разговор"],
      interactionModes: ["recognition", "production"],
    },
    {
      // usted.
      id: "es-l5-05",
      text: "¿Le gusta su trabajo?",
      ru: "Вам нравится ваша работа?",
      component: "построить вопрос с do/does",
      function: "спросить об отношении к работе",
      isChunk: true,
      rarestWordRank: 300,
      contexts: ["работа", "деловая беседа"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-06",
      text: "¿Cocinas en casa?",
      ru: "Ты готовишь дома?",
      component: "построить вопрос с do/does",
      function: "спросить о бытовой привычке",
      isChunk: true,
      rarestWordRank: 1700,
      contexts: ["семья", "разговор о еде"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-07",
      text: "¿Haces ejercicio?",
      ru: "Ты занимаешься спортом?",
      component: "построить вопрос с do/does",
      function: "спросить о физической активности",
      isChunk: true,
      rarestWordRank: 1500,
      contexts: ["здоровье", "разговор"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-08",
      text: "¿Con qué frecuencia viajas?",
      ru: "Как часто ты путешествуешь?",
      component: "уточнить частоту",
      function: "спросить о частоте действия",
      isChunk: true,
      rarestWordRank: 2200,
      contexts: ["поездки", "разговор"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-09",
      text: "Siempre trabajo por la mañana.",
      ru: "Я всегда работаю по утрам.",
      component: "уточнить частоту",
      function: "описать регулярную привычку",
      isChunk: true,
      rarestWordRank: 150,
      contexts: ["работа", "график"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-10",
      text: "A veces cocino en casa.",
      ru: "Иногда готовлю дома.",
      component: "уточнить частоту",
      function: "описать нерегулярную привычку",
      isChunk: true,
      rarestWordRank: 600,
      contexts: ["семья", "еда"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-11",
      text: "Nunca bebo café por la noche.",
      ru: "Кофе на ночь я никогда не пью.",
      component: "уточнить частоту",
      function: "описать отсутствие привычки",
      isChunk: true,
      rarestWordRank: 250,
      contexts: ["здоровье", "вечер"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-12",
      text: "Casi siempre camino al trabajo.",
      ru: "На работу почти всегда иду пешком.",
      component: "уточнить частоту",
      function: "описать почти регулярную привычку",
      isChunk: true,
      rarestWordRank: 1300,
      contexts: ["работа", "здоровье"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-13",
      text: "Llamo a mis hijos cada semana.",
      ru: "Детям я звоню каждую неделю.",
      component: "уточнить частоту",
      function: "указать конкретную частоту",
      isChunk: true,
      rarestWordRank: 1000,
      contexts: ["семья", "разговор"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-14",
      text: "Rara vez salgo de noche.",
      ru: "Вечером я выхожу редко.",
      component: "уточнить частоту",
      function: "описать редкую привычку",
      isChunk: true,
      rarestWordRank: 1800,
      contexts: ["разговор", "семья"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-15",
      text: "Todos los días leo un poco.",
      ru: "Каждый день понемногу читаю.",
      component: "уточнить частоту",
      function: "описать ежедневную привычку",
      isChunk: true,
      rarestWordRank: 500,
      contexts: ["разговор", "досуг"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-16",
      text: "¿En serio?",
      ru: "Серьёзно?",
      component: "отреагировать на ответ",
      function: "выразить удивление",
      isChunk: true,
      rarestWordRank: 950,
      contexts: ["разговор", "семья"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-17",
      text: "Qué interesante.",
      ru: "Как интересно.",
      component: "отреагировать на ответ",
      function: "выразить интерес",
      isChunk: true,
      rarestWordRank: 1300,
      contexts: ["разговор", "работа"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-18",
      text: "Yo también.",
      ru: "И я тоже.",
      component: "отреагировать на ответ",
      function: "показать совпадение",
      isChunk: true,
      rarestWordRank: 100,
      contexts: ["разговор", "семья"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-19",
      text: "Yo tampoco.",
      ru: "Я тоже нет.",
      component: "отреагировать на ответ",
      function: "показать совпадение в отрицании",
      isChunk: true,
      rarestWordRank: 1200,
      contexts: ["разговор", "семья"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-20",
      text: "Qué bien.",
      ru: "Как хорошо.",
      component: "отреагировать на ответ",
      function: "одобрительно отреагировать",
      isChunk: true,
      rarestWordRank: 350,
      contexts: ["разговор", "работа"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-21",
      text: "No lo sabía.",
      ru: "Вот этого не знала.",
      component: "отреагировать на ответ",
      function: "отреагировать на новость",
      isChunk: true,
      rarestWordRank: 700,
      contexts: ["разговор", "работа"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l5-22",
      text: "¿Y tú qué haces?",
      ru: "А ты чем занимаешься?",
      component: "отреагировать на ответ",
      function: "вернуть вопрос собеседнику",
      isChunk: true,
      rarestWordRank: 400,
      contexts: ["разговор", "знакомство"],
      interactionModes: ["recognition", "production"],
    },
  ] as const);
