import type { LearningV2BankPhraseV1 } from "../phrase_bank_v1";

/**
 * Испанский банк урока 2 — «Спросить о человеке и коротко ответить».
 *
 * зачем: испанский требует выбирать между ser и estar там, где в русском один
 * глагол. Здесь это видно сразу: «¿Eres de aquí?» (происхождение — ser) против
 * «¿Estás cansado?» (усталость — estar). Ошибка в этой паре — самая стойкая у
 * русскоязычных, поэтому она разведена уже во втором уроке.
 *
 * Гендерные формы даны парами: женщина не должна учить «casado» вместо
 * «casada». Русский перевод у пары различается («женат» / «замужем»), поэтому
 * обратная проверка не ломается.
 *
 * Правка черновика: «No estoy seguro» шло только в мужском роде — добавлена
 * женская форма, иначе половина учениц заучила бы чужое окончание.
 */
export const ES_LESSON_02_PHRASES_V1: readonly LearningV2BankPhraseV1[] =
  Object.freeze([
    {
      id: "es-l2-01",
      text: "¿Eres de aquí?",
      ru: "Ты отсюда?",
      component: "задать вопрос с are you",
      function: "спросить о происхождении на «ты»",
      isChunk: true,
      rarestWordRank: 40,
      contexts: ["знакомство в кафе", "разговор в очереди"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-02",
      text: "¿Es usted de aquí?",
      ru: "Вы отсюда?",
      component: "задать вопрос с are you",
      function: "спросить о происхождении на «вы»",
      isChunk: true,
      rarestWordRank: 40,
      contexts: ["вежливый разговор в отеле", "обращение к незнакомцу"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-03",
      text: "¿Estás casado?",
      ru: "Ты женат?",
      component: "задать вопрос с are you",
      function: "спросить о семейном положении мужчины",
      isChunk: true,
      rarestWordRank: 900,
      contexts: ["личный разговор", "анкета в клинике"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-04",
      text: "¿Estás casada?",
      ru: "Ты замужем?",
      component: "задать вопрос с are you",
      function: "спросить о семейном положении женщины",
      isChunk: true,
      rarestWordRank: 900,
      contexts: ["личный разговор", "анкета в клинике"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-05",
      text: "¿Estás ocupado?",
      ru: "Ты сейчас занят?",
      component: "задать вопрос с are you",
      function: "спросить, есть ли время",
      isChunk: true,
      rarestWordRank: 410,
      contexts: ["перед просьбой", "перед приглашением"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-06",
      text: "¿Estás cansado?",
      ru: "Ты устал?",
      component: "задать вопрос с are you",
      function: "спросить о самочувствии",
      isChunk: true,
      rarestWordRank: 600,
      contexts: ["после долгой дороги", "в конце дня"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-07",
      text: "¿Estás bien?",
      ru: "Ты в порядке?",
      component: "задать вопрос с are you",
      function: "проявить заботу",
      isChunk: true,
      rarestWordRank: 30,
      contexts: ["собеседник расстроен", "после неловкости"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-08",
      text: "¿Está usted bien?",
      ru: "Вы хорошо себя чувствуете?",
      component: "задать вопрос с are you",
      function: "вежливо проявить заботу",
      isChunk: true,
      rarestWordRank: 30,
      contexts: ["обращение к пожилому человеку", "вежливый вопрос"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-09",
      text: "¿Eres nuevo aquí?",
      ru: "Ты здесь недавно?",
      component: "задать вопрос с are you",
      function: "спросить, давно ли человек здесь",
      isChunk: true,
      rarestWordRank: 220,
      contexts: ["первый день на новом месте", "новый сосед"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-10",
      text: "¿Estás aquí por trabajo?",
      ru: "Ты здесь по работе?",
      component: "задать вопрос с are you",
      function: "спросить о цели приезда",
      isChunk: true,
      rarestWordRank: 180,
      contexts: ["разговор в отеле", "знакомство в самолёте"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-11",
      text: "Sí",
      ru: "Да",
      component: "ответить да/нет",
      function: "кратко подтвердить",
      isChunk: false,
      rarestWordRank: 1,
      contexts: ["ответ на любой вопрос", "подтверждение по телефону"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-12",
      text: "No",
      ru: "Нет",
      component: "ответить да/нет",
      function: "кратко возразить",
      isChunk: false,
      rarestWordRank: 1,
      contexts: ["ответ на предположение", "уточнение"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-13",
      text: "Sí, un poco",
      ru: "Да, немного",
      component: "ответить да/нет",
      function: "смягчённое подтверждение",
      isChunk: true,
      rarestWordRank: 190,
      contexts: ["на вопрос про усталость", "на вопрос про язык"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-14",
      text: "La verdad, no",
      ru: "Честно говоря, нет",
      component: "ответить да/нет",
      function: "смягчённое отрицание",
      isChunk: true,
      rarestWordRank: 370,
      contexts: ["на вопрос про занятость", "на вопрос про голод"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-15",
      text: "No estoy seguro",
      ru: "Точно не скажу",
      component: "ответить да/нет",
      function: "признать неуверенность, говорит мужчина",
      isChunk: true,
      rarestWordRank: 150,
      contexts: ["нет чёткого ответа", "при сомнении"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-16",
      // Добавлена женская форма: без неё половина учениц заучит чужое окончание.
      text: "No estoy segura",
      ru: "Не уверена, что скажу точно",
      component: "ответить да/нет",
      function: "признать неуверенность, говорит женщина",
      isChunk: true,
      rarestWordRank: 150,
      contexts: ["нет чёткого ответа", "при сомнении"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-17",
      text: "Sí, claro",
      ru: "Да, конечно",
      component: "ответить да/нет",
      function: "уверенно подтвердить",
      isChunk: true,
      rarestWordRank: 95,
      contexts: ["на просьбу", "на прямой вопрос"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-18",
      text: "¿Y tú?",
      ru: "А ты?",
      component: "переспросить вежливо",
      function: "вернуть вопрос на «ты»",
      isChunk: true,
      rarestWordRank: 15,
      contexts: ["после ответа о себе", "в лёгкой беседе"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-19",
      text: "¿Y usted?",
      ru: "А вы?",
      component: "переспросить вежливо",
      function: "вернуть вопрос на «вы»",
      isChunk: true,
      rarestWordRank: 15,
      contexts: ["вежливый обмен репликами", "деловая беседа"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-20",
      text: "¿Perdón?",
      ru: "Простите?",
      component: "переспросить вежливо",
      function: "переспросить, если не расслышал",
      isChunk: true,
      rarestWordRank: 330,
      contexts: ["в шумном месте", "при быстрой речи"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-21",
      text: "¿Puede repetir, por favor?",
      ru: "Повторите, пожалуйста",
      component: "переспросить вежливо",
      function: "вежливо попросить повторить",
      isChunk: true,
      rarestWordRank: 270,
      contexts: ["на встрече", "в разговоре по телефону"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l2-22",
      text: "No entiendo",
      ru: "Я не понимаю",
      component: "переспросить вежливо",
      function: "сообщить о непонимании",
      isChunk: true,
      rarestWordRank: 160,
      contexts: ["при незнакомом слове", "в сложном разговоре"],
      interactionModes: ["recognition", "production"],
    },
  ] as const);
