import type { LearningV2BankPhraseV1 } from "../phrase_bank_v1";

/**
 * Испанский банк урока 10 — «Попросить о помощи и предложить помощь».
 *
 * зачем: три уровня вежливости даны рядом: ¿Puedes…? (свои), ¿Puede…? (вы), ¿Podría…? (максимально мягко). Разница по-русски почти не слышна, а в испанском определяет, воспримут просьбу как просьбу или как команду. Половина урока — предложить помощь: без этого человек только просит.
 */
export const ES_LESSON_10_PHRASES_V1: readonly LearningV2BankPhraseV1[] =
  Object.freeze([
    {
      id: "es-l10-01",
      text: "¿Puede ayudarme, por favor?",
      ru: "Вы не могли бы мне помочь?",
      component: "попросить вежливо",
      function: "вежливо попросить о помощи на «вы»",
      isChunk: true,
      rarestWordRank: 600,
      contexts: ["аптека", "ресепшен"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-02",
      text: "¿Puedes ayudarme un momento?",
      ru: "Поможешь на минутку?",
      component: "попросить вежливо",
      function: "попросить помощь на «ты»",
      isChunk: true,
      rarestWordRank: 600,
      contexts: ["семья", "молодой сосед"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-03",
      text: "¿Podría explicarme esto?",
      ru: "Не могли бы вы мне это объяснить?",
      component: "попросить вежливо",
      function: "мягко попросить объяснение",
      isChunk: false,
      rarestWordRank: 1400,
      contexts: ["банк", "приём у врача"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-04",
      text: "¿Puede hablar más despacio?",
      ru: "Говорите, пожалуйста, помедленнее.",
      component: "попросить вежливо",
      function: "попросить говорить медленнее",
      isChunk: false,
      rarestWordRank: 1500,
      contexts: ["магазин", "телефон"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-05",
      text: "¿Puede repetir eso, por favor?",
      ru: "Повторите, пожалуйста, ещё раз.",
      component: "попросить вежливо",
      function: "попросить повторить",
      isChunk: true,
      rarestWordRank: 1000,
      contexts: ["клиника", "телефон"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-06",
      text: "¿Me permite pasar, por favor?",
      ru: "Разрешите пройти.",
      component: "попросить вежливо",
      function: "попросить пропустить",
      isChunk: false,
      rarestWordRank: 1600,
      contexts: ["автобус", "очередь"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-07",
      text: "¿Podría darme la dirección?",
      ru: "Не подскажете адрес?",
      component: "попросить вежливо",
      function: "попросить адрес",
      isChunk: false,
      rarestWordRank: 1400,
      contexts: ["турагентство", "запись в клинику"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-08",
      text: "¿Podrías acompañarme al banco?",
      ru: "Сходишь со мной в банк?",
      component: "попросить вежливо",
      function: "попросить сопровождение",
      isChunk: false,
      rarestWordRank: 1700,
      contexts: ["семья", "близкий друг"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-09",
      text: "¿Puedo dejar aquí mi maleta?",
      ru: "Чемодан можно тут оставить?",
      component: "попросить вежливо",
      function: "попросить разрешения оставить вещь",
      isChunk: false,
      rarestWordRank: 1850,
      contexts: ["ресепшен", "зал ожидания"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-10",
      text: "¿Puede guardarme el sitio?",
      ru: "Займёте мне место?",
      component: "попросить вежливо",
      function: "попросить придержать место",
      isChunk: false,
      rarestWordRank: 1900,
      contexts: ["очередь в клинике", "кафе"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-11",
      text: "Puedo ayudar con las bolsas.",
      ru: "Помогу с сумками.",
      component: "предложить помощь",
      function: "предложить помощь с вещами",
      isChunk: false,
      rarestWordRank: 1300,
      contexts: ["соседка с покупками", "аэропорт"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-12",
      text: "Puedo llevarlo al médico.",
      ru: "Могу отвезти его к врачу.",
      component: "предложить помощь",
      function: "предложить сопровождение к врачу",
      isChunk: false,
      rarestWordRank: 1500,
      contexts: ["родственник", "сосед"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-13",
      text: "Puedo esperar aquí con usted.",
      ru: "Подожду здесь вместе с вами.",
      component: "предложить помощь",
      function: "предложить компанию",
      isChunk: false,
      rarestWordRank: 1000,
      contexts: ["очередь в поликлинике", "аэропорт"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-14",
      text: "¿Le ayudo con eso?",
      ru: "Вам помочь с этим?",
      component: "предложить помощь",
      function: "предложить помощь сразу",
      isChunk: true,
      rarestWordRank: 1000,
      contexts: ["человек не справляется", "магазин"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-15",
      text: "Puedo traerle un vaso de agua.",
      ru: "Принесу вам воды.",
      component: "предложить помощь",
      function: "предложить конкретную помощь",
      isChunk: false,
      rarestWordRank: 1500,
      contexts: ["гостю плохо", "дом"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-16",
      text: "Puedo explicarle el camino.",
      ru: "Дорогу объясню.",
      component: "предложить помощь",
      function: "предложить объяснить маршрут",
      isChunk: false,
      rarestWordRank: 1400,
      contexts: ["растерянный турист", "новый сосед"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-17",
      text: "¿Puedo ayudarle en algo?",
      ru: "Чем-нибудь вам помочь?",
      component: "предложить помощь",
      function: "предложить помощь при первом контакте",
      isChunk: true,
      rarestWordRank: 1000,
      contexts: ["улица", "магазин"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-18",
      text: "Puedo venir mañana si necesita.",
      ru: "Если нужно, завтра приду.",
      component: "сказать о возможности",
      function: "предложить доступность позже",
      isChunk: false,
      rarestWordRank: 900,
      contexts: ["визит к врачу", "мастер по ремонту"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-19",
      text: "No puedo ahora, pero sí más tarde.",
      ru: "Сейчас никак, а позже смогу.",
      component: "сказать о возможности",
      function: "отложить помощь на другое время",
      isChunk: false,
      rarestWordRank: 1450,
      contexts: ["срочная просьба соседа", "работа"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-20",
      text: "¿Puede venir mañana a las diez?",
      ru: "Придёте завтра к десяти?",
      component: "сказать о возможности",
      function: "уточнить возможность визита",
      isChunk: false,
      rarestWordRank: 900,
      contexts: ["запись к врачу", "мастер"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-21",
      text: "¿Es posible cambiar la cita?",
      ru: "Приём перенести можно?",
      component: "сказать о возможности",
      function: "спросить о переносе записи",
      isChunk: false,
      rarestWordRank: 1300,
      contexts: ["поликлиника", "салон"],
      interactionModes: ["recognition", "production"],
    },
    {
      id: "es-l10-22",
      text: "Puedo llamar si hay un problema.",
      ru: "Если что-то случится, позвоню.",
      component: "сказать о возможности",
      function: "предложить связь на случай трудностей",
      isChunk: false,
      rarestWordRank: 1200,
      contexts: ["присмотр за квартирой", "перед поездкой"],
      interactionModes: ["recognition", "production"],
    },
  ] as const);
