// AUTO-GENERATED by scripts/upload_achievement_images_to_storage.mjs — DO NOT EDIT BY HAND.
// Maps achievement id -> Firebase Storage download URL. Позволяет стримить и
// дисково кэшировать остальной актуальный арт вместо включения его в бинарь.
// Читается через constants/achievementImageAssets.ts; «ядро» из
// constants/achievementCoreArt.ts остаётся в бандле и сюда не попадает.
// Entries: 35.

export const ACHIEVEMENT_IMAGE_URL_MAP: Readonly<Record<string, string>> = {
  "league_champion": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fleague_champion.webp?alt=media&token=3201b72b-49d1-4c15-b50f-9066fb958283",
  "league_champion_10": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fleague_champion_10.webp?alt=media&token=56cbb8fb-2665-48ba-b5b5-5f4c1b42dd0e",
  "league_champion_5": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fleague_champion_5.webp?alt=media&token=b10d74de-a04f-4ea1-8d8c-1103f1a26307",
  "league_diamond": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fleague_diamond.webp?alt=media&token=45a31fc4-7472-456a-b65f-7f5c8e0518de",
  "league_diamond_4_weeks": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fleague_diamond_4_weeks.webp?alt=media&token=520791df-12df-41be-a880-578d12b65dc8",
  "recall_50": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Frecall_50.webp?alt=media&token=0fefe2a7-86e7-47d7-8512-7764abc92b9a",
  "shards_1000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fshards_1000.webp?alt=media&token=af2f0daf-029d-4304-af0a-6ecced4183b4",
  "shards_250": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fshards_250.webp?alt=media&token=2cd6916b-3b02-4eb7-9428-c39e99150900",
  "shards_500": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fshards_500.webp?alt=media&token=288eeabd-92bb-463b-a6cc-27943c446b3e",
  "streak_100": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_100.webp?alt=media&token=7f0ba977-9bb5-4163-b71b-bb953c7b09a9",
  "streak_1000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_1000.webp?alt=media&token=1895a428-3932-4cf5-9abe-a558ee62447f",
  "streak_14": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_14.webp?alt=media&token=9c16cce3-3516-4688-bb79-c1329e3f4224",
  "streak_150": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_150.webp?alt=media&token=ff5cd25d-bfdc-4e0a-aba5-7a7ab9488b34",
  "streak_200": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_200.webp?alt=media&token=af2f69ac-326c-460a-9200-ea3d5fd6fe16",
  "streak_250": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_250.webp?alt=media&token=2836602f-7ae9-4864-bf69-2a714933bd08",
  "streak_30": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_30.webp?alt=media&token=ca5237d7-105b-4848-a716-3a1a75c0b803",
  "streak_365": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_365.webp?alt=media&token=ef14e4c2-7892-4a55-b06d-dab0cdcdc275",
  "streak_500": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_500.webp?alt=media&token=51e3af81-0538-4d1d-a7f9-e2434d11049d",
  "streak_60": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_60.webp?alt=media&token=73294736-5622-4dfe-918b-8b2fc83caf99",
  "streak_750": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_750.webp?alt=media&token=ce85fac2-c272-47f6-b246-7b0618095308",
  "streak_clean_365": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fstreak_clean_365.webp?alt=media&token=4e689e8d-5a34-4faf-8b77-fd0630524518",
  "xp_1000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_1000.webp?alt=media&token=4f9bb60e-1beb-4e96-95ce-126ba00830b2",
  "xp_10000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_10000.webp?alt=media&token=ee49b3f6-304a-41f0-a883-2673c5bf014f",
  "xp_100000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_100000.webp?alt=media&token=c2a05ab3-0f8b-49f7-9d68-9c353909f375",
  "xp_1000000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_1000000.webp?alt=media&token=7fd621b7-0bc9-4e3e-b378-834672156e93",
  "xp_150000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_150000.webp?alt=media&token=f0f8a3ff-635f-4ab8-9735-547c6546307b",
  "xp_20000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_20000.webp?alt=media&token=a008da00-e645-492c-88ec-ed4cfe623b1c",
  "xp_2000000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_2000000.webp?alt=media&token=8f983805-b7f7-492c-8cb2-37ca6d3dbda5",
  "xp_2500": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_2500.webp?alt=media&token=8d4fae58-1944-4e07-9892-6fff0ca2d162",
  "xp_250000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_250000.webp?alt=media&token=87b8e46c-820b-412b-a27b-0c7eac0113fb",
  "xp_5000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_5000.webp?alt=media&token=b55e7e76-2cc2-4dfa-9145-bbfe9c128fe7",
  "xp_50000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_50000.webp?alt=media&token=75a3fdd8-b4aa-4a01-8282-f8262b5fc48c",
  "xp_500000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_500000.webp?alt=media&token=12ee4e9f-1959-4db7-8a3d-7709d993b5f6",
  "xp_75000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_75000.webp?alt=media&token=d3c9499e-0249-4b08-af8c-5f81df2fd146",
  "xp_750000": "https://firebasestorage.googleapis.com/v0/b/phraseman-ea0b3.firebasestorage.app/o/achievement-images%2Fxp_750000.webp?alt=media&token=7cb9d0d1-a33a-4d41-885f-f7af06d054b2",
};

/** URL удалённого арта достижения (undefined — значит арт в бандле или его нет). */
export function getAchievementImageUrl(id: string): string | undefined {
  return ACHIEVEMENT_IMAGE_URL_MAP[id];
}
