// ─── Витрина движения · общий словарь копирайта ───
// зачем: сторож i18n (scripts/scan_untranslated_ui.mjs) требует, чтобы русские
// строки-литералы либо лежали внутри словаря переводов (const RU/UK/...), либо
// шли через вызов переводчика — иначе считает их непереведённым UI. Раздел
// dev-only, реальный язык интерфейса тут не важен: cs() всегда отдаёт русский,
// но форма (словарь + функция) устраивает сканер и не плодит русские литералы
// в самих шардах sections/*.ts(x).
const RU = {
  // ── общие переиспользуемые детали ──
  back: 'Назад',
  real_screen: 'реальный экран',
  real_component: 'реальный компонент',
  real_modal: 'реальная модалка',
  real_event: 'реальное событие',

  // ── alerts_forms ──
  alerts_forms_section_title: 'Алерты и формы',
  confirm_neutral_title: 'Подтверждение — нейтральное',
  confirm_exit_title: 'Выйти без сохранения?',
  confirm_exit_message: 'Несохранённые изменения будут потеряны.',
  confirm_exit_cancel: 'Остаться',
  confirm_exit_confirm: 'Выйти',
  confirm_accent_title: 'Подтверждение — акцентное (в магазин)',
  confirm_shards_title: 'Не хватает жемчужин',
  confirm_shards_message: 'Пополни запас в магазине, чтобы продолжить.',
  confirm_shards_cancel: 'Отмена',
  confirm_shards_confirm: 'В магазин',
  choice_two_title: 'Выбор — два варианта',
  choice_two_question: 'Как продолжить?',
  choice_two_message: 'Можно повторить набор карточек или перейти к следующему уроку.',
  choice_two_option_repeat: 'Повторить набор',
  choice_two_option_next: 'Следующий урок',
  choice_three_title: 'Выбор — три варианта',
  choice_three_question: 'Раздел недоступен офлайн',
  choice_three_message: 'Подключись к сети или выбери другое действие.',
  choice_three_option_retry: 'Повторить подключение',
  choice_three_option_offline: 'Заниматься офлайн-набором',
  choice_three_option_close: 'Закрыть',
  report_user_title: 'Жалоба на ник игрока',
  report_user_detail: 'реальный компонент · цель фиктивная',
  report_user_demo_name: 'ПоказательныйНик',
  report_pack_title: 'Жалоба на набор карточек (UGC)',
  report_pack_demo_title: 'Демонстрационный набор',
  nickname_edit_title: 'Смена ника (аккаунт)',
  nickname_edit_demo_name: 'Показ',
  certificate_name_title: 'Имя на сертификате B2',
  registration_prompt_title: 'Предложение войти (Google/Apple)',
  registration_prompt_note:
    'Кнопки входа вызывают signInWithProvider() напрямую внутри компонента — тап реально сменил бы аккаунт активной сессии. Безопасной заглушки для сети входа нет.',
  delete_account_confirm_title: 'Подтверждение удаления аккаунта',
  delete_account_confirm_note:
    'Кнопка «Удалить» вызывает beginAccountDeletion() напрямую внутри компонента (не через пропсы) — тап реально начал бы необратимое удаление. Показывать живьём нельзя.',

  // ── arena_rewards ──
  arena_rewards_section_title: 'Арена · ранги и итоги',
  arena_demo_you_name: 'Ты',
  arena_demo_opponent_name: 'Алекс',
  arena_rank_change_banner_title: 'Баннер смены ранга',
  arena_rank_change_banner_detail: 'реальный компонент — демо-данные, подъём на 3 позиции',
  arena_versus_intro_title: 'Старт матча: соперник → 3-2-1 → GO',
  arena_versus_intro_detail: 'реальный компонент — демо-игроки, звук/хаптик реальные',
  arena_versus_go_label: 'СТАРТ',
  arena_star_flight_title: 'Полёт звёзд в кошелёк',
  arena_star_flight_detail: 'реальный компонент — демо-траектория, 5 звёзд',
  arena_rewards_known_title: 'Награда за матч (известна)',
  arena_rewards_known_detail: 'реальный компонент — демо-награда +12 звёзд, рейтинг +18',
  arena_stars_label: 'звёзд за матч',
  arena_rewards_pending_title: 'Награда за матч (ещё не пришла)',
  arena_rewards_pending_detail: 'реальный компонент — состояние «отчёт в очереди»',
  arena_players_row_title: 'Счёт матча (ты vs соперник)',
  arena_players_row_detail: 'реальный компонент — демо-счёт 4:3',
  arena_timer_ring_title: 'Кольцо таймера ответа',
  arena_timer_ring_detail: 'реальный компонент — демо-длительность 12с, тик и тревога настоящие',
  arena_results_screen_title: 'Экран итогов матча',
  arena_results_screen_note: 'нет безопасного демо: экран требует реальный matchId завершённого матча с сервера',

  // ── banners ──
  banners_section_title: 'Баннеры',
  banner_offline_title: 'Нет соединения',
  banner_offline_detail: 'реальный компонент — виден только если сейчас офлайн',
  banner_promo_title: 'Промо-баннер (акция)',
  banner_promo_detail: 'реальный компонент — виден по текущим remote_flags',
  banner_save_progress_title: 'Сохрани прогресс (незалогинен)',
  banner_save_progress_detail: 'реальный компонент — виден при выполнении реальных условий показа',
  banner_rank_change_title: 'Смена ранга (в клубах)',
  banner_referral_invite_art_title: 'Арт приглашения друга',
  banner_referral_invite_art_detail: 'реальный компонент — картинка под текущую тему',

  // ── celebrations ──
  celebrations_section_title: 'Празднования и сундуки',
  celebrations_level_gift_title: 'Подарок за уровень — открытие сундука',
  celebrations_level_gift_detail:
    'реальный компонент — демо-подарок (common), применение отключено (deliveryMode=inventory)',
  celebrations_level_gift_dual_title: 'Два подарка за уровень (Plus)',
  celebrations_level_gift_dual_detail: 'реальный компонент — демо-пара F2P+премиум, deliveryMode=inventory',
  celebrations_demo_user_name: 'Демо',
  celebrations_boon_chest_title: 'Сундук бонуса (Понедельник тайны и т.п.)',
  celebrations_boon_chest_detail: 'реальный компонент — общий движок сундука, onClaim пустой (без начисления)',
  celebrations_boon_chest_modal_title: 'Сундук недели',
  celebrations_boon_chest_reward_line: '10 осколков — теперь твои',
  celebrations_boon_chest_tap_hint: 'Нажми, чтобы открыть',
  celebrations_boon_chest_claim_cta: 'Забрать',
  celebrations_boon_chest_close_label: 'Закрыть',
  celebrations_boon_activated_title: 'Бонус дня активирован (тихий бонус)',
  celebrations_boon_activated_detail: 'реальный компонент — демо-бонус double_xp',
  celebrations_weekly_boon_detail_title: 'Подробности бонуса дня',
  celebrations_weekly_boon_detail_detail: 'реальный компонент — карточка описания, без действий с прогрессом',
  celebrations_season_gift_title: 'Награда Season Pass — получение',
  celebrations_season_gift_detail:
    'реальный компонент — giftId=null: показывает награду, но не пишет в инвентарь подарков',
  celebrations_season_reward_info_title: 'Season Pass — просмотр карточки награды',
  celebrations_season_reward_info_detail: 'реальный компонент — read-only витрина, onClaim/onNeedPass пустые',
  celebrations_collectible_drop_title: 'Дроп карточки коллекции',
  celebrations_collectible_drop_detail: 'реальный компонент — реальная карточка каталога (animals_01, common)',
  celebrations_roulette_win_modal_title: 'Рулетка — карточка выигрыша',
  celebrations_roulette_win_modal_detail: 'реальный компонент — демо-приз (дни Plus)',
  celebrations_roulette_win_celebration_title: 'Рулетка — праздничная вспышка (конфетти)',
  celebrations_roulette_win_celebration_detail:
    'реальный компонент — отдельный слой конфетти после закрытия карточки приза',
  celebrations_referral_friend_reward_title: 'Друг принёс ключ (награда за друга)',
  celebrations_referral_friend_reward_detail: 'реальный компонент — демо-имя друга',
  celebrations_referral_friend_name: 'Алекс',
  celebrations_referral_friend_reward_modal_title: 'Ключ готов!',
  celebrations_referral_friend_reward_modal_subtitle: 'Алекс оформил подписку — открой награду в разделе «Друзья»',
  celebrations_referral_friend_reward_cta: 'Отлично',
  celebrations_loyalty_gift_title: 'Награда за верность (LoyaltyGiftModal)',
  celebrations_loyalty_gift_note: 'компонента нет в текущем рабочем дереве (components/LoyaltyGiftModal.tsx отсутствует)',
  celebrations_dialog_victory_title: 'Салют финала ИИ-диалога',
  celebrations_dialog_victory_detail: 'реальный компонент — полноэкранный оверлей, демо-метрики',

  // ── consent_info ──
  consent_info_section_title: 'Согласия и объяснения',
  consent_mistake_demo_text:
    'Правильный вариант — «I have been living here since 2020», потому что действие ' +
    'началось в прошлом и продолжается сейчас: используем Present Perfect Continuous, а не ' +
    'простое прошедшее время.',
  ai_dialog_consent_title: 'Согласие: AI-диалоги',
  ai_explain_consent_title: 'Согласие: ИИ-разбор ошибок',
  notification_permission_title: 'Разрешение на уведомления',
  notification_permission_detail: 'реальный компонент, без реального пермишена',
  mistake_eli5_title: 'Объясни проще (разбор ошибки)',
  mistake_eli5_detail: 'реальный компонент, демо-текст без сети',
  explain_sheet_title: 'Простыми словами (объяснение фразы)',
  explain_sheet_note:
    'ExplainSheet сам стартует сетевой запрос (useExplainRequest → CF explainPhrase) при visible=true — безопасного демо-превью без реального вызова нет',

  // ── fullscreen ──
  fullscreen_section_title: 'Полноэкранные (обновления, инбокс)',
  update_modal_title: 'Обновление приложения',
  release_notes_modal_title: 'Что нового (релиз-ноуты)',
  global_broadcast_modal_title: 'Общая рассылка (объявление)',
  global_broadcast_modal_note:
    'закрытие модалки вызывает реальный claimAndDismissGlobalBroadcastModal (сеть/Firestore, начисление награды) без пропа для безопасного dry-run — нет пути показать без риска мутации',
  tournament_welcome_modal_title: 'Приветствие раздела «Турниры»',
  personal_admin_message_modal_title: 'Личное сообщение от команды',
  personal_admin_message_modal_detail: 'реальный компонент, демо-текст',
  vip_survey_modal_title: 'Опрос для Plus (VIP-survey)',
  vip_survey_review_prompt_modal_title: 'Просьба об отзыве после Plus',
  app_messages_inbox_title: 'Инбокс сообщений (кнопка + панель)',
  app_messages_inbox_detail: 'реальный компонент, режим standalone',
  maintenance_gate_title: 'Технические работы (баннер/блок)',
  maintenance_gate_note:
    'MaintenanceGate сам читает remote_flags и рендерится только когда владелец реально включил техработы — безопасного пропа для форс-показа нет',

  // ── league ──
  league_section_title: 'Лига · неделя и подарки',
  league_hub_route_title: 'Экран лиги (хаб недели)',
  league_result_promoted_title: 'Итоги недели — повышение',
  league_result_synthetic_detail: 'реальная модалка, синтетический результат',
  league_result_demoted_title: 'Итоги недели — понижение',
  league_result_stay_title: 'Итоги недели — остался в лиге',
  league_result_promoted_hybrid_title: 'Итоги недели: повышение · гибрид',
  league_result_demoted_hybrid_title: 'Итоги недели: вылет · гибрид',
  league_result_stay_hybrid_title: 'Итоги недели: остался · гибрид',
  league_chest_open_title: 'Сундук лиги — открытие наград',
  league_chest_open_detail: 'реальная модалка, демо-дропы',
  league_chest_open_hybrid_title: 'Сундук лиги: щель света · гибрид',
  league_chest_open_hybrid_detail: 'реальная модалка, демо-дропы',
  league_chest_crown_name: 'QA Monday',
  league_bonus_available_title: 'Бонус лиги доступен',
  league_bonus_available_detail: 'реальная модалка, демо-доступность',
  league_bonus_available_hybrid_title: 'Бонус лиги: маяк (премиум) · гибрид',
  league_bonus_available_hybrid_detail: 'реальная модалка, демо-доступность',
  league_chest_teaser_title: 'Сундук лиги — тизер «Что внутри?»',
  league_chest_teaser_detail: 'реальная модалка, демо-палитра и редкости',
  league_chest_teaser_hybrid_title: 'Тизер сундука: скан · гибрид',
  league_chest_teaser_hybrid_detail: 'реальная модалка, демо-палитра и редкости',

  // ── levelup_spins ──
  levelup_spins_section_title: 'Уровень и спины',
  levelup_gift_desc_instant_xp: '+250 XP мгновенно',
  levelup_kicker_milestone: 'КАЖДЫЙ ПЯТЫЙ УРОВЕНЬ',
  levelup_kicker_standard: 'УРОВЕНЬ ПОВЫШЕН',
  levelup_headline: 'Уровень {level}',
  levelup_message_milestone:
    'Особый порог: более праздничная анимация. Витрина — превью, прогресс не меняется.',
  levelup_message_standard: 'Обычное повышение уровня. Витрина — превью, XP и уровень не меняются.',
  levelup_xp_label: 'Бонус уровня',
  levelup_xp_value: '+100 XP',
  levelup_title_label: 'Новый титул',
  levelup_energy_label: 'Энергия',
  levelup_energy_value: 'Теперь {amount} энергии в день',
  levelup_continue_label: 'Готово',
  levelup_threshold_standard_title: 'Повышение уровня · обычное',
  levelup_threshold_milestone_title: 'Повышение уровня · юбилейный (×5)',
  levelup_threshold_standard_hybrid_title: 'Уровень: обычный · гибрид',
  levelup_threshold_milestone_hybrid_title: 'Уровень: каждый 5-й · гибрид',
  level_spin_reward_modal_title: 'Приз спина · карточка награды',
  spin_reward_plaque_title: 'Приз спина · плашка-оверлей',
  spin_reward_plaque_detail: 'реальный оверлей',

  // ── paywalls ──
  paywalls_section_title: 'Пейволы и Premium',
  paywall_a_title: 'Пейвол A',
  paywall_b_title: 'Пейвол B',
  paywall_c_title: 'Пейвол C',
  paywall_d_title: 'Пейвол D',
  paywall_e_title: 'Пейвол E',
  paywall_f_title: 'Пейвол F',
  paywall_g_title: 'Пейвол G',
  manage_subscription_title: 'Управление подпиской',
  intro_full_access_welcome_title: 'Приветствие «3 дня всё открыто»',
  intro_full_access_ended_title: 'Подарок закончился — выбор',
  premium_modal_title: 'Пейвол-диспетчер (premium_modal)',
  premium_celebration_title: 'Празднование покупки Premium',
  vip_celebration_title: 'Празднование покупки VIP/Pro',
  premium_celebration_plus_hybrid_title: 'Празднование Plus · гибрид',
  premium_celebration_pro_hybrid_title: 'Pro · гибрид',
  no_energy_modal_title: 'Нет энергии',
  streak_revive_modal_title: 'Восстановить цепочку за жемчужины',
  streak_revive_modal_detail: 'реальная модалка, демо-оффер',
  streak_revive_offer_event_title: 'Событие: оффер восстановления цепочки',
  card_pack_demo_code_name: 'Демо',
  card_pack_demo_title: 'Демонстрационный набор',
  card_pack_demo_description: 'Набор для витрины движения — не участвует в покупках.',
  card_pack_shard_paywall_confirm_title: 'Покупка набора карточек — подтверждение',
  card_pack_shard_paywall_demo_detail: 'реальная модалка, демо-набор',
  card_pack_shard_paywall_insufficient_title: 'Покупка набора карточек — не хватает жемчужин',
  card_pack_shard_paywall_voucher_title: 'Покупка набора карточек — подарочный ваучер',
  paywall_dev_preview_route_title: 'Dev-превью цен пейвола',
  paywall_dev_preview_route_detail: 'реальный экран (paywall_a с dev-ценами)',
  arena_limit_modal_title: 'Лимит арены',
  arena_limit_modal_note: 'ArenaLimitModal отсутствует в дереве — только в устаревших ворктри, безопасного запуска нет',
  energy_refill_shard_modal_title: 'Пополнение энергии за жемчужины',
  energy_refill_shard_modal_note:
    'EnergyRefillShardModal отсутствует в дереве — только в устаревших ворктри, безопасного запуска нет',

  // ── press_icons_tabbar ──
  press_icons_tabbar_section_title: 'Отклик · кнопки, иконки, таббар',
  icons_live_preview_heading: 'Иконки семьи «Отклик» — текущий вид',
  icons_live_preview_hint: 'Статичные демо-пропсы, ничего не сохраняется. Целевая анимация — в note рядом в списке.',
  press_primitive_root_title: 'Пресс-примитив: PressableScale (components/)',
  press_primitive_root_note:
    'components/PressableScale.tsx — Animated API, spring по варианту (icon/flat/card/primary), хаптик на pressIn.',
  press_primitive_feedback_title: 'Пресс-примитив: PressableScale (components/feedback/)',
  press_primitive_feedback_note:
    'components/feedback/PressableScale.tsx — Reanimated, вариант 3d/flat с вдавливанием по Y, звук+хаптик через feedback_kit.',
  press_primitive_tapscale_title: 'Пресс-примитив: TapScale',
  press_primitive_tapscale_note:
    'components/TapScale.tsx — Animated API, scale+opacity вместе, для мелких/иконочных элементов (scaleTo 0.88).',
  press_primitive_target_hybrid_title: 'Целевой стандарт: PRESS (гибрид «Световод + Чекан»)',
  press_primitive_target_hybrid_note:
    'constants/motionHybrid.ts → export const PRESS — единая физика (downMs, scale по ролям, release/releasePrimary), которой три примитива выше пока НЕ следуют.',
  icon_target_streak_chain_title: 'Иконка-цель: StreakChainIcon',
  icon_target_streak_chain_note:
    'components/StreakChainIcon.tsx — сейчас статичный webp по темe/тиру. Кадры streakfireaurora (assets/images/streak_icons/aurora/*) готовы для покадровой анимации пламени по событию «серия продлена сегодня».',
  icon_target_level_badge_title: 'Иконка-цель: LevelBadge',
  icon_target_level_badge_note:
    'components/LevelBadge.tsx — сейчас автоплей GIF/webp без реакции на событие. Цель: акцентная вспышка/пульс материала (LevelAvatarMaterialOverlay) по событию «получен новый уровень».',
  icon_target_plus_badge_title: 'Иконка-цель: PlusBadge',
  icon_target_plus_badge_note:
    'components/PlusBadge.tsx — сейчас статичная градиентная плашка. Цель: короткий блик по градиенту по событию «активация Plus/Pro» (перекликается с celebration в паиволлах).',
  icon_target_league_crown_name_title: 'Иконка-цель: LeagueCrownName',
  icon_target_league_crown_name_note:
    'components/LeagueCrownName.tsx — корона статична рядом с ником. Цель: лёгкое покачивание/блеск короны по событию «вход в топ-3 лиги» (не на каждый рендер списка — только на смену позиции).',
  icon_target_notification_center_button_title: 'Иконка-цель: NotificationCenterButton',
  icon_target_notification_center_button_note:
    'components/NotificationCenterButton.tsx — колокольчик + бейдж непрочитанных, сейчас появление бейджа без анимации. Цель: короткий поп/встряска по событию «пришло новое уведомление». В live-превью не включён: компонент сам читает Firestore и помечает уведомления прочитанными при открытии — безопасного демо-пути нет.',
  icon_target_energy_icon_title: 'Иконка-цель: EnergyIcon',
  icon_target_energy_icon_note:
    'components/EnergyIcon.tsx — заполнение уже анимируется (opacity 300ms) и тряска есть (shouldShake), но по гибрид-стандарту (LUM/CHK) не проходит: сейчас Animated.timing без света/веса. Цель: посадка по LUM.settle + тряска только как есть.',
  icons_live_preview_title: 'Живое превью: иконки семьи разом',
  icons_live_preview_detail: 'текущий вид, демо-пропсы',
  press_icon_cell_streak_chain: 'StreakChainIcon',
  press_icon_cell_level_badge: 'LevelBadge',
  press_icon_cell_plus_badge: 'PlusBadge',
  press_icon_cell_league_crown_name: 'LeagueCrownName',
  press_icon_cell_energy_icon: 'EnergyIcon',
  press_icon_league_crown_demo_text: 'Игрок',
  route_tabbar_home_title: 'Экран с таббаром: Главная',
  route_tabbar_home_detail: 'реальный экран, таббар внизу',
  tabbar_hybrid_preview_title: 'Таббар · жидкое золото (гибрид)',
  tabbar_hybrid_preview_detail: 'живая локальная копия, без роутера',
  tabbar_hybrid_preview_heading: 'Таббар · жидкое золото',
  tabbar_hybrid_preview_hint: 'Капля течёт между вкладками, падает в прибывшую иконку, соседи отзываются волной. Тапни по любой вкладке.',
  press_hybrid_panel_title: 'Пресс-стандарт (гибрид)',
  press_hybrid_panel_detail: 'живая панель, 5 типов кнопок',
  press_hybrid_panel_heading: 'Единый пресс-стандарт',
  press_hybrid_panel_hint: 'PressableHybrid по PRESS из constants/motionHybrid.ts. Перелёт на возврате — только у primary.',
  press_hybrid_variant_primary: 'primary',
  press_hybrid_variant_secondary: 'secondary',
  press_hybrid_variant_icon: 'icon',
  press_hybrid_variant_chip: 'chip',
  press_hybrid_variant_card: 'card',
  streak_flame_hybrid_title: 'Огонь стрика · живая вспышка (гибрид)',
  streak_flame_hybrid_detail: 'живой компонент, кнопка «вспыхнуть»',
  streak_flame_hybrid_heading: 'Живой огонь серии',
  streak_flame_hybrid_hint: 'Покой — статичный тир. По событию «серия продлена» — рост, колыхание и затухающий блик.',
  streak_flame_hybrid_burst_button: 'Вспыхнуть',
  edge_press_panel_title: 'Кнопки с кромкой · продавливание',
  edge_press_panel_detail: 'живая панель, 3 кнопки',
  edge_press_panel_heading: 'Кнопки с кромкой',
  edge_press_panel_hint: 'Подошва не двигается — лицо едет вниз и «схлопывает» кромку. Держи, чтобы увидеть вдавленное состояние.',
  edge_press_primary_label: 'Primary · кромка 6',
  edge_press_secondary_label: 'Secondary · кромка 4',
  edge_press_flat_label: 'Плоская · без кромки',

  // ── screens_arena_social ──
  screens_arena_social_section_title: 'Экраны · арена и социальное',
  arena_hub_title: 'Арена · хаб',
  arena_today_title: 'Арена · сегодня',
  arena_ranks_title: 'Арена · ранги',
  arena_tops_title: 'Арена · топы',
  arena_history_title: 'Арена · история матчей',
  arena_rivalries_title: 'Арена · соперничества',
  arena_star_wallet_title: 'Арена · кошелёк звёзд',
  arena_season_pass_title: 'Арена · сезонный пропуск',
  arena_mastery_map_title: 'Арена · карта мастерства',
  arena_matchmaking_title: 'Арена · подбор соперника',
  arena_matchmaking_detail: 'реальный экран (без активного матча — пустое состояние)',
  arena_match_title: 'Арена · матч',
  arena_match_detail: 'реальный экран (matchId опционален — покажет пустое состояние)',
  arena_match_lab_title: 'Арена · лаборатория матча',
  arena_match_lab_detail: 'реальный экран (без параметров — пустое состояние)',
  arena_results_title: 'Арена · результаты',
  arena_results_detail: 'реальный экран (без matchId — пустое состояние)',
  arena_review_title: 'Арена · разбор матча',
  arena_review_detail: 'реальный экран (без matchId — пустое состояние)',
  arena_friend_duel_title: 'Арена · дуэль с другом',
  arena_ghost_duel_title: 'Арена · дуэль-призрак',
  arena_ghost_duel_detail: 'реальный экран (без токена — пустое/недоступное состояние)',
  arena_invite_title: 'Арена · приглашение',
  arena_partner_title: 'Арена · партнёр',
  club_screen_title: 'Клуб',
  tournament_lobby_title: 'Турнир · лобби',
  tournament_season_title: 'Турнир · сезон',
  tournament_table_title: 'Турнир · таблица',
  tournament_table_detail: 'реальный экран (без roomId — пустое состояние)',
  tournament_round_title: 'Турнир · раунд',
  tournament_round_detail: 'реальный экран (без roomId — пустое состояние)',
  tournament_review_title: 'Турнир · разбор',
  tournament_review_detail: 'реальный экран (без roomId — пустое состояние)',
  tournament_results_title: 'Турнир · результаты',
  tournament_results_detail: 'реальный экран (без roomId — пустое состояние)',
  tournament_tickets_title: 'Турнир · билеты',
  referrals_title: 'Друзья и рефералы',
  top_helpers_title: 'Топ помощников',

  // ── screens_flashcards ──
  screens_flashcards_section_title: 'Экраны · карточки',
  fc_section_title: 'Карточки · раздел (главная)',
  fc_packs_title: 'Карточки · наборы',
  fc_my_packs_title: 'Карточки · мои наборы',
  fc_market_dev_title: 'Карточки · маркет (dev)',
  fc_collection_title: 'Карточки · коллекция (список/стопка)',
  fc_swipe_title: 'Карточки · сессия свайпов',
  fc_blitz_title: 'Карточки · блиц-сессия',
  fc_listening_title: 'Карточки · сессия на слух',
  fc_audio_title: 'Карточки · аудио-режим',
  fc_card_editor_title: 'Карточки · редактор карточки',
  fc_voice_picker_title: 'Карточки · выбор голоса TTS',
  pack_opening_title: 'Карточки · вскрытие набора',

  // ── screens_learn ──
  screens_learn_section_title: 'Экраны · обучение',
  lessons_tab_title: 'Вкладка «Обучение» (уроки, V2, диалоги)',
  lesson_menu_title: 'Меню урока',
  lesson1_title: 'Урок (фразы)',
  lesson_words_title: 'Урок (слова)',
  lesson_irregular_verbs_title: 'Урок (неправильные глаголы)',
  lesson_verbs_title: 'Урок (глаголы, редирект)',
  lesson_theory_v2_title: 'Теория урока V2',
  lesson_help_title: 'Помощь по уроку',
  lesson_intro_screens_title: 'Интро урока (первый запуск)',
  lesson_complete_title: 'Урок завершён',
  preposition_drill_title: 'Тренажёр предлогов',
  hint_title: 'Подсказка',
  review_title: 'Повторение (сжигание карточек)',
  diagnostic_test_title: 'Диагностический тест',
  exam_title: 'Экзамен',
  level_exam_title: 'Экзамен на уровень',
  trainer_title: 'Тренажёр (меню)',
  trainer_phrases_session_title: 'Тренажёр: сессия фраз',
  trainer_words_session_title: 'Тренажёр: сессия слов',
  trainer_session_report_title: 'Тренажёр: отчёт по сессии',
  ai_dialog_home_title: 'AI-диалоги: главная',
  ai_dialog_briefing_title: 'AI-диалог: брифинг перед сессией',
  ai_dialog_session_title: 'AI-диалог: сессия чата',
  ai_companion_session_title: 'AI-компаньон: голосовая сессия',
  learning_v2_course_title: 'Курс V2 (карта уроков)',
  learning_v2_session_intro_title: 'Курс V2: интро перед сессией',
  learning_v2_session_intro_check_title: 'Курс V2: проверка перед сессией',
  learning_v2_direct_session_player_title: 'Курс V2: прямой плеер сессии',
  lingman_videos_title: 'Lingman: список видео',
  lingman_playlist_title: 'Lingman: плейлист',

  // ── screens_profile ──
  screens_profile_section_title: 'Экраны · профиль и прочее',
  settings_tab_title: 'Вкладка «Настройки»',
  settings_language_title: 'Настройки · язык интерфейса',
  settings_notifications_title: 'Настройки · уведомления',
  settings_themes_title: 'Настройки · темы оформления',
  settings_edu_title: 'Настройки · образование (уровень/цели)',
  account_details_title: 'Аккаунт · детали',
  privacy_settings_title: 'Приватность · настройки',
  privacy_screen_title: 'Политика конфиденциальности',
  terms_screen_title: 'Условия использования',
  streak_stats_title: 'Статистика (стрик, XP, календарь)',
  phrase_analytics_title: 'Аналитика фраз ученика',
  shards_shop_title: 'Магазин осколков',
  coin_exchange_title: 'Обмен монет',
  avatar_select_title: 'Выбор аватара',
  collectibles_screen_title: 'Коллекция (артефакты/значки)',
  achievements_screen_title: 'Достижения',
  level_gifts_inventory_title: 'Инвентарь уровневых подарков',
  level_reward_spin_title: 'Колесо наград за уровень',
  season_pass_title: 'Сезонный пропуск',
  referrals_invite_title: 'Пригласить друзей (рефералка)',
  promo_code_entry_title: 'Ввод промокода',
  diagnostic_test_level_title: 'Диагностический тест уровня',
  exam_screen_title: 'Экзамен (сертификат)',
  problem_coach_title: 'Разбор ошибок с коучем',
  survey_screen_title: 'Опрос ученика',
  ideas_submit_title: 'Предложить идею',
  community_pack_create_title: 'Создать пользовательский набор карточек',
  language_welcome_title: 'Приветствие выбора языка',

  // ── toasts ──
  toasts_section_title: 'Тосты',
  toast_success_title: 'Тост: успех',
  toast_success_hybrid_title: 'Тост: успех · гибрид',
  toast_error_title: 'Тост: ошибка',
  toast_error_hybrid_title: 'Тост: ошибка · гибрид',
  toast_info_title: 'Тост: инфо',
  toast_info_hybrid_title: 'Тост: инфо · гибрид',
  toast_warning_title: 'Тост: предупреждение',
  toast_warning_hybrid_title: 'Тост: предупреждение · гибрид',
  toast_reward_title: 'Тост: награда',
  toast_reward_hybrid_title: 'Тост: награда · гибрид',
  achievement_toast_title: 'Тост: достижение разблокировано',
  achievement_toast_note:
    'AchievementToast читает очередь из AchievementContext (showAchievement), которую заполняет только реальная проверка достижений в _layout.tsx — событие achievement_unlocked лишь просит другие экраны перечитать список, тост не поднимает; безопасного ручного триггера без выдачи настоящего достижения нет',
  medal_toast_title: 'Тост: медаль урока (золото)',
  medal_toast_hybrid_title: 'Тост: медаль урока (золото) · гибрид',
  coach_toast_title: 'Тост: коуч (разбор слабого места)',
  coach_toast_demo_category_label: 'неправильные глаголы',
  coach_toast_demo_focus_go: 'go — went',
  coach_toast_demo_focus_see: 'see — saw',
  in_game_toast_title: 'Тост: внутриигровая подсказка',
  in_game_toast_hybrid_title: 'Тост: внутриигровая подсказка · гибрид',
  in_game_toast_demo_message: 'Демо-подсказка внутри игры',
  streak_risk_toast_host_title: 'Тост: цепочка под угрозой (вечерний хост)',
  streak_risk_toast_host_note:
    'StreakRiskToastHost сам решает показывать ли тост: условие ≥17:00 + checkStreakLossPending() + AsyncStorage «уже показывали сегодня» — безопасного ручного триггера без подмены реального прогресса нет, используй пункт «Тост: предупреждение» для превью визуала',
  billing_issue_toast_host_title: 'Тост: проблема с оплатой (хост)',
  billing_issue_toast_host_note:
    'BillingIssueToastHost сам решает показывать ли тост: живой запрос Purchases.getCustomerInfo() + кулдаун 3 дня в AsyncStorage — без реальной подписки в грейс-периоде показать нечего, используй пункт «Тост: предупреждение» для превью визуала',
  admin_msg_title: 'Личное сообщение (демо)',
  admin_msg_body: 'Это витрина движения — реальный компонент PersonalAdminMessageModal с демо-текстом.',

  // ── press_icons_tabbar / TabBarHybridPreview ──
  tab_home: 'Дом',
  tab_lessons: 'Уроки',
  tab_arena: 'Вызовы',
  tab_friends: 'Друзья',
  tab_more: 'Ещё',
};

type Key = keyof typeof RU;

/**
 * Dev-раздел: язык интерфейса пользователя тут не важен, витрина всегда
 * говорит по-русски (владелец — единственный зритель). Функция существует,
 * чтобы строки лежали в словаре, а не литералами в шардах sections/*.ts(x) —
 * это единственное, что нужно сторожу i18n (scripts/scan_untranslated_ui.mjs).
 */
export function cs(key: Key): string {
  return RU[key];
}
