import { triLang, type Lang } from '../../constants/i18n';

const X = {
  /**
   * Название ПЕРВОГО раздела внутри хаба, а не вкладки. Вкладка внизу уже
   * называется «Сегодня»: два одинаковых слова на одном экране игрок читает
   * как одно и то же место и перестаёт понимать, где он.
   */
  today: ['Обзор', 'Огляд', 'Resumen', 'Visão geral', 'Tổng quan', 'Ringkasan', 'Genel bakış', 'Przegląd'],
  play: ['Играть', 'Грати', 'Jugar', 'Jogar', 'Chơi', 'Main', 'Oyna', 'Graj'],
  growth: ['Рост', 'Розвиток', 'Progreso', 'Progresso', 'Tiến bộ', 'Progres', 'Gelişim', 'Rozwój'],
  together: ['Вместе', 'Разом', 'Juntos', 'Juntos', 'Cùng nhau', 'Bersama', 'Birlikte', 'Razem'],
  wallet: ['Звёздный кошелёк', 'Зоряний гаманець', 'Monedero de estrellas', 'Carteira de estrelas', 'Ví sao', 'Dompet bintang', 'Yıldız cüzdanı', 'Portfel gwiazd'],
  walletShort: ['Кошелёк', 'Гаманець', 'Monedero', 'Carteira', 'Ví sao', 'Dompet', 'Cüzdan', 'Portfel'],
  spendable: ['Доступно для покупок', 'Доступно для покупок', 'Disponible para compras', 'Disponível para compras', 'Có thể dùng để mua', 'Tersedia untuk belanja', 'Alışveriş bakiyesi', 'Dostępne na zakupy'],
  seasonEarned: ['Заработано за сезон', 'Зароблено за сезон', 'Ganadas esta temporada', 'Ganhas na temporada', 'Đã kiếm trong mùa', 'Didapat musim ini', 'Bu sezon kazanılan', 'Zdobyte w sezonie'],
  // Вкладка «Сегодня» — это раздел дня с целями. Заход из десяти заданий —
  // ДРУГОЕ, и называться так же он не может: игрок видел бы «Сегодня» дважды и
  // считал бы, что нажал не туда. Здесь он называется испытанием дня.
  todayTitle: ['Испытание дня', 'Випробування дня', 'Reto del día', 'Desafio do dia', 'Thử thách hôm nay', 'Tantangan harian', 'Günün meydan okuması', 'Wyzwanie dnia'],
  todayBody: ['10 заданий · один короткий заход', '10 завдань · одна коротка сесія', '10 preguntas · una sesión corta', '10 perguntas · uma sessão curta', '10 câu hỏi · một lượt ngắn', '10 soal · satu sesi singkat', '10 soru · kısa bir oturum', '10 pytań · krótka sesja'],
  todayStart: ['Начать 10 заданий', 'Почати 10 завдань', 'Empezar 10 preguntas', 'Começar 10 perguntas', 'Bắt đầu 10 câu', 'Mulai 10 soal', '10 soruya başla', 'Rozpocznij 10 pytań'],
  todayContinue: ['Продолжить испытание', 'Продовжити випробування', 'Continuar el reto', 'Continuar o desafio', 'Tiếp tục thử thách', 'Lanjutkan tantangan', 'Meydan okumaya devam et', 'Kontynuuj wyzwanie'],
  todayComplete: ['Испытание дня пройдено', 'Випробування дня пройдено', 'Reto del día completado', 'Desafio do dia concluído', 'Đã hoàn thành thử thách hôm nay', 'Tantangan harian selesai', 'Günün meydan okuması tamamlandı', 'Wyzwanie dnia ukończone'],
  todayNextDay: ['Новое откроется завтра', 'Нове відкриється завтра', 'El siguiente llega mañana', 'O próximo chega amanhã', 'Thử thách mới mở vào ngày mai', 'Yang baru terbuka besok', 'Yenisi yarın açılır', 'Nowe otworzy się jutro'],
  starsEarned: ['Заработано звёзд: {amount}', 'Зароблено зірок: {amount}', 'Estrellas ganadas: {amount}', 'Estrelas ganhas: {amount}', 'Sao đã kiếm: {amount}', 'Bintang didapat: {amount}', 'Kazanılan yıldız: {amount}', 'Zdobyte gwiazdki: {amount}'],
  activeMatch: ['Вернуться в матч', 'Повернутися до матчу', 'Volver a la partida', 'Voltar à partida', 'Quay lại trận đấu', 'Kembali ke laga', 'Maça dön', 'Wróć do meczu'],
  activeQueue: ['Вернуться к поиску', 'Повернутися до пошуку', 'Volver a la búsqueda', 'Voltar à busca', 'Quay lại tìm đối thủ', 'Kembali mencari', 'Aramaya dön', 'Wróć do wyszukiwania'],
  playTitle: ['Выбери способ игры', 'Обери спосіб гри', 'Elige cómo jugar', 'Escolha como jogar', 'Chọn cách chơi', 'Pilih cara bermain', 'Oyun şeklini seç', 'Wybierz tryb gry'],
  lab: ['Лаборатория матчей', 'Лабораторія матчів', 'Laboratorio de partidas', 'Laboratório de partidas', 'Phòng thí nghiệm trận đấu', 'Lab pertandingan', 'Maç laboratuvarı', 'Laboratorium meczów'],
  labBody: ['Тренировка режима без рейтинга и наград', 'Тренування режиму без рейтингу й нагород', 'Practica un modo sin rango ni premios', 'Treine um modo sem ranking nem prêmios', 'Luyện chế độ không xếp hạng hay thưởng', 'Latih mode tanpa rank atau hadiah', 'Derece ve ödül olmadan pratik yap', 'Trenuj bez rankingu i nagród'],
  labStart: ['Начать тренировку', 'Почати тренування', 'Empezar práctica', 'Começar treino', 'Bắt đầu luyện tập', 'Mulai latihan', 'Pratiğe başla', 'Rozpocznij trening'],
  ghost: ['Дуэль с записью', 'Дуель із записом', 'Duelo con grabación', 'Duelo com gravação', 'Đấu với bản ghi', 'Duel rekaman', 'Kayıt düellosu', 'Pojedynek z nagraniem'],
  ghostDisclosure: ['Это запись игры соперника. Он сейчас не находится в матче.', 'Це запис гри суперника. Зараз він не перебуває в матчі.', 'Es una grabación del rival. No está jugando ahora.', 'É uma gravação do adversário. Ele não está jogando agora.', 'Đây là bản ghi trận đấu. Đối thủ không chơi trực tiếp lúc này.', 'Ini rekaman permainan lawan. Mereka tidak sedang bermain langsung.', 'Bu rakibin oyun kaydıdır. Şu anda maçta değil.', 'To nagranie gry rywala. Nie gra teraz na żywo.'],
  ghostExpired: ['Срок записи истёк', 'Термін запису минув', 'La grabación ha caducado', 'A gravação expirou', 'Bản ghi đã hết hạn', 'Rekaman sudah kedaluwarsa', 'Kaydın süresi doldu', 'Nagranie wygasło'],
  ghostExpiredHint: ['Запись живёт 48 часов. Попроси друга прислать новую.', 'Запис живе 48 годин. Попроси друга надіслати новий.', 'La grabación dura 48 horas. Pide otra a tu amigo.', 'A gravação dura 48 horas. Peça outra ao seu amigo.', 'Bản ghi tồn tại 48 giờ. Nhờ bạn gửi bản mới.', 'Rekaman berlaku 48 jam. Minta teman mengirim yang baru.', 'Kayıt 48 saat yaşar. Arkadaşından yenisini iste.', 'Nagranie żyje 48 godzin. Poproś znajomego o nowe.'],
  ghostCreate: ['Создать мою запись', 'Створити мій запис', 'Crear mi grabación', 'Criar minha gravação', 'Tạo bản ghi của tôi', 'Buat rekaman saya', 'Kaydımı oluştur', 'Utwórz moje nagranie'],
  ghostAccept: ['Сыграть с записью', 'Зіграти із записом', 'Jugar contra la grabación', 'Jogar contra a gravação', 'Đấu với bản ghi', 'Main melawan rekaman', 'Kayıtla oyna', 'Zagraj z nagraniem'],
  recordingBadge: ['ЗАПИСЬ · НЕ LIVE', 'ЗАПИС · НЕ LIVE', 'GRABACIÓN · NO EN VIVO', 'GRAVAÇÃO · NÃO AO VIVO', 'BẢN GHI · KHÔNG TRỰC TIẾP', 'REKAMAN · BUKAN LIVE', 'KAYIT · CANLI DEĞİL', 'NAGRANIE · NIE NA ŻYWO'],
  rivalry: ['Соперничество', 'Суперництво', 'Rivalidad', 'Rivalidade', 'Kình địch', 'Rivalitas', 'Rekabet', 'Rywalizacja'],
  rivalryBody: ['Серия из трёх игр · до двух побед', 'Серія з трьох ігор · до двох перемог', 'Al mejor de 3 · dos victorias', 'Melhor de 3 · duas vitórias', 'Loạt 3 trận · thắng 2', 'Best-of-3 · dua kemenangan', '3 maçlık seri · iki galibiyet', 'Do dwóch zwycięstw · maks. 3 gry'],
  rivalryPropose: ['Бросить вызов', 'Кинути виклик', 'Lanzar desafío', 'Desafiar', 'Thách đấu', 'Tantang', 'Meydan oku', 'Rzuć wyzwanie'],
  rivalryIncoming: ['Соперник предлагает серию', 'Суперник пропонує серію', 'Tu rival propone una serie', 'Seu rival propõe uma série', 'Đối thủ đề nghị đấu loạt', 'Lawan mengajak seri', 'Rakibin seri öneriyor', 'Rywal proponuje serię'],
  rivalryContinue: ['Следующая игра', 'Наступна гра', 'Siguiente partida', 'Próxima partida', 'Trận tiếp theo', 'Laga berikutnya', 'Sonraki maç', 'Następna gra'],
  rivalryLeave: ['Завершить соперничество', 'Завершити суперництво', 'Terminar rivalidad', 'Encerrar rivalidade', 'Kết thúc kình địch', 'Akhiri rivalitas', 'Rekabeti bitir', 'Zakończ rywalizację'],
  rivalryMute: ['Не получать новые вызовы', 'Не отримувати нові виклики', 'Silenciar nuevos desafíos', 'Silenciar novos desafios', 'Tắt thử thách mới', 'Bisukan tantangan baru', 'Yeni meydan okumaları sessize al', 'Wycisz nowe wyzwania'],
  rivalryUnmute: ['Снова получать вызовы', 'Знову отримувати виклики', 'Permitir desafíos', 'Permitir desafios', 'Cho phép thử thách', 'Izinkan tantangan', 'Meydan okumalara izin ver', 'Zezwól na wyzwania'],
  mastery: ['Карта мастерства', 'Карта майстерності', 'Mapa de dominio', 'Mapa de domínio', 'Bản đồ thành thạo', 'Peta penguasaan', 'Ustalık haritası', 'Mapa biegłości'],
  masteryLow: ['Данных пока мало', 'Даних поки мало', 'Aún hay pocos datos', 'Ainda há poucos dados', 'Chưa đủ dữ liệu', 'Data belum cukup', 'Henüz az veri var', 'Za mało danych'],
  masteryTrain: ['Потренировать режим', 'Потренувати режим', 'Practicar modo', 'Treinar modo', 'Luyện chế độ', 'Latih mode', 'Modu çalış', 'Trenuj tryb'],
  partner: ['Партнёр Арены', 'Партнер Арени', 'Compañero de Arena', 'Parceiro da Arena', 'Đồng đội Đấu trường', 'Partner Arena', 'Arena partneri', 'Partner Areny'],
  partnerBody: ['Общая цель недели', 'Спільна ціль тижня', 'Meta semanal compartida', 'Meta semanal compartilhada', 'Mục tiêu chung trong tuần', 'Target mingguan bersama', 'Ortak haftalık hedef', 'Wspólny cel tygodnia'],
  partnerInvite: ['Выбрать партнёра', 'Обрати партнера', 'Elegir compañero', 'Escolher parceiro', 'Chọn đồng đội', 'Pilih partner', 'Partner seç', 'Wybierz partnera'],
  partnerPause: ['Поставить на паузу', 'Поставити на паузу', 'Pausar', 'Pausar', 'Tạm dừng', 'Jeda', 'Duraklat', 'Wstrzymaj'],
  partnerResume: ['Возобновить', 'Відновити', 'Reanudar', 'Retomar', 'Tiếp tục', 'Lanjutkan', 'Sürdür', 'Wznów'],
  store: ['Магазин Арены', 'Магазин Арени', 'Tienda de Arena', 'Loja da Arena', 'Cửa hàng Đấu trường', 'Toko Arena', 'Arena mağazası', 'Sklep Areny'],
  buy: ['Купить за {amount}', 'Купити за {amount}', 'Comprar por {amount}', 'Comprar por {amount}', 'Mua với {amount}', 'Beli seharga {amount}', '{amount} karşılığında al', 'Kup za {amount}'],
  equip: ['Использовать', 'Використати', 'Equipar', 'Usar', 'Sử dụng', 'Pakai', 'Kullan', 'Użyj'],
  equipped: ['Используется', 'Використовується', 'Equipado', 'Em uso', 'Đang dùng', 'Dipakai', 'Kullanılıyor', 'Używane'],
  owned: ['Уже куплено', 'Уже придбано', 'Ya comprado', 'Já comprado', 'Đã mua', 'Sudah dibeli', 'Zaten alındı', 'Już kupiono'],
  insufficient: ['Недостаточно звёзд для покупки', 'Недостатньо зірок для покупки', 'No tienes suficientes estrellas', 'Estrelas insuficientes', 'Không đủ sao', 'Bintang tidak cukup', 'Yeterli yıldız yok', 'Za mało gwiazd'],
  purchaseSuccess: ['Покупка готова', 'Покупка готова', 'Compra lista', 'Compra concluída', 'Đã mua thành công', 'Pembelian selesai', 'Satın alma tamam', 'Zakup gotowy'],
  emptyLab: ['Разбор появится после первого матча', 'Розбір з’явиться після першого матчу', 'El análisis aparece tras tu primera partida', 'A análise aparece após a primeira partida', 'Phân tích xuất hiện sau trận đầu tiên', 'Ulasan muncul setelah laga pertama', 'Analiz ilk maçtan sonra görünür', 'Analiza pojawi się po pierwszym meczu'],
  emptyRivalry: ['Серию предлагают после матча с живым соперником', 'Серію пропонують після матчу з живим суперником', 'La serie se propone tras jugar con una persona', 'A série é proposta após jogar com uma pessoa', 'Loạt đấu được đề nghị sau trận với người thật', 'Seri ditawarkan setelah laga dengan orang sungguhan', 'Seri, gerçek bir rakiple maçtan sonra önerilir', 'Serię proponuje się po meczu z żywym rywalem'],
  emptyPartner: ['Партнёра можно выбрать из взаимных друзей', 'Партнера можна обрати із взаємних друзів', 'Puedes elegir compañero entre tus amigos mutuos', 'Você pode escolher um parceiro entre amigos mútuos', 'Chọn đồng đội trong danh sách bạn chung', 'Pilih partner dari teman yang saling menambahkan', 'Partneri karşılıklı arkadaşlarından seçebilirsin', 'Partnera wybierzesz spośród wzajemnych znajomych'],
  emptyStore: ['Товары появятся, когда магазин включат', 'Товари з’являться, коли магазин увімкнуть', 'Los artículos aparecerán cuando la tienda se active', 'Os itens aparecem quando a loja for ativada', 'Vật phẩm sẽ xuất hiện khi cửa hàng bật', 'Barang muncul saat toko diaktifkan', 'Ürünler mağaza açıldığında görünür', 'Przedmioty pojawią się po włączeniu sklepu'],
  emptyGhost: ['Запись создаётся из завершённого матча', 'Запис створюється із завершеного матчу', 'La grabación se crea desde una partida terminada', 'A gravação é criada a partir de uma partida concluída', 'Bản ghi được tạo từ trận đã hoàn tất', 'Rekaman dibuat dari laga yang sudah selesai', 'Kayıt, tamamlanmış bir maçtan oluşturulur', 'Nagranie tworzy się z ukończonego meczu'],
  empty: ['Здесь пока пусто', 'Тут поки порожньо', 'Aún no hay nada aquí', 'Ainda não há nada aqui', 'Chưa có gì ở đây', 'Belum ada apa pun', 'Burada henüz bir şey yok', 'Na razie jest pusto'],
  loadFailed: ['Не удалось загрузить', 'Не вдалося завантажити', 'No se pudo cargar', 'Não foi possível carregar', 'Không tải được', 'Gagal memuat', 'Yüklenemedi', 'Nie udało się wczytać'],
  loadFailedHint: ['Проверь связь и попробуй снова', 'Перевір зв’язок і спробуй ще раз', 'Revisa la conexión e inténtalo otra vez', 'Verifique a conexão e tente de novo', 'Kiểm tra kết nối rồi thử lại', 'Periksa koneksi dan coba lagi', 'Bağlantını kontrol edip tekrar dene', 'Sprawdź połączenie i spróbuj ponownie'],
  unavailableHint: ['Раздел временно выключен. Он вернётся — остальная Арена работает.', 'Розділ тимчасово вимкнено. Він повернеться — решта Арени працює.', 'La sección está desactivada temporalmente. Volverá; el resto de Arena funciona.', 'A seção está desativada temporariamente. Ela volta; o resto da Arena funciona.', 'Mục này tạm tắt. Nó sẽ trở lại — phần còn lại của Đấu trường vẫn chạy.', 'Bagian ini dimatikan sementara. Akan kembali — sisa Arena tetap jalan.', 'Bu bölüm geçici olarak kapalı. Geri gelecek — Arena’nın kalanı çalışıyor.', 'Sekcja jest tymczasowo wyłączona. Wróci — reszta Areny działa.'],
  unavailable: ['Сейчас недоступно', 'Зараз недоступно', 'No disponible ahora', 'Indisponível agora', 'Hiện không khả dụng', 'Saat ini tidak tersedia', 'Şu anda kullanılamıyor', 'Teraz niedostępne'],
  expired: ['Срок действия истёк', 'Термін дії минув', 'Ha caducado', 'Expirou', 'Đã hết hạn', 'Sudah kedaluwarsa', 'Süresi doldu', 'Wygasło'],
  loading: ['Загрузка…', 'Завантаження…', 'Cargando…', 'Carregando…', 'Đang tải…', 'Memuat…', 'Yükleniyor…', 'Ładowanie…'],
  ready: ['Готово', 'Готово', 'Listo', 'Pronto', 'Sẵn sàng', 'Siap', 'Hazır', 'Gotowe'],
  localReaction: ['Локальная реакция на экране результата', 'Локальна реакція на екрані результату', 'Reacción local en tu pantalla de resultado', 'Reação local na sua tela de resultado', 'Phản ứng chỉ hiện trên màn hình kết quả của bạn', 'Reaksi lokal di layar hasil Anda', 'Yalnızca sonuç ekranındaki yerel tepki', 'Lokalna reakcja na ekranie wyniku'],
  reactionRespect: ['Уважение', 'Повага', 'Respeto', 'Respeito', 'Tôn trọng', 'Hormat', 'Saygı', 'Szacunek'],
  reactionWellPlayed: ['Отличная игра', 'Чудова гра', 'Buena partida', 'Boa partida', 'Trận hay', 'Permainan bagus', 'İyi oyundu', 'Dobra gra'],
  reactionComeback: ['Вот это возвращение', 'Оце повернення', 'Qué remontada', 'Que virada', 'Lội ngược dòng hay', 'Comeback hebat', 'Ne geri dönüştü', 'Co za powrót'],
  reactionAgain: ['Ещё раз', 'Ще раз', 'Otra vez', 'De novo', 'Chơi lại', 'Lagi', 'Bir daha', 'Jeszcze raz'],
  retry: ['Повторить', 'Повторити', 'Reintentar', 'Tentar novamente', 'Thử lại', 'Coba lagi', 'Tekrar dene', 'Spróbuj ponownie'],
  continueAction: ['Продолжить', 'Продовжити', 'Continuar', 'Continuar', 'Tiếp tục', 'Lanjutkan', 'Devam et', 'Kontynuuj'],
  share: ['Поделиться', 'Поділитися', 'Compartir', 'Compartilhar', 'Chia sẻ', 'Bagikan', 'Paylaş', 'Udostępnij'],
  inviteCode: ['Код приглашения', 'Код запрошення', 'Código de invitación', 'Código do convite', 'Mã mời', 'Kode undangan', 'Davet kodu', 'Kod zaproszenia'],
  sourceRequired: ['Открой запись из завершённого матча', 'Відкрий запис із завершеного матчу', 'Abre la grabación desde una partida terminada', 'Abra a gravação de uma partida concluída', 'Mở bản ghi từ trận đã hoàn tất', 'Buka rekaman dari laga yang selesai', 'Kaydı tamamlanan maçtan aç', 'Otwórz nagranie z ukończonego meczu'],
  noEconomy: ['Без рейтинга и наград', 'Без рейтингу й нагород', 'Sin rango ni premios', 'Sem ranking nem prêmios', 'Không xếp hạng hay phần thưởng', 'Tanpa rank atau hadiah', 'Derece ve ödül yok', 'Bez rankingu i nagród'],
  turningPoint: ['Поворотный момент', 'Поворотний момент', 'Punto de inflexión', 'Ponto de virada', 'Bước ngoặt', 'Titik balik', 'Dönüm noktası', 'Punkt zwrotny'],
  turnSlowCorrect: ['Верный ответ занял больше времени', 'Правильна відповідь зайняла більше часу', 'Una respuesta correcta llevó más tiempo', 'Uma resposta certa levou mais tempo', 'Câu đúng mất nhiều thời gian hơn', 'Jawaban benar membutuhkan lebih banyak waktu', 'Doğru cevap daha uzun sürdü', 'Poprawna odpowiedź zajęła więcej czasu'],
  turnFastWrong: ['Поспешный ответ изменил ход игры', 'Поспішна відповідь змінила хід гри', 'Una respuesta apresurada cambió la partida', 'Uma resposta apressada mudou a partida', 'Câu trả lời vội đã đổi cục diện', 'Jawaban terburu-buru mengubah laga', 'Acele cevap oyunu değiştirdi', 'Pośpieszna odpowiedź zmieniła grę'],
  turnMissedStreak: ['Серия ошибок стала решающей', 'Серія помилок стала вирішальною', 'Una racha de errores fue decisiva', 'Uma sequência de erros foi decisiva', 'Chuỗi sai lầm mang tính quyết định', 'Rangkaian kesalahan menjadi penentu', 'Hata serisi belirleyici oldu', 'Seria błędów okazała się kluczowa'],
  turnComeback: ['Здесь началось возвращение в игру', 'Тут почалося повернення в гру', 'Aquí comenzó la remontada', 'A virada começou aqui', 'Màn lội ngược dòng bắt đầu tại đây', 'Kebangkitan dimulai di sini', 'Geri dönüş burada başladı', 'Tu zaczął się powrót'],
  recovery: ['Закрепление', 'Закріплення', 'Recuperación', 'Recuperação', 'Củng cố', 'Pemulihan', 'Pekiştirme', 'Utrwalenie'],
  review: ['Разбор матча', 'Розбір матчу', 'Análisis de partida', 'Análise da partida', 'Phân tích trận đấu', 'Ulasan laga', 'Maç analizi', 'Analiza meczu'],
  sharedDays: ['Общие дни', 'Спільні дні', 'Días compartidos', 'Dias compartilhados', 'Ngày chung', 'Hari bersama', 'Ortak günler', 'Wspólne dni'],
  claim: ['Получить', 'Отримати', 'Recoger', 'Resgatar', 'Nhận', 'Klaim', 'Al', 'Odbierz'],
  checkProgress: ['Проверить прогресс', 'Перевірити прогрес', 'Comprobar progreso', 'Verificar progresso', 'Kiểm tra tiến độ', 'Periksa progres', 'İlerlemeyi kontrol et', 'Sprawdź postęp'],
  nudge: ['Мягко напомнить', 'М’яко нагадати', 'Enviar recordatorio', 'Enviar lembrete', 'Nhắc nhẹ', 'Ingatkan', 'Nazikçe hatırlat', 'Przypomnij'],
  nudgePreferences: ['Мягкие напоминания', 'М’які нагадування', 'Recordatorios suaves', 'Lembretes suaves', 'Nhắc nhở nhẹ nhàng', 'Pengingat lembut', 'Nazik hatırlatmalar', 'Delikatne przypomnienia'],
  nudgeQuietHours: ['Без уведомлений с 22:00 до 08:00 UTC', 'Без сповіщень з 22:00 до 08:00 UTC', 'Sin avisos de 22:00 a 08:00 UTC', 'Sem avisos das 22:00 às 08:00 UTC', 'Không thông báo từ 22:00 đến 08:00 UTC', 'Tanpa notifikasi pukul 22.00–08.00 UTC', '22.00–08.00 UTC arasında bildirim yok', 'Bez powiadomień od 22:00 do 08:00 UTC'],
  nudgeEnable: ['Разрешить', 'Дозволити', 'Permitir', 'Permitir', 'Cho phép', 'Izinkan', 'İzin ver', 'Włącz'],
  nudgeDisable: ['Отключить', 'Вимкнути', 'Desactivar', 'Desativar', 'Tắt', 'Nonaktifkan', 'Kapat', 'Wyłącz'],
  remove: ['Завершить партнёрство', 'Завершити партнерство', 'Terminar colaboración', 'Encerrar parceria', 'Kết thúc đồng hành', 'Akhiri kemitraan', 'Partnerliği bitir', 'Zakończ partnerstwo'],
  spin: ['Редкий спин', 'Рідкісний спін', 'Giro raro', 'Giro raro', 'Vòng quay hiếm', 'Spin langka', 'Nadir çevirme', 'Rzadki spin'],
  spinClaim: ['Открыть спин', 'Відкрити спін', 'Abrir giro', 'Abrir giro', 'Mở vòng quay', 'Buka spin', 'Çevirmeyi aç', 'Otwórz spin'],
  hidden: ['Скрыто до новых данных', 'Приховано до нових даних', 'Oculto hasta tener más datos', 'Oculto até haver mais dados', 'Ẩn đến khi có thêm dữ liệu', 'Disembunyikan sampai ada data baru', 'Yeni veriye kadar gizli', 'Ukryte do czasu nowych danych'],
  starter: ['Старт', 'Старт', 'Inicio', 'Início', 'Khởi đầu', 'Pemula', 'Başlangıç', 'Start'],
  developing: ['Развивается', 'Розвивається', 'En desarrollo', 'Em evolução', 'Đang phát triển', 'Berkembang', 'Gelişiyor', 'Rozwój'],
  strong: ['Уверенно', 'Упевнено', 'Sólido', 'Sólido', 'Vững', 'Kuat', 'Güçlü', 'Pewnie'],
  expert: ['Эксперт', 'Експерт', 'Experto', 'Especialista', 'Chuyên gia', 'Ahli', 'Uzman', 'Ekspert'],
  mastered: ['Освоено', 'Опановано', 'Dominado', 'Dominado', 'Thành thạo', 'Dikuasai', 'Ustalaşıldı', 'Opanowane'],
  modeGuess: ['Угадай фразу', 'Вгадай фразу', 'Adivina la frase', 'Adivinhe a frase', 'Đoán cụm từ', 'Tebak frasa', 'İfadeyi tahmin et', 'Zgadnij frazę'],
  modeGap: ['Заполни пропуск', 'Заповни пропуск', 'Completa el hueco', 'Complete a lacuna', 'Điền chỗ trống', 'Isi bagian kosong', 'Boşluğu doldur', 'Uzupełnij lukę'],
  modeOddity: ['Найди лишнее', 'Знайди зайве', 'Encuentra el intruso', 'Encontre o intruso', 'Tìm từ khác biệt', 'Temukan yang berbeda', 'Farklı olanı bul', 'Znajdź intruza'],
  modeTranslate: ['Собери перевод', 'Склади переклад', 'Construye la traducción', 'Monte a tradução', 'Ghép bản dịch', 'Susun terjemahan', 'Çeviriyi oluştur', 'Ułóż tłumaczenie'],
  modeSpeed: ['Скоростные пары', 'Швидкі пари', 'Parejas rápidas', 'Pares rápidos', 'Ghép cặp tốc độ', 'Pasangan cepat', 'Hızlı eşleştirme', 'Szybkie pary'],
  score: ['Счёт {you}:{them}', 'Рахунок {you}:{them}', 'Marcador {you}:{them}', 'Placar {you}:{them}', 'Tỉ số {you}:{them}', 'Skor {you}:{them}', 'Skor {you}:{them}', 'Wynik {you}:{them}'],
} as const;

export type ArenaExpansionCopyKey = keyof typeof X;

export function arenaExpansionText(lang: Lang, key: ArenaExpansionCopyKey): string {
  const [ru, uk, es, ptBR, vi, id, tr, pl] = X[key];
  return triLang(lang, { ru, uk, es, 'pt-BR': ptBR, vi, id, tr, pl });
}
