// Generated by scripts/import_learning_v2_first_ten_candidate.mjs.
import { EPISODE_01_SESSION_07_SOURCE } from '../modules/learning-v2/content/source/episode_01_session_07_v1';
import { assertApprovedFirstTenSession } from './learning_v2_approved_first_ten_source_assertions';

describe('episode 1 approved session 7 source', () => {
  test('matches the exact approved projection and runtime contract', () => {
    assertApprovedFirstTenSession(EPISODE_01_SESSION_07_SOURCE, 7);
  });
});
