// Generated by scripts/import_learning_v2_first_ten_candidate.mjs.
import { EPISODE_01_SESSION_02_SOURCE } from '../modules/learning-v2/content/source/episode_01_session_02_v1';
import { assertApprovedFirstTenSession } from './learning_v2_approved_first_ten_source_assertions';

describe('episode 1 approved session 2 source', () => {
  test('matches the exact approved projection and runtime contract', () => {
    assertApprovedFirstTenSession(EPISODE_01_SESSION_02_SOURCE, 2);
  });
});
