import type { LearningV2ModeNativePayloadV1 } from "../../contracts/mode_native_payload_v1";
import type { EpisodeSourcePhrase } from "./episode_01_source_v1";
import { expandLocalized, type LocalizedSource, type SessionModeNativePracticeSourceV1, type SessionSource, type SessionSourceIntroPage, type SessionVocabularySourceV1 } from "./session_shard_from_source_v1";
import { LESSON3_SESSION_15_MODE_NATIVE_PLAN_ID_V1 } from "./lesson3_session_choreography_v1";

const l=(ru:string,uk:string,es:string,pt:string,vi:string,id:string,tr:string,pl:string):LocalizedSource=>({ru,uk,es,"pt-BR":pt,vi,id,tr,pl});
const en=(x:string)=>l(x,x,x,x,x,x,x,x); const ARTICLE="en.grammar.nouns_core_determiners.definite_article";
const coat=l("пальто","пальто","abrigo","casaco","áo khoác","mantel","palto","płaszcz");
const title=l("Знакомое пальто","Знайоме пальто","Un abrigo conocido","Um casaco conhecido","Áo khoác đã biết","Mantel yang dikenal","Bilinen palto","Znany płaszcz");
const summary=l("The coat называет конкретное уже понятное пальто.","The coat називає конкретне вже зрозуміле пальто.","The coat nombra un abrigo concreto conocido.","The coat nomeia um casaco concreto conhecido.","The coat gọi một chiếc áo khoác cụ thể đã rõ.","The coat menyebut mantel tertentu yang dikenal.","The coat bilinen belirli paltoyu adlandırır.","The coat nazywa konkretny znany płaszcz.");
const goal=l("Сказать короткую фразу о знакомом пальто.","Сказати коротку фразу про знайоме пальто.","Decir una frase corta sobre un abrigo conocido.","Dizer uma frase curta sobre um casaco conhecido.","Nói câu ngắn về áo khoác đã rõ.","Mengucapkan frasa pendek tentang mantel yang dikenal.","Bilinen palto hakkında kısa cümle söyleyin.","Powiedzieć krótkie zdanie o znanym płaszczu.");
const page=(kind:SessionSourceIntroPage["kind"],title:LocalizedSource,body:LocalizedSource,prompt:LocalizedSource,c:readonly[string,string,string],explanation:LocalizedSource,d:string):SessionSourceIntroPage=>({kind,title,body,question:{grammarFeatureId:ARTICLE,testedDimension:d,prompt,choices:[en(c[0]),en(c[1]),en(c[2])],correctChoiceIndex:0,explanation}});
const intro=Object.freeze([
page("concept",l("Это пальто","Це пальто","Este abrigo","Este casaco","Áo khoác này","Mantel ini","Bu palto","Ten płaszcz"),l("Мы уже выбрали одно пальто: The coat is warm. The отмечает именно это понятное пальто.","Ми вже вибрали одне пальто: The coat is warm. The позначає саме це зрозуміле пальто.","Ya elegimos un abrigo: The coat is warm. The señala ese abrigo conocido.","Já escolhemos um casaco: The coat is warm. The aponta esse casaco conhecido.","Ta đã chọn một chiếc áo khoác: The coat is warm. The chỉ áo khoác đã rõ đó.","Kita sudah memilih satu mantel: The coat is warm. The menunjukkan mantel yang dikenal itu.","Bir paltoyu zaten seçtik: The coat is warm. The bu bilinen paltoyu gösterir.","Wybraliśmy już jeden płaszcz: The coat is warm. The wskazuje ten znany płaszcz."),l("Выберите фразу о пальто.","Оберіть фразу про пальто.","Elige la frase sobre el abrigo.","Escolha a frase sobre o casaco.","Chọn câu về áo khoác.","Pilih frasa tentang mantel.","Palto cümlesini seçin.","Wybierz zdanie o płaszczu."),["The coat is warm.","A coat is warm.","Coat is warm."],l("Верно: The coat is warm, потому что пальто уже понятно.","Правильно: The coat is warm, бо пальто вже зрозуміле.","Correcto: The coat is warm, porque el abrigo ya es conocido.","Certo: The coat is warm, porque o casaco já é conhecido.","Đúng: The coat is warm, vì áo khoác đã rõ.","Benar: The coat is warm, karena mantel sudah dikenal.","Doğru: The coat is warm, çünkü palto zaten biliniyor.","Dobrze: The coat is warm, ponieważ płaszcz jest już znany."),"meaning"),
page("formula",l("The перед coat","The перед coat","The antes de coat","The antes de coat","The trước coat","The sebelum coat","The coat önünde","The przed coat"),l("The coat is important. The стоит перед coat, поэтому говорим о конкретном пальто.","The coat is important. The стоїть перед coat, тому говоримо про конкретне пальто.","The coat is important. The va antes de coat, por eso hablamos de un abrigo concreto.","The coat is important. The vem antes de coat, por isso falamos de um casaco concreto.","The coat is important. The đứng trước coat, nên ta nói về áo khoác cụ thể.","The coat is important. The ada sebelum coat, jadi kita membahas mantel tertentu.","The coat is important. The coat'tan önce gelir; belirli paltodan söz ederiz.","The coat is important. The stoi przed coat, więc mówimy o konkretnym płaszczu."),l("Выберите правильный порядок.","Оберіть правильний порядок.","Elige el orden correcto.","Escolha a ordem correta.","Chọn đúng thứ tự.","Pilih urutan yang benar.","Doğru sırayı seçin.","Wybierz poprawny szyk."),["The coat is important.","Coat the is important.","Important the is coat."],l("Верно: The coat is important, потому что the стоит перед известным пальто.","Правильно: The coat is important, бо the стоїть перед відомим пальто.","Correcto: The coat is important, porque the va antes del abrigo conocido.","Certo: The coat is important, porque the vem antes do casaco conhecido.","Đúng: The coat is important, vì the đứng trước áo khoác đã rõ.","Benar: The coat is important, karena the ada sebelum mantel yang dikenal.","Doğru: The coat is important, çünkü the bilinen paltonun önünde gelir.","Dobrze: The coat is important, ponieważ the stoi przed znanym płaszczem."),"form"),
page("trap",l("Не любое пальто","Не будь-яке пальто","No cualquier abrigo","Não qualquer casaco","Không phải mọi áo khoác","Bukan mantel apa saja","Herhangi bir palto değil","Nie dowolny płaszcz"),l("A coat — любое пальто. Когда речь о том, которое уже выбрали, говорим The coat is silent.","A coat — будь-яке пальто. Коли йдеться про те, яке вже вибрали, кажемо The coat is silent.","A coat es cualquier abrigo. Para el que ya elegimos decimos The coat is silent.","A coat é qualquer casaco. Para o que já escolhemos dizemos The coat is silent.","A coat là bất kỳ áo khoác nào. Với áo khoác đã chọn, nói The coat is silent.","A coat berarti mantel apa saja. Untuk mantel yang sudah dipilih, katakan The coat is silent.","A coat herhangi bir paltodur. Seçtiğimiz palto için The coat is silent deriz.","A coat to dowolny płaszcz. O tym, który już wybraliśmy, mówimy The coat is silent."),l("Выберите фразу о выбранном пальто.","Оберіть фразу про вибране пальто.","Elige la frase sobre el abrigo elegido.","Escolha a frase sobre o casaco escolhido.","Chọn câu về áo khoác đã chọn.","Pilih frasa tentang mantel yang dipilih.","Seçilmiş palto cümlesini seçin.","Wybierz zdanie o wybranym płaszczu."),["The coat is silent.","A coat is silent.","The silent is coat."],l("Верно: The coat is silent, потому что выбранное пальто получает the.","Правильно: The coat is silent, бо вибране пальто має the.","Correcto: The coat is silent, porque el abrigo elegido lleva the.","Certo: The coat is silent, porque o casaco escolhido leva the.","Đúng: The coat is silent, vì áo khoác đã chọn dùng the.","Benar: The coat is silent, karena mantel yang dipilih memakai the.","Doğru: The coat is silent, çünkü seçilmiş palto the alır.","Dobrze: The coat is silent, ponieważ wybrany płaszcz ma the."),"diagnostic_error")]);
const feedback=(x:string,r:LocalizedSource)=>l(`Вы выбрали ${x}. ${r.ru}`,`Ви обрали ${x}. ${r.uk}`,`Elegiste ${x}. ${r.es}`,`Você escolheu ${x}. ${r["pt-BR"]}`,`Bạn chọn ${x}. ${r.vi}`,`Anda memilih ${x}. ${r.id}`,`${x} seçtiniz. ${r.tr}`,`Wybrano ${x}. ${r.pl}`);
const contact=()=>({guidance:l("Выберите coat: это пальто.","Оберіть coat: це пальто.","Elige coat: significa abrigo.","Escolha coat: significa casaco.","Chọn coat: nghĩa là áo khoác.","Pilih coat: artinya mantel.","Coat palto demektir.","Wybierz coat: to płaszcz."),distractors:[{value:"goat",reasonCode:"coat-goat",trapType:"phonetic" as const,feedback:feedback("goat",l("Goat — коза; coat — пальто.","Goat — коза; coat — пальто.","Goat es cabra; coat es abrigo.","Goat é cabra; coat é casaco.","Goat là dê; coat là áo khoác.","Goat berarti kambing; coat berarti mantel.","Goat keçidir; coat paltodur.","Goat to koza; coat to płaszcz."))},{value:"coats",reasonCode:"coat-plural",trapType:"grammar" as const,feedback:feedback("coats",l("Coats — несколько пальто; здесь один coat.","Coats — кілька пальт; тут один coat.","Coats son varios abrigos; aquí un coat.","Coats são vários casacos; aqui um coat.","Coats là nhiều áo khoác; ở đây một coat.","Coats berarti beberapa mantel; di sini satu coat.","Coats birden çok paltodur; burada tek coat var.","Coats to kilka płaszczy; tutaj jeden coat."))},{value:"cup",reasonCode:"coat-cup",trapType:"semantic_neighbor" as const,feedback:feedback("cup",l("Cup — чашка; coat — пальто.","Cup — чашка; coat — пальто.","Cup es taza; coat es abrigo.","Cup é xícara; coat é casaco.","Cup là cốc; coat là áo khoác.","Cup berarti cangkir; coat berarti mantel.","Cup kupadır; coat paltodur.","Cup to kubek; coat to płaszcz."))}]});
const phrases=Object.freeze([
  {id:"e03-s15-the-coat-is-easy",english:"The coat is easy.",russian:"Пальто лёгкое.",explanation:"Так описывают конкретное лёгкое пальто."},
  {id:"e03-s15-the-door-is-open",english:"The door is open.",russian:"Дверь открыта.",explanation:"Так называют конкретную дверь."},
  {id:"e03-s15-the-key-is-here",english:"The key is here.",russian:"Ключ здесь.",explanation:"Так называют конкретный ключ."},
  {id:"e03-s15-the-lock-is-open",english:"The lock is open.",russian:"Замок открыт.",explanation:"Так называют конкретный замок."},
  {id:"e03-s15-the-cup-is-important",english:"The cup is important.",russian:"Чашка важна.",explanation:"Так говорят о конкретной нужной чашке."},
  {id:"e03-s15-the-coat-is-important",english:"The coat is important.",russian:"Пальто важное.",explanation:"Так говорят о конкретном пальто."},
].map((p):EpisodeSourcePhrase=>({...p,explanation:`${p.explanation} The + предмет показывает, что предмет уже понятен.`,words:p.english.replace(/[?.]/gu,"").split(" ").map(correct=>({correct,category:"definite_article_phrase",distractors:["a","an","are"].map((value,index)=>({value,trapType:"phrase_assembly" as const,reasonCode:`${p.id}-${correct}-${index}`,why:`${value} не подходит вместо ${correct}.`}))})),features:["copula_be","definite_article"]})) as const);
const ok=(id:string,target:string)=>({responseId:id,correct:true,testedDimension:"identifiable_noun",feedbackByLocale:expandLocalized(l(`Верно: ${target}.`,`Правильно: ${target}.`,`Correcto: ${target}.`,`Certo: ${target}.`,`Đúng: ${target}.`,`Benar: ${target}.`,`Doğru: ${target}.`,`Dobrze: ${target}.`))});
const simple=(family:LearningV2ModeNativePayloadV1["family"],target:string):LearningV2ModeNativePayloadV1=>family==="phrase_builder"?{family,targetPhrase:target,localizedMeaning:expandLocalized(coat),orderedTokens:target.replace(".","").split(" "),authoredDistractorTokens:["a","an","are"],slotFeedback:[ok("built",target)]}:family==="listen_build_dictation"?{family,referenceAudio:{audioTargetId:"e03-s15-key",transcript:target},slowReferenceAudio:{audioTargetId:"e03-s15-key-slow",transcript:target},hiddenTargetPhrase:target,orderedTokens:target.replace(".","").split(" "),authoredDistractorTokens:["a","an","are"],slotFeedback:[ok("dictated",target)]}:{family,targetPhrase:target,referenceAudio:{audioTargetId:"e03-s15-repeat",transcript:target},slowReferenceAudio:{audioTargetId:"e03-s15-repeat-slow",transcript:target},recordControlPolicy:"hold_press_release_with_accessible_toggle",modelPlayback:"reference_and_slow",learnerPlayback:"available_after_capture",honestOutcomeStates:["PASS_CONFIDENT","NEEDS_WORK_CONFIDENT","UNCERTAIN","INVALID_AUDIO_OR_SYSTEM"]} as LearningV2ModeNativePayloadV1;
const instruction=l("Сделайте одно точное действие.","Виконайте одну точну дію.","Haz una acción precisa.","Faça uma ação precisa.","Làm một thao tác chính xác.","Lakukan satu tindakan tepat.","Tek doğru işlem yapın.","Wykonaj jedno dokładne działanie.");
const robustTiles: Readonly<Record<string, readonly string[]>> = Object.freeze({ The: ["A", "An", "This"], coat: ["coats", "goat", "cup"], is: ["are", "am", "not"], easy: ["difficult", "important", "silent"], warm: ["cold", "easy", "silent"], door: ["doors", "coat", "cup"], open: ["closed", "easy", "silent"], key: ["keys", "coat", "cup"], here: ["there", "open", "silent"], lock: ["locks", "look", "coat"], cup: ["cups", "coat", "key"], important: ["easy", "difficult", "silent"] });
const robustPhrases: readonly EpisodeSourcePhrase[] = Object.freeze(phrases.map((phrase) => ({
  ...phrase,
  explanation: `${phrase.explanation} The + предмет показывает, что собеседник уже понимает, о каком конкретном предмете идёт речь.`,
  words: phrase.english.replace(/[?.]/gu, "").split(" ").map((correct) => ({
    correct,
    category: "definite_article_phrase",
    distractors: (robustTiles[correct] ?? ["a", "an", "are"]).map((value, index) => ({
      value,
      trapType: "phrase_assembly" as const,
      reasonCode: `${phrase.id}-${correct}-${index}-${value}`,
      why: `Плитка ${value} не подходит вместо ${correct}: она меняет форму или смысл фразы ${phrase.english}.`,
    })),
  })),
  features: ["copula_be", "definite_article"],
})));
const warmPhrase: EpisodeSourcePhrase = {
  ...robustPhrases[5]!, id: "e03-s15-the-coat-is-warm", english: "The coat is warm.", russian: "Пальто тёплое.",
  explanation: "Так описывают конкретное уже понятное тёплое пальто. The + предмет показывает, что предмет уже понятен.",
  words: ["The", "coat", "is", "warm"].map((correct) => ({ correct, category: "definite_article_phrase", distractors: (robustTiles[correct] ?? []).map((value, index) => ({ value, trapType: "phrase_assembly" as const, reasonCode: `e03-s15-warm-${correct}-${index}`, why: `Плитка ${value} не подходит вместо ${correct}: она меняет форму или смысл фразы The coat is warm.` })) })),
};
const finalPhrases = Object.freeze([...robustPhrases.slice(0, 5), warmPhrase] as const);
const finalIntro = Object.freeze([
  { ...intro[0]!, title: { ...intro[0]!.title, uk: "Вибране пальто", tr: "Bilinen palto" } },
  { ...intro[1]!, title: { ...intro[1]!.title, uk: "The перед іменником", "pt-BR": "The antes do casaco" } },
  { ...intro[2]!, body: { ...intro[2]!.body, tr: "A coat herhangi bir paltodur. Seçtiğimiz palto için doğru cümle: The coat is silent. deriz." } },
] as const);
function wrongOption(responseId: string, selected: string) { return { responseId, correct: false, testedDimension: "identifiable_noun", feedbackByLocale: expandLocalized(l(`Вы выбрали ${selected}. Нужна форма The lock is open.`, `Ви обрали ${selected}. Потрібна форма The lock is open.`, `Elegiste ${selected}. Hace falta The lock is open.`, `Você escolheu ${selected}. A forma é The lock is open.`, `Bạn chọn ${selected}. Cần dạng The lock is open.`, `Anda memilih ${selected}. Bentuknya The lock is open.`, `${selected} seçtiniz. Doğru biçim The lock is open.`, `Wybrano ${selected}. Potrzebna forma: The lock is open.`)) }; }
const practice:readonly SessionModeNativePracticeSourceV1[]=Object.freeze([
{family:"phrase_builder",purpose:"supported_practice",learningStage:"apply_in_phrase",target:{kind:"phrase",sourceIndex:0},modePayload:simple("phrase_builder",phrases[0].english),instruction},
{family:"listen_choose",purpose:"guided_practice",learningStage:"apply_in_phrase",target:{kind:"phrase",sourceIndex:1},modePayload:{family:"listen_choose",referenceAudio:{audioTargetId:"e03-s15-door",transcript:phrases[1].english},slowReferenceAudio:{audioTargetId:"e03-s15-door-slow",transcript:phrases[1].english},localizedMeaningChoices:[{responseId:"right",targetText:phrases[1].english,meaningByLocale:expandLocalized(l("Дверь открыта.","Двері відчинені.","La puerta está abierta.","A porta está aberta.","Cánh cửa mở.","Pintunya terbuka.","Kapı açık.","Drzwi są otwarte."))},{responseId:"a",targetText:"A door is open.",meaningByLocale:expandLocalized(l("Любая дверь","Будь-які двері","Cualquier puerta","Qualquer porta","Bất kỳ cửa nào","Pintu apa saja","Herhangi bir kapı","Dowolne drzwi"))},{responseId:"missing",targetText:"The door open.",meaningByLocale:expandLocalized(l("Нет is","Немає is","Falta is","Falta is","Thiếu is","Tidak ada is","Is yok","Brakuje is"))},{responseId:"order",targetText:"Open is the door.",meaningByLocale:expandLocalized(l("Другой порядок","Інший порядок","Otro orden","Outra ordem","Trật tự khác","Urutan lain","Başka sıra","Inny szyk"))}],transcriptRevealPolicy:"after_first_attempt",choiceFeedback:[ok("right",phrases[1].english),ok("a",phrases[1].english),ok("missing",phrases[1].english),ok("order",phrases[1].english)]},instruction},
{family:"listen_build_dictation",purpose:"retrieval_practice",learningStage:"build_form",target:{kind:"phrase",sourceIndex:2},modePayload:simple("listen_build_dictation",phrases[2].english),instruction},
{family:"context_gap_grammar",purpose:"near_transfer",learningStage:"apply_in_phrase",target:{kind:"phrase",sourceIndex:3},modePayload:{family:"context_gap_grammar",localizedScene:expandLocalized(l("Замок уже известен. Вставьте короткое слово перед lock.","Замок уже відомий. Вставте коротке слово перед lock.","La cerradura ya es conocida. Inserta la palabra corta antes de lock.","A fechadura já é conhecida. Coloque a palavra curta antes de lock.","Ổ khóa đã rõ. Điền từ ngắn trước lock.","Kunci sudah dikenal. Isi kata pendek sebelum lock.","Kilit zaten biliniyor. Lock önüne kısa sözcüğü ekleyin.","Zamek jest już znany. Wstaw krótkie słowo przed lock.")),gappedTargetPhrase:"___ lock is open.",gapOptions:[{responseId:"the",text:"the"},{responseId:"a",text:"a"},{responseId:"an",text:"an"},{responseId:"none",text:"no word"}],testedDimension:"identifiable_noun",choiceFeedback:[ok("the",phrases[3].english),wrongOption("a","a"),wrongOption("an","an"),wrongOption("none","no word")]},instruction},
{family:"speed_match",purpose:"independent_check",learningStage:"retrieve_meaning",target:{kind:"vocabulary_grid",sourceIndices:[0],knownItems:[{id:"e03-s15-coat",target:"coat",meaning:coat,features:["singular_count_noun"],contacts:{recognize:contact(),retrieve_meaning:contact(),build_form:contact()}}]},modePayload:{family:"speed_match",pairGrid:[{pairId:"coat",target:"coat",meaningByLocale:expandLocalized(coat)}],leftColumn:["coat"],rightColumn:["coat"],pairingKey:"pair_id",timerPolicy:{enabledByDefault:true,learnerCanDisable:true,pausesOnInterruption:true},finishStats:["speed","accuracy","personal_best"]},instruction},
{family:"scripted_repeat_compare",purpose:"independent_check",learningStage:"speak_with_model",target:{kind:"phrase",sourceIndex:4},modePayload:simple("scripted_repeat_compare",phrases[4].english),instruction},
]);
const wrongChoice = (responseId: string, selected: string) => ({ responseId, correct: false, testedDimension: "identifiable_noun", feedbackByLocale: expandLocalized(l(`Вы выбрали ${selected}. Нужна форма The door is open.`, `Ви обрали ${selected}. Потрібна форма The door is open.`, `Elegiste ${selected}. Hace falta The door is open.`, `Você escolheu ${selected}. A forma é The door is open.`, `Bạn chọn ${selected}. Cần dạng The door is open.`, `Anda memilih ${selected}. Bentuknya The door is open.`, `${selected} seçtiniz. Doğru biçim The door is open.`, `Wybrano ${selected}. Potrzebna forma: The door is open.`)) });
const finalPractice: readonly SessionModeNativePracticeSourceV1[] = Object.freeze([
  practice[0]!,
  { ...practice[1]!, modePayload: { ...(practice[1]!.modePayload as LearningV2ModeNativePayloadV1), choiceFeedback: [ok("right", phrases[1].english), wrongChoice("a", "A door is open."), wrongChoice("missing", "The door open."), wrongChoice("order", "Open is the door.")] } as LearningV2ModeNativePayloadV1 },
  ...practice.slice(2),
]);
export const EPISODE_03_SESSION_15_SOURCE:SessionSource=Object.freeze({packageId:"learning-v2-en-v1",targetLanguage:"en",episodeOrdinal:3,requiredSessionOrdinal:15,canDoOutcomeId:"obj-en-definite-article-coat-spoken",generationInputFingerprint:"en-e03-s15-coat-spoken-v2",sessionKindOverride:"words_then_phrases",distractorAuthorship:"manual",title,summary,learningGoal:goal,introPages:finalIntro,newVocabulary:[{id:"e03-s15-coat",target:"coat",meaning:coat,features:["singular_count_noun","definite_article"],contacts:{recognize:contact(),retrieve_meaning:contact(),build_form:contact()}}] as readonly SessionVocabularySourceV1[],phrases:finalPhrases,modeNativePlanId:LESSON3_SESSION_15_MODE_NATIVE_PLAN_ID_V1,modeNativePractice:finalPractice});
