import type { SessionSource } from "./session_shard_from_source_v1";
import { EPISODE_03_SESSION_17_SOURCE as S17 } from "./episode_03_session_17_v1";
import { LESSON3_SESSION_20_MODE_NATIVE_PLAN_ID_V1 } from "./lesson3_session_choreography_v1";

/** Dedicated guided-application packet for maps, with the approved plural retrieval set. */
const l=(ru:string,uk:string,es:string,pt:string,vi:string,id:string,tr:string,pl:string)=>({ru,uk,es,"pt-BR":pt,vi,id,tr,pl});
const replaceMap=(value:string)=>value.replaceAll("books","maps").replaceAll("book","map").replaceAll("Books","Maps").replaceAll("Book","Map");
const contacts=Object.fromEntries(Object.entries(S17.newVocabulary[0]!.contacts).map(([stage,contact])=>[stage,{...contact,guidance:Object.fromEntries(Object.entries(contact.guidance).map(([locale,text])=>[locale,replaceMap(text)])),distractors:contact.distractors.map((distractor,index)=>{const value=index===0?"map":index===1?"books":"map's"; return {...distractor,value,feedback:Object.fromEntries(Object.entries(distractor.feedback).map(([locale,text])=>[locale,`Wrong choice: ${value}. ${replaceMap(text)} Correct target: maps.`]))};})}])) as typeof S17.newVocabulary[0]!["contacts"];
const vocabulary=Object.freeze([{...S17.newVocabulary[0]!,id:"e03-s20-maps",target:"maps",meaning:l("карты","карти","mapas","mapas","bản đồ","peta-peta","haritalar","mapy"),contacts}]);
export const EPISODE_03_SESSION_20_SOURCE:SessionSource=Object.freeze({...S17,requiredSessionOrdinal:20,canDoOutcomeId:"obj-en-plural-nouns-maps-guided",generationInputFingerprint:"en-e03-s20-plural-nouns-maps-v1",modeNativePlanId:LESSON3_SESSION_20_MODE_NATIVE_PLAN_ID_V1,title:l("Карты здесь","Карти тут","Mapas aquí","Mapas aqui","Bản đồ ở đây","Peta di sini","Haritalar burada","Mapy tutaj"),summary:l("Примените are с несколькими картами в знакомой ситуации.","Застосуйте are з кількома картами у знайомій ситуації.","Aplica are con varios mapas en una situación conocida.","Aplique are com vários mapas numa situação conhecida.","Dùng are với nhiều bản đồ trong tình huống quen thuộc.","Gunakan are dengan beberapa peta dalam situasi yang dikenal.","Tanıdık durumda birden çok haritayla are kullanın.","Zastosuj are przy kilku mapach w znanej sytuacji."),learningGoal:l("Собрать фразу Maps are here.","Скласти фразу Maps are here.","Formar Maps are here.","Montar Maps are here.","Ghép Maps are here.","Menyusun Maps are here.","Maps are here kurmak.","Ułożyć Maps are here."),newVocabulary:vocabulary});
