// Generated by scripts/import_learning_v2_first_ten_candidate.mjs.
// Learner-facing bytes come from the immutable owner-approved SHA below.
import { APPROVED_FIRST_TEN_SESSION_SOURCES_V2 } from './approved_first_ten_source_v2';

export const EPISODE_01_SESSION_04_SOURCE =
  APPROVED_FIRST_TEN_SESSION_SOURCES_V2[3];
