import { expandLocalized, type SessionSource } from "./session_shard_from_source_v1";
import { EPISODE_03_SESSION_17_SOURCE as S17 } from "./episode_03_session_17_v1";
import { LESSON3_SESSION_22_MODE_NATIVE_PLAN_ID_V1 } from "./lesson3_session_choreography_v1";

/** Dedicated listening-retrieval packet for cups. */
const l=(ru:string,uk:string,es:string,pt:string,vi:string,id:string,tr:string,pl:string)=>({ru,uk,es,"pt-BR":pt,vi,id,tr,pl});
const replaceCup=(value:string)=>value.replaceAll("books","cups").replaceAll("book","cup").replaceAll("Books","Cups").replaceAll("Book","Cup");
const contacts=Object.fromEntries(Object.entries(S17.newVocabulary[0]!.contacts).map(([stage,contact])=>[stage,{...contact,guidance:Object.fromEntries(Object.entries(contact.guidance).map(([locale,text])=>[locale,replaceCup(text)])),distractors:contact.distractors.map((distractor,index)=>{const value=index===0?"cup":index===1?"books":"cup's"; return {...distractor,value,feedback:Object.fromEntries(Object.entries(distractor.feedback).map(([locale,text])=>[locale,`Wrong choice: ${value}. ${replaceCup(text)} Correct target: cups.`]))};})}])) as typeof S17.newVocabulary[0]!["contacts"];
const vocabulary=Object.freeze([{...S17.newVocabulary[0]!,id:"e03-s22-cups",target:"cups",meaning:l("чашки","чашки","tazas","xícaras","cốc","cangkir","bardaklar","kubki"),contacts}]);
const phrases=Object.freeze([{...S17.phrases[0]!,id:"e03-s22-cups-full",english:"Cups are full.",russian:"Чашки полные.",words:[{correct:"Cups",category:"plural_noun_phrase",distractors:[{value:"Cup",trapType:"phrase_assembly" as const,reasonCode:"cups-singular",why:"Cup не подходит вместо Cups: Cup означает одну чашку, а Cups — несколько."},{value:"Books",trapType:"phrase_assembly" as const,reasonCode:"cups-books",why:"Books не подходит вместо Cups: Books — книги, а Cups — чашки."},{value:"Boxes",trapType:"phrase_assembly" as const,reasonCode:"cups-boxes",why:"Boxes не подходит вместо Cups: Boxes — коробки, а Cups — чашки."}]},{correct:"are",category:"plural_noun_phrase",distractors:[{value:"is",trapType:"phrase_assembly" as const,reasonCode:"are-is",why:"is не подходит вместо are: Cups обозначает несколько предметов, поэтому нужна are."},{value:"am",trapType:"phrase_assembly" as const,reasonCode:"are-am",why:"am не подходит вместо are: am идёт с I, а Cups — несколько предметов."},{value:"be",trapType:"phrase_assembly" as const,reasonCode:"are-be",why:"be не подходит вместо are: в готовой фразе нужна форма are."}]},{correct:"full",category:"plural_noun_phrase",distractors:[{value:"empty",trapType:"phrase_assembly" as const,reasonCode:"full-empty",why:"empty не подходит вместо full: empty означает пустые, а full — полные."},{value:"open",trapType:"phrase_assembly" as const,reasonCode:"full-open",why:"open не подходит вместо full: open означает открытые, а full — полные."},{value:"here",trapType:"phrase_assembly" as const,reasonCode:"full-here",why:"here не подходит вместо full: here говорит о месте, а full — о наполненности."}]}]},...S17.phrases.slice(1)]);
const practice=Object.freeze(S17.modeNativePractice.map((step,index)=>index===0?{...step,modePayload:{...step.modePayload,targetPhrase:"Cups are full.",localizedMeaning:expandLocalized(l("Чашки полные.","Чашки повні.","Las tazas están llenas.","As xícaras estão cheias.","Các cốc đầy.","Cangkir-cangkir penuh.","Bardaklar dolu.","Kubki są pełne.")),orderedTokens:["Cups","are","full"],authoredDistractorTokens:["Cup","is","empty"]}}:step));
export const EPISODE_03_SESSION_22_SOURCE:SessionSource=Object.freeze({...S17,requiredSessionOrdinal:22,canDoOutcomeId:"obj-en-plural-nouns-cups-listening",generationInputFingerprint:"en-e03-s22-plural-nouns-cups-v1",modeNativePlanId:LESSON3_SESSION_22_MODE_NATIVE_PLAN_ID_V1,title:l("Полные чашки","Повні чашки","Tazas llenas","Xícaras cheias","Cốc đầy","Cangkir penuh","Dolu bardaklar","Pełne kubki"),summary:l("Услышьте are после cups и выберите точную фразу.","Почуйте are після cups та оберіть точну фразу.","Escucha are después de cups y elige la frase exacta.","Ouça are depois de cups e escolha a frase exata.","Nghe are sau cups và chọn câu chính xác.","Dengarkan are setelah cups dan pilih frasa tepat.","Cups sonrasında are'yi dinleyin ve doğru cümleyi seçin.","Usłysz are po cups i wybierz dokładne zdanie."),learningGoal:l("Узнать на слух Cups are full.","Упізнати на слух Cups are full.","Reconocer Cups are full al oírla.","Reconhecer Cups are full ao ouvir.","Nhận ra Cups are full khi nghe.","Mengenali Cups are full saat mendengar.","Cups are full ifadesini dinleyince tanımak.","Rozpoznać ze słuchu Cups are full."),newVocabulary:vocabulary,phrases,modeNativePractice:practice});
