// Generated by scripts/import_learning_v2_first_ten_candidate.mjs.
// This is the exact phrase slice used by the approved session source.
import { APPROVED_FIRST_TEN_PHRASE_SOURCES_V2 } from './approved_first_ten_source_v2';

export const EPISODE_01_SESSION_06_PHRASES =
  APPROVED_FIRST_TEN_PHRASE_SOURCES_V2[5];
