import type {
  LocalizedSource,
  SessionVocabularyContactSourceV1,
  SessionVocabularySourceV1,
} from './session_shard_from_source_v1';

const L = (value: LocalizedSource): LocalizedSource => value;

const contact = (
  guidance: LocalizedSource,
  distractors: SessionVocabularyContactSourceV1['distractors'],
): SessionVocabularyContactSourceV1 => ({ guidance, distractors });

export const EPISODE_01_SESSION_01_VOCABULARY_V1:
  readonly SessionVocabularySourceV1[] = Object.freeze([
  {
    id: 'e01-s01-word-i',
    target: 'I',
    meaning: L({
      ru: 'я — человек, который говорит',
      uk: 'я — людина, яка говорить',
      es: 'yo — la persona que habla',
      'pt-BR': 'eu — a pessoa que fala',
      vi: 'tôi — người đang nói',
      id: 'saya — orang yang berbicara',
      tr: 'ben — konuşan kişi',
      pl: 'ja — osoba, która mówi',
    }),
    features: ['first_person_singular', 'subject_pronoun'],
    contacts: {
      recognize: contact(
        L({
          ru: 'Название буквы I звучит /aɪ/. Буква A звучит /eɪ/, а E — /iː/: различается главный гласный звук.',
          uk: 'Назва літери I звучить /aɪ/. Літера A звучить /eɪ/, а E — /iː/: різниться головний голосний звук.',
          es: 'El nombre de la letra I suena /aɪ/. A suena /eɪ/ y E suena /iː/: cambia la vocal principal.',
          'pt-BR': 'O nome da letra I soa /aɪ/. A soa /eɪ/ e E soa /iː/: a vogal principal muda.',
          vi: 'Tên chữ I có âm /aɪ/. Chữ A có âm /eɪ/, còn E có âm /iː/: nguyên âm chính khác nhau.',
          id: 'Nama huruf I berbunyi /aɪ/. A berbunyi /eɪ/ dan E /iː/: vokal utamanya berbeda.',
          tr: 'I harfinin adı /aɪ/ diye okunur. A /eɪ/, E ise /iː/ olur: temel ünlü ses değişir.',
          pl: 'Nazwa litery I brzmi /aɪ/. A brzmi /eɪ/, a E — /iː/: zmienia się główna samogłoska.',
        }),
        [
          {
            value: 'A',
            reasonCode: 'i_recognize_a_vowel_contrast',
            trapType: 'phonetic',
            feedback: L({
              ru: 'A звучит /eɪ/, а I — /aɪ/; в I первый гласный открыт сильнее.',
              uk: 'A звучить /eɪ/, а I — /aɪ/; у I перший голосний відкритіший.',
              es: 'A suena /eɪ/, mientras I suena /aɪ/; la primera vocal cambia.',
              'pt-BR': 'A soa /eɪ/, enquanto I soa /aɪ/; a primeira vogal é diferente.',
              vi: 'A có âm /eɪ/, còn I có âm /aɪ/; nguyên âm đầu khác nhau.',
              id: 'A berbunyi /eɪ/, sedangkan I /aɪ/; vokal pertamanya berbeda.',
              tr: 'A /eɪ/, I ise /aɪ/ diye okunur; ilk ünlü farklıdır.',
              pl: 'A brzmi /eɪ/, a I — /aɪ/; pierwsza samogłoska jest inna.',
            }),
          },
          {
            value: 'E',
            reasonCode: 'i_recognize_e_vowel_contrast',
            trapType: 'phonetic',
            feedback: L({
              ru: 'E звучит долгим /iː/, а I — дифтонгом /aɪ/; это разные названия букв.',
              uk: 'E звучить довгим /iː/, а I — дифтонгом /aɪ/; це різні назви літер.',
              es: 'E suena con /iː/ largo e I con el diptongo /aɪ/; son letras distintas.',
              'pt-BR': 'E soa com /iː/ longo e I com o ditongo /aɪ/; são letras diferentes.',
              vi: 'E có âm /iː/ dài, còn I có nguyên âm đôi /aɪ/; đó là hai chữ khác nhau.',
              id: 'E berbunyi /iː/ panjang, sedangkan I memakai diftong /aɪ/; keduanya huruf berbeda.',
              tr: 'E uzun /iː/, I ise /aɪ/ diftonguyla okunur; bunlar farklı harflerdir.',
              pl: 'E ma długie /iː/, a I dyftong /aɪ/; to różne nazwy liter.',
            }),
          },
        ],
      ),
      retrieve_meaning: contact(
        L({
          ru: 'I называет говорящего как действующее лицо: «я». Me — «меня/мне», а my показывает принадлежность.',
          uk: 'I називає мовця як діяча: «я». Me означає «мене/мені», а my показує належність.',
          es: 'I nombra a quien habla como sujeto: yo. Me funciona como objeto y my expresa posesión.',
          'pt-BR': 'I nomeia quem fala como sujeito: eu. Me é objeto e my indica posse.',
          vi: 'I chỉ người nói ở vị trí chủ ngữ: tôi. Me là tân ngữ, còn my chỉ sở hữu.',
          id: 'I menyebut penutur sebagai subjek: saya. Me adalah objek, sedangkan my menyatakan kepunyaan.',
          tr: 'I konuşanı özne olarak gösterir: ben. Me nesne, my ise iyelik bildirir.',
          pl: 'I nazywa mówiącego jako podmiot: ja. Me jest formą dopełnienia, a my oznacza „mój”.',
        }),
        [
          {
            value: 'me',
            reasonCode: 'i_meaning_me_object_case',
            trapType: 'grammar',
            feedback: L({
              ru: 'Me означает «меня/мне»; когда говорящий называет себя как подлежащее, нужно I.',
              uk: 'Me означає «мене/мені»; коли мовець є підметом, потрібне I.',
              es: 'Me es objeto; para nombrar al hablante como sujeto se usa I.',
              'pt-BR': 'Me funciona como objeto; para o falante como sujeito, usa-se I.',
              vi: 'Me là tân ngữ; khi người nói làm chủ ngữ, cần I.',
              id: 'Me adalah objek; untuk penutur sebagai subjek digunakan I.',
              tr: 'Me nesnedir; konuşan özne olduğunda I kullanılır.',
              pl: 'Me jest formą dopełnienia; mówiący jako podmiot wymaga I.',
            }),
          },
          {
            value: 'my',
            reasonCode: 'i_meaning_my_possessive',
            trapType: 'grammar',
            feedback: L({
              ru: 'My означает «мой/моя» и требует предмет после себя; отдельное «я» — I.',
              uk: 'My означає «мій/моя» й потребує назви предмета; окреме «я» — I.',
              es: 'My significa «mi» y acompaña a una cosa; «yo» como sujeto es I.',
              'pt-BR': 'My significa «meu/minha» e acompanha algo; «eu» como sujeito é I.',
              vi: 'My nghĩa là “của tôi” và đi trước một vật; “tôi” làm chủ ngữ là I.',
              id: 'My berarti “milik saya” dan diikuti benda; “saya” sebagai subjek adalah I.',
              tr: 'My “benim” anlamında bir adın önüne gelir; özne olan “ben” I olur.',
              pl: 'My znaczy „mój” i stoi przed rzeczą; samodzielne „ja” jako podmiot to I.',
            }),
          },
        ],
      ),
      build_form: contact(
        L({
          ru: 'Местоимение I всегда пишется заглавной. Строчная i и буква l без точки похожи на него, но не являются словом «я».',
          uk: 'Займенник I завжди пишеться великою. Мала i та літера l без крапки схожі на нього, але не є словом «я».',
          es: 'El pronombre I siempre lleva mayúscula. La i minúscula y la letra l sin punto se parecen, pero no significan «yo».',
          'pt-BR': 'O pronome I sempre usa maiúscula. A letra i minúscula e l sem ponto se parecem, mas não significam «eu».',
          vi: 'Đại từ I luôn viết hoa. Chữ i thường và chữ l không có dấu chấm trông giống, nhưng không mang nghĩa “tôi”.',
          id: 'Kata ganti I selalu ditulis besar. Huruf i kecil dan l tanpa titik tampak mirip, tetapi bukan kata “saya”.',
          tr: 'I zamiri her zaman büyük yazılır. Küçük i ve noktasız l ona benzer ama “ben” sözcüğü değildir.',
          pl: 'Zaimek I zawsze zapisuje się wielką literą. Małe i i litera l bez kropki są podobne, ale nie znaczą „ja”.',
        }),
        [
          {
            value: 'i',
            reasonCode: 'i_form_lowercase_pronoun',
            trapType: 'orthographic',
            feedback: L({
              ru: 'Строчная i — не форма местоимения; английское «я» всегда пишется I.',
              uk: 'Мала i — не форма займенника; англійське «я» завжди пишеться I.',
              es: 'La i minúscula no es el pronombre; el «yo» inglés siempre se escribe I.',
              'pt-BR': 'A letra i minúscula não é o pronome; o «eu» inglês sempre se escreve I.',
              vi: 'i viết thường không phải đại từ; “tôi” trong tiếng Anh luôn là I.',
              id: 'i kecil bukan bentuk kata ganti; “saya” dalam bahasa Inggris selalu ditulis I.',
              tr: 'Küçük i zamir değildir; İngilizce “ben” her zaman I yazılır.',
              pl: 'Małe i nie jest zaimkiem; angielskie „ja” zawsze zapisuje się jako I.',
            }),
          },
          {
            value: 'l',
            reasonCode: 'i_form_lowercase_l_shape',
            trapType: 'orthographic',
            feedback: L({
              ru: 'l — строчная буква L без точки; английское местоимение «я» пишется заглавной I.',
              uk: 'l — мала літера L без крапки; англійський займенник «я» пишеться великою I.',
              es: 'l es la letra L minúscula sin punto; el pronombre inglés «yo» se escribe I.',
              'pt-BR': 'l é a letra L minúscula sem ponto; o pronome inglês «eu» se escreve I.',
              vi: 'l là chữ L thường không có dấu chấm; đại từ tiếng Anh “tôi” được viết là I.',
              id: 'l adalah huruf L kecil tanpa titik; kata ganti Inggris “saya” ditulis I.',
              tr: 'l noktasız küçük L harfidir; İngilizce “ben” zamiri büyük I yazılır.',
              pl: 'l to mała litera L bez kropki; angielski zaimek „ja” zapisuje się jako I.',
            }),
          },
        ],
      ),
    },
  },
  {
    id: 'e01-s01-word-am',
    target: 'am',
    meaning: L({
      ru: 'форма to be, которая соединяет I с описанием',
      uk: 'форма to be, що з’єднує I з описом',
      es: 'la forma de to be que acompaña a I',
      'pt-BR': 'a forma de to be usada com I',
      vi: 'dạng to be dùng để nối I với phần mô tả',
      id: 'bentuk to be yang menghubungkan I dengan keterangan',
      tr: 'I ile kullanılan to be biçimi',
      pl: 'forma to be używana z I',
    }),
    features: ['copula_be', 'first_person_singular'],
    contacts: {
      recognize: contact(
        L({
          ru: 'Am начинается с короткого гласного и заканчивается чётким /m/. В an конец /n/, а um начинается другим гласным звуком.',
          uk: 'Am починається з короткого голосного й закінчується чітким /m/. В an кінець /n/, а um починається іншим голосним.',
          es: 'Am empieza con una vocal breve y termina en /m/. An termina en /n/ y um empieza con otra vocal.',
          'pt-BR': 'Am começa com uma vogal breve e termina em /m/. An termina em /n/ e um começa com outra vogal.',
          vi: 'Am bắt đầu bằng nguyên âm ngắn và kết thúc bằng /m/. An kết thúc bằng /n/, còn um có nguyên âm đầu khác.',
          id: 'Am diawali vokal pendek dan berakhir dengan /m/. An berakhir dengan /n/, sedangkan um memakai vokal awal berbeda.',
          tr: 'Am kısa bir ünlüyle başlayıp /m/ ile biter. An /n/ ile biter, um ise başka bir ünlüyle başlar.',
          pl: 'Am zaczyna się krótką samogłoską i kończy /m/. An kończy się /n/, a um zaczyna inną samogłoską.',
        }),
        [
          {
            value: 'an',
            reasonCode: 'am_recognize_an_final_n',
            trapType: 'phonetic',
            feedback: L({
              ru: 'An заканчивается /n/; в am губы смыкаются на /m/.',
              uk: 'An закінчується /n/; в am губи змикаються на /m/.',
              es: 'An acaba en /n/; am cierra los labios para /m/.',
              'pt-BR': 'An termina em /n/; am fecha os lábios no /m/.',
              vi: 'An kết thúc bằng /n/; am khép môi ở âm /m/.',
              id: 'An berakhir dengan /n/; am menutup bibir pada /m/.',
              tr: 'An /n/ ile biter; am söylerken dudaklar /m/ için kapanır.',
              pl: 'An kończy się /n/; w am wargi zamykają się przy /m/.',
            }),
          },
          {
            value: 'um',
            reasonCode: 'am_recognize_um_vowel_contrast',
            trapType: 'phonetic',
            feedback: L({
              ru: 'Um начинается звуком /ʌ/, а am — /æ/; обе формы кончаются /m/, но гласный различается.',
              uk: 'Um починається звуком /ʌ/, а am — /æ/; обидві форми мають /m/, але голосний різниться.',
              es: 'Um empieza con /ʌ/ y am con /æ/; ambas terminan en /m/, pero la vocal cambia.',
              'pt-BR': 'Um começa com /ʌ/ e am com /æ/; ambas terminam em /m/, mas a vogal muda.',
              vi: 'Um bắt đầu bằng /ʌ/, còn am bằng /æ/; cả hai kết thúc /m/ nhưng nguyên âm khác nhau.',
              id: 'Um diawali /ʌ/, sedangkan am /æ/; keduanya berakhir /m/, tetapi vokalnya berbeda.',
              tr: 'Um /ʌ/, am ise /æ/ ile başlar; ikisi de /m/ ile biter ama ünlü farklıdır.',
              pl: 'Um zaczyna się /ʌ/, a am — /æ/; oba kończą się /m/, lecz różni je samogłoska.',
            }),
          },
        ],
      ),
      retrieve_meaning: contact(
        L({
          ru: 'Am — короткая английская связка для говорящего I. An заканчивается другим согласным, а m без начального a остаётся одной буквой.',
          uk: 'Am — коротка англійська зв’язка для мовця I. An закінчується іншим приголосним, а m без початкової a лишається однією літерою.',
          es: 'Am es la unión inglesa breve para el hablante I. An termina con otra consonante y m sin la a inicial es solo una letra.',
          'pt-BR': 'Am é a ligação inglesa breve para o falante I. An termina com outra consoante e m sem a inicial a é só uma letra.',
          vi: 'Am là từ nối tiếng Anh ngắn dành cho người nói I. An kết thúc bằng phụ âm khác, còn m thiếu a ở đầu chỉ là một chữ cái.',
          id: 'Am ialah penghubung Inggris pendek untuk penutur I. An berakhir dengan konsonan lain dan m tanpa a awal hanya sebuah huruf.',
          tr: 'Am, I konuşanı için kısa İngilizce bağlantıdır. An başka bir ünsüzle biter; başında a olmayan m ise tek harftir.',
          pl: 'Am jest krótkim angielskim łącznikiem dla mówiącego I. An kończy się inną spółgłoską, a m bez początkowego a jest tylko literą.',
        }),
        [
          {
            value: 'an',
            reasonCode: 'am_meaning_an_not_connector',
            trapType: 'phonetic',
            feedback: L({
              ru: 'An — другое английское слово с финальным /n/; связку для говорящего I передаёт am с /m/.',
              uk: 'An — інше англійське слово з кінцевим /n/; зв’язку для мовця I передає am із /m/.',
              es: 'An es otra palabra inglesa y termina en /n/; la unión para el hablante I es am con /m/.',
              'pt-BR': 'An é outra palavra inglesa e termina em /n/; a ligação para o falante I é am com /m/.',
              vi: 'An là một từ tiếng Anh khác và kết thúc bằng /n/; từ nối cho người nói I là am với /m/.',
              id: 'An adalah kata Inggris lain dan berakhir /n/; penghubung untuk penutur I ialah am dengan /m/.',
              tr: 'An /n/ ile biten başka bir İngilizce sözcüktür; I konuşanını bağlayan biçim /m/ ile am olur.',
              pl: 'An jest innym angielskim słowem zakończonym /n/; łącznikiem dla mówiącego I jest am z /m/.',
            }),
          },
          {
            value: 'm',
            reasonCode: 'am_meaning_m_letter_not_connector',
            trapType: 'orthographic',
            feedback: L({
              ru: 'm — только одна буква и не выполняет работу связки; рядом с говорящим I требуется полное am.',
              uk: 'm — лише одна літера й не виконує роботу зв’язки; поруч із мовцем I потрібне повне am.',
              es: 'm es una sola letra y no funciona como unión; junto al hablante I se necesita la forma completa am.',
              'pt-BR': 'm é uma única letra e não funciona como ligação; junto ao falante I é necessária a forma completa am.',
              vi: 'm chỉ là một chữ cái và không làm nhiệm vụ nối; bên cạnh người nói I cần dạng đầy đủ am.',
              id: 'm hanya sebuah huruf dan bukan penghubung; di samping penutur I diperlukan bentuk lengkap am.',
              tr: 'm yalnızca bir harftir ve bağlantı kurmaz; konuşan I yanında tam am biçimi gerekir.',
              pl: 'm jest tylko literą i nie działa jako łącznik; przy mówiącym I potrzebna jest pełna forma am.',
            }),
          },
        ],
      ),
      build_form: contact(
        L({
          ru: 'Форма am состоит из двух букв: сначала a, затем m. An меняет последний звук и букву, а одиночная m теряет начало слова.',
          uk: 'Форма am складається з двох літер: спочатку a, потім m. An змінює останній звук і літеру, а окрема m втрачає початок слова.',
          es: 'Am tiene dos letras: primero a y después m. An cambia el sonido y la letra final; m sola pierde el comienzo de la palabra.',
          'pt-BR': 'Am tem duas letras: primeiro a e depois m. An muda o som e a letra final; m sozinho perde o começo da palavra.',
          vi: 'Am có hai chữ cái: a trước rồi đến m. An đổi âm và chữ cuối; m đứng một mình làm mất phần đầu của từ.',
          id: 'Am terdiri dari dua huruf: a lalu m. An mengubah bunyi dan huruf akhir; m sendirian kehilangan awal katanya.',
          tr: 'Am iki harften oluşur: önce a, sonra m. An son sesi ve harfi değiştirir; tek m ise sözcüğün başını kaybeder.',
          pl: 'Am ma dwie litery: najpierw a, potem m. An zmienia końcowy dźwięk i literę, a samo m gubi początek słowa.',
        }),
        [
          {
            value: 'an',
            reasonCode: 'am_form_an_last_letter',
            trapType: 'orthographic',
            feedback: L({
              ru: 'An заканчивается n и является другим словом; форма с I пишется am через m.',
              uk: 'An закінчується n і є іншим словом; форма з I пишеться am через m.',
              es: 'An termina en n y es otra palabra; la forma con I se escribe am con m.',
              'pt-BR': 'An termina em n e é outra palavra; a forma com I se escreve am com m.',
              vi: 'An kết thúc bằng n và là từ khác; dạng đi với I viết am bằng m.',
              id: 'An berakhir dengan n dan merupakan kata lain; bentuk untuk I ditulis am dengan m.',
              tr: 'An n ile biter ve başka bir sözcüktür; I ile kullanılan biçim m ile am yazılır.',
              pl: 'An kończy się literą n i jest innym słowem; forma z I to am przez m.',
            }),
          },
          {
            value: 'm',
            reasonCode: 'am_form_missing_initial_a',
            trapType: 'orthographic',
            feedback: L({
              ru: 'm — одна конечная буква без a; связка для I пишется двумя буквами: am.',
              uk: 'm — одна кінцева літера без a; зв’язка для I пишеться двома літерами: am.',
              es: 'm es solo la letra final sin a; la unión para I se escribe con dos letras: am.',
              'pt-BR': 'm é apenas a letra final sem a; a ligação para I se escreve com duas letras: am.',
              vi: 'm chỉ là chữ cuối không có a; từ nối cho I phải viết đủ hai chữ: am.',
              id: 'm hanya huruf akhir tanpa a; penghubung untuk I ditulis lengkap dengan dua huruf: am.',
              tr: 'm başındaki a olmadan yalnız son harftir; I için bağlantı iki harfle am yazılır.',
              pl: 'm jest tylko końcową literą bez a; łącznik dla I zapisuje się dwiema literami: am.',
            }),
          },
        ],
      ),
    },
  },
  {
    id: 'e01-s01-word-here',
    target: 'here',
    meaning: L({
      ru: 'здесь, в этом месте',
      uk: 'тут, у цьому місці',
      es: 'aquí, en este lugar',
      'pt-BR': 'aqui, neste lugar',
      vi: 'ở đây, tại chỗ này',
      id: 'di sini, di tempat ini',
      tr: 'burada, bu yerde',
      pl: 'tutaj, w tym miejscu',
    }),
    features: ['adverb_place', 'proximal_location'],
    contacts: {
      recognize: contact(
        L({
          ru: 'Here начинается с /h/ и заканчивается долгим звуком, похожим на «иэ». Hair шире звучит как /eə/, а he не имеет конечного /r/.',
          uk: 'Here починається з /h/ і має довгий кінець, схожий на «іе». Hair звучить ширше як /eə/, а he не має кінцевого /r/.',
          es: 'Here empieza con /h/ y termina con el sonido de /ɪə/ o /ɪr/. Hair lleva una vocal más abierta; he termina en /iː/.',
          'pt-BR': 'Here começa com /h/ e termina em /ɪə/ ou /ɪr/. Hair tem vogal mais aberta; he termina em /iː/.',
          vi: 'Here bắt đầu bằng /h/ và kết thúc bằng /ɪə/ hoặc /ɪr/. Hair có nguyên âm mở hơn; he kết thúc bằng /iː/.',
          id: 'Here diawali /h/ dan berakhir dengan /ɪə/ atau /ɪr/. Hair memakai vokal lebih terbuka; he berakhir /iː/.',
          tr: 'Here /h/ ile başlar ve /ɪə/ ya da /ɪr/ ile biter. Hair daha açık bir ünlü taşır; he /iː/ ile biter.',
          pl: 'Here zaczyna się od /h/ i kończy /ɪə/ lub /ɪr/. Hair ma bardziej otwartą samogłoskę, a he kończy się /iː/.',
        }),
        [
          {
            value: 'hair',
            reasonCode: 'here_recognize_hair_vowel',
            trapType: 'phonetic',
            feedback: L({
              ru: 'Hair имеет более открытый звук /eə/ и означает «волосы»; here со звуком /ɪə/ означает «здесь».',
              uk: 'Hair має відкритіший звук /eə/ й означає «волосся»; here зі звуком /ɪə/ означає «тут».',
              es: 'Hair usa la vocal abierta /eə/ y significa «pelo»; here usa /ɪə/ y significa «aquí».',
              'pt-BR': 'Hair usa a vogal aberta /eə/ e significa «cabelo»; here usa /ɪə/ e significa «aqui».',
              vi: 'Hair có âm mở /eə/ và nghĩa là “tóc”; here có /ɪə/ và nghĩa là “ở đây”.',
              id: 'Hair memakai vokal terbuka /eə/ dan berarti “rambut”; here memakai /ɪə/ dan berarti “di sini”.',
              tr: 'Hair açık /eə/ sesiyle “saç” demektir; here /ɪə/ sesiyle “burada” demektir.',
              pl: 'Hair ma otwarte /eə/ i znaczy „włosy”; here ma /ɪə/ i znaczy „tutaj”.',
            }),
          },
          {
            value: 'he',
            reasonCode: 'here_recognize_he_long_i',
            trapType: 'phonetic',
            feedback: L({
              ru: 'He заканчивается долгим /iː/ и означает «он»; here имеет дополнительное окончание и означает «здесь».',
              uk: 'He закінчується довгим /iː/ й означає «він»; here має додатковий кінець і означає «тут».',
              es: 'He termina en /iː/ y significa «él»; here añade otro final y significa «aquí».',
              'pt-BR': 'He termina em /iː/ e significa «ele»; here tem outro final e significa «aqui».',
              vi: 'He kết thúc bằng /iː/ và nghĩa là “anh ấy”; here có phần cuối khác và nghĩa là “ở đây”.',
              id: 'He berakhir dengan /iː/ dan berarti “dia”; here memiliki akhir tambahan dan berarti “di sini”.',
              tr: 'He uzun /iː/ ile biter ve “o” demektir; here farklı bir sonla “burada” demektir.',
              pl: 'He kończy się długim /iː/ i znaczy „on”; here ma dodatkowe zakończenie i znaczy „tutaj”.',
            }),
          },
        ],
      ),
      retrieve_meaning: contact(
        L({
          ru: 'Here указывает на место рядом с говорящим: «здесь». There отсылает дальше, а home называет дом, а не просто близкое место.',
          uk: 'Here вказує на місце біля мовця: «тут». There відсилає далі, а home називає дім, а не будь-яке близьке місце.',
          es: 'Here señala el lugar del hablante: aquí. There apunta más lejos; home nombra el hogar.',
          'pt-BR': 'Here aponta para o lugar do falante: aqui. There aponta para longe; home nomeia a casa.',
          vi: 'Here chỉ nơi gần người nói: ở đây. There chỉ nơi xa hơn; home là nhà.',
          id: 'Here menunjuk tempat penutur: di sini. There menunjuk tempat lebih jauh; home berarti rumah.',
          tr: 'Here konuşanın bulunduğu yeri gösterir: burada. There daha uzaktaki yeri, home ise evi adlandırır.',
          pl: 'Here wskazuje miejsce mówiącego: tutaj. There wskazuje dalej, a home nazywa dom.',
        }),
        [
          {
            value: 'there',
            reasonCode: 'here_meaning_there_distance',
            trapType: 'semantic_neighbor',
            feedback: L({
              ru: 'There означает «там»; для места рядом с говорящим нужно here — «здесь».',
              uk: 'There означає «там»; для місця біля мовця потрібне here — «тут».',
              es: 'There significa «allí»; para el lugar del hablante se usa here, «aquí».',
              'pt-BR': 'There significa «lá»; para o lugar do falante usa-se here, «aqui».',
              vi: 'There nghĩa là “ở đó”; nơi gần người nói dùng here, “ở đây”.',
              id: 'There berarti “di sana”; tempat penutur memakai here, “di sini”.',
              tr: 'There “orada” demektir; konuşanın yeri için here, yani “burada” gerekir.',
              pl: 'There znaczy „tam”; miejsce mówiącego określa here, czyli „tutaj”.',
            }),
          },
          {
            value: 'home',
            reasonCode: 'here_meaning_home_place_name',
            trapType: 'semantic_neighbor',
            feedback: L({
              ru: 'Home означает «дом/дома»; нейтральное указание «здесь» передаёт here.',
              uk: 'Home означає «дім/удома»; нейтральне «тут» передає here.',
              es: 'Home significa «casa/en casa»; la indicación neutral «aquí» es here.',
              'pt-BR': 'Home significa «casa/em casa»; a indicação neutral «aqui» é here.',
              vi: 'Home nghĩa là “nhà/ở nhà”; chỉ “ở đây” nói chung là here.',
              id: 'Home berarti “rumah/di rumah”; penunjuk umum “di sini” adalah here.',
              tr: 'Home “ev/evde” demektir; genel “burada” anlamı here ile verilir.',
              pl: 'Home znaczy „dom/w domu”; neutralne „tutaj” to here.',
            }),
          },
        ],
      ),
      build_form: contact(
        L({
          ru: 'Here пишется h-e-r-e. Hear звучит так же во многих вариантах английского, но означает «слышать»; her означает «её/ей».',
          uk: 'Here пишеться h-e-r-e. Hear у багатьох варіантах звучить так само, але означає «чути»; her означає «її/їй».',
          es: 'Here se escribe h-e-r-e. Hear puede sonar igual, pero significa «oír»; her significa «su/a ella».',
          'pt-BR': 'Here se escreve h-e-r-e. Hear pode soar igual, mas significa «ouvir»; her significa «dela/a ela».',
          vi: 'Here viết h-e-r-e. Hear có thể phát âm giống nhưng nghĩa là “nghe”; her nghĩa là “cô ấy/của cô ấy”.',
          id: 'Here ditulis h-e-r-e. Hear dapat terdengar sama tetapi berarti “mendengar”; her berarti “dia/miliknya”.',
          tr: 'Here h-e-r-e yazılır. Hear aynı duyulabilir ama “duymak”, her ise “onu/onun” anlamındadır.',
          pl: 'Here zapisuje się h-e-r-e. Hear może brzmieć tak samo, ale znaczy „słyszeć”; her znaczy „ją/jej”.',
        }),
        [
          {
            value: 'hear',
            reasonCode: 'here_form_hear_homophone_meaning',
            trapType: 'orthographic',
            feedback: L({
              ru: 'Hear пишется с ea и означает «слышать»; значение «здесь» пишется here.',
              uk: 'Hear пишеться з ea й означає «чути»; значення «тут» пишеться here.',
              es: 'Hear lleva ea y significa «oír»; «aquí» se escribe here.',
              'pt-BR': 'Hear leva ea e significa «ouvir»; «aqui» se escreve here.',
              vi: 'Hear có ea và nghĩa là “nghe”; “ở đây” viết là here.',
              id: 'Hear memakai ea dan berarti “mendengar”; “di sini” ditulis here.',
              tr: 'Hear ea ile yazılır ve “duymak” demektir; “burada” here yazılır.',
              pl: 'Hear ma ea i znaczy „słyszeć”; „tutaj” zapisuje się here.',
            }),
          },
          {
            value: 'her',
            reasonCode: 'here_form_her_missing_final_e',
            trapType: 'orthographic',
            feedback: L({
              ru: 'Her без конечной e означает «её/ей»; слово «здесь» имеет форму here.',
              uk: 'Her без кінцевої e означає «її/їй»; слово «тут» має форму here.',
              es: 'Her sin e final significa «su/a ella»; «aquí» tiene la forma here.',
              'pt-BR': 'Her sem e final significa «dela/a ela»; «aqui» tem a forma here.',
              vi: 'Her thiếu e cuối và nghĩa là “cô ấy/của cô ấy”; “ở đây” là here.',
              id: 'Her tanpa e akhir berarti “dia/miliknya”; “di sini” adalah here.',
              tr: 'Sonunda e olmayan her “onu/onun” demektir; “burada” here biçimidir.',
              pl: 'Her bez końcowego e znaczy „ją/jej”; „tutaj” ma formę here.',
            }),
          },
        ],
      ),
    },
  },
  {
    id: 'e01-s01-word-ready',
    target: 'ready',
    meaning: L({
      ru: 'готов, готова — можно начинать',
      uk: 'готовий, готова — можна починати',
      es: 'listo/lista, preparado/preparada para empezar',
      'pt-BR': 'pronto/pronta para começar',
      vi: 'sẵn sàng để bắt đầu',
      id: 'siap untuk mulai',
      tr: 'hazır, başlamaya uygun',
      pl: 'gotowy/gotowa, można zaczynać',
    }),
    features: ['state_adjective', 'readiness'],
    contacts: {
      recognize: contact(
        L({
          ru: 'Ready начинается /red-/. Really после /riː/ имеет звук /l/, а reading заканчивается слогом /-dɪŋ/.',
          uk: 'Ready починається /red-/. Really після /riː/ має звук /l/, а reading закінчується складом /-dɪŋ/.',
          es: 'Ready empieza /red-/. Really tiene /l/ después de /riː/ y reading termina en /-dɪŋ/.',
          'pt-BR': 'Ready começa /red-/. Really tem /l/ depois de /riː/ e reading termina em /-dɪŋ/.',
          vi: 'Ready bắt đầu /red-/. Really có âm /l/ sau /riː/, còn reading kết thúc bằng /-dɪŋ/.',
          id: 'Ready diawali /red-/. Really memiliki /l/ setelah /riː/, sedangkan reading berakhir /-dɪŋ/.',
          tr: 'Ready /red-/ ile başlar. Really içinde /l/ vardır; reading /-dɪŋ/ ile biter.',
          pl: 'Ready zaczyna się /red-/. Really ma głoskę /l/, a reading kończy się sylabą /-dɪŋ/.',
        }),
        [
          {
            value: 'really',
            reasonCode: 'ready_recognize_really_medial_l',
            trapType: 'phonetic',
            feedback: L({
              ru: 'В really слышится /l/ и начальное /riː/; ready звучит /ˈredi/ без /l/.',
              uk: 'У really чути /l/ і початкове /riː/; ready звучить /ˈredi/ без /l/.',
              es: 'Really contiene /l/ y empieza /riː/; ready suena /ˈredi/ sin /l/.',
              'pt-BR': 'Really contém /l/ e começa /riː/; ready soa /ˈredi/ sem /l/.',
              vi: 'Really có /l/ và bắt đầu /riː/; ready đọc /ˈredi/ không có /l/.',
              id: 'Really mengandung /l/ dan diawali /riː/; ready berbunyi /ˈredi/ tanpa /l/.',
              tr: 'Really içinde /l/ ve başta /riː/ vardır; ready /l/ olmadan /ˈredi/ okunur.',
              pl: 'Really zawiera /l/ i zaczyna się /riː/; ready brzmi /ˈredi/ bez /l/.',
            }),
          },
          {
            value: 'reading',
            reasonCode: 'ready_recognize_reading_final_ing',
            trapType: 'phonetic',
            feedback: L({
              ru: 'Reading имеет два слога с окончанием /-dɪŋ/; ready заканчивается коротким /-di/.',
              uk: 'Reading має два склади із закінченням /-dɪŋ/; ready закінчується коротким /-di/.',
              es: 'Reading termina en /-dɪŋ/; ready termina en el breve /-di/.',
              'pt-BR': 'Reading termina em /-dɪŋ/; ready termina no breve /-di/.',
              vi: 'Reading kết thúc bằng /-dɪŋ/; ready kết thúc ngắn bằng /-di/.',
              id: 'Reading berakhir dengan /-dɪŋ/; ready berakhir pendek dengan /-di/.',
              tr: 'Reading /-dɪŋ/ ile biter; ready kısa /-di/ ile biter.',
              pl: 'Reading kończy się /-dɪŋ/; ready ma krótkie zakończenie /-di/.',
            }),
          },
        ],
      ),
      retrieve_meaning: contact(
        L({
          ru: 'Ready означает, что можно начинать. Busy говорит о занятости, tired — об усталости; оба состояния могут помешать готовности.',
          uk: 'Ready означає, що можна починати. Busy говорить про зайнятість, tired — про втому; обидва стани можуть заважати готовності.',
          es: 'Ready indica que se puede empezar. Busy significa ocupado y tired, cansado; ninguno equivale a estar preparado.',
          'pt-BR': 'Ready indica que é possível começar. Busy significa ocupado e tired, cansado; nenhum equivale a estar pronto.',
          vi: 'Ready nghĩa là có thể bắt đầu. Busy là bận, tired là mệt; hai trạng thái này không đồng nghĩa với sẵn sàng.',
          id: 'Ready berarti dapat mulai. Busy berarti sibuk dan tired berarti lelah; keduanya bukan “siap”.',
          tr: 'Ready başlanabileceğini gösterir. Busy “meşgul”, tired “yorgun” demektir; ikisi de “hazır” değildir.',
          pl: 'Ready oznacza, że można zaczynać. Busy to „zajęty”, tired to „zmęczony”; żadne nie znaczy „gotowy”.',
        }),
        [
          {
            value: 'busy',
            reasonCode: 'ready_meaning_busy_state',
            trapType: 'semantic_neighbor',
            feedback: L({
              ru: 'Busy означает «занят»; «готов и можно начинать» передаёт ready.',
              uk: 'Busy означає «зайнятий»; «готовий і можна починати» передає ready.',
              es: 'Busy significa «ocupado»; «preparado para empezar» es ready.',
              'pt-BR': 'Busy significa «ocupado»; «pronto para começar» é ready.',
              vi: 'Busy nghĩa là “bận”; “sẵn sàng để bắt đầu” là ready.',
              id: 'Busy berarti “sibuk”; “siap untuk mulai” adalah ready.',
              tr: 'Busy “meşgul” demektir; “başlamaya hazır” anlamı ready ile verilir.',
              pl: 'Busy znaczy „zajęty”; „gotowy, by zacząć” to ready.',
            }),
          },
          {
            value: 'tired',
            reasonCode: 'ready_meaning_tired_state',
            trapType: 'semantic_neighbor',
            feedback: L({
              ru: 'Tired означает «устал»; состояние готовности выражает ready.',
              uk: 'Tired означає «втомлений»; стан готовності виражає ready.',
              es: 'Tired significa «cansado»; el estado de preparación se expresa con ready.',
              'pt-BR': 'Tired significa «cansado»; o estado de prontidão se expressa com ready.',
              vi: 'Tired nghĩa là “mệt”; trạng thái sẵn sàng là ready.',
              id: 'Tired berarti “lelah”; keadaan siap dinyatakan dengan ready.',
              tr: 'Tired “yorgun” demektir; hazır olma durumu ready ile anlatılır.',
              pl: 'Tired znaczy „zmęczony”; gotowość wyraża ready.',
            }),
          },
        ],
      ),
      build_form: contact(
        L({
          ru: 'Ready пишется r-e-a-d-y: внутри сохраняется ea, а перед y стоит одна d. В redy пропущена a, в readdy ошибочно удвоена d.',
          uk: 'Ready пишеться r-e-a-d-y: усередині зберігається ea, а перед y стоїть одна d. У redy пропущено a, у readdy помилково подвоєно d.',
          es: 'Ready se escribe r-e-a-d-y: conserva ea y lleva una sola d antes de y. Redy pierde la a; readdy duplica la d.',
          'pt-BR': 'Ready se escreve r-e-a-d-y: mantém ea e usa um único d antes de y. Redy perde o a; readdy duplica o d.',
          vi: 'Ready viết r-e-a-d-y: giữ ea và chỉ có một d trước y. Redy thiếu a, còn readdy thừa một d.',
          id: 'Ready ditulis r-e-a-d-y: bagian ea tetap dan hanya ada satu d sebelum y. Redy kehilangan a; readdy menggandakan d.',
          tr: 'Ready r-e-a-d-y yazılır: ea korunur ve y önünde tek d bulunur. Redy a harfini atlar; readdy d harfini gereksiz çiftler.',
          pl: 'Ready zapisuje się r-e-a-d-y: zachowuje ea i ma jedno d przed y. Redy pomija a, a readdy błędnie podwaja d.',
        }),
        [
          {
            value: 'redy',
            reasonCode: 'ready_form_redy_missing_a',
            trapType: 'orthographic',
            feedback: L({
              ru: 'Redy выглядит правдоподобно на слух, но теряет букву a; точная форма «готов» — ready.',
              uk: 'Redy виглядає правдоподібно на слух, але втрачає літеру a; точна форма «готовий» — ready.',
              es: 'Redy parece posible por el sonido, pero pierde la letra a; la forma exacta de «preparado» es ready.',
              'pt-BR': 'Redy parece possível pelo som, mas perde a letra a; a forma exata de «pronto» é ready.',
              vi: 'Redy trông hợp lý theo âm nhưng thiếu chữ a; dạng chính xác cho “sẵn sàng” là ready.',
              id: 'Redy tampak masuk akal dari bunyinya, tetapi kehilangan a; bentuk tepat untuk “siap” ialah ready.',
              tr: 'Redy sese göre mümkün görünür ama a harfini kaybeder; “hazır” için doğru biçim ready olur.',
              pl: 'Redy wygląda wiarygodnie ze słuchu, ale gubi literę a; dokładna forma „gotowy” to ready.',
            }),
          },
          {
            value: 'readdy',
            reasonCode: 'ready_form_readdy_double_d',
            trapType: 'orthographic',
            feedback: L({
              ru: 'Readdy ошибочно удваивает d; в английской форме «готов» перед y стоит одна d: ready.',
              uk: 'Readdy помилково подвоює d; в англійській формі «готовий» перед y стоїть одна d: ready.',
              es: 'Readdy duplica la d por error; la forma inglesa de «preparado» lleva una sola d: ready.',
              'pt-BR': 'Readdy duplica o d por engano; a forma inglesa de «pronto» usa apenas um d: ready.',
              vi: 'Readdy thừa một chữ d; dạng tiếng Anh cho “sẵn sàng” chỉ có một d trước y: ready.',
              id: 'Readdy menggandakan d secara keliru; bentuk Inggris untuk “siap” hanya memakai satu d: ready.',
              tr: 'Readdy d harfini yanlışlıkla çiftler; İngilizce “hazır” biçiminde y önünde tek d vardır: ready.',
              pl: 'Readdy błędnie podwaja d; angielska forma „gotowy” ma przed y tylko jedno d: ready.',
            }),
          },
        ],
      ),
    },
  },
]);
