import type { LocalizedSource, SessionVocabularyContactSourceV1, SessionVocabularySourceV1 } from './session_shard_from_source_v1';

const L = (value: LocalizedSource): LocalizedSource => value;
const contact = (guidance: LocalizedSource, distractors: SessionVocabularyContactSourceV1['distractors']): SessionVocabularyContactSourceV1 => ({ guidance, distractors });

export const EPISODE_01_SESSION_10_VOCABULARY_V1: readonly SessionVocabularySourceV1[] = Object.freeze([
  {
    id: 'e01-s10-word-alone', target: 'alone', features: ['state', 'predicative_adjective'],
    meaning: L({ ru: 'один / одна, без других людей', uk: 'сам / сама, без інших людей', es: 'solo / sola, sin compañía', 'pt-BR': 'sozinho / sozinha, sem companhia', vi: 'một mình, không có ai bên cạnh', id: 'sendirian, tanpa orang lain', tr: 'yalnız, yanında kimse olmadan', pl: 'sam / sama, bez innych osób' }),
    contacts: {
      recognize: contact(
        L({ ru: 'Alone звучит /əˈloʊn/: ударение падает на второй слог, а в конце слышится /n/. Along оканчивается на /ŋ/, а запись a lone ошибочно разрывает одно слово на два.', uk: 'Alone звучить /əˈloʊn/: наголос падає на другий склад, а наприкінці чути /n/. Along закінчується на /ŋ/, а запис a lone помилково розриває одне слово на два.', es: 'Alone suena /əˈloʊn/, con el acento en la segunda sílaba y /n/ final. Along termina en /ŋ/; a lone separa por error una sola palabra.', 'pt-BR': 'Alone soa /əˈloʊn/, com força na segunda sílaba e /n/ no fim. Along termina em /ŋ/; a lone separa indevidamente uma palavra.', vi: 'Alone phát âm /əˈloʊn/, nhấn ở âm tiết thứ hai và kết thúc bằng /n/. Along kết thúc bằng /ŋ/; a lone tách sai một từ thành hai.', id: 'Alone berbunyi /əˈloʊn/, tekanan pada suku kedua dan berakhir /n/. Along berakhir /ŋ/; a lone keliru memisahkan satu kata.', tr: 'Alone /əˈloʊn/ duyulur; vurgu ikinci hecededir ve son ses /n/ olur. Along /ŋ/ ile biter; a lone tek sözcüğü yanlışlıkla ikiye böler.', pl: 'Alone brzmi /əˈloʊn/, z akcentem na drugiej sylabie i końcowym /n/. Along kończy się /ŋ/, a a lone błędnie rozdziela jedno słowo.' }),
        [
          { value: 'along', reasonCode: 'alone_recognize_along_final_ng', trapType: 'phonetic', feedback: L({ ru: 'Along заканчивается звуком /ŋ/ и означает движение «вдоль» или «вместе». В alone слышится финальный /n/, и речь идёт о человеке без компании.', uk: 'Along закінчується звуком /ŋ/ і означає рух «уздовж» або «разом». В alone чути кінцевий /n/, і йдеться про людину без компанії.', es: 'Along termina en /ŋ/ y suele expresar «a lo largo» o acompañamiento. Alone termina en /n/ y describe estar sin compañía.', 'pt-BR': 'Along termina em /ŋ/ e costuma indicar “ao longo” ou acompanhamento. Alone termina em /n/ e descreve estar sem companhia.', vi: 'Along kết thúc bằng /ŋ/ và thường mang nghĩa “dọc theo” hoặc đi cùng. Alone kết thúc bằng /n/ và nói về việc không có ai bên cạnh.', id: 'Along berakhir /ŋ/ dan biasanya berarti “sepanjang” atau bersama. Alone berakhir /n/ dan menyatakan tanpa teman.', tr: 'Along /ŋ/ ile biter ve “boyunca/birlikte” anlamına gelir. Alone /n/ ile biter ve yanında kimse olmamasını anlatır.', pl: 'Along kończy się /ŋ/ i oznacza zwykle „wzdłuż” albo towarzyszenie. Alone kończy się /n/ i opisuje brak towarzystwa.' }) },
          { value: 'a lone', reasonCode: 'alone_recognize_split_spelling', trapType: 'orthographic', feedback: L({ ru: 'A lone выглядит как два слова и меняет структуру: a требует существительного после себя. Значение «без других людей» передаёт одно цельное слово alone.', uk: 'A lone виглядає як два слова й змінює будову: a потребує іменника після себе. Значення «без інших людей» передає одне цілісне слово alone.', es: 'A lone crea dos piezas y hace que a espere un sustantivo. El significado «sin compañía» se escribe como una sola palabra: alone.', 'pt-BR': 'A lone cria duas partes e faz a esperar um substantivo. O sentido “sem companhia” é uma só palavra: alone.', vi: 'A lone tạo thành hai phần và khiến a cần một danh từ theo sau. Nghĩa “một mình” được viết liền thành alone.', id: 'A lone menjadi dua bagian dan membuat a menuntut nomina setelahnya. Arti “sendirian” ditulis sebagai satu kata: alone.', tr: 'A lone iki parça oluşturur ve a sonrasında isim bekletir. “Yalnız” anlamı tek sözcükle yazılır: alone.', pl: 'A lone tworzy dwie części, a rodzajnik a wymaga po sobie rzeczownika. Znaczenie „bez innych” zapisuje się jako jedno słowo: alone.' }) },
        ],
      ),
      retrieve_meaning: contact(
        L({ ru: 'Alone описывает фактическое отсутствие других людей рядом: человек находится один. Lonely говорит уже о неприятном чувстве одиночества, а only означает «только» и не описывает компанию.', uk: 'Alone описує фактичну відсутність інших людей поруч: людина перебуває сама. Lonely називає неприємне відчуття самотності, а only означає «лише» й не описує компанію.', es: 'Alone describe el hecho de no tener a otras personas alrededor. Lonely añade el sentimiento de soledad; only significa «solamente» y no describe compañía.', 'pt-BR': 'Alone descreve o fato de não haver outras pessoas por perto. Lonely acrescenta o sentimento de solidão; only significa “somente” e não fala de companhia.', vi: 'Alone nói về thực tế không có người khác bên cạnh. Lonely thêm cảm giác cô đơn, còn only nghĩa là “chỉ” và không nói về việc có người đi cùng.', id: 'Alone menyatakan keadaan tanpa orang lain di sekitar. Lonely menambahkan perasaan kesepian; only berarti “hanya” dan bukan keadaan tanpa teman.', tr: 'Alone çevrede başka kimsenin bulunmadığı gerçeğini anlatır. Lonely yalnızlık duygusunu ekler; only “sadece” demektir ve eşlik durumunu anlatmaz.', pl: 'Alone opisuje fakt, że nikogo innego nie ma obok. Lonely dodaje przykre poczucie samotności, a only znaczy „tylko” i nie mówi o towarzystwie.' }),
        [
          { value: 'lonely', reasonCode: 'alone_meaning_lonely_feeling', trapType: 'semantic_neighbor', feedback: L({ ru: 'Lonely означает, что человек чувствует одиночество; рядом могут даже быть люди. Alone нейтрально сообщает сам факт: человек сейчас один.', uk: 'Lonely означає, що людина почувається самотньою; поруч навіть можуть бути інші. Alone нейтрально повідомляє факт: людина зараз сама.', es: 'Lonely expresa sentirse solo, incluso si hay gente alrededor. Alone comunica de forma neutral el hecho de estar sin compañía.', 'pt-BR': 'Lonely expressa sentir solidão, mesmo com pessoas por perto. Alone informa de modo neutro o fato de estar sem companhia.', vi: 'Lonely diễn tả cảm giác cô đơn, ngay cả khi có người xung quanh. Alone chỉ nêu trung tính rằng hiện không có ai đi cùng.', id: 'Lonely menyatakan perasaan kesepian, bahkan saat ada orang lain. Alone hanya menyatakan fakta tanpa teman secara netral.', tr: 'Lonely, çevrede insanlar olsa bile yalnızlık hissetmeyi anlatır. Alone yalnızca yanında kimse bulunmadığı gerçeğini nötr biçimde bildirir.', pl: 'Lonely oznacza poczucie samotności, nawet gdy ludzie są w pobliżu. Alone neutralnie stwierdza fakt braku towarzystwa.' }) },
          { value: 'only', reasonCode: 'alone_meaning_only_limit', trapType: 'semantic_neighbor', feedback: L({ ru: 'Only ограничивает значение: «только». Оно не говорит, есть ли рядом другие люди; состояние «один, без компании» выражает alone.', uk: 'Only обмежує значення: «лише». Воно не каже, чи є поруч інші люди; стан «сам, без компанії» виражає alone.', es: 'Only limita algo y significa «solamente». No indica si hay otras personas; el estado «sin compañía» es alone.', 'pt-BR': 'Only limita algo e significa “somente”. Não diz se há outras pessoas; o estado “sem companhia” é alone.', vi: 'Only giới hạn nghĩa là “chỉ”. Nó không cho biết có người khác bên cạnh hay không; trạng thái “một mình” là alone.', id: 'Only membatasi arti menjadi “hanya”. Kata itu tidak menyatakan ada tidaknya orang lain; keadaan “sendirian” adalah alone.', tr: 'Only “sadece” diyerek sınırlar; yanında başkalarının olup olmadığını söylemez. “Yanında kimse yok” durumu alone ile anlatılır.', pl: 'Only ogranicza znaczenie do „tylko”. Nie mówi, czy ktoś jest obok; stan „bez towarzystwa” wyraża alone.' }) },
        ],
      ),
      build_form: contact(
        L({ ru: 'Alone пишется слитно: a-l-o-n-e. Внутри есть lone, но перед ним не ставится пробел; along меняет последнюю букву e на g и образует другое слово.', uk: 'Alone пишеться разом: a-l-o-n-e. Усередині є lone, але перед ним не ставиться пробіл; along змінює останню e на g й утворює інше слово.', es: 'Alone se escribe unido: a-l-o-n-e. Contiene lone, pero no lleva espacio; along cambia la e final por g y forma otra palabra.', 'pt-BR': 'Alone se escreve junto: a-l-o-n-e. Contém lone, mas não leva espaço; along troca o e final por g e cria outra palavra.', vi: 'Alone được viết liền: a-l-o-n-e. Bên trong có lone nhưng không có khoảng trắng; along đổi e cuối thành g và tạo từ khác.', id: 'Alone ditulis serangkai: a-l-o-n-e. Di dalamnya ada lone tanpa spasi; along mengganti e akhir dengan g dan menjadi kata lain.', tr: 'Alone bitişik yazılır: a-l-o-n-e. İçinde lone vardır ama önünde boşluk yoktur; along son e yerine g getirerek başka sözcük olur.', pl: 'Alone pisze się łącznie: a-l-o-n-e. Zawiera lone, ale bez spacji; along zmienia końcowe e na g i tworzy inne słowo.' }),
        [
          { value: 'a lone', reasonCode: 'alone_form_space_inside_word', trapType: 'orthographic', feedback: L({ ru: 'A lone вставляет пробел внутрь нужной формы и превращает a в отдельный артикль. Состояние «один» пишется без разрыва: alone.', uk: 'A lone вставляє пробіл усередину потрібної форми й робить a окремим артиклем. Стан «сам» пишеться без розриву: alone.', es: 'A lone inserta un espacio y convierte a en un artículo independiente. El estado «sin compañía» se escribe sin separación: alone.', 'pt-BR': 'A lone insere espaço e transforma a em artigo separado. O estado “sem companhia” se escreve sem divisão: alone.', vi: 'A lone chèn khoảng trắng và biến a thành mạo từ riêng. Trạng thái “một mình” phải viết liền: alone.', id: 'A lone menyisipkan spasi dan menjadikan a sebuah artikel terpisah. Keadaan “sendirian” ditulis tanpa pemisah: alone.', tr: 'A lone araya boşluk koyup a harfini ayrı artik el yapar. “Yalnız” durumu ayrılmadan yazılır: alone.', pl: 'A lone wstawia spację i zmienia a w osobny rodzajnik. Stan „bez towarzystwa” zapisuje się bez przerwy: alone.' }) },
          { value: 'along', reasonCode: 'alone_form_final_g_not_e', trapType: 'orthographic', feedback: L({ ru: 'Along заканчивается g и образует другое слово со значением «вдоль». Нужная форма заканчивается e: a-l-o-n-e, alone.', uk: 'Along закінчується g й утворює інше слово зі значенням «уздовж». Потрібна форма закінчується e: a-l-o-n-e, alone.', es: 'Along termina en g y forma la palabra «a lo largo». La forma buscada termina en e: a-l-o-n-e, alone.', 'pt-BR': 'Along termina em g e forma a palavra “ao longo”. A forma desejada termina em e: a-l-o-n-e, alone.', vi: 'Along kết thúc bằng g và tạo từ mang nghĩa “dọc theo”. Dạng cần tìm kết thúc bằng e: a-l-o-n-e, alone.', id: 'Along berakhir g dan berarti “sepanjang”. Bentuk yang diperlukan berakhir e: a-l-o-n-e, alone.', tr: 'Along g ile biter ve “boyunca” anlamındaki başka sözcüğü oluşturur. Gerekli biçim e ile biter: a-l-o-n-e, alone.', pl: 'Along kończy się g i tworzy słowo „wzdłuż”. Potrzebna forma kończy się e: a-l-o-n-e, alone.' }) },
        ],
      ),
    },
  },
]);
