import type { LearningV2ModeNativePayloadV1 } from "../../contracts/mode_native_payload_v1";
import type { EpisodeSourcePhrase } from "./episode_01_source_v1";
import { expandLocalized, type LocalizedSource, type SessionModeNativePracticeSourceV1, type SessionSourceIntroPage, type SessionVocabularySourceV1 } from "./session_shard_from_source_v1";

const l = (ru: string, uk: string, es: string, pt: string, vi: string, id: string, tr: string, pl: string): LocalizedSource => ({ ru, uk, es, "pt-BR": pt, vi, id, tr, pl });
const en = (value: string) => l(value, value, value, value, value, value, value, value);
const ARTICLE = "en.grammar.nouns_core_determiners.definite_article";
const room = l("комната", "кімната", "habitación", "quarto", "phòng", "ruangan", "oda", "pokój");

export const EPISODE_03_SESSION_11_TITLE_V2 = l("Знакомая комната", "Знайома кімната", "Una habitación conocida", "Um quarto conhecido", "Căn phòng đã biết", "Ruangan yang dikenal", "Bilinen oda", "Znany pokój");
export const EPISODE_03_SESSION_11_SUMMARY_V2 = l("The room — это конкретная уже понятная комната.", "The room — це конкретна вже зрозуміла кімната.", "The room es una habitación concreta ya identificada.", "The room é um quarto concreto já identificado.", "The room là một căn phòng cụ thể đã rõ.", "The room adalah ruangan tertentu yang sudah dikenal.", "The room, bilinen belirli bir odadır.", "The room to konkretny rozpoznany pokój.");
export const EPISODE_03_SESSION_11_GOAL_V2 = l("Отличить the room от a room в понятном контексте.", "Відрізнити the room від a room у зрозумілому контексті.", "Distinguir the room de a room en un contexto claro.", "Distinguir the room de a room num contexto claro.", "Phân biệt the room với a room trong ngữ cảnh rõ ràng.", "Membedakan the room dan a room dalam konteks yang jelas.", "Açık bağlamda the room ile a room'u ayırt edin.", "Odróżnić the room od a room w jasnym kontekście.");

const page = (kind: SessionSourceIntroPage["kind"], title: LocalizedSource, body: LocalizedSource, prompt: LocalizedSource, choices: readonly [string, string, string], explanation: LocalizedSource, testedDimension: string): SessionSourceIntroPage => ({
  kind, title, body,
  question: { grammarFeatureId: ARTICLE, testedDimension, prompt, choices: [en(choices[0]), en(choices[1]), en(choices[2])], correctChoiceIndex: 0, explanation },
});

export const EPISODE_03_SESSION_11_INTRO_V2 = Object.freeze([
  page("concept", l("Вот эта комната", "Ось ця кімната", "Esta habitación", "Este quarto", "Căn phòng này", "Ruangan ini", "Bilinen oda", "Znany pokój tutaj"),
    l("Мы уже говорим об одной комнате: The room is clean. The показывает именно эту понятную комнату.", "Ми вже говоримо про одну кімнату: The room is clean. The показує саме цю зрозумілу кімнату.", "Ya hablamos de una habitación: The room is clean. The señala esa habitación conocida.", "Já falamos de um quarto: The room is clean. The aponta esse quarto conhecido.", "Ta đã nói về một căn phòng: The room is clean. The chỉ căn phòng đã rõ đó.", "Kita sudah membahas satu ruangan: The room is clean. The menunjukkan ruangan yang dikenal itu.", "Bir odadan zaten söz ediyoruz: The room is clean. The bu bilinen odayı gösterir.", "Mówimy już o jednym pokoju: The room is clean. The wskazuje ten znany pokój."),
    l("Выберите фразу об этой комнате.", "Оберіть фразу про цю кімнату.", "Elige la frase sobre esta habitación.", "Escolha a frase sobre este quarto.", "Chọn câu về căn phòng này.", "Pilih frasa tentang ruangan ini.", "Bu oda cümlesini seçin.", "Wybierz zdanie o tym pokoju."), ["The room is clean.", "A room is clean.", "Room is clean."],
    l("Верно: The room is clean, потому что речь идёт об уже понятной комнате.", "Правильно: The room is clean, бо йдеться про вже зрозумілу кімнату.", "Correcto: The room is clean, porque hablamos de una habitación ya conocida.", "Certo: The room is clean, porque falamos de um quarto já conhecido.", "Đúng: The room is clean, vì ta nói về căn phòng đã rõ.", "Benar: The room is clean, karena kita membahas ruangan yang dikenal.", "Doğru: The room is clean, çünkü bilinen odadan söz ediyoruz.", "Dobrze: The room is clean, ponieważ mówimy o znanym pokoju."), "meaning"),
  page("formula", l("Порядок с the", "Порядок із the", "Orden con the", "Ordem com the", "Trật tự với the", "Urutan dengan the", "The ile sıra", "Szyk z the"),
    l("The book is small. В этой форме the стоит перед book, поэтому сначала называем известный предмет.", "The book is small. У цій формі the стоїть перед book, тому спершу називаємо відомий предмет.", "The book is small. En esta forma the va antes de book, por eso nombramos primero el objeto conocido.", "The book is small. Nesta forma the vem antes de book, por isso nomeamos primeiro o objeto conhecido.", "The book is small. Trong dạng này the đứng trước book, nên ta nêu đồ vật đã rõ trước.", "The book is small. Dalam bentuk ini the ada sebelum book, jadi benda yang dikenal disebut lebih dulu.", "The book is small. Bu biçimde the book'tan önce gelir; bilinen nesne önce adlandırılır.", "The book is small. W tej formie the stoi przed book, więc najpierw nazywamy znany przedmiot."),
    l("Выберите правильный порядок слов.", "Оберіть правильний порядок слів.", "Elige el orden correcto.", "Escolha a ordem correta.", "Chọn đúng thứ tự từ.", "Pilih urutan kata yang benar.", "Doğru kelime sırasını seçin.", "Wybierz poprawny szyk."), ["The book is small.", "Book the is small.", "Small the is book."],
    l("Верно: The book is small, потому что the стоит перед известной книгой.", "Правильно: The book is small, бо the стоїть перед відомою книгою.", "Correcto: The book is small, porque the va antes del libro conocido.", "Certo: The book is small, porque the vem antes do livro conhecido.", "Đúng: The book is small, vì the đứng trước cuốn sách đã rõ.", "Benar: The book is small, karena the ada sebelum buku yang dikenal.", "Doğru: The book is small, çünkü the bilinen kitabın önünde gelir.", "Dobrze: The book is small, ponieważ the stoi przed znaną książką."), "form"),
  page("trap", l("Не любая комната", "Не будь-яка кімната", "No cualquier habitación", "Não qualquer quarto", "Không phải mọi căn phòng", "Bukan ruangan apa saja", "Herhangi bir oda değil", "Nie dowolny pokój"),
    l("A room — любая комната. Когда речь о той комнате, которую уже обсудили, говорим The room is quiet.", "A room — будь-яка кімната. Коли йдеться про ту кімнату, яку вже обговорили, кажемо The room is quiet.", "A room es cualquier habitación. Para la habitación ya mencionada decimos The room is quiet.", "A room é qualquer quarto. Para o quarto já mencionado dizemos The room is quiet.", "A room là bất kỳ căn phòng nào. Với căn phòng đã nhắc đến, nói The room is quiet.", "A room berarti ruangan apa saja. Untuk ruangan yang sudah dibahas, katakan The room is quiet.", "A room herhangi bir odadır. Daha önce konuşulan oda için doğru cümle: The room is quiet. Çünkü oda biliniyor.", "A room to dowolny pokój. O już omówionym pokoju mówimy The room is quiet."),
    l("Выберите фразу о комнате, которую уже назвали.", "Оберіть фразу про кімнату, яку вже назвали.", "Elige la frase sobre la habitación ya mencionada.", "Escolha a frase sobre o quarto já mencionado.", "Chọn câu về căn phòng đã được nhắc đến.", "Pilih frasa tentang ruangan yang sudah disebut.", "Daha önce adı geçen oda cümlesini seçin.", "Wybierz zdanie o wcześniej nazwanym pokoju."), ["The room is quiet.", "A room is quiet.", "The quiet is room."],
    l("Верно: The room is quiet, потому что известная комната получает the.", "Правильно: The room is quiet, бо відома кімната має the.", "Correcto: The room is quiet, porque la habitación conocida lleva the.", "Certo: The room is quiet, porque o quarto conhecido leva the.", "Đúng: The room is quiet, vì căn phòng đã biết dùng the.", "Benar: The room is quiet, karena ruangan yang dikenal memakai the.", "Doğru: The room is quiet, çünkü bilinen oda the alır.", "Dobrze: The room is quiet, ponieważ znany pokój ma the."), "diagnostic_error"),
] as const);

const feedback = (choice: string, reason: LocalizedSource) => l(`Вы выбрали ${choice}. ${reason.ru}`, `Ви обрали ${choice}. ${reason.uk}`, `Elegiste ${choice}. ${reason.es}`, `Você escolheu ${choice}. ${reason["pt-BR"]}`, `Bạn chọn ${choice}. ${reason.vi}`, `Anda memilih ${choice}. ${reason.id}`, `${choice} seçtiniz. ${reason.tr}`, `Wybrano ${choice}. ${reason.pl}`);
const roomContact = () => ({ guidance: l("Выберите room: это комната.", "Оберіть room: це кімната.", "Elige room: significa habitación.", "Escolha room: significa quarto.", "Chọn room: nghĩa là căn phòng.", "Pilih room: artinya ruangan.", "Room oda demektir.", "Wybierz room: to pokój."), distractors: [
  { value: "roof", reasonCode: "room-roof", trapType: "phonetic" as const, feedback: feedback("roof", l("Roof — крыша; room — комната.", "Roof — дах; room — кімната.", "Roof es tejado; room es habitación.", "Roof é telhado; room é quarto.", "Roof là mái nhà; room là căn phòng.", "Roof berarti atap; room berarti ruangan.", "Roof çatı demektir; room odadır.", "Roof to dach; room to pokój.")) },
  { value: "rooms", reasonCode: "room-plural", trapType: "grammar" as const, feedback: feedback("rooms", l("Rooms — несколько комнат; здесь один room.", "Rooms — кілька кімнат; тут один room.", "Rooms son varias habitaciones; aquí hay una room.", "Rooms são vários quartos; aqui há uma room.", "Rooms là nhiều phòng; ở đây là một room.", "Rooms berarti beberapa ruangan; di sini satu room.", "Rooms birden çok odadır; burada tek room var.", "Rooms to kilka pokoi; tutaj jest jeden room.")) },
  { value: "door", reasonCode: "room-door", trapType: "semantic_neighbor" as const, feedback: feedback("door", l("Door — дверь; room — комната.", "Door — двері; room — кімната.", "Door es puerta; room es habitación.", "Door é porta; room é quarto.", "Door là cửa; room là căn phòng.", "Door berarti pintu; room berarti ruangan.", "Door kapıdır; room odadır.", "Door to drzwi; room to pokój.")) },
] });
export const EPISODE_03_SESSION_11_VOCABULARY_V2: readonly SessionVocabularySourceV1[] = Object.freeze([{ id: "e03-s11-room", target: "room", meaning: room, features: ["singular_count_noun", "definite_article"], contacts: { recognize: roomContact(), retrieve_meaning: roomContact(), build_form: roomContact() } }]);

const tiles: Readonly<Record<string, readonly string[]>> = Object.freeze({ The: ["A", "An", "This"], old: ["young", "quiet", "clean"], room: ["rooms", "roof", "door"], is: ["are", "am", "not"], clean: ["open", "quiet", "strong"], door: ["doors", "room", "book"], open: ["closed", "quiet", "clean"], key: ["keys", "door", "book"], here: ["there", "open", "quiet"], lock: ["locks", "look", "room"], quiet: ["loud", "strong", "smart"], book: ["books", "room", "door"] });
const phrase = (id: string, english: string, russian: string, explanation: string): EpisodeSourcePhrase => ({ id, english, russian, explanation: `${explanation} The + предмет показывает, что собеседник уже понимает, о каком именно предмете речь.`, words: english.replace(/[?.]/gu, "").split(" ").map((correct) => ({ correct, category: "definite_article_phrase", distractors: (tiles[correct] ?? ["the", "is", "open"]).map((value, index) => ({ value, trapType: "phrase_assembly" as const, reasonCode: `${id}-${correct}-${index}-${value}`, why: `Плитка ${value} не подходит вместо ${correct}: она меняет смысл фразы ${english}.` })) })), features: ["copula_be", "definite_article"] });
export const EPISODE_03_SESSION_11_PHRASES_V2 = Object.freeze([
  phrase("e03-s11-the-lock-is-open", "The lock is open.", "Замок открыт.", "Так говорят о конкретном уже понятном замке."),
  phrase("e03-s11-the-door-is-open", "The door is open.", "Дверь открыта.", "Так называют конкретную уже понятную дверь."),
  phrase("e03-s11-the-book-is-here", "The book is here.", "Книга здесь.", "Так называют конкретную уже понятную книгу."),
  phrase("e03-s11-the-old-room-is-clean", "The old room is clean.", "Старая комната чистая.", "Так говорят о конкретной уже понятной старой комнате."),
  phrase("e03-s11-the-lock-is-quiet", "The lock is quiet.", "Замок тихий.", "Так описывают конкретный замок, который не шумит."),
  phrase("e03-s11-the-book-is-small", "The book is small.", "Книга маленькая.", "Так описывают конкретную уже понятную книгу."),
] as const);

const audio = (audioTargetId: string, transcript: string) => ({ audioTargetId, transcript });
const ok = (responseId: string, target: string) => ({ responseId, correct: true, testedDimension: "definite_article_identifiable", feedbackByLocale: expandLocalized(l(`Верно: ${target}.`, `Правильно: ${target}.`, `Correcto: ${target}.`, `Certo: ${target}.`, `Đúng: ${target}.`, `Benar: ${target}.`, `Doğru: ${target}.`, `Dobrze: ${target}.`)) });
const wrong = (responseId: string, selected: string, target: string, reason: LocalizedSource) => ({ responseId, correct: false, testedDimension: "definite_article_identifiable", feedbackByLocale: expandLocalized(l(`Вы выбрали ${selected}. ${reason.ru} Нужна форма ${target}.`, `Ви обрали ${selected}. ${reason.uk} Потрібна форма ${target}.`, `Elegiste ${selected}. ${reason.es} Hace falta ${target}.`, `Você escolheu ${selected}. ${reason["pt-BR"]} A forma é ${target}.`, `Bạn chọn ${selected}. ${reason.vi} Cần dạng ${target}.`, `Anda memilih ${selected}. ${reason.id} Bentuknya ${target}.`, `${selected} seçtiniz. ${reason.tr} Doğru biçim ${target}.`, `Wybrano ${selected}. ${reason.pl} Potrzebna forma: ${target}.`)) });
const builder = (target: string): LearningV2ModeNativePayloadV1 => ({ family: "phrase_builder", targetPhrase: target, localizedMeaning: expandLocalized(room), orderedTokens: target.replace(/[?.]/gu, "").split(" "), authoredDistractorTokens: ["a", "an", "are"], slotFeedback: [ok("built", target)] });
const listen = (target: string): LearningV2ModeNativePayloadV1 => ({ family: "listen_choose", referenceAudio: audio("e03-s11-listen-door", target), slowReferenceAudio: audio("e03-s11-listen-door-slow", target), localizedMeaningChoices: [{ responseId: "right", targetText: target, meaningByLocale: expandLocalized(l("Дверь открыта.", "Двері відчинені.", "La puerta está abierta.", "A porta está aberta.", "Cánh cửa mở.", "Pintunya terbuka.", "Kapı açık.", "Drzwi są otwarte.")) }, { responseId: "a", targetText: "A door is open.", meaningByLocale: expandLocalized(l("Любая дверь", "Будь-які двері", "Cualquier puerta", "Qualquer porta", "Bất kỳ cửa nào", "Pintu apa saja", "Herhangi bir kapı", "Dowolne drzwi")) }, { responseId: "missing", targetText: "The door open.", meaningByLocale: expandLocalized(l("Нет is", "Немає is", "Falta is", "Falta is", "Thiếu is", "Tidak ada is", "Is yok", "Brakuje is")) }, { responseId: "order", targetText: "Open is the door.", meaningByLocale: expandLocalized(l("Другой порядок", "Інший порядок", "Otro orden", "Outra ordem", "Trật tự khác", "Urutan lain", "Başka sıra", "Inny szyk")) }], transcriptRevealPolicy: "after_first_attempt", choiceFeedback: [ok("right", target), wrong("a", "A door is open.", target, l("A называет любую дверь, а аудио — известную.", "A називає будь-які двері, а аудіо — відомі.", "A nombra cualquier puerta; el audio, una conocida.", "A nomeia qualquer porta; o áudio, uma conhecida.", "A chỉ bất kỳ cửa nào; audio nói về cửa đã rõ.", "A menyebut pintu apa saja; audio menyebut pintu yang dikenal.", "A herhangi bir kapıyı söyler; ses bilinen kapıyı söyler.", "A mówi o dowolnych drzwiach; nagranie o znanych.")), wrong("missing", "The door open.", target, l("Между door и open нужна форма is.", "Між door і open потрібна форма is.", "Entre door y open hace falta is.", "Entre door e open é preciso is.", "Giữa door và open cần is.", "Antara door dan open perlu is.", "Door ile open arasında is gerekir.", "Między door a open potrzebne jest is.")), wrong("order", "Open is the door.", target, l("Это другой порядок; в аудио сначала называют известную дверь.", "Це інший порядок; в аудіо спершу називають відомі двері.", "Es otro orden; el audio nombra primero la puerta conocida.", "É outra ordem; o áudio nomeia primeiro a porta conhecida.", "Đây là thứ tự khác; audio gọi cánh cửa đã rõ trước.", "Ini urutan lain; audio menyebut pintu yang dikenal lebih dulu.", "Bu başka sıradır; seste önce bilinen kapı adlandırılır.", "To inny szyk; nagranie najpierw nazywa znane drzwi."))] });
const dictation = (target: string): LearningV2ModeNativePayloadV1 => ({ family: "listen_build_dictation", referenceAudio: audio("e03-s11-dictation-key", target), slowReferenceAudio: audio("e03-s11-dictation-key-slow", target), hiddenTargetPhrase: target, orderedTokens: target.replace(/[?.]/gu, "").split(" "), authoredDistractorTokens: ["a", "an", "are"], slotFeedback: [ok("dictated", target)] });
const gap = (target: string): LearningV2ModeNativePayloadV1 => ({ family: "context_gap_grammar", localizedScene: expandLocalized(l("Замок уже известен. Вставьте короткое слово перед lock.", "Замок уже відомий. Вставте коротке слово перед lock.", "La cerradura ya es conocida. Inserta la palabra corta antes de lock.", "A fechadura já é conhecida. Coloque a palavra curta antes de lock.", "Ổ khóa đã rõ. Điền từ ngắn trước lock.", "Kunci sudah dikenal. Isi kata pendek sebelum lock.", "Kilit zaten biliniyor. Lock önüne kısa sözcüğü ekleyin.", "Zamek jest już znany. Wstaw krótkie słowo przed lock.")), gappedTargetPhrase: target.replace("The", "___"), gapOptions: [{ responseId: "the", text: "the" }, { responseId: "a", text: "a" }, { responseId: "an", text: "an" }, { responseId: "none", text: "no word" }], testedDimension: "identifiable_noun", choiceFeedback: [ok("the", target), wrong("a", "a", target, l("A называет любой предмет, а lock уже известен.", "A називає будь-який предмет, а lock уже відомий.", "A nombra cualquier objeto; lock ya es conocido.", "A nomeia qualquer objeto; lock já é conhecido.", "A nói về bất kỳ đồ vật nào; lock đã rõ.", "A menyebut benda apa saja; lock sudah dikenal.", "A herhangi bir nesneyi söyler; lock zaten biliniyor.", "A mówi o dowolnym przedmiocie; lock jest już znany.")), wrong("an", "an", target, l("An не отмечает известный предмет; здесь нужен the.", "An не позначає відомий предмет; тут потрібне the.", "An no marca un objeto conocido; aquí hace falta the.", "An não marca um objeto conhecido; aqui é preciso the.", "An không chỉ đồ vật đã biết; ở đây cần the.", "An tidak menandai benda yang dikenal; di sini perlu the.", "An bilinen nesneyi belirtmez; burada the gerekir.", "An nie oznacza znanego przedmiotu; tutaj potrzebne jest the.")), wrong("none", "no word", target, l("Перед известным lock нужен the.", "Перед відомим lock потрібне the.", "Antes de lock conocido hace falta the.", "Antes de lock conhecido é preciso the.", "Trước lock đã biết cần the.", "Sebelum lock yang dikenal perlu the.", "Bilinen lock önünde the gerekir.", "Przed znanym lock potrzebne jest the."))] });
const speed = (): LearningV2ModeNativePayloadV1 => ({ family: "speed_match", pairGrid: [{ pairId: "room", target: "room", meaningByLocale: expandLocalized(room) }], leftColumn: ["room"], rightColumn: ["room"], pairingKey: "pair_id", timerPolicy: { enabledByDefault: true, learnerCanDisable: true, pausesOnInterruption: true }, finishStats: ["speed", "accuracy", "personal_best"] });
const repeat = (target: string): LearningV2ModeNativePayloadV1 => ({ family: "scripted_repeat_compare", referenceAudio: audio("e03-s11-repeat-quiet-room", target), slowReferenceAudio: audio("e03-s11-repeat-quiet-room-slow", target), targetPhrase: target, recordControlPolicy: "hold_press_release_with_accessible_toggle", modelPlayback: "reference_and_slow", learnerPlayback: "available_after_capture", honestOutcomeStates: ["PASS_CONFIDENT", "NEEDS_WORK_CONFIDENT", "UNCERTAIN", "INVALID_AUDIO_OR_SYSTEM"] });
const instruction = l("Сделайте одно точное действие.", "Виконайте одну точну дію.", "Haz una acción precisa.", "Faça uma ação precisa.", "Làm một thao tác chính xác.", "Lakukan satu tindakan tepat.", "Tek doğru işlem yapın.", "Wykonaj jedno dokładne działanie.");
const step = (family: SessionModeNativePracticeSourceV1["family"], purpose: SessionModeNativePracticeSourceV1["purpose"], learningStage: SessionModeNativePracticeSourceV1["learningStage"], target: SessionModeNativePracticeSourceV1["target"], modePayload: LearningV2ModeNativePayloadV1): SessionModeNativePracticeSourceV1 => ({ family, purpose, learningStage, target, modePayload, instruction });
export const EPISODE_03_SESSION_11_MODE_NATIVE_PRACTICE_V2 = Object.freeze([
  step("phrase_builder", "supported_practice", "apply_in_phrase", { kind: "phrase", sourceIndex: 0 }, builder(EPISODE_03_SESSION_11_PHRASES_V2[0].english)),
  step("listen_choose", "guided_practice", "apply_in_phrase", { kind: "phrase", sourceIndex: 1 }, listen(EPISODE_03_SESSION_11_PHRASES_V2[1].english)),
  step("listen_build_dictation", "retrieval_practice", "build_form", { kind: "phrase", sourceIndex: 2 }, dictation(EPISODE_03_SESSION_11_PHRASES_V2[2].english)),
  step("context_gap_grammar", "near_transfer", "apply_in_phrase", { kind: "phrase", sourceIndex: 3 }, gap(EPISODE_03_SESSION_11_PHRASES_V2[3].english)),
  step("speed_match", "independent_check", "retrieve_meaning", { kind: "vocabulary_grid", sourceIndices: [0], knownItems: EPISODE_03_SESSION_11_VOCABULARY_V2 }, speed()),
  step("scripted_repeat_compare", "independent_check", "speak_with_model", { kind: "phrase", sourceIndex: 4 }, repeat(EPISODE_03_SESSION_11_PHRASES_V2[4].english)),
]);
