import type { SessionSource } from "./session_shard_from_source_v1";
import { EPISODE_03_SESSION_17_SOURCE as S17 } from "./episode_03_session_17_v1";
import { LESSON3_SESSION_21_MODE_NATIVE_PLAN_ID_V1 } from "./lesson3_session_choreography_v1";

/** Dedicated diagnostic-repair packet for pens, retaining only approved plural retrieval contexts. */
const l=(ru:string,uk:string,es:string,pt:string,vi:string,id:string,tr:string,pl:string)=>({ru,uk,es,"pt-BR":pt,vi,id,tr,pl});
const replacePen=(value:string)=>value.replaceAll("books","pens").replaceAll("book","pen").replaceAll("Books","Pens").replaceAll("Book","Pen");
const contacts=Object.fromEntries(Object.entries(S17.newVocabulary[0]!.contacts).map(([stage,contact])=>[stage,{...contact,guidance:Object.fromEntries(Object.entries(contact.guidance).map(([locale,text])=>[locale,replacePen(text)])),distractors:contact.distractors.map((distractor,index)=>{const value=index===0?"pen":index===1?"books":"pen's"; return {...distractor,value,feedback:Object.fromEntries(Object.entries(distractor.feedback).map(([locale,text])=>[locale,`Wrong choice: ${value}. ${replacePen(text)} Correct target: pens.`]))};})}])) as typeof S17.newVocabulary[0]!["contacts"];
const vocabulary=Object.freeze([{...S17.newVocabulary[0]!,id:"e03-s21-pens",target:"pens",meaning:l("ручки","ручки","bolígrafos","canetas","bút","pena-pena","kalemler","długopisy"),contacts}]);
export const EPISODE_03_SESSION_21_SOURCE:SessionSource=Object.freeze({...S17,requiredSessionOrdinal:21,canDoOutcomeId:"obj-en-plural-nouns-pens-repair",generationInputFingerprint:"en-e03-s21-plural-nouns-pens-v1",modeNativePlanId:LESSON3_SESSION_21_MODE_NATIVE_PLAN_ID_V1,title:l("Ручки здесь","Ручки тут","Bolígrafos aquí","Canetas aqui","Bút ở đây","Pena di sini","Kalemler burada","Długopisy tutaj"),summary:l("Исправьте is на are, когда предметов несколько.","Виправте is на are, коли предметів кілька.","Cambia is por are cuando hay varios objetos.","Troque is por are quando há vários objetos.","Đổi is thành are khi có nhiều đồ vật.","Ganti is dengan are saat ada beberapa benda.","Birden çok nesnede is'i are yapın.","Zamień is na are, gdy rzeczy jest kilka."),learningGoal:l("Исправить Pens is here на Pens are here.","Виправити Pens is here на Pens are here.","Corregir Pens is here a Pens are here.","Corrigir Pens is here para Pens are here.","Sửa Pens is here thành Pens are here.","Memperbaiki Pens is here menjadi Pens are here.","Pens is here ifadesini Pens are here yapın.","Poprawić Pens is here na Pens are here."),newVocabulary:vocabulary});
