import type { EpisodeSourcePhrase, EpisodeSourcePhraseLocalizedDetails } from './episode_01_source_v1';
import type { SessionKind } from './episode_01_session_map_v1';
import type { LocalizedIntroRunsSource, LocalizedSource, SessionSource } from './session_shard_from_source_v1';

type Locale = 'ru' | 'uk' | 'es' | 'pt-BR' | 'vi' | 'id' | 'tr' | 'pl';
const LOCALES: readonly Locale[] = ['ru', 'uk', 'es', 'pt-BR', 'vi', 'id', 'tr', 'pl'];
type Copy = { title: string; concept: string; formula: string; trap: string; prompt: string; correct: string; wrong: string; meaning: string; explanation: string };

// Каждая версия объясняет английский через привычную структуру собственного языка.
const COPY: Record<Locale, Copy> = {
  ru: { title: 'Вопросы о людях и вещах', concept: 'В русском вопросительное слово сразу ведёт вопрос. В английском после What, Where, Who или How маленькая форма to be выходит перед тем, о ком или о чём спрашивают.', formula: 'Стройте вопрос так: question word + am/is/are + subject + complement. What is this? и How are you? — две полные живые модели.', trap: 'Не оставляйте порядок утверждения после вопросительного слова. What this is? звучит как кусок, а What is this? — готовый вопрос.', prompt: 'Выберите полную английскую фразу.', correct: 'Верно: вопросительное слово, форма to be и порядок стоят на своих местах.', wrong: 'Этот вариант меняет обязательный порядок или форму to be.', meaning: 'Значение', explanation: 'Это самостоятельная живая фраза для вопроса или короткого описания.' },
  uk: { title: 'Запитання про людей і речі', concept: 'В українській питальне слово одразу веде запитання. В англійській після What, Where, Who або How форма to be стоїть перед тим, про кого чи про що питають.', formula: 'Будуйте так: question word + am/is/are + subject + complement. What is this? і How are you? — повні живі моделі.', trap: 'Не залишайте порядок твердження після питального слова. What this is? звучить уривком, а What is this? — готове запитання.', prompt: 'Оберіть повну англійську фразу.', correct: 'Правильно: питальне слово, форма to be і порядок на своїх місцях.', wrong: 'Цей варіант змінює обов’язковий порядок або форму to be.', meaning: 'Значення', explanation: 'Це самостійна жива фраза для запитання або короткого опису.' },
  es: { title: 'Preguntas sobre personas y cosas', concept: 'En español la palabra interrogativa abre la pregunta. En inglés, después de What, Where, Who o How, la forma de to be va antes de la persona o la cosa consultada.', formula: 'La forma es: question word + am/is/are + subject + complement. What is this? y How are you? son modelos completos.', trap: 'No mantengas el orden afirmativo después de la palabra interrogativa. What this is? queda incompleto; What is this? es una pregunta lista.', prompt: 'Elige la frase inglesa completa.', correct: 'Correcto: la palabra interrogativa, to be y el orden encajan.', wrong: 'Esta opción cambia el orden obligatorio o la forma de to be.', meaning: 'Significado', explanation: 'Es una frase independiente y natural para preguntar o describir brevemente.' },
  'pt-BR': { title: 'Perguntas sobre pessoas e coisas', concept: 'Em português, a palavra interrogativa abre a pergunta. Em inglês, depois de What, Where, Who ou How, a forma de to be fica antes da pessoa ou coisa perguntada.', formula: 'A estrutura é: question word + am/is/are + subject + complement. What is this? e How are you? são modelos completos.', trap: 'Não mantenha a ordem afirmativa após a palavra interrogativa. What this is? fica quebrado; What is this? é uma pergunta pronta.', prompt: 'Escolha a frase inglesa completa.', correct: 'Certo: a palavra interrogativa, to be e a ordem combinam.', wrong: 'Esta opção altera a ordem obrigatória ou a forma de to be.', meaning: 'Significado', explanation: 'É uma frase independente e natural para perguntar ou descrever brevemente.' },
  vi: { title: 'Câu hỏi về người và vật', concept: 'Trong tiếng Việt, từ hỏi mở đầu câu hỏi. Trong tiếng Anh, sau What, Where, Who hoặc How, dạng to be đứng trước người hay vật được hỏi.', formula: 'Mẫu là: question word + am/is/are + subject + complement. What is this? và How are you? là hai mẫu hoàn chỉnh.', trap: 'Đừng giữ trật tự câu kể sau từ hỏi. What this is? bị rời rạc; What is this? là câu hỏi hoàn chỉnh.', prompt: 'Chọn câu tiếng Anh hoàn chỉnh.', correct: 'Đúng: từ hỏi, dạng to be và trật tự đều phù hợp.', wrong: 'Phương án này đổi trật tự bắt buộc hoặc dạng to be.', meaning: 'Nghĩa', explanation: 'Đây là câu độc lập tự nhiên để hỏi hoặc miêu tả ngắn.' },
  id: { title: 'Pertanyaan tentang orang dan benda', concept: 'Dalam bahasa Indonesia kata tanya membuka pertanyaan. Dalam bahasa Inggris, setelah What, Where, Who, atau How, bentuk to be berada sebelum orang atau benda yang ditanyakan.', formula: 'Polanya: question word + am/is/are + subject + complement. What is this? dan How are you? adalah pola lengkap.', trap: 'Jangan memakai urutan pernyataan setelah kata tanya. What this is? terasa terputus; What is this? adalah pertanyaan lengkap.', prompt: 'Pilih kalimat bahasa Inggris lengkap.', correct: 'Benar: kata tanya, bentuk to be, dan urutannya sesuai.', wrong: 'Pilihan ini mengubah urutan wajib atau bentuk to be.', meaning: 'Arti', explanation: 'Ini kalimat mandiri yang alami untuk bertanya atau menjelaskan singkat.' },
  tr: { title: 'İnsanlar ve nesneler hakkında sorular', concept: 'Türkçede soru sözcüğü soruyu açar. İngilizcede What, Where, Who ya da How sonrasında to be biçimi sorulan kişi veya nesneden önce gelir.', formula: 'Kalıp: question word + am/is/are + subject + complement. What is this? ve How are you? tam örneklerdir.', trap: 'Soru sözcüğünden sonra bildirme sırasını korumayın. What this is? kopuktur; What is this? hazır bir sorudur.', prompt: 'Tam İngilizce cümleyi seçin.', correct: 'Doğru: soru sözcüğü, to be biçimi ve sıra uyumludur.', wrong: 'Bu seçenek zorunlu sırayı veya to be biçimini değiştirir.', meaning: 'Anlam', explanation: 'Bu, sormak veya kısa açıklama yapmak için doğal ve bağımsız bir cümledir.' },
  pl: { title: 'Pytania o ludzi i rzeczy', concept: 'Po polsku słowo pytające otwiera pytanie. W angielskim po What, Where, Who lub How forma to be stoi przed osobą albo rzeczą, o którą pytamy.', formula: 'Wzór: question word + am/is/are + subject + complement. What is this? oraz How are you? są pełnymi modelami.', trap: 'Nie zachowuj szyku oznajmującego po słowie pytającym. What this is? brzmi urwanie; What is this? jest gotowym pytaniem.', prompt: 'Wybierz pełne zdanie po angielsku.', correct: 'Dobrze: słowo pytające, forma to be i szyk pasują.', wrong: 'Ta opcja zmienia obowiązkowy szyk albo formę to be.', meaning: 'Znaczenie', explanation: 'To naturalne, samodzielne zdanie służące pytaniu albo krótkiej informacji.' },
};

const L = (select: (copy: Copy) => string): LocalizedSource => Object.fromEntries(LOCALES.map((locale) => [locale, select(COPY[locale])])) as unknown as LocalizedSource;
const tokens = (english: string): string[] => english.replace(/[?.!]/gu, '').split(/\s+/u).filter(Boolean);
const alternatives = (word: string): readonly string[] => ['what', 'where', 'who', 'how', 'this', 'that', 'my', 'your', 'his', 'her', 'is', 'are', 'am', 'he', 'she', 'it', 'you', 'we', 'they', 'here', 'home', 'ready', 'calm', 'fine', 'book', 'bag', 'cup', 'key'].filter((item) => item.toLowerCase() !== word.toLowerCase()).slice(0, 5);
const category = (word: string): string => /^(what|where|who|how)$/iu.test(word) ? 'question-word' : /^(is|are|am)$/iu.test(word) ? 'to-be' : /^(my|your|his|her)$/iu.test(word) ? 'possessive' : /^(this|that)$/iu.test(word) ? 'demonstrative' : /^(he|she|it|you|we|they)$/iu.test(word) ? 'pronoun' : 'lexical';
function localizedDetails(english: string): Record<Locale, EpisodeSourcePhraseLocalizedDetails> {
  const phraseTokens = tokens(english);
  return Object.fromEntries(LOCALES.map((locale) => {
    const copy = COPY[locale];
    return [locale, { meaning: `${copy.meaning}: ${english}`, explanation: `${copy.explanation} ${english}`, distractors: alternatives(phraseTokens[0]).map((value) => ({ value, reason: copy.wrong })), words: phraseTokens.map((correct) => ({ correct, prompt: `${copy.prompt} ${correct}`, distractors: alternatives(correct).map((value) => ({ value, reason: copy.wrong })) })) }];
  })) as unknown as Record<Locale, EpisodeSourcePhraseLocalizedDetails>;
}
function phrase(ordinal: number, position: number, english: string, features: readonly string[]): EpisodeSourcePhrase {
  const localized = localizedDetails(english);
  return { id: `e01-s${String(ordinal).padStart(2, '0')}-${String(position + 1).padStart(2, '0')}`, english, russian: localized.ru.meaning, explanation: localized.ru.explanation, localizedDetails: localized, features, words: tokens(english).map((correct) => ({ correct, category: category(correct), distractors: alternatives(correct).map((value) => ({ value, reasonCode: 'wrong_token_for_position', why: 'Это другое слово; в этой позиции оно не строит нужную английскую фразу.' })) })) };
}
function runs(body: LocalizedSource, target: string): LocalizedIntroRunsSource {
  return Object.fromEntries(LOCALES.map((locale) => { const text = body[locale] as string; const at = text.indexOf(target); return [locale, at < 0 ? [{ text, semantic: 'explanation' as const }] : [{ text: text.slice(0, at), semantic: 'explanation' as const }, { text: target, semantic: 'targetCorrect' as const }, { text: text.slice(at + target.length), semantic: 'explanation' as const }]]; })) as unknown as LocalizedIntroRunsSource;
}

const PHRASES: Record<number, readonly string[]> = {
  33: ['What is this?', 'What is that?', 'What is it?', 'This is a book.', 'That is a bag.', 'This is a cup.', 'That is a key.', 'What is this book?', 'What is that bag?', 'Is this a cup?', 'Is that a key?', 'This is my book.', 'That is your bag.', 'What is my cup?', 'What is your key?'],
  34: ['Where is he?', 'Where is she?', 'Where is it?', 'Where are you?', 'Where are we?', 'Where are they?', 'Where is my mother?', 'Where is your father?', 'Where is this book?', 'Where is that bag?', 'Is he here?', 'Is she home?', 'Are you here?', 'Are they home?', 'Where is my key?'],
  35: ['Who is he?', 'Who is she?', 'Who is this?', 'Who is that?', 'Who is your mother?', 'Who is your father?', 'Who is my sister?', 'Who is my brother?', 'Is this your mother?', 'Is that your father?', 'He is my brother.', 'She is my sister.', 'This is my mother.', 'That is your father.', 'Who is your sister?'],
  36: ['How are you?', 'How is he?', 'How is she?', 'How are we?', 'How are they?', 'I am fine.', 'You are okay.', 'He is ready.', 'She is calm.', 'We are happy.', 'They are busy.', 'Is he tired?', 'Is she happy?', 'Are you ready?', 'Are they calm?'],
  37: ['This is my book.', 'That is your bag.', 'My cup is here.', 'Your key is here.', 'Is this my book?', 'Is that your bag?', 'Where is my cup?', 'Where is your key?', 'My mother is here.', 'Your father is home.', 'My sister is ready.', 'Your brother is calm.', 'Is this your cup?', 'Is that my key?', 'Who is your mother?'],
  38: ['This is his book.', 'That is her bag.', 'His cup is here.', 'Her key is here.', 'Is this his book?', 'Is that her bag?', 'Where is his cup?', 'Where is her key?', 'His mother is here.', 'Her father is home.', 'His sister is ready.', 'Her brother is calm.', 'Is this her cup?', 'Is that his key?', 'Who is her mother?'],
  39: ['What is this?', 'Where is he?', 'Who is she?', 'How are you?', 'What is that?', 'Where are they?', 'Who is your mother?', 'How is he?', 'What is my book?', 'Where is her key?', 'Who is this?', 'How are they?', 'What is your bag?', 'Where is my cup?', 'How is she?'],
  40: ['What is this?', 'Where is my book?', 'Who is your mother?', 'How are you?', 'This is my cup.', 'That is your bag.', 'His key is here.', 'Her book is here.', 'Is this his bag?', 'Is that her cup?', 'Where are they?', 'Who is my brother?', 'How is she?', 'What is your key?', 'Where is her father?'],
};
const KINDS: Record<number, SessionKind> = { 33: 'words_then_phrases', 34: 'phrases', 35: 'phrases', 36: 'phrases', 37: 'words_then_phrases', 38: 'words_then_phrases', 39: 'voice', 40: 'checkpoint' };
const FEATURES: Record<number, readonly string[]> = { 33: ['copula_be', 'question_inversion', 'question_word', 'demonstrative'], 34: ['copula_be', 'question_inversion', 'question_word'], 35: ['copula_be', 'question_inversion', 'question_word', 'family_noun'], 36: ['copula_be', 'question_inversion', 'question_word', 'state_adjective'], 37: ['copula_be', 'question_inversion', 'possessive_my', 'possessive_your'], 38: ['copula_be', 'question_inversion', 'possessive_his_her'], 39: ['copula_be', 'question_inversion', 'question_word', 'spoken_production'], 40: ['copula_be', 'question_inversion', 'question_word', 'possessive_my', 'possessive_your', 'possessive_his_her'] };

export function buildEpisode01Session33To40(ordinal: 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40): SessionSource {
  const target = PHRASES[ordinal][0];
  const title = L((copy) => copy.title);
  const bodies = [L((copy) => `${copy.concept} ${target}`), L((copy) => `${copy.formula} ${target}`), L((copy) => `${copy.trap} ${target}`)];
  const introPages = bodies.map((body, index) => ({ kind: (['concept', 'formula', 'trap'] as const)[index], title, body, bodyRuns: runs(body, target), question: { prompt: L((copy) => copy.prompt), choices: [L(() => target), L(() => PHRASES[ordinal][1]), L(() => target.replace(/\b(is|are|am)\b/gu, 'be'))], correctChoiceIndex: 0 as const, explanation: L((copy) => copy.correct) } })) as unknown as SessionSource['introPages'];
  return { packageId: 'learning-v2-en-v1', targetLanguage: 'en', episodeOrdinal: 1, requiredSessionOrdinal: ordinal, canDoOutcomeId: 'obj-e01-question-words-and-possessives', generationInputFingerprint: `authored-e01-s${ordinal}-v1`, title, summary: L((copy) => copy.explanation), learningGoal: L((copy) => copy.formula), introPages, phrases: PHRASES[ordinal].map((english, index) => phrase(ordinal, index, english, FEATURES[ordinal])) };
}

export function assertEpisode01Sessions33To40Contract(sources: readonly SessionSource[]): void {
  const chapter = sources.filter((source) => source.requiredSessionOrdinal >= 33 && source.requiredSessionOrdinal <= 40);
  expect(chapter.map((source) => source.requiredSessionOrdinal)).toEqual([33, 34, 35, 36, 37, 38, 39, 40]);
  chapter.forEach((source) => { const ordinal = source.requiredSessionOrdinal; expect(KINDS[ordinal]).toBeTruthy(); expect(source.phrases).toHaveLength(15); source.phrases.forEach((item) => { expect(item.english).not.toMatch(/\b(?:do|does)\b/iu); expect(Object.keys(item.localizedDetails ?? {}).sort()).toEqual([...LOCALES].sort()); item.words.forEach((word) => expect(new Set(word.distractors.map((entry) => entry.value)).size).toBe(5)); }); source.introPages.forEach((page) => LOCALES.forEach((locale) => { expect(page.bodyRuns?.[locale]?.map((run) => run.text).join('')).toBe(page.body[locale]); expect(page.question.choices[page.question.correctChoiceIndex][locale]).not.toMatch(/\b(?:do|does)\b/iu); })); });
  expect(chapter[0].phrases.some((item) => item.features.includes('demonstrative'))).toBe(true);
  expect(chapter[4].phrases.some((item) => item.features.includes('possessive_your'))).toBe(true);
  expect(chapter[5].phrases.some((item) => item.features.includes('possessive_his_her'))).toBe(true);
}
