import type { LocalizedSource } from "./session_shard_from_source_v1";

type Locale = "ru" | "uk" | "es" | "pt-BR" | "vi" | "id" | "tr" | "pl";
type Family = "speed_match" | "listen_build_dictation" | "context_gap_grammar" | "phrase_builder";
type Selection = Readonly<{
  correct: string;
  distractors: readonly Readonly<{ value: string; sourceValue: string }>[];
}>;
const L = (value: Record<Locale, string>): LocalizedSource => value as LocalizedSource;

const S = (
  correct: string,
  first: readonly [value: string, sourceValue: string],
  second: readonly [value: string, sourceValue: string],
): Selection => Object.freeze({
  correct,
  distractors: Object.freeze([
    Object.freeze({ value: first[0], sourceValue: first[1] }),
    Object.freeze({ value: second[0], sourceValue: second[1] }),
  ]),
});

const SELECTIONS: Readonly<Record<string, Selection>> = Object.freeze({
  ["speed_match\0Am I here?"]: S("here", ["Are you here?", "Are you here?"], ["I am here.", "I am here."]),
  ["listen_build_dictation\0You’re here."]: S("You’re", ["Your", "Your"], ["You", "You"]),
  ["context_gap_grammar\0I am not ready."]: S("not", ["very", "very"], ["too", "too"]),
  ["phrase_builder\0You are not ready."]: S("are", ["am", "am"], ["is", "is"]),
  ["listen_build_dictation\0Are you ready?"]: S("Are", ["Is", "Is"], ["Do", "Do"]),
  ["context_gap_grammar\0Am I ready?"]: S("Am", ["Are", "Are"], ["Do", "Do"]),
  ["phrase_builder\0You’re not ready."]: S("You’re", ["Your", "Your"], ["You", "You"]),
  ["speed_match\0I am cold."]: S("cold", ["I am calm.", "I am calm."], ["I am warm.", "I am warm."]),
  ["listen_build_dictation\0I am warm."]: S("am", ["are", "are"], ["cold", "cold"]),
  ["context_gap_grammar\0Are you on the bus?"]: S("on", ["in", "in"], ["at", "at"]),
  ["phrase_builder\0Am I okay?"]: S("Am", ["Are", "Are"], ["Is", "Is"]),
  ["speed_match\0You’re all right."]: S("all right", ["Are you all right?", "Are you all right?"], ["You’re not all right.", "You’re not all right."]),
});

export function episode01Session16TaskSelectionV1(
  family: string,
  target: string,
): Selection | undefined {
  return SELECTIONS[`${family}\0${target}`];
}

const FEEDBACK: Readonly<Record<string, LocalizedSource>> = Object.freeze({
  ["Am I here?\0Are you here?"]: L({
    ru: "Are you here? спрашивает о месте собеседника и потому легко отвлекает тем же here. В нужном вопросе говорящий спрашивает о себе: Am ставится перед I.",
    uk: "Are you here? питає про місце співрозмовника й тому легко відволікає тим самим here. У потрібному питанні мовець питає про себе: Am ставиться перед I.",
    es: "Are you here? pregunta por el lugar del interlocutor y atrae porque conserva here. La pregunta buscada habla de quien la formula: Am debe aparecer delante de I.",
    "pt-BR": "Are you here? pergunta pelo lugar do interlocutor e distrai porque mantém here. A pergunta necessária fala de quem pergunta: Am deve vir antes de I.",
    vi: "Are you here? hỏi vị trí của người nghe nên dễ gây nhầm vì vẫn có here. Câu cần chọn hỏi về chính người nói, vì thế Am phải đứng trước I.",
    id: "Are you here? menanyakan lokasi lawan bicara dan menggoda karena tetap memakai here. Pertanyaan yang dicari tentang penutur sendiri, jadi Am harus berada sebelum I.",
    tr: "Are you here? aynı here sözcüğüyle karşıdaki kişinin yerini sorar ve bu yüzden yanıltır. Aranan soru konuşanın kendisidir; Am, I önüne gelmelidir.",
    pl: "Are you here? pyta o miejsce rozmówcy i kusi tym samym here. Potrzebne pytanie dotyczy mówiącego, dlatego Am musi stać przed I.",
  }),
  ["Am I here?\0I am here."]: L({
    ru: "I am here. сохраняет человека и место, но прямой порядок уже утверждает «Я здесь». Чтобы попросить подтверждение, am выходит вперёд и получается Am I here?",
    uk: "I am here. зберігає людину й місце, але прямий порядок уже стверджує «Я тут». Щоб попросити підтвердження, am виходить уперед: Am I here?",
    es: "I am here. conserva la persona y el lugar, pero el orden directo afirma «estoy aquí». Para pedir confirmación, am pasa delante y forma Am I here?",
    "pt-BR": "I am here. mantém a pessoa e o lugar, mas a ordem direta afirma «estou aqui». Para pedir confirmação, am passa para a frente e forma Am I here?",
    vi: "I am here. giữ nguyên người và nơi nhưng trật tự thẳng tạo câu kể “tôi ở đây”. Muốn xin xác nhận, am phải lên trước để thành Am I here?",
    id: "I am here. mempertahankan orang dan tempat, tetapi urutan langsung membuat pernyataan. Untuk meminta kepastian, am pindah ke depan menjadi Am I here?",
    tr: "I am here. kişi ve yeri korur, fakat düz sıra “Buradayım” bildirimi yapar. Doğrulama istemek için am öne geçer ve Am I here? oluşur.",
    pl: "I am here. zachowuje osobę i miejsce, lecz prosty szyk tworzy stwierdzenie. Aby poprosić o potwierdzenie, am przechodzi na początek: Am I here?",
  }),
  ["You’re here.\0Your"]: L({
    ru: "Your звучит рядом с You’re, но выражает принадлежность и требует существительного: your bag. Здесь нужно сокращение you are, поэтому выбирается цельное You’re.",
    uk: "Your звучить схоже на You’re, але виражає належність і потребує іменника: your bag. Тут потрібне скорочення you are, тому обираємо You’re.",
    es: "Your suena cerca de You’re, pero expresa posesión y necesita un sustantivo, como your bag. Aquí se requiere la contracción de you are: You’re.",
    "pt-BR": "Your soa parecido com You’re, mas indica posse e precisa de um substantivo, como your bag. Aqui é necessária a contração de you are: You’re.",
    vi: "Your nghe gần giống You’re nhưng chỉ sự sở hữu và phải có danh từ như your bag. Ở đây cần dạng rút gọn của you are, nên chọn You’re.",
    id: "Your terdengar dekat dengan You’re, tetapi menyatakan kepemilikan dan memerlukan nomina seperti your bag. Di sini diperlukan singkatan you are: You’re.",
    tr: "Your, You’re biçimine benzer duyulur; ancak sahiplik bildirir ve your bag gibi bir isim ister. Burada you are kısaltması olan You’re gerekir.",
    pl: "Your brzmi podobnie do You’re, lecz oznacza posiadanie i wymaga rzeczownika, np. your bag. Tutaj potrzebny jest skrót od you are: You’re.",
  }),
  ["You’re here.\0You"]: L({
    ru: "You правильно называет собеседника, но само по себе не связывает его с here. В полной фразе обязательно слышно are внутри сокращения You’re.",
    uk: "You правильно називає співрозмовника, але саме не пов’язує його з here. У повній фразі обов’язково чути are всередині скорочення You’re.",
    es: "You identifica bien al interlocutor, pero por sí solo no lo enlaza con here. La frase completa necesita are dentro de la contracción You’re.",
    "pt-BR": "You identifica corretamente o interlocutor, mas sozinho não o liga a here. A frase completa precisa de are dentro da contração You’re.",
    vi: "You gọi đúng người nghe nhưng đứng một mình không nối người đó với here. Câu đầy đủ phải có are bên trong dạng rút gọn You’re.",
    id: "You menunjuk lawan bicara dengan benar, tetapi sendirian tidak menghubungkannya dengan here. Kalimat lengkap memerlukan are di dalam You’re.",
    tr: "You doğru kişiyi gösterir, fakat tek başına onu here ile bağlamaz. Tam cümlede You’re kısaltmasının içindeki are mutlaka bulunur.",
    pl: "You właściwie wskazuje rozmówcę, ale samo nie łączy go z here. Pełne zdanie wymaga are ukrytego w skrócie You’re.",
  }),
  ["I am not ready.\0very"]: L({
    ru: "Very усиливает признак и дало бы смысл «Я очень готов», а не отрицание. Здесь требуется not после am, чтобы прямо сообщить об отсутствии готовности.",
    uk: "Very підсилює ознаку й дало б зміст «Я дуже готовий», а не заперечення. Тут потрібне not після am, щоб повідомити про неготовність.",
    es: "Very intensifica la cualidad y produciría «estoy muy preparado», no una negación. Aquí hace falta not después de am para negar ready.",
    "pt-BR": "Very intensifica a característica e produziria «estou muito pronto», não uma negação. Aqui é preciso not depois de am para negar ready.",
    vi: "Very làm mức độ ready mạnh hơn, thành ý “rất sẵn sàng”, chứ không phủ định. Ở đây cần not sau am để nói chưa sẵn sàng.",
    id: "Very memperkuat ready dan akan berarti “sangat siap”, bukan penyangkalan. Di sini not harus berada setelah am untuk menolak ready.",
    tr: "Very, ready özelliğini güçlendirip “çok hazırım” anlamı verir; olumsuzluk kurmaz. Hazır olmadığını söylemek için am sonrasında not gerekir.",
    pl: "Very wzmacnia cechę i dałoby znaczenie „jestem bardzo gotowy”, a nie przeczenie. Tutaj po am potrzebne jest not, aby zanegować ready.",
  }),
  ["I am not ready.\0too"]: L({
    ru: "Too может означать «тоже» или чрезмерную степень, но не создаёт «не». Отрицание готовности строится единственным not между am и ready.",
    uk: "Too може означати «теж» або надмірний ступінь, але не створює «не». Заперечення готовності будується через not між am і ready.",
    es: "Too puede significar «también» o un grado excesivo, pero no crea la negación. La falta de preparación se expresa con not entre am y ready.",
    "pt-BR": "Too pode significar «também» ou um grau excessivo, mas não cria negação. A falta de prontidão se expressa com not entre am e ready.",
    vi: "Too có thể mang nghĩa “cũng” hoặc quá mức, nhưng không tạo ý phủ định. Muốn nói chưa sẵn sàng phải đặt not giữa am và ready.",
    id: "Too dapat berarti “juga” atau berlebihan, tetapi tidak membentuk penyangkalan. Ketidaksiapan dinyatakan dengan not di antara am dan ready.",
    tr: "Too “de/da” ya da aşırı derece anlamı verebilir, fakat olumsuzluk kurmaz. Hazır olmama anlamı am ile ready arasındaki not ile oluşur.",
    pl: "Too może znaczyć „też” albo nadmierny stopień, lecz nie tworzy przeczenia. Brak gotowości wyraża not umieszczone między am i ready.",
  }),
  ["You are not ready.\0am"]: L({
    ru: "Am привычно связано с I, поэтому рядом с you создаёт смешанную пару. Для собеседника нужна форма are: You are not ready.",
    uk: "Am звично пов’язане з I, тому поруч із you створює змішану пару. Для співрозмовника потрібне are: You are not ready.",
    es: "Am pertenece a la pareja con I y junto a you mezcla dos personas. Para el interlocutor corresponde are: You are not ready.",
    "pt-BR": "Am pertence à dupla com I e, ao lado de you, mistura duas pessoas. Para o interlocutor corresponde are: You are not ready.",
    vi: "Am vốn đi với I nên đặt cạnh you sẽ trộn hai cặp. Khi nói về người nghe phải dùng are: You are not ready.",
    id: "Am berpasangan dengan I, sehingga di samping you mencampur dua orang. Untuk lawan bicara diperlukan are: You are not ready.",
    tr: "Am, I ile eşleşir; you yanında kullanılması iki kişiyi karıştırır. Karşıdaki kişi için are gerekir: You are not ready.",
    pl: "Am tworzy parę z I, więc obok you miesza dwie osoby. Dla rozmówcy potrzebna jest forma are: You are not ready.",
  }),
  ["You are not ready.\0is"]: L({
    ru: "Is относится к he, she или it, а не к you. В этой фразе человек — собеседник, поэтому после you должна стоять are.",
    uk: "Is стосується he, she або it, а не you. У цій фразі людина — співрозмовник, тому після you має стояти are.",
    es: "Is corresponde a he, she o it, no a you. En esta frase se habla del interlocutor, así que después de you debe aparecer are.",
    "pt-BR": "Is corresponde a he, she ou it, não a you. Nesta frase se fala do interlocutor, portanto depois de you deve aparecer are.",
    vi: "Is đi với he, she hoặc it chứ không đi với you. Câu này nói về người nghe nên sau you phải là are.",
    id: "Is digunakan untuk he, she, atau it, bukan you. Kalimat ini membicarakan lawan bicara, jadi sesudah you harus ada are.",
    tr: "Is, he, she ya da it ile kullanılır; you ile değil. Bu cümle karşıdaki kişiyi anlattığı için you sonrasında are gelmelidir.",
    pl: "Is pasuje do he, she lub it, a nie do you. Zdanie dotyczy rozmówcy, dlatego po you musi wystąpić are.",
  }),
  ["Are you ready?\0Is"]: L({
    ru: "Is выглядит как вопросительная связка, но с you не согласуется: оно ждёт he, she или it. Вопрос к собеседнику открывается Are you.",
    uk: "Is схоже на питальну зв’язку, але з you не узгоджується: воно чекає he, she або it. Питання до співрозмовника починається Are you.",
    es: "Is parece una cópula interrogativa, pero no concuerda con you: espera he, she o it. La pregunta al interlocutor empieza con Are you.",
    "pt-BR": "Is parece uma ligação interrogativa, mas não concorda com you: espera he, she ou it. A pergunta ao interlocutor começa com Are you.",
    vi: "Is trông giống từ mở đầu câu hỏi nhưng không hòa hợp với you; nó cần he, she hoặc it. Câu hỏi cho người nghe bắt đầu Are you.",
    id: "Is tampak seperti pembuka pertanyaan, tetapi tidak sesuai dengan you; bentuk itu menunggu he, she, atau it. Pertanyaan kepada lawan bicara dimulai Are you.",
    tr: "Is soru başlangıcına benzer, fakat you ile uyuşmaz; he, she ya da it bekler. Karşıdaki kişiye soru Are you ile başlar.",
    pl: "Is wygląda jak początek pytania, lecz nie zgadza się z you; oczekuje he, she lub it. Pytanie do rozmówcy zaczyna się od Are you.",
  }),
  ["Are you ready?\0Do"]: L({
    ru: "Do часто начинает английский вопрос, но оно нужно перед обычным глаголом. Ready здесь соединяется с you через be, поэтому вопрос начинается Are.",
    uk: "Do часто починає англійське питання, але потрібне перед звичайним дієсловом. Ready тут поєднується з you через be, тому питання починається Are.",
    es: "Do inicia muchas preguntas, pero se usa delante de un verbo léxico. Ready se enlaza aquí con you mediante be, así que la pregunta comienza con Are.",
    "pt-BR": "Do inicia muitas perguntas, mas é usado diante de um verbo comum. Ready se liga aqui a you por meio de be, então a pergunta começa com Are.",
    vi: "Do thường mở đầu câu hỏi nhưng dùng trước động từ thường. Ready ở đây nối với you bằng be, vì thế câu hỏi phải bắt đầu bằng Are.",
    id: "Do memang membuka banyak pertanyaan, tetapi dipakai sebelum verba biasa. Ready terhubung dengan you melalui be, jadi pertanyaan dimulai Are.",
    tr: "Do birçok soruyu başlatır, ancak normal bir fiilden önce kullanılır. Ready burada you ile be üzerinden bağlanır; bu yüzden soru Are ile başlar.",
    pl: "Do rozpoczyna wiele pytań, lecz stoi przed zwykłym czasownikiem. Ready łączy się tutaj z you przez be, więc pytanie zaczyna Are.",
  }),
  ["Am I ready?\0Are"]: L({
    ru: "Are правильно образует вопрос с you, но после него здесь стоит I. Для I сохраняется форма am, вынесенная вперёд: Am I ready?",
    uk: "Are правильно утворює питання з you, але після нього тут стоїть I. Для I зберігається форма am, винесена вперед: Am I ready?",
    es: "Are forma correctamente una pregunta con you, pero aquí aparece I. Con I se conserva am y se adelanta: Am I ready?",
    "pt-BR": "Are forma corretamente uma pergunta com you, mas aqui aparece I. Com I se mantém am e ele vai para a frente: Am I ready?",
    vi: "Are tạo câu hỏi đúng với you, nhưng ở đây sau chỗ trống là I. I phải giữ am và đưa lên đầu: Am I ready?",
    id: "Are membentuk pertanyaan dengan you, tetapi di sini subjeknya I. I tetap memakai am yang dipindahkan ke depan: Am I ready?",
    tr: "Are, you ile doğru soru kurar; burada ise özne I olur. I, öne taşınan am biçimini korur: Am I ready?",
    pl: "Are poprawnie tworzy pytanie z you, lecz tutaj występuje I. Przy I pozostaje am przeniesione na początek: Am I ready?",
  }),
  ["Am I ready?\0Do"]: L({
    ru: "Do соблазняет привычным вопросительным началом, но ready не является действием. Состояние говорящего связывается через am, поэтому нужен порядок Am I.",
    uk: "Do спокушає звичним початком питання, але ready не є дією. Стан мовця пов’язується через am, тому потрібен порядок Am I.",
    es: "Do atrae como inicio habitual de pregunta, pero ready no es una acción. El estado de quien habla se enlaza con am, por eso corresponde Am I.",
    "pt-BR": "Do atrai como começo comum de pergunta, mas ready não é uma ação. O estado de quem fala se liga por am, portanto corresponde Am I.",
    vi: "Do dễ gây nhầm vì thường mở đầu câu hỏi, nhưng ready không phải hành động. Trạng thái của người nói nối bằng am, nên cần Am I.",
    id: "Do menggoda sebagai awal pertanyaan yang umum, tetapi ready bukan tindakan. Keadaan penutur dihubungkan dengan am, sehingga bentuknya Am I.",
    tr: "Do alışıldık bir soru başlangıcı gibi görünür, fakat ready bir eylem değildir. Konuşanın durumu am ile bağlanır; bu yüzden Am I gerekir.",
    pl: "Do kusi jako częsty początek pytania, lecz ready nie jest czynnością. Stan mówiącego łączy się przez am, dlatego potrzebne jest Am I.",
  }),
  ["You’re not ready.\0Your"]: L({
    ru: "Your обозначает принадлежность и должно стоять перед существительным, например your bag. Здесь нужен смысл you are, уже собранный в You’re перед not ready.",
    uk: "Your позначає належність і має стояти перед іменником, наприклад your bag. Тут потрібне you are, уже зібране в You’re перед not ready.",
    es: "Your expresa posesión y debe ir delante de un sustantivo, como your bag. Aquí se necesita you are, ya contraído en You’re antes de not ready.",
    "pt-BR": "Your expressa posse e deve vir antes de um substantivo, como your bag. Aqui é preciso you are, já contraído em You’re antes de not ready.",
    vi: "Your chỉ sự sở hữu và phải đứng trước danh từ như your bag. Ở đây cần nghĩa you are đã rút gọn thành You’re trước not ready.",
    id: "Your menyatakan kepemilikan dan harus diikuti nomina seperti your bag. Di sini diperlukan you are yang sudah disingkat menjadi You’re sebelum not ready.",
    tr: "Your sahiplik bildirir ve your bag örneğindeki gibi bir isimden önce gelir. Burada not ready önünde You’re içinde kısalan you are gerekir.",
    pl: "Your oznacza posiadanie i musi stać przed rzeczownikiem, np. your bag. Tutaj potrzebne jest you are skrócone do You’re przed not ready.",
  }),
  ["You’re not ready.\0You"]: L({
    ru: "You оставляет правильного человека, но убирает связку are. Полная отрицательная фраза требует You’re, затем not и только потом ready.",
    uk: "You лишає правильну людину, але прибирає зв’язку are. Повна заперечна фраза потребує You’re, потім not і лише тоді ready.",
    es: "You mantiene a la persona correcta, pero elimina are. La frase negativa completa necesita You’re, después not y finalmente ready.",
    "pt-BR": "You mantém a pessoa correta, mas elimina are. A frase negativa completa precisa de You’re, depois not e por fim ready.",
    vi: "You giữ đúng người nhưng làm mất are. Câu phủ định đầy đủ cần You’re, sau đó là not rồi mới đến ready.",
    id: "You mempertahankan orang yang benar, tetapi menghilangkan are. Kalimat negatif lengkap memerlukan You’re, lalu not, kemudian ready.",
    tr: "You doğru kişiyi korur, fakat are bağını düşürür. Tam olumsuz cümlede önce You’re, sonra not ve en son ready gerekir.",
    pl: "You zachowuje właściwą osobę, ale usuwa are. Pełne przeczenie wymaga kolejno You’re, not i dopiero ready.",
  }),
  ["I am cold.\0I am calm."]: L({
    ru: "I am calm. сохраняет правильную модель I am, но calm означает «я спокоен». Для ощущения холода нужно другое слово — cold.",
    uk: "I am calm. зберігає правильну модель I am, але calm означає «я спокійний». Для відчуття холоду потрібне інше слово — cold.",
    es: "I am calm. conserva la estructura I am, pero calm significa «estoy tranquilo». Para expresar la sensación de frío se necesita cold.",
    "pt-BR": "I am calm. mantém a estrutura I am, mas calm significa «estou calmo». Para expressar a sensação de frio é preciso cold.",
    vi: "I am calm. giữ đúng cấu trúc I am nhưng calm nghĩa là “tôi bình tĩnh”. Muốn nói cảm giác lạnh phải chọn cold.",
    id: "I am calm. mempertahankan pola I am, tetapi calm berarti “saya tenang”. Untuk menyatakan rasa dingin diperlukan cold.",
    tr: "I am calm. doğru I am yapısını korur, ancak calm “sakinim” demektir. Soğuk hissetmek için cold sözcüğü gerekir.",
    pl: "I am calm. zachowuje poprawny wzór I am, lecz calm znaczy „jestem spokojny”. Odczucie chłodu wymaga słowa cold.",
  }),
  ["I am cold.\0I am warm."]: L({
    ru: "I am warm. говорит о противоположном ощущении: говорящему тепло. Человек и модель те же, но значение проверки требует cold — «мне холодно».",
    uk: "I am warm. говорить про протилежне відчуття: мовцеві тепло. Людина й модель ті самі, але потрібне cold — «мені холодно».",
    es: "I am warm. expresa la sensación contraria: quien habla siente calor. La persona y la estructura coinciden, pero el significado pedido requiere cold.",
    "pt-BR": "I am warm. expressa a sensação oposta: quem fala sente calor. A pessoa e a estrutura coincidem, mas o sentido pedido exige cold.",
    vi: "I am warm. diễn tả cảm giác đối lập là người nói thấy ấm. Người và cấu trúc đều giống, nhưng nghĩa được hỏi cần cold.",
    id: "I am warm. menyatakan perasaan sebaliknya, yaitu penutur merasa hangat. Orang dan polanya sama, tetapi makna yang diminta memerlukan cold.",
    tr: "I am warm. karşıt duyguyu, yani konuşanın sıcak hissettiğini söyler. Kişi ve yapı aynıdır; istenen anlam cold gerektirir.",
    pl: "I am warm. wyraża przeciwne odczucie: mówiącemu jest ciepło. Osoba i konstrukcja są te same, lecz wymagane znaczenie potrzebuje cold.",
  }),
  ["I am warm.\0are"]: L({
    ru: "Are относится к you и множественному числу, поэтому после I ломает согласование. Говорящий о себе выбирает устойчивую пару I am.",
    uk: "Are стосується you та множини, тому після I ламає узгодження. Мовець про себе обирає сталу пару I am.",
    es: "Are corresponde a you y al plural, por eso después de I rompe la concordancia. Quien habla de sí mismo necesita la pareja fija I am.",
    "pt-BR": "Are corresponde a you e ao plural, por isso depois de I quebra a concordância. Quem fala de si precisa da dupla fixa I am.",
    vi: "Are đi với you và số nhiều nên đặt sau I sẽ sai hòa hợp. Người nói về mình phải giữ cặp cố định I am.",
    id: "Are digunakan untuk you dan bentuk jamak, sehingga sesudah I merusak kesesuaian. Penutur tentang dirinya memerlukan pasangan I am.",
    tr: "Are, you ve çoğul öznelerle kullanılır; I sonrasında uyumu bozar. Konuşan kendisi için sabit I am çiftini seçer.",
    pl: "Are pasuje do you i liczby mnogiej, dlatego po I łamie zgodę. Mówiący o sobie potrzebuje stałej pary I am.",
  }),
  ["I am warm.\0cold"]: L({
    ru: "Cold называет противоположное ощущение — «мне холодно». Здесь нужно warm, потому что проверяется состояние, когда говорящему тепло.",
    uk: "Cold називає протилежне відчуття — «мені холодно». Тут потрібне warm, бо перевіряється стан, коли мовцеві тепло.",
    es: "Cold nombra la sensación contraria, «tengo frío». Aquí se necesita warm porque se pregunta por el estado de sentir calor.",
    "pt-BR": "Cold nomeia a sensação contrária, «estou com frio». Aqui é preciso warm porque se pergunta pelo estado de sentir calor.",
    vi: "Cold gọi cảm giác đối lập là “tôi thấy lạnh”. Ở đây cần warm vì ý được kiểm tra là người nói cảm thấy ấm.",
    id: "Cold menyebut perasaan sebaliknya, yaitu merasa dingin. Di sini diperlukan warm karena keadaan yang diuji adalah rasa hangat.",
    tr: "Cold karşıt duyguyu, “üşüyorum” anlamını verir. Burada konuşanın sıcak hissetmesi sorulduğu için warm gerekir.",
    pl: "Cold nazywa przeciwne odczucie: „jest mi zimno”. Tutaj potrzebne jest warm, ponieważ sprawdzany stan oznacza odczuwanie ciepła.",
  }),
  ["Are you on the bus?\0in"]: L({
    ru: "In the bus понятно буквально как нахождение внутри, но для обычной поездки английский выбирает готовое on the bus. В этой ситуации нужен предлог on.",
    uk: "In the bus буквально зрозуміле як перебування всередині, але для звичайної поїздки англійська обирає on the bus. Тут потрібен on.",
    es: "In the bus puede entenderse como estar físicamente dentro, pero para viajar normalmente el inglés usa el bloque on the bus. Aquí corresponde on.",
    "pt-BR": "In the bus pode ser entendido como estar fisicamente dentro, mas para uma viagem comum o inglês usa on the bus. Aqui corresponde on.",
    vi: "In the bus có thể hiểu theo nghĩa ở bên trong, nhưng khi nói đang đi xe buýt tiếng Anh dùng cụm on the bus. Vì vậy cần on.",
    id: "In the bus dapat dipahami sebagai berada di bagian dalam, tetapi untuk perjalanan biasa bahasa Inggris memakai on the bus. Jadi yang diperlukan on.",
    tr: "In the bus fiziksel olarak içeride bulunmayı düşündürebilir; normal yolculukta İngilizce on the bus kalıbını kullanır. Burada on gerekir.",
    pl: "In the bus może dosłownie sugerować wnętrze pojazdu, lecz przy zwykłej podróży angielski używa on the bus. Tutaj potrzebne jest on.",
  }),
  ["Are you on the bus?\0at"]: L({
    ru: "At the bus указывает скорее на точку рядом с автобусом, а не на поездку в нём. Вопрос о пассажире использует цельное сочетание on the bus.",
    uk: "At the bus указує радше на точку біля автобуса, а не на поїздку в ньому. Питання про пасажира використовує ціле on the bus.",
    es: "At the bus situaría a la persona junto al autobús, no viajando en él. La pregunta sobre un pasajero usa la combinación completa on the bus.",
    "pt-BR": "At the bus colocaria a pessoa junto ao ônibus, não viajando nele. A pergunta sobre um passageiro usa a combinação completa on the bus.",
    vi: "At the bus gợi vị trí ở cạnh xe buýt chứ không phải đang đi trên xe. Câu hỏi về hành khách dùng trọn cụm on the bus.",
    id: "At the bus menunjuk titik di dekat bus, bukan keadaan sedang bepergian di dalamnya. Pertanyaan tentang penumpang memakai on the bus.",
    tr: "At the bus kişiyi otobüsün yanında bir noktaya yerleştirir, yolculuğu anlatmaz. Yolcuyu soran cümle on the bus bütününü kullanır.",
    pl: "At the bus wskazywałoby punkt przy autobusie, a nie podróż w nim. Pytanie o pasażera używa pełnego połączenia on the bus.",
  }),
  ["Am I okay?\0Are"]: L({
    ru: "Are открывает вопрос о you, но здесь говорящий проверяет собственное состояние через I. Поэтому нужна форма am перед I: Am I okay?",
    uk: "Are відкриває питання про you, але тут мовець перевіряє власний стан через I. Тому потрібне am перед I: Am I okay?",
    es: "Are abre una pregunta sobre you, pero aquí quien habla comprueba su propio estado con I. Por eso hace falta am delante de I: Am I okay?",
    "pt-BR": "Are abre uma pergunta sobre you, mas aqui quem fala verifica o próprio estado com I. Por isso é necessário am antes de I: Am I okay?",
    vi: "Are mở câu hỏi về you, còn ở đây người nói kiểm tra trạng thái của chính mình bằng I. Vì vậy phải dùng am trước I: Am I okay?",
    id: "Are membuka pertanyaan tentang you, sedangkan di sini penutur memeriksa dirinya dengan I. Karena itu am harus berada sebelum I: Am I okay?",
    tr: "Are, you hakkında soru açar; burada konuşan I ile kendi durumunu sorar. Bu nedenle I önünde am gerekir: Am I okay?",
    pl: "Are rozpoczyna pytanie o you, a tutaj mówiący sprawdza własny stan przez I. Dlatego przed I potrzebne jest am: Am I okay?",
  }),
  ["Am I okay?\0Is"]: L({
    ru: "Is нужно для he, she или it, поэтому с I оно меняет согласование. Вопрос о себе сохраняет личную пару I am и выносит am вперёд.",
    uk: "Is потрібне для he, she або it, тому з I воно змінює узгодження. Питання про себе зберігає пару I am і виносить am вперед.",
    es: "Is se usa con he, she o it, por eso con I rompe la concordancia. La pregunta sobre uno mismo conserva I am y adelanta am.",
    "pt-BR": "Is é usado com he, she ou it, por isso com I quebra a concordância. A pergunta sobre si mantém I am e leva am para a frente.",
    vi: "Is dùng với he, she hoặc it nên đi cùng I sẽ sai hòa hợp. Câu hỏi về bản thân giữ cặp I am và đưa am lên đầu.",
    id: "Is digunakan dengan he, she, atau it, sehingga bersama I tidak sesuai. Pertanyaan tentang diri menjaga pasangan I am dan memajukan am.",
    tr: "Is, he, she ya da it ile kullanılır; I ile uyumu bozar. Kendine yönelen soru I am çiftini korur ve am biçimini öne alır.",
    pl: "Is łączy się z he, she lub it, więc przy I łamie zgodę. Pytanie o siebie zachowuje parę I am i przenosi am na początek.",
  }),
  ["You’re all right.\0Are you all right?"]: L({
    ru: "Are you all right? содержит те же слова, но порядок делает их вопросом «Ты в порядке?». Здесь требуется успокаивающее утверждение, поэтому you остаётся первым внутри You’re.",
    uk: "Are you all right? містить ті самі слова, але порядок робить їх питанням «Ти в порядку?». Тут потрібне заспокійливе твердження, тому you лишається першим у You’re.",
    es: "Are you all right? contiene las mismas palabras, pero el orden crea la pregunta «¿estás bien?». Aquí se busca una afirmación tranquilizadora, por eso you queda primero en You’re.",
    "pt-BR": "Are you all right? contém as mesmas palavras, mas a ordem cria a pergunta «você está bem?». Aqui se busca uma afirmação tranquilizadora, então you fica primeiro em You’re.",
    vi: "Are you all right? có cùng từ nhưng trật tự biến thành câu hỏi “bạn ổn chứ?”. Ở đây cần lời khẳng định trấn an nên you đứng trước trong You’re.",
    id: "Are you all right? memakai kata yang sama, tetapi urutannya membuat pertanyaan. Di sini diperlukan pernyataan yang menenangkan, jadi you tetap di depan dalam You’re.",
    tr: "Are you all right? aynı sözcükleri soru sırasına koyup “İyi misin?” der. Burada rahatlatan bir bildirim gerekir; bu yüzden you, You’re içinde başta kalır.",
    pl: "Are you all right? ma te same słowa, lecz szyk tworzy pytanie „wszystko w porządku?”. Tutaj potrzebne jest uspokajające stwierdzenie, więc you zostaje pierwsze w You’re.",
  }),
  ["You’re all right.\0You’re not all right."]: L({
    ru: "You’re not all right. сохраняет человека, но not переворачивает смысл и сообщает, что с ним не всё хорошо. Успокаивающая фраза не содержит not: You’re all right.",
    uk: "You’re not all right. зберігає людину, але not перевертає зміст і повідомляє, що не все гаразд. Заспокійлива фраза не містить not: You’re all right.",
    es: "You’re not all right. conserva a la persona, pero not invierte el sentido y dice que algo va mal. La afirmación tranquilizadora no contiene not: You’re all right.",
    "pt-BR": "You’re not all right. mantém a pessoa, mas not inverte o sentido e diz que algo não está bem. A afirmação tranquilizadora não contém not: You’re all right.",
    vi: "You’re not all right. giữ nguyên người nhưng not đảo nghĩa thành “bạn không ổn”. Lời trấn an không có not và phải là You’re all right.",
    id: "You’re not all right. mempertahankan orangnya, tetapi not membalik arti menjadi keadaan yang tidak baik. Pernyataan menenangkan tanpa not ialah You’re all right.",
    tr: "You’re not all right. kişiyi korur, fakat not anlamı tersine çevirip iyi olmadığını söyler. Rahatlatan bildirimde not yoktur: You’re all right.",
    pl: "You’re not all right. zachowuje osobę, ale not odwraca sens i mówi, że nie wszystko jest dobrze. Uspokajające zdanie nie ma not: You’re all right.",
  }),
});

export function episode01Session16TaskFeedbackV1(
  locale: Locale,
  target: string,
  wrong: string,
): string | undefined {
  return FEEDBACK[`${target}\0${wrong}`]?.[locale];
}
