type Locale = "ru" | "uk" | "es" | "pt-BR" | "vi" | "id" | "tr" | "pl";
type PhraseCopy = Readonly<{ meaning: string; explanation: string }>;
const L = (value: Record<Locale, PhraseCopy>): Readonly<Record<Locale, PhraseCopy>> => value;

/** Hand-authored voice-recall copy. Every locale explains its own learner-facing cue. */
export const EPISODE_01_SESSION_15_EDITORIAL_COPY_V1: Readonly<
  Record<string, Readonly<Record<Locale, PhraseCopy>>>
> = Object.freeze({
  "Are you ready?": L({
    ru: { meaning: "Ты готов?", explanation: "Are you ready? — нейтральный вопрос собеседнику о готовности. Начало Are you сразу показывает, что ответ ждут от человека напротив." },
    uk: { meaning: "Ти готовий?", explanation: "Are you ready? — нейтральне запитання співрозмовникові про готовність. Початок Are you відразу показує, що відповіді чекають від людини навпроти." },
    es: { meaning: "¿Estás listo?", explanation: "Are you ready? pregunta de manera neutral si la otra persona está preparada. El comienzo Are you señala desde el primer momento a quién se dirige la pregunta." },
    "pt-BR": { meaning: "Você está pronto?", explanation: "Are you ready? pergunta de modo neutro se a outra pessoa está pronta. O começo Are you já deixa claro que a resposta deve vir do interlocutor." },
    vi: { meaning: "Bạn đã sẵn sàng chưa?", explanation: "Are you ready? hỏi người nghe đã sẵn sàng hay chưa. Phần mở đầu Are you báo ngay rằng câu hỏi hướng tới người đối diện, không phải người nói." },
    id: { meaning: "Apakah kamu siap?", explanation: "Are you ready? menanyakan kesiapan lawan bicara secara netral. Awal Are you langsung menunjukkan bahwa pertanyaan diarahkan kepada orang di depan kita." },
    tr: { meaning: "Hazır mısın?", explanation: "Are you ready? karşınızdaki kişinin hazır olup olmadığını nötr biçimde sorar. Are you başlangıcı, cevabın karşıdaki kişiden beklendiğini hemen gösterir." },
    pl: { meaning: "Czy jesteś gotowy?", explanation: "Are you ready? to neutralne pytanie rozmówcy o gotowość. Początek Are you od razu wskazuje, że odpowiedzi oczekuje się od osoby po drugiej stronie." },
  }),
  "You’re ready.": L({
    ru: { meaning: "Ты готов.", explanation: "You’re ready. спокойно сообщает о готовности собеседника. В You’re уже спрятано are, поэтому после сокращения остаётся только признак ready." },
    uk: { meaning: "Ти готовий.", explanation: "You’re ready. спокійно повідомляє про готовність співрозмовника. У You’re вже міститься are, тому після скорочення залишається лише ознака ready." },
    es: { meaning: "Estás listo.", explanation: "You’re ready. afirma que la otra persona está preparada. You’re ya contiene are, de modo que después de la contracción solo queda la cualidad ready." },
    "pt-BR": { meaning: "Você está pronto.", explanation: "You’re ready. afirma que a outra pessoa está pronta. You’re já contém are, por isso depois da contração vem diretamente a característica ready." },
    vi: { meaning: "Bạn đã sẵn sàng.", explanation: "You’re ready. xác nhận rằng người nghe đã sẵn sàng. You’re đã chứa are, vì vậy sau dạng rút gọn chỉ cần thêm đặc điểm ready." },
    id: { meaning: "Kamu siap.", explanation: "You’re ready. menyatakan bahwa lawan bicara sudah siap. You’re telah memuat are, sehingga setelah singkatan cukup ditambahkan sifat ready." },
    tr: { meaning: "Hazırsın.", explanation: "You’re ready. karşınızdaki kişinin hazır olduğunu bildirir. You’re biçiminin içinde are bulunduğu için ardından yalnız ready özelliği gelir." },
    pl: { meaning: "Jesteś gotowy.", explanation: "You’re ready. stwierdza, że rozmówca jest gotowy. You’re zawiera już are, dlatego po skrócie pojawia się bezpośrednio cecha ready." },
  }),
  "You’re in class.": L({
    ru: { meaning: "Ты на занятии.", explanation: "You’re in class. говорит, что собеседник сейчас участвует в занятии. Сокращение You’re называет человека, а цельный блок in class — его ситуацию." },
    uk: { meaning: "Ти на занятті.", explanation: "You’re in class. означає, що співрозмовник зараз бере участь у занятті. Скорочення You’re називає людину, а цілий блок in class — її ситуацію." },
    es: { meaning: "Estás en clase.", explanation: "You’re in class. indica que la otra persona está participando en una clase. You’re identifica al interlocutor y el bloque in class completa su situación." },
    "pt-BR": { meaning: "Você está na aula.", explanation: "You’re in class. mostra que a outra pessoa está participando de uma aula. You’re identifica o interlocutor e o bloco in class completa a situação." },
    vi: { meaning: "Bạn đang ở lớp.", explanation: "You’re in class. cho biết người nghe đang tham gia giờ học. You’re xác định người được nói tới, còn cụm in class cho biết tình huống hiện tại." },
    id: { meaning: "Kamu sedang mengikuti kelas.", explanation: "You’re in class. berarti lawan bicara sedang mengikuti pelajaran. You’re menunjukkan orangnya, sedangkan kelompok in class melengkapi keadaannya." },
    tr: { meaning: "Derstesin.", explanation: "You’re in class. karşınızdaki kişinin o anda derse katıldığını söyler. You’re kişiyi, in class bütünü ise içinde bulunduğu durumu belirtir." },
    pl: { meaning: "Jesteś na zajęciach.", explanation: "You’re in class. mówi, że rozmówca uczestniczy teraz w zajęciach. You’re wskazuje osobę, a gotowe połączenie in class uzupełnia jej sytuację." },
  }),
  "Am I ready?": L({
    ru: { meaning: "Я готов?", explanation: "Am I ready? — вопрос говорящего о собственной готовности. Am выходит перед I, поэтому собеседник слышит вопрос, а не утверждение I am ready." },
    uk: { meaning: "Я готовий?", explanation: "Am I ready? — запитання мовця про власну готовність. Am виходить перед I, тому співрозмовник чує запитання, а не твердження I am ready." },
    es: { meaning: "¿Estoy listo?", explanation: "Am I ready? permite que quien habla pregunte por su propia preparación. Am aparece delante de I y distingue la pregunta de la afirmación I am ready." },
    "pt-BR": { meaning: "Estou pronto?", explanation: "Am I ready? permite que quem fala pergunte sobre a própria prontidão. Am vem antes de I e separa a pergunta da afirmação I am ready." },
    vi: { meaning: "Tôi đã sẵn sàng chưa?", explanation: "Am I ready? là câu người nói hỏi về chính mình. Am đứng trước I nên người nghe nhận ra đây là câu hỏi, khác với câu kể I am ready." },
    id: { meaning: "Apakah saya siap?", explanation: "Am I ready? dipakai penutur untuk menanyakan kesiapan dirinya sendiri. Am berada sebelum I sehingga bentuk ini berbeda jelas dari pernyataan I am ready." },
    tr: { meaning: "Hazır mıyım?", explanation: "Am I ready? konuşanın kendi hazırlığını sormasını sağlar. Am, I önüne geçtiği için bu biçim I am ready bildiriminden açıkça ayrılır." },
    pl: { meaning: "Czy jestem gotowy?", explanation: "Am I ready? pozwala mówiącemu zapytać o własną gotowość. Am stoi przed I, dzięki czemu pytanie różni się od stwierdzenia I am ready." },
  }),
  "I am ready.": L({
    ru: { meaning: "Я готов.", explanation: "I am ready. — полный спокойный ответ о собственной готовности. В утверждении I стоит первым, а am связывает говорящего с состоянием ready." },
    uk: { meaning: "Я готовий.", explanation: "I am ready. — повна спокійна відповідь про власну готовність. У твердженні I стоїть першим, а am пов’язує мовця зі станом ready." },
    es: { meaning: "Estoy listo.", explanation: "I am ready. es una afirmación completa sobre la preparación de quien habla. I ocupa el primer lugar y am lo une con el estado ready." },
    "pt-BR": { meaning: "Estou pronto.", explanation: "I am ready. é uma afirmação completa sobre a prontidão de quem fala. I aparece primeiro e am liga o falante ao estado ready." },
    vi: { meaning: "Tôi đã sẵn sàng.", explanation: "I am ready. là lời xác nhận đầy đủ về sự sẵn sàng của người nói. Trong câu kể, I đứng trước và am nối người nói với trạng thái ready." },
    id: { meaning: "Saya siap.", explanation: "I am ready. merupakan pernyataan lengkap tentang kesiapan penutur. Dalam kalimat berita, I datang lebih dahulu dan am menghubungkannya dengan ready." },
    tr: { meaning: "Hazırım.", explanation: "I am ready. konuşanın hazır olduğunu tam bir bildirimle anlatır. Bildirim sırasındaki I önce gelir, am ise konuşanı ready durumuna bağlar." },
    pl: { meaning: "Jestem gotowy.", explanation: "I am ready. jest pełnym stwierdzeniem o gotowości mówiącego. W zdaniu oznajmującym I stoi pierwsze, a am łączy osobę ze stanem ready." },
  }),
  "Are you okay?": L({
    ru: { meaning: "Ты в порядке?", explanation: "Are you okay? спрашивает собеседника о самочувствии или ситуации. Are you сохраняет вопросительное начало, а okay уточняет, всё ли с человеком нормально." },
    uk: { meaning: "Ти в порядку?", explanation: "Are you okay? запитує співрозмовника про самопочуття або ситуацію. Are you зберігає питальний початок, а okay уточнює, чи все з людиною гаразд." },
    es: { meaning: "¿Estás bien?", explanation: "Are you okay? pregunta por el estado o la situación de la otra persona. Are you mantiene el inicio interrogativo y okay comprueba si todo va bien." },
    "pt-BR": { meaning: "Você está bem?", explanation: "Are you okay? pergunta pelo estado ou pela situação da outra pessoa. Are you mantém o começo interrogativo e okay verifica se está tudo bem." },
    vi: { meaning: "Bạn ổn chứ?", explanation: "Are you okay? hỏi người nghe về sức khỏe hoặc tình hình hiện tại. Are you giữ phần mở đầu của câu hỏi, còn okay kiểm tra xem mọi việc có ổn không." },
    id: { meaning: "Apakah kamu baik-baik saja?", explanation: "Are you okay? menanyakan keadaan atau situasi lawan bicara. Are you mempertahankan awal pertanyaan, sedangkan okay memeriksa apakah semuanya baik." },
    tr: { meaning: "İyi misin?", explanation: "Are you okay? karşınızdaki kişinin durumunu ya da nasıl hissettiğini sorar. Are you soru başlangıcını korur, okay ise her şeyin yolunda olup olmadığını yoklar." },
    pl: { meaning: "Wszystko z tobą w porządku?", explanation: "Are you okay? pyta o samopoczucie lub sytuację rozmówcy. Are you zachowuje początek pytania, a okay sprawdza, czy wszystko jest w porządku." },
  }),
  "I am okay.": L({
    ru: { meaning: "Я в порядке.", explanation: "I am okay. сообщает, что с говорящим всё нормально. Прямой порядок I am превращает проверку самочувствия в ясный спокойный ответ." },
    uk: { meaning: "Я в порядку.", explanation: "I am okay. повідомляє, що з мовцем усе гаразд. Прямий порядок I am перетворює перевірку самопочуття на ясну спокійну відповідь." },
    es: { meaning: "Estoy bien.", explanation: "I am okay. comunica que quien habla se encuentra bien. El orden directo I am convierte la comprobación del estado en una respuesta clara y tranquila." },
    "pt-BR": { meaning: "Estou bem.", explanation: "I am okay. informa que quem fala está bem. A ordem direta I am transforma a pergunta sobre o estado numa resposta clara e tranquila." },
    vi: { meaning: "Tôi ổn.", explanation: "I am okay. cho biết người nói vẫn ổn. Trật tự thẳng I am biến việc hỏi thăm tình trạng thành một câu trả lời rõ ràng và bình tĩnh." },
    id: { meaning: "Saya baik-baik saja.", explanation: "I am okay. menyatakan bahwa keadaan penutur baik. Urutan langsung I am mengubah pemeriksaan keadaan menjadi jawaban yang jelas dan tenang." },
    tr: { meaning: "İyiyim.", explanation: "I am okay. konuşanın durumunun iyi olduğunu bildirir. Düz I am sırası, durum sorusunu açık ve sakin bir cevaba dönüştürür." },
    pl: { meaning: "Wszystko ze mną w porządku.", explanation: "I am okay. informuje, że mówiący czuje się dobrze. Prosty szyk I am zmienia pytanie o stan w jasną i spokojną odpowiedź." },
  }),
  "Am I okay?": L({
    ru: { meaning: "Со мной всё в порядке?", explanation: "Am I okay? просит собеседника оценить состояние говорящего. Начальное Am I сохраняет вопрос о себе, а okay направляет его на самочувствие или ситуацию." },
    uk: { meaning: "Зі мною все гаразд?", explanation: "Am I okay? просить співрозмовника оцінити стан мовця. Початкове Am I зберігає запитання про себе, а okay спрямовує його на самопочуття або ситуацію." },
    es: { meaning: "¿Estoy bien?", explanation: "Am I okay? pide a la otra persona que valore el estado de quien habla. El inicio Am I mantiene la pregunta sobre uno mismo y okay la dirige al bienestar." },
    "pt-BR": { meaning: "Estou bem?", explanation: "Am I okay? pede que a outra pessoa avalie o estado de quem fala. O começo Am I mantém a pergunta sobre si mesmo e okay a dirige ao bem-estar." },
    vi: { meaning: "Tôi có ổn không?", explanation: "Am I okay? nhờ người nghe đánh giá tình trạng của người nói. Phần mở đầu Am I giữ câu hỏi hướng về bản thân, còn okay tập trung vào việc có ổn hay không." },
    id: { meaning: "Apakah saya baik-baik saja?", explanation: "Am I okay? meminta lawan bicara menilai keadaan penutur. Awal Am I mempertahankan pertanyaan tentang diri sendiri, sedangkan okay menyoroti kondisinya." },
    tr: { meaning: "İyi miyim?", explanation: "Am I okay? karşıdaki kişiden konuşanın durumunu değerlendirmesini ister. Am I başlangıcı soruyu konuşana yöneltir, okay ise iyi olma durumunu yoklar." },
    pl: { meaning: "Czy wszystko ze mną w porządku?", explanation: "Am I okay? prosi rozmówcę o ocenę stanu mówiącego. Początek Am I kieruje pytanie na siebie, a okay skupia je na samopoczuciu lub sytuacji." },
  }),
  "You’re okay.": L({
    ru: { meaning: "С тобой всё в порядке.", explanation: "You’re okay. успокаивает собеседника или подтверждает его состояние. You’re уже содержит you are, поэтому okay сразу завершает короткое утверждение." },
    uk: { meaning: "З тобою все гаразд.", explanation: "You’re okay. заспокоює співрозмовника або підтверджує його стан. You’re уже містить you are, тому okay одразу завершує коротке твердження." },
    es: { meaning: "Estás bien.", explanation: "You’re okay. tranquiliza a la otra persona o confirma su estado. You’re ya contiene you are, por lo que okay completa de inmediato la afirmación breve." },
    "pt-BR": { meaning: "Você está bem.", explanation: "You’re okay. tranquiliza a outra pessoa ou confirma o estado dela. You’re já contém you are, então okay conclui diretamente a afirmação curta." },
    vi: { meaning: "Bạn vẫn ổn.", explanation: "You’re okay. dùng để trấn an người nghe hoặc xác nhận tình trạng của họ. You’re đã chứa you are nên okay có thể kết thúc ngay câu khẳng định ngắn." },
    id: { meaning: "Kamu baik-baik saja.", explanation: "You’re okay. menenangkan lawan bicara atau menegaskan keadaannya. You’re sudah memuat you are, sehingga okay langsung menyelesaikan pernyataan singkat." },
    tr: { meaning: "İyisin.", explanation: "You’re okay. karşınızdaki kişiyi rahatlatır ya da durumunu doğrular. You’re içinde you are bulunduğundan okay kısa bildirimi doğrudan tamamlar." },
    pl: { meaning: "Wszystko z tobą w porządku.", explanation: "You’re okay. uspokaja rozmówcę albo potwierdza jego stan. You’re zawiera już you are, więc okay od razu domyka krótkie stwierdzenie." },
  }),
  "Are you at home?": L({
    ru: { meaning: "Ты дома?", explanation: "Are you at home? уточняет текущее место собеседника. Вопрос сохраняет начало Are you, а знакомый блок at home проверяет именно нахождение дома." },
    uk: { meaning: "Ти вдома?", explanation: "Are you at home? уточнює поточне місце співрозмовника. Запитання зберігає початок Are you, а знайомий блок at home перевіряє саме перебування вдома." },
    es: { meaning: "¿Estás en casa?", explanation: "Are you at home? comprueba el lugar actual de la otra persona. La pregunta conserva Are you y el bloque conocido at home verifica específicamente que esté en casa." },
    "pt-BR": { meaning: "Você está em casa?", explanation: "Are you at home? verifica o local atual da outra pessoa. A pergunta mantém Are you e o bloco conhecido at home confirma especificamente a presença em casa." },
    vi: { meaning: "Bạn đang ở nhà à?", explanation: "Are you at home? hỏi vị trí hiện tại của người nghe. Câu hỏi giữ phần đầu Are you, còn cụm quen thuộc at home kiểm tra đúng việc đang ở nhà." },
    id: { meaning: "Apakah kamu di rumah?", explanation: "Are you at home? memeriksa lokasi lawan bicara saat ini. Pertanyaan mempertahankan Are you, sedangkan kelompok at home secara khusus menanyakan rumah." },
    tr: { meaning: "Evde misin?", explanation: "Are you at home? karşınızdaki kişinin şu an nerede olduğunu netleştirir. Soru Are you ile başlar, at home bütünü ise özellikle evde bulunmayı sorar." },
    pl: { meaning: "Czy jesteś w domu?", explanation: "Are you at home? sprawdza aktualne miejsce rozmówcy. Pytanie zachowuje początek Are you, a znany blok at home dotyczy dokładnie przebywania w domu." },
  }),
  "I am at home.": L({
    ru: { meaning: "Я дома.", explanation: "I am at home. сообщает текущее место говорящего. I am образует прямой ответ, а at home остаётся цельным английским способом сказать «дома»." },
    uk: { meaning: "Я вдома.", explanation: "I am at home. повідомляє поточне місце мовця. I am утворює пряму відповідь, а at home залишається цілісним англійським способом сказати «вдома»." },
    es: { meaning: "Estoy en casa.", explanation: "I am at home. informa del lugar actual de quien habla. I am forma la respuesta directa y at home permanece como el bloque inglés completo para estar en casa." },
    "pt-BR": { meaning: "Estou em casa.", explanation: "I am at home. informa o local atual de quem fala. I am forma a resposta direta e at home continua como o bloco inglês completo para estar em casa." },
    vi: { meaning: "Tôi đang ở nhà.", explanation: "I am at home. cho biết vị trí hiện tại của người nói. I am tạo câu trả lời trực tiếp, còn at home giữ nguyên như một cụm hoàn chỉnh mang nghĩa ở nhà." },
    id: { meaning: "Saya di rumah.", explanation: "I am at home. memberitahukan lokasi penutur sekarang. I am membentuk jawaban langsung dan at home tetap menjadi kelompok utuh untuk keadaan berada di rumah." },
    tr: { meaning: "Evdeyim.", explanation: "I am at home. konuşanın şu an evde bulunduğunu bildirir. I am düz cevabı kurar, at home ise evde olmayı anlatan bütün İngilizce kalıp olarak kalır." },
    pl: { meaning: "Jestem w domu.", explanation: "I am at home. podaje aktualne miejsce mówiącego. I am tworzy prostą odpowiedź, a at home pozostaje całym angielskim połączeniem oznaczającym pobyt w domu." },
  }),
  "Am I at home?": L({
    ru: { meaning: "Я дома?", explanation: "Am I at home? спрашивает о месте самого говорящего. Am I задаёт вопросительную рамку о себе, а at home сохраняет точное значение «дома»." },
    uk: { meaning: "Я вдома?", explanation: "Am I at home? запитує про місце самого мовця. Am I задає питальну рамку про себе, а at home зберігає точне значення «вдома»." },
    es: { meaning: "¿Estoy en casa?", explanation: "Am I at home? pregunta por el lugar de quien habla. Am I crea la estructura interrogativa sobre uno mismo y at home conserva el sentido exacto de estar en casa." },
    "pt-BR": { meaning: "Estou em casa?", explanation: "Am I at home? pergunta pelo local de quem fala. Am I cria a estrutura interrogativa sobre si mesmo e at home mantém o sentido exato de estar em casa." },
    vi: { meaning: "Tôi đang ở nhà phải không?", explanation: "Am I at home? hỏi về vị trí của chính người nói. Am I tạo khung câu hỏi hướng về bản thân, còn at home giữ đúng nghĩa đang ở nhà." },
    id: { meaning: "Apakah saya di rumah?", explanation: "Am I at home? menanyakan lokasi penutur sendiri. Am I membentuk kerangka pertanyaan tentang diri, sedangkan at home mempertahankan arti tepat berada di rumah." },
    tr: { meaning: "Evde miyim?", explanation: "Am I at home? konuşanın kendi yerini sorar. Am I kendine yönelen soru çerçevesini kurar, at home bütünü ise tam olarak evde bulunmayı anlatır." },
    pl: { meaning: "Czy jestem w domu?", explanation: "Am I at home? pyta o miejsce samego mówiącego. Am I tworzy pytanie skierowane na siebie, a at home zachowuje dokładne znaczenie przebywania w domu." },
  }),
  "You’re at home.": L({
    ru: { meaning: "Ты дома.", explanation: "You’re at home. подтверждает, что собеседник находится дома. Сокращение You’re сохраняет you are целиком, после него без изменения идёт блок at home." },
    uk: { meaning: "Ти вдома.", explanation: "You’re at home. підтверджує, що співрозмовник перебуває вдома. Скорочення You’re зберігає you are цілком, після нього без зміни йде блок at home." },
    es: { meaning: "Estás en casa.", explanation: "You’re at home. confirma que la otra persona se encuentra en casa. La contracción You’re conserva you are completo y después mantiene intacto el bloque at home." },
    "pt-BR": { meaning: "Você está em casa.", explanation: "You’re at home. confirma que a outra pessoa está em casa. A contração You’re preserva you are inteiro e depois mantém o bloco at home sem mudança." },
    vi: { meaning: "Bạn đang ở nhà.", explanation: "You’re at home. xác nhận người nghe hiện đang ở nhà. Dạng rút gọn You’re giữ trọn you are, rồi cụm at home đi sau mà không thay đổi." },
    id: { meaning: "Kamu di rumah.", explanation: "You’re at home. menegaskan bahwa lawan bicara berada di rumah. Singkatan You’re menyimpan you are secara utuh, lalu kelompok at home tetap tidak berubah." },
    tr: { meaning: "Evdesin.", explanation: "You’re at home. karşınızdaki kişinin evde olduğunu doğrular. You’re kısaltması you are bütününü korur; ardından at home kalıbı değişmeden gelir." },
    pl: { meaning: "Jesteś w domu.", explanation: "You’re at home. potwierdza, że rozmówca znajduje się w domu. Skrót You’re zachowuje całe you are, a po nim bez zmian występuje blok at home." },
  }),
  "Are you in class?": L({
    ru: { meaning: "Ты на занятии?", explanation: "Are you in class? спрашивает, участвует ли собеседник сейчас в занятии. Are you направляет вопрос человеку, а in class называет именно ситуацию учёбы." },
    uk: { meaning: "Ти на занятті?", explanation: "Are you in class? запитує, чи бере співрозмовник зараз участь у занятті. Are you спрямовує питання людині, а in class називає саме ситуацію навчання." },
    es: { meaning: "¿Estás en clase?", explanation: "Are you in class? pregunta si la otra persona está participando en una clase. Are you dirige la pregunta al interlocutor e in class nombra la situación de estudio." },
    "pt-BR": { meaning: "Você está na aula?", explanation: "Are you in class? pergunta se a outra pessoa está participando de uma aula. Are you dirige a pergunta ao interlocutor e in class nomeia a situação de estudo." },
    vi: { meaning: "Bạn đang ở lớp à?", explanation: "Are you in class? hỏi người nghe có đang tham gia giờ học hay không. Are you hướng câu hỏi tới người đối diện, còn in class nêu đúng tình huống học tập." },
    id: { meaning: "Apakah kamu sedang mengikuti kelas?", explanation: "Are you in class? menanyakan apakah lawan bicara sedang mengikuti pelajaran. Are you mengarahkan pertanyaan kepada orang itu dan in class menyebut situasi belajar." },
    tr: { meaning: "Derste misin?", explanation: "Are you in class? karşınızdaki kişinin o anda derse katılıp katılmadığını sorar. Are you soruyu kişiye yöneltir, in class ise öğrenme durumunu adlandırır." },
    pl: { meaning: "Czy jesteś na zajęciach?", explanation: "Are you in class? pyta, czy rozmówca uczestniczy teraz w zajęciach. Are you kieruje pytanie do tej osoby, a in class nazywa sytuację nauki." },
  }),
  "I am in class.": L({
    ru: { meaning: "Я на занятии.", explanation: "I am in class. сообщает, что говорящий сейчас участвует в занятии. Прямое I am называет человека, а in class показывает его текущую учебную ситуацию." },
    uk: { meaning: "Я на занятті.", explanation: "I am in class. повідомляє, що мовець зараз бере участь у занятті. Пряме I am називає людину, а in class показує її поточну навчальну ситуацію." },
    es: { meaning: "Estoy en clase.", explanation: "I am in class. informa que quien habla está participando en una clase. El orden directo I am identifica a la persona e in class completa la situación de estudio." },
    "pt-BR": { meaning: "Estou na aula.", explanation: "I am in class. informa que quem fala está participando de uma aula. A ordem direta I am identifica a pessoa e in class completa a situação de estudo." },
    vi: { meaning: "Tôi đang ở lớp.", explanation: "I am in class. cho biết người nói đang tham gia giờ học. Trật tự thẳng I am xác định người được nói tới, còn in class hoàn tất tình huống học tập." },
    id: { meaning: "Saya sedang mengikuti kelas.", explanation: "I am in class. memberitahukan bahwa penutur sedang mengikuti pelajaran. Urutan langsung I am menunjukkan orangnya dan in class melengkapi situasi belajar." },
    tr: { meaning: "Dersteyim.", explanation: "I am in class. konuşanın o anda derse katıldığını bildirir. Düz I am sırası kişiyi belirtir, in class bütünü ise mevcut öğrenme durumunu tamamlar." },
    pl: { meaning: "Jestem na zajęciach.", explanation: "I am in class. informuje, że mówiący uczestniczy teraz w zajęciach. Prosty szyk I am wskazuje osobę, a in class uzupełnia jej bieżącą sytuację nauki." },
  }),
});
