import type { LearningV2IntroTextRunV1 } from '../intro_semantic_runs_v1';
import type {
  LocalizedSource,
  SessionSourceIntroPage,
} from './session_shard_from_source_v1';

// зачем этот файл (владелец, 2026-08-25, карта сессий es_episode_01_session_map_v1.ts,
// сессия 28 "Вдвоём: somos dos" / number_with_ser, builtOn: [9, 27],
// recalls: [9, 27]): три страницы concept/formula/trap вводят числительное
// сразу после связки ser как способ назвать точный размер группы. Somos
// (сессия 25) и son (сессия 27) уже закреплены за первым и третьим лицом
// множественного числа; здесь к ним добавляется число — dos, tres — которое
// встаёт сразу после связки и не меняется никогда, как así или de acuerdo
// раньше. Eres (сессия 9) остаётся в игре только как одиночный собеседник,
// с которым число не сочетается вовсе — это и есть главная ловушка сессии.
const L = (value: LocalizedSource): LocalizedSource => value;
const R = (
  ...runs: readonly LearningV2IntroTextRunV1[]
): readonly LearningV2IntroTextRunV1[] => runs;

export const ES_EPISODE_01_SESSION_28_TITLE = L({
  ru: 'Вдвоём: somos dos',
  uk: 'Удвох: somos dos',
  es: 'Together: somos dos',
  'pt-BR': 'A dois: somos dos',
  vi: 'Cùng nhau: somos dos',
  id: 'Berdua: somos dos',
  tr: 'İkimiz: somos dos',
  pl: 'We dwoje: somos dos',
});

export const ES_EPISODE_01_SESSION_28_SUMMARY = L({
  ru: 'Число встаёт сразу после уже знакомой связки и просто называет, сколько человек в группе — ни связка, ни число от этого не меняются.',
  uk: 'Число стає одразу після вже знайомої зв’язки і просто називає, скільки людей у групі — ні зв’язка, ні число від цього не змінюються.',
  es: 'A number goes right after the already familiar linking word and simply states how many people are in the group — neither the linking word nor the number changes because of this.',
  'pt-BR': 'Um número vem logo após a ligação já conhecida e simplesmente diz quantas pessoas há no grupo — nem a ligação nem o número mudam por causa disso.',
  vi: 'Một con số đứng ngay sau từ nối đã quen thuộc và chỉ đơn giản nói ra có bao nhiêu người trong nhóm — cả từ nối lẫn con số đều không đổi vì điều này.',
  id: 'Sebuah angka muncul tepat setelah kata penghubung yang sudah dikenal dan hanya menyatakan berapa banyak orang dalam kelompok — baik kata penghubung maupun angkanya tidak berubah karena ini.',
  tr: 'Bir sayı, zaten tanıdık olan bağlaçtan hemen sonra gelir ve grupta kaç kişi olduğunu basitçe söyler — ne bağlaç ne de sayı bundan dolayı değişir.',
  pl: 'Liczba pojawia się zaraz po już znanym łączniku i po prostu podaje, ile osób jest w grupie — ani łącznik, ani liczba się przez to nie zmieniają.',
});

export const ES_EPISODE_01_SESSION_28_GOAL = L({
  ru: 'Узнать на слух, понять и точно построить связку ser с числительным, называя размер своей группы через somos и чужой через son.',
  uk: 'Упізнати на слух, зрозуміти й точно побудувати зв’язку ser із числівником, називаючи розмір своєї групи через somos і чужої через son.',
  es: 'Recognize, understand, and correctly build the linking word ser with a number, stating the size of your own group with somos and another group with son.',
  'pt-BR': 'Reconhecer de ouvido, entender e construir corretamente a ligação ser com um numeral, dizendo o tamanho do próprio grupo com somos e de outro grupo com son.',
  vi: 'Nghe ra, hiểu và xây dựng đúng từ nối ser cùng số đếm, nói ra quy mô nhóm của mình bằng somos và nhóm khác bằng son.',
  id: 'Mengenali dari suara, memahami, dan membangun dengan tepat kata penghubung ser dengan angka, menyatakan ukuran kelompok sendiri dengan somos dan kelompok lain dengan son.',
  tr: 'Ser bağlacını bir sayıyla duyup tanımak, anlamak ve doğru kurmak; kendi grubunun büyüklüğünü somos ile, başka bir grubunkini son ile söylemek.',
  pl: 'Rozpoznać ze słuchu, zrozumieć i poprawnie zbudować łącznik ser z liczebnikiem, podając rozmiar własnej grupy przez somos i innej przez son.',
});

const CONCEPT_BODY = L({
  ru: 'Somos и son уже знакомы: somos — про группу, в которую входит сам говорящий, son — про группу со стороны, без него. Число встаёт сразу после любой из этих связок и просто называет точный размер группы: Somos dos — нас двое, Son tres — их трое. Лицо и число связки при этом не меняются вовсе — числительное лишь добавляет уточнение, сколько именно человек имеется в виду. С eres так не работает: собеседник один, и один человек не может быть «два» или «три» — числа встают только после somos и son, никогда после eres. Порядок слов простой и жёсткий: сначала связка, сразу за ней число, без дополнительных слов между ними.',
  uk: 'Somos і son уже знайомі: somos — про групу, до якої входить сам мовець, son — про групу збоку, без нього. Число стає одразу після будь-якої з цих зв’язок і просто називає точний розмір групи: Somos dos — нас двоє, Son tres — їх троє. Особа і число зв’язки при цьому не змінюються зовсім — числівник лише додає уточнення, скільки саме людей мається на увазі. З eres так не працює: співрозмовник один, і одна людина не може бути «два» чи «три» — числа стають лише після somos і son, ніколи після eres. Порядок слів простий і жорсткий: спершу зв’язка, одразу за нею число, без додаткових слів між ними.',
  es: 'Somos and son are already familiar: somos is about a group that includes the speaker, son is about a group from the outside, without them. A number goes right after either of these linking words and simply states the exact size of the group: Somos dos — there are two of us, Son tres — there are three of them. The person and number of the linking word do not change at all — the numeral only adds how many people exactly are meant. This does not work with eres: the listener is one person, and one person cannot be "two" or "three" — numbers go only after somos and son, never after eres.',
  'pt-BR': 'Somos e son já são conhecidas: somos é sobre um grupo que inclui quem fala, son é sobre um grupo de fora, sem ele. Um número vem logo após qualquer uma dessas ligações e simplesmente indica o tamanho exato do grupo: Somos dos — somos dois, Son tres — são três. A pessoa e o número da ligação não mudam em nada — o numeral só acrescenta quantas pessoas exatamente estão sendo mencionadas. Isso não funciona com eres: o interlocutor é uma só pessoa, e uma pessoa não pode ser "dois" ou "três" — números vêm só depois de somos e son, nunca depois de eres. A ordem das palavras é simples e rígida: primeiro a ligação, logo depois o número, sem palavras extras entre eles.',
  vi: 'Somos và son đã quen thuộc: somos nói về nhóm gồm cả người nói, son nói về nhóm từ bên ngoài, không có người nói. Một con số đứng ngay sau bất kỳ từ nối nào trong hai từ này và chỉ đơn giản nói ra quy mô chính xác của nhóm: Somos dos — chúng tôi có hai người, Son tres — họ có ba người. Ngôi và số của từ nối hoàn toàn không đổi — số đếm chỉ thêm vào chính xác bao nhiêu người được nhắc tới. Điều này không dùng được với eres: người nghe chỉ có một, và một người không thể là "hai" hay "ba" — số chỉ đứng sau somos và son, không bao giờ sau eres. Trật tự từ đơn giản và chặt chẽ: đầu tiên là từ nối, ngay sau đó là con số, không có từ thừa nào ở giữa.',
  id: 'Somos dan son sudah dikenal: somos tentang kelompok yang mencakup penutur, son tentang kelompok dari luar, tanpa penutur. Angka muncul tepat setelah salah satu kata penghubung ini dan hanya menyatakan ukuran pasti kelompok: Somos dos — kami berdua, Son tres — mereka bertiga. Orang dan jumlah kata penghubung sama sekali tidak berubah — angka hanya menambahkan berapa persisnya orang yang dimaksud. Ini tidak berlaku untuk eres: pendengar hanya satu orang, dan satu orang tidak bisa menjadi "dua" atau "tiga" — angka hanya muncul setelah somos dan son, tidak pernah setelah eres. Urutan katanya sederhana dan ketat: kata penghubung dulu, angka tepat setelahnya, tanpa kata tambahan di antaranya.',
  tr: 'Somos ve son zaten tanıdıktır: somos, konuşanı da içeren bir grup hakkındadır, son ise dışarıdan, konuşan olmadan bir grup hakkındadır. Bir sayı bu bağlaçlardan birinin hemen ardından gelir ve grubun tam büyüklüğünü basitçe belirtir: Somos dos — ikimiziz, Son tres — onlar üç kişi. Bağlacın kişisi ve sayısı hiç değişmez — sayı yalnızca tam olarak kaç kişinin kastedildiğini ekler. Bu, eres ile çalışmaz: dinleyici tek bir kişidir, ve tek bir kişi "iki" ya da "üç" olamaz — sayılar yalnızca somos ve son’dan sonra gelir, asla eres’ten sonra değil. Kelime sırası basit ve katıdır: önce bağlaç, hemen ardından sayı, aralarında fazladan kelime olmadan.',
  pl: 'Somos i son są już znane: somos dotyczy grupy, do której należy mówiący, son dotyczy grupy z zewnątrz, bez niego. Liczba pojawia się zaraz po jednym z tych łączników i po prostu podaje dokładny rozmiar grupy: Somos dos — jest nas dwoje, Son tres — jest ich troje. Osoba i liczba łącznika wcale się nie zmieniają — liczebnik tylko dodaje, ile dokładnie osób ma się na myśli. Z eres to nie działa: słuchacz to jedna osoba, a jedna osoba nie może być „dwa” ani „trzy” — liczby pojawiają się tylko po somos i son, nigdy po eres. Szyk wyrazów jest prosty i sztywny: najpierw łącznik, zaraz po nim liczba, bez dodatkowych słów między nimi.',
});

const FORMULA_BODY = L({
  ru: 'Формула проста: связка (somos для своей группы, son для чужой) плюс число сразу за ней. Somos dos говорит о размере своей группы в два человека, Son tres — о чужой группе в три человека, и оба раза число не меняется ни от чего — ни от рода, ни от того, о ком идёт речь. Отрицание работает точно так же, как и раньше: No встаёт перед связкой, No somos dos отрицает число своей группы, No son tres — чужой. Число можно даже уточнять подряд: Somos dos, no tres — сначала называется верное число, затем через no отрицается соседнее, ошибочное.',
  uk: 'Формула проста: зв’язка (somos для своєї групи, son для чужої) плюс число одразу за нею. Somos dos говорить про розмір своєї групи у дві людини, Son tres — про чужу групу у три людини, і обидва рази число не змінюється ні від чого — ні від роду, ні від того, про кого йдеться. Заперечення працює точнісінько як і раніше: No стає перед зв’язкою, No somos dos заперечує число своєї групи, No son tres — чужої. Число можна навіть уточнювати підряд: Somos dos, no tres — спершу називається правильне число, потім через no заперечується сусіднє, помилкове.',
  es: 'The formula is simple: linking word (somos for your own group, son for another) plus a number right after it. Somos dos states the size of your own group as two people, Son tres states another group as three people, and both times the number does not change for anything — not for gender, not for who is being talked about. Negation works exactly as before: No comes before the linking word, No somos dos negates the number of your own group, No son tres negates another\'s. The number can even be clarified in a row: Somos dos, no tres — first the right number is stated, then no negates the neighboring, wrong one.',
  'pt-BR': 'A fórmula é simples: ligação (somos para o próprio grupo, son para outro) mais um número logo depois. Somos dos indica o tamanho do próprio grupo em duas pessoas, Son tres indica outro grupo em três pessoas, e nas duas vezes o número não muda por nada — nem por gênero, nem por quem está sendo mencionado. A negação funciona exatamente como antes: No vem antes da ligação, No somos dos nega o número do próprio grupo, No son tres nega o de outro. O número pode até ser esclarecido em sequência: Somos dos, no tres — primeiro se indica o número certo, depois no nega o vizinho, o errado.',
  vi: 'Công thức đơn giản: từ nối (somos cho nhóm của mình, son cho nhóm khác) cộng con số ngay sau đó. Somos dos nói ra quy mô nhóm của mình là hai người, Son tres nói về nhóm khác là ba người, và cả hai lần con số không đổi vì bất cứ điều gì — không vì giống, không vì đang nói về ai. Phủ định hoạt động y hệt như trước: No đứng trước từ nối, No somos dos phủ định con số của nhóm mình, No son tres phủ định con số của nhóm khác. Con số thậm chí có thể được làm rõ liên tiếp: Somos dos, no tres — đầu tiên nói ra con số đúng, sau đó no phủ định con số lân cận, sai.',
  id: 'Rumusnya sederhana: kata penghubung (somos untuk kelompok sendiri, son untuk kelompok lain) ditambah angka tepat setelahnya. Somos dos menyatakan ukuran kelompok sendiri sebagai dua orang, Son tres menyatakan kelompok lain sebagai tiga orang, dan kedua kalinya angkanya sama sekali tidak berubah — bukan karena gender, bukan karena siapa yang dibicarakan. Negasi bekerja persis seperti sebelumnya: No berada sebelum kata penghubung, No somos dos menegasikan angka kelompok sendiri, No son tres menegasikan kelompok lain. Angkanya bahkan bisa diklarifikasi berturut-turut: Somos dos, no tres — pertama angka yang benar disebutkan, lalu no menegasikan angka tetangganya yang salah.',
  tr: 'Formül basittir: bağlaç (kendi grubu için somos, başkası için son) artı hemen ardından bir sayı. Somos dos kendi grubunun büyüklüğünü iki kişi olarak belirtir, Son tres başka bir grubu üç kişi olarak belirtir, ve her iki seferde de sayı hiçbir şeyden dolayı değişmez — ne cinsiyetten, ne de kimden bahsedildiğinden. Olumsuzlama tam olarak öncekiyle aynı şekilde çalışır: No bağlaçtan önce gelir, No somos dos kendi grubunun sayısını olumsuzlar, No son tres başkasınınkini olumsuzlar. Sayı arka arkaya bile netleştirilebilir: Somos dos, no tres — önce doğru sayı söylenir, sonra no komşu, yanlış olanı olumsuzlar.',
  pl: 'Formuła jest prosta: łącznik (somos dla własnej grupy, son dla innej) plus liczba zaraz po nim. Somos dos podaje rozmiar własnej grupy jako dwie osoby, Son tres podaje inną grupę jako trzy osoby, i za każdym razem liczba się nie zmienia z żadnego powodu — ani przez rodzaj, ani przez to, o kim mowa. Przeczenie działa dokładnie jak wcześniej: No stoi przed łącznikiem, No somos dos zaprzecza liczbie własnej grupy, No son tres zaprzecza liczbie innej. Liczbę można nawet doprecyzować pod rząd: Somos dos, no tres — najpierw podaje się właściwą liczbę, potem no zaprzecza sąsiedniej, błędnej.',
});

const TRAP_BODY = L({
  ru: 'Самая частая ошибка — сказать Eres dos, обращаясь к одному собеседнику: один человек физически не может быть «два», числа встают только после somos или son, никогда после eres. Вторая ловушка — перепутать somos и son при счёте: если говорящий сам входит в число тех, кого считают, — нужна somos, если считает со стороны, не включая себя, — нужна son. Проверка та же, что и раньше: есть ли «я» внутри группы. Запомнить легко: eres — это всегда «ты» один, а число появляется, только когда речь идёт о нескольких — своих через somos или чужих через son.',
  uk: 'Найчастіша помилка — сказати Eres dos, звертаючись до одного співрозмовника: одна людина фізично не може бути «два», числа стають лише після somos або son, ніколи після eres. Друга пастка — сплутати somos і son при рахунку: якщо мовець сам входить до числа тих, кого рахують, — потрібна somos, якщо рахує збоку, не включаючи себе, — потрібна son. Перевірка та сама, що й раніше: чи є «я» всередині групи. Запам’ятати легко: eres — це завжди «ти» один, а число з’являється лише тоді, коли йдеться про кількох — своїх через somos або чужих через son.',
  es: 'The most common mistake is saying Eres dos to a single listener: one person physically cannot be "two", numbers go only after somos or son, never after eres. The second trap is confusing somos and son when counting: if the speaker is among those being counted, somos is needed; if counting from the outside, not including themselves, son is needed. The check is the same as before: is "I" inside the group. It is easy to remember: eres is always one "you", and a number appears only when talking about several — your own through somos or another\'s through son.',
  'pt-BR': 'O erro mais comum é dizer Eres dos a um único interlocutor: uma pessoa não pode fisicamente ser "dois", números vêm só depois de somos ou son, nunca depois de eres. A segunda armadilha é confundir somos e son ao contar: se quem fala está entre os contados, precisa de somos; se conta de fora, sem se incluir, precisa de son. A checagem é a mesma de antes: se "eu" está dentro do grupo. É fácil lembrar: eres é sempre um "você" só, e um número aparece apenas ao falar de vários — os próprios com somos ou os de fora com son.',
  vi: 'Lỗi phổ biến nhất là nói Eres dos với một người nghe duy nhất: một người không thể là "hai" về mặt vật lý, số chỉ đứng sau somos hoặc son, không bao giờ sau eres. Cái bẫy thứ hai là nhầm somos với son khi đếm: nếu người nói nằm trong số những người được đếm — cần somos, nếu đếm từ bên ngoài, không tính bản thân — cần son. Cách kiểm tra giống như trước: "tôi" có ở trong nhóm không. Dễ nhớ: eres luôn là một "bạn" duy nhất, và con số chỉ xuất hiện khi nói về nhiều người — của mình qua somos hoặc của người khác qua son.',
  id: 'Kesalahan paling umum adalah mengatakan Eres dos kepada satu pendengar: satu orang secara fisik tidak bisa menjadi "dua", angka hanya muncul setelah somos atau son, tidak pernah setelah eres. Jebakan kedua adalah mengacaukan somos dan son saat menghitung: jika penutur termasuk yang dihitung — diperlukan somos, jika menghitung dari luar, tanpa memasukkan diri sendiri — diperlukan son. Pengecekannya sama seperti sebelumnya: apakah "saya" ada di dalam kelompok. Mudah diingat: eres selalu satu "kamu", dan angka hanya muncul ketika membicarakan beberapa — milik sendiri lewat somos atau milik orang lain lewat son.',
  tr: 'En yaygın hata, tek bir dinleyiciye Eres dos demektir: bir kişi fiziksel olarak "iki" olamaz, sayılar yalnızca somos ya da son’dan sonra gelir, asla eres’ten sonra değil. İkinci tuzak, sayarken somos ile son’u karıştırmaktır: konuşan sayılanlar arasındaysa — somos gerekir, dışarıdan, kendini dahil etmeden sayıyorsa — son gerekir. Kontrol öncekiyle aynıdır: "ben" grubun içinde mi. Hatırlamak kolaydır: eres her zaman tek bir "sen"dir, ve sayı yalnızca birkaç kişiden bahsedilirken ortaya çıkar — somos ile kendi grubu ya da son ile başkasınınki.',
  pl: 'Najczęstszy błąd to powiedzieć Eres dos do jednego słuchacza: jedna osoba fizycznie nie może być „dwa”, liczby pojawiają się tylko po somos lub son, nigdy po eres. Druga pułapka to mylenie somos i son przy liczeniu: jeśli mówiący jest wśród liczonych — potrzebne jest somos, jeśli liczy z zewnątrz, nie wliczając siebie — potrzebne jest son. Sprawdzenie jest takie samo jak wcześniej: czy „ja” jest wewnątrz grupy. Łatwo zapamiętać: eres to zawsze jedno „ty”, a liczba pojawia się tylko wtedy, gdy mowa o kilku — swoich przez somos albo cudzych przez son.',
});

export const ES_EPISODE_01_SESSION_28_INTRO: readonly [
  SessionSourceIntroPage,
  SessionSourceIntroPage,
  SessionSourceIntroPage,
] = [
  {
    kind: 'concept',
    title: L({
      ru: 'Число сразу после связки',
      uk: 'Число одразу після зв’язки',
      es: 'A number right after the linking word',
      'pt-BR': 'Um número logo após a ligação',
      vi: 'Một con số ngay sau từ nối',
      id: 'Angka tepat setelah kata penghubung',
      tr: 'Bağlaçtan hemen sonra bir sayı',
      pl: 'Liczba zaraz po łączniku',
    }),
    body: CONCEPT_BODY,
    bodyRuns: {
      ru: R({ text: 'Somos и son уже знакомы: somos — про группу, в которую входит сам говорящий, son — про группу со стороны, без него. Число встаёт сразу после любой из этих связок и просто называет точный размер группы: ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' — нас двое, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' — их трое. Лицо и число связки при этом не меняются вовсе — числительное лишь добавляет уточнение, сколько именно человек имеется в виду. С eres так не работает: собеседник один, и один человек не может быть «два» или «три» — числа встают только после somos и son, никогда после eres. Порядок слов простой и жёсткий: сначала связка, сразу за ней число, без дополнительных слов между ними.', semantic: 'explanation' }),
      uk: R({ text: 'Somos і son уже знайомі: somos — про групу, до якої входить сам мовець, son — про групу збоку, без нього. Число стає одразу після будь-якої з цих зв’язок і просто називає точний розмір групи: ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' — нас двоє, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' — їх троє. Особа і число зв’язки при цьому не змінюються зовсім — числівник лише додає уточнення, скільки саме людей мається на увазі. З eres так не працює: співрозмовник один, і одна людина не може бути «два» чи «три» — числа стають лише після somos і son, ніколи після eres. Порядок слів простий і жорсткий: спершу зв’язка, одразу за нею число, без додаткових слів між ними.', semantic: 'explanation' }),
      es: R({ text: 'Somos and son are already familiar: somos is about a group that includes the speaker, son is about a group from the outside, without them. A number goes right after either of these linking words and simply states the exact size of the group: ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' — there are two of us, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' — there are three of them. The person and number of the linking word do not change at all — the numeral only adds how many people exactly are meant. This does not work with eres: the listener is one person, and one person cannot be "two" or "three" — numbers go only after somos and son, never after eres.', semantic: 'explanation' }),
      'pt-BR': R({ text: 'Somos e son já são conhecidas: somos é sobre um grupo que inclui quem fala, son é sobre um grupo de fora, sem ele. Um número vem logo após qualquer uma dessas ligações e simplesmente indica o tamanho exato do grupo: ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' — somos dois, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' — são três. A pessoa e o número da ligação não mudam em nada — o numeral só acrescenta quantas pessoas exatamente estão sendo mencionadas. Isso não funciona com eres: o interlocutor é uma só pessoa, e uma pessoa não pode ser "dois" ou "três" — números vêm só depois de somos e son, nunca depois de eres. A ordem das palavras é simples e rígida: primeiro a ligação, logo depois o número, sem palavras extras entre eles.', semantic: 'explanation' }),
      vi: R({ text: 'Somos và son đã quen thuộc: somos nói về nhóm gồm cả người nói, son nói về nhóm từ bên ngoài, không có người nói. Một con số đứng ngay sau bất kỳ từ nối nào trong hai từ này và chỉ đơn giản nói ra quy mô chính xác của nhóm: ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' — chúng tôi có hai người, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' — họ có ba người. Ngôi và số của từ nối hoàn toàn không đổi — số đếm chỉ thêm vào chính xác bao nhiêu người được nhắc tới. Điều này không dùng được với eres: người nghe chỉ có một, và một người không thể là "hai" hay "ba" — số chỉ đứng sau somos và son, không bao giờ sau eres. Trật tự từ đơn giản và chặt chẽ: đầu tiên là từ nối, ngay sau đó là con số, không có từ thừa nào ở giữa.', semantic: 'explanation' }),
      id: R({ text: 'Somos dan son sudah dikenal: somos tentang kelompok yang mencakup penutur, son tentang kelompok dari luar, tanpa penutur. Angka muncul tepat setelah salah satu kata penghubung ini dan hanya menyatakan ukuran pasti kelompok: ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' — kami berdua, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' — mereka bertiga. Orang dan jumlah kata penghubung sama sekali tidak berubah — angka hanya menambahkan berapa persisnya orang yang dimaksud. Ini tidak berlaku untuk eres: pendengar hanya satu orang, dan satu orang tidak bisa menjadi "dua" atau "tiga" — angka hanya muncul setelah somos dan son, tidak pernah setelah eres. Urutan katanya sederhana dan ketat: kata penghubung dulu, angka tepat setelahnya, tanpa kata tambahan di antaranya.', semantic: 'explanation' }),
      tr: R({ text: 'Somos ve son zaten tanıdıktır: somos, konuşanı da içeren bir grup hakkındadır, son ise dışarıdan, konuşan olmadan bir grup hakkındadır. Bir sayı bu bağlaçlardan birinin hemen ardından gelir ve grubun tam büyüklüğünü basitçe belirtir: ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' — ikimiziz, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' — onlar üç kişi. Bağlacın kişisi ve sayısı hiç değişmez — sayı yalnızca tam olarak kaç kişinin kastedildiğini ekler. Bu, eres ile çalışmaz: dinleyici tek bir kişidir, ve tek bir kişi "iki" ya da "üç" olamaz — sayılar yalnızca somos ve son’dan sonra gelir, asla eres’ten sonra değil. Kelime sırası basit ve katıdır: önce bağlaç, hemen ardından sayı, aralarında fazladan kelime olmadan.', semantic: 'explanation' }),
      pl: R({ text: 'Somos i son są już znane: somos dotyczy grupy, do której należy mówiący, son dotyczy grupy z zewnątrz, bez niego. Liczba pojawia się zaraz po jednym z tych łączników i po prostu podaje dokładny rozmiar grupy: ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' — jest nas dwoje, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' — jest ich troje. Osoba i liczba łącznika wcale się nie zmieniają — liczebnik tylko dodaje, ile dokładnie osób ma się na myśli. Z eres to nie działa: słuchacz to jedna osoba, a jedna osoba nie może być „dwa” ani „trzy” — liczby pojawiają się tylko po somos i son, nigdy po eres. Szyk wyrazów jest prosty i sztywny: najpierw łącznik, zaraz po nim liczba, bez dodatkowych słów między nimi.', semantic: 'explanation' }),
    },
    question: {
      prompt: L({
        ru: 'Как правильно назвать точный размер своей группы из двух человек?',
        uk: 'Як правильно назвати точний розмір своєї групи з двох людей?',
        es: 'How do you correctly state the exact size of your own group of two people?',
        'pt-BR': 'Como se diz corretamente o tamanho exato do próprio grupo de duas pessoas?',
        vi: 'Nói đúng quy mô chính xác của nhóm mình gồm hai người, như thế nào?',
        id: 'Bagaimana cara menyatakan dengan benar ukuran pasti kelompok sendiri yang terdiri dari dua orang?',
        tr: 'Kendi iki kişilik grubunun tam büyüklüğü doğru nasıl söylenir?',
        pl: 'Jak poprawnie podać dokładny rozmiar własnej grupy dwóch osób?',
      }),
      choices: [
        L({ ru: 'Somos dos', uk: 'Somos dos', es: 'Somos dos', 'pt-BR': 'Somos dos', vi: 'Somos dos', id: 'Somos dos', tr: 'Somos dos', pl: 'Somos dos' }),
        L({ ru: 'Eres dos', uk: 'Eres dos', es: 'Eres dos', 'pt-BR': 'Eres dos', vi: 'Eres dos', id: 'Eres dos', tr: 'Eres dos', pl: 'Eres dos' }),
        L({ ru: 'Son dos', uk: 'Son dos', es: 'Son dos', 'pt-BR': 'Son dos', vi: 'Son dos', id: 'Son dos', tr: 'Son dos', pl: 'Son dos' }),
      ],
      correctChoiceIndex: 0,
      explanation: L({
        ru: 'Somos dos верно, потому что говорящий сам входит в группу из двух человек. Eres dos невозможно — один собеседник не может быть «два», а Son dos назвало бы чужую группу без говорящего.',
        uk: 'Somos dos правильно, бо мовець сам входить до групи з двох людей. Eres dos неможливо — один співрозмовник не може бути «два», а Son dos назвало б чужу групу без мовця.',
        es: 'Somos dos is correct because the speaker is part of a group of two. Eres dos is impossible — one listener cannot be "two", and Son dos would name another group without the speaker.',
        'pt-BR': 'Somos dos está correto porque quem fala faz parte de um grupo de duas pessoas. Eres dos é impossível — um interlocutor não pode ser "dois", e Son dos indicaria outro grupo sem quem fala.',
        vi: 'Somos dos đúng vì người nói thuộc về nhóm hai người. Eres dos là không thể — một người nghe không thể là "hai", còn Son dos sẽ chỉ nhóm khác không có người nói.',
        id: 'Somos dos benar karena penutur adalah bagian dari kelompok dua orang. Eres dos tidak mungkin — satu pendengar tidak bisa menjadi "dua", dan Son dos akan menyebutkan kelompok lain tanpa penutur.',
        tr: 'Somos dos doğrudur çünkü konuşan iki kişilik grubun bir parçasıdır. Eres dos imkansızdır — tek bir dinleyici "iki" olamaz, ve Son dos konuşan olmadan başka bir grubu adlandırırdı.',
        pl: 'Somos dos jest poprawne, ponieważ mówiący jest częścią dwuosobowej grupy. Eres dos jest niemożliwe — jeden słuchacz nie może być „dwa”, a Son dos nazywałoby inną grupę bez mówiącego.',
      }),
    },
  },
  {
    kind: 'formula',
    title: L({
      ru: 'Связка плюс число, и больше ничего',
      uk: 'Зв’язка плюс число, і більше нічого',
      es: 'Linking word plus number, nothing else',
      'pt-BR': 'Ligação mais número, e nada mais',
      vi: 'Từ nối cộng con số, không gì khác',
      id: 'Kata penghubung ditambah angka, tidak ada lagi',
      tr: 'Bağlaç artı sayı, başka bir şey değil',
      pl: 'Łącznik plus liczba, i nic więcej',
    }),
    body: FORMULA_BODY,
    bodyRuns: {
      ru: R({ text: 'Формула проста: связка (somos для своей группы, son для чужой) плюс число сразу за ней. ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' говорит о размере своей группы в два человека, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' — о чужой группе в три человека, и оба раза число не меняется ни от чего — ни от рода, ни от того, о ком идёт речь. Отрицание работает точно так же, как и раньше: No встаёт перед связкой, ', semantic: 'explanation' }, { text: 'No somos dos', semantic: 'targetCorrect' }, { text: ' отрицает число своей группы, ', semantic: 'explanation' }, { text: 'No son tres', semantic: 'targetCorrect' }, { text: ' — чужой. Число можно даже уточнять подряд: Somos dos, no tres — сначала называется верное число, затем через no отрицается соседнее, ошибочное.', semantic: 'explanation' }),
      uk: R({ text: 'Формула проста: зв’язка (somos для своєї групи, son для чужої) плюс число одразу за нею. ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' говорить про розмір своєї групи у дві людини, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' — про чужу групу у три людини, і обидва рази число не змінюється ні від чого — ні від роду, ні від того, про кого йдеться. Заперечення працює точнісінько як і раніше: No стає перед зв’язкою, ', semantic: 'explanation' }, { text: 'No somos dos', semantic: 'targetCorrect' }, { text: ' заперечує число своєї групи, ', semantic: 'explanation' }, { text: 'No son tres', semantic: 'targetCorrect' }, { text: ' — чужої. Число можна навіть уточнювати підряд: Somos dos, no tres — спершу називається правильне число, потім через no заперечується сусіднє, помилкове.', semantic: 'explanation' }),
      es: R({ text: 'The formula is simple: linking word (somos for your own group, son for another) plus a number right after it. ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' states the size of your own group as two people, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' states another group as three people, and both times the number does not change for anything — not for gender, not for who is being talked about. Negation works exactly as before: No comes before the linking word, ', semantic: 'explanation' }, { text: 'No somos dos', semantic: 'targetCorrect' }, { text: ' negates the number of your own group, ', semantic: 'explanation' }, { text: 'No son tres', semantic: 'targetCorrect' }, { text: ' negates another\'s. The number can even be clarified in a row: Somos dos, no tres — first the right number is stated, then no negates the neighboring, wrong one.', semantic: 'explanation' }),
      'pt-BR': R({ text: 'A fórmula é simples: ligação (somos para o próprio grupo, son para outro) mais um número logo depois. ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' indica o tamanho do próprio grupo em duas pessoas, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' indica outro grupo em três pessoas, e nas duas vezes o número não muda por nada — nem por gênero, nem por quem está sendo mencionado. A negação funciona exatamente como antes: No vem antes da ligação, ', semantic: 'explanation' }, { text: 'No somos dos', semantic: 'targetCorrect' }, { text: ' nega o número do próprio grupo, ', semantic: 'explanation' }, { text: 'No son tres', semantic: 'targetCorrect' }, { text: ' nega o de outro. O número pode até ser esclarecido em sequência: Somos dos, no tres — primeiro se indica o número certo, depois no nega o vizinho, o errado.', semantic: 'explanation' }),
      vi: R({ text: 'Công thức đơn giản: từ nối (somos cho nhóm của mình, son cho nhóm khác) cộng con số ngay sau đó. ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' nói ra quy mô nhóm của mình là hai người, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' nói về nhóm khác là ba người, và cả hai lần con số không đổi vì bất cứ điều gì — không vì giống, không vì đang nói về ai. Phủ định hoạt động y hệt như trước: No đứng trước từ nối, ', semantic: 'explanation' }, { text: 'No somos dos', semantic: 'targetCorrect' }, { text: ' phủ định con số của nhóm mình, ', semantic: 'explanation' }, { text: 'No son tres', semantic: 'targetCorrect' }, { text: ' phủ định con số của nhóm khác. Con số thậm chí có thể được làm rõ liên tiếp: Somos dos, no tres — đầu tiên nói ra con số đúng, sau đó no phủ định con số lân cận, sai.', semantic: 'explanation' }),
      id: R({ text: 'Rumusnya sederhana: kata penghubung (somos untuk kelompok sendiri, son untuk kelompok lain) ditambah angka tepat setelahnya. ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' menyatakan ukuran kelompok sendiri sebagai dua orang, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' menyatakan kelompok lain sebagai tiga orang, dan kedua kalinya angkanya sama sekali tidak berubah — bukan karena gender, bukan karena siapa yang dibicarakan. Negasi bekerja persis seperti sebelumnya: No berada sebelum kata penghubung, ', semantic: 'explanation' }, { text: 'No somos dos', semantic: 'targetCorrect' }, { text: ' menegasikan angka kelompok sendiri, ', semantic: 'explanation' }, { text: 'No son tres', semantic: 'targetCorrect' }, { text: ' menegasikan kelompok lain. Angkanya bahkan bisa diklarifikasi berturut-turut: Somos dos, no tres — pertama angka yang benar disebutkan, lalu no menegasikan angka tetangganya yang salah.', semantic: 'explanation' }),
      tr: R({ text: 'Formül basittir: bağlaç (kendi grubu için somos, başkası için son) artı hemen ardından bir sayı. ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' kendi grubunun büyüklüğünü iki kişi olarak belirtir, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' başka bir grubu üç kişi olarak belirtir, ve her iki seferde de sayı hiçbir şeyden dolayı değişmez — ne cinsiyetten, ne de kimden bahsedildiğinden. Olumsuzlama tam olarak öncekiyle aynı şekilde çalışır: No bağlaçtan önce gelir, ', semantic: 'explanation' }, { text: 'No somos dos', semantic: 'targetCorrect' }, { text: ' kendi grubunun sayısını olumsuzlar, ', semantic: 'explanation' }, { text: 'No son tres', semantic: 'targetCorrect' }, { text: ' başkasınınkini olumsuzlar. Sayı arka arkaya bile netleştirilebilir: Somos dos, no tres — önce doğru sayı söylenir, sonra no komşu, yanlış olanı olumsuzlar.', semantic: 'explanation' }),
      pl: R({ text: 'Formuła jest prosta: łącznik (somos dla własnej grupy, son dla innej) plus liczba zaraz po nim. ', semantic: 'explanation' }, { text: 'Somos dos', semantic: 'targetCorrect' }, { text: ' podaje rozmiar własnej grupy jako dwie osoby, ', semantic: 'explanation' }, { text: 'Son tres', semantic: 'targetCorrect' }, { text: ' podaje inną grupę jako trzy osoby, i za każdym razem liczba się nie zmienia z żadnego powodu — ani przez rodzaj, ani przez to, o kim mowa. Przeczenie działa dokładnie jak wcześniej: No stoi przed łącznikiem, ', semantic: 'explanation' }, { text: 'No somos dos', semantic: 'targetCorrect' }, { text: ' zaprzecza liczbie własnej grupy, ', semantic: 'explanation' }, { text: 'No son tres', semantic: 'targetCorrect' }, { text: ' zaprzecza liczbie innej. Liczbę można nawet doprecyzować pod rząd: Somos dos, no tres — najpierw podaje się właściwą liczbę, potem no zaprzecza sąsiedniej, błędnej.', semantic: 'explanation' }),
    },
    question: {
      prompt: L({
        ru: 'Где встаёт No, когда нужно отрицать число своей группы?',
        uk: 'Де стає No, коли потрібно заперечити число своєї групи?',
        es: 'Where does No go when negating the number of your own group?',
        'pt-BR': 'Onde fica No ao negar o número do próprio grupo?',
        vi: 'No đứng ở đâu khi phủ định con số của nhóm mình?',
        id: 'Di mana No diletakkan saat menegasikan angka kelompok sendiri?',
        tr: 'Kendi grubunun sayısı olumsuzlanırken No nereye gelir?',
        pl: 'Gdzie stoi No, gdy trzeba zaprzeczyć liczbie własnej grupy?',
      }),
      choices: [
        L({ ru: 'No somos dos', uk: 'No somos dos', es: 'No somos dos', 'pt-BR': 'No somos dos', vi: 'No somos dos', id: 'No somos dos', tr: 'No somos dos', pl: 'No somos dos' }),
        L({ ru: 'Somos dos no', uk: 'Somos dos no', es: 'Somos dos no', 'pt-BR': 'Somos dos no', vi: 'Somos dos no', id: 'Somos dos no', tr: 'Somos dos no', pl: 'Somos dos no' }),
        L({ ru: 'Somos no dos', uk: 'Somos no dos', es: 'Somos no dos', 'pt-BR': 'Somos no dos', vi: 'Somos no dos', id: 'Somos no dos', tr: 'Somos no dos', pl: 'Somos no dos' }),
      ],
      correctChoiceIndex: 0,
      explanation: L({
        ru: 'No somos dos верно, потому что No встаёт перед связкой, а не рядом с числом: отрицается всё утверждение целиком, а связка с числом остаются в паре без изменений.',
        uk: 'No somos dos правильно, бо No стає перед зв’язкою, а не поруч із числом: заперечується все твердження цілком, а зв’язка з числом лишаються в парі без змін.',
        es: 'No somos dos is correct because No goes before the linking word, not next to the number: the whole statement is negated, while the linking word and the number stay together unchanged.',
        'pt-BR': 'No somos dos está correto porque No vem antes da ligação, não perto do número: toda a afirmação é negada, enquanto a ligação e o número permanecem juntos sem mudanças.',
        vi: 'No somos dos đúng vì No đứng trước từ nối, không phải bên cạnh con số: toàn bộ câu khẳng định bị phủ định, còn từ nối với con số vẫn đi cùng nhau không đổi.',
        id: 'No somos dos benar karena No berada sebelum kata penghubung, bukan di dekat angka: seluruh pernyataan dinegasikan, sementara kata penghubung dan angka tetap bersama tanpa berubah.',
        tr: 'No somos dos doğrudur çünkü No, sayının yanına değil bağlaçtan önce gelir: tüm ifade olumsuzlanır, bağlaç ile sayı ise değişmeden birlikte kalır.',
        pl: 'No somos dos jest poprawne, ponieważ No stoi przed łącznikiem, a nie obok liczby: zaprzecza się całemu stwierdzeniu, a łącznik z liczbą pozostają razem bez zmian.',
      }),
    },
  },
  {
    kind: 'trap',
    title: L({
      ru: 'Число не сочетается с eres',
      uk: 'Число не поєднується з eres',
      es: 'A number does not combine with eres',
      'pt-BR': 'Um número não combina com eres',
      vi: 'Con số không kết hợp với eres',
      id: 'Angka tidak digabungkan dengan eres',
      tr: 'Sayı eres ile birleşmez',
      pl: 'Liczba nie łączy się z eres',
    }),
    body: TRAP_BODY,
    bodyRuns: {
      ru: R({ text: 'Самая частая ошибка — сказать ', semantic: 'explanation' }, { text: 'Eres dos', semantic: 'targetWrong' }, { text: ', обращаясь к одному собеседнику: один человек физически не может быть «два», числа встают только после ', semantic: 'explanation' }, { text: 'somos', semantic: 'targetCorrect' }, { text: ' или ', semantic: 'explanation' }, { text: 'son', semantic: 'targetCorrect' }, { text: ', никогда после eres. Вторая ловушка — перепутать somos и son при счёте: если говорящий сам входит в число тех, кого считают, — нужна somos, если считает со стороны, не включая себя, — нужна son. Проверка та же, что и раньше: есть ли «я» внутри группы. Запомнить легко: eres — это всегда «ты» один, а число появляется, только когда речь идёт о нескольких — своих через somos или чужих через son.', semantic: 'explanation' }),
      uk: R({ text: 'Найчастіша помилка — сказати ', semantic: 'explanation' }, { text: 'Eres dos', semantic: 'targetWrong' }, { text: ', звертаючись до одного співрозмовника: одна людина фізично не може бути «два», числа стають лише після ', semantic: 'explanation' }, { text: 'somos', semantic: 'targetCorrect' }, { text: ' або ', semantic: 'explanation' }, { text: 'son', semantic: 'targetCorrect' }, { text: ', ніколи після eres. Друга пастка — сплутати somos і son при рахунку: якщо мовець сам входить до числа тих, кого рахують, — потрібна somos, якщо рахує збоку, не включаючи себе, — потрібна son. Перевірка та сама, що й раніше: чи є «я» всередині групи. Запам’ятати легко: eres — це завжди «ти» один, а число з’являється лише тоді, коли йдеться про кількох — своїх через somos або чужих через son.', semantic: 'explanation' }),
      es: R({ text: 'The most common mistake is saying ', semantic: 'explanation' }, { text: 'Eres dos', semantic: 'targetWrong' }, { text: ' to a single listener: one person physically cannot be "two", numbers go only after ', semantic: 'explanation' }, { text: 'somos', semantic: 'targetCorrect' }, { text: ' or ', semantic: 'explanation' }, { text: 'son', semantic: 'targetCorrect' }, { text: ', never after eres. The second trap is confusing somos and son when counting: if the speaker is among those being counted, somos is needed; if counting from the outside, not including themselves, son is needed. The check is the same as before: is "I" inside the group. It is easy to remember: eres is always one "you", and a number appears only when talking about several — your own through somos or another\'s through son.', semantic: 'explanation' }),
      'pt-BR': R({ text: 'O erro mais comum é dizer ', semantic: 'explanation' }, { text: 'Eres dos', semantic: 'targetWrong' }, { text: ' a um único interlocutor: uma pessoa não pode fisicamente ser "dois", números vêm só depois de ', semantic: 'explanation' }, { text: 'somos', semantic: 'targetCorrect' }, { text: ' ou ', semantic: 'explanation' }, { text: 'son', semantic: 'targetCorrect' }, { text: ', nunca depois de eres. A segunda armadilha é confundir somos e son ao contar: se quem fala está entre os contados, precisa de somos; se conta de fora, sem se incluir, precisa de son. A checagem é a mesma de antes: se "eu" está dentro do grupo. É fácil lembrar: eres é sempre um "você" só, e um número aparece apenas ao falar de vários — os próprios com somos ou os de fora com son.', semantic: 'explanation' }),
      vi: R({ text: 'Lỗi phổ biến nhất là nói ', semantic: 'explanation' }, { text: 'Eres dos', semantic: 'targetWrong' }, { text: ' với một người nghe duy nhất: một người không thể là "hai" về mặt vật lý, số chỉ đứng sau ', semantic: 'explanation' }, { text: 'somos', semantic: 'targetCorrect' }, { text: ' hoặc ', semantic: 'explanation' }, { text: 'son', semantic: 'targetCorrect' }, { text: ', không bao giờ sau eres. Cái bẫy thứ hai là nhầm somos với son khi đếm: nếu người nói nằm trong số những người được đếm — cần somos, nếu đếm từ bên ngoài, không tính bản thân — cần son. Cách kiểm tra giống như trước: "tôi" có ở trong nhóm không. Dễ nhớ: eres luôn là một "bạn" duy nhất, và con số chỉ xuất hiện khi nói về nhiều người — của mình qua somos hoặc của người khác qua son.', semantic: 'explanation' }),
      id: R({ text: 'Kesalahan paling umum adalah mengatakan ', semantic: 'explanation' }, { text: 'Eres dos', semantic: 'targetWrong' }, { text: ' kepada satu pendengar: satu orang secara fisik tidak bisa menjadi "dua", angka hanya muncul setelah ', semantic: 'explanation' }, { text: 'somos', semantic: 'targetCorrect' }, { text: ' atau ', semantic: 'explanation' }, { text: 'son', semantic: 'targetCorrect' }, { text: ', tidak pernah setelah eres. Jebakan kedua adalah mengacaukan somos dan son saat menghitung: jika penutur termasuk yang dihitung — diperlukan somos, jika menghitung dari luar, tanpa memasukkan diri sendiri — diperlukan son. Pengecekannya sama seperti sebelumnya: apakah "saya" ada di dalam kelompok. Mudah diingat: eres selalu satu "kamu", dan angka hanya muncul ketika membicarakan beberapa — milik sendiri lewat somos atau milik orang lain lewat son.', semantic: 'explanation' }),
      tr: R({ text: 'En yaygın hata, tek bir dinleyiciye ', semantic: 'explanation' }, { text: 'Eres dos', semantic: 'targetWrong' }, { text: ' demektir: bir kişi fiziksel olarak "iki" olamaz, sayılar yalnızca ', semantic: 'explanation' }, { text: 'somos', semantic: 'targetCorrect' }, { text: ' ya da ', semantic: 'explanation' }, { text: 'son', semantic: 'targetCorrect' }, { text: '’dan sonra gelir, asla eres’ten sonra değil. İkinci tuzak, sayarken somos ile son’u karıştırmaktır: konuşan sayılanlar arasındaysa — somos gerekir, dışarıdan, kendini dahil etmeden sayıyorsa — son gerekir. Kontrol öncekiyle aynıdır: "ben" grubun içinde mi. Hatırlamak kolaydır: eres her zaman tek bir "sen"dir, ve sayı yalnızca birkaç kişiden bahsedilirken ortaya çıkar — somos ile kendi grubu ya da son ile başkasınınki.', semantic: 'explanation' }),
      pl: R({ text: 'Najczęstszy błąd to powiedzieć ', semantic: 'explanation' }, { text: 'Eres dos', semantic: 'targetWrong' }, { text: ' do jednego słuchacza: jedna osoba fizycznie nie może być „dwa”, liczby pojawiają się tylko po ', semantic: 'explanation' }, { text: 'somos', semantic: 'targetCorrect' }, { text: ' lub ', semantic: 'explanation' }, { text: 'son', semantic: 'targetCorrect' }, { text: ', nigdy po eres. Druga pułapka to mylenie somos i son przy liczeniu: jeśli mówiący jest wśród liczonych — potrzebne jest somos, jeśli liczy z zewnątrz, nie wliczając siebie — potrzebne jest son. Sprawdzenie jest takie samo jak wcześniej: czy „ja” jest wewnątrz grupy. Łatwo zapamiętać: eres to zawsze jedno „ty”, a liczba pojawia się tylko wtedy, gdy mowa o kilku — swoich przez somos albo cudzych przez son.', semantic: 'explanation' }),
    },
    question: {
      prompt: L({
        ru: 'Как правильно сказать, что чужая группа состоит из трёх человек?',
        uk: 'Як правильно сказати, що чужа група складається з трьох людей?',
        es: 'How do you correctly say that another group consists of three people?',
        'pt-BR': 'Como se diz corretamente que outro grupo é composto por três pessoas?',
        vi: 'Nói đúng rằng nhóm khác gồm ba người, như thế nào?',
        id: 'Bagaimana cara mengatakan dengan benar bahwa kelompok lain terdiri dari tiga orang?',
        tr: 'Başka bir grubun üç kişiden oluştuğu doğru nasıl söylenir?',
        pl: 'Jak poprawnie powiedzieć, że inna grupa składa się z trzech osób?',
      }),
      choices: [
        L({ ru: 'Son tres', uk: 'Son tres', es: 'Son tres', 'pt-BR': 'Son tres', vi: 'Son tres', id: 'Son tres', tr: 'Son tres', pl: 'Son tres' }),
        L({ ru: 'Eres tres', uk: 'Eres tres', es: 'Eres tres', 'pt-BR': 'Eres tres', vi: 'Eres tres', id: 'Eres tres', tr: 'Eres tres', pl: 'Eres tres' }),
        L({ ru: 'Somos tres', uk: 'Somos tres', es: 'Somos tres', 'pt-BR': 'Somos tres', vi: 'Somos tres', id: 'Somos tres', tr: 'Somos tres', pl: 'Somos tres' }),
      ],
      correctChoiceIndex: 0,
      explanation: L({
        ru: 'Son tres верно, потому что говорящий не входит в эту группу — считает со стороны. Eres tres невозможно — один собеседник не может быть «три», а Somos tres включало бы говорящего в число этих трёх.',
        uk: 'Son tres правильно, бо мовець не входить до цієї групи — рахує збоку. Eres tres неможливо — один співрозмовник не може бути «три», а Somos tres включало б мовця до числа цих трьох.',
        es: 'Son tres is correct because the speaker is not part of this group — counting from the outside. Eres tres is impossible — one listener cannot be "three", and Somos tres would include the speaker among these three.',
        'pt-BR': 'Son tres está correto porque quem fala não faz parte desse grupo — conta de fora. Eres tres é impossível — um interlocutor não pode ser "três", e Somos tres incluiria quem fala entre esses três.',
        vi: 'Son tres đúng vì người nói không thuộc nhóm này — đếm từ bên ngoài. Eres tres là không thể — một người nghe không thể là "ba", còn Somos tres sẽ bao gồm người nói trong số ba người này.',
        id: 'Son tres benar karena penutur tidak termasuk dalam kelompok ini — menghitung dari luar. Eres tres tidak mungkin — satu pendengar tidak bisa menjadi "tiga", dan Somos tres akan mencakup penutur di antara ketiga orang ini.',
        tr: 'Son tres doğrudur çünkü konuşan bu grubun parçası değildir — dışarıdan sayar. Eres tres imkansızdır — tek bir dinleyici "üç" olamaz, ve Somos tres konuşanı bu üç kişi arasına dahil ederdi.',
        pl: 'Son tres jest poprawne, ponieważ mówiący nie jest częścią tej grupy — liczy z zewnątrz. Eres tres jest niemożliwe — jeden słuchacz nie może być „trzy”, a Somos tres objęłoby mówiącego wśród tych trzech.',
      }),
    },
  },
];
