import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

type PlannedTrainingLocale = 'pt-BR' | 'vi' | 'id' | 'tr' | 'pl';

const PP_QN_NEEDS_REVIEW_PLANNED: Record<PlannedTrainingLocale, string> = {
  'pt-BR': 'needs-review: esta explicação sobre perguntas e negações no Present Perfect ainda precisa de revisão para português do Brasil.',
  vi: 'needs-review: phần giải thích về câu hỏi và phủ định trong Present Perfect này vẫn cần được rà soát cho tiếng Việt.',
  id: 'needs-review: penjelasan pertanyaan dan negatif Present Perfect ini masih perlu ditinjau untuk bahasa Indonesia.',
  tr: 'needs-review: bu Present Perfect soru ve olumsuzluk açıklaması Türkçe için hâlâ gözden geçirilmeli.',
  pl: 'needs-review: to objaśnienie pytań i przeczeń w Present Perfect nadal wymaga przeglądu po polsku.',
};

const tri = (
  ru: string,
  uk: string,
  es: string,
  planned: Partial<Record<PlannedTrainingLocale, string>> = {},
): TriText => {
  const copy: TriText = { ru, uk, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    copy[locale] = planned[locale] ?? PP_QN_NEEDS_REVIEW_PLANNED[locale];
  }
  return copy;
};

const CONTRAST = [
  'have you + V3',
  'has she + V3',
  "haven't + V3",
  "hasn't + V3",
  'yet',
  'ever',
  'already',
  'did vs have',
];

const MODEL = tri(
  'Держи три решения. В вопросе служебное слово выходит вперед. В отрицании к нему добавляется not. После этого нужен третий вид глагола: сделал, видел, закончил.',
  'Тримай три рішення. У питанні службове слово виходить уперед. У запереченні до нього додається not. Після цього потрібна третя форма дієслова: зробив, бачив, закінчив.',
  "Las preguntas en Present Perfect empiezan con have o has: Have you finished? Has she called? Las negativas usan haven't o hasn't: I haven't finished. She hasn't seen it. Despues de estas palabras usa V3: finished, called, seen, done.",
  {
    'pt-BR': 'Guarde três decisões. Na pergunta, a palavra auxiliar vai para a frente. Na negativa, acrescentamos not a ela. Depois disso, precisamos da terceira forma do verbo: done, seen, finished, called.',
    vi: 'Hãy nhớ ba quyết định. Trong câu hỏi, trợ động từ đi lên đầu. Trong câu phủ định, thêm not vào trợ động từ đó. Sau đó cần dạng thứ ba của động từ: done, seen, finished, called.',
    id: 'Ingat tiga keputusan. Dalam pertanyaan, kata bantu maju ke depan. Dalam negatif, not ditambahkan ke kata bantu itu. Setelah itu perlu bentuk ketiga kata kerja: done, seen, finished, called.',
    tr: 'Üç kararı aklında tut. Soruda yardımcı kelime başa çıkar. Olumsuzda ona not eklenir. Bundan sonra fiilin üçüncü hali gerekir: done, seen, finished, called.',
    pl: 'Zapamiętaj trzy decyzje. W pytaniu słowo pomocnicze wychodzi na początek. W przeczeniu dodajemy do niego not. Potem potrzebna jest trzecia forma czasownika: done, seen, finished, called.',
  },
);

const PP_QN_SKILL_ES: Record<string, string> = {
  have_you_finished: 'La pregunta empieza con Have, y finished se queda en V3.',
  have_they_left: 'Con they usa have; yet suele ir al final de la pregunta.',
  question_order_have: 'En una pregunta neutral, have va antes de you.',
  has_she_called: 'Con she usa has, no have ni did.',
  has_he_seen: 'Despues de has necesitas seen, no saw ni see.',
  has_it_started: 'Con it usa has al principio de la pregunta.',
  haven_t_finished: "Con I usa haven't; despues va V3.",
  hasn_t_called: "Con she usa hasn't; called se mantiene como V3.",
  haven_t_seen: "Despues de haven't necesitas seen.",
  yet_question: 'En la pregunta neutral de ya?, yet suele ir al final.',
  ever_question: 'Ever pregunta por experiencia.',
  never_no_double_negative: "Never ya da sentido negativo; no anadas haven't.",
  mixed_question_negative_pair: "Pregunta con Have; negativa con haven't + V3.",
  mixed_has_question_negative: "Con she usa has / hasn't y luego V3.",
  mixed_sentence_correction: "Ever pregunta experiencia; haven't seen yet significa que aun no lo has visto.",
};

function withEs(
  copy: TriText,
  es: string,
  planned: Partial<Record<PlannedTrainingLocale, string>> = PP_QN_NEEDS_REVIEW_PLANNED,
): TriText {
  const next: TriText = { ...copy, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    if (!next[locale] || next[locale]?.startsWith('needs-review:')) {
      next[locale] = planned[locale] ?? PP_QN_NEEDS_REVIEW_PLANNED[locale];
    }
  }
  return next;
}

function ppQnEsFeedback(input: {
  targetSkill: string;
  correctAnswer: string;
  focusWords: string[];
}): string {
  const focus = input.focusWords.join(' / ');
  const hint = PP_QN_SKILL_ES[input.targetSkill] ?? 'Comprueba have/has, el orden de pregunta y la forma V3.';
  return `Usa "${input.correctAnswer}"${focus ? ` con ${focus}` : ''}. ${hint}`;
}

function retry(correct: string): [TriText, TriText, TriText, TriText] {
  return [
    tri(
      'Сначала реши: это вопрос или отрицание.',
      'Спочатку виріши: це питання чи заперечення.',
      'Primero decide si es pregunta o negativa.',
    ),
    tri(
      'В вопросе have или has выходит в начало. В отрицании not приклеивается к have или has.',
      'У питанні have або has виходить на початок. У запереченні not приклеюється до have або has.',
      'En una pregunta, have o has va primero. En una negativa, not se une a have o has.',
    ),
    tri(
      'После этих слов нужен третий вид глагола: не простая форма и не прошедшее время из Past Simple.',
      'Після цих слів потрібна третя форма дієслова: не проста форма і не минулий час із Past Simple.',
      "Despues de have, has, haven't o hasn't usa V3: done, seen, finished, called.",
    ),
    tri(
      `Нужный вариант здесь: ${correct}.`,
      `Потрібний варіант тут: ${correct}.`,
      `La respuesta aqui es: ${correct}.`,
    ),
  ];
}

function defaultWrong(correct: string): TriText {
  return tri(
    `Почти. Проверь have/has, порядок вопроса и V3. Здесь нужно: ${correct}.`,
    `Майже. Перевір have/has, порядок питання і V3. Тут потрібно: ${correct}.`,
    `Casi. Revisa have/has, el orden de pregunta y V3. Usa: ${correct}.`,
  );
}

function qnStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  sentence: string;
  translation: TriText;
  options: string[];
  correctAnswer: string;
  correctFeedback: TriText;
  wrong: Record<string, TriText>;
  focusWords: string[];
}): DiagnosisTrainingStep {
  const esFeedback = ppQnEsFeedback(input);
  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    translation: withEs(input.translation, esFeedback),
    teachingText: withEs(MODEL, esFeedback),
    explanationBlock: withEs(MODEL, esFeedback),
    microTask: tri(
      'Выбери правильный вопрос или отрицание в Present Perfect.',
      'Обери правильне питання або заперечення в Present Perfect.',
      'Elige la pregunta o negativa correcta en Present Perfect.',
    ),
    sentence: input.sentence,
    answerOptions: input.options.map((text) => ({ id: text, text })),
    correctAnswerId: input.correctAnswer,
    correctIndex: input.options.findIndex((option) => option === input.correctAnswer),
    correctFeedback: withEs(input.correctFeedback, esFeedback),
    wrongFeedbackByOption: Object.fromEntries(
      input.options
        .filter((option) => option !== input.correctAnswer)
        .map((option) => [option, withEs(input.wrong[option] ?? defaultWrong(input.correctAnswer), esFeedback)]),
    ),
    retryFeedback: retry(input.correctAnswer).map((item) => withEs(item, esFeedback)) as [TriText, TriText, TriText, TriText],
    fallbackExplanation: tri(
      'Скелет такой: сначала have или has для вопроса; not для отрицания; затем третий вид глагола. Did здесь не нужен.',
      'Скелет такий: спочатку have або has для питання; not для заперечення; потім третя форма дієслова. Did тут не потрібен.',
      "Patron: Have you finished? Has she called? I haven't finished. She hasn't seen it. Aqui no uses did.",
    ),
    focusWords: input.focusWords,
  };
}

export const PRESENT_PERFECT_QUESTIONS_NEGATIVES_TRAINING: DiagnosisTraining = {
  id: 'present_perfect_questions_negatives',
  category: 'verb',
  version: '1.0.0',
  status: 'active',
  priority: 40,
  supportedLocales: ['ru', 'uk', 'es'],
  title: tri(
    'Present Perfect: вопросы и отрицания',
    'Present Perfect: питання і заперечення',
    "Present Perfect: preguntas y haven't / hasn't",
    {
      'pt-BR': 'Present Perfect: perguntas e negações',
      vi: 'Present Perfect: câu hỏi và phủ định',
      id: 'Present Perfect: pertanyaan dan negatif',
      tr: 'Present Perfect: sorular ve olumsuzlar',
      pl: 'Present Perfect: pytania i przeczenia',
    },
  ),
  shortTitle: tri('Perfect вопрос', 'Perfect питання', 'Perfect pregunta/negativa', {
    'pt-BR': 'Perfect: pergunta',
    vi: 'Perfect: câu hỏi',
    id: 'Perfect: pertanyaan',
    tr: 'Perfect: soru',
    pl: 'Perfect: pytanie',
  }),
  shortDiagnosis: tri(
    'Ты строишь вопрос как Past Simple, забываешь вынести служебное слово вперед или берешь не ту форму глагола.',
    'Ти будуєш питання як Past Simple, забуваєш винести службове слово вперед або береш не ту форму дієслова.',
    "Usas did, olvidas poner have/has al principio o pones see despues de haven't en vez de seen.",
    {
      'pt-BR': 'Você monta a pergunta como Past Simple, esquece de colocar o auxiliar no começo ou usa a forma errada do verbo.',
      vi: 'Bạn tạo câu hỏi như Past Simple, quên đưa trợ động từ lên đầu hoặc chọn sai dạng động từ.',
      id: 'Kamu membangun pertanyaan seperti Past Simple, lupa menaruh kata bantu di depan, atau memakai bentuk kata kerja yang salah.',
      tr: 'Soruyu Past Simple gibi kuruyorsun, yardımcı kelimeyi başa almayı unutuyorsun ya da fiilin yanlış halini seçiyorsun.',
      pl: 'Budujesz pytanie jak Past Simple, zapominasz wynieść słowo pomocnicze na początek albo bierzesz złą formę czasownika.',
    },
  ),
  diagnosisText: tri(
    'Здесь нужна одна привычка. В вопросе сначала ставим служебное слово. В отрицании добавляем not. А слово действия оставляем в третьем виде: закончил, видел, позвонил, сделал.',
    'Тут потрібна одна звичка. У питанні спочатку ставимо службове слово. У запереченні додаємо not. А слово дії залишаємо в третій формі: закінчив, бачив, подзвонив, зробив.',
    "Aqui necesitas un habito: la pregunta empieza con have o has. En la negativa, not va dentro de haven't o hasn't. El verbo de accion queda en V3: finished, seen, called, done.",
    {
      'pt-BR': 'Aqui você precisa de um hábito. Na pergunta, colocamos primeiro a palavra auxiliar. Na negativa, acrescentamos not. E o verbo da ação fica na terceira forma: finished, seen, called, done.',
      vi: 'Ở đây bạn cần một thói quen. Trong câu hỏi, đặt trợ động từ trước. Trong câu phủ định, thêm not. Còn động từ hành động giữ ở dạng thứ ba: finished, seen, called, done.',
      id: 'Di sini kamu perlu satu kebiasaan. Dalam pertanyaan, kata bantu diletakkan lebih dulu. Dalam negatif, tambahkan not. Kata kerja aksinya tetap dalam bentuk ketiga: finished, seen, called, done.',
      tr: 'Burada tek bir alışkanlık gerekir. Soruda önce yardımcı kelimeyi koyarız. Olumsuzda not ekleriz. Eylem fiili üçüncü halde kalır: finished, seen, called, done.',
      pl: 'Tutaj potrzebny jest jeden nawyk. W pytaniu najpierw stawiamy słowo pomocnicze. W przeczeniu dodajemy not. A czasownik czynności zostaje w trzeciej formie: finished, seen, called, done.',
    },
  ),
  mentalModel: MODEL,
  contrastSet: CONTRAST,
  coreRule: tri(
    'В вопросе служебное слово выходит в начало. В отрицании not прячется внутри короткой отрицательной формы. Yet обычно ставим в конце, когда смысл "уже?" или "еще не". Ever спрашивает про опыт.',
    'У питанні службове слово виходить на початок. У запереченні not ховається всередині короткої заперечної форми. Yet зазвичай ставимо в кінці, коли сенс "вже?" або "ще не". Ever питає про досвід.',
    "Pregunta: Have you finished? Has she seen it? Negativa: I haven't finished. She hasn't seen it. Yet suele ir al final. Ever pregunta por experiencia.",
    {
      'pt-BR': 'Na pergunta, a palavra auxiliar vai para o começo. Na negativa, not fica dentro da forma negativa curta. Yet geralmente vai no fim quando o sentido é "já?" ou "ainda não". Ever pergunta sobre experiência.',
      vi: 'Trong câu hỏi, trợ động từ đi lên đầu. Trong câu phủ định, not nằm trong dạng phủ định rút gọn. Yet thường đứng cuối câu khi nghĩa là "đã chưa?" hoặc "vẫn chưa". Ever hỏi về trải nghiệm.',
      id: 'Dalam pertanyaan, kata bantu maju ke awal. Dalam negatif, not tersembunyi di dalam bentuk negatif pendek. Yet biasanya berada di akhir ketika maknanya "sudah?" atau "belum". Ever menanyakan pengalaman.',
      tr: 'Soruda yardımcı kelime başa çıkar. Olumsuzda not kısa olumsuz biçimin içine girer. Yet, anlam "çoktan mı?" ya da "henüz değil" olduğunda genellikle sona gelir. Ever deneyim sorar.',
      pl: 'W pytaniu słowo pomocnicze wychodzi na początek. W przeczeniu not ukrywa się w krótkiej formie przeczącej. Yet zwykle stawiamy na końcu, gdy sens to "już?" albo "jeszcze nie". Ever pyta o doświadczenie.',
    },
  ),
  whatUserMustLearn: {
    ru: [
      'В вопросе have/has выходит в начало: Have you finished?',
      'С he, she, it в вопросе используем has: Has she called?',
      'После have или has нужен V3: done, seen, finished, called.',
      'Не говори Did you finished? Для Present Perfect нужен Have you finished?',
      "В отрицании используем haven't или hasn't.",
      "После haven't и hasn't нужен V3: haven't seen, hasn't called.",
      'Yet часто стоит в конце вопроса или отрицания.',
      'Ever обычно спрашивает об опыте: Have you ever been there?',
      "Never уже несет отрицательный смысл: обычно не нужно haven't never.",
      'Already возможно в вопросе, но нейтральное "уже?" часто строится с yet.',
    ],
    uk: [
      'У питанні have/has виходить на початок: Have you finished?',
      'З he, she, it у питанні використовуємо has: Has she called?',
      'Після have або has потрібен V3: done, seen, finished, called.',
      'Не кажи Did you finished? Для Present Perfect потрібно Have you finished?',
      "У запереченні використовуємо haven't або hasn't.",
      "Після haven't і hasn't потрібен V3: haven't seen, hasn't called.",
      'Yet часто стоїть у кінці питання або заперечення.',
      'Ever зазвичай питає про досвід: Have you ever been there?',
      "Never уже несе заперечний зміст: зазвичай не потрібно haven't never.",
      'Already можливе в питанні, але нейтральне "вже?" часто будується з yet.',
    ],
    es: [
      'En una pregunta, have/has va primero: Have you finished?',
      'Con he, she, it usa has: Has she called?',
      'Despues de have o has usa V3: done, seen, finished, called.',
      'No digas Did you finished? Para Present Perfect usa Have you finished?',
      "Las negativas usan haven't o hasn't.",
      "Despues de haven't y hasn't usa V3: haven't seen, hasn't called.",
      'Yet suele ir al final de preguntas o negativas.',
      'Ever normalmente pregunta por experiencia: Have you ever been there?',
      "Never ya da sentido negativo: normalmente no digas haven't never.",
      'Already puede aparecer en preguntas, pero la pregunta neutral de ya? muchas veces usa yet.',
    ],
    'pt-BR': [
      'Em perguntas, have/has vem no começo: Have you finished?',
      'Com he, she, it, usamos has: Has she called?',
      'Depois de have/has, use V3: done, seen, finished, called.',
      'Não diga Did you finished? Para Present Perfect, use Have you finished?',
      "Em negativas, usamos haven't ou hasn't.",
      "Depois de haven't/hasn't, use V3: haven't seen, hasn't called.",
      'Yet costuma ficar no fim de perguntas ou negativas.',
      'Ever normalmente pergunta sobre experiência: Have you ever been there?',
      "Never já traz sentido negativo: normalmente não diga haven't never.",
      'Already pode aparecer em perguntas, mas o "já?" neutro muitas vezes usa yet.',
    ],
    vi: [
      'Trong câu hỏi, have/has đứng đầu: Have you finished?',
      'Với he, she, it, dùng has: Has she called?',
      'Sau have/has, dùng V3: done, seen, finished, called.',
      'Đừng nói Did you finished? Với Present Perfect, dùng Have you finished?',
      "Câu phủ định dùng haven't hoặc hasn't.",
      "Sau haven't/hasn't, dùng V3: haven't seen, hasn't called.",
      'Yet thường đứng cuối câu hỏi hoặc câu phủ định.',
      'Ever thường hỏi về trải nghiệm: Have you ever been there?',
      "Never đã mang nghĩa phủ định, nên thường không dùng haven't never.",
      'Already có thể xuất hiện trong câu hỏi, nhưng câu hỏi trung tính "đã chưa?" thường dùng yet.',
    ],
    id: [
      'Dalam pertanyaan, have/has berada di awal: Have you finished?',
      'Dengan he, she, it, gunakan has: Has she called?',
      'Setelah have/has, gunakan V3: done, seen, finished, called.',
      'Jangan mengatakan Did you finished? Untuk Present Perfect, gunakan Have you finished?',
      "Kalimat negatif memakai haven't atau hasn't.",
      "Setelah haven't/hasn't, gunakan V3: haven't seen, hasn't called.",
      'Yet sering berada di akhir pertanyaan atau kalimat negatif.',
      'Ever biasanya menanyakan pengalaman: Have you ever been there?',
      "Never sudah bermakna negatif, jadi biasanya jangan memakai haven't never.",
      'Already bisa muncul dalam pertanyaan, tetapi pertanyaan netral "sudah?" sering memakai yet.',
    ],
    tr: [
      'Soruda have/has başa gelir: Have you finished?',
      'He, she, it ile has kullanırız: Has she called?',
      'Have/has sonrasında V3 kullan: done, seen, finished, called.',
      'Did you finished? deme. Present Perfect için Have you finished? kullan.',
      "Olumsuzda haven't veya hasn't kullanırız.",
      "Haven't/hasn't sonrasında V3 kullan: haven't seen, hasn't called.",
      'Yet genellikle soru veya olumsuz cümlenin sonunda durur.',
      'Ever genellikle deneyim sorar: Have you ever been there?',
      "Never zaten olumsuz anlam taşır; genelde haven't never deme.",
      'Already sorularda olabilir, ama nötr "çoktan mı?" sorusunda sıkça yet kullanılır.',
    ],
    pl: [
      'W pytaniu have/has stoi na początku: Have you finished?',
      'Z he, she, it używamy has: Has she called?',
      'Po have/has użyj V3: done, seen, finished, called.',
      'Nie mów Did you finished? W Present Perfect użyj Have you finished?',
      "W przeczeniach używamy haven't albo hasn't.",
      "Po haven't/hasn't użyj V3: haven't seen, hasn't called.",
      'Yet często stoi na końcu pytania albo przeczenia.',
      'Ever zwykle pyta o doświadczenie: Have you ever been there?',
      "Never już ma znaczenie przeczenia, więc zwykle nie mówimy haven't never.",
      'Already może wystąpić w pytaniu, ale neutralne "już?" często budujemy z yet.',
    ],
  },
  examples: [
    {
      en: 'Have you finished the lesson?',
      ru: 'Ты закончил урок?',
      uk: 'Ти закінчив урок?',
      es: 'Terminaste la leccion?',
      'pt-BR': 'Você terminou a lição?',
      vi: 'Bạn đã hoàn thành bài học chưa?',
      id: 'Apakah kamu sudah menyelesaikan pelajaran?',
      tr: 'Dersi bitirdin mi?',
      pl: 'Czy skończyłeś lekcję?',
      why: tri('В вопросе have выходит в начало, а finished остается V3.', 'У питанні have виходить на початок, а finished залишається V3.', 'Have va primero en la pregunta, y finished se queda en V3.'),
    },
    {
      en: 'Has she called you?',
      ru: 'Она тебе позвонила?',
      uk: 'Вона тобі подзвонила?',
      es: 'Ella te llamo?',
      'pt-BR': 'Ela ligou para você?',
      vi: 'Cô ấy đã gọi cho bạn chưa?',
      id: 'Apakah dia sudah meneleponmu?',
      tr: 'Seni aradı mı?',
      pl: 'Czy ona do ciebie zadzwoniła?',
      why: tri('С she нужен has. Called уже правильная форма после has.', 'З she потрібен has. Called уже правильна форма після has.', 'Con she necesitas has. Called es la forma correcta despues de has.'),
    },
    {
      en: "I haven't finished yet.",
      ru: 'Я еще не закончил.',
      uk: 'Я ще не закінчив.',
      es: 'Todavia no he terminado.',
      'pt-BR': 'Ainda não terminei.',
      vi: 'Tôi vẫn chưa hoàn thành.',
      id: 'Saya belum selesai.',
      tr: 'Henüz bitirmedim.',
      pl: 'Jeszcze nie skończyłem.',
      why: tri("Haven't finished yet дает смысл 'еще не закончил'.", "Haven't finished yet дає зміст 'ще не закінчив'.", "Haven't finished yet significa todavia no he terminado."),
    },
    {
      en: "She hasn't seen the message.",
      ru: 'Она не видела сообщение.',
      uk: 'Вона не бачила повідомлення.',
      es: 'Ella no ha visto el mensaje.',
      'pt-BR': 'Ela não viu a mensagem.',
      vi: 'Cô ấy chưa xem tin nhắn.',
      id: 'Dia belum melihat pesannya.',
      tr: 'Mesajı görmedi.',
      pl: 'Ona nie widziała wiadomości.',
      why: tri("С she берем hasn't. После hasn't нужен seen, не see и не saw.", "З she беремо hasn't. Після hasn't потрібен seen, не see і не saw.", "Con she usa hasn't. Despues de hasn't necesitas seen, no see ni saw."),
    },
    {
      en: 'Have you ever tried it?',
      ru: 'Ты когда-нибудь это пробовал?',
      uk: 'Ти коли-небудь це пробував?',
      es: 'Alguna vez lo has probado?',
      'pt-BR': 'Você já experimentou isso?',
      vi: 'Bạn đã từng thử nó chưa?',
      id: 'Apakah kamu pernah mencobanya?',
      tr: 'Bunu hiç denedin mi?',
      pl: 'Czy kiedykolwiek tego próbowałeś?',
      why: tri('Ever удобно спрашивает об опыте.', 'Ever зручно питає про досвід.', 'Ever pregunta naturalmente por experiencia.'),
    },
    {
      en: 'I have never tried it.',
      ru: 'Я никогда этого не пробовал.',
      uk: 'Я ніколи цього не пробував.',
      es: 'Nunca lo he probado.',
      'pt-BR': 'Nunca experimentei isso.',
      vi: 'Tôi chưa bao giờ thử nó.',
      id: 'Saya belum pernah mencobanya.',
      tr: 'Bunu hiç denemedim.',
      pl: 'Nigdy tego nie próbowałem.',
      why: tri("Never уже дает отрицательный смысл, поэтому не нужно haven't never.", "Never уже дає заперечний зміст, тому не потрібно haven't never.", "Never ya da sentido negativo, asi que no uses haven't never."),
    },
    {
      en: 'Have they left yet?',
      ru: 'Они уже ушли?',
      uk: 'Вони вже пішли?',
      es: 'Ya se fueron?',
      'pt-BR': 'Eles já foram embora?',
      vi: 'Họ đã rời đi chưa?',
      id: 'Apakah mereka sudah pergi?',
      tr: 'Onlar ayrıldı mı?',
      pl: 'Czy oni już wyszli?',
      why: tri('В нейтральном вопросе "уже?" yet часто стоит в конце.', 'У нейтральному питанні "вже?" yet часто стоїть у кінці.', 'En una pregunta neutral de ya?, yet suele ir al final.'),
    },
    {
      en: "They haven't left yet.",
      ru: 'Они еще не ушли.',
      uk: 'Вони ще не пішли.',
      es: 'Todavia no se han ido.',
      'pt-BR': 'Eles ainda não foram embora.',
      vi: 'Họ vẫn chưa rời đi.',
      id: 'Mereka belum pergi.',
      tr: 'Henüz ayrılmadılar.',
      pl: 'Oni jeszcze nie wyszli.',
      why: tri("Haven't left yet значит, что до текущего момента они еще не ушли.", "Haven't left yet означає, що до поточного моменту вони ще не пішли.", "Haven't left yet significa que hasta ahora todavia no se han ido."),
    },
  ],
  introBlocks: [
    {
      id: 'intro_problem',
      type: 'diagnosis',
      text: tri(
        'Похоже, ты строишь вопрос как обычное прошедшее время или как обычное утверждение. В этой теме так не работает: сначала ставим служебное слово.',
        'Схоже, ти будуєш питання як звичайний минулий час або як звичайне твердження. У цій темі так не працює: спочатку ставимо службове слово.',
        'Parece que construyes la pregunta como Past Simple o como una afirmacion: Did you finished? You have finished? Aqui la pregunta empieza con have o has.',
      ),
    },
    {
      id: 'intro_rule',
      type: 'rule',
      text: tri(
        'Схема простая: в вопросе служебное слово впереди, потом человек, потом третий вид глагола. В отрицании человек идет первым, потом отрицательная форма, потом третий вид.',
        'Схема проста: у питанні службове слово попереду, потім людина, потім третя форма дієслова. У запереченні людина йде першою, потім заперечна форма, потім третя форма.',
        "Pregunta: Have/Has + persona + V3? Negativa: persona + haven't/hasn't + V3.",
      ),
    },
    {
      id: 'intro_warning',
      type: 'warning',
      text: tri(
        'Главные ошибки тут три: ставить did, забывать has с he/she/it и брать обычный глагол после отрицания. Проверяй порядок вопроса и третий вид глагола.',
        'Головні помилки тут три: ставити did, забувати has з he/she/it і брати звичайне дієслово після заперечення. Перевіряй порядок питання і третю форму дієслова.',
        "Errores principales: Did you finished? She haven't seen. I haven't saw. Correcto: Have you finished? Has she seen? She hasn't seen. I haven't seen.",
      ),
    },
  ],
  steps: [
    qnStep({
      id: 'pp_qn_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'have_you_finished',
      sentence: '___ you finished the lesson?',
      translation: tri('Ты закончил урок?', 'Ти закінчив урок?', 'Have you finished the lesson?'),
      options: ['Have', 'Did', 'Do', 'Are'],
      correctAnswer: 'Have',
      correctFeedback: tri('Да. Вопрос Present Perfect начинается с Have: Have you finished?', 'Так. Питання Present Perfect починається з Have: Have you finished?', 'Yes. A Present Perfect question starts with Have: Have you finished?'),
      wrong: {
        Did: tri('Did здесь уводит в другое время. В этой теме вопрос начинается с Have: Have you finished?', 'Did тут веде в інший час. У цій темі питання починається з Have.', 'Did does not build Present Perfect. Use Have you finished.'),
        Do: tri('Do здесь не подходит. С finished нужен вопрос Have you finished?', 'Do тут не підходить. З finished потрібне питання Have you finished?', 'Do does not fit here. With finished, use Have you finished?'),
        Are: tri('Are здесь не строит нужный вопрос. Нужно Have you finished?', 'Are тут не будує потрібне питання. Потрібно Have you finished?', 'Are does not build this question. Use Have you finished?'),
      },
      focusWords: ['have you', 'finished'],
    }),
    qnStep({
      id: 'pp_qn_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'have_they_left',
      sentence: '___ they left yet?',
      translation: tri('Они уже ушли?', 'Вони вже пішли?', 'Have they left yet?'),
      options: ['Have', 'Has', 'Did', 'Are'],
      correctAnswer: 'Have',
      correctFeedback: tri('Верно. С they берем have: Have they left yet?', 'Правильно. З they беремо have: Have they left yet?', 'Correct. With they, use have: Have they left yet?'),
      wrong: {
        Has: tri('Has идет с he, she, it. С they нужен have.', 'Has іде з he, she, it. З they потрібен have.', 'Has goes with he, she, it. With they, use have.'),
        Did: tri('Did they left неверно. Здесь нужен вопрос Have they left yet?', 'Did they left неправильно. Тут потрібне питання Have they left yet?', 'Did they left is wrong. Use Have they left yet?'),
        Are: tri('Are they left не работает для этого смысла. Нужно Have they left yet?', 'Are they left не працює для цього змісту. Потрібно Have they left yet?', 'Are they left does not work for this meaning. Use Have they left yet?'),
      },
      focusWords: ['have they', 'left yet'],
    }),
    qnStep({
      id: 'pp_qn_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'question_order_have',
      sentence: 'Choose the natural question.',
      translation: tri('Выбери естественный вопрос: "Ты это сделал?"', 'Обери природне питання: "Ти це зробив?"', 'Choose the natural question: Have you done it?'),
      options: ['Have you done it?', 'You have done it?', 'Did you done it?', 'Do you have done it?'],
      correctAnswer: 'Have you done it?',
      correctFeedback: tri('Да. В вопросе have выходит в начало: Have you done it?', 'Так. У питанні have виходить на початок: Have you done it?', 'Yes. In the question, have comes first.'),
      wrong: {
        'You have done it?': tri('Это порядок обычной фразы. В нейтральном вопросе нужно Have you done it?', 'Це порядок звичайної фрази. У нейтральному питанні потрібно Have you done it?', 'This is statement order. In a neutral question, use Have you done it?'),
        'Did you done it?': tri('Did you done неверно. Для Present Perfect нужно Have you done.', 'Did you done неправильно. Для Present Perfect потрібно Have you done.', 'Did you done is wrong. Use Have you done.'),
        'Do you have done it?': tri('Do здесь лишний. Have само выходит в начало.', 'Do тут зайвий. Have саме виходить на початок.', 'Do is extra here. Have comes first by itself.'),
      },
      focusWords: ['have you', 'done'],
    }),
    qnStep({
      id: 'pp_qn_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'has_she_called',
      sentence: '___ she called you?',
      translation: tri('Она тебе позвонила?', 'Вона тобі подзвонила?', 'Has she called you?'),
      options: ['Has', 'Have', 'Did', 'Does'],
      correctAnswer: 'Has',
      correctFeedback: tri('Да. С she нужен has: Has she called you?', 'Так. З she потрібен has: Has she called you?', 'Yes. With she, use has: Has she called you?'),
      wrong: {
        Have: tri('С she нужен has, не Have. Правильно: Has she called you?', 'З she потрібен has, не Have. Правильно: Has she called you?', 'With she, use has, not Have.'),
        Did: tri('Did she called неверно. Для Present Perfect нужен вопрос Has she called?', 'Did she called неправильно. Для Present Perfect потрібне питання Has she called?', 'Did she called is wrong. Use Has she called?'),
        Does: tri('Does здесь не подходит. Нужно Has she called?', 'Does тут не підходить. Потрібно Has she called?', 'Does does not fit here. Use Has she called?'),
      },
      focusWords: ['has she', 'called'],
    }),
    qnStep({
      id: 'pp_qn_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'has_he_seen',
      sentence: 'Has he ___ the message?',
      translation: tri('Он видел сообщение?', 'Він бачив повідомлення?', 'Has he seen the message?'),
      options: ['seen', 'saw', 'see', 'seeing'],
      correctAnswer: 'seen',
      correctFeedback: tri('Да. После has нужен seen.', 'Так. Після has потрібен seen.', 'Yes. After has, use seen.'),
      wrong: {
        saw: tri('Saw не ставим после has. Нужен seen.', 'Saw не ставимо після has. Потрібен seen.', 'Do not use saw after has. Use seen.'),
        see: tri('See слишком обычное после has. Нужен seen.', 'See занадто звичайне після has. Потрібен seen.', 'See is too plain after has. Use seen.'),
        seeing: tri('Seeing здесь не подходит. Нужно Has he seen?', 'Seeing тут не підходить. Потрібно Has he seen?', 'Seeing does not fit here. Use Has he seen?'),
      },
      focusWords: ['has', 'seen'],
    }),
    qnStep({
      id: 'pp_qn_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'has_it_started',
      sentence: '___ it started?',
      translation: tri('Это началось?', 'Це почалося?', 'Has it started?'),
      options: ['Has', 'Have', 'Did', 'Is'],
      correctAnswer: 'Has',
      correctFeedback: tri('Да. С it нужен has: Has it started?', 'Так. З it потрібен has: Has it started?', 'Yes. With it, use has: Has it started?'),
      wrong: {
        Have: tri('С it нужен has, не have.', 'З it потрібен has, не have.', 'With it, use has, not have.'),
        Did: tri('Did здесь не подходит: это не обычное прошедшее время. Нужен вопрос через Has.', 'Did тут не підходить: це не звичайний минулий час. Потрібне питання через Has.', 'Did it started is wrong. Use Has it started?'),
        Is: tri('Is строит другую грамматику. Для этого смысла нужен вопрос через Has.', 'Is будує іншу граматику. Для цього сенсу потрібне питання через Has.', 'Is it started does not build Present Perfect. Use Has it started?'),
      },
      focusWords: ['has it', 'started'],
    }),
    qnStep({
      id: 'pp_qn_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'haven_t_finished',
      sentence: 'I ___ finished yet.',
      translation: tri('Я еще не закончил.', 'Я ще не закінчив.', "I haven't finished yet."),
      options: ["haven't", "hasn't", "didn't", "don't"],
      correctAnswer: "haven't",
      correctFeedback: tri("Да. С I берем haven't, а слово действия остается в третьем виде.", "Так. З I беремо haven't, а слово дії залишається в третій формі.", "Yes. With I, use haven't: I haven't finished yet."),
      wrong: {
        "hasn't": tri("Hasn't идет с he, she, it. С I нужно haven't.", "Hasn't іде з he, she, it. З I потрібно haven't.", "Hasn't goes with he, she, it. With I, use haven't."),
        "didn't": tri("Didn't здесь не нужен: отрицание строится через haven't и третий вид глагола.", "Didn't тут не потрібен: заперечення будується через haven't і третю форму дієслова.", "Didn't finished is wrong. Use haven't finished."),
        "don't": tri("Don't не работает с этим временем. Нужна отрицательная форма через haven't.", "Don't не працює з цим часом. Потрібна заперечна форма через haven't.", "Don't finished is wrong. Use haven't finished yet."),
      },
      focusWords: ["haven't", 'finished yet'],
    }),
    qnStep({
      id: 'pp_qn_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'hasn_t_called',
      sentence: 'She ___ called me.',
      translation: tri('Она мне не позвонила.', 'Вона мені не подзвонила.', "She hasn't called me."),
      options: ["hasn't", "haven't", "didn't", "doesn't"],
      correctAnswer: "hasn't",
      correctFeedback: tri("Да. С she берем hasn't, потому что это he/she/it группа.", "Так. З she беремо hasn't, бо це група he/she/it.", "Yes. With she, use hasn't: She hasn't called me."),
      wrong: {
        "haven't": tri("С she нужно hasn't, не haven't.", "З she потрібно hasn't, не haven't.", "With she, use hasn't, not haven't."),
        "didn't": tri("Didn't called неверно. Здесь нужно hasn't called.", "Didn't called неправильно. Тут потрібно hasn't called.", "Didn't called is wrong. Use hasn't called."),
        "doesn't": tri("Doesn't called неверно. Здесь нужно hasn't called.", "Doesn't called неправильно. Тут потрібно hasn't called.", "Doesn't called is wrong. Use hasn't called."),
      },
      focusWords: ["hasn't", 'called'],
    }),
    qnStep({
      id: 'pp_qn_contrast_006',
      order: 9,
      difficulty: 'contrast',
      targetSkill: 'haven_t_seen',
      sentence: "I haven't ___ it.",
      translation: tri('Я этого не видел.', 'Я цього не бачив.', "I haven't seen it."),
      options: ['seen', 'saw', 'see', 'seeing'],
      correctAnswer: 'seen',
      correctFeedback: tri("Да. После haven't нужен seen.", "Так. Після haven't потрібен seen.", "Yes. After haven't, use seen."),
      wrong: {
        saw: tri("Haven't saw неверно. После haven't нужен seen.", "Haven't saw неправильно. Після haven't потрібен seen.", "Haven't saw is wrong. Use seen."),
        see: tri("Haven't see неверно. После haven't нужен seen.", "Haven't see неправильно. Після haven't потрібен seen.", "Haven't see is wrong. Use seen."),
        seeing: tri("Haven't seeing неверно. Нужно haven't seen.", "Haven't seeing неправильно. Потрібно haven't seen.", "Haven't seeing is wrong. Use haven't seen."),
      },
      focusWords: ["haven't", 'seen'],
    }),
    qnStep({
      id: 'pp_qn_mixed_001',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'yet_question',
      sentence: 'Have you finished ___?',
      translation: tri('Ты уже закончил?', 'Ти вже закінчив?', 'Have you finished yet?'),
      options: ['yet', 'already', 'never', 'ever'],
      correctAnswer: 'yet',
      correctFeedback: tri('Да. В нейтральном вопросе "уже?" часто ставим yet в конце.', 'Так. У нейтральному питанні "вже?" часто ставимо yet у кінці.', 'Yes. In a neutral already? question, put yet at the end.'),
      wrong: {
        already: tri('Already возможно с оттенком удивления, но базовый нейтральный вопрос: Have you finished yet?', 'Already можливе з відтінком здивування, але базове нейтральне питання: Have you finished yet?', 'Already can sound surprised. The neutral question is Have you finished yet?'),
        never: tri('Never значит "никогда". Здесь вопрос "уже?" = yet.', 'Never означає "ніколи". Тут питання "вже?" = yet.', 'Never means never. Here use yet.'),
        ever: tri('Ever спрашивает об опыте. Здесь вопрос про завершение: yet.', 'Ever питає про досвід. Тут питання про завершення: yet.', 'Ever asks about experience. Here use yet.'),
      },
      focusWords: ['yet', 'question'],
    }),
    qnStep({
      id: 'pp_qn_mixed_002',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'ever_question',
      sentence: 'Have you ___ been there?',
      translation: tri('Ты когда-нибудь там был?', 'Ти коли-небудь там був?', 'Have you ever been there?'),
      options: ['ever', 'yet', 'already', 'never'],
      correctAnswer: 'ever',
      correctFeedback: tri('Верно. Ever спрашивает об опыте: Have you ever been there?', 'Правильно. Ever питає про досвід: Have you ever been there?', 'Correct. Ever asks about experience: Have you ever been there?'),
      wrong: {
        yet: tri('Yet спрашивает "уже?" о завершении. Для опыта "когда-нибудь" нужен ever.', 'Yet питає "вже?" про завершення. Для досвіду "коли-небудь" потрібен ever.', 'Yet asks already? For experience, use ever.'),
        already: tri('Already не передает нейтральное "когда-нибудь". Нужен ever.', 'Already не передає нейтральне "коли-небудь". Потрібен ever.', 'Already does not mean neutral ever. Use ever.'),
        never: tri('Never значит "никогда", а вопрос "когда-нибудь?" = ever.', 'Never означає "ніколи", а питання "коли-небудь?" = ever.', 'Never means never. The question needs ever.'),
      },
      focusWords: ['ever', 'been'],
    }),
    qnStep({
      id: 'pp_qn_mixed_003',
      order: 12,
      difficulty: 'mixed',
      targetSkill: 'never_no_double_negative',
      sentence: 'Choose the natural sentence.',
      translation: tri('Я никогда там не был.', 'Я ніколи там не був.', 'I have never been there.'),
      options: ['I have never been there.', "I haven't never been there.", "I didn't never been there.", 'I have ever not been there.'],
      correctAnswer: 'I have never been there.',
      correctFeedback: tri("Да. Never уже делает смысл отрицательным. Не нужен haven't never.", "Так. Never уже робить зміст заперечним. Не потрібен haven't never.", "Yes. Never already makes the meaning negative. Do not use haven't never."),
      wrong: {
        "I haven't never been there.": tri("Haven't never - двойное отрицание для этого тренинга. Нужна фраза I have never been there.", "Haven't never - подвійне заперечення для цього тренінгу. Потрібна фраза I have never been there.", "Haven't never is a double negative here. Use I have never been there."),
        "I didn't never been there.": tri('Did never been неверно. Для опыта нужна фраза have never been.', 'Did never been неправильно. Для досвіду потрібна фраза have never been.', 'Did never been is wrong. Use have never been.'),
        'I have ever not been there.': tri('Для "никогда не был" нужна простая фраза have never been.', 'Для "ніколи не був" потрібна проста фраза have never been.', 'For never been, use have never been.'),
      },
      focusWords: ['have never', 'been'],
    }),
    qnStep({
      id: 'pp_qn_mixed_004',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_question_negative_pair',
      sentence: 'Choose the natural pair.',
      translation: tri('Ты закончил? / я еще не закончил.', 'Ти закінчив? / я ще не закінчив.', "Have you finished? / I haven't finished yet."),
      options: [
        "Have you finished? / I haven't finished yet.",
        "Did you finished? / I didn't finished yet.",
        "You have finished? / I haven't finish yet.",
        "Have you finish? / I didn't finish yet.",
      ],
      correctAnswer: "Have you finished? / I haven't finished yet.",
      correctFeedback: tri("Да. Вопрос: Have you finished? Отрицание: I haven't finished yet.", "Так. Питання: Have you finished? Заперечення: I haven't finished yet.", "Yes. Question: Have you finished? Negative: I haven't finished yet."),
      wrong: {
        "Did you finished? / I didn't finished yet.": tri("Обе части ушли в обычное прошедшее время. Здесь нужна пара: вопрос через Have и отрицание через haven't.", "Обидві частини пішли у звичайний минулий час. Тут потрібна пара: питання через Have і заперечення через haven't.", "Did you finished and didn't finished are wrong. Use Have you finished / haven't finished yet."),
        "You have finished? / I haven't finish yet.": tri("Вопрос должен начинаться с Have. После haven't нужен finished, не finish.", "Питання має починатися з Have. Після haven't потрібен finished, не finish.", "The question should start with Have. After haven't, use finished."),
        "Have you finish? / I didn't finish yet.": tri("После have нужен finished. Для 'еще не' здесь лучше haven't finished yet.", "Після have потрібен finished. Для 'ще не' тут краще haven't finished yet.", "After have, use finished. For not yet, use haven't finished yet."),
      },
      focusWords: ['have you', "haven't", 'yet'],
    }),
    qnStep({
      id: 'pp_qn_mixed_005',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_has_question_negative',
      sentence: 'Choose the natural pair.',
      translation: tri('Она звонила? / она еще не звонила.', 'Вона дзвонила? / вона ще не дзвонила.', "Has she called? / She hasn't called yet."),
      options: [
        "Has she called? / She hasn't called yet.",
        "Have she called? / She haven't called yet.",
        "Did she called? / She didn't called yet.",
        "Has she call? / She hasn't call yet.",
      ],
      correctAnswer: "Has she called? / She hasn't called yet.",
      correctFeedback: tri("Да. С she: has / hasn't. После них called.", "Так. З she: has / hasn't. Після них called.", "Yes. With she: has / hasn't. Then called."),
      wrong: {
        "Have she called? / She haven't called yet.": tri("С she нужны has и hasn't, не have и haven't.", "З she потрібні has і hasn't, не have і haven't.", "With she, use has and hasn't, not have and haven't."),
        "Did she called? / She didn't called yet.": tri("Это опять обычное прошедшее время. Здесь нужна пара через has и hasn't.", "Це знову звичайний минулий час. Тут потрібна пара через has і hasn't.", "Did she called and didn't called are wrong. Use Has she called / hasn't called."),
        "Has she call? / She hasn't call yet.": tri("После has и hasn't нужен called, не call.", "Після has і hasn't потрібен called, не call.", "After has and hasn't, use called, not call."),
      },
      focusWords: ['has she', "hasn't", 'called'],
    }),
    qnStep({
      id: 'pp_qn_mixed_006',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_sentence_correction',
      sentence: 'Choose the natural sentence.',
      translation: tri('Ты когда-нибудь видел это? Я еще этого не видел.', 'Ти коли-небудь бачив це? Я ще цього не бачив.', "Have you ever seen it? I haven't seen it yet."),
      options: [
        "Have you ever seen it? I haven't seen it yet.",
        "Did you ever saw it? I didn't saw it yet.",
        "Have you ever saw it? I haven't see it yet.",
        "You have ever seen it? I haven't seen it already.",
      ],
      correctAnswer: "Have you ever seen it? I haven't seen it yet.",
      correctFeedback: tri("Да. Have you ever seen = вопрос об опыте. Haven't seen yet = еще не видел.", "Так. Have you ever seen = питання про досвід. Haven't seen yet = ще не бачив.", "Yes. Have you ever seen asks about experience. Haven't seen yet means not seen yet."),
      wrong: {
        "Did you ever saw it? I didn't saw it yet.": tri('Did you ever saw и didn’t saw неверны. Для опыта и yet здесь нужен Present Perfect.', 'Did you ever saw і didn’t saw неправильні. Для досвіду і yet тут потрібен Present Perfect.', 'Did you ever saw and didn’t saw are wrong. Use Present Perfect here.'),
        "Have you ever saw it? I haven't see it yet.": tri("После have и haven't нужен seen, не saw и не see.", "Після have і haven't потрібен seen, не saw і не see.", "After have and haven't, use seen, not saw or see."),
        "You have ever seen it? I haven't seen it already.": tri('Вопрос должен начинаться с Have. В отрицании "еще не" нужен yet, не already.', 'Питання має починатися з Have. У запереченні "ще не" потрібен yet, не already.', 'The question should start with Have. In a not yet negative, use yet, not already.'),
      },
      focusWords: ['have you ever', "haven't seen", 'yet'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'question_order_have_has_error',
      'did_instead_of_have_error',
      'have_has_choice_error',
      'negative_have_has_choice_error',
      'wrong_v3_error',
      'haven_t_plus_plain_word_error',
      'haven_t_plus_past_simple_error',
      'yet_position_error',
      'ever_question_error',
      'double_negative_never_error',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri('Показываем have/has и V3.', 'Показуємо have/has і V3.', 'Mostramos have/has y V3.'),
    depth2: tri('Проще: вопрос начинается с have/has, отрицание строится через haven’t/hasn’t.', 'Простіше: питання починається з have/has, заперечення будується через haven’t/hasn’t.', "Mas simple: la pregunta empieza con have/has; la negativa usa haven't/hasn't."),
    depth3: tri("Даем пару: вопрос через Have и отрицание через hasn't.", "Даємо пару: питання через Have і заперечення через hasn't.", "Usa el par: Have you done? / She hasn't done."),
    depth4: tri("Почти подсказка: прямо указываем have/has/haven't/hasn't и нужный V3.", "Майже підказка: прямо вказуємо have/has/haven't/hasn't і потрібний V3.", "Casi una pista: senala directamente have/has/haven't/hasn't y el V3 correcto."),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri(
        'Стоп. В вопросе служебное слово выходит вперед. В отрицании человек идет первым, потом короткая отрицательная форма. Did здесь не нужен. После служебного слова держим третий вид глагола.',
        'Стоп. У питанні службове слово виходить уперед. У запереченні людина йде першою, потім коротка заперечна форма. Did тут не потрібен. Після службового слова тримаємо третю форму дієслова.',
        "Alto. Pregunta: Have/Has + persona + V3? Negativa: persona + haven't/hasn't + V3. Aqui no uses did. Despues de have/has/haven't/hasn't usa V3.",
      ),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_question_negative_hint_then_retry',
      card: tri(
        'Система подсветит, это вопрос или отрицание, и напомнит have/has. Ответ она не выбирает.',
        'Система підсвітить, це питання чи заперечення, і нагадає have/has. Відповідь вона не обирає.',
        'El sistema resalta si es pregunta o negativa y recuerda have/has. No elige la respuesta.',
      ),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri(
        "Режим подсказки: сначала вопрос или отрицание. Потом have/has/haven't/hasn't. Потом V3.",
        "Режим підказки: спочатку питання чи заперечення. Потім have/has/haven't/hasn't. Потім V3.",
        "Modo guiado: primero pregunta o negativa. Luego have/has/haven't/hasn't. Luego V3.",
      ),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      {
        id: 'guided_pp_qn_001',
        prompt: tri('В вопросе Present Perfect have стоит в начале или после you?', 'У питанні Present Perfect have стоїть на початку чи після you?', 'En una pregunta de Present Perfect, have va primero o despues de you?'),
        options: ['в начале', 'после you'],
        correctIndex: 0,
        thenReturnToExerciseId: 'pp_qn_easy_001',
      },
      {
        id: 'guided_pp_qn_002',
        prompt: tri('С she в Present Perfect нужен has или have?', 'З she у Present Perfect потрібен has чи have?', 'Con she, necesitas has o have?'),
        options: ['has', 'have'],
        correctIndex: 0,
        thenReturnToExerciseId: 'pp_qn_contrast_001',
      },
      {
        id: 'guided_pp_qn_003',
        prompt: tri("После haven't правильно seen или see?", "Після haven't правильно seen чи see?", "Despues de haven't, es correcto seen o see?"),
        options: ['seen', 'see'],
        correctIndex: 0,
        thenReturnToExerciseId: 'pp_qn_contrast_006',
      },
      {
        id: 'guided_pp_qn_004',
        prompt: tri('В вопросе об опыте "когда-нибудь" обычно ever или yet?', 'У питанні про досвід "коли-небудь" зазвичай ever чи yet?', 'En una pregunta de experiencia, se usa normalmente ever o yet?'),
        options: ['ever', 'yet'],
        correctIndex: 0,
        thenReturnToExerciseId: 'pp_qn_mixed_002',
      },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'verb',
    microDiagnosisId: 'present_perfect_questions_negatives',
    diagnosisLabel: tri('Present Perfect: вопросы и отрицания', 'Present Perfect: питання і заперечення', 'Present Perfect: preguntas y negativas'),
    contrastSet: CONTRAST,
    difficultyLevel: 2,
    focusWords: ['have you', 'has she', "haven't", "hasn't", 'seen', 'finished', 'yet', 'ever'],
    focusPatterns: [
      'have_you_finished',
      'have_they_left',
      'question_order_have',
      'has_she_called',
      'has_he_seen',
      'has_it_started',
      'haven_t_finished',
      'hasn_t_called',
      'haven_t_seen',
      'yet_question',
      'ever_question',
      'never_no_double_negative',
      'mixed_question_negative_pair',
      'mixed_has_question_negative',
      'mixed_sentence_correction',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 3,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_present_perfect_questions_negatives_start',
    answer: 'diagnosis_training_present_perfect_questions_negatives_answer',
    mastery: 'diagnosis_training_present_perfect_questions_negatives_mastery',
    recovery: 'diagnosis_training_present_perfect_questions_negatives_recovery',
    onStart: 'diagnosis_training_started',
    onCorrect: 'diagnosis_training_answer_correct',
    onWrong: 'diagnosis_training_answer_wrong',
    onDepthIncrease: 'diagnosis_training_feedback_depth_increased',
    onGuidedMode: 'diagnosis_training_guided_mode_started',
    onMastery: 'diagnosis_training_mastered',
    onSmartTrainerOpen: 'diagnosis_training_smart_trainer_opened',
    payload: {
      category: 'verb',
      microDiagnosisId: 'present_perfect_questions_negatives',
      contrastSet: ['have/has question', "haven't/hasn't negative", 'yet', 'ever', 'never'],
      logExactToken: true,
      logMistakeType: true,
      logExerciseId: true,
      logAttemptCount: true,
      logFeedbackDepth: true,
      logHaveHasForm: true,
      logPastParticiple: true,
      logSentencePolarity: true,
    },
  },
  routing: {
    diagnosisTrainerRoute: '/problem_coach?category=verb&microDiagnosisId=present_perfect_questions_negatives',
  },
  qualityChecklist: {
    hasStableId: true,
    hasCategory: true,
    hasMultilingualTitle: true,
    hasPlainDiagnosisText: true,
    hasMentalModel: true,
    hasContrastSet: true,
    hasAtLeastSixExamples: true,
    hasAtLeastTwelveExercises: true,
    hasEasyContrastMixedStructure: true,
    hasDistractorSpecificFeedback: true,
    hasRetryFeedbackLevels: true,
    hasGuidedModeForRepeatedMistakes: true,
    hasMasteryRules: true,
    hasSmartTrainerConfig: true,
    hasAnalyticsPayload: true,
    hasFallbackRoute: true,
  },
};
