import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

const tri = (ru: string, uk: string, es: string): TriText => ({ ru, uk, es });

const CONTRAST = ['am + verb-ing', 'is + verb-ing', 'are + verb-ing', 'now', 'right now', 'at the moment', 'present simple'];

const PC_MODEL = tri(
  'Если действие происходит прямо сейчас или вокруг текущего момента, английскому нужны две части: am/is/are и слово с -ing. Не I working, а I am working. Не She study now, а She is studying now.',
  'Якщо дія відбувається прямо зараз або навколо поточного моменту, англійській потрібні дві частини: am/is/are і слово з -ing. Не I working, а I am working. Не She study now, а She is studying now.',
  'For an action happening now, English needs two parts: am/is/are and an -ing word.',
);

function retry(answer: string): [TriText, TriText, TriText, TriText] {
  return [
    tri('Сначала выбери am, is или are.', 'Спочатку обери am, is або are.', 'First choose am, is, or are.'),
    tri('Потом проверь, что действие стоит с -ing.', 'Потім перевір, що дія стоїть з -ing.', 'Then check the -ing form.'),
    tri('Держи логику: я беру am, один человек берет is, несколько людей или you берут are.', 'Тримай логіку: я беру am, одна людина бере is, кілька людей або you беруть are.', 'Use the pairs: I am working / She is working / They are working.'),
    tri('Теперь выбери вариант с полной связкой.', 'Тепер обери варіант із повною звʼязкою.', `Answer: ${answer}`),
  ];
}

function defaultWrong(correct: string): TriText {
  return tri(
    `Почти. Здесь нужна полная связка: ${correct}`,
    `Майже. Тут потрібна повна зв'язка: ${correct}`,
    `Almost. Use the full pattern: ${correct}`,
  );
}

function pcStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  sentence: string;
  translation: TriText;
  options: string[];
  correctAnswer: string;
  correctFeedback: TriText;
  wrong?: Record<string, TriText>;
  fallbackExplanation: TriText;
  focusWords: string[];
}): DiagnosisTrainingStep {
  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    translation: input.translation,
    teachingText: PC_MODEL,
    explanationBlock: PC_MODEL,
    microTask: tri(
      'Выбери форму для действия, которое происходит сейчас.',
      'Обери форму для дії, яка відбувається зараз.',
      'Choose the form for an action happening now.',
    ),
    sentence: input.sentence,
    answerOptions: input.options.map((text) => ({ id: text, text })),
    correctAnswerId: input.correctAnswer,
    correctIndex: input.options.findIndex((option) => option === input.correctAnswer),
    correctFeedback: input.correctFeedback,
    wrongFeedbackByOption: Object.fromEntries(
      input.options
        .filter((option) => option !== input.correctAnswer)
        .map((option) => [option, input.wrong?.[option] ?? defaultWrong(input.correctAnswer)]),
    ),
    retryFeedback: retry(input.correctAnswer),
    fallbackExplanation: input.fallbackExplanation,
    focusWords: input.focusWords,
  };
}

export const VERB_PRESENT_CONTINUOUS_BASIC_TRAINING: DiagnosisTraining = {
  id: 'verb_present_continuous_basic',
  category: 'verb',
  version: '1.0.0',
  status: 'active',
  priority: 23,
  supportedLocales: ['ru', 'uk', 'es'],
  title: tri(
    'I am working: действие сейчас',
    'I am working: дія зараз',
    'I am working: action happening now',
  ),
  shortTitle: tri('am/is/are + -ing', 'am/is/are + -ing', 'am/is/are + -ing'),
  shortDiagnosis: tri(
    'Ты видишь -ing, но пропускаешь am/is/are. Или ставишь am/is/are, но забываешь -ing.',
    'Ти бачиш -ing, але пропускаєш am/is/are. Або ставиш am/is/are, але забуваєш -ing.',
    'You skip am/is/are before -ing, or forget -ing after am/is/are.',
  ),
  diagnosisText: tri(
    'Для действия прямо сейчас английский не говорит I working. Ему нужна связка из двух частей: I am working. То же самое: She is studying, They are waiting. Если убрать одну часть, фраза сразу звучит сломанно.',
    'Для дії прямо зараз англійська не каже I working. Їй потрібна звʼязка з двох частин: I am working. Так само: She is studying, They are waiting. Якщо прибрати одну частину, фраза одразу звучить зламано.',
    'For an action right now, English uses two parts: I am working, She is studying, They are waiting.',
  ),
  mentalModel: tri(
    'Сначала выбери маленькую опору: I am, she is, they are. Потом добавь действие с -ing: working, studying, waiting. Получается I am working now, She is studying at the moment, They are waiting outside.',
    'Спочатку обери маленьку опору: I am, she is, they are. Потім додай дію з -ing: working, studying, waiting. Виходить I am working now, She is studying at the moment, They are waiting outside.',
    'Choose the be form, then add the -ing action.',
  ),
  contrastSet: CONTRAST,
  coreRule: tri(
    'Для действия сейчас нужны две части. С I берем am. С he/she/it берем is. С you/we/they берем are. В отрицании добавляем not после этой маленькой опоры. В вопросе опора выходит вперед.',
    'Для дії зараз потрібні дві частини. З I беремо am. З he/she/it беремо is. З you/we/they беремо are. У запереченні додаємо not після цієї маленької опори. У питанні опора виходить уперед.',
    'I am working. He/she/it is working. You/we/they are working. Negative: I am not working. Question: Are you working?',
  ),
  whatUserMustLearn: {
    ru: [
      'Для действия сейчас нужна связка am/is/are + -ing.',
      'С I используем am: I am working.',
      'С he/she/it используем is: She is studying.',
      'С you/we/they используем are: They are waiting.',
      'Не говорим I working: перед -ing нужна маленькая опора.',
      'Не говорим I am work: после am/is/are нужно действие с -ing.',
      'Now, right now, at the moment часто подсказывают действие сейчас.',
      'Every day обычно говорит о привычке, там чаще нужен обычный Present Simple.',
    ],
    uk: [
      'Для дії зараз потрібна звʼязка am/is/are + -ing.',
      'З I використовуємо am: I am working.',
      'З he/she/it використовуємо is: She is studying.',
      'З you/we/they використовуємо are: They are waiting.',
      'Не кажемо I working: перед -ing потрібна маленька опора.',
      'Не кажемо I am work: після am/is/are потрібна дія з -ing.',
      'Now, right now, at the moment часто підказують дію зараз.',
      'Every day зазвичай говорить про звичку, там частіше потрібен звичайний Present Simple.',
    ],
    es: [
      'For action now, use am/is/are + -ing.',
      'I uses am: I am working.',
      'He/she/it uses is: She is studying.',
      'You/we/they uses are: They are waiting.',
      'Do not say I working.',
      'Do not say I am work.',
      'Now, right now, and at the moment often point to action now.',
      'Every day usually points to Present Simple.',
    ],
  },
  examples: [
    { en: 'I am working now.', ru: 'Я сейчас работаю.', uk: 'Я зараз працюю.', es: 'Estoy trabajando ahora.', why: tri('I идет с am, а work становится working.', 'I йде з am, а work стає working.', 'I uses am; work becomes working.') },
    { en: 'She is studying at the moment.', ru: 'Она сейчас учится.', uk: 'Вона зараз вчиться.', es: 'Ella esta estudiando ahora.', why: tri('She идет с is, а at the moment показывает действие сейчас.', 'She йде з is, а at the moment показує дію зараз.', 'She uses is; at the moment points to now.') },
    { en: 'They are waiting outside.', ru: 'Они ждут снаружи.', uk: 'Вони чекають зовні.', es: 'Estan esperando afuera.', why: tri('They идет с are.', 'They йде з are.', 'They uses are.') },
    { en: 'He is talking on the phone.', ru: 'Он говорит по телефону.', uk: 'Він розмовляє телефоном.', es: 'Esta hablando por telefono.', why: tri('He идет с is, потом talking.', 'He йде з is, потім talking.', 'He uses is, then talking.') },
    { en: 'We are having dinner now.', ru: 'Мы сейчас ужинаем.', uk: 'Ми зараз вечеряємо.', es: 'Estamos cenando ahora.', why: tri('We идет с are, now показывает процесс сейчас.', 'We йде з are, now показує процес зараз.', 'We uses are; now points to a current action.') },
    { en: 'The baby is sleeping.', ru: 'Ребенок спит.', uk: 'Дитина спить.', es: 'El bebe esta durmiendo.', why: tri('The baby значит один ребенок, поэтому is sleeping.', 'The baby означає одну дитину, тому is sleeping.', 'One baby: is sleeping.') },
    { en: 'You are making progress.', ru: 'У тебя есть прогресс.', uk: 'У тебе є прогрес.', es: 'Estas progresando.', why: tri('You идет с are.', 'You йде з are.', 'You uses are.') },
    { en: 'I am not working today.', ru: 'Я сегодня не работаю.', uk: 'Я сьогодні не працюю.', es: 'Hoy no estoy trabajando.', why: tri('В отрицании not идет после am: am not working.', 'У запереченні not іде після am: am not working.', 'In negatives, not goes after am/is/are.') },
  ],
  introBlocks: [
    {
      id: 'intro_problem',
      type: 'diagnosis',
      text: tri(
        'Один -ing в конце слова не спасает фразу. Для действия сейчас английскому нужна маленькая опора перед ним: am, is или are.',
        'Один -ing у кінці слова не рятує фразу. Для дії зараз англійській потрібна маленька опора перед ним: am, is або are.',
        'An -ing ending is not enough. You also need am, is, or are.',
      ),
    },
    {
      id: 'intro_rule',
      type: 'rule',
      text: tri(
        'Три готовые пары по смыслу: я сейчас делаю, она сейчас делает, они сейчас делают. Меняется маленькая опора перед действием.',
        'Три готові пари за сенсом: я зараз роблю, вона зараз робить, вони зараз роблять. Змінюється маленька опора перед дією.',
        'Three pairs: I am working. She is working. They are working.',
      ),
    },
    {
      id: 'intro_warning',
      type: 'warning',
      text: tri(
        'Две самые липкие ошибки: I working и I am work. В первой не хватает am. Во второй не хватает -ing.',
        'Дві найлипкіші помилки: I working і I am work. У першій бракує am. У другій бракує -ing.',
        'Two sticky mistakes: I working and I am work.',
      ),
    },
  ],
  steps: [
    pcStep({
      id: 'pc_basic_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'i_am_ing',
      sentence: 'I ___ working now.',
      translation: tri('Я сейчас работаю.', 'Я зараз працюю.', 'Estoy trabajando ahora.'),
      options: ['am', 'is', 'are', 'do'],
      correctAnswer: 'am',
      correctFeedback: tri('Да. С I нужна форма am: I am working.', 'Так. З I потрібна форма am: I am working.', 'Yes. I uses am: I am working.'),
      wrong: {
        is: tri('Is идет с he/she/it. С I нужна форма am.', 'Is йде з he/she/it. З I потрібна форма am.', 'Is goes with he/she/it. I uses am.'),
        are: tri('Are идет с you/we/they. С I нужна форма am.', 'Are йде з you/we/they. З I потрібна форма am.', 'Are goes with you/we/they. I uses am.'),
        do: tri('Do не собирает действие с -ing. Здесь нужно am working.', 'Do не збирає дію з -ing. Тут потрібно am working.', 'Do does not build this -ing form. Use am working.'),
      },
      fallbackExplanation: tri('I всегда идет с am: I am working.', 'I завжди йде з am: I am working.', 'I uses am: I am working.'),
      focusWords: ['am', 'working'],
    }),
    pcStep({
      id: 'pc_basic_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'she_is_ing',
      sentence: 'She ___ studying at the moment.',
      translation: tri('Она сейчас учится.', 'Вона зараз вчиться.', 'Ella esta estudiando ahora.'),
      options: ['am', 'is', 'are', 'does'],
      correctAnswer: 'is',
      correctFeedback: tri('Да. She идет с is: She is studying.', 'Так. She йде з is: She is studying.', 'Yes. She uses is: She is studying.'),
      wrong: {
        am: tri('Am идет только с I. С she нужна форма is.', 'Am йде тільки з I. З she потрібна форма is.', 'Am goes only with I. She uses is.'),
        are: tri('Are идет с you/we/they. С she нужна форма is.', 'Are йде з you/we/they. З she потрібна форма is.', 'Are goes with you/we/they. She uses is.'),
        does: tri('Does не ставим перед studying. Здесь нужно is studying.', 'Does не ставимо перед studying. Тут потрібно is studying.', 'Does does not go before studying. Use is studying.'),
      },
      fallbackExplanation: tri('She = is. Поэтому She is studying.', 'She = is. Тому She is studying.', 'She uses is.'),
      focusWords: ['is', 'studying'],
    }),
    pcStep({
      id: 'pc_basic_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'they_are_ing',
      sentence: 'They ___ waiting outside.',
      translation: tri('Они ждут снаружи.', 'Вони чекають зовні.', 'Estan esperando afuera.'),
      options: ['am', 'is', 'are', 'do'],
      correctAnswer: 'are',
      correctFeedback: tri('Да. They идет с are: They are waiting.', 'Так. They йде з are: They are waiting.', 'Yes. They uses are: They are waiting.'),
      wrong: {
        am: tri('Am идет только с I. С they нужна форма are.', 'Am йде тільки з I. З they потрібна форма are.', 'Am goes only with I. They uses are.'),
        is: tri('Is идет с he/she/it. С they нужна форма are.', 'Is йде з he/she/it. З they потрібна форма are.', 'Is goes with he/she/it. They uses are.'),
        do: tri('Do не ставим перед waiting в этой фразе. Нужно are waiting.', 'Do не ставимо перед waiting у цій фразі. Потрібно are waiting.', 'Use are waiting.'),
      },
      fallbackExplanation: tri('They = are. Поэтому They are waiting.', 'They = are. Тому They are waiting.', 'They uses are.'),
      focusWords: ['are', 'waiting'],
    }),
    pcStep({
      id: 'pc_basic_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'he_is_ing',
      sentence: 'He ___ talking on the phone.',
      translation: tri('Он говорит по телефону.', 'Він розмовляє телефоном.', 'Esta hablando por telefono.'),
      options: ['am', 'is', 'are', 'does'],
      correctAnswer: 'is',
      correctFeedback: tri('Да. He идет с is: He is talking.', 'Так. He йде з is: He is talking.', 'Yes. He uses is: He is talking.'),
      wrong: {
        am: tri('Am идет только с I. С he нужна форма is.', 'Am йде тільки з I. З he потрібна форма is.', 'He uses is.'),
        are: tri('Are идет с you/we/they. С he нужна форма is.', 'Are йде з you/we/they. З he потрібна форма is.', 'He uses is.'),
        does: tri('Does не ставим перед talking. Нужно is talking.', 'Does не ставимо перед talking. Потрібно is talking.', 'Use is talking.'),
      },
      fallbackExplanation: tri('He = is. Потом talking.', 'He = is. Потім talking.', 'He uses is, then talking.'),
      focusWords: ['is', 'talking'],
    }),
    pcStep({
      id: 'pc_basic_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'we_are_ing',
      sentence: 'We ___ having dinner now.',
      translation: tri('Мы сейчас ужинаем.', 'Ми зараз вечеряємо.', 'Estamos cenando ahora.'),
      options: ['am', 'is', 'are', 'do'],
      correctAnswer: 'are',
      correctFeedback: tri('Да. We идет с are: We are having dinner.', 'Так. We йде з are: We are having dinner.', 'Yes. We uses are.'),
      wrong: {
        am: tri('Am идет только с I. С we нужна форма are.', 'Am йде тільки з I. З we потрібна форма are.', 'We uses are.'),
        is: tri('Is идет с he/she/it. С we нужна форма are.', 'Is йде з he/she/it. З we потрібна форма are.', 'We uses are.'),
        do: tri('Do не собирает having dinner сейчас. Нужно are having dinner.', 'Do не збирає having dinner зараз. Потрібно are having dinner.', 'Use are having dinner.'),
      },
      fallbackExplanation: tri('We = are. Поэтому We are having dinner.', 'We = are. Тому We are having dinner.', 'We uses are.'),
      focusWords: ['are', 'having'],
    }),
    pcStep({
      id: 'pc_basic_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'noun_subject_is_ing',
      sentence: 'The baby ___ sleeping.',
      translation: tri('Ребенок спит.', 'Дитина спить.', 'El bebe esta durmiendo.'),
      options: ['am', 'is', 'are', 'does'],
      correctAnswer: 'is',
      correctFeedback: tri('Да. The baby — один ребенок, поэтому is sleeping.', 'Так. The baby — одна дитина, тому is sleeping.', 'Yes. One baby: is sleeping.'),
      wrong: {
        am: tri('Am идет только с I. Здесь нужно is.', 'Am йде тільки з I. Тут потрібно is.', 'Use is.'),
        are: tri('Are идет с you/we/they или несколькими людьми. The baby — один ребенок, поэтому is.', 'Are йде з you/we/they або кількома людьми. The baby — одна дитина, тому is.', 'One baby: use is.'),
        does: tri('Does не ставим перед sleeping. Нужно is sleeping.', 'Does не ставимо перед sleeping. Потрібно is sleeping.', 'Use is sleeping.'),
      },
      fallbackExplanation: tri('Один ребенок: The baby is sleeping.', 'Одна дитина: The baby is sleeping.', 'One baby: is sleeping.'),
      focusWords: ['is', 'sleeping'],
    }),
    pcStep({
      id: 'pc_basic_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'missing_be_before_ing',
      sentence: 'Choose the correct sentence.',
      translation: tri('Выбери правильное предложение.', 'Обери правильне речення.', 'Elige la oracion correcta.'),
      options: ['I am working now.', 'I working now.', 'I am work now.', 'I work now.'],
      correctAnswer: 'I am working now.',
      correctFeedback: tri('Да. Now показывает действие сейчас: I am working now.', 'Так. Now показує дію зараз: I am working now.', 'Yes. Now points to action now.'),
      wrong: {
        'I working now.': tri('В I working now пропущено am. Нужно: I am working now.', 'У I working now пропущено am. Потрібно: I am working now.', 'Missing am: I am working now.'),
        'I am work now.': tri('После am для действия сейчас нужно -ing: I am working now.', 'Після am для дії зараз потрібно -ing: I am working now.', 'After am, use working.'),
        'I work now.': tri('I work now может звучать как "теперь у меня есть работа". Для действия прямо сейчас: I am working now.', 'I work now може звучати як "тепер у мене є робота". Для дії прямо зараз: I am working now.', 'For action right now, use I am working now.'),
      },
      fallbackExplanation: tri('Не I working. Полная связка: I am working.', 'Не I working. Повна звʼязка: I am working.', 'Use I am working.'),
      focusWords: ['am working'],
    }),
    pcStep({
      id: 'pc_basic_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'be_plus_base_error',
      sentence: 'Choose the correct sentence.',
      translation: tri('Выбери правильное предложение.', 'Обери правильне речення.', 'Elige la oracion correcta.'),
      options: ['She is studying at the moment.', 'She studying at the moment.', 'She is study at the moment.', 'She studies at the moment.'],
      correctAnswer: 'She is studying at the moment.',
      correctFeedback: tri('Да. At the moment показывает действие сейчас: She is studying.', 'Так. At the moment показує дію зараз: She is studying.', 'Yes. At the moment points to action now.'),
      wrong: {
        'She studying at the moment.': tri('В She studying пропущено is. Нужно: She is studying.', 'У She studying пропущено is. Потрібно: She is studying.', 'Missing is: She is studying.'),
        'She is study at the moment.': tri('После is нужно studying, не study: She is studying.', 'Після is потрібно studying, не study: She is studying.', 'After is, use studying.'),
        'She studies at the moment.': tri('Studies больше похоже на привычку или факт. At the moment просит действие сейчас: is studying.', 'Studies більше схоже на звичку або факт. At the moment просить дію зараз: is studying.', 'At the moment needs is studying.'),
      },
      fallbackExplanation: tri('At the moment: She is studying.', 'At the moment: She is studying.', 'At the moment: She is studying.'),
      focusWords: ['is studying'],
    }),
    pcStep({
      id: 'pc_basic_contrast_006',
      order: 9,
      difficulty: 'contrast',
      targetSkill: 'they_are_ing_full',
      sentence: 'Choose the correct sentence.',
      translation: tri('Выбери правильное предложение.', 'Обери правильне речення.', 'Elige la oracion correcta.'),
      options: ['They are waiting outside.', 'They waiting outside.', 'They are wait outside.', 'They waits outside.'],
      correctAnswer: 'They are waiting outside.',
      correctFeedback: tri('Да. They are waiting outside.', 'Так. They are waiting outside.', 'Yes. They are waiting outside.'),
      wrong: {
        'They waiting outside.': tri('Перед действием не хватает are. Без маленькой опоры фраза разваливается.', 'Перед дією бракує are. Без маленької опори фраза розвалюється.', 'Missing are.'),
        'They are wait outside.': tri('После are действие должно быть с -ing. Обычная форма wait здесь не подходит.', 'Після are дія має бути з -ing. Звичайна форма wait тут не підходить.', 'After are, use waiting.'),
        'They waits outside.': tri('Waits здесь не подходит. Для действия сейчас: They are waiting outside.', 'Waits тут не підходить. Для дії зараз: They are waiting outside.', 'Use They are waiting outside.'),
      },
      fallbackExplanation: tri('They + are + waiting.', 'They + are + waiting.', 'They + are + waiting.'),
      focusWords: ['are waiting'],
    }),
    pcStep({
      id: 'pc_basic_mixed_001',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'negative_order',
      sentence: 'I ___ working today.',
      translation: tri('Я сегодня не работаю.', 'Я сьогодні не працюю.', 'Hoy no estoy trabajando.'),
      options: ['am not', 'not am', "don't", 'am no'],
      correctAnswer: 'am not',
      correctFeedback: tri('Да. В отрицании not идет после am: I am not working.', 'Так. У запереченні not іде після am: I am not working.', 'Yes. Not goes after am.'),
      wrong: {
        'not am': tri('Порядок другой: am not, не not am.', 'Порядок інший: am not, не not am.', 'Use am not.'),
        "don't": tri("Don't здесь не работает перед working. Нужно am not working.", "Don't тут не працює перед working. Потрібно am not working.", 'Use am not working.'),
        'am no': tri('С am используем not: am not working.', 'З am використовуємо not: am not working.', 'Use am not.'),
      },
      fallbackExplanation: tri('Отрицание: I am not working.', 'Заперечення: I am not working.', 'Negative: I am not working.'),
      focusWords: ['am not'],
    }),
    pcStep({
      id: 'pc_basic_mixed_002',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'question_order',
      sentence: '___ you working now?',
      translation: tri('Ты сейчас работаешь?', 'Ти зараз працюєш?', 'Estas trabajando ahora?'),
      options: ['Are', 'Do', 'Is', 'You are'],
      correctAnswer: 'Are',
      correctFeedback: tri('Да. В вопросе Are выходит вперед: Are you working now?', 'Так. У питанні Are виходить уперед: Are you working now?', 'Yes. Are goes first.'),
      wrong: {
        Do: tri('Do не ставим перед working. Вопрос: Are you working now?', 'Do не ставимо перед working. Питання: Are you working now?', 'Use Are you working now?'),
        Is: tri('Is идет с he/she/it. С you нужна форма are: Are you working now?', 'Is йде з he/she/it. З you потрібна форма are: Are you working now?', 'You uses are.'),
        'You are': tri('You are working now — это утверждение. Вопрос: Are you working now?', 'You are working now — це твердження. Питання: Are you working now?', 'Question: Are you working now?'),
      },
      fallbackExplanation: tri('Вопрос: Are + you + working?', 'Питання: Are + you + working?', 'Question: Are you working?'),
      focusWords: ['are you'],
    }),
    pcStep({
      id: 'pc_basic_mixed_003',
      order: 12,
      difficulty: 'mixed',
      targetSkill: 'now_continuous_vs_simple',
      sentence: 'Right now, she ___.',
      translation: tri('Прямо сейчас она читает.', 'Прямо зараз вона читає.', 'Ahora mismo ella esta leyendo.'),
      options: ['reads', 'is reading', 'reading', 'does read'],
      correctAnswer: 'is reading',
      correctFeedback: tri('Да. Right now просит is reading.', 'Так. Right now просить is reading.', 'Yes. Right now needs is reading.'),
      wrong: {
        reads: tri('Reads больше похоже на привычку или факт. Right now просит is reading.', 'Reads більше схоже на звичку або факт. Right now просить is reading.', 'Right now needs is reading.'),
        reading: tri('Reading без is не работает. Нужно she is reading.', 'Reading без is не працює. Потрібно she is reading.', 'Missing is.'),
        'does read': tri('Does read здесь звучит не как обычное действие прямо сейчас. Нужно is reading.', 'Does read тут звучить не як звичайна дія прямо зараз. Потрібно is reading.', 'Use is reading.'),
      },
      fallbackExplanation: tri('Right now = is reading.', 'Right now = is reading.', 'Right now = is reading.'),
      focusWords: ['is reading'],
    }),
    pcStep({
      id: 'pc_basic_mixed_004',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_be_agreement',
      sentence: 'Choose the correct pair.',
      translation: tri('Выбери правильную пару.', 'Обери правильну пару.', 'Elige la pareja correcta.'),
      options: ['I am working / They are waiting', 'I is working / They is waiting', 'I are working / They am waiting', 'I working / They waiting'],
      correctAnswer: 'I am working / They are waiting',
      correctFeedback: tri('Да. I am working. They are waiting.', 'Так. I am working. They are waiting.', 'Yes. I am. They are.'),
      wrong: {
        'I is working / They is waiting': tri('С I нужна форма am, с they нужна are. Здесь перепутана маленькая опора.', 'З I потрібна форма am, з they потрібна are. Тут переплутана маленька опора.', 'Use I am / They are.'),
        'I are working / They am waiting': tri('Формы перепутаны. Нужно: I am working / They are waiting.', 'Форми переплутані. Потрібно: I am working / They are waiting.', 'Use I am / They are.'),
        'I working / They waiting': tri('Не хватает am и are. В действии сейчас нельзя оставлять -ing один.', 'Бракує am і are. У дії зараз не можна лишати -ing сам.', 'Missing am and are.'),
      },
      fallbackExplanation: tri('Пара: I am working / They are waiting.', 'Пара: I am working / They are waiting.', 'Pair: I am working / They are waiting.'),
      focusWords: ['am working', 'are waiting'],
    }),
    pcStep({
      id: 'pc_basic_mixed_005',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_simple_vs_continuous_signal',
      sentence: 'Choose the correct pair.',
      translation: tri('Выбери правильную пару.', 'Обери правильну пару.', 'Elige la pareja correcta.'),
      options: ['I work every day / I am working now', 'I am working every day / I work now', 'I working every day / I am work now', 'I am work every day / I working now'],
      correctAnswer: 'I work every day / I am working now',
      correctFeedback: tri('Да. Every day — привычка: I work. Now — действие сейчас: I am working.', 'Так. Every day — звичка: I work. Now — дія зараз: I am working.', 'Yes. Every day = habit; now = action now.'),
      wrong: {
        'I am working every day / I work now': tri('Формы поменялись местами. Every day обычно просит I work, а now — I am working.', 'Форми помінялися місцями. Every day зазвичай просить I work, а now — I am working.', 'Every day needs I work; now needs I am working.'),
        'I working every day / I am work now': tri('В I working не хватает am. В I am work не хватает -ing. Нужно: I work / I am working.', 'У I working бракує am. У I am work бракує -ing. Потрібно: I work / I am working.', 'Use I work / I am working.'),
        'I am work every day / I working now': tri('Обе части сломаны: привычка не просит am, а действие сейчас не может быть без am.', 'Обидві частини зламані: звичка не просить am, а дія зараз не може бути без am.', 'Use I work every day / I am working now.'),
      },
      fallbackExplanation: tri('Every day = I work. Now = I am working.', 'Every day = I work. Now = I am working.', 'Every day = I work. Now = I am working.'),
      focusWords: ['work', 'am working'],
    }),
    pcStep({
      id: 'pc_basic_mixed_006',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_sentence_correction',
      sentence: 'Choose the correct sentence.',
      translation: tri('Выбери правильное предложение.', 'Обери правильне речення.', 'Elige la oracion correcta.'),
      options: ['She is studying now, but they are watching TV.', 'She studying now, but they watching TV.', 'She is study now, but they are watch TV.', 'She studies now, but they watches TV.'],
      correctAnswer: 'She is studying now, but they are watching TV.',
      correctFeedback: tri('Да. She is studying. They are watching.', 'Так. She is studying. They are watching.', 'Yes. She is studying. They are watching.'),
      wrong: {
        'She studying now, but they watching TV.': tri('Не хватает is и are. Для действия сейчас нужна маленькая опора перед каждым действием.', 'Бракує is і are. Для дії зараз потрібна маленька опора перед кожною дією.', 'Missing is and are.'),
        'She is study now, but they are watch TV.': tri('Опора есть, но действие осталось без -ing. После is и are нужна форма процесса.', 'Опора є, але дія залишилася без -ing. Після is і are потрібна форма процесу.', 'Use studying and watching.'),
        'She studies now, but they watches TV.': tri('Now просит действие прямо сейчас, а не обычную привычку.', 'Now просить дію прямо зараз, а не звичайну звичку.', 'Use the current-action form.'),
      },
      fallbackExplanation: tri('С she берем is, с they берем are, оба действия ставим с -ing.', 'З she беремо is, з they беремо are, обидві дії ставимо з -ing.', 'She is studying now, but they are watching TV.'),
      focusWords: ['is studying', 'are watching'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'missing_be_before_ing',
      'be_plus_base_error',
      'wrong_be_form',
      'present_simple_instead_of_continuous_now',
      'ing_spelling_error',
      'negative_order_error',
      'question_order_error',
      'habit_vs_now_confusion',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri('Показываем пару am/is/are + -ing.', 'Показуємо пару am/is/are + -ing.', 'Show am/is/are + -ing.'),
    depth2: tri('Отдельно проверяем маленькую опору: am, is или are.', 'Окремо перевіряємо маленьку опору: am, is або are.', 'Check am, is, or are.'),
    depth3: tri('Потом проверяем -ing: working, studying, waiting.', 'Потім перевіряємо -ing: working, studying, waiting.', 'Then check -ing.'),
    depth4: tri('Почти подсказка: показываем готовую фразу.', 'Майже підказка: показуємо готову фразу.', 'Almost a hint: show the ready sentence.'),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri(
        'Стоп. Для действия сейчас нужны две части: am/is/are + -ing. Не пропускай первую часть и не оставляй действие без -ing.',
        'Стоп. Для дії зараз потрібні дві частини: am/is/are + -ing. Не пропускай першу частину і не лишай дію без -ing.',
        'Stop. For action now, use am/is/are + -ing.',
      ),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_be_ing_hint_then_retry',
      card: tri(
        'Подсказка: система покажет, какую маленькую форму выбрать, но ответ ты соберешь сам.',
        'Підказка: система покаже, яку маленьку форму обрати, але відповідь ти збереш сам.',
        'Hint: the system shows the be form, but you choose the answer.',
      ),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri(
        'Режим подсказки: сначала выбираем am/is/are, потом проверяем -ing.',
        'Режим підказки: спочатку обираємо am/is/are, потім перевіряємо -ing.',
        'Guided mode: choose am/is/are, then check -ing.',
      ),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      {
        id: 'guided_pc_basic_001',
        prompt: tri('С I выбираем am, is или are?', 'З I обираємо am, is або are?', 'With I, choose am, is, or are?'),
        options: ['am', 'is', 'are'],
        correctIndex: 0,
        thenReturnToExerciseId: 'pc_basic_easy_001',
      },
      {
        id: 'guided_pc_basic_002',
        prompt: tri('С she выбираем am, is или are?', 'З she обираємо am, is або are?', 'With she, choose am, is, or are?'),
        options: ['am', 'is', 'are'],
        correctIndex: 1,
        thenReturnToExerciseId: 'pc_basic_easy_002',
      },
      {
        id: 'guided_pc_basic_003',
        prompt: tri('С they выбираем am, is или are?', 'З they обираємо am, is або are?', 'With they, choose am, is, or are?'),
        options: ['am', 'is', 'are'],
        correctIndex: 2,
        thenReturnToExerciseId: 'pc_basic_easy_003',
      },
      {
        id: 'guided_pc_basic_004',
        prompt: tri('После am/is/are для действия сейчас нужно work или working?', 'Після am/is/are для дії зараз потрібно work чи working?', 'After am/is/are, choose work or working?'),
        options: ['work', 'working'],
        correctIndex: 1,
        thenReturnToExerciseId: 'pc_basic_contrast_004',
      },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'verb',
    microDiagnosisId: 'verb_present_continuous_basic',
    diagnosisLabel: tri('am/is/are + -ing', 'am/is/are + -ing', 'am/is/are + -ing'),
    contrastSet: CONTRAST,
    focusWords: ['am working', 'is studying', 'are waiting', 'now', 'right now', 'at the moment'],
    focusPatterns: [
      'i_am_ing',
      'she_is_ing',
      'they_are_ing',
      'he_is_ing',
      'we_are_ing',
      'noun_subject_is_ing',
      'missing_be_before_ing',
      'be_plus_base_error',
      'they_are_ing_full',
      'negative_order',
      'question_order',
      'now_continuous_vs_simple',
      'mixed_be_agreement',
      'mixed_simple_vs_continuous_signal',
      'mixed_sentence_correction',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyLevel: 2,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 3,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_verb_present_continuous_basic_start',
    answer: 'diagnosis_training_verb_present_continuous_basic_answer',
    mastery: 'diagnosis_training_verb_present_continuous_basic_mastery',
    fallback: 'diagnosis_training_verb_present_continuous_basic_fallback',
    onStart: 'diagnosis_training_started',
    onCorrect: 'diagnosis_training_answer_correct',
    onWrong: 'diagnosis_training_answer_wrong',
    onDepthIncrease: 'diagnosis_training_feedback_depth_increased',
    onGuidedMode: 'diagnosis_training_guided_mode_started',
    onMastery: 'diagnosis_training_mastered',
    onSmartTrainerOpen: 'diagnosis_training_smart_trainer_opened',
    payload: {
      category: 'verb',
      microDiagnosisId: 'verb_present_continuous_basic',
      contrastSet: CONTRAST,
      logExactToken: true,
      logMistakeType: true,
      logExerciseId: true,
      logAttemptCount: true,
      logFeedbackDepth: true,
      logBeForm: true,
      logVerbIngForm: true,
      logTimeSignal: true,
    },
  },
  routing: {
    diagnosisTrainerRoute: '/problem_coach?category=verb&microDiagnosisId=verb_present_continuous_basic',
    problemCoachRoute: '/problem_coach?category=verb&microDiagnosisId=verb_present_continuous_basic',
    smartTrainerRoute: '/trainer_smart_session?mode=weak&source=diagnosis_training&category=verb&microDiagnosisId=verb_present_continuous_basic',
    fallbackIfTrainingMissing: '/problem_coach?category=verb',
  },
  qualityChecklist: {
    hasStableId: true,
    hasCategory: true,
    hasMultilingualTitle: true,
    hasPlainDiagnosisText: true,
    hasMentalModel: true,
    hasContrastSet: true,
    hasAtLeastSixExamples: true,
    hasAtLeastTwelveExercises: true,
    hasEasyContrastMixedStructure: true,
    hasDistractorSpecificFeedback: true,
    hasRetryFeedbackLevels: true,
    hasGuidedModeForRepeatedMistakes: true,
    hasMasteryRules: true,
    hasSmartTrainerConfig: true,
    hasAnalyticsPayload: true,
    hasFallbackRoute: true,
  },
};
