import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

const tri = (ru: string, uk: string, es: string): TriText => ({ ru, uk, es });

const ARTICLE_OPTIONS = [
  { id: 'a', text: 'a' },
  { id: 'an', text: 'an' },
  { id: 'the', text: 'the' },
  { id: 'no article', text: 'no article' },
];

type ArticleOptionId = 'a' | 'an' | 'the' | 'no article';

function zeroStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  sentence: string;
  translation: TriText;
  correctAnswer: ArticleOptionId;
  correctFeedback: TriText;
  wrong: Partial<Record<ArticleOptionId, TriText>>;
  retry: [TriText, TriText, TriText];
  focusWords: string[];
}): DiagnosisTrainingStep {
  const correctIndex = ARTICLE_OPTIONS.findIndex((option) => option.id === input.correctAnswer);
  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    translation: input.translation,
    explanationBlock: tri(
      'Не выбирай артикль автоматически. Сначала спроси: это один предмет, конкретный предмет или общая идея?',
      'Не обирай артикль автоматично. Спочатку запитай: це один предмет, конкретний предмет чи загальна ідея?',
      'No elijas artículo automáticamente. Primero pregunta: es una cosa, algo específico o una idea general?',
    ),
    microTask: tri(
      'Выбери: a/an, the или no article.',
      'Обери: a/an, the або no article.',
      'Elige: a/an, the o no article.',
    ),
    sentence: input.sentence,
    answerOptions: ARTICLE_OPTIONS,
    correctAnswerId: input.correctAnswer,
    correctIndex,
    correctFeedback: input.correctFeedback,
    wrongFeedbackByOption: {
      a: input.wrong.a ?? tri(
        'a нужен перед одним исчисляемым предметом. Здесь смысл другой: проверь, не говорит ли слово о категории или идее вообще.',
        'a потрібен перед одним злічуваним предметом. Тут зміст інший: перевір, чи не говорить слово про категорію або ідею загалом.',
        'a is used before one countable thing. Here the meaning is different: check if the word means a category or idea in general.',
      ),
      an: input.wrong.an ?? tri(
        'an работает как a, только перед гласным звуком. Здесь сначала надо решить, нужен ли артикль вообще.',
        'an працює як a, тільки перед голосним звуком. Тут спочатку треба вирішити, чи потрібен артикль узагалі.',
        'an works like a, but before a vowel sound. Here first decide whether an article is needed at all.',
      ),
      the: input.wrong.the ?? tri(
        'the делает предмет конкретным. Здесь фраза чаще говорит об общей идее, поэтому артикль может быть не нужен.',
        'the робить предмет конкретним. Тут фраза частіше говорить про загальну ідею, тому артикль може бути не потрібен.',
        'the makes the thing specific. Here the phrase usually means a general idea, so an article may not be needed.',
      ),
      'no article': input.wrong['no article'] ?? tri(
        'Без артикля не всегда правильно. Если слово стало конкретным из-за контекста, английский часто возвращает the.',
        'Без артикля не завжди правильно. Якщо слово стало конкретним через контекст, англійська часто повертає the.',
        'No article is not always right. If the word becomes specific because of context, English often brings back the.',
      ),
    },
    retryFeedback: [
      input.retry[0],
      input.retry[1],
      input.retry[2],
      tri(
        `Подсказка: здесь правильный выбор - ${input.correctAnswer}.`,
        `Підказка: тут правильний вибір - ${input.correctAnswer}.`,
        `Pista: aquí la opción correcta es ${input.correctAnswer}.`,
      ),
    ],
    fallbackExplanation: tri(
      'Один исчисляемый предмет - a/an. Конкретный предмет - the. Общая категория, вещество, язык, спорт или обычный прием пищи - часто no article.',
      'Один злічуваний предмет - a/an. Конкретний предмет - the. Загальна категорія, речовина, мова, спорт або звичайний прийом їжі - часто no article.',
      'One countable thing - a/an. Specific thing - the. General category, substance, language, sport or normal meal - often no article.',
    ),
    focusWords: input.focusWords,
  };
}

export const ARTICLE_ZERO_TRAINING: DiagnosisTraining = {
  id: 'article_zero',
  category: 'article',
  version: '1.0.0',
  status: 'active',
  priority: 3,
  supportedLocales: ['ru', 'uk', 'es'],
  title: tri('Zero Article: когда артикль не нужен', 'Zero Article: коли артикль не потрібен', 'Zero Article: cuando no usamos artículo'),
  shortTitle: tri('Без артикля', 'Без артикля', 'Sin artículo'),
  shortDiagnosis: tri(
    'Ты ставишь артикль там, где английский часто оставляет слово без артикля.',
    'Ти ставиш артикль там, де англійська часто залишає слово без артикля.',
    'Usas artículo donde el inglés muchas veces deja la palabra sin artículo.',
  ),
  diagnosisText: tri(
    'Ты ставишь a/an или the там, где английский часто не ставит артикль вообще. Обычно это происходит с общими идеями, множественным числом, неисчисляемыми словами, языками, спортом, приемами пищи и некоторыми устойчивыми выражениями.',
    'Ти ставиш a/an або the там, де англійська часто не ставить артикль взагалі. Зазвичай це трапляється із загальними ідеями, множиною, незлічуваними словами, мовами, спортом, прийомами їжі та деякими сталими виразами.',
    'Usas a/an o the donde el inglés muchas veces no usa artículo. Normalmente pasa con ideas generales, plural, incontables, idiomas, deportes, comidas y algunas expresiones fijas.',
  ),
  mentalModel: tri(
    'Если ты говоришь не об одном конкретном предмете, а о категории, идее, веществе, языке, спорте или еде в общем смысле - часто артикль не нужен.',
    'Якщо ти говориш не про один конкретний предмет, а про категорію, ідею, речовину, мову, спорт або їжу в загальному сенсі - часто артикль не потрібен.',
    'Si no hablas de un objeto específico, sino de una categoría, idea, sustancia, idioma, deporte o comida en sentido general, muchas veces no usamos artículo.',
  ),
  contrastSet: ['a', 'an', 'the', 'no article'],
  coreRule: tri(
    'No article используется, когда слово говорит об общем смысле: I like music, Dogs are friendly, She speaks English, We play football, I had breakfast.',
    'No article використовується, коли слово має загальний сенс: I like music, Dogs are friendly, She speaks English, We play football, I had breakfast.',
    'No article se usa cuando la palabra tiene sentido general: I like music, Dogs are friendly, She speaks English, We play football, I had breakfast.',
  ),
  whatUserMustLearn: {
    ru: [
      'A/an нужен только перед одним исчисляемым предметом: a book, an apple.',
      'The нужен, когда предмет конкретный или уже понятный: the book on the table.',
      'No article часто нужен с общими plural nouns: Dogs are friendly.',
      'No article часто нужен с uncountable nouns в общем смысле: I like music, Water is important.',
      'No article обычно используется с языками: She speaks English.',
      'No article обычно используется со спортом и играми: We play football.',
      'No article часто используется с meals в общем смысле: I had breakfast.',
      'Если слово становится конкретным, article может вернуться: the music in this film, the breakfast you made.',
    ],
    uk: [
      'A/an потрібен тільки перед одним злічуваним предметом: a book, an apple.',
      'The потрібен, коли предмет конкретний або вже зрозумілий: the book on the table.',
      'No article часто потрібен із загальними plural nouns: Dogs are friendly.',
      'No article часто потрібен із uncountable nouns у загальному сенсі: I like music, Water is important.',
      'No article зазвичай використовується з мовами: She speaks English.',
      'No article зазвичай використовується зі спортом та іграми: We play football.',
      'No article часто використовується з meals у загальному сенсі: I had breakfast.',
      'Якщо слово стає конкретним, article може повернутися: the music in this film, the breakfast you made.',
    ],
    es: [
      'A/an se usa solo antes de una cosa contable singular: a book, an apple.',
      'The se usa cuando el objeto es específico o ya claro: the book on the table.',
      'No article se usa mucho con plural nouns en sentido general: Dogs are friendly.',
      'No article se usa mucho con uncountable nouns en sentido general: I like music, Water is important.',
      'No article normalmente se usa con idiomas: She speaks English.',
      'No article normalmente se usa con deportes y juegos: We play football.',
      'No article se usa mucho con meals en sentido general: I had breakfast.',
      'Si la palabra se vuelve específica, el artículo puede volver: the music in this film, the breakfast you made.',
    ],
  },
  examples: [
    { en: 'Dogs are friendly.', ru: 'Собаки дружелюбные.', uk: 'Собаки дружелюбні.', es: 'Los perros son amigables.', why: tri('Dogs во множественном числе говорит о собаках вообще. Это категория, не конкретная группа собак. Поэтому без артикля.', 'Dogs у множині говорить про собак загалом. Це категорія, не конкретна група собак. Тому без артикля.', 'Dogs en plural habla de perros en general. Es una categoría, no un grupo específico de perros. Por eso va sin artículo.') },
    { en: 'I like music.', ru: 'Мне нравится музыка.', uk: 'Мені подобається музика.', es: 'Me gusta la música.', why: tri('Music здесь общая идея и неисчисляемое слово. Это не конкретная музыка, поэтому без the.', 'Music тут загальна ідея і незлічуване слово. Це не конкретна музика, тому без the.', 'Music aquí es una idea general y una palabra incontable. No es música específica, por eso va sin the.') },
    { en: 'She speaks English.', ru: 'Она говорит по-английски.', uk: 'Вона говорить англійською.', es: 'Ella habla inglés.', why: tri('Названия языков обычно идут без артикля: English, Spanish, Ukrainian.', 'Назви мов зазвичай ідуть без артикля: English, Spanish, Ukrainian.', 'Los nombres de idiomas normalmente van sin artículo: English, Spanish, Ukrainian.') },
    { en: 'We play football on Sundays.', ru: 'Мы играем в футбол по воскресеньям.', uk: 'Ми граємо у футбол по неділях.', es: 'Jugamos al fútbol los domingos.', why: tri('Названия спорта и игр обычно идут без артикля: play football, play tennis, play chess.', 'Назви спорту та ігор зазвичай ідуть без артикля: play football, play tennis, play chess.', 'Los deportes y juegos normalmente van sin artículo: play football, play tennis, play chess.') },
    { en: 'I had breakfast at seven.', ru: 'Я позавтракал в семь.', uk: 'Я поснідав о сьомій.', es: 'Desayuné a las siete.', why: tri('Meals в обычном общем смысле часто идут без артикля: have breakfast, have lunch, have dinner.', 'Meals у звичайному загальному сенсі часто йдуть без артикля: have breakfast, have lunch, have dinner.', 'Las comidas en sentido general muchas veces van sin artículo: have breakfast, have lunch, have dinner.') },
    { en: 'Water is important.', ru: 'Вода важна.', uk: 'Вода важлива.', es: 'El agua es importante.', why: tri('Water здесь вещество в общем смысле. Это не конкретная вода в стакане, поэтому без артикля.', 'Water тут речовина в загальному сенсі. Це не конкретна вода у склянці, тому без артикля.', 'Water aquí es una sustancia en sentido general. No es agua específica en un vaso, por eso va sin artículo.') },
    { en: 'The water in this bottle is cold.', ru: 'Вода в этой бутылке холодная.', uk: 'Вода в цій пляшці холодна.', es: 'El agua de esta botella está fría.', why: tri('Здесь water уже конкретная: вода в этой бутылке. Поэтому the water.', 'Тут water уже конкретна: вода в цій пляшці. Тому the water.', 'Aquí water ya es específica: el agua de esta botella. Por eso the water.') },
    { en: 'Children need attention.', ru: 'Детям нужно внимание.', uk: 'Дітям потрібна увага.', es: 'Los niños necesitan atención.', why: tri('Children здесь означает детей вообще. Это plural general meaning, поэтому без артикля.', 'Children тут означає дітей загалом. Це plural general meaning, тому без артикля.', 'Children aquí significa niños en general. Es plural general meaning, por eso va sin artículo.') },
  ],
  introBlocks: [
    { id: 'intro_problem', type: 'diagnosis', text: tri('Похоже, ты иногда ставишь артикль там, где английский оставляет слово голым. Это не хаос. У zero article есть логика: часто мы не ставим артикль, когда говорим о вещи вообще, а не о конкретном экземпляре.', 'Схоже, ти іноді ставиш артикль там, де англійська залишає слово без нього. Це не хаос. У zero article є логіка: часто ми не ставимо артикль, коли говоримо про річ загалом, а не про конкретний екземпляр.', 'Parece que a veces pones artículo donde el inglés deja la palabra sin artículo. No es caos. Zero article tiene lógica: muchas veces no usamos artículo cuando hablamos de algo en general, no de un ejemplo específico.') },
    { id: 'intro_rule', type: 'rule', text: tri('Главный вопрос: это конкретный предмет или общая идея? Конкретный предмет часто требует the. Общая идея часто идет без артикля.', 'Головне питання: це конкретний предмет чи загальна ідея? Конкретний предмет часто потребує the. Загальна ідея часто йде без артикля.', 'La pregunta principal: es un objeto específico o una idea general? El objeto específico muchas veces necesita the. La idea general muchas veces va sin artículo.') },
    { id: 'intro_warning', type: 'warning', text: tri('Не переноси артикли из русского перевода. В английском I like music без the, хотя по-русски мы говорим “музыка”.', 'Не перенось артиклі з українського перекладу. В англійській I like music без the, хоча українською ми говоримо “музика”.', 'No copies los artículos desde la traducción española o rusa/ucraniana. En inglés decimos I like music sin the, aunque en español sea la música.') },
  ],
  steps: [
    zeroStep({
      id: 'zero_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'general_plural',
      sentence: '___ dogs are loyal animals.',
      translation: tri('Собаки - верные животные.', 'Собаки - вірні тварини.', 'Los perros son animales leales.'),
      correctAnswer: 'no article',
      correctFeedback: tri('Да. Dogs здесь означает собак вообще. Это plural general meaning, поэтому артикль не нужен.', 'Так. Dogs тут означає собак загалом. Це plural general meaning, тому артикль не потрібен.', 'Sí. Dogs aquí significa perros en general. Es plural general meaning, por eso no usamos artículo.'),
      wrong: {
        a: tri('A нельзя ставить перед dogs, потому что dogs - множественное число. A/an работает с одним предметом.', 'A не можна ставити перед dogs, бо dogs - множина. A/an працює з одним предметом.', 'A no puede ir antes de dogs porque dogs es plural. A/an funciona con una sola cosa.'),
        an: tri('An нельзя ставить перед dogs. An нужен перед одним предметом, а dogs - множественное число.', 'An не можна ставити перед dogs. An потрібен перед одним предметом, а dogs - множина.', 'An no puede ir antes de dogs. An se usa antes de una sola cosa, y dogs es plural.'),
        the: tri('The dogs означало бы конкретные собаки. Здесь речь о собаках вообще, поэтому без the.', 'The dogs означало б конкретні собаки. Тут йдеться про собак загалом, тому без the.', 'The dogs significaría perros específicos. Aquí hablamos de perros en general, por eso sin the.'),
      },
      retry: [
        tri('Собаки вообще - dogs. Конкретные собаки - the dogs.', 'Собаки загалом - dogs. Конкретні собаки - the dogs.', 'Perros en general - dogs. Perros específicos - the dogs.'),
        tri('Plural + общий смысл = часто без артикля.', 'Plural + загальний сенс = часто без артикля.', 'Plural + sentido general = muchas veces sin artículo.'),
        tri('Подсказка: Dogs are loyal animals.', 'Підказка: Dogs are loyal animals.', 'Pista: Dogs are loyal animals.'),
      ],
      focusWords: ['dogs'],
    }),
    zeroStep({
      id: 'zero_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'general_plural',
      sentence: '___ children learn very fast.',
      translation: tri('Дети учатся очень быстро.', 'Діти вчаться дуже швидко.', 'Los niños aprenden muy rápido.'),
      correctAnswer: 'no article',
      correctFeedback: tri('Да. Children здесь означает детей вообще. Это общая категория, поэтому без артикля.', 'Так. Children тут означає дітей загалом. Це загальна категорія, тому без артикля.', 'Sí. Children aquí significa niños en general. Es una categoría general, por eso va sin artículo.'),
      wrong: {
        a: tri('A нельзя ставить перед children. Children - множественное число.', 'A не можна ставити перед children. Children - множина.', 'A no puede ir antes de children. Children es plural.'),
        an: tri('An нельзя ставить перед children. Это plural noun, а an нужен перед одним предметом.', 'An не можна ставити перед children. Це plural noun, а an потрібен перед одним предметом.', 'An no puede ir antes de children. Es plural noun, y an se usa antes de una sola cosa.'),
        the: tri('The children означало бы конкретные дети. Здесь дети вообще, поэтому артикль не нужен.', 'The children означало б конкретні діти. Тут діти загалом, тому артикль не потрібен.', 'The children significaría niños específicos. Aquí son niños en general, por eso no usamos artículo.'),
      },
      retry: [
        tri('Дети вообще - children. Конкретные дети - the children.', 'Діти загалом - children. Конкретні діти - the children.', 'Niños en general - children. Niños específicos - the children.'),
        tri('Общая категория - без the.', 'Загальна категорія - без the.', 'Categoría general - sin the.'),
        tri('Подсказка: Children learn very fast.', 'Підказка: Children learn very fast.', 'Pista: Children learn very fast.'),
      ],
      focusWords: ['children'],
    }),
    zeroStep({
      id: 'zero_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'specific_plural_the',
      sentence: '___ children in this room are very quiet.',
      translation: tri('Дети в этой комнате очень тихие.', 'Діти в цій кімнаті дуже тихі.', 'Los niños de esta habitación están muy tranquilos.'),
      correctAnswer: 'the',
      correctFeedback: tri('Да. Children здесь не дети вообще, а конкретные дети в этой комнате. Поэтому the children.', 'Так. Children тут не діти загалом, а конкретні діти в цій кімнаті. Тому the children.', 'Sí. Children aquí no son niños en general, sino niños específicos en esta habitación. Por eso the children.'),
      wrong: {
        a: tri('A нельзя ставить перед children. Children - множественное число.', 'A не можна ставити перед children. Children - множина.', 'A no puede ir antes de children. Children es plural.'),
        an: tri('An нельзя ставить перед children. Это не один предмет.', 'An не можна ставити перед children. Це не один предмет.', 'An no puede ir antes de children. No es una sola cosa.'),
        'no article': tri('Без артикля children звучит как дети вообще. Но in this room делает группу конкретной. Поэтому the.', 'Без артикля children звучить як діти загалом. Але in this room робить групу конкретною. Тому the.', 'Sin artículo, children suena como niños en general. Pero in this room hace que el grupo sea específico. Por eso the.'),
      },
      retry: [
        tri('Какие дети? Те, что в этой комнате. Конкретная группа - the children.', 'Які діти? Ті, що в цій кімнаті. Конкретна група - the children.', 'Qué niños? Los de esta habitación. Grupo específico - the children.'),
        tri('In this room делает слово конкретным. Значит the.', 'In this room робить слово конкретним. Значить the.', 'In this room hace la palabra específica. Entonces the.'),
        tri('Подсказка: The children in this room.', 'Підказка: The children in this room.', 'Pista: The children in this room.'),
      ],
      focusWords: ['children'],
    }),
    zeroStep({
      id: 'zero_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'uncountable_general',
      sentence: 'I like ___ music.',
      translation: tri('Мне нравится музыка.', 'Мені подобається музика.', 'Me gusta la música.'),
      correctAnswer: 'no article',
      correctFeedback: tri('Да. Music здесь означает музыку вообще. Это uncountable general meaning, поэтому артикль не нужен.', 'Так. Music тут означає музику загалом. Це uncountable general meaning, тому артикль не потрібен.', 'Sí. Music aquí significa música en general. Es uncountable general meaning, por eso no usamos artículo.'),
      wrong: {
        a: tri('A music не подходит, если речь о музыке вообще. Music обычно неисчисляемое слово.', 'A music не підходить, якщо йдеться про музику загалом. Music зазвичай незлічуване слово.', 'A music no encaja si hablamos de música en general. Music normalmente es incontable.'),
        an: tri('An music невозможно в этом смысле. Music здесь общая идея, без артикля.', 'An music неможливо в цьому сенсі. Music тут загальна ідея, без артикля.', 'An music no funciona en este sentido. Music aquí es una idea general, sin artículo.'),
        the: tri('The music означало бы конкретную музыку, например музыку в комнате. Здесь музыка вообще, поэтому без the.', 'The music означало б конкретну музику, наприклад музику в кімнаті. Тут музика загалом, тому без the.', 'The music significaría música específica, por ejemplo la música de una habitación. Aquí es música en general, por eso sin the.'),
      },
      retry: [
        tri('Музыка вообще - music. Конкретная музыка - the music.', 'Музика загалом - music. Конкретна музика - the music.', 'Música en general - music. Música específica - the music.'),
        tri('I like music = без артикля.', 'I like music = без артикля.', 'I like music = sin artículo.'),
        tri('Подсказка: I like music.', 'Підказка: I like music.', 'Pista: I like music.'),
      ],
      focusWords: ['music'],
    }),
    zeroStep({
      id: 'zero_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'uncountable_general',
      sentence: '___ water is important for life.',
      translation: tri('Вода важна для жизни.', 'Вода важлива для життя.', 'El agua es importante para la vida.'),
      correctAnswer: 'no article',
      correctFeedback: tri('Да. Water здесь означает воду как вещество вообще. Поэтому без артикля.', 'Так. Water тут означає воду як речовину загалом. Тому без артикля.', 'Sí. Water aquí significa agua como sustancia en general. Por eso va sin artículo.'),
      wrong: {
        a: tri('A water обычно не подходит, когда water означает вещество вообще. Это неисчисляемое слово.', 'A water зазвичай не підходить, коли water означає речовину загалом. Це незлічуване слово.', 'A water normalmente no encaja cuando water significa la sustancia en general. Es incontable.'),
        an: tri('An water невозможно здесь. Water не начинается с гласного звука и в этом смысле неисчисляемое.', 'An water неможливо тут. Water не починається з голосного звуку і в цьому сенсі незлічуване.', 'An water no funciona aquí. Water no empieza con vocal y en este sentido es incontable.'),
        the: tri('The water означало бы конкретную воду, например воду в бутылке. Здесь вода вообще, поэтому без the.', 'The water означало б конкретну воду, наприклад воду в пляшці. Тут вода загалом, тому без the.', 'The water significaría agua específica, por ejemplo el agua de una botella. Aquí es agua en general, por eso sin the.'),
      },
      retry: [
        tri('Вода вообще - water. Конкретная вода - the water.', 'Вода загалом - water. Конкретна вода - the water.', 'Agua en general - water. Agua específica - the water.'),
        tri('Вещество вообще - без артикля.', 'Речовина загалом - без артикля.', 'Sustancia en general - sin artículo.'),
        tri('Подсказка: Water is important.', 'Підказка: Water is important.', 'Pista: Water is important.'),
      ],
      focusWords: ['water'],
    }),
    zeroStep({
      id: 'zero_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'specific_uncountable_the',
      sentence: '___ water in this glass is cold.',
      translation: tri('Вода в этом стакане холодная.', 'Вода в цій склянці холодна.', 'El agua de este vaso está fría.'),
      correctAnswer: 'the',
      correctFeedback: tri('Да. Это не вода вообще, а конкретная вода в этом стакане. Поэтому the water.', 'Так. Це не вода загалом, а конкретна вода в цій склянці. Тому the water.', 'Sí. No es agua en general, sino el agua específica de este vaso. Por eso the water.'),
      wrong: {
        a: tri('A water здесь не подходит. Water неисчисляемое, а конкретность здесь выражает the.', 'A water тут не підходить. Water незлічуване, а конкретність тут виражає the.', 'A water no encaja aquí. Water es incontable, y la especificidad aquí se expresa con the.'),
        an: tri('An water не подходит. Water не требует an, а здесь конкретная вода требует the.', 'An water не підходить. Water не потребує an, а тут конкретна вода потребує the.', 'An water no encaja. Water no necesita an, y aquí el agua específica necesita the.'),
        'no article': tri('Без артикля water означало бы воду вообще. Но in this glass делает воду конкретной. Поэтому the.', 'Без артикля water означало б воду загалом. Але in this glass робить воду конкретною. Тому the.', 'Sin artículo, water significaría agua en general. Pero in this glass la hace específica. Por eso the.'),
      },
      retry: [
        tri('Какая вода? В этом стакане. Конкретная вода - the water.', 'Яка вода? У цій склянці. Конкретна вода - the water.', 'Qué agua? La de este vaso. Agua específica - the water.'),
        tri('In this glass делает water конкретным. Значит the.', 'In this glass робить water конкретним. Значить the.', 'In this glass hace water específico. Entonces the.'),
        tri('Подсказка: The water in this glass.', 'Підказка: The water in this glass.', 'Pista: The water in this glass.'),
      ],
      focusWords: ['water'],
    }),
    zeroStep({
      id: 'zero_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'language_no_article',
      sentence: 'She speaks ___ English very well.',
      translation: tri('Она очень хорошо говорит по-английски.', 'Вона дуже добре говорить англійською.', 'Ella habla inglés muy bien.'),
      correctAnswer: 'no article',
      correctFeedback: tri('Да. Названия языков обычно идут без артикля: speak English, speak Spanish, speak Ukrainian.', 'Так. Назви мов зазвичай ідуть без артикля: speak English, speak Spanish, speak Ukrainian.', 'Sí. Los nombres de idiomas normalmente van sin artículo: speak English, speak Spanish, speak Ukrainian.'),
      wrong: {
        a: tri('A English не используется. С языками обычно без артикля: speak English.', 'A English не використовується. З мовами зазвичай без артикля: speak English.', 'A English no se usa. Con idiomas normalmente no usamos artículo: speak English.'),
        an: tri('An English не нужно, когда English означает язык. Правильно: speak English.', 'An English не потрібно, коли English означає мову. Правильно: speak English.', 'An English no se usa cuando English significa el idioma. Correcto: speak English.'),
        the: tri('The English может означать “англичане” в другом контексте. Но язык английский - просто English.', 'The English може означати “англійці” в іншому контексті. Але мова англійська - просто English.', 'The English puede significar “los ingleses” en otro contexto. Pero el idioma inglés es simplemente English.'),
      },
      retry: [
        tri('Язык как навык - без артикля: speak English.', 'Мова як навичка - без артикля: speak English.', 'Idioma como habilidad - sin artículo: speak English.'),
        tri('Speak English. Без a, без an, без the.', 'Speak English. Без a, без an, без the.', 'Speak English. Sin a, sin an, sin the.'),
        tri('Подсказка: She speaks English.', 'Підказка: She speaks English.', 'Pista: She speaks English.'),
      ],
      focusWords: ['English'],
    }),
    zeroStep({
      id: 'zero_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'sport_no_article',
      sentence: 'We play ___ football every Friday.',
      translation: tri('Мы играем в футбол каждую пятницу.', 'Ми граємо у футбол щоп’ятниці.', 'Jugamos al fútbol todos los viernes.'),
      correctAnswer: 'no article',
      correctFeedback: tri('Да. С названиями спорта и игр обычно без артикля: play football, play tennis, play chess.', 'Так. З назвами спорту та ігор зазвичай без артикля: play football, play tennis, play chess.', 'Sí. Con deportes y juegos normalmente no usamos artículo: play football, play tennis, play chess.'),
      wrong: {
        a: tri('A football может означать один футбольный мяч в некоторых контекстах. Но play football = играть в футбол, без артикля.', 'A football може означати один футбольний м’яч у деяких контекстах. Але play football = грати у футбол, без артикля.', 'A football puede significar un balón en algunos contextos. Pero play football = jugar fútbol, sin artículo.'),
        an: tri('An football невозможно по звуку и не нужно по смыслу. Спорт идет без артикля: play football.', 'An football неможливо за звуком і не потрібно за змістом. Спорт іде без артикля: play football.', 'An football no funciona por sonido ni por sentido. El deporte va sin artículo: play football.'),
        the: tri('The football звучит как конкретный мяч или конкретный футбол в особом контексте. Название игры обычно без артикля.', 'The football звучить як конкретний м’яч або конкретний футбол в особливому контексті. Назва гри зазвичай без артикля.', 'The football suena como un balón específico o un fútbol específico en un contexto especial. El nombre del juego normalmente va sin artículo.'),
      },
      retry: [
        tri('Игра как вид спорта - без артикля: play football.', 'Гра як вид спорту - без артикля: play football.', 'Juego/deporte como actividad - sin artículo: play football.'),
        tri('Play football. Без the.', 'Play football. Без the.', 'Play football. Sin the.'),
        tri('Подсказка: We play football.', 'Підказка: We play football.', 'Pista: We play football.'),
      ],
      focusWords: ['football'],
    }),
    zeroStep({
      id: 'zero_contrast_006',
      order: 9,
      difficulty: 'contrast',
      targetSkill: 'meal_no_article',
      sentence: 'I had ___ breakfast at seven.',
      translation: tri('Я позавтракал в семь.', 'Я поснідав о сьомій.', 'Desayuné a las siete.'),
      correctAnswer: 'no article',
      correctFeedback: tri('Да. В обычном смысле meals часто идут без артикля: have breakfast, have lunch, have dinner.', 'Так. У звичайному сенсі meals часто йдуть без артикля: have breakfast, have lunch, have dinner.', 'Sí. En sentido normal, meals muchas veces van sin artículo: have breakfast, have lunch, have dinner.'),
      wrong: {
        a: tri('A breakfast возможен, если ты описываешь особый завтрак: a big breakfast. Но обычное have breakfast идет без артикля.', 'A breakfast можливий, якщо ти описуєш особливий сніданок: a big breakfast. Але звичайне have breakfast іде без артикля.', 'A breakfast es posible si describes un desayuno especial: a big breakfast. Pero have breakfast normal va sin artículo.'),
        an: tri('An breakfast невозможно по звуку и не нужно по смыслу. Правильно: have breakfast.', 'An breakfast неможливо за звуком і не потрібно за змістом. Правильно: have breakfast.', 'An breakfast no funciona por sonido ni por sentido. Correcto: have breakfast.'),
        the: tri('The breakfast возможно, если завтрак конкретный: the breakfast you made. Но здесь обычное действие - have breakfast.', 'The breakfast можливе, якщо сніданок конкретний: the breakfast you made. Але тут звичайна дія - have breakfast.', 'The breakfast es posible si el desayuno es específico: the breakfast you made. Pero aquí es una acción normal - have breakfast.'),
      },
      retry: [
        tri('Обычное действие: have breakfast. Без артикля.', 'Звичайна дія: have breakfast. Без артикля.', 'Acción normal: have breakfast. Sin artículo.'),
        tri('Breakfast как прием пищи - без артикля.', 'Breakfast як прийом їжі - без артикля.', 'Breakfast como comida - sin artículo.'),
        tri('Подсказка: I had breakfast.', 'Підказка: I had breakfast.', 'Pista: I had breakfast.'),
      ],
      focusWords: ['breakfast'],
    }),
    zeroStep({
      id: 'zero_mixed_001',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'specific_uncountable_the',
      sentence: 'I like ___ music in this film.',
      translation: tri('Мне нравится музыка в этом фильме.', 'Мені подобається музика в цьому фільмі.', 'Me gusta la música de esta película.'),
      correctAnswer: 'the',
      correctFeedback: tri('Да. Это не музыка вообще, а конкретная музыка в этом фильме. Поэтому the music.', 'Так. Це не музика загалом, а конкретна музика в цьому фільмі. Тому the music.', 'Sí. No es música en general, sino la música específica de esta película. Por eso the music.'),
      wrong: {
        a: tri('A music не подходит. Music обычно неисчисляемое слово. Конкретность здесь выражает the.', 'A music не підходить. Music зазвичай незлічуване слово. Конкретність тут виражає the.', 'A music no encaja. Music normalmente es incontable. La especificidad aquí se expresa con the.'),
        an: tri('An music невозможно. Здесь нужна конкретная музыка, поэтому the music.', 'An music неможливо. Тут потрібна конкретна музика, тому the music.', 'An music no funciona. Aquí necesitamos música específica, por eso the music.'),
        'no article': tri('Без артикля music означало бы музыку вообще. Но in this film делает музыку конкретной. Поэтому the.', 'Без артикля music означало б музику загалом. Але in this film робить музику конкретною. Тому the.', 'Sin artículo, music significaría música en general. Pero in this film la hace específica. Por eso the.'),
      },
      retry: [
        tri('Какая музыка? В этом фильме. Конкретная - the music.', 'Яка музика? У цьому фільмі. Конкретна - the music.', 'Qué música? La de esta película. Específica - the music.'),
        tri('In this film делает music конкретным.', 'In this film робить music конкретною.', 'In this film hace music específica.'),
        tri('Подсказка: the music in this film.', 'Підказка: the music in this film.', 'Pista: the music in this film.'),
      ],
      focusWords: ['music'],
    }),
    zeroStep({
      id: 'zero_mixed_002',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'meal_specific_the',
      sentence: '___ breakfast you made was amazing.',
      translation: tri('Завтрак, который ты приготовил, был потрясающим.', 'Сніданок, який ти приготував, був чудовим.', 'El desayuno que preparaste fue increíble.'),
      correctAnswer: 'the',
      correctFeedback: tri('Да. Это не breakfast вообще, а конкретный breakfast you made. Поэтому the breakfast.', 'Так. Це не breakfast загалом, а конкретний breakfast you made. Тому the breakfast.', 'Sí. No es breakfast en general, sino el desayuno específico que preparaste. Por eso the breakfast.'),
      wrong: {
        a: tri('A breakfast возможно, если мы просто описываем один завтрак. Но you made делает завтрак конкретным, поэтому the.', 'A breakfast можливе, якщо ми просто описуємо один сніданок. Але you made робить сніданок конкретним, тому the.', 'A breakfast puede funcionar si describimos un desayuno. Pero you made lo hace específico, por eso the.'),
        an: tri('Breakfast начинается с согласного звука, поэтому an не подходит. И завтрак конкретный, поэтому the.', 'Breakfast починається з приголосного звуку, тому an не підходить. І сніданок конкретний, тому the.', 'Breakfast empieza con consonante, así que an no encaja. Y el desayuno es específico, por eso the.'),
        'no article': tri('Обычное have breakfast без артикля. Но breakfast you made - конкретный завтрак. Нужен the.', 'Звичайне have breakfast без артикля. Але breakfast you made - конкретний сніданок. Потрібен the.', 'Have breakfast normal va sin artículo. Pero breakfast you made es un desayuno específico. Necesita the.'),
      },
      retry: [
        tri('Какой завтрак? Тот, который ты приготовил. Значит the breakfast.', 'Який сніданок? Той, який ти приготував. Значить the breakfast.', 'Qué desayuno? El que preparaste. Entonces the breakfast.'),
        tri('You made делает breakfast конкретным.', 'You made робить breakfast конкретним.', 'You made hace breakfast específico.'),
        tri('Подсказка: The breakfast you made.', 'Підказка: The breakfast you made.', 'Pista: The breakfast you made.'),
      ],
      focusWords: ['breakfast'],
    }),
    zeroStep({
      id: 'zero_mixed_003',
      order: 12,
      difficulty: 'mixed',
      targetSkill: 'language_no_article',
      sentence: 'I am learning ___ Spanish.',
      translation: tri('Я учу испанский.', 'Я вивчаю іспанську.', 'Estoy aprendiendo español.'),
      correctAnswer: 'no article',
      correctFeedback: tri('Да. Spanish как язык идет без артикля: learn Spanish.', 'Так. Spanish як мова йде без артикля: learn Spanish.', 'Sí. Spanish como idioma va sin artículo: learn Spanish.'),
      wrong: {
        a: tri('A Spanish не используется, когда Spanish означает язык. Правильно: learn Spanish.', 'A Spanish не використовується, коли Spanish означає мову. Правильно: learn Spanish.', 'A Spanish no se usa cuando Spanish significa el idioma. Correcto: learn Spanish.'),
        an: tri('An Spanish не подходит по звуку и по правилу. Языки обычно без артикля.', 'An Spanish не підходить за звуком і за правилом. Мови зазвичай без артикля.', 'An Spanish no encaja por sonido ni por regla. Los idiomas normalmente van sin artículo.'),
        the: tri('The Spanish может значить “испанцы” в другом контексте. Язык испанский - просто Spanish.', 'The Spanish може означати “іспанці” в іншому контексті. Мова іспанська - просто Spanish.', 'The Spanish puede significar “los españoles” en otro contexto. El idioma español es simplemente Spanish.'),
      },
      retry: [
        tri('Язык как предмет изучения - без артикля: learn Spanish.', 'Мова як предмет вивчення - без артикля: learn Spanish.', 'Idioma como objeto de estudio - sin artículo: learn Spanish.'),
        tri('Learn Spanish. Без артикля.', 'Learn Spanish. Без артикля.', 'Learn Spanish. Sin artículo.'),
        tri('Подсказка: I am learning Spanish.', 'Підказка: I am learning Spanish.', 'Pista: I am learning Spanish.'),
      ],
      focusWords: ['Spanish'],
    }),
    zeroStep({
      id: 'zero_mixed_004',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'general_plural',
      sentence: '___ teachers need patience.',
      translation: tri('Учителям нужно терпение.', 'Учителям потрібне терпіння.', 'Los profesores necesitan paciencia.'),
      correctAnswer: 'no article',
      correctFeedback: tri('Да. Teachers здесь означает учителей вообще. Это plural general meaning, поэтому без артикля.', 'Так. Teachers тут означає вчителів загалом. Це plural general meaning, тому без артикля.', 'Sí. Teachers aquí significa profesores en general. Es plural general meaning, por eso no usamos artículo.'),
      wrong: {
        a: tri('A нельзя ставить перед teachers. Teachers - множественное число.', 'A не можна ставити перед teachers. Teachers - множина.', 'A no puede ir antes de teachers. Teachers es plural.'),
        an: tri('An нельзя ставить перед teachers. An нужен перед одним предметом.', 'An не можна ставити перед teachers. An потрібен перед одним предметом.', 'An no puede ir antes de teachers. An se usa antes de una sola cosa.'),
        the: tri('The teachers означало бы конкретные учителя. Здесь речь об учителях вообще, поэтому без the.', 'The teachers означало б конкретні вчителі. Тут йдеться про вчителів загалом, тому без the.', 'The teachers significaría profesores específicos. Aquí hablamos de profesores en general, por eso sin the.'),
      },
      retry: [
        tri('Учителя вообще - teachers. Конкретные учителя - the teachers.', 'Вчителі загалом - teachers. Конкретні вчителі - the teachers.', 'Profesores en general - teachers. Profesores específicos - the teachers.'),
        tri('Профессия как категория - без артикля.', 'Професія як категорія - без артикля.', 'Profesión como categoría - sin artículo.'),
        tri('Подсказка: Teachers need patience.', 'Підказка: Teachers need patience.', 'Pista: Teachers need patience.'),
      ],
      focusWords: ['teachers'],
    }),
    zeroStep({
      id: 'zero_mixed_005',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'uncountable_general',
      sentence: "___ money can't buy happiness.",
      translation: tri('Деньги не могут купить счастье.', 'Гроші не можуть купити щастя.', 'El dinero no puede comprar la felicidad.'),
      correctAnswer: 'no article',
      correctFeedback: tri('Да. Money здесь означает деньги вообще. Это uncountable general meaning, поэтому без артикля.', 'Так. Money тут означає гроші загалом. Це uncountable general meaning, тому без артикля.', 'Sí. Money aquí significa dinero en general. Es uncountable general meaning, por eso va sin artículo.'),
      wrong: {
        a: tri('A money не подходит. Money в этом смысле неисчисляемое слово.', 'A money не підходить. Money у цьому сенсі незлічуване слово.', 'A money no encaja. Money en este sentido es incontable.'),
        an: tri('An money невозможно. Money не используется с an в таком общем смысле.', 'An money неможливо. Money не використовується з an у такому загальному сенсі.', 'An money no funciona. Money no se usa con an en este sentido general.'),
        the: tri('The money означало бы конкретные деньги, например деньги на столе. Здесь деньги вообще, поэтому без the.', 'The money означало б конкретні гроші, наприклад гроші на столі. Тут гроші загалом, тому без the.', 'The money significaría dinero específico, por ejemplo el dinero en la mesa. Aquí es dinero en general, por eso sin the.'),
      },
      retry: [
        tri('Деньги вообще - money. Конкретные деньги - the money.', 'Гроші загалом - money. Конкретні гроші - the money.', 'Dinero en general - money. Dinero específico - the money.'),
        tri('Money как идея - без артикля.', 'Money як ідея - без артикля.', 'Money como idea - sin artículo.'),
        tri("Подсказка: Money can't buy happiness.", "Підказка: Money can't buy happiness.", "Pista: Money can't buy happiness."),
      ],
      focusWords: ['money'],
    }),
    zeroStep({
      id: 'zero_mixed_006',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'sport_specific_equipment_contrast',
      sentence: 'He kicked ___ football into the garden.',
      translation: tri('Он пнул футбольный мяч в сад.', 'Він копнув футбольний м’яч у сад.', 'Él pateó un balón al jardín.'),
      correctAnswer: 'a',
      correctFeedback: tri('Да. Здесь football означает один мяч, а не игру. Это один исчисляемый предмет, поэтому a football.', 'Так. Тут football означає один м’яч, а не гру. Це один злічуваний предмет, тому a football.', 'Sí. Aquí football significa un balón, no el juego. Es una cosa contable singular, por eso a football.'),
      wrong: {
        an: tri('Football начинается с согласного звука /f/. Если это один мяч, нужен a, не an.', 'Football починається з приголосного звуку /f/. Якщо це один м’яч, потрібен a, не an.', 'Football empieza con /f/. Si es un balón, necesitamos a, no an.'),
        the: tri('The football возможно, если мяч уже известен. Но здесь просто один мяч, поэтому a football.', 'The football можливе, якщо м’яч уже відомий. Але тут просто один м’яч, тому a football.', 'The football es posible si el balón ya es conocido. Pero aquí es simplemente un balón, por eso a football.'),
        'no article': tri('Play football без артикля, потому что это игра. Но kicked a football - это один мяч. Нужен a.', 'Play football без артикля, бо це гра. Але kicked a football - це один м’яч. Потрібен a.', 'Play football va sin artículo porque es el juego. Pero kicked a football es un balón. Necesita a.'),
      },
      retry: [
        tri('Football может быть игра или мяч. Play football - игра, без артикля. Kick a football - мяч, нужен a.', 'Football може бути гра або м’яч. Play football - гра, без артикля. Kick a football - м’яч, потрібен a.', 'Football puede ser juego o balón. Play football - juego, sin artículo. Kick a football - balón, necesita a.'),
        tri('Один мяч - a football.', 'Один м’яч - a football.', 'Un balón - a football.'),
        tri('Подсказка: kicked a football.', 'Підказка: kicked a football.', 'Pista: kicked a football.'),
      ],
      focusWords: ['football'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'general_plural_overuse_the',
      'uncountable_overuse_the',
      'language_article_error',
      'sport_article_error',
      'meal_article_error',
      'specific_vs_general_confusion',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri('Обычное объяснение: показываем, почему здесь общий смысл, а не конкретный предмет.', 'Звичайне пояснення: показуємо, чому тут загальний сенс, а не конкретний предмет.', 'Explicación normal: mostramos por qué aquí hay sentido general, no objeto específico.'),
    depth2: tri('Проще: сводим выбор к вопросу “конкретное или вообще?”', 'Простіше: зводимо вибір до питання “конкретне чи загалом?”', 'Más simple: reducimos la elección a “específico o en general?”'),
    depth3: tri('Еще проще: даем готовую пару general vs specific.', 'Ще простіше: даємо готову пару general vs specific.', 'Aún más simple: damos una pareja lista general vs specific.'),
    depth4: tri('Почти подсказка: прямо указываем, что артикль не нужен.', 'Майже підказка: прямо вказуємо, що артикль не потрібен.', 'Casi pista: indicamos directamente que no se necesita artículo.'),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri('Остановись. Не выбирай артикль автоматически. Сначала спроси: это “конкретное” или “вообще”? Конкретное - часто the. Вообще - часто без артикля.', 'Зупинись. Не обирай артикль автоматично. Спочатку запитай: це “конкретне” чи “загалом”? Конкретне - часто the. Загалом - часто без артикля.', 'Detente. No elijas artículo automáticamente. Primero pregunta: es “específico” o “en general”? Específico - muchas veces the. En general - muchas veces sin artículo.'),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_general_specific_hint_then_retry',
      card: tri('Подсказка по смыслу: система покажет, слово используется в общем или конкретном смысле, но не выберет ответ за пользователя.', 'Підказка за змістом: система покаже, слово використовується в загальному чи конкретному сенсі, але не вибере відповідь за користувача.', 'Pista de significado: el sistema mostrará si la palabra se usa en sentido general o específico, pero no elegirá la respuesta por el usuario.'),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri('Режим подсказки: сначала выбери смысл - “вещь вообще” или “конкретная вещь”. Потом система вернет тебя к выбору артикля.', 'Режим підказки: спочатку обери сенс - “річ загалом” чи “конкретна річ”. Потім система поверне тебе до вибору артикля.', 'Modo guiado: primero elige el sentido - “cosa en general” o “cosa específica”. Luego el sistema te devuelve al artículo.'),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      { id: 'guided_zero_001', prompt: tri('В предложении Dogs are loyal animals речь о конкретных собаках или о собаках вообще?', 'У реченні Dogs are loyal animals йдеться про конкретних собак чи про собак загалом?', 'En Dogs are loyal animals hablamos de perros específicos o de perros en general?'), options: ['конкретные собаки', 'собаки вообще'], correctIndex: 1, thenReturnToExerciseId: 'zero_easy_001' },
      { id: 'guided_zero_002', prompt: tri('В предложении I like music речь о конкретной музыке или о музыке вообще?', 'У реченні I like music йдеться про конкретну музику чи про музику загалом?', 'En I like music hablamos de música específica o música en general?'), options: ['конкретная музыка', 'музыка вообще'], correctIndex: 1, thenReturnToExerciseId: 'zero_contrast_001' },
      { id: 'guided_zero_003', prompt: tri('В фразе the water in this glass вода конкретная?', 'У фразі the water in this glass вода конкретна?', 'En the water in this glass, el agua es específica?'), options: ['да', 'нет'], correctIndex: 0, thenReturnToExerciseId: 'zero_contrast_003' },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'article',
    microDiagnosisId: 'article_zero',
    diagnosisLabel: tri('Когда артикль не нужен', 'Коли артикль не потрібен', 'Cuando no usamos artículo'),
    contrastSet: ['a', 'an', 'the', 'no article'],
    focusWords: ['no article', 'the', 'a', 'an'],
    focusPatterns: [
      'general_plural',
      'specific_plural_the',
      'uncountable_general',
      'specific_uncountable_the',
      'language_no_article',
      'sport_no_article',
      'meal_no_article',
      'general_vs_specific',
      'sport_vs_object_contrast',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyLevel: 2,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 3,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_article_zero_start',
    answer: 'diagnosis_training_article_zero_answer',
    mastery: 'diagnosis_training_article_zero_mastery',
    fallback: 'diagnosis_training_article_zero_fallback',
    onStart: 'diagnosis_training_started',
    onCorrect: 'diagnosis_training_answer_correct',
    onWrong: 'diagnosis_training_answer_wrong',
    onDepthIncrease: 'diagnosis_training_feedback_depth_increased',
    onGuidedMode: 'diagnosis_training_guided_mode_started',
    onMastery: 'diagnosis_training_mastered',
    onSmartTrainerOpen: 'diagnosis_training_smart_trainer_opened',
    payload: {
      category: 'article',
      microDiagnosisId: 'article_zero',
      contrastSet: ['a', 'an', 'the', 'no article'],
      logExactToken: true,
      logMistakeType: true,
      logExerciseId: true,
      logAttemptCount: true,
      logFeedbackDepth: true,
      logGeneralSpecificType: true,
    },
  },
  routing: {
    diagnosisTrainerRoute: '/problem_coach?category=article&microDiagnosisId=article_zero',
  },
  qualityChecklist: {
    hasStableId: true,
    hasCategory: true,
    hasMultilingualTitle: true,
    hasPlainDiagnosisText: true,
    hasMentalModel: true,
    hasContrastSet: true,
    hasAtLeastSixExamples: true,
    hasAtLeastTwelveExercises: true,
    hasEasyContrastMixedStructure: true,
    hasDistractorSpecificFeedback: true,
    hasRetryFeedbackLevels: true,
    hasGuidedModeForRepeatedMistakes: true,
    hasMasteryRules: true,
    hasSmartTrainerConfig: true,
    hasAnalyticsPayload: true,
    hasFallbackRoute: true,
  },
};


