// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

type PlannedTrainingLocale = 'pt-BR' | 'vi' | 'id' | 'tr' | 'pl';

const TOO_ENOUGH_NEEDS_REVIEW_PLANNED: Record<PlannedTrainingLocale, string> = {
  'pt-BR': 'needs-review: esta explicação sobre too/enough ainda precisa de revisão para português do Brasil.',
  vi: 'needs-review: phần giải thích về too/enough này vẫn cần được rà soát cho tiếng Việt.',
  id: 'needs-review: penjelasan too/enough ini masih perlu ditinjau untuk bahasa Indonesia.',
  tr: 'needs-review: bu too/enough açıklaması Türkçe için hâlâ gözden geçirilmeli.',
  pl: 'needs-review: to objaśnienie too/enough nadal wymaga przeglądu po polsku.',
};

const tri = (
  ru: string,
  uk = ru,
  es = ru,
  planned: Partial<Record<PlannedTrainingLocale, string>> = {},
): TriText => {
  const copy: TriText = { ru, uk, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    copy[locale] = planned[locale] ?? TOO_ENOUGH_NEEDS_REVIEW_PLANNED[locale];
  }
  return copy;
};

const CONTRAST = [
  'too + adjective',
  'adjective + enough',
  'enough + noun',
  'too much',
  'too many',
  'not enough',
  'too ... to',
];

const TOO_ENOUGH_SKILL_ES: Record<string, string> = {
  too_adjective_hot: 'Exceso de temperatura: too hot.',
  too_adjective_expensive: 'Exceso de precio: too expensive.',
  too_adverb_fast: 'Exceso de velocidad: too fast.',
  adjective_enough_good: 'Enough va despues de good: good enough.',
  adjective_enough_old: 'Enough va despues de old: old enough.',
  adverb_enough_fast: 'Enough va despues de fast: fast enough.',
  enough_before_noun_time: 'Enough va antes de time: enough time.',
  enough_before_noun_money: 'Enough va antes de money: enough money.',
  not_enough_quality: 'No alcanza la calidad: not good enough.',
  too_many_plural: 'Con people usa too many people.',
  too_much_uncountable: 'Con noise usa too much noise.',
  too_to_structure: 'Demasiado para hacer algo: too tired to work.',
  mixed_too_enough_position: 'Too expensive, pero good enough.',
  mixed_enough_adjective_noun: 'Old enough, pero enough money.',
  mixed_sentence_correction: 'Too small y enough chairs.',
};

function withEs(
  copy: TriText,
  es: string,
  planned: Partial<Record<PlannedTrainingLocale, string>> = TOO_ENOUGH_NEEDS_REVIEW_PLANNED,
): TriText {
  const next: TriText = { ...copy, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    if (!next[locale] || next[locale]?.startsWith('needs-review:')) {
      next[locale] = planned[locale] ?? TOO_ENOUGH_NEEDS_REVIEW_PLANNED[locale];
    }
  }
  return next;
}

function tooEnoughEsFeedback(input: {
  targetSkill: string;
  correctAnswer: string;
  focusWords: string[];
}): string {
  const focus = input.focusWords.join(' / ');
  const hint = TOO_ENOUGH_SKILL_ES[input.targetSkill] ?? 'Decide si significa exceso o suficiente y revisa el orden.';
  return `Usa "${input.correctAnswer}"${focus ? ` con ${focus}` : ''}. ${hint}`;
}

function makeStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  sentence: string;
  translation: TriText;
  options: string[];
  correctAnswer: string;
  correctFeedback: TriText;
  wrong: Record<string, TriText>;
  clue: TriText;
  finalHint: TriText;
  focusWords: string[];
}): DiagnosisTrainingStep {
  const esFeedback = tooEnoughEsFeedback(input);
  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    translation: withEs(input.translation, esFeedback),
    explanationBlock: tri(
      'Too обычно значит “слишком”, то есть уже проблема: too hot, too expensive, too fast. Enough значит “достаточно”, но место меняется: good enough, old enough, enough time, enough chairs.',
      'Too зазвичай означає “занадто”, тобто вже проблема: too hot, too expensive, too fast. Enough означає “достатньо”, але місце змінюється: good enough, old enough, enough time, enough chairs.',
      'Too significa exceso: too hot. Enough significa suficiente: good enough, enough time.',
    ),
    microTask: tri(
      'Выбери живой кусок с too или enough.',
      'Обери живий шматок із too або enough.',
      'Elige el bloque natural con too o enough.',
    ),
    sentence: input.sentence,
    answerOptions: input.options.map((text) => ({ id: text, text })),
    correctAnswerId: input.correctAnswer,
    correctIndex: input.options.findIndex((option) => option === input.correctAnswer),
    correctFeedback: withEs(input.correctFeedback, esFeedback),
    wrongFeedbackByOption: Object.fromEntries(
      input.options
        .filter((option) => option !== input.correctAnswer)
        .map((option) => [
          option,
          withEs(input.wrong[option] ??
            tri(
              `Почти, но здесь нужен другой кусок: ${input.correctAnswer}.`,
              `Майже, але тут потрібен інший шматок: ${input.correctAnswer}.`,
              `Casi. Usa: ${input.correctAnswer}.`,
            ), esFeedback),
        ]),
    ),
    retryFeedback: [
      withEs(input.clue, esFeedback),
      tri(
        'Сначала поймай смысл: too = перебор и обычно проблема, enough = хватает. Потом проверь место: too стоит перед словом, которое усиливает, а enough часто идет после качества, но перед вещью.',
        'Спочатку злови сенс: too = перебір і зазвичай проблема, enough = вистачає. Потім перевір місце: too стоїть перед словом, яке підсилює, а enough часто йде після якості, але перед річчю.',
        'Too = demasiado y normalmente problema. Enough = suficiente. Revisa el orden.',
      ),
      withEs(input.finalHint, esFeedback),
      tri(
        'Теперь выбери вариант, где смысл и место слова совпадают.',
        'Тепер обери варіант, де сенс і місце слова збігаються.',
        `Respuesta: ${input.correctAnswer}.`,
      ),
    ],
    fallbackExplanation: tri(
      'Карта такая: too ставим перед качеством, когда есть перебор. Enough ставим после качества, но перед вещью. Much берем для массы, many - для отдельных штук.',
      'Карта така: too ставимо перед якістю, коли є перебір. Enough ставимо після якості, але перед річчю. Much беремо для маси, many - для окремих штук.',
      'Bloques: too hot, good enough, enough time, too much noise, too many people.',
    ),
    focusWords: input.focusWords,
  };
}

export const TOO_ENOUGH_TRAINING: DiagnosisTraining = {
  id: 'too_enough',
  category: 'modifier',
  version: '1.0.0',
  status: 'active',
  priority: 34,
  supportedLocales: ['ru', 'uk', 'es'],
  title: tri(
    'Too / Enough: слишком или достаточно',
    'Too / Enough: занадто чи достатньо',
    'Too / Enough',
    {
      'pt-BR': 'Too / Enough: demais ou suficiente',
      vi: 'Too / Enough: quá mức hay đủ',
      id: 'Too / Enough: terlalu atau cukup',
      tr: 'Too / Enough: fazla mı yeterli mi',
      pl: 'Too / Enough: za dużo czy wystarczająco',
    },
  ),
  shortTitle: tri('Too / Enough', 'Too / Enough', 'Too / Enough', {
    'pt-BR': 'Too / Enough',
    vi: 'Too / Enough',
    id: 'Too / Enough',
    tr: 'Too / Enough',
    pl: 'Too / Enough',
  }),
  shortDiagnosis: tri(
    'Ты смешиваешь “слишком” и “достаточно”, а еще ставишь enough не туда.',
    'Ти змішуєш “занадто” і “достатньо”, а ще ставиш enough не туди.',
    'Confundes demasiado y suficiente, y ademas pones enough en el lugar incorrecto.',
    {
      'pt-BR': 'Você mistura "demais" e "suficiente", e também coloca enough no lugar errado.',
      vi: 'Bạn nhầm giữa "quá mức" và "đủ", và còn đặt enough sai vị trí.',
      id: 'Kamu mencampuradukkan "terlalu" dan "cukup", dan juga meletakkan enough di posisi yang salah.',
      tr: '"Fazla" ile "yeterli" anlamlarını karıştırıyorsun ve enough kelimesini de yanlış yere koyuyorsun.',
      pl: 'Mylisz "za bardzo" z "wystarczająco", a do tego stawiasz enough w złym miejscu.',
    },
  ),
  diagnosisText: tri(
    'Too и enough ломаются в двух местах. Первое: смысл. Too обычно значит перебор: кофе слишком горячий, телефон слишком дорогой. Enough значит хватает: достаточно хороший, достаточно времени. Второе: место в фразе. Говорим too hot, но good enough. Говорим enough time, а не time enough.',
    'Too і enough ламаються у двох місцях. Перше: сенс. Too зазвичай означає перебір: кава занадто гаряча, телефон занадто дорогий. Enough означає вистачає: достатньо хороший, достатньо часу. Друге: місце у фразі. Кажемо too hot, але good enough. Кажемо enough time, а не time enough.',
    'Too y enough se rompen en dos sitios: sentido y orden de palabras.',
    {
      'pt-BR': 'Too e enough quebram em dois pontos. Primeiro: o sentido. Too geralmente marca excesso: o café está quente demais, o telefone é caro demais. Enough significa que basta: bom o suficiente, tempo suficiente. Segundo: a posição na frase. Dizemos too hot, mas good enough. Dizemos enough time, não time enough.',
      vi: 'Too và enough thường sai ở hai chỗ. Thứ nhất: ý nghĩa. Too thường nghĩa là quá mức: cà phê quá nóng, điện thoại quá đắt. Enough nghĩa là đủ: đủ tốt, đủ thời gian. Thứ hai: vị trí trong câu. Ta nói too hot, nhưng good enough. Ta nói enough time, không phải time enough.',
      id: 'Too dan enough sering rusak di dua tempat. Pertama: makna. Too biasanya berarti berlebihan: kopinya terlalu panas, ponselnya terlalu mahal. Enough berarti cukup: cukup bagus, cukup waktu. Kedua: posisi dalam frasa. Kita mengatakan too hot, tetapi good enough. Kita mengatakan enough time, bukan time enough.',
      tr: 'Too ve enough iki yerde bozulur. Birincisi anlamdır. Too genellikle aşırılık demektir: kahve fazla sıcak, telefon fazla pahalı. Enough yeterli olduğunu gösterir: yeterince iyi, yeterince zaman. İkincisi cümledeki yerdir. Too hot deriz, ama good enough deriz. Enough time deriz, time enough değil.',
      pl: 'Too i enough psują się w dwóch miejscach. Pierwsze to sens. Too zwykle oznacza nadmiar: kawa jest za gorąca, telefon za drogi. Enough znaczy, że wystarcza: wystarczająco dobry, wystarczająco dużo czasu. Drugie to miejsce w zdaniu. Mówimy too hot, ale good enough. Mówimy enough time, nie time enough.',
    },
  ),
  mentalModel: tri(
    'Запомни четыре полки: too hot — перебор. good enough — качества хватает. enough time — времени хватает. too many people / too much noise — слишком много, но выбор зависит от слова после.',
    'Запамʼятай чотири полиці: too hot — перебір. good enough — якості вистачає. enough time — часу вистачає. too many people / too much noise — занадто багато, але вибір залежить від слова після.',
    'Cuatro bloques: too hot, good enough, enough time, too many people / too much noise.',
    {
      'pt-BR': 'Guarde quatro prateleiras: too hot = excesso. good enough = a qualidade basta. enough time = o tempo basta. too many people / too much noise = demais, mas a escolha depende da palavra depois.',
      vi: 'Hãy nhớ bốn nhóm: too hot = quá mức. good enough = chất lượng đã đủ. enough time = thời gian đã đủ. too many people / too much noise = quá nhiều, nhưng lựa chọn phụ thuộc vào từ phía sau.',
      id: 'Ingat empat rak: too hot = berlebihan. good enough = kualitasnya cukup. enough time = waktunya cukup. too many people / too much noise = terlalu banyak, tetapi pilihannya bergantung pada kata setelahnya.',
      tr: 'Dört rafı aklında tut: too hot = aşırılık. good enough = kalite yeterli. enough time = zaman yeterli. too many people / too much noise = çok fazla, ama seçim sonraki kelimeye bağlıdır.',
      pl: 'Zapamiętaj cztery półki: too hot = nadmiar. good enough = jakość wystarcza. enough time = czasu wystarcza. too many people / too much noise = za dużo, ale wybór zależy od następnego słowa.',
    },
  ),
  contrastSet: CONTRAST,
  coreRule: tri(
    'Too значит перебор и обычно стоит перед качеством. Enough значит хватает: после качества, но перед вещью. Для "слишком много" выбираем much или many по типу слова.',
    'Too означає перебір і зазвичай стоїть перед якістю. Enough означає вистачає: після якості, але перед річчю. Для "занадто багато" обираємо much або many за типом слова.',
    'Too hot. Good enough. Enough time. Too much noise. Too many people.',
    {
      'pt-BR': 'Too marca excesso e geralmente vem antes da qualidade. Enough significa que basta: depois da qualidade, mas antes da coisa. Para "demais", escolha much ou many pelo tipo da palavra.',
      vi: 'Too chỉ sự quá mức và thường đứng trước tính chất. Enough nghĩa là đủ: đứng sau tính chất, nhưng trước sự vật. Với "quá nhiều", chọn much hoặc many theo loại từ.',
      id: 'Too berarti berlebihan dan biasanya berada sebelum kualitas. Enough berarti cukup: setelah kualitas, tetapi sebelum benda. Untuk "terlalu banyak", pilih much atau many sesuai jenis katanya.',
      tr: 'Too aşırılık gösterir ve genellikle niteliğin önünde durur. Enough yeterli demektir: nitelikten sonra, ama isimden önce. "Çok fazla" için kelimenin türüne göre much ya da many seç.',
      pl: 'Too oznacza nadmiar i zwykle stoi przed cechą. Enough znaczy, że wystarcza: po cesze, ale przed rzeczą. Dla "za dużo" wybieramy much albo many według typu słowa.',
    },
  ),
  whatUserMustLearn: {
    ru: [
      'Too часто показывает перебор, который мешает: too hot, too expensive, too fast.',
      'Enough после качества: good enough, old enough, fast enough.',
      'Enough перед вещью: enough money, enough time, enough chairs.',
      'Not enough значит “не хватает”: not enough time, not good enough.',
      'Too much подходит к шуму, воде, времени: too much noise, too much water.',
      'Too many подходит к людям, вопросам, стульям: too many people, too many questions.',
      'Too ... to часто значит “слишком ..., чтобы ...”: too tired to work.',
      'Не enough good. Нормально: good enough.',
      'Не time enough в базовой фразе. Нормально: enough time.',
    ],
    uk: [
      'Too часто показує перебір, який заважає: too hot, too expensive, too fast.',
      'Enough після якості: good enough, old enough, fast enough.',
      'Enough перед річчю: enough money, enough time, enough chairs.',
      'Not enough означає “не вистачає”: not enough time, not good enough.',
      'Too much підходить до шуму, води, часу: too much noise, too much water.',
      'Too many підходить до людей, питань, стільців: too many people, too many questions.',
      'Too ... to часто означає “занадто ..., щоб ...”: too tired to work.',
      'Не enough good. Нормально: good enough.',
      'Не time enough у базовій фразі. Нормально: enough time.',
    ],
    es: [
      'Too suele significar exceso: too hot, too expensive.',
      'Enough va despues de palabras de cualidad: good enough, old enough.',
      'Enough va antes de cosas: enough time, enough chairs.',
      'Not enough significa insuficiente.',
      'Too much: too much noise.',
      'Too many: too many people.',
    ],
    'pt-BR': [
      'Too muitas vezes significa excesso: too hot, too expensive.',
      'Enough vem depois de palavras de qualidade: good enough, old enough.',
      'Enough vem antes de coisas: enough time, enough chairs.',
      'Not enough significa insuficiente.',
      'Too much: too much noise.',
      'Too many: too many people.',
    ],
    vi: [
      'Too thường nghĩa là quá mức: too hot, too expensive.',
      'Enough đứng sau từ chỉ chất lượng: good enough, old enough.',
      'Enough đứng trước danh từ/sự vật: enough time, enough chairs.',
      'Not enough nghĩa là không đủ.',
      'Too much: too much noise.',
      'Too many: too many people.',
    ],
    id: [
      'Too sering berarti berlebihan: too hot, too expensive.',
      'Enough berada setelah kata sifat/kualitas: good enough, old enough.',
      'Enough berada sebelum benda: enough time, enough chairs.',
      'Not enough berarti tidak cukup.',
      'Too much: too much noise.',
      'Too many: too many people.',
    ],
    tr: [
      'Too çoğu zaman aşırılık demektir: too hot, too expensive.',
      'Enough nitelik kelimelerinden sonra gelir: good enough, old enough.',
      'Enough isimlerden önce gelir: enough time, enough chairs.',
      'Not enough yetersiz demektir.',
      'Too much: too much noise.',
      'Too many: too many people.',
    ],
    pl: [
      'Too często oznacza nadmiar: too hot, too expensive.',
      'Enough stoi po słowach jakości: good enough, old enough.',
      'Enough stoi przed rzeczami: enough time, enough chairs.',
      'Not enough oznacza niewystarczająco.',
      'Too much: too much noise.',
      'Too many: too many people.',
    ],
  },
  examples: [
    {
      en: 'This coffee is too hot.',
      ru: 'Этот кофе слишком горячий.',
      uk: 'Ця кава занадто гаряча.',
      es: 'Este cafe esta demasiado caliente.',
      'pt-BR': 'Este café está quente demais.',
      vi: 'Cà phê này quá nóng.',
      id: 'Kopi ini terlalu panas.',
      tr: 'Bu kahve çok sıcak.',
      pl: 'Ta kawa jest za gorąca.',
      why: tri('Too hot = перебор, пить неудобно.', 'Too hot = перебір, пити незручно.', 'Too hot significa exceso.'),
    },
    {
      en: 'This coffee is hot enough.',
      ru: 'Этот кофе достаточно горячий.',
      uk: 'Ця кава достатньо гаряча.',
      es: 'Este cafe esta suficientemente caliente.',
      'pt-BR': 'Este café está quente o suficiente.',
      vi: 'Cà phê này đủ nóng.',
      id: 'Kopi ini cukup panas.',
      tr: 'Bu kahve yeterince sıcak.',
      pl: 'Ta kawa jest wystarczająco gorąca.',
      why: tri('Enough стоит после hot: hot enough.', 'Enough стоїть після hot: hot enough.', 'Enough va despues de hot.'),
    },
    {
      en: "I don't have enough time.",
      ru: 'У меня недостаточно времени.',
      uk: 'У мене недостатньо часу.',
      es: 'No tengo suficiente tiempo.',
      'pt-BR': 'Não tenho tempo suficiente.',
      vi: 'Tôi không có đủ thời gian.',
      id: 'Saya tidak punya cukup waktu.',
      tr: 'Yeterince zamanım yok.',
      pl: 'Nie mam wystarczająco dużo czasu.',
      why: tri('Enough стоит перед time: enough time.', 'Enough стоїть перед time: enough time.', 'Enough va antes de time.'),
    },
    {
      en: 'She is old enough to drive.',
      ru: 'Она достаточно взрослая, чтобы водить.',
      uk: 'Вона достатньо доросла, щоб водити.',
      es: 'Ella tiene edad suficiente para conducir.',
      'pt-BR': 'Ela tem idade suficiente para dirigir.',
      vi: 'Cô ấy đủ tuổi để lái xe.',
      id: 'Dia cukup umur untuk mengemudi.',
      tr: 'Araba kullanacak kadar büyük.',
      pl: 'Ona jest wystarczająco dorosła, żeby prowadzić.',
      why: tri('Enough стоит после old: old enough.', 'Enough стоїть після old: old enough.', 'Old enough.'),
    },
    {
      en: 'He is too tired to work.',
      ru: 'Он слишком устал, чтобы работать.',
      uk: 'Він занадто втомлений, щоб працювати.',
      es: 'Esta demasiado cansado para trabajar.',
      'pt-BR': 'Ele está cansado demais para trabalhar.',
      vi: 'Anh ấy quá mệt để làm việc.',
      id: 'Dia terlalu lelah untuk bekerja.',
      tr: 'Çalışamayacak kadar yorgun.',
      pl: 'On jest zbyt zmęczony, żeby pracować.',
      why: tri('Too tired to work = устал настолько, что работать не может.', 'Too tired to work = втомився настільки, що не може працювати.', 'Too tired to work significa que esta tan cansado que no puede trabajar.'),
    },
    {
      en: 'There are too many people here.',
      ru: 'Здесь слишком много людей.',
      uk: 'Тут занадто багато людей.',
      es: 'Hay demasiada gente aqui.',
      'pt-BR': 'Há gente demais aqui.',
      vi: 'Ở đây có quá nhiều người.',
      id: 'Ada terlalu banyak orang di sini.',
      tr: 'Burada çok fazla insan var.',
      pl: 'Jest tu za dużo ludzi.',
      why: tri('С people нужен блок too many people.', 'З people потрібен блок too many people.', 'Con people usa too many people.'),
    },
    {
      en: 'There is too much noise.',
      ru: 'Слишком много шума.',
      uk: 'Занадто багато шуму.',
      es: 'Hay demasiado ruido.',
      'pt-BR': 'Há barulho demais.',
      vi: 'Có quá nhiều tiếng ồn.',
      id: 'Terlalu banyak suara bising.',
      tr: 'Çok fazla gürültü var.',
      pl: 'Jest za dużo hałasu.',
      why: tri('С noise нужен блок too much noise.', 'З noise потрібен блок too much noise.', 'Con noise usa too much noise.'),
    },
    {
      en: 'This answer is not good enough.',
      ru: 'Этот ответ недостаточно хороший.',
      uk: 'Ця відповідь недостатньо хороша.',
      es: 'Esta respuesta no es suficientemente buena.',
      'pt-BR': 'Esta resposta não é boa o suficiente.',
      vi: 'Câu trả lời này chưa đủ tốt.',
      id: 'Jawaban ini tidak cukup baik.',
      tr: 'Bu cevap yeterince iyi değil.',
      pl: 'Ta odpowiedź nie jest wystarczająco dobra.',
      why: tri('Not good enough = качества не хватает.', 'Not good enough = якості не вистачає.', 'Not good enough significa que falta calidad.'),
    },
  ],
  introBlocks: [
    {
      id: 'intro_problem',
      type: 'diagnosis',
      text: tri(
        'Похоже, ты видишь смысл, но путаешь два разных вопроса: это слишком много или этого хватает?',
        'Схоже, ти бачиш сенс, але плутаєш два різні питання: цього занадто багато чи цього вистачає?',
        'Mezclas dos preguntas distintas: si algo es demasiado o si ya es suficiente.',
      ),
    },
    {
      id: 'intro_rule',
      type: 'rule',
      text: tri(
        'Главная карта: too перед качеством, enough после качества, enough перед вещью.',
        'Головна карта: too перед якістю, enough після якості, enough перед річчю.',
        'Mapa principal: too antes de la cualidad; enough despues de la cualidad, pero antes del objeto.',
      ),
    },
    {
      id: 'intro_word_order',
      type: 'contrast',
      text: tri(
        'Проверка в два шага: сначала смысл - перебор или хватает. Потом место: too перед качеством, enough после качества, но перед вещью.',
        'Перевірка у два кроки: спочатку сенс - перебір чи вистачає. Потім місце: too перед якістю, enough після якості, але перед річчю.',
        'Comprueba en dos pasos: primero el sentido, despues la posicion. Too va antes de la cualidad; enough va despues de la cualidad, pero antes del sustantivo.',
      ),
    },
  ],
  steps: [
    makeStep({
      id: 'too_enough_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'too_adjective_hot',
      sentence: 'This coffee is ___ hot.',
      translation: tri('Этот кофе слишком горячий.', 'Ця кава занадто гаряча.', 'This coffee is too hot.'),
      options: ['too', 'enough', 'too much', 'many'],
      correctAnswer: 'too',
      correctFeedback: tri('Да. Слишком горячий = too hot.', 'Так. Занадто гаряча = too hot.', 'Yes. Too hot.'),
      wrong: {
        enough: tri('Enough значит “достаточно”, а здесь перебор. Нужен кусок too hot.', 'Enough означає “достатньо”, а тут перебір. Потрібен шматок too hot.', 'Use too hot.'),
        'too much': tri('Too much не ставим перед hot. Нормально: too hot.', 'Too much не ставимо перед hot. Нормально: too hot.', 'Use too hot.'),
        many: tri('Many здесь вообще не подходит. Горячий кофе = too hot.', 'Many тут взагалі не підходить. Гаряча кава = too hot.', 'Use too hot.'),
      },
      clue: tri('Перебор по температуре: too hot.', 'Перебір за температурою: too hot.', 'Too hot.'),
      finalHint: tri('Фраза: This coffee is too hot.', 'Фраза: This coffee is too hot.', 'Sentence: This coffee is too hot.'),
      focusWords: ['too', 'hot'],
    }),
    makeStep({
      id: 'too_enough_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'too_adjective_expensive',
      sentence: 'This phone is ___ expensive.',
      translation: tri('Этот телефон слишком дорогой.', 'Цей телефон занадто дорогий.', 'This phone is too expensive.'),
      options: ['too', 'enough', 'too many', 'many'],
      correctAnswer: 'too',
      correctFeedback: tri('Да. Слишком дорогой = too expensive.', 'Так. Занадто дорогий = too expensive.', 'Yes. Too expensive.'),
      wrong: {
        enough: tri('Enough expensive не звучит естественно и не дает смысл “слишком”. Нужно too expensive.', 'Enough expensive не звучить природно і не дає сенс “занадто”. Потрібно too expensive.', 'Use too expensive.'),
        'too many': tri('Too many не ставим перед expensive. Нормально: too expensive.', 'Too many не ставимо перед expensive. Нормально: too expensive.', 'Use too expensive.'),
        many: tri('Many не подходит к expensive. Нужен кусок too expensive.', 'Many не підходить до expensive. Потрібен шматок too expensive.', 'Use too expensive.'),
      },
      clue: tri('Перебор по цене: too expensive.', 'Перебір за ціною: too expensive.', 'Too expensive.'),
      finalHint: tri('Фраза: This phone is too expensive.', 'Фраза: This phone is too expensive.', 'Sentence: This phone is too expensive.'),
      focusWords: ['too', 'expensive'],
    }),
    makeStep({
      id: 'too_enough_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'too_adverb_fast',
      sentence: 'You are speaking ___ fast.',
      translation: tri('Ты говоришь слишком быстро.', 'Ти говориш занадто швидко.', 'You are speaking too fast.'),
      options: ['too', 'enough', 'too many', 'many'],
      correctAnswer: 'too',
      correctFeedback: tri('Да. Слишком быстро = too fast.', 'Так. Занадто швидко = too fast.', 'Yes. Too fast.'),
      wrong: {
        enough: tri('Fast enough значит “достаточно быстро”. Здесь смысл “слишком быстро”: too fast.', 'Fast enough означає “достатньо швидко”. Тут сенс “занадто швидко”: too fast.', 'Use too fast.'),
        'too many': tri('Too many здесь не подходит. Нужен короткий блок too fast.', 'Too many тут не підходить. Потрібен короткий блок too fast.', 'Use too fast.'),
        many: tri('Many не работает с fast. Нужен too fast.', 'Many не працює з fast. Потрібен too fast.', 'Use too fast.'),
      },
      clue: tri('Перебор по скорости: too fast.', 'Перебір за швидкістю: too fast.', 'Too fast.'),
      finalHint: tri('Фраза: You are speaking too fast.', 'Фраза: You are speaking too fast.', 'Sentence: You are speaking too fast.'),
      focusWords: ['too', 'fast'],
    }),
    makeStep({
      id: 'too_enough_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'adjective_enough_good',
      sentence: 'This answer is good ___.',
      translation: tri('Этот ответ достаточно хороший.', 'Ця відповідь достатньо хороша.', 'This answer is good enough.'),
      options: ['enough', 'too', 'enough good', 'many'],
      correctAnswer: 'enough',
      correctFeedback: tri('Да. Достаточно хороший = good enough.', 'Так. Достатньо хороша = good enough.', 'Yes. Good enough.'),
      wrong: {
        too: tri('Good too не дает смысл “достаточно хороший”. Нужен good enough.', 'Good too не дає сенс “достатньо хороша”. Потрібен good enough.', 'Use good enough.'),
        'enough good': tri('Enough good звучит наоборот. Нормальный порядок: good enough.', 'Enough good звучить навпаки. Нормальний порядок: good enough.', 'Use good enough.'),
        many: tri('Many здесь не подходит. Нужен good enough.', 'Many тут не підходить. Потрібен good enough.', 'Use good enough.'),
      },
      clue: tri('Enough идет после good: good enough.', 'Enough іде після good: good enough.', 'Good enough.'),
      finalHint: tri('Фраза: This answer is good enough.', 'Фраза: This answer is good enough.', 'Sentence: This answer is good enough.'),
      focusWords: ['good enough', 'enough'],
    }),
    makeStep({
      id: 'too_enough_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'adjective_enough_old',
      sentence: 'She is old ___ to drive.',
      translation: tri('Она достаточно взрослая, чтобы водить.', 'Вона достатньо доросла, щоб водити.', 'She is old enough to drive.'),
      options: ['enough', 'too', 'enough old', 'many'],
      correctAnswer: 'enough',
      correctFeedback: tri('Да. Достаточно взрослая = old enough.', 'Так. Достатньо доросла = old enough.', 'Yes. Old enough.'),
      wrong: {
        too: tri('Too old to drive значит “слишком старая, чтобы водить”. Здесь нужно old enough to drive.', 'Too old to drive означає “занадто стара, щоб водити”. Тут потрібно old enough to drive.', 'Use old enough.'),
        'enough old': tri('Enough old звучит наоборот. Нормально: old enough.', 'Enough old звучить навпаки. Нормально: old enough.', 'Use old enough.'),
        many: tri('Many здесь не подходит. Нужен old enough.', 'Many тут не підходить. Потрібен old enough.', 'Use old enough.'),
      },
      clue: tri('Enough идет после old: old enough.', 'Enough іде після old: old enough.', 'Old enough.'),
      finalHint: tri('Фраза: She is old enough to drive.', 'Фраза: She is old enough to drive.', 'Sentence: She is old enough to drive.'),
      focusWords: ['old enough', 'enough'],
    }),
    makeStep({
      id: 'too_enough_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'adverb_enough_fast',
      sentence: 'You are not speaking fast ___.',
      translation: tri('Ты говоришь недостаточно быстро.', 'Ти говориш недостатньо швидко.', 'You are not speaking fast enough.'),
      options: ['enough', 'too', 'enough fast', 'many'],
      correctAnswer: 'enough',
      correctFeedback: tri('Да. Недостаточно быстро = not fast enough.', 'Так. Недостатньо швидко = not fast enough.', 'Yes. Fast enough.'),
      wrong: {
        too: tri('Too fast значит “слишком быстро”. Здесь “не хватает скорости”: not fast enough.', 'Too fast означає “занадто швидко”. Тут “не вистачає швидкості”: not fast enough.', 'Use fast enough.'),
        'enough fast': tri('Enough fast звучит наоборот. Нормально: fast enough.', 'Enough fast звучить навпаки. Нормально: fast enough.', 'Use fast enough.'),
        many: tri('Many здесь не подходит. Нужен fast enough.', 'Many тут не підходить. Потрібен fast enough.', 'Use fast enough.'),
      },
      clue: tri('Enough идет после fast: fast enough.', 'Enough іде після fast: fast enough.', 'Fast enough.'),
      finalHint: tri('Фраза: You are not speaking fast enough.', 'Фраза: You are not speaking fast enough.', 'Sentence: You are not speaking fast enough.'),
      focusWords: ['fast enough', 'not enough'],
    }),
    makeStep({
      id: 'too_enough_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'enough_before_noun_time',
      sentence: "I don't have ___ time.",
      translation: tri('У меня недостаточно времени.', 'У мене недостатньо часу.', "I don't have enough time."),
      options: ['enough', 'time enough', 'too', 'many'],
      correctAnswer: 'enough',
      correctFeedback: tri('Да. С time порядок: enough time.', 'Так. З time порядок: enough time.', 'Yes. Enough time.'),
      wrong: {
        'time enough': tri('Time enough в базовой фразе звучит наоборот. Нужен порядок enough time.', 'Time enough у базовій фразі звучить навпаки. Потрібен порядок enough time.', 'Use enough time.'),
        too: tri('Too time не работает. Если времени хватает или не хватает, нужен блок enough time.', 'Too time не працює. Якщо часу вистачає або не вистачає, потрібен блок enough time.', 'Use enough time.'),
        many: tri('Many не подходит к time. Нужен enough time.', 'Many не підходить до time. Потрібен enough time.', 'Use enough time.'),
      },
      clue: tri('Enough стоит перед time: enough time.', 'Enough стоїть перед time: enough time.', 'Enough time.'),
      finalHint: tri("Фраза: I don't have enough time.", "Фраза: I don't have enough time.", "Sentence: I don't have enough time."),
      focusWords: ['enough time', 'time'],
    }),
    makeStep({
      id: 'too_enough_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'enough_before_noun_money',
      sentence: 'We have ___ money.',
      translation: tri('У нас достаточно денег.', 'У нас достатньо грошей.', 'We have enough money.'),
      options: ['enough', 'money enough', 'too', 'many'],
      correctAnswer: 'enough',
      correctFeedback: tri('Да. С money порядок: enough money.', 'Так. З money порядок: enough money.', 'Yes. Enough money.'),
      wrong: {
        'money enough': tri('Money enough в базовой фразе звучит наоборот. Нужен порядок enough money.', 'Money enough у базовій фразі звучить навпаки. Потрібен порядок enough money.', 'Use enough money.'),
        too: tri('Too money не работает. Нужен enough money.', 'Too money не працює. Потрібен enough money.', 'Use enough money.'),
        many: tri('Many money не звучит нормально. Нужен enough money.', 'Many money не звучить нормально. Потрібен enough money.', 'Use enough money.'),
      },
      clue: tri('Enough стоит перед money: enough money.', 'Enough стоїть перед money: enough money.', 'Enough money.'),
      finalHint: tri('Фраза: We have enough money.', 'Фраза: We have enough money.', 'Sentence: We have enough money.'),
      focusWords: ['enough money', 'money'],
    }),
    makeStep({
      id: 'too_enough_contrast_006',
      order: 9,
      difficulty: 'contrast',
      targetSkill: 'not_enough_quality',
      sentence: 'This answer is not good ___.',
      translation: tri('Этот ответ недостаточно хороший.', 'Ця відповідь недостатньо хороша.', 'This answer is not good enough.'),
      options: ['enough', 'too', 'enough good', 'many'],
      correctAnswer: 'enough',
      correctFeedback: tri('Да. Не достаточно хороший = not good enough.', 'Так. Не достатньо хороша = not good enough.', 'Yes. Not good enough.'),
      wrong: {
        too: tri('Not good too не дает нужный смысл. Нужен блок not good enough.', 'Not good too не дає потрібний сенс. Потрібен блок not good enough.', 'Use not good enough.'),
        'enough good': tri('Enough good звучит наоборот. Нормально: not good enough.', 'Enough good звучить навпаки. Нормально: not good enough.', 'Use not good enough.'),
        many: tri('Many здесь не подходит. Нужен not good enough.', 'Many тут не підходить. Потрібен not good enough.', 'Use not good enough.'),
      },
      clue: tri('Not + good enough.', 'Not + good enough.', 'Not good enough.'),
      finalHint: tri('Фраза: This answer is not good enough.', 'Фраза: This answer is not good enough.', 'Sentence: This answer is not good enough.'),
      focusWords: ['not good enough'],
    }),
    makeStep({
      id: 'too_enough_mixed_001',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'too_many_plural',
      sentence: 'There are ___ people here.',
      translation: tri('Здесь слишком много людей.', 'Тут занадто багато людей.', 'There are too many people here.'),
      options: ['too many', 'too much', 'enough', 'many enough'],
      correctAnswer: 'too many',
      correctFeedback: tri('Да. С people нужен блок too many people.', 'Так. З people потрібен блок too many people.', 'Yes. Too many people.'),
      wrong: {
        'too much': tri('Too much people звучит неправильно. С people нужен блок too many people.', 'Too much people звучить неправильно. З people потрібен блок too many people.', 'Use too many people.'),
        enough: tri('Enough people значит “достаточно людей”. Здесь перебор: too many people.', 'Enough people означає “достатньо людей”. Тут перебір: too many people.', 'Use too many people.'),
        'many enough': tri('Many enough people здесь не работает. Нужен блок too many people.', 'Many enough people тут не працює. Потрібен блок too many people.', 'Use too many people.'),
      },
      clue: tri('Людей слишком много: too many people.', 'Людей занадто багато: too many people.', 'Too many people.'),
      finalHint: tri('Фраза: There are too many people here.', 'Фраза: There are too many people here.', 'Sentence: There are too many people here.'),
      focusWords: ['too many', 'people'],
    }),
    makeStep({
      id: 'too_enough_mixed_002',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'too_much_uncountable',
      sentence: 'There is ___ noise.',
      translation: tri('Слишком много шума.', 'Занадто багато шуму.', 'There is too much noise.'),
      options: ['too much', 'too many', 'enough', 'many'],
      correctAnswer: 'too much',
      correctFeedback: tri('Да. С noise нужен блок too much noise.', 'Так. З noise потрібен блок too much noise.', 'Yes. Too much noise.'),
      wrong: {
        'too many': tri('Too many noise звучит неправильно. С noise нужен блок too much noise.', 'Too many noise звучить неправильно. З noise потрібен блок too much noise.', 'Use too much noise.'),
        enough: tri('Enough noise значит “достаточно шума”. Здесь перебор: too much noise.', 'Enough noise означає “достатньо шуму”. Тут перебір: too much noise.', 'Use too much noise.'),
        many: tri('Many noise не звучит нормально. Нужен too much noise.', 'Many noise не звучить нормально. Потрібен too much noise.', 'Use too much noise.'),
      },
      clue: tri('Шума слишком много: too much noise.', 'Шуму занадто багато: too much noise.', 'Too much noise.'),
      finalHint: tri('Фраза: There is too much noise.', 'Фраза: There is too much noise.', 'Sentence: There is too much noise.'),
      focusWords: ['too much', 'noise'],
    }),
    makeStep({
      id: 'too_enough_mixed_003',
      order: 12,
      difficulty: 'mixed',
      targetSkill: 'too_to_structure',
      sentence: 'He is ___ tired to work.',
      translation: tri('Он слишком устал, чтобы работать.', 'Він занадто втомлений, щоб працювати.', 'He is too tired to work.'),
      options: ['too', 'enough', 'too much', 'many'],
      correctAnswer: 'too',
      correctFeedback: tri('Да. Слишком устал, чтобы работать = too tired to work.', 'Так. Занадто втомлений, щоб працювати = too tired to work.', 'Yes. Too tired to work.'),
      wrong: {
        enough: tri('Tired enough to work значит, что сил хватает. Здесь наоборот: too tired to work.', 'Tired enough to work означає, що сил вистачає. Тут навпаки: too tired to work.', 'Use too tired to work.'),
        'too much': tri('Too much tired не звучит нормально. Нужен блок too tired.', 'Too much tired не звучить нормально. Потрібен блок too tired.', 'Use too tired.'),
        many: tri('Many не подходит к tired. Нужен too tired.', 'Many не підходить до tired. Потрібен too tired.', 'Use too tired.'),
      },
      clue: tri('Слишком устал, чтобы работать: too tired to work.', 'Занадто втомлений, щоб працювати: too tired to work.', 'Too tired to work.'),
      finalHint: tri('Фраза: He is too tired to work.', 'Фраза: He is too tired to work.', 'Sentence: He is too tired to work.'),
      focusWords: ['too tired', 'too ... to'],
    }),
    makeStep({
      id: 'too_enough_mixed_004',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_too_enough_position',
      sentence: 'Choose the natural pair.',
      translation: tri('Выбери естественную пару.', 'Обери природну пару.', 'Choose the natural pair.'),
      options: ['too expensive / good enough', 'expensive too / enough good', 'too expensive / enough good', 'expensive enough / too good'],
      correctAnswer: 'too expensive / good enough',
      correctFeedback: tri('Да. Too expensive и good enough.', 'Так. Too expensive і good enough.', 'Yes. Too expensive / good enough.'),
      wrong: {
        'expensive too / enough good': tri('Оба порядка перепутаны. Нужно too expensive / good enough.', 'Обидва порядки переплутані. Потрібно too expensive / good enough.', 'Use too expensive / good enough.'),
        'too expensive / enough good': tri('Too expensive верно, но enough good нет. Нужен good enough.', 'Too expensive правильно, але enough good ні. Потрібен good enough.', 'Use good enough.'),
        'expensive enough / too good': tri('Эта пара меняет смысл. Для “слишком дорого / достаточно хорошо” нужно too expensive / good enough.', 'Ця пара змінює сенс. Для “занадто дорого / достатньо добре” потрібно too expensive / good enough.', 'Use too expensive / good enough.'),
      },
      clue: tri('Too expensive. Good enough.', 'Too expensive. Good enough.', 'Too expensive. Good enough.'),
      finalHint: tri('Пара: too expensive / good enough.', 'Пара: too expensive / good enough.', 'Pair: too expensive / good enough.'),
      focusWords: ['too expensive', 'good enough'],
    }),
    makeStep({
      id: 'too_enough_mixed_005',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_enough_adjective_noun',
      sentence: 'Choose the natural pair.',
      translation: tri('Выбери естественную пару.', 'Обери природну пару.', 'Choose the natural pair.'),
      options: ['old enough / enough money', 'enough old / money enough', 'old enough / money enough', 'enough old / enough money'],
      correctAnswer: 'old enough / enough money',
      correctFeedback: tri('Да. Old enough, но enough money.', 'Так. Old enough, але enough money.', 'Yes. Old enough / enough money.'),
      wrong: {
        'enough old / money enough': tri('Оба порядка перепутаны. Нужно old enough / enough money.', 'Обидва порядки переплутані. Потрібно old enough / enough money.', 'Use old enough / enough money.'),
        'old enough / money enough': tri('Old enough верно, но money enough нет. Нужен порядок enough money.', 'Old enough правильно, але money enough ні. Потрібен порядок enough money.', 'Use enough money.'),
        'enough old / enough money': tri('Enough money верно, но enough old нет. Нужен порядок old enough.', 'Enough money правильно, але enough old ні. Потрібен порядок old enough.', 'Use old enough.'),
      },
      clue: tri('Old enough. Enough money.', 'Old enough. Enough money.', 'Old enough. Enough money.'),
      finalHint: tri('Пара: old enough / enough money.', 'Пара: old enough / enough money.', 'Pair: old enough / enough money.'),
      focusWords: ['old enough', 'enough money'],
    }),
    makeStep({
      id: 'too_enough_mixed_006',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_sentence_correction',
      sentence: 'Choose the natural sentence.',
      translation: tri('Выбери естественное предложение.', 'Обери природне речення.', 'Choose the natural sentence.'),
      options: [
        "The room is too small, and we don't have enough chairs.",
        "The room is small too, and we don't have chairs enough.",
        "The room is enough small, and we don't have too chairs.",
        "The room is too much small, and we don't have many enough chairs.",
      ],
      correctAnswer: "The room is too small, and we don't have enough chairs.",
      correctFeedback: tri('Да. Too small и enough chairs.', 'Так. Too small і enough chairs.', 'Yes. Too small / enough chairs.'),
      wrong: {
        "The room is small too, and we don't have chairs enough.": tri('Порядок сломан в двух местах. Нужно too small / enough chairs.', 'Порядок зламаний у двох місцях. Потрібно too small / enough chairs.', 'Use too small / enough chairs.'),
        "The room is enough small, and we don't have too chairs.": tri('Enough small и too chairs не звучат нормально. Нужно too small / enough chairs.', 'Enough small і too chairs не звучать нормально. Потрібно too small / enough chairs.', 'Use too small / enough chairs.'),
        "The room is too much small, and we don't have many enough chairs.": tri('Здесь смешались две ошибки: too не требует much перед качеством, а enough перед вещью ставится отдельно. Нужно: too small / enough chairs.', 'Тут змішалися дві помилки: too не потребує much перед якістю, а enough перед річчю ставиться окремо.', 'Use too small / enough chairs.'),
      },
      clue: tri('Too small. Enough chairs.', 'Too small. Enough chairs.', 'Too small. Enough chairs.'),
      finalHint: tri('В первой части есть перебор по размеру, во второй - нехватка стульев.', 'У першій частині є перебір за розміром, у другій - нестача стільців.', "Sentence: The room is too small, and we don't have enough chairs."),
      focusWords: ['too small', 'enough chairs'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'enough_before_quality_error',
      'enough_after_thing_error',
      'too_after_quality_error',
      'too_enough_meaning_confusion',
      'too_much_many_confusion',
      'not_enough_position_error',
      'too_to_structure_error',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri('Сначала отделяем смысл: перебор или хватает.', 'Спочатку відділяємо сенс: перебір чи вистачає.', 'Primero separa el sentido: exceso o suficiente.'),
    depth2: tri('Потом порядок: too перед качеством, enough после качества или перед вещью.', 'Потім порядок: too перед якістю, enough після якості або перед річчю.', 'Despues revisa el orden: too hot, good enough, enough time.'),
    depth3: tri('Для “слишком много” выбираем much для массы и many для отдельных штук.', 'Для “занадто багато” обираємо much для маси і many для окремих штук.', 'Para demasiado: too much noise, too many people.'),
    depth4: tri('Почти подсказка: держи готовую пару из задания.', 'Майже підказка: тримай готову пару із завдання.', 'Usa el bloque que ya aparece en la tarea.'),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri(
        'Карта: too перед качеством; enough после качества, но перед вещью; much для массы, many для отдельных штук.',
        'Карта: too перед якістю; enough після якості, але перед річчю; much для маси, many для окремих штук.',
        'Mapa: too hot, good enough, enough time, too much noise, too many people.',
      ),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_word_type_hint_then_retry',
      card: tri(
        'Подсказка покажет, что стоит рядом с too/enough, но ответ все равно выбираешь ты.',
        'Підказка покаже, що стоїть поруч із too/enough, але відповідь усе одно обираєш ти.',
        'La pista muestra la palabra vecina, pero la respuesta la eliges tu.',
      ),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri(
        'Включаем пошаговый режим: сначала смысл, потом порядок.',
        'Вмикаємо покроковий режим: спочатку сенс, потім порядок.',
        'Modo guiado: primero el sentido, despues el orden.',
      ),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      {
        id: 'guided_too_enough_001',
        prompt: tri('Too hot значит “слишком горячий”?', 'Too hot означає “занадто гарячий”?', 'Too hot significa demasiado caliente?'),
        options: ['yes', 'no'],
        correctIndex: 0,
        thenReturnToExerciseId: 'too_enough_easy_001',
      },
      {
        id: 'guided_too_enough_002',
        prompt: tri('Достаточно хороший: good enough или enough good?', 'Достатньо хороший: good enough чи enough good?', 'Para suficientemente bueno: good enough o enough good?'),
        options: ['good enough', 'enough good'],
        correctIndex: 0,
        thenReturnToExerciseId: 'too_enough_contrast_001',
      },
      {
        id: 'guided_too_enough_003',
        prompt: tri('Достаточно времени: enough time или time enough?', 'Достатньо часу: enough time чи time enough?', 'Para suficiente tiempo: enough time o time enough?'),
        options: ['enough time', 'time enough'],
        correctIndex: 0,
        thenReturnToExerciseId: 'too_enough_contrast_004',
      },
      {
        id: 'guided_too_enough_004',
        prompt: tri('С people звучит too many people?', 'З people звучить too many people?', 'Con people decimos too many people?'),
        options: ['yes', 'no'],
        correctIndex: 0,
        thenReturnToExerciseId: 'too_enough_mixed_001',
      },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'modifier',
    microDiagnosisId: 'too_enough',
    diagnosisLabel: tri('Too / Enough', 'Too / Enough', 'Too / Enough'),
    contrastSet: CONTRAST,
    focusWords: ['too hot', 'good enough', 'enough time', 'too much', 'too many', 'not enough'],
    focusPatterns: [
      'too_adjective_hot',
      'too_adjective_expensive',
      'too_adverb_fast',
      'adjective_enough_good',
      'adjective_enough_old',
      'adverb_enough_fast',
      'enough_before_noun_time',
      'enough_before_noun_money',
      'not_enough_quality',
      'too_many_plural',
      'too_much_uncountable',
      'too_to_structure',
      'mixed_too_enough_position',
      'mixed_enough_adjective_noun',
      'mixed_sentence_correction',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyLevel: 2,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 3,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_too_enough_start',
    answer: 'diagnosis_training_too_enough_answer',
    mastery: 'diagnosis_training_too_enough_mastery',
    recovery: 'diagnosis_training_too_enough_recovery',
    onStart: 'diagnosis_training_started',
    onCorrect: 'diagnosis_training_answer_correct',
    onWrong: 'diagnosis_training_answer_wrong',
    onDepthIncrease: 'diagnosis_training_feedback_depth_increased',
    onGuidedMode: 'diagnosis_training_guided_mode_started',
    onMastery: 'diagnosis_training_mastered',
    onSmartTrainerOpen: 'diagnosis_training_smart_trainer_opened',
    payload: {
      category: 'modifier',
      microDiagnosisId: 'too_enough',
      contrastSet: CONTRAST,
      logExactToken: true,
      logMistakeType: true,
      logExerciseId: true,
      logAttemptCount: true,
      logFeedbackDepth: true,
    },
  },
  routing: {
    diagnosisTrainerRoute: '/problem_coach?category=modifier&microDiagnosisId=too_enough',
  },
  qualityChecklist: {
    hasStableId: true,
    hasCategory: true,
    hasMultilingualTitle: true,
    hasPlainDiagnosisText: true,
    hasMentalModel: true,
    hasContrastSet: true,
    hasAtLeastSixExamples: true,
    hasAtLeastTwelveExercises: true,
    hasEasyContrastMixedStructure: true,
    hasDistractorSpecificFeedback: true,
    hasRetryFeedbackLevels: true,
    hasGuidedModeForRepeatedMistakes: true,
    hasMasteryRules: true,
    hasSmartTrainerConfig: true,
    hasAnalyticsPayload: true,
    hasFallbackRoute: true,
  },
};
