// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

type PlannedTrainingLocale = 'pt-BR' | 'vi' | 'id' | 'tr' | 'pl';

const tri = (
  ru: string,
  uk = ru,
  es = ru,
  planned: Partial<Record<PlannedTrainingLocale, string>> = {},
): TriText => {
  const copy: TriText = { ru, uk, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    if (planned[locale]) copy[locale] = planned[locale];
  }
  return copy;
};

const CONTRAST = ['adjective', 'adverb', 'good/well', '-ly adverbs', 'linking verbs'];

const ADJ_ADV_STEP_TRANSLATIONS: Record<string, Record<PlannedTrainingLocale, string>> = {
  adj_adv_easy_001: {
    'pt-BR': 'Ela é uma boa professora.',
    vi: 'Cô ấy là một giáo viên giỏi.',
    id: 'Dia adalah guru yang baik.',
    tr: 'O iyi bir öğretmen.',
    pl: 'Ona jest dobrą nauczycielką.',
  },
  adj_adv_easy_002: {
    'pt-BR': 'Ela ensina muito bem.',
    vi: 'Cô ấy dạy rất tốt.',
    id: 'Dia mengajar dengan sangat baik.',
    tr: 'O çok iyi öğretir.',
    pl: 'Ona uczy bardzo dobrze.',
  },
  adj_adv_easy_003: {
    'pt-BR': 'Ele é muito cuidadoso.',
    vi: 'Anh ấy rất cẩn thận.',
    id: 'Dia sangat berhati-hati.',
    tr: 'O çok dikkatli.',
    pl: 'On jest bardzo ostrożny.',
  },
  adj_adv_contrast_001: {
    'pt-BR': 'Ele deu uma resposta rápida.',
    vi: 'Anh ấy đưa ra một câu trả lời nhanh.',
    id: 'Dia memberikan jawaban yang cepat.',
    tr: 'O hızlı bir cevap verdi.',
    pl: 'On dał szybką odpowiedź.',
  },
  adj_adv_contrast_002: {
    'pt-BR': 'Ele respondeu muito rapidamente.',
    vi: 'Anh ấy trả lời rất nhanh.',
    id: 'Dia menjawab dengan sangat cepat.',
    tr: 'O çok hızlı cevap verdi.',
    pl: 'On odpowiedział bardzo szybko.',
  },
  adj_adv_contrast_003: {
    'pt-BR': 'Ela é uma motorista cuidadosa.',
    vi: 'Cô ấy là một tài xế cẩn thận.',
    id: 'Dia pengemudi yang hati-hati.',
    tr: 'O dikkatli bir sürücü.',
    pl: 'Ona jest ostrożnym kierowcą.',
  },
  adj_adv_contrast_004: {
    'pt-BR': 'Isto é um problema sério.',
    vi: 'Đây là một vấn đề nghiêm trọng.',
    id: 'Ini masalah serius.',
    tr: 'Bu ciddi bir sorun.',
    pl: 'To poważny problem.',
  },
  adj_adv_contrast_005: {
    'pt-BR': 'Por favor, dirija com cuidado.',
    vi: 'Vui lòng lái xe cẩn thận.',
    id: 'Tolong mengemudi dengan hati-hati.',
    tr: 'Lütfen dikkatli sür.',
    pl: 'Proszę, jedź ostrożnie.',
  },
  adj_adv_mixed_001: {
    'pt-BR': 'Isso soa estranho.',
    vi: 'Điều đó nghe có vẻ lạ.',
    id: 'Itu terdengar aneh.',
    tr: 'Bu kulağa garip geliyor.',
    pl: 'To brzmi dziwnie.',
  },
  adj_adv_mixed_002: {
    'pt-BR': 'Eu me sinto mal.',
    vi: 'Tôi thấy không khỏe.',
    id: 'Saya merasa tidak enak.',
    tr: 'Kendimi kötü hissediyorum.',
    pl: 'Czuję się źle.',
  },
  adj_adv_mixed_003: {
    'pt-BR': 'Ele olhou para mim de forma estranha.',
    vi: 'Anh ấy nhìn tôi một cách kỳ lạ.',
    id: 'Dia menatap saya dengan aneh.',
    tr: 'Bana tuhaf bir şekilde baktı.',
    pl: 'On spojrzał na mnie dziwnie.',
  },
  adj_adv_mixed_004: {
    'pt-BR': 'Escolha o par natural.',
    vi: 'Chọn cặp tự nhiên.',
    id: 'Pilih pasangan yang alami.',
    tr: 'Doğal çifti seç.',
    pl: 'Wybierz naturalną parę.',
  },
  adj_adv_mixed_005: {
    'pt-BR': 'Escolha o par natural.',
    vi: 'Chọn cặp tự nhiên.',
    id: 'Pilih pasangan yang alami.',
    tr: 'Doğal çifti seç.',
    pl: 'Wybierz naturalną parę.',
  },
  adj_adv_mixed_006: {
    'pt-BR': 'Escolha o par natural.',
    vi: 'Chọn cặp tự nhiên.',
    id: 'Pilih pasangan yang alami.',
    tr: 'Doğal çifti seç.',
    pl: 'Wybierz naturalną parę.',
  },
  adj_adv_mixed_007: {
    'pt-BR': 'Escolha a frase natural.',
    vi: 'Chọn câu tự nhiên.',
    id: 'Pilih kalimat yang alami.',
    tr: 'Doğal cümleyi seç.',
    pl: 'Wybierz naturalne zdanie.',
  },
};

const ADJ_ADV_SKILL_HINTS: Record<string, Record<PlannedTrainingLocale, string>> = {
  good_before_person_word: {
    'pt-BR': 'Teacher é pessoa; antes dela use good.',
    vi: 'Teacher là người; trước nó dùng good.',
    id: 'Teacher adalah orang; sebelumnya gunakan good.',
    tr: 'Teacher bir kişidir; önünde good kullan.',
    pl: 'Teacher to osoba; przed nim użyj good.',
  },
  well_after_teaches: {
    'pt-BR': 'Teaches é ação; ação usa well.',
    vi: 'Teaches là hành động; hành động dùng well.',
    id: 'Teaches adalah aksi; aksi memakai well.',
    tr: 'Teaches bir eylemdir; eylem well alır.',
    pl: 'Teaches to czynność; czynność używa well.',
  },
  careful_after_is: {
    'pt-BR': 'Depois de is descrevemos a pessoa; use careful.',
    vi: 'Sau is ta mô tả người; dùng careful.',
    id: 'Setelah is kita menjelaskan orang; gunakan careful.',
    tr: 'Is sonrasında kişiyi anlatırız; careful kullan.',
    pl: 'Po is opisujemy osobę; użyj careful.',
  },
  quick_before_thing: {
    'pt-BR': 'Answer é coisa; antes dela use quick.',
    vi: 'Answer là vật/ý; trước nó dùng quick.',
    id: 'Answer adalah benda/hal; sebelumnya gunakan quick.',
    tr: 'Answer bir şeydir; önünde quick kullan.',
    pl: 'Answer to rzecz; przed nią użyj quick.',
  },
  quickly_after_answered: {
    'pt-BR': 'Answered é ação; use quickly.',
    vi: 'Answered là hành động; dùng quickly.',
    id: 'Answered adalah aksi; gunakan quickly.',
    tr: 'Answered bir eylemdir; quickly kullan.',
    pl: 'Answered to czynność; użyj quickly.',
  },
  careful_before_driver: {
    'pt-BR': 'Driver é pessoa; use careful.',
    vi: 'Driver là người; dùng careful.',
    id: 'Driver adalah orang; gunakan careful.',
    tr: 'Driver bir kişidir; careful kullan.',
    pl: 'Driver to osoba; użyj careful.',
  },
  serious_before_problem: {
    'pt-BR': 'Problem é coisa; use serious.',
    vi: 'Problem là sự việc; dùng serious.',
    id: 'Problem adalah hal; gunakan serious.',
    tr: 'Problem bir şeydir; serious kullan.',
    pl: 'Problem to rzecz; użyj serious.',
  },
  carefully_after_drive: {
    'pt-BR': 'Drive é ação; use carefully.',
    vi: 'Drive là hành động; dùng carefully.',
    id: 'Drive adalah aksi; gunakan carefully.',
    tr: 'Drive bir eylemdir; carefully kullan.',
    pl: 'Drive to czynność; użyj carefully.',
  },
  sounds_strange_state: {
    'pt-BR': 'Sounds descreve estado; use strange.',
    vi: 'Sounds mô tả trạng thái; dùng strange.',
    id: 'Sounds menjelaskan keadaan; gunakan strange.',
    tr: 'Sounds durumu anlatır; strange kullan.',
    pl: 'Sounds opisuje stan; użyj strange.',
  },
  feel_bad_state: {
    'pt-BR': 'Feel descreve estado; use bad.',
    vi: 'Feel mô tả trạng thái; dùng bad.',
    id: 'Feel menjelaskan keadaan; gunakan bad.',
    tr: 'Feel durumu anlatır; bad kullan.',
    pl: 'Feel opisuje stan; użyj bad.',
  },
  looked_at_strangely_action: {
    'pt-BR': 'Looked at descreve ação; use strangely.',
    vi: 'Looked at mô tả hành động; dùng strangely.',
    id: 'Looked at menjelaskan aksi; gunakan strangely.',
    tr: 'Looked at eylemi anlatır; strangely kullan.',
    pl: 'Looked at opisuje czynność; użyj strangely.',
  },
};

const ADJ_ADV_GENERIC_HINTS: Record<PlannedTrainingLocale, string> = {
  'pt-BR': 'Pergunte se a palavra descreve pessoa/coisa/estado ou ação.',
  vi: 'Hãy hỏi từ đó mô tả người/vật/trạng thái hay hành động.',
  id: 'Tanyakan apakah kata itu menjelaskan orang/benda/keadaan atau aksi.',
  tr: 'Kelimenin kişi/şey/durum mu yoksa eylem mi anlattığını sor.',
  pl: 'Zapytaj, czy słowo opisuje osobę/rzecz/stan, czy czynność.',
};

function fillPlanned(copy: TriText, planned: Partial<Record<PlannedTrainingLocale, string>>): TriText {
  const next: TriText = { ...copy };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    if (!next[locale] && planned[locale]) next[locale] = planned[locale];
  }
  return next;
}

function plannedAdjAdvFeedback(input: {
  targetSkill: string;
  correctAnswer: string;
  focusWords: string[];
}): Record<PlannedTrainingLocale, string> {
  const focus = input.focusWords.join(' / ');
  const hints = ADJ_ADV_SKILL_HINTS[input.targetSkill] ?? ADJ_ADV_GENERIC_HINTS;
  return {
    'pt-BR': `Use "${input.correctAnswer}"${focus ? ` com ${focus}` : ''}. ${hints['pt-BR']}`,
    vi: `Dùng "${input.correctAnswer}"${focus ? ` với ${focus}` : ''}. ${hints.vi}`,
    id: `Gunakan "${input.correctAnswer}"${focus ? ` dengan ${focus}` : ''}. ${hints.id}`,
    tr: `"${input.correctAnswer}" kullan${focus ? ` (${focus})` : ''}. ${hints.tr}`,
    pl: `Użyj "${input.correctAnswer}"${focus ? ` z ${focus}` : ''}. ${hints.pl}`,
  };
}

function makeStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  sentence: string;
  translation: TriText;
  options: string[];
  correctAnswer: string;
  correctFeedback: TriText;
  wrong: Record<string, TriText>;
  clue: TriText;
  finalHint: TriText;
  focusWords: string[];
}): DiagnosisTrainingStep {
  const plannedFeedback = plannedAdjAdvFeedback(input);
  const plannedTranslation = ADJ_ADV_STEP_TRANSLATIONS[input.id] ?? plannedFeedback;
  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    translation: fillPlanned(input.translation, plannedTranslation),
    explanationBlock: tri(
      'Сначала спроси: мы описываем человека или вещь? Тогда часто нужен короткий вид слова: good, quick, careful, strange. Или мы описываем действие? Тогда часто нужен how-кусок: well, quickly, carefully, strangely.',
      'Спочатку спитай: ми описуємо людину або річ? Тоді часто потрібен короткий вид слова: good, quick, careful, strange. Або ми описуємо дію? Тоді часто потрібен how-шматок: well, quickly, carefully, strangely.',
      'First ask: are we describing a person/thing/state, or the action? Person/thing/state: good, quick, careful. Action: well, quickly, carefully.',
      {
        'pt-BR': 'Primeiro pergunte: descrevemos pessoa/coisa/estado ou a ação? Pessoa/coisa/estado: good, quick, careful. Ação: well, quickly, carefully.',
        vi: 'Trước tiên hãy hỏi: ta mô tả người/vật/trạng thái hay hành động? Người/vật/trạng thái: good, quick, careful. Hành động: well, quickly, carefully.',
        id: 'Tanyakan dulu: kita menjelaskan orang/benda/keadaan atau aksinya? Orang/benda/keadaan: good, quick, careful. Aksi: well, quickly, carefully.',
        tr: 'Önce sor: kişi/şey/durum mu anlatıyoruz, yoksa eylemi mi? Kişi/şey/durum: good, quick, careful. Eylem: well, quickly, carefully.',
        pl: 'Najpierw zapytaj: opisujemy osobę/rzecz/stan czy czynność? Osoba/rzecz/stan: good, quick, careful. Czynność: well, quickly, carefully.',
      },
    ),
    microTask: tri(
      'Выбери слово, которое подходит к смыслу фразы.',
      'Обери слово, яке підходить до змісту фрази.',
      'Choose the word that fits the sentence.',
      {
        'pt-BR': 'Escolha a palavra que combina com o sentido da frase.',
        vi: 'Chọn từ phù hợp với nghĩa của câu.',
        id: 'Pilih kata yang cocok dengan makna kalimat.',
        tr: 'Cümlenin anlamına uyan kelimeyi seç.',
        pl: 'Wybierz słowo pasujące do sensu zdania.',
      },
    ),
    sentence: input.sentence,
    answerOptions: input.options.map((text) => ({ id: text, text })),
    correctAnswerId: input.correctAnswer,
    correctIndex: input.options.findIndex((option) => option === input.correctAnswer),
    correctFeedback: fillPlanned(input.correctFeedback, plannedFeedback),
    wrongFeedbackByOption: Object.fromEntries(
      input.options
        .filter((option) => option !== input.correctAnswer)
        .map((option) => [
          option,
          fillPlanned(input.wrong[option] ??
            tri(
              `Почти, но здесь нужен другой кусок. Нормально звучит: ${input.correctAnswer}.`,
              `Майже, але тут потрібен інший шматок. Нормально звучить: ${input.correctAnswer}.`,
              `Almost. Use: ${input.correctAnswer}.`,
            ), plannedFeedback),
        ]),
    ),
    retryFeedback: [
      fillPlanned(input.clue, plannedFeedback),
      tri(
        'Если слово стоит рядом с человеком или вещью, чаще нужен обычный вид. Если слово говорит, как идет действие, часто нужен хвост -ly. Good отдельно: для действия обычно well.',
        'Якщо слово стоїть поруч із людиною або річчю, частіше потрібен звичайний вид. Якщо слово каже, як іде дія, часто потрібен хвіст -ly. Good окремо: для дії зазвичай well.',
        'If it describes a person/thing/state, use the plain word. If it describes how an action happens, often use -ly. Good becomes well for actions.',
        {
          'pt-BR': 'Se descreve pessoa/coisa/estado, use a palavra simples. Se descreve como uma ação acontece, muitas vezes use -ly. Good vira well para ações.',
          vi: 'Nếu mô tả người/vật/trạng thái, dùng từ đơn giản. Nếu mô tả hành động diễn ra như thế nào, thường dùng -ly. Good thành well cho hành động.',
          id: 'Jika menjelaskan orang/benda/keadaan, pakai kata biasa. Jika menjelaskan bagaimana aksi terjadi, sering pakai -ly. Good menjadi well untuk aksi.',
          tr: 'Kişi/şey/durum anlatıyorsa yalın kelimeyi kullan. Eylemin nasıl olduğunu anlatıyorsa çoğu zaman -ly gerekir. Good, eylemler için well olur.',
          pl: 'Jeśli opisuje osobę/rzecz/stan, użyj zwykłej formy. Jeśli opisuje, jak dzieje się czynność, często użyj -ly. Good dla czynności zmienia się w well.',
        },
      ),
      fillPlanned(input.finalHint, plannedFeedback),
      tri(
        'Теперь выбери вариант, где слово подходит к своей роли в фразе.',
        'Тепер обери варіант, де слово підходить до своєї ролі у фразі.',
        `Answer: ${input.correctAnswer}.`,
        plannedFeedback,
      ),
    ],
    fallbackExplanation: tri(
      'Проверяй роль слова. Если оно описывает человека, вещь или состояние, чаще нужен обычный вид. Если оно описывает действие, нужен вид "как именно". Для good в действии используем well.',
      'Перевіряй роль слова. Якщо воно описує людину, річ або стан, частіше потрібен звичайний вид. Якщо воно описує дію, потрібен вид "як саме". Для good у дії використовуємо well.',
      'Remember the pairs: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
      {
        'pt-BR': 'Lembre dos pares: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
        vi: 'Hãy nhớ các cặp: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
        id: 'Ingat pasangannya: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
        tr: 'Çiftleri hatırla: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
        pl: 'Zapamiętaj pary: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
      },
    ),
    focusWords: input.focusWords,
  };
}

export const ADJECTIVE_VS_ADVERB_TRAINING: DiagnosisTraining = {
  id: 'adjective_vs_adverb',
  category: 'adverb',
  version: '1.0.0',
  status: 'active',
  priority: 14,
  supportedLocales: ['ru', 'uk', 'es'],
  title: tri(
    'Good или well: где ломается выбор',
    'Good чи well: де ламається вибір',
    'Good or well: good teacher, but teaches well',
    {
      'pt-BR': 'Good ou well: good teacher, mas teaches well',
      vi: 'Good hay well: good teacher, nhưng teaches well',
      id: 'Good atau well: good teacher, tetapi teaches well',
      tr: 'Good mu well mi: good teacher, ama teaches well',
      pl: 'Good czy well: good teacher, ale teaches well',
    },
  ),
  shortTitle: tri('Good / Well', 'Good / Well', 'Good / Well: adjetivo o adverbio', {
    'pt-BR': 'Good / Well: adjetivo ou advérbio',
    vi: 'Good / Well: tính từ hay trạng từ',
    id: 'Good / Well: adjektiva atau adverbia',
    tr: 'Good / Well: sıfat mı zarf mı',
    pl: 'Good / Well: przymiotnik czy przysłówek',
  }),
  shortDiagnosis: tri(
    'Ты выбираешь слово по русскому переводу, а английский смотрит на роль слова в фразе.',
    'Ти обираєш слово за перекладом, а англійська дивиться на роль слова у фразі.',
    'You choose by translation, but English checks what the word describes.',
    {
      'pt-BR': 'Você escolhe pela tradução, mas o inglês olha o que a palavra descreve.',
      vi: 'Bạn chọn theo bản dịch, nhưng tiếng Anh kiểm tra từ đó mô tả gì.',
      id: 'Kamu memilih berdasarkan terjemahan, tetapi bahasa Inggris melihat apa yang dijelaskan kata itu.',
      tr: 'Kelimeyi çeviriye göre seçiyorsun, ama İngilizce kelimenin neyi anlattığına bakar.',
      pl: 'Wybierasz według tłumaczenia, a angielski sprawdza, co słowo opisuje.',
    },
  ),
  diagnosisText: tri(
    'Проблема обычно не в значении. Ты понимаешь “хороший” и “хорошо”, “осторожный” и “осторожно”. Ломается выбор куска: good teacher, но teaches well; careful driver, но drives carefully.',
    'Проблема зазвичай не у значенні. Ти розумієш “хороший” і “добре”, “обережний” і “обережно”. Ламається вибір шматка: good teacher, але teaches well; careful driver, але drives carefully.',
    'The meaning is usually clear. The chunk choice breaks: good teacher, but teaches well; careful driver, but drives carefully.',
    {
      'pt-BR': 'O sentido geralmente está claro. A escolha do bloco quebra: good teacher, mas teaches well; careful driver, mas drives carefully.',
      vi: 'Nghĩa thường đã rõ. Lựa chọn cụm bị sai: good teacher, nhưng teaches well; careful driver, nhưng drives carefully.',
      id: 'Maknanya biasanya jelas. Pilihan potongannya yang rusak: good teacher, tetapi teaches well; careful driver, tetapi drives carefully.',
      tr: 'Anlam genelde nettir. Parça seçimi bozulur: good teacher, ama teaches well; careful driver, ama drives carefully.',
      pl: 'Znaczenie zwykle jest jasne. Psuje się wybór kawałka: good teacher, ale teaches well; careful driver, ale drives carefully.',
    },
  ),
  mentalModel: tri(
    'Смотри не на русский перевод, а на то, что описывает слово. Если описываем человека, вещь или состояние: good, quick, careful, strange. Если описываем действие: well, quickly, carefully, strangely.',
    'Дивись не на переклад, а на те, що описує слово. Якщо описуємо людину, річ або стан: good, quick, careful, strange. Якщо описуємо дію: well, quickly, carefully, strangely.',
    'Do not start from translation. Ask what the word describes: person/thing/state or action.',
    {
      'pt-BR': 'Não comece pela tradução. Pergunte o que a palavra descreve: pessoa/coisa/estado ou ação.',
      vi: 'Đừng bắt đầu từ bản dịch. Hãy hỏi từ đó mô tả gì: người/vật/trạng thái hay hành động.',
      id: 'Jangan mulai dari terjemahan. Tanyakan apa yang dijelaskan kata itu: orang/benda/keadaan atau aksi.',
      tr: 'Çeviriden başlama. Kelimenin neyi anlattığını sor: kişi/şey/durum mu, eylem mi.',
      pl: 'Nie zaczynaj od tłumaczenia. Zapytaj, co opisuje słowo: osobę/rzecz/stan czy czynność.',
    },
  ),
  contrastSet: CONTRAST,
  coreRule: tri(
    'Обычный вид слова описывает человека, вещь или состояние. Вид с хвостом -ly обычно описывает действие. Отдельная ловушка: good для действия меняется на well.',
    'Звичайний вид слова описує людину, річ або стан. Вид із хвостом -ly зазвичай описує дію. Окрема пастка: good для дії змінюється на well.',
    'Pairs: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
    {
      'pt-BR': 'Pares: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
      vi: 'Các cặp: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
      id: 'Pasangan: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
      tr: 'Çiftler: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
      pl: 'Pary: good teacher / teaches well, quick answer / answers quickly, careful driver / drives carefully.',
    },
  ),
  whatUserMustLearn: {
    ru: [
      'Перед teacher, answer, driver обычно стоит обычный вид: good teacher, quick answer, careful driver.',
      'После действия часто нужен how-кусок: teaches well, answers quickly, drives carefully.',
      'Good не превращается в goodly. Для действия почти всегда нужно well.',
      'После is, seems, sounds, feels часто описывается состояние: He is careful, It sounds strange.',
      'Look может описывать состояние: You look tired. Но looked at me описывает действие: looked at me strangely.',
    ],
    uk: [
      'Перед teacher, answer, driver зазвичай стоїть звичайний вид: good teacher, quick answer, careful driver.',
      'Після дії часто потрібен how-шматок: teaches well, answers quickly, drives carefully.',
      'Good не перетворюється на goodly. Для дії майже завжди потрібно well.',
      'Після is, seems, sounds, feels часто описується стан: He is careful, It sounds strange.',
      'Look може описувати стан: You look tired. Але looked at me описує дію: looked at me strangely.',
    ],
    es: [
      'Before teacher/answer/driver, use the plain word: good teacher, quick answer, careful driver.',
      'For how an action happens, use well/quickly/carefully.',
      'Good does not become goodly. For actions, use well.',
      'After is/seems/sounds/feels, we often describe a state: It sounds strange.',
      'Look can describe a state, but looked at me describes an action.',
    ],
    'pt-BR': [
      'Antes de teacher, answer ou driver, use a forma simples: good teacher, quick answer, careful driver.',
      'Para dizer como a ação acontece, use well, quickly ou carefully.',
      'Good não vira goodly. Para ações, quase sempre use well.',
      'Depois de is, seems, sounds ou feels, muitas vezes descrevemos um estado: It sounds strange.',
      'Look pode descrever um estado: You look tired. Mas looked at me descreve uma ação: looked at me strangely.',
    ],
    vi: [
      'Trước teacher, answer hoặc driver, dùng dạng đơn giản: good teacher, quick answer, careful driver.',
      'Khi nói hành động diễn ra như thế nào, dùng well, quickly hoặc carefully.',
      'Good không đổi thành goodly. Với hành động, gần như luôn dùng well.',
      'Sau is, seems, sounds, feels, ta thường mô tả trạng thái: It sounds strange.',
      'Look có thể mô tả trạng thái: You look tired. Nhưng looked at me mô tả hành động: looked at me strangely.',
    ],
    id: [
      'Sebelum teacher, answer, atau driver, pakai bentuk biasa: good teacher, quick answer, careful driver.',
      'Untuk cara sebuah aksi terjadi, pakai well, quickly, atau carefully.',
      'Good tidak menjadi goodly. Untuk aksi, hampir selalu pakai well.',
      'Setelah is, seems, sounds, feels, kita sering menjelaskan keadaan: It sounds strange.',
      'Look bisa menjelaskan keadaan: You look tired. Tetapi looked at me menjelaskan aksi: looked at me strangely.',
    ],
    tr: [
      'Teacher, answer veya driver öncesinde yalın biçimi kullan: good teacher, quick answer, careful driver.',
      'Bir eylemin nasıl yapıldığını anlatmak için well, quickly veya carefully kullan.',
      'Good, goodly olmaz. Eylemler için neredeyse her zaman well gerekir.',
      'is, seems, sounds, feels sonrası çoğu zaman durumu anlatırız: It sounds strange.',
      'Look bir durumu anlatabilir: You look tired. Ama looked at me eylemi anlatır: looked at me strangely.',
    ],
    pl: [
      'Przed teacher, answer albo driver użyj zwykłej formy: good teacher, quick answer, careful driver.',
      'Gdy mówisz, jak dzieje się czynność, użyj well, quickly albo carefully.',
      'Good nie zmienia się w goodly. Dla czynności prawie zawsze używamy well.',
      'Po is, seems, sounds, feels często opisujemy stan: It sounds strange.',
      'Look może opisywać stan: You look tired. Ale looked at me opisuje czynność: looked at me strangely.',
    ],
  },
  examples: [
    {
      en: 'She is a good teacher.',
      ru: 'Она хороший учитель.',
      uk: 'Вона хороша вчителька.',
      es: 'Ella es una buena profesora.',
            'pt-BR': 'Ela é uma boa professora.',
      vi: 'Cô ấy là một giáo viên giỏi.',
      id: 'Dia adalah guru yang baik.',
      tr: 'O iyi bir öğretmen.',
      pl: 'Ona jest dobrą nauczycielką.',
      why: tri('Good стоит рядом с teacher: описываем человека.', 'Good стоїть поруч із teacher: описуємо людину.', 'Good describes teacher.', { 'pt-BR': 'Good fica junto de teacher: descrevemos uma pessoa.', vi: 'Good đứng cạnh teacher: ta mô tả người.', id: 'Good berdiri dekat teacher: kita menjelaskan orang.', tr: 'Good, teacher yanında durur: kişiyi anlatıyoruz.', pl: 'Good stoi przy teacher: opisujemy osobę.' }),
    },
    {
      en: 'She teaches well.',
      ru: 'Она хорошо преподает.',
      uk: 'Вона добре викладає.',
      es: 'Ella enseña bien.',
            'pt-BR': 'Ela ensina bem.',
      vi: 'Cô ấy dạy tốt.',
      id: 'Dia mengajar dengan baik.',
      tr: 'O iyi öğretir.',
      pl: 'Ona dobrze uczy.',
      why: tri('Well говорит, как она teaches.', 'Well каже, як вона teaches.', 'Well describes how she teaches.', { 'pt-BR': 'Well diz como ela teaches.', vi: 'Well nói cô ấy teaches như thế nào.', id: 'Well menjelaskan bagaimana dia teaches.', tr: 'Well, onun nasıl teaches yaptığını anlatır.', pl: 'Well mówi, jak ona teaches.' }),
    },
    {
      en: 'He gave a quick answer.',
      ru: 'Он дал быстрый ответ.',
      uk: 'Він дав швидку відповідь.',
      es: 'Dio una respuesta rápida.',
            'pt-BR': 'Ele deu uma resposta rápida.',
      vi: 'Anh ấy đưa ra một câu trả lời nhanh.',
      id: 'Dia memberikan jawaban yang cepat.',
      tr: 'O hızlı bir cevap verdi.',
      pl: 'On dał szybką odpowiedź.',
      why: tri('Quick стоит рядом с answer: описываем вещь.', 'Quick стоїть поруч із answer: описуємо річ.', 'Quick describes answer.', { 'pt-BR': 'Quick fica junto de answer: descrevemos uma coisa.', vi: 'Quick đứng cạnh answer: ta mô tả vật/ý.', id: 'Quick berdiri dekat answer: kita menjelaskan benda/hal.', tr: 'Quick, answer yanında durur: bir şeyi anlatıyoruz.', pl: 'Quick stoi przy answer: opisujemy rzecz.' }),
    },
    {
      en: 'He answered quickly.',
      ru: 'Он ответил быстро.',
      uk: 'Він відповів швидко.',
      es: 'Respondió rápidamente.',
            'pt-BR': 'Ele respondeu rapidamente.',
      vi: 'Anh ấy trả lời nhanh chóng.',
      id: 'Dia menjawab dengan cepat.',
      tr: 'O hızlıca cevap verdi.',
      pl: 'On szybko odpowiedział.',
      why: tri('Quickly говорит, как он answered.', 'Quickly каже, як він answered.', 'Quickly describes how he answered.', { 'pt-BR': 'Quickly diz como ele answered.', vi: 'Quickly nói anh ấy answered như thế nào.', id: 'Quickly menjelaskan bagaimana dia answered.', tr: 'Quickly, onun nasıl answered yaptığını anlatır.', pl: 'Quickly mówi, jak on answered.' }),
    },
    {
      en: 'Be careful.',
      ru: 'Будь осторожен.',
      uk: 'Будь обережним.',
      es: 'Ten cuidado.',
            'pt-BR': 'Tenha cuidado.',
      vi: 'Hãy cẩn thận.',
      id: 'Berhati-hatilah.',
      tr: 'Dikkatli ol.',
      pl: 'Bądź ostrożny.',
      why: tri('После be описываем состояние человека: careful.', 'Після be описуємо стан людини: careful.', 'After be, use careful.', { 'pt-BR': 'Depois de be descrevemos o estado da pessoa: careful.', vi: 'Sau be ta mô tả trạng thái của người: careful.', id: 'Setelah be kita menjelaskan keadaan orang: careful.', tr: 'Be sonrasında kişinin durumunu anlatırız: careful.', pl: 'Po be opisujemy stan osoby: careful.' }),
    },
    {
      en: 'Drive carefully.',
      ru: 'Води осторожно.',
      uk: 'Води обережно.',
      es: 'Conduce con cuidado.',
            'pt-BR': 'Dirija com cuidado.',
      vi: 'Hãy lái xe cẩn thận.',
      id: 'Mengemudilah dengan hati-hati.',
      tr: 'Dikkatli sür.',
      pl: 'Jedź ostrożnie.',
      why: tri('Carefully говорит, как drive.', 'Carefully каже, як drive.', 'Carefully describes how you drive.', { 'pt-BR': 'Carefully diz como drive acontece.', vi: 'Carefully nói drive diễn ra như thế nào.', id: 'Carefully menjelaskan bagaimana drive dilakukan.', tr: 'Carefully, drive eyleminin nasıl olduğunu anlatır.', pl: 'Carefully mówi, jak odbywa się drive.' }),
    },
    {
      en: 'It sounds strange.',
      ru: 'Это звучит странно.',
      uk: 'Це звучить дивно.',
      es: 'Suena raro.',
            'pt-BR': 'Isso soa estranho.',
      vi: 'Điều đó nghe có vẻ lạ.',
      id: 'Itu terdengar aneh.',
      tr: 'Bu kulağa garip geliyor.',
      pl: 'To brzmi dziwnie.',
      why: tri('Sounds здесь описывает состояние: strange.', 'Sounds тут описує стан: strange.', 'Sounds takes strange here.', { 'pt-BR': 'Sounds aqui descreve estado: strange.', vi: 'Sounds ở đây mô tả trạng thái: strange.', id: 'Sounds di sini menjelaskan keadaan: strange.', tr: 'Sounds burada durumu anlatır: strange.', pl: 'Sounds tutaj opisuje stan: strange.' }),
    },
    {
      en: 'He looked at me strangely.',
      ru: 'Он странно посмотрел на меня.',
      uk: 'Він дивно подивився на мене.',
      es: 'Me miró de forma extraña.',
            'pt-BR': 'Ele olhou para mim de forma estranha.',
      vi: 'Anh ấy nhìn tôi một cách kỳ lạ.',
      id: 'Dia menatap saya dengan aneh.',
      tr: 'Bana tuhaf bir şekilde baktı.',
      pl: 'On spojrzał na mnie dziwnie.',
      why: tri('Looked at me — действие, поэтому strangely.', 'Looked at me — дія, тому strangely.', 'Looked at me describes an action.', { 'pt-BR': 'Looked at me descreve uma ação, por isso strangely.', vi: 'Looked at me mô tả hành động, vì vậy dùng strangely.', id: 'Looked at me menjelaskan aksi, jadi gunakan strangely.', tr: 'Looked at me bir eylemi anlatır, bu yüzden strangely.', pl: 'Looked at me opisuje czynność, więc strangely.' }),
    },
  ],
  introBlocks: [
    {
      id: 'intro_problem',
      type: 'diagnosis',
      text: tri(
        'Здесь не надо зубрить названия. Достаточно поймать вопрос: слово описывает человека/вещь или само действие?',
        'Тут не треба зубрити назви. Достатньо зловити питання: слово описує людину/річ чи саму дію?',
        'You do not need labels. Ask: person/thing/state, or action?',
        {
          'pt-BR': 'Você não precisa decorar nomes. Pergunte: a palavra descreve pessoa/coisa/estado ou a própria ação?',
          vi: 'Bạn không cần học thuộc nhãn. Hãy hỏi: từ đó mô tả người/vật/trạng thái hay chính hành động?',
          id: 'Kamu tidak perlu menghafal label. Tanyakan: kata itu menjelaskan orang/benda/keadaan atau aksinya sendiri?',
          tr: 'Terimleri ezberlemene gerek yok. Sor: kelime kişi/şey/durum mu anlatıyor, yoksa eylemin kendisini mi?',
          pl: 'Nie trzeba wkuwać nazw. Wystarczy złapać pytanie: słowo opisuje osobę/rzecz/stan czy samą czynność?',
        },
      ),
    },
    {
      id: 'intro_pair',
      type: 'rule',
      text: tri(
        'Главная пара: good teacher, но teaches well. Если держать эту пару в голове, половина ошибок исчезает.',
        'Головна пара: good teacher, але teaches well. Якщо тримати цю пару в голові, половина помилок зникає.',
        'Main pair: good teacher, but teaches well.',
        {
          'pt-BR': 'Par principal: good teacher, mas teaches well. Se guardar esse par, metade dos erros desaparece.',
          vi: 'Cặp chính: good teacher, nhưng teaches well. Nếu nhớ cặp này, một nửa lỗi sẽ biến mất.',
          id: 'Pasangan utama: good teacher, tetapi teaches well. Jika mengingat pasangan ini, separuh kesalahan hilang.',
          tr: 'Ana çift: good teacher, ama teaches well. Bu çifti akılda tutarsan hataların yarısı kaybolur.',
          pl: 'Główna para: good teacher, ale teaches well. Jeśli trzymasz ją w głowie, połowa błędów znika.',
        },
      ),
    },
    {
      id: 'intro_check_question',
      type: 'contrast',
      text: tri(
        'Быстрая проверка: если слово отвечает "какой человек или какая вещь?" - good, quick, careful. Если отвечает "как делает?" - well, quickly, carefully.',
        'Швидка перевірка: якщо слово відповідає "яка людина або яка річ?" - good, quick, careful. Якщо відповідає "як робить?" - well, quickly, carefully.',
        'Quick check: person or thing takes good/quick/careful. Action takes well/quickly/carefully.',
        {
          'pt-BR': 'Checagem rápida: pessoa/coisa usa good/quick/careful. Ação usa well/quickly/carefully.',
          vi: 'Kiểm tra nhanh: người/vật dùng good/quick/careful. Hành động dùng well/quickly/carefully.',
          id: 'Cek cepat: orang/benda memakai good/quick/careful. Aksi memakai well/quickly/carefully.',
          tr: 'Hızlı kontrol: kişi/şey good/quick/careful alır. Eylem well/quickly/carefully alır.',
          pl: 'Szybka kontrola: osoba/rzecz bierze good/quick/careful. Czynność bierze well/quickly/carefully.',
        },
      ),
    },
  ],
  steps: [
    makeStep({
      id: 'adj_adv_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'good_before_person_word',
      sentence: 'She is a ___ teacher.',
      translation: tri('Она хороший учитель.', 'Вона хороша вчителька.', 'Ella es una buena profesora.'),
      options: ['good', 'well', 'goodly', 'better'],
      correctAnswer: 'good',
      correctFeedback: tri('Да. Перед teacher нужно good: good teacher.', 'Так. Перед teacher потрібно good: good teacher.', 'Yes. Good teacher.'),
      wrong: {
        well: tri('Well подходит к действию: teaches well. Перед teacher нужно good.', 'Well підходить до дії: teaches well. Перед teacher потрібно good.', 'Use good before teacher.'),
        goodly: tri('Goodly здесь не нужно. Нормальный кусок: good teacher.', 'Goodly тут не потрібно. Нормальний шматок: good teacher.', 'Use good teacher.'),
        better: tri('Better значит “лучше”. Здесь просто качество: good teacher.', 'Better означає “краще”. Тут просто якість: good teacher.', 'Use good teacher.'),
      },
      clue: tri('Teacher — это человек. Описываем человека: good.', 'Teacher — це людина. Описуємо людину: good.', 'Teacher is a person: good.'),
      finalHint: tri('Фраза целиком: She is a good teacher.', 'Фраза повністю: She is a good teacher.', 'Full sentence: She is a good teacher.'),
      focusWords: ['good', 'teacher'],
    }),
    makeStep({
      id: 'adj_adv_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'well_after_teaches',
      sentence: 'She teaches very ___.',
      translation: tri('Она очень хорошо преподает.', 'Вона дуже добре викладає.', 'Ella enseña muy bien.'),
      options: ['good', 'well', 'goodly', 'best'],
      correctAnswer: 'well',
      correctFeedback: tri('Да. Teaches — действие, значит teaches well.', 'Так. Teaches — дія, отже teaches well.', 'Yes. Teaches well.'),
      wrong: {
        good: tri('Good стоит рядом с человеком или вещью: good teacher. Действие teaches описывает well.', 'Good стоїть поруч із людиною або річчю: good teacher. Дію teaches описує well.', 'Use well after teaches.'),
        goodly: tri('Goodly не нужен. От good для действия работает well.', 'Goodly не потрібен. Від good для дії працює well.', 'Use well.'),
        best: tri('Best значит “лучше всех”. Здесь нужно просто “хорошо”: well.', 'Best означає “найкраще”. Тут потрібно просто “добре”: well.', 'Use well.'),
      },
      clue: tri('Teaches — что она делает. Как делает? Well.', 'Teaches — що вона робить. Як робить? Well.', 'How does she teach? Well.'),
      finalHint: tri('Фраза целиком: She teaches very well.', 'Фраза повністю: She teaches very well.', 'Full sentence: She teaches very well.'),
      focusWords: ['teaches', 'well'],
    }),
    makeStep({
      id: 'adj_adv_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'careful_after_is',
      sentence: 'He is very ___.',
      translation: tri('Он очень осторожный.', 'Він дуже обережний.', 'Él es muy cuidadoso.'),
      options: ['careful', 'carefully', 'care', 'caringly'],
      correctAnswer: 'careful',
      correctFeedback: tri('Да. После is описываем человека: careful.', 'Так. Після is описуємо людину: careful.', 'Yes. He is careful.'),
      wrong: {
        carefully: tri('Carefully описывает действие: drive carefully. После is нужно careful.', 'Carefully описує дію: drive carefully. Після is потрібно careful.', 'Use careful after is.'),
        care: tri('Care здесь не описывает человека. Нужен careful.', 'Care тут не описує людину. Потрібен careful.', 'Use careful.'),
        caringly: tri('Caringly говорит, как кто-то что-то делает. Здесь состояние человека: careful.', 'Caringly каже, як хтось щось робить. Тут стан людини: careful.', 'Use careful.'),
      },
      clue: tri('После is мы говорим, какой он. Значит careful.', 'Після is ми кажемо, який він. Отже careful.', 'After is, use careful.'),
      finalHint: tri('Фраза целиком: He is very careful.', 'Фраза повністю: He is very careful.', 'Full sentence: He is very careful.'),
      focusWords: ['is', 'careful'],
    }),
    makeStep({
      id: 'adj_adv_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'quick_before_thing',
      sentence: 'He gave a ___ answer.',
      translation: tri('Он дал быстрый ответ.', 'Він дав швидку відповідь.', 'Dio una respuesta rápida.'),
      options: ['quick', 'quickly', 'quicker', 'quickness'],
      correctAnswer: 'quick',
      correctFeedback: tri('Да. Перед answer нужно quick: a quick answer.', 'Так. Перед answer потрібно quick: a quick answer.', 'Yes. A quick answer.'),
      wrong: {
        quickly: tri('Quickly говорит, как кто-то ответил: answered quickly. Перед answer нужно quick.', 'Quickly каже, як хтось відповів: answered quickly. Перед answer потрібно quick.', 'Use quick before answer.'),
        quicker: tri('Quicker значит “быстрее”. Здесь просто быстрый ответ: quick answer.', 'Quicker означає “швидше”. Тут просто швидка відповідь: quick answer.', 'Use quick.'),
        quickness: tri('Quickness — это другое слово. В этой фразе нужен quick.', 'Quickness — це інше слово. У цій фразі потрібен quick.', 'Use quick.'),
      },
      clue: tri('Answer — вещь, которую описываем. Нужен quick.', 'Answer — річ, яку описуємо. Потрібен quick.', 'Answer takes quick.'),
      finalHint: tri('Фраза целиком: He gave a quick answer.', 'Фраза повністю: He gave a quick answer.', 'Full sentence: He gave a quick answer.'),
      focusWords: ['quick', 'answer'],
    }),
    makeStep({
      id: 'adj_adv_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'quickly_after_answered',
      sentence: 'He answered very ___.',
      translation: tri('Он ответил очень быстро.', 'Він відповів дуже швидко.', 'Respondió muy rápido.'),
      options: ['quick', 'quickly', 'quicker', 'quickness'],
      correctAnswer: 'quickly',
      correctFeedback: tri('Да. Answered — действие, значит answered quickly.', 'Так. Answered — дія, отже answered quickly.', 'Yes. Answered quickly.'),
      wrong: {
        quick: tri('Quick подходит к answer: quick answer. Но answered — действие, нужно quickly.', 'Quick підходить до answer: quick answer. Але answered — дія, потрібно quickly.', 'Use quickly after answered.'),
        quicker: tri('Quicker значит “быстрее”. Здесь нужно “быстро”: quickly.', 'Quicker означає “швидше”. Тут потрібно “швидко”: quickly.', 'Use quickly.'),
        quickness: tri('Quickness не говорит, как он ответил. Нужен quickly.', 'Quickness не каже, як він відповів. Потрібен quickly.', 'Use quickly.'),
      },
      clue: tri('Answered — что он сделал. Как сделал? Quickly.', 'Answered — що він зробив. Як зробив? Quickly.', 'How did he answer? Quickly.'),
      finalHint: tri('Фраза целиком: He answered very quickly.', 'Фраза повністю: He answered very quickly.', 'Full sentence: He answered very quickly.'),
      focusWords: ['answered', 'quickly'],
    }),
    makeStep({
      id: 'adj_adv_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'careful_before_driver',
      sentence: 'She is a ___ driver.',
      translation: tri('Она осторожный водитель.', 'Вона обережний водій.', 'Ella es una conductora cuidadosa.'),
      options: ['careful', 'carefully', 'care', 'carefulness'],
      correctAnswer: 'careful',
      correctFeedback: tri('Да. Перед driver нужно careful: a careful driver.', 'Так. Перед driver потрібно careful: a careful driver.', 'Yes. A careful driver.'),
      wrong: {
        carefully: tri('Carefully подходит к drives: drives carefully. Перед driver нужно careful.', 'Carefully підходить до drives: drives carefully. Перед driver потрібно careful.', 'Use careful before driver.'),
        care: tri('Care не описывает driver в этой фразе. Нужен careful.', 'Care не описує driver у цій фразі. Потрібен careful.', 'Use careful.'),
        carefulness: tri('Carefulness слишком тяжелое и здесь не подходит. Нужен careful driver.', 'Carefulness занадто важке і тут не підходить. Потрібен careful driver.', 'Use careful driver.'),
      },
      clue: tri('Driver — человек. Описываем человека: careful.', 'Driver — людина. Описуємо людину: careful.', 'Driver takes careful.'),
      finalHint: tri('Фраза целиком: She is a careful driver.', 'Фраза повністю: She is a careful driver.', 'Full sentence: She is a careful driver.'),
      focusWords: ['careful', 'driver'],
    }),
    makeStep({
      id: 'adj_adv_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'serious_before_problem',
      sentence: 'This is a ___ problem.',
      translation: tri('Это серьезная проблема.', 'Це серйозна проблема.', 'Este es un problema serio.'),
      options: ['serious', 'seriously', 'seriousness', 'more seriously'],
      correctAnswer: 'serious',
      correctFeedback: tri('Да. Мы описываем саму проблему, поэтому нужен обычный вид слова.', 'Так. Ми описуємо саму проблему, тому потрібен звичайний вид слова.', 'Yes. A serious problem.'),
      wrong: {
        seriously: tri('Seriously говорит, как что-то делают или говорят. Перед problem нужно serious.', 'Seriously каже, як щось роблять або кажуть. Перед problem потрібно serious.', 'Use serious before problem.'),
        seriousness: tri('Seriousness — это “серьезность”. Здесь нужен serious problem.', 'Seriousness — це “серйозність”. Тут потрібен serious problem.', 'Use serious.'),
        'more seriously': tri('More seriously описывает действие. Здесь описываем problem: serious.', 'More seriously описує дію. Тут описуємо problem: serious.', 'Use serious.'),
      },
      clue: tri('Problem — вещь. Описываем вещь: serious.', 'Problem — річ. Описуємо річ: serious.', 'Problem takes serious.'),
      finalHint: tri('Фраза целиком: This is a serious problem.', 'Фраза повністю: This is a serious problem.', 'Full sentence: This is a serious problem.'),
      focusWords: ['serious', 'problem'],
    }),
    makeStep({
      id: 'adj_adv_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'carefully_after_drive',
      sentence: 'Please drive ___.',
      translation: tri('Пожалуйста, води осторожно.', 'Будь ласка, води обережно.', 'Por favor, conduce con cuidado.'),
      options: ['careful', 'carefully', 'care', 'carefulness'],
      correctAnswer: 'carefully',
      correctFeedback: tri('Да. Drive — действие, значит drive carefully.', 'Так. Drive — дія, отже drive carefully.', 'Yes. Drive carefully.'),
      wrong: {
        careful: tri('Careful описывает человека: careful driver. Но drive — действие, нужно carefully.', 'Careful описує людину: careful driver. Але drive — дія, потрібно carefully.', 'Use carefully after drive.'),
        care: tri('Care здесь не говорит, как водить. Нужен carefully.', 'Care тут не каже, як водити. Потрібен carefully.', 'Use carefully.'),
        carefulness: tri('Carefulness — не команда “води осторожно”. Нормально: drive carefully.', 'Carefulness — не команда “води обережно”. Нормально: drive carefully.', 'Use drive carefully.'),
      },
      clue: tri('Drive — действие. Как водить? Carefully.', 'Drive — дія. Як водити? Carefully.', 'How should you drive? Carefully.'),
      finalHint: tri('Фраза целиком: Please drive carefully.', 'Фраза повністю: Please drive carefully.', 'Full sentence: Please drive carefully.'),
      focusWords: ['drive', 'carefully'],
    }),
    makeStep({
      id: 'adj_adv_mixed_001',
      order: 9,
      difficulty: 'mixed',
      targetSkill: 'sounds_strange_state',
      sentence: 'It sounds ___.',
      translation: tri('Это звучит странно.', 'Це звучить дивно.', 'Suena raro.'),
      options: ['strange', 'strangely', 'stranger', 'strangeness'],
      correctAnswer: 'strange',
      correctFeedback: tri('Да. Sounds описывает состояние: It sounds strange.', 'Так. Sounds описує стан: It sounds strange.', 'Yes. It sounds strange.'),
      wrong: {
        strangely: tri('Strangely подходит к действию: he looked at me strangely. С sounds нужен strange.', 'Strangely підходить до дії: he looked at me strangely. Із sounds потрібен strange.', 'Use strange after sounds.'),
        stranger: tri('Stranger значит “более странный” или “незнакомец”. Здесь нужно strange.', 'Stranger означає “дивніший” або “незнайомець”. Тут потрібно strange.', 'Use strange.'),
        strangeness: tri('Strangeness — “странность”. Фраза звучит нормально как It sounds strange.', 'Strangeness — “дивність”. Фраза звучить нормально як It sounds strange.', 'Use strange.'),
      },
      clue: tri('Sounds здесь как feels/seems: описываем состояние.', 'Sounds тут як feels/seems: описуємо стан.', 'Sounds takes strange here.'),
      finalHint: tri('Фраза целиком: It sounds strange.', 'Фраза повністю: It sounds strange.', 'Full sentence: It sounds strange.'),
      focusWords: ['sounds', 'strange'],
    }),
    makeStep({
      id: 'adj_adv_mixed_002',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'feel_bad_state',
      sentence: 'I feel ___.',
      translation: tri('Мне плохо.', 'Мені погано.', 'Me siento mal.'),
      options: ['bad', 'badly', 'worse', 'badness'],
      correctAnswer: 'bad',
      correctFeedback: tri('Да. Feel здесь описывает состояние: I feel bad.', 'Так. Feel тут описує стан: I feel bad.', 'Yes. I feel bad.'),
      wrong: {
        badly: tri('Badly может описывать, как что-то сделано. Но I feel bad — состояние.', 'Badly може описувати, як щось зроблено. Але I feel bad — стан.', 'Use I feel bad.'),
        worse: tri('Worse значит “хуже”. Здесь базовая фраза: I feel bad.', 'Worse означає “гірше”. Тут базова фраза: I feel bad.', 'Use bad.'),
        badness: tri('Badness — “плохость”. В живой фразе нужно I feel bad.', 'Badness — “поганість”. У живій фразі потрібно I feel bad.', 'Use bad.'),
      },
      clue: tri('Feel здесь не про действие, а про состояние.', 'Feel тут не про дію, а про стан.', 'Feel describes a state here.'),
      finalHint: tri('Фраза целиком: I feel bad.', 'Фраза повністю: I feel bad.', 'Full sentence: I feel bad.'),
      focusWords: ['feel', 'bad'],
    }),
    makeStep({
      id: 'adj_adv_mixed_003',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'looked_at_strangely_action',
      sentence: 'He looked at me ___.',
      translation: tri('Он странно посмотрел на меня.', 'Він дивно подивився на мене.', 'Me miró de forma extraña.'),
      options: ['strange', 'strangely', 'stranger', 'strangeness'],
      correctAnswer: 'strangely',
      correctFeedback: tri('Да. Здесь описываем не человека, а то, как он посмотрел.', 'Так. Тут описуємо не людину, а те, як він подивився.', 'Yes. Looked at me strangely.'),
      wrong: {
        strange: tri('Strange подходит к It sounds strange. Но looked at me — действие, нужно strangely.', 'Strange підходить до It sounds strange. Але looked at me — дія, потрібно strangely.', 'Use strangely here.'),
        stranger: tri('Stranger здесь меняет смысл. Нужно сказать, как он посмотрел: strangely.', 'Stranger тут змінює зміст. Потрібно сказати, як він подивився: strangely.', 'Use strangely.'),
        strangeness: tri('Strangeness — не способ смотреть. Нужен кусок looked strangely.', 'Strangeness — не спосіб дивитися. Потрібен шматок looked strangely.', 'Use strangely.'),
      },
      clue: tri('Looked at me — что он сделал. Как сделал? Strangely.', 'Looked at me — що він зробив. Як зробив? Strangely.', 'How did he look at me? Strangely.'),
      finalHint: tri('Фраза целиком: He looked at me strangely.', 'Фраза повністю: He looked at me strangely.', 'Full sentence: He looked at me strangely.'),
      focusWords: ['looked', 'strangely'],
    }),
    makeStep({
      id: 'adj_adv_mixed_004',
      order: 12,
      difficulty: 'mixed_review',
      targetSkill: 'good_well_pair',
      sentence: 'Choose the natural pair.',
      translation: tri('Выбери естественную пару.', 'Обери природну пару.', 'Choose the natural pair.'),
      options: ['good teacher / teaches well', 'well teacher / teaches good', 'good teacher / teaches good', 'well teacher / teaches well'],
      correctAnswer: 'good teacher / teaches well',
      correctFeedback: tri('Да. Good рядом с teacher, well рядом с teaches.', 'Так. Good поруч із teacher, well поруч із teaches.', 'Yes. Good teacher / teaches well.'),
      wrong: {
        'well teacher / teaches good': tri('Оба куска перепутаны. Нужно: good teacher / teaches well.', 'Обидва шматки переплутані. Потрібно: good teacher / teaches well.', 'Use good teacher / teaches well.'),
        'good teacher / teaches good': tri('Good teacher верно, но teaches good звучит плохо. Действие teaches требует well.', 'Good teacher правильно, але teaches good звучить погано. Дія teaches потребує well.', 'Use teaches well.'),
        'well teacher / teaches well': tri('Teaches well верно, но well teacher неверно. Перед teacher нужно good.', 'Teaches well правильно, але well teacher неправильно. Перед teacher потрібно good.', 'Use good teacher.'),
      },
      clue: tri('Teacher берет good. Teaches берет well.', 'Teacher бере good. Teaches бере well.', 'Teacher: good. Teaches: well.'),
      finalHint: tri('Пара: good teacher / teaches well.', 'Пара: good teacher / teaches well.', 'Pair: good teacher / teaches well.'),
      focusWords: ['good', 'well'],
    }),
    makeStep({
      id: 'adj_adv_mixed_005',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'careful_carefully_pair',
      sentence: 'Choose the natural pair.',
      translation: tri('Выбери естественную пару.', 'Обери природну пару.', 'Choose the natural pair.'),
      options: ['careful driver / drives carefully', 'carefully driver / drives careful', 'careful driver / drives careful', 'carefully driver / drives carefully'],
      correctAnswer: 'careful driver / drives carefully',
      correctFeedback: tri('Да. Careful рядом с driver, carefully рядом с drives.', 'Так. Careful поруч із driver, carefully поруч із drives.', 'Yes. Careful driver / drives carefully.'),
      wrong: {
        'carefully driver / drives careful': tri('Оба куска перепутаны. Нужно: careful driver / drives carefully.', 'Обидва шматки переплутані. Потрібно: careful driver / drives carefully.', 'Use careful driver / drives carefully.'),
        'careful driver / drives careful': tri('Careful driver верно, но drives careful неверно. Действие drives требует carefully.', 'Careful driver правильно, але drives careful неправильно. Дія drives потребує carefully.', 'Use drives carefully.'),
        'carefully driver / drives carefully': tri('Drives carefully верно, но carefully driver неверно. Перед driver нужно careful.', 'Drives carefully правильно, але carefully driver неправильно. Перед driver потрібно careful.', 'Use careful driver.'),
      },
      clue: tri('Водитель - человек, а вторая часть описывает действие.', 'Водій - людина, а друга частина описує дію.', 'Driver: careful. Drives: carefully.'),
      finalHint: tri('Пара: careful driver / drives carefully.', 'Пара: careful driver / drives carefully.', 'Pair: careful driver / drives carefully.'),
      focusWords: ['careful', 'carefully'],
    }),
    makeStep({
      id: 'adj_adv_mixed_006',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'sound_vs_look_at_pair',
      sentence: 'Choose the natural pair.',
      translation: tri('Выбери естественную пару.', 'Обери природну пару.', 'Choose the natural pair.'),
      options: ['sounds strange / looked strangely', 'sounds strangely / looked strange', 'sounds strange / looked strange', 'sounds strangely / looked strangely'],
      correctAnswer: 'sounds strange / looked strangely',
      correctFeedback: tri('Да. Sounds strange, но looked strangely.', 'Так. Sounds strange, але looked strangely.', 'Yes. Sounds strange / looked strangely.'),
      wrong: {
        'sounds strangely / looked strange': tri('Оба куска перепутаны. Sounds берет strange, looked at me берет strangely.', 'Обидва шматки переплутані. Sounds бере strange, looked at me бере strangely.', 'Use sounds strange / looked strangely.'),
        'sounds strange / looked strange': tri('Sounds strange верно, но looked strange не показывает, как он посмотрел. Нужно looked strangely.', 'Sounds strange правильно, але looked strange не показує, як він подивився. Потрібно looked strangely.', 'Use looked strangely.'),
        'sounds strangely / looked strangely': tri('Looked strangely верно, но sounds strangely здесь лишнее. Нормально: sounds strange.', 'Looked strangely правильно, але sounds strangely тут зайве. Нормально: sounds strange.', 'Use sounds strange.'),
      },
      clue: tri('Sounds описывает состояние. Looked at me описывает действие.', 'Sounds описує стан. Looked at me описує дію.', 'Sounds: state. Looked at me: action.'),
      finalHint: tri('Пара: sounds strange / looked strangely.', 'Пара: sounds strange / looked strangely.', 'Pair: sounds strange / looked strangely.'),
      focusWords: ['strange', 'strangely'],
    }),
    makeStep({
      id: 'adj_adv_mixed_007',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_sentence_correction',
      sentence: 'Choose the natural sentence.',
      translation: tri('Выбери естественное предложение.', 'Обери природне речення.', 'Choose the natural sentence.'),
      options: [
        'He is careful, and he drives carefully.',
        'He is carefully, and he drives careful.',
        'He is careful, and he drives careful.',
        'He is carefully, and he drives carefully.',
      ],
      correctAnswer: 'He is careful, and he drives carefully.',
      correctFeedback: tri('Да. He is careful, and he drives carefully.', 'Так. He is careful, and he drives carefully.', 'Yes. He is careful, and he drives carefully.'),
      wrong: {
        'He is carefully, and he drives careful.': tri('Оба места перепутаны. После is нужно careful, после drives — carefully.', 'Обидва місця переплутані. Після is потрібно careful, після drives — carefully.', 'Use careful after is and carefully after drives.'),
        'He is careful, and he drives careful.': tri('Первая часть верная. Во второй части drives — действие, нужно carefully.', 'Перша частина правильна. У другій drives — дія, потрібно carefully.', 'Use drives carefully.'),
        'He is carefully, and he drives carefully.': tri('Вторая часть верная. В первой после is нужно careful, не carefully.', 'Друга частина правильна. У першій після is потрібно careful, не carefully.', 'Use he is careful.'),
      },
      clue: tri('Is описывает человека. Drives описывает действие.', 'Is описує людину. Drives описує дію.', 'Is: person/state. Drives: action.'),
      finalHint: tri('Фраза соединяет состояние человека и то, как он водит.', 'Фраза поєднує стан людини і те, як він водить.', 'Sentence: He is careful, and he drives carefully.'),
      focusWords: ['careful', 'carefully'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'good_well_confusion',
      'plain_word_after_action',
      'ly_word_after_is',
      'sounds_strange_vs_looked_strangely',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri('Сначала найди, что описывает слово: человека/вещь/состояние или действие.', 'Спочатку знайди, що описує слово: людину/річ/стан чи дію.', 'First find what the word describes.', { 'pt-BR': 'Primeiro encontre o que a palavra descreve: pessoa/coisa/estado ou ação.', vi: 'Trước tiên tìm xem từ đó mô tả gì: người/vật/trạng thái hay hành động.', id: 'Pertama cari apa yang dijelaskan kata itu: orang/benda/keadaan atau aksi.', tr: 'Önce kelimenin neyi anlattığını bul: kişi/şey/durum mu, eylem mi.', pl: 'Najpierw znajdź, co opisuje słowo: osobę/rzecz/stan czy czynność.' }),
    depth2: tri('Проще: “какой?” или “как делает?”', 'Простіше: “який?” або “як робить?”', 'Simpler: what kind, or how?', { 'pt-BR': 'Mais simples: "que tipo?" ou "como faz?".', vi: 'Đơn giản hơn: "loại nào?" hay "làm như thế nào?".', id: 'Lebih sederhana: "seperti apa?" atau "bagaimana melakukannya?".', tr: 'Daha basit: "nasıl biri/şey?" mi, "nasıl yapıyor?" mu?', pl: 'Prościej: "jaki?" czy "jak robi?".' }),
    depth3: tri('Держи смысловые пары: человек или вещь отдельно, действие отдельно.', 'Тримай смислові пари: людина або річ окремо, дія окремо.', 'Use pairs: good teacher / teaches well.', { 'pt-BR': 'Use pares de sentido: pessoa/coisa separada, ação separada.', vi: 'Giữ các cặp nghĩa: người/vật riêng, hành động riêng.', id: 'Gunakan pasangan makna: orang/benda terpisah, aksi terpisah.', tr: 'Anlam çiftlerini tut: kişi ya da şey ayrı, eylem ayrı.', pl: 'Trzymaj pary znaczeniowe: osoba/rzecz osobno, czynność osobno.' }),
    depth4: tri('Почти подсказка: рядом с действием чаще нужен well/quickly/carefully.', 'Майже підказка: поруч із дією частіше потрібен well/quickly/carefully.', 'Near an action, use well/quickly/carefully.', { 'pt-BR': 'Quase uma dica: perto de uma ação, muitas vezes use well/quickly/carefully.', vi: 'Gần như gợi ý: cạnh hành động thường dùng well/quickly/carefully.', id: 'Hampir petunjuk: dekat aksi, sering gunakan well/quickly/carefully.', tr: 'Neredeyse ipucu: eylem yanında çoğu zaman well/quickly/carefully gerekir.', pl: 'Prawie podpowiedź: przy czynności często użyj well/quickly/carefully.' }),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri(
        'Остановись и спроси: описываю кого-то/что-то или описываю действие?',
        'Зупинись і спитай: описую когось/щось чи описую дію?',
        'Pause and ask: person/thing/state, or action?',
        {
          'pt-BR': 'Pare e pergunte: estou descrevendo alguém/algo ou descrevendo uma ação?',
          vi: 'Dừng lại và hỏi: mình đang mô tả ai/cái gì hay mô tả hành động?',
          id: 'Berhenti dan tanyakan: aku menjelaskan seseorang/sesuatu atau menjelaskan aksi?',
          tr: 'Dur ve sor: birini/bir şeyi mi anlatıyorum, yoksa eylemi mi?',
          pl: 'Zatrzymaj się i zapytaj: opisuję kogoś/coś czy opisuję czynność?',
        },
      ),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_described_target_hint_then_retry',
      card: tri(
        'Подсказка покажет, к чему относится слово, но выбор все равно за тобой.',
        'Підказка покаже, до чого належить слово, але вибір усе одно за тобою.',
        'The hint shows what the word describes, but you still choose.',
        {
          'pt-BR': 'A dica mostra a que a palavra se refere, mas a escolha ainda é sua.',
          vi: 'Gợi ý sẽ cho biết từ đó gắn với gì, nhưng bạn vẫn tự chọn.',
          id: 'Petunjuk menunjukkan kata itu merujuk ke apa, tetapi pilihan tetap milikmu.',
          tr: 'İpucu kelimenin neye bağlı olduğunu gösterir, ama seçim yine sende.',
          pl: 'Podpowiedź pokaże, do czego odnosi się słowo, ale wybór nadal należy do ciebie.',
        },
      ),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri(
        'Включаем пошаговый режим: сначала смысл, потом слово.',
        'Вмикаємо покроковий режим: спочатку зміст, потім слово.',
        'Guided mode: meaning first, then the word.',
        {
          'pt-BR': 'Modo guiado: primeiro o sentido, depois a palavra.',
          vi: 'Chế độ từng bước: trước tiên là nghĩa, sau đó là từ.',
          id: 'Mode terpandu: makna dulu, lalu kata.',
          tr: 'Rehberli mod: önce anlam, sonra kelime.',
          pl: 'Tryb prowadzony: najpierw sens, potem słowo.',
        },
      ),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      {
        id: 'guided_adj_adv_001',
        prompt: tri('В good teacher слово good описывает teacher или teaches?', 'У good teacher слово good описує teacher чи teaches?', 'In good teacher, does good describe teacher or teaches?', { 'pt-BR': 'Em good teacher, good descreve teacher ou teaches?', vi: 'Trong good teacher, good mô tả teacher hay teaches?', id: 'Dalam good teacher, good menjelaskan teacher atau teaches?', tr: 'Good teacher ifadesinde good, teacher mı teaches mı anlatır?', pl: 'W good teacher słowo good opisuje teacher czy teaches?' }),
        options: ['teacher', 'teaches'],
        correctIndex: 0,
        thenReturnToExerciseId: 'adj_adv_easy_001',
      },
      {
        id: 'guided_adj_adv_002',
        prompt: tri('В teaches well слово well говорит, как она учит?', 'У teaches well слово well каже, як вона вчить?', 'In teaches well, does well say how she teaches?', { 'pt-BR': 'Em teaches well, well diz como ela ensina?', vi: 'Trong teaches well, well nói cô ấy dạy như thế nào phải không?', id: 'Dalam teaches well, apakah well mengatakan bagaimana dia mengajar?', tr: 'Teaches well ifadesinde well, onun nasıl öğrettiğini mi söyler?', pl: 'W teaches well słowo well mówi, jak ona uczy?' }),
        options: ['yes', 'no'],
        correctIndex: 0,
        thenReturnToExerciseId: 'adj_adv_easy_002',
      },
      {
        id: 'guided_adj_adv_003',
        prompt: tri('После is в He is ___ мы описываем человека?', 'Після is у He is ___ ми описуємо людину?', 'After is in He is ___, are we describing the person?', { 'pt-BR': 'Depois de is em He is ___, descrevemos a pessoa?', vi: 'Sau is trong He is ___, ta đang mô tả người phải không?', id: 'Setelah is dalam He is ___, apakah kita menjelaskan orangnya?', tr: 'He is ___ içinde is sonrasında kişiyi mi anlatıyoruz?', pl: 'Po is w He is ___ opisujemy osobę?' }),
        options: ['yes', 'no'],
        correctIndex: 0,
        thenReturnToExerciseId: 'adj_adv_easy_003',
      },
      {
        id: 'guided_adj_adv_004',
        prompt: tri('В drive ___ мы говорим, как водить?', 'У drive ___ ми кажемо, як водити?', 'In drive ___, do we say how to drive?', { 'pt-BR': 'Em drive ___, dizemos como dirigir?', vi: 'Trong drive ___, ta nói lái xe như thế nào phải không?', id: 'Dalam drive ___, apakah kita mengatakan bagaimana mengemudi?', tr: 'Drive ___ içinde nasıl sürüldüğünü mü söylüyoruz?', pl: 'W drive ___ mówimy, jak prowadzić?' }),
        options: ['yes', 'no'],
        correctIndex: 0,
        thenReturnToExerciseId: 'adj_adv_contrast_005',
      },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'adverb',
    microDiagnosisId: 'adjective_vs_adverb',
    diagnosisLabel: tri('Good / Well', 'Good / Well', 'Good / Well: adjetivo o adverbio', {
      'pt-BR': 'Good / Well: adjetivo ou advérbio',
      vi: 'Good / Well: tính từ hay trạng từ',
      id: 'Good / Well: adjektiva atau adverbia',
      tr: 'Good / Well: sıfat mı zarf mı',
      pl: 'Good / Well: przymiotnik czy przysłówek',
    }),
    contrastSet: CONTRAST,
    focusWords: ['good', 'well', 'quick', 'quickly', 'careful', 'carefully', 'strange', 'strangely'],
    focusPatterns: [
      'good_before_person_word',
      'well_after_teaches',
      'careful_after_is',
      'quick_before_thing',
      'quickly_after_answered',
      'carefully_after_drive',
      'sounds_strange_state',
      'looked_at_strangely_action',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyLevel: 2,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 3,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_adjective_vs_adverb_start',
    answer: 'diagnosis_training_adjective_vs_adverb_answer',
    mastery: 'diagnosis_training_adjective_vs_adverb_mastery',
    recovery: 'diagnosis_training_adjective_vs_adverb_recovery',
    onStart: 'diagnosis_training_started',
    onCorrect: 'diagnosis_training_answer_correct',
    onWrong: 'diagnosis_training_answer_wrong',
    onDepthIncrease: 'diagnosis_training_feedback_depth_increased',
    onGuidedMode: 'diagnosis_training_guided_mode_started',
    onMastery: 'diagnosis_training_mastered',
    onSmartTrainerOpen: 'diagnosis_training_smart_trainer_opened',
    payload: {
      category: 'adverb',
      microDiagnosisId: 'adjective_vs_adverb',
      contrastSet: CONTRAST,
      logExactToken: true,
      logMistakeType: true,
      logExerciseId: true,
      logAttemptCount: true,
      logFeedbackDepth: true,
    },
  },
  routing: {
    diagnosisTrainerRoute: '/problem_coach?category=adverb&microDiagnosisId=adjective_vs_adverb',
  },
  qualityChecklist: {
    hasStableId: true,
    hasCategory: true,
    hasMultilingualTitle: true,
    hasPlainDiagnosisText: true,
    hasMentalModel: true,
    hasContrastSet: true,
    hasAtLeastSixExamples: true,
    hasAtLeastTwelveExercises: true,
    hasEasyContrastMixedStructure: true,
    hasDistractorSpecificFeedback: true,
    hasRetryFeedbackLevels: true,
    hasGuidedModeForRepeatedMistakes: true,
    hasMasteryRules: true,
    hasSmartTrainerConfig: true,
    hasAnalyticsPayload: true,
    hasFallbackRoute: true,
  },
};
