// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

const PLANNED_LOCALE_FALLBACK = {
  'pt-BR': 'Este treino está sendo preparado para este idioma.',
  vi: 'Bài luyện này đang được chuẩn bị cho ngôn ngữ này.',
  id: 'Latihan ini sedang disiapkan untuk bahasa ini.',
  tr: 'Bu alıştırma bu dil için hazırlanıyor.',
  pl: 'To ćwiczenie jest przygotowywane dla tego języka.',
} as const;

const tri = (ru: string, uk = ru, es = ru, planned: Partial<Record<keyof typeof PLANNED_LOCALE_FALLBACK, string>> = {}): TriText => {
  return {
    ru,
    uk,
    es,
  'pt-BR': planned['pt-BR'] ?? PLANNED_LOCALE_FALLBACK['pt-BR'],
  vi: planned.vi ?? PLANNED_LOCALE_FALLBACK.vi,
  id: planned.id ?? PLANNED_LOCALE_FALLBACK.id,
  tr: planned.tr ?? PLANNED_LOCALE_FALLBACK.tr,
  pl: planned.pl ?? PLANNED_LOCALE_FALLBACK.pl,
  };
};

const CONTRAST = ['some', 'any', 'no', 'not any', 'someone/anyone', 'something/anything'];
const SMART_CONTRAST = ['some', 'any', 'no', 'not any', 'something', 'anything'];

function defaultWrong(correct: string): Record<string, TriText> {
  return {
    some: tri(
      `Some здесь звучит не под эту ситуацию. Нужен ${correct}.`,
      `Some тут звучить не пiд цю ситуацiю. Потрiбен ${correct}.`,
      `Some does not fit this situation. Use ${correct}.`,
      {
        'pt-BR': `Some não combina com esta situação. Use ${correct}.`,
        vi: `Some không hợp với tình huống này. Dùng ${correct}.`,
        id: `Some tidak cocok dengan situasi ini. Gunakan ${correct}.`,
        tr: `Some bu duruma uymaz. ${correct} kullan.`,
        pl: `Some nie pasuje do tej sytuacji. Użyj ${correct}.`,
      },
    ),
    any: tri(
      `Any здесь звучит не под эту ситуацию. Нужен ${correct}.`,
      `Any тут звучить не пiд цю ситуацiю. Потрiбен ${correct}.`,
      `Any does not fit this situation. Use ${correct}.`,
      {
        'pt-BR': `Any não combina com esta situação. Use ${correct}.`,
        vi: `Any không hợp với tình huống này. Dùng ${correct}.`,
        id: `Any tidak cocok dengan situasi ini. Gunakan ${correct}.`,
        tr: `Any bu duruma uymaz. ${correct} kullan.`,
        pl: `Any nie pasuje do tej sytuacji. Użyj ${correct}.`,
      },
    ),
    no: tri(
      `No делает фразу отрицательной без don't/not. Здесь нужен ${correct}.`,
      `No робить фразу заперечною без don't/not. Тут потрiбен ${correct}.`,
      `No makes the phrase negative without don't/not. Use ${correct}.`,
      {
        'pt-BR': `No deixa a frase negativa sem don't/not. Aqui precisamos de ${correct}.`,
        vi: `No làm câu phủ định mà không cần don't/not. Ở đây cần ${correct}.`,
        id: `No membuat frasa negatif tanpa don't/not. Di sini perlu ${correct}.`,
        tr: `No, don't/not olmadan cümleyi olumsuz yapar. Burada ${correct} gerekir.`,
        pl: `No tworzy przeczenie bez don't/not. Tutaj potrzebne jest ${correct}.`,
      },
    ),
    none: tri(
      `None не ставится так перед обычным словом. Нужен ${correct}.`,
      `None не ставиться так перед звичайним словом. Потрiбен ${correct}.`,
      `None does not go in this slot. Use ${correct}.`,
      {
        'pt-BR': `None não entra assim antes de uma palavra comum. Use ${correct}.`,
        vi: `None không đặt như vậy trước từ thường. Dùng ${correct}.`,
        id: `None tidak dipakai seperti ini sebelum kata biasa. Gunakan ${correct}.`,
        tr: `None normal bir kelimeden önce böyle gelmez. ${correct} kullan.`,
        pl: `None nie stawia się tak przed zwykłym słowem. Użyj ${correct}.`,
      },
    ),
    something: tri(
      `Something значит "что-то". Здесь нужен ${correct}.`,
      `Something означає "щось". Тут потрiбен ${correct}.`,
      `Something means "something". Use ${correct}.`,
      {
        'pt-BR': `Something significa "algo". Aqui precisamos de ${correct}.`,
        vi: `Something nghĩa là "một điều gì đó". Ở đây cần ${correct}.`,
        id: `Something berarti "sesuatu". Di sini perlu ${correct}.`,
        tr: `Something "bir şey" demektir. Burada ${correct} gerekir.`,
        pl: `Something znaczy "coś". Tutaj potrzebne jest ${correct}.`,
      },
    ),
    anything: tri(
      `Anything здесь меняет оттенок. Нужен ${correct}.`,
      `Anything тут змiнює вiдтiнок. Потрiбен ${correct}.`,
      `Anything changes the tone here. Use ${correct}.`,
      {
        'pt-BR': `Anything muda o tom aqui. Use ${correct}.`,
        vi: `Anything làm đổi sắc thái ở đây. Dùng ${correct}.`,
        id: `Anything mengubah nuansa di sini. Gunakan ${correct}.`,
        tr: `Anything burada tonu değiştirir. ${correct} kullan.`,
        pl: `Anything zmienia tutaj odcień. Użyj ${correct}.`,
      },
    ),
    nothing: tri(
      `Nothing уже само отрицательное. Здесь нужен ${correct}.`,
      `Nothing уже саме заперечне. Тут потрiбен ${correct}.`,
      `Nothing is already negative. Use ${correct}.`,
      {
        'pt-BR': `Nothing já é negativo. Aqui precisamos de ${correct}.`,
        vi: `Nothing tự nó đã phủ định. Ở đây cần ${correct}.`,
        id: `Nothing sudah negatif. Di sini perlu ${correct}.`,
        tr: `Nothing zaten olumsuzdur. Burada ${correct} gerekir.`,
        pl: `Nothing samo jest już przeczące. Tutaj potrzebne jest ${correct}.`,
      },
    ),
    somebody: tri(
      `Somebody - про человека. Здесь нужен ${correct}.`,
      `Somebody - про людину. Тут потрiбен ${correct}.`,
      `Somebody is for a person. Use ${correct}.`,
      {
        'pt-BR': `Somebody é para pessoa. Aqui precisamos de ${correct}.`,
        vi: `Somebody dùng cho người. Ở đây cần ${correct}.`,
        id: `Somebody untuk orang. Di sini perlu ${correct}.`,
        tr: `Somebody insan içindir. Burada ${correct} gerekir.`,
        pl: `Somebody dotyczy osoby. Tutaj potrzebne jest ${correct}.`,
      },
    ),
    anybody: tri(
      `Anybody - про человека. Здесь нужен ${correct}.`,
      `Anybody - про людину. Тут потрiбен ${correct}.`,
      `Anybody is for a person. Use ${correct}.`,
      {
        'pt-BR': `Anybody é para pessoa. Aqui precisamos de ${correct}.`,
        vi: `Anybody dùng cho người. Ở đây cần ${correct}.`,
        id: `Anybody untuk orang. Di sini perlu ${correct}.`,
        tr: `Anybody insan içindir. Burada ${correct} gerekir.`,
        pl: `Anybody dotyczy osoby. Tutaj potrzebne jest ${correct}.`,
      },
    ),
  };
}

function makeStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  sentence: string;
  translation: TriText;
  options: string[];
  correctAnswer: string;
  correctFeedback: TriText;
  wrong?: Record<string, TriText>;
  clue: TriText;
  finalHint: TriText;
  focusWords: string[];
}): DiagnosisTrainingStep {
  const fallbackWrong = defaultWrong(input.correctAnswer);

  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    translation: input.translation,
    explanationBlock: tri(
      'Some и any нельзя выбирать только по переводу "какой-то". Сначала посмотри на ситуацию: обычное утверждение, вопрос, отрицание, предложение, просьба или свободный выбор.',
      'Some i any не можна обирати лише за перекладом "якийсь". Спочатку подивись на ситуацiю: звичайне твердження, питання, заперечення, пропозицiя, прохання або вiльний вибiр.',
      'Do not choose some/any by translation only. First look at the situation: statement, question, negative, offer, request, or free choice.',
      {
        'pt-BR': 'Não escolha some/any apenas pela tradução. Primeiro olhe para a situação: afirmação, pergunta, negativa, oferta, pedido ou escolha livre.',
        vi: 'Đừng chọn some/any chỉ theo bản dịch. Trước tiên hãy nhìn vào tình huống: câu khẳng định, câu hỏi, phủ định, lời mời, yêu cầu hoặc lựa chọn tự do.',
        id: 'Jangan memilih some/any hanya dari terjemahan. Pertama lihat situasinya: pernyataan, pertanyaan, negatif, tawaran, permintaan, atau pilihan bebas.',
        tr: 'Some/any seçimini sadece çeviriye göre yapma. Önce duruma bak: olumlu cümle, soru, olumsuz, teklif, rica veya serbest seçim.',
        pl: 'Nie wybieraj some/any tylko według tłumaczenia. Najpierw spójrz na sytuację: twierdzenie, pytanie, przeczenie, propozycja, prośba albo wolny wybór.',
      },
    ),
    microTask: tri(
      'Выбери естественный кусок: some, any, no, something или anything.',
      'Обери природний шматок: some, any, no, something або anything.',
      'Choose the natural chunk: some, any, no, something, or anything.',
      {
        'pt-BR': 'Escolha o trecho natural: some, any, no, something ou anything.',
        vi: 'Chọn cụm tự nhiên: some, any, no, something hoặc anything.',
        id: 'Pilih potongan yang alami: some, any, no, something, atau anything.',
        tr: 'Doğal parçayı seç: some, any, no, something veya anything.',
        pl: 'Wybierz naturalny fragment: some, any, no, something albo anything.',
      },
    ),
    sentence: input.sentence,
    answerOptions: input.options.map((text) => ({ id: text, text })),
    correctAnswerId: input.correctAnswer,
    correctIndex: input.options.findIndex((option) => option === input.correctAnswer),
    correctFeedback: input.correctFeedback,
    wrongFeedbackByOption: Object.fromEntries(
      input.options
        .filter((option) => option !== input.correctAnswer)
        .map((option) => [
          option,
          input.wrong?.[option] ??
            fallbackWrong[option] ??
            tri(
              'Почти, но здесь решает тип ситуации: утверждение, отрицание, вопрос, предложение или смысл "любой".',
              'Майже, але тут вирiшує тип ситуацiї: твердження, заперечення, питання, пропозицiя або сенс "будь-який".',
              `Almost. Use ${input.correctAnswer}.`,
              {
                'pt-BR': `Quase. Use ${input.correctAnswer}.`,
                vi: `Gần đúng. Dùng ${input.correctAnswer}.`,
                id: `Hampir. Gunakan ${input.correctAnswer}.`,
                tr: `Neredeyse. ${input.correctAnswer} kullan.`,
                pl: `Prawie. Użyj ${input.correctAnswer}.`,
              },
            ),
        ]),
    ),
    retryFeedback: [
      input.clue,
      tri(
        'База такая: some - когда что-то есть или ты мягко предлагаешь/просишь. Any - в отрицаниях, нейтральных вопросах и смысле "любой".',
        'База така: some - коли щось є або ти мʼяко пропонуєш/просиш. Any - у запереченнях, нейтральних питаннях i значеннi "будь-який".',
        'Base rule: some for a positive amount or an offer/request. Any for negatives, neutral questions, and free choice.',
        {
          'pt-BR': 'Regra base: some para quantidade positiva ou oferta/pedido. Any para negativas, perguntas neutras e escolha livre.',
          vi: 'Quy tắc cơ bản: some cho lượng có thật hoặc lời mời/yêu cầu. Any cho phủ định, câu hỏi trung tính và lựa chọn tự do.',
          id: 'Aturan dasar: some untuk jumlah positif atau tawaran/permintaan. Any untuk negatif, pertanyaan netral, dan pilihan bebas.',
          tr: 'Temel kural: some pozitif miktar veya teklif/rica için. Any olumsuzlarda, nötr sorularda ve serbest seçimde kullanılır.',
          pl: 'Podstawowa zasada: some dla pozytywnej ilości albo propozycji/prośby. Any dla przeczeń, neutralnych pytań i wolnego wyboru.',
        },
      ),
      tri(
        'Теперь проверь смысл: что-то есть, чего-то нет, мы спрашиваем, предлагаем или даем свободный выбор?',
        'Тепер перевiр сенс: щось є, чогось немає, ми питаємо, пропонуємо чи даємо вiльний вибiр?',
        input.finalHint.es,
        {
          'pt-BR': 'Agora verifique o sentido: algo existe, algo não existe, estamos perguntando, oferecendo ou dando escolha livre?',
          vi: 'Bây giờ kiểm tra nghĩa: có gì đó, không có gì, ta đang hỏi, đề nghị hay cho lựa chọn tự do?',
          id: 'Sekarang periksa makna: ada sesuatu, tidak ada sesuatu, kita bertanya, menawarkan, atau memberi pilihan bebas?',
          tr: 'Şimdi anlamı kontrol et: bir şey var mı, yok mu, soruyor muyuz, teklif mi ediyoruz, yoksa serbest seçim mi veriyoruz?',
          pl: 'Teraz sprawdź sens: coś jest, czegoś nie ma, pytamy, proponujemy czy dajemy wolny wybór?',
        },
      ),
      tri(
        'Здесь не надо переводить слово отдельно. Надо выбрать по ситуации целиком.',
        'Тут не треба перекладати слово окремо. Треба обрати за ситуацiєю цiлком.',
        `Answer: ${input.correctAnswer}.`,
        {
          'pt-BR': `Resposta: ${input.correctAnswer}.`,
          vi: `Đáp án: ${input.correctAnswer}.`,
          id: `Jawaban: ${input.correctAnswer}.`,
          tr: `Cevap: ${input.correctAnswer}.`,
          pl: `Odpowiedź: ${input.correctAnswer}.`,
        },
      ),
    ],
    fallbackExplanation: tri(
      'Держи карту смысла: что-то есть или мягко предлагаем - some. Отрицание, нейтральный вопрос или выбор без ограничения - any.',
      'Тримай карту сенсу: щось є або мʼяко пропонуємо - some. Заперечення, нейтральне питання або вибір без обмеження - any.',
      "Chunks: I have some time. I don't have any money. Do you have any questions? Would you like some coffee? Choose any lesson.",
      {
        'pt-BR': 'Mapa de sentido: algo existe ou oferecemos gentilmente - some. Negativa, pergunta neutra ou escolha sem limite - any.',
        vi: 'Bản đồ nghĩa: có gì đó hoặc mời nhẹ nhàng - some. Phủ định, câu hỏi trung tính hoặc lựa chọn không giới hạn - any.',
        id: 'Peta makna: ada sesuatu atau menawarkan dengan halus - some. Negatif, pertanyaan netral, atau pilihan tanpa batas - any.',
        tr: 'Anlam haritası: bir şey var veya nazikçe teklif ediyoruz - some. Olumsuz, nötr soru veya sınırsız seçim - any.',
        pl: 'Mapa sensu: coś jest albo łagodnie proponujemy - some. Przeczenie, neutralne pytanie albo wybór bez ograniczeń - any.',
      },
    ),
    focusWords: input.focusWords,
  };
}

export const QUANTIFIER_SOME_ANY_TRAINING: DiagnosisTraining = {
  id: 'quantifier_some_any',
  category: 'determiner',
  version: '1.0.0',
  status: 'active',
  priority: 18,
  supportedLocales: ['ru', 'uk', 'es'],
  title: tri(
    'Some / Any: что-то есть или вообще нет',
    'Some / Any: щось є або взагалі немає',
    'Some / Any',
    {
      'pt-BR': 'Some / Any: algo existe ou não existe nada',
      vi: 'Some / Any: có gì đó hay hoàn toàn không có',
      id: 'Some / Any: ada sesuatu atau tidak ada sama sekali',
      tr: 'Some / Any: bir şey var mı yok mu',
      pl: 'Some / Any: coś jest albo nie ma nic',
    },
  ),
  shortTitle: tri('Some / Any', 'Some / Any', 'Some / Any', {
    'pt-BR': 'Some / Any',
    vi: 'Some / Any',
    id: 'Some / Any',
    tr: 'Some / Any',
    pl: 'Some / Any',
  }),
  shortDiagnosis: tri(
    'Ты путаешь some и any, потому что переводишь их как "какой-то" или "немного", а английский смотрит на тип ситуации.',
    'Ти плутаєш some i any, бо перекладаєш їх як "якийсь" або "трохи", а англiйська дивиться на тип ситуацiї.',
    'You mix some and any because you translate the word, not the situation.',
    {
      'pt-BR': 'Você confunde some e any porque traduz a palavra, não a situação.',
      vi: 'Bạn nhầm some và any vì dịch từng từ, không nhìn vào tình huống.',
      id: 'Kamu mencampur some dan any karena menerjemahkan kata, bukan situasinya.',
      tr: 'Some ve any karışıyor çünkü kelimeyi çeviriyorsun, duruma bakmıyorsun.',
      pl: 'Mylisz some i any, bo tłumaczysz słowo, a nie sytuację.',
    },
  ),
  diagnosisText: tri(
    'Some обычно звучит так, будто что-то есть или ты мягко предлагаешь. Any часто проверяет, есть ли что-то вообще, работает после отрицания или значит "любой". Поэтому вопрос сам по себе еще не решает выбор.',
    'Some зазвичай звучить так, ніби щось є або ти мʼяко пропонуєш. Any часто перевіряє, чи є щось узагалі, працює після заперечення або означає "будь-який". Тому питання саме по собі ще не вирішує вибір.',
    "Some often means there is a positive amount. Any often checks existence or follows a negative. In offers and requests, some returns.",
    {
      'pt-BR': 'Some muitas vezes soa como se algo existisse ou como uma oferta gentil. Any muitas vezes verifica existência, vem depois de negativa ou significa "qualquer". A pergunta sozinha não decide a escolha.',
      vi: 'Some thường nghe như có một lượng gì đó hoặc là lời mời nhẹ nhàng. Any thường kiểm tra có tồn tại không, đi sau phủ định hoặc nghĩa là "bất kỳ". Chỉ có câu hỏi chưa đủ để quyết định.',
      id: 'Some sering terdengar seolah ada sesuatu atau sebagai tawaran halus. Any sering memeriksa keberadaan, mengikuti negatif, atau berarti "apa saja". Pertanyaan saja belum menentukan pilihan.',
      tr: 'Some çoğu zaman bir şey varmış gibi veya nazik teklif gibi duyulur. Any varlığı kontrol eder, olumsuzdan sonra gelir veya "herhangi bir" anlamına gelir. Soru tek başına seçimi belirlemez.',
      pl: 'Some często brzmi tak, jakby coś było, albo jak łagodna propozycja. Any często sprawdza istnienie, działa po przeczeniu albo znaczy "dowolny". Samo pytanie jeszcze nie rozstrzyga wyboru.',
    },
  ),
  mentalModel: tri(
    'Не спрашивай "some или any переводится как какой-то?". Спроси: это что-то есть? Проверяем наличие? Отрицаем? Предлагаем? Просим? Говорим "любой"? От ответа зависит выбор.',
    'Не питай "some чи any перекладається як якийсь?". Запитай: щось є? Перевiряємо наявнiсть? Заперечуємо? Пропонуємо? Просимо? Кажемо "будь-який"? Вiд вiдповiдi залежить вибiр.',
    'Ask what the situation does: positive amount, checking existence, negative, offer, request, or free choice.',
    {
      'pt-BR': 'Pergunte o que a situação faz: quantidade positiva, verificação de existência, negativa, oferta, pedido ou escolha livre.',
      vi: 'Hãy hỏi tình huống đang làm gì: lượng có thật, kiểm tra tồn tại, phủ định, lời mời, yêu cầu hay lựa chọn tự do.',
      id: 'Tanyakan apa fungsi situasinya: jumlah positif, memeriksa keberadaan, negatif, tawaran, permintaan, atau pilihan bebas.',
      tr: 'Durumun ne yaptığına bak: pozitif miktar, varlık kontrolü, olumsuz, teklif, rica veya serbest seçim.',
      pl: 'Zapytaj, co robi sytuacja: pozytywna ilość, sprawdzanie istnienia, przeczenie, propozycja, prośba albo wolny wybór.',
    },
  ),
  contrastSet: CONTRAST,
  coreRule: tri(
    'Положительное количество или мягкое предложение часто берут some. Отрицание, нейтральный вопрос и смысл "любой" часто берут any.',
    'Позитивна кількість або мʼяка пропозиція часто беруть some. Заперечення, нейтральне питання і сенс "будь-який" часто беруть any.',
    "I have some money. I don't have any money. Do you have any questions? Would you like some tea? Can I have some water? You can choose any lesson.",
    {
      'pt-BR': 'Quantidade positiva ou oferta gentil costuma usar some. Negativa, pergunta neutra e sentido de "qualquer" costumam usar any.',
      vi: 'Lượng có thật hoặc lời mời nhẹ nhàng thường dùng some. Phủ định, câu hỏi trung tính và nghĩa "bất kỳ" thường dùng any.',
      id: 'Jumlah positif atau tawaran halus sering memakai some. Negatif, pertanyaan netral, dan makna "apa saja" sering memakai any.',
      tr: 'Pozitif miktar veya nazik teklif çoğu zaman some alır. Olumsuz, nötr soru ve "herhangi bir" anlamı çoğu zaman any alır.',
      pl: 'Pozytywna ilość albo łagodna propozycja często bierze some. Przeczenie, neutralne pytanie i sens "dowolny" często biorą any.',
    },
  ),
  whatUserMustLearn: {
    ru: [
      'В обычном положительном ответе часто нужен some: I have some time.',
      "После don't/not часто нужен any: I don't have any money.",
      'В нейтральном вопросе часто нужен any: Do you have any questions?',
      'В предложении еды или напитка часто нужен some: Would you like some coffee?',
      'В просьбе часто нужен some: Can I have some water?',
      'В смысле "любой" нужен any: Choose any lesson.',
      "No работает без don't/not: I have no idea.",
      'Something часто звучит как "что-то" в положительной фразе.',
      'Anything часто идет после отрицания или в вопросе.',
    ],
    uk: [
      'У звичайному позитивному реченнi часто потрiбен some: I have some time.',
      "Пiсля don't/not часто потрiбен any: I don't have any money.",
      'У нейтральному питаннi часто потрiбен any: Do you have any questions?',
      'У пропозицiї їжi або напою часто потрiбен some: Would you like some coffee?',
      'У проханнi часто потрiбен some: Can I have some water?',
      'У значеннi "будь-який" потрiбен any: Choose any lesson.',
      "No працює без don't/not: I have no idea.",
      'Something часто звучить як "щось" у позитивнiй фразi.',
      'Anything часто йде пiсля заперечення або в питаннi.',
    ],
    es: [
      'Positive amount: I have some time.',
      "Negative: I don't have any money.",
      'Neutral question: Do you have any questions?',
      'Offer: Would you like some coffee?',
      'Request: Can I have some water?',
      'Free choice: Choose any lesson.',
      "No works without don't/not: I have no idea.",
      'Something is often positive.',
      'Anything often follows a negative or question.',
    ],
    'pt-BR': [
      'Em uma afirmação comum, some muitas vezes indica uma quantidade positiva: I have some time.',
      "Depois de don't/not, muitas vezes usamos any: I don't have any money.",
      'Em pergunta neutra, muitas vezes usamos any: Do you have any questions?',
      'Em oferta de comida ou bebida, muitas vezes usamos some: Would you like some coffee?',
      'Em pedido, muitas vezes usamos some: Can I have some water?',
      'No sentido de "qualquer", usamos any: Choose any lesson.',
      "A palavra no funciona sem don't/not: I have no idea.",
      'Something costuma soar positivo.',
      'Anything costuma aparecer depois de negativa ou pergunta.',
    ],
    vi: [
      'Trong câu khẳng định thông thường, some thường chỉ một lượng có thật: I have some time.',
      "Sau don't/not, thường dùng any: I don't have any money.",
      'Trong câu hỏi trung tính, thường dùng any: Do you have any questions?',
      'Khi mời đồ ăn hoặc đồ uống, thường dùng some: Would you like some coffee?',
      'Khi xin hoặc yêu cầu, thường dùng some: Can I have some water?',
      'Với nghĩa "bất kỳ", dùng any: Choose any lesson.',
      "No hoạt động không cần don't/not: I have no idea.",
      'Something thường mang cảm giác khẳng định.',
      'Anything thường đi sau phủ định hoặc trong câu hỏi.',
    ],
    id: [
      'Dalam pernyataan biasa, some sering menunjukkan jumlah positif: I have some time.',
      "Setelah don't/not, sering gunakan any: I don't have any money.",
      'Dalam pertanyaan netral, sering gunakan any: Do you have any questions?',
      'Dalam tawaran makanan atau minuman, sering gunakan some: Would you like some coffee?',
      'Dalam permintaan, sering gunakan some: Can I have some water?',
      'Untuk arti "apa saja", gunakan any: Choose any lesson.',
      "No bekerja tanpa don't/not: I have no idea.",
      'Something sering terdengar positif.',
      'Anything sering mengikuti kalimat negatif atau pertanyaan.',
    ],
    tr: [
      'Normal olumlu cümlede some genellikle pozitif bir miktar gösterir: I have some time.',
      "Don't/not sonrasında genellikle any kullanılır: I don't have any money.",
      'Nötr soruda genellikle any kullanılır: Do you have any questions?',
      'Yiyecek veya içecek teklifinde genellikle some kullanılır: Would you like some coffee?',
      'Rica ederken genellikle some kullanılır: Can I have some water?',
      '"Herhangi bir" anlamında any kullanılır: Choose any lesson.',
      "No, don't/not olmadan çalışır: I have no idea.",
      'Something çoğu zaman olumlu duyulur.',
      'Anything çoğu zaman olumsuz cümle veya sorudan sonra gelir.',
    ],
    pl: [
      'W zwykłym zdaniu twierdzącym some często oznacza pozytywną ilość: I have some time.',
      "Po don't/not często używamy any: I don't have any money.",
      'W neutralnym pytaniu często używamy any: Do you have any questions?',
      'W propozycji jedzenia albo napoju często używamy some: Would you like some coffee?',
      'W prośbie często używamy some: Can I have some water?',
      'W znaczeniu "dowolny" używamy any: Choose any lesson.',
      "No działa bez don't/not: I have no idea.",
      'Something często brzmi pozytywnie.',
      'Anything często występuje po przeczeniu albo w pytaniu.',
    ],
  },
  examples: [
    {
      en: 'I have some free time today.',
      ru: 'У меня сегодня есть немного свободного времени.',
      uk: 'У мене сьогоднi є трохи вiльного часу.',
      es: 'I have some free time today.',
      'pt-BR': 'Tenho um pouco de tempo livre hoje.',
      vi: 'Hôm nay tôi có chút thời gian rảnh.',
      id: 'Saya punya sedikit waktu luang hari ini.',
      tr: 'Bugün biraz boş vaktim var.',
      pl: 'Mam dziś trochę wolnego czasu.',
      why: tri('Время есть, количество положительное: some.', 'Час є, кiлькiсть позитивна: some.', 'Positive amount: some.', {
        'pt-BR': 'Há tempo, quantidade positiva: some.',
        vi: 'Có thời gian, lượng là khẳng định: some.',
        id: 'Ada waktu, jumlah positif: some.',
        tr: 'Zaman var, miktar olumlu: some.',
        pl: 'Czas jest, ilość pozytywna: some.',
      }),
    },
    {
      en: "I don't have any free time today.",
      ru: 'У меня сегодня нет свободного времени.',
      uk: 'У мене сьогоднi немає вiльного часу.',
      es: "I don't have any free time today.",
      'pt-BR': 'Hoje não tenho nenhum tempo livre.',
      vi: 'Hôm nay tôi không có chút thời gian rảnh nào.',
      id: 'Saya tidak punya waktu luang sama sekali hari ini.',
      tr: 'Bugün hiç boş vaktim yok.',
      pl: 'Dziś nie mam wcale wolnego czasu.',
      why: tri("После don't нужен any.", "Пiсля don't потрiбен any.", "After don't: any.", {
        'pt-BR': "Depois de don't, precisamos de any.",
        vi: "Sau don't cần any.",
        id: "Setelah don't perlu any.",
        tr: "Don't sonrasında any gerekir.",
        pl: "Po don't potrzebne jest any.",
      }),
    },
    {
      en: 'Do you have any questions?',
      ru: 'У тебя есть вопросы?',
      uk: 'У тебе є питання?',
      es: 'Do you have any questions?',
      'pt-BR': 'Você tem alguma pergunta?',
      vi: 'Bạn có câu hỏi nào không?',
      id: 'Apakah kamu punya pertanyaan?',
      tr: 'Herhangi bir sorun var mı?',
      pl: 'Czy masz jakieś pytania?',
      why: tri('Нейтрально проверяем наличие вопросов: any.', 'Нейтрально перевiряємо наявнiсть питань: any.', 'Neutral question: any.', {
        'pt-BR': 'Verificamos de forma neutra se há perguntas: any.',
        vi: 'Kiểm tra trung tính xem có câu hỏi không: any.',
        id: 'Memeriksa secara netral apakah ada pertanyaan: any.',
        tr: 'Soru var mı diye nötr biçimde kontrol ediyoruz: any.',
        pl: 'Neutralnie sprawdzamy, czy są pytania: any.',
      }),
    },
    {
      en: 'Would you like some tea?',
      ru: 'Хочешь чаю?',
      uk: 'Хочеш чаю?',
      es: 'Would you like some tea?',
      'pt-BR': 'Você gostaria de um pouco de chá?',
      vi: 'Bạn có muốn uống chút trà không?',
      id: 'Apakah kamu mau sedikit teh?',
      tr: 'Biraz çay ister misin?',
      pl: 'Czy chcesz trochę herbaty?',
      why: tri('Это предложение, поэтому звучит some.', 'Це пропозицiя, тому звучить some.', 'Offer: some.', {
        'pt-BR': 'É uma oferta, por isso soa natural usar some.',
        vi: 'Đây là lời mời, nên dùng some tự nhiên.',
        id: 'Ini tawaran, jadi some terdengar alami.',
        tr: 'Bu bir teklif, bu yüzden some doğal gelir.',
        pl: 'To propozycja, więc naturalnie brzmi some.',
      }),
    },
    {
      en: 'Can I have some water?',
      ru: 'Можно мне воды?',
      uk: 'Можна менi води?',
      es: 'Can I have some water?',
      'pt-BR': 'Posso tomar um pouco de água?',
      vi: 'Cho tôi xin chút nước được không?',
      id: 'Boleh saya minta sedikit air?',
      tr: 'Biraz su alabilir miyim?',
      pl: 'Czy mogę prosić trochę wody?',
      why: tri('Это просьба, поэтому звучит some.', 'Це прохання, тому звучить some.', 'Request: some.', {
        'pt-BR': 'É um pedido, por isso soa natural usar some.',
        vi: 'Đây là lời yêu cầu, nên dùng some tự nhiên.',
        id: 'Ini permintaan, jadi some terdengar alami.',
        tr: 'Bu bir rica, bu yüzden some doğal gelir.',
        pl: 'To prośba, więc naturalnie brzmi some.',
      }),
    },
    {
      en: 'You can choose any lesson.',
      ru: 'Ты можешь выбрать любой урок.',
      uk: 'Ти можеш обрати будь-який урок.',
      es: 'You can choose any lesson.',
      'pt-BR': 'Você pode escolher qualquer lição.',
      vi: 'Bạn có thể chọn bất kỳ bài học nào.',
      id: 'Kamu bisa memilih pelajaran apa saja.',
      tr: 'Herhangi bir dersi seçebilirsin.',
      pl: 'Możesz wybrać dowolną lekcję.',
      why: tri('Любой без ограничения = any.', 'Будь-який без обмеження = any.', 'Free choice: any.', {
        'pt-BR': 'Qualquer sem limite = any.',
        vi: 'Bất kỳ không giới hạn = any.',
        id: 'Apa saja tanpa batas = any.',
        tr: 'Sınırsız herhangi bir = any.',
        pl: 'Dowolny bez ograniczeń = any.',
      }),
    },
    {
      en: 'I need something to drink.',
      ru: 'Мне нужно что-нибудь выпить.',
      uk: 'Менi потрiбно щось випити.',
      es: 'I need something to drink.',
      'pt-BR': 'Preciso de algo para beber.',
      vi: 'Tôi cần thứ gì đó để uống.',
      id: 'Saya butuh sesuatu untuk diminum.',
      tr: 'İçecek bir şeye ihtiyacım var.',
      pl: 'Potrzebuję czegoś do picia.',
      why: tri('В положительной фразе естественно something.', 'У позитивнiй фразi природно something.', 'Positive need: something.', {
        'pt-BR': 'Em frase positiva, something é natural.',
        vi: 'Trong câu khẳng định, something tự nhiên.',
        id: 'Dalam kalimat positif, something terdengar alami.',
        tr: 'Olumlu cümlede something doğaldır.',
        pl: 'W zdaniu twierdzącym naturalne jest something.',
      }),
    },
    {
      en: "I don't need anything.",
      ru: 'Мне ничего не нужно.',
      uk: 'Менi нiчого не потрiбно.',
      es: "I don't need anything.",
      'pt-BR': 'Não preciso de nada.',
      vi: 'Tôi không cần gì cả.',
      id: 'Saya tidak membutuhkan apa pun.',
      tr: 'Hiçbir şeye ihtiyacım yok.',
      pl: 'Nie potrzebuję niczego.',
      why: tri("После don't естественно anything.", "Пiсля don't природно anything.", "After don't: anything.", {
        'pt-BR': "Depois de don't, anything é natural.",
        vi: "Sau don't, anything tự nhiên.",
        id: "Setelah don't, anything terdengar alami.",
        tr: "Don't sonrasında anything doğaldır.",
        pl: "Po don't naturalne jest anything.",
      }),
    },
  ],
  introBlocks: [
    {
      id: 'intro_problem',
      type: 'diagnosis',
      text: tri(
        'Some и any ломаются, когда ты переводишь слово отдельно. Английский сначала смотрит на ситуацию.',
        'Some i any ламаються, коли ти перекладаєш слово окремо. Англiйська спочатку дивиться на ситуацiю.',
        'Some and any break when you translate the word in isolation.',
        {
          'pt-BR': 'Some e any quebram quando você traduz a palavra isoladamente. O inglês olha primeiro para a situação.',
          vi: 'Some và any dễ sai khi bạn dịch từng từ riêng lẻ. Tiếng Anh nhìn vào tình huống trước.',
          id: 'Some dan any menjadi salah ketika kamu menerjemahkan kata secara terpisah. Bahasa Inggris melihat situasinya terlebih dahulu.',
          tr: 'Some ve any, kelimeyi tek başına çevirdiğinde bozulur. İngilizce önce duruma bakar.',
          pl: 'Some i any psują się, gdy tłumaczysz słowo osobno. Angielski najpierw patrzy na sytuację.',
        },
      ),
    },
    {
      id: 'intro_rule',
      type: 'rule',
      text: tri(
        'Карта: что-то есть - some. Ничего нет или проверяем вообще наличие - any. Предлагаем или просим мягко - снова some.',
        'Карта: щось є - some. Нічого немає або перевіряємо наявність узагалі - any. Пропонуємо або просимо мʼяко - знову some.',
        "Map: some time, any money, any questions, some coffee, any lesson.",
        {
          'pt-BR': 'Mapa: algo existe - some. Nada existe ou verificamos se existe algo - any. Oferecemos ou pedimos com delicadeza - some de novo.',
          vi: 'Bản đồ: có gì đó - some. Không có gì hoặc kiểm tra có tồn tại không - any. Mời hoặc xin một cách nhẹ nhàng - lại dùng some.',
          id: 'Peta: ada sesuatu - some. Tidak ada apa pun atau memeriksa keberadaan - any. Menawarkan atau meminta dengan halus - some lagi.',
          tr: 'Harita: bir şey var - some. Hiçbir şey yok veya varlığı kontrol ediyoruz - any. Nazikçe teklif ediyor veya rica ediyoruz - yine some.',
          pl: 'Mapa: coś jest - some. Niczego nie ma albo sprawdzamy istnienie - any. Proponujemy albo prosimy łagodnie - znowu some.',
        },
      ),
    },
    {
      id: 'intro_warning',
      type: 'warning',
      text: tri(
        'Вопрос не всегда означает any. Would you like some coffee? - это предложение, поэтому some.',
        'Питання не завжди означає any. Would you like some coffee? - це пропозицiя, тому some.',
        'A question does not always mean any. Offers often use some.',
        {
          'pt-BR': 'Pergunta nem sempre significa any. Would you like some coffee? é uma oferta, por isso some.',
          vi: 'Câu hỏi không phải lúc nào cũng là any. Would you like some coffee? là lời mời, nên dùng some.',
          id: 'Pertanyaan tidak selalu berarti any. Would you like some coffee? adalah tawaran, jadi some.',
          tr: 'Soru her zaman any demek değildir. Would you like some coffee? bir tekliftir, bu yüzden some.',
          pl: 'Pytanie nie zawsze oznacza any. Would you like some coffee? to propozycja, więc some.',
        },
      ),
    },
  ],
  steps: [
    makeStep({
      id: 'some_any_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'some_positive_statement',
      sentence: 'I have ___ free time today.',
      translation: tri('У меня сегодня есть немного свободного времени.', 'У мене сьогоднi є трохи вiльного часу.', 'I have some free time today.', {
        'pt-BR': 'Tenho um pouco de tempo livre hoje.',
        vi: 'Hôm nay tôi có chút thời gian rảnh.',
        id: 'Saya punya sedikit waktu luang hari ini.',
        tr: 'Bugün biraz boş vaktim var.',
        pl: 'Mam dziś trochę wolnego czasu.',
      }),
      options: ['some', 'any', 'no', 'none'],
      correctAnswer: 'some',
      correctFeedback: tri('Да. Время есть, поэтому some free time.', 'Так. Час є, тому some free time.', 'Yes. Positive amount: some free time.', {
        'pt-BR': 'Sim. Há tempo, por isso some free time.',
        vi: 'Đúng. Có thời gian, nên dùng some free time.',
        id: 'Ya. Ada waktu, jadi some free time.',
        tr: 'Evet. Zaman var, bu yüzden some free time.',
        pl: 'Tak. Czas jest, więc some free time.',
      }),
      clue: tri('Есть немного времени = some time.', 'Є трохи часу = some time.', 'There is some time.', {
        'pt-BR': 'Há um pouco de tempo = some time.',
        vi: 'Có một chút thời gian = some time.',
        id: 'Ada sedikit waktu = some time.',
        tr: 'Biraz zaman var = some time.',
        pl: 'Jest trochę czasu = some time.',
      }),
      finalHint: tri('Фраза: I have some free time today.', 'Фраза: I have some free time today.', 'Sentence: I have some free time today.', {
        'pt-BR': 'Frase: I have some free time today.',
        vi: 'Câu: I have some free time today.',
        id: 'Kalimat: I have some free time today.',
        tr: 'Cümle: I have some free time today.',
        pl: 'Zdanie: I have some free time today.',
      }),
      focusWords: ['some time'],
    }),
    makeStep({
      id: 'some_any_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'some_positive_plural',
      sentence: 'She bought ___ apples.',
      translation: tri('Она купила несколько яблок.', 'Вона купила кiлька яблук.', 'She bought some apples.', {
        'pt-BR': 'Ela comprou algumas maçãs.',
        vi: 'Cô ấy đã mua vài quả táo.',
        id: 'Dia membeli beberapa apel.',
        tr: 'Birkaç elma aldı.',
        pl: 'Kupiła kilka jabłek.',
      }),
      options: ['some', 'any', 'no', 'anything'],
      correctAnswer: 'some',
      correctFeedback: tri('Да. Яблоки реально куплены: some apples.', 'Так. Яблука справдi купленi: some apples.', 'Yes. Positive amount: some apples.', {
        'pt-BR': 'Sim. As maçãs foram realmente compradas: some apples.',
        vi: 'Đúng. Táo thực sự đã được mua: some apples.',
        id: 'Ya. Apelnya benar-benar dibeli: some apples.',
        tr: 'Evet. Elmalar gerçekten alınmış: some apples.',
        pl: 'Tak. Jabłka naprawdę zostały kupione: some apples.',
      }),
      clue: tri('Несколько яблок = some apples.', 'Кiлька яблук = some apples.', 'Some apples.', {
        'pt-BR': 'Algumas maçãs = some apples.',
        vi: 'Vài quả táo = some apples.',
        id: 'Beberapa apel = some apples.',
        tr: 'Birkaç elma = some apples.',
        pl: 'Kilka jabłek = some apples.',
      }),
      finalHint: tri('Фраза: She bought some apples.', 'Фраза: She bought some apples.', 'Sentence: She bought some apples.', {
        'pt-BR': 'Frase: She bought some apples.',
        vi: 'Câu: She bought some apples.',
        id: 'Kalimat: She bought some apples.',
        tr: 'Cümle: She bought some apples.',
        pl: 'Zdanie: She bought some apples.',
      }),
      focusWords: ['some apples'],
    }),
    makeStep({
      id: 'some_any_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'any_negative',
      sentence: "I don't have ___ money.",
      translation: tri('У меня нет денег.', 'У мене немає грошей.', "I don't have any money.", {
        'pt-BR': 'Não tenho dinheiro.',
        vi: 'Tôi không có tiền.',
        id: 'Saya tidak punya uang.',
        tr: 'Param yok.',
        pl: 'Nie mam pieniędzy.',
      }),
      options: ['some', 'any', 'something', 'somebody'],
      correctAnswer: 'any',
      correctFeedback: tri("Да. После don't в такой фразе нужен any money.", "Так. Пiсля don't у такiй фразi потрiбен any money.", "Yes. After don't: any money.", {
        'pt-BR': "Sim. Depois de don't, nesta frase precisamos de any money.",
        vi: "Đúng. Sau don't trong câu này cần any money.",
        id: "Ya. Setelah don't dalam frasa ini perlu any money.",
        tr: "Evet. Bu cümlede don't sonrasında any money gerekir.",
        pl: "Tak. Po don't w takim zdaniu potrzebne jest any money.",
      }),
      wrong: {
        some: tri("Some после don't здесь не работает. Нормально: I don't have any money.", "Some пiсля don't тут не працює. Нормально: I don't have any money.", "After don't, use any money.", {
          'pt-BR': "Some depois de don't não funciona aqui. Natural: I don't have any money.",
          vi: "Some sau don't không đúng ở đây. Tự nhiên: I don't have any money.",
          id: "Some setelah don't tidak cocok di sini. Alami: I don't have any money.",
          tr: "Some, don't sonrasında burada çalışmaz. Doğal olan: I don't have any money.",
          pl: "Some po don't tutaj nie działa. Naturalnie: I don't have any money.",
        }),
      },
      clue: tri("Есть don't, значит нужен блок any money.", "Є don't, отже потрiбен блок any money.", "Don't -> any money.", {
        'pt-BR': "Há don't, então precisamos do bloco any money.",
        vi: "Có don't, nên cần cụm any money.",
        id: "Ada don't, jadi perlu blok any money.",
        tr: "Don't var, bu yüzden any money bloğu gerekir.",
        pl: "Jest don't, więc potrzebny jest blok any money.",
      }),
      finalHint: tri("Фраза: I don't have any money.", "Фраза: I don't have any money.", "Sentence: I don't have any money.", {
        'pt-BR': "Frase: I don't have any money.",
        vi: "Câu: I don't have any money.",
        id: "Kalimat: I don't have any money.",
        tr: "Cümle: I don't have any money.",
        pl: "Zdanie: I don't have any money.",
      }),
      focusWords: ['any money'],
    }),
    makeStep({
      id: 'some_any_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'any_neutral_question',
      sentence: 'Do you have ___ questions?',
      translation: tri('У тебя есть вопросы?', 'У тебе є питання?', 'Do you have any questions?', {
        'pt-BR': 'Você tem alguma pergunta?',
        vi: 'Bạn có câu hỏi nào không?',
        id: 'Apakah kamu punya pertanyaan?',
        tr: 'Herhangi bir sorun var mı?',
        pl: 'Czy masz jakieś pytania?',
      }),
      options: ['some', 'any', 'no', 'something'],
      correctAnswer: 'any',
      correctFeedback: tri('Да. Нейтрально проверяем наличие вопросов: any questions.', 'Так. Нейтрально перевiряємо наявнiсть питань: any questions.', 'Yes. Neutral question: any questions.', {
        'pt-BR': 'Sim. Verificamos de forma neutra se há perguntas: any questions.',
        vi: 'Đúng. Kiểm tra trung tính xem có câu hỏi không: any questions.',
        id: 'Ya. Memeriksa secara netral apakah ada pertanyaan: any questions.',
        tr: 'Evet. Soru var mı diye nötr biçimde kontrol ediyoruz: any questions.',
        pl: 'Tak. Neutralnie sprawdzamy, czy są pytania: any questions.',
      }),
      wrong: {
        some: tri('Some в вопросе возможно, если ты ожидаешь "да" или предлагаешь. Здесь нейтральный вопрос: any questions.', 'Some у питаннi можливе, якщо ти очiкуєш "так" або пропонуєш. Тут нейтральне питання: any questions.', 'Here it is a neutral question: any questions.', {
          'pt-BR': 'Some em pergunta é possível se você espera "sim" ou oferece algo. Aqui é pergunta neutra: any questions.',
          vi: 'Some trong câu hỏi có thể dùng nếu bạn mong câu trả lời "có" hoặc đang mời. Ở đây là câu hỏi trung tính: any questions.',
          id: 'Some dalam pertanyaan bisa dipakai jika kamu mengharapkan "ya" atau menawarkan. Di sini pertanyaannya netral: any questions.',
          tr: 'Soruda some, "evet" bekliyorsan veya teklif ediyorsan mümkündür. Burada nötr soru var: any questions.',
          pl: 'Some w pytaniu jest możliwe, jeśli oczekujesz "tak" albo coś proponujesz. Tutaj jest neutralne pytanie: any questions.',
        }),
      },
      clue: tri('Просто спрашиваем, есть ли вопросы вообще.', 'Просто питаємо, чи є питання взагалi.', 'Checking if questions exist.', {
        'pt-BR': 'Só perguntamos se existem perguntas.',
        vi: 'Chỉ hỏi xem có câu hỏi nào không.',
        id: 'Hanya bertanya apakah ada pertanyaan.',
        tr: 'Sadece soru var mı diye soruyoruz.',
        pl: 'Po prostu pytamy, czy są jakieś pytania.',
      }),
      finalHint: tri('Фраза: Do you have any questions?', 'Фраза: Do you have any questions?', 'Sentence: Do you have any questions?', {
        'pt-BR': 'Frase: Do you have any questions?',
        vi: 'Câu: Do you have any questions?',
        id: 'Kalimat: Do you have any questions?',
        tr: 'Cümle: Do you have any questions?',
        pl: 'Zdanie: Do you have any questions?',
      }),
      focusWords: ['any questions'],
    }),
    makeStep({
      id: 'some_any_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'any_negative_plural',
      sentence: "There aren't ___ chairs in the room.",
      translation: tri('В комнате нет стульев.', 'У кiмнатi немає стiльцiв.', "There aren't any chairs in the room.", {
        'pt-BR': 'Não há cadeiras no quarto.',
        vi: 'Trong phòng không có chiếc ghế nào.',
        id: 'Tidak ada kursi di ruangan itu.',
        tr: 'Odada hiç sandalye yok.',
        pl: 'W pokoju nie ma żadnych krzeseł.',
      }),
      options: ['some', 'any', 'no', 'none'],
      correctAnswer: 'any',
      correctFeedback: tri("Да. После aren't нужен блок any chairs.", "Так. Пiсля aren't потрiбен блок any chairs.", "Yes. After aren't: any chairs.", {
        'pt-BR': "Sim. Depois de aren't precisamos do bloco any chairs.",
        vi: "Đúng. Sau aren't cần cụm any chairs.",
        id: "Ya. Setelah aren't perlu blok any chairs.",
        tr: "Evet. Aren't sonrasında any chairs bloğu gerekir.",
        pl: "Tak. Po aren't potrzebny jest blok any chairs.",
      }),
      wrong: {
        no: tri("Aren't no chairs дает лишнее отрицание. Нормально: aren't any chairs или there are no chairs.", "Aren't no chairs дає зайве заперечення. Нормально: aren't any chairs або there are no chairs.", "Use aren't any chairs or there are no chairs.", {
          'pt-BR': "Aren't no chairs cria uma negativa extra. Natural: aren't any chairs ou there are no chairs.",
          vi: "Aren't no chairs tạo phủ định thừa. Tự nhiên: aren't any chairs hoặc there are no chairs.",
          id: "Aren't no chairs memberi negatif berlebih. Alami: aren't any chairs atau there are no chairs.",
          tr: "Aren't no chairs fazla olumsuzluk verir. Doğal olan: aren't any chairs veya there are no chairs.",
          pl: "Aren't no chairs daje dodatkowe przeczenie. Naturalnie: aren't any chairs albo there are no chairs.",
        }),
        some: tri("Some после aren't здесь не работает. Нормально: aren't any chairs.", "Some пiсля aren't тут не працює. Нормально: aren't any chairs.", "After aren't, use any chairs.", {
          'pt-BR': "Some depois de aren't não funciona aqui. Natural: aren't any chairs.",
          vi: "Some sau aren't không đúng ở đây. Tự nhiên: aren't any chairs.",
          id: "Some setelah aren't tidak cocok di sini. Alami: aren't any chairs.",
          tr: "Some, aren't sonrasında burada çalışmaz. Doğal olan: aren't any chairs.",
          pl: "Some po aren't tutaj nie działa. Naturalnie: aren't any chairs.",
        }),
      },
      clue: tri("Aren't + any.", "Aren't + any.", "Aren't + any.", {
        'pt-BR': "Aren't + any.",
        vi: "Aren't + any.",
        id: "Aren't + any.",
        tr: "Aren't + any.",
        pl: "Aren't + any.",
      }),
      finalHint: tri("Фраза: There aren't any chairs in the room.", "Фраза: There aren't any chairs in the room.", "Sentence: There aren't any chairs in the room.", {
        'pt-BR': "Frase: There aren't any chairs in the room.",
        vi: "Câu: There aren't any chairs in the room.",
        id: "Kalimat: There aren't any chairs in the room.",
        tr: "Cümle: There aren't any chairs in the room.",
        pl: "Zdanie: There aren't any chairs in the room.",
      }),
      focusWords: ['any chairs'],
    }),
    makeStep({
      id: 'some_any_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'no_vs_not_any',
      sentence: 'I have ___ idea.',
      translation: tri('У меня нет идеи.', 'У мене немає iдеї.', 'I have no idea.', {
        'pt-BR': 'Não tenho ideia.',
        vi: 'Tôi không có ý tưởng nào.',
        id: 'Saya tidak punya ide.',
        tr: 'Hiç fikrim yok.',
        pl: 'Nie mam pojęcia.',
      }),
      options: ['some', 'any', 'no', 'none'],
      correctAnswer: 'no',
      correctFeedback: tri("Да. Без don't можно сказать no idea.", "Так. Без don't можна сказати no idea.", "Yes. Without don't, use no idea.", {
        'pt-BR': "Sim. Sem don't, podemos dizer no idea.",
        vi: "Đúng. Không có don't, có thể nói no idea.",
        id: "Ya. Tanpa don't, bisa mengatakan no idea.",
        tr: "Evet. Don't olmadan no idea diyebiliriz.",
        pl: "Tak. Bez don't można powiedzieć no idea.",
      }),
      wrong: {
        any: tri("I have any idea не делает фразу отрицательной. Нормально: I have no idea или I don't have any idea.", "I have any idea не робить фразу заперечною. Нормально: I have no idea або I don't have any idea.", "Use I have no idea or I don't have any idea.", {
          'pt-BR': "I have any idea não torna a frase negativa. Natural: I have no idea ou I don't have any idea.",
          vi: "I have any idea không làm câu thành phủ định. Tự nhiên: I have no idea hoặc I don't have any idea.",
          id: "I have any idea tidak membuat frasa menjadi negatif. Alami: I have no idea atau I don't have any idea.",
          tr: "I have any idea cümleyi olumsuz yapmaz. Doğal olan: I have no idea veya I don't have any idea.",
          pl: "I have any idea nie tworzy przeczenia. Naturalnie: I have no idea albo I don't have any idea.",
        }),
      },
      clue: tri("Без don't отрицание можно дать через no.", "Без don't заперечення можна дати через no.", "Without don't, use no.", {
        'pt-BR': "Sem don't, a negativa pode vir com no.",
        vi: "Không có don't, có thể tạo phủ định bằng no.",
        id: "Tanpa don't, negatif bisa dibuat dengan no.",
        tr: "Don't olmadan olumsuzluk no ile verilebilir.",
        pl: "Bez don't przeczenie można zrobić przez no.",
      }),
      finalHint: tri('Фраза: I have no idea.', 'Фраза: I have no idea.', 'Sentence: I have no idea.', {
        'pt-BR': 'Frase: I have no idea.',
        vi: 'Câu: I have no idea.',
        id: 'Kalimat: I have no idea.',
        tr: 'Cümle: I have no idea.',
        pl: 'Zdanie: I have no idea.',
      }),
      focusWords: ['no idea'],
    }),
    makeStep({
      id: 'some_any_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'some_offer',
      sentence: 'Would you like ___ coffee?',
      translation: tri('Хочешь кофе?', 'Хочеш кави?', 'Would you like some coffee?', {
        'pt-BR': 'Você gostaria de um pouco de café?',
        vi: 'Bạn có muốn uống chút cà phê không?',
        id: 'Apakah kamu mau sedikit kopi?',
        tr: 'Biraz kahve ister misin?',
        pl: 'Czy chcesz trochę kawy?',
      }),
      options: ['some', 'any', 'no', 'anything'],
      correctAnswer: 'some',
      correctFeedback: tri('Да. Это предложение кофе, поэтому some.', 'Так. Це пропозицiя кави, тому some.', 'Yes. It is an offer: some.', {
        'pt-BR': 'Sim. É uma oferta de café, por isso some.',
        vi: 'Đúng. Đây là lời mời cà phê, nên dùng some.',
        id: 'Ya. Ini tawaran kopi, jadi some.',
        tr: 'Evet. Bu kahve teklifi, bu yüzden some.',
        pl: 'Tak. To propozycja kawy, więc some.',
      }),
      wrong: {
        any: tri('Any нормально в нейтральном вопросе, но Would you like coffee? - это предложение. Здесь нужен some.', 'Any нормальне у нейтральному питаннi, але Would you like coffee? - це пропозицiя. Тут потрiбен some.', 'This is an offer, so use some.', {
          'pt-BR': 'Any é normal em pergunta neutra, mas Would you like coffee? é uma oferta. Aqui precisamos de some.',
          vi: 'Any hợp với câu hỏi trung tính, nhưng Would you like coffee? là lời mời. Ở đây cần some.',
          id: 'Any normal dalam pertanyaan netral, tetapi Would you like coffee? adalah tawaran. Di sini perlu some.',
          tr: 'Any nötr soruda normaldir, ama Would you like coffee? bir tekliftir. Burada some gerekir.',
          pl: 'Any jest normalne w neutralnym pytaniu, ale Would you like coffee? to propozycja. Tutaj potrzebne jest some.',
        }),
      },
      clue: tri('Предлагаем кофе: Would you like some coffee?', 'Пропонуємо каву: Would you like some coffee?', 'Offer: some coffee.', {
        'pt-BR': 'Oferecemos café: Would you like some coffee?',
        vi: 'Mời cà phê: Would you like some coffee?',
        id: 'Menawarkan kopi: Would you like some coffee?',
        tr: 'Kahve teklif ediyoruz: Would you like some coffee?',
        pl: 'Proponujemy kawę: Would you like some coffee?',
      }),
      finalHint: tri('Фраза: Would you like some coffee?', 'Фраза: Would you like some coffee?', 'Sentence: Would you like some coffee?', {
        'pt-BR': 'Frase: Would you like some coffee?',
        vi: 'Câu: Would you like some coffee?',
        id: 'Kalimat: Would you like some coffee?',
        tr: 'Cümle: Would you like some coffee?',
        pl: 'Zdanie: Would you like some coffee?',
      }),
      focusWords: ['some coffee'],
    }),
    makeStep({
      id: 'some_any_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'some_request',
      sentence: 'Can I have ___ water?',
      translation: tri('Можно мне воды?', 'Можна менi води?', 'Can I have some water?', {
        'pt-BR': 'Posso tomar um pouco de água?',
        vi: 'Cho tôi xin chút nước được không?',
        id: 'Boleh saya minta sedikit air?',
        tr: 'Biraz su alabilir miyim?',
        pl: 'Czy mogę prosić trochę wody?',
      }),
      options: ['some', 'any', 'no', 'anything'],
      correctAnswer: 'some',
      correctFeedback: tri('Да. Это обычная просьба: some water.', 'Так. Це звичайне прохання: some water.', 'Yes. Normal request: some water.', {
        'pt-BR': 'Sim. É um pedido comum: some water.',
        vi: 'Đúng. Đây là yêu cầu bình thường: some water.',
        id: 'Ya. Ini permintaan biasa: some water.',
        tr: 'Evet. Bu normal bir rica: some water.',
        pl: 'Tak. To zwykła prośba: some water.',
      }),
      wrong: {
        any: tri('Can I have any water? возможно в особом смысле, но обычная просьба звучит как Can I have some water?', 'Can I have any water? можливе в особливому сенсi, але звичайне прохання звучить як Can I have some water?', 'For a normal request, use some water.', {
          'pt-BR': 'Can I have any water? é possível em sentido especial, mas o pedido comum soa como Can I have some water?',
          vi: 'Can I have any water? có thể dùng trong nghĩa đặc biệt, nhưng yêu cầu bình thường là Can I have some water?',
          id: 'Can I have any water? mungkin dalam makna khusus, tetapi permintaan biasa berbunyi Can I have some water?',
          tr: 'Can I have any water? özel bir anlamda mümkün, ama normal rica Can I have some water? diye duyulur.',
          pl: 'Can I have any water? jest możliwe w szczególnym sensie, ale zwykła prośba brzmi Can I have some water?',
        }),
      },
      clue: tri('Просишь воду: some water.', 'Просиш води: some water.', 'Request: some water.', {
        'pt-BR': 'Você pede água: some water.',
        vi: 'Bạn xin nước: some water.',
        id: 'Meminta air: some water.',
        tr: 'Su istiyorsun: some water.',
        pl: 'Prosisz o wodę: some water.',
      }),
      finalHint: tri('Фраза: Can I have some water?', 'Фраза: Can I have some water?', 'Sentence: Can I have some water?', {
        'pt-BR': 'Frase: Can I have some water?',
        vi: 'Câu: Can I have some water?',
        id: 'Kalimat: Can I have some water?',
        tr: 'Cümle: Can I have some water?',
        pl: 'Zdanie: Can I have some water?',
      }),
      focusWords: ['some water'],
    }),
    makeStep({
      id: 'some_any_contrast_006',
      order: 9,
      difficulty: 'contrast',
      targetSkill: 'some_offer_plural',
      sentence: 'Would you like ___ cookies?',
      translation: tri('Хочешь печенья?', 'Хочеш печива?', 'Would you like some cookies?', {
        'pt-BR': 'Você gostaria de alguns biscoitos?',
        vi: 'Bạn có muốn ăn vài cái bánh quy không?',
        id: 'Apakah kamu mau beberapa kue?',
        tr: 'Biraz kurabiye ister misin?',
        pl: 'Czy chcesz trochę ciastek?',
      }),
      options: ['some', 'any', 'no', 'anybody'],
      correctAnswer: 'some',
      correctFeedback: tri('Да. Предлагаем еду: some cookies.', 'Так. Пропонуємо їжу: some cookies.', 'Yes. Offer food: some cookies.', {
        'pt-BR': 'Sim. Oferecemos comida: some cookies.',
        vi: 'Đúng. Mời đồ ăn: some cookies.',
        id: 'Ya. Menawarkan makanan: some cookies.',
        tr: 'Evet. Yiyecek teklif ediyoruz: some cookies.',
        pl: 'Tak. Proponujemy jedzenie: some cookies.',
      }),
      wrong: {
        any: tri('Any cookies звучит как нейтральная проверка. Здесь ты предлагаешь еду, нужен some.', 'Any cookies звучить як нейтральна перевiрка. Тут ти пропонуєш їжу, потрiбен some.', 'This is an offer, so use some.', {
          'pt-BR': 'Any cookies soa como verificação neutra. Aqui você oferece comida, então precisamos de some.',
          vi: 'Any cookies nghe như kiểm tra trung tính. Ở đây bạn đang mời đồ ăn, nên cần some.',
          id: 'Any cookies terdengar seperti pemeriksaan netral. Di sini kamu menawarkan makanan, jadi perlu some.',
          tr: 'Any cookies nötr kontrol gibi duyulur. Burada yiyecek teklif ediyorsun, some gerekir.',
          pl: 'Any cookies brzmi jak neutralne sprawdzenie. Tutaj proponujesz jedzenie, więc potrzebne jest some.',
        }),
      },
      clue: tri('Предлагаешь печенье: some cookies.', 'Пропонуєш печиво: some cookies.', 'Offer: some cookies.', {
        'pt-BR': 'Você oferece biscoitos: some cookies.',
        vi: 'Bạn mời bánh quy: some cookies.',
        id: 'Menawarkan kue: some cookies.',
        tr: 'Kurabiye teklif ediyorsun: some cookies.',
        pl: 'Proponujesz ciastka: some cookies.',
      }),
      finalHint: tri('Фраза: Would you like some cookies?', 'Фраза: Would you like some cookies?', 'Sentence: Would you like some cookies?', {
        'pt-BR': 'Frase: Would you like some cookies?',
        vi: 'Câu: Would you like some cookies?',
        id: 'Kalimat: Would you like some cookies?',
        tr: 'Cümle: Would you like some cookies?',
        pl: 'Zdanie: Would you like some cookies?',
      }),
      focusWords: ['some cookies'],
    }),
    makeStep({
      id: 'some_any_mixed_001',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'any_free_choice',
      sentence: 'You can choose ___ lesson.',
      translation: tri('Ты можешь выбрать любой урок.', 'Ти можеш обрати будь-який урок.', 'You can choose any lesson.', {
        'pt-BR': 'Você pode escolher qualquer lição.',
        vi: 'Bạn có thể chọn bất kỳ bài học nào.',
        id: 'Kamu bisa memilih pelajaran apa saja.',
        tr: 'Herhangi bir dersi seçebilirsin.',
        pl: 'Możesz wybrać dowolną lekcję.',
      }),
      options: ['some', 'any', 'no', 'nothing'],
      correctAnswer: 'any',
      correctFeedback: tri('Да. Любой без ограничения = any lesson.', 'Так. Будь-який без обмеження = any lesson.', 'Yes. Free choice: any lesson.', {
        'pt-BR': 'Sim. Qualquer sem limite = any lesson.',
        vi: 'Đúng. Bất kỳ không giới hạn = any lesson.',
        id: 'Ya. Apa saja tanpa batas = any lesson.',
        tr: 'Evet. Sınırsız herhangi bir = any lesson.',
        pl: 'Tak. Dowolny bez ograniczeń = any lesson.',
      }),
      wrong: {
        some: tri('Some lesson значит "какой-то урок", но для смысла "любой" нужен any.', 'Some lesson означає "якийсь урок", але для сенсу "будь-який" потрiбен any.', 'For free choice, use any.', {
          'pt-BR': 'Some lesson significa "alguma lição", mas para o sentido de "qualquer" precisamos de any.',
          vi: 'Some lesson nghĩa là "một bài học nào đó", nhưng với nghĩa "bất kỳ" cần any.',
          id: 'Some lesson berarti "suatu pelajaran", tetapi untuk makna "apa saja" perlu any.',
          tr: 'Some lesson "bir ders" demektir, ama "herhangi bir" anlamı için any gerekir.',
          pl: 'Some lesson znaczy "jakaś lekcja", ale dla sensu "dowolny" potrzebne jest any.',
        }),
      },
      clue: tri('Любой урок = any lesson.', 'Будь-який урок = any lesson.', 'Any lesson.', {
        'pt-BR': 'Qualquer lição = any lesson.',
        vi: 'Bất kỳ bài học nào = any lesson.',
        id: 'Pelajaran apa saja = any lesson.',
        tr: 'Herhangi bir ders = any lesson.',
        pl: 'Dowolna lekcja = any lesson.',
      }),
      finalHint: tri('Фраза: You can choose any lesson.', 'Фраза: You can choose any lesson.', 'Sentence: You can choose any lesson.', {
        'pt-BR': 'Frase: You can choose any lesson.',
        vi: 'Câu: You can choose any lesson.',
        id: 'Kalimat: You can choose any lesson.',
        tr: 'Cümle: You can choose any lesson.',
        pl: 'Zdanie: You can choose any lesson.',
      }),
      focusWords: ['any lesson'],
    }),
    makeStep({
      id: 'some_any_mixed_002',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'something_positive',
      sentence: 'I need ___ to drink.',
      translation: tri('Мне нужно что-нибудь выпить.', 'Менi потрiбно щось випити.', 'I need something to drink.', {
        'pt-BR': 'Preciso de algo para beber.',
        vi: 'Tôi cần thứ gì đó để uống.',
        id: 'Saya butuh sesuatu untuk diminum.',
        tr: 'İçecek bir şeye ihtiyacım var.',
        pl: 'Potrzebuję czegoś do picia.',
      }),
      options: ['something', 'anything', 'nothing', 'any'],
      correctAnswer: 'something',
      correctFeedback: tri('Да. В положительной фразе естественно something.', 'Так. У позитивнiй фразi природно something.', 'Yes. Positive need: something.', {
        'pt-BR': 'Sim. Em frase positiva, something é natural.',
        vi: 'Đúng. Trong câu khẳng định, something tự nhiên.',
        id: 'Ya. Dalam kalimat positif, something terdengar alami.',
        tr: 'Evet. Olumlu cümlede something doğaldır.',
        pl: 'Tak. W zdaniu twierdzącym naturalne jest something.',
      }),
      wrong: {
        anything: tri('Anything здесь звучит как "что угодно", но обычная просьба - I need something to drink.', 'Anything тут звучить як "що завгодно", але звичайне прохання - I need something to drink.', 'For a normal positive need, use something.', {
          'pt-BR': 'Anything aqui soa como "qualquer coisa", mas a necessidade comum é I need something to drink.',
          vi: 'Anything ở đây nghe như "bất cứ thứ gì", nhưng nhu cầu bình thường là I need something to drink.',
          id: 'Anything di sini terdengar seperti "apa saja", tetapi kebutuhan biasa adalah I need something to drink.',
          tr: 'Anything burada "ne olursa" gibi duyulur, ama normal ihtiyaç I need something to drink.',
          pl: 'Anything tutaj brzmi jak "cokolwiek", ale zwykła potrzeba to I need something to drink.',
        }),
      },
      clue: tri('Нужно что-то выпить = something to drink.', 'Потрiбно щось випити = something to drink.', 'Something to drink.', {
        'pt-BR': 'Precisa de algo para beber = something to drink.',
        vi: 'Cần thứ gì đó để uống = something to drink.',
        id: 'Butuh sesuatu untuk diminum = something to drink.',
        tr: 'İçecek bir şey lazım = something to drink.',
        pl: 'Potrzeba czegoś do picia = something to drink.',
      }),
      finalHint: tri('Фраза: I need something to drink.', 'Фраза: I need something to drink.', 'Sentence: I need something to drink.', {
        'pt-BR': 'Frase: I need something to drink.',
        vi: 'Câu: I need something to drink.',
        id: 'Kalimat: I need something to drink.',
        tr: 'Cümle: I need something to drink.',
        pl: 'Zdanie: I need something to drink.',
      }),
      focusWords: ['something'],
    }),
    makeStep({
      id: 'some_any_mixed_003',
      order: 12,
      difficulty: 'mixed',
      targetSkill: 'anything_negative',
      sentence: "I don't need ___.",
      translation: tri('Мне ничего не нужно.', 'Менi нiчого не потрiбно.', "I don't need anything.", {
        'pt-BR': 'Não preciso de nada.',
        vi: 'Tôi không cần gì cả.',
        id: 'Saya tidak membutuhkan apa pun.',
        tr: 'Hiçbir şeye ihtiyacım yok.',
        pl: 'Nie potrzebuję niczego.',
      }),
      options: ['something', 'anything', 'nothing', 'some'],
      correctAnswer: 'anything',
      correctFeedback: tri("Да. После don't нужно anything.", "Так. Пiсля don't потрiбно anything.", "Yes. After don't: anything.", {
        'pt-BR': "Sim. Depois de don't precisamos de anything.",
        vi: "Đúng. Sau don't cần anything.",
        id: "Ya. Setelah don't perlu anything.",
        tr: "Evet. Don't sonrasında anything gerekir.",
        pl: "Tak. Po don't potrzebne jest anything.",
      }),
      wrong: {
        nothing: tri("Don't need nothing дает лишнее отрицание. Нормально: don't need anything.", "Don't need nothing дає зайве заперечення. Нормально: don't need anything.", "Use don't need anything.", {
          'pt-BR': "Don't need nothing cria uma negativa extra. Natural: don't need anything.",
          vi: "Don't need nothing tạo phủ định thừa. Tự nhiên: don't need anything.",
          id: "Don't need nothing memberi negatif berlebih. Alami: don't need anything.",
          tr: "Don't need nothing fazla olumsuzluk verir. Doğal olan: don't need anything.",
          pl: "Don't need nothing daje dodatkowe przeczenie. Naturalnie: don't need anything.",
        }),
        something: tri("Something после don't здесь не работает. Нормально: don't need anything.", "Something пiсля don't тут не працює. Нормально: don't need anything.", "Use don't need anything.", {
          'pt-BR': "Something depois de don't não funciona aqui. Natural: don't need anything.",
          vi: "Something sau don't không đúng ở đây. Tự nhiên: don't need anything.",
          id: "Something setelah don't tidak cocok di sini. Alami: don't need anything.",
          tr: "Something, don't sonrasında burada çalışmaz. Doğal olan: don't need anything.",
          pl: "Something po don't tutaj nie działa. Naturalnie: don't need anything.",
        }),
      },
      clue: tri("Есть don't, значит anything.", "Є don't, отже anything.", "Don't -> anything.", {
        'pt-BR': "Há don't, então anything.",
        vi: "Có don't, nên dùng anything.",
        id: "Ada don't, jadi anything.",
        tr: "Don't var, bu yüzden anything.",
        pl: "Jest don't, więc anything.",
      }),
      finalHint: tri("Фраза: I don't need anything.", "Фраза: I don't need anything.", "Sentence: I don't need anything.", {
        'pt-BR': "Frase: I don't need anything.",
        vi: "Câu: I don't need anything.",
        id: "Kalimat: I don't need anything.",
        tr: "Cümle: I don't need anything.",
        pl: "Zdanie: I don't need anything.",
      }),
      focusWords: ['anything'],
    }),
    makeStep({
      id: 'some_any_mixed_004',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_some_any_pair',
      sentence: 'Choose the correct pair.',
      translation: tri('Выбери правильную пару.', 'Обери правильну пару.', 'Choose the correct pair.', {
        'pt-BR': 'Escolha o par correto.',
        vi: 'Chọn cặp đúng.',
        id: 'Pilih pasangan yang benar.',
        tr: 'Doğru çifti seç.',
        pl: 'Wybierz poprawną parę.',
      }),
      options: [
        "I have some time / I don't have any time",
        "I have any time / I don't have some time",
        "I have no time / I don't have no time",
        "I have any time / I don't have no time",
      ],
      correctAnswer: "I have some time / I don't have any time",
      correctFeedback: tri("Да. Есть время = some time. Нет времени после don't = any time.", "Так. Є час = some time. Немає часу пiсля don't = any time.", "Yes. Positive: some time. Negative: any time.", {
        'pt-BR': "Sim. Há tempo = some time. Não há tempo depois de don't = any time.",
        vi: "Đúng. Có thời gian = some time. Không có thời gian sau don't = any time.",
        id: "Ya. Ada waktu = some time. Tidak ada waktu setelah don't = any time.",
        tr: "Evet. Zaman var = some time. Don't sonrasında zaman yok = any time.",
        pl: "Tak. Czas jest = some time. Brak czasu po don't = any time.",
      }),
      clue: tri("Есть = some. Нет после don't = any.", "Є = some. Немає пiсля don't = any.", "Positive some, negative any.", {
        'pt-BR': "Há = some. Não há depois de don't = any.",
        vi: "Có = some. Không có sau don't = any.",
        id: "Ada = some. Tidak ada setelah don't = any.",
        tr: "Var = some. Don't sonrasında yok = any.",
        pl: "Jest = some. Nie ma po don't = any.",
      }),
      finalHint: tri("Ответ: I have some time / I don't have any time.", "Вiдповiдь: I have some time / I don't have any time.", "Answer: I have some time / I don't have any time.", {
        'pt-BR': "Resposta: I have some time / I don't have any time.",
        vi: "Đáp án: I have some time / I don't have any time.",
        id: "Jawaban: I have some time / I don't have any time.",
        tr: "Cevap: I have some time / I don't have any time.",
        pl: "Odpowiedź: I have some time / I don't have any time.",
      }),
      focusWords: ['some time', 'any time'],
    }),
    makeStep({
      id: 'some_any_mixed_005',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_question_offer',
      sentence: 'Choose the correct pair.',
      translation: tri('Выбери правильную пару.', 'Обери правильну пару.', 'Choose the correct pair.', {
        'pt-BR': 'Escolha o par correto.',
        vi: 'Chọn cặp đúng.',
        id: 'Pilih pasangan yang benar.',
        tr: 'Doğru çifti seç.',
        pl: 'Wybierz poprawną parę.',
      }),
      options: [
        'Do you have any questions? / Would you like some tea?',
        'Do you have some questions? / Would you like any tea?',
        'Do you have no questions? / Would you like no tea?',
        'Do you have anything questions? / Would you like something tea?',
      ],
      correctAnswer: 'Do you have any questions? / Would you like some tea?',
      correctFeedback: tri('Да. Нейтральный вопрос = any questions. Предложение = some tea.', 'Так. Нейтральне питання = any questions. Пропозицiя = some tea.', 'Yes. Neutral question: any. Offer: some.', {
        'pt-BR': 'Sim. Pergunta neutra = any questions. Oferta = some tea.',
        vi: 'Đúng. Câu hỏi trung tính = any questions. Lời mời = some tea.',
        id: 'Ya. Pertanyaan netral = any questions. Tawaran = some tea.',
        tr: 'Evet. Nötr soru = any questions. Teklif = some tea.',
        pl: 'Tak. Neutralne pytanie = any questions. Propozycja = some tea.',
      }),
      clue: tri('Вопрос про наличие: any. Предлагаем чай: some.', 'Питання про наявнiсть: any. Пропонуємо чай: some.', 'Question: any. Offer: some.', {
        'pt-BR': 'Pergunta sobre existência: any. Oferecemos chá: some.',
        vi: 'Hỏi về sự tồn tại: any. Mời trà: some.',
        id: 'Pertanyaan tentang keberadaan: any. Menawarkan teh: some.',
        tr: 'Varlık sorusu: any. Çay teklif ediyoruz: some.',
        pl: 'Pytanie o istnienie: any. Proponujemy herbatę: some.',
      }),
      finalHint: tri('Ответ: Do you have any questions? / Would you like some tea?', 'Вiдповiдь: Do you have any questions? / Would you like some tea?', 'Answer: Do you have any questions? / Would you like some tea?', {
        'pt-BR': 'Resposta: Do you have any questions? / Would you like some tea?',
        vi: 'Đáp án: Do you have any questions? / Would you like some tea?',
        id: 'Jawaban: Do you have any questions? / Would you like some tea?',
        tr: 'Cevap: Do you have any questions? / Would you like some tea?',
        pl: 'Odpowiedź: Do you have any questions? / Would you like some tea?',
      }),
      focusWords: ['any questions', 'some tea'],
    }),
    makeStep({
      id: 'some_any_mixed_006',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_sentence_correction',
      sentence: 'Choose the correct sentence.',
      translation: tri('Выбери естественное предложение.', 'Обери природне речення.', 'Choose the natural sentence.', {
        'pt-BR': 'Escolha a frase natural.',
        vi: 'Chọn câu tự nhiên.',
        id: 'Pilih kalimat yang alami.',
        tr: 'Doğal cümleyi seç.',
        pl: 'Wybierz naturalne zdanie.',
      }),
      options: [
        "I need something to drink, but I don't want any coffee.",
        "I need anything to drink, but I don't want some coffee.",
        "I need nothing to drink, but I don't want no coffee.",
        "I need any to drink, but I don't want something coffee.",
      ],
      correctAnswer: "I need something to drink, but I don't want any coffee.",
      correctFeedback: tri("Да. Положительная потребность = something. После don't want = any coffee.", "Так. Позитивна потреба = something. Пiсля don't want = any coffee.", "Yes. Positive need: something. After don't want: any coffee.", {
        'pt-BR': "Sim. Necessidade positiva = something. Depois de don't want = any coffee.",
        vi: "Đúng. Nhu cầu khẳng định = something. Sau don't want = any coffee.",
        id: "Ya. Kebutuhan positif = something. Setelah don't want = any coffee.",
        tr: "Evet. Pozitif ihtiyaç = something. Don't want sonrasında = any coffee.",
        pl: "Tak. Pozytywna potrzeba = something. Po don't want = any coffee.",
      }),
      clue: tri("Нужно что-то выпить, но кофе не хочу.", "Потрiбно щось випити, але кави не хочу.", "Need something, don't want any coffee.", {
        'pt-BR': 'Precisa de algo para beber, mas não quer café.',
        vi: 'Cần thứ gì đó để uống, nhưng không muốn cà phê.',
        id: 'Butuh sesuatu untuk diminum, tetapi tidak mau kopi.',
        tr: 'İçecek bir şey lazım, ama kahve istemiyor.',
        pl: 'Potrzeba czegoś do picia, ale kawy nie chcę.',
      }),
      finalHint: tri("Фраза: I need something to drink, but I don't want any coffee.", "Фраза: I need something to drink, but I don't want any coffee.", "Sentence: I need something to drink, but I don't want any coffee.", {
        'pt-BR': "Frase: I need something to drink, but I don't want any coffee.",
        vi: "Câu: I need something to drink, but I don't want any coffee.",
        id: "Kalimat: I need something to drink, but I don't want any coffee.",
        tr: "Cümle: I need something to drink, but I don't want any coffee.",
        pl: "Zdanie: I need something to drink, but I don't want any coffee.",
      }),
      focusWords: ['something', 'any coffee'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'some_in_negative_error',
      'any_in_positive_error',
      'any_offer_error',
      'some_neutral_question_error',
      'no_not_any_confusion',
      'double_negative_any_error',
      'any_free_choice_error',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri(
      'Показываем тип ситуации.',
      'Показуємо тип ситуацiї.',
      'Show the situation type.',
      {
        'pt-BR': 'Mostramos o tipo de situação.',
        vi: 'Hiển thị loại tình huống.',
        id: 'Tampilkan jenis situasinya.',
        tr: 'Durum türünü gösteriyoruz.',
        pl: 'Pokazujemy typ sytuacji.',
      },
    ),
    depth2: tri(
      'Проще: что-то есть, спрашиваем, отрицаем, предлагаем или говорим "любой"?',
      'Простiше: щось є, питаємо, заперечуємо, пропонуємо чи кажемо "будь-який"?',
      'Simpler: positive amount, question, negative, offer, or free choice?',
      {
        'pt-BR': 'Mais simples: algo existe, perguntamos, negamos, oferecemos ou dizemos "qualquer"?',
        vi: 'Đơn giản hơn: có gì đó, đang hỏi, phủ định, mời hay nói "bất kỳ"?',
        id: 'Lebih sederhana: ada sesuatu, bertanya, menolak, menawarkan, atau berarti "apa saja"?',
        tr: 'Daha basit: bir şey var mı, soruyor muyuz, olumsuz mu, teklif mi, yoksa "herhangi bir" mi?',
        pl: 'Prościej: coś jest, pytamy, przeczymy, proponujemy czy mówimy "dowolny"?',
      },
    ),
    depth3: tri(
      'Готовая логика: в утверждении что-то есть, в отрицании чего-то нет, в нейтральном вопросе проверяем наличие, в предложении звучим мягче.',
      'Готова логiка: у твердженнi щось є, у запереченнi чогось немає, у нейтральному питаннi перевiряємо наявнiсть, у пропозицiї звучимо мʼякше.',
      "Ready pairs: some time / any money / any questions / some coffee / any lesson.",
      {
        'pt-BR': 'Lógica pronta: na afirmação algo existe, na negativa algo não existe, na pergunta neutra verificamos existência, na oferta soamos mais gentis.',
        vi: 'Logic sẵn: trong câu khẳng định có gì đó, trong phủ định không có gì đó, trong câu hỏi trung tính kiểm tra tồn tại, trong lời mời thì mềm hơn.',
        id: 'Logika siap: dalam pernyataan ada sesuatu, dalam negatif sesuatu tidak ada, dalam pertanyaan netral memeriksa keberadaan, dalam tawaran terdengar lebih halus.',
        tr: 'Hazır mantık: olumlu cümlede bir şey vardır, olumsuzda bir şey yoktur, nötr soruda varlığı kontrol ederiz, teklifte daha nazik duyuluruz.',
        pl: 'Gotowa logika: w twierdzeniu coś jest, w przeczeniu czegoś nie ma, w neutralnym pytaniu sprawdzamy istnienie, w propozycji brzmi to łagodniej.',
      },
    ),
    depth4: tri(
      'Почти подсказка: прямо возвращаем к нужному блоку.',
      'Майже пiдказка: прямо повертаємо до потрiбного блоку.',
      'Near answer: return to the needed chunk.',
      {
        'pt-BR': 'Quase uma dica: voltamos direto ao bloco necessário.',
        vi: 'Gần như gợi ý: quay thẳng lại cụm cần dùng.',
        id: 'Hampir petunjuk: langsung kembali ke potongan yang diperlukan.',
        tr: 'Neredeyse ipucu: doğrudan gerekli parçaya dönüyoruz.',
        pl: 'Prawie podpowiedź: wracamy prosto do potrzebnego bloku.',
      },
    ),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri(
        "Some = что-то есть или мягко предлагаем/просим. Any = вопрос, отрицание или \"любой\". No = отрицание без don't/not.",
        "Some = щось є або мʼяко пропонуємо/просимо. Any = питання, заперечення або \"будь-який\". No = заперечення без don't/not.",
        "Some = positive amount or offer/request. Any = question, negative, or free choice. No = negative without don't/not.",
        {
          'pt-BR': 'Some = algo existe ou oferecemos/pedimos com delicadeza. Any = pergunta, negativa ou "qualquer". No = negativa sem don\'t/not.',
          vi: 'Some = có gì đó hoặc mời/yêu cầu nhẹ nhàng. Any = câu hỏi, phủ định hoặc "bất kỳ". No = phủ định không cần don\'t/not.',
          id: 'Some = ada sesuatu atau menawarkan/meminta dengan halus. Any = pertanyaan, negatif, atau "apa saja". No = negatif tanpa don\'t/not.',
          tr: 'Some = bir şey var veya nazikçe teklif/rica ediyoruz. Any = soru, olumsuz veya "herhangi bir". No = don\'t/not olmadan olumsuz.',
          pl: 'Some = coś jest albo łagodnie proponujemy/prosimy. Any = pytanie, przeczenie albo "dowolny". No = przeczenie bez don\'t/not.',
        },
      ),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_sentence_type_hint_then_retry',
      card: tri(
        'Система покажет тип ситуации, но не выберет some/any за пользователя.',
        'Система покаже тип ситуацiї, але не обере some/any за користувача.',
        'The system shows the situation type, but does not choose some/any for the user.',
        {
          'pt-BR': 'O sistema mostra o tipo de situação, mas não escolhe some/any pelo usuário.',
          vi: 'Hệ thống hiển thị loại tình huống, nhưng không chọn some/any thay cho người dùng.',
          id: 'Sistem menampilkan jenis situasi, tetapi tidak memilih some/any untuk pengguna.',
          tr: 'Sistem durum türünü gösterir, ama kullanıcı yerine some/any seçmez.',
          pl: 'System pokazuje typ sytuacji, ale nie wybiera some/any za użytkownika.',
        },
      ),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri(
        'Режим подсказки: сначала выбираем ситуацию, потом возвращаемся к полной фразе.',
        'Режим пiдказки: спочатку обираємо ситуацiю, потiм повертаємося до повної фрази.',
        'Guided mode: choose the situation first, then return to the sentence.',
        {
          'pt-BR': 'Modo guiado: primeiro escolhemos a situação, depois voltamos à frase completa.',
          vi: 'Chế độ gợi ý: trước hết chọn tình huống, rồi quay lại câu đầy đủ.',
          id: 'Mode panduan: pilih situasinya dulu, lalu kembali ke kalimat lengkap.',
          tr: 'Rehberli mod: önce durumu seç, sonra tam cümleye dön.',
          pl: 'Tryb podpowiedzi: najpierw wybieramy sytuację, potem wracamy do pełnego zdania.',
        },
      ),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      {
        id: 'guided_some_any_001',
        prompt: tri('I have ___ free time: время есть или его нет?', 'I have ___ free time: час є чи його немає?', 'I have ___ free time: positive or negative?', {
          'pt-BR': 'I have ___ free time: há tempo ou não há?',
          vi: 'I have ___ free time: có thời gian hay không có?',
          id: 'I have ___ free time: ada waktu atau tidak?',
          tr: 'I have ___ free time: zaman var mı yok mu?',
          pl: 'I have ___ free time: czas jest czy go nie ma?',
        }),
        options: ['есть', 'нет'],
        correctIndex: 0,
        thenReturnToExerciseId: 'some_any_easy_001',
      },
      {
        id: 'guided_some_any_002',
        prompt: tri("I don't have ___ money: есть don't?", "I don't have ___ money: є don't?", "I don't have ___ money: is there don't?", {
          'pt-BR': "I don't have ___ money: há don't?",
          vi: "I don't have ___ money: có don't không?",
          id: "I don't have ___ money: ada don't?",
          tr: "I don't have ___ money: don't var mı?",
          pl: "I don't have ___ money: jest don't?",
        }),
        options: ['да', 'нет'],
        correctIndex: 0,
        thenReturnToExerciseId: 'some_any_easy_003',
      },
      {
        id: 'guided_some_any_003',
        prompt: tri('Would you like ___ coffee: это нейтральный вопрос или предложение?', 'Would you like ___ coffee: це нейтральне питання чи пропозицiя?', 'Would you like ___ coffee: neutral question or offer?', {
          'pt-BR': 'Would you like ___ coffee: pergunta neutra ou oferta?',
          vi: 'Would you like ___ coffee: câu hỏi trung tính hay lời mời?',
          id: 'Would you like ___ coffee: pertanyaan netral atau tawaran?',
          tr: 'Would you like ___ coffee: nötr soru mu, teklif mi?',
          pl: 'Would you like ___ coffee: neutralne pytanie czy propozycja?',
        }),
        options: ['нейтральный вопрос', 'предложение'],
        correctIndex: 1,
        thenReturnToExerciseId: 'some_any_contrast_004',
      },
      {
        id: 'guided_some_any_004',
        prompt: tri('Choose ___ lesson: смысл "любой урок"?', 'Choose ___ lesson: сенс "будь-який урок"?', 'Choose ___ lesson: free choice?', {
          'pt-BR': 'Choose ___ lesson: sentido de "qualquer lição"?',
          vi: 'Choose ___ lesson: nghĩa là "bất kỳ bài học nào"?',
          id: 'Choose ___ lesson: maknanya "pelajaran apa saja"?',
          tr: 'Choose ___ lesson: "herhangi bir ders" anlamı mı?',
          pl: 'Choose ___ lesson: sens "dowolna lekcja"?',
        }),
        options: ['да', 'нет'],
        correctIndex: 0,
        thenReturnToExerciseId: 'some_any_mixed_001',
      },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'determiner',
    microDiagnosisId: 'quantifier_some_any',
    diagnosisLabel: tri('Some / Any', 'Some / Any', 'Some / Any', {
      'pt-BR': 'Some / Any',
      vi: 'Some / Any',
      id: 'Some / Any',
      tr: 'Some / Any',
      pl: 'Some / Any',
    }),
    contrastSet: SMART_CONTRAST,
    difficultyLevel: 2,
    focusWords: ['some time', 'any money', 'any questions', 'some coffee', 'any lesson', 'something', 'anything'],
    focusPatterns: [
      'some_positive_statement',
      'some_positive_plural',
      'any_negative',
      'any_neutral_question',
      'no_vs_not_any',
      'some_offer',
      'some_request',
      'any_free_choice',
      'something_positive',
      'anything_negative',
      'mixed_question_offer',
      'mixed_sentence_correction',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 3,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_quantifier_some_any_start',
    answer: 'diagnosis_training_quantifier_some_any_answer',
    mastery: 'diagnosis_training_quantifier_some_any_mastery',
    recovery: 'diagnosis_training_quantifier_some_any_recovery',
    smartTrainerUnlocked: 'diagnosis_training_quantifier_some_any_smart_trainer_unlocked',
    payload: {
      category: 'determiner',
      microDiagnosisId: 'quantifier_some_any',
      contrastSet: SMART_CONTRAST,
      priority: 18,
    },
  },
  routing: {
    appScreen: 'ProblemCoach',
    webPath: '/problem-coach/determiner/some-any',
    deepLink: 'phraseman://problem-coach/determiner/some-any',
    diagnosisTrainerRoute: '/problem_coach?category=determiner&microDiagnosisId=quantifier_some_any',
    smartTrainerRoute: '/smart_trainer?source=diagnosis_training&microDiagnosisId=quantifier_some_any',
  },
  qualityChecklist: {
    hasContrastiveMinimalPairs: true,
    hasDistractorSpecificFeedback: true,
    hasNegativeTransferWarning: true,
    hasMicroDiagnosis: true,
    hasAdaptiveFeedback: true,
    hasSmartTrainerUnlock: true,
  },
};
