// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

type PlannedTrainingLocale = 'pt-BR' | 'vi' | 'id' | 'tr' | 'pl';

const MAY_MIGHT_NEEDS_REVIEW_PLANNED: Record<PlannedTrainingLocale, string> = {
  'pt-BR': 'needs-review: esta explicação sobre may/might ainda precisa de revisão para português do Brasil.',
  vi: 'needs-review: phần giải thích về may/might này vẫn cần được rà soát cho tiếng Việt.',
  id: 'needs-review: penjelasan may/might ini masih perlu ditinjau untuk bahasa Indonesia.',
  tr: 'needs-review: bu may/might açıklaması Türkçe için hâlâ gözden geçirilmeli.',
  pl: 'needs-review: to objaśnienie may/might nadal wymaga przeglądu po polsku.',
};

const tri = (
  ru: string,
  uk = ru,
  es = ru,
  planned: Partial<Record<PlannedTrainingLocale, string>> = {},
): TriText => {
  const copy: TriText = { ru, uk, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    copy[locale] = planned[locale] ?? MAY_MIGHT_NEEDS_REVIEW_PLANNED[locale];
  }
  return copy;
};

const CONTRAST = [
  'may + base verb',
  'might + base verb',
  'possibility',
  'probability',
  'uncertainty',
  'may not',
  'might not',
  'can vs may',
  'will vs may',
];

const MODEL = tri(
  'May и might говорят не "я умею", а "возможно". It may rain - возможно, будет дождь. She might come - возможно, она придет. Will звучит увереннее. Can чаще про умение или общую возможность.',
  'May і might говорять не "я вмію", а "можливо". It may rain - можливо, буде дощ. She might come - можливо, вона прийде. Will звучить впевненіше. Can частіше про вміння або загальну можливість.',
  'May/might significan quiza o posiblemente. Will suena mas seguro. Can suele hablar de habilidad o posibilidad general.',
  {
    'pt-BR': 'May e might não significam "eu sei fazer", mas "talvez". It may rain: talvez chova. She might come: talvez ela venha. Will soa mais certo. Can costuma falar de habilidade ou possibilidade geral.',
    vi: 'May và might không nói "tôi biết làm", mà nói "có thể". It may rain: có thể trời mưa. She might come: có thể cô ấy sẽ đến. Will nghe chắc chắn hơn. Can thường nói về khả năng hoặc khả năng chung.',
    id: 'May dan might bukan berarti "saya bisa", melainkan "mungkin". It may rain: mungkin akan hujan. She might come: mungkin dia akan datang. Will terdengar lebih pasti. Can biasanya tentang kemampuan atau kemungkinan umum.',
    tr: 'May ve might "yapabiliyorum" değil, "belki" anlamı verir. It may rain: belki yağmur yağar. She might come: belki gelir. Will daha kesin duyulur. Can çoğu zaman beceri ya da genel olasılık anlatır.',
    pl: 'May i might nie mówią "umiem", tylko "możliwe". It may rain: być może będzie padać. She might come: być może przyjdzie. Will brzmi pewniej. Can częściej mówi o umiejętności albo ogólnej możliwości.',
  },
);

const MAY_MIGHT_SKILL_ES: Record<string, string> = {
  may_rain: 'May rain expresa probabilidad: puede llover.',
  may_be_busy: 'May be busy es una suposicion, no un hecho.',
  may_help: 'May help significa que quiza ayude.',
  might_less_certain: 'Might come suena cauteloso: quiza venga.',
  might_work: 'Might work significa que quiza funcione.',
  may_vs_will_certainty: 'Might es menos seguro que will.',
  may_base_no_to: 'Despues de may usa la forma corta: may know.',
  might_base_no_to: 'Despues de might usa be, sin to.',
  may_base_pair: 'Despues de may/might no agregues -s ni to.',
  may_not_probability: 'May not significa quiza no.',
  might_not_work: 'Might not work significa que quiza no funcione.',
  maybe_vs_might: 'Maybe es adverbio separado; might es modal.',
  mixed_can_may_will: 'Can = habilidad, may = probabilidad, will = certeza.',
  mixed_may_might_negative: 'May help y might not work son bloques naturales.',
  mixed_sentence_correction: 'May be y might not answer expresan probabilidad.',
};

function withEs(
  copy: TriText,
  es: string,
  planned: Partial<Record<PlannedTrainingLocale, string>> = MAY_MIGHT_NEEDS_REVIEW_PLANNED,
): TriText {
  const next: TriText = { ...copy, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    if (!next[locale] || next[locale]?.startsWith('needs-review:')) {
      next[locale] = planned[locale] ?? MAY_MIGHT_NEEDS_REVIEW_PLANNED[locale];
    }
  }
  return next;
}

function mayMightEsFeedback(input: {
  targetSkill: string;
  correctAnswer: string;
  focusWords: string[];
}): string {
  const focus = input.focusWords.join(' / ');
  const hint = MAY_MIGHT_SKILL_ES[input.targetSkill] ?? 'Decide si es probabilidad, certeza o habilidad.';
  return `Usa "${input.correctAnswer}"${focus ? ` con ${focus}` : ''}. ${hint}`;
}

function retryFor(correct: string, contrast: TriText, finalHint: TriText): [TriText, TriText, TriText, TriText] {
  return [
    tri(
      'Сначала выбери смысл: это точно, возможно, умение или "возможно нет"?',
      'Спочатку обери зміст: це точно, можливо, вміння чи "можливо ні"?',
      'Primero elige el sentido: seguro, posible, habilidad o quiza no.',
    ),
    contrast,
    tri(
      'Потом проверь английский кусок. Нормально: may rain, might come, may know, might not work.',
      'Потім перевір англійський зворот. Нормально: may rain, might come, may know, might not work.',
      'Luego revisa el bloque: may rain, might come, may know, might not work.',
    ),
    tri(
      `Ответ здесь: ${correct}. Проверь две вещи: это "возможно", а после may/might стоит короткое действие без to, -s и do/does.`,
      `Відповідь тут: ${correct}. Перевір дві речі: це "можливо", а після may/might стоїть коротка дія без to, -s і do/does.`,
      `La respuesta es ${correct}. ${finalHint.es}`,
    ),
  ];
}

function defaultWrong(correct: string): TriText {
  return tri(
    `Почти. Проверь, это вероятность, уверенность или умение. Здесь нужен вариант: ${correct}.`,
    `Майже. Перевір, це ймовірність, упевненість чи вміння. Тут потрібен варіант: ${correct}.`,
    `Casi. Revisa si es probabilidad, certeza o habilidad. Usa: ${correct}.`,
  );
}

function modalStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  sentence: string;
  translation: TriText;
  options: string[];
  correctAnswer: string;
  correctFeedback: TriText;
  wrong: Record<string, TriText>;
  contrast: TriText;
  finalHint: TriText;
  focusWords: string[];
}): DiagnosisTrainingStep {
  const esFeedback = mayMightEsFeedback(input);
  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    translation: withEs(input.translation, esFeedback),
    teachingText: MODEL,
    explanationBlock: MODEL,
    microTask: tri(
      'Выбери кусок для вероятности: may, might, may not или might not. Не путай с can и will.',
      'Обери зворот для ймовірності: may, might, may not або might not. Не плутай із can і will.',
      'Elige el bloque de probabilidad: may, might, may not o might not.',
    ),
    sentence: input.sentence,
    answerOptions: input.options.map((text) => ({ id: text, text })),
    correctAnswerId: input.correctAnswer,
    correctIndex: input.options.findIndex((option) => option === input.correctAnswer),
    correctFeedback: withEs(input.correctFeedback, esFeedback),
    wrongFeedbackByOption: Object.fromEntries(
      input.options
        .filter((option) => option !== input.correctAnswer)
        .map((option) => [option, withEs(input.wrong[option] ?? defaultWrong(input.correctAnswer), esFeedback)]),
    ),
    retryFeedback: retryFor(input.correctAnswer, withEs(input.contrast, esFeedback), withEs(input.finalHint, esFeedback)),
    fallbackExplanation: tri(
      "Коротко: may/might = возможно. will = увереннее. can = чаще умею/могу. Отрицание: may not / might not. После may/might не добавляй to, -s или do/does.",
      "Коротко: may/might = можливо. will = упевненіше. can = частіше вмію/можу. Заперечення: may not / might not. Після may/might не додавай to, -s або do/does.",
      "Corto: may/might = quiza. will = mas seguro. can = habilidad o posibilidad general.",
    ),
    focusWords: input.focusWords,
  };
}

export const MODAL_MAY_MIGHT_PROBABILITY_TRAINING: DiagnosisTraining = {
  id: 'modal_may_might_probability',
  category: 'modal',
  version: '1.0.0',
  status: 'active',
  priority: 48,
  supportedLocales: ['ru', 'uk', 'es'],
  title: tri(
    'May / Might: возможно, но не точно',
    'May / Might: можливо, але не точно',
    'May / Might',
    {
      'pt-BR': 'May / Might: talvez, mas não com certeza',
      vi: 'May / Might: có thể, nhưng không chắc chắn',
      id: 'May / Might: mungkin, tetapi tidak pasti',
      tr: 'May / Might: belki, ama kesin değil',
      pl: 'May / Might: możliwe, ale nie na pewno',
    },
  ),
  shortTitle: tri('may / might', 'may / might', 'may / might', {
    'pt-BR': 'may / might',
    vi: 'may / might',
    id: 'may / might',
    tr: 'may / might',
    pl: 'may / might',
  }),
  shortDiagnosis: tri(
    'Ты смешиваешь вероятность с умением, уверенным будущим и ошибками после may/might.',
    'Ти змішуєш ймовірність із умінням, упевненим майбутнім і помилками після may/might.',
    'Mezclas probabilidad con habilidad, certeza y la forma despues de may/might.',
    {
      'pt-BR': 'Você mistura probabilidade com habilidade, futuro certo e erros depois de may/might.',
      vi: 'Bạn trộn khả năng xảy ra với khả năng làm được, tương lai chắc chắn và lỗi sau may/might.',
      id: 'Kamu mencampur kemungkinan dengan kemampuan, masa depan yang pasti, dan kesalahan setelah may/might.',
      tr: 'Olasılığı beceriyle, kesin gelecekle ve may/might sonrası biçim hatalarıyla karıştırıyorsun.',
      pl: 'Mieszasz prawdopodobieństwo z umiejętnością, pewną przyszłością i błędami po may/might.',
    },
  ),
  diagnosisText: tri(
    'Ошибка часто появляется, когда хочется сказать "может быть", а рука тянется к can или will. It may rain - возможно, будет дождь. It can rain - звучит скорее как "такое вообще бывает". It will rain - звучит увереннее.',
    'Помилка часто зʼявляється, коли хочеться сказати "можливо", а рука тягнеться до can або will. It may rain - можливо, буде дощ. It can rain - звучить радше як "таке взагалі буває". It will rain - звучить упевненіше.',
    'El error aparece cuando "quiza" se mezcla con can o will. It may rain = puede que llueva. It will rain suena mas seguro.',
    {
      'pt-BR': 'O erro costuma aparecer quando você quer dizer "talvez" e a mão vai para can ou will. It may rain: talvez chova. It can rain soa mais como "isso pode acontecer em geral". It will rain soa mais certo.',
      vi: 'Lỗi thường xuất hiện khi bạn muốn nói "có thể", nhưng lại dùng can hoặc will. It may rain: có thể trời mưa. It can rain nghe giống "mưa là chuyện có thể xảy ra nói chung". It will rain nghe chắc chắn hơn.',
      id: 'Kesalahan sering muncul saat kamu ingin mengatakan "mungkin", tetapi tangan memilih can atau will. It may rain: mungkin akan hujan. It can rain lebih terdengar seperti "hujan memang bisa terjadi". It will rain terdengar lebih pasti.',
      tr: 'Hata çoğu zaman "belki" demek isterken elin can veya will seçmesine kaydığında çıkar. It may rain: belki yağmur yağar. It can rain daha çok "yağmur genel olarak yağabilir" gibi duyulur. It will rain daha kesin duyulur.',
      pl: 'Błąd często pojawia się, gdy chcesz powiedzieć "może", a ręka idzie do can albo will. It may rain: być może będzie padać. It can rain brzmi raczej jak "deszcz w ogóle może padać". It will rain brzmi pewniej.',
    },
  ),
  mentalModel: MODEL,
  contrastSet: CONTRAST,
  coreRule: tri(
    'May/might показывают вероятность: It may rain, She might come. После них действие остается коротким: may know, might be. Отрицание ставится сразу после may/might: may not, might not.',
    'May/might показують ймовірність: It may rain, She might come. Після них дія залишається короткою: may know, might be. Заперечення ставиться одразу після may/might: may not, might not.',
    'May/might muestran probabilidad. Usa may know, might be, may not, might not.',
    {
      'pt-BR': 'May/might mostram probabilidade: It may rain, She might come. Depois deles, a ação fica curta: may know, might be. A negação vem logo depois de may/might: may not, might not.',
      vi: 'May/might diễn tả khả năng xảy ra: It may rain, She might come. Sau chúng, động từ giữ dạng ngắn: may know, might be. Phủ định đứng ngay sau may/might: may not, might not.',
      id: 'May/might menunjukkan kemungkinan: It may rain, She might come. Setelah itu, kata kerja tetap pendek: may know, might be. Negasi langsung setelah may/might: may not, might not.',
      tr: 'May/might olasılık gösterir: It may rain, She might come. Sonrasında eylem kısa kalır: may know, might be. Olumsuzluk doğrudan may/might sonrasına gelir: may not, might not.',
      pl: 'May/might pokazują prawdopodobieństwo: It may rain, She might come. Po nich czynność zostaje krótka: may know, might be. Przeczenie stoi zaraz po may/might: may not, might not.',
    },
  ),
  whatUserMustLearn: {
    ru: [
      'May показывает вероятность: It may rain.',
      'Might тоже показывает вероятность, часто осторожнее: She might come.',
      'После may/might действие остается коротким: may go, might come, may be.',
      'Не говори may to go или might to come.',
      'С she/he/it после may/might не добавляй -s: she may know.',
      'С may/might не нужен do/does: It might not work.',
      'May not / might not значит возможно нет.',
      'Can чаще про умение или общую возможность, а may/might про вероятность в ситуации.',
      'Will звучит увереннее: She will come. Might звучит неуверенно: She might come.',
      'Maybe - отдельное слово: Maybe she will come. С модалом: She might come.',
    ],
    uk: [
      'May показує ймовірність: It may rain.',
      'Might теж показує ймовірність, часто обережніше: She might come.',
      'Після may/might дія залишається короткою: may go, might come, may be.',
      'Не кажи may to go або might to come.',
      'З she/he/it після may/might не додавай -s: she may know.',
      'З may/might не потрібен do/does: It might not work.',
      'May not / might not означає можливо ні.',
      'Can частіше про вміння або загальну можливість, а may/might про ймовірність у ситуації.',
      'Will звучить упевненіше: She will come. Might звучить невпевнено: She might come.',
      'Maybe - окреме слово: Maybe she will come. З модалом: She might come.',
    ],
    es: [
      'May muestra probabilidad: It may rain.',
      'Might tambien muestra probabilidad, a menudo con mas cautela.',
      'Despues de may/might, la accion queda en forma corta.',
      'No uses may to go.',
      'No agregues -s despues de may/might.',
      'No uses do/does con may/might.',
      'May not / might not significa quiza no.',
      'Can suele hablar de habilidad o posibilidad general.',
      'Will suena mas seguro.',
      'Maybe es un adverbio separado.',
    ],
    'pt-BR': [
      'May mostra probabilidade.',
      'Might também mostra probabilidade, muitas vezes com mais cautela.',
      'Depois de may/might, a ação fica na forma curta.',
      'Não use may to go.',
      'Não acrescente -s depois de may/might.',
      'Não use do/does com may/might.',
      'May not / might not significa talvez não.',
      'Can muitas vezes indica habilidade ou possibilidade geral.',
      'Will soa mais certo.',
      'Maybe é um advérbio separado.',
    ],
    vi: [
      'May diễn tả khả năng có thể xảy ra.',
      'Might cũng diễn tả khả năng, thường thận trọng hơn.',
      'Sau may/might, hành động giữ dạng ngắn.',
      'Đừng dùng may to go.',
      'Đừng thêm -s sau may/might.',
      'Đừng dùng do/does với may/might.',
      'May not / might not nghĩa là có thể không.',
      'Can thường nói về khả năng hoặc khả năng chung.',
      'Will chắc chắn hơn.',
      'Maybe là một trạng từ riêng.',
    ],
    id: [
      'May menunjukkan kemungkinan.',
      'Might juga menunjukkan kemungkinan, sering lebih hati-hati.',
      'Setelah may/might, tindakan tetap dalam bentuk pendek.',
      'Jangan gunakan may to go.',
      'Jangan tambahkan -s setelah may/might.',
      'Jangan gunakan do/does dengan may/might.',
      'May not / might not berarti mungkin tidak.',
      'Can sering berarti kemampuan atau kemungkinan umum.',
      'Will lebih pasti.',
      'Maybe adalah adverbia terpisah.',
    ],
    tr: [
      'May olasılık gösterir.',
      'Might da olasılık gösterir, çoğu zaman daha temkinlidir.',
      'May/might sonrasında eylem kısa halde kalır.',
      'May to go kullanma.',
      'May/might sonrasında -s ekleme.',
      'May/might ile do/does kullanma.',
      'May not / might not belki hayır demektir.',
      'Can çoğu zaman beceri veya genel olasılık anlatır.',
      'Will daha kesin duyulur.',
      'Maybe ayrı bir zarftır.',
    ],
    pl: [
      'May pokazuje prawdopodobieństwo.',
      'Might też pokazuje prawdopodobieństwo, często ostrożniej.',
      'Po may/might czynność zostaje w krótkiej formie.',
      'Nie używaj may to go.',
      'Nie dodawaj -s po may/might.',
      'Nie używaj do/does z may/might.',
      'May not / might not znaczy może nie.',
      'Can często oznacza umiejętność albo ogólną możliwość.',
      'Will brzmi pewniej.',
      'Maybe to osobny przysłówek.',
    ],
  },
  examples: [
    {
      en: 'It may rain tomorrow.',
      ru: 'Возможно, завтра будет дождь.',
      uk: 'Можливо, завтра буде дощ.',
      es: 'Puede que llueva manana.',
      'pt-BR': 'Pode chover amanhã.',
      vi: 'Có thể ngày mai trời mưa.',
      id: 'Besok mungkin hujan.',
      tr: 'Yarın yağmur yağabilir.',
      pl: 'Jutro może padać.',
      why: tri('May rain = возможно, будет дождь.', 'May rain = можливо, буде дощ.', 'Probabilidad: puede que llueva.'),
    },
    {
      en: 'It might rain tomorrow.',
      ru: 'Возможно, завтра будет дождь.',
      uk: 'Можливо, завтра буде дощ.',
      es: 'Quizas llueva manana.',
      'pt-BR': 'Talvez chova amanhã.',
      vi: 'Ngày mai có lẽ trời sẽ mưa.',
      id: 'Besok mungkin akan hujan.',
      tr: 'Belki yarın yağmur yağar.',
      pl: 'Może jutro będzie padać.',
      why: tri('Might часто звучит чуть осторожнее.', 'Might часто звучить трохи обережніше.', 'Probabilidad mas cautelosa.'),
    },
    {
      en: 'She may be at work.',
      ru: 'Возможно, она на работе.',
      uk: 'Можливо, вона на роботі.',
      es: 'Puede que ella este en el trabajo.',
      'pt-BR': 'Ela pode estar no trabalho.',
      vi: 'Có thể cô ấy đang ở chỗ làm.',
      id: 'Dia mungkin sedang di kantor.',
      tr: 'İşte olabilir.',
      pl: 'Ona może być w pracy.',
      why: tri('После may нужен be, не is.', 'Після may потрібен be, не is.', 'Despues de may usa be.'),
    },
    {
      en: 'He might come later.',
      ru: 'Возможно, он придет позже.',
      uk: 'Можливо, він прийде пізніше.',
      es: 'Puede que venga mas tarde.',
      'pt-BR': 'Ele talvez venha mais tarde.',
      vi: 'Có lẽ anh ấy sẽ đến muộn hơn.',
      id: 'Dia mungkin datang nanti.',
      tr: 'Daha sonra gelebilir.',
      pl: 'On może przyjść później.',
      why: tri('Might come = может быть придет.', 'Might come = може прийде.', 'Futuro incierto.'),
    },
    {
      en: 'This might help.',
      ru: 'Возможно, это поможет.',
      uk: 'Можливо, це допоможе.',
      es: 'Puede que esto ayude.',
      'pt-BR': 'Isto talvez ajude.',
      vi: 'Điều này có thể giúp.',
      id: 'Ini mungkin membantu.',
      tr: 'Bu yardımcı olabilir.',
      pl: 'To może pomóc.',
      why: tri('Might help - это шанс, не физическое умение.', 'Might help - це шанс, не фізичне вміння.', 'Quiza ayude, no habilidad fisica.'),
    },
    {
      en: 'He may not know the answer.',
      ru: 'Возможно, он не знает ответ.',
      uk: 'Можливо, він не знає відповідь.',
      es: 'Puede que el no sepa la respuesta.',
      'pt-BR': 'Ele talvez não saiba a resposta.',
      vi: 'Có thể anh ấy không biết câu trả lời.',
      id: 'Dia mungkin tidak tahu jawabannya.',
      tr: 'Cevabı bilmiyor olabilir.',
      pl: 'On może nie znać odpowiedzi.',
      why: tri('May not = возможно нет.', 'May not = можливо ні.', 'Quiza no.'),
    },
    {
      en: 'She will come.',
      ru: 'Она придет.',
      uk: 'Вона прийде.',
      es: 'Ella vendra.',
      'pt-BR': 'Ela virá.',
      vi: 'Cô ấy sẽ đến.',
      id: 'Dia akan datang.',
      tr: 'O gelecek.',
      pl: 'Ona przyjdzie.',
      why: tri('Will звучит увереннее, чем may/might.', 'Will звучить упевненіше, ніж may/might.', 'Mas seguro.'),
    },
    {
      en: 'She might come.',
      ru: 'Возможно, она придет.',
      uk: 'Можливо, вона прийде.',
      es: 'Puede que ella venga.',
      'pt-BR': 'Ela talvez venha.',
      vi: 'Có lẽ cô ấy sẽ đến.',
      id: 'Dia mungkin datang.',
      tr: 'O gelebilir.',
      pl: 'Ona może przyjść.',
      why: tri('Might оставляет сомнение.', 'Might залишає сумнів.', 'Incierto.'),
    },
  ],
  introBlocks: [
    {
      id: 'intro_problem',
      type: 'diagnosis',
      text: tri(
        'Похоже, ты используешь can там, где хочешь сказать "возможно". Can часто про умение. May/might - про вероятность.',
        'Схоже, ти використовуєш can там, де хочеш сказати "можливо". Can часто про вміння. May/might - про ймовірність.',
        'Parece que usas can cuando quieres decir quiza. Can suele ser habilidad; may/might son probabilidad.',
      ),
    },
    {
      id: 'intro_rule',
      type: 'rule',
      text: tri(
        'May/might ставим, когда говорим "возможно": may rain, might come, may be busy. Это не умение и не уверенное будущее.',
        'May/might ставимо, коли кажемо "можливо": may rain, might come, may be busy. Це не вміння і не впевнене майбутнє.',
        'Usa may/might cuando dices quiza: may rain, might come, may be busy.',
      ),
    },
    {
      id: 'intro_warning',
      type: 'warning',
      text: tri(
        "Главные поломки такие: добавили to, добавили -s или поставили doesn't. Нормально: may rain, she may know, it might not work.",
        "Головні поломки такі: додали to, додали -s або поставили doesn't. Нормально: may rain, she may know, it might not work.",
        "Errores tipicos: may to rain, she may knows, it doesn't might work. Correcto: may rain, she may know, it might not work.",
      ),
    },
  ],
  steps: [
    modalStep({
      id: 'modal_may_might_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'may_rain',
      sentence: 'It ___ rain tomorrow.',
      translation: tri('Возможно, завтра будет дождь.', 'Можливо, завтра буде дощ.', 'It may rain tomorrow.'),
      options: ['may', 'can', 'is', 'does'],
      correctAnswer: 'may',
      correctFeedback: tri('Да. May rain показывает вероятность: возможно, будет дождь.', 'Так. May rain показує ймовірність: можливо, буде дощ.', 'Yes. May rain shows probability.'),
      wrong: {
        can: tri('can rain звучит скорее как "дождь вообще может идти". Для прогноза "возможно" нужен кусок may rain.', 'can rain звучить радше як "дощ узагалі може йти". Для прогнозу "можливо" потрібен зворот may rain.', 'Use may rain.'),
        is: tri('is rain не собирается. Для вероятности нужен кусок may rain.', 'is rain не збирається. Для ймовірності потрібен зворот may rain.', 'Use may rain.'),
        does: tri('does rain здесь не подходит. Для "возможно" нужен may rain.', 'does rain тут не підходить. Для "можливо" потрібно may rain.', 'Use may rain.'),
      },
      contrast: tri('В прогнозе с "возможно" часто нужен may.', 'У прогнозі з "можливо" часто потрібен may.', 'Maybe it will = may.'),
      finalHint: tri('It may rain tomorrow.', 'It may rain tomorrow.', 'It may rain tomorrow.'),
      focusWords: ['may rain'],
    }),
    modalStep({
      id: 'modal_may_might_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'may_be_busy',
      sentence: 'She ___ be busy.',
      translation: tri('Возможно, она занята.', 'Можливо, вона зайнята.', 'She may be busy.'),
      options: ['may', 'can', 'does', 'is'],
      correctAnswer: 'may',
      correctFeedback: tri('Да. May be busy = возможно, она занята.', 'Так. May be busy = можливо, вона зайнята.', 'Yes. Maybe busy = may be busy.'),
      wrong: {
        can: tri('can be busy звучит как общая возможность. Здесь догадка сейчас: may be busy.', 'can be busy звучить як загальна можливість. Тут здогад зараз: may be busy.', 'Use may be busy.'),
        does: tri('does be busy не собирается. Нормально: may be busy.', 'does be busy не збирається. Нормально: may be busy.', 'Use may be busy.'),
        is: tri('She is busy звучит как факт. Для "возможно" нужен may.', 'She is busy звучить як факт. Для "можливо" потрібен may.', 'Use may be busy.'),
      },
      contrast: tri('Догадка, не факт: may be.', 'Здогад, не факт: may be.', 'Guess, not fact: may be.'),
      finalHint: tri('She may be busy.', 'She may be busy.', 'She may be busy.'),
      focusWords: ['may be'],
    }),
    modalStep({
      id: 'modal_may_might_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'may_help',
      sentence: 'This ___ help.',
      translation: tri('Возможно, это поможет.', 'Можливо, це допоможе.', 'This may help.'),
      options: ['may', 'is', 'does', 'has'],
      correctAnswer: 'may',
      correctFeedback: tri('Да. May help = возможно, поможет.', 'Так. May help = можливо, допоможе.', 'Yes. May help = maybe it will help.'),
      wrong: {
        is: tri('is help не собирается. Нормально: may help.', 'is help не збирається. Нормально: may help.', 'Use may help.'),
        does: tri('does help звучит как факт "это помогает". Для "возможно поможет" нужен may help.', 'does help звучить як факт "це допомагає". Для "можливо допоможе" потрібно may help.', 'Use may help.'),
        has: tri('has help не собирается. Нормально: may help.', 'has help не збирається. Нормально: may help.', 'Use may help.'),
      },
      contrast: tri('Возможно поможет = may help.', 'Можливо допоможе = may help.', 'Maybe it will help = may help.'),
      finalHint: tri('This may help.', 'This may help.', 'This may help.'),
      focusWords: ['may help'],
    }),
    modalStep({
      id: 'modal_may_might_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'might_less_certain',
      sentence: 'He ___ come later.',
      translation: tri('Возможно, он придет позже.', 'Можливо, він прийде пізніше.', 'He might come later.'),
      options: ['might', 'does', 'is', 'has'],
      correctAnswer: 'might',
      correctFeedback: tri('Да. Might come звучит осторожно: возможно, придет.', 'Так. Might come звучить обережно: можливо, прийде.', 'Yes. Might come shows cautious probability.'),
      wrong: {
        does: tri('does come не показывает "возможно". Нужен кусок might come.', 'does come не показує "можливо". Потрібен зворот might come.', 'Use might come.'),
        is: tri('is come не собирается. Нормально: might come.', 'is come не збирається. Нормально: might come.', 'Use might come.'),
        has: tri('has come значит "уже пришел". Здесь будущее возможно: might come.', 'has come означає "уже прийшов". Тут майбутнє можливе: might come.', 'Use might come.'),
      },
      contrast: tri('Осторожное "может быть" часто удобно через might.', 'Обережне "можливо" часто зручно через might.', 'Cautious maybe = might.'),
      finalHint: tri('He might come later.', 'He might come later.', 'He might come later.'),
      focusWords: ['might come'],
    }),
    modalStep({
      id: 'modal_may_might_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'might_work',
      sentence: 'It ___ work.',
      translation: tri('Возможно, это сработает.', 'Можливо, це спрацює.', 'It might work.'),
      options: ['might', 'is', 'does', 'can to'],
      correctAnswer: 'might',
      correctFeedback: tri('Да. Might work = возможно, сработает.', 'Так. Might work = можливо, спрацює.', 'Yes. Might work = maybe it will work.'),
      wrong: {
        is: tri('is work не собирается. Нормально: might work.', 'is work не збирається. Нормально: might work.', 'Use might work.'),
        does: tri('does work звучит как факт "это работает". Здесь вероятность: might work.', 'does work звучить як факт "це працює". Тут ймовірність: might work.', 'Use might work.'),
        'can to': tri('can to не работает. Для вероятности нужен might work.', 'can to не працює. Для ймовірності потрібен might work.', 'Use might work.'),
      },
      contrast: tri('Возможно сработает = might work.', 'Можливо спрацює = might work.', 'Maybe it will work = might work.'),
      finalHint: tri('It might work.', 'It might work.', 'It might work.'),
      focusWords: ['might work'],
    }),
    modalStep({
      id: 'modal_may_might_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'may_vs_will_certainty',
      sentence: 'Choose the less certain sentence.',
      translation: tri('Выбери менее уверенную фразу.', 'Обери менш упевнену фразу.', 'Choose the less certain sentence.'),
      options: ['She might come.', 'She will come.', 'She is here.', 'She came.'],
      correctAnswer: 'She might come.',
      correctFeedback: tri('Да. Might come менее уверенно, чем will come.', 'Так. Might come менш упевнено, ніж will come.', 'Yes. Might is less certain than will.'),
      wrong: {
        'She will come.': tri('will come звучит уверенно. Менее уверенно: might come.', 'will come звучить упевнено. Менш упевнено: might come.', 'Use might come.'),
        'She is here.': tri('She is here - это факт, не вероятность.', 'She is here - це факт, не ймовірність.', 'That is a fact.'),
        'She came.': tri('She came - факт в прошлом, не неуверенное будущее.', 'She came - факт у минулому, не невпевнене майбутнє.', 'That is a past fact.'),
      },
      contrast: tri('Will увереннее. Might осторожнее.', 'Will упевненіше. Might обережніше.', 'Will is more certain. Might is less certain.'),
      finalHint: tri('She might come.', 'She might come.', 'She might come.'),
      focusWords: ['might come', 'will come'],
    }),
    modalStep({
      id: 'modal_may_might_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'may_base_no_to',
      sentence: 'She may ___ the answer.',
      translation: tri('Возможно, она знает ответ.', 'Можливо, вона знає відповідь.', 'She may know the answer.'),
      options: ['know', 'knows', 'to know', 'knowing'],
      correctAnswer: 'know',
      correctFeedback: tri('Да. После may действие короткое: may know.', 'Так. Після may дія коротка: may know.', 'Yes. May know.'),
      wrong: {
        knows: tri('После may не добавляй -s. Даже с she нормально: may know.', 'Після may не додавай -s. Навіть із she нормально: may know.', 'Use may know.'),
        'to know': tri('После may не нужен to. Нормально: may know.', 'Після may не потрібен to. Нормально: may know.', 'Use may know.'),
        knowing: tri('may knowing не собирается. Нормально: may know.', 'may knowing не збирається. Нормально: may know.', 'Use may know.'),
      },
      contrast: tri('May уже показывает вероятность. Дальше идет know.', 'May уже показує ймовірність. Далі йде know.', 'May takes know.'),
      finalHint: tri('She may know the answer.', 'She may know the answer.', 'She may know the answer.'),
      focusWords: ['may know'],
    }),
    modalStep({
      id: 'modal_may_might_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'might_base_no_to',
      sentence: 'He might ___ late.',
      translation: tri('Возможно, он опоздает.', 'Можливо, він запізниться.', 'He might be late.'),
      options: ['be', 'is', 'to be', 'being'],
      correctAnswer: 'be',
      correctFeedback: tri('Да. После might нужен be: might be late.', 'Так. Після might потрібен be: might be late.', 'Yes. Might be late.'),
      wrong: {
        is: tri('После might не нужен is. Нормально: might be.', 'Після might не потрібен is. Нормально: might be.', 'Use might be.'),
        'to be': tri('После might не нужен to. Нормально: might be.', 'Після might не потрібен to. Нормально: might be.', 'Use might be.'),
        being: tri('might being не собирается. Нормально: might be.', 'might being не збирається. Нормально: might be.', 'Use might be.'),
      },
      contrast: tri('Возможно будет/окажется = might be.', 'Можливо буде/виявиться = might be.', 'Maybe he will be = might be.'),
      finalHint: tri('He might be late.', 'He might be late.', 'He might be late.'),
      focusWords: ['might be'],
    }),
    modalStep({
      id: 'modal_may_might_contrast_006',
      order: 9,
      difficulty: 'contrast',
      targetSkill: 'may_base_pair',
      sentence: 'Choose the correct pair.',
      translation: tri('may know / might come', 'may know / might come', 'may know / might come'),
      options: ['may know / might come', 'may knows / might comes', 'may to know / might to come', 'may knowing / might coming'],
      correctAnswer: 'may know / might come',
      correctFeedback: tri('Да. После may/might действие короткое: know, come.', 'Так. Після may/might дія коротка: know, come.', 'Yes. May know / might come.'),
      wrong: {
        'may knows / might comes': tri('После may/might не добавляй -s. Нормально: know / come.', 'Після may/might не додавай -s. Нормально: know / come.', 'No -s after may/might.'),
        'may to know / might to come': tri('После may/might не нужен to.', 'Після may/might не потрібен to.', 'No to after may/might.'),
        'may knowing / might coming': tri('Здесь после may/might не нужен -ing. Нормально: may know / might come.', 'Тут після may/might не потрібен -ing. Нормально: may know / might come.', 'Use may know / might come.'),
      },
      contrast: tri('May/might + короткое действие.', 'May/might + коротка дія.', 'May/might + action.'),
      finalHint: tri('may know / might come.', 'may know / might come.', 'may know / might come.'),
      focusWords: ['may know', 'might come'],
    }),
    modalStep({
      id: 'modal_may_might_mixed_001',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'may_not_probability',
      sentence: 'He ___ know the answer.',
      translation: tri('Возможно, он не знает ответ.', 'Можливо, він не знає відповідь.', 'He may not know the answer.'),
      options: ['may not', "doesn't may", "may doesn't", 'not may'],
      correctAnswer: 'may not',
      correctFeedback: tri('Да. May not = возможно нет.', 'Так. May not = можливо ні.', 'Yes. May not = maybe not.'),
      wrong: {
        "doesn't may": tri("May не требует doesn't. Нормально: may not know.", "May не потребує doesn't. Нормально: may not know.", 'Use may not know.'),
        "may doesn't": tri("После may не нужен doesn't. Нормально: may not know.", "Після may не потрібен doesn't. Нормально: may not know.", 'Use may not know.'),
        'not may': tri('Not ставится после may: may not.', 'Not ставиться після may: may not.', 'Use may not.'),
      },
      contrast: tri('Возможно нет = may not.', 'Можливо ні = may not.', 'Maybe not = may not.'),
      finalHint: tri('He may not know the answer.', 'He may not know the answer.', 'He may not know the answer.'),
      focusWords: ['may not know'],
    }),
    modalStep({
      id: 'modal_may_might_mixed_002',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'might_not_work',
      sentence: 'It ___ work.',
      translation: tri('Возможно, это не сработает.', 'Можливо, це не спрацює.', 'It might not work.'),
      options: ['might not', "doesn't might", "might doesn't", 'not might'],
      correctAnswer: 'might not',
      correctFeedback: tri('Да. Might not work = возможно, не сработает.', 'Так. Might not work = можливо, не спрацює.', 'Yes. Might not work.'),
      wrong: {
        "doesn't might": tri("Might не требует doesn't. Нормально: might not work.", "Might не потребує doesn't. Нормально: might not work.", 'Use might not work.'),
        "might doesn't": tri("После might не нужен doesn't. Нормально: might not work.", "Після might не потрібен doesn't. Нормально: might not work.", 'Use might not work.'),
        'not might': tri('Not ставится после might: might not work.', 'Not ставиться після might: might not work.', 'Use might not work.'),
      },
      contrast: tri('Возможно не сработает = might not work.', 'Можливо не спрацює = might not work.', 'Maybe not = might not.'),
      finalHint: tri('It might not work.', 'It might not work.', 'It might not work.'),
      focusWords: ['might not work'],
    }),
    modalStep({
      id: 'modal_may_might_mixed_003',
      order: 12,
      difficulty: 'mixed',
      targetSkill: 'maybe_vs_might',
      sentence: 'Choose the correct sentence.',
      translation: tri('Возможно, она придет.', 'Можливо, вона прийде.', 'She might come.'),
      options: ['She might come.', 'She maybe come.', 'She might to come.', 'She may comes.'],
      correctAnswer: 'She might come.',
      correctFeedback: tri('Да. С модалом нормально: might come.', 'Так. З модалом нормально: might come.', 'Yes. Might come.'),
      wrong: {
        'She maybe come.': tri('Maybe обычно отдельное слово: Maybe she will come. С модалом нормально: She might come.', 'Maybe зазвичай окреме слово: Maybe she will come. З модалом нормально: She might come.', 'Use She might come.'),
        'She might to come.': tri('После might не нужен to. Нормально: She might come.', 'Після might не потрібен to. Нормально: She might come.', 'Use She might come.'),
        'She may comes.': tri('После may не добавляй -s. Нормально: She may come.', 'Після may не додавай -s. Нормально: She may come.', 'Use She may come.'),
      },
      contrast: tri('Maybe - отдельное слово. Might - модальный кусок.', 'Maybe - окреме слово. Might - модальний зворот.', 'Maybe is separate; might is modal.'),
      finalHint: tri('She might come.', 'She might come.', 'She might come.'),
      focusWords: ['might come'],
    }),
    modalStep({
      id: 'modal_may_might_mixed_004',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_can_may_will',
      sentence: 'Choose the correct set.',
      translation: tri('Я умею плавать / Возможно, будет дождь / Она придет.', 'Я вмію плавати / Можливо, буде дощ / Вона прийде.', 'I can swim / It may rain / She will come'),
      options: [
        'I can swim / It may rain / She will come',
        'I may swim / It can rain / She might come',
        'I will swim / It does may rain / She may comes',
        'I can to swim / It may to rain / She will to come',
      ],
      correctAnswer: 'I can swim / It may rain / She will come',
      correctFeedback: tri('Да. Умение = can. Вероятность = may. Уверенное будущее = will.', 'Так. Вміння = can. Ймовірність = may. Упевнене майбутнє = will.', 'Yes. Ability / probability / certainty.'),
      wrong: {
        'I may swim / It can rain / She might come': tri('may swim значит возможно поплыву, не умею. It can rain звучит как общее "дождь бывает". She might come не уверенно.', 'may swim означає можливо попливу, не вмію. It can rain звучить як загальне "дощ буває". She might come не впевнено.', 'Meanings are mixed.'),
        'I will swim / It does may rain / She may comes': tri('does may rain и may comes не работают. Will swim не значит умею.', 'does may rain і may comes не працюють. Will swim не означає вмію.', 'Broken forms and meanings.'),
        'I can to swim / It may to rain / She will to come': tri('После can/may/will не нужен to.', 'Після can/may/will не потрібен to.', 'No to after these modals.'),
      },
      contrast: tri('Три разные полки: can / may / will.', 'Три різні полиці: can / may / will.', 'Ability / probability / certainty.'),
      finalHint: tri('I can swim / It may rain / She will come.', 'I can swim / It may rain / She will come.', 'I can swim / It may rain / She will come.'),
      focusWords: ['can', 'may', 'will'],
    }),
    modalStep({
      id: 'modal_may_might_mixed_005',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_may_might_negative',
      sentence: 'Choose the correct pair.',
      translation: tri('Возможно, это поможет / Возможно, это не сработает.', 'Можливо, це допоможе / Можливо, це не спрацює.', 'It may help / It might not work'),
      options: [
        'It may help / It might not work',
        "It may to help / It doesn't might work",
        "It may helps / It might doesn't work",
        'It maybe help / It not might work',
      ],
      correctAnswer: 'It may help / It might not work',
      correctFeedback: tri('Да. May help = возможно поможет. Might not work = возможно не сработает.', 'Так. May help = можливо допоможе. Might not work = можливо не спрацює.', 'Yes. May help / might not work.'),
      wrong: {
        "It may to help / It doesn't might work": tri("После may не нужен to. Might не требует doesn't.", "Після may не потрібен to. Might не потребує doesn't.", 'No to; no does with might.'),
        "It may helps / It might doesn't work": tri("После may не добавляй -s. После might не нужен doesn't.", "Після may не додавай -s. Після might не потрібен doesn't.", 'No -s; no does with might.'),
        'It maybe help / It not might work': tri('Maybe так не встраивается в этот кусок, а not ставится после might.', 'Maybe так не вбудовується в цей зворот, а not ставиться після might.', 'Use may help / might not work.'),
      },
      contrast: tri('Положительная вероятность и отрицательная вероятность.', 'Позитивна ймовірність і негативна ймовірність.', 'Positive and negative probability.'),
      finalHint: tri('It may help / It might not work.', 'It may help / It might not work.', 'It may help / It might not work.'),
      focusWords: ['may help', 'might not work'],
    }),
    modalStep({
      id: 'modal_may_might_mixed_006',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_sentence_correction',
      sentence: 'Choose the correct sentence.',
      translation: tri('Возможно, она занята, поэтому, возможно, не ответит.', 'Можливо, вона зайнята, тому, можливо, не відповість.', 'She may be busy, so she might not answer.'),
      options: [
        'She may be busy, so she might not answer.',
        "She may is busy, so she doesn't might answer.",
        "She maybe busy, so she might doesn't answer.",
        'She may to be busy, so she might not to answer.',
      ],
      correctAnswer: 'She may be busy, so she might not answer.',
      correctFeedback: tri('Да. May be busy и might not answer правильно передают вероятность.', 'Так. May be busy і might not answer правильно передають ймовірність.', 'Yes. May be / might not answer.'),
      wrong: {
        "She may is busy, so she doesn't might answer.": tri("После may нужен be, не is. Might не требует doesn't.", "Після may потрібен be, не is. Might не потребує doesn't.", 'Use may be / might not answer.'),
        "She maybe busy, so she might doesn't answer.": tri("Maybe busy без be не собирается, а после might не нужен doesn't.", "Maybe busy без be не збирається, а після might не потрібен doesn't.", 'Use may be / might not answer.'),
        'She may to be busy, so she might not to answer.': tri('После may/might не нужен to. Нормально: may be / might not answer.', 'Після may/might не потрібен to. Нормально: may be / might not answer.', 'No to after may/might.'),
      },
      contrast: tri('Две вероятности в одной фразе: may be / might not answer.', 'Дві ймовірності в одній фразі: may be / might not answer.', 'Two probability chunks.'),
      finalHint: tri('She may be busy, so she might not answer.', 'She may be busy, so she might not answer.', 'She may be busy, so she might not answer.'),
      focusWords: ['may be', 'might not answer'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'may_to_error',
      'might_to_error',
      'modal_plus_s_error',
      'modal_plus_ing_error',
      'can_probability_confusion',
      'will_probability_confusion',
      'may_not_meaning_error',
      'do_with_modal_error',
      'maybe_modal_confusion',
      'wrong_uncertainty_strength_error',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri('Обычное объяснение: показать вероятность, уверенность и форму после may/might.', 'Звичайне пояснення: показати ймовірність, упевненість і форму після may/might.', 'Muestra probabilidad, certeza y forma despues de may/might.'),
    depth2: tri('Проще: спросить, это точно, возможно или умение?', 'Простіше: спитати, це точно, можливо чи вміння?', 'Pregunta: seguro, posible o habilidad?'),
    depth3: tri('Еще проще: сравнить will come / might come / can swim.', 'Ще простіше: порівняти will come / might come / can swim.', 'Compara will / might / can.'),
    depth4: tri('Почти подсказка: показать прямо may, might, may not или might not.', 'Майже підказка: показати прямо may, might, may not або might not.', 'Senala el bloque correcto.'),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri(
        'May/might = возможно. После них действие короткое: may be, may know, might come. Not стоит после модала: may not, might not. Do/does не нужен.',
        'May/might = можливо. Після них дія коротка: may be, may know, might come. Not стоїть після модала: may not, might not. Do/does не потрібен.',
        'May/might = quiza. Usa may be, may know, might come, might not work.',
      ),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_probability_hint_then_retry',
      card: tri(
        'Подсказка: сначала выбери полку. Это вероятность, уверенность или умение?',
        'Підказка: спочатку обери полицю. Це ймовірність, упевненість чи вміння?',
        'Pista: primero elige probabilidad, certeza o habilidad.',
      ),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri(
        'Режим с подсказками: сначала отделяем возможно / точно / умею, потом возвращаемся к полной фразе.',
        'Режим із підказками: спочатку відділяємо можливо / точно / вмію, потім повертаємося до повної фрази.',
        'Modo guiado: separa quiza / seguro / habilidad primero.',
      ),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      {
        id: 'guided_modal_may_might_001',
        prompt: tri('May rain значит точно дождь или возможно дождь?', 'May rain означає точно дощ чи можливо дощ?', 'May rain significa seguro que llueve o quiza llueva?'),
        options: ['certainly rain', 'maybe rain'],
        correctIndex: 1,
        thenReturnToExerciseId: 'modal_may_might_easy_001',
      },
      {
        id: 'guided_modal_may_might_002',
        prompt: tri('После may правильно knows или know?', 'Після may правильно knows чи know?', 'Despues de may, correcto es knows o know?'),
        options: ['knows', 'know'],
        correctIndex: 1,
        thenReturnToExerciseId: 'modal_may_might_contrast_004',
      },
      {
        id: 'guided_modal_may_might_003',
        prompt: tri('Might not значит возможно нет или точно нет?', 'Might not означає можливо ні чи точно ні?', 'Might not significa quiza no o definitivamente no?'),
        options: ['maybe not', 'definitely not'],
        correctIndex: 0,
        thenReturnToExerciseId: 'modal_may_might_mixed_002',
      },
      {
        id: 'guided_modal_may_might_004',
        prompt: tri('Can чаще про умение или вероятность?', 'Can частіше про вміння чи ймовірність?', 'Can suele hablar de habilidad o de probabilidad?'),
        options: ['ability', 'probability'],
        correctIndex: 0,
        thenReturnToExerciseId: 'modal_may_might_mixed_004',
      },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'modal',
    microDiagnosisId: 'modal_may_might_probability',
    diagnosisLabel: tri('May / Might', 'May / Might', 'May / Might'),
    contrastSet: CONTRAST,
    difficultyLevel: 2,
    focusWords: ['may rain', 'may be', 'might come', 'might work', 'may not know', 'might not work'],
    focusPatterns: [
      'may_rain',
      'may_be_busy',
      'may_help',
      'might_less_certain',
      'might_work',
      'may_vs_will_certainty',
      'may_base_no_to',
      'might_base_no_to',
      'may_base_pair',
      'may_not_probability',
      'might_not_work',
      'maybe_vs_might',
      'mixed_can_may_will',
      'mixed_may_might_negative',
      'mixed_sentence_correction',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 3,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_started',
    answer: 'diagnosis_training_answer',
    mastery: 'diagnosis_training_mastered',
    recovery: 'diagnosis_training_recovery',
    onStart: 'diagnosis_training_started',
    onCorrect: 'diagnosis_training_answer_correct',
    onWrong: 'diagnosis_training_answer_wrong',
    onDepthIncrease: 'diagnosis_training_feedback_depth_increased',
    onGuidedMode: 'diagnosis_training_guided_mode_started',
    onMastery: 'diagnosis_training_mastered',
    onSmartTrainerOpen: 'diagnosis_training_smart_trainer_opened',
    payload: {
      category: 'modal',
      microDiagnosisId: 'modal_may_might_probability',
      contrastSet: ['may', 'might', 'may not', 'might not', 'can', 'will'],
      logExactToken: true,
      logMistakeType: true,
      logExerciseId: true,
      logAttemptCount: true,
      logFeedbackDepth: true,
      logModalMeaning: true,
      logProbabilityStrength: true,
      logVerbFormAfterModal: true,
      logPolarity: true,
    },
  },
  routing: {
    diagnosisTrainerRoute: '/problem_coach?category=modal&microDiagnosisId=modal_may_might_probability',
  },
  qualityChecklist: {
    hasStableId: true,
    hasCategory: true,
    hasMultilingualTitle: true,
    hasPlainDiagnosisText: true,
    hasMentalModel: true,
    hasContrastSet: true,
    hasAtLeastSixExamples: true,
    hasAtLeastTwelveExercises: true,
    hasEasyContrastMixedStructure: true,
    hasDistractorSpecificFeedback: true,
    hasRetryFeedbackLevels: true,
    hasGuidedModeForRepeatedMistakes: true,
    hasMasteryRules: true,
    hasSmartTrainerConfig: true,
    hasAnalyticsPayload: true,
    hasFallbackRoute: true,
  },
};
