import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

type PlannedTrainingLocale = 'pt-BR' | 'vi' | 'id' | 'tr' | 'pl';

const tri = (
  ru: string,
  uk: string,
  es = ru,
  planned: Partial<Record<PlannedTrainingLocale, string>> = {},
): TriText => {
  const copy: TriText = { ru, uk, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    copy[locale] = planned[locale] ?? DIRECTION_NEEDS_REVIEW_PLANNED[locale];
  }
  return copy;
};

const CONTRAST = ['to', 'into', 'from', 'out of', 'towards', 'in', 'direction', 'source'];

const DIRECTION_STEP_ES: Record<string, string> = {
  prep_dir_easy_001: 'Voy al trabajo todos los dias.',
  prep_dir_easy_002: 'Fuimos en coche a Dublin.',
  prep_dir_easy_003: 'Envialo a mi.',
  prep_dir_contrast_001: 'Ella entro en la habitacion.',
  prep_dir_contrast_002: 'Pon las llaves dentro de la bolsa.',
  prep_dir_contrast_003: 'Entre en la habitacion.',
  prep_dir_contrast_004: 'El vino del trabajo tarde.',
  prep_dir_contrast_005: 'Ella es de Ucrania.',
  prep_dir_contrast_006: 'Recibi un mensaje de mi amigo.',
  prep_dir_mixed_001: 'Sal del coche.',
  prep_dir_mixed_002: 'Saca el telefono de la bolsa.',
  prep_dir_mixed_003: 'meterlo en la bolsa / sacarlo de la bolsa',
  prep_dir_mixed_004: 'al trabajo / del trabajo',
  prep_dir_mixed_005: 'estoy en la habitacion / entre en la habitacion',
  prep_dir_mixed_006: 'Ella vino del trabajo y entro en la habitacion.',
};

const DIRECTION_STEP_PLANNED: Record<string, Record<PlannedTrainingLocale, string>> = {
  prep_dir_easy_001: {
    'pt-BR': 'Eu vou ao trabalho todos os dias.',
    vi: 'Tôi đi làm mỗi ngày.',
    id: 'Saya pergi bekerja setiap hari.',
    tr: 'Her gün işe giderim.',
    pl: 'Chodzę do pracy codziennie.',
  },
  prep_dir_easy_002: {
    'pt-BR': 'Fomos de carro para Dublin.',
    vi: 'Chúng tôi đã lái xe đến Dublin.',
    id: 'Kami berkendara ke Dublin.',
    tr: "Dublin'e arabayla gittik.",
    pl: 'Pojechaliśmy samochodem do Dublina.',
  },
  prep_dir_easy_003: {
    'pt-BR': 'Envie isso para mim.',
    vi: 'Gửi nó cho tôi.',
    id: 'Kirimkan itu kepada saya.',
    tr: 'Onu bana gönder.',
    pl: 'Wyślij mi to.',
  },
  prep_dir_contrast_001: {
    'pt-BR': 'Ela entrou na sala.',
    vi: 'Cô ấy bước vào phòng.',
    id: 'Dia berjalan masuk ke ruangan.',
    tr: 'Odaya girdi.',
    pl: 'Weszła do pokoju.',
  },
  prep_dir_contrast_002: {
    'pt-BR': 'Coloque as chaves na bolsa.',
    vi: 'Bỏ chìa khóa vào túi.',
    id: 'Masukkan kunci ke dalam tas.',
    tr: 'Anahtarları çantanın içine koy.',
    pl: 'Włóż klucze do torby.',
  },
  prep_dir_contrast_003: {
    'pt-BR': 'Entrei na sala.',
    vi: 'Tôi đã đi vào phòng.',
    id: 'Saya masuk ke ruangan.',
    tr: 'Odaya girdim.',
    pl: 'Wszedłem do pokoju.',
  },
  prep_dir_contrast_004: {
    'pt-BR': 'Ele chegou tarde do trabalho.',
    vi: 'Anh ấy đi làm về muộn.',
    id: 'Dia pulang dari kerja terlambat.',
    tr: 'İşten geç geldi.',
    pl: 'Przyszedł późno z pracy.',
  },
  prep_dir_contrast_005: {
    'pt-BR': 'Ela é da Ucrânia.',
    vi: 'Cô ấy đến từ Ukraine.',
    id: 'Dia berasal dari Ukraina.',
    tr: 'O Ukraynalı.',
    pl: 'Ona jest z Ukrainy.',
  },
  prep_dir_contrast_006: {
    'pt-BR': 'Recebi uma mensagem do meu amigo.',
    vi: 'Tôi nhận được tin nhắn từ bạn tôi.',
    id: 'Saya mendapat pesan dari teman saya.',
    tr: 'Arkadaşımdan bir mesaj aldım.',
    pl: 'Dostałem wiadomość od mojego znajomego.',
  },
  prep_dir_mixed_001: {
    'pt-BR': 'Saia do carro.',
    vi: 'Ra khỏi xe đi.',
    id: 'Keluar dari mobil.',
    tr: 'Arabadan çık.',
    pl: 'Wysiądź z samochodu.',
  },
  prep_dir_mixed_002: {
    'pt-BR': 'Tire o telefone da bolsa.',
    vi: 'Lấy điện thoại ra khỏi túi.',
    id: 'Keluarkan telepon dari tas.',
    tr: 'Telefonu çantadan çıkar.',
    pl: 'Wyjmij telefon z torby.',
  },
  prep_dir_mixed_003: {
    'pt-BR': 'colocar na bolsa / tirar da bolsa',
    vi: 'bỏ vào túi / lấy ra khỏi túi',
    id: 'memasukkan ke tas / mengeluarkan dari tas',
    tr: 'çantaya koymak / çantadan çıkarmak',
    pl: 'włożyć do torby / wyjąć z torby',
  },
  prep_dir_mixed_004: {
    'pt-BR': 'para o trabalho / do trabalho',
    vi: 'đi làm / từ chỗ làm về',
    id: 'ke tempat kerja / dari tempat kerja',
    tr: 'işe / işten',
    pl: 'do pracy / z pracy',
  },
  prep_dir_mixed_005: {
    'pt-BR': 'estou na sala / entrei na sala',
    vi: 'tôi ở trong phòng / tôi đi vào phòng',
    id: 'saya ada di ruangan / saya masuk ke ruangan',
    tr: 'odadayım / odaya girdim',
    pl: 'jestem w pokoju / wszedłem do pokoju',
  },
  prep_dir_mixed_006: {
    'pt-BR': 'Ela veio do trabalho e entrou na sala.',
    vi: 'Cô ấy từ chỗ làm về và đi vào phòng.',
    id: 'Dia datang dari tempat kerja dan masuk ke ruangan.',
    tr: 'İşten geldi ve odaya girdi.',
    pl: 'Przyszła z pracy i weszła do pokoju.',
  },
};

const DIRECTION_NEEDS_REVIEW_PLANNED: Record<PlannedTrainingLocale, string> = {
  'pt-BR': 'needs-review: esta explicação sobre preposições de direção ainda precisa de revisão para português do Brasil.',
  vi: 'needs-review: phần giải thích về giới từ chỉ hướng này vẫn cần được rà soát cho tiếng Việt.',
  id: 'needs-review: penjelasan preposisi arah ini masih perlu ditinjau untuk bahasa Indonesia.',
  tr: 'needs-review: bu yön edatları açıklaması Türkçe için hâlâ gözden geçirilmeli.',
  pl: 'needs-review: to objaśnienie przyimków kierunku nadal wymaga przeglądu po polsku.',
};

const DIRECTION_SKILL_ES: Record<string, string> = {
  to_destination_work: 'Movimiento hacia un lugar o una meta: usa to.',
  to_city_destination: 'La ciudad es el destino del viaje: usa to.',
  to_recipient: 'La persona recibe algo: usa to.',
  into_room: 'La flecha entra dentro de un espacio: usa into.',
  into_bag: 'El objeto se mueve hacia dentro de una bolsa o caja: usa into.',
  in_vs_into_room: 'In es estar ya dentro; into es entrar hacia dentro.',
  from_work: 'From responde a "de donde?".',
  from_country: 'El origen se marca con from.',
  from_person_source: 'La fuente de un mensaje o cosa se marca con from.',
  out_of_car: 'La persona sale desde dentro hacia fuera: usa out of.',
  out_of_bag: 'El objeto sale desde dentro hacia fuera: usa out of.',
  into_out_of_pair: 'Compara dos flechas: hacia dentro = into; hacia fuera desde dentro = out of.',
  mixed_to_from: 'To y from son flechas opuestas: hacia un lugar y desde un lugar.',
  mixed_in_into: 'In marca estado dentro; into marca movimiento hacia dentro.',
  mixed_sentence_correction: 'Divide la frase en bloques: from work y into the room.',
};

function withEs(
  copy: TriText,
  es: string,
  planned: Partial<Record<PlannedTrainingLocale, string>> = DIRECTION_NEEDS_REVIEW_PLANNED,
): TriText {
  const next: TriText = { ...copy, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    if (!next[locale] || next[locale]?.startsWith('needs-review:')) {
      next[locale] = planned[locale] ?? DIRECTION_NEEDS_REVIEW_PLANNED[locale];
    }
  }
  return next;
}

function directionEsFeedback(input: {
  targetSkill: string;
  correctAnswer: string;
  focusWords: string[];
}): string {
  const focus = input.focusWords.join(' / ');
  const hint = DIRECTION_SKILL_ES[input.targetSkill] ?? 'Dibuja la flecha de movimiento antes de elegir la palabra pequena.';
  return `Usa "${input.correctAnswer}"${focus ? ` con ${focus}` : ''}. ${hint}`;
}

function directionStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  teachingText: TriText;
  sentence: string;
  translation: TriText;
  options: string[];
  correctAnswer: string;
  correctFeedback: TriText;
  wrong: Record<string, TriText>;
  retry: [TriText, TriText, TriText];
  fallbackExplanation: TriText;
  focusWords: string[];
}): DiagnosisTrainingStep {
  const correctIndex = input.options.findIndex((option) => option === input.correctAnswer);
  const esFeedback = directionEsFeedback(input);

  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    teachingText: withEs(input.teachingText, esFeedback),
    translation: withEs(input.translation, DIRECTION_STEP_ES[input.id] ?? esFeedback, DIRECTION_STEP_PLANNED[input.id]),
    explanationBlock: withEs(input.teachingText, esFeedback),
    microTask: tri(
      'Выбери маленькое слово по движению: куда, внутрь, откуда или изнутри наружу.',
      'Обери маленьке слово за рухом: куди, всередину, звідки або зсередини назовні.',
      'Elige la palabra pequena segun el movimiento: hacia donde, hacia dentro, desde donde o desde dentro hacia fuera.',
    ),
    sentence: input.sentence,
    answerOptions: input.options.map((text) => ({ id: text, text })),
    correctAnswerId: input.correctAnswer,
    correctIndex,
    correctFeedback: withEs(input.correctFeedback, esFeedback),
    wrongFeedbackByOption: Object.fromEntries(
      input.options
        .filter((option) => option !== input.correctAnswer)
        .map((option) => [option, withEs(input.wrong[option] ?? tri(
          `Почти. Здесь нужен готовый кусок с ${input.correctAnswer}.`,
          `Майже. Тут потрібен готовий зворот з ${input.correctAnswer}.`,
          `Casi. Aquí necesitas el bloque con ${input.correctAnswer}.`,
        ), esFeedback)]),
    ),
    retryFeedback: [
      withEs(input.retry[0], esFeedback),
      withEs(input.retry[1], esFeedback),
      withEs(input.retry[2], esFeedback),
      tri(
        `Подсказка: готовый кусок - ${input.correctAnswer} ${input.focusWords[0] ?? ''}.`.trim(),
        `Підказка: готовий зворот - ${input.correctAnswer} ${input.focusWords[0] ?? ''}.`.trim(),
        `Pista: el bloque listo es ${input.correctAnswer} ${input.focusWords[0] ?? ''}.`.trim(),
      ),
    ],
    fallbackExplanation: withEs(input.fallbackExplanation, esFeedback),
    focusWords: input.focusWords,
  };
}

export const PREPOSITION_DIRECTION_TO_INTO_FROM_TRAINING: DiagnosisTraining = {
  id: 'preposition_direction_to_into_from',
  category: 'preposition',
  version: '1.0.0',
  status: 'active',
  priority: 28,
  supportedLocales: ['ru', 'uk', 'es'],
  title: tri(
    'To / Into / From / Out of: куда движется действие',
    'To / Into / From / Out of: куди рухається дія',
    'To / Into / From / Out of: hacia donde se mueve la accion',
    {
      'pt-BR': 'To / Into / From / Out of: para onde a ação se move',
      vi: 'To / Into / From / Out of: hành động di chuyển về đâu',
      id: 'To / Into / From / Out of: ke mana aksi bergerak',
      tr: 'To / Into / From / Out of: eylem nereye hareket ediyor',
      pl: 'To / Into / From / Out of: dokąd porusza się czynność',
    },
  ),
  shortTitle: tri(
    'Куда / внутрь / откуда',
    'Куди / всередину / звідки',
    'Hacia / dentro / desde',
    {
      'pt-BR': 'Para / para dentro / de onde',
      vi: 'Đến đâu / vào trong / từ đâu',
      id: 'Ke mana / ke dalam / dari mana',
      tr: 'Nereye / içeri / nereden',
      pl: 'Dokąd / do środka / skąd',
    },
  ),
  shortDiagnosis: tri(
    'Ты путаешь маленькие слова движения: к месту, внутрь, откуда и изнутри наружу.',
    'Ти плутаєш маленькі слова руху: до місця, всередину, звідки та зсередини назовні.',
    'Confundes palabras pequenas de movimiento: hacia un lugar, hacia dentro, desde un lugar y desde dentro hacia fuera.',
    {
      'pt-BR': 'Você confunde pequenas palavras de movimento: para um lugar, para dentro, de onde e de dentro para fora.',
      vi: 'Bạn đang nhầm các từ nhỏ chỉ chuyển động: đến một nơi, vào trong, từ đâu và từ trong ra ngoài.',
      id: 'Kamu mencampur kata kecil untuk gerakan: ke tempat, ke dalam, dari mana, dan dari dalam ke luar.',
      tr: 'Hareketin küçük kelimelerini karıştırıyorsun: bir yere, içeri, nereden ve içeriden dışarı.',
      pl: 'Mylisz małe słowa ruchu: do miejsca, do środka, skąd oraz ze środka na zewnątrz.',
    },
  ),
  diagnosisText: tri(
    'Похоже, ты выбираешь маленькое слово по переводу, а не по движению. Английский здесь смотрит на маршрут: действие идёт к месту, входит внутрь, выходит изнутри или начинается откуда-то.',
    'Схоже, ти обираєш маленьке слово за перекладом, а не за рухом. Англійська тут дивиться на маршрут: дія йде до місця, входить усередину, виходить зсередини або починається звідкись.',
    'El problema es elegir por traduccion en vez de por movimiento. El ingles mira la ruta: hacia un lugar, hacia dentro, desde dentro hacia fuera o desde algun punto.',
    {
      'pt-BR': 'Parece que você escolhe a palavra pequena pela tradução, não pelo movimento. O inglês olha para a rota: a ação vai para um lugar, entra, sai de dentro ou começa em algum ponto.',
      vi: 'Có vẻ bạn chọn từ nhỏ theo bản dịch, không theo chuyển động. Tiếng Anh nhìn vào lộ trình: hành động đi đến một nơi, đi vào trong, đi từ trong ra ngoài hoặc bắt đầu từ đâu đó.',
      id: 'Sepertinya kamu memilih kata kecil berdasarkan terjemahan, bukan gerakan. Bahasa Inggris melihat rutenya: aksi menuju tempat, masuk ke dalam, keluar dari dalam, atau mulai dari suatu titik.',
      tr: 'Küçük kelimeyi harekete göre değil çeviriye göre seçiyor gibisin. İngilizce burada rotaya bakar: eylem bir yere gider, içeri girer, içeriden dışarı çıkar ya da bir noktadan başlar.',
      pl: 'Wygląda na to, że wybierasz małe słowo według tłumaczenia, a nie według ruchu. Angielski patrzy tu na trasę: czynność idzie do miejsca, wchodzi do środka, wychodzi ze środka albo zaczyna się skądś.',
    },
  ),
  mentalModel: tri(
    'Представь стрелку. To - стрелка к месту или человеку. Into - стрелка внутрь. From - стрелка откуда началось движение. Out of - стрелка изнутри наружу. In - уже внутри, без входа.',
    'Уяви стрілку. To - стрілка до місця або людини. Into - стрілка всередину. From - стрілка звідки почався рух. Out of - стрілка зсередини назовні. In - уже всередині, без входу.',
    'Imagina una flecha. To = hacia un lugar o persona. Into = hacia dentro. From = punto de inicio. Out of = desde dentro hacia fuera. In = ya dentro.',
    {
      'pt-BR': 'Imagine uma seta. To = seta para um lugar ou pessoa. Into = seta para dentro. From = ponto de partida. Out of = de dentro para fora. In = já dentro.',
      vi: 'Hãy tưởng tượng một mũi tên. To = mũi tên đến nơi hoặc người. Into = mũi tên vào trong. From = điểm bắt đầu. Out of = từ trong ra ngoài. In = đã ở bên trong.',
      id: 'Bayangkan sebuah panah. To = panah ke tempat atau orang. Into = panah ke dalam. From = titik awal. Out of = dari dalam ke luar. In = sudah di dalam.',
      tr: 'Bir ok düşün. To = bir yere veya kişiye doğru ok. Into = içeri doğru ok. From = başlangıç noktası. Out of = içeriden dışarı. In = zaten içeride.',
      pl: 'Wyobraź sobie strzałkę. To = strzałka do miejsca albo osoby. Into = strzałka do środka. From = punkt startu. Out of = ze środka na zewnątrz. In = już w środku.',
    },
  ),
  contrastSet: CONTRAST,
  coreRule: tri(
    'go to work, walk into the room, come from work, get out of the car, be in the room.',
    'go to work, walk into the room, come from work, get out of the car, be in the room.',
    'go to work, walk into the room, come from work, get out of the car, be in the room.',
    {
      'pt-BR': 'go to work, walk into the room, come from work, get out of the car, be in the room.',
      vi: 'go to work, walk into the room, come from work, get out of the car, be in the room.',
      id: 'go to work, walk into the room, come from work, get out of the car, be in the room.',
      tr: 'go to work, walk into the room, come from work, get out of the car, be in the room.',
      pl: 'go to work, walk into the room, come from work, get out of the car, be in the room.',
    },
  ),
  whatUserMustLearn: {
    ru: [
      'To показывает движение к месту или человеку: go to work, send it to me.',
      'Into показывает вход внутрь: go into the room, put it into the bag.',
      'From показывает, откуда началось движение: come from work, be from Ukraine.',
      'Out of показывает выход изнутри наружу: get out of the car, take it out of the bag.',
      'In показывает, что кто-то или что-то уже внутри: I am in the room.',
      'Towards показывает движение в сторону, но не обязательно до самой точки.',
      'Главная привычка: сначала нарисовать стрелку, потом выбрать маленькое слово.',
    ],
    uk: [
      'To показує рух до місця або людини: go to work, send it to me.',
      'Into показує вхід усередину: go into the room, put it into the bag.',
      'From показує, звідки почався рух: come from work, be from Ukraine.',
      'Out of показує вихід зсередини назовні: get out of the car, take it out of the bag.',
      'In показує, що хтось або щось уже всередині: I am in the room.',
      'Towards показує рух у бік, але не обовʼязково до самої точки.',
      'Головна звичка: спочатку намалювати стрілку, потім обрати маленьке слово.',
    ],
    es: [
      'To muestra movimiento hacia un lugar o una persona.',
      'Into muestra entrada hacia dentro.',
      'From muestra el punto de inicio.',
      'Out of muestra salida desde dentro hacia fuera.',
      'In muestra que alguien o algo ya esta dentro.',
      'Towards muestra movimiento en direccion a algo, no siempre hasta el punto final.',
      'Primero dibuja la flecha, luego elige la palabra.',
    ],
    'pt-BR': [
      'To = movimento para um lugar ou pessoa.',
      'Into = movimento para dentro.',
      'From = ponto de partida.',
      'Out of = de dentro para fora.',
      'In = já dentro.',
      'Towards = na direção de.',
      'Primeiro desenhe a seta, depois escolha a palavra.',
    ],
    vi: [
      'To = chuyển động đến một nơi hoặc một người.',
      'Into = chuyển động vào bên trong.',
      'From = điểm xuất phát.',
      'Out of = từ bên trong ra ngoài.',
      'In = đã ở bên trong.',
      'Towards = theo hướng về phía.',
      'Trước tiên vẽ mũi tên, rồi chọn từ.',
    ],
    id: [
      'To = gerakan menuju tempat atau orang.',
      'Into = gerakan masuk ke dalam.',
      'From = titik awal.',
      'Out of = dari dalam ke luar.',
      'In = sudah berada di dalam.',
      'Towards = ke arah.',
      'Gambar panahnya dulu, lalu pilih katanya.',
    ],
    tr: [
      'To = bir yere veya kişiye doğru hareket.',
      'Into = içeri doğru hareket.',
      'From = başlangıç noktası.',
      'Out of = içeriden dışarı.',
      'In = zaten içeride.',
      'Towards = yönüne doğru.',
      'Önce oku çiz, sonra kelimeyi seç.',
    ],
    pl: [
      'To = ruch do miejsca lub osoby.',
      'Into = ruch do środka.',
      'From = punkt startowy.',
      'Out of = ze środka na zewnątrz.',
      'In = już w środku.',
      'Towards = w kierunku.',
      'Najpierw narysuj strzałkę, potem wybierz słowo.',
    ],
  },
  examples: [
    { en: 'I go to work every day.', ru: 'Я хожу на работу каждый день.', uk: 'Я ходжу на роботу щодня.', es: 'Voy al trabajo todos los dias.', 'pt-BR': 'Eu vou ao trabalho todos os dias.', vi: 'Tôi đi làm mỗi ngày.', id: 'Saya pergi bekerja setiap hari.', tr: 'Her gün işe giderim.', pl: 'Chodzę do pracy codziennie.', why: tri('Стрелка идёт к месту: to work.', 'Стрілка йде до місця: to work.', 'La flecha va hacia un lugar: to work.') },
    { en: 'She walked into the room.', ru: 'Она вошла в комнату.', uk: 'Вона увійшла в кімнату.', es: 'Ella entro en la habitacion.', 'pt-BR': 'Ela entrou na sala.', vi: 'Cô ấy bước vào phòng.', id: 'Dia berjalan masuk ke ruangan.', tr: 'Odaya girdi.', pl: 'Weszła do pokoju.', why: tri('Стрелка входит внутрь комнаты: into the room.', 'Стрілка входить усередину кімнати: into the room.', 'La flecha entra hacia dentro: into the room.') },
    { en: 'He came from work late.', ru: 'Он пришёл с работы поздно.', uk: 'Він прийшов з роботи пізно.', es: 'El vino tarde del trabajo.', 'pt-BR': 'Ele chegou tarde do trabalho.', vi: 'Anh ấy đi làm về muộn.', id: 'Dia pulang dari kerja terlambat.', tr: 'İşten geç geldi.', pl: 'Przyszedł późno z pracy.', why: tri('Work - место, откуда он пришёл: from work.', 'Work - місце, звідки він прийшов: from work.', 'Work es el lugar desde donde vino: from work.') },
    { en: 'Take the phone out of the bag.', ru: 'Достань телефон из сумки.', uk: 'Дістань телефон із сумки.', es: 'Saca el telefono de la bolsa.', 'pt-BR': 'Tire o telefone da bolsa.', vi: 'Lấy điện thoại ra khỏi túi.', id: 'Keluarkan telepon dari tas.', tr: 'Telefonu çantadan çıkar.', pl: 'Wyjmij telefon z torby.', why: tri('Телефон был внутри сумки и движется наружу: out of the bag.', 'Телефон був усередині сумки і рухається назовні: out of the bag.', 'El telefono estaba dentro y se mueve hacia fuera: out of the bag.') },
    { en: 'I am in the room.', ru: 'Я в комнате.', uk: 'Я в кімнаті.', es: 'Estoy en la habitacion.', 'pt-BR': 'Estou na sala.', vi: 'Tôi đang ở trong phòng.', id: 'Saya ada di ruangan.', tr: 'Odadayım.', pl: 'Jestem w pokoju.', why: tri('Движения нет. Человек уже внутри комнаты: in the room.', 'Руху немає. Людина вже всередині кімнати: in the room.', 'No hay movimiento. Ya esta dentro: in the room.') },
    { en: 'I went into the room.', ru: 'Я вошёл в комнату.', uk: 'Я увійшов у кімнату.', es: 'Entre en la habitacion.', 'pt-BR': 'Entrei na sala.', vi: 'Tôi đã đi vào phòng.', id: 'Saya masuk ke ruangan.', tr: 'Odaya girdim.', pl: 'Wszedłem do pokoju.', why: tri('Здесь есть вход внутрь, поэтому into the room.', 'Тут є вхід усередину, тому into the room.', 'Aqui hay entrada hacia dentro: into the room.') },
    { en: 'Send it to me.', ru: 'Отправь это мне.', uk: 'Надішли це мені.', es: 'Envialo a mi.', 'pt-BR': 'Envie isso para mim.', vi: 'Gửi nó cho tôi.', id: 'Kirimkan itu kepada saya.', tr: 'Onu bana gönder.', pl: 'Wyślij mi to.', why: tri('To может показывать не место, а человека-получателя: to me.', 'To може показувати не місце, а людину-отримувача: to me.', 'To tambien puede apuntar al receptor: to me.') },
    { en: 'She walked towards the door.', ru: 'Она пошла к двери.', uk: 'Вона пішла до дверей.', es: 'Ella camino hacia la puerta.', 'pt-BR': 'Ela caminhou em direção à porta.', vi: 'Cô ấy đi về phía cửa.', id: 'Dia berjalan menuju pintu.', tr: 'Kapıya doğru yürüdü.', pl: 'Poszła w stronę drzwi.', why: tri('Towards - в сторону двери. Не обязательно значит, что она дошла до двери.', 'Towards - у бік дверей. Не обовʼязково значить, що вона дійшла до дверей.', 'Towards significa en direccion a la puerta, no necesariamente hasta ella.') },
  ],
  introBlocks: [
    { id: 'intro_problem', type: 'diagnosis', text: tri('Здесь ловушка в маршруте. Слова похожи, но стрелка движения разная.', 'Тут пастка в маршруті. Слова схожі, але стрілка руху різна.', 'La trampa esta en la ruta. Las palabras se parecen, pero la flecha de movimiento es distinta.') },
    { id: 'intro_rule', type: 'rule', text: tri('Не начинай с перевода. Сначала спроси: действие идёт к месту, внутрь, откуда или наружу изнутри?', 'Не починай з перекладу. Спочатку спитай: дія йде до місця, всередину, звідки або назовні зсередини?', 'No empieces por la traduccion. Pregunta: hacia un lugar, hacia dentro, desde donde o desde dentro hacia fuera?') },
    { id: 'intro_tone', type: 'encouragement', text: tri('Это чинится быстро, если видеть стрелку. Давай закрепим несколько готовых кусков.', 'Це швидко чиниться, якщо бачити стрілку. Закріпімо кілька готових зворотів.', 'Esto se arregla rapido si ves la flecha. Vamos a fijar unos bloques listos.') },
  ],
  steps: [
    directionStep({
      id: 'prep_dir_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'to_destination_work',
      teachingText: tri('Когда действие идёт к месту как к цели, нужен to. Работа здесь место, куда человек идёт.', 'Коли дія йде до місця як до цілі, потрібен to. Робота тут місце, куди людина йде.', 'When movement goes to a place as a goal, use to.'),
      sentence: 'I go ___ work every day.',
      translation: tri('Я хожу на работу каждый день.', 'Я ходжу на роботу щодня.', 'I go to work every day.'),
      options: ['to', 'into', 'from', 'out of'],
      correctAnswer: 'to',
      correctFeedback: tri('Да. Стрелка идёт к месту: to work.', 'Так. Стрілка йде до місця: to work.', 'Yes. The arrow goes to a place: to work.'),
      wrong: {
        into: tri('Into значило бы “внутрь”, как вход в комнату. Здесь обычная цель пути: to work.', 'Into означало б “всередину”, як вхід у кімнату. Тут звичайна ціль шляху: to work.', 'Into means inside. Here the goal is the place: to work.'),
        from: tri('From значит “откуда”. Здесь человек идёт к работе, а не от работы. Нужен to work.', 'From означає “звідки”. Тут людина йде до роботи, а не з роботи. Потрібен to work.', 'From means from where. Here it is to work.'),
        'out of': tri('Out of значит изнутри наружу. Работа здесь цель пути, поэтому to work.', 'Out of означає зсередини назовні. Робота тут ціль шляху, тому to work.', 'Out of means from inside to outside. Here: to work.'),
      },
      retry: [
        tri('Спроси: куда идёт стрелка?', 'Спитай: куди йде стрілка?', 'Ask: where does the arrow go?'),
        tri('К месту = to.', 'До місця = to.', 'To a place = to.'),
        tri('Готовый кусок: to work.', 'Готовий зворот: to work.', 'Ready block: to work.'),
      ],
      fallbackExplanation: tri('К месту или цели пути = to: go to work.', 'До місця або цілі шляху = to: go to work.', 'To a place or goal = to.'),
      focusWords: ['work'],
    }),
    directionStep({
      id: 'prep_dir_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'to_city_destination',
      teachingText: tri('Город может быть целью поездки. Если человек едет к этому месту, нужен to.', 'Місто може бути ціллю поїздки. Якщо людина їде до цього місця, потрібен to.', 'A city can be the destination. If you drive to it, use to.'),
      sentence: 'We drove ___ Dublin.',
      translation: tri('Мы поехали в Дублин.', 'Ми поїхали до Дубліна.', 'We drove to Dublin.'),
      options: ['to', 'from', 'into', 'in'],
      correctAnswer: 'to',
      correctFeedback: tri('Да. Dublin - цель поездки: to Dublin.', 'Так. Dublin - ціль поїздки: to Dublin.', 'Yes. Dublin is the destination: to Dublin.'),
      wrong: {
        from: tri('From было бы “из Дублина”. Здесь направление в Дублин: to Dublin.', 'From було б “з Дубліна”. Тут напрям до Дубліна: to Dublin.', 'From would be from Dublin. Here: to Dublin.'),
        into: tri('Into подчёркивает вход внутрь контейнера. Для поездки в город как цель пути обычно нужен to Dublin.', 'Into підкреслює вхід усередину контейнера. Для поїздки до міста як цілі шляху зазвичай потрібен to Dublin.', 'Into stresses entering inside. For destination: to Dublin.'),
        in: tri('In показывает “уже в Дублине”. Но drove говорит о движении к городу: to Dublin.', 'In показує “уже в Дубліні”. Але drove каже про рух до міста: to Dublin.', 'In means already in Dublin. Movement to the city: to Dublin.'),
      },
      retry: [
        tri('Drove показывает движение.', 'Drove показує рух.', 'Drove shows movement.'),
        tri('Цель поездки = to.', 'Ціль поїздки = to.', 'Destination = to.'),
        tri('Готовый кусок: to Dublin.', 'Готовий зворот: to Dublin.', 'Ready block: to Dublin.'),
      ],
      fallbackExplanation: tri('Ехать в город как к цели пути = drive to Dublin.', 'Їхати до міста як до цілі шляху = drive to Dublin.', 'Drive to a city as destination = to Dublin.'),
      focusWords: ['Dublin'],
    }),
    directionStep({
      id: 'prep_dir_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'to_recipient',
      teachingText: tri('To может вести не только к месту, но и к человеку, который получает вещь.', 'To може вести не тільки до місця, а й до людини, яка отримує річ.', 'To can point not only to a place, but also to the person receiving something.'),
      sentence: 'Send it ___ me.',
      translation: tri('Отправь это мне.', 'Надішли це мені.', 'Send it to me.'),
      options: ['to', 'for', 'from', 'into'],
      correctAnswer: 'to',
      correctFeedback: tri('Да. Me - получатель: to me.', 'Так. Me - отримувач: to me.', 'Yes. Me is the receiver: to me.'),
      wrong: {
        for: tri('For может значить “для меня”, но send обычно просит направление к получателю: send it to me.', 'For може означати “для мене”, але send зазвичай просить напрям до отримувача: send it to me.', 'For can mean for me, but send needs direction to the receiver: to me.'),
        from: tri('From значит “от меня”. Здесь нужно “мне”, к получателю: to me.', 'From означає “від мене”. Тут потрібно “мені”, до отримувача: to me.', 'From means from me. Here: to me.'),
        into: tri('Into значит внутрь чего-то. Человек не контейнер для этой фразы. Нужен to me.', 'Into означає всередину чогось. Людина не контейнер для цієї фрази. Потрібен to me.', 'Into means inside something. Here: to me.'),
      },
      retry: [
        tri('Кто получает?', 'Хто отримує?', 'Who receives it?'),
        tri('Получатель = to.', 'Отримувач = to.', 'Receiver = to.'),
        tri('Готовый кусок: to me.', 'Готовий зворот: to me.', 'Ready block: to me.'),
      ],
      fallbackExplanation: tri('После send человек-получатель часто идёт с to: send it to me.', 'Після send людина-отримувач часто йде з to: send it to me.', 'With send, receiver often uses to.'),
      focusWords: ['me'],
    }),
    directionStep({
      id: 'prep_dir_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'into_room',
      teachingText: tri('Если человек не просто идёт к комнате, а входит внутрь, нужен into.', 'Якщо людина не просто йде до кімнати, а входить усередину, потрібен into.', 'If someone enters inside, use into.'),
      sentence: 'She walked ___ the room.',
      translation: tri('Она вошла в комнату.', 'Вона увійшла в кімнату.', 'She walked into the room.'),
      options: ['into', 'to', 'in', 'from'],
      correctAnswer: 'into',
      correctFeedback: tri('Да. Стрелка входит внутрь комнаты: into the room.', 'Так. Стрілка входить усередину кімнати: into the room.', 'Yes. The arrow goes inside: into the room.'),
      wrong: {
        to: tri('To говорит “к комнате” как к цели. Но здесь она вошла внутрь, поэтому into the room.', 'To каже “до кімнати” як до цілі. Але тут вона увійшла всередину, тому into the room.', 'To means to the room. Here she enters inside: into the room.'),
        in: tri('In обычно показывает, что человек уже внутри: I am in the room. Но walked показывает вход внутрь, поэтому into.', 'In зазвичай показує, що людина вже всередині: I am in the room. Але walked показує вхід усередину, тому into.', 'In means already inside: I am in the room. Walked inside = into.'),
        from: tri('From значит “из/откуда”. Здесь движение внутрь комнаты: into the room.', 'From означає “з/звідки”. Тут рух усередину кімнати: into the room.', 'From means from where. Here: into the room.'),
      },
      retry: [
        tri('Есть вход внутрь?', 'Є вхід усередину?', 'Is there movement inside?'),
        tri('Внутрь = into.', 'Всередину = into.', 'Inside movement = into.'),
        tri('Готовый кусок: into the room.', 'Готовий зворот: into the room.', 'Ready block: into the room.'),
      ],
      fallbackExplanation: tri('Войти внутрь комнаты = go/walk into the room.', 'Увійти всередину кімнати = go/walk into the room.', 'Enter inside = into the room.'),
      focusWords: ['the room'],
    }),
    directionStep({
      id: 'prep_dir_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'into_bag',
      teachingText: tri('Если предмет перемещают внутрь сумки или коробки, нужен into.', 'Якщо предмет переміщують усередину сумки або коробки, потрібен into.', 'If you move something inside a bag or box, use into.'),
      sentence: 'Put the keys ___ the bag.',
      translation: tri('Положи ключи в сумку.', 'Поклади ключі в сумку.', 'Put the keys into the bag.'),
      options: ['into', 'in', 'to', 'out of'],
      correctAnswer: 'into',
      correctFeedback: tri('Да. Ключи движутся внутрь сумки: into the bag.', 'Так. Ключі рухаються всередину сумки: into the bag.', 'Yes. The keys move inside: into the bag.'),
      wrong: {
        in: tri('In может описать, что ключи уже внутри. Но put показывает движение внутрь, поэтому into the bag.', 'In може описати, що ключі вже всередині. Але put показує рух усередину, тому into the bag.', 'In can mean already inside. Put shows movement inside: into the bag.'),
        to: tri('To ведёт к месту, но не показывает вход внутрь сумки. Здесь нужно into.', 'To веде до місця, але не показує вхід усередину сумки. Тут потрібно into.', 'To points to a place, but not inside. Here: into.'),
        'out of': tri('Out of - наоборот: изнутри наружу. Здесь ключи идут внутрь: into the bag.', 'Out of - навпаки: зсередини назовні. Тут ключі йдуть усередину: into the bag.', 'Out of is the opposite. Here: into the bag.'),
      },
      retry: [
        tri('Ключи куда движутся?', 'Ключі куди рухаються?', 'Where do the keys move?'),
        tri('Внутрь сумки = into.', 'Всередину сумки = into.', 'Inside the bag = into.'),
        tri('Готовый кусок: into the bag.', 'Готовий зворот: into the bag.', 'Ready block: into the bag.'),
      ],
      fallbackExplanation: tri('Положить внутрь = put into.', 'Покласти всередину = put into.', 'Put inside = put into.'),
      focusWords: ['the bag'],
    }),
    directionStep({
      id: 'prep_dir_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'in_vs_into_room',
      teachingText: tri('Здесь важно разделить “уже внутри” и “вошёл внутрь”. In - уже внутри. Into - движение внутрь.', 'Тут важливо розділити “уже всередині” і “увійшов усередину”. In - уже всередині. Into - рух усередину.', 'Separate already inside and movement inside. In = already inside. Into = movement inside.'),
      sentence: 'I went ___ the room.',
      translation: tri('Я вошёл в комнату.', 'Я увійшов у кімнату.', 'I went into the room.'),
      options: ['into', 'in', 'to', 'from'],
      correctAnswer: 'into',
      correctFeedback: tri('Да. Went показывает движение внутрь: into the room.', 'Так. Went показує рух усередину: into the room.', 'Yes. Went shows movement inside: into the room.'),
      wrong: {
        in: tri('In - это когда человек уже внутри: I am in the room. Но здесь went: человек вошёл внутрь, поэтому into.', 'In - це коли людина вже всередині: I am in the room. Але тут went: людина увійшла всередину, тому into.', 'In = already inside: I am in the room. But went inside = into.'),
        to: tri('To the room значит к комнате как к точке. Но “вошёл в комнату” подчёркивает вход внутрь: into the room.', 'To the room означає до кімнати як до точки. Але “увійшов у кімнату” підкреслює вхід усередину: into the room.', 'To the room means toward it. Entered inside = into the room.'),
        from: tri('From the room значит из комнаты. Здесь движение в комнату внутрь: into the room.', 'From the room означає з кімнати. Тут рух у кімнату всередину: into the room.', 'From the room means out from it. Here: into the room.'),
      },
      retry: [
        tri('Went - есть движение.', 'Went - є рух.', 'Went shows movement.'),
        tri('Движение внутрь = into.', 'Рух усередину = into.', 'Movement inside = into.'),
        tri('Сравни состояние и движение: уже внутри комнаты или входишь внутрь.', 'Порівняй стан і рух: уже всередині кімнати чи заходиш усередину.', 'Compare: I am in the room / I went into the room.'),
      ],
      fallbackExplanation: tri('I am in the room - уже внутри. I went into the room - вошёл внутрь.', 'I am in the room - уже всередині. I went into the room - увійшов усередину.', 'In = already inside. Into = movement inside.'),
      focusWords: ['the room'],
    }),
    directionStep({
      id: 'prep_dir_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'from_work',
      teachingText: tri('From отвечает на вопрос “откуда?”. Если человек пришёл с работы, работа - точка старта.', 'From відповідає на питання “звідки?”. Якщо людина прийшла з роботи, робота - точка старту.', 'From answers “from where?”. Work is the starting point.'),
      sentence: 'He came ___ work late.',
      translation: tri('Он пришёл с работы поздно.', 'Він прийшов з роботи пізно.', 'He came from work late.'),
      options: ['from', 'to', 'into', 'out of'],
      correctAnswer: 'from',
      correctFeedback: tri('Да. Откуда пришёл? From work.', 'Так. Звідки прийшов? From work.', 'Yes. From where? From work.'),
      wrong: {
        to: tri('To work = на работу. Но он пришёл с работы, поэтому from work.', 'To work = на роботу. Але він прийшов з роботи, тому from work.', 'To work = to work. Here he came from work.'),
        into: tri('Into work звучит как вход внутрь работы. Здесь вопрос “откуда?” - from work.', 'Into work звучить як вхід усередину роботи. Тут питання “звідки?” - from work.', 'Into means inside. Here: from where? from work.'),
        'out of': tri('Out of подчёркивает выход изнутри. Для обычного “с работы” нужен from work.', 'Out of підкреслює вихід зсередини. Для звичного “з роботи” потрібен from work.', 'Out of stresses exit from inside. Normal block: from work.'),
      },
      retry: [
        tri('Спроси: откуда?', 'Спитай: звідки?', 'Ask: from where?'),
        tri('Откуда = from.', 'Звідки = from.', 'From where = from.'),
        tri('Готовый кусок: from work.', 'Готовий зворот: from work.', 'Ready block: from work.'),
      ],
      fallbackExplanation: tri('С работы = from work.', 'З роботи = from work.', 'From work = from work.'),
      focusWords: ['work'],
    }),
    directionStep({
      id: 'prep_dir_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'from_country',
      teachingText: tri('From также показывает происхождение: откуда человек или вещь.', 'From також показує походження: звідки людина або річ.', 'From can also show origin: where someone or something is from.'),
      sentence: 'She is ___ Ukraine.',
      translation: tri('Она из Украины.', 'Вона з України.', 'She is from Ukraine.'),
      options: ['from', 'in', 'to', 'out of'],
      correctAnswer: 'from',
      correctFeedback: tri('Да. Откуда она? From Ukraine.', 'Так. Звідки вона? From Ukraine.', 'Yes. Where is she from? From Ukraine.'),
      wrong: {
        in: tri('In Ukraine значит “в Украине сейчас”. Но “она из Украины” = from Ukraine.', 'In Ukraine означає “в Україні зараз”. Але “вона з України” = from Ukraine.', 'In Ukraine means located there now. Origin = from Ukraine.'),
        to: tri('To Ukraine - движение в Украину. Здесь происхождение: from Ukraine.', 'To Ukraine - рух до України. Тут походження: from Ukraine.', 'To Ukraine is movement to Ukraine. Origin = from Ukraine.'),
        'out of': tri('Out of звучит как выход изнутри. Для страны как происхождения нужен from Ukraine.', 'Out of звучить як вихід зсередини. Для країни як походження потрібен from Ukraine.', 'Out of sounds like exiting from inside. Origin = from Ukraine.'),
      },
      retry: [
        tri('Вопрос: откуда она?', 'Питання: звідки вона?', 'Question: where is she from?'),
        tri('Происхождение = from.', 'Походження = from.', 'Origin = from.'),
        tri('Готовый кусок: from Ukraine.', 'Готовий зворот: from Ukraine.', 'Ready block: from Ukraine.'),
      ],
      fallbackExplanation: tri('Из страны / откуда родом = from.', 'З країни / звідки родом = from.', 'Country of origin = from.'),
      focusWords: ['Ukraine'],
    }),
    directionStep({
      id: 'prep_dir_contrast_006',
      order: 9,
      difficulty: 'contrast',
      targetSkill: 'from_person_source',
      teachingText: tri('From может показывать источник: от кого пришла вещь или сообщение.', 'From може показувати джерело: від кого прийшла річ або повідомлення.', 'From can show the source: who something came from.'),
      sentence: 'I got a message ___ my friend.',
      translation: tri('Я получил сообщение от друга.', 'Я отримав повідомлення від друга.', 'I got a message from my friend.'),
      options: ['from', 'to', 'into', 'for'],
      correctAnswer: 'from',
      correctFeedback: tri('Да. Сообщение пришло от друга: from my friend.', 'Так. Повідомлення прийшло від друга: from my friend.', 'Yes. The message came from your friend.'),
      wrong: {
        to: tri('To my friend значило бы “моему другу”. Но сообщение пришло от друга: from my friend.', 'To my friend означало б “моєму другу”. Але повідомлення прийшло від друга: from my friend.', 'To my friend means to your friend. Here: from my friend.'),
        into: tri('Into показывает движение внутрь. Человек здесь источник сообщения, поэтому from.', 'Into показує рух усередину. Людина тут джерело повідомлення, тому from.', 'Into is movement inside. Here the person is the source: from.'),
        for: tri('For my friend значило бы “для друга”. Но сообщение пришло от него: from my friend.', 'For my friend означало б “для друга”. Але повідомлення прийшло від нього: from my friend.', 'For my friend means for the friend. Here: from my friend.'),
      },
      retry: [
        tri('От кого пришло сообщение?', 'Від кого прийшло повідомлення?', 'Who did it come from?'),
        tri('Источник = from.', 'Джерело = from.', 'Source = from.'),
        tri('Готовый кусок: from my friend.', 'Готовий зворот: from my friend.', 'Ready block: from my friend.'),
      ],
      fallbackExplanation: tri('От человека-источника = from: from my friend.', 'Від людини-джерела = from: from my friend.', 'Source person = from.'),
      focusWords: ['my friend'],
    }),
    directionStep({
      id: 'prep_dir_mixed_001',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'out_of_car',
      teachingText: tri('Out of нужен, когда кто-то был внутри и выходит наружу.', 'Out of потрібен, коли хтось був усередині й виходить назовні.', 'Use out of when someone was inside and moves outside.'),
      sentence: 'Get ___ the car.',
      translation: tri('Выйди из машины.', 'Вийди з машини.', 'Get out of the car.'),
      options: ['out of', 'into', 'from', 'to'],
      correctAnswer: 'out of',
      correctFeedback: tri('Да. Изнутри машины наружу: out of the car.', 'Так. Зсередини машини назовні: out of the car.', 'Yes. From inside the car to outside: out of the car.'),
      wrong: {
        into: tri('Into - наоборот: внутрь машины. Здесь нужно выйти наружу, поэтому out of the car.', 'Into - навпаки: всередину машини. Тут треба вийти назовні, тому out of the car.', 'Into is the opposite: inside the car. Here: out of the car.'),
        from: tri('From показывает “откуда”, но для выхода изнутри машины естественный блок: out of the car.', 'From показує “звідки”, але для виходу зсередини машини природний зворот: out of the car.', 'From shows from where, but exiting inside-to-outside is out of the car.'),
        to: tri('To показывает движение к месту. Здесь движение изнутри наружу: out of the car.', 'To показує рух до місця. Тут рух зсередини назовні: out of the car.', 'To means to a place. Here: out of the car.'),
      },
      retry: [
        tri('Человек был внутри машины?', 'Людина була всередині машини?', 'Was the person inside the car?'),
        tri('Изнутри наружу = out of.', 'Зсередини назовні = out of.', 'From inside to outside = out of.'),
        tri('Готовый кусок: out of the car.', 'Готовий зворот: out of the car.', 'Ready block: out of the car.'),
      ],
      fallbackExplanation: tri('Выйти из машины = get out of the car.', 'Вийти з машини = get out of the car.', 'Exit a car = get out of the car.'),
      focusWords: ['the car'],
    }),
    directionStep({
      id: 'prep_dir_mixed_002',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'out_of_bag',
      teachingText: tri('Если предмет был внутри сумки и ты достаёшь его наружу, нужен out of.', 'Якщо предмет був усередині сумки і ти дістаєш його назовні, потрібен out of.', 'If something was inside a bag and you take it outside, use out of.'),
      sentence: 'Take the phone ___ the bag.',
      translation: tri('Достань телефон из сумки.', 'Дістань телефон із сумки.', 'Take the phone out of the bag.'),
      options: ['out of', 'from', 'into', 'in'],
      correctAnswer: 'out of',
      correctFeedback: tri('Да. Телефон идёт изнутри сумки наружу: out of the bag.', 'Так. Телефон іде зсередини сумки назовні: out of the bag.', 'Yes. From inside the bag to outside: out of the bag.'),
      wrong: {
        from: tri('From показывает источник, но здесь важен выход изнутри сумки. Лучше: out of the bag.', 'From показує джерело, але тут важливий вихід зсередини сумки. Краще: out of the bag.', 'From shows source, but here the movement is inside-to-outside: out of the bag.'),
        into: tri('Into - внутрь сумки. Здесь телефон достают наружу, поэтому out of.', 'Into - всередину сумки. Тут телефон дістають назовні, тому out of.', 'Into is inside the bag. Here: out of.'),
        in: tri('In показывает, что телефон уже внутри. Но take говорит о движении наружу: out of.', 'In показує, що телефон уже всередині. Але take каже про рух назовні: out of.', 'In means already inside. Take shows movement outside: out of.'),
      },
      retry: [
        tri('Телефон был внутри?', 'Телефон був усередині?', 'Was the phone inside?'),
        tri('Достаём наружу = out of.', 'Дістаємо назовні = out of.', 'Take outside = out of.'),
        tri('Готовый кусок: out of the bag.', 'Готовий зворот: out of the bag.', 'Ready block: out of the bag.'),
      ],
      fallbackExplanation: tri('Достать изнутри наружу = take out of.', 'Дістати зсередини назовні = take out of.', 'Take from inside to outside = take out of.'),
      focusWords: ['the bag'],
    }),
    directionStep({
      id: 'prep_dir_mixed_003',
      order: 12,
      difficulty: 'mixed_review',
      targetSkill: 'into_out_of_pair',
      teachingText: tri('Теперь сравни две стрелки: положить внутрь и достать наружу.', 'Тепер порівняй дві стрілки: покласти всередину і дістати назовні.', 'Now compare two arrows: put inside and take outside.'),
      sentence: 'Choose the correct pair.',
      translation: tri('положить в сумку / достать из сумки', 'покласти в сумку / дістати із сумки', 'put in the bag / take out of the bag'),
      options: ['put it into the bag / take it out of the bag', 'put it out of the bag / take it into the bag', 'put it from the bag / take it to the bag', 'put it in the bag / take it from the bag'],
      correctAnswer: 'put it into the bag / take it out of the bag',
      correctFeedback: tri('Да. Внутрь = into. Изнутри наружу = out of.', 'Так. Всередину = into. Зсередини назовні = out of.', 'Yes. Inside = into. From inside out = out of.'),
      wrong: {
        'put it out of the bag / take it into the bag': tri('Ты поменял стрелки местами. Положить внутрь = into. Достать наружу = out of.', 'Ти поміняв стрілки місцями. Покласти всередину = into. Дістати назовні = out of.', 'The arrows are reversed. Put inside = into. Take outside = out of.'),
        'put it from the bag / take it to the bag': tri('From/to не показывают вход внутрь и выход наружу. Нужна пара into / out of.', 'From/to не показують вхід усередину і вихід назовні. Потрібна пара into / out of.', 'From/to do not show inside/outside. Use into / out of.'),
        'put it in the bag / take it from the bag': tri('In может быть понятно, но здесь мы тренируем движение внутрь: into. Для “достать изнутри наружу” лучше out of.', 'In може бути зрозуміло, але тут ми тренуємо рух усередину: into. Для “дістати зсередини назовні” краще out of.', 'In can be understood, but movement inside is into. Taking outside is out of.'),
      },
      retry: [
        tri('Одна стрелка внутрь, другая наружу.', 'Одна стрілка всередину, друга назовні.', 'One arrow inside, one outside.'),
        tri('Внутрь = into. Наружу изнутри = out of.', 'Всередину = into. Назовні зсередини = out of.', 'Inside = into. Inside to outside = out of.'),
        tri('Готовая пара: into the bag / out of the bag.', 'Готова пара: into the bag / out of the bag.', 'Pair: into the bag / out of the bag.'),
      ],
      fallbackExplanation: tri('Не выбирай по одному русскому “в/из”. Нарисуй стрелку.', 'Не обирай за одним українським “в/з”. Намалюй стрілку.', 'Do not choose by one translation. Draw the arrow.'),
      focusWords: ['the bag'],
    }),
    directionStep({
      id: 'prep_dir_mixed_004',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_to_from',
      teachingText: tri('To и from работают как две противоположные стрелки: к месту и от места.', 'To і from працюють як дві протилежні стрілки: до місця і від місця.', 'To and from are opposite arrows: to a place and from a place.'),
      sentence: 'Choose the correct pair.',
      translation: tri('на работу / с работы', 'на роботу / з роботи', 'to work / from work'),
      options: ['go to work / come from work', 'go from work / come to work', 'go into work / come out of work', 'go out of work / come into work'],
      correctAnswer: 'go to work / come from work',
      correctFeedback: tri('Да. На работу = to work. С работы = from work.', 'Так. На роботу = to work. З роботи = from work.', 'Yes. To work / from work.'),
      wrong: {
        'go from work / come to work': tri('Ты поменял направления. На работу = to work. С работы = from work.', 'Ти поміняв напрями. На роботу = to work. З роботи = from work.', 'The directions are reversed. To work / from work.'),
        'go into work / come out of work': tri('Into/out of звучат как вход внутрь и выход наружу. Для обычного “на работу / с работы” нужна пара to/from.', 'Into/out of звучать як вхід усередину і вихід назовні. Для звичного “на роботу / з роботи” потрібна пара to/from.', 'Into/out of sound like entering/exiting. Normal pair: to/from.'),
        'go out of work / come into work': tri('Это меняет смысл. Базовая пара здесь: go to work / come from work.', 'Це змінює зміст. Базова пара тут: go to work / come from work.', 'This changes the meaning. Basic pair: go to work / come from work.'),
      },
      retry: [
        tri('Куда? На работу. Откуда? С работы.', 'Куди? На роботу. Звідки? З роботи.', 'Where to? To work. From where? From work.'),
        tri('Куда = to. Откуда = from.', 'Куди = to. Звідки = from.', 'To where = to. From where = from.'),
        tri('Готовая пара: go to work / come from work.', 'Готова пара: go to work / come from work.', 'Pair: go to work / come from work.'),
      ],
      fallbackExplanation: tri('To и from лучше видеть как две противоположные стрелки.', 'To і from краще бачити як дві протилежні стрілки.', 'See to/from as opposite arrows.'),
      focusWords: ['work'],
    }),
    directionStep({
      id: 'prep_dir_mixed_005',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_in_into',
      teachingText: tri('Финальная ловушка: in и into похожи, но одно говорит “уже внутри”, другое - “вошёл внутрь”.', 'Фінальна пастка: in і into схожі, але одне каже “уже всередині”, інше - “увійшов усередину”.', 'Final trap: in and into are close, but one means already inside and the other means movement inside.'),
      sentence: 'Choose the correct pair.',
      translation: tri('я в комнате / я вошёл в комнату', 'я в кімнаті / я увійшов у кімнату', 'I am in the room / I went into the room'),
      options: ['I am in the room / I went into the room', 'I am into the room / I went in the room', 'I am from the room / I went out of the room', 'I am to the room / I went from the room'],
      correctAnswer: 'I am in the room / I went into the room',
      correctFeedback: tri('Да. Где сейчас? In the room. Куда вошёл? Into the room.', 'Так. Де зараз? In the room. Куди увійшов? Into the room.', 'Yes. Already inside = in. Movement inside = into.'),
      wrong: {
        'I am into the room / I went in the room': tri('Для положения нужен in the room. Для входа внутрь нужен into the room.', 'Для положення потрібен in the room. Для входу всередину потрібен into the room.', 'Already inside = in the room. Movement inside = into the room.'),
        'I am from the room / I went out of the room': tri('Вторая часть говорит “вышел из комнаты”, а не “вошёл”. Нужна пара in the room / into the room.', 'Друга частина каже “вийшов із кімнати”, а не “увійшов”. Потрібна пара in the room / into the room.', 'Second part means went out, not entered. Use in the room / into the room.'),
        'I am to the room / I went from the room': tri('To/from не описывают эту пару. Нужно: уже внутри = in the room, вошёл внутрь = into the room.', 'To/from не описують цю пару. Потрібно: уже всередині = in the room, увійшов усередину = into the room.', 'To/from do not fit this pair. Use in the room / into the room.'),
      },
      retry: [
        tri('Где? И куда вошёл?', 'Де? І куди увійшов?', 'Where? And movement inside?'),
        tri('Где = in. Внутрь = into.', 'Де = in. Всередину = into.', 'Where = in. Inside movement = into.'),
        tri('Готовая пара: сначала состояние внутри, потом движение внутрь.', 'Готова пара: спочатку стан усередині, потім рух усередину.', 'Pair: I am in the room / I went into the room.'),
      ],
      fallbackExplanation: tri('In - уже внутри. Into - движение внутрь.', 'In - уже всередині. Into - рух усередину.', 'In = already inside. Into = movement inside.'),
      focusWords: ['the room'],
    }),
    directionStep({
      id: 'prep_dir_mixed_006',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_sentence_correction',
      teachingText: tri('Теперь собираем два движения в одной фразе: с работы и внутрь комнаты.', 'Тепер збираємо два рухи в одній фразі: з роботи і всередину кімнати.', 'Now combine two movements: from work and into the room.'),
      sentence: 'Choose the correct sentence.',
      translation: tri('Она пришла с работы и вошла в комнату.', 'Вона прийшла з роботи й увійшла в кімнату.', 'She came from work and went into the room.'),
      options: ['She came from work and went into the room.', 'She came to work and went from the room.', 'She came out of work and went to the room.', 'She came into work and went out of the room.'],
      correctAnswer: 'She came from work and went into the room.',
      correctFeedback: tri('Да. С работы = from work. Вошла внутрь комнаты = into the room.', 'Так. З роботи = from work. Увійшла всередину кімнати = into the room.', 'Yes. From work / into the room.'),
      wrong: {
        'She came to work and went from the room.': tri('Это обратное движение: пришла на работу и пошла из комнаты. Нужно: from work / into the room.', 'Це зворотний рух: прийшла на роботу і пішла з кімнати. Потрібно: from work / into the room.', 'This reverses the movement. Use from work / into the room.'),
        'She came out of work and went to the room.': tri('Out of work звучит как выход изнутри работы, а went to the room не показывает вход внутрь. Нужно: from work / into the room.', 'Out of work звучить як вихід зсередини роботи, а went to the room не показує вхід усередину. Потрібно: from work / into the room.', 'Out of work sounds like exiting from inside work, and went to the room does not show entering inside. Use from work / into the room.'),
        'She came into work and went out of the room.': tri('Это другой смысл: пришла на работу и вышла из комнаты. Здесь нужно “с работы” и “в комнату внутрь”: from work / into the room.', 'Це інший зміст: прийшла на роботу і вийшла з кімнати. Тут потрібно “з роботи” і “в кімнату всередину”: from work / into the room.', 'This is a different meaning. Needed: from work / into the room.'),
      },
      retry: [
        tri('Раздели на две стрелки.', 'Розділи на дві стрілки.', 'Split it into two arrows.'),
        tri('С работы = from work. Внутрь комнаты = into the room.', 'З роботи = from work. Усередину кімнати = into the room.', 'From work. Into the room.'),
        tri('Готовая фраза: пришла откуда-то и вошла внутрь комнаты.', 'Готова фраза: прийшла звідкись і зайшла всередину кімнати.', 'Ready sentence: She came from work and went into the room.'),
      ],
      fallbackExplanation: tri('В длинной фразе не угадывай. Разбей движение на куски: from work / into the room.', 'У довгій фразі не вгадуй. Розбий рух на звороти: from work / into the room.', 'Do not guess in a long sentence. Split into blocks: from work / into the room.'),
      focusWords: ['work', 'the room'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'to_into_confusion',
      'in_into_confusion',
      'from_out_of_confusion',
      'from_missing_source_error',
      'out_of_missing_inside_error',
      'to_recipient_error',
      'towards_to_confusion',
      'wrong_direction_preposition',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri('Сначала показываем стрелку движения.', 'Спочатку показуємо стрілку руху.', 'Primero mostramos la flecha de movimiento.'),
    depth2: tri('Потом уточняем: к месту, внутрь, откуда или наружу изнутри.', 'Потім уточнюємо: до місця, всередину, звідки або назовні зсередини.', 'Luego aclaramos: hacia un lugar, hacia dentro, desde donde o desde dentro hacia fuera.'),
    depth3: tri('Показываем готовые куски: to work, into the room, from work, out of the car.', 'Показуємо готові звороти: to work, into the room, from work, out of the car.', 'Mostramos bloques listos: to work, into the room, from work, out of the car.'),
    depth4: tri('Почти подсказка: называем нужную стрелку и просим выбрать маленькое слово.', 'Майже підказка: називаємо потрібну стрілку і просимо обрати маленьке слово.', 'Casi una pista: nombramos la flecha necesaria y pedimos elegir la palabra pequena.'),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri(
        'Стоп. Нарисуй стрелку: к месту = to, внутрь = into, откуда = from, изнутри наружу = out of. Если движения нет и кто-то уже внутри, часто нужен in.',
        'Стоп. Намалюй стрілку: до місця = to, всередину = into, звідки = from, зсередини назовні = out of. Якщо руху немає і хтось уже всередині, часто потрібен in.',
        'Alto. Dibuja la flecha: hacia un lugar = to, hacia dentro = into, desde donde = from, desde dentro hacia fuera = out of. Ya dentro = in.',
      ),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_direction_hint_then_retry',
      card: tri(
        'Подсказка покажет только стрелку движения. Маленькое слово ты выберешь сам.',
        'Підказка покаже тільки стрілку руху. Маленьке слово ти обереш сам.',
        'La pista muestra solo la flecha. Tu eliges la palabra pequena.',
      ),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri(
        'Переходим мягче: сначала выбираем маршрут, потом возвращаемся к фразе.',
        'Переходимо мʼякше: спочатку обираємо маршрут, потім повертаємося до фрази.',
        'Modo guiado: primero elige la ruta y luego vuelve a la frase.',
      ),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      { id: 'guided_prep_dir_001', prompt: tri('Go to work - стрелка к месту или внутрь контейнера?', 'Go to work - стрілка до місця чи всередину контейнера?', 'Go to work: hacia un lugar o hacia dentro de un contenedor?'), options: ['к месту', 'внутрь контейнера'], correctIndex: 0, thenReturnToExerciseId: 'prep_dir_easy_001' },
      { id: 'guided_prep_dir_002', prompt: tri('Walk into the room - движение внутрь или откуда-то?', 'Walk into the room - рух усередину чи звідкись?', 'Walk into the room: movimiento hacia dentro o desde algun lugar?'), options: ['внутрь', 'откуда-то'], correctIndex: 0, thenReturnToExerciseId: 'prep_dir_contrast_001' },
      { id: 'guided_prep_dir_003', prompt: tri('Come from work отвечает на “куда?” или “откуда?”', 'Come from work відповідає на “куди?” чи “звідки?”', 'Come from work responde a "hacia donde?" o "desde donde?"'), options: ['куда', 'откуда'], correctIndex: 1, thenReturnToExerciseId: 'prep_dir_contrast_004' },
      { id: 'guided_prep_dir_004', prompt: tri('Get out of the car - внутрь машины или изнутри наружу?', 'Get out of the car - всередину машини чи зсередини назовні?', 'Get out of the car: hacia dentro del coche o desde dentro hacia fuera?'), options: ['внутрь', 'изнутри наружу'], correctIndex: 1, thenReturnToExerciseId: 'prep_dir_mixed_001' },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'preposition',
    microDiagnosisId: 'preposition_direction_to_into_from',
    diagnosisLabel: tri('To / Into / From / Out of', 'To / Into / From / Out of', 'To / Into / From / Out of: movimiento'),
    contrastSet: CONTRAST,
    focusWords: ['to', 'into', 'from', 'out of', 'in', 'towards'],
    focusPatterns: [
      'to_destination',
      'to_city_destination',
      'to_recipient',
      'into_room',
      'into_bag',
      'in_vs_into',
      'from_work',
      'from_country',
      'from_person_source',
      'out_of_car',
      'out_of_bag',
      'into_out_of_pair',
      'mixed_to_from',
      'mixed_in_into',
      'mixed_sentence_correction',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyLevel: 2,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 3,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_preposition_direction_to_into_from_start',
    answer: 'diagnosis_training_preposition_direction_to_into_from_answer',
    mastery: 'diagnosis_training_preposition_direction_to_into_from_mastery',
    recovery: 'diagnosis_training_preposition_direction_to_into_from_recovery',
    onStart: 'diagnosis_training_started',
    onCorrect: 'diagnosis_training_answer_correct',
    onWrong: 'diagnosis_training_answer_wrong',
    onDepthIncrease: 'diagnosis_training_feedback_depth_increased',
    onGuidedMode: 'diagnosis_training_guided_mode_started',
    onMastery: 'diagnosis_training_mastered',
    onSmartTrainerOpen: 'diagnosis_training_smart_trainer_opened',
    payload: {
      category: 'preposition',
      microDiagnosisId: 'preposition_direction_to_into_from',
      contrastSet: ['to', 'into', 'from', 'out of', 'towards', 'in'],
      logExactToken: true,
      logMistakeType: true,
      logExerciseId: true,
      logAttemptCount: true,
      logFeedbackDepth: true,
      logMovementType: true,
      logPreposition: true,
    },
  },
  routing: {
    diagnosisTrainerRoute: '/problem_coach?category=preposition&microDiagnosisId=preposition_direction_to_into_from',
  },
  qualityChecklist: {
    hasStableId: true,
    hasCategory: true,
    hasMultilingualTitle: true,
    hasPlainDiagnosisText: true,
    hasMentalModel: true,
    hasContrastSet: true,
    hasAtLeastSixExamples: true,
    hasAtLeastTwelveExercises: true,
    hasEasyContrastMixedStructure: true,
    hasDistractorSpecificFeedback: true,
    hasRetryFeedbackLevels: true,
    hasGuidedModeForRepeatedMistakes: true,
    hasMasteryRules: true,
    hasSmartTrainerConfig: true,
    hasAnalyticsPayload: true,
    hasFallbackRoute: true,
  },
};
