import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

type PlannedTrainingLocale = 'pt-BR' | 'vi' | 'id' | 'tr' | 'pl';

const OBJECT_ORDER_NEEDS_REVIEW_PLANNED: Record<PlannedTrainingLocale, string> = {
  'pt-BR': 'needs-review: esta explicação sobre ordem de objeto ainda precisa de revisão para português do Brasil.',
  vi: 'needs-review: phần giải thích về thứ tự tân ngữ này vẫn cần được rà soát cho tiếng Việt.',
  id: 'needs-review: penjelasan urutan objek ini masih perlu ditinjau untuk bahasa Indonesia.',
  tr: 'needs-review: bu nesne sırası açıklaması Türkçe için hâlâ gözden geçirilmeli.',
  pl: 'needs-review: to objaśnienie szyku dopełnienia nadal wymaga przeglądu po polsku.',
};

const tri = (
  ru: string,
  uk: string,
  es = ru,
  planned: Partial<Record<PlannedTrainingLocale, string>> = {},
): TriText => {
  const copy: TriText = { ru, uk, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    copy[locale] = planned[locale] ?? OBJECT_ORDER_NEEDS_REVIEW_PLANNED[locale];
  }
  return copy;
};

const CONTRAST = [
  'verb + person + thing',
  'verb + thing + to + person',
  'verb + thing + for + person',
  'give it to me',
  'send it to her',
  'buy it for him',
];

const OBJECT_ORDER_SKILL_ES: Record<string, string> = {
  full_object_after_person: 'Con una cosa completa, la persona puede ir justo despues del verbo.',
  send_full_object: 'Con un objeto completo: send her the file.',
  show_full_object: 'Con un objeto completo: show me your phone.',
  object_to_person: 'Si primero va la cosa, despues usa to + persona.',
  give_it_to_me: 'Con it, usa el orden seguro: it to me.',
  send_it_to_her: 'Con it, usa send it to her, no send her it.',
  show_it_to_me: 'Con it, usa show it to me, no show me it.',
  buy_it_for_me: 'Con buy, la persona suele ir con for: buy it for me.',
  make_it_for_her: 'Con make, la persona suele ir con for: make it for her.',
  tell_me_truth_vs_it: 'Con la cosa completa puedes decir tell me the truth; con it usa tell it to me.',
  mixed_book_it: 'No mezcles los dos caminos: cosa completa y it usan patrones distintos.',
  mixed_to_for: 'Send suele llevar to; buy suele llevar for.',
  mixed_sentence_correction: 'Photo va completo con show me; it va antes de to her.',
};

function withEs(
  copy: TriText,
  es: string,
  planned: Partial<Record<PlannedTrainingLocale, string>> = OBJECT_ORDER_NEEDS_REVIEW_PLANNED,
): TriText {
  const next: TriText = { ...copy, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    if (!next[locale] || next[locale]?.startsWith('needs-review:')) {
      next[locale] = planned[locale] ?? OBJECT_ORDER_NEEDS_REVIEW_PLANNED[locale];
    }
  }
  return next;
}

function objectOrderEsFeedback(input: {
  targetSkill: string;
  correctAnswer: string;
  focusWords: string[];
}): string {
  const focus = input.focusWords.join(' / ');
  const hint = OBJECT_ORDER_SKILL_ES[input.targetSkill] ?? 'Decide si la cosa esta completa o si es it/them.';
  return `Usa "${input.correctAnswer}"${focus ? ` con ${focus}` : ''}. ${hint}`;
}

function orderStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  teachingText: TriText;
  sentence: string;
  translation: TriText;
  options: string[];
  correctAnswer: string;
  correctFeedback: TriText;
  wrong: Record<string, TriText>;
  retryFeedback: [TriText, TriText, TriText, TriText];
  fallbackExplanation: TriText;
  focusWords: string[];
}): DiagnosisTrainingStep {
  const correctIndex = input.options.findIndex((option) => option === input.correctAnswer);
  const esFeedback = objectOrderEsFeedback(input);

  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    teachingText: withEs(input.teachingText, esFeedback),
    translation: withEs(input.translation, esFeedback),
    explanationBlock: withEs(input.teachingText, esFeedback),
    microTask: tri(
      'Выбери порядок: кому и что. Особенно следи за it.',
      'Обери порядок: кому і що. Особливо стеж за it.',
      'Elige el orden: quien recibe y que se da. Vigila especialmente it.',
    ),
    sentence: input.sentence,
    answerOptions: input.options.map((text) => ({ id: text, text })),
    correctAnswerId: input.correctAnswer,
    correctIndex,
    correctFeedback: withEs(input.correctFeedback, esFeedback),
    wrongFeedbackByOption: Object.fromEntries(
      input.options
        .filter((option) => option !== input.correctAnswer)
        .map((option) => [option, withEs(input.wrong[option] ?? tri(
          `Почти. Здесь безопаснее порядок: ${input.correctAnswer}.`,
          `Майже. Тут безпечніший порядок: ${input.correctAnswer}.`,
          `Casi. El orden mas seguro es: ${input.correctAnswer}.`,
        ), esFeedback)]),
    ),
    retryFeedback: input.retryFeedback.map((item) => withEs(item, esFeedback)) as [TriText, TriText, TriText, TriText],
    fallbackExplanation: withEs(input.fallbackExplanation, esFeedback),
    focusWords: input.focusWords,
  };
}

const TWO_PATHS = tri(
  'Есть две нормальные дороги: Give me the book или Give the book to me. Но если вещь заменили на it, безопасная дорога почти всегда Give it to me.',
  'Є дві нормальні дороги: Give me the book або Give the book to me. Але якщо річ замінили на it, безпечна дорога майже завжди Give it to me.',
  'Hay dos caminos normales: Give me the book o Give the book to me. Pero con it, el camino mas seguro casi siempre es Give it to me.',
  {
    'pt-BR': 'Há dois caminhos normais: Give me the book ou Give the book to me. Mas, com it, o caminho mais seguro quase sempre é Give it to me.',
    vi: 'Có hai cách bình thường: Give me the book hoặc Give the book to me. Nhưng với it, cách an toàn nhất hầu như luôn là Give it to me.',
    id: 'Ada dua pola normal: Give me the book atau Give the book to me. Namun dengan it, pola yang paling aman hampir selalu Give it to me.',
    tr: 'İki normal yol var: Give me the book veya Give the book to me. Ama it ile en güvenli yol neredeyse her zaman Give it to me olur.',
    pl: 'Są dwie normalne drogi: Give me the book albo Give the book to me. Ale z it najbezpieczniejsza droga to prawie zawsze Give it to me.',
  },
);

export const OBJECT_ORDER_GIVE_ME_IT_TRAINING: DiagnosisTraining = {
  id: 'object_order_give_me_it',
  category: 'syntax',
  version: '1.0.0',
  status: 'active',
  priority: 30,
  supportedLocales: ['ru', 'uk', 'es'],
  title: tri(
    'Give me the book / Give it to me: порядок без каши',
    'Give me the book / Give it to me: порядок без каші',
    'Give me the book / Give it to me: orden claro',
    {
      'pt-BR': 'Give me the book / Give it to me: ordem sem confusão',
      vi: 'Give me the book / Give it to me: thứ tự rõ ràng',
      id: 'Give me the book / Give it to me: urutan yang jelas',
      tr: 'Give me the book / Give it to me: karışmadan sıra',
      pl: 'Give me the book / Give it to me: szyk bez chaosu',
    },
  ),
  shortTitle: tri(
    'Give it to me',
    'Give it to me',
    'Give it to me',
    {
      'pt-BR': 'Give it to me',
      vi: 'Give it to me',
      id: 'Give it to me',
      tr: 'Give it to me',
      pl: 'Give it to me',
    },
  ),
  shortDiagnosis: tri(
    'Ты смешиваешь два нормальных порядка и получаешь странные фразы вроде give me it.',
    'Ти змішуєш два нормальні порядки й отримуєш дивні фрази на кшталт give me it.',
    'Mezclas dos ordenes normales y terminas con frases raras como give me it.',
    {
      'pt-BR': 'Você mistura duas ordens normais e acaba com frases estranhas como give me it.',
      vi: 'Bạn trộn hai thứ tự bình thường và tạo ra các câu lạ như give me it.',
      id: 'Kamu mencampur dua urutan normal dan akhirnya membuat frasa aneh seperti give me it.',
      tr: 'İki normal sırayı karıştırıyorsun ve give me it gibi tuhaf ifadeler ortaya çıkıyor.',
      pl: 'Mieszasz dwa normalne szyki i dostajesz dziwne frazy typu give me it.',
    },
  ),
  diagnosisText: tri(
    'Похоже, ты знаешь все слова, но ставишь "кому" и "что" в неудобном порядке. С полной вещью можно сказать Give me the book. Но с it лучше Give it to me. Это маленькое правило спасает give me it, send her it, buy me it.',
    'Схоже, ти знаєш усі слова, але ставиш "кому" і "що" в незручному порядку. З повною річчю можна сказати Give me the book. Але з it краще Give it to me. Це маленьке правило рятує give me it, send her it, buy me it.',
    'Sabes las palabras, pero colocas "a quien" y "que" en un orden incomodo. Con una cosa completa: Give me the book. Con it: Give it to me. Esta regla pequena evita give me it, send her it, buy me it.',
    {
      'pt-BR': 'Parece que você sabe todas as palavras, mas coloca "para quem" e "o quê" em uma ordem desconfortável. Com uma coisa completa, dá para dizer Give me the book. Com it, é melhor Give it to me. Essa pequena regra evita give me it, send her it, buy me it.',
      vi: 'Có vẻ bạn biết tất cả các từ, nhưng đặt "cho ai" và "cái gì" theo thứ tự không tự nhiên. Với đồ vật được nói đầy đủ, có thể nói Give me the book. Với it, tốt hơn là Give it to me. Quy tắc nhỏ này giúp tránh give me it, send her it, buy me it.',
      id: 'Sepertinya kamu tahu semua katanya, tetapi menaruh "kepada siapa" dan "apa" dalam urutan yang kurang nyaman. Dengan benda lengkap, kamu bisa mengatakan Give me the book. Dengan it, lebih baik Give it to me. Aturan kecil ini mencegah give me it, send her it, buy me it.',
      tr: 'Tüm kelimeleri biliyorsun gibi, ama "kime" ve "neyi" kısmını rahat olmayan bir sıraya koyuyorsun. Tam nesneyle Give me the book denebilir. Ama it ile Give it to me daha iyidir. Bu küçük kural give me it, send her it, buy me it hatalarını önler.',
      pl: 'Wygląda na to, że znasz wszystkie słowa, ale ustawiasz "komu" i "co" w niewygodnym szyku. Przy pełnej nazwie rzeczy można powiedzieć Give me the book. Z it lepiej Give it to me. Ta mała reguła chroni przed give me it, send her it, buy me it.',
    },
  ),
  mentalModel: tri(
    'Сначала реши, что за вещь в конце. Если она названа полностью: give me the book, send her the file, show me your phone. Если это it или them: give it to me, send it to her, show it to me. Для buy/make чаще нужен for: buy it for me.',
    'Спочатку виріши, що за річ у кінці. Якщо вона названа повністю: give me the book, send her the file, show me your phone. Якщо це it або them: give it to me, send it to her, show it to me. Для buy/make частіше потрібне for: buy it for me.',
    'Primero decide que tipo de cosa tienes. Si esta nombrada completa: give me the book, send her the file, show me your phone. Si es it o them: give it to me, send it to her, show it to me. Con buy/make suele ir for: buy it for me.',
    {
      'pt-BR': 'Primeiro decida que tipo de coisa está no final. Se ela está nomeada por completo: give me the book, send her the file, show me your phone. Se é it ou them: give it to me, send it to her, show it to me. Com buy/make, normalmente entra for: buy it for me.',
      vi: 'Trước hết hãy xác định vật ở cuối là gì. Nếu nó được gọi đầy đủ: give me the book, send her the file, show me your phone. Nếu đó là it hoặc them: give it to me, send it to her, show it to me. Với buy/make thường dùng for: buy it for me.',
      id: 'Pertama tentukan benda di akhir itu jenis apa. Jika disebut lengkap: give me the book, send her the file, show me your phone. Jika memakai it atau them: give it to me, send it to her, show it to me. Untuk buy/make, biasanya gunakan for: buy it for me.',
      tr: 'Önce sondaki şeyin ne olduğuna karar ver. Tam adı söylenmişse: give me the book, send her the file, show me your phone. it veya them ise: give it to me, send it to her, show it to me. buy/make ile çoğu zaman for gerekir: buy it for me.',
      pl: 'Najpierw zdecyduj, jaka rzecz jest na końcu. Jeśli jest nazwana w całości: give me the book, send her the file, show me your phone. Jeśli to it albo them: give it to me, send it to her, show it to me. Przy buy/make częściej potrzebne jest for: buy it for me.',
    },
  ),
  contrastSet: CONTRAST,
  coreRule: tri(
    'Если вещь названа полностью, можно поставить человека сразу после действия или после вещи с to. Если вещь заменена на it/them, безопаснее: сначала it/them, потом to или for и человек.',
    'Якщо річ названа повністю, можна поставити людину одразу після дії або після речі з to. Якщо річ замінена на it/them, безпечніше: спочатку it/them, потім to або for і людина.',
    'Give me the book = Give the book to me. Con it/them: Give it to me, Send it to her. Buy it for me.',
    {
      'pt-BR': 'Se a coisa está nomeada por completo, a pessoa pode vir logo depois da ação ou depois da coisa com to. Se a coisa virou it/them, é mais seguro: primeiro it/them, depois to ou for e a pessoa.',
      vi: 'Nếu đồ vật được gọi đầy đủ, người nhận có thể đứng ngay sau hành động hoặc sau đồ vật với to. Nếu đồ vật được thay bằng it/them, an toàn hơn là: it/them trước, rồi to hoặc for và người nhận.',
      id: 'Jika bendanya disebut lengkap, orangnya bisa langsung setelah tindakan atau setelah benda dengan to. Jika bendanya diganti dengan it/them, lebih aman: it/them dulu, lalu to atau for dan orangnya.',
      tr: 'Şey tam adıyla söylenmişse, kişi eylemden hemen sonra ya da şeyden sonra to ile gelebilir. Şey it/them olduysa daha güvenlisi: önce it/them, sonra to veya for ve kişi.',
      pl: 'Jeśli rzecz jest nazwana w całości, osobę można postawić zaraz po czynności albo po rzeczy z to. Jeśli rzecz zastępuje it/them, bezpieczniej: najpierw it/them, potem to albo for i osoba.',
    },
  ),
  whatUserMustLearn: {
    ru: [
      'Если вещь названа полностью, можно поставить человека сразу после действия: Give me the book.',
      'Можно и наоборот: Give the book to me.',
      'Если вещь заменили на it или them, безопаснее ставить её сразу после действия: Give it to me.',
      'То же самое с send: Send her the file, но Send it to her.',
      'То же самое с show: Show me your phone, но Show it to me.',
      'Для give/send/show/tell человеку обычно помогает to: give it to me, send it to her.',
      'Для buy/make/get человеку обычно помогает for: buy it for me, make it for her.',
      'Не смешивай две дороги: Give to me the book и Give me it звучат плохо для стандартной учебной фразы.',
    ],
    uk: [
      'Якщо річ названа повністю, можна поставити людину одразу після дії: Give me the book.',
      'Можна і навпаки: Give the book to me.',
      'Якщо річ замінили на it або them, безпечніше ставити її одразу після дії: Give it to me.',
      'Так само з send: Send her the file, але Send it to her.',
      'Так само з show: Show me your phone, але Show it to me.',
      'Для give/send/show/tell людині зазвичай допомагає to: give it to me, send it to her.',
      'Для buy/make/get людині зазвичай допомагає for: buy it for me, make it for her.',
      'Не змішуй дві дороги: Give to me the book і Give me it звучать погано для стандартної навчальної фрази.',
    ],
    es: [
      'Si la cosa esta nombrada completa, la persona puede ir justo despues del verbo: Give me the book.',
      'Tambien puedes invertirlo: Give the book to me.',
      'Si la cosa se cambia por it o them, es mas seguro ponerla justo despues del verbo: Give it to me.',
      'Lo mismo con send: Send her the file, pero Send it to her.',
      'Lo mismo con show: Show me your phone, pero Show it to me.',
      'Con give/send/show/tell, la persona suele ir con to: give it to me, send it to her.',
      'Con buy/make/get, la persona suele ir con for: buy it for me, make it for her.',
      'No mezcles los dos caminos: Give to me the book y Give me it suenan mal en la frase estandar de aprendizaje.',
    ],
    'pt-BR': [
      'Coisa completa: Give me the book.',
      'Também é possível: Give the book to me.',
      'Com it/them, use Give it to me.',
      'Send her the file, mas Send it to her.',
      'Show me your phone, mas Show it to me.',
      'Give/send/show/tell muitas vezes usam to.',
      'Buy/make/get muitas vezes usam for.',
      'Não misture os dois caminhos.',
    ],
    vi: [
      'Đồ vật được nói đầy đủ: Give me the book.',
      'Cũng có thể nói: Give the book to me.',
      'Với it/them, dùng Give it to me.',
      'Send her the file, nhưng Send it to her.',
      'Show me your phone, nhưng Show it to me.',
      'Give/send/show/tell thường dùng to.',
      'Buy/make/get thường dùng for.',
      'Đừng trộn hai cách.',
    ],
    id: [
      'Benda lengkap: Give me the book.',
      'Juga bisa: Give the book to me.',
      'Dengan it/them, gunakan Give it to me.',
      'Send her the file, tetapi Send it to her.',
      'Show me your phone, tetapi Show it to me.',
      'Give/send/show/tell sering memakai to.',
      'Buy/make/get sering memakai for.',
      'Jangan campur dua pola itu.',
    ],
    tr: [
      'Tam adlandırılmış şey: Give me the book.',
      'Şu da mümkün: Give the book to me.',
      'It/them ile Give it to me kullan.',
      'Send her the file, ama Send it to her.',
      'Show me your phone, ama Show it to me.',
      'Give/send/show/tell çoğu zaman to kullanır.',
      'Buy/make/get çoğu zaman for kullanır.',
      'İki yolu karıştırma.',
    ],
    pl: [
      'Pełna nazwa rzeczy: Give me the book.',
      'Możliwe też: Give the book to me.',
      'Z it/them używaj Give it to me.',
      'Send her the file, ale Send it to her.',
      'Show me your phone, ale Show it to me.',
      'Give/send/show/tell często używają to.',
      'Buy/make/get często używają for.',
      'Nie mieszaj tych dwóch ścieżek.',
    ],
  },
  examples: [
    {
      en: 'Give me the book.',
      ru: 'Дай мне книгу.',
      uk: 'Дай мені книжку.',
      es: 'Dame el libro.',
      'pt-BR': 'Me dê o livro.',
      vi: 'Đưa cho tôi quyển sách.',
      id: 'Berikan buku itu kepada saya.',
      tr: 'Kitabı bana ver.',
      pl: 'Daj mi książkę.',
      why: tri('Книга названа полностью, поэтому человек может идти сразу после give.', 'Книжка названа повністю, тому людина може йти одразу після give.', 'El libro esta nombrado completo, asi que la persona puede ir justo despues de give.'),
    },
    {
      en: 'Give the book to me.',
      ru: 'Дай книгу мне.',
      uk: 'Дай книжку мені.',
      es: 'Dame el libro a mi.',
      'pt-BR': 'Dê o livro para mim.',
      vi: 'Đưa quyển sách cho tôi.',
      id: 'Berikan buku itu kepada saya.',
      tr: 'Kitabı bana ver.',
      pl: 'Daj mi książkę.',
      why: tri('Это вторая нормальная дорога: сначала вещь, потом to me.', 'Це друга нормальна дорога: спочатку річ, потім to me.', 'Segundo camino normal: primero la cosa, despues to me.'),
    },
    {
      en: 'Give it to me.',
      ru: 'Дай это мне.',
      uk: 'Дай це мені.',
      es: 'Damelo.',
      'pt-BR': 'Dê isso para mim.',
      vi: 'Đưa nó cho tôi.',
      id: 'Berikan itu kepada saya.',
      tr: 'Onu bana ver.',
      pl: 'Daj mi to.',
      why: tri('С it безопасный порядок: it to me, не me it.', 'З it безпечний порядок: it to me, не me it.', 'Con it, usa it to me, no me it.'),
    },
    {
      en: 'Send her the file.',
      ru: 'Отправь ей файл.',
      uk: 'Надішли їй файл.',
      es: 'Enviale el archivo.',
      'pt-BR': 'Envie o arquivo para ela.',
      vi: 'Gửi cho cô ấy tệp đó.',
      id: 'Kirimkan file itu kepadanya.',
      tr: 'Dosyayı ona gönder.',
      pl: 'Wyślij jej plik.',
      why: tri('Файл назван полностью, поэтому send her the file звучит нормально.', 'Файл названо повністю, тому send her the file звучить нормально.', 'El archivo esta nombrado completo, asi que send her the file suena natural.'),
    },
    {
      en: 'Send it to her.',
      ru: 'Отправь это ей.',
      uk: 'Надішли це їй.',
      es: 'Enviaselo a ella.',
      'pt-BR': 'Envie isso para ela.',
      vi: 'Gửi nó cho cô ấy.',
      id: 'Kirimkan itu kepadanya.',
      tr: 'Onu ona gönder.',
      pl: 'Wyślij jej to.',
      why: tri('С it лучше send it to her, не send her it.', 'З it краще send it to her, не send her it.', 'Con it, usa send it to her, no send her it.'),
    },
    {
      en: 'Show me your phone.',
      ru: 'Покажи мне свой телефон.',
      uk: 'Покажи мені свій телефон.',
      es: 'Muestrame tu telefono.',
      'pt-BR': 'Mostre-me seu telefone.',
      vi: 'Cho tôi xem điện thoại của bạn.',
      id: 'Tunjukkan ponselmu kepada saya.',
      tr: 'Telefonunu bana göster.',
      pl: 'Pokaż mi swój telefon.',
      why: tri('Your phone названо полностью: show me your phone.', 'Your phone названо повністю: show me your phone.', 'Your phone esta nombrado completo: show me your phone.'),
    },
    {
      en: 'Show it to me.',
      ru: 'Покажи это мне.',
      uk: 'Покажи це мені.',
      es: 'Muestramelo.',
      'pt-BR': 'Mostre isso para mim.',
      vi: 'Cho tôi xem nó.',
      id: 'Tunjukkan itu kepada saya.',
      tr: 'Onu bana göster.',
      pl: 'Pokaż mi to.',
      why: tri('С it безопаснее show it to me.', 'З it безпечніше show it to me.', 'Con it, es mas seguro show it to me.'),
    },
    {
      en: 'Buy it for me.',
      ru: 'Купи это для меня.',
      uk: 'Купи це для мене.',
      es: 'Compramelo.',
      'pt-BR': 'Compre isso para mim.',
      vi: 'Mua nó cho tôi.',
      id: 'Belikan itu untuk saya.',
      tr: 'Onu benim için satın al.',
      pl: 'Kup mi to.',
      why: tri('Buy часто показывает "для кого" через for: buy it for me.', 'Buy часто показує "для кого" через for: buy it for me.', 'Buy suele marcar "para quien" con for: buy it for me.'),
    },
  ],
  introBlocks: [
    {
      id: 'intro_problem',
      type: 'diagnosis',
      text: tri(
        'Похоже, ты иногда берёшь русскую логику "дай мне это" и переносишь её прямо в английский. Так появляется give me it. В английском с it лучше иначе: give it to me.',
        'Схоже, ти іноді береш українську логіку "дай мені це" і переносиш її прямо в англійську. Так зʼявляється give me it. В англійській з it краще інакше: give it to me.',
        'Puede que estes llevando el orden de tu idioma directamente al ingles. Asi aparece give me it. Con it, usa give it to me.',
      ),
    },
    {
      id: 'intro_rule',
      type: 'rule',
      text: TWO_PATHS,
    },
    {
      id: 'intro_warning',
      type: 'warning',
      text: tri(
        'Главная ловушка: Give me it. Для стандартной учебной фразы безопаснее Give it to me.',
        'Головна пастка: Give me it. Для стандартної навчальної фрази безпечніше Give it to me.',
        'Trampa principal: Give me it. En ingles estandar de aprendizaje, prefiere Give it to me.',
      ),
    },
  ],
  steps: [
    orderStep({
      id: 'object_order_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'give_person_thing',
      teachingText: TWO_PATHS,
      sentence: 'Give ___ the book.',
      translation: tri('Дай мне книгу.', 'Дай мені книжку.', 'Give me the book.'),
      options: ['me', 'to me', 'it', 'for me'],
      correctAnswer: 'me',
      correctFeedback: tri('Да. Книга названа полностью, поэтому можно: give me the book.', 'Так. Книжка названа повністю, тому можна: give me the book.', 'Yes. The book is named fully: give me the book.'),
      wrong: {
        'to me': tri('Give to me the book - не базовый порядок. Нормально: give me the book или give the book to me.', 'Give to me the book - не базовий порядок. Нормально: give me the book або give the book to me.', 'Give to me the book is not the basic order. Use give me the book or give the book to me.'),
        it: tri('Give it the book ломает смысл. Здесь нужен человек: me.', 'Give it the book ламає сенс. Тут потрібна людина: me.', 'Here you need the receiver: me.'),
        'for me': tri('С give для человека обычно нужен to, но в этой дороге проще: give me the book.', 'З give для людини зазвичай потрібне to, але в цій дорозі простіше: give me the book.', 'With give, use give me the book here.'),
      },
      retryFeedback: [
        tri('Кому дать?', 'Кому дати?', 'Who gets it?'),
        tri('Мне: me.', 'Мені: me.', 'Me.'),
        tri('Книга названа полностью: give me the book.', 'Книжка названа повністю: give me the book.', 'The book is named fully: give me the book.'),
        tri('Ответ: Give me the book.', 'Відповідь: Give me the book.', 'Answer: Give me the book.'),
      ],
      fallbackExplanation: tri('Полная вещь: give me the book.', 'Повна річ: give me the book.', 'Full thing: give me the book.'),
      focusWords: ['give', 'me', 'the book'],
    }),
    orderStep({
      id: 'object_order_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'send_person_thing',
      teachingText: TWO_PATHS,
      sentence: 'Send ___ the file.',
      translation: tri('Отправь ей файл.', 'Надішли їй файл.', 'Send her the file.'),
      options: ['her', 'to her', 'it', 'for her'],
      correctAnswer: 'her',
      correctFeedback: tri('Да. Файл назван полностью: send her the file.', 'Так. Файл названо повністю: send her the file.', 'Yes. The file is named fully: send her the file.'),
      wrong: {
        'to her': tri('Send to her the file - тяжёлый порядок. Нормально: send her the file или send the file to her.', 'Send to her the file - важкий порядок. Нормально: send her the file або send the file to her.', 'Use send her the file or send the file to her.'),
        it: tri('Send it the file не работает. Здесь нужен человек: her.', 'Send it the file не працює. Тут потрібна людина: her.', 'Here you need her.'),
        'for her': tri('Send обычно ведёт к человеку через to. Здесь нужна короткая дорога: send her the file.', 'Send зазвичай веде до людини через to. Тут потрібна коротка дорога: send her the file.', 'Send uses to for the receiver; here use send her the file.'),
      },
      retryFeedback: [
        tri('Кому отправить?', 'Кому надіслати?', 'Who receives it?'),
        tri('Ей: her.', 'Їй: her.', 'Her.'),
        tri('Файл назван полностью: send her the file.', 'Файл названо повністю: send her the file.', 'The file is named fully: send her the file.'),
        tri('Ответ: Send her the file.', 'Відповідь: Send her the file.', 'Answer: Send her the file.'),
      ],
      fallbackExplanation: tri('Полная вещь: send her the file.', 'Повна річ: send her the file.', 'Full thing: send her the file.'),
      focusWords: ['send', 'her', 'the file'],
    }),
    orderStep({
      id: 'object_order_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'show_person_thing',
      teachingText: TWO_PATHS,
      sentence: 'Show ___ your phone.',
      translation: tri('Покажи мне свой телефон.', 'Покажи мені свій телефон.', 'Show me your phone.'),
      options: ['me', 'to me', 'it', 'for me'],
      correctAnswer: 'me',
      correctFeedback: tri('Да. Телефон назван полностью: show me your phone.', 'Так. Телефон названо повністю: show me your phone.', 'Yes. Your phone is named fully: show me your phone.'),
      wrong: {
        'to me': tri('Такой порядок с to звучит тяжело. Либо ставь человека сразу после show, либо перенеси его в конец после вещи.', 'Такий порядок з to звучить важко. Або став людину одразу після show, або перенеси її в кінець після речі.', 'Use show me your phone or show your phone to me.'),
        it: tri('Show it your phone не работает. Здесь нужен человек: me.', 'Show it your phone не працює. Тут потрібна людина: me.', 'Here you need me.'),
        'for me': tri('Show обычно ведёт к человеку через to, не for. Здесь проще: show me your phone.', 'Show зазвичай веде до людини через to, не for. Тут простіше: show me your phone.', 'Show uses to, not for. Here use show me your phone.'),
      },
      retryFeedback: [
        tri('Кому показать?', 'Кому показати?', 'Who sees it?'),
        tri('Мне: me.', 'Мені: me.', 'Me.'),
        tri('Телефон назван полностью: show me your phone.', 'Телефон названо повністю: show me your phone.', 'The phone is named fully: show me your phone.'),
        tri('Ответ: Show me your phone.', 'Відповідь: Show me your phone.', 'Answer: Show me your phone.'),
      ],
      fallbackExplanation: tri('Полная вещь: show me your phone.', 'Повна річ: show me your phone.', 'Full thing: show me your phone.'),
      focusWords: ['show', 'me', 'your phone'],
    }),
    orderStep({
      id: 'object_order_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'give_thing_to_person',
      teachingText: TWO_PATHS,
      sentence: 'Give the book ___ me.',
      translation: tri('Дай книгу мне.', 'Дай книжку мені.', 'Give the book to me.'),
      options: ['to', 'for', 'at', 'into'],
      correctAnswer: 'to',
      correctFeedback: tri('Да. Если сначала вещь, потом человек: give the book to me.', 'Так. Якщо спочатку річ, потім людина: give the book to me.', 'Yes. Thing first, then person: give the book to me.'),
      wrong: {
        for: tri('Give обычно ведёт вещь к человеку через to: give the book to me.', 'Give зазвичай веде річ до людини через to: give the book to me.', 'Give uses to for the receiver: give the book to me.'),
        at: tri('Give the book at me не работает. Нужно to me.', 'Give the book at me не працює. Потрібно to me.', 'Use to me.'),
        into: tri('Into - внутрь. Здесь книга идёт человеку: to me.', 'Into - всередину. Тут книжка йде людині: to me.', 'Into means inside. Here use to me.'),
      },
      retryFeedback: [
        tri('Сначала вещь.', 'Спочатку річ.', 'Thing first.'),
        tri('Потом к человеку: to me.', 'Потім до людини: to me.', 'Then to the person: to me.'),
        tri('Готовый кусок: give the book to me.', 'Готовий зворот: give the book to me.', 'Ready chunk: give the book to me.'),
        tri('Ответ: Give the book to me.', 'Відповідь: Give the book to me.', 'Answer: Give the book to me.'),
      ],
      fallbackExplanation: tri('Вещь потом to + человек: give the book to me.', 'Річ потім to + людина: give the book to me.', 'Thing + to + person: give the book to me.'),
      focusWords: ['give', 'to me'],
    }),
    orderStep({
      id: 'object_order_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'send_thing_to_person',
      teachingText: TWO_PATHS,
      sentence: 'Send the file ___ her.',
      translation: tri('Отправь файл ей.', 'Надішли файл їй.', 'Send the file to her.'),
      options: ['to', 'for', 'at', 'from'],
      correctAnswer: 'to',
      correctFeedback: tri('Да. Файл идёт к ней: send the file to her.', 'Так. Файл іде до неї: send the file to her.', 'Yes. The file goes to her: send the file to her.'),
      wrong: {
        for: tri('Send обычно говорит, кому отправляем, через to: send the file to her.', 'Send зазвичай каже, кому надсилаємо, через to: send the file to her.', 'Send uses to for the receiver.'),
        at: tri('Send the file at her не работает. Нужен кусок to her.', 'Send the file at her не працює. Потрібен зворот to her.', 'Use to her.'),
        from: tri('From her значит от неё. Здесь файл отправляют ей: to her.', 'From her означає від неї. Тут файл надсилають їй: to her.', 'From her means from her. Here use to her.'),
      },
      retryFeedback: [
        tri('Файл идёт кому?', 'Файл іде кому?', 'Who receives the file?'),
        tri('Ей: to her.', 'Їй: to her.', 'To her.'),
        tri('Готовый кусок: send the file to her.', 'Готовий зворот: send the file to her.', 'Ready chunk: send the file to her.'),
        tri('Ответ: Send the file to her.', 'Відповідь: Send the file to her.', 'Answer: Send the file to her.'),
      ],
      fallbackExplanation: tri('Send + вещь + to her.', 'Send + річ + to her.', 'Send + thing + to her.'),
      focusWords: ['send', 'to her'],
    }),
    orderStep({
      id: 'object_order_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'show_thing_to_person',
      teachingText: TWO_PATHS,
      sentence: 'Show the photo ___ them.',
      translation: tri('Покажи фото им.', 'Покажи фото їм.', 'Show the photo to them.'),
      options: ['to', 'for', 'at', 'on'],
      correctAnswer: 'to',
      correctFeedback: tri('Да. Фото показывают им: show the photo to them.', 'Так. Фото показують їм: show the photo to them.', 'Yes. Show the photo to them.'),
      wrong: {
        for: tri('Show обычно ведёт к человеку через to: show the photo to them.', 'Show зазвичай веде до людини через to: show the photo to them.', 'Show uses to here.'),
        at: tri('Show the photo at them не работает. Нужен кусок to them.', 'Show the photo at them не працює. Потрібен зворот to them.', 'Use to them.'),
        on: tri('On не показывает, кому показываем. Нужен to.', 'On не показує, кому показуємо. Потрібен to.', 'Use to for the receiver.'),
      },
      retryFeedback: [
        tri('Фото показывают кому?', 'Фото показують кому?', 'Who sees the photo?'),
        tri('Им: to them.', 'Їм: to them.', 'To them.'),
        tri('Готовый кусок: show the photo to them.', 'Готовий зворот: show the photo to them.', 'Ready chunk: show the photo to them.'),
        tri('Ответ: Show the photo to them.', 'Відповідь: Show the photo to them.', 'Answer: Show the photo to them.'),
      ],
      fallbackExplanation: tri('Show + вещь + to them.', 'Show + річ + to them.', 'Show + thing + to them.'),
      focusWords: ['show', 'to them'],
    }),
    orderStep({
      id: 'object_order_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'give_it_to_me',
      teachingText: tri(
        'Вот главная ловушка. С it не ставим человека сразу после give. Безопасно: give it to me.',
        'Ось головна пастка. З it не ставимо людину одразу після give. Безпечно: give it to me.',
        'Main trap. With it, do not put the person right after give. Use give it to me.',
      ),
      sentence: 'Give ___.',
      translation: tri('Дай это мне.', 'Дай це мені.', 'Give it to me.'),
      options: ['it to me', 'me it', 'to me it', 'it for me'],
      correctAnswer: 'it to me',
      correctFeedback: tri('Да. С it безопасный порядок: give it to me.', 'Так. З it безпечний порядок: give it to me.', 'Yes. With it: give it to me.'),
      wrong: {
        'me it': tri('Give me it звучит плохо в стандартной учебной фразе. Безопаснее: give it to me.', 'Give me it звучить погано у стандартній навчальній фразі. Безпечніше: give it to me.', 'Give me it sounds awkward in standard learner English. Use give it to me.'),
        'to me it': tri('Give to me it ломает порядок. Нужен кусок give it to me.', 'Give to me it ламає порядок. Потрібен зворот give it to me.', 'Use give it to me.'),
        'it for me': tri('С give человеку обычно помогает to: give it to me.', 'З give людині зазвичай допомагає to: give it to me.', 'Give uses to here: give it to me.'),
      },
      retryFeedback: [
        tri('Вещь = it.', 'Річ = it.', 'Thing = it.'),
        tri('С it ставим: it to me.', 'З it ставимо: it to me.', 'With it: it to me.'),
        tri('Готовый кусок: give it to me.', 'Готовий зворот: give it to me.', 'Ready chunk: give it to me.'),
        tri('Ответ: Give it to me.', 'Відповідь: Give it to me.', 'Answer: Give it to me.'),
      ],
      fallbackExplanation: tri('С it: give it to me.', 'З it: give it to me.', 'With it: give it to me.'),
      focusWords: ['give it to me'],
    }),
    orderStep({
      id: 'object_order_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'send_it_to_her',
      teachingText: tri(
        'С send такая же ловушка: send her the file, но send it to her.',
        'З send така сама пастка: send her the file, але send it to her.',
        'Same trap with send: send her the file, but send it to her.',
      ),
      sentence: 'Send ___.',
      translation: tri('Отправь это ей.', 'Надішли це їй.', 'Send it to her.'),
      options: ['it to her', 'her it', 'to her it', 'it for her'],
      correctAnswer: 'it to her',
      correctFeedback: tri('Да. С it естественно: send it to her.', 'Так. З it природно: send it to her.', 'Yes. With it: send it to her.'),
      wrong: {
        'her it': tri('Send her it звучит плохо для стандартной учебной фразы. Лучше send it to her.', 'Send her it звучить погано для стандартної навчальної фрази. Краще send it to her.', 'Use send it to her.'),
        'to her it': tri('Send to her it ломает порядок. Нужен кусок send it to her.', 'Send to her it ламає порядок. Потрібен зворот send it to her.', 'Use send it to her.'),
        'it for her': tri('С send человеку обычно помогает to: send it to her.', 'З send людині зазвичай допомагає to: send it to her.', 'Send uses to here.'),
      },
      retryFeedback: [
        tri('Вещь = it.', 'Річ = it.', 'Thing = it.'),
        tri('К ней: to her.', 'До неї: to her.', 'To her.'),
        tri('Готовый кусок: send it to her.', 'Готовий зворот: send it to her.', 'Ready chunk: send it to her.'),
        tri('Ответ: Send it to her.', 'Відповідь: Send it to her.', 'Answer: Send it to her.'),
      ],
      fallbackExplanation: tri('С it: send it to her.', 'З it: send it to her.', 'With it: send it to her.'),
      focusWords: ['send it to her'],
    }),
    orderStep({
      id: 'object_order_contrast_006',
      order: 9,
      difficulty: 'contrast',
      targetSkill: 'show_it_to_me',
      teachingText: tri(
        'Show me your phone нормально. Но если уже it, лучше show it to me.',
        'Show me your phone нормально. Але якщо вже it, краще show it to me.',
        'Show me your phone is fine. But with it, use show it to me.',
      ),
      sentence: 'Show ___.',
      translation: tri('Покажи это мне.', 'Покажи це мені.', 'Show it to me.'),
      options: ['it to me', 'me it', 'to me it', 'it for me'],
      correctAnswer: 'it to me',
      correctFeedback: tri('Да. С it: show it to me.', 'Так. З it: show it to me.', 'Yes. With it: show it to me.'),
      wrong: {
        'me it': tri('Show me it звучит плохо для стандартной учебной фразы. Лучше show it to me.', 'Show me it звучить погано для стандартної навчальної фрази. Краще show it to me.', 'Use show it to me.'),
        'to me it': tri('Show to me it ломает порядок. Нужен кусок show it to me.', 'Show to me it ламає порядок. Потрібен зворот show it to me.', 'Use show it to me.'),
        'it for me': tri('С show человеку обычно помогает to: show it to me.', 'З show людині зазвичай допомагає to: show it to me.', 'Show uses to here.'),
      },
      retryFeedback: [
        tri('Вещь = it.', 'Річ = it.', 'Thing = it.'),
        tri('Кому показать? To me.', 'Кому показати? To me.', 'To me.'),
        tri('Готовый кусок: show it to me.', 'Готовий зворот: show it to me.', 'Ready chunk: show it to me.'),
        tri('Ответ: Show it to me.', 'Відповідь: Show it to me.', 'Answer: Show it to me.'),
      ],
      fallbackExplanation: tri('С it: show it to me.', 'З it: show it to me.', 'With it: show it to me.'),
      focusWords: ['show it to me'],
    }),
    orderStep({
      id: 'object_order_mixed_001',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'buy_it_for_me',
      teachingText: tri(
        'Для buy часто работает for: покупка делается для человека.',
        'Для buy часто працює for: покупка робиться для людини.',
        'Buy often uses for: the purchase is for someone.',
      ),
      sentence: 'Buy ___.',
      translation: tri('Купи это для меня.', 'Купи це для мене.', 'Buy it for me.'),
      options: ['it for me', 'it to me', 'me it', 'for me it'],
      correctAnswer: 'it for me',
      correctFeedback: tri('Да. Покупка для меня: buy it for me.', 'Так. Покупка для мене: buy it for me.', 'Yes. Buy it for me.'),
      wrong: {
        'it to me': tri('С buy обычно не "куда", а "для кого". Поэтому buy it for me.', 'З buy зазвичай не "куди", а "для кого". Тому buy it for me.', 'With buy, use for here: buy it for me.'),
        'me it': tri('Buy me it звучит плохо. С it безопаснее buy it for me.', 'Buy me it звучить погано. З it безпечніше buy it for me.', 'Use buy it for me.'),
        'for me it': tri('Buy for me it ломает порядок. Нужен кусок buy it for me.', 'Buy for me it ламає порядок. Потрібен зворот buy it for me.', 'Use buy it for me.'),
      },
      retryFeedback: [
        tri('Вещь = it.', 'Річ = it.', 'Thing = it.'),
        tri('Для меня = for me.', 'Для мене = for me.', 'For me.'),
        tri('Готовый кусок: buy it for me.', 'Готовий зворот: buy it for me.', 'Ready chunk: buy it for me.'),
        tri('Ответ: Buy it for me.', 'Відповідь: Buy it for me.', 'Answer: Buy it for me.'),
      ],
      fallbackExplanation: tri('Buy + it + for me.', 'Buy + it + for me.', 'Buy + it + for me.'),
      focusWords: ['buy it for me'],
    }),
    orderStep({
      id: 'object_order_mixed_002',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'make_it_for_her',
      teachingText: tri(
        'Make тоже часто говорит "для кого" через for.',
        'Make теж часто каже "для кого" через for.',
        'Make also often uses for for the person.',
      ),
      sentence: 'Make ___.',
      translation: tri('Сделай это для неё.', 'Зроби це для неї.', 'Make it for her.'),
      options: ['it for her', 'it to her', 'her it', 'for her it'],
      correctAnswer: 'it for her',
      correctFeedback: tri('Да. Сделай это для неё: make it for her.', 'Так. Зроби це для неї: make it for her.', 'Yes. Make it for her.'),
      wrong: {
        'it to her': tri('С make обычно нужен for, когда смысл "для неё": make it for her.', 'З make зазвичай потрібен for, коли сенс "для неї": make it for her.', 'Make uses for here.'),
        'her it': tri('Make her it звучит плохо. С it безопаснее make it for her.', 'Make her it звучить погано. З it безпечніше make it for her.', 'Use make it for her.'),
        'for her it': tri('Make for her it ломает порядок. Нужен make it for her.', 'Make for her it ламає порядок. Потрібно make it for her.', 'Use make it for her.'),
      },
      retryFeedback: [
        tri('Вещь = it.', 'Річ = it.', 'Thing = it.'),
        tri('Для неё = for her.', 'Для неї = for her.', 'For her.'),
        tri('Готовый кусок: make it for her.', 'Готовий зворот: make it for her.', 'Ready chunk: make it for her.'),
        tri('Ответ: Make it for her.', 'Відповідь: Make it for her.', 'Answer: Make it for her.'),
      ],
      fallbackExplanation: tri('Make + it + for her.', 'Make + it + for her.', 'Make + it + for her.'),
      focusWords: ['make it for her'],
    }),
    orderStep({
      id: 'object_order_mixed_003',
      order: 12,
      difficulty: 'mixed',
      targetSkill: 'tell_me_truth_tell_it_to_me',
      teachingText: tri(
        'С полной вещью человек может идти сразу после действия. Но если вещь заменена на it, ставь it сразу после действия, а человека в конец.',
        'З повною річчю людина може йти одразу після дії. Але якщо річ замінена на it, став it одразу після дії, а людину в кінець.',
        'Tell me the truth is fine because truth is named fully. With it: tell it to me.',
      ),
      sentence: 'Choose the correct pair.',
      translation: tri('Выбери правильную пару.', 'Обери правильну пару.', 'Choose the correct pair.'),
      options: ['Tell me the truth / Tell it to me', 'Tell me it / Tell to me the truth', 'Tell it for me / Tell me to it', 'Tell to me it / Tell the truth me'],
      correctAnswer: 'Tell me the truth / Tell it to me',
      correctFeedback: tri('Да. Полная фраза: tell me the truth. С it: tell it to me.', 'Так. Повна фраза: tell me the truth. З it: tell it to me.', 'Yes. Full phrase: tell me the truth. With it: tell it to me.'),
      wrong: {
        'Tell me it / Tell to me the truth': tri('Tell me it звучит плохо. Tell to me the truth тоже тяжело. Нужна пара tell me the truth / tell it to me.', 'Tell me it звучить погано. Tell to me the truth теж важко. Потрібна пара tell me the truth / tell it to me.', 'Use tell me the truth / tell it to me.'),
        'Tell it for me / Tell me to it': tri('Tell ведёт к человеку через to: tell it to me.', 'Tell веде до людини через to: tell it to me.', 'Tell uses to here: tell it to me.'),
        'Tell to me it / Tell the truth me': tri('Обе фразы ломают порядок. Нормально: tell it to me или tell me the truth.', 'Обидві фрази ламають порядок. Нормально: tell it to me або tell me the truth.', 'Both orders break. Use tell it to me or tell me the truth.'),
      },
      retryFeedback: [
        tri('Truth названа полностью: tell me the truth.', 'Truth названа повністю: tell me the truth.', 'Truth is named fully: tell me the truth.'),
        tri('Если it: tell it to me.', 'Якщо it: tell it to me.', 'If it: tell it to me.'),
        tri('Пара такая: полная вещь идет одним порядком, короткое it идет другим.', 'Пара така: повна річ іде одним порядком, коротке it іде іншим.', 'Pair: Tell me the truth / Tell it to me.'),
        tri('Выбери вариант, где полная вещь и it не смешаны в один порядок.', 'Обери варіант, де повна річ і it не змішані в один порядок.', 'Answer: Tell me the truth / Tell it to me.'),
      ],
      fallbackExplanation: tri('Если вещь названа полностью, человек может идти сразу после действия. Если вместо вещи it, ставь it перед to me.', 'Якщо річ названа повністю, людина може йти одразу після дії. Якщо замість речі it, став it перед to me.', 'Full thing: tell me the truth. It: tell it to me.'),
      focusWords: ['tell me the truth', 'tell it to me'],
    }),
    orderStep({
      id: 'object_order_mixed_004',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_give_patterns',
      teachingText: TWO_PATHS,
      sentence: 'Choose the correct pair.',
      translation: tri('Выбери правильную пару.', 'Обери правильну пару.', 'Choose the correct pair.'),
      options: ['Give me the book / Give it to me', 'Give me it / Give to me the book', 'Give it for me / Give to me it', 'Give the book me / Give me to it'],
      correctAnswer: 'Give me the book / Give it to me',
      correctFeedback: tri('Да. Book названа полностью: give me the book. С it: give it to me.', 'Так. Book названа повністю: give me the book. З it: give it to me.', 'Yes. Book is named fully: give me the book. With it: give it to me.'),
      wrong: {
        'Give me it / Give to me the book': tri('Give me it и give to me the book - две разные поломки порядка. Нужна пара give me the book / give it to me.', 'Give me it і give to me the book - дві різні поломки порядку. Потрібна пара give me the book / give it to me.', 'Use give me the book / give it to me.'),
        'Give it for me / Give to me it': tri('С give человеку помогает to, а с it порядок такой: give it to me.', 'З give людині допомагає to, а з it порядок такий: give it to me.', 'Give uses to; with it use give it to me.'),
        'Give the book me / Give me to it': tri('Give the book me ломает порядок. Нужно give the book to me или give me the book.', 'Give the book me ламає порядок. Потрібно give the book to me або give me the book.', 'Use give the book to me or give me the book.'),
      },
      retryFeedback: [
        tri('Book названа полностью: give me the book.', 'Book названа повністю: give me the book.', 'Book is named fully: give me the book.'),
        tri('It: give it to me.', 'It: give it to me.', 'It: give it to me.'),
        tri('Пара: Give me the book / Give it to me.', 'Пара: Give me the book / Give it to me.', 'Pair: Give me the book / Give it to me.'),
        tri('Ответ: Give me the book / Give it to me.', 'Відповідь: Give me the book / Give it to me.', 'Answer: Give me the book / Give it to me.'),
      ],
      fallbackExplanation: tri('Book: give me the book. It: give it to me.', 'Book: give me the book. It: give it to me.', 'Book: give me the book. It: give it to me.'),
      focusWords: ['give me the book', 'give it to me'],
    }),
    orderStep({
      id: 'object_order_mixed_005',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_to_for',
      teachingText: tri(
        'Send ведёт вещь к человеку через to. Buy делает покупку для человека через for.',
        'Send веде річ до людини через to. Buy робить покупку для людини через for.',
        'Send uses to. Buy uses for.',
      ),
      sentence: 'Choose the correct pair.',
      translation: tri('Выбери правильную пару.', 'Обери правильну пару.', 'Choose the correct pair.'),
      options: ['Send it to her / Buy it for her', 'Send it for her / Buy it to her', 'Send her it / Buy her it', 'Send to her it / Buy for her it'],
      correctAnswer: 'Send it to her / Buy it for her',
      correctFeedback: tri('Да. Send it to her. Buy it for her.', 'Так. Send it to her. Buy it for her.', 'Yes. Send it to her. Buy it for her.'),
      wrong: {
        'Send it for her / Buy it to her': tri('To/for поменялись местами. Нужно: Send it to her / Buy it for her.', 'To/for помінялися місцями. Потрібно: Send it to her / Buy it for her.', 'To/for are reversed. Use Send it to her / Buy it for her.'),
        'Send her it / Buy her it': tri('С it безопаснее: send it to her, buy it for her.', 'З it безпечніше: send it to her, buy it for her.', 'With it, use send it to her, buy it for her.'),
        'Send to her it / Buy for her it': tri('Порядок ломается. Нужна пара: send it to her / buy it for her.', 'Порядок ламається. Потрібна пара: send it to her / buy it for her.', 'Wrong order. Use send it to her / buy it for her.'),
      },
      retryFeedback: [
        tri('Send: it to her.', 'Send: it to her.', 'Send: it to her.'),
        tri('Buy: it for her.', 'Buy: it for her.', 'Buy: it for her.'),
        tri('Пара: Send it to her / Buy it for her.', 'Пара: Send it to her / Buy it for her.', 'Pair: Send it to her / Buy it for her.'),
        tri('Ответ: Send it to her / Buy it for her.', 'Відповідь: Send it to her / Buy it for her.', 'Answer: Send it to her / Buy it for her.'),
      ],
      fallbackExplanation: tri('Send it to her. Buy it for her.', 'Send it to her. Buy it for her.', 'Send it to her. Buy it for her.'),
      focusWords: ['send it to her', 'buy it for her'],
    }),
    orderStep({
      id: 'object_order_mixed_006',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_sentence_correction',
      teachingText: tri(
        'Финальная сборка: photo названа полностью, а потом появляется it.',
        'Фінальна збірка: photo названа повністю, а потім зʼявляється it.',
        'Final build: photo is named fully, then it appears.',
      ),
      sentence: 'Choose the correct sentence.',
      translation: tri('Выбери правильное предложение.', 'Обери правильне речення.', 'Choose the correct sentence.'),
      options: [
        'Show me the photo, then send it to her.',
        'Show me it, then send her it.',
        'Show to me the photo, then send to her it.',
        'Show it for me, then send it for her.',
      ],
      correctAnswer: 'Show me the photo, then send it to her.',
      correctFeedback: tri('Да. Photo названа полностью: show me the photo. Потом it: send it to her.', 'Так. Photo названа повністю: show me the photo. Потім it: send it to her.', 'Yes. Photo is named fully: show me the photo. Then it: send it to her.'),
      wrong: {
        'Show me it, then send her it.': tri('С it лучше show it to me и send it to her. А здесь первая часть нормальная как show me the photo.', 'З it краще show it to me і send it to her. А тут перша частина нормальна як show me the photo.', 'With it, use show it to me and send it to her. Here the first part is show me the photo.'),
        'Show to me the photo, then send to her it.': tri('Порядок с to здесь ломается дважды: для полной вещи и для it нужны разные схемы.', 'Порядок з to тут ламається двічі: для повної речі і для it потрібні різні схеми.', 'The to order breaks. Use show me the photo / send it to her.'),
        'Show it for me, then send it for her.': tri('Show и send обычно ведут к человеку через to: show it to me, send it to her.', 'Show і send зазвичай ведуть до людини через to: show it to me, send it to her.', 'Show and send use to here: show it to me, send it to her.'),
      },
      retryFeedback: [
        tri('Photo названа полностью: show me the photo.', 'Photo названа повністю: show me the photo.', 'Photo is named fully: show me the photo.'),
        tri('Потом it: send it to her.', 'Потім it: send it to her.', 'Then it: send it to her.'),
        tri('Сначала полная вещь: человека можно поставить сразу после show. Потом it: его ставим перед to her.', 'Спочатку повна річ: людину можна поставити одразу після show. Потім it: його ставимо перед to her.', 'Ready sentence: Show me the photo, then send it to her.'),
        tri('Выбирай вариант, где photo названа полностью, а it стоит сразу после send.', 'Обирай варіант, де photo названа повністю, а it стоїть одразу після send.', 'Answer: Show me the photo, then send it to her.'),
      ],
      fallbackExplanation: tri('Правило то же: полная вещь допускает короткий порядок с человеком, а it требует порядок через to.', 'Правило те саме: повна річ допускає короткий порядок з людиною, а it вимагає порядок через to.', 'Show me the photo, then send it to her.'),
      focusWords: ['show me the photo', 'send it to her'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'give_me_it_error',
      'send_her_it_error',
      'show_me_it_error',
      'wrong_to_order_error',
      'to_for_confusion',
      'pronoun_object_order_error',
      'double_object_pattern_confusion',
      'mixed_pattern_error',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri(
      'Сначала найди, кто получает, и что передают.',
      'Спочатку знайди, хто отримує, і що передають.',
      'Primero encuentra quien recibe y que se entrega.',
    ),
    depth2: tri(
      'Проверь вещь: она названа полностью или это it/them?',
      'Перевір річ: вона названа повністю чи це it/them?',
      'Comprueba la cosa: esta nombrada completa o es it/them?',
    ),
    depth3: tri(
      'Держи смысл: полная вещь может идти после человека, а it лучше ставить сразу после действия.',
      'Тримай зміст: повна річ може йти після людини, а it краще ставити одразу після дії.',
      'Usa los pares modelo: give me the book / give it to me.',
    ),
    depth4: tri(
      'Почти подсказка: система покажет безопасный порядок слов.',
      'Майже підказка: система покаже безпечний порядок слів.',
      'Casi una pista: el sistema muestra el orden seguro de palabras.',
    ),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri(
        'Стоп. Если вещь названа полностью: give me the book. Если вещь = it/them: give it to me. Give/send/show/tell чаще идут с to. Buy/make/get чаще идут с for.',
        'Стоп. Якщо річ названа повністю: give me the book. Якщо річ = it/them: give it to me. Give/send/show/tell частіше йдуть з to. Buy/make/get частіше йдуть з for.',
        'Para. Cosa completa: give me the book. It/them: give it to me. Give/send/show/tell suelen usar to. Buy/make/get suelen usar for.',
      ),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_object_type_hint_then_retry',
      card: tri(
        'Подсказка: система покажет, где человек, где вещь, и названа ли вещь полностью или заменена на it/them.',
        'Підказка: система покаже, де людина, де річ, і чи названа річ повністю, чи замінена на it/them.',
        'Pista: el sistema muestra donde esta la persona, donde esta la cosa y si la cosa esta nombrada completa o reemplazada por it/them.',
      ),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri(
        'Режим с подсказками: сначала выбираем, полная вещь или it/them. Потом выбираем to или for.',
        'Режим із підказками: спочатку обираємо, повна річ чи it/them. Потім обираємо to або for.',
        'Modo guiado: primero elegimos cosa completa o it/them. Despues elegimos to o for.',
      ),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      {
        id: 'guided_object_order_001',
        prompt: tri('В Give me the book книга названа полностью или заменена на it?', 'У Give me the book книжка названа повністю чи замінена на it?', 'En Give me the book, el libro esta nombrado completo o reemplazado por it?'),
        options: ['названа полностью', 'it'],
        correctIndex: 0,
        thenReturnToExerciseId: 'object_order_easy_001',
      },
      {
        id: 'guided_object_order_002',
        prompt: tri('Если вещь = it, что безопаснее?', 'Якщо річ = it, що безпечніше?', 'Si la cosa es it, que es mas seguro?'),
        options: ['Give me it', 'Give it to me'],
        correctIndex: 1,
        thenReturnToExerciseId: 'object_order_contrast_004',
      },
      {
        id: 'guided_object_order_003',
        prompt: tri('Send ведёт вещь к человеку через to или for?', 'Send веде річ до людини через to чи for?', 'Send suele llevar la cosa a la persona con to o con for?'),
        options: ['to', 'for'],
        correctIndex: 0,
        thenReturnToExerciseId: 'object_order_contrast_002',
      },
      {
        id: 'guided_object_order_004',
        prompt: tri('Buy показывает "для кого" через to или for?', 'Buy показує "для кого" через to чи for?', 'Buy muestra "para quien" con to o con for?'),
        options: ['to', 'for'],
        correctIndex: 1,
        thenReturnToExerciseId: 'object_order_mixed_001',
      },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'syntax',
    microDiagnosisId: 'object_order_give_me_it',
    diagnosisLabel: tri(
      'Give it to me',
      'Give it to me',
      'Give it to me: orden',
    ),
    contrastSet: CONTRAST,
    focusWords: ['give me the book', 'give it to me', 'send it to her', 'buy it for me'],
    focusPatterns: [
      'give_person_thing',
      'send_person_thing',
      'show_person_thing',
      'give_thing_to_person',
      'send_thing_to_person',
      'show_thing_to_person',
      'give_it_to_me',
      'send_it_to_her',
      'show_it_to_me',
      'buy_it_for_me',
      'make_it_for_her',
      'tell_me_truth_tell_it_to_me',
      'mixed_give_patterns',
      'mixed_to_for',
      'mixed_sentence_correction',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyLevel: 2,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 3,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_started',
    answer: 'diagnosis_training_answer',
    mastery: 'diagnosis_training_mastered',
    recovery: 'diagnosis_training_recovery',
    onStart: 'diagnosis_training_started',
    onCorrect: 'diagnosis_training_answer_correct',
    onWrong: 'diagnosis_training_answer_wrong',
    onDepthIncrease: 'diagnosis_training_feedback_depth_increased',
    onGuidedMode: 'diagnosis_training_guided_mode_started',
    onMastery: 'diagnosis_training_mastered',
    onSmartTrainerOpen: 'diagnosis_training_smart_trainer_opened',
    payload: {
      category: 'syntax',
      microDiagnosisId: 'object_order_give_me_it',
      contrastSet: ['verb + person + thing', 'verb + thing + to + person', 'verb + thing + for + person', 'it/them order'],
      logExactToken: true,
      logMistakeType: true,
      logExerciseId: true,
      logAttemptCount: true,
      logFeedbackDepth: true,
      logObjectType: true,
      logObjectOrderPattern: true,
      logPreposition: true,
    },
  },
  routing: {
    diagnosisTrainerRoute: '/problem_coach?category=syntax&microDiagnosisId=object_order_give_me_it',
    problemCoachRoute: '/problem_coach?category=syntax&microDiagnosisId=object_order_give_me_it',
    smartTrainerRoute: '/problem_coach?category=syntax&microDiagnosisId=object_order_give_me_it',
    fallbackIfTrainingMissing: '/problem_coach?category=syntax',
  },
  qualityChecklist: {
    hasStableId: true,
    hasCategory: true,
    hasMultilingualTitle: true,
    hasPlainDiagnosisText: true,
    hasMentalModel: true,
    hasContrastSet: true,
    hasAtLeastSixExamples: true,
    hasAtLeastTwelveExercises: true,
    hasEasyContrastMixedStructure: true,
    hasDistractorSpecificFeedback: true,
    hasRetryFeedbackLevels: true,
    hasGuidedModeForRepeatedMistakes: true,
    hasMasteryRules: true,
    hasSmartTrainerConfig: true,
    hasAnalyticsPayload: true,
    hasFallbackRoute: true,
  },
};
