import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

type PlannedTrainingLocale = 'pt-BR' | 'vi' | 'id' | 'tr' | 'pl';

const VERB_PATTERN_NEEDS_REVIEW_PLANNED: Record<PlannedTrainingLocale, string> = {
  'pt-BR': 'needs-review: esta explicação sobre padrões verbo + preposição ainda precisa de revisão para português do Brasil.',
  vi: 'needs-review: phần giải thích về mẫu động từ + giới từ này vẫn cần được rà soát cho tiếng Việt.',
  id: 'needs-review: penjelasan pola kata kerja + preposisi ini masih perlu ditinjau untuk bahasa Indonesia.',
  tr: 'needs-review: bu fiil + edat kalıbı açıklaması Türkçe için hâlâ gözden geçirilmeli.',
  pl: 'needs-review: to objaśnienie wzorca czasownik + przyimek nadal wymaga przeglądu po polsku.',
};

const tri = (
  ru: string,
  uk: string,
  es = ru,
  planned: Partial<Record<PlannedTrainingLocale, string>> = {},
): TriText => {
  const copy: TriText = { ru, uk, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    copy[locale] = planned[locale] ?? VERB_PATTERN_NEEDS_REVIEW_PLANNED[locale];
  }
  return copy;
};

const CONTRAST = ['listen to', 'wait for', 'depend on', 'look at', 'talk to', 'think about', 'ask for', 'believe in'];

const VERB_PATTERN_SKILL_ES: Record<string, string> = {
  listen_to: 'Listen se aprende con to: listen to music.',
  wait_for: 'Wait se aprende con for cuando esperas a una persona.',
  wait_for_bus: 'Cuando esperas algo, el bloque normal es wait for.',
  depend_on: 'Depend se aprende con on, aunque la traduccion empuje a from.',
  look_at: 'Look at significa dirigir la mirada a algo.',
  look_for_vs_look_at: 'Look for es buscar; look at es mirar.',
  talk_to: 'Talk to marca la persona con quien hablas.',
  think_about: 'Think about marca el tema del pensamiento.',
  talk_about: 'Talk about marca el tema de la conversacion.',
  ask_for: 'Ask for significa pedir algo.',
  believe_in: 'Believe in marca confianza en alguien, algo o uno mismo.',
  ask_about_topic: 'Ask about se usa para preguntar sobre un tema.',
  mixed_listen_wait: 'Guarda los bloques completos: listen to y wait for.',
  mixed_depend_look: 'Guarda los bloques completos: depend on y look at.',
  mixed_sentence_correction: 'Une cada accion con su cola fija: listen to, wait for, talk to.',
};

function withEs(
  copy: TriText,
  es: string,
  planned: Partial<Record<PlannedTrainingLocale, string>> = VERB_PATTERN_NEEDS_REVIEW_PLANNED,
): TriText {
  const next: TriText = { ...copy, es };
  for (const locale of ['pt-BR', 'vi', 'id', 'tr', 'pl'] as const) {
    if (!next[locale] || next[locale]?.startsWith('needs-review:')) {
      next[locale] = planned[locale] ?? VERB_PATTERN_NEEDS_REVIEW_PLANNED[locale];
    }
  }
  return next;
}

function verbPatternEsFeedback(input: {
  targetSkill: string;
  correctAnswer: string;
  focusWords: string[];
}): string {
  const focus = input.focusWords.join(' / ');
  const hint = VERB_PATTERN_SKILL_ES[input.targetSkill] ?? 'Aprende el verbo con su pequena cola como un solo bloque.';
  return `Usa "${input.correctAnswer}"${focus ? ` con ${focus}` : ''}. ${hint}`;
}

function verbPatternStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  teachingText: TriText;
  sentence: string;
  translation: TriText;
  options: string[];
  correctAnswer: string;
  correctFeedback: TriText;
  wrong: Record<string, TriText>;
  retryFeedback: [TriText, TriText, TriText, TriText];
  fallbackExplanation: TriText;
  focusWords: string[];
}): DiagnosisTrainingStep {
  const correctIndex = input.options.findIndex((option) => option === input.correctAnswer);
  const esFeedback = verbPatternEsFeedback(input);

  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    teachingText: withEs(input.teachingText, esFeedback),
    translation: withEs(input.translation, esFeedback),
    explanationBlock: withEs(input.teachingText, esFeedback),
    microTask: tri(
      'Выбери маленькое слово, которое живёт вместе с этим действием.',
      'Обери маленьке слово, яке живе разом із цією дією.',
      'Elige la palabra pequena que vive junto con esta accion.',
    ),
    sentence: input.sentence,
    answerOptions: input.options.map((text) => ({ id: text, text })),
    correctAnswerId: input.correctAnswer,
    correctIndex,
    correctFeedback: withEs(input.correctFeedback, esFeedback),
    wrongFeedbackByOption: Object.fromEntries(
      input.options
        .filter((option) => option !== input.correctAnswer)
        .map((option) => [option, withEs(input.wrong[option] ?? tri(
          `Почти. Здесь нужен готовый кусок с ${input.correctAnswer}.`,
          `Майже. Тут потрібен готовий зворот з ${input.correctAnswer}.`,
          `Casi. Aqui necesitas el bloque con ${input.correctAnswer}.`,
        ), esFeedback)]),
    ),
    retryFeedback: input.retryFeedback.map((item) => withEs(item, esFeedback)) as [TriText, TriText, TriText, TriText],
    fallbackExplanation: withEs(input.fallbackExplanation, esFeedback),
    focusWords: input.focusWords,
  };
}

const CHUNK_MODEL = tri(
  'Здесь маленькое слово нельзя спокойно выбрать по переводу. Оно хранится вместе с действием: listen to, wait for, depend on.',
  'Тут маленьке слово не варто обирати лише за перекладом. Воно зберігається разом із дією: listen to, wait for, depend on.',
  'Aqui la palabra pequena no se elige solo por traduccion. Se guarda con la accion: listen to, wait for, depend on.',
  {
    'pt-BR': 'Aqui a palavrinha não pode ser escolhida só pela tradução. Ela fica guardada junto com a ação: listen to, wait for, depend on.',
    vi: 'Ở đây không thể chọn từ nhỏ chỉ theo bản dịch. Nó được ghi nhớ cùng hành động: listen to, wait for, depend on.',
    id: 'Di sini kata kecil tidak bisa dipilih hanya dari terjemahan. Kata itu disimpan bersama tindakannya: listen to, wait for, depend on.',
    tr: 'Burada küçük kelime yalnızca çeviriye göre seçilemez. Eylemle birlikte saklanır: listen to, wait for, depend on.',
    pl: 'Tutaj małego słowa nie da się spokojnie wybrać tylko z tłumaczenia. Trzyma się je razem z czynnością: listen to, wait for, depend on.',
  },
);

export const PREPOSITION_COMMON_VERB_PATTERNS_TRAINING: DiagnosisTraining = {
  id: 'preposition_common_verb_patterns',
  category: 'preposition',
  version: '1.0.0',
  status: 'active',
  priority: 29,
  supportedLocales: ['ru', 'uk', 'es'],
  title: tri(
    'Listen to / Wait for / Depend on: готовые связки',
    'Listen to / Wait for / Depend on: готові звʼязки',
    'Listen to / Wait for / Depend on: bloques fijos',
    {
      'pt-BR': 'Listen to / Wait for / Depend on: blocos prontos',
      vi: 'Listen to / Wait for / Depend on: cụm cố định',
      id: 'Listen to / Wait for / Depend on: pola tetap',
      tr: 'Listen to / Wait for / Depend on: hazır kalıplar',
      pl: 'Listen to / Wait for / Depend on: gotowe połączenia',
    },
  ),
  shortTitle: tri(
    'Listen to / Wait for',
    'Listen to / Wait for',
    'Listen to / Wait for',
    {
      'pt-BR': 'Verbo + preposição',
      vi: 'Động từ + giới từ',
      id: 'Kata kerja + preposisi',
      tr: 'Fiil + edat',
      pl: 'Czasownik + przyimek',
    },
  ),
  shortDiagnosis: tri(
    'Ты знаешь слова, но теряешь маленький хвост: listen to, wait for, depend on, look at.',
    'Ти знаєш слова, але губиш маленький хвіст: listen to, wait for, depend on, look at.',
    'Conoces las palabras, pero pierdes la cola pequena: listen to, wait for, depend on, look at.',
    {
      'pt-BR': 'Você conhece as palavras, mas perde a cauda pequena: listen to, wait for, depend on, look at.',
      vi: 'Bạn biết các từ, nhưng làm mất phần đuôi nhỏ: listen to, wait for, depend on, look at.',
      id: 'Kamu tahu kata-katanya, tetapi kehilangan ekor kecilnya: listen to, wait for, depend on, look at.',
      tr: 'Kelimeleri biliyorsun ama küçük kuyruğu kaçırıyorsun: listen to, wait for, depend on, look at.',
      pl: 'Znasz słowa, ale gubisz mały ogon: listen to, wait for, depend on, look at.',
    },
  ),
  diagnosisText: tri(
    'Похоже, ты переводишь маленькое слово отдельно. Поэтому появляются listen music, wait me, depend from, look on. В английском такие куски лучше хранить целиком: listen to music, wait for me, depend on the weather, look at the screen.',
    'Схоже, ти перекладаєш маленьке слово окремо. Тому зʼявляються listen music, wait me, depend from, look on. В англійській такі звороти краще зберігати цілими: listen to music, wait for me, depend on the weather, look at the screen.',
    'Parece que traduces la palabra pequena por separado. Por eso aparecen listen music, wait me, depend from, look on. En ingles conviene guardar estos bloques enteros: listen to music, wait for me, depend on the weather, look at the screen.',
    {
      'pt-BR': 'Parece que você traduz a palavrinha separadamente. Por isso aparecem listen music, wait me, depend from, look on. Em inglês, é melhor guardar esses blocos inteiros: listen to music, wait for me, depend on the weather, look at the screen.',
      vi: 'Có vẻ bạn dịch từ nhỏ riêng lẻ. Vì vậy mới xuất hiện listen music, wait me, depend from, look on. Trong tiếng Anh, tốt hơn là ghi nhớ cả cụm: listen to music, wait for me, depend on the weather, look at the screen.',
      id: 'Sepertinya kamu menerjemahkan kata kecil itu secara terpisah. Karena itu muncul listen music, wait me, depend from, look on. Dalam bahasa Inggris, lebih baik menyimpan blok ini secara utuh: listen to music, wait for me, depend on the weather, look at the screen.',
      tr: 'Küçük kelimeyi ayrı ayrı çeviriyor gibisin. Bu yüzden listen music, wait me, depend from, look on gibi hatalar çıkıyor. İngilizcede bu parçaları bütün olarak tutmak daha iyidir: listen to music, wait for me, depend on the weather, look at the screen.',
      pl: 'Wygląda na to, że tłumaczysz małe słowo osobno. Dlatego pojawiają się listen music, wait me, depend from, look on. W angielskim lepiej przechowywać takie bloki w całości: listen to music, wait for me, depend on the weather, look at the screen.',
    },
  ),
  mentalModel: tri(
    'Не держи listen отдельно и to отдельно. Держи один кусок: listen to. То же самое: wait for, depend on, look at, talk to, think about, ask for, believe in.',
    'Не тримай listen окремо і to окремо. Тримай один зворот: listen to. Так само: wait for, depend on, look at, talk to, think about, ask for, believe in.',
    'No guardes listen y to por separado. Guarda un solo bloque: listen to. Igual con wait for, depend on, look at, talk to, think about, ask for, believe in.',
    {
      'pt-BR': 'Não guarde listen separado de to. Guarde um bloco: listen to. O mesmo vale para wait for, depend on, look at, talk to, think about, ask for, believe in.',
      vi: 'Đừng ghi nhớ listen tách khỏi to. Hãy giữ một cụm: listen to. Tương tự với wait for, depend on, look at, talk to, think about, ask for, believe in.',
      id: 'Jangan simpan listen terpisah dari to. Simpan sebagai satu blok: listen to. Sama juga dengan wait for, depend on, look at, talk to, think about, ask for, believe in.',
      tr: 'Listen ve to parçalarını ayrı tutma. Tek kalıp olarak tut: listen to. Aynısı wait for, depend on, look at, talk to, think about, ask for, believe in için de geçerli.',
      pl: 'Nie trzymaj listen osobno i to osobno. Trzymaj jeden blok: listen to. Tak samo: wait for, depend on, look at, talk to, think about, ask for, believe in.',
    },
  ),
  contrastSet: CONTRAST,
  coreRule: tri(
    'listen to music, wait for me, depend on the weather, look at the screen, talk to you, think about it, ask for help, believe in yourself.',
    'listen to music, wait for me, depend on the weather, look at the screen, talk to you, think about it, ask for help, believe in yourself.',
    'listen to music, wait for me, depend on the weather, look at the screen, talk to you, think about it, ask for help, believe in yourself.',
    {
      'pt-BR': 'Aprenda estes blocos inteiros: listen to music, wait for me, depend on the weather, look at the screen, talk to you, think about it, ask for help, believe in yourself.',
      vi: 'Hãy học trọn các cụm này: listen to music, wait for me, depend on the weather, look at the screen, talk to you, think about it, ask for help, believe in yourself.',
      id: 'Pelajari blok lengkap ini: listen to music, wait for me, depend on the weather, look at the screen, talk to you, think about it, ask for help, believe in yourself.',
      tr: 'Bu kalıpları bütün olarak öğren: listen to music, wait for me, depend on the weather, look at the screen, talk to you, think about it, ask for help, believe in yourself.',
      pl: 'Ucz się tych całych bloków: listen to music, wait for me, depend on the weather, look at the screen, talk to you, think about it, ask for help, believe in yourself.',
    },
  ),
  whatUserMustLearn: {
    ru: [
      'Listen to = слушать кого-то или что-то: listen to music, listen to me.',
      'Wait for = ждать кого-то или что-то: wait for me, wait for the bus.',
      'Depend on = зависеть от чего-то: It depends on the weather.',
      'Look at = смотреть на что-то: look at the screen.',
      'Look for = искать: look for my keys. Это не то же самое, что look at.',
      'Talk to = говорить с человеком: talk to you.',
      'Talk about = говорить о теме: talk about the problem.',
      'Think about = думать о теме: think about your answer.',
      'Ask for = просить что-то: ask for help.',
      'Believe in = верить в человека, идею или себя: believe in yourself.',
      'Главная привычка: учить не маленькое слово отдельно, а весь готовый кусок.',
    ],
    uk: [
      'Listen to = слухати когось або щось: listen to music, listen to me.',
      'Wait for = чекати когось або щось: wait for me, wait for the bus.',
      'Depend on = залежати від чогось: It depends on the weather.',
      'Look at = дивитися на щось: look at the screen.',
      'Look for = шукати: look for my keys. Це не те саме, що look at.',
      'Talk to = говорити з людиною: talk to you.',
      'Talk about = говорити про тему: talk about the problem.',
      'Think about = думати про тему: think about your answer.',
      'Ask for = просити щось: ask for help.',
      'Believe in = вірити в людину, ідею або себе: believe in yourself.',
      'Головна звичка: вчити не маленьке слово окремо, а весь готовий зворот.',
    ],
    es: [
      'Listen to = escuchar a alguien o algo: listen to music, listen to me.',
      'Wait for = esperar a alguien o algo: wait for me, wait for the bus.',
      'Depend on = depender de algo: It depends on the weather.',
      'Look at = mirar algo: look at the screen.',
      'Look for = buscar: look for my keys. No es lo mismo que look at.',
      'Talk to = hablar con una persona: talk to you.',
      'Talk about = hablar de un tema: talk about the problem.',
      'Think about = pensar en un tema: think about your answer.',
      'Ask for = pedir algo: ask for help.',
      'Believe in = creer en una persona, una idea o en ti mismo: believe in yourself.',
      'El habito principal: aprender el bloque completo, no la palabra pequena sola.',
    ],
    'pt-BR': [
      'Listen to = ouvir alguém ou algo.',
      'Wait for = esperar por alguém ou algo.',
      'Depend on = depender de algo.',
      'Look at = olhar para algo.',
      'Look for = procurar algo. Não é o mesmo que look at.',
      'Talk to = falar com uma pessoa.',
      'Talk about = falar sobre um assunto.',
      'Think about = pensar sobre um assunto.',
      'Ask for = pedir algo.',
      'Believe in = acreditar em alguém, em uma ideia ou em si mesmo.',
      'Aprenda o bloco inteiro, não a palavrinha sozinha.',
    ],
    vi: [
      'Listen to = nghe ai đó hoặc thứ gì đó.',
      'Wait for = chờ ai đó hoặc thứ gì đó.',
      'Depend on = phụ thuộc vào điều gì đó.',
      'Look at = nhìn vào thứ gì đó.',
      'Look for = tìm thứ gì đó. Không giống look at.',
      'Talk to = nói chuyện với một người.',
      'Talk about = nói về một chủ đề.',
      'Think about = nghĩ về một chủ đề.',
      'Ask for = xin hoặc yêu cầu thứ gì đó.',
      'Believe in = tin vào ai đó, một ý tưởng hoặc chính mình.',
      'Học cả cụm, không học riêng từ nhỏ.',
    ],
    id: [
      'Listen to = mendengarkan seseorang atau sesuatu.',
      'Wait for = menunggu seseorang atau sesuatu.',
      'Depend on = bergantung pada sesuatu.',
      'Look at = melihat ke sesuatu.',
      'Look for = mencari sesuatu. Ini tidak sama dengan look at.',
      'Talk to = berbicara dengan seseorang.',
      'Talk about = berbicara tentang suatu topik.',
      'Think about = memikirkan suatu topik.',
      'Ask for = meminta sesuatu.',
      'Believe in = percaya pada seseorang, ide, atau diri sendiri.',
      'Pelajari seluruh chunk, bukan kata kecilnya saja.',
    ],
    tr: [
      'Listen to = birini veya bir şeyi dinlemek.',
      'Wait for = birini veya bir şeyi beklemek.',
      'Depend on = bir şeye bağlı olmak.',
      'Look at = bir şeye bakmak.',
      'Look for = bir şeyi aramak. Look at ile aynı değildir.',
      'Talk to = bir kişiyle konuşmak.',
      'Talk about = bir konu hakkında konuşmak.',
      'Think about = bir konu hakkında düşünmek.',
      'Ask for = bir şey istemek.',
      'Believe in = birine, bir fikre veya kendine inanmak.',
      'Küçük kelimeyi tek başına değil, bütün kalıbı öğren.',
    ],
    pl: [
      'Listen to = słuchać kogoś lub czegoś.',
      'Wait for = czekać na kogoś lub coś.',
      'Depend on = zależeć od czegoś.',
      'Look at = patrzeć na coś.',
      'Look for = szukać czegoś. To nie to samo co look at.',
      'Talk to = rozmawiać z osobą.',
      'Talk about = mówić o temacie.',
      'Think about = myśleć o temacie.',
      'Ask for = prosić o coś.',
      'Believe in = wierzyć w kogoś, ideę albo siebie.',
      'Ucz się całego bloku, nie małego słowa osobno.',
    ],
  },
  examples: [
    {
      en: 'I listen to music every day.',
      ru: 'Я слушаю музыку каждый день.',
      uk: 'Я слухаю музику щодня.',
      es: 'Escucho musica todos los dias.',
      'pt-BR': 'Eu ouço música todos os dias.',
      vi: 'Tôi nghe nhạc mỗi ngày.',
      id: 'Saya mendengarkan musik setiap hari.',
      tr: 'Her gün müzik dinlerim.',
      pl: 'Słucham muzyki codziennie.',
      why: tri('Кусок хранится целиком: listen to music.', 'Зворот зберігається цілим: listen to music.', 'Guarda el bloque entero: listen to music.'),
    },
    {
      en: 'Please wait for me.',
      ru: 'Пожалуйста, подожди меня.',
      uk: 'Будь ласка, почекай мене.',
      es: 'Por favor, esperame.',
      'pt-BR': 'Por favor, espere por mim.',
      vi: 'Làm ơn chờ tôi.',
      id: 'Tolong tunggu saya.',
      tr: 'Lütfen beni bekle.',
      pl: 'Proszę, poczekaj na mnie.',
      why: tri('Ждать человека: wait for me.', 'Чекати людину: wait for me.', 'Esperar a una persona: wait for me.'),
    },
    {
      en: 'It depends on the weather.',
      ru: 'Это зависит от погоды.',
      uk: 'Це залежить від погоди.',
      es: 'Depende del clima.',
      'pt-BR': 'Isso depende do tempo.',
      vi: 'Điều đó phụ thuộc vào thời tiết.',
      id: 'Itu tergantung pada cuaca.',
      tr: 'Bu hava durumuna bağlı.',
      pl: 'To zależy od pogody.',
      why: tri('Русский подсказывает "от", но английский кусок: depend on.', 'Українська підказує "від", але англійський зворот: depend on.', 'La traduccion puede sugerir from, pero el bloque ingles es depend on.'),
    },
    {
      en: 'Look at the screen.',
      ru: 'Посмотри на экран.',
      uk: 'Подивися на екран.',
      es: 'Mira la pantalla.',
      'pt-BR': 'Olhe para a tela.',
      vi: 'Nhìn vào màn hình.',
      id: 'Lihat layarnya.',
      tr: 'Ekrana bak.',
      pl: 'Spójrz na ekran.',
      why: tri('Направить взгляд: look at the screen.', 'Спрямувати погляд: look at the screen.', 'Dirigir la mirada: look at the screen.'),
    },
    {
      en: 'I need to talk to you.',
      ru: 'Мне нужно поговорить с тобой.',
      uk: 'Мені потрібно поговорити з тобою.',
      es: 'Necesito hablar contigo.',
      'pt-BR': 'Preciso falar com você.',
      vi: 'Tôi cần nói chuyện với bạn.',
      id: 'Saya perlu berbicara denganmu.',
      tr: 'Seninle konuşmam gerekiyor.',
      pl: 'Muszę z tobą porozmawiać.',
      why: tri('Человек, с кем говорим: talk to you.', 'Людина, з ким говоримо: talk to you.', 'La persona con quien hablas: talk to you.'),
    },
    {
      en: 'Think about your answer.',
      ru: 'Подумай о своём ответе.',
      uk: 'Подумай про свою відповідь.',
      es: 'Piensa en tu respuesta.',
      'pt-BR': 'Pense na sua resposta.',
      vi: 'Hãy nghĩ về câu trả lời của bạn.',
      id: 'Pikirkan jawabanmu.',
      tr: 'Cevabını düşün.',
      pl: 'Pomyśl o swojej odpowiedzi.',
      why: tri('Тема мысли: think about your answer.', 'Тема думки: think about your answer.', 'El tema del pensamiento: think about your answer.'),
    },
    {
      en: 'She asked for help.',
      ru: 'Она попросила помощи.',
      uk: 'Вона попросила допомоги.',
      es: 'Ella pidio ayuda.',
      'pt-BR': 'Ela pediu ajuda.',
      vi: 'Cô ấy đã nhờ giúp đỡ.',
      id: 'Dia meminta bantuan.',
      tr: 'Yardım istedi.',
      pl: 'Poprosiła o pomoc.',
      why: tri('Просить что-то: ask for help.', 'Просити щось: ask for help.', 'Pedir algo: ask for help.'),
    },
    {
      en: 'You have to believe in yourself.',
      ru: 'Ты должен верить в себя.',
      uk: 'Ти маєш вірити в себе.',
      es: 'Tienes que creer en ti mismo.',
      'pt-BR': 'Você precisa acreditar em si mesmo.',
      vi: 'Bạn phải tin vào chính mình.',
      id: 'Kamu harus percaya pada dirimu sendiri.',
      tr: 'Kendine inanmalısın.',
      pl: 'Musisz wierzyć w siebie.',
      why: tri('Верить в себя: believe in yourself.', 'Вірити в себе: believe in yourself.', 'Creer en ti mismo: believe in yourself.'),
    },
  ],
  introBlocks: [
    {
      id: 'intro_problem',
      type: 'diagnosis',
      text: tri(
        'Проблема здесь обычно не в смысле слов. Ты понимаешь listen, wait, depend, look. Но в живой фразе к ним нужен маленький хвост.',
        'Проблема тут зазвичай не в значенні слів. Ти розумієш listen, wait, depend, look. Але в живій фразі до них потрібен маленький хвіст.',
        'El problema normalmente no esta en el significado de las palabras. Entiendes listen, wait, depend, look. Pero en una frase real necesitan una cola pequena.',
      ),
    },
    {
      id: 'intro_rule',
      type: 'rule',
      text: tri(
        'Учить надо блоком: listen to, wait for, depend on, look at. Иначе мозг начинает подбирать "на/о/к/за" прямо во время ответа.',
        'Вчити треба блоком: listen to, wait for, depend on, look at. Інакше мозок починає підбирати "на/про/до/за" прямо під час відповіді.',
        'Hay que aprenderlo como bloque: listen to, wait for, depend on, look at.',
      ),
    },
    {
      id: 'intro_warning',
      type: 'warning',
      text: tri(
        'Самые липкие ошибки: listen music, wait me, depend from, look on. Исправляем их короткими готовыми кусками.',
        'Найлипкіші помилки: listen music, wait me, depend from, look on. Виправляємо їх короткими готовими зворотами.',
        'Errores pegajosos: listen music, wait me, depend from, look on. Los corregimos con bloques cortos ya listos.',
      ),
    },
  ],
  steps: [
    verbPatternStep({
      id: 'verb_prep_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'listen_to',
      teachingText: CHUNK_MODEL,
      sentence: 'I listen ___ music every day.',
      translation: tri('Я слушаю музыку каждый день.', 'Я слухаю музику щодня.', 'I listen to music every day.'),
      options: ['to', 'for', 'on', 'at'],
      correctAnswer: 'to',
      correctFeedback: tri('Да. Готовый кусок: listen to music.', 'Так. Готовий зворот: listen to music.', 'Yes. Ready chunk: listen to music.'),
      wrong: {
        for: tri('Listen for бывает, когда ты прислушиваешься и ждёшь звук. Здесь обычное "слушаю музыку": listen to music.', 'Listen for буває, коли ти прислухаєшся і чекаєш звук. Тут звичайне "слухаю музику": listen to music.', 'Listen for can mean listening for an expected sound. Here use listen to music.'),
        on: tri('Listen on music не работает. Нужен готовый кусок listen to music.', 'Listen on music не працює. Потрібен готовий зворот listen to music.', 'Listen on music does not work. Use listen to music.'),
        at: tri('Listen at music не работает. После listen здесь нужен хвост to: listen to music.', 'Listen at music не працює. Після listen тут потрібен хвіст to: listen to music.', 'Listen at music does not work. Use listen to music.'),
      },
      retryFeedback: [
        tri('Не переводи маленькое слово отдельно.', 'Не перекладай маленьке слово окремо.', 'Do not translate the small word alone.'),
        tri('Держи кусок: listen to.', 'Тримай зворот: listen to.', 'Keep the chunk: listen to.'),
        tri('С музыкой: listen to music.', 'З музикою: listen to music.', 'With music: listen to music.'),
        tri('Ответ: I listen to music every day.', 'Відповідь: I listen to music every day.', 'Answer: I listen to music every day.'),
      ],
      fallbackExplanation: tri('Слушать музыку: listen to music.', 'Слухати музику: listen to music.', 'Listen to music.'),
      focusWords: ['listen to', 'music'],
    }),
    verbPatternStep({
      id: 'verb_prep_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'wait_for',
      teachingText: CHUNK_MODEL,
      sentence: 'Please wait ___ me.',
      translation: tri('Пожалуйста, подожди меня.', 'Будь ласка, почекай мене.', 'Please wait for me.'),
      options: ['to', 'for', 'on', 'at'],
      correctAnswer: 'for',
      correctFeedback: tri('Да. Подождать меня: wait for me.', 'Так. Почекати мене: wait for me.', 'Yes. Wait for me.'),
      wrong: {
        to: tri('Wait to me не работает. Когда ждёшь человека, нужен готовый кусок wait for me.', 'Wait to me не працює. Коли чекаєш людину, потрібен готовий зворот wait for me.', 'Wait to me does not work. Use wait for me.'),
        on: tri('Wait on бывает в других смыслах. Нейтральное "подожди меня": wait for me.', 'Wait on буває в інших значеннях. Нейтральне "почекай мене": wait for me.', 'Wait on has other uses. Here use wait for me.'),
        at: tri('Wait at нужен с местом: wait at the station. Здесь человек: wait for me.', 'Wait at потрібен із місцем: wait at the station. Тут людина: wait for me.', 'Wait at goes with a place. For a person, use wait for me.'),
      },
      retryFeedback: [
        tri('Кого ждём?', 'Кого чекаємо?', 'Who are we waiting for?'),
        tri('Человека: for me.', 'Людину: for me.', 'A person: for me.'),
        tri('Готовый кусок: wait for me.', 'Готовий зворот: wait for me.', 'Ready chunk: wait for me.'),
        tri('Ответ: Please wait for me.', 'Відповідь: Please wait for me.', 'Answer: Please wait for me.'),
      ],
      fallbackExplanation: tri('Ждать человека: wait for me.', 'Чекати людину: wait for me.', 'Wait for a person: wait for me.'),
      focusWords: ['wait for', 'me'],
    }),
    verbPatternStep({
      id: 'verb_prep_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'wait_for_bus',
      teachingText: CHUNK_MODEL,
      sentence: 'We are waiting ___ the bus.',
      translation: tri('Мы ждём автобус.', 'Ми чекаємо автобус.', 'We are waiting for the bus.'),
      options: ['to', 'for', 'on', 'at'],
      correctAnswer: 'for',
      correctFeedback: tri('Да. Ждём автобус: waiting for the bus.', 'Так. Чекаємо автобус: waiting for the bus.', 'Yes. Waiting for the bus.'),
      wrong: {
        to: tri('Waiting to the bus не работает. Ждать автобус: waiting for the bus.', 'Waiting to the bus не працює. Чекати автобус: waiting for the bus.', 'Waiting to the bus does not work. Use waiting for the bus.'),
        on: tri('Waiting on the bus может звучать как "ждать в автобусе". Здесь ждём сам автобус: for.', 'Waiting on the bus може звучати як "чекати в автобусі". Тут чекаємо сам автобус: for.', 'Waiting on the bus can sound like location. Here use for.'),
        at: tri('Wait at подходит к месту: at the bus stop. Но ждём автобус: wait for the bus.', 'Wait at підходить до місця: at the bus stop. Але чекаємо автобус: wait for the bus.', 'Wait at goes with a place. Here use wait for the bus.'),
      },
      retryFeedback: [
        tri('Ждём что?', 'Чекаємо що?', 'Waiting for what?'),
        tri('Автобус.', 'Автобус.', 'The bus.'),
        tri('Готовый кусок: waiting for the bus.', 'Готовий зворот: waiting for the bus.', 'Ready chunk: waiting for the bus.'),
        tri('Ответ: We are waiting for the bus.', 'Відповідь: We are waiting for the bus.', 'Answer: We are waiting for the bus.'),
      ],
      fallbackExplanation: tri('Ждать автобус: wait for the bus.', 'Чекати автобус: wait for the bus.', 'Wait for the bus.'),
      focusWords: ['waiting for', 'bus'],
    }),
    verbPatternStep({
      id: 'verb_prep_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'depend_on',
      teachingText: tri(
        'Здесь перевод особенно обманывает: по-русски "зависит от", но английский кусок - depend on.',
        'Тут переклад особливо обманює: українською "залежить від", але англійський зворот - depend on.',
        'Translation is especially tricky here: English uses depend on.',
      ),
      sentence: 'It depends ___ the weather.',
      translation: tri('Это зависит от погоды.', 'Це залежить від погоди.', 'It depends on the weather.'),
      options: ['from', 'on', 'at', 'to'],
      correctAnswer: 'on',
      correctFeedback: tri('Да. Несмотря на "от", английский кусок: depend on.', 'Так. Попри "від", англійський зворот: depend on.', 'Yes. Despite translation, the English chunk is depend on.'),
      wrong: {
        from: tri('Вот ловушка. Русский тянет к from, но английский говорит depend on.', 'Ось пастка. Українська тягне до from, але англійська каже depend on.', 'This is the trap. Translation suggests from, but English uses depend on.'),
        at: tri('Depend at не работает. Нужен кусок depend on.', 'Depend at не працює. Потрібен зворот depend on.', 'Depend at does not work. Use depend on.'),
        to: tri('Depend to не работает. Готовый кусок: depend on.', 'Depend to не працює. Готовий зворот: depend on.', 'Depend to does not work. Use depend on.'),
      },
      retryFeedback: [
        tri('Не верь переводу "от".', 'Не вір перекладу "від".', 'Do not trust the direct translation.'),
        tri('Английский кусок: depend on.', 'Англійський зворот: depend on.', 'English chunk: depend on.'),
        tri('С погодой: depends on the weather.', 'З погодою: depends on the weather.', 'With weather: depends on the weather.'),
        tri('Ответ: It depends on the weather.', 'Відповідь: It depends on the weather.', 'Answer: It depends on the weather.'),
      ],
      fallbackExplanation: tri('Зависит от погоды: depends on the weather.', 'Залежить від погоди: depends on the weather.', 'Depends on the weather.'),
      focusWords: ['depends on', 'weather'],
    }),
    verbPatternStep({
      id: 'verb_prep_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'look_at',
      teachingText: tri(
        'Look at и look for - разные куски. Look at - направить взгляд. Look for - искать.',
        'Look at і look for - різні звороти. Look at - спрямувати погляд. Look for - шукати.',
        'Look at and look for are different chunks. Look at = direct your eyes. Look for = search.',
      ),
      sentence: 'Look ___ the screen.',
      translation: tri('Посмотри на экран.', 'Подивися на екран.', 'Look at the screen.'),
      options: ['to', 'for', 'on', 'at'],
      correctAnswer: 'at',
      correctFeedback: tri('Да. Направить взгляд на экран: look at the screen.', 'Так. Спрямувати погляд на екран: look at the screen.', 'Yes. Direct your eyes at the screen: look at the screen.'),
      wrong: {
        to: tri('Look to бывает в других смыслах. Здесь обычное "посмотри на экран": look at the screen.', 'Look to буває в інших значеннях. Тут звичайне "подивися на екран": look at the screen.', 'Look to has other uses. Here use look at the screen.'),
        for: tri('Look for значит искать. Здесь не искать экран, а смотреть на экран: Look for - искать, look at - смотреть.', 'Look for означає шукати. Тут не шукати екран, а дивитися на екран: look for - шукати, look at - дивитися.', 'Look for means search. Here you need look at the screen.'),
        on: tri('Look on the screen может звучать как "посмотри на экране". Здесь взгляд направлен на экран: look at.', 'Look on the screen може звучати як "подивися на екрані". Тут погляд спрямований на екран: look at.', 'Look on the screen has another meaning. Here use look at.'),
      },
      retryFeedback: [
        tri('Ты ищешь экран или смотришь на него?', 'Ти шукаєш екран чи дивишся на нього?', 'Are you searching for the screen or looking at it?'),
        tri('Смотришь на него.', 'Дивишся на нього.', 'Looking at it.'),
        tri('Готовый кусок: look at the screen.', 'Готовий зворот: look at the screen.', 'Ready chunk: look at the screen.'),
        tri('Ответ: Look at the screen.', 'Відповідь: Look at the screen.', 'Answer: Look at the screen.'),
      ],
      fallbackExplanation: tri('Смотреть на экран: look at the screen.', 'Дивитися на екран: look at the screen.', 'Look at the screen.'),
      focusWords: ['look at', 'screen'],
    }),
    verbPatternStep({
      id: 'verb_prep_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'look_for_vs_look_at',
      teachingText: tri(
        'Если смысл "искать", нужен look for. Если смысл "смотреть на", нужен look at.',
        'Якщо сенс "шукати", потрібен look for. Якщо сенс "дивитися на", потрібен look at.',
        'If the meaning is search, use look for. If the meaning is look at, use look at.',
      ),
      sentence: 'I am looking ___ my keys.',
      translation: tri('Я ищу свои ключи.', 'Я шукаю свої ключі.', 'I am looking for my keys.'),
      options: ['at', 'for', 'to', 'on'],
      correctAnswer: 'for',
      correctFeedback: tri('Да. Искать ключи: looking for my keys.', 'Так. Шукати ключі: looking for my keys.', 'Yes. Search for keys: looking for my keys.'),
      wrong: {
        at: tri('Look at - смотреть на ключи, если они перед тобой. Но здесь ты их ищешь: look for.', 'Look at - дивитися на ключі, якщо вони перед тобою. Але тут ти їх шукаєш: look for.', 'Look at means look at keys if they are in front of you. Here you search: look for.'),
        to: tri('Looking to my keys не даёт смысл "ищу". Нужен кусок looking for my keys.', 'Looking to my keys не дає сенс "шукаю". Потрібен зворот looking for my keys.', 'Looking to my keys does not mean search. Use looking for my keys.'),
        on: tri('Looking on my keys не даёт смысл "ищу". Нужен кусок looking for.', 'Looking on my keys не дає сенс "шукаю". Потрібен зворот looking for.', 'Looking on my keys does not mean search. Use looking for.'),
      },
      retryFeedback: [
        tri('Смысл: искать.', 'Сенс: шукати.', 'Meaning: search.'),
        tri('Искать = look for.', 'Шукати = look for.', 'Search = look for.'),
        tri('Готовый кусок: looking for my keys.', 'Готовий зворот: looking for my keys.', 'Ready chunk: looking for my keys.'),
        tri('Ответ: I am looking for my keys.', 'Відповідь: I am looking for my keys.', 'Answer: I am looking for my keys.'),
      ],
      fallbackExplanation: tri('Искать ключи: looking for my keys.', 'Шукати ключі: looking for my keys.', 'Looking for my keys.'),
      focusWords: ['looking for', 'keys'],
    }),
    verbPatternStep({
      id: 'verb_prep_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'talk_to',
      teachingText: tri(
        'Talk to - человек, с кем говорим. Talk about - тема разговора.',
        'Talk to - людина, з ким говоримо. Talk about - тема розмови.',
        'Talk to = the person. Talk about = the topic.',
      ),
      sentence: 'I need to talk ___ you.',
      translation: tri('Мне нужно поговорить с тобой.', 'Мені потрібно поговорити з тобою.', 'I need to talk to you.'),
      options: ['to', 'for', 'on', 'at'],
      correctAnswer: 'to',
      correctFeedback: tri('Да. Человек, с кем говорим: talk to you.', 'Так. Людина, з ким говоримо: talk to you.', 'Yes. The person you speak with: talk to you.'),
      wrong: {
        for: tri('Talk for you может значить "говорить за тебя". Здесь нужно поговорить с тобой: talk to you.', 'Talk for you може означати "говорити за тебе". Тут треба поговорити з тобою: talk to you.', 'Talk for you can mean speak for you. Here use talk to you.'),
        on: tri('Talk on you не работает для "поговорить с тобой". Нужен кусок talk to you.', 'Talk on you не працює для "поговорити з тобою". Потрібен зворот talk to you.', 'Talk on you does not work here. Use talk to you.'),
        at: tri('Talk at someone звучит как говорить на человека, без нормального диалога. Нейтрально: talk to you.', 'Talk at someone звучить як говорити на людину, без нормального діалогу. Нейтрально: talk to you.', 'Talk at someone sounds one-way. Neutral: talk to you.'),
      },
      retryFeedback: [
        tri('С кем говорим?', 'З ким говоримо?', 'Who are we talking to?'),
        tri('С тобой: to you.', 'З тобою: to you.', 'To you.'),
        tri('Готовый кусок: talk to you.', 'Готовий зворот: talk to you.', 'Ready chunk: talk to you.'),
        tri('Ответ: I need to talk to you.', 'Відповідь: I need to talk to you.', 'Answer: I need to talk to you.'),
      ],
      fallbackExplanation: tri('Поговорить с человеком: talk to you.', 'Поговорити з людиною: talk to you.', 'Talk to you.'),
      focusWords: ['talk to', 'you'],
    }),
    verbPatternStep({
      id: 'verb_prep_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'think_about',
      teachingText: tri(
        'About часто нужен, когда после действия идёт тема: think about, talk about, ask about.',
        'About часто потрібен, коли після дії йде тема: think about, talk about, ask about.',
        'About often appears before a topic: think about, talk about, ask about.',
      ),
      sentence: 'Think ___ your answer.',
      translation: tri('Подумай о своём ответе.', 'Подумай про свою відповідь.', 'Think about your answer.'),
      options: ['to', 'for', 'about', 'at'],
      correctAnswer: 'about',
      correctFeedback: tri('Да. Тема мысли: think about your answer.', 'Так. Тема думки: think about your answer.', 'Yes. Topic of thought: think about your answer.'),
      wrong: {
        to: tri('Think to your answer не работает. Тема мысли идёт через about: think about your answer.', 'Think to your answer не працює. Тема думки йде через about: think about your answer.', 'Think to your answer does not work. Use think about.'),
        for: tri('Think for бывает в других кусках, но "подумай о" здесь: think about.', 'Think for буває в інших зворотух, але "подумай про" тут: think about.', 'Think for has other uses. Here use think about.'),
        at: tri('Think at не работает для темы мысли. Нужен кусок think about.', 'Think at не працює для теми думки. Потрібен зворот think about.', 'Think at does not work for a topic. Use think about.'),
      },
      retryFeedback: [
        tri('О чём думаем?', 'Про що думаємо?', 'What are we thinking about?'),
        tri('О твоём ответе.', 'Про твою відповідь.', 'Your answer.'),
        tri('Готовый кусок: think about your answer.', 'Готовий зворот: think about your answer.', 'Ready chunk: think about your answer.'),
        tri('Ответ: Think about your answer.', 'Відповідь: Think about your answer.', 'Answer: Think about your answer.'),
      ],
      fallbackExplanation: tri('Думать о теме: think about your answer.', 'Думати про тему: think about your answer.', 'Think about your answer.'),
      focusWords: ['think about', 'answer'],
    }),
    verbPatternStep({
      id: 'verb_prep_contrast_006',
      order: 9,
      difficulty: 'contrast',
      targetSkill: 'talk_about',
      teachingText: tri(
        'Talk to - с кем говорим. Talk about - о чём говорим.',
        'Talk to - з ким говоримо. Talk about - про що говоримо.',
        'Talk to = the person. Talk about = the topic.',
      ),
      sentence: 'We talked ___ the problem.',
      translation: tri('Мы поговорили о проблеме.', 'Ми поговорили про проблему.', 'We talked about the problem.'),
      options: ['to', 'for', 'about', 'at'],
      correctAnswer: 'about',
      correctFeedback: tri('Да. Проблема здесь тема разговора: talked about the problem.', 'Так. Проблема тут тема розмови: talked about the problem.', 'Yes. The problem is the topic: talked about the problem.'),
      wrong: {
        to: tri('Talk to нужен для человека. Проблема здесь тема: talk about the problem.', 'Talk to потрібен для людини. Проблема тут тема: talk about the problem.', 'Talk to is for a person. Here the problem is the topic: talk about.'),
        for: tri('Talk for не передаёт "о проблеме". Нужен кусок talk about.', 'Talk for не передає "про проблему". Потрібен зворот talk about.', 'Talk for does not mean about a problem. Use talk about.'),
        at: tri('Talk at the problem не работает. О теме говорим через about.', 'Talk at the problem не працює. Про тему говоримо через about.', 'Talk at the problem does not work. Use talk about.'),
      },
      retryFeedback: [
        tri('О чём говорили?', 'Про що говорили?', 'What did we talk about?'),
        tri('О проблеме.', 'Про проблему.', 'The problem.'),
        tri('Готовый кусок: talked about the problem.', 'Готовий зворот: talked about the problem.', 'Ready chunk: talked about the problem.'),
        tri('Ответ: We talked about the problem.', 'Відповідь: We talked about the problem.', 'Answer: We talked about the problem.'),
      ],
      fallbackExplanation: tri('Говорить о теме: talk about the problem.', 'Говорити про тему: talk about the problem.', 'Talk about the problem.'),
      focusWords: ['talk about', 'problem'],
    }),
    verbPatternStep({
      id: 'verb_prep_mixed_001',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'ask_for',
      teachingText: tri(
        'Ask for - просить что-то. Ask about - спрашивать о теме.',
        'Ask for - просити щось. Ask about - питати про тему.',
        'Ask for = request something. Ask about = ask about a topic.',
      ),
      sentence: 'She asked ___ help.',
      translation: tri('Она попросила помощи.', 'Вона попросила допомоги.', 'She asked for help.'),
      options: ['to', 'for', 'about', 'at'],
      correctAnswer: 'for',
      correctFeedback: tri('Да. Просить помощи: ask for help.', 'Так. Просити допомоги: ask for help.', 'Yes. Request help: ask for help.'),
      wrong: {
        to: tri('Ask to help - другой кусок. Просить помощь: ask for help.', 'Ask to help - інший зворот. Просити допомогу: ask for help.', 'Ask to help is another chunk. Request help: ask for help.'),
        about: tri('Ask about значит спрашивать о теме. Здесь она просила помощь: ask for help.', 'Ask about означає питати про тему. Тут вона просила допомогу: ask for help.', 'Ask about means ask about a topic. Here she requested help: ask for help.'),
        at: tri('Ask at help не работает. Нужен кусок ask for help.', 'Ask at help не працює. Потрібен зворот ask for help.', 'Ask at help does not work. Use ask for help.'),
      },
      retryFeedback: [
        tri('Она спрашивала о помощи или просила помощь?', 'Вона питала про допомогу чи просила допомогу?', 'Did she ask about help or request help?'),
        tri('Просила.', 'Просила.', 'Requested.'),
        tri('Готовый кусок: ask for help.', 'Готовий зворот: ask for help.', 'Ready chunk: ask for help.'),
        tri('Ответ: She asked for help.', 'Відповідь: She asked for help.', 'Answer: She asked for help.'),
      ],
      fallbackExplanation: tri('Просить помощь: ask for help.', 'Просити допомогу: ask for help.', 'Ask for help.'),
      focusWords: ['ask for', 'help'],
    }),
    verbPatternStep({
      id: 'verb_prep_mixed_002',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'believe_in',
      teachingText: tri(
        'Believe in - верить в человека, идею или себя. Это тоже готовый кусок.',
        'Believe in - вірити в людину, ідею або себе. Це теж готовий зворот.',
        'Believe in = have faith in someone, something, or yourself.',
      ),
      sentence: 'You have to believe ___ yourself.',
      translation: tri('Ты должен верить в себя.', 'Ти маєш вірити в себе.', 'You have to believe in yourself.'),
      options: ['to', 'for', 'in', 'at'],
      correctAnswer: 'in',
      correctFeedback: tri('Да. Верить в себя: believe in yourself.', 'Так. Вірити в себе: believe in yourself.', 'Yes. Believe in yourself.'),
      wrong: {
        to: tri('Believe to yourself не работает. Готовый кусок: believe in yourself.', 'Believe to yourself не працює. Готовий зворот: believe in yourself.', 'Believe to yourself does not work. Use believe in yourself.'),
        for: tri('Believe for yourself не передаёт "верить в себя". Нужен кусок believe in yourself.', 'Believe for yourself не передає "вірити в себе". Потрібен зворот believe in yourself.', 'Believe for yourself does not mean believe in yourself.'),
        at: tri('Believe at yourself не работает. Нужен кусок believe in.', 'Believe at yourself не працює. Потрібен зворот believe in.', 'Believe at yourself does not work. Use believe in.'),
      },
      retryFeedback: [
        tri('Во что верить?', 'У що вірити?', 'Believe in what?'),
        tri('В себя.', 'У себе.', 'Yourself.'),
        tri('Готовый кусок: believe in yourself.', 'Готовий зворот: believe in yourself.', 'Ready chunk: believe in yourself.'),
        tri('Ответ: You have to believe in yourself.', 'Відповідь: You have to believe in yourself.', 'Answer: You have to believe in yourself.'),
      ],
      fallbackExplanation: tri('Верить в себя: believe in yourself.', 'Вірити в себе: believe in yourself.', 'Believe in yourself.'),
      focusWords: ['believe in', 'yourself'],
    }),
    verbPatternStep({
      id: 'verb_prep_mixed_003',
      order: 12,
      difficulty: 'mixed',
      targetSkill: 'ask_about_topic',
      teachingText: tri(
        'Ask about - спросить о теме. Ask for - попросить что-то.',
        'Ask about - запитати про тему. Ask for - попросити щось.',
        'Ask about = ask about a topic. Ask for = request something.',
      ),
      sentence: 'He asked ___ the price.',
      translation: tri('Он спросил о цене.', 'Він запитав про ціну.', 'He asked about the price.'),
      options: ['for', 'about', 'to', 'at'],
      correctAnswer: 'about',
      correctFeedback: tri('Да. Цена здесь тема вопроса: asked about the price.', 'Так. Ціна тут тема питання: asked about the price.', 'Yes. The price is the topic: asked about the price.'),
      wrong: {
        for: tri('Ask for the price может значить попросить назвать цену. Здесь именно спросил о цене: asked about the price.', 'Ask for the price може означати попросити назвати ціну. Тут саме запитав про ціну: asked about the price.', 'Ask for the price can mean request the price. For the topic, use asked about the price.'),
        to: tri('Asked to the price не работает. О теме вопроса: asked about the price.', 'Asked to the price не працює. Про тему питання: asked about the price.', 'Asked to the price does not work. Use asked about the price.'),
        at: tri('Asked at the price не работает. Нужен кусок asked about the price.', 'Asked at the price не працює. Потрібен зворот asked about the price.', 'Asked at the price does not work. Use asked about the price.'),
      },
      retryFeedback: [
        tri('Он просил цену или спрашивал о цене?', 'Він просив ціну чи питав про ціну?', 'Did he request the price or ask about it?'),
        tri('Спрашивал о цене.', 'Питав про ціну.', 'Asked about it.'),
        tri('Готовый кусок: asked about the price.', 'Готовий зворот: asked about the price.', 'Ready chunk: asked about the price.'),
        tri('Ответ: He asked about the price.', 'Відповідь: He asked about the price.', 'Answer: He asked about the price.'),
      ],
      fallbackExplanation: tri('Спросить о цене: ask about the price.', 'Запитати про ціну: ask about the price.', 'Ask about the price.'),
      focusWords: ['ask about', 'price'],
    }),
    verbPatternStep({
      id: 'verb_prep_mixed_004',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_listen_wait',
      teachingText: tri(
        'Собираем два самых частых куска: listen to и wait for.',
        'Збираємо два найчастіші звороти: listen to і wait for.',
        'Combine two frequent chunks: listen to and wait for.',
      ),
      sentence: 'Choose the correct pair.',
      translation: tri('Выбери правильную пару.', 'Обери правильну пару.', 'Choose the correct pair.'),
      options: ['listen to music / wait for me', 'listen music / wait me', 'listen for music / wait to me', 'listen at music / wait on me'],
      correctAnswer: 'listen to music / wait for me',
      correctFeedback: tri('Да. Listen to music. Wait for me.', 'Так. Listen to music. Wait for me.', 'Yes. Listen to music. Wait for me.'),
      wrong: {
        'listen music / wait me': tri('В обеих фразах пропали хвосты. Нужны куски listen to и wait for.', 'В обох фразах зникли хвости. Потрібні звороти listen to і wait for.', 'Both chunks are missing the small word: listen to and wait for.'),
        'listen for music / wait to me': tri('Listen for имеет другой смысл, а wait to me не работает. Нужна пара listen to / wait for.', 'Listen for має інший сенс, а wait to me не працює. Потрібна пара listen to / wait for.', 'Listen for has another meaning, and wait to me does not work. Use listen to / wait for.'),
        'listen at music / wait on me': tri('Listen at music не работает. Wait on me не нейтрально для "подожди меня". Нужна пара listen to / wait for.', 'Listen at music не працює. Wait on me не нейтрально для "почекай мене". Потрібна пара listen to / wait for.', 'Listen at music does not work. Use listen to / wait for.'),
      },
      retryFeedback: [
        tri('Первый кусок: listen to.', 'Перший зворот: listen to.', 'First chunk: listen to.'),
        tri('Второй кусок: wait for.', 'Другий зворот: wait for.', 'Second chunk: wait for.'),
        tri('Итого: listen to music / wait for me.', 'Разом: listen to music / wait for me.', 'Together: listen to music / wait for me.'),
        tri('Ответ: listen to music / wait for me.', 'Відповідь: listen to music / wait for me.', 'Answer: listen to music / wait for me.'),
      ],
      fallbackExplanation: tri('Listen to music. Wait for me.', 'Listen to music. Wait for me.', 'Listen to music. Wait for me.'),
      focusWords: ['listen to', 'wait for'],
    }),
    verbPatternStep({
      id: 'verb_prep_mixed_005',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_depend_look',
      teachingText: tri(
        'Теперь две ловушки перевода: depend on и look at.',
        'Тепер дві пастки перекладу: depend on і look at.',
        'Now two translation traps: depend on and look at.',
      ),
      sentence: 'Choose the correct pair.',
      translation: tri('Выбери правильную пару.', 'Обери правильну пару.', 'Choose the correct pair.'),
      options: ['depend on the situation / look at the screen', 'depend from the situation / look on the screen', 'depend to the situation / look for the screen', 'depend at the situation / look to the screen'],
      correctAnswer: 'depend on the situation / look at the screen',
      correctFeedback: tri('Да. Depend on. Look at.', 'Так. Depend on. Look at.', 'Yes. Depend on. Look at.'),
      wrong: {
        'depend from the situation / look on the screen': tri('По-русски тянет к "from", но английский кусок depend on. Смотреть на экран: look at.', 'Українською тягне до "from", але англійський зворот depend on. Дивитися на екран: look at.', 'Translation suggests from, but English uses depend on. Looking at a screen = look at.'),
        'depend to the situation / look for the screen': tri('Depend to не работает. Look for значит искать экран, а не смотреть на экран.', 'Depend to не працює. Look for означає шукати екран, а не дивитися на екран.', 'Depend to does not work. Look for means search, not look at.'),
        'depend at the situation / look to the screen': tri('Depend at не работает. Look to the screen не даёт обычный смысл "смотреть на экран".', 'Depend at не працює. Look to the screen не дає звичайний сенс "дивитися на екран".', 'Depend at does not work. Look to the screen does not mean look at the screen here.'),
      },
      retryFeedback: [
        tri('Первый кусок: depend on.', 'Перший зворот: depend on.', 'First chunk: depend on.'),
        tri('Второй кусок: look at.', 'Другий зворот: look at.', 'Second chunk: look at.'),
        tri('Итого: depend тянет on, а look в значении "смотреть на" тянет at.', 'Разом: depend тягне on, а look у значенні "дивитися на" тягне at.', 'Together: depend on the situation / look at the screen.'),
        tri('Ответ держится на двух связках: depend on для зависимости и look at для взгляда на экран.', 'Відповідь тримається на двох звʼязках: depend on для залежності і look at для погляду на екран.', 'Answer: depend on the situation / look at the screen.'),
      ],
      fallbackExplanation: tri('Depend on. Look at.', 'Depend on. Look at.', 'Depend on. Look at.'),
      focusWords: ['depend on', 'look at'],
    }),
    verbPatternStep({
      id: 'verb_prep_mixed_006',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_sentence_correction',
      teachingText: tri(
        'Финальная сборка: три действия, три маленьких хвоста.',
        'Фінальна збірка: три дії, три маленькі хвости.',
        'Final build: three actions, three small tails.',
      ),
      sentence: 'Choose the correct sentence.',
      translation: tri('Выбери правильное предложение.', 'Обери правильне речення.', 'Choose the correct sentence.'),
      options: [
        'I listened to him, waited for him, and talked to him.',
        'I listened him, waited him, and talked him.',
        'I listened at him, waited to him, and talked for him.',
        'I listened for him, waited at him, and talked on him.',
      ],
      correctAnswer: 'I listened to him, waited for him, and talked to him.',
      correctFeedback: tri('Да. Listen to, wait for, talk to.', 'Так. Listen to, wait for, talk to.', 'Yes. Listen to, wait for, talk to.'),
      wrong: {
        'I listened him, waited him, and talked him.': tri('После listen, wait и talk здесь нужны маленькие хвосты: to, for, to.', 'Після listen, wait і talk тут потрібні маленькі хвости: to, for, to.', 'After listen, wait, and talk, you need: to, for, to.'),
        'I listened at him, waited to him, and talked for him.': tri('Хвосты выбраны неверно. Нужны куски: listened to, waited for, talked to.', 'Хвости обрані неправильно. Потрібні звороти: listened to, waited for, talked to.', 'The small words are wrong. Use listened to, waited for, talked to.'),
        'I listened for him, waited at him, and talked on him.': tri('Listen for, wait at и talk on дают другие или неправильные смыслы. Нужна базовая цепочка: listened to, waited for, talked to.', 'Listen for, wait at і talk on дають інші або неправильні сенси. Потрібен базовий ланцюжок: listened to, waited for, talked to.', 'Listen for, wait at, and talk on have other or wrong meanings. Use listened to, waited for, talked to.'),
      },
      retryFeedback: [
        tri('Сначала listen to.', 'Спочатку listen to.', 'First: listen to.'),
        tri('Потом wait for.', 'Потім wait for.', 'Then: wait for.'),
        tri('Потом talk to.', 'Потім talk to.', 'Then: talk to.'),
        tri('Ответ собирается из трех привычных связок: listen to, wait for и talk to.', 'Відповідь збирається з трьох звичних звʼязок: listen to, wait for і talk to.', 'Answer: I listened to him, waited for him, and talked to him.'),
      ],
      fallbackExplanation: tri('Цепочка здесь не по переводу, а по связкам после глаголов: слушал кого-то через to, ждал кого-то через for, разговаривал с кем-то через to.', 'Ланцюжок тут не за перекладом, а за звʼязками після дієслів: слухав когось через to, чекав когось через for, говорив із кимось через to.', 'The chain: listened to him, waited for him, talked to him.'),
      focusWords: ['listened to', 'waited for', 'talked to'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'listen_missing_to_error',
      'wait_missing_for_error',
      'depend_wrong_preposition_error',
      'look_wrong_preposition_error',
      'talk_wrong_preposition_error',
      'think_wrong_preposition_error',
      'ask_for_error',
      'believe_in_error',
      'translation_based_preposition_error',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri(
      'Сначала найди действие и вспомни его готовый хвост.',
      'Спочатку знайди дію і згадай її готовий хвіст.',
      'Primero encuentra la accion y recuerda su cola fija.',
    ),
    depth2: tri(
      'Не выбирай по переводу. Выбирай по готовому куску.',
      'Не обирай за перекладом. Обирай за готовим зворотом.',
      'No elijas por traduccion. Elige por el bloque fijo.',
    ),
    depth3: tri(
      'Сравни ошибку и нормальный кусок: listen music -> listen to music.',
      'Порівняй помилку і нормальний зворот: listen music -> listen to music.',
      'Compara el error y el bloque normal: listen music -> listen to music.',
    ),
    depth4: tri(
      'Почти подсказка: система покажет нужный готовый кусок.',
      'Майже підказка: система покаже потрібний готовий зворот.',
      'Casi una pista: el sistema muestra el bloque necesario.',
    ),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri(
        'Стоп. Не переводим маленькое слово отдельно. Вспоминаем кусок: listen to, wait for, depend on, look at, talk to, think about, ask for, believe in.',
        'Стоп. Не перекладаємо маленьке слово окремо. Згадуємо зворот: listen to, wait for, depend on, look at, talk to, think about, ask for, believe in.',
        'Para. No traduzcas la palabra pequena por separado. Recuerda el bloque: listen to, wait for, depend on, look at, talk to, think about, ask for, believe in.',
      ),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_chunk_hint_then_retry',
      card: tri(
        'Подсказка: сначала система покажет действие, потом готовые куски рядом с ним.',
        'Підказка: спочатку система покаже дію, потім готові звороти поруч із нею.',
        'Pista: primero el sistema muestra la accion y despues los bloques fijos que van con ella.',
      ),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri(
        'Режим с подсказками: выбираем не правило, а готовый речевой кусок.',
        'Режим із підказками: обираємо не правило, а готовий мовний зворот.',
        'Modo guiado: elegimos el bloque de habla ya listo, no una regla suelta.',
      ),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      {
        id: 'guided_verb_prep_001',
        prompt: tri('Какой кусок звучит нормально?', 'Який зворот звучить нормально?', 'Que bloque suena normal?'),
        options: ['listen to music', 'listen music'],
        correctIndex: 0,
        thenReturnToExerciseId: 'verb_prep_easy_001',
      },
      {
        id: 'guided_verb_prep_002',
        prompt: tri('Какой кусок для "подожди меня"?', 'Який зворот для "почекай мене"?', 'Que bloque significa "esperame"?'),
        options: ['wait for me', 'wait to me'],
        correctIndex: 0,
        thenReturnToExerciseId: 'verb_prep_easy_002',
      },
      {
        id: 'guided_verb_prep_003',
        prompt: tri('Какой кусок после depend?', 'Який зворот після depend?', 'Que bloque va con depend?'),
        options: ['depend from', 'depend on'],
        correctIndex: 1,
        thenReturnToExerciseId: 'verb_prep_contrast_001',
      },
      {
        id: 'guided_verb_prep_004',
        prompt: tri('Look at - это смотреть или искать?', 'Look at - це дивитися чи шукати?', 'Look at: mirar o buscar?'),
        options: ['смотреть', 'искать'],
        correctIndex: 0,
        thenReturnToExerciseId: 'verb_prep_contrast_002',
      },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'preposition',
    microDiagnosisId: 'preposition_common_verb_patterns',
    diagnosisLabel: tri(
      'Listen to / Wait for',
      'Listen to / Wait for',
      'Listen to / Wait for: bloques',
    ),
    contrastSet: CONTRAST,
    focusWords: ['listen to', 'wait for', 'depend on', 'look at', 'talk to', 'think about', 'ask for', 'believe in'],
    focusPatterns: [
      'listen_to',
      'wait_for',
      'wait_for_bus',
      'depend_on',
      'look_at',
      'look_for_vs_look_at',
      'talk_to',
      'think_about',
      'talk_about',
      'ask_for',
      'believe_in',
      'ask_about_topic',
      'mixed_listen_wait',
      'mixed_depend_look',
      'mixed_sentence_correction',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyLevel: 2,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 3,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_preposition_common_verb_patterns_start',
    answer: 'diagnosis_training_preposition_common_verb_patterns_answer',
    mastery: 'diagnosis_training_preposition_common_verb_patterns_mastery',
    recovery: 'diagnosis_training_preposition_common_verb_patterns_recovery',
    onStart: 'diagnosis_training_started',
    onCorrect: 'diagnosis_training_answer_correct',
    onWrong: 'diagnosis_training_answer_wrong',
    onDepthIncrease: 'diagnosis_training_feedback_depth_increased',
    onGuidedMode: 'diagnosis_training_guided_mode_started',
    onMastery: 'diagnosis_training_mastered',
    onSmartTrainerOpen: 'diagnosis_training_smart_trainer_opened',
    payload: {
      category: 'preposition',
      microDiagnosisId: 'preposition_common_verb_patterns',
      contrastSet: CONTRAST,
      logExactToken: true,
      logMistakeType: true,
      logExerciseId: true,
      logAttemptCount: true,
      logFeedbackDepth: true,
      logVerbPattern: true,
      logPreposition: true,
    },
  },
  routing: {
    diagnosisTrainerRoute: '/problem_coach?category=preposition&microDiagnosisId=preposition_common_verb_patterns',
    problemCoachRoute: '/problem_coach?category=preposition&microDiagnosisId=preposition_common_verb_patterns',
    smartTrainerRoute: '/problem_coach?category=preposition&microDiagnosisId=preposition_common_verb_patterns',
    fallbackIfTrainingMissing: '/problem_coach?category=preposition',
  },
  qualityChecklist: {
    hasStableId: true,
    hasCategory: true,
    hasMultilingualTitle: true,
    hasPlainDiagnosisText: true,
    hasMentalModel: true,
    hasContrastSet: true,
    hasAtLeastSixExamples: true,
    hasAtLeastTwelveExercises: true,
    hasEasyContrastMixedStructure: true,
    hasDistractorSpecificFeedback: true,
    hasRetryFeedbackLevels: true,
    hasGuidedModeForRepeatedMistakes: true,
    hasMasteryRules: true,
    hasSmartTrainerConfig: true,
    hasAnalyticsPayload: true,
    hasFallbackRoute: true,
  },
};
