// JESSE_REWORKED_PERSONAL_TRAINING
// This file is protected from legacy replacement unless this exact id is being rebuilt.

import type { DiagnosisTraining, DiagnosisTrainingStep, TriText } from './diagnosis_training_types';

const tri = (ru: string, uk = ru, es = ru): TriText => ({ ru, uk, es });

const CONTRAST = [
  'very + adjective',
  'really + adjective',
  'quite + adjective',
  'gradable adjective',
  'strong adjective',
  'intensifier position',
  'too vs very',
];

function makeStep(input: {
  id: string;
  order: number;
  difficulty: DiagnosisTrainingStep['difficulty'];
  targetSkill: string;
  sentence: string;
  translation: TriText;
  options: string[];
  correctAnswer: string;
  correctFeedback: TriText;
  wrong: Record<string, TriText>;
  clue: TriText;
  finalHint: TriText;
  focusWords: string[];
}): DiagnosisTrainingStep {
  return {
    id: input.id,
    order: input.order,
    difficulty: input.difficulty,
    type: 'single_choice',
    targetSkill: input.targetSkill,
    translation: input.translation,
    explanationBlock: tri(
      'Эти слова стоят перед качеством, но дают разный тон. Very - нейтральное "очень". Really - сильнее и разговорнее. Quite - мягкое "довольно". Too - уже перебор или проблема.',
      'Ці слова стоять перед якістю, але дають різний тон. Very - нейтральне "дуже". Really - сильніше й розмовніше. Quite - мʼяке "доволі". Too - уже перебір або проблема.',
      'Very, really, and quite intensify the next word, but with different tone. Too marks a problem.',
    ),
    microTask: tri(
      'Выбери живой кусок: very, really, quite или too.',
      'Обери живий шматок: very, really, quite або too.',
      'Choose the natural chunk: very, really, quite, or too.',
    ),
    sentence: input.sentence,
    answerOptions: input.options.map((text) => ({ id: text, text })),
    correctAnswerId: input.correctAnswer,
    correctIndex: input.options.findIndex((option) => option === input.correctAnswer),
    correctFeedback: input.correctFeedback,
    wrongFeedbackByOption: Object.fromEntries(
      input.options
        .filter((option) => option !== input.correctAnswer)
        .map((option) => [
          option,
          input.wrong[option] ??
            tri(
              `Почти, но здесь нужен другой кусок: ${input.correctAnswer}.`,
              `Майже, але тут потрiбен iнший шматок: ${input.correctAnswer}.`,
              `Almost. Use: ${input.correctAnswer}.`,
            ),
        ]),
    ),
    retryFeedback: [
      input.clue,
      tri(
        'Сначала поймай оттенок. Very = просто очень. Really = живее и сильнее в разговоре. Quite = довольно, часто мягче. Too = слишком, уже есть проблема.',
        'Спочатку злови вiдтiнок. Very = просто дуже. Really = живiше й сильнiше в розмовi. Quite = доволi, часто мʼякше. Too = занадто, вже є проблема.',
        'Very = neutral strength. Really = stronger and more conversational. Quite = moderate. Too = excessive/problem.',
      ),
      tri(
        'Теперь проверь порядок: усилитель должен стоять перед словом, которое он усиливает.',
        'Тепер перевiр порядок: пiдсилювач має стояти перед словом, яке вiн пiдсилює.',
        input.finalHint.es,
      ),
      tri(
        'Здесь решает не перевод, а оттенок и место усилителя.',
        'Тут вирiшує не переклад, а вiдтiнок i мiсце пiдсилювача.',
        `Answer: ${input.correctAnswer}.`,
      ),
    ],
    fallbackExplanation: tri(
      'Сначала выбери тон: нейтрально, живее, мягче или слишком много. Потом ставь усилитель перед словом, которое он усиливает.',
      'Спочатку обери тон: нейтрально, живіше, мʼякше або занадто багато. Потім став підсилювач перед словом, яке він підсилює.',
      'Chunks: very useful, really tired, quite good, quite difficult, very hot, too hot.',
    ),
    focusWords: input.focusWords,
  };
}

export const MODIFIER_VERY_REALLY_QUITE_TRAINING: DiagnosisTraining = {
  id: 'modifier_very_really_quite',
  category: 'modifier',
  version: '1.0.0',
  status: 'active',
  priority: 35,
  supportedLocales: ['ru', 'uk'],
  title: tri(
    'Very / Really / Quite: оттенки усиления',
    'Very / Really / Quite: відтінки підсилення',
    'Very / Really / Quite',
  ),
  shortTitle: tri('Very / Really / Quite', 'Very / Really / Quite', 'Very / Really / Quite'),
  shortDiagnosis: tri(
    'Ты знаешь very, really и quite, но выбираешь их как одно и то же "очень". Из-за этого фраза звучит либо слишком резко, либо неестественно.',
    'Ти знаєш very, really i quite, але обираєш їх як одне й те саме "дуже". Через це фраза звучить або занадто рiзко, або неприродно.',
    'You treat very, really, and quite as the same word, so the tone breaks.',
  ),
  diagnosisText: tri(
    'Проблема не в том, что ты не знаешь перевод. Проблема в оттенке. Very useful - спокойно и нейтрально. Really useful - живее, как в разговоре. Quite useful - положительно, но мягче. А too useful уже звучит как перебор, будто полезности стало слишком много.',
    'Проблема не в тому, що ти не знаєш переклад. Проблема у вiдтiнку. Very useful - спокiйно й нейтрально. Really useful - живiше, як у розмовi. Quite useful - позитивно, але мʼякше. А too useful вже звучить як перебiр, нiби корисностi стало забагато.',
    'The issue is tone: very useful is neutral, really useful is conversational, quite useful is softer, and too useful sounds excessive.',
  ),
  mentalModel: tri(
    'Не переводи все как "очень". Выбирай настроение фразы. Very - обычное усиление. Really - живое усиление. Quite - осторожная положительная оценка. Too - проблема или перебор.',
    'Не перекладай усе як "дуже". Обирай настрiй фрази. Very - звичайне пiдсилення. Really - живе пiдсилення. Quite - обережна позитивна оцiнка. Too - проблема або перебiр.',
    'Do not translate all of them as very. Choose the tone: neutral, conversational, softer, or excessive.',
  ),
  contrastSet: CONTRAST,
  coreRule: tri(
    'Very обычно просто усиливает. Really звучит живее. Quite часто смягчает оценку. Too показывает, что качества уже слишком много и появилась проблема.',
    'Very зазвичай просто підсилює. Really звучить живіше. Quite часто помʼякшує оцінку. Too показує, що якості вже занадто багато і зʼявилася проблема.',
    'Chunks: very useful, really tired, quite good, quite difficult. Very hot is strong; too hot is a problem.',
  ),
  whatUserMustLearn: {
    ru: [
      'Very звучит нейтрально: very useful, very fast, very important.',
      'Really звучит живее и разговорнее: really useful, really tired, really interesting.',
      'Quite часто делает оценку мягче: quite good, quite difficult, quite interesting.',
      'Very не равно too. Very hot - очень горячий. Too hot - слишком горячий, есть проблема.',
      'Не говори very much useful. Нормально: very useful.',
      'Не говори really much tired. Нормально: really tired.',
      'Не говори quite much difficult. Нормально: quite difficult.',
      'Не ставь усилитель после слова: не useful very, а very useful.',
    ],
    uk: [
      'Very звучить нейтрально: very useful, very fast, very important.',
      'Really звучить живiше й розмовнiше: really useful, really tired, really interesting.',
      'Quite часто робить оцiнку мʼякшою: quite good, quite difficult, quite interesting.',
      'Very не дорiвнює too. Very hot - дуже гарячий. Too hot - занадто гарячий, є проблема.',
      'Не кажи very much useful. Нормально: very useful.',
      'Не кажи really much tired. Нормально: really tired.',
      'Не кажи quite much difficult. Нормально: quite difficult.',
      'Не став пiдсилювач пiсля слова: не useful very, а very useful.',
    ],
    es: [
      'Very is neutral: very useful.',
      'Really is more conversational: really tired.',
      'Quite is often softer: quite good.',
      'Very is not too: very hot vs too hot.',
      'Use very useful, not very much useful.',
      'Use really tired, not really much tired.',
    ],
  },
  examples: [
    {
      en: 'This lesson is very useful.',
      ru: 'Этот урок очень полезный.',
      uk: 'Цей урок дуже корисний.',
      es: 'This lesson is very useful.',
      why: tri('Very useful - нейтральное усиление.', 'Very useful - нейтральне пiдсилення.', 'Very useful is neutral.'),
    },
    {
      en: 'This lesson is really useful.',
      ru: 'Этот урок реально полезный.',
      uk: 'Цей урок реально корисний.',
      es: 'This lesson is really useful.',
      why: tri('Really useful звучит живее и разговорнее.', 'Really useful звучить живiше й розмовнiше.', 'Really useful is more conversational.'),
    },
    {
      en: 'The lesson was quite good.',
      ru: 'Урок был довольно хорошим.',
      uk: 'Урок був доволi хорошим.',
      es: 'The lesson was quite good.',
      why: tri('Quite good - положительно, но без сильного восторга.', 'Quite good - позитивно, але без сильного захвату.', 'Quite good is positive but softer.'),
    },
    {
      en: 'I am really tired.',
      ru: 'Я реально устал.',
      uk: 'Я реально втомився.',
      es: 'I am really tired.',
      why: tri('Really tired звучит естественно в живой речи.', 'Really tired звучить природно в живiй мовi.', 'Really tired is natural in conversation.'),
    },
    {
      en: 'The test was quite difficult.',
      ru: 'Тест был довольно сложным.',
      uk: 'Тест був доволi складним.',
      es: 'The test was quite difficult.',
      why: tri('Quite difficult звучит мягче, чем really difficult.', 'Quite difficult звучить мʼякше, нiж really difficult.', 'Quite difficult is softer than really difficult.'),
    },
    {
      en: 'The coffee is very hot, but I can drink it.',
      ru: 'Кофе очень горячий, но я могу его пить.',
      uk: 'Кава дуже гаряча, але я можу її пити.',
      es: 'The coffee is very hot, but I can drink it.',
      why: tri('Very hot - сильная оценка, но не обязательно проблема.', 'Very hot - сильна оцiнка, але не обовʼязково проблема.', 'Very hot is strong, not necessarily a problem.'),
    },
    {
      en: 'The coffee is too hot to drink.',
      ru: 'Кофе слишком горячий, чтобы его пить.',
      uk: 'Кава занадто гаряча, щоб її пити.',
      es: 'The coffee is too hot to drink.',
      why: tri('Too hot - уже проблема.', 'Too hot - уже проблема.', 'Too hot is a problem.'),
    },
  ],
  introBlocks: [
    {
      id: 'intro_problem',
      type: 'diagnosis',
      text: tri(
        'Здесь ломается не грамматика, а тон. Very, really, quite и too стоят рядом, но звучат по-разному.',
        'Тут ламається не граматика, а тон. Very, really, quite i too стоять поруч, але звучать по-рiзному.',
        'This is about tone, not just grammar.',
      ),
    },
    {
      id: 'intro_rule',
      type: 'rule',
      text: tri(
        'Запомни четыре пары: very useful, really tired, quite good, too hot.',
        'Запамʼятай чотири пари: very useful, really tired, quite good, too hot.',
        'Remember: very useful, really tired, quite good, too hot.',
      ),
    },
    {
      id: 'intro_tone_scale',
      type: 'contrast',
      text: tri(
        'Держи шкалу тона: very просто усиливает, really звучит эмоциональнее, quite делает мягче или осторожнее, too уже показывает проблему.',
        'Тримай шкалу тону: very просто підсилює, really звучить емоційніше, quite робить мʼякше або обережніше, too вже показує проблему.',
        'Tone scale: very strengthens, really feels more emotional, quite softens, and too usually shows a problem.',
      ),
    },
  ],
  steps: [
    makeStep({
      id: 'modifier_vrq_easy_001',
      order: 1,
      difficulty: 'easy',
      targetSkill: 'very_useful_basic',
      sentence: 'This tool is ___ useful.',
      translation: tri('Этот инструмент очень полезный.', 'Цей iнструмент дуже корисний.', 'This tool is very useful.'),
      options: ['very', 'very much', 'many', 'too many'],
      correctAnswer: 'very',
      correctFeedback: tri('Да. Очень полезный = very useful.', 'Так. Дуже корисний = very useful.', 'Yes. Very useful.'),
      wrong: {
        'very much': tri('Very much useful звучит лишним. Нужен короткий блок very useful.', 'Very much useful звучить зайвим. Потрiбен короткий блок very useful.', 'Use very useful.'),
        many: tri('Many не усиливает useful. Нужен блок very useful.', 'Many не пiдсилює useful. Потрiбен блок very useful.', 'Use very useful.'),
        'too many': tri('Too many не ставится перед useful. Нормально: very useful.', 'Too many не ставиться перед useful. Нормально: very useful.', 'Use very useful.'),
      },
      clue: tri('Просто "очень полезный" - very useful.', 'Просто "дуже корисний" - very useful.', 'Very useful.'),
      finalHint: tri('Фраза: This tool is very useful.', 'Фраза: This tool is very useful.', 'Sentence: This tool is very useful.'),
      focusWords: ['very useful', 'very'],
    }),
    makeStep({
      id: 'modifier_vrq_easy_002',
      order: 2,
      difficulty: 'easy',
      targetSkill: 'very_fast_basic',
      sentence: 'She speaks ___ fast.',
      translation: tri('Она говорит очень быстро.', 'Вона говорить дуже швидко.', 'She speaks very fast.'),
      options: ['very', 'very much', 'many', 'fast very'],
      correctAnswer: 'very',
      correctFeedback: tri('Да. Очень быстро = very fast.', 'Так. Дуже швидко = very fast.', 'Yes. Very fast.'),
      wrong: {
        'very much': tri('Very much fast не звучит нормально. Нужен блок very fast.', 'Very much fast не звучить нормально. Потрiбен блок very fast.', 'Use very fast.'),
        many: tri('Many не работает с fast. Нужен блок very fast.', 'Many не працює з fast. Потрiбен блок very fast.', 'Use very fast.'),
        'fast very': tri('Very стоит перед fast: very fast.', 'Very стоїть перед fast: very fast.', 'Use very fast.'),
      },
      clue: tri('Усилитель ставим перед fast.', 'Пiдсилювач ставимо перед fast.', 'Put very before fast.'),
      finalHint: tri('Фраза: She speaks very fast.', 'Фраза: She speaks very fast.', 'Sentence: She speaks very fast.'),
      focusWords: ['very fast', 'very'],
    }),
    makeStep({
      id: 'modifier_vrq_easy_003',
      order: 3,
      difficulty: 'easy',
      targetSkill: 'very_important_basic',
      sentence: 'This is ___ important.',
      translation: tri('Это очень важно.', 'Це дуже важливо.', 'This is very important.'),
      options: ['very', 'much', 'many', 'important very'],
      correctAnswer: 'very',
      correctFeedback: tri('Да. Очень важно = very important.', 'Так. Дуже важливо = very important.', 'Yes. Very important.'),
      wrong: {
        much: tri('Much important не звучит естественно. Нужен блок very important.', 'Much important не звучить природно. Потрiбен блок very important.', 'Use very important.'),
        many: tri('Many не подходит к important. Нужен блок very important.', 'Many не пасує до important. Потрiбен блок very important.', 'Use very important.'),
        'important very': tri('Very не ставят после important. Нормально: very important.', 'Very не ставлять пiсля important. Нормально: very important.', 'Use very important.'),
      },
      clue: tri('Очень важно = very important.', 'Дуже важливо = very important.', 'Very important.'),
      finalHint: tri('Фраза: This is very important.', 'Фраза: This is very important.', 'Sentence: This is very important.'),
      focusWords: ['very important'],
    }),
    makeStep({
      id: 'modifier_vrq_contrast_001',
      order: 4,
      difficulty: 'contrast',
      targetSkill: 'really_tired_conversation',
      sentence: 'I am ___ tired today.',
      translation: tri('Я сегодня реально устал.', 'Я сьогоднi реально втомився.', 'I am really tired today.'),
      options: ['really', 'really much', 'many', 'tired really'],
      correctAnswer: 'really',
      correctFeedback: tri('Да. Живой разговорный блок: really tired.', 'Так. Живий розмовний блок: really tired.', 'Yes. Really tired.'),
      wrong: {
        'really much': tri('Really much tired звучит перегруженно. Нужен короткий блок really tired.', 'Really much tired звучить перевантажено. Потрiбен короткий блок really tired.', 'Use really tired.'),
        many: tri('Many не усиливает tired. Нужен блок really tired.', 'Many не пiдсилює tired. Потрiбен блок really tired.', 'Use really tired.'),
        'tired really': tri('Really стоит перед tired: really tired.', 'Really стоїть перед tired: really tired.', 'Use really tired.'),
      },
      clue: tri('Реально устал = really tired.', 'Реально втомився = really tired.', 'Really tired.'),
      finalHint: tri('Фраза: I am really tired today.', 'Фраза: I am really tired today.', 'Sentence: I am really tired today.'),
      focusWords: ['really tired', 'really'],
    }),
    makeStep({
      id: 'modifier_vrq_contrast_002',
      order: 5,
      difficulty: 'contrast',
      targetSkill: 'really_interesting_conversation',
      sentence: 'The idea is ___ interesting.',
      translation: tri('Идея реально интересная.', 'Iдея реально цiкава.', 'The idea is really interesting.'),
      options: ['really', 'really much', 'many', 'interesting really'],
      correctAnswer: 'really',
      correctFeedback: tri('Да. Really interesting звучит живее, чем сухое very interesting.', 'Так. Really interesting звучить живiше, нiж сухе very interesting.', 'Yes. Really interesting.'),
      wrong: {
        'really much': tri('Лишнее слово после really перегружает фразу. Нужен короткий разговорный усилитель перед качеством.', 'Зайве слово пiсля really перевантажує фразу. Потрiбен короткий розмовний пiдсилювач перед якiстю.', 'Use really interesting.'),
        many: tri('Many не подходит к interesting. Нужен блок really interesting.', 'Many не пасує до interesting. Потрiбен блок really interesting.', 'Use really interesting.'),
        'interesting really': tri('Порядок обратный: сначала усилитель, потом качество. После слова его не ставим.', 'Порядок зворотний: спочатку пiдсилювач, потiм якiсть. Пiсля слова його не ставимо.', 'Use really interesting.'),
      },
      clue: tri('Если хочешь живее, бери really interesting.', 'Якщо хочеш живiше, бери really interesting.', 'Really interesting.'),
      finalHint: tri('Фраза: The idea is really interesting.', 'Фраза: The idea is really interesting.', 'Sentence: The idea is really interesting.'),
      focusWords: ['really interesting'],
    }),
    makeStep({
      id: 'modifier_vrq_contrast_003',
      order: 6,
      difficulty: 'contrast',
      targetSkill: 'really_good_conversation',
      sentence: 'Your answer is ___ good.',
      translation: tri('Твой ответ реально хороший.', 'Твоя вiдповiдь реально хороша.', 'Your answer is really good.'),
      options: ['really', 'really much', 'many', 'good really'],
      correctAnswer: 'really',
      correctFeedback: tri('Да. Really good - живой сильный вариант.', 'Так. Really good - живий сильний варiант.', 'Yes. Really good.'),
      wrong: {
        'really much': tri('Really much good не звучит естественно. Нормально: really good.', 'Really much good не звучить природно. Нормально: really good.', 'Use really good.'),
        many: tri('Many не подходит к good. Нужен блок really good.', 'Many не пасує до good. Потрiбен блок really good.', 'Use really good.'),
        'good really': tri('Really стоит перед good: really good.', 'Really стоїть перед good: really good.', 'Use really good.'),
      },
      clue: tri('Реально хороший = really good.', 'Реально хороший = really good.', 'Really good.'),
      finalHint: tri('Фраза: Your answer is really good.', 'Фраза: Your answer is really good.', 'Sentence: Your answer is really good.'),
      focusWords: ['really good'],
    }),
    makeStep({
      id: 'modifier_vrq_contrast_004',
      order: 7,
      difficulty: 'contrast',
      targetSkill: 'quite_good_moderate',
      sentence: 'The lesson was ___ good.',
      translation: tri('Урок был довольно хорошим.', 'Урок був доволi хорошим.', 'The lesson was quite good.'),
      options: ['quite', 'too', 'many', 'good quite'],
      correctAnswer: 'quite',
      correctFeedback: tri('Да. Довольно хороший, без сильного восторга = quite good.', 'Так. Доволi хороший, без сильного захвату = quite good.', 'Yes. Quite good.'),
      wrong: {
        too: tri('Too good не передает здесь "довольно хороший". Нужен мягкий блок quite good.', 'Too good не передає тут "доволi хороший". Потрiбен мʼякий блок quite good.', 'Use quite good.'),
        many: tri('Many не подходит к good. Нужен блок quite good.', 'Many не пасує до good. Потрiбен блок quite good.', 'Use quite good.'),
        'good quite': tri('Quite стоит перед good: quite good.', 'Quite стоїть перед good: quite good.', 'Use quite good.'),
      },
      clue: tri('Довольно хороший = quite good.', 'Доволi хороший = quite good.', 'Quite good.'),
      finalHint: tri('Фраза: The lesson was quite good.', 'Фраза: The lesson was quite good.', 'Sentence: The lesson was quite good.'),
      focusWords: ['quite good', 'quite'],
    }),
    makeStep({
      id: 'modifier_vrq_contrast_005',
      order: 8,
      difficulty: 'contrast',
      targetSkill: 'quite_difficult_moderate',
      sentence: 'The test was ___ difficult.',
      translation: tri('Тест был довольно сложным.', 'Тест був доволi складним.', 'The test was quite difficult.'),
      options: ['quite', 'too', 'many', 'difficult quite'],
      correctAnswer: 'quite',
      correctFeedback: tri('Да. Довольно сложный = quite difficult.', 'Так. Доволi складний = quite difficult.', 'Yes. Quite difficult.'),
      wrong: {
        too: tri('Too difficult значит "слишком сложный", уже проблема. Здесь мягче: quite difficult.', 'Too difficult означає "занадто складний", уже проблема. Тут мʼякше: quite difficult.', 'Use quite difficult.'),
        many: tri('Many не подходит к difficult. Нужен блок quite difficult.', 'Many не пасує до difficult. Потрiбен блок quite difficult.', 'Use quite difficult.'),
        'difficult quite': tri('Порядок обратный: мягкий усилитель ставим перед качеством, а не после него.', 'Порядок зворотний: мʼякий пiдсилювач ставимо перед якiстю, а не пiсля неї.', 'Use quite difficult.'),
      },
      clue: tri('Довольно сложный = quite difficult.', 'Доволi складний = quite difficult.', 'Quite difficult.'),
      finalHint: tri('Фраза: The test was quite difficult.', 'Фраза: The test was quite difficult.', 'Sentence: The test was quite difficult.'),
      focusWords: ['quite difficult'],
    }),
    makeStep({
      id: 'modifier_vrq_contrast_006',
      order: 9,
      difficulty: 'contrast',
      targetSkill: 'quite_interesting_moderate',
      sentence: 'The article was ___ interesting.',
      translation: tri('Статья была довольно интересной.', 'Стаття була доволi цiкавою.', 'The article was quite interesting.'),
      options: ['quite', 'too', 'many', 'interesting quite'],
      correctAnswer: 'quite',
      correctFeedback: tri('Да. Довольно интересная = quite interesting.', 'Так. Доволi цiкава = quite interesting.', 'Yes. Quite interesting.'),
      wrong: {
        too: tri('Too interesting звучит как перебор. Здесь нужна мягкая оценка: quite interesting.', 'Too interesting звучить як перебiр. Тут потрiбна мʼяка оцiнка: quite interesting.', 'Use quite interesting.'),
        many: tri('Many не подходит к interesting. Нужен блок quite interesting.', 'Many не пасує до interesting. Потрiбен блок quite interesting.', 'Use quite interesting.'),
        'interesting quite': tri('Порядок обратный: сначала мягкий усилитель, потом качество. После слова он звучит сломанно.', 'Порядок зворотний: спочатку мʼякий пiдсилювач, потiм якiсть. Пiсля слова вiн звучить зламано.', 'Use quite interesting.'),
      },
      clue: tri('Довольно интересная = quite interesting.', 'Доволi цiкава = quite interesting.', 'Quite interesting.'),
      finalHint: tri('Фраза: The article was quite interesting.', 'Фраза: The article was quite interesting.', 'Sentence: The article was quite interesting.'),
      focusWords: ['quite interesting'],
    }),
    makeStep({
      id: 'modifier_vrq_mixed_001',
      order: 10,
      difficulty: 'mixed',
      targetSkill: 'very_vs_too_hot',
      sentence: 'The soup is ___ hot, but I can eat it.',
      translation: tri('Суп очень горячий, но я могу его есть.', 'Суп дуже гарячий, але я можу його їсти.', 'The soup is very hot, but I can eat it.'),
      options: ['very', 'too', 'many', 'very much'],
      correctAnswer: 'very',
      correctFeedback: tri('Да. Если можно есть, это very hot, а не too hot.', 'Так. Якщо можна їсти, це very hot, а не too hot.', 'Yes. Very hot.'),
      wrong: {
        too: tri('Too hot обычно значит, что уже есть проблема. Здесь суп горячий, но его можно есть: very hot.', 'Too hot зазвичай означає, що вже є проблема. Тут суп гарячий, але його можна їсти: very hot.', 'Use very hot.'),
        many: tri('Many не подходит к hot. Нужен блок very hot.', 'Many не пасує до hot. Потрiбен блок very hot.', 'Use very hot.'),
        'very much': tri('Very much hot не нужно. Нормально: very hot.', 'Very much hot не потрiбно. Нормально: very hot.', 'Use very hot.'),
      },
      clue: tri('Горячий, но терпимо = very hot.', 'Гарячий, але терпимо = very hot.', 'Very hot.'),
      finalHint: tri('Фраза: The soup is very hot, but I can eat it.', 'Фраза: The soup is very hot, but I can eat it.', 'Sentence: The soup is very hot, but I can eat it.'),
      focusWords: ['very hot', 'too hot'],
    }),
    makeStep({
      id: 'modifier_vrq_mixed_002',
      order: 11,
      difficulty: 'mixed',
      targetSkill: 'too_hot_problem',
      sentence: 'The soup is ___ hot to eat.',
      translation: tri('Суп слишком горячий, чтобы его есть.', 'Суп занадто гарячий, щоб його їсти.', 'The soup is too hot to eat.'),
      options: ['too', 'very', 'many', 'too much'],
      correctAnswer: 'too',
      correctFeedback: tri('Да. Слишком горячий, чтобы есть = too hot to eat.', 'Так. Занадто гарячий, щоб їсти = too hot to eat.', 'Yes. Too hot to eat.'),
      wrong: {
        very: tri('Very hot не показывает невозможность. Здесь есть проблема: too hot to eat.', 'Very hot не показує неможливiсть. Тут є проблема: too hot to eat.', 'Use too hot to eat.'),
        many: tri('Many не подходит к hot. Нужен блок too hot.', 'Many не пасує до hot. Потрiбен блок too hot.', 'Use too hot.'),
        'too much': tri('Too much hot не звучит нормально. Нужен короткий блок too hot.', 'Too much hot не звучить нормально. Потрiбен короткий блок too hot.', 'Use too hot.'),
      },
      clue: tri('Слишком горячий, чтобы есть = too hot to eat.', 'Занадто гарячий, щоб їсти = too hot to eat.', 'Too hot to eat.'),
      finalHint: tri('Фраза: The soup is too hot to eat.', 'Фраза: The soup is too hot to eat.', 'Sentence: The soup is too hot to eat.'),
      focusWords: ['too hot', 'too hot to'],
    }),
    makeStep({
      id: 'modifier_vrq_mixed_003',
      order: 12,
      difficulty: 'mixed',
      targetSkill: 'quite_vs_really_tone',
      sentence: 'The film was ___ good, but not amazing.',
      translation: tri('Фильм был довольно хорошим, но не потрясающим.', 'Фiльм був доволi хорошим, але не вражаючим.', 'The film was quite good, but not amazing.'),
      options: ['quite', 'really', 'too', 'good very'],
      correctAnswer: 'quite',
      correctFeedback: tri('Да. Положительно, но не восторг = quite good.', 'Так. Позитивно, але не захват = quite good.', 'Yes. Quite good.'),
      wrong: {
        really: tri('Really good звучит сильнее. Здесь фраза мягче: quite good.', 'Really good звучить сильнiше. Тут фраза мʼякша: quite good.', 'Use quite good.'),
        too: tri('Too good не значит "довольно хороший" в этой фразе. Нужен блок quite good.', 'Too good не означає "доволi хороший" у цiй фразi. Потрiбен блок quite good.', 'Use quite good.'),
        'good very': tri('Very не ставится после good. По смыслу здесь quite good.', 'Very не ставиться пiсля good. За змiстом тут quite good.', 'Use quite good.'),
      },
      clue: tri('Хорошо, но не потрясающе = quite good.', 'Добре, але не вражаюче = quite good.', 'Quite good.'),
      finalHint: tri('Фраза: The film was quite good, but not amazing.', 'Фраза: The film was quite good, but not amazing.', 'Sentence: The film was quite good, but not amazing.'),
      focusWords: ['quite good', 'really good'],
    }),
    makeStep({
      id: 'modifier_vrq_mixed_004',
      order: 13,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_very_really_quite',
      sentence: 'Choose the best pair.',
      translation: tri('Очень полезно / реально устал / довольно сложно', 'Дуже корисно / реально втомився / доволi складно', 'Very useful / really tired / quite difficult'),
      options: [
        'very useful / really tired / quite difficult',
        'useful very / tired really / difficult quite',
        'many useful / much tired / many difficult',
        'very useful / really much tired / quite much difficult',
      ],
      correctAnswer: 'very useful / really tired / quite difficult',
      correctFeedback: tri('Да. Здесь все три усилителя стоят перед качеством и дают нужный оттенок.', 'Так. Тут усi три пiдсилювачi стоять перед якiстю i дають потрiбний вiдтiнок.', 'Yes. Natural chunks.'),
      wrong: {
        'useful very / tired really / difficult quite': tri('Усилитель стоит после слова. Нормально: very useful / really tired / quite difficult.', 'Пiдсилювач стоїть пiсля слова. Нормально: very useful / really tired / quite difficult.', 'Use very useful / really tired / quite difficult.'),
        'many useful / much tired / many difficult': tri('Здесь не считаем предметы и не говорим о количестве. Нужны короткие усилители качества.', 'Тут не рахуємо предмети i не говоримо про кiлькiсть. Потрiбнi короткi пiдсилювачi якостi.', 'Use very useful / really tired / quite difficult.'),
        'very useful / really much tired / quite much difficult': tri('После разговорного или мягкого усилителя не добавляем лишнее much. Фраза должна быть короче.', 'Пiсля розмовного або мʼякого пiдсилювача не додаємо зайве much. Фраза має бути коротшою.', 'Use really tired / quite difficult.'),
      },
      clue: tri('Три живых куска: нейтрально, разговорно, мягко. Во всех трех усилитель идет перед качеством.', 'Три живi шматки: нейтрально, розмовно, мʼяко. В усiх трьох пiдсилювач iде перед якiстю.', 'Three chunks.'),
      finalHint: tri('Ответ: very useful / really tired / quite difficult.', 'Вiдповiдь: very useful / really tired / quite difficult.', 'Answer: very useful / really tired / quite difficult.'),
      focusWords: ['very useful', 'really tired', 'quite difficult'],
    }),
    makeStep({
      id: 'modifier_vrq_mixed_005',
      order: 14,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_very_too',
      sentence: 'Choose the correct pair.',
      translation: tri('Очень горячий, но можно пить / слишком горячий, нельзя пить', 'Дуже гарячий, але можна пити / занадто гарячий, не можна пити', 'Very hot but drinkable / too hot to drink'),
      options: [
        'very hot, but I can drink it / too hot to drink',
        'too hot, but I can drink it / very hot to drink',
        'hot very, but I can drink it / hot too to drink',
        'many hot, but I can drink it / too much hot to drink',
      ],
      correctAnswer: 'very hot, but I can drink it / too hot to drink',
      correctFeedback: tri('Да. Very hot - просто сильно. Too hot - уже проблема.', 'Так. Very hot - просто сильно. Too hot - уже проблема.', 'Yes. Very hot is strong; too hot is a problem.'),
      wrong: {
        'too hot, but I can drink it / very hot to drink': tri('Если можно пить, лучше very hot. Если нельзя пить, нужен блок too hot to drink.', 'Якщо можна пити, краще very hot. Якщо не можна пити, потрiбен блок too hot to drink.', 'Use very hot / too hot to drink.'),
        'hot very, but I can drink it / hot too to drink': tri('Very и too стоят перед hot: very hot, too hot.', 'Very i too стоять перед hot: very hot, too hot.', 'Use very hot / too hot.'),
        'many hot, but I can drink it / too much hot to drink': tri('Many hot и too much hot не звучат нормально. Нужны very hot / too hot.', 'Many hot i too much hot не звучать нормально. Потрiбнi very hot / too hot.', 'Use very hot / too hot.'),
      },
      clue: tri('Терпимо = very hot. Нельзя пить = too hot to drink.', 'Терпимо = very hot. Не можна пити = too hot to drink.', 'Very hot vs too hot.'),
      finalHint: tri('Ответ: very hot, but I can drink it / too hot to drink.', 'Вiдповiдь: very hot, but I can drink it / too hot to drink.', 'Answer: very hot, but I can drink it / too hot to drink.'),
      focusWords: ['very hot', 'too hot'],
    }),
    makeStep({
      id: 'modifier_vrq_mixed_006',
      order: 15,
      difficulty: 'mixed_review',
      targetSkill: 'mixed_sentence_correction',
      sentence: 'Choose the correct sentence.',
      translation: tri('Выбери естественное предложение.', 'Обери природне речення.', 'Choose the natural sentence.'),
      options: [
        'The course is really useful, but the last test was quite difficult.',
        'The course is useful really, but the last test was difficult quite.',
        'The course is many useful, but the last test was much difficult.',
        'The course is really much useful, but the last test was quite much difficult.',
      ],
      correctAnswer: 'The course is really useful, but the last test was quite difficult.',
      correctFeedback: tri('Да. Сначала идет усилитель, потом качество: так фраза звучит естественно.', 'Так. Спочатку йде пiдсилювач, потiм якiсть: так фраза звучить природно.', 'Yes. Really useful / quite difficult.'),
      wrong: {
        'The course is useful really, but the last test was difficult quite.': tri('Really и quite стоят не там. Нормально: really useful / quite difficult.', 'Really i quite стоять не там. Нормально: really useful / quite difficult.', 'Use really useful / quite difficult.'),
        'The course is many useful, but the last test was much difficult.': tri('Many useful и much difficult не звучат нормально. Нужны really useful / quite difficult.', 'Many useful i much difficult не звучать нормально. Потрiбнi really useful / quite difficult.', 'Use really useful / quite difficult.'),
        'The course is really much useful, but the last test was quite much difficult.': tri('Здесь лишнее much после усилителей. Оставляем короткий разговорный и мягкий вариант: really useful / quite difficult.', 'Тут зайве much пiсля пiдсилювачiв. Залишаємо короткий розмовний i мʼякий варiант.', 'Use really useful / quite difficult.'),
      },
      clue: tri('Курс реально полезный, тест довольно сложный: really useful / quite difficult.', 'Курс реально корисний, тест доволi складний: really useful / quite difficult.', 'Really useful / quite difficult.'),
      finalHint: tri('Фраза: The course is really useful, but the last test was quite difficult.', 'Фраза: The course is really useful, but the last test was quite difficult.', 'Sentence: The course is really useful, but the last test was quite difficult.'),
      focusWords: ['really useful', 'quite difficult'],
    }),
  ],
  masteryRules: {
    minCorrect: 10,
    minCorrectStreak: 4,
    requireCorrectAfterWrong: true,
    requireMixedReview: true,
    maxAllowedCriticalMistakes: 2,
    criticalMistakeIds: [
      'very_much_useful_error',
      'really_much_tired_error',
      'quite_much_difficult_error',
      'too_instead_of_very_error',
      'intensifier_after_word_error',
    ],
    repeatIfCorrectRateBelow: 0.78,
    unlockSmartTrainerAfterMastery: true,
  },
  adaptiveFeedbackPolicy: {
    maxDepth: 4,
    depth1: tri(
      'Сначала показываем разницу в оттенке: very, really, quite или too.',
      'Спочатку показуємо рiзницю у вiдтiнку: very, really, quite або too.',
      'First show the tone difference.',
    ),
    depth2: tri(
      'Если ошибка повторяется, даем готовые пары: very useful, really tired, quite good, too hot.',
      'Якщо помилка повторюється, даємо готовi пари: very useful, really tired, quite good, too hot.',
      'Then show ready-made chunks.',
    ),
    depth3: tri(
      'Еще проще: very = просто очень, really = живее, quite = мягче, too = проблема.',
      'Ще простiше: very = просто дуже, really = живiше, quite = мʼякше, too = проблема.',
      'Simpler: neutral, conversational, softer, problem.',
    ),
    depth4: tri(
      'Почти подсказка: прямо возвращаем к нужному блоку.',
      'Майже пiдказка: прямо повертаємо до потрiбного блоку.',
      'Near answer: return to the needed chunk.',
    ),
  },
  failureRecovery: {
    afterTwoWrongInSameExercise: {
      action: 'show_simplified_rule_card',
      card: tri(
        'Остановись на секунду. Very useful. Really tired. Quite good. Too hot. Это четыре разных настроения фразы.',
        'Зупинись на секунду. Very useful. Really tired. Quite good. Too hot. Це чотири рiзнi настрої фрази.',
        'Pause: very useful, really tired, quite good, too hot.',
      ),
    },
    afterThreeWrongInSameExercise: {
      action: 'show_tone_hint_then_retry',
      card: tri(
        'Система покажет, нужен ли нейтральный, живой, мягкий или проблемный оттенок, а потом вернет к полной фразе.',
        'Система покаже, потрiбен нейтральний, живий, мʼякий чи проблемний вiдтiнок, а потiм поверне до повної фрази.',
        'Show tone hint, then retry.',
      ),
    },
    afterFourWrongInSameExercise: {
      action: 'switch_to_guided_mode',
      card: tri(
        'Режим подсказки: сначала выбираем смысл, потом возвращаемся к фразе.',
        'Режим пiдказки: спочатку обираємо сенс, потiм повертаємося до фрази.',
        'Guided mode: choose meaning, then return.',
      ),
    },
  },
  guidedMode: {
    enabled: true,
    triggerAfterWrongAttempts: 4,
    tasks: [
      {
        id: 'guided_modifier_vrq_001',
        prompt: tri('Very usually means neutral strength or a problem?', 'Very usually means neutral strength or a problem?', 'Very usually means neutral strength or a problem?'),
        options: ['neutral strength', 'a problem'],
        correctIndex: 0,
        thenReturnToExerciseId: 'modifier_vrq_easy_001',
      },
      {
        id: 'guided_modifier_vrq_002',
        prompt: tri('Фраза с really здесь звучит более книжно или более разговорно?', 'Фраза з really тут звучить бiльш книжно чи бiльш розмовно?', 'Really tired sounds more written or more conversational?'),
        options: ['more written', 'more conversational'],
        correctIndex: 1,
        thenReturnToExerciseId: 'modifier_vrq_contrast_001',
      },
      {
        id: 'guided_modifier_vrq_003',
        prompt: tri('Quite good is usually softer or stronger than really good?', 'Quite good is usually softer or stronger than really good?', 'Quite good is usually softer or stronger than really good?'),
        options: ['softer', 'stronger'],
        correctIndex: 0,
        thenReturnToExerciseId: 'modifier_vrq_contrast_004',
      },
      {
        id: 'guided_modifier_vrq_004',
        prompt: tri('Too hot usually means strong but okay, or already a problem?', 'Too hot usually means strong but okay, or already a problem?', 'Too hot usually means strong but okay, or already a problem?'),
        options: ['strong but okay', 'already a problem'],
        correctIndex: 1,
        thenReturnToExerciseId: 'modifier_vrq_mixed_001',
      },
    ],
  },
  smartTrainerConfig: {
    mode: 'weak',
    source: 'diagnosis_training',
    category: 'modifier',
    microDiagnosisId: 'modifier_very_really_quite',
    diagnosisLabel: tri('Very / Really / Quite', 'Very / Really / Quite', 'Very / Really / Quite'),
    contrastSet: CONTRAST,
    difficultyLevel: 2,
    focusWords: ['very useful', 'really tired', 'quite good', 'quite difficult', 'very hot', 'too hot'],
    focusPatterns: [
      'very_useful_neutral',
      'really_tired_conversation',
      'quite_good_soft',
      'quite_difficult_soft',
      'very_vs_too_hot',
      'wrong_really_much',
      'wrong_quite_much',
      'position_before_word',
    ],
    includeFailedItems: true,
    includeRecoveredItems: true,
    includeSimilarItems: true,
    minItems: 12,
    recommendedItems: 20,
    difficultyEscalation: {
      start: 'easy',
      afterCorrectInRow: 2,
      next: 'contrast',
      afterCorrectInRowAtContrast: 3,
      final: 'mixed_review',
    },
  },
  analyticsEvents: {
    start: 'diagnosis_training_modifier_very_really_quite_start',
    answer: 'diagnosis_training_modifier_very_really_quite_answer',
    mastery: 'diagnosis_training_modifier_very_really_quite_mastery',
    fallback: 'diagnosis_training_modifier_very_really_quite_fallback',
    smartTrainerUnlocked: 'diagnosis_training_modifier_very_really_quite_smart_trainer_unlocked',
    payload: {
      category: 'modifier',
      microDiagnosisId: 'modifier_very_really_quite',
      contrastSet: CONTRAST,
      priority: 35,
    },
  },
  routing: {
    appScreen: 'ProblemCoach',
    webPath: '/problem-coach/modifier/very-really-quite',
    deepLink: 'phraseman://problem-coach/modifier/very-really-quite',
    diagnosisTrainerRoute: '/problem_coach?category=modifier&microDiagnosisId=modifier_very_really_quite',
    smartTrainerRoute: '/smart_trainer?source=diagnosis_training&microDiagnosisId=modifier_very_really_quite',
  },
  qualityChecklist: {
    hasContrastiveMinimalPairs: true,
    hasDistractorSpecificFeedback: true,
    hasNegativeTransferWarning: true,
    hasMicroDiagnosis: true,
    hasAdaptiveFeedback: true,
    hasSmartTrainerUnlock: true,
  },
};
