export interface IrregularVerb {
  base: string;
  past: string;
  pp: string;
  ru: string;
  uk: string;
}

// Irregular Verbs by Lesson
export const IRREGULAR_VERBS_BY_LESSON: Record<number, IrregularVerb[]> = {
  1: [
    { base: 'be', past: 'was/were', pp: 'been', ru: 'Быть', uk: 'Бути' },
    { base: 'break', past: 'broke', pp: 'broken', ru: 'Ломать', uk: 'Ламати' },
  ],
  2: [
    { base: 'be', past: 'was/were', pp: 'been', ru: 'Быть', uk: 'Бути' },
    { base: 'build', past: 'built', pp: 'built', ru: 'Строить', uk: 'Будувати' },
  ],
  3: [
    { base: 'drink', past: 'drank', pp: 'drunk', ru: 'Пить', uk: 'Пити' },
    { base: 'speak', past: 'spoke', pp: 'spoken', ru: 'Говорить', uk: 'Говорити' },
    { base: 'understand', past: 'understood', pp: 'understood', ru: 'Понимать', uk: 'Розуміти' },
    { base: 'know', past: 'knew', pp: 'known', ru: 'Знать', uk: 'Знати' },
    { base: 'eat', past: 'ate', pp: 'eaten', ru: 'Есть', uk: 'Їсти' },
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
    { base: 'read', past: 'read', pp: 'read', ru: 'Читать', uk: 'Читати' },
    { base: 'live', past: 'lived', pp: 'lived', ru: 'Жить', uk: 'Жити' },
    { base: 'come', past: 'came', pp: 'come', ru: 'Приходить', uk: 'Приходити' },
    { base: 'write', past: 'wrote', pp: 'written', ru: 'Писать', uk: 'Писати' },
    { base: 'drive', past: 'drove', pp: 'driven', ru: 'Водить', uk: 'Водити' },
    { base: 'feel', past: 'felt', pp: 'felt', ru: 'Чувствовать', uk: 'Відчувати' },
    { base: 'forget', past: 'forgot', pp: 'forgotten', ru: 'Забывать', uk: 'Забувати' },
    { base: 'take', past: 'took', pp: 'taken', ru: 'Брать', uk: 'Брати' },
    { base: 'teach', past: 'taught', pp: 'taught', ru: 'Преподавать', uk: 'Викладати' },
    { base: 'wear', past: 'wore', pp: 'worn', ru: 'Носить', uk: 'Носити' },
  ],
  4: [
    { base: 'drink', past: 'drank', pp: 'drunk', ru: 'Пить', uk: 'Пити' },
    { base: 'eat', past: 'ate', pp: 'eaten', ru: 'Есть', uk: 'Їсти' },
    { base: 'understand', past: 'understood', pp: 'understood', ru: 'Понимать', uk: 'Розуміти' },
    { base: 'know', past: 'knew', pp: 'known', ru: 'Знать', uk: 'Знати' },
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
    { base: 'see', past: 'saw', pp: 'seen', ru: 'Видеть', uk: 'Бачити' },
    { base: 'wear', past: 'wore', pp: 'worn', ru: 'Носить', uk: 'Носити' },
    { base: 'pay', past: 'paid', pp: 'paid', ru: 'Платить', uk: 'Платити' },
    { base: 'sell', past: 'sold', pp: 'sold', ru: 'Продавать', uk: 'Продавати' },
    { base: 'drive', past: 'drove', pp: 'driven', ru: 'Водить', uk: 'Водити' },
    { base: 'lose', past: 'lost', pp: 'lost', ru: 'Терять', uk: 'Втрачати' },
    { base: 'feel', past: 'felt', pp: 'felt', ru: 'Чувствовать', uk: 'Відчувати' },
    { base: 'spend', past: 'spent', pp: 'spent', ru: 'Тратить', uk: 'Витрачати' },
    { base: 'forget', past: 'forgot', pp: 'forgotten', ru: 'Забывать', uk: 'Забувати' },
    { base: 'break', past: 'broke', pp: 'broken', ru: 'Нарушать (ломать)', uk: 'Порушувати (ламати)' },
    { base: 'read', past: 'read', pp: 'read', ru: 'Читать', uk: 'Читати' },
    { base: 'take', past: 'took', pp: 'taken', ru: 'Брать', uk: 'Брати' },
  ],
  5: [
    { base: 'drink', past: 'drank', pp: 'drunk', ru: 'Пить', uk: 'Пити' },
    { base: 'do', past: 'did', pp: 'done', ru: 'Делать', uk: 'Робити' },
    { base: 'go', past: 'went', pp: 'gone', ru: 'Идти', uk: 'Йти' },
    { base: 'know', past: 'knew', pp: 'known', ru: 'Знать', uk: 'Знати' },
    { base: 'speak', past: 'spoke', pp: 'spoken', ru: 'Говорить', uk: 'Говорити' },
    { base: 'eat', past: 'ate', pp: 'eaten', ru: 'Есть', uk: 'Їсти' },
    { base: 'drive', past: 'drove', pp: 'driven', ru: 'Водить', uk: 'Водити' },
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
    { base: 'find', past: 'found', pp: 'found', ru: 'Находить', uk: 'Знаходити' },
    { base: 'cost', past: 'cost', pp: 'cost', ru: 'Стоить', uk: 'Коштувати' },
    { base: 'feel', past: 'felt', pp: 'felt', ru: 'Чувствовать', uk: 'Відчувати' },
    { base: 'forget', past: 'forgot', pp: 'forgotten', ru: 'Забывать', uk: 'Забувати' },
    { base: 'hear', past: 'heard', pp: 'heard', ru: 'Слышать', uk: 'Чути' },
    { base: 'lose', past: 'lost', pp: 'lost', ru: 'Терять', uk: 'Втрачати' },
    { base: 'pay', past: 'paid', pp: 'paid', ru: 'Платить', uk: 'Платити' },
    { base: 'read', past: 'read', pp: 'read', ru: 'Читать', uk: 'Читати' },
    { base: 'sell', past: 'sold', pp: 'sold', ru: 'Продавать', uk: 'Продавати' },
    { base: 'sing', past: 'sang', pp: 'sung', ru: 'Петь', uk: 'Співати' },
    { base: 'sleep', past: 'slept', pp: 'slept', ru: 'Спать', uk: 'Спати' },
    { base: 'take', past: 'took', pp: 'taken', ru: 'Брать', uk: 'Брати' },
    { base: 'understand', past: 'understood', pp: 'understood', ru: 'Понимать', uk: 'Розуміти' },
    { base: 'wear', past: 'wore', pp: 'worn', ru: 'Носить', uk: 'Носити' },
    { base: 'write', past: 'wrote', pp: 'written', ru: 'Писать', uk: 'Писати' },
  ],
  6: [
    { base: 'eat', past: 'ate', pp: 'eaten', ru: 'Есть', uk: 'Їсти' },
    { base: 'cost', past: 'cost', pp: 'cost', ru: 'Стоить', uk: 'Коштувати' },
    { base: 'drink', past: 'drank', pp: 'drunk', ru: 'Пить', uk: 'Пити' },
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
    { base: 'go', past: 'went', pp: 'gone', ru: 'Идти', uk: 'Йти' },
    { base: 'read', past: 'read', pp: 'read', ru: 'Читать', uk: 'Читати' },
    { base: 'come', past: 'came', pp: 'come', ru: 'Приходить', uk: 'Приходити' },
    { base: 'pay', past: 'paid', pp: 'paid', ru: 'Платить', uk: 'Платити' },
    { base: 'send', past: 'sent', pp: 'sent', ru: 'Отправлять', uk: 'Відправляти' },
    { base: 'do', past: 'did', pp: 'done', ru: 'Делать', uk: 'Робити' },
    { base: 'leave', past: 'left', pp: 'left', ru: 'Уходить', uk: 'Йти' },
    { base: 'see', past: 'saw', pp: 'seen', ru: 'Видеть', uk: 'Бачити' },
    { base: 'keep', past: 'kept', pp: 'kept', ru: 'Хранить', uk: 'Зберігати' },
    { base: 'find', past: 'found', pp: 'found', ru: 'Находить', uk: 'Знаходити' },
    { base: 'meet', past: 'met', pp: 'met', ru: 'Встречать', uk: 'Зустрічати' },
    { base: 'wear', past: 'wore', pp: 'worn', ru: 'Носить', uk: 'Носити' },
    { base: 'speak', past: 'spoke', pp: 'spoken', ru: 'Говорить', uk: 'Говорити' },
    { base: 'put', past: 'put', pp: 'put', ru: 'Класть', uk: 'Класти' },
  ],
  7: [
    { base: 'have', past: 'had', pp: 'had', ru: 'Иметь', uk: 'Мати' },
    { base: 'do', past: 'did', pp: 'done', ru: 'Делать', uk: 'Робити' },
  ],
  8: [
    { base: 'leave', past: 'left', pp: 'left', ru: 'Уходить', uk: 'Йти' },
    { base: 'pay', past: 'paid', pp: 'paid', ru: 'Платить', uk: 'Платити' },
    { base: 'have', past: 'had', pp: 'had', ru: 'Иметь', uk: 'Мати' },
    { base: 'drink', past: 'drank', pp: 'drunk', ru: 'Пить', uk: 'Пити' },
    { base: 'do', past: 'did', pp: 'done', ru: 'Делать', uk: 'Робити' },
    { base: 'meet', past: 'met', pp: 'met', ru: 'Встречаться', uk: 'Зустрічатися' },
    { base: 'come', past: 'came', pp: 'come', ru: 'Приходить', uk: 'Приходити' },
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
  ],
  9: [
    { base: 'be', past: 'was/were', pp: 'been', ru: 'Быть', uk: 'Бути' },
  ],
  10: [
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
    { base: 'come', past: 'came', pp: 'come', ru: 'Приходить', uk: 'Приходити' },
    { base: 'find', past: 'found', pp: 'found', ru: 'Находить', uk: 'Знаходити' },
    { base: 'send', past: 'sent', pp: 'sent', ru: 'Отправлять', uk: 'Надсилати' },
    { base: 'meet', past: 'met', pp: 'met', ru: 'Встречать', uk: 'Зустрічати' },
    { base: 'wear', past: 'wore', pp: 'worn', ru: 'Носить', uk: 'Носити' },
    { base: 'show', past: 'showed', pp: 'shown', ru: 'Показывать', uk: 'Показувати' },
    { base: 'pay', past: 'paid', pp: 'paid', ru: 'Платить', uk: 'Платити' },
    { base: 'keep', past: 'kept', pp: 'kept', ru: 'Хранить', uk: 'Зберігати' },
    { base: 'drive', past: 'drove', pp: 'driven', ru: 'Водить', uk: 'Водити' },
    { base: 'leave', past: 'left', pp: 'left', ru: 'Оставлять', uk: 'Залишати' },
    { base: 'take', past: 'took', pp: 'taken', ru: 'Брать (принимать)', uk: 'Брати (приймати)' },
  ],
  12: [
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
    { base: 'drink', past: 'drank', pp: 'drunk', ru: 'Пить', uk: 'Пити' },
    { base: 'find', past: 'found', pp: 'found', ru: 'Находить', uk: 'Знаходити' },
    { base: 'sell', past: 'sold', pp: 'sold', ru: 'Продавать', uk: 'Продавати' },
    { base: 'send', past: 'sent', pp: 'sent', ru: 'Отправлять', uk: 'Відправляти' },
    { base: 'eat', past: 'ate', pp: 'eaten', ru: 'Есть', uk: 'Їсти' },
    { base: 'see', past: 'saw', pp: 'seen', ru: 'Видеть', uk: 'Бачити' },
    { base: 'build', past: 'built', pp: 'built', ru: 'Строить', uk: 'Будувати' },
    { base: 'write', past: 'wrote', pp: 'written', ru: 'Писать', uk: 'Писати' },
    { base: 'bring', past: 'brought', pp: 'brought', ru: 'Приносить', uk: 'Приносити' },
    { base: 'go', past: 'went', pp: 'gone', ru: 'Идти', uk: 'Йти' },
    { base: 'make', past: 'made', pp: 'made', ru: 'Делать', uk: 'Робити' },
    { base: 'give', past: 'gave', pp: 'given', ru: 'Давать', uk: 'Давати' },
    { base: 'forget', past: 'forgot', pp: 'forgotten', ru: 'Забывать', uk: 'Забувати' },
    { base: 'hear', past: 'heard', pp: 'heard', ru: 'Слышать', uk: 'Чути' },
    { base: 'spend', past: 'spent', pp: 'spent', ru: 'Тратить', uk: 'Витрачати' },
    { base: 'read', past: 'read', pp: 'read', ru: 'Читать', uk: 'Читати' },
    { base: 'lose', past: 'lost', pp: 'lost', ru: 'Терять', uk: 'Втрачати' },
    { base: 'leave', past: 'left', pp: 'left', ru: 'Покидать', uk: 'Покидати' },
    { base: 'meet', past: 'met', pp: 'met', ru: 'Встречать', uk: 'Зустрічати' },
    { base: 'sleep', past: 'slept', pp: 'slept', ru: 'Спать', uk: 'Спати' },
    { base: 'understand', past: 'understood', pp: 'understood', ru: 'Понимать', uk: 'Розуміти' },
    { base: 'wear', past: 'wore', pp: 'worn', ru: 'Носить', uk: 'Носити' },
    { base: 'tell', past: 'told', pp: 'told', ru: 'Рассказывать', uk: 'Розповідати' },
    { base: 'say', past: 'said', pp: 'said', ru: 'Сказать', uk: 'Сказати' },
  ],
  13: [
    { base: 'meet', past: 'met', pp: 'met', ru: 'Встречать', uk: 'Зустрічати' },
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
    { base: 'bring', past: 'brought', pp: 'brought', ru: 'Приносить', uk: 'Приносити' },
    { base: 'send', past: 'sent', pp: 'sent', ru: 'Отправлять', uk: 'Надсилати' },
    { base: 'wear', past: 'wore', pp: 'worn', ru: 'Носить', uk: 'Носити' },
    { base: 'understand', past: 'understood', pp: 'understood', ru: 'Понимать', uk: 'Розуміти' },
    { base: 'read', past: 'read', pp: 'read', ru: 'Читать', uk: 'Читати' },
    { base: 'write', past: 'wrote', pp: 'written', ru: 'Писать', uk: 'Писати' },
    { base: 'see', past: 'saw', pp: 'seen', ru: 'Видеть', uk: 'Бачити' },
    { base: 'sell', past: 'sold', pp: 'sold', ru: 'Продавать', uk: 'Продавати' },
    { base: 'drink', past: 'drank', pp: 'drunk', ru: 'Пить', uk: 'Пити' },
    { base: 'find', past: 'found', pp: 'found', ru: 'Находить', uk: 'Знаходити' },
    { base: 'eat', past: 'ate', pp: 'eaten', ru: 'Есть', uk: 'Їсти' },
    { base: 'build', past: 'built', pp: 'built', ru: 'Строить', uk: 'Будувати' },
    { base: 'lose', past: 'lost', pp: 'lost', ru: 'Терять', uk: 'Втрачати' },
    { base: 'hear', past: 'heard', pp: 'heard', ru: 'Слышать', uk: 'Чути' },
    { base: 'choose', past: 'chose', pp: 'chosen', ru: 'Выбирать', uk: 'Вибирати' },
    { base: 'forget', past: 'forgot', pp: 'forgotten', ru: 'Забывать', uk: 'Забувати' },
    { base: 'tell', past: 'told', pp: 'told', ru: 'Рассказывать', uk: 'Розповідати' },
    { base: 'know', past: 'knew', pp: 'known', ru: 'Знать', uk: 'Знати' },
    { base: 'cut', past: 'cut', pp: 'cut', ru: 'Резать', uk: 'Різати' },
    { base: 'feel', past: 'felt', pp: 'felt', ru: 'Чувствовать', uk: 'Відчувати' },
    { base: 'leave', past: 'left', pp: 'left', ru: 'Оставлять', uk: 'Залишати' },
    { base: 'sing', past: 'sang', pp: 'sung', ru: 'Петь', uk: 'Співати' },
    { base: 'shut', past: 'shut', pp: 'shut', ru: 'Закрывать', uk: 'Зачиняти' },
    { base: 'get', past: 'got', pp: 'got', ru: 'Получать', uk: 'Отримувати' },
  ],
  14: [
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
    { base: 'find', past: 'found', pp: 'found', ru: 'Находить', uk: 'Знаходити' },
    { base: 'choose', past: 'chose', pp: 'chosen', ru: 'Выбирать', uk: 'Вибирати' },
    { base: 'bring', past: 'brought', pp: 'brought', ru: 'Приносить', uk: 'Приносити' },
    { base: 'feel', past: 'felt', pp: 'felt', ru: 'Чувствовать', uk: 'Відчувати' },
  ],
  15: [
    { base: 'break', past: 'broke', pp: 'broken', ru: 'Ломать', uk: 'Ламати' },
  ],
  16: [
    { base: 'wake', past: 'woke', pp: 'woken', ru: 'Просыпаться', uk: 'Прокидатися' },
    { base: 'put', past: 'put', pp: 'put', ru: 'Класть (надевать)', uk: 'Класти (надягати)' },
    { base: 'lose', past: 'lost', pp: 'lost', ru: 'Терять', uk: 'Втрачати' },
    { base: 'take', past: 'took', pp: 'taken', ru: 'Брать (снимать)', uk: 'Брати (знімати)' },
    { base: 'go', past: 'went', pp: 'gone', ru: 'Идти', uk: 'Йти' },
    { base: 'get', past: 'got', pp: 'got', ru: 'Получать (входить/выходить)', uk: 'Отримувати (входити/виходити)' },
    { base: 'throw', past: 'threw', pp: 'thrown', ru: 'Бросать', uk: 'Кидати' },
    { base: 'give', past: 'gave', pp: 'given', ru: 'Давать', uk: 'Давати' },
    { base: 'find', past: 'found', pp: 'found', ru: 'Находить', uk: 'Знаходити' },
    { base: 'sit', past: 'sat', pp: 'sat', ru: 'Сидеть', uk: 'Сидіти' },
    { base: 'see', past: 'saw', pp: 'seen', ru: 'Видеть', uk: 'Бачити' },
    { base: 'bring', past: 'brought', pp: 'brought', ru: 'Приносить', uk: 'Приносити' },
    { base: 'deal', past: 'dealt', pp: 'dealt', ru: 'Иметь дело', uk: 'Мати справу' },
    { base: 'hang', past: 'hung', pp: 'hung', ru: 'Вешать', uk: 'Вішати' },
    { base: 'come', past: 'came', pp: 'come', ru: 'Приходить', uk: 'Приходити' },
  ],
  17: [
    { base: 'read', past: 'read', pp: 'read', ru: 'Читать', uk: 'Читати' },
    { base: 'write', past: 'wrote', pp: 'written', ru: 'Писать', uk: 'Писати' },
    { base: 'build', past: 'built', pp: 'built', ru: 'Строить', uk: 'Будувати' },
    { base: 'bring', past: 'brought', pp: 'brought', ru: 'Приносить', uk: 'Приносити' },
    { base: 'choose', past: 'chose', pp: 'chosen', ru: 'Выбирать', uk: 'Обирати' },
    { base: 'cut', past: 'cut', pp: 'cut', ru: 'Резать', uk: 'Різати' },
    { base: 'throw', past: 'threw', pp: 'thrown', ru: 'Бросать', uk: 'Кидати' },
    { base: 'set', past: 'set', pp: 'set', ru: 'Накрывать (на стол)', uk: 'Накривати' },
    { base: 'hang', past: 'hung', pp: 'hung', ru: 'Вешать', uk: 'Вішати' },
    { base: 'draw', past: 'drew', pp: 'drawn', ru: 'Рисовать', uk: 'Малювати' },
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
    { base: 'lose', past: 'lost', pp: 'lost', ru: 'Терять', uk: 'Втрачати' },
  ],
  18: [
    { base: 'put', past: 'put', pp: 'put', ru: 'Класть', uk: 'Класти' },
    { base: 'leave', past: 'left', pp: 'left', ru: 'Оставлять', uk: 'Залишати' },
    { base: 'bring', past: 'brought', pp: 'brought', ru: 'Приносить', uk: 'Приносити' },
    { base: 'buy', past: 'bought', pp: 'bought', ru: 'Покупать', uk: 'Купувати' },
    { base: 'cut', past: 'cut', pp: 'cut', ru: 'Резать', uk: 'Різати' },
    { base: 'forget', past: 'forgot', pp: 'forgotten', ru: 'Забывать', uk: 'Забувати' },
    { base: 'meet', past: 'met', pp: 'met', ru: 'Встречать', uk: 'Зустрічати' },
    { base: 'send', past: 'sent', pp: 'sent', ru: 'Отправлять', uk: 'Відправляти' },
    { base: 'hang', past: 'hung', pp: 'hung', ru: 'Вешать', uk: 'Вішати' },
    { base: 'drink', past: 'drank', pp: 'drunk', ru: 'Пить', uk: 'Пити' },
    { base: 'take', past: 'took', pp: 'taken', ru: 'Брать', uk: 'Брати' },
    { base: 'choose', past: 'chose', pp: 'chosen', ru: 'Выбирать', uk: 'Обирати' },
    { base: 'show', past: 'showed', pp: 'shown', ru: 'Показывать', uk: 'Показувати' },
    { base: 'read', past: 'read', pp: 'read', ru: 'Читать', uk: 'Читати' },
    { base: 'feed', past: 'fed', pp: 'fed', ru: 'Кормить', uk: 'Годувати' },
    { base: 'build', past: 'built', pp: 'built', ru: 'Строить', uk: 'Будувати' },
    { base: 'lose', past: 'lost', pp: 'lost', ru: 'Терять', uk: 'Губити' },
    { base: 'break', past: 'broke', pp: 'broken', ru: 'Ломать', uk: 'Ламати' },
    { base: 'hide', past: 'hid', pp: 'hidden', ru: 'Прятать', uk: 'Ховати' },
    { base: 'write', past: 'wrote', pp: 'written', ru: 'Писать', uk: 'Писати' },
    { base: 'throw', past: 'threw', pp: 'thrown', ru: 'Бросать', uk: 'Кидати' },
    { base: 'eat', past: 'ate', pp: 'eaten', ru: 'Есть', uk: 'Їсти' },
    { base: 'spend', past: 'spent', pp: 'spent', ru: 'Тратить', uk: 'Витрачати' },
  ],
};

export const LESSONS_WITH_IRREGULAR_VERBS: Set<number> = new Set(Object.keys(IRREGULAR_VERBS_BY_LESSON).map(Number));
export const IRREGULAR_VERB_COUNT_BY_LESSON: Record<number, number> = Object.fromEntries(
  Object.entries(IRREGULAR_VERBS_BY_LESSON).map(([k, v]) => [Number(k), v.length])
);
