import type { LessonIntroScreen } from './lesson_data_types';

export const LESSON_21_INTRO_EXTRA: LessonIntroScreen[] = [
  {
    lessonId: 21,
    screenId: 'lesson_21_intro_1_people_words',
    order: 1,
    kind: 'concept',
    titleRU: 'Кто-то, никто, все',
    titleUK: 'Хтось, ніхто, всі',
    titleES: 'Someone, nobody, everyone',
    titlePtBr: 'Alguém, ninguém, todos',
    titleVi: 'Ai đó, không ai, mọi người',
    titleId: 'Seseorang, tidak ada orang, semua orang',
    titleTr: 'Biri, kimse, herkes',
    titlePl: 'Ktoś, nikt, wszyscy',
    subtitleRU: 'В этом уроке ты говоришь о людях, когда имя не важно или неизвестно.',
    subtitleUK: 'У цьому уроці ти говориш про людей, коли ім\'я не важливе або невідоме.',
    subtitleES: 'In this lesson, you talk about people when the name is not important or unknown.',
    subtitlePtBr: 'Nesta lição, você fala de pessoas quando o nome não importa ou é desconhecido.',
    subtitleVi: 'Trong bài này, bạn nói về người khi tên không quan trọng hoặc không biết.',
    subtitleId: 'Dalam pelajaran ini, kamu membicarakan orang saat namanya tidak penting atau tidak diketahui.',
    subtitleTr: 'Bu derste isim önemli olmadığında veya bilinmediğinde insanlardan söz edersin.',
    subtitlePl: 'W tej lekcji mówisz o ludziach, gdy imię nie jest ważne albo nie jest znane.',
    textRU: 'Слова с -one и -body говорят о людях: кто-то, никто, все.',
    textUK: 'Слова з -one і -body говорять про людей: хтось, ніхто, всі.',
    textES: 'Words with -one and -body talk about people: someone, nobody, everyone.',
    textPtBr: 'Palavras com -one e -body falam de pessoas: someone, nobody, everyone.',
    textVi: 'Các từ có -one và -body nói về người: someone, nobody, everyone.',
    textId: 'Kata dengan -one dan -body membicarakan orang: someone, nobody, everyone.',
    textTr: '-one ve -body ile biten kelimeler insanları anlatır: someone, nobody, everyone.',
    textPl: 'Słowa z -one i -body mówią o ludziach: someone, nobody, everyone.',
    linesRU: [
      { type: 'text', parts: [{ text: 'Если речь о человеке, но ты не называешь имя, английский использует готовые слова:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = кто-то', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = никто', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = все', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Somebody', tone: 'accent' }, { text: ' knocked on the door' }] },
      { type: 'correct', parts: [{ text: 'No one', tone: 'warning' }, { text: ' knows it' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
      { type: 'correct', parts: [{ text: 'Everyone', tone: 'accent' }, { text: ' is ready' }] },
      { type: 'correct', parts: [{ text: 'Everybody', tone: 'accent' }, { text: ' understands me' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главная идея: ', tone: 'strong' }, { text: 'no one / nobody уже несут отрицание, отдельное not не нужно.' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'No one does not know it', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'No one', tone: 'warning' }, { text: ' knows it' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'Якщо йдеться про людину, але ти не називаєш ім\'я, англійська використовує готові слова:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = хтось', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = ніхто', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = всі', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
      { type: 'correct', parts: [{ text: 'Everyone', tone: 'accent' }, { text: ' is ready' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'Use these words when the person is unknown or not named:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = someone', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = nobody', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = everyone', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
    ],
    linesPtBr: [
      { type: 'text', parts: [{ text: 'Use estas palavras quando a pessoa é desconhecida ou não é nomeada:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = alguém', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = ninguém', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = todos', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
      { type: 'tip', parts: [{ text: 'Ideia principal: ', tone: 'strong' }, { text: 'no one / nobody já é negativo; não adicione not.' }] },
    ],
    linesVi: [
      { type: 'text', parts: [{ text: 'Dùng các từ này khi người đó không rõ hoặc không được nêu tên:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = ai đó', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = không ai', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = mọi người', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
      { type: 'tip', parts: [{ text: 'Ý chính: ', tone: 'strong' }, { text: 'no one / nobody đã mang nghĩa phủ định; không thêm not.' }] },
    ],
    linesId: [
      { type: 'text', parts: [{ text: 'Gunakan kata-kata ini saat orangnya tidak diketahui atau tidak disebutkan:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = seseorang', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = tidak ada orang', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = semua orang', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
      { type: 'tip', parts: [{ text: 'Ide utama: ', tone: 'strong' }, { text: 'no one / nobody sudah negatif; jangan tambahkan not.' }] },
    ],
    linesTr: [
      { type: 'text', parts: [{ text: 'Kişi bilinmiyorsa veya adı söylenmiyorsa bu kelimeleri kullan:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = biri', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = kimse', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = herkes', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
      { type: 'tip', parts: [{ text: 'Ana fikir: ', tone: 'strong' }, { text: 'no one / nobody zaten olumsuzdur; ayrıca not ekleme.' }] },
    ],
    linesPl: [
      { type: 'text', parts: [{ text: 'Używaj tych słów, gdy osoba jest nieznana albo nie podajesz imienia:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = ktoś', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = nikt', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = wszyscy', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
      { type: 'tip', parts: [{ text: 'Główna myśl: ', tone: 'strong' }, { text: 'no one / nobody już ma znaczenie przeczące; nie dodawaj not.' }] },
    ],
    examples: [
      {
        labelRU: 'кто-то',
        labelUK: 'хтось',
        labelES: 'someone',
        labelPtBr: 'alguém',
        labelVi: 'ai đó',
        labelId: 'seseorang',
        labelTr: 'biri',
        labelPl: 'ktoś',
        en: [{ text: 'Someone', tone: 'accent' }, { text: ' left a message' }],
        ru: 'Кто-то оставил сообщение',
        uk: 'Хтось залишив повідомлення',
        es: 'Alguien dejó un mensaje.',
        'pt-BR': 'Alguém deixou uma mensagem.',
        vi: 'Ai đó đã để lại một tin nhắn.',
        id: 'Seseorang meninggalkan pesan.',
        tr: 'Biri mesaj bıraktı.',
        pl: 'Ktoś zostawił wiadomość.',
        trRU: 'Кто-то оставил сообщение',
        trUK: 'Хтось залишив повідомлення',
        trES: 'Alguien dejó un mensaje.',
        noteRU: 'Someone говорит о человеке, имя не важно или неизвестно.',
        noteUK: 'Someone говорить про людину, ім\'я не важливе або невідоме.',
        noteES: 'Someone refers to a person whose name is not important or unknown.',
        notePtBr: 'Someone se refere a uma pessoa cujo nome não importa ou é desconhecido.',
        noteVi: 'Someone nói về một người có tên không quan trọng hoặc không biết.',
        noteId: 'Someone merujuk pada orang yang namanya tidak penting atau tidak diketahui.',
        noteTr: 'Someone, adı önemli olmayan veya bilinmeyen bir kişiyi anlatır.',
        notePl: 'Someone odnosi się do osoby, której imię nie jest ważne albo znane.',
      },
      {
        labelRU: 'никто',
        labelUK: 'ніхто',
        labelES: 'nobody',
        labelPtBr: 'ninguém',
        labelVi: 'không ai',
        labelId: 'tidak ada orang',
        labelTr: 'kimse',
        labelPl: 'nikt',
        en: [{ text: 'Nobody', tone: 'warning' }, { text: ' left a message' }],
        ru: 'Никто не оставил сообщение',
        uk: 'Ніхто не залишив повідомлення',
        es: 'Nadie dejó un mensaje.',
        'pt-BR': 'Ninguém deixou uma mensagem.',
        vi: 'Không ai để lại tin nhắn.',
        id: 'Tidak ada yang meninggalkan pesan.',
        tr: 'Kimse mesaj bırakmadı.',
        pl: 'Nikt nie zostawił wiadomości.',
        trRU: 'Никто не оставил сообщение',
        trUK: 'Ніхто не залишив повідомлення',
        trES: 'Nadie dejó un mensaje.',
        noteRU: 'Nobody уже значит "никто", поэтому отдельное not не нужно.',
        noteUK: 'Nobody вже означає "ніхто", тому окреме not не потрібне.',
        noteES: 'Nobody already means "no person", so no extra not is needed.',
        notePtBr: 'Nobody já significa "nenhuma pessoa", então não precisa de outro not.',
        noteVi: 'Nobody đã có nghĩa là "không ai", nên không cần thêm not.',
        noteId: 'Nobody sudah berarti "tidak ada orang", jadi tidak perlu not tambahan.',
        noteTr: 'Nobody zaten "kimse yok" anlamındadır, bu yüzden ekstra not gerekmez.',
        notePl: 'Nobody już znaczy "nikt", więc dodatkowe not nie jest potrzebne.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран вводит слова для людей: someone/somebody, no one/nobody, everyone/everybody.',
      visualPriority: ['someone/somebody/everyone/everybody выделять accent.', 'no one/nobody выделять warning.', 'ошибку двойного отрицания выделять danger.'],
      highlightRules: ['positive/neutral indefinite person word = accent.', 'negative person word = warning.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять somewhere/nowhere.', 'Не добавлять every one как два слова.', 'Не использовать фразы вне урока 21.'],
      layoutRules: ['Один экран - только слова про людей.', 'Если экран узкий, оставить someone, nobody, everyone и ошибку No one does not.'],
    },
  },
  {
    lessonId: 21,
    screenId: 'lesson_21_intro_2_thing_words',
    order: 2,
    kind: 'formula',
    titleRU: 'Что-то, ничего, все',
    titleUK: 'Щось, нічого, все',
    titleES: 'Something, nothing, everything',
    titlePtBr: 'Algo, nada, tudo',
    titleVi: 'Điều gì đó, không có gì, mọi thứ',
    titleId: 'Sesuatu, tidak ada apa-apa, semuanya',
    titleTr: 'Bir şey, hiçbir şey, her şey',
    titlePl: 'Coś, nic, wszystko',
    subtitleRU: 'Слова с -thing говорят не о людях, а о вещах, событиях или идеях.',
    subtitleUK: 'Слова з -thing говорять не про людей, а про речі, події або ідеї.',
    subtitleES: 'Words with -thing talk about things, events, or ideas, not people.',
    subtitlePtBr: 'Palavras com -thing falam de coisas, eventos ou ideias, não de pessoas.',
    subtitleVi: 'Các từ có -thing nói về vật, sự việc hoặc ý tưởng, không phải người.',
    subtitleId: 'Kata dengan -thing membicarakan benda, kejadian, atau ide, bukan orang.',
    subtitleTr: '-thing ile biten kelimeler insanları değil; şeyleri, olayları veya fikirleri anlatır.',
    subtitlePl: 'Słowa z -thing mówią o rzeczach, wydarzeniach albo pomysłach, nie o ludziach.',
    textRU: 'Something/anything/nothing/everything отвечают на "что?", а не на "кто?".',
    textUK: 'Something/anything/nothing/everything відповідають на "що?", а не на "хто?".',
    textES: 'Something/anything/nothing/everything answer "what?", not "who?".',
    textPtBr: 'Something/anything/nothing/everything respondem a "o quê?", não a "quem?".',
    textVi: 'Something/anything/nothing/everything trả lời "cái gì?", không phải "ai?".',
    textId: 'Something/anything/nothing/everything menjawab "apa?", bukan "siapa?".',
    textTr: 'Something/anything/nothing/everything "ne?" sorusuna cevap verir, "kim?" sorusuna değil.',
    textPl: 'Something/anything/nothing/everything odpowiadają na "co?", nie na "kto?".',
    linesRU: [
      { type: 'formula', parts: [{ text: 'something', tone: 'accent' }, { text: ' = что-то', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'anything', tone: 'accent' }, { text: ' = что-нибудь / ничего в отрицании', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'nothing', tone: 'warning' }, { text: ' = ничего', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everything', tone: 'accent' }, { text: ' = все', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Everything', tone: 'accent' }, { text: ' is okay' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' is wrong' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' is wrong' }] },
      { type: 'correct', parts: [{ text: 'Everything', tone: 'accent' }, { text: ' is clear' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I found ' }, { text: 'something', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'I found ' }, { text: 'nothing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I do not need ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Nothing did not happen', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'something', tone: 'accent' }, { text: ' = щось', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'anything', tone: 'accent' }, { text: ' = щось / нічого в запереченні', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'nothing', tone: 'warning' }, { text: ' = нічого', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everything', tone: 'accent' }, { text: ' = все', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'something / anything / nothing / everything', tone: 'accent' }, { text: ' = thing words', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
    ],
    linesPtBr: [
      { type: 'formula', parts: [{ text: 'something', tone: 'accent' }, { text: ' = algo', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'anything', tone: 'accent' }, { text: ' = algo / nada com not', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'nothing', tone: 'warning' }, { text: ' = nada', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everything', tone: 'accent' }, { text: ' = tudo', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
      { type: 'wrong', parts: [{ text: 'Errado: ', tone: 'warning' }, { text: 'Nothing did not happen', tone: 'danger' }] },
    ],
    linesVi: [
      { type: 'formula', parts: [{ text: 'something', tone: 'accent' }, { text: ' = điều gì đó', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'anything', tone: 'accent' }, { text: ' = bất cứ điều gì / không gì với not', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'nothing', tone: 'warning' }, { text: ' = không có gì', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everything', tone: 'accent' }, { text: ' = mọi thứ', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
      { type: 'wrong', parts: [{ text: 'Sai: ', tone: 'warning' }, { text: 'Nothing did not happen', tone: 'danger' }] },
    ],
    linesId: [
      { type: 'formula', parts: [{ text: 'something', tone: 'accent' }, { text: ' = sesuatu', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'anything', tone: 'accent' }, { text: ' = apa pun / tidak apa-apa dengan not', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'nothing', tone: 'warning' }, { text: ' = tidak ada apa-apa', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everything', tone: 'accent' }, { text: ' = semuanya', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
      { type: 'wrong', parts: [{ text: 'Salah: ', tone: 'warning' }, { text: 'Nothing did not happen', tone: 'danger' }] },
    ],
    linesTr: [
      { type: 'formula', parts: [{ text: 'something', tone: 'accent' }, { text: ' = bir şey', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'anything', tone: 'accent' }, { text: ' = herhangi bir şey / not ile hiçbir şey', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'nothing', tone: 'warning' }, { text: ' = hiçbir şey', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everything', tone: 'accent' }, { text: ' = her şey', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
      { type: 'wrong', parts: [{ text: 'Yanlış: ', tone: 'warning' }, { text: 'Nothing did not happen', tone: 'danger' }] },
    ],
    linesPl: [
      { type: 'formula', parts: [{ text: 'something', tone: 'accent' }, { text: ' = coś', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'anything', tone: 'accent' }, { text: ' = cokolwiek / nic po not', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'nothing', tone: 'warning' }, { text: ' = nic', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everything', tone: 'accent' }, { text: ' = wszystko', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
      { type: 'wrong', parts: [{ text: 'Błędnie: ', tone: 'warning' }, { text: 'Nothing did not happen', tone: 'danger' }] },
    ],
    examples: [
      {
        labelRU: 'something',
        labelUK: 'something',
        labelES: 'something',
        labelPtBr: 'something',
        labelVi: 'something',
        labelId: 'something',
        labelTr: 'something',
        labelPl: 'something',
        en: [{ text: 'I found ' }, { text: 'something', tone: 'accent' }],
        ru: 'Я что-то нашел',
        uk: 'Я щось знайшов',
        es: 'Encontré algo.',
        'pt-BR': 'Encontrei algo.',
        vi: 'Tôi đã tìm thấy thứ gì đó.',
        id: 'Saya menemukan sesuatu.',
        tr: 'Bir şey buldum.',
        pl: 'Znalazłem coś.',
        trRU: 'Я что-то нашел',
        trUK: 'Я щось знайшов',
        trES: 'Encontré algo.',
        noteRU: 'Something говорит о вещи или идее, а не о человеке.',
        noteUK: 'Something говорить про річ або ідею, не про людину.',
        noteES: 'Something refers to a thing or idea, not a person.',
        notePtBr: 'Something se refere a uma coisa ou ideia, não a uma pessoa.',
        noteVi: 'Something nói về vật hoặc ý tưởng, không phải người.',
        noteId: 'Something merujuk pada benda atau ide, bukan orang.',
        noteTr: 'Something bir şeyi veya fikri anlatır, kişiyi değil.',
        notePl: 'Something odnosi się do rzeczy albo pomysłu, nie do osoby.',
      },
      {
        labelRU: 'anything',
        labelUK: 'anything',
        labelES: 'anything',
        labelPtBr: 'anything',
        labelVi: 'anything',
        labelId: 'anything',
        labelTr: 'anything',
        labelPl: 'anything',
        en: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }],
        ru: 'Он ничего не хочет',
        uk: 'Він нічого не хоче',
        es: 'Él no quiere nada.',
        'pt-BR': 'Ele não quer nada.',
        vi: 'Anh ấy không muốn gì cả.',
        id: 'Dia tidak menginginkan apa pun.',
        tr: 'Hiçbir şey istemiyor.',
        pl: 'On niczego nie chce.',
        trRU: 'Он ничего не хочет',
        trUK: 'Він нічого не хоче',
        trES: 'Él no quiere nada.',
        noteRU: 'После does not используется anything, не nothing.',
        noteUK: 'Після does not використовується anything, не nothing.',
        noteES: 'After does not, use anything, not nothing.',
        notePtBr: 'Depois de does not, use anything, não nothing.',
        noteVi: 'Sau does not, dùng anything, không dùng nothing.',
        noteId: 'Setelah does not, gunakan anything, bukan nothing.',
        noteTr: 'Does not sonrasında nothing değil anything kullan.',
        notePl: 'Po does not użyj anything, nie nothing.',
      },
      {
        labelRU: 'nothing',
        labelUK: 'nothing',
        labelES: 'nothing',
        labelPtBr: 'nothing',
        labelVi: 'nothing',
        labelId: 'nothing',
        labelTr: 'nothing',
        labelPl: 'nothing',
        en: [{ text: 'Nothing', tone: 'warning' }, { text: ' changed yesterday' }],
        ru: 'Ничего не изменилось вчера',
        uk: 'Нічого не змінилося вчора',
        es: 'Nada cambió ayer.',
        'pt-BR': 'Nada mudou ontem.',
        vi: 'Hôm qua không có gì thay đổi.',
        id: 'Tidak ada yang berubah kemarin.',
        tr: 'Dün hiçbir şey değişmedi.',
        pl: 'Nic się wczoraj nie zmieniło.',
        trRU: 'Ничего не изменилось вчера',
        trUK: 'Нічого не змінилося вчора',
        trES: 'Nada cambió ayer.',
        noteRU: 'Nothing уже отрицательное, поэтому did not не нужен.',
        noteUK: 'Nothing вже заперечне, тому did not не потрібен.',
        noteES: 'Nothing is already negative, so did not is not needed.',
        notePtBr: 'Nothing já é negativo, então did not não é necessário.',
        noteVi: 'Nothing đã mang nghĩa phủ định, nên không cần did not.',
        noteId: 'Nothing sudah negatif, jadi did not tidak diperlukan.',
        noteTr: 'Nothing zaten olumsuzdur, bu yüzden did not gerekmez.',
        notePl: 'Nothing jest już przeczące, więc did not nie jest potrzebne.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран объясняет words for things/events: something, anything, nothing, everything.',
      visualPriority: ['something/anything/everything выделять accent.', 'nothing выделять warning.', 'ошибку Nothing did not happen выделять danger.'],
      highlightRules: ['neutral/positive thing word = accent.', 'negative thing word = warning.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять somewhere/nowhere.', 'Не добавлять every thing как два слова.', 'Не использовать фразы вне урока 21.'],
      layoutRules: ['Один экран - только слова про вещи/события.', 'Если экран узкий, оставить something, anything, nothing, everything и 2 примера.'],
    },
  },
  {
    lessonId: 21,
    screenId: 'lesson_21_intro_3_questions_anyone_anything',
    order: 3,
    kind: 'formula',
    titleRU: 'Вопросы: anyone / anybody / anything',
    titleUK: 'Питання: anyone / anybody / anything',
    titleES: 'Questions: anyone / anybody / anything',
    titlePtBr: 'Perguntas: anyone / anybody / anything',
    titleVi: 'Câu hỏi: anyone / anybody / anything',
    titleId: 'Pertanyaan: anyone / anybody / anything',
    titleTr: 'Sorular: anyone / anybody / anything',
    titlePl: 'Pytania: anyone / anybody / anything',
    subtitleRU: 'В вопросах "кто-нибудь / что-нибудь" часто становятся anyone / anybody / anything.',
    subtitleUK: 'У питаннях "хтось / щось" часто стають anyone / anybody / anything.',
    subtitleES: 'In questions, "someone / something" often becomes anyone / anybody / anything.',
    subtitlePtBr: 'Em perguntas, "alguém / algo" muitas vezes vira anyone / anybody / anything.',
    subtitleVi: 'Trong câu hỏi, "ai đó / điều gì đó" thường thành anyone / anybody / anything.',
    subtitleId: 'Dalam pertanyaan, "seseorang / sesuatu" sering menjadi anyone / anybody / anything.',
    subtitleTr: 'Sorularda "biri / bir şey" çoğu zaman anyone / anybody / anything olur.',
    subtitlePl: 'W pytaniach "ktoś / coś" często zmienia się w anyone / anybody / anything.',
    textRU: 'Вопросы этого урока часто используют any-слова.',
    textUK: 'Питання цього уроку часто використовують any-слова.',
    textES: 'Questions in this lesson often use any-words.',
    textPtBr: 'As perguntas desta lição muitas vezes usam palavras com any-.',
    textVi: 'Các câu hỏi trong bài này thường dùng từ any-.',
    textId: 'Pertanyaan dalam pelajaran ini sering memakai kata any-.',
    textTr: 'Bu dersteki sorular çoğu zaman any- kelimelerini kullanır.',
    textPl: 'Pytania w tej lekcji często używają słów z any-.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody', tone: 'accent' }, { text: ' + действие?', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anybody see him?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone find my keys?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anybody bring documents?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone see my bag?', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Did you + действие + ', tone: 'formula' }, { text: 'anything?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Is', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone', tone: 'accent' }, { text: ' + место?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'warning' }, { text: ' anyone here?', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Did anyone called you?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody', tone: 'accent' }, { text: ' + дія?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'warning' }, { text: ' anyone here?', tone: 'accent' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody / anything', tone: 'accent' }, { text: ' + action?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
    ],
    linesPtBr: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody', tone: 'accent' }, { text: ' + ação?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }] },
      { type: 'formula', parts: [{ text: 'Is', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone', tone: 'accent' }, { text: ' + lugar?', tone: 'formula' }] },
      { type: 'wrong', parts: [{ text: 'Errado: ', tone: 'warning' }, { text: 'Did anyone called you?', tone: 'danger' }] },
    ],
    linesVi: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody', tone: 'accent' }, { text: ' + hành động?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }] },
      { type: 'formula', parts: [{ text: 'Is', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone', tone: 'accent' }, { text: ' + nơi chốn?', tone: 'formula' }] },
      { type: 'wrong', parts: [{ text: 'Sai: ', tone: 'warning' }, { text: 'Did anyone called you?', tone: 'danger' }] },
    ],
    linesId: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody', tone: 'accent' }, { text: ' + aksi?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }] },
      { type: 'formula', parts: [{ text: 'Is', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone', tone: 'accent' }, { text: ' + tempat?', tone: 'formula' }] },
      { type: 'wrong', parts: [{ text: 'Salah: ', tone: 'warning' }, { text: 'Did anyone called you?', tone: 'danger' }] },
    ],
    linesTr: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody', tone: 'accent' }, { text: ' + eylem?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }] },
      { type: 'formula', parts: [{ text: 'Is', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone', tone: 'accent' }, { text: ' + yer?', tone: 'formula' }] },
      { type: 'wrong', parts: [{ text: 'Yanlış: ', tone: 'warning' }, { text: 'Did anyone called you?', tone: 'danger' }] },
    ],
    linesPl: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody', tone: 'accent' }, { text: ' + czynność?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }] },
      { type: 'formula', parts: [{ text: 'Is', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone', tone: 'accent' }, { text: ' + miejsce?', tone: 'formula' }] },
      { type: 'wrong', parts: [{ text: 'Błędnie: ', tone: 'warning' }, { text: 'Did anyone called you?', tone: 'danger' }] },
    ],
    examples: [
      {
        labelRU: 'anyone',
        labelUK: 'anyone',
        labelES: 'anyone',
        labelPtBr: 'anyone',
        labelVi: 'anyone',
        labelId: 'anyone',
        labelTr: 'anyone',
        labelPl: 'anyone',
        en: [{ text: 'Did', tone: 'warning' }, { text: ' anyone find my keys?', tone: 'accent' }],
        ru: 'Кто-нибудь нашел мои ключи?',
        uk: 'Хтось знайшов мої ключі?',
        es: '¿Alguien encontró mis llaves?',
        'pt-BR': 'Alguém encontrou minhas chaves?',
        vi: 'Có ai tìm thấy chìa khóa của tôi không?',
        id: 'Apakah ada yang menemukan kunci saya?',
        tr: 'Anahtarlarımı bulan oldu mu?',
        pl: 'Czy ktoś znalazł moje klucze?',
        trRU: 'Кто-нибудь нашел мои ключи?',
        trUK: 'Хтось знайшов мої ключі?',
        trES: '¿Alguien encontró mis llaves?',
        noteRU: 'После Did основной глагол find без прошлой формы found.',
        noteUK: 'Після Did головне дієслово find без минулої форми found.',
        noteES: 'After Did, use find, not found.',
        notePtBr: 'Depois de Did, use find, não found.',
        noteVi: 'Sau Did, dùng find, không dùng found.',
        noteId: 'Setelah Did, gunakan find, bukan found.',
        noteTr: 'Did sonrasında found değil find kullan.',
        notePl: 'Po Did użyj find, nie found.',
      },
      {
        labelRU: 'anything',
        labelUK: 'anything',
        labelES: 'anything',
        labelPtBr: 'anything',
        labelVi: 'anything',
        labelId: 'anything',
        labelTr: 'anything',
        labelPl: 'anything',
        en: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }],
        ru: 'Ты что-нибудь слышал?',
        uk: 'Ти щось чув?',
        es: '¿Escuchaste algo?',
        'pt-BR': 'Você ouviu alguma coisa?',
        vi: 'Bạn có nghe thấy gì không?',
        id: 'Apakah kamu mendengar sesuatu?',
        tr: 'Bir şey duydun mu?',
        pl: 'Czy coś słyszałeś?',
        trRU: 'Ты что-нибудь слышал?',
        trUK: 'Ти щось чув?',
        trES: '¿Escuchaste algo?',
        noteRU: 'Anything говорит о "что-нибудь" в вопросе.',
        noteUK: 'Anything говорить про "щось" у питанні.',
        noteES: 'Anything means "anything" in a question.',
        notePtBr: 'Anything expressa "alguma coisa" em uma pergunta.',
        noteVi: 'Anything diễn đạt "điều gì đó" trong câu hỏi.',
        noteId: 'Anything berarti "sesuatu" dalam pertanyaan.',
        noteTr: 'Anything soruda "bir şey" anlamı verir.',
        notePl: 'Anything w pytaniu znaczy "coś / cokolwiek".',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран отдельно закрепляет вопросы с anyone/anybody/anything.',
      visualPriority: ['Did / Is выделять warning.', 'anyone/anybody/anything выделять accent.', 'ошибку Did anyone called выделять danger.'],
      highlightRules: ['question helper = warning.', 'any-word = accent.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять why/where/how questions.', 'Не добавлять somewhere/anywhere.', 'Не добавлять any как quantifier.', 'Не использовать фразы вне урока 21.'],
      layoutRules: ['Один экран - только вопросы с any-словами.', 'Если экран узкий, оставить Did anyone call, Did you hear anything, Is anyone here.'],
    },
  },
  {
    lessonId: 21,
    screenId: 'lesson_21_intro_4_negatives_practice',
    order: 4,
    kind: 'practice',
    titleRU: 'Отрицание: nobody или not anything',
    titleUK: 'Заперечення: nobody або not anything',
    titleES: 'Negatives: nobody or not anything',
    titlePtBr: 'Negativas: nobody ou not anything',
    titleVi: 'Phủ định: nobody hoặc not anything',
    titleId: 'Negatif: nobody atau not anything',
    titleTr: 'Olumsuzluk: nobody ya da not anything',
    titlePl: 'Przeczenia: nobody albo not anything',
    subtitleRU: 'В английском нельзя бездумно складывать два отрицания. Выбирай один путь.',
    subtitleUK: 'В англійській не можна бездумно складати два заперечення. Обирай один шлях.',
    subtitleES: 'In English, do not stack two negatives blindly. Choose one path.',
    subtitlePtBr: 'Em inglês, não empilhe duas negativas sem pensar. Escolha um caminho.',
    subtitleVi: 'Trong tiếng Anh, đừng chồng hai phủ định một cách máy móc. Hãy chọn một cách.',
    subtitleId: 'Dalam bahasa Inggris, jangan menumpuk dua negatif sembarangan. Pilih satu jalur.',
    subtitleTr: 'İngilizcede iki olumsuzluğu düşünmeden üst üste koyma. Tek bir yol seç.',
    subtitlePl: 'W angielskim nie dokładaj dwóch przeczeń bez namysłu. Wybierz jedną drogę.',
    textRU: 'Есть два пути: nobody/nothing или do not/does not + anything.',
    textUK: 'Є два шляхи: nobody/nothing або do not/does not + anything.',
    textES: 'There are two paths: nobody/nothing or do not/does not + anything.',
    textPtBr: 'Há dois caminhos: nobody/nothing ou do not/does not + anything.',
    textVi: 'Có hai cách: nobody/nothing hoặc do not/does not + anything.',
    textId: 'Ada dua jalur: nobody/nothing atau do not/does not + anything.',
    textTr: 'İki yol var: nobody/nothing ya da do not/does not + anything.',
    textPl: 'Są dwie drogi: nobody/nothing albo do not/does not + anything.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' уже дают отрицание', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'correct', parts: [{ text: 'No one', tone: 'warning' }, { text: ' needs help' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' changed yesterday' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' saw my bag' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' = тоже отрицательный смысл', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I do not need ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'She does not know ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Видишь nobody / nothing / no one? ', tone: 'muted' }, { text: 'Не добавляй еще одно not.', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '2. Видишь do not / does not? ', tone: 'muted' }, { text: 'После него чаще будет anything.', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. В вопросе после Did? ', tone: 'muted' }, { text: 'anyone / anybody / anything.', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Nobody did not help them', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Nobody', tone: 'warning' }, { text: ' helped them' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'He does not want nothing', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'tip', parts: [{ text: 'Главный навык урока: ', tone: 'strong' }, { text: 'понять, говоришь ты о человеке или вещи, и не смешивать no-слово с лишним not.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' уже дають заперечення', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' changed yesterday' }] },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' = теж заперечний зміст', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I do not need ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Nobody did not help them', tone: 'danger' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' already make the sentence negative', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' also gives a negative meaning', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
    ],
    linesPtBr: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' já deixam a frase negativa', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' também dá sentido negativo', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Errado: ', tone: 'warning' }, { text: 'Nobody did not help them', tone: 'danger' }] },
    ],
    linesVi: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' đã làm câu mang nghĩa phủ định', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' cũng tạo nghĩa phủ định', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Sai: ', tone: 'warning' }, { text: 'Nobody did not help them', tone: 'danger' }] },
    ],
    linesId: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' sudah membuat kalimat negatif', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' juga memberi makna negatif', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Salah: ', tone: 'warning' }, { text: 'Nobody did not help them', tone: 'danger' }] },
    ],
    linesTr: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' cümleyi zaten olumsuz yapar', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' de olumsuz anlam verir', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Yanlış: ', tone: 'warning' }, { text: 'Nobody did not help them', tone: 'danger' }] },
    ],
    linesPl: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' już nadaje zdaniu sens przeczący', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' też daje sens przeczący', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Błędnie: ', tone: 'warning' }, { text: 'Nobody did not help them', tone: 'danger' }] },
    ],
    examples: [
      {
        labelRU: 'nobody',
        labelUK: 'nobody',
        labelES: 'nobody',
        labelPtBr: 'nobody',
        labelVi: 'nobody',
        labelId: 'nobody',
        labelTr: 'nobody',
        labelPl: 'nobody',
        en: [{ text: 'Nobody', tone: 'warning' }, { text: ' brought documents' }],
        ru: 'Никто не принес документы',
        uk: 'Ніхто не приніс документи',
        es: 'Nadie trajo documentos.',
        'pt-BR': 'Ninguém trouxe os documentos.',
        vi: 'Không ai mang tài liệu đến.',
        id: 'Tidak ada yang membawa dokumen.',
        tr: 'Kimse belgeleri getirmedi.',
        pl: 'Nikt nie przyniósł dokumentów.',
        trRU: 'Никто не принес документы',
        trUK: 'Ніхто не приніс документи',
        trES: 'Nadie trajo documentos.',
        noteRU: 'Nobody уже отрицательное. Не нужно did not.',
        noteUK: 'Nobody вже заперечне. Не потрібно did not.',
        noteES: 'Nobody is already negative. Do not add did not.',
        notePtBr: 'Nobody já é negativo. Não adicione did not.',
        noteVi: 'Nobody đã phủ định rồi. Không thêm did not.',
        noteId: 'Nobody sudah negatif. Jangan tambahkan did not.',
        noteTr: 'Nobody zaten olumsuzdur. Did not ekleme.',
        notePl: 'Nobody jest już przeczące. Nie dodawaj did not.',
      },
      {
        labelRU: 'not anything',
        labelUK: 'not anything',
        labelES: 'not anything',
        labelPtBr: 'not anything',
        labelVi: 'not anything',
        labelId: 'not anything',
        labelTr: 'not anything',
        labelPl: 'not anything',
        en: [{ text: 'I do not need ' }, { text: 'anything', tone: 'accent' }],
        ru: 'Мне ничего не нужно',
        uk: 'Мені нічого не потрібно',
        es: 'No necesito nada.',
        'pt-BR': 'Não preciso de nada.',
        vi: 'Tôi không cần gì cả.',
        id: 'Saya tidak membutuhkan apa pun.',
        tr: 'Hiçbir şeye ihtiyacım yok.',
        pl: 'Nic mi nie potrzeba.',
        trRU: 'Мне ничего не нужно',
        trUK: 'Мені нічого не потрібно',
        trES: 'No necesito nada.',
        noteRU: 'Если уже есть do not, после него идет anything.',
        noteUK: 'Якщо вже є do not, після нього йде anything.',
        noteES: 'If there is already do not, use anything after it.',
        notePtBr: 'Se já existe do not, use anything depois dele.',
        noteVi: 'Nếu đã có do not, dùng anything sau nó.',
        noteId: 'Jika sudah ada do not, gunakan anything setelahnya.',
        noteTr: 'Do not varsa sonrasında anything kullan.',
        notePl: 'Jeśli jest już do not, użyj po nim anything.',
      },
      {
        labelRU: 'question',
        labelUK: 'question',
        labelES: 'question',
        labelPtBr: 'pergunta',
        labelVi: 'câu hỏi',
        labelId: 'pertanyaan',
        labelTr: 'soru',
        labelPl: 'pytanie',
        en: [{ text: 'Did', tone: 'warning' }, { text: ' anyone see my bag?', tone: 'accent' }],
        ru: 'Кто-нибудь видел мою сумку?',
        uk: 'Хтось бачив мою сумку?',
        es: '¿Alguien vio mi bolsa?',
        'pt-BR': 'Alguém viu minha bolsa?',
        vi: 'Có ai thấy túi của tôi không?',
        id: 'Apakah ada yang melihat tas saya?',
        tr: 'Çantamı gören oldu mu?',
        pl: 'Czy ktoś widział moją torbę?',
        trRU: 'Кто-нибудь видел мою сумку?',
        trUK: 'Хтось бачив мою сумку?',
        trES: '¿Alguien vio mi bolsa?',
        noteRU: 'В вопросе после Did используется anyone.',
        noteUK: 'У питанні після Did використовується anyone.',
        noteES: 'In a question after Did, use anyone.',
        notePtBr: 'Em uma pergunta depois de Did, use anyone.',
        noteVi: 'Trong câu hỏi sau Did, dùng anyone.',
        noteId: 'Dalam pertanyaan setelah Did, gunakan anyone.',
        noteTr: 'Did sonrasındaki soruda anyone kullan.',
        notePl: 'W pytaniu po Did użyj anyone.',
      },
    ],
    developerNotes: {
      screenGoal: 'Финальный экран готовит к дистракторам nobody + did not и not + nothing.',
      visualPriority: ['nobody/no one/nothing выделять warning.', 'anything после do not/does not выделять accent.', 'ошибки двойного отрицания выделять danger.', 'алгоритм 1-2-3 должен быть виден перед практикой.'],
      highlightRules: ['negative no-word = warning.', 'any-word after not/question = accent.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять nowhere / anywhere.', 'Не добавлять neither / none.', 'Не добавлять сложную теорию double negatives beyond this lesson.', 'Не использовать фразы вне урока 21.'],
      layoutRules: ['Экран финальный и практический.', 'Если не помещается, оставить Nobody helped, He does not want anything, Did anyone see и две ошибки.'],
    },
  },
];
