import type { LessonIntroScreen } from './lesson_data_types';

export const LESSON_21_INTRO_EXTRA: LessonIntroScreen[] = [
  {
    lessonId: 21,
    screenId: 'lesson_21_intro_1_people_words',
    order: 1,
    kind: 'concept',
    titleRU: 'Кто-то, никто, все',
    titleUK: 'Хтось, ніхто, всі',
    titleES: 'Someone, nobody, everyone',
    subtitleRU: 'В этом уроке ты говоришь о людях, когда имя не важно или неизвестно.',
    subtitleUK: 'У цьому уроці ти говориш про людей, коли ім\'я не важливе або невідоме.',
    subtitleES: 'In this lesson, you talk about people when the name is not important or unknown.',
    textRU: 'Слова с -one и -body говорят о людях: кто-то, никто, все.',
    textUK: 'Слова з -one і -body говорять про людей: хтось, ніхто, всі.',
    textES: 'Words with -one and -body talk about people: someone, nobody, everyone.',
    linesRU: [
      { type: 'text', parts: [{ text: 'Если речь о человеке, но ты не называешь имя, английский использует готовые слова:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = кто-то', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = никто', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = все', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Somebody', tone: 'accent' }, { text: ' knocked on the door' }] },
      { type: 'correct', parts: [{ text: 'No one', tone: 'warning' }, { text: ' knows it' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
      { type: 'correct', parts: [{ text: 'Everyone', tone: 'accent' }, { text: ' is ready' }] },
      { type: 'correct', parts: [{ text: 'Everybody', tone: 'accent' }, { text: ' understands me' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главная идея: ', tone: 'strong' }, { text: 'no one / nobody уже несут отрицание, отдельное not не нужно.' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'No one does not know it', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'No one', tone: 'warning' }, { text: ' knows it' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'Якщо йдеться про людину, але ти не називаєш ім\'я, англійська використовує готові слова:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = хтось', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = ніхто', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = всі', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
      { type: 'correct', parts: [{ text: 'Everyone', tone: 'accent' }, { text: ' is ready' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'Use these words when the person is unknown or not named:' }] },
      { type: 'formula', parts: [{ text: 'someone / somebody', tone: 'accent' }, { text: ' = someone', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'no one / nobody', tone: 'warning' }, { text: ' = nobody', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everyone / everybody', tone: 'accent' }, { text: ' = everyone', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Someone', tone: 'accent' }, { text: ' called me' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' came yesterday' }] },
    ],
    examples: [
      {
        labelRU: 'кто-то',
        labelUK: 'хтось',
        labelES: 'someone',
        en: [{ text: 'Someone', tone: 'accent' }, { text: ' left a message' }],
        ru: 'Кто-то оставил сообщение',
        uk: 'Хтось залишив повідомлення',
        es: 'Alguien dejó un mensaje.',
        trRU: 'Кто-то оставил сообщение',
        trUK: 'Хтось залишив повідомлення',
        trES: 'Alguien dejó un mensaje.',
        noteRU: 'Someone говорит о человеке, имя не важно или неизвестно.',
        noteUK: 'Someone говорить про людину, ім\'я не важливе або невідоме.',
        noteES: 'Someone refers to a person whose name is not important or unknown.',
      },
      {
        labelRU: 'никто',
        labelUK: 'ніхто',
        labelES: 'nobody',
        en: [{ text: 'Nobody', tone: 'warning' }, { text: ' left a message' }],
        ru: 'Никто не оставил сообщение',
        uk: 'Ніхто не залишив повідомлення',
        es: 'Nadie dejó un mensaje.',
        trRU: 'Никто не оставил сообщение',
        trUK: 'Ніхто не залишив повідомлення',
        trES: 'Nadie dejó un mensaje.',
        noteRU: 'Nobody уже значит "никто", поэтому отдельное not не нужно.',
        noteUK: 'Nobody вже означає "ніхто", тому окреме not не потрібне.',
        noteES: 'Nobody already means "no person", so no extra not is needed.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран вводит слова для людей: someone/somebody, no one/nobody, everyone/everybody.',
      visualPriority: ['someone/somebody/everyone/everybody выделять accent.', 'no one/nobody выделять warning.', 'ошибку двойного отрицания выделять danger.'],
      highlightRules: ['positive/neutral indefinite person word = accent.', 'negative person word = warning.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять somewhere/nowhere.', 'Не добавлять every one как два слова.', 'Не использовать фразы вне урока 21.'],
      layoutRules: ['Один экран - только слова про людей.', 'Если экран узкий, оставить someone, nobody, everyone и ошибку No one does not.'],
    },
  },
  {
    lessonId: 21,
    screenId: 'lesson_21_intro_2_thing_words',
    order: 2,
    kind: 'formula',
    titleRU: 'Что-то, ничего, все',
    titleUK: 'Щось, нічого, все',
    titleES: 'Something, nothing, everything',
    subtitleRU: 'Слова с -thing говорят не о людях, а о вещах, событиях или идеях.',
    subtitleUK: 'Слова з -thing говорять не про людей, а про речі, події або ідеї.',
    subtitleES: 'Words with -thing talk about things, events, or ideas, not people.',
    textRU: 'Something/anything/nothing/everything отвечают на "что?", а не на "кто?".',
    textUK: 'Something/anything/nothing/everything відповідають на "що?", а не на "хто?".',
    textES: 'Something/anything/nothing/everything answer "what?", not "who?".',
    linesRU: [
      { type: 'formula', parts: [{ text: 'something', tone: 'accent' }, { text: ' = что-то', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'anything', tone: 'accent' }, { text: ' = что-нибудь / ничего в отрицании', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'nothing', tone: 'warning' }, { text: ' = ничего', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everything', tone: 'accent' }, { text: ' = все', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Everything', tone: 'accent' }, { text: ' is okay' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' is wrong' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' is wrong' }] },
      { type: 'correct', parts: [{ text: 'Everything', tone: 'accent' }, { text: ' is clear' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I found ' }, { text: 'something', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'I found ' }, { text: 'nothing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I do not need ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Nothing did not happen', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'something', tone: 'accent' }, { text: ' = щось', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'anything', tone: 'accent' }, { text: ' = щось / нічого в запереченні', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'nothing', tone: 'warning' }, { text: ' = нічого', tone: 'formula' }] },
      { type: 'formula', parts: [{ text: 'everything', tone: 'accent' }, { text: ' = все', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'something / anything / nothing / everything', tone: 'accent' }, { text: ' = thing words', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Something', tone: 'accent' }, { text: ' happened' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' happened' }] },
    ],
    examples: [
      {
        labelRU: 'something',
        labelUK: 'something',
        labelES: 'something',
        en: [{ text: 'I found ' }, { text: 'something', tone: 'accent' }],
        ru: 'Я что-то нашел',
        uk: 'Я щось знайшов',
        es: 'Encontré algo.',
        trRU: 'Я что-то нашел',
        trUK: 'Я щось знайшов',
        trES: 'Encontré algo.',
        noteRU: 'Something говорит о вещи или идее, а не о человеке.',
        noteUK: 'Something говорить про річ або ідею, не про людину.',
        noteES: 'Something refers to a thing or idea, not a person.',
      },
      {
        labelRU: 'anything',
        labelUK: 'anything',
        labelES: 'anything',
        en: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }],
        ru: 'Он ничего не хочет',
        uk: 'Він нічого не хоче',
        es: 'Él no quiere nada.',
        trRU: 'Он ничего не хочет',
        trUK: 'Він нічого не хоче',
        trES: 'Él no quiere nada.',
        noteRU: 'После does not используется anything, не nothing.',
        noteUK: 'Після does not використовується anything, не nothing.',
        noteES: 'After does not, use anything, not nothing.',
      },
      {
        labelRU: 'nothing',
        labelUK: 'nothing',
        labelES: 'nothing',
        en: [{ text: 'Nothing', tone: 'warning' }, { text: ' changed yesterday' }],
        ru: 'Ничего не изменилось вчера',
        uk: 'Нічого не змінилося вчора',
        es: 'Nada cambió ayer.',
        trRU: 'Ничего не изменилось вчера',
        trUK: 'Нічого не змінилося вчора',
        trES: 'Nada cambió ayer.',
        noteRU: 'Nothing уже отрицательное, поэтому did not не нужен.',
        noteUK: 'Nothing вже заперечне, тому did not не потрібен.',
        noteES: 'Nothing is already negative, so did not is not needed.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран объясняет words for things/events: something, anything, nothing, everything.',
      visualPriority: ['something/anything/everything выделять accent.', 'nothing выделять warning.', 'ошибку Nothing did not happen выделять danger.'],
      highlightRules: ['neutral/positive thing word = accent.', 'negative thing word = warning.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять somewhere/nowhere.', 'Не добавлять every thing как два слова.', 'Не использовать фразы вне урока 21.'],
      layoutRules: ['Один экран - только слова про вещи/события.', 'Если экран узкий, оставить something, anything, nothing, everything и 2 примера.'],
    },
  },
  {
    lessonId: 21,
    screenId: 'lesson_21_intro_3_questions_anyone_anything',
    order: 3,
    kind: 'formula',
    titleRU: 'Вопросы: anyone / anybody / anything',
    titleUK: 'Питання: anyone / anybody / anything',
    titleES: 'Questions: anyone / anybody / anything',
    subtitleRU: 'В вопросах "кто-нибудь / что-нибудь" часто становятся anyone / anybody / anything.',
    subtitleUK: 'У питаннях "хтось / щось" часто стають anyone / anybody / anything.',
    subtitleES: 'In questions, "someone / something" often becomes anyone / anybody / anything.',
    textRU: 'Вопросы этого урока часто используют any-слова.',
    textUK: 'Питання цього уроку часто використовують any-слова.',
    textES: 'Questions in this lesson often use any-words.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody', tone: 'accent' }, { text: ' + действие?', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anybody see him?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone find my keys?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anybody bring documents?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone see my bag?', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Did you + действие + ', tone: 'formula' }, { text: 'anything?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Is', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone', tone: 'accent' }, { text: ' + место?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'warning' }, { text: ' anyone here?', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Did anyone called you?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody', tone: 'accent' }, { text: ' + дія?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'warning' }, { text: ' anyone here?', tone: 'accent' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'Did', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'anyone / anybody / anything', tone: 'accent' }, { text: ' + action?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Did', tone: 'warning' }, { text: ' anyone call you?', tone: 'accent' }] },
    ],
    examples: [
      {
        labelRU: 'anyone',
        labelUK: 'anyone',
        labelES: 'anyone',
        en: [{ text: 'Did', tone: 'warning' }, { text: ' anyone find my keys?', tone: 'accent' }],
        ru: 'Кто-нибудь нашел мои ключи?',
        uk: 'Хтось знайшов мої ключі?',
        es: '¿Alguien encontró mis llaves?',
        trRU: 'Кто-нибудь нашел мои ключи?',
        trUK: 'Хтось знайшов мої ключі?',
        trES: '¿Alguien encontró mis llaves?',
        noteRU: 'После Did основной глагол find без прошлой формы found.',
        noteUK: 'Після Did головне дієслово find без минулої форми found.',
        noteES: 'After Did, use find, not found.',
      },
      {
        labelRU: 'anything',
        labelUK: 'anything',
        labelES: 'anything',
        en: [{ text: 'Did you hear ' }, { text: 'anything', tone: 'accent' }, { text: '?' }],
        ru: 'Ты что-нибудь слышал?',
        uk: 'Ти щось чув?',
        es: '¿Escuchaste algo?',
        trRU: 'Ты что-нибудь слышал?',
        trUK: 'Ти щось чув?',
        trES: '¿Escuchaste algo?',
        noteRU: 'Anything говорит о "что-нибудь" в вопросе.',
        noteUK: 'Anything говорить про "щось" у питанні.',
        noteES: 'Anything means "anything" in a question.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран отдельно закрепляет вопросы с anyone/anybody/anything.',
      visualPriority: ['Did / Is выделять warning.', 'anyone/anybody/anything выделять accent.', 'ошибку Did anyone called выделять danger.'],
      highlightRules: ['question helper = warning.', 'any-word = accent.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять why/where/how questions.', 'Не добавлять somewhere/anywhere.', 'Не добавлять any как quantifier.', 'Не использовать фразы вне урока 21.'],
      layoutRules: ['Один экран - только вопросы с any-словами.', 'Если экран узкий, оставить Did anyone call, Did you hear anything, Is anyone here.'],
    },
  },
  {
    lessonId: 21,
    screenId: 'lesson_21_intro_4_negatives_practice',
    order: 4,
    kind: 'practice',
    titleRU: 'Отрицание: nobody или not anything',
    titleUK: 'Заперечення: nobody або not anything',
    titleES: 'Negatives: nobody or not anything',
    subtitleRU: 'В английском нельзя бездумно складывать два отрицания. Выбирай один путь.',
    subtitleUK: 'В англійській не можна бездумно складати два заперечення. Обирай один шлях.',
    subtitleES: 'In English, do not stack two negatives blindly. Choose one path.',
    textRU: 'Есть два пути: nobody/nothing или do not/does not + anything.',
    textUK: 'Є два шляхи: nobody/nothing або do not/does not + anything.',
    textES: 'There are two paths: nobody/nothing or do not/does not + anything.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' уже дают отрицание', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'correct', parts: [{ text: 'No one', tone: 'warning' }, { text: ' needs help' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' changed yesterday' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' saw my bag' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' = тоже отрицательный смысл', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I do not need ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'She does not know ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Видишь nobody / nothing / no one? ', tone: 'muted' }, { text: 'Не добавляй еще одно not.', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '2. Видишь do not / does not? ', tone: 'muted' }, { text: 'После него чаще будет anything.', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. В вопросе после Did? ', tone: 'muted' }, { text: 'anyone / anybody / anything.', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Nobody did not help them', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Nobody', tone: 'warning' }, { text: ' helped them' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'He does not want nothing', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'tip', parts: [{ text: 'Главный навык урока: ', tone: 'strong' }, { text: 'понять, говоришь ты о человеке или вещи, и не смешивать no-слово с лишним not.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' уже дають заперечення', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'correct', parts: [{ text: 'Nothing', tone: 'warning' }, { text: ' changed yesterday' }] },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' = теж заперечний зміст', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I do not need ' }, { text: 'anything', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Nobody did not help them', tone: 'danger' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'nobody / no one / nothing', tone: 'warning' }, { text: ' already make the sentence negative', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Nobody', tone: 'warning' }, { text: ' took your phone' }] },
      { type: 'formula', parts: [{ text: 'do not / does not + anything', tone: 'accent' }, { text: ' also gives a negative meaning', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'He does not want ' }, { text: 'anything', tone: 'accent' }] },
    ],
    examples: [
      {
        labelRU: 'nobody',
        labelUK: 'nobody',
        labelES: 'nobody',
        en: [{ text: 'Nobody', tone: 'warning' }, { text: ' brought documents' }],
        ru: 'Никто не принес документы',
        uk: 'Ніхто не приніс документи',
        es: 'Nadie trajo documentos.',
        trRU: 'Никто не принес документы',
        trUK: 'Ніхто не приніс документи',
        trES: 'Nadie trajo documentos.',
        noteRU: 'Nobody уже отрицательное. Не нужно did not.',
        noteUK: 'Nobody вже заперечне. Не потрібно did not.',
        noteES: 'Nobody is already negative. Do not add did not.',
      },
      {
        labelRU: 'not anything',
        labelUK: 'not anything',
        labelES: 'not anything',
        en: [{ text: 'I do not need ' }, { text: 'anything', tone: 'accent' }],
        ru: 'Мне ничего не нужно',
        uk: 'Мені нічого не потрібно',
        es: 'No necesito nada.',
        trRU: 'Мне ничего не нужно',
        trUK: 'Мені нічого не потрібно',
        trES: 'No necesito nada.',
        noteRU: 'Если уже есть do not, после него идет anything.',
        noteUK: 'Якщо вже є do not, після нього йде anything.',
        noteES: 'If there is already do not, use anything after it.',
      },
      {
        labelRU: 'question',
        labelUK: 'question',
        labelES: 'question',
        en: [{ text: 'Did', tone: 'warning' }, { text: ' anyone see my bag?', tone: 'accent' }],
        ru: 'Кто-нибудь видел мою сумку?',
        uk: 'Хтось бачив мою сумку?',
        es: '¿Alguien vio mi bolsa?',
        trRU: 'Кто-нибудь видел мою сумку?',
        trUK: 'Хтось бачив мою сумку?',
        trES: '¿Alguien vio mi bolsa?',
        noteRU: 'В вопросе после Did используется anyone.',
        noteUK: 'У питанні після Did використовується anyone.',
        noteES: 'In a question after Did, use anyone.',
      },
    ],
    developerNotes: {
      screenGoal: 'Финальный экран готовит к дистракторам nobody + did not и not + nothing.',
      visualPriority: ['nobody/no one/nothing выделять warning.', 'anything после do not/does not выделять accent.', 'ошибки двойного отрицания выделять danger.', 'алгоритм 1-2-3 должен быть виден перед практикой.'],
      highlightRules: ['negative no-word = warning.', 'any-word after not/question = accent.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять nowhere / anywhere.', 'Не добавлять neither / none.', 'Не добавлять сложную теорию double negatives beyond this lesson.', 'Не использовать фразы вне урока 21.'],
      layoutRules: ['Экран финальный и практический.', 'Если не помещается, оставить Nobody helped, He does not want anything, Did anyone see и две ошибки.'],
    },
  },
];
