import type { LessonIntroScreen } from './lesson_data_types';

export const LESSON_10_INTRO_SCREENS: LessonIntroScreen[] = [
  {
    lessonId: 10,
    screenId: 'lesson_10_intro_1_modal_base',
    order: 1,
    kind: 'concept',
    titleRU: 'Слово перед действием',
    titleUK: 'Слово перед дією',
    titleES: 'A word before the action',
    subtitleRU: 'can, should и must ставятся перед действием и меняют его смысл.',
    subtitleUK: 'can, should і must стоять перед дією та змінюють її зміст.',
    subtitleES: 'can, should, and must come before the action and change its meaning.',
    textRU: 'Общая формула: кто + can / should / must + действие без to и без -s.',
    textUK: 'Загальна формула: хто + can / should / must + дія без to і без -s.',
    textES: 'Core formula: who + can / should / must + base action, with no to and no -s.',
    linesRU: [
      { type: 'text', parts: [{ text: 'В этом уроке перед действием появляется короткое слово:' }] },
      { type: 'formula', parts: [{ text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'can / should / must', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'действие', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'can', tone: 'accent' }, { text: ' help' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'should', tone: 'accent' }, { text: ' rest' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' go now' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'После can / should / must действие идёт без ' }, { text: 'to', tone: 'warning' }, { text: ' и без ' }, { text: '-s', tone: 'warning' }, { text: '.' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'I can helps', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'can', tone: 'accent' }, { text: ' help' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'I must to go now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' go now' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'У цьому уроці перед дією з\'являється коротке слово:' }] },
      { type: 'formula', parts: [{ text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'can / should / must', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'дія', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'can', tone: 'accent' }, { text: ' help' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'should', tone: 'accent' }, { text: ' rest' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' go now' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Після can / should / must дія йде без ' }, { text: 'to', tone: 'warning' }, { text: ' і без ' }, { text: '-s', tone: 'warning' }, { text: '.' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'I can helps', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'can', tone: 'accent' }, { text: ' help' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'I must to go now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' go now' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'In this lesson, a short word comes before the action:' }] },
      { type: 'formula', parts: [{ text: 'who', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'can / should / must', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'action', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'can', tone: 'accent' }, { text: ' help' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'should', tone: 'accent' }, { text: ' rest' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' go now' }] },
      { type: 'tip', parts: [{ text: 'After can / should / must, use the base verb: no ' }, { text: 'to', tone: 'warning' }, { text: ', no ' }, { text: '-s', tone: 'warning' }, { text: '.' }] },
    ],
    examples: [
      {
        labelRU: 'can',
        labelUK: 'can',
        labelES: 'can',
        en: [{ text: 'I ', tone: 'strong' }, { text: 'can', tone: 'accent' }, { text: ' help' }],
        ru: 'Я могу помочь',
        uk: 'Я можу допомогти',
        es: 'Puedo ayudar.',
        'pt-BR': 'Posso ajudar.',
        vi: 'Tôi có thể giúp.',
        id: 'Saya bisa membantu.',
        tr: 'Yardım edebilirim.',
        pl: 'Mogę pomóc.',
        trRU: 'Я могу помочь',
        trUK: 'Я можу допомогти',
        trES: 'Puedo ayudar.',
        noteRU: 'После can стоит help, не helps и не to help.',
        noteUK: 'Після can стоїть help, не helps і не to help.',
        noteES: 'After can, use help, not helps or to help.',
      },
      {
        labelRU: 'should',
        labelUK: 'should',
        labelES: 'should',
        en: [{ text: 'You ', tone: 'strong' }, { text: 'should', tone: 'accent' }, { text: ' rest' }],
        ru: 'Тебе стоит отдохнуть',
        uk: 'Тобі варто відпочити',
        es: 'Deberías descansar.',
        'pt-BR': 'Você deveria descansar.',
        vi: 'Bạn nên nghỉ ngơi.',
        id: 'Kamu sebaiknya istirahat.',
        tr: 'Dinlenmelisin.',
        pl: 'Powinieneś odpocząć.',
        trRU: 'Тебе стоит отдохнуть',
        trUK: 'Тобі варто відпочити',
        trES: 'Deberías descansar.',
        noteRU: 'После should действие тоже без to.',
        noteUK: 'Після should дія теж без to.',
        noteES: 'After should, the action also goes without to.',
      },
      {
        labelRU: 'must',
        labelUK: 'must',
        labelES: 'must',
        en: [{ text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' go now' }],
        ru: 'Я должен идти сейчас',
        uk: 'Я мушу йти зараз',
        es: 'Debo irme ahora.',
        'pt-BR': 'Preciso ir agora.',
        vi: 'Tôi phải đi ngay bây giờ.',
        id: 'Saya harus pergi sekarang.',
        tr: 'Şimdi gitmeliyim.',
        pl: 'Muszę teraz iść.',
        trRU: 'Я должен идти сейчас',
        trUK: 'Я мушу йти зараз',
        trES: 'Debo irme ahora.',
        noteRU: 'После must стоит go, не to go.',
        noteUK: 'Після must стоїть go, не to go.',
        noteES: 'After must, use go, not to go.',
      },
    ],
    developerNotes: {
      screenGoal:
        'Экран даёт общий механизм модалок урока: can/should/must + base verb. Главная защита от ошибок: не ставить to и не добавлять -s после модалки.',
      visualPriority: [
        'can / should / must выделять accent.',
        'to и -s в предупреждении выделять warning.',
        'Ошибки I can helps и I must to go now выделять danger.',
      ],
      highlightRules: [
        'modal = accent.',
        'subject = strong.',
        'wrong example = danger.',
        'forbidden to/-s = warning.',
      ],
      forbiddenContent: [
        'Не добавлять модалки вне урока 10.',
        'Не добавлять другие конструкции обязанности.',
        'Не добавлять посторонние have-конструкции.',
        'Не использовать фразы вне урока 10.',
      ],
      layoutRules: [
        'Один экран - только базовая формула.',
        'Не грузить экран смысловыми различиями. Они идут дальше.',
      ],
    },
  },
  {
    lessonId: 10,
    screenId: 'lesson_10_intro_2_can',
    order: 2,
    kind: 'formula',
    titleRU: 'CAN - могу',
    titleUK: 'CAN - можу',
    titleES: 'CAN - can',
    subtitleRU: 'can показывает возможность: могу сделать.',
    subtitleUK: 'can показує можливість: можу зробити.',
    subtitleES: 'can shows possibility: I can do it.',
    textRU: 'CAN одинаковый для I, you, he, she, we, they.',
    textUK: 'CAN однаковий для I, you, he, she, we, they.',
    textES: 'CAN stays the same with I, you, he, she, we, they.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'can', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'действие', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'can', tone: 'accent' }, { text: ' help' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Can', tone: 'accent' }, { text: ' + кто + действие?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can', tone: 'accent' }, { text: ' you help me?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'cannot', tone: 'warning' }, { text: ' = не могу / не может', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'cannot', tone: 'warning' }, { text: ' wait' }] },
      { type: 'tip', parts: [{ text: 'Главная проверка: ', tone: 'strong' }, { text: 'can не получает -s. Вопрос начинается с Can.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'can', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'дія', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'can', tone: 'accent' }, { text: ' help' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Can', tone: 'accent' }, { text: ' + хто + дія?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can', tone: 'accent' }, { text: ' you help me?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'cannot', tone: 'warning' }, { text: ' = не можу / не може', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'cannot', tone: 'warning' }, { text: ' wait' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'who', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'can', tone: 'accent' }, { text: ' + action', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'can', tone: 'accent' }, { text: ' help' }] },
      { type: 'formula', parts: [{ text: 'Can', tone: 'accent' }, { text: ' + who + action?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can', tone: 'accent' }, { text: ' you help me?' }] },
      { type: 'formula', parts: [{ text: 'cannot', tone: 'warning' }, { text: ' = cannot do it', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'cannot', tone: 'warning' }, { text: ' wait' }] },
    ],
    examples: [
      {
        labelRU: 'утверждение',
        labelUK: 'ствердження',
        labelES: 'positive',
        en: [{ text: 'I ', tone: 'strong' }, { text: 'can', tone: 'accent' }, { text: ' help' }],
        ru: 'Я могу помочь',
        uk: 'Я можу допомогти',
        es: 'Puedo ayudar.',
        'pt-BR': 'Posso ajudar.',
        vi: 'Tôi có thể giúp.',
        id: 'Saya bisa membantu.',
        tr: 'Yardım edebilirim.',
        pl: 'Mogę pomóc.',
        trRU: 'Я могу помочь',
        trUK: 'Я можу допомогти',
        trES: 'Puedo ayudar.',
        noteRU: 'Can ставится перед действием help.',
        noteUK: 'Can стоїть перед дією help.',
        noteES: 'Can comes before the action help.',
      },
      {
        labelRU: 'вопрос',
        labelUK: 'питання',
        labelES: 'question',
        en: [{ text: 'Can', tone: 'accent' }, { text: ' you help me?' }],
        ru: 'Ты можешь мне помочь?',
        uk: 'Ти можеш мені допомогти?',
        es: '¿Puedes ayudarme?',
        'pt-BR': 'Você pode me ajudar?',
        vi: 'Bạn có thể giúp tôi không?',
        id: 'Bisakah kamu membantu saya?',
        tr: 'Bana yardım edebilir misin?',
        pl: 'Czy możesz mi pomóc?',
        trRU: 'Ты можешь мне помочь?',
        trUK: 'Ти можеш мені допомогти?',
        trES: '¿Puedes ayudarme?',
        noteRU: 'В вопросе Can выходит в начало.',
        noteUK: 'У питанні Can виходить на початок.',
        noteES: 'In a question, Can moves to the front.',
      },
      {
        labelRU: 'отрицание',
        labelUK: 'заперечення',
        labelES: 'negative',
        en: [{ text: 'I ', tone: 'strong' }, { text: 'cannot', tone: 'warning' }, { text: ' wait' }],
        ru: 'Я не могу ждать',
        uk: 'Я не можу чекати',
        es: 'No puedo esperar.',
        'pt-BR': 'Não posso esperar.',
        vi: 'Tôi không thể chờ.',
        id: 'Saya tidak bisa menunggu.',
        tr: 'Bekleyemem.',
        pl: 'Nie mogę czekać.',
        trRU: 'Я не могу ждать',
        trUK: 'Я не можу чекати',
        trES: 'No puedo esperar.',
        noteRU: 'Cannot пишется одним словом.',
        noteUK: 'Cannot пишеться одним словом.',
        noteES: 'Cannot is written as one word.',
      },
    ],
    developerNotes: {
      screenGoal:
        'Экран отдельно объясняет can: утверждение, вопрос и cannot. Не смешивать с should/must.',
      visualPriority: [
        'can = accent.',
        'Can в вопросе = accent.',
        'cannot = warning.',
        'Подлежащее = strong.',
      ],
      highlightRules: [
        'can/Can = accent.',
        'cannot = warning.',
        'subject = strong.',
      ],
      forbiddenContent: [
        'Не добавлять другие модалки возможности.',
        'Не добавлять синонимичные конструкции возможности.',
        'Не расширять экран за пределы can / cannot.',
        'Не использовать фразы вне урока 10.',
      ],
      layoutRules: [
        'Один экран - только can/cannot.',
        'Использовать только реальные фразы урока: I can help, Can you help me?, I cannot wait.',
      ],
    },
  },
  {
    lessonId: 10,
    screenId: 'lesson_10_intro_3_should',
    order: 3,
    kind: 'formula',
    titleRU: 'SHOULD - стоит',
    titleUK: 'SHOULD - варто',
    titleES: 'SHOULD - advice',
    subtitleRU: 'should звучит как совет: "тебе стоит", "лучше так сделать".',
    subtitleUK: 'should звучить як порада: "тобі варто", "краще так зробити".',
    subtitleES: 'should sounds like advice: it is a good idea to do it.',
    textRU: 'SHOULD даёт совет, а should not значит "не стоит".',
    textUK: 'SHOULD дає пораду, а should not означає "не варто".',
    textES: 'SHOULD gives advice, and should not means advice against doing something.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'should', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'действие', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'should', tone: 'accent' }, { text: ' rest' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Should', tone: 'accent' }, { text: ' + кто + действие?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Should', tone: 'accent' }, { text: ' I call him?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'should not', tone: 'warning' }, { text: ' = не стоит', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'should not', tone: 'warning' }, { text: ' wait' }] },
      { type: 'tip', parts: [{ text: 'Главная идея: ', tone: 'strong' }, { text: 'should - это совет, а не жёсткий приказ.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'should', tone: 'accent' }, { text: ' + дія', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'should', tone: 'accent' }, { text: ' rest' }] },
      { type: 'formula', parts: [{ text: 'Should', tone: 'accent' }, { text: ' + хто + дія?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Should', tone: 'accent' }, { text: ' I call him?' }] },
      { type: 'formula', parts: [{ text: 'should not', tone: 'warning' }, { text: ' = не варто', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'should not', tone: 'warning' }, { text: ' wait' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'who + ', tone: 'formula' }, { text: 'should', tone: 'accent' }, { text: ' + action', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'should', tone: 'accent' }, { text: ' rest' }] },
      { type: 'formula', parts: [{ text: 'Should', tone: 'accent' }, { text: ' + who + action?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Should', tone: 'accent' }, { text: ' I call him?' }] },
      { type: 'formula', parts: [{ text: 'should not', tone: 'warning' }, { text: ' = should avoid doing it', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'should not', tone: 'warning' }, { text: ' wait' }] },
    ],
    examples: [
      {
        labelRU: 'совет',
        labelUK: 'порада',
        labelES: 'advice',
        en: [{ text: 'You ', tone: 'strong' }, { text: 'should', tone: 'accent' }, { text: ' rest' }],
        ru: 'Тебе стоит отдохнуть',
        uk: 'Тобі варто відпочити',
        es: 'Deberías descansar.',
        'pt-BR': 'Você deveria descansar.',
        vi: 'Bạn nên nghỉ ngơi.',
        id: 'Kamu sebaiknya istirahat.',
        tr: 'Dinlenmelisin.',
        pl: 'Powinieneś odpocząć.',
        trRU: 'Тебе стоит отдохнуть',
        trUK: 'Тобі варто відпочити',
        trES: 'Deberías descansar.',
        noteRU: 'Should звучит как совет.',
        noteUK: 'Should звучить як порада.',
        noteES: 'Should sounds like advice.',
      },
      {
        labelRU: 'вопрос',
        labelUK: 'питання',
        labelES: 'question',
        en: [{ text: 'Should', tone: 'accent' }, { text: ' I call him?' }],
        ru: 'Мне стоит ему позвонить?',
        uk: 'Мені варто йому подзвонити?',
        es: '¿Debería llamarlo?',
        'pt-BR': 'Eu deveria ligar para ele?',
        vi: 'Tôi có nên gọi cho anh ấy không?',
        id: 'Haruskah saya menelepon dia?',
        tr: 'Onu aramalı mıyım?',
        pl: 'Czy powinienem do niego zadzwonić?',
        trRU: 'Мне стоит ему позвонить?',
        trUK: 'Мені варто йому подзвонити?',
        trES: '¿Debería llamarlo?',
        noteRU: 'В вопросе Should выходит в начало.',
        noteUK: 'У питанні Should виходить на початок.',
        noteES: 'In a question, Should moves to the front.',
      },
      {
        labelRU: 'не стоит',
        labelUK: 'не варто',
        labelES: 'should not',
        en: [{ text: 'You ', tone: 'strong' }, { text: 'should not', tone: 'warning' }, { text: ' wait' }],
        ru: 'Тебе не стоит ждать',
        uk: 'Тобі не варто чекати',
        es: 'No deberías esperar.',
        'pt-BR': 'Você não deveria esperar.',
        vi: 'Bạn không nên chờ.',
        id: 'Kamu sebaiknya tidak menunggu.',
        tr: 'Beklememelisin.',
        pl: 'Nie powinieneś czekać.',
        trRU: 'Тебе не стоит ждать',
        trUK: 'Тобі не варто чекати',
        trES: 'No deberías esperar.',
        noteRU: 'Should not - мягкое "не стоит", не запрет.',
        noteUK: 'Should not - м\'яке "не варто", не заборона.',
        noteES: 'Should not is advice against doing something, not a strict ban.',
      },
    ],
    developerNotes: {
      screenGoal:
        'Экран отдельно объясняет should / should not: совет, вопрос, отрицательный совет. Не смешивать с must.',
      visualPriority: [
        'should / Should выделять accent.',
        'should not выделять warning.',
        'Подлежащее выделять strong.',
      ],
      highlightRules: [
        'should/Should = accent.',
        'should not = warning.',
        'subject = strong.',
      ],
      forbiddenContent: [
        'Не добавлять другие модалки совета.',
        'Не расширять экран за пределы should / should not.',
        'Не добавлять must как часть этого экрана.',
        'Не использовать фразы вне урока 10.',
      ],
      layoutRules: [
        'Один экран - только should.',
        'Использовать только реальные фразы урока: You should rest, Should I call him?, You should not wait.',
      ],
    },
  },
  {
    lessonId: 10,
    screenId: 'lesson_10_intro_4_must',
    order: 4,
    kind: 'formula',
    titleRU: 'MUST - должен / нельзя',
    titleUK: 'MUST - мушу / не можна',
    titleES: 'MUST - strong obligation',
    subtitleRU: 'must сильнее, чем should. А must not часто значит запрет.',
    subtitleUK: 'must сильніше, ніж should. А must not часто означає заборону.',
    subtitleES: 'must is stronger than should. must not often means prohibition.',
    textRU: 'MUST = обязан, MUST NOT = нельзя.',
    textUK: 'MUST = мушу, MUST NOT = не можна.',
    textES: 'MUST = strong obligation, MUST NOT = prohibition.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'must', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'действие', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' go now' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Must', tone: 'accent' }, { text: ' + кто + действие?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Must', tone: 'accent' }, { text: ' I sign it?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'must not', tone: 'warning' }, { text: ' = нельзя / запрещено', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'must not', tone: 'warning' }, { text: ' smoke here' }] },
      { type: 'tip', parts: [{ text: 'Главная разница: ', tone: 'strong' }, { text: 'should not = не стоит, must not = нельзя.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'must', tone: 'accent' }, { text: ' + дія', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' go now' }] },
      { type: 'formula', parts: [{ text: 'Must', tone: 'accent' }, { text: ' + хто + дія?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Must', tone: 'accent' }, { text: ' I sign it?' }] },
      { type: 'formula', parts: [{ text: 'must not', tone: 'warning' }, { text: ' = не можна / заборонено', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'must not', tone: 'warning' }, { text: ' smoke here' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'who + ', tone: 'formula' }, { text: 'must', tone: 'accent' }, { text: ' + action', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' go now' }] },
      { type: 'formula', parts: [{ text: 'Must', tone: 'accent' }, { text: ' + who + action?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Must', tone: 'accent' }, { text: ' I sign it?' }] },
      { type: 'formula', parts: [{ text: 'must not', tone: 'warning' }, { text: ' = prohibition', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'must not', tone: 'warning' }, { text: ' smoke here' }] },
    ],
    examples: [
      {
        labelRU: 'обязанность',
        labelUK: 'обов\'язок',
        labelES: 'obligation',
        en: [{ text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' go now' }],
        ru: 'Я должен идти сейчас',
        uk: 'Я мушу йти зараз',
        es: 'Debo irme ahora.',
        'pt-BR': 'Preciso ir agora.',
        vi: 'Tôi phải đi ngay bây giờ.',
        id: 'Saya harus pergi sekarang.',
        tr: 'Şimdi gitmeliyim.',
        pl: 'Muszę teraz iść.',
        trRU: 'Я должен идти сейчас',
        trUK: 'Я мушу йти зараз',
        trES: 'Debo irme ahora.',
        noteRU: 'Must звучит жёстче, чем should.',
        noteUK: 'Must звучить жорсткіше, ніж should.',
        noteES: 'Must sounds stronger than should.',
      },
      {
        labelRU: 'вопрос',
        labelUK: 'питання',
        labelES: 'question',
        en: [{ text: 'Must', tone: 'accent' }, { text: ' I sign it?' }],
        ru: 'Я должен это подписать?',
        uk: 'Я мушу це підписати?',
        es: '¿Debo firmarlo?',
        'pt-BR': 'Eu devo assinar isso?',
        vi: 'Tôi có phải ký nó không?',
        id: 'Haruskah saya menandatanganinya?',
        tr: 'İmzalamalı mıyım?',
        pl: 'Czy muszę to podpisać?',
        trRU: 'Я должен это подписать?',
        trUK: 'Я мушу це підписати?',
        trES: '¿Debo firmarlo?',
        noteRU: 'В вопросе Must выходит в начало.',
        noteUK: 'У питанні Must виходить на початок.',
        noteES: 'In a question, Must moves to the front.',
      },
      {
        labelRU: 'запрет',
        labelUK: 'заборона',
        labelES: 'prohibition',
        en: [{ text: 'You ', tone: 'strong' }, { text: 'must not', tone: 'warning' }, { text: ' smoke here' }],
        ru: 'Тебе нельзя здесь курить',
        uk: 'Тобі не можна тут курити',
        es: 'No debes fumar aquí.',
        'pt-BR': 'Você não deve fumar aqui.',
        vi: 'Bạn không được hút thuốc ở đây.',
        id: 'Kamu tidak boleh merokok di sini.',
        tr: 'Burada sigara içmemelisin.',
        pl: 'Nie wolno ci tu palić.',
        trRU: 'Тебе нельзя здесь курить',
        trUK: 'Тобі не можна тут курити',
        trES: 'No debes fumar aquí.',
        noteRU: 'Must not = запрет, не просто совет.',
        noteUK: 'Must not = заборона, не просто порада.',
        noteES: 'Must not means prohibition, not advice.',
      },
    ],
    developerNotes: {
      screenGoal:
        'Экран отдельно объясняет must/must not. Главная задача - отделить must not от should not.',
      visualPriority: [
        'must / Must выделять accent.',
        'must not выделять warning.',
        'Фразу should not = не стоит, must not = нельзя сделать takeaway.',
      ],
      highlightRules: [
        'must/Must = accent.',
        'must not = warning.',
        'subject = strong.',
      ],
      forbiddenContent: [
        'Не добавлять have to на этом экране.',
        'Не добавлять другие конструкции обязанности.',
        'Не добавлять модалки возможности.',
        'Не использовать фразы вне урока 10.',
      ],
      layoutRules: [
        'Один экран - только must.',
        'Использовать только реальные фразы урока: I must go now, Must I sign it?, You must not smoke here.',
      ],
    },
  },
  {
    lessonId: 10,
    screenId: 'lesson_10_intro_5_have_to_practice',
    order: 5,
    kind: 'practice',
    titleRU: 'HAVE TO - нужно / приходится',
    titleUK: 'HAVE TO - потрібно / доводиться',
    titleES: 'HAVE TO - have to',
    subtitleRU: 'have to не работает как can / should / must. Здесь to обязательно.',
    subtitleUK: 'have to не працює як can / should / must. Тут to обов\'язкове.',
    subtitleES: 'have to does not work like can / should / must. Here, to is required.',
    textRU: 'Have to строит вопросы и отрицания через do / does.',
    textUK: 'Have to будує питання й заперечення через do / does.',
    textES: 'Have to uses do / does in questions and negatives.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'have to', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'действие', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' work today' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Do / Does', tone: 'warning' }, { text: ' + кто + ', tone: 'formula' }, { text: 'have to', tone: 'accent' }, { text: ' + действие?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Do', tone: 'warning' }, { text: ' you ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' go now?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'кто + do not / does not + ', tone: 'formula' }, { text: 'have to', tone: 'accent' }, { text: ' + действие', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' ' }, { text: 'have to', tone: 'accent' }, { text: ' wait' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'I must to work today', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Если must: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'must', tone: 'accent' }, { text: ' work today' }] },
      { type: 'correct', parts: [{ text: 'Если have to: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' work today' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Does she has to wait?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Does', tone: 'warning' }, { text: ' she ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' wait?' }] },
      { type: 'tip', parts: [{ text: 'Главная проверка: ', tone: 'strong' }, { text: 'после does / does not всегда have to, не has to.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'хто + ', tone: 'formula' }, { text: 'have to', tone: 'accent' }, { text: ' + дія', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' work today' }] },
      { type: 'formula', parts: [{ text: 'Do / Does', tone: 'warning' }, { text: ' + хто + ', tone: 'formula' }, { text: 'have to', tone: 'accent' }, { text: ' + дія?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Do', tone: 'warning' }, { text: ' you ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' go now?' }] },
      { type: 'formula', parts: [{ text: 'хто + do not / does not + ', tone: 'formula' }, { text: 'have to', tone: 'accent' }, { text: ' + дія', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' ' }, { text: 'have to', tone: 'accent' }, { text: ' wait' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Does she has to wait?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Does', tone: 'warning' }, { text: ' she ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' wait?' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'who + ', tone: 'formula' }, { text: 'have to', tone: 'accent' }, { text: ' + action', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' work today' }] },
      { type: 'formula', parts: [{ text: 'Do / Does', tone: 'warning' }, { text: ' + who + ', tone: 'formula' }, { text: 'have to', tone: 'accent' }, { text: ' + action?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Do', tone: 'warning' }, { text: ' you ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' go now?' }] },
      { type: 'correct', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' ' }, { text: 'have to', tone: 'accent' }, { text: ' wait' }] },
    ],
    examples: [
      {
        labelRU: 'обязанность',
        labelUK: 'обов\'язок',
        labelES: 'obligation',
        en: [{ text: 'I ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' work today' }],
        ru: 'Мне нужно работать сегодня',
        uk: 'Мені потрібно працювати сьогодні',
        es: 'Tengo que trabajar hoy.',
        'pt-BR': 'Tenho que trabalhar hoje.',
        vi: 'Hôm nay tôi phải làm việc.',
        id: 'Saya harus bekerja hari ini.',
        tr: 'Bugün çalışmak zorundayım.',
        pl: 'Muszę dziś pracować.',
        trRU: 'Мне нужно работать сегодня',
        trUK: 'Мені потрібно працювати сьогодні',
        trES: 'Tengo que trabajar hoy.',
        noteRU: 'В have to слово to обязательно.',
        noteUK: 'У have to слово to обов\'язкове.',
        noteES: 'In have to, the word to is required.',
      },
      {
        labelRU: 'вопрос',
        labelUK: 'питання',
        labelES: 'question',
        en: [{ text: 'Do', tone: 'warning' }, { text: ' you ', tone: 'strong' }, { text: 'have to', tone: 'accent' }, { text: ' go now?' }],
        ru: 'Тебе нужно идти сейчас?',
        uk: 'Тобі потрібно іти зараз?',
        es: '¿Tienes que irte ahora?',
        'pt-BR': 'Você tem que ir agora?',
        vi: 'Bạn có phải đi ngay bây giờ không?',
        id: 'Apakah kamu harus pergi sekarang?',
        tr: 'Şimdi gitmek zorunda mısın?',
        pl: 'Czy musisz teraz iść?',
        trRU: 'Тебе нужно идти сейчас?',
        trUK: 'Тобі потрібно іти зараз?',
        trES: '¿Tienes que irte ahora?',
        noteRU: 'В вопросе нужен Do, потому что have to ведёт себя как обычный глагол have.',
        noteUK: 'У питанні потрібен Do, бо have to поводиться як звичайне дієслово have.',
        noteES: 'In questions, use Do because have to behaves like the verb have.',
      },
      {
        labelRU: 'не нужно',
        labelUK: 'не потрібно',
        labelES: 'not necessary',
        en: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' ' }, { text: 'have to', tone: 'accent' }, { text: ' wait' }],
        ru: 'Ей не нужно ждать',
        uk: 'Їй не потрібно чекати',
        es: 'Ella no tiene que esperar.',
        'pt-BR': 'Ela não precisa esperar.',
        vi: 'Cô ấy không cần chờ.',
        id: 'Dia tidak perlu menunggu.',
        tr: 'Beklemek zorunda değil.',
        pl: 'Ona nie musi czekać.',
        trRU: 'Ей не нужно ждать',
        trUK: 'Їй не потрібно чекати',
        trES: 'Ella no tiene que esperar.',
        noteRU: 'Does not have to = не нужно. Это не запрет.',
        noteUK: 'Does not have to = не потрібно. Це не заборона.',
        noteES: 'Does not have to = not necessary. It is not a prohibition.',
      },
    ],
    developerNotes: {
      screenGoal:
        'Финальный экран отдельно объясняет have to, потому что оно не ведёт себя как can/should/must. Здесь to обязательно, а вопросы/отрицания строятся через do/does.',
      visualPriority: [
        'have to выделять accent.',
        'do/does/do not/does not выделять warning.',
        'Ошибку Does she has to wait выделять danger.',
        'Разницу must work vs have to work показать явно.',
      ],
      highlightRules: [
        'have to = accent.',
        'do/does helpers = warning.',
        'subject = strong.',
        'wrong examples = danger.',
      ],
      forbiddenContent: [
        'Не добавлять другие конструкции обязанности.',
        'Не добавлять has to как отдельную утверждательную форму, потому что в уроке нет he/she has to утверждений.',
        'Не добавлять don\'t/doesn\'t сокращения.',
        'Не использовать фразы вне урока 10.',
      ],
      layoutRules: [
        'Экран финальный и практический.',
        'Если не помещается, оставить: I have to work today, Do you have to go now?, She does not have to wait, Does she has to wait? ошибка.',
      ],
    },
  },
];
