import type { LessonIntroScreen } from './lesson_data_types';

export const LESSON_4_INTRO_SCREENS: LessonIntroScreen[] = [
  {
    lessonId: 4,
    screenId: 'lesson_4_intro_1_concept',
    order: 1,
    kind: 'concept',
    titleRU: 'Как отрицать действие',
    titleUK: 'Як заперечувати дію',
    titleES: 'How to make an action negative',
    titlePtBr: 'Como negar uma ação',
    titleVi: 'Cách phủ định một hành động',
    titleId: 'Cara membuat tindakan menjadi negatif',
    titleTr: 'Bir eylem nasıl olumsuz yapılır',
    titlePl: 'Jak zaprzeczyć czynności',
    subtitleRU: 'Если человек что-то не делает, в английском нужен do not или does not.',
    subtitleUK: 'Якщо людина чогось не робить, в англійській потрібні do not або does not.',
    subtitleES: 'If someone does not do an action, English uses do not or does not.',
    subtitlePtBr: 'Se alguém não faz uma ação, o inglês usa do not ou does not.',
    subtitleVi: 'Nếu ai đó không làm một hành động, tiếng Anh dùng do not hoặc does not.',
    subtitleId: 'Jika seseorang tidak melakukan tindakan, bahasa Inggris memakai do not atau does not.',
    subtitleTr: 'Bir kişi bir eylemi yapmıyorsa İngilizcede do not ya da does not gerekir.',
    subtitlePl: 'Jeśli ktoś czegoś nie robi, angielski używa do not albo does not.',
    textRU: 'Отрицание действия строится через do not или does not: I do not drink milk. You do not listen. It does not work.',
    textUK: 'Заперечення дії будується через do not або does not: I do not drink milk. You do not listen. It does not work.',
    textES: 'Negative action sentences use do not or does not: I do not drink milk. You do not listen. It does not work.',
    textPtBr: 'Frases negativas de ação usam do not ou does not: I do not drink milk. You do not listen. It does not work.',
    textVi: 'Câu phủ định hành động dùng do not hoặc does not: I do not drink milk. You do not listen. It does not work.',
    textId: 'Kalimat tindakan negatif memakai do not atau does not: I do not drink milk. You do not listen. It does not work.',
    textTr: 'Olumsuz eylem cümleleri do not ya da does not kullanır: I do not drink milk. You do not listen. It does not work.',
    textPl: 'Przeczące zdania z czynnością używają do not albo does not: I do not drink milk. You do not listen. It does not work.',
    linesRU: [
      { type: 'text', parts: [{ text: 'В уроке 3 ты собирал обычные действия:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Теперь смысл меняется: ' }, { text: 'не пью, не слушаешь, не курит, не работает.', tone: 'strong' }] },
      { type: 'formula', parts: [{ text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'действие', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главное: ', tone: 'strong' }, { text: 'not не ставится одиноко перед действием. Ему нужен помощник do или does.', tone: 'warning' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'В уроці 3 ти складав звичайні дії:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Тепер зміст змінюється: ' }, { text: 'не п\'ю, не слухаєш, не курить, не працює.', tone: 'strong' }] },
      { type: 'formula', parts: [{ text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'дія', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Головне: ', tone: 'strong' }, { text: 'not не стоїть сам перед дією. Йому потрібен помічник do або does.', tone: 'warning' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'In lesson 3, you built normal actions:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'who', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'action', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Main idea: ', tone: 'strong' }, { text: 'not needs do or does before an action verb.', tone: 'warning' }] },
    ],
    linesPtBr: [
      { type: 'text', parts: [{ text: 'Na lição 3, você montou ações normais:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Agora o sentido muda: ' }, { text: 'não bebo, não escuta, não fuma, não funciona.', tone: 'strong' }] },
      { type: 'formula', parts: [{ text: 'quem', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'ação', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Ideia principal: ', tone: 'strong' }, { text: 'not não fica sozinho antes da ação. Ele precisa do auxiliar do ou does.', tone: 'warning' }] },
    ],
    linesVi: [
      { type: 'text', parts: [{ text: 'Ở bài 3, bạn đã ghép các hành động bình thường:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Bây giờ nghĩa thay đổi: ' }, { text: 'không uống, không nghe, không hút thuốc, không hoạt động.', tone: 'strong' }] },
      { type: 'formula', parts: [{ text: 'ai', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'hành động', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Ý chính: ', tone: 'strong' }, { text: 'not không đứng một mình trước hành động. Nó cần trợ động từ do hoặc does.', tone: 'warning' }] },
    ],
    linesId: [
      { type: 'text', parts: [{ text: 'Di pelajaran 3, kamu menyusun tindakan biasa:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Sekarang maknanya berubah: ' }, { text: 'tidak minum, tidak mendengarkan, tidak merokok, tidak berfungsi.', tone: 'strong' }] },
      { type: 'formula', parts: [{ text: 'siapa', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'tindakan', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Ide utama: ', tone: 'strong' }, { text: 'not tidak berdiri sendiri sebelum tindakan. Ia membutuhkan pembantu do atau does.', tone: 'warning' }] },
    ],
    linesTr: [
      { type: 'text', parts: [{ text: '3. derste normal eylemler kurdun:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Şimdi anlam değişiyor: ' }, { text: 'içmiyorum, dinlemiyorsun, sigara içmiyor, çalışmıyor.', tone: 'strong' }] },
      { type: 'formula', parts: [{ text: 'kim', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'eylem', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Ana fikir: ', tone: 'strong' }, { text: 'not eylemden önce tek başına durmaz. do ya da does yardımcısına ihtiyaç duyar.', tone: 'warning' }] },
    ],
    linesPl: [
      { type: 'text', parts: [{ text: 'W lekcji 3 budowałeś zwykłe czynności:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Teraz znaczenie się zmienia: ' }, { text: 'nie piję, nie słuchasz, nie pali, nie działa.', tone: 'strong' }] },
      { type: 'formula', parts: [{ text: 'kto', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'czynność', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Główna myśl: ', tone: 'strong' }, { text: 'not nie stoi samotnie przed czynnością. Potrzebuje pomocnika do albo does.', tone: 'warning' }] },
    ],
    examples: [
      { labelRU: 'я не', labelUK: 'я не', labelES: 'I do not', labelPtBr: 'I do not', labelVi: 'I do not', labelId: 'I do not', labelTr: 'I do not', labelPl: 'I do not', en: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }], ru: 'Я не пью молоко', uk: 'Я не п\'ю молоко', es: 'No bebo leche.', 'pt-BR': 'Eu não bebo leite.', vi: 'Tôi không uống sữa.', id: 'Saya tidak minum susu.', tr: 'Süt içmem.', pl: 'Nie piję mleka.', trRU: 'Я не пью молоко', trUK: 'Я не п\'ю молоко', trES: 'No bebo leche.', noteRU: 'После I используется do not.', noteUK: 'Після I використовується do not.', noteES: 'After I, use do not.', notePtBr: 'Depois de I, use do not.', noteVi: 'Sau I, dùng do not.', noteId: 'Setelah I, gunakan do not.', noteTr: 'I sonrasında do not kullan.', notePl: 'Po I użyj do not.' },
      { labelRU: 'ты не', labelUK: 'ти не', labelES: 'you do not', labelPtBr: 'you do not', labelVi: 'you do not', labelId: 'you do not', labelTr: 'you do not', labelPl: 'you do not', en: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }], ru: 'Ты не слушаешь', uk: 'Ти не слухаєш', es: 'No escuchas.', 'pt-BR': 'Você não escuta.', vi: 'Bạn không nghe.', id: 'Kamu tidak mendengarkan.', tr: 'Dinlemiyorsun.', pl: 'Nie słuchasz.', trRU: 'Ты не слушаешь', trUK: 'Ти не слухаєш', trES: 'No escuchas.', noteRU: 'После you тоже используется do not.', noteUK: 'Після you теж використовується do not.', noteES: 'After you, use do not too.', notePtBr: 'Depois de you, também use do not.', noteVi: 'Sau you, cũng dùng do not.', noteId: 'Setelah you, gunakan do not juga.', noteTr: 'You sonrasında da do not kullan.', notePl: 'Po you też użyj do not.' },
      { labelRU: 'это не', labelUK: 'це не', labelES: 'it does not', labelPtBr: 'it does not', labelVi: 'it does not', labelId: 'it does not', labelTr: 'it does not', labelPl: 'it does not', en: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }], ru: 'Это не работает', uk: 'Це не працює', es: 'No funciona.', 'pt-BR': 'Isso não funciona.', vi: 'Nó không hoạt động.', id: 'Itu tidak berfungsi.', tr: 'Bu çalışmıyor.', pl: 'To nie działa.', trRU: 'Это не работает', trUK: 'Це не працює', trES: 'No funciona.', noteRU: 'После it используется does not.', noteUK: 'Після it використовується does not.', noteES: 'After it, use does not.', notePtBr: 'Depois de it, use does not.', noteVi: 'Sau it, dùng does not.', noteId: 'Setelah it, gunakan does not.', noteTr: 'It sonrasında does not kullan.', notePl: 'Po it użyj does not.' },
    ],
    developerNotes: {
      screenGoal: 'Объяснить разницу между уроком 2 и уроком 4: с состояниями было am/is/are not, а с действиями нужен do not/does not.',
      visualPriority: ['do not / does not выделять warning.', 'Смысловой глагол drink/listen/work выделять accent только когда нужно показать действие.', 'not отдельно не подсвечивать сильнее, чем вся конструкция do not/does not.'],
      highlightRules: ['Подлежащее выделять strong.', 'do not / does not всегда подсвечивать warning.', 'Действие можно подсвечивать accent, если оно является центром примера.'],
      forbiddenContent: ['Не добавлять don\'t / doesn\'t.', 'Не добавлять вопросы do/does.', 'Не добавлять am/is/are not как правильный вариант для действия.', 'Не добавлять Present Continuous.', 'Не добавлять модальные глаголы.'],
      layoutRules: ['Сначала связать с уроком 3.', 'Потом показать новую отрицательную формулу.', 'Потом дать короткие примеры.', 'Не делать один длинный абзац.'],
    },
  },
  {
    lessonId: 4,
    screenId: 'lesson_4_intro_2_do_vs_does',
    order: 2,
    kind: 'formula',
    titleRU: 'Когда do not, а когда does not',
    titleUK: 'Коли do not, а коли does not',
    titleES: 'When to use do not or does not',
    titlePtBr: 'Quando usar do not ou does not',
    titleVi: 'Khi nào dùng do not hoặc does not',
    titleId: 'Kapan memakai do not atau does not',
    titleTr: 'Ne zaman do not, ne zaman does not',
    titlePl: 'Kiedy używać do not albo does not',
    subtitleRU: 'Выбор зависит от первого слова: кто делает действие.',
    subtitleUK: 'Вибір залежить від першого слова: хто робить дію.',
    subtitleES: 'The choice depends on the first word: who does the action.',
    subtitlePtBr: 'A escolha depende da primeira palavra: quem faz a ação.',
    subtitleVi: 'Lựa chọn phụ thuộc vào từ đầu tiên: ai làm hành động.',
    subtitleId: 'Pilihannya bergantung pada kata pertama: siapa yang melakukan tindakan.',
    subtitleTr: 'Seçim ilk kelimeye bağlıdır: eylemi kim yapıyor.',
    subtitlePl: 'Wybór zależy od pierwszego słowa: kto wykonuje czynność.',
    textRU: 'I / you / we / they используют do not. He / she / it используют does not. После does not глагол без -s: He does not smoke.',
    textUK: 'I / you / we / they використовують do not. He / she / it використовують does not. Після does not дієслово без -s: He does not smoke.',
    textES: 'I / you / we / they use do not. He / she / it use does not. After does not, the verb has no -s: He does not smoke.',
    textPtBr: 'I / you / we / they usam do not. He / she / it usam does not. Depois de does not, o verbo não leva -s: He does not smoke.',
    textVi: 'I / you / we / they dùng do not. He / she / it dùng does not. Sau does not, động từ không có -s: He does not smoke.',
    textId: 'I / you / we / they memakai do not. He / she / it memakai does not. Setelah does not, kata kerja tidak memakai -s: He does not smoke.',
    textTr: 'I / you / we / they do not kullanır. He / she / it does not kullanır. Does not sonrasında fiilde -s olmaz: He does not smoke.',
    textPl: 'I / you / we / they używają do not. He / she / it używają does not. Po does not czasownik nie ma -s: He does not smoke.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'обычный глагол', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'обычный глагол', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'После ' }, { text: 'does not', tone: 'warning' }, { text: ' глагол уже ' }, { text: 'без -s', tone: 'accent' }, { text: ': smoke, eat, work.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'звичайне дієслово', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'звичайне дієслово', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Після ' }, { text: 'does not', tone: 'warning' }, { text: ' дієслово вже ' }, { text: 'без -s', tone: 'accent' }, { text: ': smoke, eat, work.' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'base verb', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'base verb', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'After ' }, { text: 'does not', tone: 'warning' }, { text: ', the main verb has ' }, { text: 'no -s', tone: 'accent' }, { text: '.' }] },
    ],
    linesPtBr: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'verbo base', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'verbo base', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Depois de ' }, { text: 'does not', tone: 'warning' }, { text: ', o verbo já fica ' }, { text: 'sem -s', tone: 'accent' }, { text: ': smoke, eat, work.' }] },
    ],
    linesVi: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'động từ nguyên mẫu', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'động từ nguyên mẫu', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Sau ' }, { text: 'does not', tone: 'warning' }, { text: ', động từ chính ' }, { text: 'không có -s', tone: 'accent' }, { text: ': smoke, eat, work.' }] },
    ],
    linesId: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'kata kerja dasar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'kata kerja dasar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Setelah ' }, { text: 'does not', tone: 'warning' }, { text: ', kata kerja sudah ' }, { text: 'tanpa -s', tone: 'accent' }, { text: ': smoke, eat, work.' }] },
    ],
    linesTr: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'yalın fiil', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'yalın fiil', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Does not sonrasında fiil artık ' }, { text: '-s almaz', tone: 'accent' }, { text: ': smoke, eat, work.' }] },
    ],
    linesPl: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'forma podstawowa', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'forma podstawowa', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Po ' }, { text: 'does not', tone: 'warning' }, { text: ' czasownik jest już ' }, { text: 'bez -s', tone: 'accent' }, { text: ': smoke, eat, work.' }] },
    ],
    examples: [
      { labelRU: 'I / you / we / they', labelUK: 'I / you / we / they', labelES: 'I / you / we / they', labelPtBr: 'I / you / we / they', labelVi: 'I / you / we / they', labelId: 'I / you / we / they', labelTr: 'I / you / we / they', labelPl: 'I / you / we / they', en: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }], ru: 'Они здесь не живут', uk: 'Вони тут не живуть', es: 'No viven aquí.', 'pt-BR': 'Eles não moram aqui.', vi: 'Họ không sống ở đây.', id: 'Mereka tidak tinggal di sini.', tr: 'Onlar burada yaşamıyor.', pl: 'Oni tutaj nie mieszkają.', trRU: 'Они здесь не живут', trUK: 'Вони тут не живуть', trES: 'No viven aquí.', noteRU: 'They требует do not.', noteUK: 'They вимагає do not.', noteES: 'Use do not with they.', notePtBr: 'Use do not com they.', noteVi: 'Dùng do not với they.', noteId: 'Gunakan do not dengan they.', noteTr: 'They ile do not kullan.', notePl: 'Z they użyj do not.' },
      { labelRU: 'he', labelUK: 'he', labelES: 'he', labelPtBr: 'he', labelVi: 'he', labelId: 'he', labelTr: 'he', labelPl: 'he', en: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }], ru: 'Он не курит', uk: 'Він не курить', es: 'Él no fuma.', 'pt-BR': 'Ele não fuma.', vi: 'Anh ấy không hút thuốc.', id: 'Dia tidak merokok.', tr: 'O sigara içmiyor.', pl: 'On nie pali.', trRU: 'Он не курит', trUK: 'Він не курить', trES: 'Él no fuma.', noteRU: 'He требует does not, но глагол smoke остаётся обычным.', noteUK: 'He вимагає does not, але дієслово smoke залишається звичайним.', noteES: 'Use does not with he, but smoke stays in the base form.', notePtBr: 'Use does not com he, mas smoke fica na forma base.', noteVi: 'Dùng does not với he, nhưng smoke vẫn ở dạng nguyên mẫu.', noteId: 'Gunakan does not dengan he, tetapi smoke tetap bentuk dasar.', noteTr: 'He ile does not kullan, ama smoke yalın biçimde kalır.', notePl: 'Z he użyj does not, ale smoke zostaje w formie podstawowej.' },
      { labelRU: 'she', labelUK: 'she', labelES: 'she', labelPtBr: 'she', labelVi: 'she', labelId: 'she', labelTr: 'she', labelPl: 'she', en: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }], ru: 'Она не ест сахар', uk: 'Вона не їсть цукор', es: 'Ella no come azúcar.', 'pt-BR': 'Ela não come açúcar.', vi: 'Cô ấy không ăn đường.', id: 'Dia tidak makan gula.', tr: 'O şeker yemez.', pl: 'Ona nie je cukru.', trRU: 'Она не ест сахар', trUK: 'Вона не їсть цукор', trES: 'Ella no come azúcar.', noteRU: 'Не eats, потому что does уже забрал -s.', noteUK: 'Не eats, бо does вже забрав -s.', noteES: 'Not eats, because does already carries the -s.', notePtBr: 'Não eats, porque does já carrega o -s.', noteVi: 'Không dùng eats, vì does đã mang -s rồi.', noteId: 'Bukan eats, karena does sudah membawa -s.', noteTr: 'Eats değil, çünkü -s görevini does taşır.', notePl: 'Nie eats, bo does już niesie -s.' },
    ],
    developerNotes: {
      screenGoal: 'Научить выбирать do not или does not по подлежащему и убрать ошибку he does not smokes.',
      visualPriority: ['Две группы должны быть визуально разделены.', 'I/you/we/they + do not.', 'he/she/it + does not.', 'Фразу "после does not глагол без -s" выделить как главный takeaway.'],
      highlightRules: ['do not/does not = warning.', 'Подлежащее = strong.', 'Обычный глагол после отрицания = accent.'],
      forbiddenContent: ['Не добавлять does not smokes как правильный вариант.', 'Не добавлять сокращения.', 'Не добавлять вопросительный порядок.', 'Не добавлять he does not to smoke.'],
      layoutRules: ['Экран должен быть почти как мини-таблица из двух групп.', 'Не перегружать всеми местоимениями в одной длинной строке, если экран узкий.', 'Можно рендерить две карточки: do not group и does not group.'],
    },
  },
  {
    lessonId: 4,
    screenId: 'lesson_4_intro_3_practice',
    order: 3,
    kind: 'practice',
    titleRU: 'Как собирать отрицание',
    titleUK: 'Як складати заперечення',
    titleES: 'How to build a negative sentence',
    titlePtBr: 'Como montar uma frase negativa',
    titleVi: 'Cách ghép câu phủ định',
    titleId: 'Cara menyusun kalimat negatif',
    titleTr: 'Olumsuz cümle nasıl kurulur',
    titlePl: 'Jak zbudować zdanie przeczące',
    subtitleRU: 'Сначала кто. Потом do not или does not. Потом обычный глагол.',
    subtitleUK: 'Спочатку хто. Потім do not або does not. Потім звичайне дієслово.',
    subtitleES: 'First who. Then do not or does not. Then the base verb.',
    subtitlePtBr: 'Primeiro quem. Depois do not ou does not. Depois o verbo base.',
    subtitleVi: 'Trước tiên là ai. Sau đó do not hoặc does not. Rồi động từ nguyên mẫu.',
    subtitleId: 'Pertama siapa. Lalu do not atau does not. Lalu kata kerja dasar.',
    subtitleTr: 'Önce kim. Sonra do not ya da does not. Sonra yalın fiil.',
    subtitlePl: 'Najpierw kto. Potem do not albo does not. Potem forma podstawowa czasownika.',
    textRU: 'Собирай отрицание так: кто -> do not / does not -> обычный глагол. He does not smoke, не He does not smokes.',
    textUK: 'Складай заперечення так: хто -> do not / does not -> звичайне дієслово. He does not smoke, не He does not smokes.',
    textES: 'Build negatives like this: who -> do not / does not -> base verb. He does not smoke, not He does not smokes.',
    textPtBr: 'Monte negativas assim: quem -> do not / does not -> verbo base. He does not smoke, não He does not smokes.',
    textVi: 'Ghép câu phủ định như sau: ai -> do not / does not -> động từ nguyên mẫu. He does not smoke, không phải He does not smokes.',
    textId: 'Susun negatif seperti ini: siapa -> do not / does not -> kata kerja dasar. He does not smoke, bukan He does not smokes.',
    textTr: 'Olumsuz cümleyi şöyle kur: kim -> do not / does not -> yalın fiil. He does not smoke, He does not smokes değil.',
    textPl: 'Buduj przeczenia tak: kto -> do not / does not -> forma podstawowa. He does not smoke, nie He does not smokes.',
    linesRU: [
      { type: 'text', parts: [{ text: 'Когда видишь русское ' }, { text: '"не делает"', tone: 'warning' }, { text: ', не ставь not прямо перед глаголом.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Найди, кто делает действие: ', tone: 'muted' }, { text: 'he / she / it или I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Выбери помощник: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Поставь обычный глагол: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'She not eats sugar', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главный навык урока: ', tone: 'strong' }, { text: 'выбрать правильный помощник и не добавлять -s к глаголу после does not.' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'Коли бачиш українське ' }, { text: '"не робить"', tone: 'warning' }, { text: ', не став not прямо перед дієсловом.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Знайди, хто робить дію: ', tone: 'muted' }, { text: 'he / she / it або I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Обери помічник: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Постав звичайне дієслово: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'She not eats sugar', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Головна навичка уроку: ', tone: 'strong' }, { text: 'обрати правильний помічник і не додавати -s до дієслова після does not.' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'When the meaning is negative, do not put ' }, { text: 'not', tone: 'warning' }, { text: ' alone before the action.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Find who does the action: ', tone: 'muted' }, { text: 'he / she / it or I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Choose the helper: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Use the base verb: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Wrong: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correct: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Wrong: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correct: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
    ],
    linesPtBr: [
      { type: 'text', parts: [{ text: 'Quando o sentido for negativo, não coloque ' }, { text: 'not', tone: 'warning' }, { text: ' sozinho antes da ação.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Encontre quem faz a ação: ', tone: 'muted' }, { text: 'he / she / it ou I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Escolha o auxiliar: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Use o verbo base: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correto: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'She not eats sugar', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correto: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correto: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Habilidade principal da lição: ', tone: 'strong' }, { text: 'escolher o auxiliar correto e não adicionar -s ao verbo depois de does not.' }] },
    ],
    linesVi: [
      { type: 'text', parts: [{ text: 'Khi nghĩa là phủ định, đừng đặt ' }, { text: 'not', tone: 'warning' }, { text: ' một mình trước hành động.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Tìm ai làm hành động: ', tone: 'muted' }, { text: 'he / she / it hoặc I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Chọn trợ động từ: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Dùng động từ nguyên mẫu: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Không dùng: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Không dùng: ', tone: 'warning' }, { text: 'She not eats sugar', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Không dùng: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Kỹ năng chính của bài: ', tone: 'strong' }, { text: 'chọn đúng trợ động từ và không thêm -s vào động từ sau does not.' }] },
    ],
    linesId: [
      { type: 'text', parts: [{ text: 'Saat maknanya negatif, jangan letakkan ' }, { text: 'not', tone: 'warning' }, { text: ' sendirian sebelum tindakan.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Cari siapa yang melakukan tindakan: ', tone: 'muted' }, { text: 'he / she / it atau I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Pilih pembantu: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Gunakan kata kerja dasar: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Bukan: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Bukan: ', tone: 'warning' }, { text: 'She not eats sugar', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Bukan: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Keterampilan utama pelajaran: ', tone: 'strong' }, { text: 'pilih pembantu yang benar dan jangan menambahkan -s pada kata kerja setelah does not.' }] },
    ],
    linesTr: [
      { type: 'text', parts: [{ text: 'Anlam olumsuzsa ' }, { text: 'not', tone: 'warning' }, { text: ' kelimesini eylemden önce tek başına koyma.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Eylemi kimin yaptığını bul: ', tone: 'muted' }, { text: 'he / she / it ya da I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Yardımcıyı seç: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Yalın fiili koy: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'She not eats sugar', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Dersin ana becerisi: ', tone: 'strong' }, { text: 'doğru yardımcıyı seçmek ve does not sonrasında fiile -s eklememek.' }] },
    ],
    linesPl: [
      { type: 'text', parts: [{ text: 'Gdy znaczenie jest przeczące, nie stawiaj ' }, { text: 'not', tone: 'warning' }, { text: ' samotnie przed czynnością.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Znajdź, kto wykonuje czynność: ', tone: 'muted' }, { text: 'he / she / it albo I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Wybierz pomocnik: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Wstaw formę podstawową: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'She not eats sugar', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Główna umiejętność lekcji: ', tone: 'strong' }, { text: 'wybrać właściwy pomocnik i nie dodawać -s do czasownika po does not.' }] },
    ],
    examples: [
      { labelRU: 'шаги', labelUK: 'кроки', labelES: 'steps', labelPtBr: 'passos', labelVi: 'các bước', labelId: 'langkah', labelTr: 'adımlar', labelPl: 'kroki', en: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }], ru: 'Он не курит', uk: 'Він не курить', es: 'Él no fuma.', 'pt-BR': 'Ele não fuma.', vi: 'Anh ấy không hút thuốc.', id: 'Dia tidak merokok.', tr: 'O sigara içmiyor.', pl: 'On nie pali.', trRU: 'Он не курит', trUK: 'Він не курить', trES: 'Él no fuma.', noteRU: 'He -> does not -> smoke. Не smokes.', noteUK: 'He -> does not -> smoke. Не smokes.', noteES: 'He -> does not -> smoke. Not smokes.', notePtBr: 'He -> does not -> smoke. Não smokes.', noteVi: 'He -> does not -> smoke. Không dùng smokes.', noteId: 'He -> does not -> smoke. Bukan smokes.', noteTr: 'He -> does not -> smoke. Smokes değil.', notePl: 'He -> does not -> smoke. Nie smokes.' },
      { labelRU: 'они', labelUK: 'вони', labelES: 'they', labelPtBr: 'they', labelVi: 'they', labelId: 'they', labelTr: 'they', labelPl: 'they', en: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }], ru: 'Они здесь не живут', uk: 'Вони тут не живуть', es: 'No viven aquí.', 'pt-BR': 'Eles não moram aqui.', vi: 'Họ không sống ở đây.', id: 'Mereka tidak tinggal di sini.', tr: 'Onlar burada yaşamıyor.', pl: 'Oni tutaj nie mieszkają.', trRU: 'Они здесь не живут', trUK: 'Вони тут не живуть', trES: 'No viven aquí.', noteRU: 'They -> do not -> live here.', noteUK: 'They -> do not -> live here.', noteES: 'They -> do not -> live here.', notePtBr: 'They -> do not -> live here.', noteVi: 'They -> do not -> live here.', noteId: 'They -> do not -> live here.', noteTr: 'They -> do not -> live here.', notePl: 'They -> do not -> live here.' },
      { labelRU: 'она', labelUK: 'вона', labelES: 'she', labelPtBr: 'she', labelVi: 'she', labelId: 'she', labelTr: 'she', labelPl: 'she', en: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }], ru: 'Она не ест сахар', uk: 'Вона не їсть цукор', es: 'Ella no come azúcar.', 'pt-BR': 'Ela não come açúcar.', vi: 'Cô ấy không ăn đường.', id: 'Dia tidak makan gula.', tr: 'O şeker yemez.', pl: 'Ona nie je cukru.', trRU: 'Она не ест сахар', trUK: 'Вона не їсть цукор', trES: 'Ella no come azúcar.', noteRU: 'She -> does not -> eat sugar. Не eats.', noteUK: 'She -> does not -> eat sugar. Не eats.', noteES: 'She -> does not -> eat sugar. Not eats.', notePtBr: 'She -> does not -> eat sugar. Não eats.', noteVi: 'She -> does not -> eat sugar. Không dùng eats.', noteId: 'She -> does not -> eat sugar. Bukan eats.', noteTr: 'She -> does not -> eat sugar. Eats değil.', notePl: 'She -> does not -> eat sugar. Nie eats.' },
    ],
    developerNotes: {
      screenGoal: 'Подготовить к сборке предложений с дистракторами: do/does, base verb/verb+s, неправильное место not.',
      visualPriority: ['Шаги 1-2-3 сделать отдельными строками.', 'Wrong/correct пары показать компактными карточками.', 'Особенно выделить ошибку He does not smokes.'],
      highlightRules: ['wrong examples полностью danger.', 'correct examples: subject strong, helper warning, base verb accent.', 'В takeaway выделить does not и без -s.'],
      forbiddenContent: ['Не добавлять don\'t/doesn\'t.', 'Не добавлять вопросы.', 'Не добавлять модалки.', 'Не использовать фразы вне урока 4.'],
      layoutRules: ['Если экран перегружен, оставить 2 wrong/correct пары: He does not smokes и They does not live here.', 'Основной алгоритм должен быть виден без скролла.', 'Examples можно показывать ниже как дополнительные карточки.'],
    },
  },
];
