import type { IntroTextTone, LessonIntroScreen } from './lesson_data_types';

export const INTRO_TONE_STYLE_MAP: Record<IntroTextTone, {
  colorRole: string;
  fontWeight: 'regular' | 'medium' | 'semibold' | 'bold';
}> = {
  normal: { colorRole: 'textPrimary', fontWeight: 'regular' },
  muted: { colorRole: 'textSecondary', fontWeight: 'regular' },
  strong: { colorRole: 'textPrimary', fontWeight: 'bold' },
  accent: { colorRole: 'accent', fontWeight: 'bold' },
  success: { colorRole: 'success', fontWeight: 'bold' },
  danger: { colorRole: 'danger', fontWeight: 'bold' },
  warning: { colorRole: 'warning', fontWeight: 'semibold' },
  formula: { colorRole: 'formula', fontWeight: 'bold' },
  code: { colorRole: 'code', fontWeight: 'semibold' },
};

export const LESSON_1_INTRO_SCREENS: LessonIntroScreen[] = [
  {
    lessonId: 1,
    screenId: 'lesson_1_intro_1_concept',
    order: 1,
    kind: 'concept',
    titleRU: 'Почему нужен am / is / are',
    titleUK: 'Чому потрібні am / is / are',
    titleES: 'Por qué necesitas am / is / are',
    subtitleRU: 'В русском глагола часто не видно. В английском он обязателен.',
    subtitleUK: 'Українською дієслова часто не видно. В англійській воно обов\'язкове.',
    subtitleES: 'En ruso o ucraniano el verbo puede faltar. En inglés debe estar.',
    textRU: 'В русском фраза может быть без видимого глагола. В английском нужны am / is / are: I am here, He is busy, It is important.',
    textUK: 'Українською фраза може бути без видимого дієслова. В англійській потрібні am / is / are: I am here, He is busy, It is important.',
    textES: 'In English you need am / is / are: I am here, He is busy, It is important.',
    linesRU: [
      { type: 'text', parts: [{ text: 'В русском можно сказать: ' }, { text: '«Я здесь»', tone: 'strong' }, { text: ', ' }, { text: '«Он занят»', tone: 'strong' }, { text: ', ' }, { text: '«Это важно»', tone: 'strong' }, { text: '.' }] },
      { type: 'text', parts: [{ text: 'Мы не произносим глагол, но смысл всё равно понятен.', tone: 'muted' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'I here', tone: 'danger' }, { text: ' / ', tone: 'muted' }, { text: 'He busy', tone: 'danger' }, { text: ' / ', tone: 'muted' }, { text: 'It important', tone: 'danger' }] },
      { type: 'text', parts: [{ text: 'Так по-английски фраза сломана.', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ' }, { text: 'am', tone: 'accent' }, { text: ' here' }, { text: ' / ', tone: 'muted' }, { text: 'He ' }, { text: 'is', tone: 'accent' }, { text: ' busy' }, { text: ' / ', tone: 'muted' }, { text: 'It ' }, { text: 'is', tone: 'accent' }, { text: ' important' }] },
      { type: 'tip', parts: [{ text: 'am / is / are', tone: 'accent' }, { text: ' держат фразу вместе: кто где находится, кто в каком состоянии или каким является.' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'Українською можна сказати: ' }, { text: '«Я тут»', tone: 'strong' }, { text: ', ' }, { text: '«Він зайнятий»', tone: 'strong' }, { text: ', ' }, { text: '«Це важливо»', tone: 'strong' }, { text: '.' }] },
      { type: 'text', parts: [{ text: 'Ми не вимовляємо дієслово, але зміст зрозумілий.', tone: 'muted' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'I here', tone: 'danger' }, { text: ' / ', tone: 'muted' }, { text: 'He busy', tone: 'danger' }, { text: ' / ', tone: 'muted' }, { text: 'It important', tone: 'danger' }] },
      { type: 'text', parts: [{ text: 'Так англійською фраза зламана.', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ' }, { text: 'am', tone: 'accent' }, { text: ' here' }, { text: ' / ', tone: 'muted' }, { text: 'He ' }, { text: 'is', tone: 'accent' }, { text: ' busy' }, { text: ' / ', tone: 'muted' }, { text: 'It ' }, { text: 'is', tone: 'accent' }, { text: ' important' }] },
      { type: 'tip', parts: [{ text: 'am / is / are', tone: 'accent' }, { text: ' тримають фразу разом: хто де знаходиться, хто в якому стані або яким є.' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'En tu idioma puedes decir una frase sin verbo visible.' }] },
      { type: 'text', parts: [{ text: 'En inglés no funciona así.', tone: 'strong' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'I here', tone: 'danger' }, { text: ' / ', tone: 'muted' }, { text: 'He busy', tone: 'danger' }, { text: ' / ', tone: 'muted' }, { text: 'It important', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'I ' }, { text: 'am', tone: 'accent' }, { text: ' here' }, { text: ' / ', tone: 'muted' }, { text: 'He ' }, { text: 'is', tone: 'accent' }, { text: ' busy' }, { text: ' / ', tone: 'muted' }, { text: 'It ' }, { text: 'is', tone: 'accent' }, { text: ' important' }] },
      { type: 'tip', parts: [{ text: 'am / is / are', tone: 'accent' }, { text: ' connect the person with a place, state, or quality.' }] },
    ],
    developerNotes: {
      screenGoal: 'Объяснить главную проблему урока: в русском/украинском фраза может быть без видимого глагола, но в английском am/is/are обязателен.',
      visualPriority: ['Ошибки I here / He busy / It important красным.', 'Правильные варианты ниже.', 'am / is / are акцентным цветом.'],
      highlightRules: ['accent = основной цвет обучения', 'danger = красный', 'warning = предупреждение', 'muted = второстепенный текст'],
      forbiddenContent: ['Не добавлять at home.', 'Не добавлять профессии.', 'Не добавлять вопросы.', 'Не добавлять отрицания.', 'Не объяснять весь To Be глобально.'],
      layoutRules: ['Каждая line отдельным блоком.', 'После wrong и перед correct нужен отступ.'],
    },
  },
  {
    lessonId: 1,
    screenId: 'lesson_1_intro_2_formula',
    order: 2,
    kind: 'formula',
    titleRU: 'Формула урока',
    titleUK: 'Формула уроку',
    titleES: 'Lesson formula',
    subtitleRU: 'Сначала кто. Потом am / is / are. Потом описание.',
    subtitleUK: 'Спочатку хто. Потім am / is / are. Потім опис.',
    subtitleES: 'First who. Then am / is / are. Then description.',
    textRU: 'Кто? + am / is / are + описание. I am ready. She is calm. They are happy.',
    textUK: 'Хто? + am / is / are + опис. I am ready. She is calm. They are happy.',
    textES: 'Who? + am / is / are + description. I am ready. She is calm. They are happy.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'Кто?', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'описание', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'example', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ready' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' calm' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' happy' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'I', tone: 'strong' }, { text: ' всегда идёт с ' }, { text: 'am', tone: 'accent' }, { text: '.' }] },
      { type: 'tip', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' идут с ' }, { text: 'is', tone: 'accent' }, { text: '.' }] },
      { type: 'tip', parts: [{ text: 'you / we / they', tone: 'strong' }, { text: ' идут с ' }, { text: 'are', tone: 'accent' }, { text: '.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'Хто?', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'опис', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'example', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ready' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' calm' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' happy' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'I', tone: 'strong' }, { text: ' завжди йде з ' }, { text: 'am', tone: 'accent' }, { text: '.' }] },
      { type: 'tip', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' йдуть з ' }, { text: 'is', tone: 'accent' }, { text: '.' }] },
      { type: 'tip', parts: [{ text: 'you / we / they', tone: 'strong' }, { text: ' йдуть з ' }, { text: 'are', tone: 'accent' }, { text: '.' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'Who?', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'description', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'example', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ready' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' calm' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' happy' }] },
    ],
    examples: [
      { labelRU: 'один человек', labelUK: 'одна людина', labelES: 'one person', en: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' busy' }], ru: 'Он занят', uk: 'Він зайнятий', es: 'Él está ocupado.', trRU: 'Он занят', trUK: 'Він зайнятий', trES: 'Él está ocupado.' },
      { labelRU: 'несколько людей', labelUK: 'кілька людей', labelES: 'several people', en: [{ text: 'We ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' together' }], ru: 'Мы вместе', uk: 'Ми разом', es: 'Estamos juntos.', trRU: 'Мы вместе', trUK: 'Ми разом', trES: 'Estamos juntos.' },
      { labelRU: 'предмет или ситуация', labelUK: 'предмет або ситуація', labelES: 'thing or situation', en: [{ text: 'It ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' important' }], ru: 'Это важно', uk: 'Це важливо', es: 'Es importante.', trRU: 'Это важно', trUK: 'Це важливо', trES: 'Es importante.' },
    ],
    developerNotes: {
      screenGoal: 'Дать рабочую формулу для сборки фраз из кнопок.',
      visualPriority: ['Формулу показать отдельной крупной строкой.', 'am / is / are выделять одинаково.', 'I / he / she / it / you / we / they выделять как первую точку выбора.'],
      highlightRules: ['В примерах подсвечивать местоимение и форму To Be.', 'Описание ready / calm / happy не перегружать цветом.'],
      forbiddenContent: ['Не добавлять отрицания.', 'Не добавлять вопросы.', 'Не объяснять времена.', 'Не использовать примеры вне урока 1.'],
      layoutRules: ['Формула сверху.', 'Потом 3 коротких примера.', 'Потом правило выбора am/is/are.'],
    },
  },
  {
    lessonId: 1,
    screenId: 'lesson_1_intro_3_practice',
    order: 3,
    kind: 'practice',
    titleRU: 'Как собирать фразу в задании',
    titleUK: 'Як складати фразу в завданні',
    titleES: 'How to build the sentence',
    subtitleRU: 'Не переводи всё сразу. Собирай по шагам.',
    subtitleUK: 'Не перекладай усе одразу. Складай кроками.',
    subtitleES: 'Do not translate everything at once. Build step by step.',
    textRU: 'Собирай по шагам: найди кто, выбери am / is / are, добавь описание. She ready неверно, She is ready правильно.',
    textUK: 'Складай кроками: знайди хто, обери am / is / are, додай опис. She ready неправильно, She is ready правильно.',
    textES: 'Build step by step: find who, choose am / is / are, add the description. She ready is wrong; She is ready is correct.',
    linesRU: [
      { type: 'text', parts: [{ text: 'Допустим, в задании написано: ' }, { text: '«Она готова»', tone: 'strong' }, { text: '.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Найди, кто главный: ', tone: 'muted' }, { text: 'Она = She', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Выбери связку: ', tone: 'muted' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. Добавь описание: ', tone: 'muted' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'She ready', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главный навык урока: ', tone: 'strong' }, { text: 'увидеть "кто" и сразу выбрать ' }, { text: 'am / is / are', tone: 'accent' }, { text: '.' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'Припустимо, в завданні написано: ' }, { text: '«Вона готова»', tone: 'strong' }, { text: '.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Знайди, хто головний: ', tone: 'muted' }, { text: 'Вона = She', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Обери зв\'язку: ', tone: 'muted' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. Додай опис: ', tone: 'muted' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'She ready', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Головна навичка уроку: ', tone: 'strong' }, { text: 'побачити "хто" і одразу вибрати ' }, { text: 'am / is / are', tone: 'accent' }, { text: '.' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'Imagine the task says: ' }, { text: '"She is ready"', tone: 'strong' }, { text: '.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Find who: ', tone: 'muted' }, { text: 'She', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Choose the link: ', tone: 'muted' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. Add the description: ', tone: 'muted' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Wrong: ', tone: 'warning' }, { text: 'She ready', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correct: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ready' }] },
    ],
    examples: [
      { labelRU: 'если "я"', labelUK: 'якщо "я"', labelES: 'if "I"', en: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' outside' }], ru: 'Я снаружи', uk: 'Я зовні', es: 'Estoy afuera.', trRU: 'Я снаружи', trUK: 'Я зовні', trES: 'Estoy afuera.', noteRU: 'I всегда требует am.', noteUK: 'I завжди вимагає am.', noteES: 'Use am with I.' },
      { labelRU: 'если "они"', labelUK: 'якщо "вони"', labelES: 'if "they"', en: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' tired' }], ru: 'Они устали', uk: 'Вони втомлені', es: 'Están cansados.', trRU: 'Они устали', trUK: 'Вони втомлені', trES: 'Están cansados.', noteRU: 'They всегда требует are.', noteUK: 'They завжди вимагає are.', noteES: 'Use are with they.' },
      { labelRU: 'если "это"', labelUK: 'якщо "це"', labelES: 'if "it"', en: [{ text: 'It ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' empty' }], ru: 'Это пусто', uk: 'Це порожнє', es: 'Está vacío.', trRU: 'Это пусто', trUK: 'Це порожнє', trES: 'Está vacío.', noteRU: 'It всегда требует is.', noteUK: 'It завжди вимагає is.', noteES: 'Use is with it.' },
    ],
    developerNotes: {
      screenGoal: 'Подготовить пользователя к механике: подсказка + английские слова-кнопки + дистракторы.',
      visualPriority: ['Шаги 1-2-3 отдельными строками.', 'Wrong красным.', 'Correct сразу под ним.', 'am / is / are тем же цветом.'],
      highlightRules: ['В шаге 1 выделять She.', 'В шаге 2 выделять is.', 'В шаге 3 показывать финальную фразу.'],
      forbiddenContent: ['Не объяснять интерфейс кнопки ½.', 'Не повторять длинно как работает приложение.', 'Не добавлять новые конструкции.', 'Не превращать экран в справку по грамматике.'],
      layoutRules: ['Экран самый практический.', 'Короткие строки и шаги вместо длинного абзаца.'],
    },
  },
];
