import type { LessonIntroScreen } from './lesson_data_types';

export const LESSON_17_INTRO_EXTRA: LessonIntroScreen[] = [
  {
    lessonId: 17,
    screenId: 'lesson_17_intro_1_present_continuous_core',
    order: 1,
    kind: 'concept',
    titleRU: 'Действие прямо сейчас',
    titleUK: 'Дія прямо зараз',
    titleES: 'Action happening now',
    titlePtBr: 'Ação acontecendo agora',
    titleVi: 'Hành động đang diễn ra',
    titleId: 'Aksi yang sedang terjadi',
    titleTr: 'Şu anda olan eylem',
    titlePl: 'Czynność dzieje się teraz',
    subtitleRU: 'Present Continuous показывает действие, которое происходит сейчас или в текущий момент.',
    subtitleUK: 'Present Continuous показує дію, яка відбувається зараз або в поточний момент.',
    subtitleES: 'Present Continuous shows an action happening now or around the current moment.',
    subtitlePtBr: 'O Present Continuous mostra uma ação que acontece agora ou neste momento.',
    subtitleVi: 'Present Continuous diễn tả hành động đang xảy ra bây giờ hoặc quanh thời điểm hiện tại.',
    subtitleId: 'Present Continuous menunjukkan aksi yang terjadi sekarang atau di sekitar saat ini.',
    subtitleTr: 'Present Continuous şu anda veya bu anın çevresinde olan bir eylemi gösterir.',
    subtitlePl: 'Present Continuous pokazuje czynność, która dzieje się teraz albo w obecnym momencie.',
    textRU: 'Для действия сейчас нужны две части: am/is/are и V-ing.',
    textUK: 'Для дії зараз потрібні дві частини: am/is/are і V-ing.',
    textES: 'For an action happening now, you need two parts: am/is/are and V-ing.',
    textPtBr: 'Para uma ação acontecendo agora, você precisa de duas partes: am/is/are e V-ing.',
    textVi: 'Với hành động đang diễn ra, bạn cần hai phần: am/is/are và V-ing.',
    textId: 'Untuk aksi yang sedang terjadi, kamu perlu dua bagian: am/is/are dan V-ing.',
    textTr: 'Şu anda olan bir eylem için iki parça gerekir: am/is/are ve V-ing.',
    textPl: 'Do czynności dziejącej się teraz potrzebujesz dwóch części: am/is/are i V-ing.',
    linesRU: [
      { type: 'text', parts: [{ text: 'Если человек делает что-то ' }, { text: 'прямо сейчас', tone: 'strong' }, { text: ', английский использует связку:' }] },
      { type: 'formula', parts: [{ text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'глагол + -ing', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' reading now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главная проверка: ', tone: 'strong' }, { text: 'нужны обе части: am / is / are и -ing. Одной части недостаточно.' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'I working now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'He is cook dinner', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'Якщо людина робить щось ' }, { text: 'прямо зараз', tone: 'strong' }, { text: ', англійська використовує зв\'язку:' }] },
      { type: 'formula', parts: [{ text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'дієслово + -ing', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' reading now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'Головна перевірка: ', tone: 'strong' }, { text: 'потрібні обидві частини: am / is / are і -ing.' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'If someone is doing something now, English uses:' }] },
      { type: 'formula', parts: [{ text: 'who', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'verb + -ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' watching TV', tone: 'warning' }] },
    ],
    linesPtBr: [
      { type: 'text', parts: [{ text: 'Se alguém faz algo ' }, { text: 'agora mesmo', tone: 'strong' }, { text: ', o inglês usa:' }] },
      { type: 'formula', parts: [{ text: 'quem', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'verbo + -ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' reading now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'Teste principal: ', tone: 'strong' }, { text: 'você precisa das duas partes: am / is / are e -ing. Uma só não basta.' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'I working now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'He is cook dinner', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
    ],
    linesVi: [
      { type: 'text', parts: [{ text: 'Nếu ai đó đang làm gì ' }, { text: 'ngay bây giờ', tone: 'strong' }, { text: ', tiếng Anh dùng:' }] },
      { type: 'formula', parts: [{ text: 'ai', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'động từ + -ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' reading now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'Cách kiểm tra chính: ', tone: 'strong' }, { text: 'cần đủ hai phần: am / is / are và -ing. Một phần là chưa đủ.' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'I working now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'He is cook dinner', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
    ],
    linesId: [
      { type: 'text', parts: [{ text: 'Jika seseorang melakukan sesuatu ' }, { text: 'sekarang juga', tone: 'strong' }, { text: ', bahasa Inggris memakai:' }] },
      { type: 'formula', parts: [{ text: 'siapa', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'kata kerja + -ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' reading now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'Pemeriksaan utama: ', tone: 'strong' }, { text: 'dua bagian wajib ada: am / is / are dan -ing. Satu bagian saja tidak cukup.' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'I working now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'He is cook dinner', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
    ],
    linesTr: [
      { type: 'text', parts: [{ text: 'Bir kişi bir şeyi ' }, { text: 'tam şu anda', tone: 'strong' }, { text: ' yapıyorsa İngilizce şunu kullanır:' }] },
      { type: 'formula', parts: [{ text: 'kim', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'fiil + -ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' reading now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'Ana kontrol: ', tone: 'strong' }, { text: 'iki parça da gerekir: am / is / are ve -ing. Tek parça yetmez.' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'I working now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'He is cook dinner', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
    ],
    linesPl: [
      { type: 'text', parts: [{ text: 'Jeśli ktoś robi coś ' }, { text: 'właśnie teraz', tone: 'strong' }, { text: ', angielski używa:' }] },
      { type: 'formula', parts: [{ text: 'kto', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'czasownik + -ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' reading now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'Główna kontrola: ', tone: 'strong' }, { text: 'potrzebne są obie części: am / is / are i -ing. Jedna część nie wystarczy.' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'I working now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'He is cook dinner', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }] },
    ],
    examples: [
      {
        labelRU: 'I am',
        labelUK: 'I am',
        labelES: 'I am',
        labelPtBr: 'I am',
        labelVi: 'I am',
        labelId: 'I am',
        labelTr: 'I am',
        labelPl: 'I am',
        en: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' working now', tone: 'warning' }],
        ru: 'Я сейчас работаю',
        uk: 'Я зараз працюю',
        es: 'Estoy trabajando ahora.',
        'pt-BR': 'Estou trabalhando agora.',
        vi: 'Bây giờ tôi đang làm việc.',
        id: 'Saya sedang bekerja sekarang.',
        tr: 'Şu anda çalışıyorum.',
        pl: 'Teraz pracuję.',
        trRU: 'Я сейчас работаю',
        trUK: 'Я зараз працюю',
        trES: 'Estoy trabajando ahora.',
        noteRU: 'I требует am, а действие получает -ing.',
        noteUK: 'I вимагає am, а дія отримує -ing.',
        noteES: 'Use am with I, and add -ing to the action.',
        notePtBr: 'Use am com I e acrescente -ing à ação.',
        noteVi: 'Dùng am với I và thêm -ing vào hành động.',
        noteId: 'Gunakan am dengan I, dan tambahkan -ing pada aksinya.',
        noteTr: 'I ile am kullan ve eyleme -ing ekle.',
        notePl: 'Z I użyj am, a do czynności dodaj -ing.',
      },
      {
        labelRU: 'he is',
        labelUK: 'he is',
        labelES: 'he is',
        labelPtBr: 'he is',
        labelVi: 'he is',
        labelId: 'he is',
        labelTr: 'he is',
        labelPl: 'he is',
        en: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' cooking dinner', tone: 'warning' }],
        ru: 'Он готовит ужин',
        uk: 'Він готує вечерю',
        es: 'Está preparando la cena.',
        'pt-BR': 'Ele está preparando o jantar.',
        vi: 'Anh ấy đang nấu bữa tối.',
        id: 'Dia sedang memasak makan malam.',
        tr: 'Akşam yemeği pişiriyor.',
        pl: 'On przygotowuje kolację.',
        trRU: 'Он готовит ужин',
        trUK: 'Він готує вечерю',
        trES: 'Está preparando la cena.',
        noteRU: 'He требует is.',
        noteUK: 'He вимагає is.',
        noteES: 'Use is with he.',
        notePtBr: 'Use is com he.',
        noteVi: 'Dùng is với he.',
        noteId: 'Gunakan is dengan he.',
        noteTr: 'He ile is kullan.',
        notePl: 'Z he użyj is.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран вводит Present Continuous как am/is/are + V-ing для действия сейчас.',
      visualPriority: ['am / is / are выделять accent.', '-ing и V-ing блок выделять warning.', 'ошибки I working now и He is cook dinner выделять danger.'],
      highlightRules: ['subject = strong.', 'am/is/are = accent.', 'V-ing = warning.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять Present Simple как основную тему.', 'Не добавлять Past Continuous.', 'Не добавлять going to.', 'Не использовать фразы вне урока 17.'],
      layoutRules: ['Один экран - только базовая утвердительная формула.', 'Не смешивать отрицания и вопросы на первом экране.'],
    },
  },
  {
    lessonId: 17,
    screenId: 'lesson_17_intro_2_negatives',
    order: 2,
    kind: 'formula',
    titleRU: 'Как сказать "не сейчас делает"',
    titleUK: 'Як сказати "не зараз робить"',
    titleES: 'How to make it negative',
    titlePtBr: 'Como formar a negativa',
    titleVi: 'Cách nói phủ định',
    titleId: 'Cara membuat bentuk negatif',
    titleTr: 'Olumsuz nasıl yapılır',
    titlePl: 'Jak zrobić przeczenie',
    subtitleRU: 'В отрицании not ставится после am / is / are, а -ing остается.',
    subtitleUK: 'У запереченні not стоїть після am / is / are, а -ing залишається.',
    subtitleES: 'In negatives, not comes after am / is / are, and -ing stays.',
    subtitlePtBr: 'Na negativa, not vem depois de am / is / are, e -ing continua.',
    subtitleVi: 'Trong câu phủ định, not đứng sau am / is / are, còn -ing vẫn giữ.',
    subtitleId: 'Dalam bentuk negatif, not berada setelah am / is / are, dan -ing tetap ada.',
    subtitleTr: 'Olumsuz cümlede not, am / is / are sonrasına gelir; -ing kalır.',
    subtitlePl: 'W przeczeniu not stoi po am / is / are, a -ing zostaje.',
    textRU: 'Not ставится после am/is/are. V-ing остается.',
    textUK: 'Not стоїть після am/is/are. V-ing залишається.',
    textES: 'Not comes after am/is/are. V-ing stays.',
    textPtBr: 'Not vem depois de am/is/are. V-ing continua.',
    textVi: 'Not đứng sau am/is/are. V-ing vẫn giữ.',
    textId: 'Not berada setelah am/is/are. V-ing tetap ada.',
    textTr: 'Not, am/is/are sonrasına gelir. V-ing kalır.',
    textPl: 'Not stoi po am/is/are. V-ing zostaje.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' looking for problems', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'not не заменяет -ing. ', tone: 'strong' }, { text: 'Даже в отрицании действие остается в -ing форме.' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'They are not watch TV', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'I am not work now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' looking for problems', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'who + ', tone: 'formula' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
    ],
    linesPtBr: [
      { type: 'formula', parts: [{ text: 'quem', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' looking for problems', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'not não substitui -ing. ', tone: 'strong' }, { text: 'Mesmo na negativa, a ação fica na forma -ing.' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'They are not watch TV', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'I am not work now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
    ],
    linesVi: [
      { type: 'formula', parts: [{ text: 'ai', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' looking for problems', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'not không thay thế -ing. ', tone: 'strong' }, { text: 'Ngay cả trong phủ định, hành động vẫn ở dạng -ing.' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'They are not watch TV', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'I am not work now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
    ],
    linesId: [
      { type: 'formula', parts: [{ text: 'siapa', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' looking for problems', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'not tidak menggantikan -ing. ', tone: 'strong' }, { text: 'Bahkan dalam bentuk negatif, aksi tetap memakai bentuk -ing.' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'They are not watch TV', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'I am not work now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
    ],
    linesTr: [
      { type: 'formula', parts: [{ text: 'kim', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' looking for problems', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'not, -ing yerine geçmez. ', tone: 'strong' }, { text: 'Olumsuz cümlede bile eylem -ing biçiminde kalır.' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'They are not watch TV', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'I am not work now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
    ],
    linesPl: [
      { type: 'formula', parts: [{ text: 'kto', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' looking for problems', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'not nie zastępuje -ing. ', tone: 'strong' }, { text: 'Nawet w przeczeniu czynność zostaje w formie -ing.' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'They are not watch TV', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'I am not work now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' working now', tone: 'warning' }] },
    ],
    examples: [
      {
        labelRU: 'not after am',
        labelUK: 'not after am',
        labelES: 'not after am',
        labelPtBr: 'not depois de am',
        labelVi: 'not sau am',
        labelId: 'not setelah am',
        labelTr: 'am sonrasında not',
        labelPl: 'not po am',
        en: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' looking for problems', tone: 'warning' }],
        ru: 'Я не ищу проблем',
        uk: 'Я не шукаю проблем',
        es: 'No estoy buscando problemas.',
        'pt-BR': 'Não estou procurando problemas.',
        vi: 'Tôi không đang tìm rắc rối.',
        id: 'Saya tidak sedang mencari masalah.',
        tr: 'Sorun aramıyorum.',
        pl: 'Nie szukam problemów.',
        trRU: 'Я не ищу проблем',
        trUK: 'Я не шукаю проблем',
        trES: 'No estoy buscando problemas.',
        noteRU: 'not ставится после am, а looking for остается связкой.',
        noteUK: 'not стоїть після am, а looking for залишається зв\'язкою.',
        noteES: 'not comes after am, and looking for stays together.',
        notePtBr: 'not vem depois de am, e looking for continua junto.',
        noteVi: 'not đứng sau am, và looking for vẫn đi cùng nhau.',
        noteId: 'not berada setelah am, dan looking for tetap menjadi satu.',
        noteTr: 'not, am sonrasına gelir; looking for birlikte kalır.',
        notePl: 'not stoi po am, a looking for zostaje razem.',
      },
      {
        labelRU: 'not after are',
        labelUK: 'not after are',
        labelES: 'not after are',
        labelPtBr: 'not depois de are',
        labelVi: 'not sau are',
        labelId: 'not setelah are',
        labelTr: 'are sonrasında not',
        labelPl: 'not po are',
        en: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' watching TV', tone: 'warning' }],
        ru: 'Они не смотрят телевизор',
        uk: 'Вони не дивляться телевізор',
        es: 'No están viendo la televisión.',
        'pt-BR': 'Eles não estão assistindo TV.',
        vi: 'Họ không đang xem TV.',
        id: 'Mereka tidak sedang menonton TV.',
        tr: 'Televizyon izlemiyorlar.',
        pl: 'Oni nie oglądają telewizji.',
        trRU: 'Они не смотрят телевизор',
        trUK: 'Вони не дивляться телевізор',
        trES: 'No están viendo la televisión.',
        noteRU: 'They требует are, а watch становится watching.',
        noteUK: 'They вимагає are, а watch стає watching.',
        noteES: 'Use are with they, and watch becomes watching.',
        notePtBr: 'Use are com they, e watch vira watching.',
        noteVi: 'Dùng are với they, và watch thành watching.',
        noteId: 'Gunakan are dengan they, dan watch menjadi watching.',
        noteTr: 'They ile are kullan; watch, watching olur.',
        notePl: 'Z they użyj are, a watch zmienia się w watching.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран отдельно закрепляет отрицания Present Continuous: not после am/is/are, V-ing остается.',
      visualPriority: ['am/is/are выделять accent.', 'not и V-ing выделять warning.', 'ошибки They are not watch TV и I am not work now выделять danger.'],
      highlightRules: ['subject = strong.', 'am/is/are = accent.', 'not = warning.', 'V-ing = warning.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять do not / does not.', 'Не добавлять сокращения.', 'Не добавлять Past Continuous.', 'Не использовать фразы вне урока 17.'],
      layoutRules: ['Один экран - только отрицания.', 'Если экран узкий, оставить I am not working, I am not looking for problems, They are not watching TV.'],
    },
  },
  {
    lessonId: 17,
    screenId: 'lesson_17_intro_3_yes_no_questions',
    order: 3,
    kind: 'formula',
    titleRU: 'Как задать обычный вопрос',
    titleUK: 'Як поставити звичайне питання',
    titleES: 'How to ask a yes/no question',
    titlePtBr: 'Como fazer uma pergunta sim/não',
    titleVi: 'Cách đặt câu hỏi có/không',
    titleId: 'Cara membuat pertanyaan ya/tidak',
    titleTr: 'Evet/hayır sorusu nasıl sorulur',
    titlePl: 'Jak zadać pytanie tak/nie',
    subtitleRU: 'В вопросе am / is / are выходит в начало, а -ing остается.',
    subtitleUK: 'У питанні am / is / are виходить на початок, а -ing залишається.',
    subtitleES: 'In questions, am / is / are moves to the front, and -ing stays.',
    subtitlePtBr: 'Na pergunta, am / is / are vai para o começo, e -ing continua.',
    subtitleVi: 'Trong câu hỏi, am / is / are lên đầu, còn -ing vẫn giữ.',
    subtitleId: 'Dalam pertanyaan, am / is / are pindah ke depan, dan -ing tetap ada.',
    subtitleTr: 'Soruda am / is / are başa gelir; -ing kalır.',
    subtitlePl: 'W pytaniu am / is / are idzie na początek, a -ing zostaje.',
    textRU: 'В обычном вопросе am/is/are выходит перед человеком.',
    textUK: 'У звичайному питанні am/is/are виходить перед людиною.',
    textES: 'In a yes/no question, am/is/are moves before the person.',
    textPtBr: 'Em uma pergunta sim/não, am/is/are vem antes da pessoa.',
    textVi: 'Trong câu hỏi có/không, am/is/are đứng trước người.',
    textId: 'Dalam pertanyaan ya/tidak, am/is/are berada sebelum orangnya.',
    textTr: 'Evet/hayır sorusunda am/is/are kişiden önce gelir.',
    textPl: 'W pytaniu tak/nie am/is/are stoi przed osobą.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'Am / Is / Are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he cooking dinner?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' they watching TV?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he looking for keys?', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Вопрос строится не через do / does. ', tone: 'strong' }, { text: 'Здесь работает am / is / are.' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Do you working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'You are working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'Am / Is / Are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he cooking dinner?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' they watching TV?', tone: 'warning' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'Am / Is / Are', tone: 'accent' }, { text: ' + who + ', tone: 'formula' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
    ],
    linesPtBr: [
      { type: 'formula', parts: [{ text: 'Am / Is / Are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'quem', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he cooking dinner?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' they watching TV?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he looking for keys?', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'A pergunta não usa do / does aqui. ', tone: 'strong' }, { text: 'Nesta estrutura, quem trabalha é am / is / are.' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'Do you working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'You are working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
    ],
    linesVi: [
      { type: 'formula', parts: [{ text: 'Am / Is / Are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'ai', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he cooking dinner?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' they watching TV?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he looking for keys?', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'Câu hỏi này không dùng do / does. ', tone: 'strong' }, { text: 'Ở đây dùng am / is / are.' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'Do you working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'You are working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
    ],
    linesId: [
      { type: 'formula', parts: [{ text: 'Am / Is / Are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'siapa', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he cooking dinner?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' they watching TV?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he looking for keys?', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'Pertanyaan ini tidak memakai do / does. ', tone: 'strong' }, { text: 'Di sini yang dipakai adalah am / is / are.' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'Do you working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'You are working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
    ],
    linesTr: [
      { type: 'formula', parts: [{ text: 'Am / Is / Are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'kim', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he cooking dinner?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' they watching TV?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he looking for keys?', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'Bu soru do / does ile kurulmaz. ', tone: 'strong' }, { text: 'Burada am / is / are çalışır.' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'Do you working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'You are working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
    ],
    linesPl: [
      { type: 'formula', parts: [{ text: 'Am / Is / Are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'kto', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he cooking dinner?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' they watching TV?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Is', tone: 'accent' }, { text: ' he looking for keys?', tone: 'warning' }] },
      { type: 'tip', parts: [{ text: 'Tego pytania nie buduje się przez do / does. ', tone: 'strong' }, { text: 'Tutaj działa am / is / are.' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'Do you working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'You are working now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }] },
    ],
    examples: [
      {
        labelRU: 'Are you',
        labelUK: 'Are you',
        labelES: 'Are you',
        labelPtBr: 'Are you',
        labelVi: 'Are you',
        labelId: 'Are you',
        labelTr: 'Are you',
        labelPl: 'Are you',
        en: [{ text: 'Are', tone: 'accent' }, { text: ' you working now?', tone: 'warning' }],
        ru: 'Ты сейчас работаешь?',
        uk: 'Ти зараз працюєш?',
        es: '¿Estás trabajando ahora?',
        'pt-BR': 'Você está trabalhando agora?',
        vi: 'Bây giờ bạn đang làm việc à?',
        id: 'Apakah kamu sedang bekerja sekarang?',
        tr: 'Şu anda çalışıyor musun?',
        pl: 'Czy teraz pracujesz?',
        trRU: 'Ты сейчас работаешь?',
        trUK: 'Ти зараз працюєш?',
        trES: '¿Estás trabajando ahora?',
        noteRU: 'В вопросе Are выходит перед you.',
        noteUK: 'У питанні Are виходить перед you.',
        noteES: 'In a question, Are moves before you.',
        notePtBr: 'Na pergunta, Are vem antes de you.',
        noteVi: 'Trong câu hỏi, Are đứng trước you.',
        noteId: 'Dalam pertanyaan, Are berada sebelum you.',
        noteTr: 'Soruda Are, you önüne gelir.',
        notePl: 'W pytaniu Are stoi przed you.',
      },
      {
        labelRU: 'Is he',
        labelUK: 'Is he',
        labelES: 'Is he',
        labelPtBr: 'Is he',
        labelVi: 'Is he',
        labelId: 'Is he',
        labelTr: 'Is he',
        labelPl: 'Is he',
        en: [{ text: 'Is', tone: 'accent' }, { text: ' he looking for keys?', tone: 'warning' }],
        ru: 'Он ищет ключи?',
        uk: 'Він шукає ключі?',
        es: '¿Está buscando las llaves?',
        'pt-BR': 'Ele está procurando as chaves?',
        vi: 'Anh ấy đang tìm chìa khóa à?',
        id: 'Apakah dia sedang mencari kunci?',
        tr: 'Anahtarları arıyor mu?',
        pl: 'Czy on szuka kluczy?',
        trRU: 'Он ищет ключи?',
        trUK: 'Він шукає ключі?',
        trES: '¿Está buscando las llaves?',
        noteRU: 'Looking for остается вместе.',
        noteUK: 'Looking for залишається разом.',
        noteES: 'Looking for stays together.',
        notePtBr: 'Looking for continua junto.',
        noteVi: 'Looking for vẫn đi cùng nhau.',
        noteId: 'Looking for tetap menjadi satu.',
        noteTr: 'Looking for birlikte kalır.',
        notePl: 'Looking for zostaje razem.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран отдельно закрепляет yes/no questions в Present Continuous.',
      visualPriority: ['Am/Is/Are в начале вопроса выделять accent.', 'V-ing блок выделять warning.', 'ошибки Do you working и You are working? выделять danger.'],
      highlightRules: ['question starter Am/Is/Are = accent.', 'V-ing = warning.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять do/does как правильный способ строить вопросы.', 'Не добавлять Past Continuous.', 'Не использовать фразы вне урока 17.'],
      layoutRules: ['Один экран - только обычные вопросы.', 'Если экран узкий, оставить Am I, Are you, Is he, Are they.'],
    },
  },
  {
    lessonId: 17,
    screenId: 'lesson_17_intro_4_wh_questions_phrasal_practice',
    order: 4,
    kind: 'practice',
    titleRU: 'WH-вопросы и фразовые глаголы',
    titleUK: 'WH-питання і фразові дієслова',
    titleES: 'WH-questions and phrasal verbs',
    titlePtBr: 'Perguntas WH e phrasal verbs',
    titleVi: 'Câu hỏi WH và cụm động từ',
    titleId: 'Pertanyaan WH dan phrasal verb',
    titleTr: 'WH soruları ve phrasal verbler',
    titlePl: 'Pytania WH i czasowniki frazowe',
    subtitleRU: 'В специальных вопросах вопросительное слово идет первым, потом am / is / are.',
    subtitleUK: 'У спеціальних питаннях питальне слово йде першим, потім am / is / are.',
    subtitleES: 'In WH-questions, the question word comes first, then am / is / are.',
    subtitlePtBr: 'Em perguntas WH, a palavra interrogativa vem primeiro, depois am / is / are.',
    subtitleVi: 'Trong câu hỏi WH, từ để hỏi đứng trước, rồi đến am / is / are.',
    subtitleId: 'Dalam pertanyaan WH, kata tanya datang dulu, lalu am / is / are.',
    subtitleTr: 'WH sorularında soru kelimesi önce gelir, sonra am / is / are.',
    subtitlePl: 'W pytaniach WH najpierw stoi słowo pytające, potem am / is / are.',
    textRU: 'WH-вопрос: вопросительное слово + am/is/are + кто + V-ing.',
    textUK: 'WH-питання: питальне слово + am/is/are + хто + V-ing.',
    textES: 'WH-question: question word + am/is/are + who + V-ing.',
    textPtBr: 'Pergunta WH: palavra interrogativa + am/is/are + quem + V-ing.',
    textVi: 'Câu hỏi WH: từ để hỏi + am/is/are + ai + V-ing.',
    textId: 'Pertanyaan WH: kata tanya + am/is/are + siapa + V-ing.',
    textTr: 'WH sorusu: soru kelimesi + am/is/are + kim + V-ing.',
    textPl: 'Pytanie WH: słowo pytające + am/is/are + kto + V-ing.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'What / Where / Why', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Where', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' they going?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Why', tone: 'accent' }, { text: ' ' }, { text: 'is', tone: 'warning' }, { text: ' she crying?', tone: 'warning' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Фразовый глагол:', tone: 'formula' }, { text: ' ' }, { text: 'am / is / are + verb-ing + particle', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'warning' }, { text: ' turning ' }, { text: 'off', tone: 'accent' }, { text: ' my phone' }] },
      { type: 'correct', parts: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'warning' }, { text: ' cleaning ' }, { text: 'up', tone: 'accent' }, { text: ' their room' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Есть "что / где / почему"? ', tone: 'muted' }, { text: 'Ставь question word первым.', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. Потом выбери ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' по "кто".', tone: 'muted' }] },
      { type: 'step', parts: [{ text: '3. Потом действие с ', tone: 'muted' }, { text: '-ing', tone: 'warning' }, { text: '. Если это фразовый глагол, частицу не выбрасывай.', tone: 'muted' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'What you are doing now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'She is putting her jacket', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'What / Where / Why', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' + хто + ', tone: 'formula' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Why', tone: 'accent' }, { text: ' ' }, { text: 'is', tone: 'warning' }, { text: ' she crying?', tone: 'warning' }] },
      { type: 'formula', parts: [{ text: 'Фразове дієслово:', tone: 'formula' }, { text: ' ' }, { text: 'am / is / are + verb-ing + particle', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'What / Where / Why', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' + who + ', tone: 'formula' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
    ],
    linesPtBr: [
      { type: 'formula', parts: [{ text: 'What / Where / Why', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'quem', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Where', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' they going?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Why', tone: 'accent' }, { text: ' ' }, { text: 'is', tone: 'warning' }, { text: ' she crying?', tone: 'warning' }] },
      { type: 'formula', parts: [{ text: 'Phrasal verb:', tone: 'formula' }, { text: ' ' }, { text: 'am / is / are + verb-ing + particle', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'warning' }, { text: ' turning ' }, { text: 'off', tone: 'accent' }, { text: ' my phone' }] },
      { type: 'correct', parts: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'warning' }, { text: ' cleaning ' }, { text: 'up', tone: 'accent' }, { text: ' their room' }] },
      { type: 'step', parts: [{ text: '1. Há "what / where / why"? ', tone: 'muted' }, { text: 'Coloque a question word primeiro.', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. Depois escolha ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' pelo sujeito.', tone: 'muted' }] },
      { type: 'step', parts: [{ text: '3. Depois vem a ação com ', tone: 'muted' }, { text: '-ing', tone: 'warning' }, { text: '. Se for phrasal verb, não tire a partícula.', tone: 'muted' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'What you are doing now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'She is putting her jacket', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
    ],
    linesVi: [
      { type: 'formula', parts: [{ text: 'What / Where / Why', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'ai', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Where', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' they going?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Why', tone: 'accent' }, { text: ' ' }, { text: 'is', tone: 'warning' }, { text: ' she crying?', tone: 'warning' }] },
      { type: 'formula', parts: [{ text: 'Cụm động từ:', tone: 'formula' }, { text: ' ' }, { text: 'am / is / are + verb-ing + particle', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'warning' }, { text: ' turning ' }, { text: 'off', tone: 'accent' }, { text: ' my phone' }] },
      { type: 'correct', parts: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'warning' }, { text: ' cleaning ' }, { text: 'up', tone: 'accent' }, { text: ' their room' }] },
      { type: 'step', parts: [{ text: '1. Có "what / where / why"? ', tone: 'muted' }, { text: 'Đặt question word lên đầu.', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. Sau đó chọn ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' theo chủ ngữ.', tone: 'muted' }] },
      { type: 'step', parts: [{ text: '3. Sau đó là hành động với ', tone: 'muted' }, { text: '-ing', tone: 'warning' }, { text: '. Nếu là cụm động từ, đừng bỏ particle.', tone: 'muted' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'What you are doing now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'She is putting her jacket', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
    ],
    linesId: [
      { type: 'formula', parts: [{ text: 'What / Where / Why', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'siapa', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Where', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' they going?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Why', tone: 'accent' }, { text: ' ' }, { text: 'is', tone: 'warning' }, { text: ' she crying?', tone: 'warning' }] },
      { type: 'formula', parts: [{ text: 'Phrasal verb:', tone: 'formula' }, { text: ' ' }, { text: 'am / is / are + verb-ing + particle', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'warning' }, { text: ' turning ' }, { text: 'off', tone: 'accent' }, { text: ' my phone' }] },
      { type: 'correct', parts: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'warning' }, { text: ' cleaning ' }, { text: 'up', tone: 'accent' }, { text: ' their room' }] },
      { type: 'step', parts: [{ text: '1. Ada "what / where / why"? ', tone: 'muted' }, { text: 'Letakkan question word di awal.', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. Lalu pilih ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' sesuai subjek.', tone: 'muted' }] },
      { type: 'step', parts: [{ text: '3. Lalu aksi dengan ', tone: 'muted' }, { text: '-ing', tone: 'warning' }, { text: '. Jika phrasal verb, jangan buang partikelnya.', tone: 'muted' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'What you are doing now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'She is putting her jacket', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
    ],
    linesTr: [
      { type: 'formula', parts: [{ text: 'What / Where / Why', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'kim', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Where', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' they going?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Why', tone: 'accent' }, { text: ' ' }, { text: 'is', tone: 'warning' }, { text: ' she crying?', tone: 'warning' }] },
      { type: 'formula', parts: [{ text: 'Phrasal verb:', tone: 'formula' }, { text: ' ' }, { text: 'am / is / are + verb-ing + particle', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'warning' }, { text: ' turning ' }, { text: 'off', tone: 'accent' }, { text: ' my phone' }] },
      { type: 'correct', parts: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'warning' }, { text: ' cleaning ' }, { text: 'up', tone: 'accent' }, { text: ' their room' }] },
      { type: 'step', parts: [{ text: '1. "What / where / why" var mı? ', tone: 'muted' }, { text: 'Question word en başa gelir.', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. Sonra özneye göre ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' seç.', tone: 'muted' }] },
      { type: 'step', parts: [{ text: '3. Sonra ', tone: 'muted' }, { text: '-ing', tone: 'warning' }, { text: ' olan eylem gelir. Phrasal verb ise particle kelimesini atma.', tone: 'muted' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'What you are doing now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'She is putting her jacket', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
    ],
    linesPl: [
      { type: 'formula', parts: [{ text: 'What / Where / Why', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'kto', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'V-ing?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Where', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' they going?', tone: 'warning' }] },
      { type: 'correct', parts: [{ text: 'Why', tone: 'accent' }, { text: ' ' }, { text: 'is', tone: 'warning' }, { text: ' she crying?', tone: 'warning' }] },
      { type: 'formula', parts: [{ text: 'Czasownik frazowy:', tone: 'formula' }, { text: ' ' }, { text: 'am / is / are + verb-ing + particle', tone: 'accent' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'warning' }, { text: ' turning ' }, { text: 'off', tone: 'accent' }, { text: ' my phone' }] },
      { type: 'correct', parts: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'warning' }, { text: ' cleaning ' }, { text: 'up', tone: 'accent' }, { text: ' their room' }] },
      { type: 'step', parts: [{ text: '1. Jest "what / where / why"? ', tone: 'muted' }, { text: 'Daj question word na początek.', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. Potem wybierz ', tone: 'muted' }, { text: 'am / is / are', tone: 'warning' }, { text: ' według osoby.', tone: 'muted' }] },
      { type: 'step', parts: [{ text: '3. Potem czynność z ', tone: 'muted' }, { text: '-ing', tone: 'warning' }, { text: '. Jeśli to czasownik frazowy, nie wyrzucaj partykuły.', tone: 'muted' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'What you are doing now?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'What', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' you doing now?', tone: 'warning' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'She is putting her jacket', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }] },
    ],
    examples: [
      {
        labelRU: 'WH-вопрос',
        labelUK: 'WH-питання',
        labelES: 'WH-question',
        labelPtBr: 'pergunta WH',
        labelVi: 'câu hỏi WH',
        labelId: 'pertanyaan WH',
        labelTr: 'WH sorusu',
        labelPl: 'pytanie WH',
        en: [{ text: 'Where', tone: 'accent' }, { text: ' ' }, { text: 'are', tone: 'warning' }, { text: ' they going?', tone: 'warning' }],
        ru: 'Куда они идут?',
        uk: 'Куди вони йдуть?',
        es: '¿Adónde van?',
        'pt-BR': 'Para onde eles estão indo?',
        vi: 'Họ đang đi đâu?',
        id: 'Ke mana mereka pergi?',
        tr: 'Nereye gidiyorlar?',
        pl: 'Dokąd oni idą?',
        trRU: 'Куда они идут?',
        trUK: 'Куди вони йдуть?',
        trES: '¿Adónde van?',
        noteRU: 'Where первым, потом are, потом they going.',
        noteUK: 'Where першим, потім are, потім they going.',
        noteES: 'Where first, then are, then they going.',
        notePtBr: 'Where vem primeiro, depois are, depois they going.',
        noteVi: 'Where đứng trước, rồi are, rồi they going.',
        noteId: 'Where dulu, lalu are, lalu they going.',
        noteTr: 'Önce Where, sonra are, sonra they going.',
        notePl: 'Najpierw Where, potem are, potem they going.',
      },
      {
        labelRU: 'фразовый глагол',
        labelUK: 'фразове дієслово',
        labelES: 'phrasal verb',
        labelPtBr: 'phrasal verb',
        labelVi: 'cụm động từ',
        labelId: 'phrasal verb',
        labelTr: 'phrasal verb',
        labelPl: 'czasownik frazowy',
        en: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'warning' }, { text: ' turning ' }, { text: 'off', tone: 'accent' }, { text: ' my phone' }],
        ru: 'Я выключаю свой телефон',
        uk: 'Я вимикаю свій телефон',
        es: 'Estoy apagando mi teléfono.',
        'pt-BR': 'Estou desligando meu telefone.',
        vi: 'Tôi đang tắt điện thoại của mình.',
        id: 'Saya sedang mematikan ponsel saya.',
        tr: 'Telefonumu kapatıyorum.',
        pl: 'Wyłączam swój telefon.',
        trRU: 'Я выключаю свой телефон',
        trUK: 'Я вимикаю свій телефон',
        trES: 'Estoy apagando mi teléfono.',
        noteRU: 'Turn off остается связкой, но turn становится turning.',
        noteUK: 'Turn off залишається зв\'язкою, але turn стає turning.',
        noteES: 'Turn off stays as a unit, but turn becomes turning.',
        notePtBr: 'Turn off continua como unidade, mas turn vira turning.',
        noteVi: 'Turn off vẫn là một cụm, nhưng turn thành turning.',
        noteId: 'Turn off tetap satu unit, tetapi turn menjadi turning.',
        noteTr: 'Turn off bir birim olarak kalır, ama turn, turning olur.',
        notePl: 'Turn off zostaje jedną jednostką, ale turn zmienia się w turning.',
      },
      {
        labelRU: 'putting on',
        labelUK: 'putting on',
        labelES: 'putting on',
        labelPtBr: 'putting on',
        labelVi: 'putting on',
        labelId: 'putting on',
        labelTr: 'putting on',
        labelPl: 'putting on',
        en: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'warning' }, { text: ' putting ' }, { text: 'on', tone: 'accent' }, { text: ' her jacket' }],
        ru: 'Она надевает свою куртку',
        uk: 'Вона надягає свою куртку',
        es: 'Se está poniendo su chaqueta.',
        'pt-BR': 'Ela está vestindo a jaqueta dela.',
        vi: 'Cô ấy đang mặc áo khoác của mình.',
        id: 'Dia sedang memakai jaketnya.',
        tr: 'Ceketini giyiyor.',
        pl: 'Ona zakłada swoją kurtkę.',
        trRU: 'Она надевает свою куртку',
        trUK: 'Вона надягає свою куртку',
        trES: 'Se está poniendo su chaqueta.',
        noteRU: 'Не пропускай on: putting on = надевает одежду.',
        noteUK: 'Не пропускай on: putting on = надягає одяг.',
        noteES: 'Do not drop on: putting on = putting on clothes.',
        notePtBr: 'Não tire on: putting on = vestir roupa.',
        noteVi: 'Đừng bỏ on: putting on = mặc đồ.',
        noteId: 'Jangan hilangkan on: putting on = memakai pakaian.',
        noteTr: 'on kelimesini atma: putting on = kıyafet giymek.',
        notePl: 'Nie pomijaj on: putting on = zakładanie ubrania.',
      },
    ],
    developerNotes: {
      screenGoal: 'Финальный экран связывает WH-вопросы и phrasal verbs в Present Continuous.',
      visualPriority: ['question words выделять accent.', 'am/is/are в WH-вопросах выделять warning.', 'particle off/on/up выделять accent.', 'wrong examples выделять danger.'],
      highlightRules: ['question word = accent.', 'am/is/are in question = warning.', 'V-ing = warning.', 'particle = accent.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять Past Continuous.', 'Не добавлять Present Simple questions с do/does.', 'Не добавлять фразовые глаголы вне урока 17.'],
      layoutRules: ['Экран финальный и практический.', 'Если не помещается, оставить What are you doing, Why is she crying, turning off, putting on и две ошибки.'],
    },
  },
];
