/**
 * Alias `LESSON_*_INTRO_SCREENS` для `lesson_data_*` — тот же контент, что EXTRA_INTRO (español L2).
 */
export {
  LESSON_17_INTRO_EXTRA as LESSON_17_INTRO_SCREENS,
  LESSON_18_INTRO_EXTRA as LESSON_18_INTRO_SCREENS,
  LESSON_19_INTRO_EXTRA as LESSON_19_INTRO_SCREENS,
  LESSON_20_INTRO_EXTRA as LESSON_20_INTRO_SCREENS,
  LESSON_21_INTRO_EXTRA as LESSON_21_INTRO_SCREENS,
  LESSON_22_INTRO_EXTRA as LESSON_22_INTRO_SCREENS,
  LESSON_23_INTRO_EXTRA as LESSON_23_INTRO_SCREENS,
  LESSON_24_INTRO_EXTRA as LESSON_24_INTRO_SCREENS,
  LESSON_25_INTRO_EXTRA as LESSON_25_INTRO_SCREENS,
  LESSON_26_INTRO_EXTRA as LESSON_26_INTRO_SCREENS,
  LESSON_27_INTRO_EXTRA as LESSON_27_INTRO_SCREENS,
  LESSON_28_INTRO_EXTRA as LESSON_28_INTRO_SCREENS,
  LESSON_29_INTRO_EXTRA as LESSON_29_INTRO_SCREENS,
  LESSON_30_INTRO_EXTRA as LESSON_30_INTRO_SCREENS,
  LESSON_31_INTRO_EXTRA as LESSON_31_INTRO_SCREENS,
  LESSON_32_INTRO_EXTRA as LESSON_32_INTRO_SCREENS,
} from './lesson_intro_screens_es_l2';

/* expo-router route shim: keeps utility module from warning when discovered as route */
export default function __RouteShim() {
  return null;
}
