const L17_RU: any[] = [
  { russian: 'Я сейчас работаю.', english: 'I am working right now', level: 'A2' },
  { russian: 'Она читает книгу.', english: 'She is reading a book', level: 'A2' },
  { russian: 'Они обедают.', english: 'They are having lunch', level: 'A2' },
  { russian: 'Он звонит клиенту.', english: 'He is calling a client', level: 'A2' },
  { russian: 'Мы ждём такси.', english: 'We are waiting for a taxi', level: 'A2' },
  { russian: 'Я пишу отчёт.', english: 'I am writing a report', level: 'A2' },
  { russian: 'Она учится.', english: 'She is studying', level: 'A2' },
  { russian: 'Они переезжают в новый офис.', english: 'They are moving to a new office', level: 'B1' },
  { russian: 'Он не работает сейчас.', english: 'He is not working right now', level: 'A2' },
  { russian: 'Ты слушаешь меня?', english: 'Are you listening to me', level: 'A2' },
  { russian: 'Что ты делаешь?', english: 'What are you doing', level: 'A2' },
  { russian: 'Она не слушает.', english: 'She is not listening', level: 'A2' },
  { russian: 'Мы обсуждаем проект.', english: 'We are discussing the project', level: 'B1' },
  { russian: 'Он готовится к встрече.', english: 'He is preparing for the meeting', level: 'B1' },
  { russian: 'Я планирую поездку.', english: 'I am planning a trip', level: 'B1' },
  { russian: 'Они строят новый дом.', english: 'They are building a new house', level: 'B1' },
  { russian: 'Она улучшает свой английский.', english: 'She is improving her English', level: 'B1' },
  { russian: 'Мы сотрудничаем с новой компанией.', english: 'We are cooperating with a new company', level: 'B1' },
  { russian: 'Он ищет новую работу.', english: 'He is looking for a new job', level: 'B1' },
  { russian: 'Дети играют во дворе.', english: 'The children are playing in the yard', level: 'A2' },
  { russian: 'Я думаю о твоём предложении.', english: 'I am thinking about your offer', level: 'B1' },
  { russian: 'Они ведут переговоры.', english: 'They are conducting negotiations', level: 'B2' },
  { russian: 'Он тестирует новое приложение.', english: 'He is testing the new application', level: 'B1' },
  { russian: 'Мы расширяем команду.', english: 'We are expanding the team', level: 'B2' },
  { russian: 'Она руководит проектом.', english: 'She is managing the project', level: 'B2' },
  { russian: 'Я не понимаю, что происходит.', english: 'I do not understand what is happening', level: 'B1' },
  { russian: 'Он работает слишком много в последнее время.', english: 'He is working too much lately', level: 'B2' },
  { russian: 'Они внедряют новую систему.', english: 'They are implementing a new system', level: 'B2' },
  { russian: 'Ты ещё работаешь над этим?', english: 'Are you still working on this', level: 'B1' },
  { russian: 'Она анализирует данные.', english: 'She is analysing the data', level: 'B1' },
  { russian: 'Мы разрабатываем новый продукт.', english: 'We are developing a new product', level: 'B2' },
  { russian: 'Он консультируется с юристом.', english: 'He is consulting with a lawyer', level: 'B2' },
  { russian: 'Что происходит на рынке?', english: 'What is happening in the market', level: 'B2' },
  { russian: 'Я встречаюсь с клиентом в пять.', english: 'I am meeting with the client at five', level: 'B1' },
  { russian: 'Она готовит презентацию.', english: 'She is preparing a presentation', level: 'B1' },
  { russian: 'Они обсуждают условия договора.', english: 'They are discussing the contract terms', level: 'B2' },
  { russian: 'Он возглавляет отдел с этого месяца.', english: 'He is leading the department this month', level: 'B2' },
  { russian: 'Мы работаем над этой задачей уже неделю.', english: 'We have been working on this task for a week already', level: 'B2' },
  { russian: 'Ты не слышишь меня?', english: 'Do you not hear me', level: 'A2' },
  { russian: 'Она переезжает в другой город.', english: 'She is moving to another city', level: 'B1' },
  { russian: 'Он приходит на работу позже обычного.', english: 'He is coming to work later than usual', level: 'B2' },
  { russian: 'Что они обсуждают на совещании?', english: 'What are they discussing at the meeting', level: 'B2' },
  { russian: 'Я изучаю новые технологии.', english: 'I am learning new technologies', level: 'B1' },
  { russian: 'Компания всё ещё нанимает сотрудников.', english: 'The company is still hiring employees', level: 'B2' },
  { russian: 'Они пересматривают бюджет.', english: 'They are reviewing the budget', level: 'B2' },
  { russian: 'Она работает удалённо на этой неделе.', english: 'She is working remotely this week', level: 'B1' },
  { russian: 'Я заканчиваю проект.', english: 'I am finishing the project', level: 'A2' },
  { russian: 'Он налаживает связи с партнёрами.', english: 'He is building relationships with partners', level: 'B2' },
  { russian: 'Мы переходим на новую платформу.', english: 'We are switching to a new platform', level: 'B2' },
  { russian: 'Ты отправляешь отчёт?', english: 'Are you sending the report', level: 'A2' },
];

const L17_UK: any[] = [
  { russian: 'Я зараз працюю.', english: 'I am working right now', level: 'A2' },
  { russian: 'Вона читає книгу.', english: 'She is reading a book', level: 'A2' },
  { russian: 'Вони обідають.', english: 'They are having lunch', level: 'A2' },
  { russian: 'Він телефонує клієнту.', english: 'He is calling a client', level: 'A2' },
  { russian: 'Ми чекаємо таксі.', english: 'We are waiting for a taxi', level: 'A2' },
  { russian: 'Я пишу звіт.', english: 'I am writing a report', level: 'A2' },
  { russian: 'Вона навчається.', english: 'She is studying', level: 'A2' },
  { russian: 'Вони переїжджають до нового офісу.', english: 'They are moving to a new office', level: 'B1' },
  { russian: 'Він зараз не працює.', english: 'He is not working right now', level: 'A2' },
  { russian: 'Ти мене слухаєш?', english: 'Are you listening to me', level: 'A2' },
  { russian: 'Що ти робиш?', english: 'What are you doing', level: 'A2' },
  { russian: 'Вона не слухає.', english: 'She is not listening', level: 'A2' },
  { russian: 'Ми обговорюємо проект.', english: 'We are discussing the project', level: 'B1' },
  { russian: 'Він готується до зустрічі.', english: 'He is preparing for the meeting', level: 'B1' },
  { russian: 'Я планую поїздку.', english: 'I am planning a trip', level: 'B1' },
  { russian: 'Вони будують новий будинок.', english: 'They are building a new house', level: 'B1' },
  { russian: 'Вона покращує свою англійську.', english: 'She is improving her English', level: 'B1' },
  { russian: 'Ми співпрацюємо з новою компанією.', english: 'We are cooperating with a new company', level: 'B1' },
  { russian: 'Він шукає нову роботу.', english: 'He is looking for a new job', level: 'B1' },
  { russian: 'Діти граються у дворі.', english: 'The children are playing in the yard', level: 'A2' },
  { russian: 'Я думаю про твою пропозицію.', english: 'I am thinking about your offer', level: 'B1' },
  { russian: 'Вони ведуть переговори.', english: 'They are conducting negotiations', level: 'B2' },
  { russian: 'Він тестує новий додаток.', english: 'He is testing the new application', level: 'B1' },
  { russian: 'Ми розширюємо команду.', english: 'We are expanding the team', level: 'B2' },
  { russian: 'Вона керує проектом.', english: 'She is managing the project', level: 'B2' },
  { russian: 'Я не розумію, що відбувається.', english: 'I do not understand what is happening', level: 'B1' },
  { russian: 'Він останнім часом працює занадто багато.', english: 'He is working too much lately', level: 'B2' },
  { russian: 'Вони впроваджують нову систему.', english: 'They are implementing a new system', level: 'B2' },
  { russian: 'Ти ще працюєш над цим?', english: 'Are you still working on this', level: 'B1' },
  { russian: 'Вона аналізує дані.', english: 'She is analysing the data', level: 'B1' },
  { russian: 'Ми розробляємо новий продукт.', english: 'We are developing a new product', level: 'B2' },
  { russian: 'Він консультується з юристом.', english: 'He is consulting with a lawyer', level: 'B2' },
  { russian: 'Що відбувається на ринку?', english: 'What is happening in the market', level: 'B2' },
  { russian: 'Я зустрічаюсь з клієнтом о п\'ятій.', english: 'I am meeting with the client at five', level: 'B1' },
  { russian: 'Вона готує презентацію.', english: 'She is preparing a presentation', level: 'B1' },
  { russian: 'Вони обговорюють умови договору.', english: 'They are discussing the contract terms', level: 'B2' },
  { russian: 'Він очолює відділ з цього місяця.', english: 'He is leading the department this month', level: 'B2' },
  { russian: 'Ми працюємо над цим завданням вже тиждень.', english: 'We have been working on this task for a week already', level: 'B2' },
  { russian: 'Ти мене не чуєш?', english: 'Do you not hear me', level: 'A2' },
  { russian: 'Вона переїжджає до іншого міста.', english: 'She is moving to another city', level: 'B1' },
  { russian: 'Він приходить на роботу пізніше звичайного.', english: 'He is coming to work later than usual', level: 'B2' },
  { russian: 'Що вони обговорюють на нараді?', english: 'What are they discussing at the meeting', level: 'B2' },
  { russian: 'Я вивчаю нові технології.', english: 'I am learning new technologies', level: 'B1' },
  { russian: 'Компанія ще наймає співробітників.', english: 'The company is still hiring employees', level: 'B2' },
  { russian: 'Вони переглядають бюджет.', english: 'They are reviewing the budget', level: 'B2' },
  { russian: 'Вона працює дистанційно цього тижня.', english: 'She is working remotely this week', level: 'B1' },
  { russian: 'Я закінчую проект.', english: 'I am finishing the project', level: 'A2' },
  { russian: 'Він налагоджує зв\'язки з партнерами.', english: 'He is building relationships with partners', level: 'B2' },
  { russian: 'Ми переходимо на нову платформу.', english: 'We are switching to a new platform', level: 'B2' },
  { russian: 'Ти надсилаєш звіт?', english: 'Are you sending the report', level: 'A2' },
];

const L18_RU: any[] = [
  { russian: 'Открой дверь.', english: 'Open the door', level: 'A1' },
  { russian: 'Закрой окно.', english: 'Close the window', level: 'A1' },
  { russian: 'Сядь, пожалуйста.', english: 'Sit down please', level: 'A1' },
  { russian: 'Встань.', english: 'Stand up', level: 'A1' },
  { russian: 'Не шуми.', english: 'Do not make noise', level: 'A1' },
  { russian: 'Помоги мне.', english: 'Help me', level: 'A1' },
  { russian: 'Слушай внимательно.', english: 'Listen carefully', level: 'A1' },
  { russian: 'Не опаздывай.', english: 'Do not be late', level: 'A2' },
  { russian: 'Позвони мне.', english: 'Call me', level: 'A1' },
  { russian: 'Напиши мне.', english: 'Write to me', level: 'A1' },
  { russian: 'Не забудь документы.', english: 'Do not forget the documents', level: 'A2' },
  { russian: 'Приходи вовремя.', english: 'Come on time', level: 'A2' },
  { russian: 'Выключи телефон.', english: 'Turn off your phone', level: 'A2' },
  { russian: 'Не перебивай меня.', english: 'Do not interrupt me', level: 'A2' },
  { russian: 'Пожалуйста, говори медленнее.', english: 'Please speak more slowly', level: 'A2' },
  { russian: 'Повтори ещё раз.', english: 'Repeat it once more', level: 'A2' },
  { russian: 'Не говори так громко.', english: 'Do not speak so loudly', level: 'A2' },
  { russian: 'Объясни мне это.', english: 'Explain this to me', level: 'B1' },
  { russian: 'Подожди минуту.', english: 'Wait a minute', level: 'A1' },
  { russian: 'Не волнуйся.', english: 'Do not worry', level: 'A2' },
  { russian: 'Будь осторожен.', english: 'Be careful', level: 'A2' },
  { russian: 'Улыбнись.', english: 'Smile', level: 'A1' },
  { russian: 'Не сдавайся.', english: 'Do not give up', level: 'A2' },
  { russian: 'Сосредоточься.', english: 'Focus', level: 'B1' },
  { russian: 'Отправь мне файл.', english: 'Send me the file', level: 'A2' },
  { russian: 'Проверь свою электронную почту.', english: 'Check your email', level: 'A2' },
  { russian: 'Не трогай это.', english: 'Do not touch that', level: 'A1' },
  { russian: 'Скажи мне правду.', english: 'Tell me the truth', level: 'A2' },
  { russian: 'Не принимай поспешных решений.', english: 'Do not make hasty decisions', level: 'B1' },
  { russian: 'Будь вежлив с клиентами.', english: 'Be polite with clients', level: 'B1' },
  { russian: 'Прочитай внимательно перед подписью.', english: 'Read carefully before signing', level: 'B1' },
  { russian: 'Не откладывай на завтра.', english: 'Do not put it off until tomorrow', level: 'B1' },
  { russian: 'Сохрани файл.', english: 'Save the file', level: 'A2' },
  { russian: 'Перезапусти компьютер.', english: 'Restart the computer', level: 'A2' },
  { russian: 'Попроси о помощи, если нужно.', english: 'Ask for help if you need it', level: 'B1' },
  { russian: 'Не используй телефон на совещании.', english: 'Do not use your phone during the meeting', level: 'B1' },
  { russian: 'Сделай резервную копию данных.', english: 'Make a backup of the data', level: 'B1' },
  { russian: 'Проявляй инициативу.', english: 'Show initiative', level: 'B1' },
  { russian: 'Старайся изо всех сил.', english: 'Try your best', level: 'A2' },
  { russian: 'Не спорь с клиентом.', english: 'Do not argue with the client', level: 'B1' },
  { russian: 'Принеси мне отчёт к утру.', english: 'Bring me the report by morning', level: 'B1' },
  { russian: 'Уважай мнение других.', english: 'Respect the opinions of others', level: 'B1' },
  { russian: 'Не делай ошибок в документах.', english: 'Do not make mistakes in documents', level: 'B1' },
  { russian: 'Позаботься о деталях.', english: 'Take care of the details', level: 'B1' },
  { russian: 'Будь готов к вопросам.', english: 'Be ready for questions', level: 'B1' },
  { russian: 'Не молчи на совещании.', english: 'Do not stay silent at the meeting', level: 'B1' },
  { russian: 'Выражай свои мысли чётко.', english: 'Express your thoughts clearly', level: 'B1' },
  { russian: 'Не бойся задавать вопросы.', english: 'Do not be afraid to ask questions', level: 'A2' },
  { russian: 'Сделай это до пятницы.', english: 'Do it by Friday', level: 'A2' },
  { russian: 'Пожалуйста, подтверди получение.', english: 'Please confirm receipt', level: 'B1' },
];

const L18_UK: any[] = [
  { russian: 'Відчини двері.', english: 'Open the door', level: 'A1' },
  { russian: 'Зачини вікно.', english: 'Close the window', level: 'A1' },
  { russian: 'Сядь, будь ласка.', english: 'Sit down please', level: 'A1' },
  { russian: 'Встань.', english: 'Stand up', level: 'A1' },
  { russian: 'Не шуми.', english: 'Do not make noise', level: 'A1' },
  { russian: 'Допоможи мені.', english: 'Help me', level: 'A1' },
  { russian: 'Слухай уважно.', english: 'Listen carefully', level: 'A1' },
  { russian: 'Не запізнюйся.', english: 'Do not be late', level: 'A2' },
  { russian: 'Зателефонуй мені.', english: 'Call me', level: 'A1' },
  { russian: 'Напиши мені.', english: 'Write to me', level: 'A1' },
  { russian: 'Не забудь документи.', english: 'Do not forget the documents', level: 'A2' },
  { russian: 'Приходь вчасно.', english: 'Come on time', level: 'A2' },
  { russian: 'Вимкни телефон.', english: 'Turn off your phone', level: 'A2' },
  { russian: 'Не перебивай мене.', english: 'Do not interrupt me', level: 'A2' },
  { russian: 'Будь ласка, говори повільніше.', english: 'Please speak more slowly', level: 'A2' },
  { russian: 'Повтори ще раз.', english: 'Repeat it once more', level: 'A2' },
  { russian: 'Не говори так голосно.', english: 'Do not speak so loudly', level: 'A2' },
  { russian: 'Поясни мені це.', english: 'Explain this to me', level: 'B1' },
  { russian: 'Зачекай хвилину.', english: 'Wait a minute', level: 'A1' },
  { russian: 'Не хвилюйся.', english: 'Do not worry', level: 'A2' },
  { russian: 'Будь обережний.', english: 'Be careful', level: 'A2' },
  { russian: 'Посміхнись.', english: 'Smile', level: 'A1' },
  { russian: 'Не здавайся.', english: 'Do not give up', level: 'A2' },
  { russian: 'Зосередься.', english: 'Focus', level: 'B1' },
  { russian: 'Надішли мені файл.', english: 'Send me the file', level: 'A2' },
  { russian: 'Перевір свою електронну пошту.', english: 'Check your email', level: 'A2' },
  { russian: 'Не чіпай це.', english: 'Do not touch that', level: 'A1' },
  { russian: 'Скажи мені правду.', english: 'Tell me the truth', level: 'A2' },
  { russian: 'Не приймай поспішних рішень.', english: 'Do not make hasty decisions', level: 'B1' },
  { russian: 'Будь ввічливий з клієнтами.', english: 'Be polite with clients', level: 'B1' },
  { russian: 'Прочитай уважно перед підписом.', english: 'Read carefully before signing', level: 'B1' },
  { russian: 'Не відкладай на завтра.', english: 'Do not put it off until tomorrow', level: 'B1' },
  { russian: 'Збережи файл.', english: 'Save the file', level: 'A2' },
  { russian: 'Перезапусти комп\'ютер.', english: 'Restart the computer', level: 'A2' },
  { russian: 'Попроси допомоги, якщо потрібно.', english: 'Ask for help if you need it', level: 'B1' },
  { russian: 'Не використовуй телефон на нараді.', english: 'Do not use your phone during the meeting', level: 'B1' },
  { russian: 'Зроби резервну копію даних.', english: 'Make a backup of the data', level: 'B1' },
  { russian: 'Виявляй ініціативу.', english: 'Show initiative', level: 'B1' },
  { russian: 'Намагайся якнайкраще.', english: 'Try your best', level: 'A2' },
  { russian: 'Не сперечайся з клієнтом.', english: 'Do not argue with the client', level: 'B1' },
  { russian: 'Принеси мені звіт до ранку.', english: 'Bring me the report by morning', level: 'B1' },
  { russian: 'Поважай думку інших.', english: 'Respect the opinions of others', level: 'B1' },
  { russian: 'Не роби помилок у документах.', english: 'Do not make mistakes in documents', level: 'B1' },
  { russian: 'Подбай про деталі.', english: 'Take care of the details', level: 'B1' },
  { russian: 'Будь готовий до питань.', english: 'Be ready for questions', level: 'B1' },
  { russian: 'Не мовчи на нараді.', english: 'Do not stay silent at the meeting', level: 'B1' },
  { russian: 'Висловлюй свої думки чітко.', english: 'Express your thoughts clearly', level: 'B1' },
  { russian: 'Не бійся ставити питання.', english: 'Do not be afraid to ask questions', level: 'A2' },
  { russian: 'Зроби це до п\'ятниці.', english: 'Do it by Friday', level: 'A2' },
  { russian: 'Будь ласка, підтверди отримання.', english: 'Please confirm receipt', level: 'B1' },
];

const L19_RU: any[] = [
  { russian: 'Книга на столе.', english: 'The book is on the table', level: 'A1' },
  { russian: 'Кот под кроватью.', english: 'The cat is under the bed', level: 'A1' },
  { russian: 'Офис в центре города.', english: 'The office is in the city centre', level: 'A1' },
  { russian: 'Ключи на полке.', english: 'The keys are on the shelf', level: 'A1' },
  { russian: 'Я живу в Берлине.', english: 'I live in Berlin', level: 'A1' },
  { russian: 'Встреча в конференц-зале.', english: 'The meeting is in the conference room', level: 'A1' },
  { russian: 'Он сидит рядом со мной.', english: 'He is sitting next to me', level: 'A2' },
  { russian: 'Машина за зданием.', english: 'The car is behind the building', level: 'A2' },
  { russian: 'Банк между почтой и аптекой.', english: 'The bank is between the post office and the pharmacy', level: 'A2' },
  { russian: 'Телефон в ящике стола.', english: 'The phone is in the desk drawer', level: 'A1' },
  { russian: 'Она стоит перед входом.', english: 'She is standing in front of the entrance', level: 'A2' },
  { russian: 'Ноутбук на диване.', english: 'The laptop is on the sofa', level: 'A1' },
  { russian: 'Кофемашина рядом с холодильником.', english: 'The coffee machine is next to the fridge', level: 'A2' },
  { russian: 'Документы в папке.', english: 'The documents are in the folder', level: 'A1' },
  { russian: 'Он прячет ключ под ковриком.', english: 'He hides the key under the mat', level: 'A2' },
  { russian: 'Парковка за торговым центром.', english: 'The parking is behind the shopping centre', level: 'A2' },
  { russian: 'Ресторан между двумя магазинами.', english: 'The restaurant is between two shops', level: 'A2' },
  { russian: 'Я нашёл кошелёк под сиденьем.', english: 'I found the wallet under the seat', level: 'B1' },
  { russian: 'Выход находится в конце коридора.', english: 'The exit is at the end of the corridor', level: 'B1' },
  { russian: 'Сумка рядом с дверью.', english: 'The bag is next to the door', level: 'A1' },
  { russian: 'Пожалуйста, поставь коробку на полку.', english: 'Please put the box on the shelf', level: 'A2' },
  { russian: 'Провода под полом.', english: 'The wires are under the floor', level: 'B1' },
  { russian: 'Новый сотрудник сидит между мной и Анной.', english: 'The new employee is sitting between me and Anna', level: 'B1' },
  { russian: 'Переговорная находится напротив лифта.', english: 'The meeting room is opposite the lift', level: 'B1' },
  { russian: 'Положи папку в шкаф.', english: 'Put the folder in the cabinet', level: 'A2' },
  { russian: 'Гостиница в двух кварталах от вокзала.', english: 'The hotel is two blocks from the station', level: 'B1' },
  { russian: 'Доска объявлений над принтером.', english: 'The notice board is above the printer', level: 'B1' },
  { russian: 'Запасной выход за лестницей.', english: 'The emergency exit is behind the stairs', level: 'B1' },
  { russian: 'Кресло стоит напротив стола.', english: 'The armchair is opposite the desk', level: 'B1' },
  { russian: 'Он стоит у окна.', english: 'He is standing by the window', level: 'A2' },
  { russian: 'Все файлы хранятся в облаке.', english: 'All files are stored in the cloud', level: 'B1' },
  { russian: 'Кафе находится между двумя офисами.', english: 'The cafe is between the two offices', level: 'A2' },
  { russian: 'Я сижу напротив начальника.', english: 'I am sitting opposite my boss', level: 'A2' },
  { russian: 'Мусорное ведро рядом с дверью.', english: 'The bin is next to the door', level: 'A1' },
  { russian: 'Принтер стоит в углу комнаты.', english: 'The printer is in the corner of the room', level: 'A2' },
  { russian: 'Проектор висит над столом.', english: 'The projector is above the table', level: 'A2' },
  { russian: 'Склад за главным зданием.', english: 'The warehouse is behind the main building', level: 'B1' },
  { russian: 'Поставь телефон на зарядку.', english: 'Put the phone on charge', level: 'A2' },
  { russian: 'Наш офис на третьем этаже.', english: 'Our office is on the third floor', level: 'A2' },
  { russian: 'Гараж под домом.', english: 'The garage is under the house', level: 'A2' },
  { russian: 'Канцелярия рядом с лифтом.', english: 'The stationery room is next to the lift', level: 'B1' },
  { russian: 'Он спрятал конверт за картиной.', english: 'He hid the envelope behind the picture', level: 'B1' },
  { russian: 'Сейф находится в стене.', english: 'The safe is in the wall', level: 'B1' },
  { russian: 'Встреча проходит на первом этаже.', english: 'The meeting is taking place on the ground floor', level: 'B1' },
  { russian: 'Стул между столом и шкафом.', english: 'The chair is between the table and the cabinet', level: 'A2' },
  { russian: 'Подпись должна быть внизу страницы.', english: 'The signature must be at the bottom of the page', level: 'B1' },
  { russian: 'Расписание висит над рабочим столом.', english: 'The schedule is above the desk', level: 'A2' },
  { russian: 'Товары хранятся в холодильнике.', english: 'The goods are stored in the fridge', level: 'B1' },
  { russian: 'Туалет в конце коридора справа.', english: 'The bathroom is at the end of the corridor on the right', level: 'B1' },
  { russian: 'Офис находится напротив парка.', english: 'The office is opposite the park', level: 'A2' },
];

const L19_UK: any[] = [
  { russian: 'Книга на столі.', english: 'The book is on the table', level: 'A1' },
  { russian: 'Кіт під ліжком.', english: 'The cat is under the bed', level: 'A1' },
  { russian: 'Офіс у центрі міста.', english: 'The office is in the city centre', level: 'A1' },
  { russian: 'Ключі на полиці.', english: 'The keys are on the shelf', level: 'A1' },
  { russian: 'Я живу в Берліні.', english: 'I live in Berlin', level: 'A1' },
  { russian: 'Зустріч у конференц-залі.', english: 'The meeting is in the conference room', level: 'A1' },
  { russian: 'Він сидить поруч зі мною.', english: 'He is sitting next to me', level: 'A2' },
  { russian: 'Машина за будівлею.', english: 'The car is behind the building', level: 'A2' },
  { russian: 'Банк між поштою та аптекою.', english: 'The bank is between the post office and the pharmacy', level: 'A2' },
  { russian: 'Телефон у ящику столу.', english: 'The phone is in the desk drawer', level: 'A1' },
  { russian: 'Вона стоїть перед входом.', english: 'She is standing in front of the entrance', level: 'A2' },
  { russian: 'Ноутбук на дивані.', english: 'The laptop is on the sofa', level: 'A1' },
  { russian: 'Кавомашина поруч з холодильником.', english: 'The coffee machine is next to the fridge', level: 'A2' },
  { russian: 'Документи в папці.', english: 'The documents are in the folder', level: 'A1' },
  { russian: 'Він ховає ключ під килимком.', english: 'He hides the key under the mat', level: 'A2' },
  { russian: 'Парковка за торговим центром.', english: 'The parking is behind the shopping centre', level: 'A2' },
  { russian: 'Ресторан між двома магазинами.', english: 'The restaurant is between two shops', level: 'A2' },
  { russian: 'Я знайшов гаманець під сидінням.', english: 'I found the wallet under the seat', level: 'B1' },
  { russian: 'Вихід знаходиться в кінці коридору.', english: 'The exit is at the end of the corridor', level: 'B1' },
  { russian: 'Сумка поруч з дверима.', english: 'The bag is next to the door', level: 'A1' },
  { russian: 'Будь ласка, постав коробку на полицю.', english: 'Please put the box on the shelf', level: 'A2' },
  { russian: 'Проводи під підлогою.', english: 'The wires are under the floor', level: 'B1' },
  { russian: 'Новий співробітник сидить між мною та Анною.', english: 'The new employee is sitting between me and Anna', level: 'B1' },
  { russian: 'Переговорна знаходиться навпроти ліфта.', english: 'The meeting room is opposite the lift', level: 'B1' },
  { russian: 'Поклади папку в шафу.', english: 'Put the folder in the cabinet', level: 'A2' },
  { russian: 'Готель за два квартали від вокзалу.', english: 'The hotel is two blocks from the station', level: 'B1' },
  { russian: 'Дошка оголошень над принтером.', english: 'The notice board is above the printer', level: 'B1' },
  { russian: 'Запасний вихід за сходами.', english: 'The emergency exit is behind the stairs', level: 'B1' },
  { russian: 'Крісло стоїть навпроти столу.', english: 'The armchair is opposite the desk', level: 'B1' },
  { russian: 'Він стоїть біля вікна.', english: 'He is standing by the window', level: 'A2' },
  { russian: 'Всі файли зберігаються в хмарі.', english: 'All files are stored in the cloud', level: 'B1' },
  { russian: 'Кафе знаходиться між двома офісами.', english: 'The cafe is between the two offices', level: 'A2' },
  { russian: 'Я сиджу навпроти начальника.', english: 'I am sitting opposite my boss', level: 'A2' },
  { russian: 'Сміттєвий кошик поруч з дверима.', english: 'The bin is next to the door', level: 'A1' },
  { russian: 'Принтер стоїть у кутку кімнати.', english: 'The printer is in the corner of the room', level: 'A2' },
  { russian: 'Проектор висить над столом.', english: 'The projector is above the table', level: 'A2' },
  { russian: 'Склад за головною будівлею.', english: 'The warehouse is behind the main building', level: 'B1' },
  { russian: 'Постав телефон на зарядку.', english: 'Put the phone on charge', level: 'A2' },
  { russian: 'Наш офіс на третьому поверсі.', english: 'Our office is on the third floor', level: 'A2' },
  { russian: 'Гараж під будинком.', english: 'The garage is under the house', level: 'A2' },
  { russian: 'Канцелярія поруч з ліфтом.', english: 'The stationery room is next to the lift', level: 'B1' },
  { russian: 'Він сховав конверт за картиною.', english: 'He hid the envelope behind the picture', level: 'B1' },
  { russian: 'Сейф знаходиться в стіні.', english: 'The safe is in the wall', level: 'B1' },
  { russian: 'Зустріч проходить на першому поверсі.', english: 'The meeting is taking place on the ground floor', level: 'B1' },
  { russian: 'Стілець між столом і шафою.', english: 'The chair is between the table and the cabinet', level: 'A2' },
  { russian: 'Підпис має бути внизу сторінки.', english: 'The signature must be at the bottom of the page', level: 'B1' },
  { russian: 'Розклад висить над робочим столом.', english: 'The schedule is above the desk', level: 'A2' },
  { russian: 'Товари зберігаються в холодильнику.', english: 'The goods are stored in the fridge', level: 'B1' },
  { russian: 'Туалет в кінці коридору праворуч.', english: 'The bathroom is at the end of the corridor on the right', level: 'B1' },
  { russian: 'Офіс знаходиться навпроти парку.', english: 'The office is opposite the park', level: 'A2' },
];

const L20_RU: any[] = [
  { russian: 'Это книга.', english: 'It is a book', level: 'A2' },
  { russian: 'Это яблоко.', english: 'It is an apple', level: 'A2' },
  { russian: 'Передай мне соль.', english: 'Pass me the salt', level: 'A2' },
  { russian: 'У меня есть машина.', english: 'I have a car', level: 'A2' },
  { russian: 'Он живёт в большом доме.', english: 'He lives in a big house', level: 'A2' },
  { russian: 'Это лучший ресторан в городе.', english: 'It is the best restaurant in the city', level: 'B1' },
  { russian: 'Я купил новый телефон.', english: 'I bought a new phone', level: 'A2' },
  { russian: 'Она врач.', english: 'She is a doctor', level: 'A2' },
  { russian: 'Солнце светит ярко.', english: 'The sun is shining brightly', level: 'A2' },
  { russian: 'Мы видели слона в зоопарке.', english: 'We saw an elephant at the zoo', level: 'A2' },
  { russian: 'Он играет на гитаре.', english: 'He plays the guitar', level: 'B1' },
  { russian: 'Я читаю книгу, которую ты рекомендовал.', english: 'I am reading the book you recommended', level: 'B1' },
  { russian: 'Он студент университета.', english: 'He is a university student', level: 'A2' },
  { russian: 'Дай мне стакан воды.', english: 'Give me a glass of water', level: 'A2' },
  { russian: 'Луна красивая сегодня.', english: 'The moon is beautiful tonight', level: 'A2' },
  { russian: 'Я хочу стать инженером.', english: 'I want to become an engineer', level: 'B1' },
  { russian: 'Это самая высокая гора в мире.', english: 'It is the highest mountain in the world', level: 'B1' },
  { russian: 'Кофе — мой любимый напиток.', english: 'Coffee is my favourite drink', level: 'B1' },
  { russian: 'У нас в офисе есть принтер.', english: 'We have a printer in the office', level: 'A2' },
  { russian: 'Это отличная идея.', english: 'It is an excellent idea', level: 'A2' },
  { russian: 'Он первый в своём классе.', english: 'He is the first in his class', level: 'B1' },
  { russian: 'Я хожу в спортзал каждый день.', english: 'I go to the gym every day', level: 'B1' },
  { russian: 'Это старый замок.', english: 'It is an old castle', level: 'A2' },
  { russian: 'Небо голубое.', english: 'The sky is blue', level: 'A2' },
  { russian: 'Она изучает экономику.', english: 'She studies economics', level: 'B1' },
  { russian: 'Это был важный урок.', english: 'It was an important lesson', level: 'B1' },
  { russian: 'Он играет на фортепиано очень хорошо.', english: 'He plays the piano very well', level: 'B1' },
  { russian: 'Мы поехали на море.', english: 'We went to the sea', level: 'B1' },
  { russian: 'Это самый сложный экзамен.', english: 'It is the most difficult exam', level: 'B1' },
  { russian: 'Дети любят мороженое.', english: 'Children love ice cream', level: 'B1' },
  { russian: 'Я ищу работу.', english: 'I am looking for a job', level: 'A2' },
  { russian: 'Это уникальная возможность.', english: 'It is a unique opportunity', level: 'B1' },
  { russian: 'Отчёт на столе.', english: 'The report is on the table', level: 'A2' },
  { russian: 'Она пришла на час раньше.', english: 'She came an hour early', level: 'B1' },
  { russian: 'Это была честная ошибка.', english: 'It was an honest mistake', level: 'B1' },
  { russian: 'Он встал последним.', english: 'He was the last to stand up', level: 'B2' },
  { russian: 'Это не проблема.', english: 'It is not a problem', level: 'A2' },
  { russian: 'Президент страны выступил с речью.', english: 'The president of the country gave a speech', level: 'B2' },
  { russian: 'Вода закипела.', english: 'The water has boiled', level: 'B1' },
  { russian: 'Это был самый длинный день в году.', english: 'It was the longest day of the year', level: 'B2' },
  { russian: 'Он прибыл на час позже.', english: 'He arrived an hour late', level: 'B1' },
  { russian: 'Жизнь прекрасна.', english: 'Life is beautiful', level: 'B1' },
  { russian: 'Это не тот файл.', english: 'It is not the right file', level: 'B1' },
  { russian: 'Он играет в футбол.', english: 'He plays football', level: 'B1' },
  { russian: 'Это была неожиданная новость.', english: 'It was an unexpected piece of news', level: 'B2' },
  { russian: 'Земля вращается вокруг Солнца.', english: 'The Earth revolves around the Sun', level: 'B2' },
  { russian: 'Она окончила университет.', english: 'She graduated from university', level: 'B1' },
  { russian: 'Он самый опытный менеджер в команде.', english: 'He is the most experienced manager in the team', level: 'B2' },
  { russian: 'Я хочу выпить чашку кофе.', english: 'I want to have a cup of coffee', level: 'A2' },
  { russian: 'Это было правильное решение.', english: 'It was the right decision', level: 'B2' },
];

const L20_UK: any[] = [
  { russian: 'Це книга.', english: 'It is a book', level: 'A2' },
  { russian: 'Це яблуко.', english: 'It is an apple', level: 'A2' },
  { russian: 'Передай мені сіль.', english: 'Pass me the salt', level: 'A2' },
  { russian: 'У мене є машина.', english: 'I have a car', level: 'A2' },
  { russian: 'Він живе у великому будинку.', english: 'He lives in a big house', level: 'A2' },
  { russian: 'Це найкращий ресторан у місті.', english: 'It is the best restaurant in the city', level: 'B1' },
  { russian: 'Я купив новий телефон.', english: 'I bought a new phone', level: 'A2' },
  { russian: 'Вона лікар.', english: 'She is a doctor', level: 'A2' },
  { russian: 'Сонце яскраво світить.', english: 'The sun is shining brightly', level: 'A2' },
  { russian: 'Ми бачили слона в зоопарку.', english: 'We saw an elephant at the zoo', level: 'A2' },
  { russian: 'Він грає на гітарі.', english: 'He plays the guitar', level: 'B1' },
  { russian: 'Я читаю книгу, яку ти порекомендував.', english: 'I am reading the book you recommended', level: 'B1' },
  { russian: 'Він студент університету.', english: 'He is a university student', level: 'A2' },
  { russian: 'Дай мені склянку води.', english: 'Give me a glass of water', level: 'A2' },
  { russian: 'Місяць сьогодні красивий.', english: 'The moon is beautiful tonight', level: 'A2' },
  { russian: 'Я хочу стати інженером.', english: 'I want to become an engineer', level: 'B1' },
  { russian: 'Це найвища гора у світі.', english: 'It is the highest mountain in the world', level: 'B1' },
  { russian: 'Кава — мій улюблений напій.', english: 'Coffee is my favourite drink', level: 'B1' },
  { russian: 'У нас в офісі є принтер.', english: 'We have a printer in the office', level: 'A2' },
  { russian: 'Це чудова ідея.', english: 'It is an excellent idea', level: 'A2' },
  { russian: 'Він перший у своєму класі.', english: 'He is the first in his class', level: 'B1' },
  { russian: 'Я ходжу до спортзалу щодня.', english: 'I go to the gym every day', level: 'B1' },
  { russian: 'Це старий замок.', english: 'It is an old castle', level: 'A2' },
  { russian: 'Небо блакитне.', english: 'The sky is blue', level: 'A2' },
  { russian: 'Вона вивчає економіку.', english: 'She studies economics', level: 'B1' },
  { russian: 'Це був важливий урок.', english: 'It was an important lesson', level: 'B1' },
  { russian: 'Він грає на фортепіано дуже добре.', english: 'He plays the piano very well', level: 'B1' },
  { russian: 'Ми поїхали на море.', english: 'We went to the sea', level: 'B1' },
  { russian: 'Це найскладніший іспит.', english: 'It is the most difficult exam', level: 'B1' },
  { russian: 'Діти люблять морозиво.', english: 'Children love ice cream', level: 'B1' },
  { russian: 'Я шукаю роботу.', english: 'I am looking for a job', level: 'A2' },
  { russian: 'Це унікальна можливість.', english: 'It is a unique opportunity', level: 'B1' },
  { russian: 'Звіт на столі.', english: 'The report is on the table', level: 'A2' },
  { russian: 'Вона прийшла на годину раніше.', english: 'She came an hour early', level: 'B1' },
  { russian: 'Це була чесна помилка.', english: 'It was an honest mistake', level: 'B1' },
  { russian: 'Він встав останнім.', english: 'He was the last to stand up', level: 'B2' },
  { russian: 'Це не проблема.', english: 'It is not a problem', level: 'A2' },
  { russian: 'Президент країни виступив з промовою.', english: 'The president of the country gave a speech', level: 'B2' },
  { russian: 'Вода закипіла.', english: 'The water has boiled', level: 'B1' },
  { russian: 'Це був найдовший день у році.', english: 'It was the longest day of the year', level: 'B2' },
  { russian: 'Він прибув на годину пізніше.', english: 'He arrived an hour late', level: 'B1' },
  { russian: 'Життя прекрасне.', english: 'Life is beautiful', level: 'B1' },
  { russian: 'Це не той файл.', english: 'It is not the right file', level: 'B1' },
  { russian: 'Він грає у футбол.', english: 'He plays football', level: 'B1' },
  { russian: 'Це була несподівана новина.', english: 'It was an unexpected piece of news', level: 'B2' },
  { russian: 'Земля обертається навколо Сонця.', english: 'The Earth revolves around the Sun', level: 'B2' },
  { russian: 'Вона закінчила університет.', english: 'She graduated from university', level: 'B1' },
  { russian: 'Він найдосвідченіший менеджер у команді.', english: 'He is the most experienced manager in the team', level: 'B2' },
  { russian: 'Я хочу випити чашку кави.', english: 'I want to have a cup of coffee', level: 'A2' },
  { russian: 'Це було правильне рішення.', english: 'It was the right decision', level: 'B2' },
];

const L21_RU: any[] = [
  { russian: 'У меня есть что-то для тебя.', english: 'I have something for you', level: 'B1' },
  { russian: 'У тебя есть что-нибудь поесть?', english: 'Do you have anything to eat', level: 'B1' },
  { russian: 'Ничего страшного.', english: 'Nothing is wrong', level: 'B1' },
  { russian: 'Всё готово.', english: 'Everything is ready', level: 'B1' },
  { russian: 'Кто-то стучит в дверь.', english: 'Someone is knocking at the door', level: 'B1' },
  { russian: 'Никто не знает ответа.', english: 'Nobody knows the answer', level: 'B1' },
  { russian: 'Каждый должен знать это правило.', english: 'Everyone must know this rule', level: 'B1' },
  { russian: 'Ты где-нибудь видел мои ключи?', english: 'Have you seen my keys anywhere', level: 'B1' },
  { russian: 'Нигде не могу найти документ.', english: 'I cannot find the document anywhere', level: 'B1' },
  { russian: 'Везде есть камеры видеонаблюдения.', english: 'There are cameras everywhere', level: 'B1' },
  { russian: 'Кто-то использовал мой компьютер.', english: 'Someone used my computer', level: 'B1' },
  { russian: 'Никто не ответил на мой вопрос.', english: 'Nobody answered my question', level: 'B1' },
  { russian: 'Есть ли кто-нибудь в комнате?', english: 'Is there anyone in the room', level: 'B1' },
  { russian: 'Мне нужно что-то сказать тебе.', english: 'I need to tell you something', level: 'B1' },
  { russian: 'Всё, что он говорит, правда.', english: 'Everything he says is true', level: 'B2' },
  { russian: 'Ничто не меняется.', english: 'Nothing ever changes', level: 'B1' },
  { russian: 'Везде одинаковые правила.', english: 'The rules are the same everywhere', level: 'B2' },
  { russian: 'Кто-нибудь видел отчёт?', english: 'Has anyone seen the report', level: 'B1' },
  { russian: 'Каждый согласен с планом.', english: 'Everyone agrees with the plan', level: 'B1' },
  { russian: 'Нигде нет свободных мест.', english: 'There are no free seats anywhere', level: 'B2' },
  { russian: 'Что-то пошло не так.', english: 'Something went wrong', level: 'B1' },
  { russian: 'Никто не виноват.', english: 'Nobody is to blame', level: 'B1' },
  { russian: 'Есть кто-нибудь, кто может помочь?', english: 'Is there anyone who can help', level: 'B2' },
  { russian: 'Всё зависит от тебя.', english: 'Everything depends on you', level: 'B2' },
  { russian: 'Где-то в офисе есть запасная ручка.', english: 'There is a spare pen somewhere in the office', level: 'B2' },
  { russian: 'Ничего не изменилось после встречи.', english: 'Nothing changed after the meeting', level: 'B2' },
  { russian: 'Кто-то должен взять на себя ответственность.', english: 'Someone has to take responsibility', level: 'B2' },
  { russian: 'Где-то я видел этот документ.', english: 'I saw that document somewhere', level: 'B2' },
  { russian: 'Всё, что ты сделал, было правильно.', english: 'Everything you did was correct', level: 'B2' },
  { russian: 'Нигде нет такого качества обслуживания.', english: 'There is no such quality of service anywhere', level: 'B2' },
  { russian: 'Кто-нибудь может объяснить это?', english: 'Can anyone explain this', level: 'B1' },
  { russian: 'Ничего особенного не произошло.', english: 'Nothing special happened', level: 'B1' },
  { russian: 'Везде написано одно и то же.', english: 'It says the same thing everywhere', level: 'B2' },
  { russian: 'Кто-то оставил сумку у входа.', english: 'Someone left a bag at the entrance', level: 'B1' },
  { russian: 'Каждый имеет право на мнение.', english: 'Everyone has the right to an opinion', level: 'B2' },
  { russian: 'Что-нибудь случилось?', english: 'Did anything happen', level: 'B1' },
  { russian: 'Никто не предупредил меня об этом.', english: 'Nobody warned me about this', level: 'B2' },
  { russian: 'Есть что-то, что меня беспокоит.', english: 'There is something that worries me', level: 'B2' },
  { russian: 'Всё на месте.', english: 'Everything is in place', level: 'B1' },
  { russian: 'Где-нибудь есть кафе рядом?', english: 'Is there a cafe anywhere nearby', level: 'B1' },
  { russian: 'Ничто не сравнится с домашней едой.', english: 'Nothing compares to home cooking', level: 'B2' },
  { russian: 'Кто-нибудь читал этот договор?', english: 'Has anyone read this contract', level: 'B2' },
  { russian: 'Везде слышна музыка.', english: 'There is music everywhere', level: 'B1' },
  { russian: 'Что-то мне подсказывает, что это неправда.', english: 'Something tells me this is not true', level: 'B2' },
  { russian: 'Никто не понимает, что происходит.', english: 'Nobody understands what is happening', level: 'B2' },
  { russian: 'Каждый сделал всё возможное.', english: 'Everyone did everything possible', level: 'B2' },
  { russian: 'Нигде нет стоянки.', english: 'There is no parking anywhere', level: 'B1' },
  { russian: 'Что-то изменилось в его поведении.', english: 'Something changed in his behaviour', level: 'B2' },
  { russian: 'Есть кто-нибудь дома?', english: 'Is there anyone home', level: 'B1' },
  { russian: 'Все детали важны.', english: 'Every detail matters', level: 'B2' },
];

const L21_UK: any[] = [
  { russian: 'У мене є щось для тебе.', english: 'I have something for you', level: 'B1' },
  { russian: 'У тебе є щось поїсти?', english: 'Do you have anything to eat', level: 'B1' },
  { russian: 'Нічого страшного.', english: 'Nothing is wrong', level: 'B1' },
  { russian: 'Все готово.', english: 'Everything is ready', level: 'B1' },
  { russian: 'Хтось стукає в двері.', english: 'Someone is knocking at the door', level: 'B1' },
  { russian: 'Ніхто не знає відповіді.', english: 'Nobody knows the answer', level: 'B1' },
  { russian: 'Кожен повинен знати це правило.', english: 'Everyone must know this rule', level: 'B1' },
  { russian: 'Ти десь бачив мої ключі?', english: 'Have you seen my keys anywhere', level: 'B1' },
  { russian: 'Ніде не можу знайти документ.', english: 'I cannot find the document anywhere', level: 'B1' },
  { russian: 'Скрізь є камери відеоспостереження.', english: 'There are cameras everywhere', level: 'B1' },
  { russian: 'Хтось використовував мій комп\'ютер.', english: 'Someone used my computer', level: 'B1' },
  { russian: 'Ніхто не відповів на моє запитання.', english: 'Nobody answered my question', level: 'B1' },
  { russian: 'Чи є хтось у кімнаті?', english: 'Is there anyone in the room', level: 'B1' },
  { russian: 'Мені потрібно щось тобі сказати.', english: 'I need to tell you something', level: 'B1' },
  { russian: 'Все, що він каже, правда.', english: 'Everything he says is true', level: 'B2' },
  { russian: 'Нічого не змінюється.', english: 'Nothing ever changes', level: 'B1' },
  { russian: 'Скрізь однакові правила.', english: 'The rules are the same everywhere', level: 'B2' },
  { russian: 'Хтось бачив звіт?', english: 'Has anyone seen the report', level: 'B1' },
  { russian: 'Кожен згоден з планом.', english: 'Everyone agrees with the plan', level: 'B1' },
  { russian: 'Ніде немає вільних місць.', english: 'There are no free seats anywhere', level: 'B2' },
  { russian: 'Щось пішло не так.', english: 'Something went wrong', level: 'B1' },
  { russian: 'Ніхто не винен.', english: 'Nobody is to blame', level: 'B1' },
  { russian: 'Чи є хтось, хто може допомогти?', english: 'Is there anyone who can help', level: 'B2' },
  { russian: 'Все залежить від тебе.', english: 'Everything depends on you', level: 'B2' },
  { russian: 'Десь в офісі є запасна ручка.', english: 'There is a spare pen somewhere in the office', level: 'B2' },
  { russian: 'Нічого не змінилося після зустрічі.', english: 'Nothing changed after the meeting', level: 'B2' },
  { russian: 'Хтось повинен взяти на себе відповідальність.', english: 'Someone has to take responsibility', level: 'B2' },
  { russian: 'Десь я бачив цей документ.', english: 'I saw that document somewhere', level: 'B2' },
  { russian: 'Все, що ти зробив, було правильно.', english: 'Everything you did was correct', level: 'B2' },
  { russian: 'Ніде немає такої якості обслуговування.', english: 'There is no such quality of service anywhere', level: 'B2' },
  { russian: 'Хтось може пояснити це?', english: 'Can anyone explain this', level: 'B1' },
  { russian: 'Нічого особливого не сталося.', english: 'Nothing special happened', level: 'B1' },
  { russian: 'Скрізь написано одне й те саме.', english: 'It says the same thing everywhere', level: 'B2' },
  { russian: 'Хтось залишив сумку біля входу.', english: 'Someone left a bag at the entrance', level: 'B1' },
  { russian: 'Кожен має право на думку.', english: 'Everyone has the right to an opinion', level: 'B2' },
  { russian: 'Щось трапилось?', english: 'Did anything happen', level: 'B1' },
  { russian: 'Ніхто не попередив мене про це.', english: 'Nobody warned me about this', level: 'B2' },
  { russian: 'Є щось, що мене турбує.', english: 'There is something that worries me', level: 'B2' },
  { russian: 'Всі документи на місці.', english: 'Everything is in place', level: 'B1' },
  { russian: 'Чи є десь поруч кафе?', english: 'Is there a cafe anywhere nearby', level: 'B1' },
  { russian: 'Ніщо не зрівняється з домашньою їжею.', english: 'Nothing compares to home cooking', level: 'B2' },
  { russian: 'Хтось читав цей договір?', english: 'Has anyone read this contract', level: 'B2' },
  { russian: 'Скрізь чути музику.', english: 'There is music everywhere', level: 'B1' },
  { russian: 'Щось мені підказує, що це неправда.', english: 'Something tells me this is not true', level: 'B2' },
  { russian: 'Ніхто не розуміє, що відбувається.', english: 'Nobody understands what is happening', level: 'B2' },
  { russian: 'Кожен зробив все можливе.', english: 'Everyone did everything possible', level: 'B2' },
  { russian: 'Ніде немає паркування.', english: 'There is no parking anywhere', level: 'B1' },
  { russian: 'Щось змінилося в його поведінці.', english: 'Something changed in his behaviour', level: 'B2' },
  { russian: 'Є хтось вдома?', english: 'Is there anyone home', level: 'B1' },
  { russian: 'Кожна деталь важлива.', english: 'Every detail matters', level: 'B2' },
];

const L22_RU: any[] = [
  { russian: 'Я обожаю читать книги.', english: 'I enjoy reading books', level: 'B1' },
  { russian: 'Она бросила курить.', english: 'She stopped smoking', level: 'B1' },
  { russian: 'Он избегает принимать решения.', english: 'He avoids making decisions', level: 'B1' },
  { russian: 'Мы рассмотрели возможность переезда.', english: 'We considered moving', level: 'B1' },
  { russian: 'Я не могу перестать думать об этом.', english: 'I cannot stop thinking about it', level: 'B1' },
  { russian: 'Она предложила встретиться позже.', english: 'She suggested meeting later', level: 'B2' },
  { russian: 'Он закончил писать отчёт.', english: 'He finished writing the report', level: 'B1' },
  { russian: 'Я ненавижу ждать.', english: 'I hate waiting', level: 'B1' },
  { russian: 'Плавание — хорошее упражнение.', english: 'Swimming is good exercise', level: 'B1' },
  { russian: 'Она отрицала кражу документов.', english: 'She denied stealing the documents', level: 'B2' },
  { russian: 'Он продолжал говорить, несмотря на шум.', english: 'He kept talking despite the noise', level: 'B2' },
  { russian: 'Я думаю о том, чтобы сменить работу.', english: 'I am thinking about changing jobs', level: 'B1' },
  { russian: 'Они отложили проведение встречи.', english: 'They postponed the meeting', level: 'B2' },
  { russian: 'Курение вредно для здоровья.', english: 'Smoking is bad for your health', level: 'B1' },
  { russian: 'Он рискует опоздать.', english: 'He risks being late', level: 'B2' },
  { russian: 'Мне нравится готовить.', english: 'I like cooking', level: 'B1' },
  { russian: 'Она практикует игру на пианино каждый день.', english: 'She practises playing the piano every day', level: 'B1' },
  { russian: 'Я не возражаю против ожидания.', english: 'I do not mind waiting', level: 'B1' },
  { russian: 'Путешествие — это её страсть.', english: 'Travelling is her passion', level: 'B1' },
  { russian: 'Они избежали потери важных данных.', english: 'They avoided losing important data', level: 'B2' },
  { russian: 'Он представил себе успешное завершение проекта.', english: 'He imagined completing the project successfully', level: 'B2' },
  { russian: 'Я признал ошибку.', english: 'I admitted making a mistake', level: 'B2' },
  { russian: 'Она не может вынести опозданий.', english: 'She cannot stand being late', level: 'B2' },
  { russian: 'Обучение новым навыкам требует времени.', english: 'Learning new skills takes time', level: 'B2' },
  { russian: 'Он отрицал участие в этом деле.', english: 'He denied being involved in the matter', level: 'B2' },
  { russian: 'Я устал слышать одно и то же.', english: 'I am tired of hearing the same thing', level: 'B2' },
  { russian: 'Решение проблемы требует усилий.', english: 'Solving the problem requires effort', level: 'B2' },
  { russian: 'Она наслаждается работой в команде.', english: 'She enjoys working in a team', level: 'B1' },
  { russian: 'Мы избегаем конфликтов.', english: 'We avoid conflicts', level: 'B1' },
  { russian: 'Он продолжал повторять одни и те же ошибки.', english: 'He kept repeating the same mistakes', level: 'B2' },
  { russian: 'Написание резюме — важный навык.', english: 'Writing a CV is an important skill', level: 'B2' },
  { russian: 'Я планирую начать собственный бизнес.', english: 'I am planning on starting my own business', level: 'B2' },
  { russian: 'Она боится выступать публично.', english: 'She is afraid of speaking in public', level: 'B2' },
  { russian: 'Я с нетерпением жду путешествия.', english: 'I look forward to travelling', level: 'B2' },
  { russian: 'Он предпочитает работать один.', english: 'He prefers working alone', level: 'B1' },
  { russian: 'Это стоит попробовать.', english: 'It is worth trying', level: 'B2' },
  { russian: 'Встреча была отложена из-за болезни директора.', english: 'The meeting was postponed due to the director being ill', level: 'C1' },
  { russian: 'Она устала ждать повышения.', english: 'She is tired of waiting for a promotion', level: 'B2' },
  { russian: 'Нет смысла торопиться.', english: 'There is no point in rushing', level: 'B2' },
  { russian: 'Он наслаждается вызовами на работе.', english: 'He enjoys being challenged at work', level: 'C1' },
  { russian: 'Согласование договора заняло время.', english: 'Negotiating the contract took time', level: 'C1' },
  { russian: 'Избегание трудных разговоров не решает проблем.', english: 'Avoiding difficult conversations does not solve problems', level: 'C1' },
  { russian: 'Она настаивала на повторной проверке.', english: 'She insisted on reviewing it again', level: 'C1' },
  { russian: 'Он не привык к руководству командой.', english: 'He is not used to managing a team', level: 'C1' },
  { russian: 'Мы считали наём новых сотрудников приоритетом.', english: 'We prioritised hiring new staff', level: 'C1' },
  { russian: 'Её критиковали за нарушение сроков.', english: 'She was criticised for missing deadlines', level: 'C1' },
  { russian: 'Ему удалось убедить совет.', english: 'He succeeded in convincing the board', level: 'C1' },
  { russian: 'Мы избегаем найма неопытных людей.', english: 'We avoid hiring inexperienced people', level: 'C1' },
  { russian: 'Я привык вставать рано.', english: 'I am used to waking up early', level: 'B2' },
  { russian: 'Стоит ли рисковать?', english: 'Is it worth taking the risk', level: 'B2' },
];

const L22_UK: any[] = [
  { russian: 'Я обожнюю читати книги.', english: 'I enjoy reading books', level: 'B1' },
  { russian: 'Вона кинула курити.', english: 'She stopped smoking', level: 'B1' },
  { russian: 'Він уникає приймати рішення.', english: 'He avoids making decisions', level: 'B1' },
  { russian: 'Ми розглянули можливість переїзду.', english: 'We considered moving', level: 'B1' },
  { russian: 'Я не можу перестати думати про це.', english: 'I cannot stop thinking about it', level: 'B1' },
  { russian: 'Вона запропонувала зустрітися пізніше.', english: 'She suggested meeting later', level: 'B2' },
  { russian: 'Він закінчив писати звіт.', english: 'He finished writing the report', level: 'B1' },
  { russian: 'Я ненавиджу чекати.', english: 'I hate waiting', level: 'B1' },
  { russian: 'Плавання — гарна вправа.', english: 'Swimming is good exercise', level: 'B1' },
  { russian: 'Вона заперечувала крадіжку документів.', english: 'She denied stealing the documents', level: 'B2' },
  { russian: 'Він продовжував говорити, попри шум.', english: 'He kept talking despite the noise', level: 'B2' },
  { russian: 'Я думаю про зміну роботи.', english: 'I am thinking about changing jobs', level: 'B1' },
  { russian: 'Вони відклали проведення зустрічі.', english: 'They postponed the meeting', level: 'B2' },
  { russian: 'Куріння шкідливе для здоров\'я.', english: 'Smoking is bad for your health', level: 'B1' },
  { russian: 'Він ризикує запізнитися.', english: 'He risks being late', level: 'B2' },
  { russian: 'Мені подобається готувати.', english: 'I like cooking', level: 'B1' },
  { russian: 'Вона щодня практикує гру на фортепіано.', english: 'She practises playing the piano every day', level: 'B1' },
  { russian: 'Я не проти почекати.', english: 'I do not mind waiting', level: 'B1' },
  { russian: 'Подорожі — це її пристрасть.', english: 'Travelling is her passion', level: 'B1' },
  { russian: 'Вони уникнули втрати важливих даних.', english: 'They avoided losing important data', level: 'B2' },
  { russian: 'Він уявив успішне завершення проекту.', english: 'He imagined completing the project successfully', level: 'B2' },
  { russian: 'Я визнав помилку.', english: 'I admitted making a mistake', level: 'B2' },
  { russian: 'Вона не може терпіти запізнень.', english: 'She cannot stand being late', level: 'B2' },
  { russian: 'Навчання новим навичкам вимагає часу.', english: 'Learning new skills takes time', level: 'B2' },
  { russian: 'Він заперечував участь у цій справі.', english: 'He denied being involved in the matter', level: 'B2' },
  { russian: 'Я втомився чути одне й те саме.', english: 'I am tired of hearing the same thing', level: 'B2' },
  { russian: 'Вирішення проблеми вимагає зусиль.', english: 'Solving the problem requires effort', level: 'B2' },
  { russian: 'Вона насолоджується роботою в команді.', english: 'She enjoys working in a team', level: 'B1' },
  { russian: 'Ми уникаємо конфліктів.', english: 'We avoid conflicts', level: 'B1' },
  { russian: 'Він продовжував повторювати ті самі помилки.', english: 'He kept repeating the same mistakes', level: 'B2' },
  { russian: 'Написання резюме — важлива навичка.', english: 'Writing a CV is an important skill', level: 'B2' },
  { russian: 'Я планую відкрити власний бізнес.', english: 'I am planning on starting my own business', level: 'B2' },
  { russian: 'Вона боїться публічних виступів.', english: 'She is afraid of speaking in public', level: 'B2' },
  { russian: 'Я з нетерпінням чекаю подорожі.', english: 'I look forward to travelling', level: 'B2' },
  { russian: 'Він надає перевагу роботі наодинці.', english: 'He prefers working alone', level: 'B1' },
  { russian: 'Це варто спробувати.', english: 'It is worth trying', level: 'B2' },
  { russian: 'Зустріч була відкладена через хворобу директора.', english: 'The meeting was postponed due to the director being ill', level: 'C1' },
  { russian: 'Вона втомилася чекати підвищення.', english: 'She is tired of waiting for a promotion', level: 'B2' },
  { russian: 'Немає сенсу поспішати.', english: 'There is no point in rushing', level: 'B2' },
  { russian: 'Він насолоджується викликами на роботі.', english: 'He enjoys being challenged at work', level: 'C1' },
  { russian: 'Погодження договору зайняло час.', english: 'Negotiating the contract took time', level: 'C1' },
  { russian: 'Уникання складних розмов не вирішує проблем.', english: 'Avoiding difficult conversations does not solve problems', level: 'C1' },
  { russian: 'Вона наполягала на повторній перевірці.', english: 'She insisted on reviewing it again', level: 'C1' },
  { russian: 'Він не звик керувати командою.', english: 'He is not used to managing a team', level: 'C1' },
  { russian: 'Ми вважали найм нових співробітників пріоритетом.', english: 'We prioritised hiring new staff', level: 'C1' },
  { russian: 'Її критикували за порушення термінів.', english: 'She was criticised for missing deadlines', level: 'C1' },
  { russian: 'Йому вдалося переконати раду.', english: 'He succeeded in convincing the board', level: 'C1' },
  { russian: 'Ми уникаємо найму недосвідчених людей.', english: 'We avoid hiring inexperienced people', level: 'C1' },
  { russian: 'Я звик рано вставати.', english: 'I am used to waking up early', level: 'B2' },
  { russian: 'Чи варто ризикувати?', english: 'Is it worth taking the risk', level: 'B2' },
];

const L23_RU: any[] = [
  { russian: 'Документ был подписан вчера.', english: 'The document was signed yesterday', level: 'B1' },
  { russian: 'Письмо отправляется каждый день.', english: 'The letter is sent every day', level: 'B1' },
  { russian: 'Отчёт был написан командой.', english: 'The report was written by the team', level: 'B1' },
  { russian: 'Этот мост был построен в 1990 году.', english: 'This bridge was built in 1990', level: 'B1' },
  { russian: 'Посылка была доставлена утром.', english: 'The parcel was delivered in the morning', level: 'B1' },
  { russian: 'Все ошибки были исправлены.', english: 'All the mistakes were corrected', level: 'B1' },
  { russian: 'Продукт будет выпущен в следующем году.', english: 'The product will be released next year', level: 'B1' },
  { russian: 'Эти правила должны соблюдаться.', english: 'These rules must be followed', level: 'B2' },
  { russian: 'Письмо было написано на английском.', english: 'The letter was written in English', level: 'B1' },
  { russian: 'Деньги были переведены на счёт.', english: 'The money was transferred to the account', level: 'B2' },
  { russian: 'Его пригласили на конференцию.', english: 'He was invited to the conference', level: 'B1' },
  { russian: 'Эта книга была написана в прошлом веке.', english: 'This book was written in the last century', level: 'B2' },
  { russian: 'Все участники были уведомлены.', english: 'All participants were notified', level: 'B2' },
  { russian: 'Контракт будет подписан завтра.', english: 'The contract will be signed tomorrow', level: 'B1' },
  { russian: 'Офис был отремонтирован.', english: 'The office was renovated', level: 'B1' },
  { russian: 'Его работа была высоко оценена.', english: 'His work was highly appreciated', level: 'B2' },
  { russian: 'Вопрос ещё не был рассмотрен.', english: 'The issue has not been addressed yet', level: 'B2' },
  { russian: 'Это решение было принято советом директоров.', english: 'This decision was made by the board of directors', level: 'B2' },
  { russian: 'Данные были зашифрованы.', english: 'The data was encrypted', level: 'B2' },
  { russian: 'Новый закон был принят в прошлом году.', english: 'The new law was passed last year', level: 'B2' },
  { russian: 'Ошибка была обнаружена слишком поздно.', english: 'The mistake was discovered too late', level: 'B2' },
  { russian: 'Инструкции должны быть выполнены точно.', english: 'The instructions must be followed exactly', level: 'B2' },
  { russian: 'Встреча была отменена.', english: 'The meeting was cancelled', level: 'B1' },
  { russian: 'Ему было поручено возглавить проект.', english: 'He was assigned to lead the project', level: 'B2' },
  { russian: 'Все расходы будут возмещены.', english: 'All expenses will be reimbursed', level: 'B2' },
  { russian: 'Эта проблема уже была решена.', english: 'This problem has already been solved', level: 'B2' },
  { russian: 'Новая система была внедрена успешно.', english: 'The new system was implemented successfully', level: 'B2' },
  { russian: 'Результаты будут объявлены на следующей неделе.', english: 'The results will be announced next week', level: 'B2' },
  { russian: 'Задание должно быть выполнено к пятнице.', english: 'The task must be completed by Friday', level: 'B2' },
  { russian: 'Его заявка была отклонена.', english: 'His application was rejected', level: 'B2' },
  { russian: 'Обвинение было снято.', english: 'The accusation was dropped', level: 'C1' },
  { russian: 'Этот вопрос был передан в суд.', english: 'The matter was referred to court', level: 'C1' },
  { russian: 'Сделка была заключена после долгих переговоров.', english: 'The deal was concluded after lengthy negotiations', level: 'C1' },
  { russian: 'Бюджет был пересмотрен дважды.', english: 'The budget was revised twice', level: 'C1' },
  { russian: 'Новый сотрудник был нанят через агентство.', english: 'The new employee was hired through an agency', level: 'B2' },
  { russian: 'Ему было отказано в повышении.', english: 'He was denied a promotion', level: 'C1' },
  { russian: 'Соглашение было достигнуто обеими сторонами.', english: 'An agreement was reached by both sides', level: 'C1' },
  { russian: 'Слияние компаний было одобрено акционерами.', english: 'The merger was approved by the shareholders', level: 'C1' },
  { russian: 'Условия договора были пересмотрены.', english: 'The terms of the contract were revised', level: 'C1' },
  { russian: 'Её предложение было немедленно принято.', english: 'Her proposal was immediately accepted', level: 'C1' },
  { russian: 'Все данные уже были сохранены в системе.', english: 'All data had already been saved in the system', level: 'C1' },
  { russian: 'Его слова были неправильно истолкованы.', english: 'His words were misinterpreted', level: 'C1' },
  { russian: 'Проект был приостановлен до дальнейшего уведомления.', english: 'The project was put on hold until further notice', level: 'C1' },
  { russian: 'Ответственность была разделена между отделами.', english: 'The responsibility was shared between departments', level: 'C1' },
  { russian: 'Его уволили без объяснения причин.', english: 'He was dismissed without explanation', level: 'C1' },
  { russian: 'Документы были уничтожены после проверки.', english: 'The documents were destroyed after the audit', level: 'C1' },
  { russian: 'Новая политика была введена в действие.', english: 'The new policy was put into effect', level: 'C1' },
  { russian: 'Жалоба клиента была рассмотрена в течение недели.', english: 'The client complaint was handled within a week', level: 'C1' },
  { russian: 'Все стороны были проинформированы о рисках.', english: 'All parties were informed about the risks', level: 'C1' },
  { russian: 'Решение суда было обжаловано.', english: 'The court decision was appealed', level: 'C1' },
];

const L23_UK: any[] = [
  { russian: 'Документ був підписаний учора.', english: 'The document was signed yesterday', level: 'B1' },
  { russian: 'Лист надсилається щодня.', english: 'The letter is sent every day', level: 'B1' },
  { russian: 'Звіт був написаний командою.', english: 'The report was written by the team', level: 'B1' },
  { russian: 'Цей міст був збудований у 1990 році.', english: 'This bridge was built in 1990', level: 'B1' },
  { russian: 'Посилка була доставлена вранці.', english: 'The parcel was delivered in the morning', level: 'B1' },
  { russian: 'Всі помилки були виправлені.', english: 'All the mistakes were corrected', level: 'B1' },
  { russian: 'Продукт буде випущений наступного року.', english: 'The product will be released next year', level: 'B1' },
  { russian: 'Ці правила мають дотримуватися.', english: 'These rules must be followed', level: 'B2' },
  { russian: 'Лист був написаний англійською.', english: 'The letter was written in English', level: 'B1' },
  { russian: 'Гроші були переведені на рахунок.', english: 'The money was transferred to the account', level: 'B2' },
  { russian: 'Його запросили на конференцію.', english: 'He was invited to the conference', level: 'B1' },
  { russian: 'Ця книга була написана в минулому столітті.', english: 'This book was written in the last century', level: 'B2' },
  { russian: 'Всі учасники були повідомлені.', english: 'All participants were notified', level: 'B2' },
  { russian: 'Контракт буде підписаний завтра.', english: 'The contract will be signed tomorrow', level: 'B1' },
  { russian: 'Офіс був відремонтований.', english: 'The office was renovated', level: 'B1' },
  { russian: 'Його роботу високо оцінили.', english: 'His work was highly appreciated', level: 'B2' },
  { russian: 'Питання ще не було розглянуто.', english: 'The issue has not been addressed yet', level: 'B2' },
  { russian: 'Це рішення було прийнято радою директорів.', english: 'This decision was made by the board of directors', level: 'B2' },
  { russian: 'Дані були зашифровані.', english: 'The data was encrypted', level: 'B2' },
  { russian: 'Новий закон був прийнятий минулого року.', english: 'The new law was passed last year', level: 'B2' },
  { russian: 'Помилку виявили надто пізно.', english: 'The mistake was discovered too late', level: 'B2' },
  { russian: 'Інструкції мають виконуватися точно.', english: 'The instructions must be followed exactly', level: 'B2' },
  { russian: 'Зустріч була скасована.', english: 'The meeting was cancelled', level: 'B1' },
  { russian: 'Йому доручили очолити проект.', english: 'He was assigned to lead the project', level: 'B2' },
  { russian: 'Всі витрати будуть відшкодовані.', english: 'All expenses will be reimbursed', level: 'B2' },
  { russian: 'Ця проблема вже була вирішена.', english: 'This problem has already been solved', level: 'B2' },
  { russian: 'Нову систему впровадили успішно.', english: 'The new system was implemented successfully', level: 'B2' },
  { russian: 'Результати будуть оголошені наступного тижня.', english: 'The results will be announced next week', level: 'B2' },
  { russian: 'Завдання має бути виконане до п\'ятниці.', english: 'The task must be completed by Friday', level: 'B2' },
  { russian: 'Його заявку відхилили.', english: 'His application was rejected', level: 'B2' },
  { russian: 'Звинувачення було знято.', english: 'The accusation was dropped', level: 'C1' },
  { russian: 'Це питання передали до суду.', english: 'The matter was referred to court', level: 'C1' },
  { russian: 'Угоду було укладено після тривалих переговорів.', english: 'The deal was concluded after lengthy negotiations', level: 'C1' },
  { russian: 'Бюджет переглядали двічі.', english: 'The budget was revised twice', level: 'C1' },
  { russian: 'Нового співробітника найняли через агентство.', english: 'The new employee was hired through an agency', level: 'B2' },
  { russian: 'Йому відмовили в підвищенні.', english: 'He was denied a promotion', level: 'C1' },
  { russian: 'Угоду досягли обидві сторони.', english: 'An agreement was reached by both sides', level: 'C1' },
  { russian: 'Злиття компаній було схвалено акціонерами.', english: 'The merger was approved by the shareholders', level: 'C1' },
  { russian: 'Умови договору були переглянуті.', english: 'The terms of the contract were revised', level: 'C1' },
  { russian: 'Її пропозицію негайно прийняли.', english: 'Her proposal was immediately accepted', level: 'C1' },
  { russian: 'Всі дані вже були збережені в системі.', english: 'All data had already been saved in the system', level: 'C1' },
  { russian: 'Його слова були неправильно витлумачені.', english: 'His words were misinterpreted', level: 'C1' },
  { russian: 'Проект був призупинений до подальшого повідомлення.', english: 'The project was put on hold until further notice', level: 'C1' },
  { russian: 'Відповідальність була розподілена між відділами.', english: 'The responsibility was shared between departments', level: 'C1' },
  { russian: 'Його звільнили без пояснення причин.', english: 'He was dismissed without explanation', level: 'C1' },
  { russian: 'Документи були знищені після перевірки.', english: 'The documents were destroyed after the audit', level: 'C1' },
  { russian: 'Нову політику введено в дію.', english: 'The new policy was put into effect', level: 'C1' },
  { russian: 'Скаргу клієнта розглянули протягом тижня.', english: 'The client complaint was handled within a week', level: 'C1' },
  { russian: 'Всі сторони були поінформовані про ризики.', english: 'All parties were informed about the risks', level: 'C1' },
  { russian: 'Рішення суду було оскаржено.', english: 'The court decision was appealed', level: 'C1' },
];

const L24_RU: any[] = [
  { russian: 'Я уже закончил работу.', english: 'I have already finished the work', level: 'B1' },
  { russian: 'Она никогда не была в Лондоне.', english: 'She has never been to London', level: 'B1' },
  { russian: 'Мы только что получили ответ.', english: 'We have just received the reply', level: 'B1' },
  { russian: 'Он уже отправил письмо.', english: 'He has already sent the letter', level: 'B1' },
  { russian: 'Ты когда-нибудь ел суши?', english: 'Have you ever eaten sushi', level: 'B1' },
  { russian: 'Я никогда не слышал об этом.', english: 'I have never heard of this', level: 'B1' },
  { russian: 'Они ещё не приняли решение.', english: 'They have not made a decision yet', level: 'B1' },
  { russian: 'Она уже написала три книги.', english: 'She has already written three books', level: 'B1' },
  { russian: 'Мы только что вернулись из командировки.', english: 'We have just returned from a business trip', level: 'B1' },
  { russian: 'Он потерял ключи.', english: 'He has lost his keys', level: 'B1' },
  { russian: 'Ты видел новый фильм?', english: 'Have you seen the new film', level: 'B1' },
  { russian: 'Я уже читал эту книгу.', english: 'I have already read this book', level: 'B1' },
  { russian: 'Она работает здесь три года.', english: 'She has worked here for three years', level: 'B2' },
  { russian: 'Он живёт в этом доме с 2010 года.', english: 'He has lived in this house since 2010', level: 'B2' },
  { russian: 'Я знаю её с детства.', english: 'I have known her since childhood', level: 'B2' },
  { russian: 'Мы ещё не проверили данные.', english: 'We have not checked the data yet', level: 'B1' },
  { russian: 'Цена на нефть упала за последнее время.', english: 'The oil price has fallen recently', level: 'B2' },
  { russian: 'Я уже слышал эту историю.', english: 'I have already heard this story', level: 'B1' },
  { russian: 'Она ещё не ответила на моё письмо.', english: 'She has not replied to my email yet', level: 'B1' },
  { russian: 'Он встречался со многими знаменитостями.', english: 'He has met many celebrities', level: 'B2' },
  { russian: 'Мы существенно улучшили продукт.', english: 'We have significantly improved the product', level: 'B2' },
  { russian: 'Компания выросла за последние годы.', english: 'The company has grown in recent years', level: 'B2' },
  { russian: 'Ты когда-нибудь прыгал с парашютом?', english: 'Have you ever gone skydiving', level: 'B2' },
  { russian: 'Я никогда не нарушал закон.', english: 'I have never broken the law', level: 'B2' },
  { russian: 'Он добился большого прогресса.', english: 'He has made great progress', level: 'B2' },
  { russian: 'Они уже подписали договор.', english: 'They have already signed the contract', level: 'B2' },
  { russian: 'Я потратил всё своё время на этот проект.', english: 'I have spent all my time on this project', level: 'B2' },
  { russian: 'Она стала опытным специалистом.', english: 'She has become an experienced specialist', level: 'B2' },
  { russian: 'Мы создали отличную команду.', english: 'We have built an excellent team', level: 'B2' },
  { russian: 'Менеджер уже связался с клиентом.', english: 'The manager has already contacted the client', level: 'B2' },
  { russian: 'Он ещё не завершил анализ.', english: 'He has not completed the analysis yet', level: 'B2' },
  { russian: 'Цена выросла на десять процентов.', english: 'The price has risen by ten percent', level: 'B2' },
  { russian: 'Я понял, что допустил ошибку.', english: 'I have realised that I made a mistake', level: 'B2' },
  { russian: 'Она доказала свою правоту.', english: 'She has proved her point', level: 'C1' },
  { russian: 'Он взял на себя слишком много обязательств.', english: 'He has taken on too many commitments', level: 'C1' },
  { russian: 'Мы пересмотрели всю стратегию.', english: 'We have reviewed the entire strategy', level: 'C1' },
  { russian: 'Компания потеряла значительную долю рынка.', english: 'The company has lost a significant market share', level: 'C1' },
  { russian: 'Он выиграл несколько международных наград.', english: 'He has won several international awards', level: 'C1' },
  { russian: 'Технологии изменили нашу жизнь.', english: 'Technology has changed our lives', level: 'C1' },
  { russian: 'Она написала более двадцати научных статей.', english: 'She has written more than twenty academic papers', level: 'C1' },
  { russian: 'Я никогда не сталкивался с такой ситуацией.', english: 'I have never encountered such a situation', level: 'C1' },
  { russian: 'Правительство ввело новые меры.', english: 'The government has introduced new measures', level: 'C1' },
  { russian: 'Он накопил огромный опыт в этой области.', english: 'He has accumulated vast experience in this field', level: 'C1' },
  { russian: 'Мы столкнулись с серьёзными трудностями.', english: 'We have faced serious difficulties', level: 'C1' },
  { russian: 'Ситуация значительно ухудшилась.', english: 'The situation has deteriorated significantly', level: 'C1' },
  { russian: 'Она преодолела все препятствия.', english: 'She has overcome all obstacles', level: 'C1' },
  { russian: 'Рынок существенно изменился за последнее десятилетие.', english: 'The market has changed substantially over the last decade', level: 'C1' },
  { russian: 'Он восстановил репутацию компании.', english: 'He has restored the company\'s reputation', level: 'C1' },
  { russian: 'Мы достигли всех поставленных целей.', english: 'We have achieved all our set goals', level: 'C1' },
  { russian: 'Она подтвердила свой статус эксперта.', english: 'She has confirmed her status as an expert', level: 'C1' },
];

const L24_UK: any[] = [
  { russian: 'Я вже закінчив роботу.', english: 'I have already finished the work', level: 'B1' },
  { russian: 'Вона ніколи не була в Лондоні.', english: 'She has never been to London', level: 'B1' },
  { russian: 'Ми щойно отримали відповідь.', english: 'We have just received the reply', level: 'B1' },
  { russian: 'Він вже надіслав листа.', english: 'He has already sent the letter', level: 'B1' },
  { russian: 'Ти коли-небудь їв суші?', english: 'Have you ever eaten sushi', level: 'B1' },
  { russian: 'Я ніколи не чув про це.', english: 'I have never heard of this', level: 'B1' },
  { russian: 'Вони ще не прийняли рішення.', english: 'They have not made a decision yet', level: 'B1' },
  { russian: 'Вона вже написала три книги.', english: 'She has already written three books', level: 'B1' },
  { russian: 'Ми щойно повернулися з відрядження.', english: 'We have just returned from a business trip', level: 'B1' },
  { russian: 'Він загубив ключі.', english: 'He has lost his keys', level: 'B1' },
  { russian: 'Ти бачив новий фільм?', english: 'Have you seen the new film', level: 'B1' },
  { russian: 'Я вже читав цю книгу.', english: 'I have already read this book', level: 'B1' },
  { russian: 'Вона працює тут три роки.', english: 'She has worked here for three years', level: 'B2' },
  { russian: 'Він живе в цьому будинку з 2010 року.', english: 'He has lived in this house since 2010', level: 'B2' },
  { russian: 'Я знаю її з дитинства.', english: 'I have known her since childhood', level: 'B2' },
  { russian: 'Ми ще не перевірили дані.', english: 'We have not checked the data yet', level: 'B1' },
  { russian: 'Ціна на нафту впала останнім часом.', english: 'The oil price has fallen recently', level: 'B2' },
  { russian: 'Я вже чув цю історію.', english: 'I have already heard this story', level: 'B1' },
  { russian: 'Вона ще не відповіла на мій лист.', english: 'She has not replied to my email yet', level: 'B1' },
  { russian: 'Він зустрічався з багатьма знаменитостями.', english: 'He has met many celebrities', level: 'B2' },
  { russian: 'Ми суттєво покращили продукт.', english: 'We have significantly improved the product', level: 'B2' },
  { russian: 'Компанія зросла за останні роки.', english: 'The company has grown in recent years', level: 'B2' },
  { russian: 'Ти коли-небудь стрибав з парашутом?', english: 'Have you ever gone skydiving', level: 'B2' },
  { russian: 'Я ніколи не порушував закон.', english: 'I have never broken the law', level: 'B2' },
  { russian: 'Він досяг великого прогресу.', english: 'He has made great progress', level: 'B2' },
  { russian: 'Вони вже підписали договір.', english: 'They have already signed the contract', level: 'B2' },
  { russian: 'Я витратив весь свій час на цей проект.', english: 'I have spent all my time on this project', level: 'B2' },
  { russian: 'Вона стала досвідченим фахівцем.', english: 'She has become an experienced specialist', level: 'B2' },
  { russian: 'Ми створили відмінну команду.', english: 'We have built an excellent team', level: 'B2' },
  { russian: 'Менеджер вже зв\'язався з клієнтом.', english: 'The manager has already contacted the client', level: 'B2' },
  { russian: 'Він ще не завершив аналіз.', english: 'He has not completed the analysis yet', level: 'B2' },
  { russian: 'Ціна зросла на десять відсотків.', english: 'The price has risen by ten percent', level: 'B2' },
  { russian: 'Я зрозумів, що припустився помилки.', english: 'I have realised that I made a mistake', level: 'B2' },
  { russian: 'Вона довела свою правоту.', english: 'She has proved her point', level: 'C1' },
  { russian: 'Він узяв на себе забагато зобов\'язань.', english: 'He has taken on too many commitments', level: 'C1' },
  { russian: 'Ми переглянули всю стратегію.', english: 'We have reviewed the entire strategy', level: 'C1' },
  { russian: 'Компанія втратила значну частку ринку.', english: 'The company has lost a significant market share', level: 'C1' },
  { russian: 'Він виграв кілька міжнародних нагород.', english: 'He has won several international awards', level: 'C1' },
  { russian: 'Технології змінили наше життя.', english: 'Technology has changed our lives', level: 'C1' },
  { russian: 'Вона написала понад двадцять наукових статей.', english: 'She has written more than twenty academic papers', level: 'C1' },
  { russian: 'Я ніколи не стикався з такою ситуацією.', english: 'I have never encountered such a situation', level: 'C1' },
  { russian: 'Уряд запровадив нові заходи.', english: 'The government has introduced new measures', level: 'C1' },
  { russian: 'Він накопичив величезний досвід у цій галузі.', english: 'He has accumulated vast experience in this field', level: 'C1' },
  { russian: 'Ми зіткнулися з серйозними труднощами.', english: 'We have faced serious difficulties', level: 'C1' },
  { russian: 'Ситуація значно погіршилася.', english: 'The situation has deteriorated significantly', level: 'C1' },
  { russian: 'Вона подолала всі перешкоди.', english: 'She has overcome all obstacles', level: 'C1' },
  { russian: 'Ринок суттєво змінився за останнє десятиліття.', english: 'The market has changed substantially over the last decade', level: 'C1' },
  { russian: 'Він відновив репутацію компанії.', english: 'He has restored the company\'s reputation', level: 'C1' },
  { russian: 'Ми досягли всіх поставлених цілей.', english: 'We have achieved all our set goals', level: 'C1' },
  { russian: 'Вона підтвердила свій статус експерта.', english: 'She has confirmed her status as an expert', level: 'C1' },
];
