// Lessons 9-16 Data
import { LessonPhrase } from './lesson_data_types';

export {
  LESSON_9_PHRASES,
  LESSON_10_PHRASES,
  LESSON_11_PHRASES,
  LESSON_12_PHRASES,
  LESSON_13_PHRASES,
  LESSON_14_PHRASES,
  LESSON_15_PHRASES,
  LESSON_16_PHRASES,
} from './lesson_data_9_16_phrases_es.gen';

export {
  LESSON_9_INTRO_SCREENS,
  LESSON_10_INTRO_SCREENS,
  LESSON_11_INTRO_SCREENS,
  LESSON_12_INTRO_SCREENS,
  LESSON_13_INTRO_SCREENS,
  LESSON_14_INTRO_SCREENS,
  LESSON_15_INTRO_SCREENS,
  LESSON_16_INTRO_SCREENS,
} from './lesson_intro_screens_es_l2';




export const LESSON_9_IRREGULAR_VERBS = [
  { english: 'Sit', russian: 'Сидеть', ukrainian: 'Сидіти', past: 'sat', pastParticiple: 'sat' },
  { english: 'Stand', russian: 'Стоять', ukrainian: 'Стояти', past: 'stood', pastParticiple: 'stood' },
  { english: 'Swim', russian: 'Плавать', ukrainian: 'Плавати', past: 'swam', pastParticiple: 'swum' },
  { english: 'Let', russian: 'Позволять; пусть (let us)', ukrainian: 'Дозволяти; хай (let us)', past: 'let', pastParticiple: 'let' },
  { english: 'Fly', russian: 'Летать', ukrainian: 'Літати', past: 'flew', pastParticiple: 'flown' },
];

export const LESSON_9_VOCABULARY = [
  { english: 'There is', russian: 'Есть (один предмет)', ukrainian: 'Є (один предмет)' },
  { english: 'There are', russian: 'Есть (несколько предметов)', ukrainian: 'Є (кілька предметів)' },
  { english: 'Is there', russian: 'Есть...? (вопрос, один)', ukrainian: 'Є...? (питання, один)' },
  { english: 'Are there', russian: 'Есть...? (вопрос, несколько)', ukrainian: 'Є...? (питання, кілька)' },
  { english: 'No', russian: 'Нет (отрицание)', ukrainian: 'Немає (заперечення)' },
  { english: 'Some', russian: 'Несколько; немного', ukrainian: 'Кілька; трохи' },
  { english: 'Many', russian: 'Много', ukrainian: 'Багато' },
  { english: 'Problem', russian: 'Проблема', ukrainian: 'Проблема' },
  { english: 'Question', russian: 'Вопрос', ukrainian: 'Питання' },
  { english: 'Phone', russian: 'Телефон', ukrainian: 'Телефон' },
  { english: 'Key', russian: 'Ключ', ukrainian: 'Ключ' },
  { english: 'Ticket', russian: 'Билет', ukrainian: 'Квиток' },
  { english: 'Wi-Fi', russian: 'Wi-Fi', ukrainian: 'Wi-Fi' },
  { english: 'Money', russian: 'Деньги', ukrainian: 'Гроші' },
  { english: 'Cash', russian: 'Наличные', ukrainian: 'Готівка' },
  { english: 'Bag', russian: 'Сумка', ukrainian: 'Сумка' },
  { english: 'Charger', russian: 'Зарядное устройство', ukrainian: 'Зарядний пристрій' },
  { english: 'Idea', russian: 'Идея', ukrainian: 'Ідея' },
  { english: 'Plan', russian: 'План', ukrainian: 'План' },
  { english: 'Message', russian: 'Сообщение', ukrainian: 'Повідомлення' },
  { english: 'Food', russian: 'Еда', ukrainian: 'Їжа' },
  { english: 'Coffee', russian: 'Кофе', ukrainian: 'Кава' },
  { english: 'Document', russian: 'Документ', ukrainian: 'Документ' },
  { english: 'Mistake', russian: 'Ошибка', ukrainian: 'Помилка' },
  { english: 'Time', russian: 'Время', ukrainian: 'Час' },
  { english: 'People', russian: 'Люди', ukrainian: 'Люди' },
];


export const LESSON_10_IRREGULAR_VERBS = [
  { english: 'Go', russian: 'Идти; ехать', ukrainian: 'Іти; їхати', past: 'went', pastParticiple: 'gone' },
  { english: 'Find', russian: 'Находить', ukrainian: 'Знаходити', past: 'found', pastParticiple: 'found' },
  { english: 'Hear', russian: 'Слышать', ukrainian: 'Чути', past: 'heard', pastParticiple: 'heard' },
  { english: 'Drive', russian: 'Водить', ukrainian: 'Водити', past: 'drove', pastParticiple: 'driven' },
];

export const LESSON_10_VOCABULARY = [
  { english: 'Can', russian: 'Мочь; уметь; можно', ukrainian: 'Могти; вміти; можна' },
  { english: 'Cannot', russian: 'Не могу / не можешь (нельзя)', ukrainian: 'Не можу / не можеш (не можна)' },
  { english: 'Should', russian: 'Стоит; следует (совет)', ukrainian: 'Варто; слід (порада)' },
  { english: 'Must', russian: 'Должен; нужно (обязанность)', ukrainian: 'Повинен; потрібно (обов\'язок)' },
  { english: 'Must not', russian: 'Нельзя; запрещено', ukrainian: 'Не можна; заборонено' },
  { english: 'Have to', russian: 'Нужно; приходится (необходимость)', ukrainian: 'Потрібно; доводиться (необхідність)' },
  { english: 'Help', russian: 'Помогать', ukrainian: 'Допомагати' },
  { english: 'Start', russian: 'Начинать', ukrainian: 'Починати' },
  { english: 'Wait', russian: 'Ждать', ukrainian: 'Чекати' },
  { english: 'Call', russian: 'Звонить', ukrainian: 'Телефонувати' },
  { english: 'Go', russian: 'Идти; ехать', ukrainian: 'Іти; їхати' },
  { english: 'Work', russian: 'Работать', ukrainian: 'Працювати' },
  { english: 'Drive', russian: 'Водить', ukrainian: 'Водити' },
  { english: 'Hear', russian: 'Слышать', ukrainian: 'Чути' },
  { english: 'Find', russian: 'Находить', ukrainian: 'Знаходити' },
  { english: 'Use', russian: 'Использовать', ukrainian: 'Використовувати' },
  { english: 'Rest', russian: 'Отдыхать', ukrainian: 'Відпочивати' },
  { english: 'Drink', russian: 'Пить', ukrainian: 'Пити' },
  { english: 'Order', russian: 'Заказывать', ukrainian: 'Замовляти' },
  { english: 'Pay', russian: 'Платить', ukrainian: 'Платити' },
  { english: 'Listen', russian: 'Слушать', ukrainian: 'Слухати' },
  { english: 'Finish', russian: 'Заканчивать', ukrainian: 'Закінчувати' },
  { english: 'Check', russian: 'Проверять', ukrainian: 'Перевіряти' },
  { english: 'Show', russian: 'Показывать', ukrainian: 'Показувати' },
  { english: 'Sign', russian: 'Подписывать', ukrainian: 'Підписувати' },
  { english: 'Enter', russian: 'Входить', ukrainian: 'Входити' },
  { english: 'Share', russian: 'Делиться', ukrainian: 'Ділитися' },
  { english: 'Answer', russian: 'Отвечать', ukrainian: 'Відповідати' },
  { english: 'Speak', russian: 'Говорить', ukrainian: 'Говорити' },
  { english: 'Water', russian: 'Вода', ukrainian: 'Вода' },
  { english: 'Fast', russian: 'Быстро', ukrainian: 'Швидко' },
  { english: 'Later', russian: 'Позже', ukrainian: 'Пізніше' },
  { english: 'Outside', russian: 'Снаружи; на улице', ukrainian: 'Надворі; зовні' },
  { english: 'Smoke', russian: 'Курить', ukrainian: 'Курити' },
  { english: 'Password', russian: 'Пароль', ukrainian: 'Пароль' },
  { english: 'Room', russian: 'Комната', ukrainian: 'Кімната' },
  { english: 'Rent', russian: 'Аренда', ukrainian: 'Оренда' },
];


export const LESSON_11_IRREGULAR_VERBS = [];

export const LESSON_11_VOCABULARY = [
  { english: 'Worked', russian: 'Работал', ukrainian: 'Працював' },
  { english: 'Helped', russian: 'Помог', ukrainian: 'Допоміг' },
  { english: 'Called', russian: 'Позвонил', ukrainian: 'Зателефонував' },
  { english: 'Cooked', russian: 'Приготовил', ukrainian: 'Приготував' },
  { english: 'Watched', russian: 'Смотрел', ukrainian: 'Дивився' },
  { english: 'Played', russian: 'Играл', ukrainian: 'Грав' },
  { english: 'Cleaned', russian: 'Помыл; убрал', ukrainian: 'Помив; прибрав' },
  { english: 'Opened', russian: 'Открыл', ukrainian: 'Відкрив' },
  { english: 'Checked', russian: 'Проверил', ukrainian: 'Перевірив' },
  { english: 'Washed', russian: 'Помыл; постирал', ukrainian: 'Помив; виправ' },
  { english: 'Finished', russian: 'Закончил', ukrainian: 'Закінчив' },
  { english: 'Started', russian: 'Начал', ukrainian: 'Почав' },
  { english: 'Waited', russian: 'Ждал', ukrainian: 'Чекав' },
  { english: 'Listened', russian: 'Слушал', ukrainian: 'Слухав' },
  { english: 'Asked', russian: 'Попросил; спросил', ukrainian: 'Попросив; спитав' },
  { english: 'Answered', russian: 'Ответил', ukrainian: 'Відповів' },
  { english: 'Ordered', russian: 'Заказал', ukrainian: 'Замовив' },
  { english: 'Visited', russian: 'Навестил; посетил', ukrainian: 'Відвідав' },
  { english: 'Needed', russian: 'Нуждался; было нужно', ukrainian: 'Потребував; потрібен був' },
  { english: 'Wanted', russian: 'Хотел', ukrainian: 'Хотів' },
  { english: 'Used', russian: 'Использовал', ukrainian: 'Використовував' },
  { english: 'Booked', russian: 'Забронировал', ukrainian: 'Забронював' },
  { english: 'Rented', russian: 'Арендовал', ukrainian: 'Орендував' },
  { english: 'Printed', russian: 'Распечатал', ukrainian: 'Надрукував' },
  { english: 'Charged', russian: 'Зарядил', ukrainian: 'Зарядив' },
  { english: 'Moved', russian: 'Передвинул; переехал', ukrainian: 'Пересунув; переїхав' },
  { english: 'Painted', russian: 'Покрасил', ukrainian: 'Пофарбував' },
  { english: 'Missed', russian: 'Пропустил', ukrainian: 'Пропустив' },
  { english: 'Saved', russian: 'Сохранил; сэкономил', ukrainian: 'Зберіг; заощадив' },
  { english: 'Changed', russian: 'Изменил', ukrainian: 'Змінив' },
  { english: 'Prepared', russian: 'Приготовил; подготовил', ukrainian: 'Приготував; підготував' },
  { english: 'Canceled', russian: 'Отменил', ukrainian: 'Скасував' },
  { english: 'Returned', russian: 'Вернул', ukrainian: 'Повернув' },
  { english: 'Fixed', russian: 'Починил; исправил', ukrainian: 'Полагодив; виправив' },
  { english: 'Deleted', russian: 'Удалил', ukrainian: 'Видалив' },
  { english: 'Parked', russian: 'Припарковался', ukrainian: 'Припаркувався' },
  { english: 'Mailed', russian: 'Отправил по почте', ukrainian: 'Відправив поштою' },
  { english: 'Discussed', russian: 'Обсудил', ukrainian: 'Обговорив' },
  { english: 'Delivered', russian: 'Доставил', ukrainian: 'Доставив' },
  { english: 'Locked', russian: 'Запер', ukrainian: 'Замкнув' },
  { english: 'Brushed', russian: 'Расчесал; почистил', ukrainian: 'Розчесав; почистив' },
  { english: 'Closed', russian: 'Закрыл', ukrainian: 'Закрив' },
  { english: 'Yesterday', russian: 'Вчера', ukrainian: 'Вчора' },
  { english: 'Last week', russian: 'На прошлой неделе', ukrainian: 'Минулого тижня' },
  { english: 'Last month', russian: 'В прошлом месяце', ukrainian: 'Минулого місяця' },
  { english: 'This morning', russian: 'Сегодня утром', ukrainian: 'Сьогодні вранці' },
  { english: 'Two hours ago', russian: 'Два часа назад', ukrainian: 'Дві години тому' },
  { english: 'Clothes', russian: 'Одежда', ukrainian: 'Одяг' },
  { english: 'Walls', russian: 'Стены', ukrainian: 'Стіни' },
  { english: 'Hair', russian: 'Волосы', ukrainian: 'Волосся' },
  { english: 'Door', russian: 'Дверь', ukrainian: 'Двері' },
  { english: 'Book', russian: 'Книга', ukrainian: 'Книга' },
  { english: 'Email', russian: 'Письмо; имейл', ukrainian: 'Лист; імейл' },
];


export const LESSON_12_IRREGULAR_VERBS = [
  { english: 'Buy', russian: 'Покупать', ukrainian: 'Купувати', past: 'bought', pastParticiple: 'bought' },
  { english: 'Drink', russian: 'Пить', ukrainian: 'Пити', past: 'drank', pastParticiple: 'drunk' },
  { english: 'Find', russian: 'Находить', ukrainian: 'Знаходити', past: 'found', pastParticiple: 'found' },
  { english: 'Sell', russian: 'Продавать', ukrainian: 'Продавати', past: 'sold', pastParticiple: 'sold' },
  { english: 'Send', russian: 'Отправлять', ukrainian: 'Надсилати', past: 'sent', pastParticiple: 'sent' },
  { english: 'Come', russian: 'Приходить', ukrainian: 'Приходити', past: 'came', pastParticiple: 'come' },
  { english: 'See', russian: 'Видеть', ukrainian: 'Бачити', past: 'saw', pastParticiple: 'seen' },
  { english: 'Build', russian: 'Строить', ukrainian: 'Будувати', past: 'built', pastParticiple: 'built' },
  { english: 'Write', russian: 'Писать', ukrainian: 'Писати', past: 'wrote', pastParticiple: 'written' },
  { english: 'Bring', russian: 'Приносить', ukrainian: 'Приносити', past: 'brought', pastParticiple: 'brought' },
  { english: 'Go', russian: 'Идти; ехать', ukrainian: 'Іти; їхати', past: 'went', pastParticiple: 'gone' },
  { english: 'Put', russian: 'Класть', ukrainian: 'Класти', past: 'put', pastParticiple: 'put' },
  { english: 'Give', russian: 'Давать', ukrainian: 'Давати', past: 'gave', pastParticiple: 'given' },
  { english: 'Eat', russian: 'Есть', ukrainian: 'Їсти', past: 'ate', pastParticiple: 'eaten' },
  { english: 'Take', russian: 'Брать', ukrainian: 'Брати', past: 'took', pastParticiple: 'taken' },
  { english: 'Make', russian: 'Делать; готовить', ukrainian: 'Робити; готувати', past: 'made', pastParticiple: 'made' },
  { english: 'Hear', russian: 'Слышать', ukrainian: 'Чути', past: 'heard', pastParticiple: 'heard' },
  { english: 'Get', russian: 'Получать', ukrainian: 'Отримувати', past: 'got', pastParticiple: 'gotten' },
  { english: 'Lose', russian: 'Терять', ukrainian: 'Губити', past: 'lost', pastParticiple: 'lost' },
  { english: 'Leave', russian: 'Уходить; оставлять', ukrainian: 'Іти; залишати', past: 'left', pastParticiple: 'left' },
  { english: 'Feel', russian: 'Чувствовать', ukrainian: 'Відчувати', past: 'felt', pastParticiple: 'felt' },
  { english: 'Meet', russian: 'Встречать', ukrainian: 'Зустрічати', past: 'met', pastParticiple: 'met' },
  { english: 'Read', russian: 'Читать', ukrainian: 'Читати', past: 'read', pastParticiple: 'read' },
  { english: 'Speak', russian: 'Говорить', ukrainian: 'Говорити', past: 'spoke', pastParticiple: 'spoken' },
  { english: 'Know', russian: 'Знать', ukrainian: 'Знати', past: 'knew', pastParticiple: 'known' },
  { english: 'Think', russian: 'Думать', ukrainian: 'Думати', past: 'thought', pastParticiple: 'thought' },
  { english: 'Say', russian: 'Сказать', ukrainian: 'Сказати', past: 'said', pastParticiple: 'said' },
  { english: 'Pay', russian: 'Платить', ukrainian: 'Платити', past: 'paid', pastParticiple: 'paid' },
  { english: 'Run', russian: 'Бегать', ukrainian: 'Бігати', past: 'ran', pastParticiple: 'run' },
  { english: 'Sleep', russian: 'Спать', ukrainian: 'Спати', past: 'slept', pastParticiple: 'slept' },
  { english: 'Sit', russian: 'Сидеть', ukrainian: 'Сидіти', past: 'sat', pastParticiple: 'sat' },
  { english: 'Stand', russian: 'Стоять', ukrainian: 'Стояти', past: 'stood', pastParticiple: 'stood' },
  { english: 'Wear', russian: 'Носить', ukrainian: 'Носити', past: 'wore', pastParticiple: 'worn' },
  { english: 'Drive', russian: 'Водить', ukrainian: 'Водити', past: 'drove', pastParticiple: 'driven' },
  { english: 'Do', russian: 'Делать', ukrainian: 'Робити', past: 'did', pastParticiple: 'done' },
  { english: 'Have', russian: 'Иметь; у кого-то есть', ukrainian: 'Мати', past: 'had', pastParticiple: 'had' },
  { english: 'Tell', russian: 'Рассказывать; говорить', ukrainian: 'Розповідати; говорити', past: 'told', pastParticiple: 'told' },
  { english: 'Forget', russian: 'Забывать', ukrainian: 'Забувати', past: 'forgot', pastParticiple: 'forgotten' },
  { english: 'Choose', russian: 'Выбирать', ukrainian: 'Вибирати', past: 'chose', pastParticiple: 'chosen' },
];

export const LESSON_12_VOCABULARY = [
  { english: 'Bought', russian: 'Купил', ukrainian: 'Купив' },
  { english: 'Drank', russian: 'Выпил', ukrainian: 'Випив' },
  { english: 'Found', russian: 'Нашел', ukrainian: 'Знайшов' },
  { english: 'Sold', russian: 'Продал', ukrainian: 'Продав' },
  { english: 'Sent', russian: 'Отправил', ukrainian: 'Надіслав' },
  { english: 'Came', russian: 'Пришел', ukrainian: 'Прийшов' },
  { english: 'Saw', russian: 'Видел; увидел', ukrainian: 'Бачив; побачив' },
  { english: 'Built', russian: 'Построил', ukrainian: 'Побудував' },
  { english: 'Wrote', russian: 'Написал', ukrainian: 'Написав' },
  { english: 'Brought', russian: 'Принес', ukrainian: 'Приніс' },
  { english: 'Went', russian: 'Пошел; поехал', ukrainian: 'Пішов; поїхав' },
  { english: 'Put', russian: 'Положил', ukrainian: 'Поклав' },
  { english: 'Gave', russian: 'Дал', ukrainian: 'Дав' },
  { english: 'Ate', russian: 'Съел; поел', ukrainian: 'З\'їв; поїв' },
  { english: 'Took', russian: 'Взял', ukrainian: 'Взяв' },
  { english: 'Made', russian: 'Сделал; приготовил', ukrainian: 'Зробив; приготував' },
  { english: 'Heard', russian: 'Слышал; услышал', ukrainian: 'Чув; почув' },
  { english: 'Got', russian: 'Получил; достал', ukrainian: 'Отримав; дістав' },
  { english: 'Lost', russian: 'Потерял', ukrainian: 'Загубив' },
  { english: 'Left', russian: 'Ушел; оставил', ukrainian: 'Пішов; залишив' },
  { english: 'Felt', russian: 'Чувствовал', ukrainian: 'Відчував' },
  { english: 'Met', russian: 'Встретил', ukrainian: 'Зустрів' },
  { english: 'Read', russian: 'Читал (прош. время)', ukrainian: 'Читав (мин. час)' },
  { english: 'Spoke', russian: 'Говорил', ukrainian: 'Говорив' },
  { english: 'Knew', russian: 'Знал', ukrainian: 'Знав' },
  { english: 'Thought', russian: 'Думал', ukrainian: 'Думав' },
  { english: 'Said', russian: 'Сказал', ukrainian: 'Сказав' },
  { english: 'Paid', russian: 'Заплатил', ukrainian: 'Заплатив' },
  { english: 'Ran', russian: 'Бегал; побежал', ukrainian: 'Бігав; побіг' },
  { english: 'Slept', russian: 'Спал', ukrainian: 'Спав' },
  { english: 'Sat', russian: 'Сидел', ukrainian: 'Сидів' },
  { english: 'Stood', russian: 'Стоял', ukrainian: 'Стояв' },
  { english: 'Wore', russian: 'Носил', ukrainian: 'Носив' },
  { english: 'Drove', russian: 'Водил', ukrainian: 'Водив' },
  { english: 'Did', russian: 'Сделал', ukrainian: 'Зробив' },
  { english: 'Had', russian: 'Имел; было', ukrainian: 'Мав; було' },
  { english: 'Told', russian: 'Рассказал; сказал', ukrainian: 'Розповів; сказав' },
  { english: 'Forgot', russian: 'Забыл', ukrainian: 'Забув' },
  { english: 'Chose', russian: 'Выбрал', ukrainian: 'Вибрав' },
  { english: 'Bread', russian: 'Хлеб', ukrainian: 'Хліб' },
  { english: 'Juice', russian: 'Сок', ukrainian: 'Сік' },
  { english: 'Headphones', russian: 'Наушники', ukrainian: 'Навушники' },
  { english: 'Advice', russian: 'Совет', ukrainian: 'Порада' },
  { english: 'Early', russian: 'Рано', ukrainian: 'Рано' },
  { english: 'Before', russian: 'Раньше; до этого', ukrainian: 'Раніше; до цього' },
  { english: 'Story', russian: 'История', ukrainian: 'Історія' },
  { english: 'Last night', russian: 'Прошлой ночью', ukrainian: 'Минулої ночі' },
];






export const LESSON_16_VOCABULARY = [
  { english: 'Phrasal verb', russian: 'Фразовый глагол', ukrainian: 'Фразове дієслово' },
  { english: 'Particle (up, on, off…)', russian: 'Частица (up, on, off…)', ukrainian: 'Частка (up, on, off…)' },
  { english: 'Wake up', russian: 'Просыпаться / Проснуться', ukrainian: 'Прокидатися / Прокинутися' },
  { english: 'Put on', russian: 'Надевать', ukrainian: 'Надягати' },
  { english: 'Take off', russian: 'Снимать (одежду)', ukrainian: 'Знімати (одяг)' },
  { english: 'Look for', russian: 'Искать', ukrainian: 'Шукати' },
  { english: 'Throw away', russian: 'Выбрасывать', ukrainian: 'Викидати' },
  { english: 'Deal with', russian: 'Иметь дело с / Разбираться с', ukrainian: 'Мати справу з / Розбиратися з' },
  { english: 'Hang up', russian: 'Положить трубку / Повесить (вещи)', ukrainian: 'Покласти слухавку / Повісити (речі)' },
  { english: 'Pick up', russian: 'Подбирать / Забрать', ukrainian: 'Підбирати / Забрати' },
  { english: 'Put away / Put back', russian: 'Убрать (прочь) / Вернуть на место', ukrainian: 'Сховати / Повернути на місце' },
  { english: 'Find out', russian: 'Выяснять / Узнать', ukrainian: 'Дізнаватися / Дізнатися' },
  { english: 'Give back', russian: 'Вернуть (отдать обратно)', ukrainian: 'Повернути (віддати назад)' },
  { english: 'See off', russian: 'Провожать', ukrainian: 'Проводити' },
  { english: 'Go back', russian: 'Возвращаться', ukrainian: 'Повертатися' },
  { english: 'Get out of', russian: 'Выходить из', ukrainian: 'Виходити з' },
  { english: 'Turn on / Turn off', russian: 'Включать / Выключать', ukrainian: 'Вмикати / Вимикати' },
  { english: 'Hand over', russian: 'Передавать', ukrainian: 'Передавати' },
  { english: 'Clean up', russian: 'Убирать (наводить порядок)', ukrainian: 'Прибирати (наводити лад)' },
  { english: 'Get into', russian: 'Садиться в (такси и т.п.)', ukrainian: 'Сідати в (таксі тощо)' },
  { english: 'Get up', russian: 'Вставать (с дивана / с постели)', ukrainian: 'Вставати (з дивана / з ліжка)' },
  { english: 'Look after', russian: 'Присматривать за / Заботиться о', ukrainian: 'Доглядати за / Піклуватися про' },
  { english: 'Give out', russian: 'Раздавать (листовки и т.п.)', ukrainian: 'Роздавати (листівки тощо)' },
  { english: 'Try on', russian: 'Примерять (одежду)', ukrainian: 'Приміряти (одяг)' },
  { english: 'Fill in', russian: 'Заполнять (бланк, поля)', ukrainian: 'Заповнювати (бланк, поля)' },
  { english: 'Drop in / Drop into', russian: 'Заходить ненадолго / Заскакивать (разг.)', ukrainian: 'Заходити ненадолго / Заглянути (розм.)' },
  { english: 'Take away', russian: 'Убирать (посуду и т.п.)', ukrainian: 'Прибирати (посуд тощо)' },
  { english: 'Go away', russian: 'Уходить / Уезжать (прочь)', ukrainian: 'Йти геть / Покидати (місце, роботу)' },
  { english: 'Sit down', russian: 'Садиться', ukrainian: 'Сідати' },
  { english: 'Bring out', russian: 'Выносить / Подавать (блюда)', ukrainian: 'Виносити / Подавати (страви)' },
  { english: 'Call back', russian: 'Перезванивать', ukrainian: 'Передзвонювати' },
  { english: 'Pull on', russian: 'Натягивать (перчатки, носки)', ukrainian: 'Натягати (рукавички тощо)' },
  { english: 'Pull off', russian: 'Снимать / Стягивать (рюкзак, шапку)', ukrainian: 'Знімати / Стягувати (рюкзак, шапку)' },
  { english: 'Get back', russian: 'Возвращаться (домой и т.п.)', ukrainian: 'Повертатися (додому тощо)' },
  { english: 'Look in at', russian: 'Заглядывать в (кафе, магазин)', ukrainian: 'Заходити на хвилинку до (кафе, крамниці)' },
  { english: 'Go on with', russian: 'Продолжать заниматься (работой)', ukrainian: 'Продовжувати займатися (роботою)' },
  { english: 'Come across', russian: 'Натыкаться на / Случайно находить', ukrainian: 'Натрапляти на / Випадково знаходити' },
  { english: 'Clear away', russian: 'Убирать со стола (посуду)', ukrainian: 'Прибирати зі столу (посуд)' },
  { english: 'Room / Kitchen / Office', russian: 'Комната / Кухня / Офис', ukrainian: 'Кімната / Кухня / Офіс' },
  { english: 'Coat / Keys / Clothes', russian: 'Пальто / Ключи / Одежда', ukrainian: 'Пальто / Ключі / Одяг' },
  { english: 'Courier / Parcel', russian: 'Курьер / Посылка', ukrainian: 'Кур\'єр / Посилка' },
  { english: 'Colleague / Owner', russian: 'Коллега / Владелец', ukrainian: 'Колега / Власник' },
  { english: 'Balcony / Cupboard / Entrance', russian: 'Балкон / Шкаф / Вход', ukrainian: 'Балкон / Шафа / Вхід' },
  { english: 'Forest / Grass / Park', russian: 'Лес / Трава / Парк', ukrainian: 'Ліс / Трава / Парк' },
  { english: 'Knife / Apple / Money', russian: 'Нож / Яблоко / Деньги', ukrainian: 'Ніж / Яблуко / Гроші' },
  { english: 'Rule / Information / Folder', russian: 'Правило / Информация / Папка', ukrainian: 'Правило / Інформація / Папка' },
  { english: 'Coffee machine / Magazine', russian: 'Кофемашина / Журнал', ukrainian: 'Кавомашина / Журнал' },
  { english: 'Often / Usually / Sometimes / Seldom / Rarely', russian: 'Часто / Обычно / Иногда / Редко / Очень редко', ukrainian: 'Часто / Зазвичай / Іноді / Рідко / Дуже рідко' },
  { english: 'Together / Personally', russian: 'Вместе / Лично', ukrainian: 'Разом / Особисто' },
  { english: 'Polite / Honest / Stuffy', russian: 'Вежливый / Честный / Душный', ukrainian: 'Ввічливий / Чесний / Душний' },
  { english: 'Wi‑Fi / Password / Battery', russian: 'Wi‑Fi / Пароль / Батарея', ukrainian: 'Wi‑Fi / Пароль / Батарея' },
  { english: 'Oat cookie / Spare key', russian: 'Овсяное печенье / Запасной ключ', ukrainian: 'Вівсяне печиво / Запасний ключ' },
  { english: 'Boots / Scarf / Ring', russian: 'Сапоги / Шарф / Кольцо', ukrainian: 'Чоботи / Шарф / Кільце' },
  { english: 'Attic / Curtain / Smell', russian: 'Чердак / Штора / Запах', ukrainian: 'Горище / Штора / Запах' },
  { english: 'Hook / License / Drone', russian: 'Крючок / Права / Дрон', ukrainian: 'Гачок / Права / Дрон' },
  { english: 'Soy sauce / Crumb / Wall clock', russian: 'Соевый соус / Крошка / Настенные часы', ukrainian: 'Соєвий соус / Крихта / Настінний годинник' },
  { english: 'Sock / Glove / Helmet / Rug', russian: 'Носок / Перчатка / Шлем / Коврик', ukrainian: 'Шкарпетка / Рукавичка / Шолом / Килимок' },
  { english: 'Plastic bottle / Empty', russian: 'Пластиковая бутылка / Пустой', ukrainian: 'Пляшка з пластику / Порожній' },
];

export const LESSON_16_IRREGULAR_VERBS = [
  { english: 'Deal', russian: 'Иметь дело (with)', ukrainian: 'Мати справу (з)', past: 'dealt', pastParticiple: 'dealt' },
  { english: 'Hang', russian: 'Вешать / Висеть', ukrainian: 'Вішати / Висіти', past: 'hung', pastParticiple: 'hung' },
  { english: 'Lay', russian: 'Класть (положить)', ukrainian: 'Класти (покласти)', past: 'laid', pastParticiple: 'laid' },
  { english: 'Stick', russian: 'Вставлять / Приклеивать / Липнуть', ukrainian: 'Вставляти / Приклеювати / Липнути', past: 'stuck', pastParticiple: 'stuck' },
  { english: 'Tear', russian: 'Рвать', ukrainian: 'Рвати', past: 'tore', pastParticiple: 'torn' },
];


/* expo-router route shim: keeps utility module from warning when discovered as route */
export default function __RouteShim() { return null; }
