import type { LessonIntroScreen } from './lesson_data_types';

export const LESSON_4_INTRO_SCREENS: LessonIntroScreen[] = [
  {
    lessonId: 4,
    screenId: 'lesson_4_intro_1_concept',
    order: 1,
    kind: 'concept',
    titleRU: 'Как отрицать действие',
    titleUK: 'Як заперечувати дію',
    titleES: 'How to make an action negative',
    subtitleRU: 'Если человек что-то не делает, в английском нужен do not или does not.',
    subtitleUK: 'Якщо людина чогось не робить, в англійській потрібні do not або does not.',
    subtitleES: 'If someone does not do an action, English uses do not or does not.',
    textRU: 'Отрицание действия строится через do not или does not: I do not drink milk. You do not listen. It does not work.',
    textUK: 'Заперечення дії будується через do not або does not: I do not drink milk. You do not listen. It does not work.',
    textES: 'Negative action sentences use do not or does not: I do not drink milk. You do not listen. It does not work.',
    linesRU: [
      { type: 'text', parts: [{ text: 'В уроке 3 ты собирал обычные действия:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Теперь смысл меняется: ' }, { text: 'не пью, не слушаешь, не курит, не работает.', tone: 'strong' }] },
      { type: 'formula', parts: [{ text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'действие', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главное: ', tone: 'strong' }, { text: 'not не ставится одиноко перед действием. Ему нужен помощник do или does.', tone: 'warning' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'В уроці 3 ти складав звичайні дії:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Тепер зміст змінюється: ' }, { text: 'не п\'ю, не слухаєш, не курить, не працює.', tone: 'strong' }] },
      { type: 'formula', parts: [{ text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'дія', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Головне: ', tone: 'strong' }, { text: 'not не стоїть сам перед дією. Йому потрібен помічник do або does.', tone: 'warning' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'In lesson 3, you built normal actions:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'drink', tone: 'accent' }, { text: ' milk' }, { text: ' / ', tone: 'muted' }, { text: 'He ', tone: 'strong' }, { text: 'smokes', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'who', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'action', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }] },
      { type: 'correct', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Main idea: ', tone: 'strong' }, { text: 'not needs do or does before an action verb.', tone: 'warning' }] },
    ],
    examples: [
      { labelRU: 'я не', labelUK: 'я не', labelES: 'I do not', en: [{ text: 'I ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' drink milk' }], ru: 'Я не пью молоко', uk: 'Я не п\'ю молоко', es: 'No bebo leche.', trRU: 'Я не пью молоко', trUK: 'Я не п\'ю молоко', trES: 'No bebo leche.', noteRU: 'После I используется do not.', noteUK: 'Після I використовується do not.', noteES: 'After I, use do not.' },
      { labelRU: 'ты не', labelUK: 'ти не', labelES: 'you do not', en: [{ text: 'You ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' listen' }], ru: 'Ты не слушаешь', uk: 'Ти не слухаєш', es: 'No escuchas.', trRU: 'Ты не слушаешь', trUK: 'Ти не слухаєш', trES: 'No escuchas.', noteRU: 'После you тоже используется do not.', noteUK: 'Після you теж використовується do not.', noteES: 'After you, use do not too.' },
      { labelRU: 'это не', labelUK: 'це не', labelES: 'it does not', en: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work' }], ru: 'Это не работает', uk: 'Це не працює', es: 'No funciona.', trRU: 'Это не работает', trUK: 'Це не працює', trES: 'No funciona.', noteRU: 'После it используется does not.', noteUK: 'Після it використовується does not.', noteES: 'After it, use does not.' },
    ],
    developerNotes: {
      screenGoal: 'Объяснить разницу между уроком 2 и уроком 4: с состояниями было am/is/are not, а с действиями нужен do not/does not.',
      visualPriority: ['do not / does not выделять warning.', 'Смысловой глагол drink/listen/work выделять accent только когда нужно показать действие.', 'not отдельно не подсвечивать сильнее, чем вся конструкция do not/does not.'],
      highlightRules: ['Подлежащее выделять strong.', 'do not / does not всегда подсвечивать warning.', 'Действие можно подсвечивать accent, если оно является центром примера.'],
      forbiddenContent: ['Не добавлять don\'t / doesn\'t.', 'Не добавлять вопросы do/does.', 'Не добавлять am/is/are not как правильный вариант для действия.', 'Не добавлять Present Continuous.', 'Не добавлять модальные глаголы.'],
      layoutRules: ['Сначала связать с уроком 3.', 'Потом показать новую отрицательную формулу.', 'Потом дать короткие примеры.', 'Не делать один длинный абзац.'],
    },
  },
  {
    lessonId: 4,
    screenId: 'lesson_4_intro_2_do_vs_does',
    order: 2,
    kind: 'formula',
    titleRU: 'Когда do not, а когда does not',
    titleUK: 'Коли do not, а коли does not',
    titleES: 'When to use do not or does not',
    subtitleRU: 'Выбор зависит от первого слова: кто делает действие.',
    subtitleUK: 'Вибір залежить від першого слова: хто робить дію.',
    subtitleES: 'The choice depends on the first word: who does the action.',
    textRU: 'I / you / we / they используют do not. He / she / it используют does not. После does not глагол без -s: He does not smoke.',
    textUK: 'I / you / we / they використовують do not. He / she / it використовують does not. Після does not дієслово без -s: He does not smoke.',
    textES: 'I / you / we / they use do not. He / she / it use does not. After does not, the verb has no -s: He does not smoke.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'обычный глагол', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'обычный глагол', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'После ' }, { text: 'does not', tone: 'warning' }, { text: ' глагол уже ' }, { text: 'без -s', tone: 'accent' }, { text: ': smoke, eat, work.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'звичайне дієслово', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'звичайне дієслово', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Після ' }, { text: 'does not', tone: 'warning' }, { text: ' дієслово вже ' }, { text: 'без -s', tone: 'accent' }, { text: ': smoke, eat, work.' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'base verb', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'We ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' understand', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'does not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'base verb', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'It ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' work', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'After ' }, { text: 'does not', tone: 'warning' }, { text: ', the main verb has ' }, { text: 'no -s', tone: 'accent' }, { text: '.' }] },
    ],
    examples: [
      { labelRU: 'I / you / we / they', labelUK: 'I / you / we / they', labelES: 'I / you / we / they', en: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }], ru: 'Они здесь не живут', uk: 'Вони тут не живуть', es: 'No viven aquí.', trRU: 'Они здесь не живут', trUK: 'Вони тут не живуть', trES: 'No viven aquí.', noteRU: 'They требует do not.', noteUK: 'They вимагає do not.', noteES: 'Use do not with they.' },
      { labelRU: 'he', labelUK: 'he', labelES: 'he', en: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }], ru: 'Он не курит', uk: 'Він не курить', es: 'Él no fuma.', trRU: 'Он не курит', trUK: 'Він не курить', trES: 'Él no fuma.', noteRU: 'He требует does not, но глагол smoke остаётся обычным.', noteUK: 'He вимагає does not, але дієслово smoke залишається звичайним.', noteES: 'Use does not with he, but smoke stays in the base form.' },
      { labelRU: 'she', labelUK: 'she', labelES: 'she', en: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }], ru: 'Она не ест сахар', uk: 'Вона не їсть цукор', es: 'Ella no come azúcar.', trRU: 'Она не ест сахар', trUK: 'Вона не їсть цукор', trES: 'Ella no come azúcar.', noteRU: 'Не eats, потому что does уже забрал -s.', noteUK: 'Не eats, бо does вже забрав -s.', noteES: 'Not eats, because does already carries the -s.' },
    ],
    developerNotes: {
      screenGoal: 'Научить выбирать do not или does not по подлежащему и убрать ошибку he does not smokes.',
      visualPriority: ['Две группы должны быть визуально разделены.', 'I/you/we/they + do not.', 'he/she/it + does not.', 'Фразу "после does not глагол без -s" выделить как главный takeaway.'],
      highlightRules: ['do not/does not = warning.', 'Подлежащее = strong.', 'Обычный глагол после отрицания = accent.'],
      forbiddenContent: ['Не добавлять does not smokes как правильный вариант.', 'Не добавлять сокращения.', 'Не добавлять вопросительный порядок.', 'Не добавлять he does not to smoke.'],
      layoutRules: ['Экран должен быть почти как мини-таблица из двух групп.', 'Не перегружать всеми местоимениями в одной длинной строке, если экран узкий.', 'Можно рендерить две карточки: do not group и does not group.'],
    },
  },
  {
    lessonId: 4,
    screenId: 'lesson_4_intro_3_practice',
    order: 3,
    kind: 'practice',
    titleRU: 'Как собирать отрицание',
    titleUK: 'Як складати заперечення',
    titleES: 'How to build a negative sentence',
    subtitleRU: 'Сначала кто. Потом do not или does not. Потом обычный глагол.',
    subtitleUK: 'Спочатку хто. Потім do not або does not. Потім звичайне дієслово.',
    subtitleES: 'First who. Then do not or does not. Then the base verb.',
    textRU: 'Собирай отрицание так: кто -> do not / does not -> обычный глагол. He does not smoke, не He does not smokes.',
    textUK: 'Складай заперечення так: хто -> do not / does not -> звичайне дієслово. He does not smoke, не He does not smokes.',
    textES: 'Build negatives like this: who -> do not / does not -> base verb. He does not smoke, not He does not smokes.',
    linesRU: [
      { type: 'text', parts: [{ text: 'Когда видишь русское ' }, { text: '"не делает"', tone: 'warning' }, { text: ', не ставь not прямо перед глаголом.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Найди, кто делает действие: ', tone: 'muted' }, { text: 'he / she / it или I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Выбери помощник: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Поставь обычный глагол: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'She not eats sugar', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главный навык урока: ', tone: 'strong' }, { text: 'выбрать правильный помощник и не добавлять -s к глаголу после does not.' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'Коли бачиш українське ' }, { text: '"не робить"', tone: 'warning' }, { text: ', не став not прямо перед дієсловом.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Знайди, хто робить дію: ', tone: 'muted' }, { text: 'he / she / it або I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Обери помічник: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Постав звичайне дієслово: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'She not eats sugar', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Головна навичка уроку: ', tone: 'strong' }, { text: 'обрати правильний помічник і не додавати -s до дієслова після does not.' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'When the meaning is negative, do not put ' }, { text: 'not', tone: 'warning' }, { text: ' alone before the action.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Find who does the action: ', tone: 'muted' }, { text: 'he / she / it or I / you / we / they', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Choose the helper: ', tone: 'muted' }, { text: 'do not / does not', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Use the base verb: ', tone: 'muted' }, { text: 'drink, listen, smoke, eat, work, understand, live', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Wrong: ', tone: 'warning' }, { text: 'He does not smokes', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correct: ', tone: 'success' }, { text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Wrong: ', tone: 'warning' }, { text: 'They does not live here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correct: ', tone: 'success' }, { text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }] },
    ],
    examples: [
      { labelRU: 'шаги', labelUK: 'кроки', labelES: 'steps', en: [{ text: 'He ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' smoke', tone: 'accent' }], ru: 'Он не курит', uk: 'Він не курить', es: 'Él no fuma.', trRU: 'Он не курит', trUK: 'Він не курить', trES: 'Él no fuma.', noteRU: 'He -> does not -> smoke. Не smokes.', noteUK: 'He -> does not -> smoke. Не smokes.', noteES: 'He -> does not -> smoke. Not smokes.' },
      { labelRU: 'они', labelUK: 'вони', labelES: 'they', en: [{ text: 'They ', tone: 'strong' }, { text: 'do not', tone: 'warning' }, { text: ' live here', tone: 'accent' }], ru: 'Они здесь не живут', uk: 'Вони тут не живуть', es: 'No viven aquí.', trRU: 'Они здесь не живут', trUK: 'Вони тут не живуть', trES: 'No viven aquí.', noteRU: 'They -> do not -> live here.', noteUK: 'They -> do not -> live here.', noteES: 'They -> do not -> live here.' },
      { labelRU: 'она', labelUK: 'вона', labelES: 'she', en: [{ text: 'She ', tone: 'strong' }, { text: 'does not', tone: 'warning' }, { text: ' eat sugar', tone: 'accent' }], ru: 'Она не ест сахар', uk: 'Вона не їсть цукор', es: 'Ella no come azúcar.', trRU: 'Она не ест сахар', trUK: 'Вона не їсть цукор', trES: 'Ella no come azúcar.', noteRU: 'She -> does not -> eat sugar. Не eats.', noteUK: 'She -> does not -> eat sugar. Не eats.', noteES: 'She -> does not -> eat sugar. Not eats.' },
    ],
    developerNotes: {
      screenGoal: 'Подготовить к сборке предложений с дистракторами: do/does, base verb/verb+s, неправильное место not.',
      visualPriority: ['Шаги 1-2-3 сделать отдельными строками.', 'Wrong/correct пары показать компактными карточками.', 'Особенно выделить ошибку He does not smokes.'],
      highlightRules: ['wrong examples полностью danger.', 'correct examples: subject strong, helper warning, base verb accent.', 'В takeaway выделить does not и без -s.'],
      forbiddenContent: ['Не добавлять don\'t/doesn\'t.', 'Не добавлять вопросы.', 'Не добавлять модалки.', 'Не использовать фразы вне урока 4.'],
      layoutRules: ['Если экран перегружен, оставить 2 wrong/correct пары: He does not smokes и They does not live here.', 'Основной алгоритм должен быть виден без скролла.', 'Examples можно показывать ниже как дополнительные карточки.'],
    },
  },
];
