import type { LessonIntroScreen } from './lesson_data_types';

export const LESSON_5_INTRO_SCREENS: LessonIntroScreen[] = [
  {
    lessonId: 5,
    screenId: 'lesson_5_intro_1_concept',
    order: 1,
    kind: 'concept',
    titleRU: 'Как спросить про действие',
    titleUK: 'Як запитати про дію',
    titleES: 'How to ask about an action',
    subtitleRU: 'Если вопрос про действие, английский начинает его с Do или Does.',
    subtitleUK: 'Якщо питання про дію, англійська починає його з Do або Does.',
    subtitleES: 'If the question is about an action, English starts it with Do or Does.',
    textRU: 'Вопрос про действие начинается с Do или Does: Do you drink coffee? Does he live here? Do they know you?',
    textUK: 'Питання про дію починається з Do або Does: Do you drink coffee? Does he live here? Do they know you?',
    textES: 'Questions about actions start with Do or Does: Do you drink coffee? Does he live here? Do they know you?',
    linesRU: [
      { type: 'text', parts: [{ text: 'В уроках 1-2 вопросы были с ' }, { text: 'am / is / are', tone: 'accent' }, { text: ':' }] },
      { type: 'example', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you ready?' }, { text: ' / ', tone: 'muted' }, { text: 'Is', tone: 'accent' }, { text: ' it expensive?' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Но здесь вопрос не про состояние. Здесь вопрос про ' }, { text: 'действие', tone: 'strong' }, { text: ': пьёшь, живёт, работает, понимает, знают.' }] },
      { type: 'formula', parts: [{ text: 'Do / Does', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'действие?', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Do', tone: 'warning' }, { text: ' you drink coffee?' }] },
      { type: 'correct', parts: [{ text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'correct', parts: [{ text: 'Do', tone: 'warning' }, { text: ' they know you?' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главное: ', tone: 'strong' }, { text: 'Do / Does не переводится отдельным словом. Это сигнал вопроса про действие.', tone: 'warning' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'В уроках 1-2 питання були з ' }, { text: 'am / is / are', tone: 'accent' }, { text: ':' }] },
      { type: 'example', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you ready?' }, { text: ' / ', tone: 'muted' }, { text: 'Is', tone: 'accent' }, { text: ' it expensive?' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Але тут питання не про стан. Тут питання про ' }, { text: 'дію', tone: 'strong' }, { text: ': п\'єш, живе, працює, розуміє, знають.' }] },
      { type: 'formula', parts: [{ text: 'Do / Does', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'дія?', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Do', tone: 'warning' }, { text: ' you drink coffee?' }] },
      { type: 'correct', parts: [{ text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'correct', parts: [{ text: 'Do', tone: 'warning' }, { text: ' they know you?' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Головне: ', tone: 'strong' }, { text: 'Do / Does не перекладається окремим словом. Це сигнал питання про дію.', tone: 'warning' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'In lessons 1-2, questions used ' }, { text: 'am / is / are', tone: 'accent' }, { text: '.' }] },
      { type: 'example', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you ready?' }, { text: ' / ', tone: 'muted' }, { text: 'Is', tone: 'accent' }, { text: ' it expensive?' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Here the question is about an ' }, { text: 'action', tone: 'strong' }, { text: '.' }] },
      { type: 'formula', parts: [{ text: 'Do / Does', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'who', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'action?', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Do', tone: 'warning' }, { text: ' you drink coffee?' }] },
      { type: 'correct', parts: [{ text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'tip', parts: [{ text: 'Do / Does', tone: 'warning' }, { text: ' marks a question about an action.' }] },
    ],
    examples: [
      { labelRU: 'ты?', labelUK: 'ти?', labelES: 'you?', en: [{ text: 'Do', tone: 'warning' }, { text: ' you drink coffee?' }], ru: 'Ты пьёшь кофе?', uk: 'Ти п\'єш каву?', es: '¿Bebes café?', trRU: 'Ты пьёшь кофе?', trUK: 'Ти п\'єш каву?', trES: '¿Bebes café?', noteRU: 'После you вопрос начинается с Do.', noteUK: 'Після you питання починається з Do.', noteES: 'With you, the question starts with Do.' },
      { labelRU: 'он?', labelUK: 'він?', labelES: 'he?', en: [{ text: 'Does', tone: 'warning' }, { text: ' he live here?' }], ru: 'Он живёт здесь?', uk: 'Він живе тут?', es: '¿Él vive aquí?', trRU: 'Он живёт здесь?', trUK: 'Він живе тут?', trES: '¿Él vive aquí?', noteRU: 'После he вопрос начинается с Does.', noteUK: 'Після he питання починається з Does.', noteES: 'With he, the question starts with Does.' },
      { labelRU: 'они?', labelUK: 'вони?', labelES: 'they?', en: [{ text: 'Do', tone: 'warning' }, { text: ' they know you?' }], ru: 'Они знают тебя?', uk: 'Вони знають тебе?', es: '¿Te conocen?', trRU: 'Они знают тебя?', trUK: 'Вони знають тебе?', trES: '¿Te conocen?', noteRU: 'После they вопрос начинается с Do.', noteUK: 'Після they питання починається з Do.', noteES: 'With they, the question starts with Do.' },
    ],
    developerNotes: {
      screenGoal: 'Отделить вопросы с To Be от вопросов про действие. Пользователь должен понять, что Do/Does используется как старт вопроса про действие.',
      visualPriority: ['Do / Does всегда выделять warning.', 'am / is / are в сравнении выделить accent, но не делать их главным фокусом.', 'Действие drink/live/know можно подсвечивать accent только в формуле.'],
      highlightRules: ['В вопросах выделять первое слово Do/Does.', 'Не подсвечивать всё предложение.', 'Смысловой глагол не должен отвлекать от Do/Does на первом экране.'],
      forbiddenContent: ['Не добавлять отрицания do not / does not.', 'Не добавлять wh-questions.', 'Не добавлять модальные глаголы.', 'Не добавлять Present Continuous.', 'Не использовать сокращения.'],
      layoutRules: ['Сначала коротко связать с уроком 2.', 'Потом показать разницу: состояние vs действие.', 'Потом формула и 3 примера.'],
    },
  },
  {
    lessonId: 5,
    screenId: 'lesson_5_intro_2_do_vs_does',
    order: 2,
    kind: 'formula',
    titleRU: 'Когда Do, а когда Does',
    titleUK: 'Коли Do, а коли Does',
    titleES: 'When to use Do or Does',
    subtitleRU: 'Выбор зависит от того, кто делает действие.',
    subtitleUK: 'Вибір залежить від того, хто робить дію.',
    subtitleES: 'The choice depends on who does the action.',
    textRU: 'Do используется с I / you / we / they. Does используется с he / she / it. После Does глагол без -s: Does he live here?',
    textUK: 'Do використовується з I / you / we / they. Does використовується з he / she / it. Після Does дієслово без -s: Does he live here?',
    textES: 'Use Do with I / you / we / they. Use Does with he / she / it. After Does, the verb has no -s: Does he live here?',
    linesRU: [
      { type: 'formula', parts: [{ text: 'Do', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'обычный глагол?', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'Do', tone: 'warning' }, { text: ' you drink coffee?' }] },
      { type: 'example', parts: [{ text: 'Do', tone: 'warning' }, { text: ' they know you?' }] },
      { type: 'example', parts: [{ text: 'Do', tone: 'warning' }, { text: ' you drink coffee?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Does', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'обычный глагол?', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'example', parts: [{ text: 'Does', tone: 'warning' }, { text: ' she understand English?' }] },
      { type: 'example', parts: [{ text: 'Does', tone: 'warning' }, { text: ' it cost much?' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'После ' }, { text: 'Does', tone: 'warning' }, { text: ' глагол уже ' }, { text: 'без -s', tone: 'accent' }, { text: ': live, understand, cost.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'Do', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'звичайне дієслово?', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'Do', tone: 'warning' }, { text: ' we work here?' }] },
      { type: 'example', parts: [{ text: 'Do', tone: 'warning' }, { text: ' they know you?' }] },
      { type: 'example', parts: [{ text: 'Do', tone: 'warning' }, { text: ' we work here?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Does', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'звичайне дієслово?', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'example', parts: [{ text: 'Does', tone: 'warning' }, { text: ' she understand English?' }] },
      { type: 'example', parts: [{ text: 'Does', tone: 'warning' }, { text: ' it cost much?' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Після ' }, { text: 'Does', tone: 'warning' }, { text: ' дієслово вже ' }, { text: 'без -s', tone: 'accent' }, { text: ': live, understand, cost.' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'Do', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'I / you / we / they', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'base verb?', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'Do', tone: 'warning' }, { text: ' we work here?' }] },
      { type: 'example', parts: [{ text: 'Do', tone: 'warning' }, { text: ' they know you?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Does', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'he / she / it', tone: 'strong' }, { text: ' + ', tone: 'muted' }, { text: 'base verb?', tone: 'accent' }] },
      { type: 'example', parts: [{ text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'example', parts: [{ text: 'Does', tone: 'warning' }, { text: ' it cost much?' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'After ' }, { text: 'Does', tone: 'warning' }, { text: ', the main verb has ' }, { text: 'no -s', tone: 'accent' }, { text: '.' }] },
    ],
    examples: [
      { labelRU: 'do group', labelUK: 'do group', labelES: 'do group', en: [{ text: 'Do', tone: 'warning' }, { text: ' they know you?' }], ru: 'Они знают тебя?', uk: 'Вони знають тебе?', es: '¿Te conocen?', trRU: 'Они знают тебя?', trUK: 'Вони знають тебе?', trES: '¿Te conocen?', noteRU: 'They требует Do.', noteUK: 'They вимагає Do.', noteES: 'They take Do.' },
      { labelRU: 'does group', labelUK: 'does group', labelES: 'does group', en: [{ text: 'Does', tone: 'warning' }, { text: ' she understand English?' }], ru: 'Она понимает английский?', uk: 'Вона розуміє англійську?', es: '¿Ella entiende inglés?', trRU: 'Она понимает английский?', trUK: 'Вона розуміє англійську?', trES: '¿Ella entiende inglés?', noteRU: 'She требует Does, но глагол understand без -s.', noteUK: 'She вимагає Does, але дієслово understand без -s.', noteES: 'Use Does with she, but understand has no -s.' },
      { labelRU: 'it', labelUK: 'it', labelES: 'it', en: [{ text: 'Does', tone: 'warning' }, { text: ' it cost much?' }], ru: 'Это стоит дорого?', uk: 'Це коштує дорого?', es: '¿Cuesta mucho?', trRU: 'Это стоит дорого?', trUK: 'Це коштує дорого?', trES: '¿Cuesta mucho?', noteRU: 'It тоже требует Does.', noteUK: 'It теж вимагає Does.', noteES: 'Use Does with it too.' },
    ],
    developerNotes: {
      screenGoal: 'Научить выбирать Do или Does по подлежащему и закрепить правило: после Does глагол без -s.',
      visualPriority: ['Сделать две группы: Do group и Does group.', 'Do/Does выделять warning.', 'he/she/it и I/you/we/they выделять strong.', 'Фразу "после Does глагол без -s" сделать главным takeaway.'],
      highlightRules: ['В примерах подсвечивать только Do/Does.', 'В формуле подсвечивать Do/Does, группу подлежащих и "обычный глагол".'],
      forbiddenContent: ['Не добавлять отрицания.', 'Не добавлять wh-questions.', 'Не добавлять Do he.', 'Не добавлять Does he lives как правильный вариант.', 'Не использовать сокращения.'],
      layoutRules: ['Две группы должны быть визуально разнесены.', 'Если экран узкий, показывать по 2 примера на группу, остальные в examples.'],
    },
  },
  {
    lessonId: 5,
    screenId: 'lesson_5_intro_3_practice',
    order: 3,
    kind: 'practice',
    titleRU: 'Как собирать вопрос',
    titleUK: 'Як складати питання',
    titleES: 'How to build the question',
    subtitleRU: 'Сначала Do или Does. Потом кто. Потом обычный глагол.',
    subtitleUK: 'Спочатку Do або Does. Потім хто. Потім звичайне дієслово.',
    subtitleES: 'First Do or Does. Then who. Then the base verb.',
    textRU: 'Собирай вопрос так: Do / Does -> кто -> обычный глагол. Does he live here?, не Does he lives here?',
    textUK: 'Складай питання так: Do / Does -> хто -> звичайне дієслово. Does he live here?, не Does he lives here?',
    textES: 'Build the question like this: Do / Does -> who -> base verb. Does he live here?, not Does he lives here?',
    linesRU: [
      { type: 'text', parts: [{ text: 'Когда русская фраза спрашивает про действие, не начинай с самого действия.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Найди, кто делает действие: ', tone: 'muted' }, { text: 'you / he / she / we / they / it', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Выбери старт вопроса: ', tone: 'muted' }, { text: 'Do / Does', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Поставь обычный глагол: ', tone: 'muted' }, { text: 'drink, live, understand, cost, know', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'He lives here?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Does he lives here?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Does they know you?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Do', tone: 'warning' }, { text: ' they know you?' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главный навык урока: ', tone: 'strong' }, { text: 'в вопросе про действие сначала выбрать Do или Does, а после Does не ставить -s в глаголе.' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'Коли фраза питає про дію, не починай із самої дії.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Знайди, хто робить дію: ', tone: 'muted' }, { text: 'you / he / she / we / they / it', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Обери старт питання: ', tone: 'muted' }, { text: 'Do / Does', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Постав звичайне дієслово: ', tone: 'muted' }, { text: 'drink, live, understand, cost, know', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'He lives here?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Does he lives here?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Does they know you?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Do', tone: 'warning' }, { text: ' they know you?' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Головна навичка уроку: ', tone: 'strong' }, { text: 'у питанні про дію спочатку вибрати Do або Does, а після Does не ставити -s у дієслові.' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'When the sentence asks about an action, do not start with the action itself.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Find who does the action: ', tone: 'muted' }, { text: 'you / he / she / we / they / it', tone: 'strong' }] },
      { type: 'step', parts: [{ text: '2. Choose the question starter: ', tone: 'muted' }, { text: 'Do / Does', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '3. Use the base verb: ', tone: 'muted' }, { text: 'drink, live, understand, cost, know', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Wrong: ', tone: 'warning' }, { text: 'He lives here?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correct: ', tone: 'success' }, { text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'wrong', parts: [{ text: 'Wrong: ', tone: 'warning' }, { text: 'Does he lives here?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correct: ', tone: 'success' }, { text: 'Does', tone: 'warning' }, { text: ' he live here?' }] },
      { type: 'wrong', parts: [{ text: 'Wrong: ', tone: 'warning' }, { text: 'Does they know you?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Correct: ', tone: 'success' }, { text: 'Do', tone: 'warning' }, { text: ' they know you?' }] },
    ],
    examples: [
      { labelRU: 'you', labelUK: 'you', labelES: 'you', en: [{ text: 'Do', tone: 'warning' }, { text: ' you drink coffee?' }], ru: 'Ты пьешь кофе?', uk: 'Ти п\'єш каву?', es: '¿Bebes café?', trRU: 'Ты пьешь кофе?', trUK: 'Ти п\'єш каву?', trES: '¿Bebes café?', noteRU: 'Do -> you -> drink.', noteUK: 'Do -> you -> drink.', noteES: 'Do -> you -> drink.' },
      { labelRU: 'she', labelUK: 'she', labelES: 'she', en: [{ text: 'Does', tone: 'warning' }, { text: ' she understand English?' }], ru: 'Она понимает английский?', uk: 'Вона розуміє англійську?', es: '¿Ella entiende inglés?', trRU: 'Она понимает английский?', trUK: 'Вона розуміє англійську?', trES: '¿Ella entiende inglés?', noteRU: 'Does -> she -> understand. Не understands.', noteUK: 'Does -> she -> understand. Не understands.', noteES: 'Does -> she -> understand. Not understands.' },
      { labelRU: 'we', labelUK: 'we', labelES: 'we', en: [{ text: 'Do', tone: 'warning' }, { text: ' we work here?' }], ru: 'Мы здесь работаем?', uk: 'Ми тут працюємо?', es: '¿Trabajamos aquí?', trRU: 'Мы здесь работаем?', trUK: 'Ми тут працюємо?', trES: '¿Trabajamos aquí?', noteRU: 'We требует Do.', noteUK: 'We вимагає Do.', noteES: 'We take Do.' },
    ],
    developerNotes: {
      screenGoal: 'Подготовить к сборке вопроса из слов-кнопок: выбрать Do/Does, поставить подлежащее, потом базовый глагол.',
      visualPriority: ['Шаги 1-2-3 сделать отдельными строками.', 'Wrong/correct пары показать компактно.', 'Особенно выделить две ошибки: Does he lives и Does they.'],
      highlightRules: ['wrong examples полностью danger.', 'correct examples: Do/Does warning, остальное normal.', 'В шагах Do/Does warning, глаголы accent.'],
      forbiddenContent: ['Не добавлять отрицания.', 'Не добавлять wh-questions.', 'Не добавлять am/is/are questions как часть правильного ответа.', 'Не использовать фразы вне урока 5.'],
      layoutRules: ['Если экран перегружен, оставить 2 wrong/correct пары: Does he lives и Does they know you.', 'Главный алгоритм должен быть виден без скролла.', 'Examples можно показывать ниже как дополнительные карточки.'],
    },
  },
];
