const L9_RU: any[] = [
  { russian: 'На столе лежит книга.', english: 'There is a book on the table', level: 'A2' },
  { russian: 'В комнате три стула.', english: 'There are three chairs in the room', level: 'A2' },
  { russian: 'Рядом нет кафе.', english: 'There is no café nearby', level: 'B1' },
  { russian: 'Есть вопросы?', english: 'Are there any questions', level: 'B1' },
  { russian: 'Сегодня много пробок.', english: 'There is a lot of traffic today', level: 'B1' },
  { russian: 'В этом городе много возможностей.', english: 'There are many opportunities in this city', level: 'B2' },
  { russian: 'На парковке есть места.', english: 'There are spaces in the car park', level: 'A2' },
  { russian: 'В офисе нет принтера.', english: 'There is no printer in the office', level: 'A2' },
  { russian: 'В этом районе есть хорошие рестораны.', english: 'There are good restaurants in this area', level: 'B1' },
  { russian: 'В письме нет ошибок.', english: 'There are no mistakes in the letter', level: 'B1' },
  { russian: 'На встрече было десять человек.', english: 'There were ten people at the meeting', level: 'B1' },
  { russian: 'В нашем плане есть проблема.', english: 'There is a problem with our plan', level: 'B1' },
  { russian: 'Рядом с офисом есть метро.', english: 'There is a metro station near the office', level: 'A2' },
  { russian: 'В этом документе много ошибок.', english: 'There are many mistakes in this document', level: 'B1' },
  { russian: 'В городе нет хорошего транспорта.', english: 'There is no good transport in the city', level: 'B1' },
  { russian: 'На этаже есть конференц-зал.', english: 'There is a conference room on this floor', level: 'A2' },
  { russian: 'В проекте есть риски.', english: 'There are risks in the project', level: 'B2' },
  { russian: 'Сегодня много работы.', english: 'There is a lot of work today', level: 'A2' },
  { russian: 'В отчёте нет нужной информации.', english: 'There is no necessary information in the report', level: 'B2' },
  { russian: 'На складе достаточно товара.', english: 'There is enough stock in the warehouse', level: 'B2' },
  { russian: 'В расписании нет времени.', english: 'There is no time in the schedule', level: 'B1' },
  { russian: 'На сайте есть форма обратной связи.', english: 'There is a feedback form on the website', level: 'B1' },
  { russian: 'В компании работает несколько отделов.', english: 'There are several departments in the company', level: 'B1' },
  { russian: 'В конце улицы есть банк.', english: 'There is a bank at the end of the street', level: 'A2' },
  { russian: 'В новом офисе много света.', english: 'There is a lot of light in the new office', level: 'B1' },
  { russian: 'Есть ли альтернативное решение?', english: 'Is there an alternative solution', level: 'B2' },
  { russian: 'В контракте есть несколько пунктов.', english: 'There are several clauses in the contract', level: 'B2' },
  { russian: 'На встрече не было клиента.', english: 'There was no client at the meeting', level: 'B1' },
  { russian: 'В плане нет чёткого дедлайна.', english: 'There is no clear deadline in the plan', level: 'B2' },
  { russian: 'В коридоре есть люди.', english: 'There are people in the corridor', level: 'A2' },
  { russian: 'На дороге есть объезд.', english: 'There is a diversion on the road', level: 'B1' },
  { russian: 'В нашей команде есть специалисты.', english: 'There are specialists in our team', level: 'B1' },
  { russian: 'Рядом нет парковки.', english: 'There is no parking nearby', level: 'A2' },
  { russian: 'В системе есть ошибка.', english: 'There is an error in the system', level: 'B1' },
  { russian: 'На прошлой неделе было три встречи.', english: 'There were three meetings last week', level: 'B1' },
  { russian: 'В нашем предложении есть несколько вариантов.', english: 'There are several options in our proposal', level: 'B2' },
  { russian: 'В офисе нет кофемашины.', english: 'There is no coffee machine in the office', level: 'A2' },
  { russian: 'В городе много стартапов.', english: 'There are many start-ups in the city', level: 'B1' },
  { russian: 'На этой неделе нет свободных мест.', english: 'There are no free slots this week', level: 'B2' },
  { russian: 'В этом районе есть несколько школ.', english: 'There are several schools in this area', level: 'B1' },
  { russian: 'На сервере нет нужного файла.', english: 'There is no required file on the server', level: 'B2' },
  { russian: 'В компании нет такой политики.', english: 'There is no such policy in the company', level: 'B2' },
  { russian: 'В холодильнике ничего нет.', english: 'There is nothing in the fridge', level: 'A2' },
  { russian: 'На рынке есть конкуренция.', english: 'There is competition in the market', level: 'B2' },
  { russian: 'В плане есть хорошие идеи.', english: 'There are good ideas in the plan', level: 'B1' },
  { russian: 'На этом этаже нет лифта.', english: 'There is no lift on this floor', level: 'A2' },
  { russian: 'В договоре есть спорные пункты.', english: 'There are disputed clauses in the agreement', level: 'B2' },
  { russian: 'В центре города есть большой парк.', english: 'There is a large park in the city centre', level: 'A2' },
  { russian: 'На встрече было несколько предложений.', english: 'There were several proposals at the meeting', level: 'B1' },
  { russian: 'В офисе нет свободных переговорных.', english: 'There are no free meeting rooms in the office', level: 'B2' },
];

const L9_UK: any[] = [
  { russian: 'На столі лежить книга.', english: 'There is a book on the table', level: 'A2' },
  { russian: 'У кімнаті три стільці.', english: 'There are three chairs in the room', level: 'A2' },
  { russian: 'Поруч немає кафе.', english: 'There is no café nearby', level: 'B1' },
  { russian: 'Є запитання?', english: 'Are there any questions', level: 'B1' },
  { russian: 'Сьогодні багато заторів.', english: 'There is a lot of traffic today', level: 'B1' },
  { russian: 'У цьому місті багато можливостей.', english: 'There are many opportunities in this city', level: 'B2' },
  { russian: 'На парковці є місця.', english: 'There are spaces in the car park', level: 'A2' },
  { russian: 'В офісі немає принтера.', english: 'There is no printer in the office', level: 'A2' },
  { russian: 'У цьому районі є хороші ресторани.', english: 'There are good restaurants in this area', level: 'B1' },
  { russian: 'У листі немає помилок.', english: 'There are no mistakes in the letter', level: 'B1' },
  { russian: 'На зустрічі було десять осіб.', english: 'There were ten people at the meeting', level: 'B1' },
  { russian: 'У нашому плані є проблема.', english: 'There is a problem with our plan', level: 'B1' },
  { russian: 'Поруч з офісом є метро.', english: 'There is a metro station near the office', level: 'A2' },
  { russian: 'У цьому документі багато помилок.', english: 'There are many mistakes in this document', level: 'B1' },
  { russian: 'У місті немає хорошого транспорту.', english: 'There is no good transport in the city', level: 'B1' },
  { russian: 'На поверсі є конференц-зал.', english: 'There is a conference room on this floor', level: 'A2' },
  { russian: 'У проекті є ризики.', english: 'There are risks in the project', level: 'B2' },
  { russian: 'Сьогодні багато роботи.', english: 'There is a lot of work today', level: 'A2' },
  { russian: 'У звіті немає потрібної інформації.', english: 'There is no necessary information in the report', level: 'B2' },
  { russian: 'На складі достатньо товару.', english: 'There is enough stock in the warehouse', level: 'B2' },
  { russian: 'У розкладі немає часу.', english: 'There is no time in the schedule', level: 'B1' },
  { russian: 'На сайті є форма зворотного зв\'язку.', english: 'There is a feedback form on the website', level: 'B1' },
  { russian: 'У компанії є кілька відділів.', english: 'There are several departments in the company', level: 'B1' },
  { russian: 'В кінці вулиці є банк.', english: 'There is a bank at the end of the street', level: 'A2' },
  { russian: 'У новому офісі багато світла.', english: 'There is a lot of light in the new office', level: 'B1' },
  { russian: 'Чи є альтернативне рішення?', english: 'Is there an alternative solution', level: 'B2' },
  { russian: 'У контракті є кілька пунктів.', english: 'There are several clauses in the contract', level: 'B2' },
  { russian: 'На зустрічі не було клієнта.', english: 'There was no client at the meeting', level: 'B1' },
  { russian: 'У плані немає чіткого дедлайну.', english: 'There is no clear deadline in the plan', level: 'B2' },
  { russian: 'У коридорі є люди.', english: 'There are people in the corridor', level: 'A2' },
  { russian: 'На дорозі є об\'їзд.', english: 'There is a diversion on the road', level: 'B1' },
  { russian: 'У нашій команді є фахівці.', english: 'There are specialists in our team', level: 'B1' },
  { russian: 'Поруч немає парковки.', english: 'There is no parking nearby', level: 'A2' },
  { russian: 'У системі є помилка.', english: 'There is an error in the system', level: 'B1' },
  { russian: 'Минулого тижня було три зустрічі.', english: 'There were three meetings last week', level: 'B1' },
  { russian: 'У нашій пропозиції є кілька варіантів.', english: 'There are several options in our proposal', level: 'B2' },
  { russian: 'В офісі немає кавомашини.', english: 'There is no coffee machine in the office', level: 'A2' },
  { russian: 'У місті багато стартапів.', english: 'There are many start-ups in the city', level: 'B1' },
  { russian: 'Цього тижня немає вільних слотів.', english: 'There are no free slots this week', level: 'B2' },
  { russian: 'У цьому районі є кілька шкіл.', english: 'There are several schools in this area', level: 'B1' },
  { russian: 'На сервері немає потрібного файлу.', english: 'There is no required file on the server', level: 'B2' },
  { russian: 'У компанії немає такої політики.', english: 'There is no such policy in the company', level: 'B2' },
  { russian: 'У холодильнику нічого немає.', english: 'There is nothing in the fridge', level: 'A2' },
  { russian: 'На ринку є конкуренція.', english: 'There is competition in the market', level: 'B2' },
  { russian: 'У плані є хороші ідеї.', english: 'There are good ideas in the plan', level: 'B1' },
  { russian: 'На цьому поверсі немає ліфта.', english: 'There is no lift on this floor', level: 'A2' },
  { russian: 'У договорі є спірні пункти.', english: 'There are disputed clauses in the agreement', level: 'B2' },
  { russian: 'У центрі міста є великий парк.', english: 'There is a large park in the city centre', level: 'A2' },
  { russian: 'На зустрічі було кілька пропозицій.', english: 'There were several proposals at the meeting', level: 'B1' },
  { russian: 'В офісі немає вільних переговорних.', english: 'There are no free meeting rooms in the office', level: 'B2' },
];

const L10_RU: any[] = [
  { russian: 'Я умею плавать.', english: 'I can swim', level: 'A2' },
  { russian: 'Тебе нужно обратиться к врачу.', english: 'You should see a doctor', level: 'B1' },
  { russian: 'Она должна закончить к пятнице.', english: 'She must finish by Friday', level: 'B1' },
  { russian: 'Он может опоздать.', english: 'He might be late', level: 'B1' },
  { russian: 'Ты можешь мне помочь?', english: 'Can you help me', level: 'A2' },
  { russian: 'Тебе не нужно приходить.', english: 'You do not have to come', level: 'B1' },
  { russian: 'Я могу ошибаться.', english: 'I might be wrong', level: 'B1' },
  { russian: 'Она может не знать ответа.', english: 'She may not know the answer', level: 'B2' },
  { russian: 'Ты умеешь водить машину?', english: 'Can you drive a car', level: 'A2' },
  { russian: 'Нам нужно принять решение сегодня.', english: 'We must make a decision today', level: 'B1' },
  { russian: 'Он мог бы быть директором.', english: 'He could be the director', level: 'B1' },
  { russian: 'Вам следует прочитать контракт.', english: 'You should read the contract', level: 'B1' },
  { russian: 'Можно задать вопрос?', english: 'May I ask a question', level: 'A2' },
  { russian: 'Она должна сообщить об этом.', english: 'She must report this', level: 'B1' },
  { russian: 'Нам следует обсудить это.', english: 'We should discuss this', level: 'B1' },
  { russian: 'Он не может прийти сегодня.', english: 'He cannot come today', level: 'A2' },
  { russian: 'Вам не нужно платить сейчас.', english: 'You do not have to pay now', level: 'B1' },
  { russian: 'Это может занять время.', english: 'This might take some time', level: 'B1' },
  { russian: 'Ты должен уважать коллег.', english: 'You must respect your colleagues', level: 'B1' },
  { russian: 'Она умеет говорить на трёх языках.', english: 'She can speak three languages', level: 'A2' },
  { russian: 'Нам нужно найти решение.', english: 'We need to find a solution', level: 'B1' },
  { russian: 'Он не должен знать об этом.', english: 'He must not know about this', level: 'B2' },
  { russian: 'Тебе следует принести документы.', english: 'You should bring the documents', level: 'B1' },
  { russian: 'Она может задержаться.', english: 'She may be delayed', level: 'B1' },
  { russian: 'Можно мне взять это?', english: 'May I take this', level: 'A2' },
  { russian: 'Им нужно пересмотреть бюджет.', english: 'They need to review the budget', level: 'B1' },
  { russian: 'Он может быть прав.', english: 'He might be right', level: 'B1' },
  { russian: 'Нам не нужно торопиться.', english: 'We do not have to rush', level: 'B1' },
  { russian: 'Ты должен перезвонить ему.', english: 'You must call him back', level: 'B1' },
  { russian: 'Она не может работать с этой программой.', english: "She can't work with this program", level: 'A2' },
  { russian: 'Им следует улучшить свой сервис.', english: 'They should improve their service', level: 'B2' },
  { russian: 'Это должно работать.', english: 'This should work', level: 'B1' },
  { russian: 'Он может не согласиться.', english: 'He might not agree', level: 'B2' },
  { russian: 'Ты не должен этого делать.', english: 'You must not do this', level: 'B1' },
  { russian: 'Нам можно остаться?', english: 'Can we stay', level: 'A2' },
  { russian: 'Она должна объяснить своё решение.', english: 'She must explain her decision', level: 'B1' },
  { russian: 'Им нужно расширить команду.', english: 'They need to expand the team', level: 'B2' },
  { russian: 'Он умеет решать сложные задачи.', english: 'He can solve complex problems', level: 'B1' },
  { russian: 'Нам следует провести проверку.', english: 'We should carry out an audit', level: 'B2' },
  { russian: 'Это может быть ошибкой.', english: 'This might be a mistake', level: 'B1' },
  { russian: 'Ты можешь прислать файл?', english: 'Can you send the file', level: 'A2' },
  { russian: 'Она не должна опаздывать.', english: 'She must not be late', level: 'B1' },
  { russian: 'Им может понадобиться больше времени.', english: 'They might need more time', level: 'B1' },
  { russian: 'Нам нужно согласовать детали.', english: 'We need to agree on the details', level: 'B2' },
  { russian: 'Он должен подписать договор.', english: 'He must sign the contract', level: 'B1' },
  { russian: 'Тебе не нужно переживать.', english: 'You do not have to worry', level: 'A2' },
  { russian: 'Она может предложить хорошее решение.', english: 'She may offer a good solution', level: 'B2' },
  { russian: 'Вам следует рассмотреть все варианты.', english: 'You should consider all the options', level: 'B2' },
  { russian: 'Это может сработать.', english: 'This might work', level: 'B1' },
  { russian: 'Им нужно обратить внимание на детали.', english: 'They need to pay attention to the details', level: 'B2' },
];

const L10_UK: any[] = [
  { russian: 'Я вмію плавати.', english: 'I can swim', level: 'A2' },
  { russian: 'Тобі треба звернутися до лікаря.', english: 'You should see a doctor', level: 'B1' },
  { russian: 'Вона повинна закінчити до п\'ятниці.', english: 'She must finish by Friday', level: 'B1' },
  { russian: 'Він може запізнитися.', english: 'He might be late', level: 'B1' },
  { russian: 'Ти можеш мені допомогти?', english: 'Can you help me', level: 'A2' },
  { russian: 'Тобі не треба приходити.', english: 'You do not have to come', level: 'B1' },
  { russian: 'Я можу помилятися.', english: 'I might be wrong', level: 'B1' },
  { russian: 'Вона може не знати відповіді.', english: 'She may not know the answer', level: 'B2' },
  { russian: 'Ти вмієш водити машину?', english: 'Can you drive a car', level: 'A2' },
  { russian: 'Нам треба прийняти рішення сьогодні.', english: 'We must make a decision today', level: 'B1' },
  { russian: 'Він міг би бути директором.', english: 'He could be the director', level: 'B1' },
  { russian: 'Вам слід прочитати контракт.', english: 'You should read the contract', level: 'B1' },
  { russian: 'Можна поставити запитання?', english: 'May I ask a question', level: 'A2' },
  { russian: 'Вона повинна повідомити про це.', english: 'She must report this', level: 'B1' },
  { russian: 'Нам слід обговорити це.', english: 'We should discuss this', level: 'B1' },
  { russian: 'Він не може прийти сьогодні.', english: 'He cannot come today', level: 'A2' },
  { russian: 'Вам не потрібно платити зараз.', english: 'You do not have to pay now', level: 'B1' },
  { russian: 'Це може зайняти час.', english: 'This might take some time', level: 'B1' },
  { russian: 'Ти повинен поважати колег.', english: 'You must respect your colleagues', level: 'B1' },
  { russian: 'Вона вміє говорити трьома мовами.', english: 'She can speak three languages', level: 'A2' },
  { russian: 'Нам потрібно знайти рішення.', english: 'We need to find a solution', level: 'B1' },
  { russian: 'Він не повинен знати про це.', english: 'He must not know about this', level: 'B2' },
  { russian: 'Тобі слід принести документи.', english: 'You should bring the documents', level: 'B1' },
  { russian: 'Вона може затриматися.', english: 'She may be delayed', level: 'B1' },
  { russian: 'Можна мені взяти це?', english: 'May I take this', level: 'A2' },
  { russian: 'Їм потрібно переглянути бюджет.', english: 'They need to review the budget', level: 'B1' },
  { russian: 'Він може бути правим.', english: 'He might be right', level: 'B1' },
  { russian: 'Нам не потрібно поспішати.', english: 'We do not have to rush', level: 'B1' },
  { russian: 'Ти повинен передзвонити йому.', english: 'You must call him back', level: 'B1' },
  { russian: 'Вона не може працювати з цією програмою.', english: "She can't work with this program", level: 'A2' },
  { russian: 'Їм слід покращити свій сервіс.', english: 'They should improve their service', level: 'B2' },
  { russian: 'Це повинно працювати.', english: 'This should work', level: 'B1' },
  { russian: 'Він може не погодитися.', english: 'He might not agree', level: 'B2' },
  { russian: 'Ти не повинен цього робити.', english: 'You must not do this', level: 'B1' },
  { russian: 'Нам можна залишитися?', english: 'Can we stay', level: 'A2' },
  { russian: 'Вона повинна пояснити своє рішення.', english: 'She must explain her decision', level: 'B1' },
  { russian: 'Їм потрібно розширити команду.', english: 'They need to expand the team', level: 'B2' },
  { russian: 'Він вміє вирішувати складні завдання.', english: 'He can solve complex problems', level: 'B1' },
  { russian: 'Нам слід провести перевірку.', english: 'We should carry out an audit', level: 'B2' },
  { russian: 'Це може бути помилкою.', english: 'This might be a mistake', level: 'B1' },
  { russian: 'Ти можеш надіслати файл?', english: 'Can you send the file', level: 'A2' },
  { russian: 'Вона не повинна запізнюватися.', english: 'She must not be late', level: 'B1' },
  { russian: 'Їм може знадобитися більше часу.', english: 'They might need more time', level: 'B1' },
  { russian: 'Нам потрібно узгодити деталі.', english: 'We need to agree on the details', level: 'B2' },
  { russian: 'Він повинен підписати договір.', english: 'He must sign the contract', level: 'B1' },
  { russian: 'Тобі не потрібно переживати.', english: 'You do not have to worry', level: 'A2' },
  { russian: 'Вона може запропонувати гарне рішення.', english: 'She may offer a good solution', level: 'B2' },
  { russian: 'Вам слід розглянути всі варіанти.', english: 'You should consider all the options', level: 'B2' },
  { russian: 'Це може спрацювати.', english: 'This might work', level: 'B1' },
  { russian: 'Їм потрібно звернути увагу на деталі.', english: 'They need to pay attention to the details', level: 'B2' },
];

const L11_RU: any[] = [
  { russian: 'Я работал вчера.', english: 'I worked yesterday', level: 'A2' },
  { russian: 'Она позвонила ему вчера вечером.', english: 'She called him last night', level: 'A2' },
  { russian: 'Они посетили Лондон в прошлом году.', english: 'They visited London last year', level: 'B1' },
  { russian: 'Он начал новый проект.', english: 'He started a new project', level: 'B1' },
  { russian: 'Мы смотрели фильм вчера вечером.', english: 'We watched a film yesterday evening', level: 'A2' },
  { russian: 'Она сдала отчёт вовремя.', english: 'She submitted the report on time', level: 'B1' },
  { russian: 'Я хотел что-то сказать.', english: 'I wanted to say something', level: 'B1' },
  { russian: 'Он играл в теннис на прошлой неделе.', english: 'He played tennis last week', level: 'A2' },
  { russian: 'Она закончила курс в июне.', english: 'She completed the course in June', level: 'B1' },
  { russian: 'Мы использовали новый метод.', english: 'We used a new method', level: 'B1' },
  { russian: 'Они переехали в новый офис в прошлом месяце.', english: 'They moved to a new office last month', level: 'B1' },
  { russian: 'Я ждал тебя час.', english: 'I waited for you for an hour', level: 'A2' },
  { russian: 'Он остановился у друга.', english: 'He stayed with a friend', level: 'A2' },
  { russian: 'Она открыла новый счёт в банке.', english: 'She opened a new bank account', level: 'B1' },
  { russian: 'Мы отменили встречу.', english: 'We cancelled the meeting', level: 'B1' },
  { russian: 'Они подписали контракт в пятницу.', english: 'They signed the contract on Friday', level: 'B1' },
  { russian: 'Я заказал такси.', english: 'I ordered a taxi', level: 'A2' },
  { russian: 'Он напечатал документ.', english: 'He typed the document', level: 'A2' },
  { russian: 'Она объяснила проблему.', english: 'She explained the problem', level: 'B1' },
  { russian: 'Мы договорились о встрече.', english: 'We agreed on a meeting', level: 'B1' },
  { russian: 'Они прошли через парк.', english: 'They walked through the park', level: 'A2' },
  { russian: 'Я повторил задание несколько раз.', english: 'I repeated the task several times', level: 'B1' },
  { russian: 'Он сэкономил время.', english: 'He saved time', level: 'B1' },
  { russian: 'Она загрузила файл.', english: 'She uploaded the file', level: 'A2' },
  { russian: 'Мы попробовали другой подход.', english: 'We tried a different approach', level: 'B1' },
  { russian: 'Они обсудили бюджет.', english: 'They discussed the budget', level: 'B1' },
  { russian: 'Я заполнил форму.', english: 'I filled in the form', level: 'A2' },
  { russian: 'Он запланировал встречу на завтра.', english: 'He planned a meeting for tomorrow', level: 'B1' },
  { russian: 'Она перевела документ.', english: 'She translated the document', level: 'B1' },
  { russian: 'Мы доставили заказ вовремя.', english: 'We delivered the order on time', level: 'B1' },
  { russian: 'Они улучшили свои показатели.', english: 'They improved their results', level: 'B2' },
  { russian: 'Я поговорил с клиентом.', english: 'I talked to the client', level: 'A2' },
  { russian: 'Он уточнил детали.', english: 'He clarified the details', level: 'B1' },
  { russian: 'Она подготовила презентацию.', english: 'She prepared the presentation', level: 'B1' },
  { russian: 'Мы изменили план.', english: 'We changed the plan', level: 'B1' },
  { russian: 'Они отреагировали быстро.', english: 'They reacted quickly', level: 'B2' },
  { russian: 'Я зарегистрировался на конференцию.', english: 'I registered for the conference', level: 'B1' },
  { russian: 'Он отправил резюме.', english: 'He submitted his CV', level: 'A2' },
  { russian: 'Она работала допоздна.', english: 'She worked late', level: 'A2' },
  { russian: 'Мы сохранили файлы.', english: 'We saved the files', level: 'A2' },
  { russian: 'Они представили новый продукт.', english: 'They presented the new product', level: 'B1' },
  { russian: 'Я помог коллеге.', english: 'I helped my colleague', level: 'A2' },
  { russian: 'Он завершил проект досрочно.', english: 'He completed the project ahead of schedule', level: 'B2' },
  { russian: 'Она ответила на все письма.', english: 'She answered all the emails', level: 'B1' },
  { russian: 'Мы запустили новую программу.', english: 'We launched the new programme', level: 'B1' },
  { russian: 'Они сократили расходы.', english: 'They reduced their costs', level: 'B2' },
  { russian: 'Я проверил отчёт.', english: 'I checked the report', level: 'A2' },
  { russian: 'Он посетил семинар.', english: 'He attended the seminar', level: 'B1' },
  { russian: 'Она организовала мероприятие.', english: 'She organised the event', level: 'B1' },
  { russian: 'Мы выполнили все задачи.', english: 'We completed all the tasks', level: 'B1' },
];

const L11_UK: any[] = [
  { russian: 'Я працював учора.', english: 'I worked yesterday', level: 'A2' },
  { russian: 'Вона зателефонувала йому вчора ввечері.', english: 'She called him last night', level: 'A2' },
  { russian: 'Вони відвідали Лондон минулого року.', english: 'They visited London last year', level: 'B1' },
  { russian: 'Він почав новий проект.', english: 'He started a new project', level: 'B1' },
  { russian: 'Ми дивилися фільм учора ввечері.', english: 'We watched a film yesterday evening', level: 'A2' },
  { russian: 'Вона здала звіт вчасно.', english: 'She submitted the report on time', level: 'B1' },
  { russian: 'Я хотів щось сказати.', english: 'I wanted to say something', level: 'B1' },
  { russian: 'Він грав у теніс минулого тижня.', english: 'He played tennis last week', level: 'A2' },
  { russian: 'Вона закінчила курс у червні.', english: 'She completed the course in June', level: 'B1' },
  { russian: 'Ми використали новий метод.', english: 'We used a new method', level: 'B1' },
  { russian: 'Вони переїхали до нового офісу минулого місяця.', english: 'They moved to a new office last month', level: 'B1' },
  { russian: 'Я чекав тебе годину.', english: 'I waited for you for an hour', level: 'A2' },
  { russian: 'Він зупинився у друга.', english: 'He stayed with a friend', level: 'A2' },
  { russian: 'Вона відкрила новий рахунок у банку.', english: 'She opened a new bank account', level: 'B1' },
  { russian: 'Ми скасували зустріч.', english: 'We cancelled the meeting', level: 'B1' },
  { russian: 'Вони підписали контракт у п\'ятницю.', english: 'They signed the contract on Friday', level: 'B1' },
  { russian: 'Я замовив таксі.', english: 'I ordered a taxi', level: 'A2' },
  { russian: 'Він надрукував документ.', english: 'He typed the document', level: 'A2' },
  { russian: 'Вона пояснила проблему.', english: 'She explained the problem', level: 'B1' },
  { russian: 'Ми домовились про зустріч.', english: 'We agreed on a meeting', level: 'B1' },
  { russian: 'Вони прогулялися парком.', english: 'They walked through the park', level: 'A2' },
  { russian: 'Я повторив завдання кілька разів.', english: 'I repeated the task several times', level: 'B1' },
  { russian: 'Він заощадив час.', english: 'He saved time', level: 'B1' },
  { russian: 'Вона завантажила файл.', english: 'She uploaded the file', level: 'A2' },
  { russian: 'Ми спробували інший підхід.', english: 'We tried a different approach', level: 'B1' },
  { russian: 'Вони обговорили бюджет.', english: 'They discussed the budget', level: 'B1' },
  { russian: 'Я заповнив форму.', english: 'I filled in the form', level: 'A2' },
  { russian: 'Він запланував зустріч на завтра.', english: 'He planned a meeting for tomorrow', level: 'B1' },
  { russian: 'Вона переклала документ.', english: 'She translated the document', level: 'B1' },
  { russian: 'Ми доставили замовлення вчасно.', english: 'We delivered the order on time', level: 'B1' },
  { russian: 'Вони покращили свої показники.', english: 'They improved their results', level: 'B2' },
  { russian: 'Я поговорив з клієнтом.', english: 'I talked to the client', level: 'A2' },
  { russian: 'Він уточнив деталі.', english: 'He clarified the details', level: 'B1' },
  { russian: 'Вона підготувала презентацію.', english: 'She prepared the presentation', level: 'B1' },
  { russian: 'Ми змінили план.', english: 'We changed the plan', level: 'B1' },
  { russian: 'Вони відреагували швидко.', english: 'They reacted quickly', level: 'B2' },
  { russian: 'Я зареєструвався на конференцію.', english: 'I registered for the conference', level: 'B1' },
  { russian: 'Він надіслав резюме.', english: 'He submitted his CV', level: 'A2' },
  { russian: 'Вона працювала допізна.', english: 'She worked late', level: 'A2' },
  { russian: 'Ми зберегли файли.', english: 'We saved the files', level: 'A2' },
  { russian: 'Вони представили новий продукт.', english: 'They presented the new product', level: 'B1' },
  { russian: 'Я допоміг колезі.', english: 'I helped my colleague', level: 'A2' },
  { russian: 'Він завершив проект достроково.', english: 'He completed the project ahead of schedule', level: 'B2' },
  { russian: 'Вона відповіла на всі листи.', english: 'She answered all the emails', level: 'B1' },
  { russian: 'Ми запустили нову програму.', english: 'We launched the new programme', level: 'B1' },
  { russian: 'Вони скоротили витрати.', english: 'They reduced their costs', level: 'B2' },
  { russian: 'Я перевірив звіт.', english: 'I checked the report', level: 'A2' },
  { russian: 'Він відвідав семінар.', english: 'He attended the seminar', level: 'B1' },
  { russian: 'Вона організувала захід.', english: 'She organised the event', level: 'B1' },
  { russian: 'Ми виконали всі завдання.', english: 'We completed all the tasks', level: 'B1' },
];

const L12_RU: any[] = [
  { russian: 'Я пошёл в офис вчера.', english: 'I went to the office yesterday', level: 'A2' },
  { russian: 'Она увидела его на встрече.', english: 'She saw him at the meeting', level: 'B1' },
  { russian: 'Они узнали новости утром.', english: 'They got the news this morning', level: 'B1' },
  { russian: 'Он совершил большую ошибку.', english: 'He made a big mistake', level: 'B1' },
  { russian: 'Мы взяли такси домой.', english: 'We took a taxi home', level: 'A2' },
  { russian: 'Она сказала мне правду.', english: 'She told me the truth', level: 'B1' },
  { russian: 'Я думал об этом всю ночь.', english: 'I thought about it all night', level: 'B2' },
  { russian: 'Он дал мне важный совет.', english: 'He gave me important advice', level: 'B1' },
  { russian: 'Она нашла хорошее решение.', english: 'She found a good solution', level: 'B1' },
  { russian: 'Мы купили новое оборудование.', english: 'We bought new equipment', level: 'B1' },
  { russian: 'Они пришли на встречу без предупреждения.', english: 'They came to the meeting without warning', level: 'B2' },
  { russian: 'Я знал об этом заранее.', english: 'I knew about this in advance', level: 'B1' },
  { russian: 'Он написал отчёт за два часа.', english: 'He wrote the report in two hours', level: 'B1' },
  { russian: 'Она выбрала лучший вариант.', english: 'She chose the best option', level: 'B1' },
  { russian: 'Мы встретили директора на конференции.', english: 'We met the director at the conference', level: 'B1' },
  { russian: 'Они привели хорошие аргументы.', english: 'They put forward good arguments', level: 'B2' },
  { russian: 'Я оставил документы в офисе.', english: 'I left the documents in the office', level: 'A2' },
  { russian: 'Он понял проблему сразу.', english: 'He understood the problem immediately', level: 'B1' },
  { russian: 'Она провела отличную презентацию.', english: 'She gave an excellent presentation', level: 'B1' },
  { russian: 'Мы потеряли контракт из-за ошибки.', english: 'We lost the contract due to a mistake', level: 'B2' },
  { russian: 'Они продали компанию в прошлом году.', english: 'They sold the company last year', level: 'B2' },
  { russian: 'Я поехал на конференцию в Берлин.', english: 'I went to a conference in Berlin', level: 'B1' },
  { russian: 'Он стал директором три года назад.', english: 'He became director three years ago', level: 'B1' },
  { russian: 'Она прислала нужные файлы.', english: 'She sent the necessary files', level: 'B1' },
  { russian: 'Мы построили хорошую команду.', english: 'We built a good team', level: 'B2' },
  { russian: 'Они взяли кредит на развитие.', english: 'They took a loan for development', level: 'B2' },
  { russian: 'Я слышал об этой компании раньше.', english: 'I heard about this company before', level: 'B1' },
  { russian: 'Он поехал на переговоры в Варшаву.', english: 'He went to negotiations in Warsaw', level: 'B1' },
  { russian: 'Она привела клиента на встречу.', english: 'She brought the client to the meeting', level: 'B1' },
  { russian: 'Мы нашли инвестора.', english: 'We found an investor', level: 'B1' },
  { russian: 'Они провели аудит.', english: 'They carried out an audit', level: 'B2' },
  { russian: 'Я держал слово.', english: 'I kept my word', level: 'B2' },
  { russian: 'Он вёл переговоры два дня.', english: 'He led the negotiations for two days', level: 'B2' },
  { russian: 'Она упала духом после провала.', english: 'She lost heart after the failure', level: 'B2' },
  { russian: 'Мы приняли важное решение.', english: 'We made an important decision', level: 'B1' },
  { russian: 'Они привлекли новых партнёров.', english: 'They brought in new partners', level: 'B2' },
  { russian: 'Я расстался с партнёром.', english: 'I split with my partner', level: 'B2' },
  { russian: 'Он справился с трудной задачей.', english: 'He dealt with a difficult task', level: 'B2' },
  { russian: 'Она написала письмо директору.', english: 'She wrote a letter to the director', level: 'A2' },
  { russian: 'Мы выиграли тендер.', english: 'We won the tender', level: 'B2' },
  { russian: 'Они пришли к соглашению.', english: 'They came to an agreement', level: 'B2' },
  { russian: 'Я нашёл нужный контакт.', english: 'I found the right contact', level: 'B1' },
  { russian: 'Он сказал что-то важное.', english: 'He said something important', level: 'A2' },
  { russian: 'Она взяла дело в свои руки.', english: 'She took matters into her own hands', level: 'C1' },
  { russian: 'Мы продали последнюю партию.', english: 'We sold the last batch', level: 'B2' },
  { russian: 'Они прислали счёт на оплату.', english: 'They sent the invoice', level: 'B1' },
  { russian: 'Я поговорил с ним напрямую.', english: 'I spoke to him directly', level: 'B1' },
  { russian: 'Он забыл об этом совещании.', english: 'He forgot about this meeting', level: 'A2' },
  { russian: 'Она встала и ушла.', english: 'She stood up and left', level: 'A2' },
  { russian: 'Мы поняли свою ошибку.', english: 'We understood our mistake', level: 'B1' },
];

const L12_UK: any[] = [
  { russian: 'Я пішов до офісу вчора.', english: 'I went to the office yesterday', level: 'A2' },
  { russian: 'Вона побачила його на зустрічі.', english: 'She saw him at the meeting', level: 'B1' },
  { russian: 'Вони отримали новини вранці.', english: 'They got the news this morning', level: 'B1' },
  { russian: 'Він зробив велику помилку.', english: 'He made a big mistake', level: 'B1' },
  { russian: 'Ми взяли таксі додому.', english: 'We took a taxi home', level: 'A2' },
  { russian: 'Вона сказала мені правду.', english: 'She told me the truth', level: 'B1' },
  { russian: 'Я думав про це всю ніч.', english: 'I thought about it all night', level: 'B2' },
  { russian: 'Він дав мені важливу пораду.', english: 'He gave me important advice', level: 'B1' },
  { russian: 'Вона знайшла гарне рішення.', english: 'She found a good solution', level: 'B1' },
  { russian: 'Ми купили нове обладнання.', english: 'We bought new equipment', level: 'B1' },
  { russian: 'Вони прийшли на зустріч без попередження.', english: 'They came to the meeting without warning', level: 'B2' },
  { russian: 'Я знав про це заздалегідь.', english: 'I knew about this in advance', level: 'B1' },
  { russian: 'Він написав звіт за дві години.', english: 'He wrote the report in two hours', level: 'B1' },
  { russian: 'Вона обрала найкращий варіант.', english: 'She chose the best option', level: 'B1' },
  { russian: 'Ми зустріли директора на конференції.', english: 'We met the director at the conference', level: 'B1' },
  { russian: 'Вони навели хороші аргументи.', english: 'They put forward good arguments', level: 'B2' },
  { russian: 'Я залишив документи в офісі.', english: 'I left the documents in the office', level: 'A2' },
  { russian: 'Він зрозумів проблему одразу.', english: 'He understood the problem immediately', level: 'B1' },
  { russian: 'Вона провела чудову презентацію.', english: 'She gave an excellent presentation', level: 'B1' },
  { russian: 'Ми втратили контракт через помилку.', english: 'We lost the contract due to a mistake', level: 'B2' },
  { russian: 'Вони продали компанію минулого року.', english: 'They sold the company last year', level: 'B2' },
  { russian: 'Я поїхав на конференцію в Берлін.', english: 'I went to a conference in Berlin', level: 'B1' },
  { russian: 'Він став директором три роки тому.', english: 'He became director three years ago', level: 'B1' },
  { russian: 'Вона надіслала потрібні файли.', english: 'She sent the necessary files', level: 'B1' },
  { russian: 'Ми побудували хорошу команду.', english: 'We built a good team', level: 'B2' },
  { russian: 'Вони взяли кредит на розвиток.', english: 'They took a loan for development', level: 'B2' },
  { russian: 'Я чув про цю компанію раніше.', english: 'I heard about this company before', level: 'B1' },
  { russian: 'Він поїхав на переговори у Варшаву.', english: 'He went to negotiations in Warsaw', level: 'B1' },
  { russian: 'Вона привела клієнта на зустріч.', english: 'She brought the client to the meeting', level: 'B1' },
  { russian: 'Ми знайшли інвестора.', english: 'We found an investor', level: 'B1' },
  { russian: 'Вони провели аудит.', english: 'They carried out an audit', level: 'B2' },
  { russian: 'Я тримав слово.', english: 'I kept my word', level: 'B2' },
  { russian: 'Він вів переговори два дні.', english: 'He led the negotiations for two days', level: 'B2' },
  { russian: 'Вона впала духом після невдачі.', english: 'She lost heart after the failure', level: 'B2' },
  { russian: 'Ми прийняли важливе рішення.', english: 'We made an important decision', level: 'B1' },
  { russian: 'Вони залучили нових партнерів.', english: 'They brought in new partners', level: 'B2' },
  { russian: 'Я розійшовся з партнером.', english: 'I split with my partner', level: 'B2' },
  { russian: 'Він впорався зі складним завданням.', english: 'He dealt with a difficult task', level: 'B2' },
  { russian: 'Вона написала листа директору.', english: 'She wrote a letter to the director', level: 'A2' },
  { russian: 'Ми виграли тендер.', english: 'We won the tender', level: 'B2' },
  { russian: 'Вони дійшли угоди.', english: 'They came to an agreement', level: 'B2' },
  { russian: 'Я знайшов потрібний контакт.', english: 'I found the right contact', level: 'B1' },
  { russian: 'Він сказав щось важливе.', english: 'He said something important', level: 'A2' },
  { russian: 'Вона взяла справу у свої руки.', english: 'She took matters into her own hands', level: 'C1' },
  { russian: 'Ми продали останню партію.', english: 'We sold the last batch', level: 'B2' },
  { russian: 'Вони надіслали рахунок на оплату.', english: 'They sent the invoice', level: 'B1' },
  { russian: 'Я поговорив з ним напряму.', english: 'I spoke to him directly', level: 'B1' },
  { russian: 'Він забув про цю нараду.', english: 'He forgot about this meeting', level: 'A2' },
  { russian: 'Вона встала і пішла.', english: 'She stood up and left', level: 'A2' },
  { russian: 'Ми зрозуміли свою помилку.', english: 'We understood our mistake', level: 'B1' },
];

const L13_RU: any[] = [
  { russian: 'Я позвоню тебе завтра.', english: 'I will call you tomorrow', level: 'A2' },
  { russian: 'Она придёт на вечеринку.', english: 'She will come to the party', level: 'A2' },
  { russian: 'Они закончат проект вовремя.', english: 'They will finish the project on time', level: 'B1' },
  { russian: 'Он не опоздает.', english: 'He will not be late', level: 'B1' },
  { russian: 'Ты поможешь мне?', english: 'Will you help me', level: 'A2' },
  { russian: 'Мы обсудим это на встрече.', english: 'We will discuss it at the meeting', level: 'B1' },
  { russian: 'Я не забуду твой совет.', english: 'I will not forget your advice', level: 'B2' },
  { russian: 'Она отправит отчёт к пятнице.', english: 'She will send the report by Friday', level: 'B1' },
  { russian: 'Они не согласятся на это.', english: 'They will not agree to this', level: 'B1' },
  { russian: 'Ты придёшь на встречу?', english: 'Will you come to the meeting', level: 'A2' },
  { russian: 'Он подпишет контракт на следующей неделе.', english: 'He will sign the contract next week', level: 'B1' },
  { russian: 'Мы найдём решение.', english: 'We will find a solution', level: 'B1' },
  { russian: 'Она позвонит клиенту сегодня.', english: 'She will call the client today', level: 'A2' },
  { russian: 'Они откроют новый офис в следующем году.', english: 'They will open a new office next year', level: 'B1' },
  { russian: 'Я перезвоню тебе.', english: 'I will call you back', level: 'A2' },
  { russian: 'Он не примет это предложение.', english: 'He will not accept this offer', level: 'B1' },
  { russian: 'Она подготовит презентацию.', english: 'She will prepare the presentation', level: 'B1' },
  { russian: 'Мы не сможем встретиться в пятницу.', english: 'We will not be able to meet on Friday', level: 'B1' },
  { russian: 'Они расширят команду в этом квартале.', english: 'They will expand the team this quarter', level: 'B2' },
  { russian: 'Ты отправишь письмо?', english: 'Will you send the email', level: 'A2' },
  { russian: 'Я скажу тебе результат.', english: 'I will tell you the result', level: 'A2' },
  { russian: 'Он встретится с инвестором на следующей неделе.', english: 'He will meet the investor next week', level: 'B1' },
  { russian: 'Она не задержится.', english: 'She will not be delayed', level: 'B1' },
  { russian: 'Мы увеличим бюджет.', english: 'We will increase the budget', level: 'B2' },
  { russian: 'Они выйдут на новые рынки.', english: 'They will enter new markets', level: 'B2' },
  { russian: 'Я не уйду раньше пяти.', english: 'I will not leave before five', level: 'B1' },
  { russian: 'Он представит план на собрании.', english: 'He will present the plan at the meeting', level: 'B1' },
  { russian: 'Она уволится в конце месяца.', english: 'She will resign at the end of the month', level: 'B1' },
  { russian: 'Мы поговорим об этом позже.', english: 'We will talk about this later', level: 'A2' },
  { russian: 'Они не продлят контракт.', english: 'They will not renew the contract', level: 'B2' },
  { russian: 'Ты поддержишь это решение?', english: 'Will you support this decision', level: 'B1' },
  { russian: 'Я сообщу тебе о результатах.', english: 'I will let you know the results', level: 'B1' },
  { russian: 'Он проверит документы.', english: 'He will check the documents', level: 'A2' },
  { russian: 'Она разберётся с этим вопросом.', english: 'She will deal with this issue', level: 'B1' },
  { russian: 'Мы встретимся снова в следующем месяце.', english: 'We will meet again next month', level: 'A2' },
  { russian: 'Они запустят продукт в марте.', english: 'They will launch the product in March', level: 'B1' },
  { russian: 'Я не буду менять план.', english: 'I will not change the plan', level: 'B1' },
  { russian: 'Он возьмёт отпуск на следующей неделе.', english: 'He will take a holiday next week', level: 'A2' },
  { russian: 'Она будет ждать твоего звонка.', english: 'She will wait for your call', level: 'B1' },
  { russian: 'Мы выберем лучшего кандидата.', english: 'We will choose the best candidate', level: 'B1' },
  { russian: 'Они объявят о результатах завтра.', english: 'They will announce the results tomorrow', level: 'B1' },
  { russian: 'Ты будешь там?', english: 'Will you be there', level: 'A2' },
  { russian: 'Я сделаю всё возможное.', english: 'I will do everything possible', level: 'B1' },
  { russian: 'Он не согласится на меньшее.', english: 'He will not settle for less', level: 'B2' },
  { russian: 'Она ответит на все вопросы.', english: 'She will answer all the questions', level: 'B1' },
  { russian: 'Мы рассмотрим ваше предложение.', english: 'We will consider your proposal', level: 'B2' },
  { russian: 'Они не откажутся от сделки.', english: 'They will not turn down the deal', level: 'B2' },
  { russian: 'Ты подумаешь об этом?', english: 'Will you think about this', level: 'A2' },
  { russian: 'Я отвечу тебе сегодня.', english: 'I will reply to you today', level: 'A2' },
  { russian: 'Он пришлёт подтверждение.', english: 'He will send the confirmation', level: 'B1' },
];

const L13_UK: any[] = [
  { russian: 'Я зателефоную тобі завтра.', english: 'I will call you tomorrow', level: 'A2' },
  { russian: 'Вона прийде на вечірку.', english: 'She will come to the party', level: 'A2' },
  { russian: 'Вони закінчать проект вчасно.', english: 'They will finish the project on time', level: 'B1' },
  { russian: 'Він не запізниться.', english: 'He will not be late', level: 'B1' },
  { russian: 'Ти допоможеш мені?', english: 'Will you help me', level: 'A2' },
  { russian: 'Ми обговоримо це на зустрічі.', english: 'We will discuss it at the meeting', level: 'B1' },
  { russian: 'Я не забуду твою пораду.', english: 'I will not forget your advice', level: 'B2' },
  { russian: 'Вона надішле звіт до п\'ятниці.', english: 'She will send the report by Friday', level: 'B1' },
  { russian: 'Вони не погодяться на це.', english: 'They will not agree to this', level: 'B1' },
  { russian: 'Ти прийдеш на зустріч?', english: 'Will you come to the meeting', level: 'A2' },
  { russian: 'Він підпише контракт наступного тижня.', english: 'He will sign the contract next week', level: 'B1' },
  { russian: 'Ми знайдемо рішення.', english: 'We will find a solution', level: 'B1' },
  { russian: 'Вона зателефонує клієнту сьогодні.', english: 'She will call the client today', level: 'A2' },
  { russian: 'Вони відкриють новий офіс наступного року.', english: 'They will open a new office next year', level: 'B1' },
  { russian: 'Я передзвоню тобі.', english: 'I will call you back', level: 'A2' },
  { russian: 'Він не прийме цю пропозицію.', english: 'He will not accept this offer', level: 'B1' },
  { russian: 'Вона підготує презентацію.', english: 'She will prepare the presentation', level: 'B1' },
  { russian: 'Ми не зможемо зустрітися в п\'ятницю.', english: 'We will not be able to meet on Friday', level: 'B1' },
  { russian: 'Вони розширять команду в цьому кварталі.', english: 'They will expand the team this quarter', level: 'B2' },
  { russian: 'Ти надішлеш листа?', english: 'Will you send the email', level: 'A2' },
  { russian: 'Я скажу тобі результат.', english: 'I will tell you the result', level: 'A2' },
  { russian: 'Він зустрінеться з інвестором наступного тижня.', english: 'He will meet the investor next week', level: 'B1' },
  { russian: 'Вона не затримається.', english: 'She will not be delayed', level: 'B1' },
  { russian: 'Ми збільшимо бюджет.', english: 'We will increase the budget', level: 'B2' },
  { russian: 'Вони вийдуть на нові ринки.', english: 'They will enter new markets', level: 'B2' },
  { russian: 'Я не піду раніше п\'ятої.', english: 'I will not leave before five', level: 'B1' },
  { russian: 'Він представить план на зборах.', english: 'He will present the plan at the meeting', level: 'B1' },
  { russian: 'Вона звільниться в кінці місяця.', english: 'She will resign at the end of the month', level: 'B1' },
  { russian: 'Ми поговоримо про це пізніше.', english: 'We will talk about this later', level: 'A2' },
  { russian: 'Вони не продовжать контракт.', english: 'They will not renew the contract', level: 'B2' },
  { russian: 'Ти підтримаєш це рішення?', english: 'Will you support this decision', level: 'B1' },
  { russian: 'Я повідомлю тебе про результати.', english: 'I will let you know the results', level: 'B1' },
  { russian: 'Він перевірить документи.', english: 'He will check the documents', level: 'A2' },
  { russian: 'Вона розбереться з цим питанням.', english: 'She will deal with this issue', level: 'B1' },
  { russian: 'Ми зустрінемося знову наступного місяця.', english: 'We will meet again next month', level: 'A2' },
  { russian: 'Вони запустять продукт у березні.', english: 'They will launch the product in March', level: 'B1' },
  { russian: 'Я не буду змінювати план.', english: 'I will not change the plan', level: 'B1' },
  { russian: 'Він піде у відпустку наступного тижня.', english: 'He will take a holiday next week', level: 'A2' },
  { russian: 'Вона буде чекати твого дзвінка.', english: 'She will wait for your call', level: 'B1' },
  { russian: 'Ми оберемо найкращого кандидата.', english: 'We will choose the best candidate', level: 'B1' },
  { russian: 'Вони оголосять результати завтра.', english: 'They will announce the results tomorrow', level: 'B1' },
  { russian: 'Ти будеш там?', english: 'Will you be there', level: 'A2' },
  { russian: 'Я зроблю все можливе.', english: 'I will do everything possible', level: 'B1' },
  { russian: 'Він не погодиться на менше.', english: 'He will not settle for less', level: 'B2' },
  { russian: 'Вона відповість на всі питання.', english: 'She will answer all the questions', level: 'B1' },
  { russian: 'Ми розглянемо вашу пропозицію.', english: 'We will consider your proposal', level: 'B2' },
  { russian: 'Вони не відмовляться від угоди.', english: 'They will not turn down the deal', level: 'B2' },
  { russian: 'Ти подумаєш про це?', english: 'Will you think about this', level: 'A2' },
  { russian: 'Я відповім тобі сьогодні.', english: 'I will reply to you today', level: 'A2' },
  { russian: 'Він надішле підтвердження.', english: 'He will send the confirmation', level: 'B1' },
];

const L14_RU: any[] = [
  { russian: 'Этот отель больше другого.', english: 'This hotel is bigger than the other one', level: 'A2' },
  { russian: 'Она более опытная, чем он.', english: 'She is more experienced than him', level: 'B1' },
  { russian: 'Он работает усерднее всех.', english: 'He works harder than anyone else', level: 'B1' },
  { russian: 'Это самый важный проект года.', english: 'It is the most important project of the year', level: 'B2' },
  { russian: 'Мой телефон дешевле твоего.', english: 'My phone is cheaper than yours', level: 'A2' },
  { russian: 'Новый офис лучше старого.', english: 'The new office is better than the old one', level: 'A2' },
  { russian: 'Этот маршрут короче.', english: 'This route is shorter', level: 'A2' },
  { russian: 'Она говорит по-английски лучше меня.', english: 'She speaks English better than me', level: 'B1' },
  { russian: 'Это худшее решение из всех возможных.', english: 'It is the worst decision of all', level: 'B2' },
  { russian: 'Этот вариант дороже.', english: 'This option is more expensive', level: 'A2' },
  { russian: 'Он самый компетентный в команде.', english: 'He is the most competent person in the team', level: 'B1' },
  { russian: 'Новый продукт более популярен, чем старый.', english: 'The new product is more popular than the old one', level: 'B1' },
  { russian: 'Это самый большой контракт в истории компании.', english: 'It is the biggest contract in the company\'s history', level: 'B2' },
  { russian: 'Встреча прошла лучше, чем ожидалось.', english: 'The meeting went better than expected', level: 'B1' },
  { russian: 'Этот маршрут намного длиннее.', english: 'This route is much longer', level: 'A2' },
  { russian: 'Новое программное обеспечение более удобное.', english: 'The new software is more convenient', level: 'B1' },
  { russian: 'Это самое быстрое соединение в офисе.', english: 'It is the fastest connection in the office', level: 'B1' },
  { russian: 'Она более профессиональна, чем я ожидал.', english: 'She is more professional than I expected', level: 'B2' },
  { russian: 'Это лучший кофе, который я пробовал.', english: 'It is the best coffee I have ever tried', level: 'B1' },
  { russian: 'Переговоры прошли хуже, чем планировалось.', english: 'The negotiations went worse than planned', level: 'B2' },
  { russian: 'Этот кандидат более квалифицированный.', english: 'This candidate is more qualified', level: 'B1' },
  { russian: 'Старый способ был проще.', english: 'The old way was simpler', level: 'A2' },
  { russian: 'Он самый опытный в отделе.', english: 'He is the most experienced person in the department', level: 'B1' },
  { russian: 'Это самое дорогое предложение.', english: 'It is the most expensive offer', level: 'A2' },
  { russian: 'Второй вариант более реалистичен.', english: 'The second option is more realistic', level: 'B2' },
  { russian: 'Рынок стал более конкурентным.', english: 'The market has become more competitive', level: 'B2' },
  { russian: 'Их продукт лучше нашего.', english: 'Their product is better than ours', level: 'B1' },
  { russian: 'Это самый короткий путь к офису.', english: 'It is the shortest way to the office', level: 'A2' },
  { russian: 'Этот квартал был хуже прошлого.', english: 'This quarter was worse than the last one', level: 'B2' },
  { russian: 'Она более организована, чем её коллеги.', english: 'She is more organised than her colleagues', level: 'B1' },
  { russian: 'Новый офис намного больше.', english: 'The new office is much bigger', level: 'A2' },
  { russian: 'Это самое выгодное предложение на рынке.', english: 'It is the most advantageous offer on the market', level: 'B2' },
  { russian: 'Наш сервис лучше, чем у конкурентов.', english: "Our service is better than our competitors'", level: 'B2' },
  { russian: 'Этот проект сложнее предыдущего.', english: 'This project is more complex than the previous one', level: 'B1' },
  { russian: 'Он говорит по-английски хуже, чем она.', english: 'He speaks English worse than she does', level: 'B1' },
  { russian: 'Это самый эффективный метод.', english: 'It is the most effective method', level: 'B2' },
  { russian: 'Первый вариант лучше второго.', english: 'The first option is better than the second', level: 'A2' },
  { russian: 'Новый менеджер более строгий.', english: 'The new manager is stricter', level: 'B1' },
  { russian: 'Эта конференция более важная, чем прошлая.', english: 'This conference is more important than the last one', level: 'B1' },
  { russian: 'Наша команда сильнее, чем в прошлом году.', english: 'Our team is stronger than last year', level: 'B1' },
  { russian: 'Это наименее рискованный вариант.', english: 'It is the least risky option', level: 'B2' },
  { russian: 'Новая система быстрее старой.', english: 'The new system is faster than the old one', level: 'B1' },
  { russian: 'Проект оказался дороже, чем ожидалось.', english: 'The project turned out more expensive than expected', level: 'B2' },
  { russian: 'Это самый длинный контракт в нашей практике.', english: 'It is the longest contract in our practice', level: 'B2' },
  { russian: 'Её презентация была лучше моей.', english: 'Her presentation was better than mine', level: 'B1' },
  { russian: 'Этот офис более современный.', english: 'This office is more modern', level: 'A2' },
  { russian: 'Он менее опытный, чем другие кандидаты.', english: 'He is less experienced than the other candidates', level: 'B2' },
  { russian: 'Эта задача намного сложнее.', english: 'This task is much more difficult', level: 'B1' },
  { russian: 'Лучший способ — поговорить с ним напрямую.', english: 'The best way is to speak to him directly', level: 'B2' },
  { russian: 'Этот контракт выгоднее предыдущего.', english: 'This contract is more favourable than the previous one', level: 'B2' },
];

const L14_UK: any[] = [
  { russian: 'Цей готель більший за інший.', english: 'This hotel is bigger than the other one', level: 'A2' },
  { russian: 'Вона більш досвідчена, ніж він.', english: 'She is more experienced than him', level: 'B1' },
  { russian: 'Він працює наполегливіше за всіх.', english: 'He works harder than anyone else', level: 'B1' },
  { russian: 'Це найважливіший проект року.', english: 'It is the most important project of the year', level: 'B2' },
  { russian: 'Мій телефон дешевший за твій.', english: 'My phone is cheaper than yours', level: 'A2' },
  { russian: 'Новий офіс кращий за старий.', english: 'The new office is better than the old one', level: 'A2' },
  { russian: 'Цей маршрут коротший.', english: 'This route is shorter', level: 'A2' },
  { russian: 'Вона розмовляє англійською краще за мене.', english: 'She speaks English better than me', level: 'B1' },
  { russian: 'Це найгірше рішення з усіх можливих.', english: 'It is the worst decision of all', level: 'B2' },
  { russian: 'Цей варіант дорожчий.', english: 'This option is more expensive', level: 'A2' },
  { russian: 'Він найкомпетентніший у команді.', english: 'He is the most competent person in the team', level: 'B1' },
  { russian: 'Новий продукт популярніший за старий.', english: 'The new product is more popular than the old one', level: 'B1' },
  { russian: 'Це найбільший контракт в історії компанії.', english: 'It is the biggest contract in the company\'s history', level: 'B2' },
  { russian: 'Зустріч пройшла краще, ніж очікувалося.', english: 'The meeting went better than expected', level: 'B1' },
  { russian: 'Цей маршрут набагато довший.', english: 'This route is much longer', level: 'A2' },
  { russian: 'Нове програмне забезпечення зручніше.', english: 'The new software is more convenient', level: 'B1' },
  { russian: 'Це найшвидше з\'єднання в офісі.', english: 'It is the fastest connection in the office', level: 'B1' },
  { russian: 'Вона більш професійна, ніж я очікував.', english: 'She is more professional than I expected', level: 'B2' },
  { russian: 'Це найкраща кава, яку я пробував.', english: 'It is the best coffee I have ever tried', level: 'B1' },
  { russian: 'Переговори пройшли гірше, ніж планувалося.', english: 'The negotiations went worse than planned', level: 'B2' },
  { russian: 'Цей кандидат більш кваліфікований.', english: 'This candidate is more qualified', level: 'B1' },
  { russian: 'Старий спосіб був простішим.', english: 'The old way was simpler', level: 'A2' },
  { russian: 'Він найдосвідченіший у відділі.', english: 'He is the most experienced person in the department', level: 'B1' },
  { russian: 'Це найдорожча пропозиція.', english: 'It is the most expensive offer', level: 'A2' },
  { russian: 'Другий варіант реалістичніший.', english: 'The second option is more realistic', level: 'B2' },
  { russian: 'Ринок став більш конкурентним.', english: 'The market has become more competitive', level: 'B2' },
  { russian: 'Їхній продукт кращий за наш.', english: 'Their product is better than ours', level: 'B1' },
  { russian: 'Це найкоротший шлях до офісу.', english: 'It is the shortest way to the office', level: 'A2' },
  { russian: 'Цей квартал був гіршим за попередній.', english: 'This quarter was worse than the last one', level: 'B2' },
  { russian: 'Вона більш організована, ніж її колеги.', english: 'She is more organised than her colleagues', level: 'B1' },
  { russian: 'Новий офіс набагато більший.', english: 'The new office is much bigger', level: 'A2' },
  { russian: 'Це найвигідніша пропозиція на ринку.', english: 'It is the most advantageous offer on the market', level: 'B2' },
  { russian: 'Наш сервіс кращий, ніж у конкурентів.', english: "Our service is better than our competitors'", level: 'B2' },
  { russian: 'Цей проект складніший за попередній.', english: 'This project is more complex than the previous one', level: 'B1' },
  { russian: 'Він розмовляє англійською гірше, ніж вона.', english: 'He speaks English worse than she does', level: 'B1' },
  { russian: 'Це найефективніший метод.', english: 'It is the most effective method', level: 'B2' },
  { russian: 'Перший варіант кращий за другий.', english: 'The first option is better than the second', level: 'A2' },
  { russian: 'Новий менеджер суворіший.', english: 'The new manager is stricter', level: 'B1' },
  { russian: 'Ця конференція важливіша за минулу.', english: 'This conference is more important than the last one', level: 'B1' },
  { russian: 'Наша команда сильніша, ніж торік.', english: 'Our team is stronger than last year', level: 'B1' },
  { russian: 'Це найменш ризикований варіант.', english: 'It is the least risky option', level: 'B2' },
  { russian: 'Нова система швидша за стару.', english: 'The new system is faster than the old one', level: 'B1' },
  { russian: 'Проект виявився дорожчим, ніж очікувалося.', english: 'The project turned out more expensive than expected', level: 'B2' },
  { russian: 'Це найдовший контракт у нашій практиці.', english: 'It is the longest contract in our practice', level: 'B2' },
  { russian: 'Її презентація була кращою за мою.', english: 'Her presentation was better than mine', level: 'B1' },
  { russian: 'Цей офіс більш сучасний.', english: 'This office is more modern', level: 'A2' },
  { russian: 'Він менш досвідчений, ніж інші кандидати.', english: 'He is less experienced than the other candidates', level: 'B2' },
  { russian: 'Це завдання набагато складніше.', english: 'This task is much more difficult', level: 'B1' },
  { russian: 'Найкращий спосіб — поговорити з ним напряму.', english: 'The best way is to speak to him directly', level: 'B2' },
  { russian: 'Цей контракт вигідніший за попередній.', english: 'This contract is more favourable than the previous one', level: 'B2' },
];

const L15_RU: any[] = [
  { russian: 'Это моя книга.', english: 'This is my book', level: 'A2' },
  { russian: 'Это твоё?', english: 'Is this yours', level: 'A2' },
  { russian: 'Та машина её.', english: 'That car is hers', level: 'B1' },
  { russian: 'Решение за нами.', english: 'The decision is ours', level: 'B1' },
  { russian: 'Их идея была лучше нашей.', english: 'Their idea was better than ours', level: 'B2' },
  { russian: 'Это не его проблема.', english: 'It is not his problem', level: 'A2' },
  { russian: 'Успех принадлежит всей команде.', english: 'The success belongs to the whole team', level: 'B1' },
  { russian: 'Это мой проект.', english: 'This is my project', level: 'A2' },
  { russian: 'Чья это идея?', english: 'Whose idea is this', level: 'A2' },
  { russian: 'Это наш клиент.', english: 'This is our client', level: 'A2' },
  { russian: 'Эта должность его.', english: 'This position is his', level: 'B1' },
  { russian: 'Ошибка наша.', english: 'The mistake is ours', level: 'B1' },
  { russian: 'Это её отдел.', english: 'This is her department', level: 'A2' },
  { russian: 'Результаты — ваши.', english: 'The results are yours', level: 'B1' },
  { russian: 'Это их офис.', english: 'This is their office', level: 'A2' },
  { russian: 'Компьютер на столе твой.', english: 'The computer on the desk is yours', level: 'B1' },
  { russian: 'Это наш договор.', english: 'This is our agreement', level: 'A2' },
  { russian: 'Этот успех заслуживает быть вашим.', english: 'This success deserves to be yours', level: 'B2' },
  { russian: 'Это его решение, не моё.', english: 'It is his decision not mine', level: 'B1' },
  { russian: 'Этот отчёт — её работа.', english: 'This report is her work', level: 'B1' },
  { russian: 'Это ваш запрос.', english: 'This is your request', level: 'A2' },
  { russian: 'Эта идея была их, а не нашей.', english: 'This idea was theirs not ours', level: 'B2' },
  { russian: 'Мой телефон разрядился.', english: 'My phone is dead', level: 'A2' },
  { russian: 'Это её последнее слово.', english: 'This is her final word', level: 'B1' },
  { russian: 'Этот контракт принадлежит нам.', english: 'This contract belongs to us', level: 'B1' },
  { russian: 'Их бюджет больше нашего.', english: 'Their budget is bigger than ours', level: 'B1' },
  { russian: 'Это твой звонок.', english: 'This is your call', level: 'B1' },
  { russian: 'Вина не наша.', english: 'The fault is not ours', level: 'B2' },
  { russian: 'Этот проект стал нашим.', english: 'This project became ours', level: 'B1' },
  { russian: 'Успех всегда твой.', english: 'The success is always yours', level: 'B2' },
  { russian: 'Это его территория.', english: 'This is his territory', level: 'B1' },
  { russian: 'Этот контакт — её.', english: 'This contact is hers', level: 'B1' },
  { russian: 'Чья очередь платить?', english: 'Whose turn is it to pay', level: 'A2' },
  { russian: 'Это их дело.', english: 'This is their business', level: 'B1' },
  { russian: 'Мой вариант лучше.', english: 'My option is better', level: 'A2' },
  { russian: 'Это наша ответственность.', english: 'This is our responsibility', level: 'B1' },
  { russian: 'Этот офис — ваш.', english: 'This office is yours', level: 'A2' },
  { russian: 'Их подход отличается от нашего.', english: 'Their approach is different from ours', level: 'B2' },
  { russian: 'Это её достижение.', english: 'This is her achievement', level: 'B1' },
  { russian: 'Это мой первый проект.', english: 'This is my first project', level: 'A2' },
  { russian: 'Ответственность за это — его.', english: 'The responsibility for this is his', level: 'B2' },
  { russian: 'Это наш шанс.', english: 'This is our chance', level: 'B1' },
  { russian: 'Чья это ошибка?', english: 'Whose mistake is this', level: 'A2' },
  { russian: 'Этот успех тоже наш.', english: 'This success is ours too', level: 'B1' },
  { russian: 'Я дал ему свой совет.', english: 'I gave him my advice', level: 'B1' },
  { russian: 'Их стратегия отличается от нашей.', english: 'Their strategy differs from ours', level: 'B2' },
  { russian: 'Это её лучший результат.', english: 'This is her best result', level: 'B1' },
  { russian: 'Этот вопрос — твой.', english: 'This question is yours', level: 'A2' },
  { russian: 'Его мнение отличается от моего.', english: 'His opinion is different from mine', level: 'B2' },
  { russian: 'Это ваше решение, а не наше.', english: 'This is your decision not ours', level: 'B2' },
];

const L15_UK: any[] = [
  { russian: 'Це моя книга.', english: 'This is my book', level: 'A2' },
  { russian: 'Це твоє?', english: 'Is this yours', level: 'A2' },
  { russian: 'Та машина її.', english: 'That car is hers', level: 'B1' },
  { russian: 'Рішення за нами.', english: 'The decision is ours', level: 'B1' },
  { russian: 'Їхня ідея була кращою за нашу.', english: 'Their idea was better than ours', level: 'B2' },
  { russian: 'Це не його проблема.', english: 'It is not his problem', level: 'A2' },
  { russian: 'Успіх належить всій команді.', english: 'The success belongs to the whole team', level: 'B1' },
  { russian: 'Це мій проект.', english: 'This is my project', level: 'A2' },
  { russian: 'Чия це ідея?', english: 'Whose idea is this', level: 'A2' },
  { russian: 'Це наш клієнт.', english: 'This is our client', level: 'A2' },
  { russian: 'Ця посада його.', english: 'This position is his', level: 'B1' },
  { russian: 'Помилка наша.', english: 'The mistake is ours', level: 'B1' },
  { russian: 'Це її відділ.', english: 'This is her department', level: 'A2' },
  { russian: 'Результати — ваші.', english: 'The results are yours', level: 'B1' },
  { russian: 'Це їхній офіс.', english: 'This is their office', level: 'A2' },
  { russian: 'Комп\'ютер на столі твій.', english: 'The computer on the desk is yours', level: 'B1' },
  { russian: 'Це наш договір.', english: 'This is our agreement', level: 'A2' },
  { russian: 'Цей успіх заслуговує бути вашим.', english: 'This success deserves to be yours', level: 'B2' },
  { russian: 'Це його рішення, не моє.', english: 'It is his decision not mine', level: 'B1' },
  { russian: 'Цей звіт — її робота.', english: 'This report is her work', level: 'B1' },
  { russian: 'Це ваш запит.', english: 'This is your request', level: 'A2' },
  { russian: 'Ця ідея була їхня, а не наша.', english: 'This idea was theirs not ours', level: 'B2' },
  { russian: 'Мій телефон розрядився.', english: 'My phone is dead', level: 'A2' },
  { russian: 'Це її останнє слово.', english: 'This is her final word', level: 'B1' },
  { russian: 'Цей контракт належить нам.', english: 'This contract belongs to us', level: 'B1' },
  { russian: 'Їхній бюджет більший за наш.', english: 'Their budget is bigger than ours', level: 'B1' },
  { russian: 'Це твій дзвінок.', english: 'This is your call', level: 'B1' },
  { russian: 'Вина не наша.', english: 'The fault is not ours', level: 'B2' },
  { russian: 'Цей проект став нашим.', english: 'This project became ours', level: 'B1' },
  { russian: 'Успіх завжди твій.', english: 'The success is always yours', level: 'B2' },
  { russian: 'Це його територія.', english: 'This is his territory', level: 'B1' },
  { russian: 'Цей контакт — її.', english: 'This contact is hers', level: 'B1' },
  { russian: 'Чия черга платити?', english: 'Whose turn is it to pay', level: 'A2' },
  { russian: 'Це їхня справа.', english: 'This is their business', level: 'B1' },
  { russian: 'Мій варіант кращий.', english: 'My option is better', level: 'A2' },
  { russian: 'Це наша відповідальність.', english: 'This is our responsibility', level: 'B1' },
  { russian: 'Цей офіс — ваш.', english: 'This office is yours', level: 'A2' },
  { russian: 'Їхній підхід відрізняється від нашого.', english: 'Their approach is different from ours', level: 'B2' },
  { russian: 'Це її досягнення.', english: 'This is her achievement', level: 'B1' },
  { russian: 'Це мій перший проект.', english: 'This is my first project', level: 'A2' },
  { russian: 'Відповідальність за це — його.', english: 'The responsibility for this is his', level: 'B2' },
  { russian: 'Це наш шанс.', english: 'This is our chance', level: 'B1' },
  { russian: 'Чия це помилка?', english: 'Whose mistake is this', level: 'A2' },
  { russian: 'Цей успіх теж наш.', english: 'This success is ours too', level: 'B1' },
  { russian: 'Я дав йому свою пораду.', english: 'I gave him my advice', level: 'B1' },
  { russian: 'Їхня стратегія відрізняється від нашої.', english: 'Their strategy differs from ours', level: 'B2' },
  { russian: 'Це її найкращий результат.', english: 'This is her best result', level: 'B1' },
  { russian: 'Це твоє питання.', english: 'This question is yours', level: 'A2' },
  { russian: 'Його думка відрізняється від моєї.', english: 'His opinion is different from mine', level: 'B2' },
  { russian: 'Це ваше рішення, а не наше.', english: 'This is your decision not ours', level: 'B2' },
];

const L16_RU: any[] = [
  { russian: 'Я бросил курить в прошлом году.', english: 'I gave up smoking last year', level: 'B1' },
  { russian: 'Она заботится о своих родителях.', english: 'She looks after her parents', level: 'B1' },
  { russian: 'Ты можешь узнать детали?', english: 'Can you find out the details', level: 'B1' },
  { russian: 'Он перенёс встречу на четверг.', english: 'He put off the meeting until Thursday', level: 'B2' },
  { russian: 'Я с нетерпением жду выходных.', english: 'I am looking forward to the weekend', level: 'B1' },
  { russian: 'Она наткнулась на интересную статью.', english: 'She came across an interesting article', level: 'B2' },
  { russian: 'Они основали новую компанию в прошлом году.', english: 'They set up a new company last year', level: 'B2' },
  { russian: 'Он справился с задачей.', english: 'He got through the task', level: 'B1' },
  { russian: 'Я не могу разобраться с этой проблемой.', english: 'I cannot figure out this problem', level: 'B1' },
  { russian: 'Она не сдалась, несмотря на трудности.', english: 'She did not give up despite the difficulties', level: 'B2' },
  { russian: 'Мы выяснили причину сбоя.', english: 'We found out the reason for the failure', level: 'B2' },
  { russian: 'Он выключил компьютер после работы.', english: 'He turned off the computer after work', level: 'B1' },
  { russian: 'Она взяла на себя ответственность.', english: 'She took on the responsibility', level: 'B2' },
  { russian: 'Мы продолжаем, несмотря на проблемы.', english: 'We are carrying on despite the problems', level: 'B2' },
  { russian: 'Он прочитал отчёт перед встречей.', english: 'He went through the report before the meeting', level: 'B1' },
  { russian: 'Я отложил поездку до следующего квартала.', english: 'I put off the trip until next quarter', level: 'B2' },
  { russian: 'Она ладит со всеми коллегами.', english: 'She gets on with all her colleagues', level: 'B1' },
  { russian: 'Мы столкнулись с неожиданной проблемой.', english: 'We came up against an unexpected problem', level: 'B2' },
  { russian: 'Он принял кандидата на работу.', english: 'He took on the candidate', level: 'B1' },
  { russian: 'Она разобрала все пункты договора.', english: 'She went through all the clauses of the contract', level: 'B2' },
  { russian: 'Мы выяснили, что произошло.', english: 'We found out what happened', level: 'B1' },
  { russian: 'Он подал заявку вовремя.', english: 'He handed in his application on time', level: 'B1' },
  { russian: 'Она установила новое приложение.', english: 'She set up the new application', level: 'B1' },
  { russian: 'Мы разработали новую стратегию.', english: 'We came up with a new strategy', level: 'B2' },
  { russian: 'Он постепенно привык к новой роли.', english: 'He gradually got used to the new role', level: 'C1' },
  { russian: 'Она ушла с работы после конфликта.', english: 'She walked out after the conflict', level: 'B2' },
  { russian: 'Мы отложили запуск продукта.', english: 'We put off the product launch', level: 'B2' },
  { russian: 'Он поднял тему на совещании.', english: 'He brought up the topic at the meeting', level: 'B2' },
  { russian: 'Она отказалась от предложения.', english: 'She turned down the offer', level: 'B2' },
  { russian: 'Мы справились с кризисом.', english: 'We got through the crisis', level: 'B2' },
  { russian: 'Он пришёл в себя после болезни.', english: 'He got over the illness', level: 'B1' },
  { russian: 'Она рассчитывает на поддержку команды.', english: 'She is counting on the team\'s support', level: 'B2' },
  { russian: 'Мы занимаемся этим вопросом.', english: 'We are looking into this matter', level: 'B2' },
  { russian: 'Он включил проектор.', english: 'He turned on the projector', level: 'B1' },
  { russian: 'Она вернула долг вовремя.', english: 'She paid back the debt on time', level: 'B2' },
  { russian: 'Мы обнаружили ошибку в контракте.', english: 'We came across an error in the contract', level: 'B2' },
  { russian: 'Он поднял зарплату сотрудникам.', english: 'He put up the salaries of the employees', level: 'C1' },
  { russian: 'Она продолжает улучшать свой английский.', english: 'She keeps on improving her English', level: 'B1' },
  { russian: 'Мы убрали ненужные пункты.', english: 'We crossed out the unnecessary points', level: 'B2' },
  { russian: 'Он занялся новым проектом.', english: 'He took on a new project', level: 'B1' },
  { russian: 'Она наблюдала за ситуацией.', english: 'She was keeping an eye on the situation', level: 'C1' },
  { russian: 'Мы встретились случайно.', english: 'We ran into each other by chance', level: 'B1' },
  { russian: 'Он снова откладывает всё.', english: 'He keeps putting everything off', level: 'B2' },
  { russian: 'Она забрала документы из офиса.', english: 'She picked up the documents from the office', level: 'B1' },
  { russian: 'Мы рассмотрели их предложение.', english: 'We looked into their proposal', level: 'B2' },
  { russian: 'Он поддержал инициативу коллег.', english: 'He backed up his colleagues\' initiative', level: 'B2' },
  { russian: 'Она примирилась с ситуацией.', english: 'She came to terms with the situation', level: 'C1' },
  { russian: 'Мы сдали проект вовремя.', english: 'We handed in the project on time', level: 'B1' },
  { russian: 'Он зашёл на чашку кофе.', english: 'He dropped in for a cup of coffee', level: 'B1' },
  { russian: 'Она наладила контакт с клиентом.', english: 'She built up a relationship with the client', level: 'C1' },
];

const L16_UK: any[] = [
  { russian: 'Я кинув курити минулого року.', english: 'I gave up smoking last year', level: 'B1' },
  { russian: 'Вона доглядає за своїми батьками.', english: 'She looks after her parents', level: 'B1' },
  { russian: 'Ти можеш дізнатися деталі?', english: 'Can you find out the details', level: 'B1' },
  { russian: 'Він переніс зустріч на четвер.', english: 'He put off the meeting until Thursday', level: 'B2' },
  { russian: 'Я з нетерпінням чекаю вихідних.', english: 'I am looking forward to the weekend', level: 'B1' },
  { russian: 'Вона натрапила на цікаву статтю.', english: 'She came across an interesting article', level: 'B2' },
  { russian: 'Вони заснували нову компанію минулого року.', english: 'They set up a new company last year', level: 'B2' },
  { russian: 'Він впорався із завданням.', english: 'He got through the task', level: 'B1' },
  { russian: 'Я не можу розібратися з цією проблемою.', english: 'I cannot figure out this problem', level: 'B1' },
  { russian: 'Вона не здалась, попри труднощі.', english: 'She did not give up despite the difficulties', level: 'B2' },
  { russian: 'Ми з\'ясували причину збою.', english: 'We found out the reason for the failure', level: 'B2' },
  { russian: 'Він вимкнув комп\'ютер після роботи.', english: 'He turned off the computer after work', level: 'B1' },
  { russian: 'Вона взяла на себе відповідальність.', english: 'She took on the responsibility', level: 'B2' },
  { russian: 'Ми продовжуємо, попри проблеми.', english: 'We are carrying on despite the problems', level: 'B2' },
  { russian: 'Він переглянув звіт перед зустріччю.', english: 'He went through the report before the meeting', level: 'B1' },
  { russian: 'Я відклав поїздку до наступного кварталу.', english: 'I put off the trip until next quarter', level: 'B2' },
  { russian: 'Вона ладнає з усіма колегами.', english: 'She gets on with all her colleagues', level: 'B1' },
  { russian: 'Ми зіштовхнулися з несподіваною проблемою.', english: 'We came up against an unexpected problem', level: 'B2' },
  { russian: 'Він прийняв кандидата на роботу.', english: 'He took on the candidate', level: 'B1' },
  { russian: 'Вона розібрала всі пункти договору.', english: 'She went through all the clauses of the contract', level: 'B2' },
  { russian: 'Ми з\'ясували, що сталося.', english: 'We found out what happened', level: 'B1' },
  { russian: 'Він подав заявку вчасно.', english: 'He handed in his application on time', level: 'B1' },
  { russian: 'Вона встановила новий додаток.', english: 'She set up the new application', level: 'B1' },
  { russian: 'Ми розробили нову стратегію.', english: 'We came up with a new strategy', level: 'B2' },
  { russian: 'Він поступово звик до нової ролі.', english: 'He gradually got used to the new role', level: 'C1' },
  { russian: 'Вона пішла з роботи після конфлікту.', english: 'She walked out after the conflict', level: 'B2' },
  { russian: 'Ми відклали запуск продукту.', english: 'We put off the product launch', level: 'B2' },
  { russian: 'Він підняв тему на нараді.', english: 'He brought up the topic at the meeting', level: 'B2' },
  { russian: 'Вона відмовилась від пропозиції.', english: 'She turned down the offer', level: 'B2' },
  { russian: 'Ми впоралися з кризою.', english: 'We got through the crisis', level: 'B2' },
  { russian: 'Він одужав після хвороби.', english: 'He got over the illness', level: 'B1' },
  { russian: 'Вона розраховує на підтримку команди.', english: 'She is counting on the team\'s support', level: 'B2' },
  { russian: 'Ми займаємося цим питанням.', english: 'We are looking into this matter', level: 'B2' },
  { russian: 'Він увімкнув проектор.', english: 'He turned on the projector', level: 'B1' },
  { russian: 'Вона повернула борг вчасно.', english: 'She paid back the debt on time', level: 'B2' },
  { russian: 'Ми виявили помилку в контракті.', english: 'We came across an error in the contract', level: 'B2' },
  { russian: 'Він підвищив зарплату співробітникам.', english: 'He put up the salaries of the employees', level: 'C1' },
  { russian: 'Вона продовжує покращувати свою англійську.', english: 'She keeps on improving her English', level: 'B1' },
  { russian: 'Ми вилучили зайві пункти.', english: 'We crossed out the unnecessary points', level: 'B2' },
  { russian: 'Він зайнявся новим проектом.', english: 'He took on a new project', level: 'B1' },
  { russian: 'Вона стежила за ситуацією.', english: 'She was keeping an eye on the situation', level: 'C1' },
  { russian: 'Ми зустрілися випадково.', english: 'We ran into each other by chance', level: 'B1' },
  { russian: 'Він знову відкладає все.', english: 'He keeps putting everything off', level: 'B2' },
  { russian: 'Вона забрала документи з офісу.', english: 'She picked up the documents from the office', level: 'B1' },
  { russian: 'Ми розглянули їхню пропозицію.', english: 'We looked into their proposal', level: 'B2' },
  { russian: 'Він підтримав ініціативу колег.', english: 'He backed up his colleagues\' initiative', level: 'B2' },
  { russian: 'Вона змирилася з ситуацією.', english: 'She came to terms with the situation', level: 'C1' },
  { russian: 'Ми здали проект вчасно.', english: 'We handed in the project on time', level: 'B1' },
  { russian: 'Він зайшов на каву.', english: 'He dropped in for a cup of coffee', level: 'B1' },
  { russian: 'Вона налагодила контакт з клієнтом.', english: 'She built up a relationship with the client', level: 'C1' },
];
