import type { LessonIntroScreen } from './lesson_data_types';

export const LESSON_2_INTRO_SCREENS: LessonIntroScreen[] = [
  {
    lessonId: 2,
    screenId: 'lesson_2_intro_1_negative',
    order: 1,
    kind: 'concept',
    titleRU: 'Отрицание с To Be',
    titleUK: 'Заперечення з To Be',
    titleES: 'How to say "not" with To Be',
    subtitleRU: 'В этом уроке ты добавляешь not после am / is / are.',
    subtitleUK: 'У цьому уроці ти додаєш not після am / is / are.',
    subtitleES: 'In this lesson, you add not after am / is / are.',
    textRU: 'Отрицание с To Be строится так: кто + am / is / are + not + описание. I am not hungry. He is not here. They are not happy.',
    textUK: 'Заперечення з To Be будується так: хто + am / is / are + not + опис. I am not hungry. He is not here. They are not happy.',
    textES: 'Negative To Be sentences use: who + am / is / are + not + description. I am not hungry. He is not here. They are not happy.',
    linesRU: [
      { type: 'text', parts: [{ text: 'В уроке 1 ты собирал простые фразы:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' tired' }, { text: ' / ', tone: 'muted' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Теперь нужно научиться говорить наоборот:' }] },
      { type: 'formula', parts: [{ text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'описание', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' hungry' }] },
      { type: 'correct', parts: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' here' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' happy' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главное правило: ', tone: 'strong' }, { text: 'not ставится после am / is / are.', tone: 'warning' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'В уроці 1 ти складав прості фрази:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' tired' }, { text: ' / ', tone: 'muted' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Тепер треба навчитися казати навпаки:' }] },
      { type: 'formula', parts: [{ text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'опис', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' hungry' }] },
      { type: 'correct', parts: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' here' }] },
      { type: 'correct', parts: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' happy' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Головне правило: ', tone: 'strong' }, { text: 'not стоїть після am / is / are.', tone: 'warning' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'In lesson 1, you built simple sentences:' }] },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' tired' }, { text: ' / ', tone: 'muted' }, { text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'who', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'description', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' hungry' }] },
      { type: 'correct', parts: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' here' }] },
      { type: 'tip', parts: [{ text: 'Main rule: ', tone: 'strong' }, { text: 'not goes after am / is / are.', tone: 'warning' }] },
    ],
    examples: [
      { labelRU: 'я не', labelUK: 'я не', labelES: 'I am not', en: [{ text: 'I ', tone: 'strong' }, { text: 'am', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' tired' }], ru: 'Я не устал', uk: 'Я не втомлений', es: 'No estoy cansado.', trRU: 'Я не устал', trUK: 'Я не втомлений', trES: 'No estoy cansado.', noteRU: 'I требует am, а not ставится после am.', noteUK: 'I вимагає am, а not стоїть після am.', noteES: 'Use am with I, and not goes after am.' },
      { labelRU: 'он не', labelUK: 'він не', labelES: 'he is not', en: [{ text: 'He ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' busy' }], ru: 'Он не занят', uk: 'Він не зайнятий', es: 'Él no está ocupado.', trRU: 'Он не занят', trUK: 'Він не зайнятий', trES: 'Él no está ocupado.', noteRU: 'He требует is, а не are.', noteUK: 'He вимагає is, а не are.', noteES: 'Use is with he, not are.' },
      { labelRU: 'они не', labelUK: 'вони не', labelES: 'they are not', en: [{ text: 'They ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' ready' }], ru: 'Они не готовы', uk: 'Вони не готові', es: 'No están listos.', trRU: 'Они не готовы', trUK: 'Вони не готові', trES: 'No están listos.', noteRU: 'They требует are, а not идёт после are.', noteUK: 'They вимагає are, а not стоїть після are.', noteES: 'Use are with they, and not goes after are.' },
    ],
    developerNotes: {
      screenGoal: 'Экран объясняет отрицания To Be: not ставится после am/is/are. Пользователь должен понять порядок слов перед началом сборки.',
      visualPriority: ['am / is / are всегда выделять accent.', 'not всегда выделять warning.', 'Неправильные варианты на этом экране не перегружать, чтобы не смешивать с вопросами.'],
      highlightRules: ['В отрицаниях подсвечивать связку и not: am not, is not, are not.', 'Подлежащее выделять strong, чтобы пользователь видел, от чего выбирается am/is/are.'],
      forbiddenContent: ['Не добавлять do not / does not.', 'Не добавлять cannot.', 'Не добавлять сокращения типа isn\'t / aren\'t / I\'m not.', 'Не добавлять времена Present Simple.'],
      layoutRules: ['Формула должна быть отдельной строкой.', 'Примеры должны быть короткими.', 'Не использовать длинные абзацы.'],
    },
  },
  {
    lessonId: 2,
    screenId: 'lesson_2_intro_2_questions',
    order: 2,
    kind: 'formula',
    titleRU: 'Как задать вопрос',
    titleUK: 'Як поставити питання',
    titleES: 'How to ask a question',
    subtitleRU: 'В вопросе am / is / are выходит на первое место.',
    subtitleUK: 'У питанні am / is / are виходить на перше місце.',
    subtitleES: 'In a question, am / is / are moves to the front.',
    textRU: 'В вопросе am / is / are выходит перед тем, о ком спрашиваем: Are you sure? Is it expensive? Am I right?',
    textUK: 'У питанні am / is / are виходить перед тим, про кого питаємо: Are you sure? Is it expensive? Am I right?',
    textES: 'In a question, am / is / are comes before the person or thing: Are you sure? Is it expensive? Am I right?',
    linesRU: [
      { type: 'text', parts: [{ text: 'Обычная фраза:' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Вопрос:' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you ready?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'кто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'описание?', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'example', parts: [{ text: 'Is', tone: 'accent' }, { text: ' it expensive?' }] },
      { type: 'example', parts: [{ text: 'Is', tone: 'accent' }, { text: ' she ready?' }] },
      { type: 'example', parts: [{ text: 'Are', tone: 'accent' }, { text: ' they here?' }] },
      { type: 'example', parts: [{ text: 'Am', tone: 'accent' }, { text: ' I right?' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главный сигнал вопроса: ', tone: 'strong' }, { text: 'am / is / are стоит перед "кто".', tone: 'accent' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'Звичайна фраза:' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Питання:' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you ready?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'хто', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'опис?', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'example', parts: [{ text: 'Is', tone: 'accent' }, { text: ' it expensive?' }] },
      { type: 'example', parts: [{ text: 'Is', tone: 'accent' }, { text: ' she ready?' }] },
      { type: 'example', parts: [{ text: 'Are', tone: 'accent' }, { text: ' they here?' }] },
      { type: 'example', parts: [{ text: 'Am', tone: 'accent' }, { text: ' I right?' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Головний сигнал питання: ', tone: 'strong' }, { text: 'am / is / are стоїть перед "хто".', tone: 'accent' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'Normal sentence:' }] },
      { type: 'correct', parts: [{ text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ready' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Question:' }] },
      { type: 'correct', parts: [{ text: 'Are', tone: 'accent' }, { text: ' you ready?' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'am / is / are', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'who', tone: 'formula' }, { text: ' + ', tone: 'muted' }, { text: 'description?', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'example', parts: [{ text: 'Is', tone: 'accent' }, { text: ' it expensive?' }] },
      { type: 'example', parts: [{ text: 'Are', tone: 'accent' }, { text: ' they here?' }] },
      { type: 'tip', parts: [{ text: 'Question signal: ', tone: 'strong' }, { text: 'am / is / are comes before the person or thing.', tone: 'accent' }] },
    ],
    examples: [
      { labelRU: 'ты?', labelUK: 'ти?', labelES: 'you?', en: [{ text: 'Are', tone: 'accent' }, { text: ' you sure?' }], ru: 'Ты уверен?', uk: 'Ти впевнений?', es: '¿Estás seguro?', trRU: 'Ты уверен?', trUK: 'Ти впевнений?', trES: '¿Estás seguro?', noteRU: 'Для you вопрос начинается с Are.', noteUK: 'Для you питання починається з Are.', noteES: 'With you, the question starts with Are.' },
      { labelRU: 'это?', labelUK: 'це?', labelES: 'it?', en: [{ text: 'Is', tone: 'accent' }, { text: ' it free?' }], ru: 'Это бесплатно?', uk: 'Це безкоштовно?', es: '¿Es gratis?', trRU: 'Это бесплатно?', trUK: 'Це безкоштовно?', trES: '¿Es gratis?', noteRU: 'Для it вопрос начинается с Is.', noteUK: 'Для it питання починається з Is.', noteES: 'With it, the question starts with Is.' },
      { labelRU: 'я?', labelUK: 'я?', labelES: 'I?', en: [{ text: 'Am', tone: 'accent' }, { text: ' I right?' }], ru: 'Я прав?', uk: 'Я правий?', es: '¿Tengo razón?', trRU: 'Я прав?', trUK: 'Я правий?', trES: '¿Tengo razón?', noteRU: 'Для I вопрос начинается с Am.', noteUK: 'Для I питання починається з Am.', noteES: 'With I, the question starts with Am.' },
    ],
    developerNotes: {
      screenGoal: 'Экран объясняет вопросительный порядок с To Be. Пользователь должен понять, что в вопросе связка выходит перед подлежащим.',
      visualPriority: ['Показать контраст: You are ready -> Are you ready?', 'В вопросах подсвечивать первое слово Am/Is/Are.', 'Формулу вопроса показать отдельно.'],
      highlightRules: ['В вопросах подсвечивать только Am/Is/Are на первом месте.', 'Не подсвечивать всё предложение, иначе потеряется главный механизм.'],
      forbiddenContent: ['Не добавлять do / does.', 'Не добавлять what / where / why.', 'Не добавлять Present Simple questions.', 'Не добавлять сокращения.'],
      layoutRules: ['Сначала контраст обычной фразы и вопроса.', 'Потом формула.', 'Потом 3-4 коротких примера из урока 2.'],
    },
  },
  {
    lessonId: 2,
    screenId: 'lesson_2_intro_3_practice',
    order: 3,
    kind: 'practice',
    titleRU: 'Как понять, что собирать',
    titleUK: 'Як зрозуміти, що складати',
    titleES: 'How to know what to build',
    subtitleRU: 'Сначала определи тип фразы: обычная, отрицательная или вопрос.',
    subtitleUK: 'Спочатку визнач тип фрази: звичайна, заперечна або питання.',
    subtitleES: 'First identify the type: normal, negative, or question.',
    textRU: 'Сначала определи тип: обычная фраза, отрицание или вопрос. Если есть "не" - not после связки. Если вопрос - начинай с Am / Is / Are.',
    textUK: 'Спочатку визнач тип: звичайна фраза, заперечення або питання. Якщо є "не" - not після зв\'язки. Якщо питання - починай з Am / Is / Are.',
    textES: 'First identify the type: normal, negative, or question. If it is negative, put not after the link. If it is a question, start with Am / Is / Are.',
    linesRU: [
      { type: 'text', parts: [{ text: 'В этом уроке у тебя будет три типа фраз.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Обычная фраза: ', tone: 'muted' }, { text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ready' }] },
      { type: 'step', parts: [{ text: '2. Отрицание: ', tone: 'muted' }, { text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' ready' }] },
      { type: 'step', parts: [{ text: '3. Вопрос: ', tone: 'muted' }, { text: 'Are', tone: 'accent' }, { text: ' you ready?' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Если фраза отрицательная - ищи ' }, { text: 'not', tone: 'warning' }, { text: ' после am / is / are.' }] },
      { type: 'text', parts: [{ text: 'Если в русском стоит вопрос - начинай с ' }, { text: 'Am / Is / Are', tone: 'accent' }, { text: '.' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'You not are ready', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' ready' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'You are ready?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you ready?' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'У цьому уроці буде три типи фраз.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Звичайна фраза: ', tone: 'muted' }, { text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ready' }] },
      { type: 'step', parts: [{ text: '2. Заперечення: ', tone: 'muted' }, { text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' ready' }] },
      { type: 'step', parts: [{ text: '3. Питання: ', tone: 'muted' }, { text: 'Are', tone: 'accent' }, { text: ' you ready?' }] },
      { type: 'spacer' },
      { type: 'text', parts: [{ text: 'Якщо фраза заперечна - шукай ' }, { text: 'not', tone: 'warning' }, { text: ' після am / is / are.' }] },
      { type: 'text', parts: [{ text: 'Якщо це питання - починай з ' }, { text: 'Am / Is / Are', tone: 'accent' }, { text: '.' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'You not are ready', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' ready' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'You are ready?', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Are', tone: 'accent' }, { text: ' you ready?' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'This lesson has three sentence types.' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. Normal: ', tone: 'muted' }, { text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ready' }] },
      { type: 'step', parts: [{ text: '2. Negative: ', tone: 'muted' }, { text: 'You ', tone: 'strong' }, { text: 'are', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' ready' }] },
      { type: 'step', parts: [{ text: '3. Question: ', tone: 'muted' }, { text: 'Are', tone: 'accent' }, { text: ' you ready?' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'For negatives, use ' }, { text: 'not', tone: 'warning' }, { text: ' after am / is / are.' }] },
      { type: 'tip', parts: [{ text: 'For questions, start with ' }, { text: 'Am / Is / Are', tone: 'accent' }, { text: '.' }] },
    ],
    examples: [
      { labelRU: 'обычная фраза', labelUK: 'звичайна фраза', labelES: 'normal sentence', en: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ready' }], ru: 'Она готова', uk: 'Вона готова', es: 'Ella está lista.', trRU: 'Она готова', trUK: 'Вона готова', trES: 'Ella está lista.', noteRU: 'Сначала кто, потом is.', noteUK: 'Спочатку хто, потім is.', noteES: 'First who, then is.' },
      { labelRU: 'отрицание', labelUK: 'заперечення', labelES: 'negative', en: [{ text: 'She ', tone: 'strong' }, { text: 'is', tone: 'accent' }, { text: ' ' }, { text: 'not', tone: 'warning' }, { text: ' ready' }], ru: 'Она не готова', uk: 'Вона не готова', es: 'Ella no está lista.', trRU: 'Она не готова', trUK: 'Вона не готова', trES: 'Ella no está lista.', noteRU: 'not ставится после is.', noteUK: 'not стоїть після is.', noteES: 'not goes after is.' },
      { labelRU: 'вопрос', labelUK: 'питання', labelES: 'question', en: [{ text: 'Is', tone: 'accent' }, { text: ' she ready?' }], ru: 'Она готова?', uk: 'Вона готова?', es: '¿Está ella lista?', trRU: 'Она готова?', trUK: 'Вона готова?', trES: '¿Está ella lista?', noteRU: 'В вопросе is выходит в начало.', noteUK: 'У питанні is виходить на початок.', noteES: 'In a question, is moves to the front.' },
    ],
    developerNotes: {
      screenGoal: 'Экран связывает теорию с механикой задания: пользователь видит русскую фразу и понимает, собирать обычную фразу, отрицание или вопрос.',
      visualPriority: ['Три типа фраз показать как отдельные строки.', 'not подсветить warning.', 'Am/Is/Are в начале вопроса подсветить accent.', 'Ошибки показать красным только внизу, после объяснения.'],
      highlightRules: ['В отрицании подсвечивать not.', 'В вопросе подсвечивать первое Am/Is/Are.', 'В обычной фразе подсвечивать am/is/are внутри фразы.'],
      forbiddenContent: ['Не использовать do / does.', 'Не использовать wh-questions.', 'Не использовать сокращения.', 'Не добавлять фразы, которых нет в уроке 2.'],
      layoutRules: ['Этот экран может быть чуть плотнее, потому что он финальный перед практикой.', 'Если экран не помещается, wrong/correct пары можно отрисовать компактно.', 'Не смешивать красный цвет с правильными формами.'],
    },
  },
];
