import type { LessonIntroScreen } from './lesson_data_types';

export const LESSON_18_INTRO_EXTRA: LessonIntroScreen[] = [
  {
    lessonId: 18,
    screenId: 'lesson_18_intro_1_please_requests',
    order: 1,
    kind: 'concept',
    titleRU: 'Просьба через Please',
    titleUK: 'Прохання через Please',
    titleES: 'Requests with Please',
    titlePtBr: 'Pedidos com Please',
    titleVi: 'Lời nhờ với Please',
    titleId: 'Permintaan dengan Please',
    titleTr: 'Please ile rica',
    titlePl: 'Prośby z Please',
    subtitleRU: 'Please делает команду мягче, но порядок слов остается простым.',
    subtitleUK: 'Please робить команду м\'якшою, але порядок слів залишається простим.',
    subtitleES: 'Please makes the command softer, but the word order stays simple.',
    subtitlePtBr: 'Please deixa a ordem mais suave, mas a ordem das palavras continua simples.',
    subtitleVi: 'Please làm câu mệnh lệnh mềm hơn, nhưng trật tự từ vẫn đơn giản.',
    subtitleId: 'Please membuat perintah terdengar lebih halus, tetapi urutan katanya tetap sederhana.',
    subtitleTr: 'Please komutu yumuşatır, ama kelime sırası basit kalır.',
    subtitlePl: 'Please łagodzi polecenie, ale szyk słów zostaje prosty.',
    textRU: 'Вежливая просьба строится как Please + действие. После Please не нужен you.',
    textUK: 'Ввічливе прохання будується як Please + дія. Після Please не потрібен you.',
    textES: 'A polite request is built as Please + action. After Please, you is not needed.',
    textPtBr: 'Um pedido educado se forma como Please + ação. Depois de Please, you não é necessário.',
    textVi: 'Lời nhờ lịch sự có dạng Please + hành động. Sau Please không cần you.',
    textId: 'Permintaan sopan dibentuk sebagai Please + aksi. Setelah Please, you tidak diperlukan.',
    textTr: 'Nazik rica Please + eylem şeklinde kurulur. Please sonrasında you gerekmez.',
    textPl: 'Uprzejma prośba ma wzór Please + czynność. Po Please nie trzeba you.',
    linesRU: [
      { type: 'text', parts: [{ text: 'В этом уроке ты часто просишь человека что-то сделать:' }] },
      { type: 'formula', parts: [{ text: 'Please', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'действие', tone: 'formula' }, { text: ' + остальные слова', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' help me' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' call me later' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' check messages' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' send documents' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Главное: ', tone: 'strong' }, { text: 'после Please сразу идет действие: wait, help, call, check, send.' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Please you wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
    ],
    linesUK: [
      { type: 'text', parts: [{ text: 'У цьому уроці ти часто просиш людину щось зробити:' }] },
      { type: 'formula', parts: [{ text: 'Please', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'дія', tone: 'formula' }, { text: ' + решта слів', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' help me' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' call me later' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' check messages' }] },
      { type: 'tip', parts: [{ text: 'Головне: ', tone: 'strong' }, { text: 'після Please одразу йде дія: wait, help, call, check, send.' }] },
    ],
    linesES: [
      { type: 'text', parts: [{ text: 'In this lesson, you often ask someone to do something:' }] },
      { type: 'formula', parts: [{ text: 'Please', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'action', tone: 'formula' }, { text: ' + other words', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' help me' }] },
    ],
    linesPtBr: [
      { type: 'text', parts: [{ text: 'Nesta lição, você pede a alguém para fazer algo:' }] },
      { type: 'formula', parts: [{ text: 'Please', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'ação', tone: 'formula' }, { text: ' + outras palavras', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' help me' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' call me later' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' check messages' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' send documents' }] },
      { type: 'tip', parts: [{ text: 'Principal: ', tone: 'strong' }, { text: 'depois de Please vem direto a ação: wait, help, call, check, send.' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'Please you wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
    ],
    linesVi: [
      { type: 'text', parts: [{ text: 'Trong bài này, bạn thường nhờ ai đó làm một việc:' }] },
      { type: 'formula', parts: [{ text: 'Please', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'hành động', tone: 'formula' }, { text: ' + các từ còn lại', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' help me' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' call me later' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' check messages' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' send documents' }] },
      { type: 'tip', parts: [{ text: 'Điểm chính: ', tone: 'strong' }, { text: 'sau Please là hành động ngay: wait, help, call, check, send.' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'Please you wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
    ],
    linesId: [
      { type: 'text', parts: [{ text: 'Dalam pelajaran ini, kamu sering meminta seseorang melakukan sesuatu:' }] },
      { type: 'formula', parts: [{ text: 'Please', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'aksi', tone: 'formula' }, { text: ' + kata lain', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' help me' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' call me later' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' check messages' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' send documents' }] },
      { type: 'tip', parts: [{ text: 'Intinya: ', tone: 'strong' }, { text: 'setelah Please langsung ada aksi: wait, help, call, check, send.' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'Please you wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
    ],
    linesTr: [
      { type: 'text', parts: [{ text: 'Bu derste sık sık birinden bir şey yapmasını istersin:' }] },
      { type: 'formula', parts: [{ text: 'Please', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'eylem', tone: 'formula' }, { text: ' + diğer sözler', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' help me' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' call me later' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' check messages' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' send documents' }] },
      { type: 'tip', parts: [{ text: 'Ana nokta: ', tone: 'strong' }, { text: 'Please sonrası doğrudan eylem gelir: wait, help, call, check, send.' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'Please you wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
    ],
    linesPl: [
      { type: 'text', parts: [{ text: 'W tej lekcji często prosisz kogoś, żeby coś zrobił:' }] },
      { type: 'formula', parts: [{ text: 'Please', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'czynność', tone: 'formula' }, { text: ' + reszta słów', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' help me' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' call me later' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' check messages' }] },
      { type: 'correct', parts: [{ text: 'Please', tone: 'accent' }, { text: ' send documents' }] },
      { type: 'tip', parts: [{ text: 'Najważniejsze: ', tone: 'strong' }, { text: 'po Please od razu idzie czynność: wait, help, call, check, send.' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'Please you wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'Please', tone: 'accent' }, { text: ' wait here' }] },
    ],
    examples: [
      {
        labelRU: 'вежливая просьба',
        labelUK: 'ввічливе прохання',
        labelES: 'polite request',
        labelPtBr: 'pedido educado',
        labelVi: 'lời nhờ lịch sự',
        labelId: 'permintaan sopan',
        labelTr: 'nazik rica',
        labelPl: 'uprzejma prośba',
        en: [{ text: 'Please', tone: 'accent' }, { text: ' open the app' }],
        ru: 'Пожалуйста, открой приложение',
        uk: 'Будь ласка, відкрий застосунок',
        es: 'Por favor, abre la aplicación.',
        'pt-BR': 'Por favor, abra o aplicativo.',
        vi: 'Làm ơn mở ứng dụng.',
        id: 'Tolong buka aplikasinya.',
        tr: 'Lütfen uygulamayı aç.',
        pl: 'Proszę, otwórz aplikację.',
        trRU: 'Пожалуйста, открой приложение',
        trUK: 'Будь ласка, відкрий застосунок',
        trES: 'Por favor, abre la aplicación.',
        noteRU: 'Please делает фразу мягче, но you не нужен.',
        noteUK: 'Please робить фразу м\'якшою, але you не потрібен.',
        noteES: 'Please makes the sentence softer, but you is not needed.',
        notePtBr: 'Please deixa a frase mais suave, mas you não é necessário.',
        noteVi: 'Please làm câu mềm hơn, nhưng không cần you.',
        noteId: 'Please membuat kalimat lebih halus, tetapi you tidak diperlukan.',
        noteTr: 'Please cümleyi yumuşatır, ama you gerekmez.',
        notePl: 'Please łagodzi zdanie, ale you nie jest potrzebne.',
      },
      {
        labelRU: 'фразовый глагол',
        labelUK: 'фразове дієслово',
        labelES: 'phrasal verb',
        labelPtBr: 'phrasal verb',
        labelVi: 'cụm động từ',
        labelId: 'phrasal verb',
        labelTr: 'phrasal verb',
        labelPl: 'czasownik frazowy',
        en: [{ text: 'Please', tone: 'accent' }, { text: ' turn ' }, { text: 'off', tone: 'warning' }, { text: ' your phone' }],
        ru: 'Пожалуйста, выключи свой телефон',
        uk: 'Будь ласка, вимкни свій телефон',
        es: 'Por favor, apaga tu teléfono.',
        'pt-BR': 'Por favor, desligue seu telefone.',
        vi: 'Làm ơn tắt điện thoại của bạn.',
        id: 'Tolong matikan ponselmu.',
        tr: 'Lütfen telefonunu kapat.',
        pl: 'Proszę, wyłącz telefon.',
        trRU: 'Пожалуйста, выключи свой телефон',
        trUK: 'Будь ласка, вимкни свій телефон',
        trES: 'Por favor, apaga tu teléfono.',
        noteRU: 'Turn off остается связкой: выключить.',
        noteUK: 'Turn off залишається зв\'язкою: вимкнути.',
        noteES: 'Turn off stays as one unit.',
        notePtBr: 'Turn off continua uma unidade.',
        noteVi: 'Turn off vẫn là một cụm.',
        noteId: 'Turn off tetap satu unit.',
        noteTr: 'Turn off tek bir birim olarak kalır.',
        notePl: 'Turn off zostaje jedną jednostką.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран вводит polite imperative с Please. Главный риск - пользователь вставит you после Please.',
      visualPriority: ['Please выделять accent.', 'фразовые частицы on/off/back выделять warning.', 'ошибку Please you wait here выделять danger.'],
      highlightRules: ['Please = accent.', 'phrasal particle = warning.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять could you.', 'Не добавлять would you.', 'Не добавлять please в конец как отдельную тему.', 'Не использовать фразы вне урока 18.'],
      layoutRules: ['Один экран - только Please + действие.', 'Не смешивать с Can you и Let us.'],
    },
  },
  {
    lessonId: 18,
    screenId: 'lesson_18_intro_2_direct_commands',
    order: 2,
    kind: 'formula',
    titleRU: 'Прямая команда без you',
    titleUK: 'Пряма команда без you',
    titleES: 'Direct command without you',
    titlePtBr: 'Comando direto sem you',
    titleVi: 'Mệnh lệnh trực tiếp không có you',
    titleId: 'Perintah langsung tanpa you',
    titleTr: 'you olmadan doğrudan komut',
    titlePl: 'Bezpośrednie polecenie bez you',
    subtitleRU: 'В английской команде часто нет подлежащего you. Фраза сразу начинается с действия.',
    subtitleUK: 'В англійській команді часто немає підмета you. Фраза одразу починається з дії.',
    subtitleES: 'In English commands, you is often missing. The sentence starts with the action.',
    subtitlePtBr: 'Em comandos em inglês, muitas vezes não há sujeito you. A frase começa direto pela ação.',
    subtitleVi: 'Trong mệnh lệnh tiếng Anh, thường không có chủ ngữ you. Câu bắt đầu ngay bằng hành động.',
    subtitleId: 'Dalam perintah bahasa Inggris, subjek you sering tidak ada. Kalimat langsung mulai dengan aksi.',
    subtitleTr: 'İngilizce komutlarda you öznesi çoğu zaman yoktur. Cümle doğrudan eylemle başlar.',
    subtitlePl: 'W angielskim poleceniu często nie ma podmiotu you. Zdanie od razu zaczyna się od czynności.',
    textRU: 'Команда начинается с базового глагола: Wait, Start, Listen, Call.',
    textUK: 'Команда починається з базового дієслова: Wait, Start, Listen, Call.',
    textES: 'A command starts with the base verb: Wait, Start, Listen, Call.',
    textPtBr: 'Um comando começa com o verbo base: Wait, Start, Listen, Call.',
    textVi: 'Mệnh lệnh bắt đầu bằng động từ nguyên mẫu: Wait, Start, Listen, Call.',
    textId: 'Perintah dimulai dengan kata kerja dasar: Wait, Start, Listen, Call.',
    textTr: 'Komut temel fiille başlar: Wait, Start, Listen, Call.',
    textPl: 'Polecenie zaczyna się od czasownika w formie podstawowej: Wait, Start, Listen, Call.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'действие', tone: 'accent' }, { text: ' + остальные слова', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'correct', parts: [{ text: 'Start', tone: 'accent' }, { text: ' now' }] },
      { type: 'correct', parts: [{ text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
      { type: 'correct', parts: [{ text: 'Look', tone: 'accent' }, { text: ' at me' }] },
      { type: 'correct', parts: [{ text: 'Call', tone: 'accent' }, { text: ' her now' }] },
      { type: 'correct', parts: [{ text: 'Help', tone: 'accent' }, { text: ' us today' }] },
      { type: 'correct', parts: [{ text: 'Bring', tone: 'accent' }, { text: ' documents' }] },
      { type: 'spacer' },
      { type: 'tip', parts: [{ text: 'Это не Present Simple. ', tone: 'strong' }, { text: 'Не добавляй do / does, am / is / are или you в начало.' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'You wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Команда: ', tone: 'success' }, { text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Are listen to me', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'дія', tone: 'accent' }, { text: ' + решта слів', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'correct', parts: [{ text: 'Start', tone: 'accent' }, { text: ' now' }] },
      { type: 'correct', parts: [{ text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
      { type: 'correct', parts: [{ text: 'Call', tone: 'accent' }, { text: ' her now' }] },
      { type: 'correct', parts: [{ text: 'Bring', tone: 'accent' }, { text: ' documents' }] },
      { type: 'tip', parts: [{ text: 'Це не Present Simple. ', tone: 'strong' }, { text: 'Не додавай do / does, am / is / are або you на початок.' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'action', tone: 'accent' }, { text: ' + other words', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'correct', parts: [{ text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
    ],
    linesPtBr: [
      { type: 'formula', parts: [{ text: 'ação', tone: 'accent' }, { text: ' + outras palavras', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'correct', parts: [{ text: 'Start', tone: 'accent' }, { text: ' now' }] },
      { type: 'correct', parts: [{ text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
      { type: 'correct', parts: [{ text: 'Look', tone: 'accent' }, { text: ' at me' }] },
      { type: 'correct', parts: [{ text: 'Call', tone: 'accent' }, { text: ' her now' }] },
      { type: 'correct', parts: [{ text: 'Help', tone: 'accent' }, { text: ' us today' }] },
      { type: 'correct', parts: [{ text: 'Bring', tone: 'accent' }, { text: ' documents' }] },
      { type: 'tip', parts: [{ text: 'Isto não é Present Simple. ', tone: 'strong' }, { text: 'Não adicione do / does, am / is / are ou you no começo.' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'You wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Comando: ', tone: 'success' }, { text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'Are listen to me', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
    ],
    linesVi: [
      { type: 'formula', parts: [{ text: 'hành động', tone: 'accent' }, { text: ' + các từ còn lại', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'correct', parts: [{ text: 'Start', tone: 'accent' }, { text: ' now' }] },
      { type: 'correct', parts: [{ text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
      { type: 'correct', parts: [{ text: 'Look', tone: 'accent' }, { text: ' at me' }] },
      { type: 'correct', parts: [{ text: 'Call', tone: 'accent' }, { text: ' her now' }] },
      { type: 'correct', parts: [{ text: 'Help', tone: 'accent' }, { text: ' us today' }] },
      { type: 'correct', parts: [{ text: 'Bring', tone: 'accent' }, { text: ' documents' }] },
      { type: 'tip', parts: [{ text: 'Đây không phải Present Simple. ', tone: 'strong' }, { text: 'Đừng thêm do / does, am / is / are hoặc you ở đầu.' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'You wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Mệnh lệnh: ', tone: 'success' }, { text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'Are listen to me', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
    ],
    linesId: [
      { type: 'formula', parts: [{ text: 'aksi', tone: 'accent' }, { text: ' + kata lain', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'correct', parts: [{ text: 'Start', tone: 'accent' }, { text: ' now' }] },
      { type: 'correct', parts: [{ text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
      { type: 'correct', parts: [{ text: 'Look', tone: 'accent' }, { text: ' at me' }] },
      { type: 'correct', parts: [{ text: 'Call', tone: 'accent' }, { text: ' her now' }] },
      { type: 'correct', parts: [{ text: 'Help', tone: 'accent' }, { text: ' us today' }] },
      { type: 'correct', parts: [{ text: 'Bring', tone: 'accent' }, { text: ' documents' }] },
      { type: 'tip', parts: [{ text: 'Ini bukan Present Simple. ', tone: 'strong' }, { text: 'Jangan tambahkan do / does, am / is / are, atau you di awal.' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'You wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Perintah: ', tone: 'success' }, { text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'Are listen to me', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
    ],
    linesTr: [
      { type: 'formula', parts: [{ text: 'eylem', tone: 'accent' }, { text: ' + diğer sözler', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'correct', parts: [{ text: 'Start', tone: 'accent' }, { text: ' now' }] },
      { type: 'correct', parts: [{ text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
      { type: 'correct', parts: [{ text: 'Look', tone: 'accent' }, { text: ' at me' }] },
      { type: 'correct', parts: [{ text: 'Call', tone: 'accent' }, { text: ' her now' }] },
      { type: 'correct', parts: [{ text: 'Help', tone: 'accent' }, { text: ' us today' }] },
      { type: 'correct', parts: [{ text: 'Bring', tone: 'accent' }, { text: ' documents' }] },
      { type: 'tip', parts: [{ text: 'Bu Present Simple değil. ', tone: 'strong' }, { text: 'Başa do / does, am / is / are ya da you ekleme.' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'You wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Komut: ', tone: 'success' }, { text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'Are listen to me', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
    ],
    linesPl: [
      { type: 'formula', parts: [{ text: 'czynność', tone: 'accent' }, { text: ' + reszta słów', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'correct', parts: [{ text: 'Start', tone: 'accent' }, { text: ' now' }] },
      { type: 'correct', parts: [{ text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
      { type: 'correct', parts: [{ text: 'Look', tone: 'accent' }, { text: ' at me' }] },
      { type: 'correct', parts: [{ text: 'Call', tone: 'accent' }, { text: ' her now' }] },
      { type: 'correct', parts: [{ text: 'Help', tone: 'accent' }, { text: ' us today' }] },
      { type: 'correct', parts: [{ text: 'Bring', tone: 'accent' }, { text: ' documents' }] },
      { type: 'tip', parts: [{ text: 'To nie jest Present Simple. ', tone: 'strong' }, { text: 'Nie dodawaj do / does, am / is / are ani you na początku.' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'You wait here', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Polecenie: ', tone: 'success' }, { text: 'Wait', tone: 'accent' }, { text: ' here' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'Are listen to me', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'Listen', tone: 'accent' }, { text: ' to me' }] },
    ],
    examples: [
      {
        labelRU: 'команда',
        labelUK: 'команда',
        labelES: 'command',
        labelPtBr: 'comando',
        labelVi: 'mệnh lệnh',
        labelId: 'perintah',
        labelTr: 'komut',
        labelPl: 'polecenie',
        en: [{ text: 'Check', tone: 'accent' }, { text: ' your phone' }],
        ru: 'Проверь свой телефон',
        uk: 'Перевір свій телефон',
        es: 'Revisa tu teléfono.',
        'pt-BR': 'Verifique seu telefone.',
        vi: 'Hãy kiểm tra điện thoại của bạn.',
        id: 'Periksa ponselmu.',
        tr: 'Telefonunu kontrol et.',
        pl: 'Sprawdź swój telefon.',
        trRU: 'Проверь свой телефон',
        trUK: 'Перевір свій телефон',
        trES: 'Revisa tu teléfono.',
        noteRU: 'Команда начинается сразу с действия Check.',
        noteUK: 'Команда починається одразу з дії Check.',
        noteES: 'The command starts directly with the action Check.',
        notePtBr: 'O comando começa direto com a ação Check.',
        noteVi: 'Mệnh lệnh bắt đầu ngay bằng hành động Check.',
        noteId: 'Perintah langsung dimulai dengan aksi Check.',
        noteTr: 'Komut doğrudan Check eylemiyle başlar.',
        notePl: 'Polecenie zaczyna się od razu od czynności Check.',
      },
      {
        labelRU: 'команда',
        labelUK: 'команда',
        labelES: 'command',
        labelPtBr: 'comando',
        labelVi: 'mệnh lệnh',
        labelId: 'perintah',
        labelTr: 'komut',
        labelPl: 'polecenie',
        en: [{ text: 'Clean', tone: 'accent' }, { text: ' your room' }],
        ru: 'Убери свою комнату',
        uk: 'Приберись у своїй кімнаті',
        es: 'Limpia tu habitación.',
        'pt-BR': 'Arrume seu quarto.',
        vi: 'Hãy dọn phòng của bạn.',
        id: 'Bersihkan kamarmu.',
        tr: 'Odanı temizle.',
        pl: 'Posprzątaj swój pokój.',
        trRU: 'Убери свою комнату',
        trUK: 'Приберись у своїй кімнаті',
        trES: 'Limpia tu habitación.',
        noteRU: 'You не нужен: Clean your room.',
        noteUK: 'You не потрібен: Clean your room.',
        noteES: 'You is not needed: Clean your room.',
        notePtBr: 'You não é necessário: Clean your room.',
        noteVi: 'Không cần you: Clean your room.',
        noteId: 'You tidak diperlukan: Clean your room.',
        noteTr: 'You gerekmez: Clean your room.',
        notePl: 'You nie jest potrzebne: Clean your room.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран закрепляет прямой imperative без you: Wait here, Start now, Listen to me.',
      visualPriority: ['первый глагол команды выделять accent.', 'ошибки You wait here и Are listen to me выделять danger.'],
      highlightRules: ['command verb = accent.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять he/she commands.', 'Не добавлять Let him.', 'Не добавлять do-support для обычной команды.', 'Не использовать фразы вне урока 18.'],
      layoutRules: ['Один экран - только direct commands.', 'Если экран узкий, оставить Wait, Start, Listen, Call, Help.'],
    },
  },
  {
    lessonId: 18,
    screenId: 'lesson_18_intro_3_negative_and_can_you',
    order: 3,
    kind: 'formula',
    titleRU: 'Запрет и мягкая просьба',
    titleUK: 'Заборона і м\'яке прохання',
    titleES: 'Negative commands and soft requests',
    titlePtBr: 'Proibição e pedido suave',
    titleVi: 'Cấm đoán và lời nhờ mềm',
    titleId: 'Larangan dan permintaan halus',
    titleTr: 'Yasak ve yumuşak rica',
    titlePl: 'Zakaz i łagodna prośba',
    subtitleRU: 'Для "не делай" используй Do not. Для мягкой просьбы можно начать с Can you.',
    subtitleUK: 'Для "не роби" використовуй Do not. Для м\'якого прохання можна почати з Can you.',
    subtitleES: 'For "do not do it", use Do not. For a softer request, start with Can you.',
    subtitlePtBr: 'Para "não faça", use Do not. Para um pedido mais suave, comece com Can you.',
    subtitleVi: 'Để nói "đừng làm", dùng Do not. Với lời nhờ mềm hơn, bắt đầu bằng Can you.',
    subtitleId: 'Untuk "jangan lakukan", gunakan Do not. Untuk permintaan yang lebih halus, mulai dengan Can you.',
    subtitleTr: '"Yapma" demek için Do not kullan. Daha yumuşak rica için Can you ile başla.',
    subtitlePl: 'Dla "nie rób" użyj Do not. Dla łagodniejszej prośby zacznij od Can you.',
    textRU: 'Do not запрещает действие. Can you превращает команду в мягкую просьбу.',
    textUK: 'Do not забороняє дію. Can you перетворює команду на м\'яке прохання.',
    textES: 'Do not forbids an action. Can you turns a command into a softer request.',
    textPtBr: 'Do not proíbe uma ação. Can you transforma o comando em pedido mais suave.',
    textVi: 'Do not cấm một hành động. Can you biến mệnh lệnh thành lời nhờ mềm hơn.',
    textId: 'Do not melarang sebuah aksi. Can you mengubah perintah menjadi permintaan yang lebih halus.',
    textTr: 'Do not bir eylemi yasaklar. Can you komutu daha yumuşak ricaya çevirir.',
    textPl: 'Do not zakazuje czynności. Can you zmienia polecenie w łagodniejszą prośbę.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'действие', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' call him' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' send messages' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' open it' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' share passwords' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Not wait outside', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'spacer' },
      { type: 'formula', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'действие?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' help me?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' call me later?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' bring a charger?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' turn off the lights?' }] },
      { type: 'tip', parts: [{ text: 'Разница: ', tone: 'strong' }, { text: 'Do not = запрет. Can you = мягкая просьба.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'дія', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' call him' }] },
      { type: 'formula', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' + дія?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' help me?' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' + action', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'formula', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' + action?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' help me?' }] },
    ],
    linesPtBr: [
      { type: 'formula', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'ação', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' call him' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' send messages' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' open it' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' share passwords' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'Not wait outside', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'formula', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'ação?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' help me?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' call me later?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' bring a charger?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' turn off the lights?' }] },
      { type: 'tip', parts: [{ text: 'Diferença: ', tone: 'strong' }, { text: 'Do not = proibição. Can you = pedido suave.' }] },
    ],
    linesVi: [
      { type: 'formula', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'hành động', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' call him' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' send messages' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' open it' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' share passwords' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'Not wait outside', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'formula', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'hành động?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' help me?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' call me later?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' bring a charger?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' turn off the lights?' }] },
      { type: 'tip', parts: [{ text: 'Khác biệt: ', tone: 'strong' }, { text: 'Do not = cấm. Can you = lời nhờ mềm.' }] },
    ],
    linesId: [
      { type: 'formula', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'aksi', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' call him' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' send messages' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' open it' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' share passwords' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'Not wait outside', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'formula', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'aksi?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' help me?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' call me later?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' bring a charger?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' turn off the lights?' }] },
      { type: 'tip', parts: [{ text: 'Bedanya: ', tone: 'strong' }, { text: 'Do not = larangan. Can you = permintaan halus.' }] },
    ],
    linesTr: [
      { type: 'formula', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'eylem', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' call him' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' send messages' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' open it' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' share passwords' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'Not wait outside', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'formula', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'eylem?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' help me?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' call me later?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' bring a charger?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' turn off the lights?' }] },
      { type: 'tip', parts: [{ text: 'Fark: ', tone: 'strong' }, { text: 'Do not = yasak. Can you = yumuşak rica.' }] },
    ],
    linesPl: [
      { type: 'formula', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' + ', tone: 'muted' }, { text: 'czynność', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' call him' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' send messages' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' open it' }] },
      { type: 'correct', parts: [{ text: 'Do not', tone: 'warning' }, { text: ' share passwords' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'Not wait outside', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'Do not', tone: 'warning' }, { text: ' wait outside' }] },
      { type: 'formula', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'czynność?', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' help me?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' call me later?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' bring a charger?' }] },
      { type: 'correct', parts: [{ text: 'Can you', tone: 'accent' }, { text: ' turn off the lights?' }] },
      { type: 'tip', parts: [{ text: 'Różnica: ', tone: 'strong' }, { text: 'Do not = zakaz. Can you = łagodna prośba.' }] },
    ],
    examples: [
      {
        labelRU: 'запрет',
        labelUK: 'заборона',
        labelES: 'negative command',
        labelPtBr: 'comando negativo',
        labelVi: 'mệnh lệnh phủ định',
        labelId: 'perintah negatif',
        labelTr: 'olumsuz komut',
        labelPl: 'polecenie przeczące',
        en: [{ text: 'Do not', tone: 'warning' }, { text: ' use my phone' }],
        ru: 'Не используй мой телефон',
        uk: 'Не використовуй мій телефон',
        es: 'No uses mi teléfono.',
        'pt-BR': 'Não use meu telefone.',
        vi: 'Đừng dùng điện thoại của tôi.',
        id: 'Jangan gunakan ponsel saya.',
        tr: 'Telefonumu kullanma.',
        pl: 'Nie używaj mojego telefonu.',
        trRU: 'Не используй мой телефон',
        trUK: 'Не використовуй мій телефон',
        trES: 'No uses mi teléfono.',
        noteRU: 'Для запрета в этом уроке используется Do not.',
        noteUK: 'Для заборони в цьому уроці використовується Do not.',
        noteES: 'For a negative command, this lesson uses Do not.',
        notePtBr: 'Para comando negativo, esta lição usa Do not.',
        noteVi: 'Với mệnh lệnh phủ định, bài này dùng Do not.',
        noteId: 'Untuk perintah negatif, pelajaran ini memakai Do not.',
        noteTr: 'Olumsuz komut için bu derste Do not kullanılır.',
        notePl: 'Dla polecenia przeczącego ta lekcja używa Do not.',
      },
      {
        labelRU: 'мягкая просьба',
        labelUK: 'м\'яке прохання',
        labelES: 'soft request',
        labelPtBr: 'pedido suave',
        labelVi: 'lời nhờ mềm',
        labelId: 'permintaan halus',
        labelTr: 'yumuşak rica',
        labelPl: 'łagodna prośba',
        en: [{ text: 'Can you', tone: 'accent' }, { text: ' open the door?' }],
        ru: 'Ты можешь открыть дверь?',
        uk: 'Ти можеш відчинити двері?',
        es: '¿Puedes abrir la puerta?',
        'pt-BR': 'Você pode abrir a porta?',
        vi: 'Bạn có thể mở cửa không?',
        id: 'Bisakah kamu membuka pintu?',
        tr: 'Kapıyı açabilir misin?',
        pl: 'Czy możesz otworzyć drzwi?',
        trRU: 'Ты можешь открыть дверь?',
        trUK: 'Ти можеш відчинити двері?',
        trES: '¿Puedes abrir la puerta?',
        noteRU: 'Can you звучит мягче, чем Open the door.',
        noteUK: 'Can you звучить м\'якше, ніж Open the door.',
        noteES: 'Can you sounds softer than Open the door.',
        notePtBr: 'Can you soa mais suave que Open the door.',
        noteVi: 'Can you nghe mềm hơn Open the door.',
        noteId: 'Can you terdengar lebih halus daripada Open the door.',
        noteTr: 'Can you, Open the door ifadesinden daha yumuşak duyulur.',
        notePl: 'Can you brzmi łagodniej niż Open the door.',
      },
    ],
    developerNotes: {
      screenGoal: 'Экран отделяет запреты Do not + verb от мягких просьб Can you + verb.',
      visualPriority: ['Do not выделять warning.', 'Can you выделять accent.', 'ошибку Not wait outside выделять danger.'],
      highlightRules: ['Do not = warning.', 'Can you = accent.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять don\'t как основной вариант.', 'Не добавлять could you / would you.', 'Не добавлять can you to help.', 'Не использовать фразы вне урока 18.'],
      layoutRules: ['Один экран - два контрастных блока: Do not и Can you.', 'Если экран узкий, оставить 3 Do not и 3 Can you.'],
    },
  },
  {
    lessonId: 18,
    screenId: 'lesson_18_intro_4_let_us_practice',
    order: 4,
    kind: 'practice',
    titleRU: 'Let us = давайте',
    titleUK: 'Let us = давайте',
    titleES: 'Let us = let\'s',
    titlePtBr: 'Let us = vamos',
    titleVi: 'Let us = hãy cùng',
    titleId: 'Let us = mari kita',
    titleTr: 'Let us = haydi',
    titlePl: 'Let us = zróbmy',
    subtitleRU: 'Когда предлагаешь сделать что-то вместе, используй Let us + действие.',
    subtitleUK: 'Коли пропонуєш зробити щось разом, використовуй Let us + дія.',
    subtitleES: 'When you suggest doing something together, use Let us + action.',
    subtitlePtBr: 'Quando você sugere fazer algo juntos, use Let us + ação.',
    subtitleVi: 'Khi đề nghị cùng làm gì đó, dùng Let us + hành động.',
    subtitleId: 'Saat mengajak melakukan sesuatu bersama, gunakan Let us + aksi.',
    subtitleTr: 'Bir şeyi birlikte yapmayı önerirken Let us + eylem kullan.',
    subtitlePl: 'Gdy proponujesz zrobić coś razem, użyj Let us + czynność.',
    textRU: 'Финальная проверка: сначала определи тип фразы, потом выбери конструкцию.',
    textUK: 'Фінальна перевірка: спочатку визнач тип фрази, потім обери конструкцію.',
    textES: 'Final check: first identify the sentence type, then choose the pattern.',
    textPtBr: 'Verificação final: primeiro identifique o tipo de frase, depois escolha o padrão.',
    textVi: 'Kiểm tra cuối: trước hết xác định loại câu, rồi chọn mẫu.',
    textId: 'Pemeriksaan akhir: tentukan dulu jenis kalimat, lalu pilih polanya.',
    textTr: 'Son kontrol: önce cümle türünü belirle, sonra kalıbı seç.',
    textPl: 'Końcowa kontrola: najpierw rozpoznaj typ zdania, potem wybierz wzór.',
    linesRU: [
      { type: 'formula', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'действие', tone: 'formula' }, { text: ' + остальные слова', tone: 'formula' }] },
      { type: 'spacer' },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' work together' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' check documents' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' order food' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' go back' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'spacer' },
      { type: 'step', parts: [{ text: '1. "Пожалуйста, сделай" -> ', tone: 'muted' }, { text: 'Please wait / Please help', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. "Сделай" -> ', tone: 'muted' }, { text: 'Wait / Start / Listen', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. "Не делай" -> ', tone: 'muted' }, { text: 'Do not wait / Do not call', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '4. "Ты можешь...?" -> ', tone: 'muted' }, { text: 'Can you help / Can you open', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '5. "Давайте..." -> ', tone: 'muted' }, { text: 'Let us start / Let us go back', tone: 'accent' }] },
      { type: 'spacer' },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Let us to start now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Let us cleaning up the room', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Правильно: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'tip', parts: [{ text: 'Главный навык урока: ', tone: 'strong' }, { text: 'сначала понять тип фразы: просьба, команда, запрет, Can you или Let us.' }] },
    ],
    linesUK: [
      { type: 'formula', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'дія', tone: 'formula' }, { text: ' + решта слів', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' work together' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'wrong', parts: [{ text: 'Не так: ', tone: 'warning' }, { text: 'Let us to start now', tone: 'danger' }] },
    ],
    linesES: [
      { type: 'formula', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' + action + other words', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
    ],
    linesPtBr: [
      { type: 'formula', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'ação', tone: 'formula' }, { text: ' + outras palavras', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' work together' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' check documents' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' order food' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' go back' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'step', parts: [{ text: '1. "Por favor, faça" -> ', tone: 'muted' }, { text: 'Please wait / Please help', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. "Faça" -> ', tone: 'muted' }, { text: 'Wait / Start / Listen', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. "Não faça" -> ', tone: 'muted' }, { text: 'Do not wait / Do not call', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '4. "Você pode...?" -> ', tone: 'muted' }, { text: 'Can you help / Can you open', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '5. "Vamos..." -> ', tone: 'muted' }, { text: 'Let us start / Let us go back', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'Let us to start now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'wrong', parts: [{ text: 'Não assim: ', tone: 'warning' }, { text: 'Let us cleaning up the room', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Certo: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'tip', parts: [{ text: 'Habilidade principal: ', tone: 'strong' }, { text: 'primeiro entenda o tipo da frase: pedido, comando, proibição, Can you ou Let us.' }] },
    ],
    linesVi: [
      { type: 'formula', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'hành động', tone: 'formula' }, { text: ' + các từ còn lại', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' work together' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' check documents' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' order food' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' go back' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'step', parts: [{ text: '1. "Làm ơn làm..." -> ', tone: 'muted' }, { text: 'Please wait / Please help', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. "Làm đi" -> ', tone: 'muted' }, { text: 'Wait / Start / Listen', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. "Đừng làm" -> ', tone: 'muted' }, { text: 'Do not wait / Do not call', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '4. "Bạn có thể...?" -> ', tone: 'muted' }, { text: 'Can you help / Can you open', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '5. "Hãy cùng..." -> ', tone: 'muted' }, { text: 'Let us start / Let us go back', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'Let us to start now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'wrong', parts: [{ text: 'Không đúng: ', tone: 'warning' }, { text: 'Let us cleaning up the room', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Đúng: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'tip', parts: [{ text: 'Kỹ năng chính: ', tone: 'strong' }, { text: 'trước hết hiểu loại câu: lời nhờ, mệnh lệnh, cấm, Can you hoặc Let us.' }] },
    ],
    linesId: [
      { type: 'formula', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'aksi', tone: 'formula' }, { text: ' + kata lain', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' work together' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' check documents' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' order food' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' go back' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'step', parts: [{ text: '1. "Tolong lakukan" -> ', tone: 'muted' }, { text: 'Please wait / Please help', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. "Lakukan" -> ', tone: 'muted' }, { text: 'Wait / Start / Listen', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. "Jangan lakukan" -> ', tone: 'muted' }, { text: 'Do not wait / Do not call', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '4. "Bisakah kamu...?" -> ', tone: 'muted' }, { text: 'Can you help / Can you open', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '5. "Mari kita..." -> ', tone: 'muted' }, { text: 'Let us start / Let us go back', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'Let us to start now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'wrong', parts: [{ text: 'Bukan begini: ', tone: 'warning' }, { text: 'Let us cleaning up the room', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Benar: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'tip', parts: [{ text: 'Kemampuan utama: ', tone: 'strong' }, { text: 'pahami dulu jenis kalimatnya: permintaan, perintah, larangan, Can you, atau Let us.' }] },
    ],
    linesTr: [
      { type: 'formula', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'eylem', tone: 'formula' }, { text: ' + diğer sözler', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' work together' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' check documents' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' order food' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' go back' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'step', parts: [{ text: '1. "Lütfen yap" -> ', tone: 'muted' }, { text: 'Please wait / Please help', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. "Yap" -> ', tone: 'muted' }, { text: 'Wait / Start / Listen', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. "Yapma" -> ', tone: 'muted' }, { text: 'Do not wait / Do not call', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '4. "Yapabilir misin...?" -> ', tone: 'muted' }, { text: 'Can you help / Can you open', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '5. "Haydi..." -> ', tone: 'muted' }, { text: 'Let us start / Let us go back', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'Let us to start now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'wrong', parts: [{ text: 'Böyle değil: ', tone: 'warning' }, { text: 'Let us cleaning up the room', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Doğru: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'tip', parts: [{ text: 'Ana beceri: ', tone: 'strong' }, { text: 'önce cümle türünü anla: rica, komut, yasak, Can you veya Let us.' }] },
    ],
    linesPl: [
      { type: 'formula', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' + ', tone: 'muted' }, { text: 'czynność', tone: 'formula' }, { text: ' + reszta słów', tone: 'formula' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' work together' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' check documents' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' order food' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' go back' }] },
      { type: 'correct', parts: [{ text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'step', parts: [{ text: '1. "Proszę, zrób" -> ', tone: 'muted' }, { text: 'Please wait / Please help', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '2. "Zrób" -> ', tone: 'muted' }, { text: 'Wait / Start / Listen', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '3. "Nie rób" -> ', tone: 'muted' }, { text: 'Do not wait / Do not call', tone: 'warning' }] },
      { type: 'step', parts: [{ text: '4. "Czy możesz...?" -> ', tone: 'muted' }, { text: 'Can you help / Can you open', tone: 'accent' }] },
      { type: 'step', parts: [{ text: '5. "Zróbmy..." -> ', tone: 'muted' }, { text: 'Let us start / Let us go back', tone: 'accent' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'Let us to start now', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' start now' }] },
      { type: 'wrong', parts: [{ text: 'Nie tak: ', tone: 'warning' }, { text: 'Let us cleaning up the room', tone: 'danger' }] },
      { type: 'correct', parts: [{ text: 'Poprawnie: ', tone: 'success' }, { text: 'Let us', tone: 'accent' }, { text: ' clean up the room' }] },
      { type: 'tip', parts: [{ text: 'Główna umiejętność: ', tone: 'strong' }, { text: 'najpierw rozpoznaj typ zdania: prośba, polecenie, zakaz, Can you albo Let us.' }] },
    ],
    examples: [
      {
        labelRU: 'давайте',
        labelUK: 'давайте',
        labelES: 'let us',
        labelPtBr: 'let us',
        labelVi: 'let us',
        labelId: 'let us',
        labelTr: 'let us',
        labelPl: 'let us',
        en: [{ text: 'Let us', tone: 'accent' }, { text: ' find a better option' }],
        ru: 'Давайте найдем лучший вариант',
        uk: 'Давайте знайдемо кращий варіант',
        es: 'Busquemos una opción mejor.',
        'pt-BR': 'Vamos encontrar uma opção melhor.',
        vi: 'Hãy tìm một lựa chọn tốt hơn.',
        id: 'Mari kita cari pilihan yang lebih baik.',
        tr: 'Daha iyi bir seçenek bulalım.',
        pl: 'Znajdźmy lepszą opcję.',
        trRU: 'Давайте найдем лучший вариант',
        trUK: 'Давайте знайдемо кращий варіант',
        trES: 'Busquemos una opción mejor.',
        noteRU: 'После Let us действие идет без to.',
        noteUK: 'Після Let us дія йде без to.',
        noteES: 'After Let us, the action goes without to.',
        notePtBr: 'Depois de Let us, a ação vem sem to.',
        noteVi: 'Sau Let us, hành động đi không có to.',
        noteId: 'Setelah Let us, aksi datang tanpa to.',
        noteTr: 'Let us sonrasında eylem to olmadan gelir.',
        notePl: 'Po Let us czynność idzie bez to.',
      },
      {
        labelRU: 'фразовый глагол',
        labelUK: 'фразове дієслово',
        labelES: 'phrasal verb',
        labelPtBr: 'phrasal verb',
        labelVi: 'cụm động từ',
        labelId: 'phrasal verb',
        labelTr: 'phrasal verb',
        labelPl: 'czasownik frazowy',
        en: [{ text: 'Let us', tone: 'accent' }, { text: ' clean ' }, { text: 'up', tone: 'warning' }, { text: ' the room' }],
        ru: 'Давайте уберем комнату',
        uk: 'Давайте приберемо кімнату',
        es: 'Limpiemos la habitación.',
        'pt-BR': 'Vamos arrumar o quarto.',
        vi: 'Hãy dọn dẹp căn phòng.',
        id: 'Mari kita bersihkan kamar.',
        tr: 'Odayı toparlayalım.',
        pl: 'Posprzątajmy pokój.',
        trRU: 'Давайте уберем комнату',
        trUK: 'Давайте приберемо кімнату',
        trES: 'Limpiemos la habitación.',
        noteRU: 'Clean up остается связкой.',
        noteUK: 'Clean up залишається зв\'язкою.',
        noteES: 'Clean up stays as one unit.',
        notePtBr: 'Clean up continua uma unidade.',
        noteVi: 'Clean up vẫn là một cụm.',
        noteId: 'Clean up tetap satu unit.',
        noteTr: 'Clean up tek bir birim olarak kalır.',
        notePl: 'Clean up zostaje jedną jednostką.',
      },
    ],
    developerNotes: {
      screenGoal: 'Финальный экран объясняет Let us и дает общий алгоритм выбора между Please, direct command, Do not, Can you и Let us.',
      visualPriority: ['Let us выделять accent.', 'Do not в алгоритме выделять warning.', 'ошибки Let us to start и Let us cleaning выделять danger.', 'частицы фразовых глаголов up/back выделять warning.'],
      highlightRules: ['Let us = accent.', 'Do not = warning.', 'phrasal particle = warning.', 'wrong example = danger.'],
      forbiddenContent: ['Не добавлять Let him / Let her.', 'Не добавлять Let\'s сокращение как основной вариант.', 'Не добавлять would you / could you.', 'Не использовать фразы вне урока 18.'],
      layoutRules: ['Экран финальный и практический.', 'Если не помещается, оставить Let us start, Let us clean up, общий алгоритм и одну ошибку Let us to start.'],
    },
  },
];
