// AUTO-GENERATED by scripts/regen_plan_listen_audio_full.mjs — do not edit by hand.
//
// NEUTRALIZED 2026-06-22: the static require() map used to bundle every runtime
// listen-audio mp3 into the native binary (~126 MB). Those clips now stream from
// Firebase Storage and are disk-cached on device — see
//   app/plan_audio_url_map.generated.ts               (uri -> Storage download URL)
//   app/personal_plan_listening_playback_contract.ts  (resolver: remote-first)
//   scripts/upload_plan_audio_to_storage.mjs          (uploader / map generator)
// Removing the require() calls is what actually drops the ~126 MB from the build,
// so this map is intentionally EMPTY. The function below is kept so the resolver's
// local-asset fallback path stays type-safe; it returns undefined now (every uri
// is covered by the URL map). The original mp3 stay on disk under
// assets/audio/personal-plans-runtime/ as a backup and can be re-bundled by
// re-running the regen script if the server path is ever rolled back.
const RUNTIME_AUDIO_ASSET_MODULES: Record<string, number> = {};

export function getPersonalPlanRuntimeAudioAssetModule(uri: string): number | undefined {
  return RUNTIME_AUDIO_ASSET_MODULES[uri.trim().replace(/\\/g, '/')];
}
