// Чистый копирайт для состояний загрузки/ошибки тренажёров (без RN-импортов,
// чтобы можно было покрыть юнит-тестами в node-окружении).
export const TRAINER_LOAD_COPY = {
  loading: {
    ru: 'Загружаем…',
    uk: 'Завантажуємо…',
    es: 'Cargando…',
    'pt-BR': 'Carregando…',
    vi: 'Đang tải…',
    id: 'Memuat…',
    tr: 'Yükleniyor…',
    pl: 'Ładowanie…',
  },
  errorTitle: {
    ru: 'Не удалось загрузить',
    uk: 'Не вдалося завантажити',
    es: 'No se pudo cargar',
    'pt-BR': 'Não foi possível carregar',
    vi: 'Không tải được',
    id: 'Tidak bisa memuat',
    tr: 'Yüklenemedi',
    pl: 'Nie udało się załadować',
  },
  errorBody: {
    ru: 'Проверь интернет и попробуй ещё раз.',
    uk: 'Перевірте підключення до інтернету та спробуйте знову.',
    es: 'Comprueba tu conexión a internet e inténtalo de nuevo.',
    'pt-BR': 'Verifique sua conexão com a internet e tente novamente.',
    vi: 'Hãy kiểm tra kết nối internet rồi thử lại.',
    id: 'Periksa koneksi internetmu lalu coba lagi.',
    tr: 'İnternet bağlantını kontrol edip tekrar dene.',
    pl: 'Sprawdź połączenie z internetem i spróbuj ponownie.',
  },
  retry: {
    ru: 'Попробовать снова',
    uk: 'Спробувати знову',
    es: 'Reintentar',
    'pt-BR': 'Tentar de novo',
    vi: 'Thử lại',
    id: 'Coba lagi',
    tr: 'Tekrar dene',
    pl: 'Spróbuj ponownie',
  },
  exit: {
    ru: 'Выйти',
    uk: 'Вийти',
    es: 'Salir',
    'pt-BR': 'Sair',
    vi: 'Thoát',
    id: 'Keluar',
    tr: 'Çık',
    pl: 'Wyjdź',
  },
} as const;
