// зачем: приложение не может require() файлы по динамическому пути — RN бандлит
// только статические require. Публикация копирует ПРИНЯТЫЙ каталог в assets и
// генерирует статическую карту require'ов. Единственный путь ассета в приложение:
// check_render --accept → publish_catalog → assets/avatar-25d.
import path from 'node:path';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';

const pipelineRoot = path.resolve(import.meta.dirname, '..');
const repoRoot = path.resolve(pipelineRoot, '..', '..');
const assetsRoot = path.join(repoRoot, 'assets', 'avatar-25d');

const manifest = JSON.parse(await readFile(path.join(pipelineRoot, 'manifest.json'), 'utf8'));
await mkdir(assetsRoot, { recursive: true });

const mapEntries = [];
for (const item of manifest.items) {
  const source = path.join(pipelineRoot, item.file);
  const destination = path.join(assetsRoot, item.file);
  await mkdir(path.dirname(destination), { recursive: true });
  await copyFile(source, destination);
  mapEntries.push(`  '${item.slot}/${item.id}': require('./${item.file.replace(/\\/g, '/')}'),`);
}

await writeFile(path.join(assetsRoot, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
await writeFile(path.join(assetsRoot, 'asset_map.generated.ts'),
  '// AUTO-GENERATED by content/avatar-studio/scripts/publish_catalog.mjs — не править руками.\n' +
  '// Перегенерация: node content/avatar-studio/scripts/publish_catalog.mjs\n' +
  'export const AVATAR_25D_ASSETS: Record<string, number> = {\n' +
  mapEntries.join('\n') + (mapEntries.length ? '\n' : '') +
  '};\n');
process.stdout.write(`Опубликовано ассетов: ${manifest.items.length} → assets/avatar-25d\n`);
