// Localized labels and static UI metadata for flashcards screen.
import { CardItem, Category, CategoryId } from './types';

export const STR = {
  ru: {
    title: 'Карточки',
    hubTitle: 'Жемчужины',
    empty: 'Нет карточек', emptySub: '', nothingFound: 'Ничего не найдено',
    done: 'Все карточки просмотрены!', doneSub: 'Отличная работа', restart: 'Начать заново',
    cardOf: (a: number, b: number) => `${a} / ${b}`,
    tapFlip: 'Нажми чтобы перевернуть', delete: 'Удалить',
    deleteConfirm: 'Удалить карточку?', deleteConfirmSub: 'Она будет удалена.',
    cancel: 'Отмена', back: 'Назад',
    editFront: 'Передняя сторона', editBack: 'Задняя сторона', next: 'Далее →',
    save: 'Сохранить', editCard: 'Редактировать карточку', newCard: 'Новая карточка',
    systemCannotDelete: 'Системные карточки нельзя удалять',
    enterEN: 'Текст передней стороны...', enterRU: 'Текст задней стороны...',
    editDescription: 'Описание', enterDescription: 'Краткая заметка, контекст или подсказка (необязательно)...',
    noDelete: 'Это системная карточка',
    source: { lesson: 'Урок', word: 'Слово', verb: 'Глагол', dialog: 'Диалог' },
  },
  uk: {
    title: 'Картки',
    hubTitle: 'Жемчужини',
    empty: 'Немає карток', emptySub: '', nothingFound: 'Нічого не знайдено',
    done: 'Всі картки переглянуто!', doneSub: 'Чудова робота', restart: 'Почати знову',
    cardOf: (a: number, b: number) => `${a} / ${b}`,
    tapFlip: 'Натисни щоб перевернути', delete: 'Видалити',
    deleteConfirm: 'Видалити картку?', deleteConfirmSub: 'Вона буде видалена.',
    cancel: 'Скасувати', back: 'Назад',
    editFront: 'Передня сторона', editBack: 'Зворотна сторона', next: 'Далі →',
    save: 'Зберегти', editCard: 'Редагувати картку', newCard: 'Нова картка',
    systemCannotDelete: 'Системні картки не можна видаляти',
    enterEN: 'Текст передньої сторони...', enterRU: 'Текст зворотної сторони...',
    editDescription: 'Опис', enterDescription: 'Коротка нотатка, контекст або підказка (за бажанням)...',
    noDelete: 'Це системна картка',
    source: { lesson: 'Урок', word: 'Слово', verb: 'Дієслово', dialog: 'Діалог' },
  },
  es: {
    title: 'Tarjetas',
    hubTitle: 'Perlas',
    empty: 'No hay tarjetas', nothingFound: 'No se encontró nada',
    emptySub: '',
    done: '¡Has visto todas las tarjetas!',
    doneSub: 'Buen trabajo',
    restart: 'Empezar de nuevo',
    cardOf: (a: number, b: number) => `${a} / ${b}`,
    tapFlip: 'Toca para voltear',
    delete: 'Eliminar',
    deleteConfirm: '¿Eliminar la tarjeta?',
    deleteConfirmSub: 'Se eliminará.',
    cancel: 'Cancelar',
    back: 'Atrás',
    editFront: 'Cara delantera',
    editBack: 'Cara trasera',
    next: 'Siguiente →',
    save: 'Guardar',
    editCard: 'Editar tarjeta',
    newCard: 'Tarjeta nueva',
    systemCannotDelete: 'Las tarjetas del sistema no se pueden eliminar',
    enterEN: 'Texto de la cara delantera...',
    enterRU: 'Texto de la cara trasera...',
    editDescription: 'Descripción',
    enterDescription: 'Nota breve, contexto o pista (opcional)...',
    noDelete: 'Es una tarjeta del sistema',
    source: { lesson: 'Lección', word: 'Palabra', verb: 'Verbo', dialog: 'Diálogo' },
  },
  'pt-BR': {
    title: 'Cartões',
    hubTitle: 'Perlas',
    empty: 'Nenhum cartão', nothingFound: 'Nada encontrado',
    emptySub: '',
    done: 'Todos os cartões foram vistos!',
    doneSub: 'Bom trabalho',
    restart: 'Começar de novo',
    cardOf: (a: number, b: number) => `${a} / ${b}`,
    tapFlip: 'Toque para virar',
    delete: 'Excluir',
    deleteConfirm: 'Excluir cartão?',
    deleteConfirmSub: 'Ele será excluído.',
    cancel: 'Cancelar',
    back: 'Voltar',
    editFront: 'Frente',
    editBack: 'Verso',
    next: 'Próximo →',
    save: 'Salvar',
    editCard: 'Editar cartão',
    newCard: 'Novo cartão',
    systemCannotDelete: 'Cartões do sistema não podem ser excluídos',
    enterEN: 'Texto da frente...',
    enterRU: 'Texto do verso...',
    editDescription: 'Descrição',
    enterDescription: 'Nota curta, contexto ou dica (opcional)...',
    noDelete: 'Este é um cartão do sistema',
    source: { lesson: 'Lição', word: 'Palavra', verb: 'Verbo', dialog: 'Diálogo' },
  },
  vi: {
    title: 'Thẻ',
    hubTitle: 'Mảnh',
    empty: 'Không có thẻ', nothingFound: 'Không tìm thấy gì',
    emptySub: '',
    done: 'Bạn đã xem hết thẻ!',
    doneSub: 'Làm tốt lắm',
    restart: 'Bắt đầu lại',
    cardOf: (a: number, b: number) => `${a} / ${b}`,
    tapFlip: 'Nhấn để lật',
    delete: 'Xóa',
    deleteConfirm: 'Xóa thẻ?',
    deleteConfirmSub: 'Thẻ sẽ bị xóa.',
    cancel: 'Hủy',
    back: 'Quay lại',
    editFront: 'Mặt trước',
    editBack: 'Mặt sau',
    next: 'Tiếp →',
    save: 'Lưu',
    editCard: 'Sửa thẻ',
    newCard: 'Thẻ mới',
    systemCannotDelete: 'Không thể xóa thẻ hệ thống',
    enterEN: 'Nội dung mặt trước...',
    enterRU: 'Nội dung mặt sau...',
    editDescription: 'Mô tả',
    enterDescription: 'Ghi chú ngắn, ngữ cảnh hoặc gợi ý (không bắt buộc)...',
    noDelete: 'Đây là thẻ hệ thống',
    source: { lesson: 'Bài học', word: 'Từ', verb: 'Động từ', dialog: 'Hội thoại' },
  },
  'id': {
    title: 'Kartu',
    hubTitle: 'Shard',
    empty: 'Tidak ada kartu', nothingFound: 'Tidak ditemukan',
    emptySub: '',
    done: 'Semua kartu sudah dilihat!',
    doneSub: 'Kerja bagus',
    restart: 'Mulai lagi',
    cardOf: (a: number, b: number) => `${a} / ${b}`,
    tapFlip: 'Ketuk untuk membalik',
    delete: 'Hapus',
    deleteConfirm: 'Hapus kartu?',
    deleteConfirmSub: 'Kartu ini akan dihapus.',
    cancel: 'Batal',
    back: 'Kembali',
    editFront: 'Sisi depan',
    editBack: 'Sisi belakang',
    next: 'Lanjut →',
    save: 'Simpan',
    editCard: 'Edit kartu',
    newCard: 'Kartu baru',
    systemCannotDelete: 'Kartu sistem tidak bisa dihapus',
    enterEN: 'Teks sisi depan...',
    enterRU: 'Teks sisi belakang...',
    editDescription: 'Deskripsi',
    enterDescription: 'Catatan singkat, konteks, atau petunjuk (opsional)...',
    noDelete: 'Ini kartu sistem',
    source: { lesson: 'Pelajaran', word: 'Kata', verb: 'Verba', dialog: 'Dialog' },
  },
  tr: {
    title: 'Kartlar',
    hubTitle: 'Parçalar',
    empty: 'Kart yok', nothingFound: 'Hiçbir şey bulunamadı',
    emptySub: '',
    done: 'Tüm kartlar görüldü!',
    doneSub: 'İyi iş',
    restart: 'Yeniden başla',
    cardOf: (a: number, b: number) => `${a} / ${b}`,
    tapFlip: 'Çevirmek için dokun',
    delete: 'Sil',
    deleteConfirm: 'Kart silinsin mi?',
    deleteConfirmSub: 'Silinecek.',
    cancel: 'İptal',
    back: 'Geri',
    editFront: 'Ön yüz',
    editBack: 'Arka yüz',
    next: 'İleri →',
    save: 'Kaydet',
    editCard: 'Kartı düzenle',
    newCard: 'Yeni kart',
    systemCannotDelete: 'Sistem kartları silinemez',
    enterEN: 'Ön yüz metni...',
    enterRU: 'Arka yüz metni...',
    editDescription: 'Açıklama',
    enterDescription: 'Kısa not, bağlam veya ipucu (isteğe bağlı)...',
    noDelete: 'Bu bir sistem kartı',
    source: { lesson: 'Ders', word: 'Kelime', verb: 'Fiil', dialog: 'Diyalog' },
  },
  pl: {
    title: 'Karty',
    hubTitle: 'Perły',
    empty: 'Brak kart', nothingFound: 'Nic nie znaleziono',
    emptySub: '',
    done: 'Wszystkie karty obejrzane!',
    doneSub: 'Dobra robota',
    restart: 'Zacznij od nowa',
    cardOf: (a: number, b: number) => `${a} / ${b}`,
    tapFlip: 'Dotknij, aby odwrócić',
    delete: 'Usuń',
    deleteConfirm: 'Usunąć kartę?',
    deleteConfirmSub: 'Zostanie usunięta.',
    cancel: 'Anuluj',
    back: 'Wstecz',
    editFront: 'Przednia strona',
    editBack: 'Tylna strona',
    next: 'Dalej →',
    save: 'Zapisz',
    editCard: 'Edytuj kartę',
    newCard: 'Nowa karta',
    systemCannotDelete: 'Kart systemowych nie można usuwać',
    enterEN: 'Tekst przedniej strony...',
    enterRU: 'Tekst tylnej strony...',
    editDescription: 'Opis',
    enterDescription: 'Krótka notatka, kontekst lub podpowiedź (opcjonalnie)...',
    noDelete: 'To karta systemowa',
    source: { lesson: 'Lekcja', word: 'Słowo', verb: 'Czasownik', dialog: 'Dialog' },
  },
};

export const CATEGORIES: Category[] = [
  { id: 'saved', icon: 'bookmark-outline', labelRU: 'Сохранённые', labelUK: 'Збережені', labelES: 'Guardadas', labelPtBr: 'Salvas', labelVi: 'Đã lưu', labelId: 'Tersimpan', labelTr: 'Kaydedilenler', labelPl: 'Zapisane', fullLabelRU: 'Сохранённые', fullLabelUK: 'Збережені', fullLabelES: 'Guardadas', fullLabelPtBr: 'Salvas', fullLabelVi: 'Đã lưu', fullLabelId: 'Tersimpan', fullLabelTr: 'Kaydedilenler', fullLabelPl: 'Zapisane' },
  { id: 'emotions', icon: 'heart-outline', labelRU: 'Эмоции', labelUK: 'Емоції', labelES: 'Emoc.', labelPtBr: 'Emoç.', labelVi: 'Cảm xúc', labelId: 'Emosi', labelTr: 'Duygu', labelPl: 'Emocje', fullLabelRU: 'Эмоции', fullLabelUK: 'Емоції', fullLabelES: 'Emociones', fullLabelPtBr: 'Emoções', fullLabelVi: 'Cảm xúc', fullLabelId: 'Emosi', fullLabelTr: 'Duygular', fullLabelPl: 'Emocje' },
  { id: 'fillers', icon: 'chatbubble-ellipses-outline', labelRU: 'Филлеры', labelUK: 'Філери', labelES: 'Mulet.', labelPtBr: 'Mulet.', labelVi: 'Từ đệm', labelId: 'Pengisi', labelTr: 'Dolgu', labelPl: 'Wypeł.', fullLabelRU: 'Филлеры', fullLabelUK: 'Філери', fullLabelES: 'Muletillas', fullLabelPtBr: 'Muletilhas', fullLabelVi: 'Từ đệm', fullLabelId: 'Kata pengisi', fullLabelTr: 'Dolgu ifadeleri', fullLabelPl: 'Wypełniacze' },
  { id: 'reactions', icon: 'flash-outline', labelRU: 'Реакции', labelUK: 'Реакції', labelES: 'Reacc.', labelPtBr: 'Reaç.', labelVi: 'Phản ứng', labelId: 'Reaksi', labelTr: 'Tepki', labelPl: 'Reakcje', fullLabelRU: 'Реакции', fullLabelUK: 'Реакції', fullLabelES: 'Reacciones', fullLabelPtBr: 'Reações', fullLabelVi: 'Phản ứng', fullLabelId: 'Reaksi', fullLabelTr: 'Tepkiler', fullLabelPl: 'Reakcje' },
  { id: 'traps', icon: 'alert-circle-outline', labelRU: 'Ловушки', labelUK: 'Пастки', labelES: 'Trampas', labelPtBr: 'Armad.', labelVi: 'Bẫy', labelId: 'Jebakan', labelTr: 'Tuzak', labelPl: 'Pułapki', fullLabelRU: 'Ловушки', fullLabelUK: 'Пастки', fullLabelES: 'Trampas', fullLabelPtBr: 'Armadilhas', fullLabelVi: 'Bẫy thường gặp', fullLabelId: 'Jebakan', fullLabelTr: 'Tuzaklar', fullLabelPl: 'Pułapki' },
  { id: 'phrasal', icon: 'git-branch-outline', labelRU: 'Глаголы', labelUK: 'Дієслова', labelES: 'Verbos', labelPtBr: 'Verbos', labelVi: 'Cụm ĐT', labelId: 'Verba', labelTr: 'Fiiller', labelPl: 'Czas.', fullLabelRU: 'Фразовые глаголы', fullLabelUK: 'Дієслова', fullLabelES: 'Verbos frasales', fullLabelPtBr: 'Phrasal verbs', fullLabelVi: 'Cụm động từ', fullLabelId: 'Phrasal verbs', fullLabelTr: 'Phrasal verbs', fullLabelPl: 'Czasowniki frazowe' },
  { id: 'situations', icon: 'map-outline', labelRU: 'Ситуации', labelUK: 'Ситуації', labelES: 'Situac.', labelPtBr: 'Situaç.', labelVi: 'Tình huống', labelId: 'Situasi', labelTr: 'Durum', labelPl: 'Sytuacje', fullLabelRU: 'Ситуации', fullLabelUK: 'Ситуації', fullLabelES: 'Situaciones', fullLabelPtBr: 'Situações', fullLabelVi: 'Tình huống', fullLabelId: 'Situasi', fullLabelTr: 'Durumlar', fullLabelPl: 'Sytuacje' },
  { id: 'connectors', icon: 'git-network-outline', labelRU: 'Связки', labelUK: 'Зв\'язки', labelES: 'Conect.', labelPtBr: 'Conect.', labelVi: 'Liên kết', labelId: 'Konektor', labelTr: 'Bağlaç', labelPl: 'Łącz.', fullLabelRU: 'Связки', fullLabelUK: 'Зв\'язки', fullLabelES: 'Conectores', fullLabelPtBr: 'Conectores', fullLabelVi: 'Từ nối', fullLabelId: 'Konektor', fullLabelTr: 'Bağlayıcılar', fullLabelPl: 'Łączniki' },
  {
    id: 'custom',
    icon: 'add-circle-outline',
    labelRU: 'Создать',
    labelUK: 'Створити',
    labelES: 'Crear',
    labelPtBr: 'Criar',
    labelVi: 'Tạo',
    labelId: 'Buat',
    labelTr: 'Oluştur',
    labelPl: 'Utwórz',
    fullLabelRU: 'Мои карточки',
    fullLabelUK: 'Мої картки',
    fullLabelES: 'Mis tarjetas',
    fullLabelPtBr: 'Meus cartões',
    fullLabelVi: 'Thẻ của tôi',
    fullLabelId: 'Kartu saya',
    fullLabelTr: 'Kartlarım',
    fullLabelPl: 'Moje karty',
  },
];

/** Плитки на экране-хабе карточек: только сохранённые и свои; системные темы — только в данных/фильтрах. */
export const FLASHCARDS_HUB_CATEGORY_ORDER: CategoryId[] = ['saved'];

export function categoriesForFlashcardsHub(): Category[] {
  const orderedHubItems = FLASHCARDS_HUB_CATEGORY_ORDER.map((id) => CATEGORIES.find((c) => c.id === id)).filter(
    (c): c is Category => c != null,
  );
  return orderedHubItems;
}

export const SOURCE_COLORS: Record<string, string> = {
  lesson: '#4A90D9', word: '#7B68EE', verb: '#E87D3E', dialog: '#50BFA0',
};

export function getCardTint(card: CardItem): string | null {
  if (!card.source) return null;
  if (card.source === 'lesson' && card.sourceId) {
    const n = parseInt(card.sourceId, 10);
    if (n <= 8) return '#4CAF72';
    if (n <= 18) return '#40B4E8';
    if (n <= 28) return '#D4A017';
    return '#DC6428';
  }
  return SOURCE_COLORS[card.source] ?? null;
}

/* expo-router route shim: keeps utility module from warning when discovered as route */
export default function __RouteShim() { return null; }
