"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EPISODE_01_SESSION_06_SOURCE = void 0;
// Generated by scripts/import_learning_v2_first_ten_candidate.mjs.
// Learner-facing bytes come from the immutable owner-approved SHA below.
const approved_first_ten_source_v2_1 = require("./approved_first_ten_source_v2");
exports.EPISODE_01_SESSION_06_SOURCE = approved_first_ten_source_v2_1.APPROVED_FIRST_TEN_SESSION_SOURCES_V2[5];
//# sourceMappingURL=episode_01_session_06_v1.js.map