#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const check = process.argv.includes("--check");
const manifestPath = path.resolve(root, "assets/audio/learning-v2/factory-production-v1/manifest.json");
const outputPath = path.resolve(root, "app/learning_v2_factory_production_audio_entries_v1.generated.ts");
if (!fs.existsSync(manifestPath)) throw new Error("factory_audio_manifest_missing");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
const lines = [
  "/* Generated by scripts/build_learning_v2_factory_audio_module.mjs. */",
  `export const FACTORY_PRODUCTION_AUDIO_EXPECTED_ENTRY_COUNT_V1 = ${manifest.expectedEntryCount} as const;`,
  "export const FACTORY_PRODUCTION_AUDIO_ENTRIES_V1 = Object.freeze([",
];
for (const entry of manifest.entries) {
  const absolute = path.resolve(root, entry.assetPath);
  if (!fs.existsSync(absolute) || fs.statSync(absolute).size !== entry.byteSize) throw new Error(`factory_audio_asset_invalid:${entry.assetPath}`);
  const requirePath = `../${entry.assetPath}`.replaceAll("\\", "/");
  lines.push(`  Object.freeze({ transcript: ${JSON.stringify(entry.transcript)}, voiceId: ${JSON.stringify(entry.voiceId)} as const, contentHash: ${JSON.stringify(entry.contentHash)}, byteSize: ${entry.byteSize}, assetModule: require(${JSON.stringify(requirePath)}) as number }),`);
}
lines.push("] as const);", "");
const next = lines.join("\n");
if (check) {
  if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== next) throw new Error("factory_audio_module_stale");
  console.log(`factory audio module PASS (${manifest.entries.length}/${manifest.expectedEntryCount} files)`);
} else {
  fs.writeFileSync(outputPath, next, "utf8");
  console.log(`wrote ${path.relative(root, outputPath)} (${manifest.entries.length}/${manifest.expectedEntryCount} files)`);
}
