/** Lesson 21 — pronombres indefinidos / past simple */
export default [
  'Alguien llamó a mi puerta tarde por la noche.',
  'Nadie conoce este código secreto.',
  'Todos trajeron sus portátiles a la reunión.',
  'Encontré algo interesante en tu jardín.',
  '¿Viste a alguien en aquella oficina vacía?',
  'Alguien te dejó este mensaje sobre la mesa.',
  'No oímos nada sobre ese incidente.',
  'Todos quieren saber la verdad sobre esta situación.',
  '¿Encontraste algo útil en aquel libro viejo?',
  'Nadie acudió a aquella conferencia importante ayer.',
  'Alguien me robó el bolso de cuero en ese centro comercial.',
  'Nadie creyó esa historia extraña de fantasmas.',
  'Todo cambió después de esa breve llamada.',
  '¿Trajiste algo rico para nuestro almuerzo festivo?',
  'Alguien escondió esos documentos importantes en la caja fuerte vieja.',
  'Alguien derramó café sobre tu vestido blanco nuevo.',
  'Nadie respondió a esa llamada rara.',
  'Todos entendieron esa tarea difícil después de la explicación.',
  '¿Notaste algo raro en aquel jardín viejo?',
  'Alguien puso esas cajas pesadas en la estantería frágil.',
  'Alguien envió esta carta anónima ayer por la mañana.',
  'Nadie abrió esa puerta pesada por el viento fuerte.',
  'Todo parece distinto después de este viaje largo.',
  '¿Oíste algo sobre esa nueva ley?',
  'Alguien olvidó estas gafas de sol en aquel banco de metal.',
  'Alguien robó esa cuchara de plata durante la cena de gala.',
  'Nadie vio aquel coche gris viejo en el aparcamiento.',
  'Todo parece posible en este día soleado y bonito.',
  '¿Compraste algo útil para esta cocina nueva?',
  'Alguien metió esa ropa mojada en esta cesta grande.',
  'Nadie abrió esta ventana vieja por el viento fuerte.',
  'Todos entendieron esa tarea difícil después de tu explicación.',
  '¿Trajiste algo rico para nuestra fiesta pequeña?',
  'Alguien escondió esa llave importante debajo del felpudo.',
  'No vimos nada en aquella cueva oscura ayer.',
  'Alguien derramó zumo de fruta en esta alfombra clara.',
  'Nadie reconoció a ese cantante famoso con gafas de sol.',
  'Todos se sintieron cansados después de aquella caminata larga.',
  '¿Viste a alguien cerca de ese edificio abandonado?',
  'Alguien dejó estos platos sucios en el fregadero.',
  'Alguien me robó la chaqueta de cuero en este bar lleno de gente.',
  'Nadie creyó esa excusa rara durante la reunión.',
  'Todo cambió después de esa breve visita oficial.',
  '¿Encontraste algo útil en aquel taller viejo?',
  'Alguien escondió esos documentos secretos bajo las escaleras de madera.',
  'Alguien dejó ese cuchillo afilado sobre esta mesa de cocina.',
  'Nadie oyó ese ruido fuerte en esta calle estrecha.',
  'Todos trajeron sus tentempiés favoritos a aquella fiesta en el campo.',
  '¿Encontraste algo valioso en aquel sótano viejo abandonado?',
  'Alguien escondió esa moneda de oro dentro de esta caja pequeña de hierro.',
];
