/** Lesson 22 — gerundios e infinitivos */
export default [
  'Nadar en el océano frío resulta muy refrescante.',
  '¿Terminó de escribir ese informe técnico largo?',
  'A mi hermano no le gusta cocinar comida picante.',
  'Aprender idiomas extranjeros abre nuevas oportunidades.',
  '¿Prefieres viajar en tren o en avión?',
  'Leer este artículo nuevo me ayuda a entender la economía moderna.',
  'No dejaron de hablar de ese problema viejo en la reunión.',
  'Montar en bicicleta por el parque es su actividad favorita.',
  '¿Nuestro gerente sugirió cambiar la fecha de esa reunión importante?',
  'No evitamos comprar juguetes baratos de plástico para los niños.',
  'Pintar estos paisajes luminosos requiere mucha paciencia.',
  'Sigue ignorando mis mensajes sin motivo claro.',
  '¿Tu afición es coleccionar monedas antiguas raras?',
  'No se imagina la vida sin bailar en el escenario.',
  'Limpiar este piso enorme lleva todo el día.',
  'Esperar el transporte público lleva demasiado tiempo por la mañana.',
  '¿Tu oferta incluye visitar ese museo histórico?',
  'No les gusta pasear por este centro comercial ruidoso.',
  'Revisar todos estos documentos importantes es un trabajo aburrido.',
  'Valoramos disponer de este equipo fiable en nuestro laboratorio.',
  'Está terminantemente prohibido fumar en este lugar público.',
  'Alguien sugirió pedir esa pizza grande con champiñones.',
  '¿Tu afición es coleccionar estos sellos antiguos raros?',
  'No le gusta fotografiar a estos animales salvajes en el bosque.',
  'Estudiar este tema complejo exige mucho tiempo libre.',
  'Escuchar este álbum clásico relaja mi mente estresada.',
  '¿Alguien terminó de traducir ese contrato legal complejo?',
  '¿Odias hacer cola en esas largas filas del aeropuerto?',
  'Mencionó vender esa casa familiar vieja.',
  'Visitar esta conferencia anual es una gran idea para nuestro equipo.',
  '¿Nuestro director sugirió organizar una subasta benéfica el mes que viene?',
  'Agradecemos recibir comentarios sinceros de nuestros clientes fieles.',
  'Mencionó asistir a esa conferencia científica internacional.',
  'Estudiar estas piezas antiguas nos ayuda a entender culturas viejas.',
  'Piensan mudarse a un país cálido y soleado en el futuro.',
  'Hablar con un abogado experimentado calmó al cliente preocupado.',
  'A nadie le gusta esperar mucho rato con frío y lluvia.',
  'Cada mañana correr por el parque le da energía positiva.',
  '¿Nuestro técnico terminó de arreglar ese mecanismo viejo complejo?',
  'Siempre evitamos usar productos químicos dañinos en nuestros artículos.',
  'Hablar de este contrato internacional exige plena atención.',
  'Alguien mencionó reservar un piso acogedor en el centro.',
  'No les disgusta trabajar cada día en este estudio abierto y ruidoso.',
  '¿Nuestro equipo sugirió comprar muebles modernos para la oficina nueva?',
  'Este proyecto incluye visitar esa gran planta industrial.',
  'Pasear por la orilla pintoresca de este río es muy agradable.',
  'Nadie sugirió cambiar ese horario estricto a largo plazo.',
  'Odio gastar dinero en recuerdos inútiles y caros.',
  'Su trabajo principal es enseñar cada día a jóvenes alumnos con talento.',
  '¿Piensas visitar ese castillo bonito y viejo en la montaña?',
];
