/** Lesson 23 — pasiva y modales pasivos */
export default [
  'Esta comida fresca es cocinada por un chef cada noche.',
  '¿Mi ordenador viejo suele ser reparado por tu hermano?',
  'Esas cartas importantes no las envían nuestras secretarias a tiempo.',
  '¿Su libro nuevo lo leen muchas personas en esta ciudad?',
  'Nuestras facturas no las pagan ellos a fin de mes.',
  '¿Esta oficina acogedora la limpian ellos cada mañana?',
  'Esas normas nuevas no las comenta a menudo vuestra dirección.',
  '¿Mi equipaje lo revisa seguridad en el aeropuerto?',
  'Estas flores bonitas no las riega el jardinero tres veces por semana.',
  '¿Ese ejercicio difícil siempre lo explica nuestro profesor?',
  'Esta cena rica la suele hacer mi madre los domingos.',
  'Tus datos personales siempre los protege este sistema fiable.',
  '¿Está cerrada esa puerta? No; está abierta a todos los empleados.',
  'Nuestros informes diarios los redactan ellos en inglés.',
  '¿Ese puente viejo lo visitan muchos turistas en verano?',
  'Esas verduras frescas no las trae nadie de una tienda local.',
  'Esta leyenda vieja la cuentan ellos cada invierno.',
  'Ese vaso vacío lo llena ella de agua fría.',
  '¿Nos invitas a menudo a esas reuniones de trabajo?',
  'La nueva contraseña la cambia alguien en la oficina de vez en cuando.',
  'La carta fue escrita ayer.',
  'La ventana fue rota por un balón.',
  '¿La película fue dirigida por un cineasta famoso?',
  'El pastel fue comido por los niños.',
  'La carta no fue enviada esta mañana.',
  'La carretera fue arreglada el año pasado.',
  '¿La casa fue construida en 1985?',
  'Las fotos fueron hechas por un profesional.',
  'Los premios fueron entregados a los ganadores.',
  'El cuento fue contado por un anciano.',
  '¿Hay que terminar el informe hoy?',
  'Esta regla se puede aprender fácilmente.',
  'El problema debería resolverse rápido.',
  'Este documento debe ser firmado por el gerente.',
  'Estos archivos no se pueden borrar ahora.',
  'Están arreglando la carretera.',
  '¿Están construyendo el puente nuevo?',
  'Están revisando los documentos.',
  'Están atendiendo a los pacientes.',
  'Están limpiando la habitación ahora.',
  'Ese ordenador moderno lo uso yo para trabajar todos los días.',
  'Esta bicicleta vieja no la arregla él en el garaje.',
  'Nos invitan a cada fiesta en esta casa.',
  '¿Ese vídeo interesante lo ves a menudo los fines de semana?',
  'Nuestro plan diario siempre lo comenta ella con los compañeros.',
  'Esas fotos viejas siempre las guardan ellos en esa caja pequeña.',
  'Tu correo nuevo lo trae ese cartero joven cada mañana.',
  'Esa contraseña difícil se me olvida muy a menudo.',
  'Nuestras ideas nuevas siempre las apoyas tú en cada reunión.',
  'Esa botella vacía la tira alguien en un contenedor especial.',
];
