import type { DayPack } from './gustav_echo_full_day_batch_common';
import { runFullDayBatch } from './gustav_echo_full_day_batch_common';

const DAY_PACKS: DayPack[] = [
  {
    dayIndex: 32,
    fields: [
      { fieldPath: 'topic', fieldKind: 'day_topic', frenchText: "Dire ce qui t'a plu ou non" },
      { fieldPath: 'outcome', fieldKind: 'day_outcome', frenchText: "Tu pourras dire en anglais si la nourriture t'a plu ou non, de façon directe et claire." },
      { fieldPath: 'intro[0].title', fieldKind: 'intro_title', frenchText: 'Comment dire que quelque chose est délicieux' },
      { fieldPath: 'intro[0].body', fieldKind: 'intro_body', frenchText: 'Pour dire que la nourriture est bonne, utilise le mot delicious. Avant le nom du plat, mets This ou The.' },
      { fieldPath: 'intro[0].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: "C'est délicieux." },
      { fieldPath: 'intro[0].examples[1].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Le gâteau est très bon.' },
      { fieldPath: 'intro[1].title', fieldKind: 'intro_title', frenchText: "Comment dire que quelque chose ne t'a pas plu" },
      { fieldPath: 'intro[1].body', fieldKind: 'intro_body', frenchText: "Pour décrire un défaut, ajoute too, « trop », avant l'adjectif. Par exemple : too salty, trop salé." },
      { fieldPath: 'intro[1].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: 'La soupe était trop salée.' },
      { fieldPath: 'intro[1].examples[1].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Le café est trop chaud.' },
      { fieldPath: 'intro[2].title', fieldKind: 'intro_title', frenchText: 'Une phrase, et on te comprendra' },
      { fieldPath: 'intro[2].body', fieldKind: 'intro_body', frenchText: "Il n'est pas nécessaire d'expliquer beaucoup. Une phrase courte avec le bon mot dit déjà au serveur tout ce qu'il faut." },
      { fieldPath: 'intro[2].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: "C'est délicieux." },
      { fieldPath: 'intro[2].examples[1].gloss', fieldKind: 'intro_example_gloss', frenchText: 'La soupe était trop salée.' },
      { fieldPath: 'phrases.echo_d32_p1.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Un seul mot, et tout est clair' },
      { fieldPath: 'phrases.echo_d32_p1.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'This is + mot sert à dire comment est quelque chose maintenant.' },
      { fieldPath: 'phrases.echo_d32_p1.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Delicious est le mot le plus approprié pour dire « délicieux » ou « très bon » dans un café.' },
      { fieldPath: 'phrases.echo_d32_p1.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « It delicious » : le mot is est obligatoire.' },
      { fieldPath: 'phrases.echo_d32_p2.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Comment se plaindre poliment' },
      { fieldPath: 'phrases.echo_d32_p2.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: "Too + adjectif signifie « trop ». Cela indique un problème sans être impoli." },
      { fieldPath: 'phrases.echo_d32_p2.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: "Was est au passé : tu as déjà mangé la soupe, mais tu donnes maintenant ton avis." },
      { fieldPath: 'phrases.echo_d32_p2.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: "Ne dis pas « The soup is too salty » pour quelque chose que tu as déjà mangé : utilise was." },
      { fieldPath: 'phrases.echo_d32_p3.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Un compliment simple sans mots inutiles' },
      { fieldPath: 'phrases.echo_d32_p3.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Very + adjectif renforce le sens : good devient very good, très bon.' },
      { fieldPath: 'phrases.echo_d32_p3.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Good est un compliment neutre et universel que tout le monde comprend.' },
      { fieldPath: 'phrases.echo_d32_p3.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: "Ne dis pas « The coffee very good » : n'oublie pas le mot is." },
      { fieldPath: 'phrases.echo_d32_p4.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Faire un compliment sur un produit précis' },
      { fieldPath: 'phrases.echo_d32_p4.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'This + nom + is + adjectif sert à parler de quelque chose de précis et proche de toi.' },
      { fieldPath: 'phrases.echo_d32_p4.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: "Fresh, « frais », est un mot courant dans un café. Le propriétaire aime l'entendre." },
      { fieldPath: 'phrases.echo_d32_p4.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne confonds pas this, une chose proche, et these, plusieurs choses proches.' },
      { fieldPath: 'phrases.echo_d32_p5.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Parler de la boisson maintenant' },
      { fieldPath: 'phrases.echo_d32_p5.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Choisis is si tu parles maintenant, ou was si tu as déjà fini.' },
      { fieldPath: 'phrases.echo_d32_p5.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Sweet, « sucré », est un mot clé. Le serveur comprend vite le problème.' },
      { fieldPath: 'phrases.echo_d32_p5.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: "Ne dis pas « The tea too sweet » : n'oublie pas is." },
      { fieldPath: 'phrases.echo_d32_p6.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Un compliment doux se comprend aussi' },
      { fieldPath: 'phrases.echo_d32_p6.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Not bad signifie littéralement « pas mauvais ». En anglais, c’est une approbation douce.' },
      { fieldPath: 'phrases.echo_d32_p6.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Parfois, tu ne veux pas faire un grand compliment : not bad est doux et honnête.' },
      { fieldPath: 'phrases.echo_d32_p6.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: "Ne confonds pas not bad, « c'est correct », et bad, « c'est mauvais ». La différence est dans not." },
      { fieldPath: 'vocabulary.delicious.translation', fieldKind: 'vocabulary_translation', frenchText: 'délicieux, très bon' },
      { fieldPath: 'vocabulary.salty.translation', fieldKind: 'vocabulary_translation', frenchText: 'salé' },
      { fieldPath: 'vocabulary.fresh.translation', fieldKind: 'vocabulary_translation', frenchText: 'frais' },
      { fieldPath: 'vocabulary.sweet.translation', fieldKind: 'vocabulary_translation', frenchText: 'sucré' },
      { fieldPath: 'vocabulary.too.translation', fieldKind: 'vocabulary_translation', frenchText: 'trop' },
      { fieldPath: 'vocabulary.bad.translation', fieldKind: 'vocabulary_translation', frenchText: 'mauvais' },
    ],
  },
  {
    dayIndex: 33,
    fields: [
      { fieldPath: 'topic', fieldKind: 'day_topic', frenchText: 'Réserver une table' },
      { fieldPath: 'outcome', fieldKind: 'day_outcome', frenchText: 'Tu peux réserver une table et demander les détails en anglais.' },
      { fieldPath: 'intro[0].title', fieldKind: 'intro_title', frenchText: 'Comment demander une table' },
      { fieldPath: 'intro[0].body', fieldKind: 'intro_body', frenchText: "Quand tu veux demander quelque chose poliment en anglais, utilise would like. C'est plus doux que I want. Dis : I would like to book a table, et on te comprendra dans n'importe quel café ou restaurant." },
      { fieldPath: 'intro[0].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Je voudrais réserver une table pour deux.' },
      { fieldPath: 'intro[0].examples[1].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Nous voudrions une table près de la fenêtre.' },
      { fieldPath: 'intro[1].title', fieldKind: 'intro_title', frenchText: 'Comment demander les détails' },
      { fieldPath: 'intro[1].body', fieldKind: 'intro_body', frenchText: "Pour demander l'heure ou le lieu, ajoute des mots comme after dinner, at seven, for four people. Tu peux aussi demander : Do you have a table?" },
      { fieldPath: 'intro[1].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Avez-vous une table pour ce soir ?' },
      { fieldPath: 'intro[1].examples[1].gloss', fieldKind: 'intro_example_gloss', frenchText: "J'ai besoin d'une table pour quatre personnes." },
      { fieldPath: 'intro[2].title', fieldKind: 'intro_title', frenchText: 'Un mot, une grande différence' },
      { fieldPath: 'intro[2].body', fieldKind: 'intro_body', frenchText: 'Book en anglais ne signifie pas seulement livre : cela veut aussi dire réserver. Book a table : réserver une table. Book a room : réserver une chambre. Retiens ce mot, il sert dans beaucoup de situations.' },
      { fieldPath: 'phrases.echo_d33_p1.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demande polie' },
      { fieldPath: 'phrases.echo_d33_p1.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Would like est la façon polie de dire « je veux ». Ensuite viennent to et l’action.' },
      { fieldPath: 'phrases.echo_d33_p1.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Cette formule marche au téléphone, au comptoir et dans un restaurant.' },
      { fieldPath: 'phrases.echo_d33_p1.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « I want to book a table » si tu veux sonner poli : would like est mieux.' },
      { fieldPath: 'phrases.echo_d33_p2.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander la disponibilité' },
      { fieldPath: 'phrases.echo_d33_p2.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Pour demander « avez-vous ? », commence par Do you have.' },
      { fieldPath: 'phrases.echo_d33_p2.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'For two précise le nombre de personnes. La réponse sera rapide et claire.' },
      { fieldPath: 'phrases.echo_d33_p2.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « You have a table? » dans une phrase complète : ajoute Do au début.' },
      { fieldPath: 'phrases.echo_d33_p3.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Quand vous êtes plusieurs' },
      { fieldPath: 'phrases.echo_d33_p3.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'We would like sert à demander poliment quelque chose pour tout le groupe.' },
      { fieldPath: 'phrases.echo_d33_p3.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Tonight place la réservation dans le temps : ce soir, pas demain.' },
      { fieldPath: 'phrases.echo_d33_p3.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « We likes » : avec we, utilise like, et dans cette formule would like.' },
      { fieldPath: 'phrases.echo_d33_p4.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: "Préciser l'endroit" },
      { fieldPath: 'phrases.echo_d33_p4.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Can I + verbe sert à demander la permission ou la possibilité de faire quelque chose.' },
      { fieldPath: 'phrases.echo_d33_p4.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Outside précise que tu veux une table dehors, par exemple sur la terrasse.' },
      { fieldPath: 'phrases.echo_d33_p4.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « Can I to reserve » : après can, le verbe vient sans to.' },
      { fieldPath: 'phrases.echo_d33_p5.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: "Horaire d'ouverture" },
      { fieldPath: 'phrases.echo_d33_p5.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Opens signifie « ouvre ». Avec the restaurant, on ajoute -s : opens.' },
      { fieldPath: 'phrases.echo_d33_p5.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'At seven donne l’heure exacte. C’est une structure simple pour parler des horaires.' },
      { fieldPath: 'phrases.echo_d33_p5.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « The restaurant open at seven » : il faut opens avec -s.' },
      { fieldPath: 'phrases.echo_d33_p6.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Combien de personnes' },
      { fieldPath: 'phrases.echo_d33_p6.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Need + nom sert à dire ce dont vous avez besoin. For four people précise la taille de la table.' },
      { fieldPath: 'phrases.echo_d33_p6.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Cette phrase est directe, mais reste normale et claire dans un restaurant.' },
      { fieldPath: 'phrases.echo_d33_p6.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « four peoples » : people est déjà pluriel.' },
      { fieldPath: 'vocabulary.book.translation', fieldKind: 'vocabulary_translation', frenchText: 'réserver' },
      { fieldPath: 'vocabulary.table.translation', fieldKind: 'vocabulary_translation', frenchText: 'table' },
      { fieldPath: 'vocabulary.reserve.translation', fieldKind: 'vocabulary_translation', frenchText: 'réserver' },
      { fieldPath: 'vocabulary.tonight.translation', fieldKind: 'vocabulary_translation', frenchText: 'ce soir' },
      { fieldPath: 'vocabulary.outside.translation', fieldKind: 'vocabulary_translation', frenchText: "dehors, à l'extérieur" },
      { fieldPath: 'vocabulary.opens.translation', fieldKind: 'vocabulary_translation', frenchText: 'ouvre' },
    ],
  },
  {
    dayIndex: 34,
    fields: [
      { fieldPath: 'topic', fieldKind: 'day_topic', frenchText: 'Demander les offres spéciales' },
      { fieldPath: 'outcome', fieldKind: 'day_outcome', frenchText: 'Tu peux demander les réductions, les menus du jour et les offres dans un café.' },
      { fieldPath: 'intro[0].title', fieldKind: 'intro_title', frenchText: 'Comment demander les offres spéciales' },
      { fieldPath: 'intro[0].body', fieldKind: 'intro_body', frenchText: "Quand tu es dans un café, deux questions simples suffisent souvent : Do you have...? et What do you have...? Elles permettent de demander ce qui est proposé aujourd'hui." },
      { fieldPath: 'intro[0].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: "Avez-vous un menu déjeuner spécial aujourd'hui ?" },
      { fieldPath: 'intro[0].examples[1].gloss', fieldKind: 'intro_example_gloss', frenchText: "Qu'avez-vous en offre spéciale ?" },
      { fieldPath: 'intro[1].title', fieldKind: 'intro_title', frenchText: 'Le mot special est la clé' },
      { fieldPath: 'intro[1].body', fieldKind: 'intro_body', frenchText: "Special peut parler d'un plat du jour, d'une offre ou d'un prix particulier. Dans un café, c'est un mot très utile." },
      { fieldPath: 'intro[1].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: "Avez-vous une offre spéciale aujourd'hui ?" },
      { fieldPath: 'intro[1].examples[1].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Nous avons une offre soupe et sandwich.' },
      { fieldPath: 'intro[2].title', fieldKind: 'intro_title', frenchText: 'Comment être poli' },
      { fieldPath: 'intro[2].body', fieldKind: 'intro_body', frenchText: "La question Do you have...? est déjà polie et naturelle. Ajoute here ou today si tu veux préciser le lieu ou le jour." },
      { fieldPath: 'intro[2].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Avez-vous une réduction pour les étudiants ?' },
      { fieldPath: 'intro[2].examples[1].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Avez-vous le Wi-Fi gratuit ici ?' },
      { fieldPath: 'phrases.echo_d34_p1.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander le menu du jour' },
      { fieldPath: 'phrases.echo_d34_p1.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'La question commence par Do you have, puis tu ajoutes ce que tu cherches.' },
      { fieldPath: 'phrases.echo_d34_p1.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Lunch special signifie une offre ou un plat spécial pour le déjeuner.' },
      { fieldPath: 'phrases.echo_d34_p1.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « Have you lunch special » : utilise Do you have.' },
      { fieldPath: 'phrases.echo_d34_p2.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander ce qui est en offre spéciale' },
      { fieldPath: 'phrases.echo_d34_p2.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'What do you have...? sert à demander une liste ou une option disponible.' },
      { fieldPath: 'phrases.echo_d34_p2.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'On special signifie que quelque chose est proposé avec une offre spéciale.' },
      { fieldPath: 'phrases.echo_d34_p2.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « What you have » : dans une question, il faut do.' },
      { fieldPath: 'phrases.echo_d34_p3.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Le mot any dans une question' },
      { fieldPath: 'phrases.echo_d34_p3.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Any dans une question signifie « un peu, quelque chose, n’importe lequel ». Il rend la question naturelle.' },
      { fieldPath: 'phrases.echo_d34_p3.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Free coffee signifie café gratuit. Today précise que tu demandes pour aujourd’hui.' },
      { fieldPath: 'phrases.echo_d34_p3.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « Do you have some free coffee » dans cette question : any est plus naturel.' },
      { fieldPath: 'phrases.echo_d34_p4.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Does au lieu de Do : quand et pourquoi' },
      { fieldPath: 'phrases.echo_d34_p4.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Quand tu poses une question sur un lieu au singulier, utilise Does, pas Do.' },
      { fieldPath: 'phrases.echo_d34_p4.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'This cafe est un seul lieu, donc on commence la question par Does.' },
      { fieldPath: 'phrases.echo_d34_p4.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « Do this cafe have » : avec this cafe, il faut Does.' },
      { fieldPath: 'phrases.echo_d34_p5.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander une option moins chère' },
      { fieldPath: 'phrases.echo_d34_p5.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Cheaper signifie « moins cher ». On ajoute -er à un adjectif court pour comparer.' },
      { fieldPath: 'phrases.echo_d34_p5.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Cette phrase permet de demander un prix plus bas sans paraître impoli.' },
      { fieldPath: 'phrases.echo_d34_p5.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas more cheap : pour ce mot, dis cheaper.' },
      { fieldPath: 'phrases.echo_d34_p6.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander le plat du jour à partir du menu' },
      { fieldPath: 'phrases.echo_d34_p6.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Your menu est une chose au singulier, donc la question commence par Does your menu have.' },
      { fieldPath: 'phrases.echo_d34_p6.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Daily special désigne souvent le plat du jour ou une offre qui change chaque jour.' },
      { fieldPath: 'phrases.echo_d34_p6.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « Do your menu have » : menu est singulier, donc il faut Does.' },
      { fieldPath: 'vocabulary.special.translation', fieldKind: 'vocabulary_translation', frenchText: 'offre du jour, plat spécial' },
      { fieldPath: 'vocabulary.discount.translation', fieldKind: 'vocabulary_translation', frenchText: 'réduction' },
      { fieldPath: 'vocabulary.option.translation', fieldKind: 'vocabulary_translation', frenchText: 'option' },
      { fieldPath: 'vocabulary.cheaper.translation', fieldKind: 'vocabulary_translation', frenchText: 'moins cher' },
      { fieldPath: 'vocabulary.daily.translation', fieldKind: 'vocabulary_translation', frenchText: 'quotidien, du jour' },
      { fieldPath: 'vocabulary.menu.translation', fieldKind: 'vocabulary_translation', frenchText: 'menu' },
    ],
  },
];

runFullDayBatch({
  dayPacks: DAY_PACKS,
  generatedBy: 'gustav_personal_plan_echo_days032_034_french_full_day_text_packets',
  scriptUsage: 'Usage: npx tsx scripts/gustav_personal_plan_echo_days032_034_french_full_day_text_packets.ts --run <run-dir>',
  batchTitle: 'GUSTAV Echo days 032-034 French full-day text packets',
  batchSchemaVersion: 'gustav-personal-plan-echo-days032-034-french-full-day-text-packets-v0',
  batchAuditBaseName: 'personal_plan_echo_days032_034_french_full_day_text_packets',
}).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
