export const SOURCE_EVIDENCE = [
  {
    id: 'tv5monde_grammar_index',
    label: 'TV5MONDE Apprendre - grammaire',
    url: 'https://apprendre.tv5monde.com/fr/aides/grammaire?page=2',
    use: ['prepositions', 'articles', 'learner-facing grammar progression'],
  },
  {
    id: 'lepointdufle_articles_contractes',
    label: 'Le Point du FLE - articles contractes',
    url: 'https://www.lepointdufle.net/ressources_fle/articles_contractes.htm',
    use: ['a/de contractions', 'article contraction contrast'],
  },
  {
    id: 'larousse_etre_conjugation',
    label: 'Larousse - conjugaison etre',
    url: 'https://www.larousse.fr/conjugaison/francais/%C3%AAtre/4440',
    use: ['high-frequency irregular conjugation reference'],
  },
  {
    id: 'larousse_faire_conjugation',
    label: 'Larousse - conjugaison faire',
    url: 'https://www.larousse.com/conjugaison/francais/faire/4599',
    use: ['high-frequency irregular conjugation reference'],
  },
  {
    id: 'lerobert_etre_conjugation',
    label: 'Le Robert - conjugaison etre',
    url: 'https://dictionnaire.lerobert.com/conjugaison/etre',
    use: ['cross-check present, imperfect, compound tense forms'],
  },
  {
    id: 'bescherelle_conjugation_reference',
    label: 'Bescherelle - conjugaison reference',
    url: 'https://conjugaison.bescherelle.com/',
    use: ['general conjugation-table contract and tense coverage'],
  },
  {
    id: 'bescherelle_etre',
    label: 'Bescherelle - etre',
    url: 'https://conjugaison.bescherelle.com/verbes/etre',
    use: ['etre forms and compound tense verification'],
  },
  {
    id: 'bescherelle_avoir',
    label: 'Bescherelle - avoir',
    url: 'https://conjugaison.bescherelle.com/verbes/avoir',
    use: ['avoir forms and auxiliary verification'],
  },
];

export const APP_LEVEL_BY_LESSON = Object.fromEntries(
  Array.from({ length: 32 }, (_, index) => {
    const lessonId = index + 1;
    const level = lessonId <= 8 ? 'A1' : lessonId <= 18 ? 'A2' : lessonId <= 28 ? 'B1' : 'B2';
    return [lessonId, level];
  }),
);

export const PREPOSITION_ROWS = [
  ['au', 'direction', 'Je vais ___ marche.', ['au', 'a le', 'a la', 'aux'], 'a + le devient au devant un nom masculin singulier.', 'a + le становится au перед существительным мужского рода.', 'a + le стає au перед іменником чоловічого роду.', ['lepointdufle_articles_contractes']],
  ['au', 'other', 'Elle parle ___ professeur.', ['au', 'a le', 'chez', 'de'], 'Parler a quelqu un utilise a; a + le se contracte en au.', 'Parler a quelqu un требует a; a + le сжимается в au.', 'Parler a quelqu un вимагає a; a + le стискається в au.', ['lepointdufle_articles_contractes']],
  ['aux', 'direction', 'Nous pensons ___ vacances.', ['aux', 'a les', 'des', 'dans'], 'a + les devient aux; on ne garde pas a les.', 'a + les становится aux; форма a les здесь неверна.', 'a + les стає aux; форма a les тут неправильна.', ['lepointdufle_articles_contractes']],
  ['du', 'other', 'Il revient ___ bureau.', ['du', 'de le', 'au', 'des'], 'de + le devient du, surtout avec origine ou provenance.', 'de + le становится du, когда говорим об исходной точке.', 'de + le стає du, коли говоримо про вихідну точку.', ['lepointdufle_articles_contractes']],
  ['des', 'other', 'Je viens ___ Etats-Unis.', ['des', 'de les', 'aux', 'en'], 'de + les devient des devant un pluriel defini.', 'de + les становится des перед определенным множественным числом.', 'de + les стає des перед означеним множинним числом.', ['lepointdufle_articles_contractes']],
  ['en', 'place', 'Elle habite ___ France.', ['en', 'au', 'a', 'dans'], 'On emploie en avec beaucoup de pays feminins.', 'С названиями многих стран женского рода используется en.', 'З назвами багатьох країн жіночого роду вживається en.', ['tv5monde_grammar_index']],
  ['au', 'direction', 'Nous allons ___ Portugal.', ['au', 'en', 'a', 'aux'], 'On emploie au avec beaucoup de pays masculins.', 'С названиями многих стран мужского рода используется au.', 'З назвами багатьох країн чоловічого роду вживається au.', ['tv5monde_grammar_index']],
  ['aux', 'direction', 'Ils vont ___ Pays-Bas.', ['aux', 'au', 'en', 'a'], 'On emploie aux avec les noms de pays au pluriel.', 'С названиями стран во множественном числе используется aux.', 'З назвами країн у множині вживається aux.', ['tv5monde_grammar_index']],
  ['sur', 'place', 'Le livre est ___ la table.', ['sur', 'dans', 'sous', 'a'], 'Sur marque une position au-dessus avec contact.', 'Sur показывает положение сверху с контактом.', 'Sur показує положення зверху з контактом.', ['tv5monde_grammar_index']],
  ['sous', 'place', 'Le chat dort ___ le canape.', ['sous', 'sur', 'devant', 'chez'], 'Sous marque une position plus basse ou cachee.', 'Sous показывает положение ниже или под предметом.', 'Sous показує положення нижче або під предметом.', ['tv5monde_grammar_index']],
  ['devant', 'place', 'Attends-moi ___ la gare.', ['devant', 'dans', 'en', 'pour'], 'Devant place quelqu un ou quelque chose face a un lieu.', 'Devant ставит предмет или человека перед местом.', 'Devant ставить предмет або людину перед місцем.', ['tv5monde_grammar_index']],
  ['pres de', 'place', 'Le cafe est ___ la bibliotheque.', ['pres de', 'pour', 'depuis', 'chez'], 'Pres de exprime la proximite avec un point de repere.', 'Pres de выражает близость к ориентиру.', 'Pres de виражає близькість до орієнтира.', ['tv5monde_grammar_index']],
  ['a', 'time', 'Je travaille ___ huit heures.', ['a', 'en', 'depuis', 'pendant'], 'A introduit souvent une heure precise.', 'A часто вводит точное время.', 'A часто вводить точний час.', ['tv5monde_grammar_index']],
  ['depuis', 'time', 'Il est ici ___ lundi.', ['depuis', 'pendant', 'pour', 'a'], 'Depuis indique le point de depart d une duree qui continue.', 'Depuis показывает начало длительности, которая продолжается.', 'Depuis показує початок тривалості, що триває.', ['tv5monde_grammar_index']],
  ['pour', 'time', 'Je pars ___ deux jours.', ['pour', 'depuis', 'dans', 'sur'], 'Pour peut annoncer une duree prevue.', 'Pour может обозначать запланированную длительность.', 'Pour може позначати заплановану тривалість.', ['tv5monde_grammar_index']],
  ['dans', 'place', 'Elle lit ___ le train.', ['dans', 'a', 'sur', 'chez'], 'Dans indique l interieur ou le cadre physique.', 'Dans показывает нахождение внутри пространства.', 'Dans показує перебування всередині простору.', ['tv5monde_grammar_index']],
  ['en', 'other', 'Je voyage ___ train.', ['en', 'a', 'par', 'sur'], 'En sert souvent avec un moyen de transport ferme ou general.', 'En часто используется со способом транспорта.', 'En часто вживається зі способом транспорту.', ['tv5monde_grammar_index']],
  ['a', 'other', 'Elle va ___ pied.', ['a', 'en', 'par', 'dans'], 'A pied est une expression fixe.', 'A pied - устойчивое выражение.', 'A pied - сталий вислів.', ['tv5monde_grammar_index']],
  ['par', 'direction', 'Je passe ___ la pharmacie.', ['par', 'pour', 'chez', 'a'], 'Par marque le passage par un lieu intermediaire.', 'Par показывает прохождение через промежуточное место.', 'Par показує проходження через проміжне місце.', ['tv5monde_grammar_index']],
  ['pour', 'other', 'C est ___ toi.', ['pour', 'par', 'chez', 'sans'], 'Pour introduit le destinataire ou le benefice.', 'Pour вводит адресата или пользу.', 'Pour вводить адресата або користь.', ['tv5monde_grammar_index']],
  ['chez', 'place', 'Je viens ___ Marie.', ['chez', 'a', 'dans', 'sur'], 'Chez designe la maison, le lieu ou l univers d une personne.', 'Chez указывает дом, место или сферу человека.', 'Chez позначає дім, місце або сферу людини.', ['tv5monde_grammar_index']],
  ['avec', 'other', 'Je parle ___ mon frere.', ['avec', 'sans', 'pour', 'par'], 'Avec ajoute l idee d accompagnement ou de relation.', 'Avec добавляет значение совместности или связи.', 'Avec додає значення спільності або зв язку.', ['tv5monde_grammar_index']],
  ['sans', 'other', 'Il travaille ___ bruit.', ['sans', 'avec', 'pour', 'de'], 'Sans exprime l absence de quelque chose.', 'Sans выражает отсутствие чего-то.', 'Sans виражає відсутність чогось.', ['tv5monde_grammar_index']],
  ['apres', 'time', 'Nous sortons ___ le diner.', ['apres', 'avant', 'depuis', 'a'], 'Apres place l action plus tard dans la sequence.', 'Apres ставит действие позже в последовательности.', 'Apres ставить дію пізніше в послідовності.', ['tv5monde_grammar_index']],
  ['avant', 'time', 'J arrive ___ le cours.', ['avant', 'apres', 'depuis', 'pendant'], 'Avant place l action plus tot dans la sequence.', 'Avant ставит действие раньше в последовательности.', 'Avant ставить дію раніше в послідовності.', ['tv5monde_grammar_index']],
  ['jusqu a', 'direction', 'Va ___ la porte.', ['jusqu a', 'depuis', 'chez', 'sans'], 'Jusqu a marque la limite ou le point d arrivee.', 'Jusqu a показывает предел или точку прибытия.', 'Jusqu a показує межу або пункт прибуття.', ['tv5monde_grammar_index']],
  ['a', 'place', 'Il habite ___ Paris.', ['a', 'en', 'au', 'dans'], 'A s emploie avec une ville.', 'С городами обычно используется a.', 'З містами зазвичай уживається a.', ['tv5monde_grammar_index']],
  ["d'", 'other', 'Elle vient ___ Italie.', ["d'", 'de', 'du', 'des'], 'De devient d devant une voyelle.', 'De превращается в d перед гласной.', 'De перетворюється на d перед голосною.', ['lepointdufle_articles_contractes']],
  ['pour', 'other', 'Merci ___ ton aide.', ['pour', 'a', 'de', 'par'], 'Merci pour introduit souvent la raison du remerciement.', 'Merci pour вводит причину благодарности.', 'Merci pour вводить причину подяки.', ['tv5monde_grammar_index']],
  ['pour', 'other', 'C est difficile ___ moi.', ['pour', 'a', 'de', 'chez'], 'Pour moi marque un point de vue personnel.', 'Pour moi обозначает личную точку зрения.', 'Pour moi позначає особисту точку зору.', ['tv5monde_grammar_index']],
  ['a', 'other', 'Je m interesse ___ la musique.', ['a', 'de', 'pour', 'avec'], 'S interesser se construit avec a.', 'S interesser требует a.', 'S interesser вимагає a.', ['tv5monde_grammar_index']],
  ['de', 'other', 'Il a besoin ___ repos.', ['de', 'a', 'pour', 'chez'], 'Avoir besoin se construit avec de.', 'Avoir besoin требует de.', 'Avoir besoin вимагає de.', ['tv5monde_grammar_index']],
];

export const CONJUGATION_VERBS = [
  ['etre', 'etre', [['present_je', 'je suis', 'Je ___ pret.', ['suis', 'es', 'est', 'sommes']], ['present_nous', 'nous sommes', 'Nous ___ a Paris.', ['sommes', 'etes', 'sont', 'suis']], ['passe_compose_il', 'il a ete', 'Il ___ malade hier.', ['a ete', 'est ete', 'a est', 'avait est']], ['imparfait_elle', 'elle etait', 'Elle ___ calme.', ['etait', 'est', 'ete', 'sera']]], ['larousse_etre_conjugation', 'lerobert_etre_conjugation', 'bescherelle_etre']],
  ['avoir', 'avoir', [['present_je', "j'ai", "J'___ faim.", ["ai", "as", "a", "avons"]], ['present_vous', 'vous avez', 'Vous ___ raison.', ['avez', 'avons', 'ont', 'as']], ['passe_compose_il', 'il a eu', 'Il ___ peur.', ['a eu', 'est eu', 'a eut', 'avait eu']], ['imparfait_nous', 'nous avions', 'Nous ___ le temps.', ['avions', 'avons', 'avez', 'ont']]], ['bescherelle_avoir']],
  ['aller', 'aller', [['present_je', 'je vais', 'Je ___ au travail.', ['vais', 'vas', 'va', 'allons']], ['present_nous', 'nous allons', 'Nous ___ au cinema.', ['allons', 'allez', 'vont', 'vais']], ['passe_compose_il', 'il est alle', 'Il ___ a Lyon.', ['est alle', 'a alle', 'est allait', 'a va']], ['imparfait_elle', 'elle allait', 'Elle ___ souvent au parc.', ['allait', 'va', 'ira', 'alle']]], ['bescherelle_conjugation_reference']],
  ['faire', 'faire', [['present_je', 'je fais', 'Je ___ le cafe.', ['fais', 'fait', 'faisons', 'font']], ['present_nous', 'nous faisons', 'Nous ___ attention.', ['faisons', 'faites', 'font', 'fais']], ['passe_compose_il', 'il a fait', 'Il ___ ses devoirs.', ['a fait', 'est fait', 'a fais', 'avait fais']], ['imparfait_vous', 'vous faisiez', 'Vous ___ du sport.', ['faisiez', 'faites', 'ferez', 'fait']]], ['larousse_faire_conjugation', 'bescherelle_conjugation_reference']],
  ['pouvoir', 'pouvoir', [['present_je', 'je peux', 'Je ___ venir.', ['peux', 'peut', 'pouvons', 'pouvez']], ['present_nous', 'nous pouvons', 'Nous ___ aider.', ['pouvons', 'pouvez', 'peuvent', 'peux']], ['passe_compose_il', 'il a pu', 'Il ___ finir.', ['a pu', 'est pu', 'a peut', 'avait peut']], ['imparfait_tu', 'tu pouvais', 'Tu ___ rester.', ['pouvais', 'peux', 'pourras', 'pu']]], ['bescherelle_conjugation_reference']],
  ['vouloir', 'vouloir', [['present_je', 'je veux', 'Je ___ partir.', ['veux', 'veut', 'voulons', 'voulez']], ['present_nous', 'nous voulons', 'Nous ___ comprendre.', ['voulons', 'voulez', 'veulent', 'veux']], ['passe_compose_il', 'il a voulu', 'Il ___ essayer.', ['a voulu', 'est voulu', 'a veut', 'avait veut']], ['imparfait_elle', 'elle voulait', 'Elle ___ apprendre.', ['voulait', 'veut', 'voudra', 'voulu']]], ['bescherelle_conjugation_reference']],
  ['prendre', 'prendre', [['present_je', 'je prends', 'Je ___ le metro.', ['prends', 'prend', 'prenons', 'prenez']], ['present_nous', 'nous prenons', 'Nous ___ un taxi.', ['prenons', 'prenez', 'prennent', 'prends']], ['passe_compose_il', 'il a pris', 'Il ___ le train.', ['a pris', 'est pris', 'a prend', 'avait prend']], ['imparfait_vous', 'vous preniez', 'Vous ___ des notes.', ['preniez', 'prenez', 'prendrez', 'pris']]], ['bescherelle_conjugation_reference']],
  ['venir', 'venir', [['present_je', 'je viens', 'Je ___ avec toi.', ['viens', 'vient', 'venons', 'venez']], ['present_nous', 'nous venons', 'Nous ___ demain.', ['venons', 'venez', 'viennent', 'viens']], ['passe_compose_il', 'il est venu', 'Il ___ tard.', ['est venu', 'a venu', 'est vient', 'avait venu']], ['imparfait_elle', 'elle venait', 'Elle ___ souvent.', ['venait', 'vient', 'viendra', 'venu']]], ['bescherelle_conjugation_reference']],
  ['voir', 'voir', [['present_je', 'je vois', 'Je ___ la mer.', ['vois', 'voit', 'voyons', 'voyez']], ['present_nous', 'nous voyons', 'Nous ___ le panneau.', ['voyons', 'voyez', 'voient', 'vois']], ['passe_compose_il', 'il a vu', 'Il ___ le film.', ['a vu', 'est vu', 'a voit', 'avait voit']], ['imparfait_tu', 'tu voyais', 'Tu ___ mieux.', ['voyais', 'vois', 'verras', 'vu']]], ['bescherelle_conjugation_reference']],
  ['savoir', 'savoir', [['present_je', 'je sais', 'Je ___ la reponse.', ['sais', 'sait', 'savons', 'savez']], ['present_nous', 'nous savons', 'Nous ___ pourquoi.', ['savons', 'savez', 'savent', 'sais']], ['passe_compose_il', 'il a su', 'Il ___ la nouvelle.', ['a su', 'est su', 'a sait', 'avait sait']], ['imparfait_elle', 'elle savait', 'Elle ___ deja.', ['savait', 'sait', 'saura', 'su']]], ['bescherelle_conjugation_reference']],
  ['devoir', 'devoir', [['present_je', 'je dois', 'Je ___ travailler.', ['dois', 'doit', 'devons', 'devez']], ['present_nous', 'nous devons', 'Nous ___ partir.', ['devons', 'devez', 'doivent', 'dois']], ['passe_compose_il', 'il a du', 'Il ___ payer.', ['a du', 'est du', 'a doit', 'avait doit']], ['imparfait_vous', 'vous deviez', 'Vous ___ attendre.', ['deviez', 'devez', 'devrez', 'du']]], ['bescherelle_conjugation_reference']],
  ['dire', 'dire', [['present_je', 'je dis', 'Je ___ la verite.', ['dis', 'dit', 'disons', 'dites']], ['present_vous', 'vous dites', 'Vous ___ bonjour.', ['dites', 'disez', 'disons', 'dis']], ['passe_compose_il', 'il a dit', 'Il ___ non.', ['a dit', 'est dit', 'a dis', 'avait dis']], ['imparfait_elle', 'elle disait', 'Elle ___ toujours ca.', ['disait', 'dit', 'dira', 'dit']]], ['bescherelle_conjugation_reference']],
  ['mettre', 'mettre', [['present_je', 'je mets', 'Je ___ la table.', ['mets', 'met', 'mettons', 'mettez']], ['present_nous', 'nous mettons', 'Nous ___ nos vestes.', ['mettons', 'mettez', 'mettent', 'mets']], ['passe_compose_il', 'il a mis', 'Il ___ son manteau.', ['a mis', 'est mis', 'a met', 'avait met']], ['imparfait_tu', 'tu mettais', 'Tu ___ trop de sel.', ['mettais', 'mets', 'mettras', 'mis']]], ['bescherelle_conjugation_reference']],
  ['partir', 'partir', [['present_je', 'je pars', 'Je ___ demain.', ['pars', 'part', 'partons', 'partez']], ['present_nous', 'nous partons', 'Nous ___ tot.', ['partons', 'partez', 'partent', 'pars']], ['passe_compose_il', 'il est parti', 'Il ___ a midi.', ['est parti', 'a parti', 'est part', 'avait parti']], ['imparfait_elle', 'elle partait', 'Elle ___ seule.', ['partait', 'part', 'partira', 'parti']]], ['bescherelle_conjugation_reference']],
  ['sortir', 'sortir', [['present_je', 'je sors', 'Je ___ ce soir.', ['sors', 'sort', 'sortons', 'sortez']], ['present_nous', 'nous sortons', 'Nous ___ ensemble.', ['sortons', 'sortez', 'sortent', 'sors']], ['passe_compose_il', 'il est sorti', 'Il ___ du bureau.', ['est sorti', 'a sorti', 'est sort', 'avait sorti']], ['imparfait_vous', 'vous sortiez', 'Vous ___ tard.', ['sortiez', 'sortez', 'sortirez', 'sorti']]], ['bescherelle_conjugation_reference']],
  ['finir', 'finir', [['present_je', 'je finis', 'Je ___ le livre.', ['finis', 'finit', 'finissons', 'finissez']], ['present_nous', 'nous finissons', 'Nous ___ demain.', ['finissons', 'finissez', 'finissent', 'finis']], ['passe_compose_il', 'il a fini', 'Il ___ le travail.', ['a fini', 'est fini', 'a finit', 'avait finit']], ['imparfait_elle', 'elle finissait', 'Elle ___ son repas.', ['finissait', 'finit', 'finira', 'fini']]], ['bescherelle_conjugation_reference']],
  ['choisir', 'choisir', [['present_je', 'je choisis', 'Je ___ une option.', ['choisis', 'choisit', 'choisissons', 'choisissez']], ['present_nous', 'nous choisissons', 'Nous ___ la date.', ['choisissons', 'choisissez', 'choisissent', 'choisis']], ['passe_compose_il', 'il a choisi', 'Il ___ ce chemin.', ['a choisi', 'est choisi', 'a choisit', 'avait choisit']], ['imparfait_tu', 'tu choisissais', 'Tu ___ vite.', ['choisissais', 'choisis', 'choisiras', 'choisi']]], ['bescherelle_conjugation_reference']],
  ['vendre', 'vendre', [['present_je', 'je vends', 'Je ___ ma voiture.', ['vends', 'vend', 'vendons', 'vendez']], ['present_nous', 'nous vendons', 'Nous ___ des billets.', ['vendons', 'vendez', 'vendent', 'vends']], ['passe_compose_il', 'il a vendu', 'Il ___ la maison.', ['a vendu', 'est vendu', 'a vend', 'avait vend']], ['imparfait_elle', 'elle vendait', 'Elle ___ des fleurs.', ['vendait', 'vend', 'vendra', 'vendu']]], ['bescherelle_conjugation_reference']],
  ['attendre', 'attendre', [['present_je', 'j attends', "J'___ le bus.", ['attends', 'attend', 'attendons', 'attendez']], ['present_nous', 'nous attendons', 'Nous ___ la reponse.', ['attendons', 'attendez', 'attendent', 'attends']], ['passe_compose_il', 'il a attendu', 'Il ___ longtemps.', ['a attendu', 'est attendu', 'a attend', 'avait attend']], ['imparfait_vous', 'vous attendiez', 'Vous ___ dehors.', ['attendiez', 'attendez', 'attendrez', 'attendu']]], ['bescherelle_conjugation_reference']],
  ['appeler', 'appeler', [['present_je', "j'appelle", "J'___ ma mere.", ["appelle", "appeles", "appelons", "appelez"]], ['present_nous', 'nous appelons', 'Nous ___ le medecin.', ['appelons', 'appelez', 'appellent', 'appelle']], ['passe_compose_il', 'il a appele', 'Il ___ Paul.', ['a appele', 'est appele', 'a appelle', 'avait appelle']], ['imparfait_elle', 'elle appelait', 'Elle ___ souvent.', ['appelait', 'appelle', 'appellera', 'appele']]], ['bescherelle_conjugation_reference']],
  ['manger', 'manger', [['present_je', 'je mange', 'Je ___ ici.', ['mange', 'manges', 'mangeons', 'mangez']], ['present_nous', 'nous mangeons', 'Nous ___ ensemble.', ['mangeons', 'mangez', 'mangent', 'mange']], ['passe_compose_il', 'il a mange', 'Il ___ une pomme.', ['a mange', 'est mange', 'a manges', 'avait manges']], ['imparfait_vous', 'vous mangiez', 'Vous ___ vite.', ['mangiez', 'mangez', 'mangerez', 'mange']]], ['bescherelle_conjugation_reference']],
  ['commencer', 'commencer', [['present_je', 'je commence', 'Je ___ maintenant.', ['commence', 'commences', 'commencons', 'commencez']], ['present_nous', 'nous commencons', 'Nous ___ le cours.', ['commencons', 'commencez', 'commencent', 'commence']], ['passe_compose_il', 'il a commence', 'Il ___ hier.', ['a commence', 'est commence', 'a commences', 'avait commences']], ['imparfait_elle', 'elle commencait', 'Elle ___ a neuf heures.', ['commencait', 'commence', 'commencera', 'commence']]], ['bescherelle_conjugation_reference']],
  ['preferer', 'preferer', [['present_je', 'je prefere', 'Je ___ rester.', ['prefere', 'preferes', 'preferons', 'preferez']], ['present_nous', 'nous preferons', 'Nous ___ partir.', ['preferons', 'preferez', 'preferent', 'prefere']], ['passe_compose_il', 'il a prefere', 'Il ___ attendre.', ['a prefere', 'est prefere', 'a preferes', 'avait preferes']], ['imparfait_tu', 'tu preferais', 'Tu ___ le cafe.', ['preferais', 'prefere', 'prefereras', 'prefere']]], ['bescherelle_conjugation_reference']],
  ['acheter', 'acheter', [['present_je', "j'achete", "J'___ du pain.", ['achete', 'achetes', 'achetons', 'achetez']], ['present_nous', 'nous achetons', 'Nous ___ des fruits.', ['achetons', 'achetez', 'achetent', 'achete']], ['passe_compose_il', 'il a achete', 'Il ___ un billet.', ['a achete', 'est achete', 'a achetes', 'avait achetes']], ['imparfait_elle', 'elle achetait', 'Elle ___ souvent ici.', ['achetait', 'achete', 'achetera', 'achete']]], ['bescherelle_conjugation_reference']],
  ['boire', 'boire', [['present_je', 'je bois', 'Je ___ de l eau.', ['bois', 'boit', 'buvons', 'buvez']], ['present_nous', 'nous buvons', 'Nous ___ du the.', ['buvons', 'buvez', 'boivent', 'bois']], ['passe_compose_il', 'il a bu', 'Il ___ un cafe.', ['a bu', 'est bu', 'a boit', 'avait boit']], ['imparfait_vous', 'vous buviez', 'Vous ___ trop vite.', ['buviez', 'buvez', 'boirez', 'bu']]], ['bescherelle_conjugation_reference']],
  ['lire', 'lire', [['present_je', 'je lis', 'Je ___ ce message.', ['lis', 'lit', 'lisons', 'lisez']], ['present_nous', 'nous lisons', 'Nous ___ le journal.', ['lisons', 'lisez', 'lisent', 'lis']], ['passe_compose_il', 'il a lu', 'Il ___ le contrat.', ['a lu', 'est lu', 'a lit', 'avait lit']], ['imparfait_elle', 'elle lisait', 'Elle ___ beaucoup.', ['lisait', 'lit', 'lira', 'lu']]], ['bescherelle_conjugation_reference']],
  ['ecrire', 'ecrire', [['present_je', "j'ecris", "J'___ une lettre.", ['ecris', 'ecrit', 'ecrivons', 'ecrivez']], ['present_nous', 'nous ecrivons', 'Nous ___ souvent.', ['ecrivons', 'ecrivez', 'ecrivent', 'ecris']], ['passe_compose_il', 'il a ecrit', 'Il ___ un mail.', ['a ecrit', 'est ecrit', 'a ecris', 'avait ecris']], ['imparfait_tu', 'tu ecrivais', 'Tu ___ lentement.', ['ecrivais', 'ecris', 'ecriras', 'ecrit']]], ['bescherelle_conjugation_reference']],
  ['vivre', 'vivre', [['present_je', 'je vis', 'Je ___ a Lille.', ['vis', 'vit', 'vivons', 'vivez']], ['present_nous', 'nous vivons', 'Nous ___ ensemble.', ['vivons', 'vivez', 'vivent', 'vis']], ['passe_compose_il', 'il a vecu', 'Il ___ ici.', ['a vecu', 'est vecu', 'a vit', 'avait vit']], ['imparfait_elle', 'elle vivait', 'Elle ___ en Suisse.', ['vivait', 'vit', 'vivra', 'vecu']]], ['bescherelle_conjugation_reference']],
  ['connaitre', 'connaitre', [['present_je', 'je connais', 'Je ___ cette rue.', ['connais', 'connait', 'connaissons', 'connaissez']], ['present_nous', 'nous connaissons', 'Nous ___ la ville.', ['connaissons', 'connaissez', 'connaissent', 'connais']], ['passe_compose_il', 'il a connu', 'Il ___ Marie.', ['a connu', 'est connu', 'a connait', 'avait connait']], ['imparfait_vous', 'vous connaissiez', 'Vous ___ la regle.', ['connaissiez', 'connaissez', 'connaitrez', 'connu']]], ['bescherelle_conjugation_reference']],
  ['croire', 'croire', [['present_je', 'je crois', 'Je ___ ton histoire.', ['crois', 'croit', 'croyons', 'croyez']], ['present_nous', 'nous croyons', 'Nous ___ en lui.', ['croyons', 'croyez', 'croient', 'crois']], ['passe_compose_il', 'il a cru', 'Il ___ la nouvelle.', ['a cru', 'est cru', 'a croit', 'avait croit']], ['imparfait_elle', 'elle croyait', 'Elle ___ avoir raison.', ['croyait', 'croit', 'croira', 'cru']]], ['bescherelle_conjugation_reference']],
  ['recevoir', 'recevoir', [['present_je', 'je recois', 'Je ___ un message.', ['recois', 'recoit', 'recevons', 'recevez']], ['present_nous', 'nous recevons', 'Nous ___ des amis.', ['recevons', 'recevez', 'recoivent', 'recois']], ['passe_compose_il', 'il a recu', 'Il ___ une lettre.', ['a recu', 'est recu', 'a recoit', 'avait recoit']], ['imparfait_tu', 'tu recevais', 'Tu ___ des appels.', ['recevais', 'recois', 'recevras', 'recu']]], ['bescherelle_conjugation_reference']],
  ['tenir', 'tenir', [['present_je', 'je tiens', 'Je ___ la porte.', ['tiens', 'tient', 'tenons', 'tenez']], ['present_nous', 'nous tenons', 'Nous ___ parole.', ['tenons', 'tenez', 'tiennent', 'tiens']], ['passe_compose_il', 'il a tenu', 'Il ___ sa promesse.', ['a tenu', 'est tenu', 'a tient', 'avait tient']], ['imparfait_elle', 'elle tenait', 'Elle ___ le sac.', ['tenait', 'tient', 'tiendra', 'tenu']]], ['bescherelle_conjugation_reference']],
];

export function lessonIdForIndex(index) {
  return (index % 32) + 1;
}

const FRENCH_ORTHOGRAPHY_REPLACEMENTS = [
  [/\ba le\b/g, 'à le'],
  [/\ba la\b/g, 'à la'],
  [/\ba les\b/g, 'à les'],
  [/\bEtats-Unis\b/g, 'États-Unis'],
  [/\bmarche\b/g, 'marché'],
  [/\bcanape\b/g, 'canapé'],
  [/\bbibliotheque\b/g, 'bibliothèque'],
  [/\bcafe\b/g, 'café'],
  [/\bC est\b/g, "C'est"],
  [/\bdiner\b/g, 'dîner'],
  [/\bjusqu a\b/g, "jusqu'à"],
  [/\bpres de\b/g, 'près de'],
  [/\bmere\b/g, 'mère'],
  [/\bmedecin\b/g, 'médecin'],
  [/\breponse\b/g, 'réponse'],
  [/\bdeja\b/g, 'déjà'],
  [/\bverite\b/g, 'vérité'],
  [/\bmanteau\b/g, 'manteau'],
  [/\bprete?\b/g, (match) => (match === 'pret' ? 'prêt' : 'prête')],
  [/\betre\b/g, 'être'],
  [/\bete\b/g, 'été'],
  [/\betait\b/g, 'était'],
  [/\betes\b/g, 'êtes'],
  [/\ballait\b/g, 'allait'],
  [/\bfaisiez\b/g, 'faisiez'],
  [/\bdeviez\b/g, 'deviez'],
  [/\bpreferer\b/g, 'préférer'],
  [/\bprefere\b/g, 'préfère'],
  [/\bpreferes\b/g, 'préfères'],
  [/\bpreferons\b/g, 'préférons'],
  [/\bpreferez\b/g, 'préférez'],
  [/\bpreferent\b/g, 'préfèrent'],
  [/\bpreferais\b/g, 'préférais'],
  [/\bprefereras\b/g, 'préféreras'],
  [/\bachete\b/g, 'achète'],
  [/\bachetes\b/g, 'achètes'],
  [/\bachetent\b/g, 'achètent'],
  [/\becris\b/g, 'écris'],
  [/\becrit\b/g, 'écrit'],
  [/\becrivons\b/g, 'écrivons'],
  [/\becrivez\b/g, 'écrivez'],
  [/\becrivent\b/g, 'écrivent'],
  [/\becrivais\b/g, 'écrivais'],
  [/\becriras\b/g, 'écriras'],
  [/\bvecu\b/g, 'vécu'],
  [/\bconnaitre\b/g, 'connaître'],
  [/\bconnait\b/g, 'connaît'],
  [/\bconnaitrez\b/g, 'connaîtrez'],
  [/\brecois\b/g, 'reçois'],
  [/\brecoit\b/g, 'reçoit'],
  [/\brecoivent\b/g, 'reçoivent'],
  [/\brecu\b/g, 'reçu'],
  [/\bcommencons\b/g, 'commençons'],
  [/\bcommencait\b/g, 'commençait'],
  [/\bcommences\b/g, 'commences'],
  [/\bappeles\b/g, 'appelles'],
  [/\bappele\b/g, 'appelé'],
  [/\bmange\b/g, 'mange'],
  [/\bmangeons\b/g, 'mangeons'],
  [/\bmanges\b/g, 'manges'],
];

export function restoreFrenchOrthography(value) {
  if (typeof value !== 'string') return value;
  return FRENCH_ORTHOGRAPHY_REPLACEMENTS.reduce(
    (text, [pattern, replacement]) => text.replace(pattern, replacement),
    value,
  );
}
