import type { DayPack } from './gustav_echo_full_day_batch_common';
import { runFullDayBatch } from './gustav_echo_full_day_batch_common';

const DAY_PACKS: DayPack[] = [
  {
    dayIndex: 38,
    fields: [
      { fieldPath: 'topic', fieldKind: 'day_topic', frenchText: "Demander si c'est loin" },
      { fieldPath: 'outcome', fieldKind: 'day_outcome', frenchText: 'Tu peux demander si un lieu est loin et si on peut y aller à pied.' },
      { fieldPath: 'intro[0].title', fieldKind: 'intro_title', frenchText: 'Deux questions clés sur la distance' },
      { fieldPath: 'intro[0].body', fieldKind: 'intro_body', frenchText: 'Quand tu ne sais pas si un lieu est loin, utilise deux questions. La première : Is it far? La seconde : Can I walk there? Ces deux phrases t’aideront dans n’importe quelle ville.' },
      { fieldPath: 'intro[0].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: "Est-ce loin d'ici ?" },
      { fieldPath: 'intro[1].title', fieldKind: 'intro_title', frenchText: 'Le mot far : loin' },
      { fieldPath: 'intro[1].body', fieldKind: 'intro_body', frenchText: 'Far signifie « loin ». C’est facile à retenir : Is it far? Si tu veux préciser, ajoute from here : Is it far from here?' },
      { fieldPath: 'intro[1].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: "Est-ce loin d'ici ?" },
      { fieldPath: 'intro[2].title', fieldKind: 'intro_title', frenchText: 'Can I walk there? : peut-on y aller à pied ?' },
      { fieldPath: 'intro[2].body', fieldKind: 'intro_body', frenchText: 'Can I walk there? signifie littéralement : « puis-je y aller à pied ? ». Can indique une possibilité ou une permission. There signifie « là-bas ». C’est une question courte comprise partout.' },
      { fieldPath: 'intro[2].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Peut-on y aller à pied ?' },
      { fieldPath: 'phrases.echo_d38_p1.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Is it : une question sur un lieu' },
      { fieldPath: 'phrases.echo_d38_p1.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Is it + adjectif : on pose une question sur un lieu ou une chose.' },
      { fieldPath: 'phrases.echo_d38_p1.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Far décrit la distance jusqu’à un lieu. Is it far? est une question standard.' },
      { fieldPath: 'phrases.echo_d38_p1.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « It is far? » : dans une question, is vient en premier.' },
      { fieldPath: 'phrases.echo_d38_p2.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Can I : demander la possibilité' },
      { fieldPath: 'phrases.echo_d38_p2.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Can I + verbe sert à demander s’il est possible de faire quelque chose.' },
      { fieldPath: 'phrases.echo_d38_p2.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Walk there signifie « aller là-bas à pied ». Can I rend la question polie.' },
      { fieldPath: 'phrases.echo_d38_p2.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « Can I to walk » : après can, le verbe vient sans to.' },
      { fieldPath: 'phrases.echo_d38_p3.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander si un lieu est proche' },
      { fieldPath: 'phrases.echo_d38_p3.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Is + lieu + near + autre lieu sert à demander la proximité.' },
      { fieldPath: 'phrases.echo_d38_p3.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Near signifie « près ». C’est l’opposé de far, et les deux mots servent beaucoup en ville.' },
      { fieldPath: 'phrases.echo_d38_p3.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « Is the hotel near to » : near ne prend pas to.' },
      { fieldPath: 'phrases.echo_d38_p4.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander plus de détail sur la distance' },
      { fieldPath: 'phrases.echo_d38_p4.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'How far is + lieu sert à demander à quelle distance il se trouve.' },
      { fieldPath: 'phrases.echo_d38_p4.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'How far donne une réponse précise : cinq minutes, deux kilomètres. Is it far? appelle seulement oui ou non.' },
      { fieldPath: 'phrases.echo_d38_p4.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « How far is it the museum » : ici, it est en trop.' },
      { fieldPath: 'phrases.echo_d38_p5.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'About + temps + away : une distance approximative' },
      { fieldPath: 'phrases.echo_d38_p5.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'It is about + durée + away sert à dire une distance en temps.' },
      { fieldPath: 'phrases.echo_d38_p5.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Away indique la distance depuis ici. About signifie « environ ». Cette formule est utile pour répondre.' },
      { fieldPath: 'phrases.echo_d38_p5.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « It is ten minutes far » : dans ce cas, on dit away, pas far.' },
      { fieldPath: 'phrases.echo_d38_p6.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Can you show me...? : demande polie' },
      { fieldPath: 'phrases.echo_d38_p6.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Can you + verbe + me sert à demander à quelqu’un de faire quelque chose pour toi.' },
      { fieldPath: 'phrases.echo_d38_p6.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Show me the way signifie « montre-moi le chemin ». C’est une demande d’aide simple et polie.' },
      { fieldPath: 'phrases.echo_d38_p6.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « Can you to show » : après can, le verbe vient sans to.' },
      { fieldPath: 'vocabulary.far.translation', fieldKind: 'vocabulary_translation', frenchText: 'loin' },
      { fieldPath: 'vocabulary.near.translation', fieldKind: 'vocabulary_translation', frenchText: 'près, proche' },
      { fieldPath: 'vocabulary.walk.translation', fieldKind: 'vocabulary_translation', frenchText: 'marcher, aller à pied' },
      { fieldPath: 'vocabulary.away.translation', fieldKind: 'vocabulary_translation', frenchText: 'à distance, loin' },
      { fieldPath: 'vocabulary.museum.translation', fieldKind: 'vocabulary_translation', frenchText: 'musée' },
      { fieldPath: 'vocabulary.way.translation', fieldKind: 'vocabulary_translation', frenchText: 'chemin' },
    ],
  },
  {
    dayIndex: 39,
    fields: [
      { fieldPath: 'topic', fieldKind: 'day_topic', frenchText: 'Trouver le lieu dont tu as besoin' },
      { fieldPath: 'outcome', fieldKind: 'day_outcome', frenchText: 'Tu peux demander où se trouve le lieu que tu cherches et expliquer ce que tu dois trouver.' },
      { fieldPath: 'intro[0].title', fieldKind: 'intro_title', frenchText: 'Comment dire que tu cherches quelque chose' },
      { fieldPath: 'intro[0].body', fieldKind: 'intro_body', frenchText: 'Quand tu cherches un lieu en ville, dis : I am looking for... Cela signifie « je cherche ». Ensuite, nomme le lieu : the post office, the bank, the pharmacy. Simple et clair.' },
      { fieldPath: 'intro[0].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Je cherche la poste.' },
      { fieldPath: 'intro[1].title', fieldKind: 'intro_title', frenchText: 'Y a-t-il ici ce dont tu as besoin ?' },
      { fieldPath: 'intro[1].body', fieldKind: 'intro_body', frenchText: 'Pour demander s’il y a un lieu proche, utilise : Is there a ... near here? Cela signifie « y a-t-il ... près d’ici ? ». Très utile quand tu ne connais pas le chemin.' },
      { fieldPath: 'intro[1].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: "Y a-t-il une pharmacie près d'ici ?" },
      { fieldPath: 'intro[2].title', fieldKind: 'intro_title', frenchText: 'Demande de l’aide avec politesse' },
      { fieldPath: 'intro[2].body', fieldKind: 'intro_body', frenchText: 'Avant de poser une question, il est bon de dire : Excuse me. Cela signifie « excusez-moi ». Les gens aident plus volontiers quand tu commences poliment.' },
      { fieldPath: 'intro[2].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: 'Excusez-moi, je cherche la banque.' },
      { fieldPath: 'phrases.echo_d39_p1.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Parler de ce que tu fais maintenant' },
      { fieldPath: 'phrases.echo_d39_p1.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'am/is/are + verbe en -ing indique que l’action se passe maintenant.' },
      { fieldPath: 'phrases.echo_d39_p1.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Ainsi, tu montres que tu cherches maintenant, pas en général.' },
      { fieldPath: 'phrases.echo_d39_p1.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas I look for dans cette situation : cela ne sonne pas naturel en anglais.' },
      { fieldPath: 'phrases.echo_d39_p2.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander s’il y a quelque chose près d’ici' },
      { fieldPath: 'phrases.echo_d39_p2.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Is there a...? sert à demander si quelque chose existe à cet endroit.' },
      { fieldPath: 'phrases.echo_d39_p2.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'C’est la façon la plus simple de savoir s’il y a un lieu proche.' },
      { fieldPath: 'phrases.echo_d39_p2.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne change pas l’ordre : Is there, pas There is, quand c’est une question.' },
      { fieldPath: 'phrases.echo_d39_p3.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Mouvement en ce moment' },
      { fieldPath: 'phrases.echo_d39_p3.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Are walking signifie « nous marchons maintenant », une action en cours.' },
      { fieldPath: 'phrases.echo_d39_p3.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Tu parles d’un mouvement qui se passe maintenant, pas d’une habitude.' },
      { fieldPath: 'phrases.echo_d39_p3.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne confonds pas we walk, pour une habitude, et we are walking, pour maintenant.' },
      { fieldPath: 'phrases.echo_d39_p4.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Dire que quelque chose existe' },
      { fieldPath: 'phrases.echo_d39_p4.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'There is a... sert à indiquer que quelque chose existe à cet endroit.' },
      { fieldPath: 'phrases.echo_d39_p4.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'C’est une forme utile pour signaler quelque chose qui est proche.' },
      { fieldPath: 'phrases.echo_d39_p4.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « It is a bus stop here » : ce n’est pas naturel en anglais.' },
      { fieldPath: 'phrases.echo_d39_p5.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Quelqu’un demande maintenant' },
      { fieldPath: 'phrases.echo_d39_p5.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Is asking signifie qu’elle demande en ce moment précis, une action en cours.' },
      { fieldPath: 'phrases.echo_d39_p5.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Tu décris ce que tu vois maintenant, pas ses habitudes.' },
      { fieldPath: 'phrases.echo_d39_p5.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas she ask : il faut dire she asks ou she is asking.' },
      { fieldPath: 'phrases.echo_d39_p6.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander s’il y a plusieurs lieux' },
      { fieldPath: 'phrases.echo_d39_p6.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Are there any...? sert à demander s’il y a plusieurs choses.' },
      { fieldPath: 'phrases.echo_d39_p6.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Any s’utilise dans les questions et signifie « quelques-uns », sans préciser.' },
      { fieldPath: 'phrases.echo_d39_p6.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas Are there some shops : dans les questions, utilise any, pas some.' },
      { fieldPath: 'vocabulary.pharmacy.translation', fieldKind: 'vocabulary_translation', frenchText: 'pharmacie' },
      { fieldPath: 'vocabulary.hospital.translation', fieldKind: 'vocabulary_translation', frenchText: 'hôpital' },
      { fieldPath: 'vocabulary.bank.translation', fieldKind: 'vocabulary_translation', frenchText: 'banque' },
      { fieldPath: 'vocabulary.office.translation', fieldKind: 'vocabulary_translation', frenchText: 'bureau, office' },
      { fieldPath: 'vocabulary.shops.translation', fieldKind: 'vocabulary_translation', frenchText: 'magasins, boutiques' },
      { fieldPath: 'vocabulary.stop.translation', fieldKind: 'vocabulary_translation', frenchText: 'arrêt' },
    ],
  },
  {
    dayIndex: 40,
    fields: [
      { fieldPath: 'topic', fieldKind: 'day_topic', frenchText: 'Demander les horaires d’ouverture' },
      { fieldPath: 'outcome', fieldKind: 'day_outcome', frenchText: 'Tu peux demander quand une banque, un magasin ou une pharmacie ouvre et ferme.' },
      { fieldPath: 'intro[0].title', fieldKind: 'intro_title', frenchText: 'Tu es dans une ville inconnue' },
      { fieldPath: 'intro[0].body', fieldKind: 'intro_body', frenchText: 'Tu dois aller à la banque ou à la pharmacie, mais tu ne sais pas si elles sont ouvertes maintenant. Aujourd’hui, tu apprendras à poser une question simple, comprise partout.' },
      { fieldPath: 'intro[1].title', fieldKind: 'intro_title', frenchText: 'Comment former une question sur les horaires' },
      { fieldPath: 'intro[1].body', fieldKind: 'intro_body', frenchText: 'En anglais, les questions sur les horaires se forment ainsi : d’abord what time, puis does, puis qui ou quoi, et enfin l’action. Par exemple : What time does the bank close?' },
      { fieldPath: 'intro[1].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: 'À quelle heure la banque ferme-t-elle ?' },
      { fieldPath: 'intro[1].examples[1].gloss', fieldKind: 'intro_example_gloss', frenchText: 'À quelle heure la pharmacie ouvre-t-elle ?' },
      { fieldPath: 'intro[2].title', fieldKind: 'intro_title', frenchText: 'Le mot does est ton allié dans les questions' },
      { fieldPath: 'intro[2].body', fieldKind: 'intro_body', frenchText: 'Quand tu poses une question sur la banque, le magasin ou la pharmacie, donc sur un lieu ou une personne, tu as besoin de does. Le verbe qui suit reste toujours à sa forme simple : open, close, start.' },
      { fieldPath: 'intro[2].examples[0].gloss', fieldKind: 'intro_example_gloss', frenchText: 'À quelle heure le magasin ouvre-t-il aujourd’hui ?' },
      { fieldPath: 'phrases.echo_d40_p1.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander quand un lieu ferme' },
      { fieldPath: 'phrases.echo_d40_p1.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'What time + does + lieu + close? est la question standard sur l’heure de fermeture.' },
      { fieldPath: 'phrases.echo_d40_p1.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Does est nécessaire parce que la banque est un seul lieu.' },
      { fieldPath: 'phrases.echo_d40_p1.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « What time the bank closes » : tu as besoin de does au début de la question.' },
      { fieldPath: 'phrases.echo_d40_p2.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Savoir quand un lieu ouvre' },
      { fieldPath: 'phrases.echo_d40_p2.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'What time + does + lieu + open? sert à demander l’heure d’ouverture.' },
      { fieldPath: 'phrases.echo_d40_p2.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Open vient sans -s parce que does indique déjà qu’il s’agit d’un seul lieu.' },
      { fieldPath: 'phrases.echo_d40_p2.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas opens après does : utilise seulement la forme simple, open.' },
      { fieldPath: 'phrases.echo_d40_p3.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander si un lieu travaille un jour précis' },
      { fieldPath: 'phrases.echo_d40_p3.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Does + lieu + work + on + jour? sert à demander si un lieu fonctionne un jour précis.' },
      { fieldPath: 'phrases.echo_d40_p3.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Does au début transforme une affirmation normale en question.' },
      { fieldPath: 'phrases.echo_d40_p3.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « The store works on Sunday? » : does est obligatoire pour la question.' },
      { fieldPath: 'phrases.echo_d40_p4.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Dire quand un lieu ferme' },
      { fieldPath: 'phrases.echo_d40_p4.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Lieu + closes + at + heure sert à donner un horaire.' },
      { fieldPath: 'phrases.echo_d40_p4.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Closes prend -s parce qu’on parle d’une banque, un seul lieu.' },
      { fieldPath: 'phrases.echo_d40_p4.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas close sans -s : la banque est singulière, donc il faut -s.' },
      { fieldPath: 'phrases.echo_d40_p5.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Donner l’horaire habituel' },
      { fieldPath: 'phrases.echo_d40_p5.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'Lieu + opens + at + heure + every day sert à parler de quelque chose qui arrive toujours.' },
      { fieldPath: 'phrases.echo_d40_p5.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'Every day indique que c’est l’horaire habituel, pas une exception.' },
      { fieldPath: 'phrases.echo_d40_p5.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas open sans -s avec the office : il faut -s.' },
      { fieldPath: 'phrases.echo_d40_p6.explanation.title', fieldKind: 'phrase_explanation_title', frenchText: 'Demander l’horaire avec when' },
      { fieldPath: 'phrases.echo_d40_p6.explanation.rule', fieldKind: 'phrase_explanation_rule', frenchText: 'When + does + lieu + work? est une alternative à what time pour une question générale.' },
      { fieldPath: 'phrases.echo_d40_p6.explanation.why', fieldKind: 'phrase_explanation_why', frenchText: 'When sonne un peu plus large : tu demandes tout l’horaire, pas seulement une heure.' },
      { fieldPath: 'phrases.echo_d40_p6.explanation.commonMistake', fieldKind: 'phrase_explanation_common_mistake', frenchText: 'Ne dis pas « When the hotel reception works? » : il faut does après when.' },
      { fieldPath: 'vocabulary.bank.translation', fieldKind: 'vocabulary_translation', frenchText: 'banque' },
      { fieldPath: 'vocabulary.pharmacy.translation', fieldKind: 'vocabulary_translation', frenchText: 'pharmacie' },
      { fieldPath: 'vocabulary.store.translation', fieldKind: 'vocabulary_translation', frenchText: 'magasin' },
      { fieldPath: 'vocabulary.office.translation', fieldKind: 'vocabulary_translation', frenchText: 'bureau' },
      { fieldPath: 'vocabulary.hotel.translation', fieldKind: 'vocabulary_translation', frenchText: 'hôtel' },
      { fieldPath: 'vocabulary.closes.translation', fieldKind: 'vocabulary_translation', frenchText: 'ferme' },
    ],
  },
];

runFullDayBatch({
  dayPacks: DAY_PACKS,
  generatedBy: 'gustav_personal_plan_echo_days038_040_french_full_day_text_packets',
  scriptUsage: 'Usage: npx tsx scripts/gustav_personal_plan_echo_days038_040_french_full_day_text_packets.ts --run <run-dir>',
  batchTitle: 'GUSTAV Echo days 038-040 French full-day text packets',
  batchSchemaVersion: 'gustav-personal-plan-echo-days038-040-french-full-day-text-packets-v0',
  batchAuditBaseName: 'personal_plan_echo_days038_040_french_full_day_text_packets',
}).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
