import type { VictoriaRow } from '../victoriaBundleShared';

export const PREP_BY_CARDS: VictoriaRow[] = [
  {
    id: 'official_prep_by_en_01',
    en: 'by car',
    ru: 'на машине',
    uk: 'на машині',
    es: 'en coche',
    explanationRu: 'BY + транспорт = способ, всегда без артикля. Как только появляется артикль или притяжательное — нужен IN/ON: I came by car (способ) — I came in my car (конкретная машина) — I came on the 5 o\'clock train (конкретный поезд).',
    explanationUk: 'BY + транспорт = спосіб, завжди без артикля. Як тільки з\'являється артикль або присвійне — потрібен IN/ON: I came by car (спосіб) — I came in my car (конкретна машина) — I came on the 5 o\'clock train (конкретний потяг).',
    explanationEs: 'BY + transporte = modo, siempre sin artículo. En cuanto aparece un artículo o posesivo, se usa IN/ON: I came by car (modo) — I came in my car (ese coche concreto) — I came on the 5 o\'clock train (ese tren concreto).',
  },
  {
    id: 'official_prep_by_en_02',
    en: 'by plane',
    ru: 'на самолёте',
    uk: 'на літаку',
    es: 'en avión',
    explanationRu: 'BY = способ перелёта. ON/IN = где ты находился. Три вопроса — три предлога: I came by plane (как?) — I slept on the plane (где?) — I was nervous in the small plane (внутри маленькой кабины).',
    explanationUk: 'BY = спосіб перельоту. ON/IN = де ти перебував. Три питання — три прийменники: I came by plane (як?) — I slept on the plane (де?) — I was nervous in the small plane (всередині маленької кабіни).',
    explanationEs: 'BY = modo de vuelo. ON/IN = dónde estabas. Tres preguntas — tres preposiciones: I came by plane (¿cómo?) — I slept on the plane (¿dónde?) — I was nervous in the small plane (dentro de la pequeña cabina).',
  },
  {
    id: 'official_prep_by_en_03',
    en: 'by sea',
    ru: 'морем',
    uk: 'морем',
    es: 'por mar',
    explanationRu: 'Sea/land/air — среда как маршрут. BY = через эту среду как способ. Сравни: They travelled by sea (среда-способ) — A boat on the sea (поверхность моря) — A bird in the air (внутри воздушного пространства).',
    explanationUk: 'Sea/land/air — середовище як маршрут. BY = через це середовище як спосіб. Порівняй: They travelled by sea (середовище-спосіб) — A boat on the sea (поверхня моря) — A bird in the air (всередині повітряного простору).',
    explanationEs: 'Sea/land/air = entorno como ruta. BY = a través de ese entorno como modo. Compara: They travelled by sea (entorno-modo) — A boat on the sea (superficie del mar) — A bird in the air (dentro del espacio aéreo).',
  },
  {
    id: 'official_prep_by_en_04',
    en: 'by chance',
    ru: 'случайно / по воле случая',
    uk: 'випадково',
    es: 'por casualidad',
    explanationRu: 'Chance — механизм без плана. BY = через этот механизм, а не через намерение. Часто нейтрально или позитивно: случайная встреча, открытие. Сравни: by chance (без плана) — by accident (нечаянно) — on purpose (специально).',
    explanationUk: 'Chance — механізм без плану. BY = через цей механізм, а не через намір. Часто нейтрально або позитивно: випадкова зустріч, відкриття. Порівняй: by chance (без плану) — by accident (ненавмисно) — on purpose (спеціально).',
    explanationEs: 'Chance = mecanismo sin plan. BY = a través de ese mecanismo, no de una intención. A menudo neutro o positivo: encuentro casual, descubrimiento. Compara: by chance (sin plan) — by accident (sin querer) — on purpose (a propósito).',
  },
  {
    id: 'official_prep_by_en_05',
    en: 'by accident',
    ru: 'нечаянно / не специально',
    uk: 'ненавмисно / випадково',
    es: 'por accidente',
    explanationRu: 'Тонкая разница: by accident = не хотел этого результата. By mistake = перепутал / выбрал не то. Сравни: I broke it by accident (не хотел ломать) — I took your bag by mistake (думал, что моя). By chance — нейтрально, by accident — часто с досадой.',
    explanationUk: 'Тонка різниця: by accident = не хотів цього результату. By mistake = переплутав / вибрав не те. Порівняй: I broke it by accident (не хотів зламати) — I took your bag by mistake (думав, що моя). By chance — нейтрально, by accident — часто з прикрістю.',
    explanationEs: 'Diferencia sutil: by accident = no quería ese resultado. By mistake = me confundí / elegí mal. Compara: I broke it by accident (no quería romperlo) — I took your bag by mistake (creí que era la mía). By chance — neutro; by accident — a menudo con contrariedad.',
  },
  {
    id: 'official_prep_by_en_06',
    en: 'by mistake',
    ru: 'по ошибке',
    uk: 'помилково',
    es: 'por error',
    explanationRu: 'Mistake = ошибочный выбор или понимание. BY = через этот механизм. Русское "случайно" может быть и by accident, и by mistake — смотри смысл: "не хотел" → by accident, "перепутал" → by mistake.',
    explanationUk: 'Mistake = помилковий вибір або розуміння. BY = через цей механізм. Українське "випадково" може бути і by accident, і by mistake — дивись зміст: "не хотів" → by accident, "переплутав" → by mistake.',
    explanationEs: 'Mistake = elección o comprensión equivocada. BY = a través de ese mecanismo. El español "sin querer" puede ser by accident o by mistake según el sentido: "no lo quería" → by accident; "me confundí" → by mistake.',
  },
  {
    id: 'official_prep_by_en_07',
    en: 'by heart',
    ru: 'наизусть',
    uk: 'напам\'ять',
    es: 'de memoria',
    explanationRu: 'Идиома: BY heart = из памяти, без подсказки. Работает почти всегда с know, learn, remember, recite. Сравни: He knows the song by heart (наизусть) — He read it from his phone (с телефона).',
    explanationUk: 'Ідіома: BY heart = з пам\'яті, без підказки. Працює майже завжди з know, learn, remember, recite. Порівняй: He knows the song by heart (напам\'ять) — He read it from his phone (з телефону).',
    explanationEs: 'Expresión fija: BY heart = de memoria, sin ayuda. Funciona casi siempre con know, learn, remember, recite. Compara: He knows the song by heart (de memoria) — He read it from his phone (desde el teléfono).',
  },
  {
    id: 'official_prep_by_en_08',
    en: 'by hand',
    ru: 'вручную',
    uk: 'вручну',
    es: 'a mano',
    explanationRu: 'BY = способ выполнения. WITH = конкретный инструмент. Сравни: I wrote it by hand (способ: вручную) — I wrote it with a pen (инструмент: ручка). Cambridge: BY = действие/способ, WITH = предмет-инструмент.',
    explanationUk: 'BY = спосіб виконання. WITH = конкретний інструмент. Порівняй: I wrote it by hand (спосіб: вручну) — I wrote it with a pen (інструмент: ручка). Cambridge: BY = дія/спосіб, WITH = предмет-інструмент.',
    explanationEs: 'BY = modo de ejecución. WITH = instrumento concreto. Compara: I wrote it by hand (modo: a mano) — I wrote it with a pen (instrumento: bolígrafo). Cambridge: BY = acción/modo, WITH = objeto-instrumento.',
  },
  {
    id: 'official_prep_by_en_09',
    en: 'by appointment',
    ru: 'по предварительной записи',
    uk: 'за попереднім записом',
    es: 'con cita previa',
    explanationRu: 'Appointment = условие доступа. BY = через этот механизм. Три конструкции: by appointment (через запись как условие) — make an appointment (записаться) — at the appointment (на самом приёме).',
    explanationUk: 'Appointment = умова доступу. BY = через цей механізм. Три конструкції: by appointment (через запис як умову) — make an appointment (записатися) — at the appointment (на самому прийомі).',
    explanationEs: 'Appointment = condición de acceso. BY = a través de ese mecanismo. Tres construcciones: by appointment (mediante cita como condición) — make an appointment (pedir cita) — at the appointment (en la cita misma).',
  },
  {
    id: 'official_prep_by_en_10',
    en: 'by birth',
    ru: 'по рождению / от рождения',
    uk: 'від народження',
    es: 'de nacimiento',
    explanationRu: 'Birth = источник статуса/качества. BY = рождение как механизм получения. Часто с национальностью/гражданством: She is British by birth. Ряд: by birth (рождение) — by choice (выбор) — by law (закон) — by nature (природа).',
    explanationUk: 'Birth = джерело статусу/якості. BY = народження як механізм отримання. Часто з національністю/громадянством: She is British by birth. Ряд: by birth (народження) — by choice (вибір) — by law (закон) — by nature (природа).',
    explanationEs: 'Birth = origen del estatus/cualidad. BY = el nacimiento como mecanismo de adquisición. Con frecuencia con nacionalidad/ciudadanía: She is British by birth. Serie: by birth (nacimiento) — by choice (elección) — by law (ley) — by nature (naturaleza).',
  },
  {
    id: 'official_prep_by_en_11',
    en: 'by law',
    ru: 'по закону / согласно закону',
    uk: 'за законом',
    es: 'por ley',
    explanationRu: 'Law = источник обязательства. BY = закон как механизм, который требует/запрещает. Сравни: required by law (закон требует) — against the law (нарушение) — under the law (в рамках правовой системы) — according to the law (формально).',
    explanationUk: 'Law = джерело зобов\'язання. BY = закон як механізм, що вимагає/забороняє. Порівняй: required by law (закон вимагає) — against the law (порушення) — under the law (у рамках правової системи) — according to the law (формально).',
    explanationEs: 'Law = fuente de la obligación. BY = la ley como mecanismo que exige/prohíbe. Compara: required by law (la ley lo exige) — against the law (infracción) — under the law (en el marco del sistema legal) — according to the law (formalmente).',
  },
  {
    id: 'official_prep_by_en_12',
    en: 'by far',
    ru: 'намного / с большим отрывом',
    uk: 'набагато / з великим відривом',
    es: 'con creces',
    explanationRu: 'Идиома-усилитель. BY far + превосходная степень = с большим отрывом. Три похожих выражения: by far the best (безусловно лучший) — far from the best (далеко не лучший) — so far (пока что).',
    explanationUk: 'Ідіома-підсилювач. BY far + найвищий ступінь = з великим відривом. Три схожих вирази: by far the best (безумовно найкращий) — far from the best (далеко не найкращий) — so far (поки що).',
    explanationEs: 'Expresión intensificadora. BY far + superlativo = con gran diferencia. Tres expresiones similares: by far the best (sin duda el mejor) — far from the best (lejos de ser el mejor) — so far (hasta ahora).',
  },
  {
    id: 'official_prep_by_en_13',
    en: 'by nature',
    ru: 'по природе / по натуре',
    uk: 'за природою / за натурою',
    es: 'por naturaleza',
    explanationRu: 'Nature = источник врождённой черты. BY = природа как механизм. Сравни: He is quiet by nature (врождённое) — in nature (в дикой природе как среде) — by habit (по привычке, приобретённое).',
    explanationUk: 'Nature = джерело вродженої риси. BY = природа як механізм. Порівняй: He is quiet by nature (вроджене) — in nature (у дикій природі як середовищі) — by habit (за звичкою, набуте).',
    explanationEs: 'Nature = origen del rasgo innato. BY = la naturaleza como mecanismo. Compara: He is quiet by nature (innato) — in nature (en la naturaleza como entorno) — by habit (por costumbre, adquirido).',
  },
  {
    id: 'official_prep_by_en_14',
    en: 'by means of',
    ru: 'посредством / с помощью',
    uk: 'за допомогою / шляхом',
    es: 'por medio de',
    explanationRu: 'Формальный вариант "с помощью". BY means of = через использование средства. В разговорной речи лучше using или with. Сравни: by means of a key (формально) — with a key (нейтрально) — using a key (нейтрально).',
    explanationUk: 'Формальний варіант "за допомогою". BY means of = через використання засобу. У розмовній мові краще using або with. Порівняй: by means of a key (формально) — with a key (нейтрально) — using a key (нейтрально).',
    explanationEs: 'Versión formal de "con la ayuda de". BY means of = a través del uso de un medio. En el habla cotidiana es mejor using o with. Compara: by means of a key (formal) — with a key (neutro) — using a key (neutro).',
  },
  {
    id: 'official_prep_by_en_15',
    en: 'by no means',
    ru: 'ни в коем случае / отнюдь нет',
    uk: 'жодним чином / аж ніяк',
    es: 'de ninguna manera',
    explanationRu: 'Идиома: никаким способом нельзя так сказать = категорическое отрицание. Важная пара противоположностей: by no means (вовсе нет) — by all means (конечно, разрешаю). Сравни: This is by no means perfect — Can I ask? — By all means.',
    explanationUk: 'Ідіома: жодним способом не можна так сказати = категоричне заперечення. Важна пара протилежностей: by no means (зовсім ні) — by all means (звісно, дозволяю). Порівняй: This is by no means perfect — Can I ask? — By all means.',
    explanationEs: 'Expresión fija: de ningún modo se puede decir eso = negación categórica. Par de opuestos importante: by no means (en absoluto) — by all means (por supuesto, lo permito). Compara: This is by no means perfect — Can I ask? — By all means.',
  },
];

/* expo-router route shim: keeps utility module from warning when discovered as route */
export default function __RouteShim() { return null; }
